### ISSUE TITLE
Spatial Data Support

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#4407]
Just curious if EF 7 supports spatial data types like geography yet. If so, what packages do we import to get reference to the types? I tried looking through the code on github and docs but nothing popped out at me.

Any help appreciated!

Thanks!

**Comment by ste4net** [comment]
Hello,
It is not supported. For now (it will be after 7.0.0 release)
Check this:
https://github.com/aspnet/EntityFramework/issues/1100
https://github.com/aspnet/EntityFramework/issues/242

**Comment by chassq** [comment]
Ok, fair enough. We can just switch over to tracking Lat/Long for our purposes for now. Thanks for the quick reply!
