### ISSUE TITLE
Migrations are not working on latest MyGet feed

### ISSUE THREAD

**Issue by damienbod** [dotnet/efcore#4414]
The following service registers are missing in the latest core version from MyGet

   IMigrator
        and all its child interfaces
Any ideas what's missing?

Greetings Damien

**Comment by bricelam** [comment]
I am not able to repro this. Could you share more information about your project/workflow?

**Comment by damienbod** [comment]
Hi @bricelam 
Found the missing services, need to add AddSqlite extension method from SqliteEntityFrameworkServicesBuilderExtensions.  Migrations still don't work

´´´
services.AddEntityFramework().AddSqlite()
              .AddDbContext<LocalizationModelSqliteContext>(options =>
                  options.UseSqlite(sqlConnectionString));
´´´

'Microsoft.EntityFrameworkCore.Commands' does not contain a 'Program' type suitable for an entry point

´´´
 // Entry point for the application.
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseDefaultConfiguration(args)
                .UseIISPlatformHandlerUrl()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
´´´

Greetings Damien

**Comment by bricelam** [comment]
Ah yes, the DNX commands are gone. We're transitioning to [.NET Core CLI](https://github.com/dotnet/cli). See #3925

**Comment by bricelam** [comment]
I recommend using the RC1 release during the transition.

**Comment by damienbod** [comment]
OK, thanks, I'll see if I can build the .NET Core CLI

Should I close this then?

Greetings Damien

**Comment by bricelam** [comment]
To clarify, they don't exist for CLI yet either (see PR #4381) :smile:

**Comment by damienbod** [comment]
:smile:
OK

Thanks

**Comment by rowanmiller** [comment]
Closing this out as our nightly builds are not in a state that can be used by external folks due to the transition to .NET CLI. We'll adjust Wiki to reflect this.
