### ISSUE TITLE
EF7 not supporting Oracle

### ISSUE THREAD

**Issue by sgadoury** [dotnet/efcore#4419]
I would like to use ASP.Net 5 MVC 6 App with EF7 and the Asp.Net Identity is using EF7, which is right for me.  However, my destination database is an Oracle DB and I can't change it.  So, I read many hours about this point and it seems there is no connector to use EF7 with Oracle.  Is it plan for soon?

I saw some workaround on the web, but it is not usable, because my EF is an IdentityDbContext, not a DbContext.  All seems to be link and if I try to change something like go backward with EF6, Identity system is no more working.

Thank you for your help

**Comment by smitpatel** [comment]
See #4293

**Comment by sgadoury** [comment]
Thank you for your quick answer.  If I understand correctly, I need to wait that oracle develop the connector for EF7?  Just in case, do you know where are issues on Asp.Net Identity?  I will like to search if there is an easy way to downgrade to Asp.Net Identity 2 instead of 3.

Thank you very much for your help
.

**Comment by smitpatel** [comment]
Identity repo : https://github.com/aspnet/Identity

**Comment by sgadoury** [comment]
Thank you.  I close this issue because there is another one covering this point.

**Comment by sgadoury** [comment]
Issue #4293 is talking about this behavior.
