### ISSUE TITLE
Update entity retrieved using Include

### ISSUE THREAD

**Issue by ac-esousa** [dotnet/efcore#4428]
Hello,

I am having an issue with EF7 rc1:

First, I retrieve an entity using .Include, like this

```
var entity = await context.EntitiyA
    .Where(a => a.Id == id)
    .Include(a => a.EntityB)
    .FirstOrDefaultAsync();
```

Then I change properties in `entity`, do do:

```
context.EntityA.Update(entity);
await context.SaveChangesAsync();
```

At this point, I get an exception, because EF is trying to insert a new record for `EntityB` table, with `entity.EntityB` data. (in my case, because PK value was provided for identity column).

**Comment by rowanmiller** [comment]
@ac-esousa can you include a full code listing that we can use to reproduce the issue (including you entity classes etc.)

**Comment by rowanmiller** [comment]
Closing as we have not heard back with details
