### ISSUE TITLE
Database.ExecuteSqlCommand returns void?

### ISSUE THREAD

**Issue by giancarloa** [dotnet/efcore#4430]
Hi... in EF6 Database.ExecuteSqlCommand had a int return type that represented the number of records affected... now in EF7 however it returns void... is that they way it should be???? is there another way in EF7 to execute a command and get the number of records affected???? I am trying to avoid raw ado.net code... thanks

**Comment by rowanmiller** [comment]
Already fixed in our current code base :smile: https://github.com/aspnet/EntityFramework/blob/2bc7eaa29cc57f7d550ab4eeba24b07c940595a2/src/Microsoft.EntityFrameworkCore.Relational/RelationalDatabaseFacadeExtensions.cs#L41

**Comment by giancarloa** [comment]
thanks @rowanmiller ....
