### ISSUE TITLE
DbModelBuilder Types method

### ISSUE THREAD

**Issue by giancarloa** [dotnet/efcore#4432]
Hi... in EF6 I had the code below that would apply generic configuration to all entities in the model using the Types().Configure method... I am trying to port to EF7 and am struggling trying to convert this code... I see that we no longer have DbModelBuilder and instead have ModelBuilder... that's cool... but I can't find the Types method... is there anything equivalent in EF7???? I basically want to loop through all the types in the model, check if they derive from a certain base class, and if so ignore a prop on the base class... down below DerivesFrom is a custom extension method and EntityBase is custom base class... any ideas??? Thank you

 protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

```
        modelBuilder.Types().Configure(entity =>
        {
            var isEntity = entity.ClrType.DerivesFrom(typeof(EntityBase<>));
            if (isEntity)
            {
                entity.Ignore("EntityState");
            }
        });
    }
```

**Comment by smitpatel** [comment]
`modelBuilder.Model.GetEntityTypes()` returns all entity types in the current model.
Following code snippet should give be equivalent of above code in EF6.
````c#
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    if (typeof (EntityBase<>).IsAssignableFrom(entityType.ClrType))
    {
        modelBuilder.Entity(entityType.ClrType).Ignore("EntityState");
    }
}
````

**Comment by giancarloa** [comment]
wow thanks @smitpatel... i will try it out...
