### ISSUE TITLE
QueryableExtensions Include with a string path

### ISSUE THREAD

**Issue by giancarloa** [dotnet/efcore#4435]
Hello... in EF6 the QueryableExtensions class had an Include method that accepted a string path... down below is the signature of that method... I am trying to port over to EF7 and don't see this method although I do see one that takes an Expression... any ideas on whether EF7 will support string include paths???? I saw this issue: https://github.com/aspnet/EntityFramework/issues/1151... but I don't think this is the same thing I am asking for... any ideas on how to make string include paths work in EF7???? thanks

IQueryable<T> Include<T, TProperty>(this IQueryable<T> source, Expression<Func<T, TProperty>> path)

**Comment by divega** [comment]
String based `Include()` is in our backlog at #3921. Currently we don't have plans to have it in the first release.

**Comment by giancarloa** [comment]
oh no... oh well... thanks @divega...
