### ISSUE TITLE
Follow structured logging format

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/efcore#4438]
Instead of calling `string.Format` yourself `logger.Log*(message, args)` should be called.

For example see https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/Internal/ModelValidator.cs#L46-L61

@lodejard

**Comment by smitpatel** [comment]
Logging in metadata is not implemented fully yet. We'll take care of this when we include logging.
The present issue arises because we have `{}` brace in formatted message which are being interpreted as string format (but they are just plain braces). Just putting escape sequence for now.

**Comment by BrennanConroy** [comment]
That issue has been fixed, see https://github.com/aspnet/Logging/pull/354

**Comment by smitpatel** [comment]
Looks like then no fix needed for EF :smile:

**Comment by BrennanConroy** [comment]
Why did this get closed?

**Comment by rowanmiller** [comment]
Does it add any value to have logging do the formatting for us?

**Comment by BrennanConroy** [comment]
Yes
cc @lodejard
