### ISSUE TITLE
[Conventions] Finding matching foreign key property should use null-ability

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#4440]
Future improvement to #4313 
Presently, when `ForeignKeyPropertyDiscoveryConvention` look for matching property, it ignores null-ability of property & required-ness of FK. Aligning both can be helpful in removing ambiguity in some scenarios. Non-required FK should look for null-able properties only.

**Comment by rowanmiller** [comment]
@smitpatel can you share an example of where this would help

**Comment by rowanmiller** [comment]
@smitpatel ping :smile:

**Comment by smitpatel** [comment]
````c#
public class Blog {
	public int Id {get; set;}
	public int? PostId {get; set;}
	public Post Post {get; set;}
}

public class Post {
	public int Id {get; set;}
	public int BlogId {get; set;}
	public Blog Blog {get; set;}
}

modelBuilder.Entity<Blog>().HasOne(e => e.Post).WithOne(e => e.Blog).IsRequired(true);
````
Considering required is true, a non-nullable property is more suitable choice. Even in case of multiple matching properties in same side, this can be done. It may be a rare case to have multiple matching properties. At present we just ignore null-ability fully while finding property.

**Comment by rowanmiller** [comment]
**Triage:** Discussed and decided this is starting to make the rules pretty complex, so we should just stick with what we have.
