### ISSUE TITLE
VisualStudio.Shell.Package type ambiguous -win10 build 14251.rs1 issue 

### ISSUE THREAD

**Issue by MarcAir** [dotnet/efcore#4443]
last couple of windows 10 pro insider preview have not allowed fro EF to unique call 
`Type name 'Microsoft.VisualStudio.Shell.Package'`

 [we have been directed by support to post here](https://social.msdn.microsoft.com/Forums/en-US/b0c771a5-7a52-4eb4-907e-0fd9f2ff063a/type-name-nugetvisualstudioivspackageinstallerservices-is-ambiguous?forum=adodotnetentityframework&prof=required)

as well posted in Windows Insider Feedback tool
[Windows Feedback tool](Windows-Feedback:?contextid=532&feedbackid=06e38a2b-af91-4c20-8196-98bb030f2483&form=1&src=2)
`Windows-Feedback:?contextid=532&feedbackid=06e38a2b-af91-4c20-8196-98bb030f2483&form=1&src=2`
## current setup

`Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA408
Microsoft Architecture and Modeling Tools

UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA408
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA408
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA408
Microsoft Visual C++ 2015

Visual F# 2015   00322-80000-00000-AA408
Microsoft Visual F# 2015

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.11120.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.7.1   14.0.11112.0
Azure App Service Tools v2.7.1

Bundler & Minifier   1.7.141
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Package Installer   1.5.69
Makes it easier, faster and more convenient than ever to install Bower, npm, JSPM, TSD and NuGet packages to any project

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.31105.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31105.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.31105.00
Profiling support for Python projects.

Sassy Studio   0.2.0.0
Provides some support for sass / scss in visual studio

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TypeScript   1.7.4.0
TypeScript for Microsoft Visual Studio

Web Compiler   1.10.300
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015   1.0.203
Adds many useful features to Visual Studio for web developers.

Xamarin   4.0.0.1717 (1390b70)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.0.35 (d300845)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.3.99.33 (ea30b32)
Visual Studio extension to enable development for Xamarin.iOS.

Xoreax IncrediBuild   7.1 (build 1659)
Xoreax IncrediBuild 7.1 (build 1659)`
# Error Message Details

`PM> update-database
Type name 'Microsoft.VisualStudio.Shell.Package' is ambiguous, it could be 'Microsoft.VisualStudio.Shell.Package, Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or 'Microsoft.VisualStudio.Shell.Package, Microsoft.VisualStudio.Shell.10.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
At C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\45WR4LC4.0MH\Modules\NuGet\profile.ps1:126 char:5
-     $service = [Microsoft.VisualStudio.Shell.Package]::GetGlobalServi ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [], RuntimeException
  - FullyQualifiedErrorId : AmbiguousTypeReference

Type name 'NuGet.VisualStudio.IVsPackageInstallerServices' is ambiguous, it could be 'NuGet.VisualStudio.IVsPackageInstallerServices, Microsoft.VisualStudio.ApplicationInsights, Version=4.1.60107.3, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or 'NuGet.VisualStudio.IVsPackageInstallerServices, Microsoft.Pex.VisualStudio, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
At C:\Users<removed>\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1004 char:5
-     $packageInstallerServices = $componentModel.GetService([NuGet.Vis ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [], RuntimeException
  - FullyQualifiedErrorId : AmbiguousTypeReference

You cannot call a method on a null-valued expression.
At C:\Users<removed>\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1006 char:5
-     $vsPackage = $packageInstallerServices.GetInstalledPackages() | ? ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users<removed>\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:713 char:28
-     $toolsPath = Join-Path $installPath tools
-                            ~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users<removed>\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:74
- ...  [System.Reflection.Assembly]::LoadFrom((Join-Path $ToolsPath EntityF ...
-                                                        ~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

You cannot call a method on a null-valued expression.
At C:\Users\mpozz\Source\Workspaces\AlphaOne2\ENCOM\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
-     $dispatcher = $utilityAssembly.CreateInstance(
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users<removed>\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:810 char:20
-         (Join-Path $runner.ToolsPath EntityFramework.PowerShell.dll),
-                    ~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPath

**Comment by MarcusPozzan** [comment]
adding related issue: [codeplex](https://entityframework.codeplex.com/workitem/2872)

**Comment by rowanmiller** [comment]
Closing this one out as this is the EF Core project. EF6.x is tracked on CodePlex so we're using [CodePlex #2872](https://entityframework.codeplex.com/workitem/2872) to track the issue. We are actively working on this at the moment.
