### ISSUE TITLE
How to add foreign key manually in migration Up()?

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4444]
I am trying to create a foreign key and struggling:

``` c#
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // author
            migrationBuilder.CreateTable("Author", c => new
            {
                Id = c.Column<int>(),
                Name = c.Column<string>()
            },
            constraints: c =>
            {
                c.PrimaryKey("PK_Author", x => x.Id);
            });

            // book
            migrationBuilder.CreateTable("Book", c => new
            {
                Id = c.Column<int>(),
                Name = c.Column<string>(),
                AuthorId = c.Column<int>()
            },
            constraints: c =>
            {
                c.PrimaryKey("PK_Book", x => x.Id);
                c.ForeignKey("FK_Book_Author_AuthorId", x => x.AuthorId, "Author", "AuthorId", onDelete: ReferentialAction.Cascade);
            });
        }
```

After creating some books and calling db.SaveChanges(); I get :
**{"SQLite Error 1: 'foreign key mismatch - \"Book\" referencing \"Author\"'"}**

This error only appears when I try to add the foreign key like above, otherwise it does not occur. I am taking the approach of manually creating migration files, it has been easy so far, please let me know why this error is occurring?

**Comment by Muchiachio** [comment]
I believe your principal column shouldn't be `AuthorId`, but instead `Id`. Because now you are creating FK to `Author.AuthorId` column, which doesn't exist.

**Comment by salafsoft** [comment]
@Muchiachio you were right. Many thanks!
