### ISSUE TITLE
Add an index convention

### ISSUE THREAD

**Issue by BradBarnich** [dotnet/efcore#4445]
Add an index convention, such as IIndexConvention, to allow customizing indexes on add (and possibly remove).

The specific case is I want to customize the name of the index, to line up with an existing naming convention. I am using IPropertyConvention and IForeignKeyConvention to similarly name columns and FK constraints.

**Comment by rowanmiller** [comment]
Here is some code you can put in `OnModelCreating` to rename all your indexes:

```c#
foreach (var type in modelBuilder.Model.GetEntityTypes())
{
    foreach (var index in type.GetIndexes())
    {
        index.Relational().Name = 
            type.ClrType.Name 
            + "_" 
            + string.Join("_", index.Properties.Select(p => p.Name));
    }
}
```

You probably want to put it at the end so that it applies to indexes that you create in `OnModelCreating` too (only the ones introduced by conventions exist at the start of  `OnModelCreating`).

**Comment by rowanmiller** [comment]
Closing as we also have https://github.com/aspnet/EntityFramework/issues/214 tracking a purpose built API to write your own conventions.

**Comment by AuthorProxy** [comment]
Current code convert `tables`, `properties`, `keys` and `indexes` to snake case for `Postgre`, you can use it as a base for your custom conventions:


    using System;
    using System.Text.RegularExpressions;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata;
    using Npgsql;
    
    namespace Database.Customization
    {
        public class PostgreDbContext : DbContext
        {
            private static readonly Regex _keysRegex = new Regex("^(PK|FK|IX)_", RegexOptions.Compiled);
    
            public PostgreDbContext(DbContextOptions options)
                : base(options)
            {
            }
    
            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);
                FixSnakeCaseNames(modelBuilder);
            }
    
            private void FixSnakeCaseNames(ModelBuilder modelBuilder)
            {
                var mapper = new NpgsqlSnakeCaseNameTranslator();
                foreach (var table in modelBuilder.Model.GetEntityTypes())
                {
                    ConvertToSnake(mapper, table);
                    foreach (var property in table.GetProperties())
                    {
                        ConvertToSnake(mapper, property);
                    }
    
                    foreach (var primaryKey in table.GetKeys())
                    {
                        ConvertToSnake(mapper, primaryKey);
                    }
    
                    foreach (var foreignKey in table.GetForeignKeys())
                    {
                        ConvertToSnake(mapper, foreignKey);
                    }
    
                    foreach (var indexKey in table.GetIndexes())
                    {
                        ConvertToSnake(mapper, indexKey);
                    }
                }
            }
    
            private void ConvertToSnake(INpgsqlNameTranslator mapper, object entity)
            {
                switch (entity)
                {
                    case IMutableEntityType table:
                        var relationalTable = table.Relational();
                        relationalTable.TableName = ConvertGeneralToSnake(mapper, relationalTable.TableName);
                        if (relationalTable.TableName.StartsWith("asp_net_"))
                        {
                            relationalTable.TableName = relationalTable.TableName.Replace("asp_net_", string.Empty);
                            relationalTable.Schema = "identity";
                        }
    
                        break;
                    case IMutableProperty property:
                        property.Relational().ColumnName = ConvertGeneralToSnake(mapper, property.Relational().ColumnName);
                        break;
                    case IMutableKey primaryKey:
                        primaryKey.Relational().Name = ConvertKeyToSnake(mapper, primaryKey.Relational().Name);
                        break;
                    case IMutableForeignKey foreignKey:
                        foreignKey.Relational().Name = ConvertKeyToSnake(mapper, foreignKey.Relational().Name);
                        break;
                    case IMutableIndex indexKey:
                        indexKey.Relational().Name = ConvertKeyToSnake(mapper, indexKey.Relational().Name);
                        break;
                    default:
                        throw new NotImplementedException("Unexpected type was provided to snake case converter");
                }
            }
    
            private string ConvertKeyToSnake(INpgsqlNameTranslator mapper, string keyName) =>
                ConvertGeneralToSnake(mapper, _keysRegex.Replace(keyName, match => match.Value.ToLower()));
    
            private string ConvertGeneralToSnake(INpgsqlNameTranslator mapper, string entityName) =>
                mapper.TranslateMemberName(ModifyNameBeforeConvertion(mapper, entityName));
    
            protected virtual string ModifyNameBeforeConvertion(INpgsqlNameTranslator mapper, string entityName) => entityName;
        }
    }
