### ISSUE TITLE
DNX Migration throws exception even though VS build doesn't

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#4448]
I'm switching my User ID from an Int32 to a Guid, and the project builds fine, but from the command line, when I try to add the migration, I get:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.ArgumentException: GenericArguments[0], 'MyNamespace.User', on 'Microsoft.AspNet.Identity.EntityFramework.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type 'TUser'. 
---> System.TypeLoadException: GenericArguments[0], 'MyNamespace.User', on 'Microsoft.AspNet.Identity.EntityFramework.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type parameter 'TUser'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
```

Like I said, the code builds fine in Visual Studio, so I'm a bit confused why the DNX tool would show me something different.

**Comment by bartlannoeye** [comment]
I've received the same error, even on an empty DbContext. Trying to find out the reason. I got a sample app working with Guid as Id though, so it has to be something different. Any info on how to improve debugging this would help to create a minimal sample.

**Comment by joshmouch** [comment]
@bartlannoeye Good to hear.  The past few times I've gotten perplexing issues like this, I usually destroy my Migration folder and start from scratch, but I'd rather not do that.

**Comment by joshmouch** [comment]
I couldn't figure this out, so I went to the familiar backup plan.  I deleted my Migrations folder and started from scratch.  It works now!

**Comment by joshmouch** [comment]
Actually, I spoke too soon.  The problem was that this line in Startup.cs also needed to be switched from <int> to <Guid>:
.AddEntityFrameworkStores<Repository, Guid>()
