### ISSUE TITLE
Simplify required provider services

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#4449]
Provider writers are required to implement/extend `IDatabaseProviderServices`. In stubbing out an [empty provider](https://github.com/natemcmaster/entityframework-provider-starter), I found the following APIs cumbersome. Can we review/cleanup the following?
- Required provider service [`EntityQueryModelVisitor`](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs). 
  - It is abstract but has no abstract members.
  - It has 15 constructor arguments. Can we consolidate?
  - Providers must implement `IEntityQueryModelVisitorFactory`. This must also pass 15 constructor arguments along to `EntityQueryModelVisitor`. This means means each provider ends up with a class that looks like this: [SqliteQueryModelVisitorFactory](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitorFactory.cs), even if they are not changing any base functionality. Can we get around required this kind of implementation?
- These abstract classes implement required provider services but they have no abstract members. Are they intentionally abstract or is this left-over from API changes? Do providers really need to implement them if we have fully-functioning base implementations?
  - [`EntityQueryModelVisitor`](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs)
  - [`ValueGeneratorCache`](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore/ValueGeneration/ValueGeneratorCache.cs)
  - [`ModelSource`](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore/Infrastructure/ModelSource.cs)
  - [`RelationalCompositeMethodCallTranslator`](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/RelationalCompositeMethodCallTranslator.cs)
  - [`RelationalCompositeMemberTranslator`](https://github.com/aspnet/EntityFramework/blob/9d646ae9a361490771e0e0f7719b0ecba0519420/src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/RelationalCompositeMemberTranslator.cs)
- (nit) `IDatabaseProviderServices` is in the ".Storage" namespace. IMO seems like ".Infrastructure" would me more appropriate.

**Comment by ajcvickers** [comment]
`ValueGeneratorCache` and `ModelSource` need to be implemented by providers so that each provider gets its own independent cache of these things.

**Comment by anpete** [comment]
Sending back to triage.
