### ISSUE TITLE
Update with rowversion (optimistic concurrency) and trigger causing exception

### ISSUE THREAD

**Issue by ljfolino** [dotnet/efcore#4456]
I have a simple scenario where I am trying to update an object.  I have a rowversion and optimistic concurrency enabled on the entities. This works without issues.   I then added a trigger to update the last modified time of the object on update.  I am receiving this error when doing so.

The target table 'Inbound' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

My question is can I make EF handle this better.  Is there a way to make EF not use OUTPUT?  My thought is to maybe us an INSTEAD OF INSERT SQL trigger instead, but I am not sure if this will work either.  Is there a better way to handler this?

**Comment by rowanmiller** [comment]
Hey,

This has already been fixed in our current code base and the fix will ship in RC2. I wouldn't recommend trying nightly builds at the moment as we are in the process of moving to .NET CLI and things are very unstable.

BTW here is the main issue tracking the problem https://github.com/aspnet/EntityFramework/issues/1441.

~Rowan

**Comment by emardini** [comment]
Just to make sure, can we say that this fix is available in EF core? Is there any chance to include the fix in EF 6?

**Comment by rowanmiller** [comment]
@emardini EF6 has a simpler mechanism for returning generated values, as it doesn't do batching. We don't think it suffers from the same issues with triggers. Have you hit a specific issue? It's unlikely we'd change things like this in EF6 - as they are typically high risk.
