### ISSUE TITLE
Should core types be renamed to reflect datastores

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/efcore#4463]
Given that EF is being rewritten to be used more generally than just databases, and given that EF Core is a 1.0 project, does it make to rename some core types, properties, etc.?

For instance, should `DbContext` become something like `DataContext` (used by System.Data.Linq :disappointed:), `EntityContext` or `DatastoreContext`? Should `DbContext.Database` become something like `DatastoreContext.Datastore`?

This will cause some migration issues, but for the long term path of the project, this seems an appropriate step. It would be sad for a newbie to get EF Core 1.0 and then ask, "Why is everything prefixed with DB when I'm not using a database?" and then the reason be "Legacy reasons", when, again, it's a 1.0.

Thoughts?

(I'm sure I'm not the first to think of this, but I couldn't find any other references.)

**Comment by Vasimovic** [comment]
Seems like all data that is being accessed has some structure to it, thus, calling it Database (Db) is okay in my opinion

**Comment by MisinformedDNA** [comment]
After reading more, I see that Redis is considered a key-value database. I also see that "database" is actually a pretty broad term. I like DbContext and am convinced, so I'll close this. :)
