### ISSUE TITLE
Are circular dependencies supported?

### ISSUE THREAD

**Issue by sharppanda** [dotnet/efcore#4473]
I have a follow up question to #4069 and its circular dependencies.
I have two classes Person and Car.

```
modelBuilder.Entity<Person>(entity =>
{
       entity.HasOne(d => d.CarInUse).WithOne(p => p.InUseBy).HasPrincipalKey<Car>(p => p.ID).HasForeignKey<Person>(d => d.CarID);
});
 modelBuilder.Entity<Car>(entity =>
{
       entity.HasOne(d => d.OwnedBy).WithMany(p => p.Cars).HasForeignKey(d => d.PersonID).OnDelete(DeleteBehavior.Restrict);
});
```

Like in #4069 I can store this via two SaveChanges() calls, otherwise I get circular reference.
First I store Person and Car without setting CarInUse, second i set CarInUse.

I am not sure if this is supported or i am doing something wrong.

Thanks for help

**Comment by rowanmiller** [comment]
Cyclic relationships are supported, but (as you stated) to save cyclic data you need to save in two stages.

**Comment by martinpaulicek** [comment]
Is there any recommended pattern how to work with entities like these? 
For ex should I do another layer of unit of work pattern, which would always create transaction scope before any work with context would be done?

**Comment by rowanmiller** [comment]
It really depends on your app model, if you are using a repository already then handling it in there is a good idea. If you are interacting directly with the context, then you could just do the incremental save in any area of the app where you are going to be saving a new customer and a new car which is the "car in use" at the same time.

**Comment by martinpaulicek** [comment]
Just to be sure, that i understand how incremental save works. If I call two SaveChanges() (all without creating any explicit transactions via dbContext), EF 7 will do on db level two separate transactions right?

**Comment by rowanmiller** [comment]
@martinpaulicek by default, yes. But you can use `context.Database.BeginTransaction()` etc. to manually control the scope of transactions.
