### ISSUE TITLE
Test perf of DetectChanges

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#4475]
We need some perf tests first, and then potentially some perf improvements.

Also, consider skipping the snapshot compare of scalar, non-key properties if they are already marked as modified.

**Comment by divega** [comment]
@rowanmiller @ajcvickers should we discuss the priority of completing this task for RTM in triage? it seems that perf of `DetectChanges()` should be somewhat covered indirectly by other tests.

**Comment by rowanmiller** [comment]
Sounds good, yes the update pipeline tests (really SaveChanges tests) would cover some of this.

**Comment by popcatalin81** [comment]
Please have some test cases with graph sizes > 1K-3K. This is the point where EF6 started seeing performance degradations in the order of seconds to dozens of seconds, which made EF6 complete inappropriate for large data set processing scenarios. Ideally EF7 should support such scenarios,

**Comment by rowanmiller** [comment]
@popcatalin81 - the data size for our benchmarks range from 1K - 10K rows/entities.
