### ISSUE TITLE
In-Memory Provider returns data even when not included

### ISSUE THREAD

**Issue by kwarnke** [dotnet/efcore#4481]
If you need a more detailed example, let me know (e.g., fully functioning code).  And if this is a duplicate, I apologize.  I searched the issues but couldn't find one that covered this question.

If I have a Parent that has a list of Children. I have to "include" the children in my query in order for that collection to be populated (this is expected behavior). That goes something like:

var entity = db.Parents.Include(p => p.Children).First(p => p.Id == 1);

However, when I am unit testing my code and using the in-memory provider to do so, that is not the case.  Both "db.Parents.First(...)" and "db.Parents.Include(...).First(...)" return my parent entity WITH the entity.Children populated.

The reason this is an issue is because I cannot unit test that my logic is properly requesting data from EF.  I want to unit test the LINQ/EF statement itself.  I can't ensure that ".Include(p => p.Children)" is a part of my logic because the same data is returned by the in-memory provider whether or not the include is included (no pun intended).

Any ideas how to tell the in-memory provider to NOT return data unless it has been included?

Thanks,
Kevin

**Comment by smitpatel** [comment]
Can you share the code of your test?

**Comment by kwarnke** [comment]
Here's a sample I put together that illustrates the problem.  The assert at the bottom should be comparing 0 to 2 (so it should be not equal).  But they are both 2.  I realize what is probably happening is these objects are in memory so the lists are "already there."  But that's not how EF works in the "real world" which is what I want the behavior to be.

If this is "by design," then how would you recommend we unit test our LINQ statements to ensure things like "Include" are a part of the statement so we know the data will be available when our actual app runs?

Thanks!

        public class TestDbContext : DbContext
        {
            public virtual DbSet<Parent> Parents { get; set; }
        }

        public class Parent
        {
            public int Id { get; set; }

            public List<Child> Children { get; set; } = new List<Child>();
        }

        public class Child
        {
            public int Id { get; set; }
        }

        [Fact]
        public void ShowInappropriateDataProvided()
        {
            // setup
            var serviceCollection = new Microsoft.Extensions.DependencyInjection.ServiceCollection();
            serviceCollection
                .AddEntityFramework()
                    .AddInMemoryDatabase()
                    .AddDbContext<TestDbContext>(c => c.UseInMemoryDatabase());

            var db = serviceCollection.BuildServiceProvider().GetService<TestDbContext>();

            var child1 = new Child();
            var child2 = new Child();
            var parent = new Parent();
            parent.Children.Add(child1);
            parent.Children.Add(child2);

            db.Parents.Add(parent);
            db.SaveChanges();

            // act
            var entity1 = db.Parents.First();
            var entity2 = db.Parents.Include(p => p.Children).First();

            // assert
            // this assert fails:
            Assert.NotEqual(entity1.Children.Count, entity2.Children.Count);
        }

**Comment by smitpatel** [comment]
You are using same DbContext for everything hence the objects are already loaded there.
To test the existence of include you need to use different instances for seeding, loading. If you use same instance to load with & without include it will still have all the data because one of the queries has loaded them.
We have recently added documentation on testing with InMemory database. Read more at 
http://ef.readthedocs.org/en/latest/miscellaneous/testing.html

Here is sample code I wrote to verify this with scoping
```c#
[Fact]
public void ShowInappropriateDataProvided()
{
	// setup
	var serviceCollection = new ServiceCollection();
	serviceCollection.AddEntityFramework()
		.AddInMemoryDatabase()
		.AddDbContext<TestDbContext>(c => c.UseInMemoryDatabase());

	var serviceProvider = serviceCollection.BuildServiceProvider();

	using (var scope = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
	{
		var db = scope.ServiceProvider.GetService<TestDbContext>();
		var child1 = new Child();
		var child2 = new Child();
		var parent = new Parent();
		parent.Children.Add(child1);
		parent.Children.Add(child2);

		db.Parents.Add(parent);
		db.SaveChanges();
	}

	Parent entity1, entity2;
	using (var scope = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
	{
		var db = scope.ServiceProvider.GetService<TestDbContext>();
		entity1 = db.Parents.First();
	}

	using (var scope = serviceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
	{
		var db = scope.ServiceProvider.GetService<TestDbContext>();
		entity2 = db.Parents.Include(p => p.Children).First();
	}
	Assert.NotEqual(entity1.Children.Count, entity2.Children.Count);
}
```

**Comment by kwarnke** [comment]
Brilliant!  That's exactly what I was looking for.  I will look at those updated docs as well.  Thank you!
