### ISSUE TITLE
Sqlite provider dosen't return new line charachter from database

### ISSUE THREAD

**Issue by boyarincev** [dotnet/efcore#4493]
I use sqlite provider with entity framework 7.
I try to save and get from database text contains new line charachters. As far i understand text saves properly (because i see it properly formatted at DB Browser for SQLite) but when i getting it from database, it dosen't contain any new line charachters.
I use  `"EntityFramework.Sqlite": "7.0.0-rc1-final"` package.

**Comment by natemcmaster** [comment]
Could you provide code that reproduces the issue?

**Comment by boyarincev** [comment]
Exuse me please, that was my mistake!
