### ISSUE TITLE
dnx add migration, IHostingEnvironment.WebRootPath is null

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#4494]
I have an ASP.NET 5 WebApplication, and an EF 7 db context (RC 1 Final) in a seperate project.

When I `CD` to my web project directory, and run `dnx ef migration add InitialMigration -p SomeEfDataProject`

I am getting an exception to do with the fact that during initialisation, my application makes use of `IHostingEnvironment.WebRootPath` which is Null within the context of executing the dnx migration command line.

Shouldn't this be set to something?

My application startup logic uses `IHostingEnvironment.WebRootPath` to figure out a path to a local drop folder, where plugin (mef) components can be dropped and loaded during app startup.

**Comment by dazinator** [comment]
I have worked around this by chucking this in my startup logic, seems to solve it.

```csharp
   if (string.IsNullOrWhiteSpace(_env.WebRootPath))
   {
       _env.WebRootPath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
   }
```

**Comment by rowanmiller** [comment]
cc @bricelam... seems like there probably isn't much we can do here?

**Comment by dazinator** [comment]
Setting `WebRootPath` to an empty value or a fake value, might help. I don't think when people are developing an application that they would expect the 'WebRootPath' to potentially be Null. In the normal case this is always set to something. In the EF migration case, because it's not it can cause an issue.

**Comment by bricelam** [comment]
We could provide a *better* value for `WebRootPath`, but it would still be wrong for some projects. We could also go back to taking a dependency on Hosting, but there sure was a lot of pushback...

**Comment by dazinator** [comment]
> but it would still be wrong for some projects

The webroot for an asp.net 5 project is specified in the project.json file, so is not a simple case of checking for this value in project.json and setting WebRootPath appropriately. That should then be correct for all projects unless I am missing something..

**Comment by rowanmiller** [comment]
Closing in favor of a more general issue to sort out how we interact with Startup https://github.com/aspnet/EntityFramework/issues/4546
