### ISSUE TITLE
Skip() method not working

### ISSUE THREAD

**Issue by Rajamohanrnd** [dotnet/efcore#4499]
var list = db.Orders.Skip(10).ToList(); throws "Incorrect syntax near 'OFFSET'."
var list = db.Orders.Skip(10).Take(10).OrderBy(x => x.OrderId).ToList(); throws "Incorrect syntax near 'OFFSET'.
 and
Invalid usage of the option NEXT in the FETCH statement."

This happens with or without OrderBy.
Am I missing something?

**Comment by ErikEJ** [comment]
Do you use SQL Server 2008?

**Comment by Rajamohanrnd** [comment]
Yes, I use Microsoft SQL Server 2008 R2 (SP2)

**Comment by ErikEJ** [comment]
Then you need to use UseRowNumberForPaging() in your OnConfiguring method (as OFFSET / FETCH is only supported in SQL Server 2102 and later)

**Comment by john182** [comment]
even using the method still has the error cited by fellow up
