### ISSUE TITLE
"EntityFramework.Commands": "7.0.0-rc1-final" get Internal compiler error when used with Microsoft.Data.Services.Client": "5.7.0

### ISSUE THREAD

**Issue by joeleesh** [dotnet/efcore#4511]
I am using Visual Studio 2015 and Windows 10 with latest SDK. Here are the steps to reproduce the error.
1. Create "Blank App(Universal Windows)" from VS2015
2. Add entity framework 7 package as per this link.http://docs.efproject.net/en/latest/platforms/uwp/getting-started.html
3. Add "Microsoft.Data.Services.Client": "5.7.0" from NuGet manager
4. Change solution build from Debug to Release (It works on Debug build but not release build) from VS
5 Hit F5 run the app and you will get Internal compiler error. "The type name 'RCWAdapterClass' does not exist in the type 'System.Collections.Generic.IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Object_V__V__V__V__V__V__V__V__V___Impl'
Here is project json file for reference:
{
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.SQLite": "7.0.0-rc1-final",
    "Microsoft.Data.Services.Client": "5.7.0",
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by bricelam** [comment]
@natemcmaster Could this be caused by the known .NET Native issues we had on RC1?

**Comment by rowanmiller** [comment]
We have done a major overhaul of how things with work with UWP (due to a lot of issues like this one). This should all work once RC2 is release.
