### ISSUE TITLE
Sql IsConcurrencyToken uses same value

### ISSUE THREAD

**Issue by IgorWolbers** [dotnet/efcore#4512]
Please let me know if this feature has not yet been developed or maybe the convention of marking an entity with a previous timestamp has changed from EF6.

**Platform**
- Sql Server 2012
- EF Core
  - EntityFramework.Commands 7.0.0-rc1-final
  - EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final
- Web API (_not necessary to reproduce_)

The database and corresponding entity have a rowversion / timestamp column so that concurrency exceptions can be handled.

**Scenario**
1. Web page is loaded which includes a basic entity which is retrieved from the database using EF. The EF Context is then disposed of after the request finishes.
2. Another actor makes a change to the entity that was requested in step 1, thereby updating the timestamp.
3. The entity in step 1 has been changed and is posted back using Web API, included in the post back is the old timestamp value.
4. The Web API method retrieves the entity, updates the fields, and updates the concurrency token / timestamp to that passed in.
5. Update is executed via SaveChangesAsync();

**Expected**
`DbUpdateConcurrencyException` is thrown because the passed in timestamp to the entity does not match that in the database.

**Actual**
EF ignores the set timestamp on the entity and uses the timestamp version that it had retrieved when the entity was retrieved from the database.

I have reproduced this using a simple DbContext, a simple DDL, and a simple Unit Test which does nothing other than set the timestamp to some hard coded byte array value.

Please let me know if I am missing something. I am going off of the [documentation found here](http://docs.efproject.net/en/latest/modeling/concurrency.html#how-concurrency-tokens-work-in-ef)

**DDL**

```
CREATE TABLE [dbo].[Person](
    [Id] [int] IDENTITY NOT NULL,
    [Title] [varchar](50) NOT NULL,
    [Timestamp] [rowversion] NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
))
INSERT INTO Person (title) values('user number 1')
```

**Code**

```

public class Context : DbContext
{
    public Context(DbContextOptions options)
        : base(options) {}

    public DbSet<Person> Persons { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().HasKey(x => x.Id);

        modelBuilder.Entity<Person>().Property(x => x.Id)
            .UseSqlServerIdentityColumn()
            .ValueGeneratedOnAdd()
            .ForSqlServerHasColumnName("Id");

        modelBuilder.Entity<Person>().Property(x => x.Title)
            .ForSqlServerHasColumnName("Title");

        modelBuilder.Entity<Person>().Property(x => x.Timestamp)
            .IsConcurrencyToken(true)
            .ValueGeneratedOnAddOrUpdate()
            .ForSqlServerHasColumnName("Timestamp");

        base.OnModelCreating(modelBuilder);
    }
}

public class Person
{
    public int Id { get; set; }

    public String Title { get; set; }

    // [Timestamp], tried both with & without annotation
    public byte[] Timestamp { get; set; }
}

public class UnitTest
{
    private string dbConnectionString = "DbConnectionStringOrConnectionName";
    public EFTimestampBug.Models.Context CreateContext()
    {
        var options = new DbContextOptionsBuilder();
        options.UseSqlServer(dbConnectionString);
        return new EFTimestampBug.Models.Context(options.Options);
    }

    [Fact] // this test passes
    public async Task TimestampChangedExternally()
    {
        using (var db = CreateContext())
        {
            var person = await db.Persons.SingleAsync(x => x.Id == 1);
            person.Title = "Update 2 - should fail";

            // update the database manually after we have a person instance
            using (var connection = new System.Data.SqlClient.SqlConnection(dbConnectionString))
            {
                var command = connection.CreateCommand();
                command.CommandText = "update person set title = 'changed title' where id = 1";
                connection.Open();
                await command.ExecuteNonQueryAsync();
                command.Dispose();
            }

            // should throw exception
            try
            {
                await db.SaveChangesAsync();
                throw new Exception("should have thrown exception");
            }
            catch (DbUpdateConcurrencyException)
            {
            }
        }
    }

    [Fact] // this test fails
    public async Task EmulateAspPostbackWhereTimestampHadBeenChanged()
    {
        using (var db = CreateContext())
        {
            var person = await db.Persons.SingleAsync(x => x.Id == 1);
            person.Title = "Update 2 - should fail " + DateTime.Now.Second.ToString();

            // This emulates post back where the timestamp is passed in from the web page
            // the Person entity attached dbcontext does have the latest timestamp value but
            // it needs to be changed to what was posted
            // this way the user would see that something has changed between the time that their screen initially loaded and the time they posted the form back
            person.Timestamp = new byte[] {0,0,0,0,0,0,0,120};  // a hard coded value but normally included in a postback
            try
            {
                await db.SaveChangesAsync(); // EF ignores the set Timestamp value and uses its own value in the outputed sql
                throw new Exception("should have thrown DbUpdateConcurrencyException");
            }
            catch (DbUpdateConcurrencyException)
            {
            }
        }
    }
}

```

**Comment by divega** [comment]
@IgorWolbers the optimistic concurrency mechanism relies on EF remembering the __original__ value of the Timestamp property, which is added to the WHERE clause of the UPDATE statement. Setting the __current__ value of the property as you do in your second test won't have the same effects.

**Comment by Abrissirba** [comment]
How are you supposed to work with detached entities if you can't set the timestamp? If you send a DTO from a javascript app and wants to update the db entity, how are you suppose to use the timestamp property to make sure that no one has updated the object during the time it was detached in the javascript client?

**Comment by IgorWolbers** [comment]
@divega - Got it, thank you. I have updated the code that fails to the following to get it to work. 

```
var passedInTimestamp = new byte[] { 0, 0, 0, 0, 0, 0, 0, 120 };  // a hard coded value but normally included in a postback
var entryProp = db.Entry(person).Property(u => u.Timestamp);
entryProp.OriginalValue = passedInTimestamp;

```

I do realize that the previous version(s) of EF are different that EF Core in that Core is a complete re-write. The behavior though I would expect to be similar if not the same as far as how the developer interacts with certain aspects of EF. I do know that the previous version of EF you do not have to update the original value for a Timestamp column, just by updating the current value the sql implementation would generate the correct statement that would throw an `DbUpdateConcurrencyException` if the user updates the Timestamp property manually. 

Is this also the right place to ask for an enhancement or maybe it would be considerd a bug? I would like to request that EF Core Sql Implementation generate the query in the same manner as EF 6 when manually updating the timestamp so developers do not have to figure out that you have to update the OriginalValue.

If this is something that will not or can not be done in the near future then it might be a good idea to update the documentation for now so it's spelled out clearly that this is what you have to do when updating only part of an entity in a detached state where the entity had to be retrieved for the update.

**Comment by divega** [comment]
@Abrissirba @IgorWolbers There aren't many differences in this area between EF6 and EF Core at this stage. The second test will in fact fail in EF6 in pretty much the same way it fails in EF Core. 

In order to properly emulate the scenario in a test you have two use two separate context instances: one fore retrieving the entity and another one for saving it to the database. When the entity is attached to the second context the value carried in the Timestamp property becomes both the current and the original value. 

So if you want to emulate the scenario for the purpose of a tests and don't want to use the `OriginalValue` API then set the new value on the `Timestamp` property before you attach it. Then you can choose to modify the title property so that it is marked as changed on in EF Core you can use the new `Update()` API which will attach the entity and mark it as modified in one call:

``` C#
public static void EmulateAspPostbackWhereTimestampHadBeenChanged()
{
    Person person;
    using (var db = CreateContext())
    {
        person = db.Persons.Single(x => x.Id == 1);
        person.Title = "Update 2 - should fail " + DateTime.Now.Second.ToString();
    }
    using (var db = CreateContext())
    {
        person.Timestamp = new byte[] { 0, 0, 0, 0, 0, 0, 0, 120 };
        db.Update(person);  
        try
        {
            db.SaveChanges(); 
            throw new Exception("should have thrown DbUpdateConcurrencyException");
        }
        catch (DbUpdateConcurrencyException)
        {
        }
    }
}
```

**Comment by IgorWolbers** [comment]
@divega - It's crystal clear to me now and you are 100% correct on behavior from EF6. 
Thank you for your time.
