### ISSUE TITLE
sqlite provider try to create foreign keys

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#4513]
Hi,
  I created a small ef model using sqlite adding a few relationship among entities. I see when I create migrations tries to create foreign keys, giving error trying to update the db.
  It is possible to avoid the creation of these commands? Currently I have to remove manually every time.

**Comment by bricelam** [comment]
Feel free to edit the Migration and remove the calls to `AddForeignKey`. This is a known [limitation of SQLite](http://ef.readthedocs.org/en/latest/providers/sqlite/limitations.html).

**Comment by rowanmiller** [comment]
As noted, this is just a limitation of SQLite - it does not support adding FKs to existing tables.
