### ISSUE TITLE
InMemory provider ignores unique keys

### ISSUE THREAD

**Issue by hameedfs** [dotnet/efcore#4516]
InMemory provider ignores unique key constraints defined in the model. Attached is a test code that shows the behavior comparing it to SQLite.

**Comment by hameedfs** [comment]
[UniqueIdTests.zip](https://github.com/aspnet/EntityFramework/files/121464/UniqueIdTests.zip)

**Comment by rowanmiller** [comment]
Duplicate of https://github.com/aspnet/EntityFramework/issues/3850
