### ISSUE TITLE
TPH - Error (An item with the same key has already been added)

### ISSUE THREAD

**Issue by srivch** [dotnet/efcore#4522]
I have the following TPH 

```
public class parent 
{ 
public int Id {get; set;} 
public string Name {get; set;} 
}
public class child1 : parent 
{
public string child1Property {get; set;}
}

public class child2 : parent 
{
public string child2Property {get; set;}
}

public class Master
{
public int Id {get; set;}
public List<child1> Child1List {get; set;}
public List<child2> Child2List {get; set;}
}
```

When migration is generated for the above, get the error "An item with the same key has already been added". I think we get it because EF determines the FK relationship (one to many) and adds a foreign for the first child list, but when it does for the second list the foreign key is already present and therefore throws error. Is there a way to get around this problem?

**Comment by srivch** [comment]
The following query in TPH for the above model throws - {"Sequence contains more than one matching element"}
```
(from m in Master
select m)
.Include(i => i.Child1List)
.Include(i => i.Child2List)
.FirstOrDefault();
```
This seems to be an issue with 7.0.0-rc2-16649

**Comment by rowanmiller** [comment]
@smitpatel possibly something you have already fixed?

**Comment by srivch** [comment]
Why is EF creating foreign keys by default for TPH entities.. For example
```
public class Master
{
public int Id {get; set;}
public child1 Child1 {get; set;}
public child2 Child2 {get; set;}
pubic  XYZType xyz {get; set;}
}
```
In the example above EF creates two foreign keys in Master entity one for Child1 and other for Child2, but when i reference a non TPH entity  EF does not create a foreign key by default for xyz?

**Comment by smitpatel** [comment]
> "An item with the same key has already been added"

This error is not related to model building. It throws at sorting migration operations. I tried running the model in first post and the model is created correctly by EF. Are there other model classes which are not included here? If you can provide repro code then it would be great.

For the model in previous post, it is possible that EF is creating the foreign key in entity type XYZType and not in entity type Master. Again please provide full code and issue you are seeing.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details
