### ISSUE TITLE
Duplicated Ids in HasIndex

### ISSUE THREAD

**Issue by wannadream** [dotnet/efcore#4531]
After I did a scaffolding from database, it reports errors from compiler. I have to remove them one by one.
![ef7_1](https://cloud.githubusercontent.com/assets/6989212/12959429/346cda6e-cfeb-11e5-972d-cfd11f214164.gif)

**Comment by rowanmiller** [comment]
Can you share the database schema that you scaffolded from.

**Comment by smitpatel** [comment]
dupe of #3847 ?

**Comment by lajones** [comment]
Yep - agree with @smitpatel - looks like a dupe of #3847. @wannadream what version of EF were you using?

**Comment by wannadream** [comment]
Yes, it's duplicated with #3847.
