### ISSUE TITLE
error including related entity

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#4536]
in a dbContext I have two entites connected in a n to n relationdship. I created in the context property getters that already include the related entities, so when I do a query the related entities are loaded in a consistent way.

```
        public virtual IQueryable<Deposito> DepositiCompleti
        {
            get
            {
                return Depositi
                    .Include(cli => cli.Gruppo).Include(cli => cli.SottoGruppo).Include(cli => cli.Sede)
                    .Include(cli => cli.CentroCosto).Include(cli => cli.Tipo);
            }
        }
        public virtual IQueryable<Deposito> DepositiDettagli
        {
            get
            {
                return DepositiCompleti
                    //.Include(grp => grp.Depositi_Centrali).Include(grp => grp.Depositi_CentriCosto).Include(grp => grp.Details);
                    .Include(grp => grp.Depositi_Centrali.Select(dc => dc.Centrale)).Include(grp => grp.Details);
            }
        }

```

If in the Second prop getter I include just the entity that connect the two entities

`.Include(grp => grp.Depositi_Centrali)`

all works fine, but if I include the selection of the related entities
`.Include(grp => grp.Depositi_Centrali.Select(dc => dc.Centrale))`

querying the db this way:
`var elemento = await _db.DepositiDettagli.FirstOrDefaultAsync(att => att.Id == id);`

I see this error:

> Exception thrown: 'System.InvalidCastException' in EntityFramework.Core.dll
> Microsoft.Data.Entity.Query.Internal.QueryCompiler: Error: An exception occurred in the database while iterating the results of a query.
> System.InvalidCastException: Impossibile eseguire il cast di oggetti di tipo 'Remotion.Linq.Clauses.Expressions.SubQueryExpression' sul tipo 'System.Linq.Expressions.MemberExpression'.
>    in Microsoft.Data.Entity.Query.ResultOperators.Internal.IncludeExpressionNode.CreateResultOperator(ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.IntermediateModel.ResultOperatorExpressionNodeBase.ApplyNodeSpecificSemantics(QueryModel queryModel, ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.IntermediateModel.MethodCallExpressionNodeBase.Apply(QueryModel queryModel, ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.QueryParser.ApplyAllNodes(IExpressionNode node, ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.QueryParser.ApplyAllNodes(IExpressionNode node, ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.QueryParser.ApplyAllNodes(IExpressionNode node, ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.QueryParser.ApplyAllNodes(IExpressionNode node, ClauseGenerationContext clauseGenerationContext)
>    in Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
>    in Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileAsyncQuery>b__0()
>    in Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
>    in Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
>    in Microsoft.Data.Entity.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)

Is this normal? Something changed from ef 6 and core1?

**Comment by rowanmiller** [comment]
>  Something changed from ef 6 and core1?

Yes... lots of things :wink: 

> ` .Include(grp => grp.Depositi_Centrali.Select(dc => dc.Centrale))`

The syntax in EF Core is `.Include(grp => grp.Depositi_Centrali).ThenInclude(dc => dc.Centrale))`. Can you confirm that the query works once you use that syntax.

Assuming it does, we'll open an issue to improve the exception message since that was the EF6 format and folks will likely expect it to work.

**Comment by lucamorelli** [comment]
Ah, Ok, thanks. 
  Yes, I used **ThenInclude** in other project, but since I seen that I was able to write it, tit was supposed.
 Using ThenInclude it works, but now I tried another thing and is giving me an error: I tried to include both od the sides of the navigation this way

`.Include(grp => grp.Depositi_Centrali).ThenInclude(dc => new { dc.Centrale, dc.Deposito }).Include(grp => grp.Details);
`
but I receive this error

> System.ArgumentException: The properties expression 'dc => new <>f__AnonymousType37`2(Centrale = dc.Centrale, Deposito = dc.Deposito)' is not valid. The expression should represent a property access: 't => t.MyProperty'. When specifying multiple properties use an anonymous type: 't => new { t.MyProperty1, t.MyProperty2 }'.

I don't undertand very well the message: seems to me I'm already using an anonymous type

**Comment by maumar** [comment]
@lucamorelli you need to include them one at a time, like so:
```
.Include(grp => grp.Depositi_Centrali).ThenInclude(dc => dc.Centrale)
.Include(grp => grp.Depositi_Centrali).ThenInclude(dc => dc.Deposito)
.Include(grp => grp.Details); 

```

**Comment by lucamorelli** [comment]
I know that this way works, I was looking for a simpler way to include more dependencies at the same time

**Comment by rowanmiller** [comment]
@lucamorelli we have https://github.com/aspnet/EntityFramework/issues/4490 tracking some more advanced APIs to write less verbose include code in the future.

Closing this one out now, as I think we've answered the question. Feel free to reopen if now.
