### ISSUE TITLE
Lazy loading behaves awkward when the DbContext tracks only part of the children

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#4538]
This is my seed data:

```
var firstPost = new Post
                    {
                        Forum = newsForum,
                        Text = "Root level",
                        PublishDate = DateTime.Now
                    };
var secondPost = new Post
                        {
                            Forum = newsForum,
                            Text = "Second post",
                            PublishDate = DateTime.Now,
                            ReplyToPost = firstPost
                        };

var thirdPost = new Post
                    {
                        Forum = newsForum,
                        Text = "third post",
                        PublishDate = DateTime.Now,
                        ReplyToPost = firstPost
                    };

context.Posts.AddRange(firstPost, secondPost, thirdPost);
```

And this is the Post entity:

```
public class Post
{
    public int Id { get; set; }
    public string Text { get; set; }
    public DateTime PublishDate { get; set; }
    public DateTime? LastChangedDate { get; set; }
    public int ForumId { get; set; }
    public virtual Forum Forum { get; set; }
    public int? ReplyToPostId { get; set; }
    public Post ReplyToPost { get; set; }
    public virtual List<Post> Replies { get; set; }
}
```

When I query for the root post with 

```
var root = _context.Posts.Single(x => x.Text == "Root level");
```

I get null for `Replies` which is what I was expecting (maybe proxy, but that's a different issue {pun intended})

Later I query for

```
var thirdPost = _context.Posts.Single(x => x.Text == "third post");
```

Now `root.Replies.Count == 1`
Later I query for all the posts with:

```
_context.Posts.ToList();
```

Now `root.Replies.Count == 2`. 

(All without changing or touching the root post `root` )

Now this is awkward, when it's null (or empty if I init the list in my Ctor) I can easily know it simply wasn't loaded yet.
But when I get a  List for Replies, I know it was loaded from the DB already and I don't need to load it again, but that's not true, I got the List because for some reason one of the replies was tracked already(or after like in this case) by the DbContext, it shows incorrect data.

One could argue that if I want to use the `Replies` property I should eagerly load it with `Include` and that's true, but that's just an (very) important pattern, even if I foolishly doing N+1 queries all over my application, my model should be correct as in the DB.

I think that unless the DbContext knows that it has all the children because it executed already queries like:

```
_context.Posts.ToList()
_context.Posts.Where(x=>x.Id == rootPostId).ToList()
```

It should keep the List empty.

**Comment by davidroth** [comment]
I think this is a bad idea. I expect `DbContext` to be consistent. Everything which has been loaded into the context should be reflected by its entities including collections and navigation properties.

Consider you wanted to load related posts within a certain date range:

`context.Posts.Load(x => x.PublishDate  > date1 && x.PublishDate < date2);`

With your recommendation, root.Replies would still be null because there may be other replies in the db which have not been loaded yet. 
How would you handle this? E.x. EF cannot know if the Replies Collection reflects all replies in the db. Even if EF could know the total amount of children, it is a common use case to partially load collection navigation properties (like in the example above, or with soft-deleted use case etc.)

**Comment by rowanmiller** [comment]
**EF Team Triage:** Agreed with @davidroth analysis. BTW in the future there will be an `IsLoaded` flag that you can access for navigation properties to test if they are loaded or not (https://github.com/aspnet/EntityFramework/issues/1201)
