### ISSUE TITLE
EntityFrameworkServicesBuilder AddDbContext API

### ISSUE THREAD

**Issue by louislewis2** [dotnet/efcore#4541]
Hi guys,

I have been working through an issue when I finally discovered that when calling the AddDbContext api, that it registers the type as scoped, while I am sure this is the best case for many scenarios, it might not always be the case as I have discovered.

Could another call not possibly be added that would allow us to pass in how we would like to register the given context?

**Comment by rowanmiller** [comment]
@louislewis2 I assume you are wanting to move to transient so that you get a fresh context every time you ask for it?

**Comment by divega** [comment]
@louislewis2 does the feature described at https://github.com/aspnet/EntityFramework/issues/4441sound like it would help in your scenario?

**Comment by louislewis2** [comment]
@rowanmiller Correct, I am after transient, so currently doing a bit of a manual registration, which when not done correctly gives other DI errors, so I feel that allowing an api call that allows us to pass in the type might cater for a wider range of scenarios.

**Comment by louislewis2** [comment]
@divega It might work too, but I think for my given scenario, having a simple extra api call available when registering the context initially and being able to set the type of registration would be simplest and most straight forward solution in the code base. I also think that an extra overload possibly would be more easily discoverable by users trying to achieve the same end result.

**Comment by rowanmiller** [comment]
The scenario of #4441 is "Improve experience for creating multiple instances of a DbContext in the same request". I think this falls under that banner, so I modified the description of #4441 to also consider the option to make the context transient in AddDbContext (in addition to the activator/factory pattern being discussed there).
