### ISSUE TITLE
Alternate Keys Should be interchangeable with primary keys

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dotnet/efcore#4543]
In this [repo](https://github.com/TrabacchinLuigi/EFCoreTests/tree/master/AlternateKeys) i've setupped an example of what i mean...

ALternateKeys allow an entity to be accessed using those alternative keys, but the primary keys still exist and i should be able to access that entity using also that.
One way of doing it would be creating two different relationship but i should mark both of them as nullable and this is not what i mean... i think a better behaviour would be being able to mark two foreign keys for the same relationship, i've tried that but seems i have to choose wich one to use and stick to that.

I think this is a little bit less helpful than having two foreign keys for the same relationship ... where you have to specify at least one for one to many relationships.

**Comment by Tarig0** [comment]
I don't see a reason to overload a relationship here how would you expect to use the relationship with the userid and/or username

**Comment by Tarig0** [comment]
wait your storing username and ID in both entities why? shouldn't you just need the ID?

**Comment by rowanmiller** [comment]
We discussed this as a team and concluded that this is not something we would support in EF. The concept of having a single foreign key that represents the relationship is fundamental to how EF is designed. To achieve this scenario, you would need to model two optional relationships and then handle choosing between them in your application code.

**Comment by TrabacchinLuigi** [comment]
@Tarig0 I was trying to implement an sso and wanted to have string as keys but not turn on identity insert,  so if this worked this way that would have been extremely easy to implement using way less query. 
Important thing is ef team knew the possibility :)
