### ISSUE TITLE
Accessing DbContext from additional threads

### ISSUE THREAD

**Issue by hauteur** [dotnet/efcore#4544]
I'm not sure that this is the best place for this as it touches multiple areas, but I had to pick one...

I am writing a custom file provider (and corresponding file info class) that retrieves information from a database.  In a file provider, GetFileData is called by the middleware (I reused StaticFileMiddleware since it already does everything I need), but any options are passed in startup - in ConfigureServices.

The problem with that is that DI passes an instance of the DbContext once when the FileProvider is assigned to the middleware.  If I try to use that instance, it fails if there are multiple requests occurring - basically because DbContext is not thread safe.

Also, I am using the DbContext that was configured in startup.

Now, here's the question.  How do I get a new instance of the DbContext without bypassing the services framework?  Is there a way to get a new instance from the services?

I could be totally missing it because I'm new to DI, but it seems that the DI framework doesn't reach down that far.

ConfigureServices => StaticFileMiddleware => DbFileProvider => GetFileData() [Called from multiple requests]

Below is the code that creates the file provider and the code for GetFileData().  In the only way I can see to do it, StaticFileMiddleware exists once for the application and, as a result, the file providers only exist once.  That means that a method that is called once per request is accessing a single instance of the DbContext.  What I'm not seeing how to do is to get a new instance for every request.  Is there a way to do this without breaking the DI pattern?

Thanks!

```
private static void ConfigureCmsFiles(IApplicationBuilder app) {
    Data.CmsDbContext objDb = app.ApplicationServices.GetService(typeof(Data.CmsDbContext)) as Data.CmsDbContext;
    StaticFileOptions objStaticOptions = new StaticFileOptions();

    //TODO: Replace CompositeFileProvider with stock ASP.NET class once it is released
    CompositeFileProvider objComposite = new CompositeFileProvider(
        new List<IFileProvider>() {
            new CmsFileProvider(objDb)
            // GetEmbeddedFileProvider()
        }
   );
    objStaticOptions.FileProvider = objComposite;
    app.UseMiddleware<StaticFileMiddleware>(objStaticOptions);
}

```

```
public IFileInfo GetFileInfo(string subpath) {
    string strRoot = GetPathRoot(subpath);
    string strName;
    string strPath;

    if (string.IsNullOrEmpty(strRoot) == false && BasePaths?.Count() > 0 && BasePaths.Any(s => s.ToLower() == strRoot.ToLower()) == false)
        return new NotFoundFileInfo(subpath);

    strName = GetFileName(subpath);
    strPath = subpath.Remove(subpath.Length - strName.Length).Trim('/');

    if (string.IsNullOrEmpty(strName))
       return new NotFoundFileInfo(subpath);

    CmsFileInfo objInfo = new CmsFileInfo(_db, strPath, strName);
    if (objInfo.Length == 0)
       return new NotFoundFileInfo(subpath);

    return objInfo;
 }
```

**Comment by rowanmiller** [comment]
You need to resolve the context from the `IServiceProvider` within a request, rather than resolving a singleton one during `Startup.cs`. The `Invoke` method of your middleware takes an `HttpContext`, get the `RequestServices` property from this and resolve the context from there.

Here is an example of where we do this https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore/MigrationsEndPointMiddleware.cs#L113

**Comment by rowanmiller** [comment]
Closing as I'm pretty confident I've answered this one... but feel free to reopen if not :smile:

**Comment by hauteur** [comment]
So, if I'm understanding correctly, that means I won't be able to use `StaticFileMiddleware`, I'll have to create my own.  Also, `StaticFileContext` is internal, so I'll have to recreate it as well.  Is that correct, or am I misunderstanding something?  The `Invoke` method is in `StaticFileMiddleware`, yeah?

**Comment by rowanmiller** [comment]
Ok, yep sorry I missed that `StaticFileMiddleware` is an existing piece of middleware from ASP.NET Core and not something you were building. What you really need is a way to get to the request services from within your implementation of `IFileProvider`. This seems to be a limitation in how `StaticFileMiddleware` is factored as I don't see anyway to get a hold of the request services in your component, so I don't see anyway to properly resolve any services (including your context) from there.

I think this needs to turn into a feature request in https://github.com/aspnet/StaticFiles - since I don't think there is any way to solve this on the EF side - sounds right to you?

**Comment by hauteur** [comment]
You are totally right that what I need is a way to get at the request services from my implementation of `IFileProvider`.  What I'm not sure about is where the feature request should be.  To me, it isn't anything they would change in StaticFiles (except making it more extensible, perhaps), but maybe there should be a way to access the request services when DI can't reach your objects.

On the EF side, I did see a post where someone recommended creating a `DbContext `instance with an empty constructor.  That doesn't work because there is no configuration.  It does make me wonder if there could be a way to initialize a registered `DbContext` with the configuration options specified in startup.  Does that make sense?

Of course, that would probably go back to the same problem:  How do you get at request services when you don't have access to dependency injection?

**Comment by rowanmiller** [comment]
> On the EF side, I did see a post where someone recommended creating a  DbContext instance with an empty constructor. That doesn't work because there is no configuration. It does make me wonder if there could be a way to initialize a registered  DbContext  with the configuration options specified in startup. Does that make sense?

You could do this, resolve `DbContextOptions<CmsDbContext>` from DI and then add a constructor that takes this to your context. Since `DbContextOptions` is singleton, you are safe to grab the one at startup. The downside is that the context created this way does not resolve all its other services from DI... so you won't get logging etc.

That all just feels like a workaround for not being able to get the request services though... which is what you really want to make this all work.

**Comment by hauteur** [comment]
You're right.  Right now, I'm trying to pervert MS classes to make it work - StaticFileContext and CompositeFileProvider, but it feels really messy.

On the DbContextOptions, how would that work exactly?  Wouldn't the connection from DI to the IFileInfo still mess things up?  DI happens (in this case) at startup whereas the IFileProvider/IFileInfo methods are called per request.  Trying to use the DI version of the DbContext would cause the same issue as before, wouldn't it?

**Comment by rowanmiller** [comment]
Hey,

I was suggesting getting the options from DI in Startup - options are singleton and are shared by all context instances. Then manually create a context instance outside of DI using the options you got in Startup. The only advantage this gives is that still have a single point to setup the options.

~Rowan

**Comment by hauteur** [comment]
That makes perfect sense. Thank you so much. It will be Monday before I can try
it out, but I'm hopeful that will work.

Thanks,
Mike

On Fri, Feb 12, 2016 at 4:13 PM, Rowan Miller < notifications@github.com [notifications@github.com] > wrote:
Hey,

I was suggesting getting the options from DI in Startup - options are singleton
and are shared by all context instances. Then manually create a context instance
outside of DI using the options you got in Startup. The only advantage this
gives is that still have a single point to setup the options.

~Rowan

—
Reply to this email directly or view it on GitHub
[https://github.com/aspnet/EntityFramework/issues/4544#issuecomment-183507596] .[https://github.com/notifications/beacon/AQZ1BMc7nUxjEMOPNj-uRoUFSYdBfrqEks5pjlB3gaJpZM4HZIIK.gif]

**Comment by hauteur** [comment]
That did work.  Of course, it would be better if there was a way to do it in IFileProvider, but hey...  At least this works.  Thanks for your help.

**Comment by rowanmiller** [comment]
@hauteur no problem. Feel free to open a new issue in https://github.com/aspnet/StaticFiles to look at the architecture of those components and how to get a hold of request services in you `IFileProvider`.

**Comment by neooleg** [comment]
Apologize if I missing something, but it seems there is no clear answer for initial question -- accessing DB from another thread.

Could you pls clarify how it this possible?

I assumed, that it's possible to pass DbContextOptions into a thread, but @rowanmiller stated
> Since DbContextOptions is singleton

It means it can not be read from another thread safely (ASP.NET can reread it on config change).

**Comment by ajcvickers** [comment]
@neooleg In 2.0.0, DbContextOptions is registered by default as scoped. In 1.1.x it is registered by default as singleton.
