### ISSUE TITLE
EF Commands

### ISSUE THREAD

**Issue by dneimke** [dotnet/efcore#4555]
is it possible to run EF Commands again ? e.g. is there a dotnet CLI version of the EF commands that we can run?

**Comment by gdoron** [comment]
#4406

**Comment by bricelam** [comment]
They should be usable (but not throughly tested) now. Add the following to your `project.json`
```JSON
{
  "tools": {
    "dotnet-ef": "1.0.0-*"
  }
}
```
Then restore, build, and use the tool just like you did `dnx ef`
```cmd
cd src\MyProject
dotnet restore
dotnet build
dotnet ef dbcontext list
```

**Comment by bricelam** [comment]
Closing. Use #3925 to track further progress of the commands.

**Comment by dneimke** [comment]
Thanks!

**Comment by capesean** [comment]
I get `No executable found matching command "dotnet-ef"`

Am I missing something?

**Comment by bricelam** [comment]
Did you run `dotnet restore` first? Are you in the directory containing the `project.json`?

**Comment by capesean** [comment]
Trying it in an "empty" project I now get `Failed to initialize CoreCLR`m after running `dotnet restore` successfully. 

project.json is:
`````
{
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.AspNetCore.Hosting": "1.0.0-*",
    "Microsoft.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
  },
  "commands": {
      "ef": "EntityFrameworkCore.Commands"
  },
  "frameworks": {
    "net451": { }
  },
  "tools": {
    "dotnet-ef": "1.0.0-*"
  }
}
`````
