### ISSUE TITLE
Problems with updating db relations. The instance of entity type cannot be tracked because another instance of this type with the same key is already being tracked.

### ISSUE THREAD

**Issue by piotrek-k** [dotnet/efcore#4557]
I'm currently trying to update some related data in my database. [I've descrived it accurately here](http://stackoverflow.com/questions/35379166/how-to-update-many-to-many-relationship-in-entity-framework-7), but well, no answers yet. Since the docs [looks rather empty](http://ef.readthedocs.org/en/latest/saving/related-data.html) I'm not sure if I'm using it correctly. As far as I remember, this way worked quite well on previous versions of EF, so maybe it's a bug?

As I mentioned before,[ I've described it already on StackOverflow](http://stackoverflow.com/questions/35379166/how-to-update-many-to-many-relationship-in-entity-framework-7), but see my entire function that I use:

``` csharp
[HttpPut("{id}")]
        public IActionResult PutNote(int id, [FromBody] Note note)
        {
            if (!ModelState.IsValid)
            {
                return HttpBadRequest(ModelState);
            }

            if (id != note.NoteId)
            {
                return HttpBadRequest();
            }

            try
            {

                if (note.TagsToAdd != "" && note.TagsToAdd != null && note.TagsToAdd != note.TagsAsSingleString)
                {
                    var dbNote = db.Notes.Include(x=>x.NoteTags).ThenInclude(x=>x.Tag).FirstOrDefault(x => x.NoteId == note.NoteId);
                    dbNote.NoteTags.Clear();
                    dbNote.NoteTags = TagsToAddToTags(note).NoteTags;
                }
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NoteExists(id))
                {
                    return HttpNotFound();
                }
                else
                {
                    throw;
                }
            }
            catch (Exception e)
            {
                Trace.WriteLine(e);
            }

            return new HttpStatusCodeResult(StatusCodes.Status204NoContent);
        }
```

The error from title appeares in the second "catch". 
Error:

> System.InvalidOperationException: The instance of entity type 'ConsoleNotepad.Models.NoteTag' cannot be tracked because another instance of this type with the same key is already being tracked. For new entities consider using an IIdentityGenerator to generate unique key values.

TagsToAddToTags function:

``` csharp
//it converts tags provided by user as a string, to tags as c# objects
public Note TagsToAddToTags(Note note)
        {
            string[] separators = { " " };
            List<string> tags = note.TagsToAdd.Split(separators, StringSplitOptions.RemoveEmptyEntries).ToList();
            note.NoteTags = new List<NoteTag>();
            note.TooManySpecialTags = false;
            foreach (var t in tags)
            {
                Tag tagInDb = db.Tags.FirstOrDefault(x => x.Name == t);

                if (tagInDb == null)
                {
                    tagInDb = db.Tags.Add(new Tag { Name = t }).Entity;
                }

                note.NoteTags.Add(new NoteTag { Tag = tagInDb});
            }

            return note;
        }
```

**Comment by rowanmiller** [comment]
As the error suggests, you are ending up with two entity instances that represent the same NoteTag. The problem is that you query for all NoteTags from the database, then you also add all the incoming ones - and there are presumably some duplicates.

I would handle this by querying from the database, comparing the loaded NoteTags to the incomings ones, and then adding the new ones and removing the deleted ones.
