### ISSUE TITLE
Passing an open transaction/connection to a new context

### ISSUE THREAD

**Issue by umu24013** [dotnet/efcore#4559]
How can I encapsulate context A and context B into a single transaction?

```
void SomeMethod()
{
  ...
  using (var contextA = new DBContext())
  {
    ...
    contextA.SaveChanges();
  }

  using (var contextB = new DBContext())
  {
    ...
    contextB.SaveChanges();
  }
  ...
}
```

In EF6 there was a special constructor `DbContext(DbConnection existingConnection, bool contextOwnsConnection)` that could have been used to do the trick.

Actually, we are recreating the same context in a foreach loop like this:

```
// best (so far) experimental value of 60 items per commit. 780,000 items total.
int maxItemsPerCommit = 60;

foreach (var batch in users.Page(maxItemsPerCommit))

// we recreate the context for each 60 items (batch) to release the pressure
// on the changetracker from too many items attached to it at once. This greatly speeds up
// the insertion of too many items.
   using (var db = new DBContext())
    {
      db.Users.AddRange(batch);
      db.SaveChanges();
    }
```

Is there a chance we can do this within a single RelationalTransaction?
FYI we are using MicrosoftSqlServer.

**Comment by rowanmiller** [comment]
There is an overload of `UseSqlServer` that takes a DbConnection... so you can have a context like this, that allows passing in an existing connection.

```c#
public partial class TestContext : DbContext
{
    private DbConnection _connection;

    public TestContext(DbConnection connection)
    {
        _connection = connection;
    }

    public virtual DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options.UseSqlServer(_connection);
    }
}
```

There is also a `DbContext.Database.UseTransaction()` API to allow you to enlist in an existing transaction.
