### ISSUE TITLE
error creating migration

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#4564]
I have a db context, and I want to add support for tracking the user that added, modified and virtually deleted the record. To to this I added to the class the required properties

```
public interface ILoggedTable
{
    int UtenteCreazioneId { get; set; }
    DateTime CreazioneTs{ get; set; }
    Utente UtenteCreazione { get; set; }
    int ?UtenteModificaId { get; set; }
    DateTime ?ModificaTs{ get; set; }
    Utente UtenteModifica { get; set; }
    int? UtenteCancellazioneId { get; set; }
    DateTime ?CancellazioneTs{ get; set; }
    Utente UtenteCancellazione { get; set; }
}

```

This implies that in the user entity I'll have 3 collections of entity has been deleted,added, modfied by the user, for every table. To avoid this I would like to group these navigation properties in a generic class this way:

```
public class LoggedTableRevProps<T> where T : class
{
    public virtual ICollection<T> Creati { get; set; }
    public virtual ICollection<T> Modificati { get; set; }
    public virtual ICollection<T> Cancellati { get; set; }

    public LoggedTableRevProps() {
        Creati = new HashSet<T>();
        Modificati = new HashSet<T>();
        Cancellati = new HashSet<T>();
    }
}
```

And in the OnModelCreating I use

```
entity.HasOne(d => d.UtenteCreazione).WithMany(p => p.UtentiLogProps.Creati).HasForeignKey(d => d.UtenteCreazioneId).OnDelete(DeleteBehavior.Restrict);
entity.HasOne(d => d.UtenteModifica).WithMany(p => p.UtentiLogProps.Modificati).HasForeignKey(d => d.UtenteModificaId).OnDelete(DeleteBehavior.Restrict);
entity.HasOne(d => d.UtenteCancellazione).WithMany(p => p.UtentiLogProps.Cancellati).HasForeignKey(d => d.UtenteCancellazioneId).OnDelete(DeleteBehavior.Restrict);

```

It compiles , but when I try to create the migration I obtain this error message

The expression 'p => p.UtentiLogProps.Creati' is not a valid property expression. The expression should represent a property access: 't => t.MyProperty'.
Nome parametro: propertyAccessExpression

[Sources](https://dl.dropboxusercontent.com/u/19486794/AspNet5Apps.zip)

**Comment by rowanmiller** [comment]
Thanks for sharing the code, turns out this is actually #246 that you want (sorry for the runaround on that one). Properties (both scalar and navigation) need to be defined on the entity and can not be nested. So it's this piece of code that is causing the error `WithMany(p => p.UtentiLogProps.Creati)`, since this is referencing a property not directly on the type.
