### ISSUE TITLE
IdentityDbContext Migration problem

### ISSUE THREAD

**Issue by Burgyn** [dotnet/efcore#4567]
Hi,
I have problem with DbContext, which is derived from **IdentityDbContext**.
When I add new migration, then in this migration (by my opinion) are generated senseless commands:

```
migrationBuilder.DropForeignKey(name: "FK_IdentityRoleClaim<string>_IdentityRole_RoleId", table: "AspNetRoleClaims");
migrationBuilder.DropForeignKey(name: "FK_IdentityUserClaim<string>_ApplicationUser_UserId", table: "AspNetUserClaims");
migrationBuilder.DropForeignKey(name: "FK_IdentityUserLogin<string>_ApplicationUser_UserId", table: "AspNetUserLogins");
migrationBuilder.DropForeignKey(name: "FK_IdentityUserRole<string>_IdentityRole_RoleId", table: "AspNetUserRoles");
migrationBuilder.DropForeignKey(name: "FK_IdentityUserRole<string>_ApplicationUser_UserId", table: "AspNetUserRoles");
```

Steps to reproduce:
1. Create new ASP.NET 5 Web application by template
2. Add new model class Room
3. Add `public DbSet<Room> Rooms { get; set; }` property to `ApplicationDbContext`
4. run `dnx ef migrations add AddRooms` command

I'm doing something wrong? Or it is a bug?

**Comment by gdoron** [comment]
Every migration in EF 7 will drop **all** Foreign Keys at the beginning of the migration scripts and will add them back in the end.

It's not specific to Identity, add a FK of your own and see for yourself.

I believe they designed it this way so when you're doing migrations you'll never have constraints that limit you from doing the change you want.

**Comment by smitpatel** [comment]
It is not specific to identity. But bug in EF. See #3751
It was fixed in #3756 & #4349

**Comment by gdoron** [comment]
@smitpatel  Good to know it's a bug, because I didn't like the _feature_ :)

**Comment by Burgyn** [comment]
Thank you for clarification.
