### ISSUE TITLE
Migrations: multiple datacontexts subfolder generation

### ISSUE THREAD

**Issue by bartlannoeye** [dotnet/efcore#4568]
In my UWP application I have multiple DbContexts. I'm able to generate the migrations for each context:

```
Add-Migration Bookings -c BookingsContext
Add-Migration Config -c  ConfigurationContext
```

However the first migration is added right under the Migrations folder and the second is added in a subfolder. Deleting the first one and re-adding it, adds it under the root again.

![image](https://cloud.githubusercontent.com/assets/5115577/13059232/feebce3a-d428-11e5-925a-202e5b4317f7.png)

I would like to see a consistent behavior when generating migrations for multiple DbContexts and since we specify the context in both commands, I suppose that would be a subfolder for both.

**Comment by bricelam** [comment]
Move the last migration where you want it to be and the tool should follow suit. :wink:

**Comment by rowanmiller** [comment]
Our rules are "try to put things directly into the migrations folder, unless there is something for another model there already - in which case we create a sub folder". As @bricelam mentioned you can just move things around though and migrations will put the next migration wherever the last one is.

We did discuss always having subfolders, but decided we did not want to complicate the single-context scenario.

**Comment by bartlannoeye** [comment]
With the single-context scenario you'd probably not use the -c parameter, so that might be a decision point to decide on using a subfolder or not?

Anyway, thanks for the feedback !
