### ISSUE TITLE
Database migration on Azure returns 500

### ISSUE THREAD

**Issue by deherle** [dotnet/efcore#4570]
Hi,

I have an MVC 5/EF 7 app I'm trying to deploy to Azure from VS 2015 using RC1.  It works fine locally, but bombs when trying to publish to Azure web app + sql database.  

I've broken out the data context into a separate class library, and am pointing to that library using .MigrationsAsembly().  I also have a separate Startup.cs in that class library.  My connection string is the DefaultConnection picked up from the Azure web app.

I'm seeing this error after catching the exception and returning via browser (without that, the 500 error is hidden):

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 52 - Unable to locate a Local Database Runtime installation. Verify that SQL Server Express is properly installed and that the Local Database Runtime feature is enabled.)

which suggests EF is trying to connect/migrate to the debug database I have locally.  Ideas?

**Comment by rowanmiller** [comment]
@deherle how are you overriding the connection string when you publish?

**Comment by deherle** [comment]
Hi Rowan, I figured this out...  the connection string was indeed wrong.  I overwrote it manually in appsettings.json with the Azure connection string.

I was convinced the connection string ("DefaultConnection") was being overwritten properly via the Azure web app - I was returning it in my exception handler via the browser, and it was the right one but for some reason this wasn't honored...

services.AddEntityFramework()
                    .AddSqlServer()
                    .AddDbContext<ApplicationDbContext>(options =>
                        options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]).MigrationsAssembly("TeamBuilder.Data"));

Not sure what I was doing wrong...

**Comment by rowanmiller** [comment]
Glad you got it sorted :smile:

**Comment by abettadapur** [comment]
@deherle What did you end up changing to get it to work? I'm also having this issue
