### ISSUE TITLE
Make Testing framework available via Nuget

### ISSUE THREAD

**Issue by meikeric** [dotnet/efcore#4571]
We're developing a drag and drop system for designing and building SQL Server objects. We are using a good bit of the low level Entity Framework Migrations Builder classes for SQL server code generation.

Because of this code re-use, we'd like to be able to use some of the existing EF testing infrastructure.

Can the EF7 Testing classes be made available in Nuget? For example, I was unable to find "MigrationSqlGeneratorTestBase".

**Comment by ErikEJ** [comment]
Most of the base test component are available on myget, or you can copy and paste from the source

**Comment by rowanmiller** [comment]
**EF Team Triage:** Discussed and concluded that for unit test code it would be better just to copy the code. Unit tests have very minimal infrastructure, so we tend not to share things much.
