### ISSUE TITLE
Embrace the .NET Platform Standard (stop cross-compiling)

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#4578]
We currently cross-compile to `net451` for three reasons:
- To throw on ambient System.Transactions
- To throw when data binding to DbSet on WinForms (via IListSource)
- For better (but imperfect) compile-time Mono compatibility checking

Personally, I believe the value of producing a single, portable, [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) assembly outweighs all of these.

**Comment by bricelam** [comment]
The minimum version of .NET Framework that we need to support is 4.5.2 (for parts of Azure). This means the maximum version of .NET Platform Standard that we can use is 1.2.

The last time I investigated downgrading our .NET Platform Standard, I found that Caching used `AsyncLocal` which requires version 1.3 or higher.

**Comment by ErikEJ** [comment]
Does that mean that the 4.5.1 based sqlce provider must be changed to require 4.5.2?

**Comment by bricelam** [comment]
For now, we'll keep cross-compiling to `net451` and `netstandard1.3`. If our dependencies change in the future, we'll reevaluate.

**Comment by bricelam** [comment]
Reopening. @pranavkm did a bunch of work for aspnet/Universe#315 that would help with this. I also failed to realize that just because some of our dependencies cross-compile, that doesn't me we have to.
