### ISSUE TITLE
[EFCore] How to migration?

### ISSUE THREAD

**Issue by alfadb** [dotnet/efcore#4580]
In EF7, we can use 'dnx ef migrations add xx'. 
But in EF Core, I get a message: 'Microsoft.EntityFrameworkCore.Commands' does not contain a 'Program' type suitable for an entry point

**Comment by bricelam** [comment]
The nightly builds are transitioning to the .NET Core CLI. DNX will no longer work. I recommend using RC1 until RC2 is released.

**Comment by rowanmiller** [comment]
Work is already tracked by https://github.com/aspnet/EntityFramework/issues/3925

**Comment by alfadb** [comment]
Thanks!
