### ISSUE TITLE
Specify Principal Or Dependent - One To One Relationship

### ISSUE THREAD

**Issue by marcels2204** [dotnet/efcore#4585]
How to specify the dependent or principal without explicit foreign key property?

```
    public class Artikel
    {
        public int Id { get; set; }
        public string Bezeichnung { get; set; }

        public Ressource Ressource { get; set; }
    }

    public class Ressource
    {
        public int Id { get; set; }
        public string Bezeichnung { get; set; }

        public Artikel Artikel { get; set; }
    }
```

**Comment by rowanmiller** [comment]
You need to create a shadow state property to use as the FK (what EF does under the covers when it can work out which one is the dependent, but there is no FK property).

```c#
modelBuilder.Entity<Resource>()
    .Property<int>("ArtikelId");

modelBuilder.Entity<Resource>()
    .HasOne(r => r.Artikel)
    .WithOne(a => a.Ressource)
    .HasForeignKey<Resource>("ArtikelId");
```

**Comment by marcels2204** [comment]
I'm using EF Core 1 RC.

I would not have an explicit foreign key property in the entity class and not in the resulting SQL Server table.

I would like to specify the dependent object. The Primary Key of the dependent must be also the Foreign Key to the principal.

**Comment by rowanmiller** [comment]
@marcels2204 you can use the HasForeignKey call to let EF know to use the PK as the FK:

```c#
modelBuilder.Entity<Resource>()
    .HasOne(r => r.Artikel)
    .WithOne(a => a.Ressource)
    .HasForeignKey<Resource>(r => r.Id);
```

**Comment by marcels2204** [comment]
It's a One to One Relationship. I used HasForeignKey to use the PK also as the FK. But now there is also a Foreign Key Property in the Principal Table?!

**Comment by rowanmiller** [comment]
@marcels2204 here is some code that I was using to try and reproduce the issue you are seeing.

```c#
using Microsoft.Data.Entity;

namespace Console.CI
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }
        }
    }

    class MyContext : DbContext
    {
        public DbSet<Artikel> Artikel { get; set; }
        public DbSet<Ressource> Ressource { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Ressource>()
                .HasOne(r => r.Artikel)
                .WithOne(a => a.Ressource)
                .HasForeignKey<Ressource>(r => r.Id);
        }
    }

    public class Artikel
    {
        public int Id { get; set; }
        public string Bezeichnung { get; set; }

        public Ressource Ressource { get; set; }
    }

    public class Ressource
    {
        public int Id { get; set; }
        public string Bezeichnung { get; set; }

        public Artikel Artikel { get; set; }
    }
}
```

But this results in `Ressource.Id` correctly being used as the foreign key.

<img width="231" alt="schema" src="https://cloud.githubusercontent.com/assets/4741851/13227297/ca954b30-d94a-11e5-88bb-a71e9d97175b.png">

Can you adjust the above code to demonstrate the issue you are seeing?

**Comment by marcels2204** [comment]
i've used the generic Version of HasOne: .HasOne<Artikel>

**Comment by rowanmiller** [comment]
@marcels2204 The code I shared uses the generic version too, it's just inferred from the navigation property I specified. Do you mean you are using the parameter-less overload (i.e. `.HasOne<Artikel>()`)? If so, that would explain the issue. The empty method call tells EF that there is a "one of the relationship" there, but there is no navigation property. Given this, `Ressource.Artikel` is not part of the relationship being configured, and therefore represents a second relationship - hence the additional foreign key.

**Comment by marcels2204** [comment]
Yes, i'm used the parameter-less overload.
