### ISSUE TITLE
ToEntityEntry 

### ISSUE THREAD

**Issue by meikeric** [dotnet/efcore#4590]
I realize this is an edge use case, but none the less, it is one I am up against.

I am writing a custom dynamic entity tracker/state manager, essentially a dynamic JSON Object -> database implementation. It leverages EntityFramework 7 since you guys have done the heavy lifting.  However, I've run into an issue which requires a concrete implementation of EntityEntry instead of an interface which ends up being tightly coupling some pieces because of one interface method: 

"src/Microsoft.EntityFrameworkCore/Update/IUpdateEntry.cs" requires "ToEntityEntry()" for "Microsoft.EntityFrameworkCore/DbUpdateException.cs".

Can DbUpdateException rely on IUpdateEntity instead of EntityEntry, thus removing the need for the concrete implementation of EntityEntry and ToEntityEntry?

EntityEntry is pretty heavy and to have to write a decent amount of code to return a new EntityEntry via ToEntityEntry just for an exception message seems extreme.  It's declared once in IUpdateEntry.cs, it's implemented once in InternalEntityEntry.cs, and it's invoked once in DbUpdateException.cs.  I can't find **anywhere** in the repo that DbUpdateException.Entries is used, therefore I don't foresee an impact.

EDIT: Looking through the code, I don't see why a few changes wouldn't resolve the tight coupling.

Line 20:
`private readonly LazyRef<IReadOnlyList<EntityEntry>> _entries;`
becomes
`private readonly LazyRef<IReadOnlyList<IUpdateEntry>> _entries;`

Line 30:
`_entries = new LazyRef<IReadOnlyList<EntityEntry>>(() => new List<EntityEntry>());`
becomes
`_entries = new LazyRef<IReadOnlyList<IUpdateEntry>>(() => new List<IUpdateEntry>());`

Line 59:
`_entries = new LazyRef<IReadOnlyList<EntityEntry>>(() => entries.Select(e => e.ToEntityEntry()).ToList());`
becomes
`_entries = new LazyRef<IReadOnlyList<IUpdateEntry>>(entries);`

Line 66:
`public virtual IReadOnlyList<EntityEntry> Entries => _entries.Value;`
become
`public virtual IReadOnlyList<IUpdateEntry> Entries => _entries.Value;`

**Comment by meikeric** [comment]
I went ahead and created a pull request. https://github.com/aspnet/EntityFramework/pull/4592

**Comment by rowanmiller** [comment]
`DbUpdateException.Entries` is used by application code when it needs to resolve a database exception. For example, if there is a concurrency exception, then it can use the data and operations from `EntityEntry` to show the user the different values and allow them to resolve the issues.

`IUpdateEntry` is the API designed for database providers to persist changes to the database. 

Given these two APIs are designed for completely different audiences it does not make sense to change them.

**Comment by meikeric** [comment]
Rowan, before you close this, I'd like to discuss. Can you give me 48 hours to articulate my argument regarding this?

**Comment by rowanmiller** [comment]
@meikeric sure. The important thing to keep in mind is that `DbUpdateException` is designed to be useful to developers catching it in applications - therefore it needs to be optimized for usability/helpfulness.

**Comment by divega** [comment]
@meikeric One suggestion that comes to mind is that you try to find a different way to remove the coupling you have found. We need to expose entity entries here. IUpdateEntry just doesn't make any sense for this.

**Comment by rowanmiller** [comment]
Closing as we have not heard back. Feel free to reply if you want to follow up, we still track comment on closed issues.
