### ISSUE TITLE
Cast a short to enum raised an exception.

### ISSUE THREAD

**Issue by sumtec** [dotnet/efcore#4593]
It's in 7.0.0-rc1-final. Not sure if any one reported this before or it was fixed in rc2.

``` csharp
var query = from partsList in db.PartsList
    select new { Status = (PartsListStatus)partsList.PartsListStateId }; // PartsList.PartsListStateId : short
var result = query.ToList();

public enum PartsListStatus  // this doesn't work.
{
    //...
}

// but this works
public enum PartsListStatus : short 
{
    //...
}
```

A "short -> int -> enum:int" casting should work without any problem but now raise exception like this:

```
InvalidCastException: Specified cast is not valid.
lambda_method(Closure , Object[] )
Microsoft.Data.Entity.Storage.Internal.UntypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
ASPNET5.Controllers.PartsListController.GetListByBodyShopId(Int32 bodyShopId) in PartsListController.cs
                return (from item in query.ToList()
...

```

**Comment by mikary** [comment]
This behavior is actually consistent with the behavior of Linq-to-objects.

For example, the expression in the following sample will throw:
```cs
    public enum TestEnum
    {
        First,
        Second
    }

    class Program
    {
        static void Main(string[] args)
        {
            var value = new object[] { (short)0 };

            try
            {
                var result = value.Select(p => (TestEnum)p).ToList();
            }
            catch (InvalidCastException ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
```
The exception is actually the result of casting a `short` to an `int` type. As a work around, you can use `Convert.ToInt32` as in the following:
```cs
    public enum TestEnum
    {
        First,
        Second
    }

    class Program
    {
        static void Main(string[] args)
        {
            var value = new object[] { (short)0 };

            var result = value.Select(p => (TestEnum)Convert.ToInt32(p)).ToList();
        }
    }
```

**Comment by mikary** [comment]
While investigating the original issue, I did note that this exception is not thrown when using the InMemory provider, which may mean it is accommodating for the conversion when it shouldn't.

**Comment by sumtec** [comment]
Hi @mikary,

I think it is not a good idea to think that it should always consistent with the Linq2Object. If you are going to that way, I'd like to show you something which is and should inconsistent nowadays:

``` csharp
var query = from item in db.Users // It will match in Linq2EF, but not in Linq2Object
    where item.UserName == "upper case in database" // in database: 'UPPER CASE IN DATABASE'
    select item;

var query = from item in db.Users // it will return empty list in Linq2EF but through exception in Linq2Object
    where item.UserName.Contains("actually null in database")  // in database: NULL
    select item;
```

And if you are correct that the Linq2Object will raise exception, I would rather think that there is a bug in the Linq2Object. However, I believe it's not the case and maybe you used an example not equivalent to my issue. And these piece of code can actually be compiled and run without a problem, and it's much closer to my original issue I thought:

``` csharp
using System;
using System.Linq;

namespace ConsoleApplication1
{
    class Program
    {

        public enum TestEnum
        {
            Value = 1
        }

        public class Entity
        {
            public short Value;
        }

        static void Main(string[] args)
        {
            short value = 1;
            TestEnum test = (TestEnum)value;

            var list = new[] { new Entity { Value = 1 } };

            try
            {
                var result = list.Select(item => (TestEnum)item.Value); // PLEASE NOTE that the Value is "short", not "object".
                Console.WriteLine("Succeeded!");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Failed with: " + ex.ToString());
            }
            Console.ReadLine();
        }
    }
}
```

I have to say that, even if the above example is not the case, when talking about the database, we will have a different way of thinking. We expect it to be translated in SQL and do something for us when trying to project the result to an object. 

And also, in the real world, people create crappy source code and I have to use that. For example, the DBA wants to save a bit space and make that field to short. And the library programmer is just too lazy to put an short after the enum. And If I can't do anything about the enum class, I'll have to do some dirty job which is not funny at all. Yes, it might be as simple as "(SomeEnum)(short)item.Field" but why I need to if it's actually not a problem?

Cheers,
Frank.

**Comment by rowanmiller** [comment]
**Team Triage:** In general out LINQ implementation begins as LINQ to Objects and then picks pieces of the query to push to the underlying database. This does mean that some of pieces may evaluate a little differently than L2O due to database semantics. At the same time, we don't want to make the query pipeline even more complex in order to refine how things happen in memory. Given that (and that there is an easy tweak to the query to make it work) we are not planning to change this.
