### ISSUE TITLE
DateTime columns Conversion failed when converting date and/or time from character string

### ISSUE THREAD

**Issue by lordofscripts** [dotnet/efcore#4600]
I am using Code First Migrations (duh!) on Visual Studio 2015 for .NET 4.5 and EF 6.1.3. I am trying to add a (new) DateTime column to the table using a DEFAULT value because it is a REQUIRED field and therefore NOT NULLABLE.

It generated this which was not suitable because  it is REQUIRED and therefore I need to set a default value:
`AddColumn("dbo.AspNetUsers", "MemberSince", c => c.DateTime(nullable: false));`

Because it is a required field it cannot be nullable and it must have a value. Therefore I used the defaultValue parameter as follows:

`AddColumn("dbo.AspNetUsers", "MemberSince", c => c.DateTime(nullable: false, defaultValue: DateTime.Now));`

But when I execute the Update-Database statement on the Package Manager I get this error:

_DateTime columns failed when coverting date and/or time from character string. The statement has been terminated._

First I don't see why it says "from character string" because DateTime.Now returns DateTime not string. If I append .ToShortDateTimeString() then I get a compilation error

**So as far as I can see there is an error with the handling of DateTime default values in EF Code First Migrations**.

**Comment by anpete** [comment]
@lordofscripts You could try using defaultValueSql as a workaround.

**Comment by rowanmiller** [comment]
@lordofscripts this repo is for EF Core, EF6.x is managed on CodePlex - http://entityframework.codeplex.com/. Could you open an issue over there and include the following info:

* What version of SQL Server are you using?
* Run the `Update-Database` command with the `-verbose` parameter and include the SQL that is being sent to the database.

I was not able to reproduce this with LocalDB v12 and EF6.1.3.

**Comment by Sholofly** [comment]
I think you want to set de default value to the moment you create the record. Then use 
defaultValueSql: "GETDATE()". 
If not, use 

defaultValueSql:'yyyy-MM-dd HH:mm:ss' with the desired date.
