### ISSUE TITLE
Proposal: make UserStore.ThrowIfDispose protected

### ISSUE THREAD

**Issue by sumtec** [dotnet/efcore#4607]
Hi,

Is it possible to make ThrowIfDispose in the UserStore<> protected? I am trying to make it work for a legacy database and I have to write my own UserStore to enable login. When trying to implementing the UserStore class, I found no way to call the ThrowIfDispose.

I need to query different table to get a wrapped IdentityUser object. So, I can't call the FindByName in the base class directly. Or, any other advice other than implementing my own UserStore class?

Thanks,
Frank

**Comment by divega** [comment]
This issue was moved to aspnet/Identity#750
