### ISSUE TITLE
Build initialize fails with latest source

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#4612]
dotnet does not seem to understand: 
**error: Unrecognized option '--parallel'**
**fail: Exit code 1 from dotnet**

Package "Sake.0.2.2" is already installed.
Package "xunit.runner.console.2.1.0" is already installed.
dotnet_install: Preparing to install .NET Tools to C:\Users\eejj\AppData\Local\M
icrosoft\dotnet
dotnet_install: Latest version: 1.0.1.001579
dotnet_install: Local Version: 1.0.0.000943
dotnet_install: Downloading dotnet-win-x64.latest.zip from https://dotnetcli.blo
b.core.windows.net/dotnet/dev/Binaries/Latest
dotnet_install: Extracting zip
dotnet_install: The .NET Tools have been installed to C:\Users\eejj\AppData\Loca
l\Microsoft\dotnet\cli!
dotnet_install: Add 'C:\Users\eejj\AppData\Local\Microsoft\dotnet\cli\bin' to yo
ur PATH to use dotnet
Adding C:\Users\eejj\AppData\Local\Microsoft\dotnet\cli\bin to PATH
Setting DOTNET_HOME to C:\Users\eejj\AppData\Local\Microsoft\dotnet\cli
Determining latest version
Downloading dnx-coreclr-win-x86.1.0.0-rc2-16541 from https://www.myget.org/F/asp
netcidev/api/v2
Installing to C:\Users\eejj.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc2-16541
Adding C:\Users\eejj.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc2-16541\bin to pr
ocess PATH
Compiling native images for dnx-coreclr-win-x86.1.0.0-rc2-16541 to improve start
up performance...
Finished native image compilation.
Updating alias 'default' to 'dnx-coreclr-win-x86.1.0.0-rc2-16541'
Downloading dnx-clr-win-x86.1.0.0-rc2-16541 from https://www.myget.org/F/aspnetc
idev/api/v2
Installing to C:\Users\eejj.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16541
Adding C:\Users\eejj.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16541\bin to proces
s PATH
Native image generation (ngen) is skipped. Include -Ngen switch to turn on nativ
e image generation to improve application startup time.
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc2-16541'
Using makefile: makefile.shade
info: Exec
info:   program: dotnet
info:   commandline: restore  --parallel
info:   workingdir: C:\Code\EntityFramework
Specify --help for a list of available options and commands.
error: Unrecognized option '--parallel'
fail: Exit code 1 from dotnet
fail: Stack trace:
   at View914a8de3fead4cf1b67102a296154077.<RenderViewLevel0>b__ab() in c:\Users
\eejj\AppData\Local\Temp\b1e0c3e993ba45fea4302c029c0a6ea3-1.cs:line 9431
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View914a8de3fead4cf1b67102a296154077.StartingTarget(String name) in c:\Use
rs\eejj\AppData\Local\Temp\b1e0c3e993ba45fea4302c029c0a6ea3-1.cs:line 3341

**Comment by rowanmiller** [comment]
@ErikEJ can you try cleaning your repo and trying again

**Comment by ErikEJ** [comment]
Thanks, that fixed it
