### ISSUE TITLE
Migrations error page, allow credentials to be supplied for apply migrations

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#4634]
I have just deployed my ASP.NET 5 application, and it tries to apply migrations on startup - I get this handy error page:

![image](https://cloud.githubusercontent.com/assets/3176632/13287589/b4486af4-daff-11e5-9698-f3f8b6863296.png)

It would be great if, when running on "https", this screen gave you the chance to enter the username and password of an account that has sufficient permissions to run migrations, before clicking the Apply Migrations button.

At the moment, we use trusted security in the connection string, and the app pool account for the website doesn't have necessery permissions to create databases etc. We ideally don't want to change this, but at the point of running migrations it would be great if we could specify some one-time credentials on this page to apply the migrations with.

**Comment by rowanmiller** [comment]
@dazinator this really isn't something you should be running in a production/deployed application. It is only designed to help with the "code, run, repeat" developer loop. I'm assuming you modified the default template to get the page to show up in a deployed app? Or set the environment variable to make ASP.NET think it's running in development environment?

**Comment by dazinator** [comment]
@Rowan, I see. 

Our team works locally and then when we check in, we have continuos deployment process that ensures the latest build of the application is deployed to our "Development" environment. This a seperate environment that always has the latest build of the application deployed - its not a "production" environment, and so this screen does appear on that environment and it does come in handy on the occasion that there are issues with a migration that a developer has checked in - as it allows us to see the problem and try and "re-apply" the migrations. (Although if they failed the first time they will generally always fail).

I guess I was looking at the "Apply Migrations" button in that context, in that, where we most often see issues with migrations is around permissions. Using this screen would allow and dirty resolution to that issue, but only if it allowed credentials to be supplied. Thinking on it more though you are right, we should instead fix the deployment process so that the migration is applied correctly during the deployment or the permissions are fixed so that we don't see this screen at all.

**Comment by rowanmiller** [comment]
> Thinking on it more though you are right, we should instead fix the deployment process so that the migration is applied correctly during the deployment or the permissions are fixed so that we don't see this screen at all. 

Agreed. If you find things that we could improve when you are setting this up then please let us know :smile:
