### ISSUE TITLE
There is already an object named 'PK_HistoryRow' in the database.

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#4636]
Hello,

I tryied to change the __EFMigrationsHistory table name using:

```
public class Context : DbContext {
  protected override void OnModelCreating(ModelBuilder builder) {
      builder.Entity<HistoryRow>(x => {
        x.ToTable("Migrations");
        x.HasKey(y => y.MigrationId);
        x.Property(y => y.MigrationId).HasMaxLength(150).ValueGeneratedNever();
        x.Property(y => y.ProductVersion).IsRequired().HasMaxLength(32);
      });
      base.OnModelCreating(builder);
  }
```

   }

I am able to create the migration I get the following:

```
public partial class FirstMigration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Migrations",
            columns: table => new
            {
                MigrationId = table.Column<string>(nullable: false),
                ProductVersion = table.Column<string>(nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_HistoryRow", x => x.MigrationId);
            });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("Migrations");
    }
}    
```

When I apply it to the database I get the "__EFMigrationsHistory" table and the error:

```
There is already an object named 'PK_HistoryRow' in the database.
Could not create constraint or index.
```

Is this a bug? What am I missing? 

How can the name of __EFMigrationsHistory table be changed?

Thank You,
Miguel

**Comment by rowanmiller** [comment]
(@"Server=(localdb)\mssqllocaldb;Initial Catalog=Sample;Trusted_Connection=TrueThis is not how you would change the migrations history table, by adding it to your own model you are effectively introducing a new entity that conflicts with the table the migrations uses under the covers. 

You can change the name of the table in OnConfiguring (or in Startup.cs if you are using ASP.NET Core):

```c#
optionsBuilder.UseSqlServer(@"<connection string>")
    .MigrationsHistoryTable("MyTable", schema: "MySchema")
```

For any more significant customization, you would need to look at overriding the [HistoryRepository](
https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Migrations/HistoryRepository.cs)
