### ISSUE TITLE
Column name with underscore

### ISSUE THREAD

**Issue by jerry2007** [dotnet/efcore#4644]
Hello,
I have column in DB called 'Attachment_ID'
Column name with underscore.

In Beta 8 everything was good.
But in RC1-Final EF throw excpetions Column Name 'AttachmentId' was not found.
EF translate Attachment_ID from object model to AttachmentId column in sql.

Could you help me?

**Comment by gdoron** [comment]
@jerry2007  can you share your model, `OnModelCreating` and migrations?

**Comment by jerry2007** [comment]
`modelBuilder.Entity<System_ObjectAttachmentLink>().ToTable("System_ObjectAttachmentLink");
            modelBuilder.Entity<System_ObjectAttachmentLink>().HasKey(p => p.ID);
            modelBuilder.Entity<System_ObjectAttachmentLink>().Property(p => p.Object_Caption).HasMaxLength(50);
            modelBuilder.Entity<System_ObjectAttachmentLink>().Ignore(p => p.IsNew);
            modelBuilder.Entity<System_ObjectAttachmentLink>()
                .Property(p => p.Attachment_ID)
                .ForSqlServerHasColumnName("Attachment_ID");

            modelBuilder.Entity<System_Attachment>()
                .HasMany(p => p.ObjectAttachmentLinks)
                .WithOne()
                .HasForeignKey(p => p.Attachment_ID);
`

**Comment by rowanmiller** [comment]
@jerry2007 you want to update the relationship configuration to specify that `System_ObjectAttachmentLink.Attachment` is a navigation property in the relationship. At the moment you are using the empty overload of `WithOne()` - which is telling EF there is no navigation property on that end of the relationship... which in turn means `System_ObjectAttachmentLink.Attachment` must represent another relationship between the two entities. To handle this second relationship, EF is introducing the `AttachmentId` column you are seeing.

```c#
            modelBuilder.Entity<System_Attachment>()
                .HasMany(p => p.ObjectAttachmentLinks)
                .WithOne(a => a.Attachment)
                .HasForeignKey(p => p.Attachment_ID);`
```
