### ISSUE TITLE
What is a proper way to use "dotnet ef" command? Failed to initialize CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by sergekolchin** [dotnet/efcore#4647]
After running "dotnet ef" in project directory i get "Failed to initialize CoreCLR, HRESULT: 0x80004005".
**project.json**

```
{
  "dependencies": {
    "Microsoft.AspNetCore.Hosting": "1.0.0-*",
    "Microsoft.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
  },
  "frameworks": {
    "net451": { }
  },
  "tools": {
    "dotnet-ef": "1.0.0-*"
  }
}
```

**dotnet --version**

```
.NET Command Line Tools (1.0.0-beta-001540)
Product Information:
 Version:     1.0.0-beta-001540
 Commit Sha:  6aeed1f52d
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**dotnet restore** - success
**dotnet build** - success
**dotnet ef** - Failed to initialize CoreCLR, HRESULT: 0x80004005

**Comment by barriestewart** [comment]
I don't have this working myself but the `dotnet-ef` nuget package only targets DNXCore. If you add `dotnet5.4` into your frameworks section does that help?

**Comment by SergeyKolchin** [comment]
I added a  
```
"dotnet5.4": {
      "imports": "portable-net452+win81"
    }
```
to the **frameworks** section, but nothing has changed:
```
dotnet ef Failed to initialize CoreCLR, HRESULT: 0x80004005
```

**Comment by SergeyKolchin** [comment]
waiting for a stable version rc2 and cli

**Comment by Cuiqs76** [comment]
same issues.

**Comment by Cuiqs76** [comment]
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x86

**Comment by bricelam** [comment]
You may want to try filing on the [dotnet/cli](https://github.com/dotnet/cli) repository.
