### ISSUE TITLE
Snapshot not staying up to-date with migrations

### ISSUE THREAD

**Issue by Inumedia** [dotnet/efcore#4663]
Upon the initial creation of the migrations, the initial snapshot is created successfully, after about a dozen migrations has been added things start to fall apart and migrations are either no longer added or do not update the snapshot ( leading to any new migrations afterwards to be a include what the previous migration did ).

I'm not 100% sure on the steps to recreate, I'll update this once I find a consistent way to recreate.

**Comment by rowanmiller** [comment]
> I'm not 100% sure on the steps to recreate, I'll update this once I find a consistent way to recreate.

Sounds good. We haven't seen this in our testing, so we'll wait for the repro steps from you :smile:.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with info

**Comment by Inumedia** [comment]
Sorry, I have not forgotten, just been too busy to be able to replicate it in an open environment. It seems to have something to do with there being a bin/artifact folder when building ASP.NET5 and EF7 picking up that snapshot. 

I believe this is related: http://stackoverflow.com/questions/35367388/entity-framework-7-dnx-ef-migrations-add-missing-output-file/35471025

**Comment by rowanmiller** [comment]
Ah, makes sense. @bricelam does this all go away in RC2 with the move to .NET CLI?

**Comment by bricelam** [comment]
Yes, this sounds like the same situation as another issue we had recently (which I can't seem to find). It should go away in CLI world.

**Comment by rowanmiller** [comment]
Thanks. Closing out as this copying of source files won't exist in the .NET CLI world. Unfortunately in RC1 you would just need to remove the copied files as a workaround.
