### ISSUE TITLE
Using 'Microsoft.EntityFrameworkCore.Commands' in project.json

### ISSUE THREAD

**Issue by maxmantz** [dotnet/efcore#4671]
After switching to the new namespace, I have changed my project.json file to reflect the changes. My `commands`section now looks like this:

```
"commands": {
   "ef": "Microsoft.EntityFrameworkCore.Commands",
   "web": "myproject"
 }
```

However, when using the command `dnx ef` i get the following message:

`'Microsoft.EntityFrameworkCore.Commands' does not contain a 'Program' type suitable for an entry point`.

DNX Info:

 Version:      1.0.0-rc2-16551
 Type:         Clr
 Architecture: x64
 OS Name:      Windows
 OS Version:   10.0.10240
 Runtime Id:   win10-x64

**Comment by capesean** [comment]
You'll need to start using the new [CLI](https://github.com/dotnet/cli) if you're using RC2 builds. That means you have to use the syntax `dotnet ef xxx`, after adding the `tools` section to your project.json which replaces the `commands` `ef` section. But it's not 100% stable yet. See #4659 and #3925 for more info.

**Comment by Kukkimonsuta** [comment]
(this is something horrible and please don't judge me, but it sort of kind of works..)

There is a way to run under dnx, but you have to invoke the commands yourself:

https://gist.github.com/Kukkimonsuta/c42997b223c7be35b700

If you need other commands, you basically just copy them from https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Commands/Design/MigrationsOperations.cs .. good luck :)

And change your `project.json` to

```json
    "commands": {
        "web": "TestProject.Web web",
        "ef": "TestProject.Web ef"
    },
```

**Comment by bricelam** [comment]
:+1: what @capesean said
