### ISSUE TITLE
Use ExecuteReader.RecordsAffected to know the number of rows affected.

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/efcore#4674]
Hi @rowanmiller , @divega 

We are developing an EF7 provider and we are facing issues with respect to Update and Delete statement execution because of the underneath EF.Relational design.

Not all Servers return the number of rows affected as a part of command text execution , instead it will be available as a part of ExecuteReader.RecordsAffected which will be set using the SQL Communication Area.

Even though the execution is proper at the server end and returning number of rows affected in ExecuteReader, because of the first condition in the below method, we get Exception.

File Name : entityframework-7.0.0-rc1\src\entityframework.relational\update\affectedcountmodificationcommandbatch.cs
      protected virtual int ConsumeResultSetWithoutPropagation(int commandIndex, [NotNull] DbDataReader reader)
        {
            var expectedRowsAffected = 1;
*\*            while (++commandIndex < ResultSetEnds.Count
                   && !ResultSetEnds[commandIndex - 1])**
            {
                Debug.Assert(!ModificationCommands[commandIndex].RequiresResultPropagation);

```
            expectedRowsAffected++;
        }

        if (reader.Read())
        {
            var rowsAffected = reader.GetInt32(0);
            if (rowsAffected != expectedRowsAffected)
            {
                ThrowAggregateUpdateConcurrencyException(commandIndex, expectedRowsAffected, rowsAffected);
            }
        }
        else
        {
            ThrowAggregateUpdateConcurrencyException(commandIndex, 1, 0);
        }

        return commandIndex;
    }
```

Why dont we take decision using ExecuteReader.RecordsAffected value ? and instead expect the rows affected as a return value from the command text execution ?

Server does not support returning number of rows affected for Update and Delete statements. Because of which we are blocked with provider development and can not implement update and delete functionality support.

Does EF6 also expected number of rows affected in the same way as EF7 from Update and Delete statements ? was it mandatory and did it throw exception if not returned ?

Please help.

Thanks and Regards,
Prashanth.

**Comment by ErikEJ** [comment]
You can override the default implementation, I had to do that for similar reasons (my database engine only supports a single statement per batch, and I also use .RecordsAffected https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Update/Internal/SqlCeModificationCommandBatch.cs

**Comment by PrashanthIBM** [comment]
Hi ErikEJ,

Thanks for the reply.

I would expect EntityFramework.Relational to be more generic rather than being SQLSERVER specific.

So don't we have any other way apart from re-implementing the logic on the provider layer ?

Cant we change the EntityFramework.Relational files to have a generic implementation which will have no impact on other database providers ?

**Comment by rowanmiller** [comment]
@AndriySvyryd can you comment on this one?

**Comment by AndriySvyryd** [comment]
@PrashanthIBM `AffectedCountModificationCommandBatch` is a base class for providers that return the number of rows affected as a part of the results in the reader, other providers need to derive their implementation from `ReaderModificationCommandBatch`.
EF6 didn't have this because it didn't support update command batching.

**Comment by ajcvickers** [comment]
@PrashanthIBM To add to what @AndriySvyryd said, if you come up with any generally useful abstractions, then we would be very happy to consider a pull request.

**Comment by PrashanthIBM** [comment]
Thanks everyone for the inputs.

I will keep this issue open for any further discussions regarding this design change implementation.

**Comment by rowanmiller** [comment]
From the above discussion we feel like we already have the components/seams in place to allow all this functionality to be overridden. If during implementation you find that some of those seams could be adjusted to make things easier then we'd be very willing to look at a pull request for the changes.
