### ISSUE TITLE
Is EFCore supported in a WinMD component?

### ISSUE THREAD

**Issue by darenm** [dotnet/efcore#4684]
Referring to #3543 - has there been any change of thought on supporting WinMD with EFCore V1.0? Virtually all the non-trivial UWP apps I build require background tasks that  access the same data as the app (Cortana voice commands finding the next appointment, etc.) so we typically architect our apps:
- App (Universal Application)
- App.SharedDataLibrary (Universal Class Library)
- BackgroundTask (WinMD)

Based upon my current understanding, that's not going to be possible with Rc1/RC2/.../V1.0 - correct?

**Comment by bricelam** [comment]
I suspect you should be able to use the EF runtime in a Windows Runtime Component. At the end of the day, it's just like any other .NET Core package. Issue #3543 is just about being able to use the Entity Framework NuGet Commands, which I don't think we'll be able to support.

**Comment by darenm** [comment]
So I ran into an issue of not being able to leverage a DbContext in a class library, and I can't have a DbContext defined within the WinMD component due to the issue with derived types, DbSet not being allowed, etc. When I have the DbContext in a class library, migrations don't run on start-up in the main app and I get other errors that seem to suggest the database file perhaps isn't being created in the same location. Do you have any thoughts on what might be happening here?

**Comment by rowanmiller** [comment]
**Team Triage:** At this stage, supporting WinMD is not something we are going to invest in. Given the limitations around derived types etc. it feels like it is not a good fit for the EF programming experience. That said, if there are changes that would make parts of EF useful in WinMD (such as using a non-derived DbContext) then we'd be very willing to look at those individual changes (including looking at pull requests for them).
