### ISSUE TITLE
dnx ef database update to support DNX library as parameter

### ISSUE THREAD

**Issue by baywet** [dotnet/efcore#4690]
Hi,
Would it be possible to pass pre-compiled DNX library instead of a project with source code for the update?
This would allow us to build the thing in VSTS build and then to update the database schema from VSTS release without having to bring the sources along.
Thanks for your answer!

**Comment by bricelam** [comment]
A feature like this came up during the discussion of #4577. This is probably something to consider as part of #646

**Comment by rowanmiller** [comment]
Discussed and decided that #646 is the way we want to handle this.
