### ISSUE TITLE
StackOverflowException on 1.0.0-rc2-20051

### ISSUE THREAD

**Issue by chrisjmccrum** [dotnet/efcore#4691]
When I run my application _dotnet run_  I'm now hitting a StackOverflowException

> Process is terminated due to StackOverflowException.

![image](https://cloud.githubusercontent.com/assets/1857216/13480184/12b790f6-e0aa-11e5-94d6-51f45bcfea10.png)

![image](https://cloud.githubusercontent.com/assets/1857216/13480264/a1f3d8c4-e0aa-11e5-910e-8256050a0eb9.png)

**Comment by smitpatel** [comment]
Can you share your model classes & DbContext? It looks like model building is throwing SOF.

**Comment by rowanmiller** [comment]
Can you share the full stack trace from the exception too.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details.
