### ISSUE TITLE
T must be a reference type in order to use it as parameter

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#4694]
I'm struggling to write an Entity Framework's adapter for our repository pattern. here is the code and obviously "T must be a reference type in order to use it as parameter" will raise. our design is based on nhibernate and it's not possible to change repository interface. Is any trick to bypass this constraint!? just a little constraint failed us to use Entity Framework!

```
public T Get<T>(object id) 
{
    return _dbContext.Set<T>().Find(id);
}
```

**Comment by rowanmiller** [comment]
Are you using EF6.x of EF Core?

On 6.x you can do this:

```c#
public T Get<T>(object id)
{
    return (T)_dbContext.Set(typeof(T)).Find(id);
}
```

**Comment by NimaTheCoder** [comment]
It does not work on collections!

**Comment by rowanmiller** [comment]
Do you mean returning a collection of items, rather than just using `Find`? If so, it's a little messy, but this works:

```c#
public static IEnumerable<T> GetAll<T>(object id, TestContext2 _dbContext)
{
    var query = (IQueryable<T>)_dbSetMethod.MakeGenericMethod(typeof(T)).Invoke(_dbContext, Array.Empty<object>());
    return query.ToList();
}
```

**Comment by NimaTheCoder** [comment]
Reflection!? what about performance! You should choose nhibernate as role model for API design!

**Comment by rowanmiller** [comment]
I'm not sure that this is bad API design - you can't create a `DbSet` for a value type, so the `where TEntity : class` seems reasonable in this case. I get that it's painful in your particular scenario though.
