### ISSUE TITLE
The INSERT statement conflicted with the FOREIGN KEY constraint

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#4699]
Hello,

Moving from EF6 to EF7 and testing a very similar model to what you have in entity framework docs (http://ef.readthedocs.org/en/latest/modeling/relationships.html#many-to-many) for Many to Many relationships I got the following error when creating an entity:

```
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PostTag_Tag_TagId"  
```

Note: I am able to create the migration and update the database to my model without a problem.

I am using Entity Framework 7 RC1 and I have the following entities:

```
public class Post {
  public Int32 Id { get; set; }
  public String Title { get; set; }
  public virtual IList<PostTag> PostsTags { get; set; }
}

public class Tag {
  public Int32 Id { get; set; }
  public String Name { get; set; }
  public virtual IList<PostTag> PostsTags { get; set; }
}

public class PostTag {
  public Int32 PostId { get; set; }
  public Int32 TagId { get; set; }
  public virtual Post Post { get; set; }
  public virtual Tag Tag { get; set; }
}
```

And the model configuration is has follows:

```
protected override void OnModelCreating(ModelBuilder builder) {

  base.OnModelCreating(builder);

  builder.Entity<Post>(b => {
    b.ToTable("Posts");
    b.HasKey(x => x.Id);
    b.Property(x => x.Id).UseSqlServerIdentityColumn();
    b.Property(x => x.Title).IsRequired().HasMaxLength(100);
  });

  builder.Entity<Tag>(b => {
    b.ToTable("Tags");
    b.HasKey(x => x.Id);
    b.Property(x => x.Id).UseSqlServerIdentityColumn();
    b.Property(x => x.Name).IsRequired().HasMaxLength(100);
  });

  builder.Entity<PostTag>(b => {
    b.ToTable("PostsTags");
    b.HasKey(x => new { x.PostId, x.TagId });
    b.HasOne(x => x.Post).WithMany(x => x.PostsTags).HasForeignKey(x => x.PostId);
    b.HasOne(x => x.Tag).WithMany(x => x.PostsTags).HasForeignKey(x => x.TagId);
  });
}
```

Finally, I tried to create a Post:

```
Context context = new Context();

Post post = new Post {
  PostsTags = new List<PostTag> {
    new PostTag {
      Tag = new Tag { Name = "Tag name" }
    }
  },
  Title = "Post title"
};

context.Posts.Add(post);

await _context.SaveChangesAsync();
```

And got the following error:

```
An error occurred while updating the entries. 
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_PostTag_Tag_TagId". 
The conflict occurred in database "TestDb", table "dbo.Tags", column 'Id'. 
The statement has been terminated.
```

I don't see any problem in the model definition ... Am I wrong?

Thank You,
Miguel

**Comment by smitpatel** [comment]
Which version of EF are you using?

**Comment by mdmoura** [comment]
I am using EF 7 RC1 Final ... Here is the project dependencies:

    "dependencies": {
      "EntityFramework.Commands": "7.0.0-rc1-final",
      "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
      "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
      "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
      "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
      "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
      "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
      "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
      "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
      "Microsoft.AspNet.Razor.Runtime": "4.0.0-rc1-final",
      "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
      "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
      "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
      "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
      "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
      "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
      "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
    }

**Comment by rowanmiller** [comment]
This would be because `Add` in RC1 would only add children, so it adds your `Post` and then `PostTag` (because it is a child/dependent of `Post`), but it will not add the `Tag` (because it is a parent of `PostTag`). This is changing for RC2, and you will get the behavior you expect. See https://github.com/aspnet/EntityFramework/issues/4424 for more details on this.

In the meantime, you just need to call `Add` on the `Tag` as well.
