### ISSUE TITLE
Improve exceptions (more detailed types and content)

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#4700]
Hi,
since EF Core is a new rewrite, maybe it's a good time to try to improve Exceptions. While I understand that EF is a sort of generic ORM on top of different data providers, a better integration between the 2 layers could help developers. At the moment, it's a bit difficult to provide the application user a precise information about what happened.

Imagine the common scenario where EF is used inside a Web API with an SQL storage. The API caller provides an Entity and specifies its Id and suppose the Id is duplicated.
Different things can happen:
1. The API controller checks if an entity with that Id already exist. It works, but requires a DB access for a thing that DB can report on insert. But if he does not check...
2. A different exception is thrown, depending if the entity with the same id was already in EF's cache (InvalidOperationException vs DbUpdateException)

Something similar happens with relationships and foreign keys. API user provides the entity with some FK filled in. In the controller, either you check them all or just trust the DB and try to save the entity. But in the catch block it's difficult to understand what's happened exactly. Yes, you may get a DbUpdateException but how to report the reason way the model was incorrect? There is a message in the inner exceptions, but in a JSON response codes are way better than a long text.

Does this make sense?

**Comment by rowanmiller** [comment]
@bragma in general we've stayed away from trying to interpret database specific exceptions. The only case we throw something specific is for concurrency violations - since they are often actionable by the end user. Do you have some specific use cases where having a particular exception type thrown from SaveChanges would be significantly better than just checking the database specific InnerException?

**Comment by bragma** [comment]
@rowanmiller as said above, I totally agree on keeping things generic at higher framework level. In fact my request was more aimed at people working on the SQLServer or specific DB providers/integrations. Sometimes EF throws a DbUpdateException, but the inner exception is AFAIK totally generic, with only a the message left to understand what happened. It may be a FK constraint violation, or a duplicated PK and the only hint to what property caused the problem is in an English language exception message. Knowing better (programmatically) what happened may help to report what was wrong in the submitted entity, in particular if EF is used in a Web API.
When you say "just checking the db specific InnerException", can you explain how to programmatically know which property was part of a failed constraint violation?
My only gripe regarding high level EF exceptions, is that the exact same operation can fail with 2 different exception types depending on the fact that an entity was previously loaded in EF's cache or not.

Regarding a specific use case, suppose the case of a Web API using EF using an SQL server and a schema with 2 entities with a FK constraint. User POSTs a controller submitting an entity with (among other properties) a populated FK Id. If that Id is invalid (as an example it refers to an entity that does not exist on the other end of the relationship), the INSERT will fail.
As the developer of the controller I have 3 options:
1. Try to load/check the related entity on the DB using the specified FK Id. If it fails, I can report a specific error indicating the User that the Id specified in the property FK is incorrect. But this requires an access to the DB just for checking.
2. Try the INSERT, if it fails try to parse the InnerException to understand what happened, and maybe parse the Message for knowing which FK constraint was violated, then report back the property containing the incorrect Id.
3. Try the INSERT, if it fails report back the InnerException message hoping that the user will understand which property was wrong by the FK name.
I don't particularly like any of those options. :)

I don't know if something can be done to improve the situation, but if it can be done, I suggest to try it.

**Comment by rowanmiller** [comment]
> In fact my request was more aimed at people working on the SQL Server or specific DB providers/integrations.

Right that makes total sense. 

Unfortunately in the case of SQL Server the info you are after isn't really there - in fact the EF provider only has the same info that you have available in the `InnerException` since that is what the underlying ADO.NET provider returned. With the example of the FK violation, the `InnerException` is a `SqlException`, which has `ErrorCode` that you can use to work out it was an FK violation... but there is not way to determine what constraint was violated (other than parsing the message).

**Comment by bragma** [comment]
I understand, thanks for the discussion!

**Comment by roji** [comment]
For anyone ending up here, you may want to take a look at [EntityFramework.Exceptions](https://learn.microsoft.com/en-us/ef/core/extensions/#entityframeworkexceptions).
