### ISSUE TITLE
TPH: Support more discriminator conditions (NotNull etc.)

### ISSUE THREAD

**Issue by jnm2** [dotnet/efcore#4722]
EF6 had the ability to use multiple discriminator properties to avoid the use of a dedicated discriminator column. You can set that it up so that if a subclass property is not null, that tells EF that the correct type is the subclass that owns the property.

It would be great to be able to go `.HasDiscriminatorNotNull<TSubclass>(_ => _.SubclassProperty).`

That's just a suggestion as far as what the API looks like, but we do need some way to be able to get rid of logically redundant discriminator columns to keep our tables clean.

**Comment by rowanmiller** [comment]
Not currently supported but we do want to enable this (and other patterns) post v1.0.0

**Comment by ajcvickers** [comment]
Closing in favor of #10140 which is basically a duplicate and has gathered more details.
