### ISSUE TITLE
Build warning from AsyncQueryTestBase.cs

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#4732]
6>C:\Dev\aspnet\EntityFramework\test\Microsoft.EntityFrameworkCore.FunctionalTests\AsyncQueryTestBase.cs(27,35,27,62): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
6>  Microsoft.EntityFrameworkCore.FunctionalTests -> C:\Dev\aspnet\EntityFramework\test\Microsoft.EntityFrameworkCore.Functi

cc @natemcmaster

**Comment by natemcmaster** [comment]
oops. :facepalm:

**Comment by natemcmaster** [comment]
https://github.com/aspnet/EntityFramework/commit/b27717b4b8d2d3b7a16fc6d220786bf6321ce86f
