### ISSUE TITLE
Turn Tracking by global to off? : Question

### ISSUE THREAD

**Issue by neridonk** [dotnet/efcore#4751]
Is it possible to change Tracking  global to off so that I dont have to call the methode AsNoTracking() on every "get" call

**Comment by HalidCisse** [comment]
+1

**Comment by rowanmiller** [comment]
There is a `DbContext.ChangeTracker.QueryTrackingBehavior` property. If you want no tracking by default, then you can set it to `QueryTrackingBehavior.NoTracking` in the context constructor.
