### ISSUE TITLE
Connection leaks with WCF distributed transactions, not thread safe when using async/await keywords in service

### ISSUE THREAD

**Issue by ajtowf** [dotnet/efcore#4752]
We're leaking connections when using async/await keywords with distributed transactions in our services, which results in "The current TransactionScope is already complete” exceptions after a while, even from services that don't consume transactions, hence the leak.
- [Blog post with details](http://www.towfeek.se/2016/03/connection-leaks-when-using-asyncawait-with-transactions-in-wcf/)
- [Screencast illustrating the problem](https://www.youtube.com/watch?v=PHLyJSOQmJA)
- [Source code to reproduce](https://github.com/ajtowf/dist_transactions_lab)

**Comment by rowanmiller** [comment]
Moved to CodePlex since the repro uses 6.1.3 https://entityframework.codeplex.com/workitem/2898.

Our team has the next few weeks completely blocked out for EF Core, and then we are going to focus mostly on EF6.x for a short period. We will dig into this issue during that time.

**Comment by ajtowf** [comment]
Are you certain that this problem doesn't exist with EF7?  Seems a bit rash to dismiss it as a EF6.x bug.

**Comment by rowanmiller** [comment]
@ajtowf generally speaking we consider "does this apply to EF Core" when looking at EF6 issues.
