### ISSUE TITLE
Context attribute in migrations snapshot file not always correct

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#4758]
**Repro:**
Generate a migration for abc.TestContext:

``` c#
namespace ConsoleApp1
{
    public class TestContext : DbContext
    {
        // ..
    }
}

namespace abc
{
    public class TestContext : DbContext
    {
        // ..
    }
}
```

**Expected:**
The DbContext attribute on TestContextModelSnapshot.cs should refer to abc.TestContext

**Actual**
The DbContext attribute on TestContextModelSnapshot.cs refers to ConsoleApp1.TestContext

``` c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using abc;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(TestContext))] // <-- this refers to ConsoleApp1.TestContext
    partial class TestContextModelSnapshot : ModelSnapshot
```

![image](https://cloud.githubusercontent.com/assets/2696087/13683484/c7b4c49e-e6bb-11e5-9cc3-adc5138397e0.png)

**Comment by natemcmaster** [comment]
Potentially simple solution: next `using abc;`... but this could have complications I'm not aware of.
```c#
namespace ConsoleApp1.Migrations
{
    using abc;
    [DbContext(typeof(TestContext))]
```

**Comment by smitpatel** [comment]
Question: Why migrations for abc.TestContext are inside ConsoleApp1.Migrations namespace instead of abc.Migrations?

**Comment by natemcmaster** [comment]
ConsoleApp1.Migrations is the default namespace migrations chooses.

**Comment by rowanmiller** [comment]
**Triage:** Decided that two contexts with the same name in different namespaces is pretty corner case. We can reconsider if folks actually hit this in real apps.
