### ISSUE TITLE
UWP SQLite Migrations

### ISSUE THREAD

**Issue by mglodack** [dotnet/efcore#4768]
What's the proper way to run migrations for SQlite on UWP?

I see an example of running migrations [here](http://ef.readthedocs.org/en/latest/platforms/uwp/getting-started.html#create-your-database) on the entity framework 7 website, but is that the correct way?

**Comment by bricelam** [comment]
Yes, that is correct. Calling `DbContext.Database.Migrate()` during startup is probably best.

**Comment by rowanmiller** [comment]
:+1:

**Comment by mglodack** [comment]
Awesome! Thank you @bricelam
