### ISSUE TITLE
Improve compatibility of dotnet-ef logging with other scripting tools such as powershell

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#4771]
Currently dotnet-ef writes only to stderr and stdout, but this doesn't let us powershell differentiate well the logging output. To pipe logging levels through to PMC, we need a mechanism to read output on these pipes and translate it to powershell levels.

One idea: https://github.com/aspnet/EntityFramework/pull/4767/files#r55864608

**Comment by natemcmaster** [comment]
As a part of this, we should revisit the stderr/stdout mechanism in general. Using stderr causes issues for other scripting tools, not just powershell.

cref https://github.com/aspnet/EntityFramework/issues/5012

**Comment by rowanmiller** [comment]
Consolidating several related issues into https://github.com/aspnet/EntityFramework/issues/5334
