### ISSUE TITLE
unable to apply Identity migrations using ef 7

### ISSUE THREAD

**Issue by ayydevara** [dotnet/efcore#4778]
"dependencies": {
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final"
  },

Column 'Users.Id' is not the same length or scale as referencing column 'AspNetUserClaims.UserId' in foreign key 'FK_IdentityUserClaim<string>_ApplicationUser_UserId'. Columns participating in a foreign key relationship must be defined with the same length and scale.

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Can you provide detailed steps that we can use to reproduce the error.

**Comment by ayydevara** [comment]
Here are the detail steps. 

1. Create a class library (package)
2. Use IdentityDbContext for the [Project]DbContext class
3. Create the initial migration 
4. Try to apply the migration (dnx ef migrations add "Initial")
5. You should see the above error (dnx ef database update)

**Comment by rowanmiller** [comment]
Can you adjust these steps. For me they successfully create the identity schema in the database.

Using VS2015 Update 1 with ASP.NET 5 RC1 tools installed.

1. Create a new ` Class Library (package)`
2. Update the dependencies, frameworks, and commands section of `project.json`

```json
{
  "version": "1.0.0-*",
  "description": "ClassLibrary1 Class Library",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "dependencies": {
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final"
  },

  "commands": {
    "ef": "EntityFramework.Commands"
  },
  "frameworks": {
    "dnx451": { }
  }
}
```

3. Copy the ASP.NET Identity model, from the default web project template, into `Class1.cs`

```c#
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Data.Entity;

namespace ClassLibrary1
{
    public class Class1
    {
        public Class1()
        {
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro;Trusted_Connection=True;");

            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }

    public class ApplicationUser : IdentityUser
    {
    }
}
```

4. Open command prompt and cd to project directory
5. Run `dnvm use 1.0.0-rc1-final`
6. Run `dnx ef migrations add Initial`
7. Run `dnx ef database update`

For me the database is created without error
![image](https://cloud.githubusercontent.com/assets/4741851/13962286/7ab5c420-f01d-11e5-9737-543119384882.png)

**Comment by ayydevara** [comment]
@rowanmiller Let me try that again
