### ISSUE TITLE
Migrations generate a garbage using statement

### ISSUE THREAD

**Issue by glennblock** [dotnet/efcore#4779]
I am using the EF CLI (dnx ef) on OSX and seeing a weird issue whenever I generate migrations. What happens is I get a `using ;` at the top of the XXXSnapshot.cs and XXX_Designer.cs files.

I am able to continually reproduce this.

If I remove the garbage using statement, everything compiles fine.

Anyone else see this?

**Comment by rowanmiller** [comment]
You're using RC1 right? If so, this is probably because your context is not in a namespace. If that is the case, it's already fixed in our code base.

**Comment by glennblock** [comment]
Aaah, ok. Thanks @rowanmiller.
