### ISSUE TITLE
Unrelated error when ignoring jagged array via fluent API

### ISSUE THREAD

**Issue by kotmage** [dotnet/efcore#4782]
Simplified model:

```
public class PocoBook      {   
      public string Ocode { get; set; }   
....  
      public string[] Autori { get; set; }  
      public string[][] Nahledy { get; set; }  
....  
}
 public class Poco : PocoBook   {
      public string KodZdroje { get; set; }
.....
}
```

In OnModelCreating:

```
         modelBuilder.Entity<Poco>()
            .HasKey(t => new { t.KodZdroje, t.Ocode });
.....
         modelBuilder.Entity<Poco>().Ignore(t => t.Autori);
         modelBuilder.Entity<Poco>().Ignore(t => t.Nahledy); //won't change the behavior

```

Everything works fine, I have some boiler-plated code to serialize arrays (like Autori) into single columns etc...
Now, in the moment I add Nahledy to the model and try to Add-Migration, this error comes out: 

> The derived type '....Poco' cannot have keys other than those declared on the root type.

Ok, at first, I would expect something like this to be yelled at me instead:

> The property 'Autori' on entity type '....Poco' has not been added to the model or ignored.

But following "the simple array logic" - adding the Ignore fluent API call - won't change a thing. Still the same error. Strangely enough, adding `[NotMapped]`to `Nahledy` fixes the problem. For different reasons, I would like to stick with fluent API instead of introducing changes to the base class.

//Configuration: EF7 7.0.0-rc1-final + Npgsql

//The [NotMapped] solution works only for one property of type string[][], adding another such property breaks the model again.

**Comment by smitpatel** [comment]
> The derived type '....Poco' cannot have keys other than those declared on the root type.
Statement `modelBuilder.Entity<Poco>().HasKey(t => new { t.KodZdroje, t.Ocode });` adds key on type `Poco` which is derived type in the model. The exception is thrown before the fluent api calls written after that statement are actually applied. `[NotMapped]` solution works since data annotations are applied at the time of entity type discovery and which will happen before `HasKey` call.

**Comment by kotmage** [comment]
Thank you, that explains something (but as I found later, `[NotMapped]` works only for one jagged array field in model). 
What makes me wonder is: I am not referencing the base type anywhere AND it does happen only when I add jagged arrays into the model (for the time being I replaced them with simple arrays of custom structs).

**Comment by rowanmiller** [comment]
@kotmage can you provide a complete code listing (or project) that we can run to debug what is happening.
