### ISSUE TITLE
The Visual Studio component cache is out of date

### ISSUE THREAD

**Issue by jaoord** [dotnet/efcore#4785]
This happens every time I try to update my database (update-database)

These are the errors I get:

Exception calling "GetService" with "1" argument(s): "Exception calling "Invoke" with "2" argument(s): "The Visual Studio component cache is out of date. Please restart Visual Studio. The Visual Studio component cache is out of date. Please restart Visual Studio.""
At D:\Dev\Project\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1004 char:5
-     $packageInstallerServices = $componentModel.GetService([NuGet.Vis ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ScriptMethodRuntimeException

You cannot call a method on a null-valued expression.
At D:\Dev\Project\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:1006 char:5
-     $vsPackage = $packageInstallerServices.GetInstalledPackages() | ? ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At D:\Dev\Project\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:713 char:28
-     $toolsPath = Join-Path $installPath tools
-                            ~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At D:\Dev\Project\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:74
- ...  [System.Reflection.Assembly]::LoadFrom((Join-Path $ToolsPath EntityF ...
-                                                        ~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

You cannot call a method on a null-valued expression.
At D:\Dev\Project\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
-     $dispatcher = $utilityAssembly.CreateInstance(
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At D:\Dev\Project\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:810 char:20
-         (Join-Path $runner.ToolsPath EntityFramework.PowerShell.dll),
-                    ~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

**Comment by smitpatel** [comment]
Does deleting component cache help?

**Comment by jaoord** [comment]
Yes, clearing the cache helps. But I get a bit tired of starting visual studio, trying to add a migration or update database, then I get the component cache error, I close visual studio, remove all files from the component cache folder, start Visual Studio again and then I can update the database. I don't know if this is related to Visual Studio or to EF...

**Comment by rowanmiller** [comment]
@jaoord is this something that you have been able to reliably reproduce, or are you just seeing it on one machine? If you can reproduce it, could you share the exact versions of Windows, Visual Studio, and NuGet that you see the error on?

**Comment by jaoord** [comment]
Just on one machine, but I have seen it on another machine.
On Mar 22, 2016 18:28, Rowan Miller <notifications@github.com> wrote:@jaoord is this something that you have been able to reliably reproduce, or are you just seeing it on one machine? If you can reproduce it, could you share the exact versions of Windows, Visual Studio, and NuGet that you see the error on?

**Comment by rowanmiller** [comment]
@jaoord are you able to provide details of where this occurs so that we can look at reproducing and debugging the issue? We are not able to reproduce the error, so there isn't a lot we can do without info on how to produce it.

**Comment by alaatadmori** [comment]
Look at the solution here: [](https://stackoverflow.com/questions/35710263/the-visual-studio-component-cache-is-out-of-date-please-restart-visual-studio)
It seems to help so far. (Disk cleanup)
