### ISSUE TITLE
'Microsoft.EntityFrameworkCore.Commands' does not contain a 'Program' type suitable for an entry point

### ISSUE THREAD

**Issue by xatabhk** [dotnet/efcore#4787]
"commands": {
        "web": "tbweb",
        "ef": "Microsoft.EntityFrameworkCore.Commands"
    },

> dnx ef migrations add init
> 'Microsoft.EntityFrameworkCore.Commands' does not contain a 'Program' type suitable for an entry point

**Comment by rowanmiller** [comment]
RC2 is moving to .NET CLI for commands, so `dnx ef` will no longer apply. Things are very unstable at the moment, while we transition to the new command architecture (and .NET CLI in general). You can follow along with https://github.com/aspnet/EntityFramework/issues/3925 to find out when things stabilize.
