### ISSUE TITLE
Index properties, and inheritance

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#4791]
I am using RC 1, and I have an entity that inherits from one provided in ASP.NET 5 `Identity` 3, but adds an additional `IsActive` flag (i'm mapping to a legacy table).

```
    public partial class UserRole : IdentityUserRole<int>
    {
        public int UserRoleId { get; set; }

         public int RoleId { get; set; }          

        public bool? IsActive { get; set; }

    }

```

There is an index on this table. I notice that when I do this:

```
        protected void OnIdentityModelCreating(ModelBuilder builder)
        {
           base.OnModelCreating(builder);

           modelBuilder.Entity<UserRole>(entity =>
            {
entity
                entity.HasIndex(e => new { e.UserId, e.IsActive }).HasName("idxUserId_IsActive");        


           });          

        }

```

I get this exception:

```
Result Message: The properties provided for the argument 'properties' are declared on different entity types.

Result StackTrace:  
at Microsoft.Data.Entity.Metadata.Internal.MetadataHelper.CheckSameEntityType(IReadOnlyList`1 properties, String argumentName)
   at Microsoft.Data.Entity.Metadata.Internal.Index..ctor(IReadOnlyList`1 properties)
   at Microsoft.Data.Entity.Metadata.Internal.EntityType.AddIndex(IReadOnlyList`1 properties)

```

It doesn't seem to like the fact that one of the properties in the index is from the base class.

I have tried overriding the virtual property from the base, in the derived class - and also shadowing the property, and both attempts still yield the same error.

Is this just flat out not supported, or is there another approach?

**Comment by smitpatel** [comment]
Which version of EF core are you using?

**Comment by rowanmiller** [comment]
@smitpatel do you think we have fixed this already?

**Comment by rowanmiller** [comment]
Never mind, @AndriySvyryd confirmed this was fixed post RC1

**Comment by dazinator** [comment]
Ok - cheers :)
