### ISSUE TITLE
Model Builder: Should we scan for derived types?

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#4799]
I really miss derived type discovery.

``` C#
abstract class TestResult
{
    public int Id { get; set; }
}

class PassedTestResult : TestResult
{
}

class FailedTestResult : TestResult
{
}

class TestContext : DbContext
{
    public DbSet<TestResult> TestResults { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // NOTE: These are necessary :'(
        modelBuilder.Entity<PassedTestResult>();
        modelBuilder.Entity<FailedTestResult>();
    }
}
```

Even if we just limited it to types in the same assembly, it would be immensely helpful.

**Comment by anpete** [comment]
Related to #4793

**Comment by Muchiachio** [comment]
This was not available in EF6 right? Definitely a good addition, especially if you have a `BaseModel` with shared `Id` column across the models.

**Comment by bricelam** [comment]
@Muchiachio From [the EF6 docs](https://msdn.microsoft.com/en-us/data/jj679962):
> It is enough to define a `DbSet` property for the base class, and the derived types will be automatically included, if they are in the same assembly as the base class.

**Comment by Muchiachio** [comment]
Oh, I actually tried it in one of my projects and it didn't work even thought my models are in the same assembly. So I thought it was not included in EF6. Still +1, I may be doing something wrong.

**Comment by rowanmiller** [comment]
Ultimately we decided not to do this. We have some concerns about the stability and perf of scanning for types. There is also some nice symmetry in not scanning up or down the inheritance hierarchy (we definitely don't want to pull in base types automatically).
