### ISSUE TITLE
When will EF Core will be released? 

### ISSUE THREAD

**Issue by bcopmt143** [dotnet/efcore#4800]
I'm waiting the new EF Core for new project, when it will be released? or can I develop on the current version?

**Comment by ErikEJ** [comment]
When ASP.NET RC2 ships: https://github.com/aspnet/Home/wiki/Roadmap

**Comment by mikes-gh** [comment]
You could also watch the community stand ups as well.  I think Damian has been asked this question in every recent episode and always provides some sort of feedback on how things are going.
Next episode in 11 hours.
https://live.asp.net/

**Comment by gdoron** [comment]
@ErikEJ Wouldn't it be EF Core RC2? EF will be RTM together with ASP.NET, no?
(Which Damian said many times he can promise it will be this year, but he still doesn't know when)

**Comment by ErikEJ** [comment]
@gdoron Sure, it depends on what @bcopmt143 is waiting for...

**Comment by rowanmiller** [comment]
Just to confirm this from the product team... correct, EF Core is tied to ASP.NET Core (and .NET Core) releases. 

> Which Damian said many times he can promise it will be this year, but he still doesn't know when.

Also correct, we do not have definite dates yet. They will be shared when we have them.
