### ISSUE TITLE
You must target a compatible framework

### ISSUE THREAD

**Issue by erasethis** [dotnet/efcore#4810]
Sorry if this is a dumb question, but I can't seem to create a new database from my model,

PM> dotnet ef migrations add Initial
dotnet : The project 'Test' doesn't target a framework compatible with DNX Core 5.0. You must target a compatible framework like 'dotnet5.4' before using the Entity Framework Core .NET Core CLI 
Commands.
At line:1 char:1
- dotnet ef migrations add Initial
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (The project 'Te...e CLI Commands.:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

My project.json includes

   "frameworks": {
      "net451": { }
   }

Does that mean I can't add migrations for full .NET or what am I missing here?

**Comment by bricelam** [comment]
> Does that mean I can't add migrations for full .NET or what am I missing here?

Yes. See #4577. For now, you can either cross-compile to `netstandard1.3` (or similar) or plain-old Class Library project (*.csproj) and use the NuGet PowerShell commands.

**Comment by rowanmiller** [comment]
Closing this out as it is currently known that the CLI commands currently only support .NET Core... we do plan to relook at this as there may be support for cross compiled commands in CLI itself, or we may have to do something. We'll look at this as things stabilize in CLI.
