### ISSUE TITLE
KeyConvention should configure identity on composite keys if not ambigous

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#4820]
If there is only one property in a composite key that can be Identity (integer or GUID and no FKs defined on it) it should be configured by the convention as such.

**Comment by rowanmiller** [comment]
This was by-design. If you have an identity column then it is unique, but if you have a composite key then you are telling EF that you need two columns to make up the unique key. You can of course put identity back on if you really do want it.
