### ISSUE TITLE
Inheritance: Exception when using [ForeignKey] in parent class.

### ISSUE THREAD

**Issue by rok7** [dotnet/efcore#4824]
I get an ArgumentNullException on 'dnx ef migrations'-commands when using the following inheritance:

`public class Option`
`{`
`public int Id { get; set; }`
`}`

`public abstract class Parent`
`{`
`public int Id { get; set; }`
`public int TypeOptionId { get; set; }`
`[ForeignKey("TypeOptionId")]`
`public Option Type { get; set; }`
`}`

`public class Child`
`{`
`}`

When I remove '[ForeignKey("TypeOptionId")]' then migration is created, and also when the 'Child' is removed from DbContext and/or 'Parent' is changed to non-abstract.

Moving the linked property to those 'Child'-classes which need it could be a workaround, but then there's the issue #4703.

Here's the output from dnx:
PM> dnx ef migrations remove
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: builder
   bei Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   bei Microsoft.Data.Entity.ModelBuilder.Entity(Type type)
   bei Microsoft.Data.Entity.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   bei Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   bei Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   bei System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   bei Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   bei Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   bei Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   bei Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   bei Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   bei Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   bei Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass7_0.<ConfigureContextServices>b__8(IServiceProvider _)
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   bei Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   bei Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   bei Microsoft.Data.Entity.Design.MigrationsOperations.RemoveMigration(String contextType)
   bei Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass10_0.<RemoveMigration>b__0()
   bei Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Der Wert darf nicht NULL sein.
Parametername: builder
PM>

Regards
Rok

**Comment by AndriySvyryd** [comment]
This doesn't repro with the latest bits, so it must've been fixed.
