### ISSUE TITLE
Metadata: Hard to write polymorphic code over metadata.

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#4829]
We should consider creating interfaces for commonly used metadata elements such as:

``` c#
IEntityType DeclaringEntityType { get; } // Defined separately four times.
IReadOnlyList<IProperty> Properties { get; } // Defined separately three times.
```

It is often useful in tooling scenarios to be able to write polymorphic code over such elements.

**Comment by rowanmiller** [comment]
We're not going to do anything on this now, we can revisit later
