### ISSUE TITLE
ModelBuilder: Allow identifying relationships in HasKey

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#4835]
Given the following model...

``` C#
class Test
{
    public string Assembly { get; set; }
    public string Class { get; set; }
    public string Name { get; set; }
}

class TestResult
{
    public Test Test { get; set; }
    public DateTime StartTime { get; set; }
    public string Result { get; set; }
}
```

I don't care what my foreign keys are named, so I'd like to use the following configuration.

``` C#
modelBuilder.Entity<Test>().HasKey(t => new { t.Assembly, t.Class, t.Name });
modelBuilder.Entity<TestResult>().HasKey(
    t => new
    {
        t.Test, // NOTE: This is a navigation property
        t.StartTime
    });
```

Instead, I have to (at least) do this.

``` C#
modelBuilder.Entity<TestResult>().HasKey("TestAssembly", "TestClass", "TestName", "StartTime");
```

**Comment by divega** [comment]
We should consider supporting `[Key]` on a reference navigation in a similar fashion. Although the attribute is not supported on multiple properties,  it should still work for one-to-one relationships, and I had an instance in which I wanted to do this in my app week project.

**Comment by ajcvickers** [comment]
This is really owned entities in disguise, which is covered by work already done and #8172
