### ISSUE TITLE
ModelBuilder: Can't configure a by-convention, single-navProp relationship

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#4836]
Given the following model...

``` C#
class Test
{
    public string Assembly { get; set; }
    public string Class { get; set; }
    public string Name { get; set; }
    public IList<TestResult> Results { get; set; }
}

class TestResult
{
    public int Id { get; set; }
    public Test Test { get; set; }
}
```

With the following configuration...

``` C#
modelBuilder.Entity<Test>().HasKey(t => new { t.Assembly, t.Class, t.Name });
```

I'm trying to change the name of the foreign key properties using the following configuration.

``` C#
modelBuilder.Entity<Test>().HasMany(t => t.Results).WithOne()
    .HasForeignKey("Assembly", "Class", "Name");

// Or

modelBuilder.Entity<TestResult>().HasOne(r => r.Test).WithMany()
    .HasForeignKey("Assembly", "Class", "Name");

```

But on `TestResult` I end up with one navigation...
- Test

Two foreign keys...
- Assembly, Class, Name :arrow_right: Test(Assembly, Class, Name)
- TestAssembly1, TestClass1, TestName1 :arrow_right: Test(Assembly, Class, Name)

And seven properties...
- Id
- Assembly
- Class
- Name
- TestAssembly1
- TestClass1
- TestName1
### Additional information

When I use the second option, the foreign key used by the navigation is correct.

In my project, `TestResult` is abstract and has three derived types.

**Comment by AndriySvyryd** [comment]
This is by design, when up call WithOne or WithMany without any arguments you are configuring the relationship to NOT have an inverse navigation. The conventions then create another relationship using the now free inverse navigation property.

**Comment by bricelam** [comment]
Lol, just another case of myopia. I knew the behavior, but forgot about my other nav prop. Thanks, Andriy!
