### ISSUE TITLE
Query: Crash when using EF.Property on non-entity range variable

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#4844]
``` c#
using (var context = CreateContext())
{
    var cs 
        = context.Customers.AsNoTracking()
            .Select(c => new Customer { CustomerID = EF.Property<string>(c, "CustomerID") })
            .Where(c => EF.Property<string>(c, "CustomerID") == "ANATR")
            .ToList();

    Assert.Equal(91, cs.Count);
}
```

Test 'Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QuerySqlServerTest.NAME' failed: System.NullReferenceException : Object reference not set to an instance of an object.
    Query\Internal\QueryBuffer.cs(103,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetPropertyValue(Object entity, IProperty property)
    Query\ExpressionVisitors\Internal\MemberAccessBindingExpressionVisitor.cs(205,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.MemberAccessBindingExpressionVisitor.GetValue[T](QueryContext queryContext, Object entity, IProperty property)
    at lambda_method(Closure , ValueBuffer )
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    Query\Internal\LinqOperatorProvider.cs(125,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    QuerySqlServerTest.cs(32,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QuerySqlServerTest.NAME()

**Comment by tuespetre** [comment]
What should this do, throw a `NotSupportedException`?

**Comment by ajcvickers** [comment]
Clearing milestone because we decided to close this and link the other issue on, "the other bug about projecting entity types," but I can't find that issue.

**Comment by ajcvickers** [comment]
We decided not to do this for now, but would reconsider it with more feedback and scenarios where it adds real value. Also, see #9764 which would make Customer an entity type and allow Property to work here.

**Comment by smitpatel** [comment]
@ajcvickers @anpete - should we improve exception message here?
