### ISSUE TITLE
Define non-abstract base classes for e.g. ModelSource and TransactionManager

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#4848]
There are classes which you need to provide for a new provider but for which you just have to write boilerplate code e.g.  `XyzModelSource` (where you just inherit from `ModelSource` and define a constructor), and `XyzTransactionManager` which feels like it could be defined just by telling you the type of the `XyzTransaction` - which also could be defined using a non-abstract base class. Feels like it would be easier to define a "do-nothing" base class for these but still allow overrides.

Similarly for `ValueGeneratorCache`.

**Comment by ajcvickers** [comment]
We should document that ModelSource and ValueGeneratorCache need to have provider types because these act as different caching units for different providers. Not sure about TransactionManager.

**Comment by rowanmiller** [comment]
@ajcvickers can you just confirm if TransactionManager could be changed

**Comment by rowanmiller** [comment]
Feel free to close if it can't be

**Comment by ajcvickers** [comment]
We currently have two different concrete sets of implementations of the members of IDbContextTransactionManager in our code: InMemoryTransactionManager, and RelationalConnection. The RelationalConnection implementations are shared by all relational providers.

The in-memory implementation has the ability to ignore/not ignore transactions and returns a null implementation or throws. It is conceivable that other providers might want to share the in-memory implementation so we could extract a base class here, but the value seems rather small. Will let triage team decide, but on balance I don't think it is worth doing anything here.

**Comment by ajcvickers** [comment]
Still think we should document why providers must provide an use their own classes for ValueGeneratorCache and ModelSource.

**Comment by lajones** [comment]
If `InMemoryTransactionManager` is meant to be used generally (e.g. by non-relational providers) should we move it into Core (and perhaps rename it)?
