### ISSUE TITLE
IMaterializerFactory - not specific enough?

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#4849]
Probably a coding issue (perhaps a docs issue).

There are two instances of `IMaterializerFactory` - one in `Relational` in namespace `Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal` and one in `InMemory` in namespace `Microsoft.EntityFrameworkCore.Query.Internal`.

Because they are in such generic namespaces it feels like either we should rename these to be specific to the project of which they are a part - `IInMemoryMaterializerFactory` etc. Or we should decide on a common interface and move it into `EntityFrameworkCore`. At the moment the two interfaces look quite different so I'm tending towards the former approach.

Similarly for classes implementing these interfaces.

**Comment by rowanmiller** [comment]
Closing as these are internal types. They can be changed in the future if needed.
