### ISSUE TITLE
Code First: Consider going "all-in" on nested closure

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#4856]
Several folks expressed usability concerns re our current "dual" mode fluent API patterns. The main problem is that it is natural (for some users at least) to want method chaining for _sibling_ configuration; not for _child_ configuration. E.g.You can't currently easily do this:

``` c#
modelBuilder
    .Entity<Foo>()
    .Entity<Bar>()
```

**Comment by gdoron** [comment]
@anpete 
The more usable thing that is missing is moving from one child configuration to another.
e.g. changing the column type of two columns with one chain.
NHiberante has it, though if not designed right, it can cause people to use invalid configurations.

**Comment by anpete** [comment]
Related to #4960

**Comment by divega** [comment]
We decided not to do it.
