### ISSUE TITLE
Add support for ComplexTypeSerialization

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/efcore#4859]
SQL server and other database engines are supporting XML/JSON as a datatype, please consider creating a data annotation that will allow the serialization of complex types to a XML/JSON or nvarchar(max) property; the  complex property would not be directly mapped to a data column i.e.

[ComplexTypeSerializedAs(Format =[JSON/XML], Column = "EntityPropertyDataColumName"]
public ComplexType EntityPropertyName
{ get; set; }

**Comment by rowanmiller** [comment]
This is already tracked as part of https://github.com/aspnet/EntityFramework/issues/246

> When doing this we should consider different strategies for how the data is stored. In EF6 we had a column in the parent table for each property in the complex type. Another strategy that folks may want to chose if serializing the data as JSON/XML etc. (see #3486)
