### ISSUE TITLE
dotnet ef migrations add looks for a weird non-existent version of Newtonsoft.Json

### ISSUE THREAD

**Issue by rajajhansi** [dotnet/efcore#4862]
I was able to get dotnet ef running i.e., showing the command line options. But, when I tried to run dotnet ef migrations add <name>, I got a weird error.

λ `dotnet ef migrations add v1`
`System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

There is no 8.0.0.0 version of Newtonsoft.Json available as nuget package. There is 7.0.1, 8.0.1 and 8.0.3. At  least in the older version i.e. full .NET version, there is a binding redirect option but in newer version, it is all in project.json. Add to that the confusion introduced by the NETStandard.Library and NETStandard.Platform and different teams like ef, dotnetcore running on their own versions. Every sample application in the respective github repository is using different versions of NETStandard.Library and NETStandard.Platform and their own dependencies. I must say RC2 is like it is in Alpha stage and very disappointing to see things change every few months.

**Comment by bricelam** [comment]
Also tracked by parent item #3925
