### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by shumtn** [dotnet/efcore#4863]
Postgresql support requests to join our project need Postgresql, I also very like it, thank you！

**Comment by davidroth** [comment]
It's being worked on: (Community)
https://github.com/npgsql/npgsql

**Comment by shumtn** [comment]
npgsql? can be used in asp.net core rc2 in it?

**Comment by rowanmiller** [comment]
There is a package on NuGet.org that works with RC1. I don't think the current code base works with the latest RC2 builds, but it will catch up when (or very close to when) we ship RC2.
