### ISSUE TITLE
Visual location of table fields change after update model from database

### ISSUE THREAD

**Issue by YovavGad** [dotnet/efcore#4864]
When updating a database table, the updated fields go to the top of the list on the table in the schema,
The EDMX file XML needs to be edited manually in order to fix it...
It would be great if EF can maintain the same field location as it appears in the database table.

**Comment by rowanmiller** [comment]
This is an EF6.x issue, which belongs on the EF6 project site - http://entityframework.codeplex.com/. That said, this isn't something we would really fix due the relative priority compared to other issues. We would be very willing to accept a contribution that addressed it though.
