### ISSUE TITLE
Which DB ASP.NET used after deployed to IIS?

### ISSUE THREAD

**Issue by hepower** [dotnet/efcore#4897]
Hi all,

I have below configure in my ASP.NET5 demo app . in appsettings.json.

``` json
  "Data": {
    "DefaultConnection": {
      "ConnectionString": "Server=(localdb)\\mssqllocaldb;Database=aspnet5-ASP-3f26179a-584d-4169-8c18-26d0a8ce363e;Trusted_Connection=True;MultipleActiveResultSets=true"
    }
```

But after I deployed my app to local IIS services, I am not sure which DB it is using, but not this one(since I compare the data of a model list, different with the DB in table), seems it create a new DB, but I dont' know where it is.

**Comment by OsamaAbuSitta** [comment]
check IIS connection string from IIS manager

**Comment by rowanmiller** [comment]
@hepower your context will connect to whatever database is configured in Startup.cs. If you are using the default project template, then it will be SQL Server with the connection string pulled from the `Data:DefaultConnection:ConnectionString` configuration value. There is code that populates config from `appsettings.json` followed by environment variables. 

There is nothing else magic that happens in deployed applications etc.
