### ISSUE TITLE
Question: Are Repositories need any longer?

### ISSUE THREAD

**Issue by LorenDorez** [dotnet/efcore#4899]
I was doing some research and someone pointed out that Line 24 of the DBContext Class states

> DbContext is a combination of the Unit Of Work and Repository patterns.

Does this mean that we no longer need to abstract EF to a Repository and then use and Interface to inject it into Controllers?

**Comment by rowanmiller** [comment]
It's really up to you. There are two main reasons you may want to introduce a repository which are not handled by `DbContext`:
* Removing any strong coupling between your app logic and data access layer. Though in reality, even with this abstraction it is very difficult to swap out a data access layer unless you build and test for multiple data access technologies right from the start.
* Constraining the operations that the app layer can perform on the database. `DbContext` exposes `IQueryable` so the app can compose any query allowed by LINQ. Repositories that don't return `IQueryable` can help you control what is sent to the database.

Ultimately it comes down to a philosophical/style/preference decision. Many apps have been built successfully using either approach.

**Comment by LorenDorez** [comment]
@rowanmiller Thanks for the insights. I currently working on a project in which i find my repositories have a lot of methods like FindById, FindByName, FindBy.... and also a lot of dynamicness needed for When to Include and When to OrderBy etc..

I just started research <Expression<Func<>> to handle the dynamic-ness of when to Include certain tables and when not to and came across a lot of article stating there isnt a new for Repos with the new EF7 so figured it was better to go to here any get some insights.

**Comment by ilmax** [comment]
No, repository pattern for EF context is evil! Just don't use it!

**Comment by ge6a93** [comment]
@ilmax I personally prefer using repositories in my data access layer for encapsulating DbContext, so other developers can't use it directly in the application and create repetitive queries. I'd like to hear your point of view why not to use this approach.

**Comment by bricelam** [comment]
FYI, [Programmers Stack Exchange](http://programmers.stackexchange.com) is another good place to ask these types of design questions.

**Comment by ilmax** [comment]
@ge6a93 this is not the best place to discuss design, anyway there are a [tons](https://lostechies.com/jimmybogard/2012/10/08/favor-query-objects-over-repositories/) of [good](http://rob.conery.io/2014/03/04/repositories-and-unitofwork-are-not-a-good-idea/) posts int the wild on this same subject :)

**Comment by rowanmiller** [comment]
Closing this one out as I think we have addressed everything from the EF side.

**Comment by LorenDorez** [comment]
I posted this on Stack Exchange as suggested. I would appreciate the discussion continueing there

http://programmers.stackexchange.com/questions/314266/are-repositories-needed-any-longer-in-asp-net-5-ef7
