### ISSUE TITLE
Entire SQL connection string, including password is logged 

### ISSUE THREAD

**Issue by skofman1** [dotnet/efcore#4930]
I'm using EntityFramework 7.0.0-rc1-final in my service, and found that the full connection string to my SQL DB, including password is logged:
`Microsoft.Data.Entity.Storage.Internal.SqlServerConnection: Opening connection 'Server=tcp:nuget-dev-stage.database.windows.net,1433;Database=nuget-dev-stage;User ID=admin@nuget-dev-stage;Password=**mypassword**;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'.`

According to the documentation here: https://github.com/aspnet/EntityFramework/wiki/Security#security-guarantee-messages-do-not-contain-data-store-credentials
This is not supposed to happened.

**Comment by maumar** [comment]
This is already fixed in https://github.com/aspnet/EntityFramework/pull/3800
