### ISSUE TITLE
Adding Migrations/Listing DB Context when your DB Context isn't in the root

### ISSUE THREAD

**Issue by falconmick** [dotnet/efcore#4939]
Hey guys.

I have a DBContext inside of a folder like so ./Model/MyCustomDbContext

When I try dnx ef dbcontext list -p "MyCustomDbContext" -v i get the following error:
The project 'MyCustomDbContext' wasn't found. Ensure it's referenced by the current project.

But when I cd into the folder I get:
Error: Unable to resolve project from C:<path to proj><db project>\Model

This also happens for migrations add.

Any help here?? I really don't want to move my DBContext into the root folder... Also I have another folder on the root called Partial in which I have implimented the other part of the partials and added things to em.

**Comment by rowanmiller** [comment]
I think you want `-c` for context rather than `-p` for project right?

**Comment by rowanmiller** [comment]
Closing as we are pretty confident that the wrong parameter name was the issue, but feel free to reply and/or re-open if that is not the case.
