### ISSUE TITLE
Using TFV with FromSQL query as inline with linq does not keep parameters

### ISSUE THREAD

**Issue by rposener** [dotnet/efcore#4966]
Consider this Query:

``` c#
var query = from s in this.context.Staff.FromSql("SELECT * FROM [Entity].[tvf_Staff_Search](@p0)", Term)
                        join d in this.context.Departments.FromSql("SELECT * FROM [Entity].[tvf_Department_Search](@p0)", "")
                        on s.DepartmentId equals d.DepartmentId
                        select new Dtos.Staff.Staff
                        {
                            Active = s.Active,
                            AdminId = s.AdminId,
                            Name = s.Name,
                            Department = new Dtos.Reference.Lookup
                            {
                                Id = d.DepartmentId,
                                Name = d.Name
                            },
                            StaffId = s.StaffId
                        };
            return await query.ToArrayAsync();
```

The parameters to the TVF's are all the same even if passed in each.  I realize this is because of the naming is the same, but combined with the composability of LINQ this could be an issues in some places.  It would be perferrable if the FromSql could track and rename parameters if there is such a conflict.

**Comment by rowanmiller** [comment]
Hey,

The issue is that relying on the `@p0` syntax doesn't work when you compose things together. The parameter names are generated at the whole query level and not just the `FromSql` method level. So the `""` in your second call to `FromSql` is probably called `@p1`. 

After discussing this, we are going to stop using that syntax in our documentation and use the `{0}`, `{1}` syntax instead - which will cause EF to insert the name of the parameter it chose for the values you pass.

So we'll correct the docs on our side, and you should adjust the query to look like this:

```c#
var query = from s in this.context.Staff.FromSql("SELECT * FROM [Entity].[tvf_Staff_Search]({0})", Term)
                        join d in this.context.Departments.FromSql("SELECT * FROM [Entity].[tvf_Department_Search]({0})", "")
                        on s.DepartmentId equals d.DepartmentId
                        select new Dtos.Staff.Staff
                        {
                            Active = s.Active,
                            AdminId = s.AdminId,
                            Name = s.Name,
                            Department = new Dtos.Reference.Lookup
                            {
                                Id = d.DepartmentId,
                                Name = d.Name
                            },
                            StaffId = s.StaffId
                        };
            return await query.ToArrayAsync();
```

~Rowan

**Comment by rposener** [comment]
Great - thanks for the response and info.  I really like where EF core is headed - was excited to see the FromSql extension at your talk at Build.
