### ISSUE TITLE
SQlite: Exception "ExecuteNonQuery can only be called when the connection is open."

### ISSUE THREAD

**Issue by mtycholaz** [dotnet/efcore#4967]
I've been running on the 7.0.0-beta8 and recently updated to the new rc1. I'm now getting this error, although I'm not certain why it's happening. I have a feeling it may be related to the backgroundtask thread and main application thread trying to access the database at the same time (maybe?).

Reverting back does solve my problem.

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing? Can you also provide full details of the error you are seeing (message and stack trace).

**Comment by mtycholaz** [comment]
Here's the message and stack

ExecuteNonQuery can only be called when the connection is open.

`   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c.<ExecuteNonQuery>b__13_0(DbCommand cmd, IRelationalConnection con)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func``3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.EnableForeignKeys()
   at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator``2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator``2.MoveNext()
   at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0``1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator``2.MoveNext()
   at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor``1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List``1..ctor(IEnumerable``1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable``1 source)
   at communiKate.Core.Service.MessageService.<GetAllMessagesAsync>d__5.MoveNext()`

And here's the offending line

`messages = messageService.GetAllMessagesAsync().Result.ToDomain().ToList();`

This is what `GetAllMessagesAsync()` looks like:

```
public async Task<IList<IMessage>> GetAllMessagesAsync()
        {
            var list = repoService.Where<Message>()
                .Include(m => m.Contact)
                .Cast<IMessage>()
                .ToList(); //why does ToListAsync() hang?? Changed from ToListAsync to ToList for now

            return list;
        }
```

**Comment by rowanmiller** [comment]
@mtycholaz There isn't enough info in the code you provided to reproduce this. Were after something we can run to show the error you are hitting and debug it. Perhaps you could adjust the following code listing to show the issue (the code executes successfully on RC1).

```c#
using Microsoft.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Repro.RC1
{
    public class Program
    {
        static void Main(string[] args)
        {
            using (var db = new TestContext())
            {
                db.Database.EnsureCreated();
            }

            var messages = GetAllMessagesAsync().Result;
            Console.WriteLine(messages.Count);
        }

        public static async Task<IList<IMessage>> GetAllMessagesAsync()
        {
            using (var db = new TestContext())
            {
                var list = db.Messages.OfType<Message>()
                    .Include(m => m.Contact)
                    .Cast<IMessage>()
                    .ToList();

                return list;
            }
        }
    }

    public class Message : IMessage
    {
        public int MessageId { get; set; }
        public string MessageText { get; set; }

        public int ContactId { get; set; }
        public Contact Contact { get; set; }
    }

    public interface IMessage
    {
        Contact Contact { get; }
    }

    public class Contact
    {
        public int ContactId { get; set; }
        public string Name { get; set; }
    }

    public class TestContext : DbContext
    {
        public DbSet<Message> Messages { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=Message.db");
        }
    }
}
```

**Comment by mtycholaz** [comment]
I'm going to try your example when I get home. I know it's not a lot to go on, but unfortunately this is "one of those" bugs. I have unit tests that verify add/removing/reading items from the database, but the actual app throws an error. Somehow, somewhere, something is causing this. For now I've reverted back to beta-8 until this problem is solved. I'll provide more as this develops. Here's some of the details of the app

1. It's a JavaScript/Html that calls a WinRT library that calls a C# library
2. Ioc is used in the project, and their is only one database context managed by the container (LightInject)
3. There are background tasks that also read/write to the database.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details

**Comment by mtycholaz** [comment]
Sorry, I haven't had time to investigate further yet. For now I've reverted back to beta8.
