### ISSUE TITLE
Support SQL Server FILESTREAM

### ISSUE THREAD

**Issue by pankleks** [dotnet/efcore#4983]
Hi,

How can I mark column as FILESTREAM?

I created following table:

```
create table Document (
    Id UNIQUEIDENTIFIER ROWGUIDCOL PRIMARY KEY,
    Data VARBINARY(MAX) FILESTREAM
)
```

When I generated code using scaffold it does not look like anything specific is generated to mark it as FILESTREAM.

Thanks!

**Comment by rowanmiller** [comment]
We currently don't have support for `filestream`. You may just be able to treat it as a `varbinary` column... but of course you wouldn't get streaming. Moving this to the backlog to support post v1.0.0

**Comment by divega** [comment]
Closing as dupe of #4573.
