### ISSUE TITLE
"EntityFramework.SQLite": "7.0.0-rc1-final" get Internal compiler error when used with Microsoft.OData.Client

### ISSUE THREAD

**Issue by rovernant** [dotnet/efcore#4984]
Hello guys,

The issue is similar to this one https://github.com/aspnet/EntityFramework/issues/4511 .
EntityFramework.SQLite (7.0.0-rc1-final) cause several compiler errors when used with Microsoft.OData.Client (v 6.15.0) in one project when build in Release mode of Universal Windows application:
_The type name 'RCWAdapterClass' does not exist in the type 'System.Collections.Generic.IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_Generic_IEnumerable_A_System_Collections_IEnumerable_V__V__V__V__V__V__V__V__V___Impl'  in ImplTypes.g.cs_  

We should release our application at the end of the spring. 
So is there any workaround or some hotfix for this issue? Or any chance that rc2 will be released before summer?

**Comment by rowanmiller** [comment]
This should all be fixed in RC2. In RC1 we had a whole bunch of custom stuff around reflection info to support .NET Native. In RC2 this all goes away thanks to some improvements from the .NET Native team. Unfortunately you can't try it out just yet, as you'll need a UWP tooling update to support RC2.
