### ISSUE TITLE
[EF7] Error with "Include" related entites

### ISSUE THREAD

**Issue by GregH44** [dotnet/efcore#4992]
Hi everyone !

I work EF 7.0.0-rc1-final.
I have an error with Include related entities.

Here is my Get method :

```
public virtual TEntity Recuperer(Expression<Func<TEntity, bool>> filter, params Expression<Func<TEntity, object>>[] includeProperties)
{
  try
  {
    IQueryable<TEntity> query = dbSet;

    if (filter != null)
    {
      query = query.Where(filter);
    }

    if (query.Count() > 0 && includeProperties.Length > 0)
    {
      foreach (var includeProperty in includeProperties)
      {
        query = query.Include(includeProperty);
      }
    }

    return query.FirstOrDefault();
  }
  catch (Exception ex)
  {
    throw new GenericRepositoryException(correlationId, ex);
  }
}
```

And here is my call :

```
Expression<Func<TEntity, bool>> filter = ldo => ldo.RelatedEntity1.Number == '123456'
                    && ldo.RelatedEntity1.Key == '0'
                    && ldo.RelatedEntity2.Code == "ABC"

var entity = Repository.Get(filter, ldo => ldo.RelatedEntity3);
```

When I execute this code, I have this error :

> Unable to cast object of type System.Linq.Expressions.FieldExpression to type System.Linq.Expressions.ParameterExpression.

But when I remove my include property "ldo => ldo.RelatedEntity3", it works.

I have 2 questions :
1) Why I have this error ?
2) Does it exist a workaround to load related entities every time ?

Thank you for your help.

Greg

**Comment by divega** [comment]
@GregH44 could you include your entity types in the repro? Thanks.

**Comment by rowanmiller** [comment]
Closing as we have not heard back with requested details
