### ISSUE TITLE
After upgrading to 1.0.0-rc2-20221 exception adding migration

### ISSUE THREAD

**Issue by WhiteKarma** [dotnet/efcore#4993]
Hello all, 

After upgrading to rc2-20221, on windows and on UBUNTU i get the following exception on both systems:
dnx ef mig rations add initial
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformA
bstractions.ILibraryManager Microsoft.Extensions.PlatformAbstractions.PlatformSe
rvices.get_LibraryManager()'.
   at Microsoft.Data.Entity.Commands.Program.ValidateProject(String targetProjec
t)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass2_7.<Main>b__15()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(St
ring[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b_
_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
C:\Users\DEV\Desktop\DNXTest\DNXTest\src\DNXTest [master +1 ~3 -0 !]>

My project.json is this:
{
  "userSecretsId": "aspnet5-DNXTest-7773f097-f72d-4ee4-bcbf-ef291e19d8b4",
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "runtime.linux.System.Net.NetworkInformation": "4.1.0-beta-23516",
    "runtime.unix.System.Net.Security": "4.0.0-beta-23516",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework7.Npgsql": "3.1.0-rc1-3",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Formatters.Json": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Razor": "4.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Newtonsoft.Json": "8.0.3"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}

And my global.json is:

{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc2-20221"
  }
}

Can you please help, 

Thanks in advance

**Comment by ErikEJ** [comment]
Did you really type: mig rations  ?

**Comment by WhiteKarma** [comment]
sorry, no it was the copy from the command line, thanks for your answer

**Comment by davidfowl** [comment]
@WhiteKarma why did you update the dnx to rc2 and leave everything in your project.json as RC1?

**Comment by WhiteKarma** [comment]
I tried updating the references with 1.0.0-rc2-20221 in the ide and saved, but on the output it said it could not found them, so i put it back... Is 1.0.0-rc2-20221 the right string to add to the dependencies?

Thanks in advance

**Comment by WhiteKarma** [comment]
The stack trace i got on UBUNTU 14.04 Server 64 is:

dev@ubuntu:~/DNXTest/src/DNXTest$ dnx ef migrations add init
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.ILibraryManager Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_LibraryManager()'.
   at Microsoft.Data.Entity.Commands.Program.ValidateProject(String targetProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass2_7.<Main>b__15()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by WhiteKarma** [comment]
Ok, i've tried to update the dependencies that had "1.0.0-rc1-final" to "1.0.0-rc2-*" but i got the following message from the output:

    Unable to locate Dependency Microsoft.AspNet.Authentication.Cookies >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.AspNet.IISPlatformHandler >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.AspNet.Server.Kestrel >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.AspNet.StaticFiles >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.AspNet.Tooling.Razor >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.CodeGenerators.Mvc >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.Configuration.FileProviderExtensions >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.Configuration.Json >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.Configuration.UserSecrets >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.Logging >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.Logging.Console >= 1.0.0-rc2-*
    Unable to locate Dependency Microsoft.Extensions.Logging.Debug >= 1.0.0-rc2-*

all  12  that i've changed give me that error, what is the correct version string, please?

Thanks in advance,

**Comment by WhiteKarma** [comment]
I found a folder here C:\Users\DEV\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc2-20221\bin with a big list of dlls, but i could not find any of asp.net dlls, can you please help @davidfowl ?

Thanks in advance

**Comment by BrennanConroy** [comment]
You are using old package names, try changing the AspNet.* ones to AspNetCore.*

**Comment by WhiteKarma** [comment]
Thank you @BrennanConroy will try that

**Comment by WhiteKarma** [comment]
Hmmm, too many breaking changes... Going back to rc1-final. 
Thank you all!
