### ISSUE TITLE
Using commands on UWP project can lock the VS debugger files

### ISSUE THREAD

**Issue by geoffmmorgan** [dotnet/efcore#4997]
Oftentimes when I am using EF core in my UWP project and I am generating migrations, the EF commands will lock the Appx file preventing redeployment. Usually the flow goes like this:
1. Create a new initial migration
2. Run the application to create the SQLite database
3. Stop the application
4. Make some change unrelated to Models/EF/Database
5. Attempt to run the application again and get the following error

Error DEP0500 : The folder "C:\Users\me\Source\Repos\MyApp\MyApp\MyApp\bin\x86\Debug\AppX" could not be deleted. 
Access to the path 'mscordbi.dll' is denied. 

Removing EntityFramework.Commands from my project.json and restarting VS fixes the issue

**Comment by divega** [comment]
@natemcmaster any thoughts on this?

**Comment by natemcmaster** [comment]
Looks like a bug. Initial guess: one of two things is going on here. (1) the user's assembly isn't being unloaded from the powershell host in PMC. (2) the launch in step 3 above didn't properly unload the assemblies. Obviously needs more investigation.

**Comment by bricelam** [comment]
> the user's assembly isn't being unloaded from the powershell host in PMC

This *should* never happen in the first place. We shadow copy the assembly and load it into a temporary domain.

**Comment by geoffmmorgan** [comment]
I can confirm this is still occurring in Visual Studio 2015 Update 2 with EF Core RC2. Same error message as previously.

**Comment by natemcmaster** [comment]
Marking for re-triage: this may change due to changes in tools architecture for #5334. This can wait for post RTM. We believe the work here will mostly be to verify the new architecture solves the problem.

Also, I suspect this is caused by a .NET Native compile build being triggered in the solution, and not by loading the tooling assembly in powershell as I first guessed.

**Comment by rowanmiller** [comment]
We need to isolate this and hand off a bug if it is external

**Comment by natemcmaster** [comment]
I could not reproduce this. As the original error mentioned, "mscordbi.dll" was the locked file. This file is part of the VS debugger, which we don't load as a part of EF command execution. My guess is something in the debugger was not correctly exiting. 

@geoffmmorgan if this happens again, I recommend using something like ["Process Explorer"](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) to see if there is a file lock. It would be good to know what is still holding onto the file.
