### ISSUE TITLE
Question: How to get EF's ILoggerFactory without going through the DbContext?

### ISSUE THREAD

**Issue by jpoehls** [dotnet/efcore#5004]
How can I get EF's `ILoggerFactory` without having to go through the `DbContext`?

This is how we're constructing `DbContext` objects in our app... roughly...

``` csharp
class MyDbContext : DbContext { ... }
class MySqlServerDbContext : MyDbContext { ... }

IServiceCollection services; // passed in from elsewhere
ISetupSettings config; // passed in...

var efBuilder = services.AddEntityFramework().AddSqlServer();
var initOptions = dbOpts => {
    dbOpts.UseSqlServer(config.Database.ConnectionString);
};
efBuilder.AddDbContext<MySqlServerDbContext>(initOptions);
services.AddScoped<MyDbContext>(x => {
    var ctx = x.GetService<MySqlServerDbContext>();
    return ctx;
});
```

All of the examples I've seen getting the `ILoggerFactory` do something like:

``` csharp
var ctx = x.GetService<MySqlServerDbContext>();
ctx.GetService<ILoggerFactory>().AddConsole();
return ctx;
```

But if I construct multiple `DbContext` objects using that, then I believe I'm calling `AddConsole()` to the same `ILoggerFactory` instance multiple times.

I'm expecting there to be some way to get the `ILoggerFactory` from the `EntityFrameworkServicesBuilder` or something similarly high level so that I don't have to do that logic for every `DbContext` I instantiate. Is that possible?

**Comment by divega** [comment]
In RC2 bits you can pass the `ILoggerFactory` instance you want all MyDbContext instances to use in the options. E.g. based on your code snippets:

``` C#
efBuilder.AddDbContext<MySqlServerDbContext>(options => options
     .UseSqlServer(config.Database.ConnectionString)
     .UseLoggerFactory(loggerFactory));

PS: No need for the curly braces on single line lambdas, and specifying a service type `MyDbContext` that has an implementation type of `MySqlServerDbContext` should be as simple as calling `services.AddScoped<MyDbContext, MySqlServerDbContext>()` and should not need to use the lambda overload of `AddScoped`.

**Comment by jpoehls** [comment]
Thanks! That makes sense to me. We're still on RC1 but I'll give this a shot when we upgrade to RC2.
