### ISSUE TITLE
Query: This query is known to the state of Califonia to produce inefficient SQL generation when selecting and joining

### ISSUE THREAD

**Issue by joshcomley** [dotnet/efcore#5025]
I believe there is a bug with a certain scenario of SQL generation on SQL Server.

I have created a fully self contained solution in a GitHub repo to demonstrate the issue:

https://github.com/joshcomley/EntityFrameworkSqlQueryBug

Suppose we have a list of **customers**, who each have a collection of **products**.

I could run this query:

```
var query = db.Customers.Include(p => p.Products);
var products = query.ToList();
```

And get these two SQL queries:

```
SELECT [p].[CustomerId], [p].[FirstName], [p].[LastName]
FROM [Customers] AS [p]
ORDER BY [p].[CustomerId]

SELECT [p0].[ProductId], [p0].[CreatedByUserId], [p0].[CustomerId], [p0].[DateCreated], [p0].[LastModifiedByUserId], [p0].[Name], [p0].[Price], [p0].[SomeSecretFieldThatShouldNotBeReturned]
FROM [Products] AS [p0]
INNER JOIN (
    SELECT DISTINCT [p].[CustomerId]
    FROM [Customers] AS [p]
) AS [p1] ON [p0].[CustomerId] = [p1].[CustomerId]
ORDER BY [p1].[CustomerId]
```

However, suppose I want to do some kind of selection of my fields:

```
var query = db.Customers.Select(p => new
{
  p.FirstName,
  p.LastName,
  Products = p.Products.Select(x => new
  {
    x.Name,
    x.CreatedByUserId
  })
});
var result = query.ToList();
```

By this point, when `query.ToList()` is run, I end up with only this query:

```
SELECT [p].[FirstName], [p].[LastName], [p].[CustomerId]
FROM [Customers] AS [p]
```

And in fact, no more SQL executes until I iterate through each child result:

```
foreach (var customer in result)
{
  // Only when we first iterate customer.Products below do we run the next SQL query
  foreach (var product in customer.Products)
  {
  }
}
```

For every single customer, when we get to the products collection, another individual query is executed:

```
SELECT [x].[CustomerId], [x].[Name], [x].[CreatedByUserId]
FROM [Products] AS [x]
```

So for every customer result, we end up with an entire selection on the products table. So if we return 300 customers, we run 301 individual SQL queries, and 300 of those select the entire products table :) not very friendly for servers!

I hope this helps outline the bug.

I've tested the same code in EF6, and the SQL generated for an identical query and code is as follows:

```
SELECT 
    [Extent1].[CustomerId] AS [CustomerId], 
    [Extent1].[FirstName] AS [FirstName], 
    [Extent1].[LastName] AS [LastName], 
    [Project1].[C1] AS [C1], 
    [Project1].[Name] AS [Name]
    FROM  [dbo].[Customers] AS [Extent1]
    LEFT OUTER JOIN  (SELECT 
        [Extent2].[CustomerId] AS [CustomerId], 
        [Extent2].[Name] AS [Name], 
        1 AS [C1]
        FROM [dbo].[Products] AS [Extent2] ) AS [Project1] ON [Extent1].[CustomerId] = [Project1].[CustomerId]
    ORDER BY [Extent1].[CustomerId] ASC, [Project1].[C1] ASC
```

**Comment by joshcomley** [comment]
I should add that so long as the current user has enough permissions and has SQL Server installed, the project will create the database, create the tables and seed it. This will happen *every* time you run the app as it is in its current state.

**Comment by rowanmiller** [comment]
@maumar we're guessing this is RC1 and the nav prop work in RC2 will solve this

**Comment by joshcomley** [comment]
@rowanmiller This occurs in the latest RC2 version

**Comment by rowanmiller** [comment]
@joshcomley thanks for confirming, we've put this on our list to fix for 1.0.0 release

**Comment by maumar** [comment]
this has been improved by https://github.com/aspnet/EntityFramework/commit/05b24c30b8b8693bc3daa78b195831bf45749a3f

We still produce N+1 queries, but no longer query all the rows in the child queries, just the relevant ones, like so:

```sql
            SELECT [p].[FirstName], [p].[LastName], [p].[Id]
            FROM [Customers] AS [p]
```

```sql
                        SELECT [x].[Name], [x].[CreatedByUserId]
                        FROM [Products] AS [x]
                        WHERE @_outer_Id = [x].[CustomerId]
```

**Comment by maumar** [comment]
sending to re-triage

**Comment by rowanmiller** [comment]
The n+1 issue is already tracked by other issues, so closing this one out.
