### ISSUE TITLE
Issue with EF7 in UWP App

### ISSUE THREAD

**Issue by WiliamGP** [dotnet/efcore#5026]
When I compile and use my app using the .NET Native it crashes, the exception report is:

> MakeGenericMethod_NoMetadata, Microsoft.Data.Entity.Metadata.Internal.ClrCollectionAccessorFactory.CreateGeneric<Mercador... For more information, visit go.microsoft.com/fwlink/?LinkId=623485

I know that I need to add the directive Metadata in Default.rd.xml, but I dont know how to create the directive. I find this post with a related problem: [https://github.com/aspnet/EntityFramework/issues/3293](url)

I created this directive, but it did not work.

`<Type Name="Microsoft.Data.Entity.Metadata.Internal.ClrCollectionAccessorFactory{Microsoft.Data.Entity.Metadata.Internal.IClrPropertySetter}">
<MethodInstantiation Name="CreateGeneric" Arguments="Mercador.Models.DadosContext,System.Collections.Generic.List{Mercador.Models.ItemListaCompras},Mercador.Models.ListaCompras" Dynamic="Required" />
</Type>`

Someone that understand about this error can help me?

**Comment by thewindev** [comment]
I also have this issue. From what I heard, this will be fixed in RC2. Any news on when it will be released? My app is ready and I can't publish it because of this

**Comment by WiliamGP** [comment]
Hi @thewindev, I talked to the team of .NET, they said that this problem would be fixed with RC2, but the erros continue. I tried create the directive according with the arguments of method, but it didn't work.

**Comment by natemcmaster** [comment]
To fix this, update your tooling to .NET Native SDK >= 1.3.1. (See [this blog post](https://blogs.msdn.microsoft.com/visualstudio/2016/04/11/whats-new-in-vs-2015-update-2-for-universal-windows-developers/).) This version of the SDK includes a new compiler feature that removes the need to use runtime directives to get EF working. Our pre-release versions of the RC2 don't use runtime directives anymore. 

Although we don't have a firm shipping date, we are staging packages and stabilizing for release. Those packages are here: http://myget.org/gallery/aspnetrelease.

Please feel free to re-open if you encounter issues after upgrading to the newer SDK and newer versions of EF.
