### ISSUE TITLE
Creating a temporary DbContext

### ISSUE THREAD

**Issue by Heartsbane** [dotnet/efcore#5027]
I'm working with an ASP.NET 5 api project using EntityFramework v7.0.0-rc1-final. I'm trying to use the disconnected repository pattern from @julielerman EF6 course on Pluralsight, which uses a temporary context for each repository method, such as:

![image](https://cloud.githubusercontent.com/assets/7918993/14410330/26fc84d0-fefb-11e5-9284-aa43814a4050.png)

However, this throws a "System.InvalidOperationException" error. I'm not sure if this is by design or not. The more traditional approach of passing the context into the repository constructor and creating a private _context field works without any problems:

![image](https://cloud.githubusercontent.com/assets/7918993/14410375/23126cda-fefc-11e5-8283-108b9add03ff.png)

**Comment by Heartsbane** [comment]
After some more thought on this, I realized that by scoping the repository as transient in the Startup.cs file, I can achieve the same end result and don't need to create temporary context objects with using() inside each repository method, since each interaction with the repository will force a new instance with a new DbContext:

![image](https://cloud.githubusercontent.com/assets/7918993/14410442/9c13cdd0-fefd-11e5-99e4-e0767fd56261.png)

I'm still curious if the "System.InvalidOperationException" error thrown when trying to create a DbContext from inside the repository is by design.

**Comment by julielerman** [comment]
Yes! Dependency injection and IOC (via ASPNET Core services) FTW. In fact, I extended that to combining ASP.NET Core with an EF6 model still leveraging DI with ASP.NET COre’s injection services in the Feb 2016 MSDN Magazine article. https://msdn.microsoft.com/magazine/mt632269

Sorry if my older content led you astray.

Julie

**Comment by Heartsbane** [comment]
Good to know, thanks @julielerman! I'm a big fan of your Pluralsight work, and looking forward to more stuff on EF 7.
