### ISSUE TITLE
Knowing if Migrations were applied

### ISSUE THREAD

**Issue by stap123** [dotnet/efcore#5028]
I'm using rc1, trying to find a way of telling whether or not migrations have been applied (or are pending) either while calling Database.Migrate() or before I call it. I'm trying to know whether or not to call a separate method to seed some data but it seems to be a waste to call this if nothing has changed.

I was thinking that there might be something along the lines of the Database.EnsureCreated() method that returns a bool to tell me that the database was just created, but I can't find reference to anything. Is there any such method or way of getting to the information? 

Any help would be greatly appreciated.

**Comment by minterjiang** [comment]
来自我的华为手机-------- 原始邮件 --------主题：[aspnet/EntityFramework] Knowing if Migrations were applied (#5028)发件人：stap123 收件人：aspnet/EntityFramework 抄送：I'm using rc1, trying to find a way of telling whether or not migrations have been applied (or are pending) either while calling Database.Migrate() or before I call it. I'm trying to know whether or not to call a separate method to seed some data but it seems to be a waste to call this if nothing has changed.

I was thinking that there might be something along the lines of the Database.EnsureCreated() method that returns a bool to tell me that the database was just created, but I can't find reference to anything. Is there any such method or way of getting to the information? 

Any help would be greatly appreciated.

**Comment by rowanmiller** [comment]
You need to drop down to some of the lower level components to do this (at least at this stage)

```c#
using Microsoft.Data.Entity.Infrastructure;

...

var applied = context.GetService<IHistoryRepository>().GetAppliedMigrations();
var all = context.GetService<IMigrationsAssembly>().Migrations;
```
