### ISSUE TITLE
is mapping of DbGeography will be available on RTM release

### ISSUE THREAD

**Issue by ikourfaln** [dotnet/efcore#5030]
Hi,

We are working on a project with ASP.NET Core, and All our model and operations use DbGeography , so we really need this data type.
If it is not available, do you have any other solution, bcz we are already starting the asp.net core project.

**Comment by rowanmiller** [comment]
`DbGeography` is not supported as yet - and won't be for the initial 1.0.0 release. We won't add explicit support for this type, but it will be covered by a more general type conversion work item (https://github.com/aspnet/EntityFramework/issues/242). In the meantime you may be able to get away with mapping to string property and then wrapping that with a DbGeography property in your CLR class.

**Comment by ikourfaln** [comment]
thanx @rowanmiller for replay
