### ISSUE TITLE
is complex type support attribute such as JsonAttribute?

### ISSUE THREAD

**Issue by nepton** [dotnet/efcore#5031]
in our project we need save some complex type to json serialized string to database table. these complex type does not use index, search, order ....   so i think save to json string is more better.
i plan to write some code to implement a attribute named JsonAttribute in EF6, but finally failed,
i hope this feature is supportd in EF7 :)
thanks

**Comment by rowanmiller** [comment]
Not currently supported. Complex type support is tracked by https://github.com/aspnet/EntityFramework/issues/246 and the idea of allowing JSON storage is already captured in that issue (see third paragraph of description).
