### ISSUE TITLE
-e | --environment no longer available in dnx ef database update?

### ISSUE THREAD

**Issue by bigteejay** [dotnet/efcore#5041]
I see that someone [claimed](http://stackoverflow.com/questions/32937544/choose-config-json-version-during-database-update-after-migrations#comment53782757_32937544) this was available as of RC1 (I'm using RC1 final, update 1)

[This change](https://github.com/aspnet/EntityFramework/commit/7f48d0c0fca054ed70bebe0e8d2c58ee3cc3df9b#diff-b8c39a3f7fffa559788354a8e675e20eL111) shows checks and feedback to the user for environment switches were added at one point (to what appears the now "stale" [master](https://github.com/aspnet/EntityFramework/blob/master/src/EntityFramework.Commands/Commands/Program.cs) branch?)  The closest analog in the dev branch I could find is [here](https://github.com/aspnet/EntityFramework/blob/9dd83bdfd8fdc053820da646058d38a133aa8267/src/dotnet-ef/DatabaseUpdateCommand.cs) (I think?)

So, should I not be able to specify the environment when running `dnx ef database update -e Production`? Or am I doing it wrong in for my targeted runtime?  When I try (including the `-v` switch) I see that it is targeting the correct context, but with/out the switch it still targets my development database.

If I manually edit my "appsettings.json" connection string to match my "appsettings.Production.json" and try to update the database with `-v` it correctly targets the right database (and I can see the objects created when I check the in db.)

**Comment by rowanmiller** [comment]
@natemcmaster can you comment on how all this stuff works in .NET CLI land...

**Comment by natemcmaster** [comment]
> The closest analog in the dev branch I could find is here (I think?)

@bigteejay you are correct. "release" branch is our staging for RC2 and will be merged to "master" when RC2 is ready. EF RC2 doesn't support dnx commands anymore. This functionality moved to dotnet commands. You should be able to do `dotnet ef database update -e Production` with dotnet-cli when RC2 is released. This is already available on [our nightly feeds](https://github.com/aspnet/Home/wiki/NuGet-feeds). See https://github.com/aspnet/EntityFramework/blob/release/src/dotnet-ef/DatabaseUpdateCommand.cs#L25.

That said, RC1 dnx commands should support this `--environment` switch. See https://github.com/aspnet/EntityFramework/blob/master/src/EntityFramework.Commands/Commands/Program.cs#L77. If this is not working, it is a bug.
