### ISSUE TITLE
Is there a way to use the latest bits of EF while using ASP.NET Core RC1?

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#5042]
I do not want to use RC2 dotnet-cli, because [I kinda like using VS.](https://github.com/aspnet/cli-samples/issues/32#issuecomment-208431766)..
But I do want the new features and bug fixes of EF that were introduced after RC1.

Is it possible?
I hope it is/will, so the community can review the work done since RC1 before RC2 is released.

Thanks.

**Comment by divega** [comment]
EF Core and ASP.NET Core have many common dependencies and those have evolved a lot between RC1 and RC2, meaning they have lots of breaking changes. So no, mixing RC1 and RC2 bits won't work.

PS: I am not sure I understood the reason you don't want to use RC2.

**Comment by gdoron** [comment]
@divega From what I was told in the AspNetCore chat room in JabbR and in the link I linked above, I can not use VS if I use RC2 because VS tooling doesn't support the new changes, and I have to use VS code and some nasty customization to even being able to debug the application.

Is it not correct? can I still develop and debug as usual using VS?
Is there a sample MVC/API + EF application that uses RC2 that I can see how things has changed and are done now?

PS: Current VS code quality is somewhere between notepad and wordpad... :cry: 

Thanks.

**Comment by divega** [comment]
Ah, got it. It was actually clear, but somehow I misread your comment. Probably the best source of information about how the code looks like are the VS templates in the template repo.

**Comment by gdoron** [comment]
@divega I'll check the templates there, thanks.
But regarding the ability to use VS and RC2, is it possible?
Because if it's not, I'm afraid it doesn't worth it.

Thanks

**Comment by divega** [comment]
@gdoron You probably have to wait for VS tooling for RC2 to be published.
