### ISSUE TITLE
SoundCode

### ISSUE THREAD

**Issue by gparissis** [dotnet/efcore#5051]
I am wondering if there is an implementation in EF7 regarding the SOUNDEX function. For previous versions of EF we have the SoundCode function. In EF7 this kind of functionality or similar exist?

Thank you.

**Comment by rowanmiller** [comment]
This is not currently supported, but it would be enabled by https://github.com/aspnet/EntityFramework/issues/2850. For the moment you would need to drop down to raw SQL.
