### ISSUE TITLE
Conditionally updating navigation properties

### ISSUE THREAD

**Issue by sergeitemkin** [dotnet/efcore#5052]
We're having some trouble figuring out a way to conditionally update properties on entities when dealing with navigation properties. We're trying to implement a function `void UpdateEntity<T>(T entity, params Expression<Func<T, object>>[] updatedProperties)` that conditionally updates given properties on the entity.

Currently our strategy is to iterate through the list of updatedProperties and call `context.Entry(entity).Property(property).IsModified = true;`, which works perfectly for non navigation properties, for tasks such as this:

```
var entity = new ModelA()
{
    Id = existingId,
    Prop1 = "test"
}
context.UpdateEntity(entity, e => e.Prop1);
```

However, `EntityEntry<TEntity>.Property` doesn't seem to support navigation properties at this time as invoking something like `context.Entry(entity).Property(e => e.NavProperty)` throws an InvalidOperationException because `The property 'NavProperty' on entity type 'Model' could not be found. Ensure that the property exists and has been included in the model`.

Is there a proper way to do what we're trying to do?

**Comment by sergeitemkin** [comment]
Here's the source code to reproduce the problem we're having, if it helps:

    internal class Program
    {
        public class ModelA
        {
            public Guid Id { get; set; }
            public string Prop1 { get; set; }
            public ModelB Prop2 { get; set; }
        }

        public class ModelB
        {
            public Guid Id { get; set; }
            public ICollection<ModelA> ModelAs { get; set; }
        }

        public class TestContext : DbContext
        {
            public static TestContext Create()
            {
                var optionsBuilder = new DbContextOptionsBuilder();
                optionsBuilder
                    .UseSqlServer("data source=localhost;initial catalog=Test;MultipleActiveResultSets=True;Integrated Security=true;");

                return new TestContext(optionsBuilder.Options);
            }

            public TestContext(DbContextOptions options) : base(options) { }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<ModelA>((entity) =>
                {
                    entity
                        .HasOne(e => e.Prop2)
                        .WithMany(o => o.ModelAs);
                });

                modelBuilder.Entity<ModelB>();
            }
        }

        private static void Main(string[] args)
        {
            Guid modelId;
            using (var context = TestContext.Create())
            {
                context.Database.EnsureCreated();

                var tracked = context.Add(new ModelA()
                {
                    Prop1 = "test",
                    Prop2 = context.Add(new ModelB()).Entity
                });

                context.SaveChanges();

                modelId = tracked.Entity.Id;
            }

            // sometime later when the original DbContext is no longer available
            using (var context = TestContext.Create())
            {
                var model = new ModelA()
                {
                    Id = modelId,
                    Prop2 = null
                };

                // update only Prop2 on the model and leave Prop1 as is
                context.Entry(model).Property(m => m.Prop2).IsModified = true;
                context.SaveChanges();
            }
        }
    }

**Comment by rowanmiller** [comment]
The navigation property is really just a view over the foreign key properties, so rather than setting the navigation property as modified, you need to mark the foreign key as modified. In your case, the FK is a shadow property (not present in the entity class), so you would need to call:

```
context.Entry(model).Property("Prop2ID").IsModified = true;
```

I did open https://github.com/aspnet/EntityFramework/issues/5114 as it would be nice if setting the navigation property as modified would set the FKs modified for you.

**Comment by sergeitemkin** [comment]
Thanks @rowanmiller, can't believe I missed that!
