### ISSUE TITLE
Async versions of (Add/Remove/Update/Attach)Range methods that take IAsyncEnumerable

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#5058]
We have overloads of these methods that take IEnumerable, but not IAsyncEnumerable. This forces buffering when the sequence is async.

**Comment by TheAnachronism** [comment]
Why was this closed?
I'm not that familiar with ef core but I'm wondering why those overloads don't exist...

**Comment by roji** [comment]
@TheAnachronism note that inside AddRange, there's a simple enumeration over the given (non-async) enumerable. This means that there would be very little value in an AddRange accepting an IAsyncEnumerable over simply enumerating externally and calling Add each time.
