### ISSUE TITLE
Insertion Order RC1

### ISSUE THREAD

**Issue by deenairn** [dotnet/efcore#5067]
Adding things to a context via AddRange does not add entities to the DB in the anticipated order, i.e. with the lowest IDs corresponding to the earliest items added to the DbContext where the identity column is set to IDENTITY(1,1). Is the allocation of generated IDs entirely non-deterministic?

**Comment by gdoron** [comment]
Interesting, I didn't notice it, are all the inserted entities of the same type/table?
How many entities do you insert via `AddRange`? what is your max batch size?

BTW, since IDENTITY is surrogate key, do you really care about the ordering?

**Comment by ajcvickers** [comment]
@deenairn @gdoron The order in which entities begin being tracked by the context (whether through Add or AddaRange or any other mechanism) is not preserved. This is by design. The only way to ensure any specific key value is used is to assign that key value to the entity directly before adding it to the context.

**Comment by deenairn** [comment]
@gdoron I don't particularly care about the order of the IDs - but my product owner does. We have a scenario where they want the order to be preserved in the order the items are added to the application. In EF 6 - this just worked - but upgrading to EF7 - it seems the behaviour has changed. The number of entities added by AddRange is variable - it can be anything from 2 to a very large number. Start adding in batches and you'll notice the IDs are not the same order as they were in the underlying collection.

@ajcvickers thanks for clearing this behaviour up.

**Comment by gdoron** [comment]
@rowanmiller @ajcvickers   Is it possible to preserve the order for entities inside a collection?

It's really annoying to add an Order property just for this kind of stuff  

	Tips = new List<StoryTip>
	            {
	                new StoryTip
	                    {
	                        Text = "I just realized that after Sochi, I didn’t need to take those risks anymore.",
	                        Order = 1
	                    },
	                new StoryTip
	                    {
	                        Text = "I found the water to be much more forgiving when you land on your face.",
	                        Order = 2
	                    },
	                new StoryTip
	                    {
	                        Text =
	                            "I can’t duck-dive [under] a wave, so I sit on top of a surfboard and use a kayak paddle to get through the impact zone.",
	                        Order = 3
	                    },
	                new StoryTip
	                    {
	                        Text = "The day I get barreled is gonna be my best day ever.",
	                        Order = 4
	                    },
	                new StoryTip
	                    {
	                        Text =
	                            "I know there’s another female, God forbid, that’s gonna break her back. She’s gonna be lost without her sport. She’s gonna need to have that hope and really find herself as an athlete again.",
	                        Order = 5
	                    },
	                new StoryTip
	                    {
	                        Text = "Surfing, hands down, absolutely. That would be the only way I’d go back for one more.",
	                        Order = 6
	                    }
	            },
            
Had the StoryTips order were preserved, I could simply order by the Id.

**Comment by rowanmiller** [comment]
@gdoron we have ordered collection support on the backlog https://github.com/aspnet/EntityFramework/issues/2919. We don't do any general order preserving in EF as relationships etc. can have an impact on the order that data needs to be inserted.
