### ISSUE TITLE
Include multiple navigation properties of one entity

### ISSUE THREAD

**Issue by henkmollema** [dotnet/efcore#5068]
I have an entity with multiple navigation properties which I'd like to eagerly load when selecting the entity from the database. I known I can use `ThenInclude()` to select sub navigation properties of a entity, but how can I select sibling navigation properties of a single entity?

Consider a hierarchy like this:
- User
  - Blog
    - Subscribers
    - Blog Image
    - Posts

Selecting a user with it's blog along with the subscribers, image and posts of the blog results in this query:

``` csharp
context.User
       .Include(u => u.Blog)
       .ThenInclude(b => b.Subscribers)
       .Include(u => u.Blog)
       .ThenInclude(b => b.BlogImage)
       .Include(u => u.Blog)
       .ThenInclude(b => b.Posts)
```

Is this a correct query or am I missing something? I am using `v1.0.0-rc1-final`.

**Comment by mikes-gh** [comment]
Yes its a limitation and not one I am a fan of as if you examine the TSQL you will see in includes the contents of  Blog several times

see
https://github.com/aspnet/EntityFramework/issues/4490
