### ISSUE TITLE
Is there a way to only hydrate/set explicitly included properties

### ISSUE THREAD

**Issue by GrantErickson** [dotnet/efcore#5070]
It would be nice to have the option for EF to only hydrate explicitly included properties. The existing functionality will hydrate additional properties if they have already been loaded. 

Most of the time this is a good thing. However, it does seem a bit counter intuitive given the explicit nature of the include statements. I find there are times when I don't want to mess with a DTO and would like to serialize the object directly. 

The result is that I either end up serializing unwanted objects, pruning the object graph, or building a DTO. If the DTO ends up being nearly identical to the main object, I see this as unneeded code especially if the target is a JavaScript view model.

**Comment by rowanmiller** [comment]
@GrantErickson there are two ways you could do this:
* Use a smaller scope of the context. In general it is best to use a context for a short scope and then throw it away. If you used a new context for the query then there would be no existing objects that it would try to fix up navigation properties to.
* You could also use a NoTracking query, which will just give you results without tracking them in the change tracker, fixing up to existing objects, etc. (e.g. `context.Blogs.Where(b => b.Rating > 3).Include(b => b.Posts).AsNoTracking().ToList();`)
