### ISSUE TITLE
Query: Add unbounded result set warnings

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#5089]
Could warn in logger
Could throw if we enumerate past a user configured threshold - It is almost never what you want to query 1k entities

**Comment by GSPP** [comment]
This would be useful. It should not be a text log though. It should be programmatically detectable. The app decides how to handle/log that condition (possibly terminate the query?).

**Comment by gdoron** [comment]
I like the idea, I never used RavenDb in production so I can't say too much about it.
But I know that one of its core features is exactly this "safe by default".
Maybe even adding another warnings like too long queries, too many connections to the DB in one request.

All these features exist in RavenDb.

**Comment by GSPP** [comment]
@gdoron in case you are interested: the safe by default design in RavenDB often means truncating result sets silently or delivering incomplete data (you can search the web for that). Such things are not found during testing. EF should not do that... But warning in an opt-in way would be useful.

**Comment by anpete** [comment]
@GSPP Don't worry, we are NEVER going to do that!

**Comment by gdoron** [comment]
@GSPP
I know, It's a trade off. [TANSTAAFL](https://en.wikipedia.org/wiki/There_ain%27t_no_such_thing_as_a_free_lunch)
Though enumerate all the results and log a warning might be the better option in my humble opinion.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
