### ISSUE TITLE
Migrations for multiple databases

### ISSUE THREAD

**Issue by robinheghan** [dotnet/efcore#5093]
I have a project where I want to share code between backend and frontend.
The backend will have a Microsoft SQL database, the frontend will use SQLite, but both of them will require the same (or roughly the same) schema.

Last I tried EF Core, creating one set of migrations for one database, would not work for the other (the migration would run, but if I remember correctly, there were certain bugs...).

I haven't been able find an answer to this anywhere, but will it be possible for migrations to be database agnostic? Another valid use case would be to use MSQL db in production, but SQLite for local development.

Thanks!

**Comment by HalidCisse** [comment]
+1

**Comment by rowanmiller** [comment]
@Skinney migrations are mostly provider agnostic now. Where you do need to write provider specific code, there is an `ActiveProvider` property on the `MigrationBuilder` that is passed to the `Up` and `Down` methods, which allows you to write conditional logic based on the provider you are targeting.

One thing to bear in mind though, is that SQL Server supports a lot of schema changes, whereas SQLite is very limited in what it allows you to change in the schema ([see the docs for more info](http://docs.efproject.net/en/latest/providers/sqlite/limitations.html#migrations-limitations)). If your making additive changes, then everything should work fine... but more complex things will likely not work on SQLite.

**Comment by Skinney** [comment]
Great!
