### ISSUE TITLE
Navigation properties are not getting selected

### ISSUE THREAD

**Issue by jazzonaut** [dotnet/efcore#5111]
A simple query like this:

```
var results = from call in db.Calls
                select new
                {
                    IpkStatusName = call.StatusNavigation.Name
                };
```

Will result in SQL that will try to select all columns from db.Calls and none from call.StatusNavigation.
In this particular case I expect it to do a join on CallStatus and only select a Name column from it.

Using build 20620 from the 19th or April.

**Comment by amokre** [comment]
Sorry, the entity of the StatusNavigation property was not properly bound in the model, it is all working fine now!
