### ISSUE TITLE
Support Sql Server Extended Properties

### ISSUE THREAD

**Issue by jamiewest** [dotnet/efcore#5123]
It would be really helpful to access/manage extended properties on the server, in particular for documentation purposes. Currently we have to do this via the [sp_addextendedproperty](https://msdn.microsoft.com/en-us/library/ms180047.aspx) and [sp_dropextendedproperty](https://msdn.microsoft.com/en-us/library/ms178595.aspx) stored procedures. Having some extension methods and annotations would greatly ease the process of maintaining these properties.

**Comment by ajcvickers** [comment]
Closing as this is not something that the EF team plans to implement. We would consider community PRs for this, but keep in mind that it may also be more appropriate to include such APIs in an add-on package rather than in the core EF code.

**Comment by dongfo** [comment]
sorry to talk here the closed issue .  Extended Properties are hepful to well documented project. we want it to .
maybe it should be add  to Microsoft.EntityFramworkCore.SqlServer.tool
