### ISSUE TITLE
Question: Are non-parameterless constructors and initializers supported by this latest .net core version from EF?

### ISSUE THREAD

**Issue by StefH** [dotnet/efcore#5124]
I did observe in some test-code that I wrote, that it seems that this latest EF can handle this ? Or is this still not supported ?

**Comment by rowanmiller** [comment]
@StefH we're not quite sure what you are asking, could you elaborate? If you want parameterless constructors on entity types, then that is supported (it's actually all that is supported right now)

**Comment by StefH** [comment]
Sorry for the confusion.
Actually I mistyped the title, I wanted to ask if `non` parameterless constructors are supported. But I guess the answer is no.

Second question : is there public code inside corefx/coreclr which lets you easily create an **anonymous type** based on properties names and property types ?

Currently I'm using my own code (https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/DynamicClassFactory.cs) to create an anonymous type.

**Comment by rowanmiller** [comment]
@StefH - regarding the original question... https://github.com/aspnet/EntityFramework/issues/240 is tracking the ability to control how types are constructed and populated (including constructor arguments). It will be a post 1.0.0 feature.

The question about dynamic types is probably best asked at github.com/dotnet/corefx/
