### ISSUE TITLE
Any Concurrency End-to-End Tutorials?

### ISSUE THREAD

**Issue by funzeye** [dotnet/efcore#5127]
Just looking to implement concurrency.
**I know** there is a tutorial on the **docs site** but that just shows you how to add the timestamp column.

Im assuming I need to update the timestamp value before I save changes to the database each time? This isnt mentioned in that tutorial...

What value do I use? a number, a date? the values that are added automatically when adding new record look like: 0x00000000000007D1 etc

Could I put the timestamp property in an abstract class? I assume this will work? as opposed to having to add it to each model class?

**Comment by ErikEJ** [comment]
I do not think you need to do anything

**Comment by funzeye** [comment]
Okay.
I assumed that was the case but it was throwing an error.

You're right though, I found what the issue actually was - my issue was being caused by not declaring the timestamp property in my viewmodel class also, I just had it declared in the model class only so was being set to null during the update process.
Its working now.

**Comment by johnsonps08** [comment]
Sorry to add to this closed ticket but I was wondering if there is an end-to-end tutorial for using a different datatype other than _rowversion_ for concurrency? 

Trying to use string or guid as a ConcurrencyStamp (much like ASP.NET Identity does) but can never seem to get a new value generated or EF to recognize a concurrency conflict. Any help would be very appreciated.
