### ISSUE TITLE
FromSql is not working 

### ISSUE THREAD

**Issue by Imjamshid** [dotnet/efcore#5128]
FromSql option is not working ignored type.

Ignored by using 

modelBuilder.Ignore<type>

Context.type.FromSql("select ....").

It thrown an exception from framework.. its working if we removed the ignore from the model builder

**Comment by gdoron** [comment]
You probably want to add more details to the issue.
With real full code of the query, configuration and the error you get.

**Comment by anpete** [comment]
FromSql only currently works with mapped (not ignored) entities. Tracked here: #1862.
