### ISSUE TITLE
EF6: Stackoverflow exception when selecting a large number of columns from a view and not using a strongly typed entity

### ISSUE THREAD

**Issue by joekaiser** [dotnet/efcore#5131]
We have a bit of an odd use-case and I think I may have uncovered a bug. I am going to be as clear as I can, but please ask any questions you need for clarification. I know this bug (if it is a bug) isn't going to be fixed today, so if someone can point me to the location in source this might originating from, I can take a look and 1) see if I can fix it or 2) if it isn't a bug in EF adjust my code accordingly.
#### Problem

System.Stackoverflow exception originating from EntityFramework.dll is causing W3WP to crash.
#### What we are trying to do

We have an entity defined in a DB context - nothing out of the ordinary here. The entity is exposed over a WebAPI Odata endpoint. The web client is able to query the data just fine and exports it to CSV for customers to download. The view backing the entity in question is approaching 1 millions records. We have an SLA to meet when being able to export the CSV, and when you have to export 1million records this SLA is broken. 

We originally tried a multi-threaded approach by have X number of threads getting N number of records per page and each doing a specific number of pages. So, 5 threads running at a time, each responsible for 200,000 records paging through them at 100 each. This helped, but it would still take ~20 minutes for a full export. So we moved to a streaming approach - this is where the fun starts :)
#### Repro steps

1) Create a view in a database with more than 100 columns. 
2) Bind that to an entity using the designer and expose it over a WebAPI Odata endpoint
3) Using the Odata framework, construct a query that selects all 100 rows from the entity. Note, you have to **explicitly** select the rows. Allowing the default select (which returns all rows) or doing a "Select=*" will not reproduce the problem. EX: `http://localhost/odata/entity?$select=col1,col2,...col99,col100`
4) W3WP crashes with an unhandled exception. You can see this in the Application Log.

```
Faulting application name: w3wp.exe, version: 8.0.9200.16384, time stamp: 0x50108835
Faulting module name: clrjit.dll, version: 4.6.96.0, time stamp: 0x55b96549
Exception code: 0xc00000fd
Fault offset: 0x00000000000778ac
Faulting process id: 0x2f4c
Faulting application start time: 0x01d19b20a1c244cf
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
Report Id: 7678dc0b-071e-11e6-945c-000d3a900c63
Faulting package full name: 
Faulting package-relative application ID: 
```

5) Attach a debugger and make the request again. Make sure your IDE is set to stop on all exceptions and you will see this exception is caught. (The line is annotated in the Example code code blow). Dig into the error and you will see it being thrown from EntityFramework.dll.

```
System.StackOverflowException was unhandled
  HResult=-2147023895
  Message=Exception of type 'System.StackOverflowException' was thrown.
  InnerException: 
```
#### Notes
- I did some testing, and as soon as we select more than 96 columns the stackoverflow is thrown. Select 96 or less and it works
- Notice we are not using a strongly typed entity. As far as PushStreamContent is concerned, it is just an IQueryable. I think this is important because a few years ago [this non-public patch](https://support.microsoft.com/en-us/kb/2384016) was put put for something very similar. I know it isn't the same, but there are similarities. I assume this would have been included in subsequent versions though.
- If I change the endpoint to _not_ use the PushStreamContent and instead just return the data like you see in most applications (i.e. `return Request.CreateResponse(view );`) it actually works. This leads me to believe it has something to do with the enumeration over the IQueryable.
- I mention it in passing, but I want to call out that if the client does a `$select=*`, then everything works. Even if there are more than the 96 columns. I wonder if it has to do with the size of the expression tree being built?
#### Example code

 _you can see here that we are not using the @Queryable annotation, but instead calling options.ApplyTo our self_

```
public HttpResponseMessage GetEntity(ODataQueryOptions<vwEntity> options)
{
    //the IsPublic isn't important here. I am just showing the we do additional query filtering on top of what the client asks for
    IQueryable view = options.ApplyTo(DbContext.vwEntity.where(row => row.IsPublic));
    return new ResponseStreamer(Request).StreamAsync(view);
}
```

_ResponseStreamer takes the current HttpWebRequests, and flushes rows out to a `PushStreamContent` as we get read them from the database. This, in essence, allows us to send rows to the client as fast as we are able to get them from SQL_

```
public HttpResponseMessage StreamAsync(IQueryable data)
{
    HttpResponseMessage response = request.CreateResponse();

    response.Content = new PushStreamContent(
        async (outputStream, httpContent, transportContext) =>
        {
            try
            {
                using (TextWriter tw = new StreamWriter(outputStream))
                {
                    using (JsonWriter writer = new JsonTextWriter(tw))
                    {
                        writer.WriteStartArray();
                        // The exception is throw while enumerating over "data"
                        foreach (var item in data)
                        {
                            string json = JsonConvert.SerializeObject(item)+","+Environment.NewLine;
                            writer.WriteRaw(json);
                            await outputStream.FlushAsync();
                        }
                        writer.WriteEndArray();
                    }
                }

            }
            catch (Exception ex)
            {
                var errorBuffer = Encoding.Default.GetBytes("an error for the client to see");
                outputStream.Write(errorBuffer, 0, errorBuffer.Length);
                outputStream.Flush();
            }
            finally
            {
                outputStream.Close();
            }
        });

    return response;
}
```

**Comment by rowanmiller** [comment]
I've moved this one over to the EF6 project https://entityframework.codeplex.com/workitem/2910

Our team is currently heads down getting EF Core 1.0.0-rc2 ready. Once we've finished that, we are going to take a period of time to focus mostly on the EF6 code base... so we will dig into this issue then (it will probably be a couple of weeks away).

**Comment by joekaiser** [comment]
That is fine. Any clues on where in the codebase the enumeration would be happening? I couldn't find it And the pdb symbols are not included in the nuget package, which means I can't step into it. I'm asking because if I can look at where it might be.thrown from, I could potentially come up with a work aroind

**Comment by rowanmiller** [comment]
@divega who could help out with a quick pointer on this one?
