### ISSUE TITLE
.GroupBy() and .Contains() do not work for implicit joins

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5138]
(Refers to EntityFramework.Core.7.0.0-rc1-final)

example:

var q1 = db.Invoices.GroupBy(i => i.CustomerId); // this works

var q2 = db.Invoices.GroupBy(i => i.Customer.StateId); // throws exception "Sequence contains more than one element"

var q3 = db.Invoices.Where(i => customerIds.Contains(i.CustomerId)); // this works

var q4 = db.Invoices.Where(i => stateIds.Contains(i.Customer.StateId));// throws exception "Sequence contains more than one element"

**Comment by maumar** [comment]
those scenarios work in the current bits. Must have been fixed by one of the improvements that were done after RC1 has shipped.

We currently produce the following queries:

q2:
```
SELECT [i].[Id], [i].[CustomerId], [i.Customer].[StateId]
                FROM [Invoices] AS [i]
                INNER JOIN [Customers] AS [i.Customer] ON [i].[CustomerId] = [i.Customer].[Id]
                ORDER BY [i.Customer].[StateId]
```

q4:
```
SELECT [i].[Id], [i].[CustomerId]
FROM [Invoices] AS [i]
INNER JOIN [Customers] AS [i.Customer] ON [i].[CustomerId] = [i.Customer].[Id]
WHERE [i.Customer].[StateId] IN (1)
```
