### ISSUE TITLE
Contains method for strings does not add N before string literal in SQL query

### ISSUE THREAD

**Issue by azhoshkin** [dotnet/efcore#5139]
I use accent insensitive queries to DB and this is important for me to match .Net strings as unicode strings in MS SQL Server.
In fact .Net String type is Unicode string and for CONTAINS SQL clause it should always use N prefix.

**Comment by divega** [comment]
@azhoshkin what version are you using? AFAIR we did the work necessary to fix this for RC2.

**Comment by azhoshkin** [comment]
@divega I'm still on RC1. Sorry, search only in open issues. Looks like mine is duplicate of https://github.com/aspnet/EntityFramework/issues/4686
Thanks! Closing this.
