### ISSUE TITLE
.SelectMany() messes up joins

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5140]
This one is a howler:

var q = db.Customers
    .Where(c => c.StateId == stateId)
    .SelectMany(c => c.Invoices)
    .ToList();

This emits Sql:

SELECT [i].[InvoiceId], [i].[CustomerId], [i].[Amount], [i].[Date]
FROM [Invoice] AS [x]
CROSS JOIN [Invoice] AS [i]
WHERE [x].[StateId] = 'NY' AND ([x].[CustomerId] = [x].[CustomerId])

No mention of the Customer table in there, and the join clause joins x to itself.

**Comment by maumar** [comment]
This issue has already been fixed in https://github.com/aspnet/EntityFramework/commit/7d27bf6527391cd46dbb09210f7e40f7998e549e

**Comment by shaulbehr** [comment]
@maumar How do I get a release of EF that has this fix?  What command line can I run in Package manager?
Thanks!
