### ISSUE TITLE
Sqlite :: subquery with SingleOrDefault returning multiple results doesn't throw in Sqlite

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#5144]
Query:

``` cs
from e1 in ctx.Set<Employee>()
where ctx.Set<Employee>().Select(e2 => e2.EmployeeID).SingleOrDefault(e2 => e2 != e1.ReportsTo) == 0
select e1;
```

This gets translated to:

```
SELECT [e1].[EmployeeID], [e1].[City], [e1].[Country], [e1].[FirstName], [e1].[ReportsTo], [e1].[Title]
FROM [Employees] AS [e1]
WHERE (
    SELECT TOP(2) [e2].[EmployeeID]
    FROM [Employees] AS [e2]
    WHERE ([e2].[EmployeeID] <> [e1].[ReportsTo]) OR [e1].[ReportsTo] IS NULL
) = 0
```

On SQL Server this is invalid query because the subquery returns multiple results and is later compared with a scalar, which somewhat simulates SingleOrDefault, however on Sqlite this is allowed (returning first row and therefore resulting in FirstOrDefault behavior instead)

We could do a few things about it:
- leave as is,
- always force client evaluation for SingleOrDefault,
- issue a warning in a log, just like we do for Equals(object).

**Comment by rowanmiller** [comment]
Closing as this is one of the many "how SQLite works" quirks... but we will reconsider adding logic to compensate if customers hit issues with this.
