### ISSUE TITLE
How to make Identity helper classes use existing DbConnection?

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#5147]
_From @gdoron on April 19, 2016 9:48_

Hi,

I noticed through my logs, Identity helper classes (e.g. `UserManager`) open a new connection for each method.
This can be 10 new connections in a single API request.
Also, it causes changes made locally in the DbContext not "seen-able" in the other connection.

Is it possible to config Identity helper classes use existing DbConnection?
If it's not, can we please add this very needed functionality?

Thanks,
Doron

_Copied from original issue: aspnet/Identity#802_

**Comment by divega** [comment]
Identity methods should be using the same instance of a `DbContext` (an `ApplicationDbContext` in an application based on the default templates) within a request. For this to work, the `DbContext` in question has to be registered as a scoped service, e.g. using the `AddDbContext<TContext>()` method.

Each `DbContext` will only use one instance of `DbConnection` but by default it is true that it will open and close it as needed, even within the same request. In order to override this you can open the connection explicit in the beginning of the request, e.g. you could do this in the controller's constructor:

``` C#
    // assuming applicationDbContext is a constructor parameter and resolved by DI
    applicationDbContext.Database.OpenConnection(); 
```

Then the connection should remain open until you close it explicitly or the scoped context is disposed.

> Also, it causes changes made locally in the DbContext not "seen-able" in the other connection.

I am not sure what you mean by this.

**Comment by divega** [comment]
_From @gdoron on April 21, 2016 22:31_

Thanks for the answer @divega,
> but by default it is true that it will open and close it as needed, even within the same request. In order to override this you can open the connection explicit in the beginning of the request, e.g. you could do this in the controller's constructor.

I hope you classify it as a bug...

A. I can't open the connection asyncly in constructors.
B. I don't want to open a connection in each and every request, some of my actions are cache-able, meaning there will be absolutely 0 requests to the DB.
C. It's a bit awkward.

What is the reason it was designed this way?

>Also, it causes changes made locally in the DbContext not "seen-able" in the other connection.

>-I am not sure what you mean by this.

I meant that if there're changes still not flushed to the DB in the connection used by DbContext, the new connection used by UserManager wouldn't not see them.
Am I right?

**Comment by gdoron** [comment]
Just clarifying B.
Some of the actions are MVC GET requests that only returns HTML, no DB is involved.
And even for WebApi requests, some of the actions don't need DB connection, like when the data is cached.

**Comment by divega** [comment]
@gdoron I understand that opening and closing the connection on demand and automatically may sound strange to you but it is by design and has been the default behavior of EF in all previous versions, for various reasons.

Closing and reopening the connection between operations automatically may not always be the most efficient behavior but it is likely the best we can do automatically: While every time this happens there is some overhead, it maybe much less expensive than you think because of connection pooling. Precisely, this behavior helps the connection pool do its job more efficiently: if we kept the connection open for longer periods (e.g. after a database operation has finished and while doing some other lengthy operation) then potentially other incoming requests that needed to execute database operations could exhaust the connection pool. 

Also, in general the longer we maintain a connection open, the higher the probability that the connectivity with the server will break, e.g. Azure SQL DB could throttle the connection or just transient instability in the communication could break it. 

As I mentioned earlier if you know exactly when you want to open the connection then you can choose to do so (having this code in the constructor was just an example). In that case EF will not close the connection and the connection will remain open until you close it or until the DbContext is disposed.

In EF Core you can also pass an existing DbConnection, e.g. you can override the `OnConfiguring()` method on a DbContext and pass the connection to an overload of `UseSqlServer()` (or the corresponding method for other relational providers).

> Just clarifying B. Some of the actions are MVC GET requests that only returns HTML, no DB is involved

Yes, I understood this. This is a scenario in which I believe the default "on demand" behavior is preferable. 

> I meant that if there're changes still not flushed to the DB in the connection used by DbContext, the new connection used by UserManager wouldn't not see them. Am I right?

I think you are not right but feel free to write some test code to prove me wrong :smile: 

For starters, changes get "flushed" to the database through the connection on a call to `SaveChangesAsync()`. Before that there may be changes tracked by the `DbContext` that haven't been saved but there is no such thing as pending changes in a connection. 

Incidentally the `DbContext` used by the `UserManager` is by default registered as a scoped service, meaning that if you resolve it in your controller, you will get the exact same instance that `UserManager` is using in the same request, so you __do__ have visibility into any pending changes if there is such thing. That said, AFAIR in ASP.NET Core Identity we call `SaveChangesAsyn()` often after each individual operation (@haok can confirm) so I am not sure you will have many chances to observe pending changes.

**Comment by HaoK** [comment]
Yeah basically every 'write' operation in the user manager calls SaveChanges at the end as part of the Update to the user.  So if there are any unsaved changes before you call many of the UserManager apis, they will be saved as part of the identity operation anyways.

**Comment by gdoron** [comment]
@divega that makes sense.
I didn't know EF and Identity call SaveChanges implicitly.

Is it just with Identity that connections close and open frequently or is it true even for EF itself?
Because if not, and the DbContext is Scoped and there are async operations in the requests that can keep connections opened for a long time too.

Thanks.

**Comment by rowanmiller** [comment]
@divega anything left to do on this one?

**Comment by divega** [comment]
@gdoron Opening and closing the connection as needed is EF behavior. Identity has little to do with it.
I am going to close this because I believe we have answered your questions. Feel free to create a new issue if you run into problems.
