### ISSUE TITLE
zero/one to many relationship generating incorrect inner join

### ISSUE THREAD

**Issue by kev160967** [dotnet/efcore#5149]
I have two tables:

Job, integer ID, string column Container (nullable)
HaulageJob, integer ID, nullable column DeliverJobID with FK relationship to ID on Job

I have classes defined for each of them

```
public class Itinerary {
        public int ID { get; set; }
        public int? DeliverJobID { get; set; }
        public virtual Booking DeliveryBooking { get; set; }
}

public class Booking {
        public int ID { get; set; }
        public string Container { get; set; }
}

```

I configure them as follows:

```
            modelBuilder.Entity<Itinerary>(e => {
                    e.ToTable("HaulageJob");
                    e.HasOne(d => d.DeliveryBooking).WithMany().HasForeignKey(d => d.DeliverJobID ).IsRequired(false);
            });

            modelBuilder.Entity<Booking>(e => {
                    e.ToTable("Job");
                });

```

I then try to do a query something like this:

`_context.Itineraries.where(i=>i.DeliveryBooking==null || i.DeliveryBooking.ContainerNumber==container)`

But the generated SQL contains an inner join to the Job, so the DeliveryBooking==null is effectively ignored:

```
SELECT [...]
FROM [HaulageJob] AS [itin]
INNER JOIN [Job] AS [itin.DeliveryBooking] ON [itin].[DeliverJobID] = [itin.DeliveryBooking].[DeliverJobID]
WHERE  ([itin].[DeliverJobID] IS NULL OR (([itin.DeliveryBooking].[Container] = @__container_3) AND [itin.DeliveryBooking].[Container] IS NOT NULL))

```

Have I configured this incorrectly, or is this a bug?

**Comment by kev160967** [comment]
To avoid confusion with any simplifications I made to produce the above, I've reproduced it with two self contained tables. Also, never mentioned it above, but this is running on SQL Server 2014.

So here is the script for the tables:
```
CREATE TABLE [dbo].[ATestC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[StringField] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ATestC] PRIMARY KEY CLUSTERED ([ID] ASC )
)

CREATE TABLE [dbo].[ATestP](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[ChildID] [INT] NULL,
	[OtherField] [INT] NOT NULL,
 CONSTRAINT [PK_ATestP] PRIMARY KEY CLUSTERED (	[ID] ASC )
) 


ALTER TABLE [dbo].[ATestP]  WITH CHECK ADD  CONSTRAINT [FK_ATestP_ATestC] FOREIGN KEY([ChildID])
REFERENCES [dbo].[ATestC] ([ID])
```
Here are the classes:

```
    public class ATestC {
        public int ID { get; set; }
        public string StringField { get; set; }
    }
    public class ATestP {
        public int ID { get; set; }
        public int OtherField { get; set; }
        public int? ChildID { get; set; }
        public virtual ATestC Child { get; set; }
    }
```
Here is the configuration:

```
    public class SaturnContext : DbContext {

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<ATestP>(e => {
                    e.HasOne(d => d.Child).WithMany().HasForeignKey(d => d.ChildID).IsRequired(false);
                });
        }

        public virtual DbSet<ATestP> Parents { get; set; }
        public virtual DbSet<ATestC> Children { get; set; }
}
```

and here is the query:

`                var test = _context.Parents.Where(i => i.Child.StringField == "test" || i.OtherField == 5).ToList();`

This produces the following SQL:

```
SELECT [i].[ID], [i].[ChildID], [i].[OtherField]
FROM [ATestP] AS [i]
INNER JOIN [ATestC] AS [i.Child] ON [i].[ChildID] = [i.Child].[ID]
WHERE ([i.Child].[StringField] = 'test') OR ([i].[OtherField] = 5)

```

If I have  a ATestP record with ChildID: null and OtherField: 5, the Linq query should find it, but the inner join prevents this

**Comment by maumar** [comment]
This is a known issue that has been fixed after RC1 has been shipped. Essentially every navigation (optional and required) would get translated into INNER JOIN. This is fixed in the current code base, producing LEFT OUTER JOIN in case if optional navigations.

**Comment by kev160967** [comment]
Thank you maumar. If I want to use the in an ASP.Net 5 project will I need to build my own version - I'm new to github, so please excuse me if this is a stupid question!

**Comment by gdoron** [comment]
You can use the nightly builds (different nuget source), you don't need to clone the EF repository for that.
Bear in mind that there many many things have changed since RC 1.
And you won't be able to use VS until they finish wrapping the dotnet CLI tooling (Scott said RC2 Will be released in 4-6 weeks)

**Comment by kev160967** [comment]
Thanks Doron, I was thinking much the same - I hadn't realised how much things had diverged from the DNX model until I looked into this.
