### ISSUE TITLE
pluggable schemes for mapping c# names

### ISSUE THREAD

**Issue by SepiaGroup** [dotnet/efcore#5159]
I am using EF Core with PostgreSQL/Npgsql. Since PostgreSQL is case sensitive for object names and Properties are proper cased in C# this cause you to use double quotes when writing native sql.

could it be possible to create a pluggable scheme to allow the mapping of object names, similar to what is done when you want to camel case objects to json using CamelCasePropertyNamesContractResolver().

i asked this of the PostgresSQL developers and they think this functionality would be best implemented in EF Core and not in npgsql.

https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/21

**Comment by roji** [comment]
Just to add a bit of detail, this would provide users the choice to map C# names like MyClassName to my_class_name, etc.

**Comment by roji** [comment]
Another note: the same mapping scheme provider would ideally be used for reverse-engineering.

**Comment by rowanmiller** [comment]
It's actually super easy to override the default naming scheme with some simple code in your `OnConfiguring` method.

```c#
foreach (var entity in modelBuilder.Model.GetEntityTypes())
{
    foreach (var property in entity.GetProperties())
    {
        property.Relational().ColumnName = property.Name.ToLower();
    }
}
```

Or I prefer to write it like this...

```c#
modelBuilder.Model.GetEntityTypes()
    .SelectMany(e => e.GetProperties())
    .ToList()
    .ForEach(p => p.Relational().ColumnName = p.Name.ToLower());
```

**Comment by roji** [comment]
Of course... that makes total sense.

**Comment by SepiaGroup** [comment]
i am not so sure that this way of overriding the default names works.  
my first issue is that the modelBuilder is not in the OnConfiguring which is defined as

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

but it is available in OnModelCreating, which is where i placed this code.
i did see that it lowercase the names but it still builds the table in the db with capitals.

what am i missing?

**Comment by rowanmiller** [comment]
> modelBuilder does not seem to be in OnConfiguring but is in OnModelCreating

Typo on my behalf, OnModelCreating is the correct place (I updated my original comment).

**Comment by geocine** [comment]
How about lowercase of table names? Thanks.

**Comment by asymetrixs** [comment]
@geocine Your solution uses the full namespace to generate the name which can lead to very long (and ugly) names for tables and keys/indices.

Fortunately Npgsql already offers an SnakeCase-Translator (which it uses for enums) so I solved it like this:
`private void _FixSnakeCaseNames(ModelBuilder modelBuilder)
{
    var mapper = new Npgsql.NpgsqlSnakeCaseNameTranslator();

    foreach (var entity in modelBuilder.Model.GetEntityTypes())
    {
        // modify column names
        foreach (var property in entity.GetProperties())
        {
            property.Relational().ColumnName = mapper.TranslateMemberName(property.Relational().ColumnName);
        }

        // modify table name
        entity.Relational().TableName = mapper.TranslateMemberName(entity.Relational().TableName);

        // move asp_net tables into schema 'identity'
        if (entity.Relational().TableName.StartsWith("asp_net_"))
        {
            entity.Relational().TableName = entity.Relational().TableName.Replace("asp_net_", string.Empty);
            entity.Relational().Schema = "identity";
        }
    }
}`

called from here

`protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);
    _FixSnakeCaseNames(modelBuilder);
}`
Moreover I do move the identity-tables into another namespace and remove the asp_net prefix

**Comment by geocine** [comment]
@asymetrixs  I did not know there was a built in function for snake case thank you

For the table  name, I am actually using the name of the DbSet when you add it to your context.  

Example:
```csharp
public DbSet<Employee> EmployeeDetails { get; set; }
```
It will give you `employee_details`

**Comment by FikruKebede** [comment]
In my case,  **modelBuilder._Model_** is not available. in which name space the **_Model_** class is available?

**Comment by ajcvickers** [comment]
@FikruKebede Are you sure you are using EF Core, not EF6?

**Comment by FikruKebede** [comment]
I was using EF6. Now I am using EF Core and the  problem is fixed.

**Comment by neumartin** [comment]
Hi!!

Not working in my code, all tables and fields still in CamelCase.
Im using the EF Core 2.0.

My context class is this:

`public class SevntDbContext : IdentityDbContext<Usuario, IdentityRoleSevnt, int>, ISevntDbContext
    {
        public SevntDbContext() : base()
        {
            Configure();
        }

        public SevntDbContext(DbContextOptions<SevntDbContext> options) : base(options)
        {
            Configure();
        }

        private void Configure()
        {
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("project.json", optional: true)
                .AddJsonFile("appsettings.json", optional: false);

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        public DbSet<Adjunto> Adjuntos { get; set; }
        public DbSet<CategoriaEvento> CategoriasEvento { get; set; }
        public DbSet<Provincia> Provincias { get; set; }
        public DbSet<Pais> Paises { get; set; }
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<TipoCondicionFiscal> TiposCondicionesFiscales { get; set; }
        public DbSet<TipoDocumento> TiposDocumento { get; set; }
        public DbSet<TipoEntrada> TipoEntrada { get; set; }
        public DbSet<TipoEstadoCivil> TiposEstadoCivil { get; set; }
        public DbSet<Entrada> Entradas { get; set; }
        public DbSet<Evento> Eventos { get; set; }
        public DbSet<Zona> Zonas { get; set; }
        public DbSet<Pedido> Pedidos { get; set; }
        public DbSet<TipoAlerta> TiposAlerta { get; set; }
        public DbSet<Ingreso> Ingresos { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<PersonaVinculo> PersonasVinculos { get; set; }
        public DbSet<PersonaAlertaCargada> PersonasAlertasCargadas { get; set; }
        public DbSet<PersonaAlertaEmitida> PersonasAlertasEmitidas { get; set; }
        public DbSet<TipoUsuario> TiposUsuario { get; set; }
        public DbSet<Horario> Horarios { get; set; }
        public DbSet<DiaSemana> DiasSemana { get; set; }
        public DbSet<BoardingPass> BoardingPasses { get; set; }
        public DbSet<Aerolinea> Aerolineas { get; set; }
        public DbSet<IATAAeropuerto> IATAAeropuertos { get; set; }
        public DbSet<IATAPais> IATAPaises { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(Configuration["ConnectionStrings:ConnectionString"]); //.MigrationsAssembly("pBoxe.DataAccess");                                                                             // optionsBuilder.UseSqlServer("Server=localhost;Database=Sevnt;Trusted_Connection=True;MultipleActiveResultSets=true;"); //.MigrationsAssembly("pBoxe.DataAccess");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasPostgresExtension("citext");

            new AdjuntoMap(modelBuilder.Entity<Adjunto>());
            new CategoriaEventoMap(modelBuilder.Entity<CategoriaEvento>());
            new EmpresaMap(modelBuilder.Entity<Empresa>());
            new EntradaMap(modelBuilder.Entity<Entrada>());
            new EventoMap(modelBuilder.Entity<Evento>());
            new ProvinciaMap(modelBuilder.Entity<Provincia>());
            new PaisMap(modelBuilder.Entity<Pais>());
            new TipoDocumentoMap(modelBuilder.Entity<TipoDocumento>());
            new TipoEntradaMap(modelBuilder.Entity<TipoEntrada>());
            new TipoCondicionFiscalMap(modelBuilder.Entity<TipoCondicionFiscal>());
            new TipoEstadoCivilMap(modelBuilder.Entity<TipoEstadoCivil>());
            new UsuarioMap(modelBuilder.Entity<Usuario>());
            new PedidoMap(modelBuilder.Entity<Pedido>());
            new UsuarioEventoMap(modelBuilder.Entity<UsuarioEvento>());
            new UsuarioEventoFavoritosMap(modelBuilder.Entity<UsuarioEventoFavoritos>());
            new ZonaMap(modelBuilder.Entity<Zona>());
            new TipoAlertaMap(modelBuilder.Entity<TipoAlerta>());
            new IngresoMap(modelBuilder.Entity<Ingreso>());
            new PersonaMap(modelBuilder.Entity<Persona>());
            new PersonaVinculoMap(modelBuilder.Entity<PersonaVinculo>());
            new PersonaAlertaCargadaMap(modelBuilder.Entity<PersonaAlertaCargada>());
            new PersonaAlertaEmitidaMap(modelBuilder.Entity<PersonaAlertaEmitida>());
            new TipoUsuarioMap(modelBuilder.Entity<TipoUsuario>());
            new HorarioMap(modelBuilder.Entity<Horario>());
            new DiaSemanaMap(modelBuilder.Entity<DiaSemana>());
            new BoardingPassMap(modelBuilder.Entity<BoardingPass>());
            new AerolineaMap(modelBuilder.Entity<Aerolinea>());
            new IATAAeropuertoMap(modelBuilder.Entity<IATAAeropuerto>());
            new IATAPaisMap(modelBuilder.Entity<IATAPais>());

            var mapper = new Npgsql.NpgsqlSnakeCaseNameTranslator();

            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                // modify column names
                foreach (var property in entity.GetProperties())
                {
                    property.Relational().ColumnName = mapper.TranslateMemberName(property.Relational().ColumnName);
                }

                // modify table name
                entity.Relational().TableName = mapper.TranslateMemberName(entity.Relational().TableName);

                // move asp_net tables into schema 'identity'
                if (entity.Relational().TableName.StartsWith("asp_net_"))
                {
                    entity.Relational().TableName = entity.Relational().TableName.Replace("asp_net_", string.Empty);
                    entity.Relational().Schema = "identity";
                }
            }
        }

        public void Seed()
        {
            // this.Database.Migrate();
            new Seeder().Seed();
        }
    }`

Thanks!!!

**Comment by ajcvickers** [comment]
@neumartin This code works for me, assuming that NpgsqlSnakeCaseNameTranslator correctly creates a snake_case name. Can you check that NpgsqlSnakeCaseNameTranslator  is generating snake_case names? If not, then please follow up with the owner of that class. Otherwise, please file a new issue with a complete project or code listing that reproduces what you are seeing.

**Comment by neumartin** [comment]
I make an example here: 

https://github.com/neumartin/SnakeCaseTest/

But in the example works fine, forget my question.
Thanks!

**Comment by neumartin** [comment]
The problem was the migrations.
I deleted all migrations and create new one and works fine!

**Comment by AuthorProxy** [comment]
Previous example not work with keys and indexes, here is modified version that includes it:

```
using System;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql;

namespace Database.Customization
{
    public class PostgreDbContext : DbContext
    {
        private static readonly Regex _keysRegex = new Regex("^(PK|FK|IX)_", RegexOptions.Compiled);

        public PostgreDbContext(DbContextOptions options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            FixSnakeCaseNames(modelBuilder);
        }

        private void FixSnakeCaseNames(ModelBuilder modelBuilder)
        {
            var mapper = new NpgsqlSnakeCaseNameTranslator();
            foreach (var table in modelBuilder.Model.GetEntityTypes())
            {
                ConvertToSnake(mapper, table);
                foreach (var property in table.GetProperties())
                {
                    ConvertToSnake(mapper, property);
                }

                foreach (var primaryKey in table.GetKeys())
                {
                    ConvertToSnake(mapper, primaryKey);
                }

                foreach (var foreignKey in table.GetForeignKeys())
                {
                    ConvertToSnake(mapper, foreignKey);
                }

                foreach (var indexKey in table.GetIndexes())
                {
                    ConvertToSnake(mapper, indexKey);
                }
            }
        }

        private void ConvertToSnake(INpgsqlNameTranslator mapper, object entity)
        {
            switch (entity)
            {
                case IMutableEntityType table:
                    var relationalTable = table.Relational();
                    relationalTable.TableName = ConvertGeneralToSnake(mapper, relationalTable.TableName);
                    if (relationalTable.TableName.StartsWith("asp_net_"))
                    {
                        relationalTable.TableName = relationalTable.TableName.Replace("asp_net_", string.Empty);
                        relationalTable.Schema = "identity";
                    }

                    break;
                case IMutableProperty property:
                    property.Relational().ColumnName = ConvertGeneralToSnake(mapper, property.Relational().ColumnName);
                    break;
                case IMutableKey primaryKey:
                    primaryKey.Relational().Name = ConvertKeyToSnake(mapper, primaryKey.Relational().Name);
                    break;
                case IMutableForeignKey foreignKey:
                    foreignKey.Relational().Name = ConvertKeyToSnake(mapper, foreignKey.Relational().Name);
                    break;
                case IMutableIndex indexKey:
                    indexKey.Relational().Name = ConvertKeyToSnake(mapper, indexKey.Relational().Name);
                    break;
                default:
                    throw new NotImplementedException("Unexpected type was provided to snake case converter");
            }
        }

        private string ConvertKeyToSnake(INpgsqlNameTranslator mapper, string keyName) =>
            ConvertGeneralToSnake(mapper, _keysRegex.Replace(keyName, match => match.Value.ToLower()));

        private string ConvertGeneralToSnake(INpgsqlNameTranslator mapper, string entityName) =>
            mapper.TranslateMemberName(ModifyNameBeforeConvertion(mapper, entityName));

        protected virtual string ModifyNameBeforeConvertion(INpgsqlNameTranslator mapper, string entityName) => entityName;
    }
}

```

**Comment by okinoh** [comment]
@AuthorProxy 
Your full example works fine on the first `migrations add` and `database update`,
but when I add a table and do `migrations add` again, I get a migration file which includes CreateTable(s) of all existing tables. That causes relation `"mytablename" already exists` on the second `database update` run.
My EF core version: 2.1.4-rtm-31024

**Comment by williamdenton** [comment]
update for efcore3, the Relational() methods have been removed in https://github.com/aspnet/EntityFrameworkCore/commit/469177a49d251bb81184b42ce4cd2ffe623b345a, small tweaks in here to make the code compile again

```cs
property.Relational().ColumnName = ConvertGeneralToSnake(mapper, property.Relational().ColumnName);
```
changes to
```cs
property.SetColumnName(ConvertGeneralToSnake(mapper, property.GetColumnName()));

```


heres the complete extension
```cs
public static class ModelBuilderExtensions
{
	static readonly Regex _keysRegex = new Regex("^(PK|FK|IX)_", RegexOptions.Compiled);

	public static void UseSnakeCaseNames(this ModelBuilder modelBuilder)
	{
		var mapper = new NpgsqlSnakeCaseNameTranslator();

		foreach (var table in modelBuilder.Model.GetEntityTypes())
		{

			ConvertToSnake(mapper, table);

			foreach (var property in table.GetProperties())
			{
				ConvertToSnake(mapper, property);
			}

			foreach (var primaryKey in table.GetKeys())
			{
				ConvertToSnake(mapper, primaryKey);
			}

			foreach (var foreignKey in table.GetForeignKeys())
			{
				ConvertToSnake(mapper, foreignKey);
			}

			foreach (var indexKey in table.GetIndexes())
			{
				ConvertToSnake(mapper, indexKey);
			}
		}
	}

	static void ConvertToSnake(INpgsqlNameTranslator mapper, object entity)
	{
		switch (entity)
		{
			case IMutableEntityType table:
				table.SetTableName(ConvertGeneralToSnake(mapper, table.GetTableName()));
				break;
			case IMutableProperty property:
				property.SetColumnName(ConvertGeneralToSnake(mapper, property.GetColumnName()));
				break;
			case IMutableKey primaryKey:
				primaryKey.SetName(ConvertKeyToSnake(mapper, primaryKey.GetName()));
				break;
			case IMutableForeignKey foreignKey:
				foreignKey.SetConstraintName(ConvertKeyToSnake(mapper, foreignKey.GetConstraintName()));
				break;
			case IMutableIndex indexKey:
				indexKey.SetName(ConvertKeyToSnake(mapper, indexKey.GetName()));
				break;
			default:
				throw new NotImplementedException("Unexpected type was provided to snake case converter");
		}
	}

	static string ConvertKeyToSnake(INpgsqlNameTranslator mapper, string keyName) =>
		ConvertGeneralToSnake(mapper, _keysRegex.Replace(keyName, match => match.Value.ToLower()));

	static string ConvertGeneralToSnake(INpgsqlNameTranslator mapper, string entityName) =>
		mapper.TranslateMemberName(entityName);
}
```

**Comment by roji** [comment]
For anyone interesting in this, check out [EFCore.NamingConventions](https://github.com/efcore/EFCore.NamingConventions/). If anything is missing or not working for you, please file an issue in that repo.
