### ISSUE TITLE
Null pointer exception when using model

### ISSUE THREAD

**Issue by andershol** [dotnet/efcore#5160]
Running this application with EF 7.0.0-rc1-final (i.e. after running `Install-Package EntityFramework.Commands –Pre` and `Install-Package EntityFramework.MicrosoftSqlServer –Pre`)

``` csharp
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Infrastructure;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
class Program
{
    private static void Main(string[] args)
    {
        var options = new DbContextOptionsBuilder();
        options.UseSqlServer(@"Server=.;Database=Test;Integrated Security=True;");
        using (var dc = new DatabaseContext(options.Options))
            dc.Bars.Where(u => u.Id == 1).SingleOrDefault();
    }
}
public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions options) : base(options) { }
    public DbSet<Bar> Bars { get; set; }
}
public partial class Foo
{
    [NotMapped]
    public string[] ListDisplay { get { return new string[0]; } }
    [Key]
    public int Id { get; set; }
    public ICollection<Bar> Bars { get; set; }
    public ICollection<Baz> Bazs { get; set; }
}
public partial class Bar
{
    [NotMapped]
    public string[] ListDisplay { get { return new string[0]; } }
    [Key]
    public int Id { get; set; }
    public int FooId { get; set; }
    [ForeignKey("FooId")]
    [InverseProperty("Bars")]
    public Foo Foo { get; set; }
}
public partial class Baz
{
    [Key]
    public int Id { get; set; }
    public int FooId { get; set; }
    [ForeignKey("FooId")]
    [InverseProperty("Bazs")]
    public Foo Foo { get; set; }
}
```

Results in this exception in the call to "Where(...)":

> An unhandled exception of type 'System.ArgumentNullException' occurred in EntityFramework.Core.dll
> ParamName: navigation

I tried using the "aspnetcidev" package source, but using that currently results in a "missing method" error related to logging.

**Comment by maumar** [comment]
Make sure you are using Microsoft.EntityFrameworkCore.* packages, we had a rename/rebranding and there are two sets of packages available currently on myget, the new one that works and the old one that doesnt

**Comment by andershol** [comment]
So what you are saying is that I should use the "aspnetvnext" myget repository(?), as the nuget only have an alpha-version, and issue `Install-Package Microsoft.EntityFrameworkCore.Commands –Pre` and `Install-Package Microsoft.EntityFrameworkCore.SqlServer –Pre`? It does seem to fix it.
Unfortunately the database provider used in the real app does not yet support this version. But thanks for the note.

**Comment by rowanmiller** [comment]
@andershol correct, you should install from `https://www.myget.org/F/aspnetvnext/`... or wait til we ship RC2. Depending on the provider in use, they may have nightly builds that work with out nightly feed (though things are often broken at the moment).
