### ISSUE TITLE
Command Like EF Core 1 RC2

### ISSUE THREAD

**Issue by ralmsdeveloper** [dotnet/efcore#5162]
**Hello friends,**
Not bug!
I believe that could improve the production of this query

**SELECT [r]. [Codcargo], [r]. [Nomecargo]
FROM [Cargos] AS [r]
WHERE [r]. [Nomecargo] LIKE ('%' + 'test') + '%'**

For

**SELECT [r]. [Codcargo], [r]. [Nomecargo]
FROM [Cargos] AS [r]
WHERE [r]. [Nomecargo] LIKE ('%' + 'test' + '%')**

Only the "%" stand inside "()"

I'm using EF Core 1 RC2 (Windows 10x64 - Dotnet cli "1.0.0-rc2-002439")

MODEL
  public class Cargos
     {
        [Key]
        [Display (Name = "Codcargo")]
        public int codcargo {get; set; }

        [Display (Name = "Nomecargo")]
        [StringLength (50)]
        [Column (TypeName = "varchar (50)")]
        public nomecargo string {get; set; }

    }

It's just a suggestion

**Comment by rowanmiller** [comment]
Implementing this change would introduce significant complexity to work out when it is save to avoid parenthesis and when it is not. We don't think it would have any significant performance impact, so it's not something we would do.

**Comment by ralmsdeveloper** [comment]
@rowanmiller Thank you for your answer, I understand, it was just a little hint of code organization!

It really has no impact on performance, also want to say they are doing a great job ... I accompanied every project ... to migrate the ERP for my Asp.Net Core 1
