### ISSUE TITLE
Still has the error: "Property 'Count' was not found on type 'System.Collections.ArrayList'"

### ISSUE THREAD

**Issue by aloncor** [dotnet/efcore#5163]
I've tried a lot of thinks trying to put my application to work, and always I have this error:
Property 'Count' was not found on type 'System.Collections.ArrayList'
In other post says that I need to include the directive <Type Name="System.Collections.ArrayList" Dynamic="Required All" />
That doesn't work for me....
I have a project, and a class library, in the class library is where I'm using EF, in debug it works fine but in release not, I have 4 days trying to solve this and I can't do it, maybe I will use other packages like SQLite-NET because this problems is creating a time lost in the project.
Can anybody help me?

**Comment by rowanmiller** [comment]
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing? Can you also include the full stack trace of the exception.

**Comment by MMalikKhan** [comment]
Hi @rowanmiller  i am also facing the same issue in the UWP app. while running this in release mode. I found this  [link](https://github.com/aspnet/EntityFramework/issues/3768)  which suggest you need to add <Type Name="System.Collections.ArrayList" Dynamic="Required All" /> and this  already exist in my default.rd.xml file could you please suggest what could be wrong .. 

here is the code on which it is crashing.. 

var items =
                        db.Templates.Include(t => t.Media)
                            .ToList()
                            .Select(c => TemplateViewModelFromTemplate(c))
                            .OrderBy(t => t.Title)
                            .ToList();

**Comment by natemcmaster** [comment]
@MMalikKhan this issue shouldn't affect RC2. See http://ef.readthedocs.io/en/latest/platforms/uwp/getting-started.html and https://github.com/aspnet/Announcements/issues/170

**Comment by MMalikKhan** [comment]
Hi @natemcmaster where is RC2. The version i am using is 7.0.0 Rc1 Final .. is there an RC2 for EF 7?

**Comment by natemcmaster** [comment]
@MMalikKhan we rebranded since RC1, so the packages have been renamed. Checkout http://ef.readthedocs.io/en/latest/miscellaneous/rc1-rc2-upgrade.html. This includes the list of all the new package names and known issues in upgrading from RC1.

**Comment by MMalikKhan** [comment]
oh.. thanks for the link, just to make it clear .. i am already using VS 2015 Update 2. However just checked the UWP version it is attached to my app. UAP,Version=10.0.10240.0 and i believe the latest is  10.0.10586 am i right? 
I need to point to the latest version that is 10586 and also update from RC1 to RC2 run in the release mode.. ?

**Comment by MMalikKhan** [comment]
thanks @natemcmaster, i updated the project to Rc-2 and i have a new error now for the above line?
var items =
db.Templates.Include(t => t.Media)
.ToList()
.Select(t => TemplateViewModelFromTemplate(t, null))
.OrderBy(t => t.Title)
.ToList();

Note: this is a method which is returning a different object based on the values of t?
Additional information: The given expression 'value(iAuditorUWP.ViewModels.HomeViewModel).TemplateViewModelFromTemplate([t], null)' does not contain the searched expression '[t]' in a nested NewExpression with member assignments or a MemberBindingExpression.

**Comment by MMalikKhan** [comment]
@natemcmaster @maumar  I am getting this error after Rc2 upgrade and trying to generate migrations

System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.<>c.<FindContextTypes>b__11_8(Type t)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.FindContextType(String name)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

anything you can suggest?

**Comment by MMalikKhan** [comment]
@natemcmaster @divega  after further drilling i found this buried in the logs 
ILTransform_0027: Ambiguous type name detected. There are types with name 'System.Collections.ArrayList' in both assembly 'System.Collections.NonGeneric' and 'System.Xml.XmlSerializer'. This directive is ignored. Consider placing this directive within an Assembly scope.

could you please let me know how can i resolve this?

**Comment by divega** [comment]
That directive in the rd.xml file us no longer used in RC2 and with the 1.3.1 version of the Windows Universal Apps tooling. Have you reviewed the getting started document that @natemcmaster pointed to recently? Instructions have actually changed for RC2.

**Comment by MMalikKhan** [comment]
@divega yeah i did .. i am pretty sure i might be doing something wrong, right now i am struck from morning to make this EF work. its crashing with the below error on the below line.. it work perfectly fine in debug more but crashes in the release mode ..  i tried creating with other method and i still got the same error. after the below error it show this error cannot open SQL

I appreciate all your help..

this same issue is raised by someone else this morning [5386](https://github.com/aspnet/EntityFramework/issues/5386)
.EnsureCreatedAsync();//

            await appDbContext.Database.MigrateAsync();

Exception thrown: 'System.ArgumentException' in System.Linq.Expressions.dll

Additional information: Instance field '_resolvedServices' is not defined for type 'Microsoft.Extensions.DependencyInjection.ServiceProvider'

If there is a handler for this exception, the program may be safely continued.

**Comment by divega** [comment]
Are you hitting all these errors trying to update an application you had previously created with RC1? Have you tried instead creating one from scratch following the up to date instructions? I am not sure what different it could make besides not having the directives file,  but I would try it anyway because the fact is we have no problems creating UWP apps with RC2 bits and the new tooling. 

Also have you checked that you have the 1.3.1 version of the tooling installed? It is included in VS 2015 Update 2 but AFAIK you have to sect it explicitly during setup. 

Finally and just in case, are you sure you aren't hitting first chance exceptions? When you mention you can "continue" in the debugger, that is how it sounds to me. In that case just reset to the default settings in the exceptions window in VS.

**Comment by MMalikKhan** [comment]
@divega thanks, what you mean by tooling? i am using the latest UWP platform "UAP,Version=10.0.10586.0" ? i deleted the app and in release mode it is u

**Comment by MMalikKhan** [comment]
it is unable to create the database.. it just create the database file but no tables

**Comment by divega** [comment]
A few more things, in case you have mixed up packahes
- What NuGet feeds are pulling packages from? Since published RC2 you should only have the official NuGet.org one
- What exact names of packages are you installing? Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.Tools is what you need since package names changed in RC2 
- Have you cleared up your local NuGet package cache? E.g. the .nuget folder under your user profile?

**Comment by MMalikKhan** [comment]
after that the code just crashes because the tables are null.. it all works fine in debug mode.. i think, i am missing something very specific with the database creation using DI service. As the error is with the DI service not able to get some objects

**Comment by MMalikKhan** [comment]
yes i have cleared everything.. i dont see any issue with that, after looking further.. @natemcmaster shared link have all the mappings that i needed to migrate. but i think i have no part doing this .. [this](http://ef.readthedocs.io/en/latest/miscellaneous/configuring-dbcontext.html#using-dbcontext-with-dependency-injection)

do you have a simple sample which uses autofac or any DI and shows how i can use this .. piece

**Comment by MMalikKhan** [comment]
when should i call this ?
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<BloggingContext>(options => options.UseSqlite("Filename=./blog.db"));
}

in my app.cs when the application first start to register my app context with specific parameter?

**Comment by divega** [comment]
> what you mean by tooling? 

See https://blogs.msdn.microsoft.com/dotnet/2016/04/18/whats-new-for-the-net-native-compiler-and-runtime-in-visual-studio-2015-update-2/,  in particular the screen shot from the selection list in the installer. 

> As the error is with the DI service not able to get some objects

The error you mentioned actually sounds more like your application is using a stale version of the DI package. 

Again I encourage you to try creating a UWP application  from scratch to confirm whether you hit the same issues.

**Comment by MMalikKhan** [comment]
@divega AFAIK just went to see that tooling by going to VS Modify setting and guess what it says i was actually on 1.3.1 it says deprecated and there is 1.3.2 available for update the UAP,Version=10.0.10586.0 is still the same..

**Comment by divega** [comment]
> when should i call this ? @divega @natemcmaster
public void ConfigureServices(IServiceCollection services)

Not sure. That method normally only exists in the start up class in ASP.NET Core apps. It doesn't apply to UWP apps, unless you chose to create your own method mimicking how ASP.NET Core apps work with DI. Where did you copy it from? 

Normally for non-ASP.NET Core apps you would just  override the `OnConfiguring()` method on the DbContext and put the call to `UseSqlite()` in there.

**Comment by MMalikKhan** [comment]
i got all this from [here](http://ef.readthedocs.io/en/latest/miscellaneous/configuring-dbcontext.html#using-dbcontext-with-dependency-injection)  this is the link that @natemcmaster shared with me .. for migration from RC1 to RC2

**Comment by divega** [comment]
Ok. Still,  that pattern is specific to ASP.NET Core as clarified in http://ef.readthedocs.io/en/latest/miscellaneous/rc1-rc2-upgrade.html#adddbcontext-startup-cs-changes-asp-net-core-projects-only

**Comment by MMalikKhan** [comment]
i have something similar.. i have onConfiguring and inside that the call to UseSqlite .. and then i have a IDataStorageService which i have a method to GetDBContext and any viewModel or anywhere int the app if i need to open conenction i am injecting IDataStorageService and calling 

(var db  = await dataStorageService.GetDbContext())
{
do stuff
}

these are the only lines inside the implementaiton of the GetDbContext 
var appDbContext = new AppDbContext(_filePath);
await appDbContext.EnsureFilePathExists();
await appDbContext.Database.MigrateAsync();
return appDbContext;

and things run fine in debug but in release mode the app crash at MigrateAsync with the DI error i posted above
@divega

**Comment by MMalikKhan** [comment]
@divega any idea what i am missing here that is causing this error ? @natemcmaster

**Comment by divega** [comment]
No, I have enumerated everything I could think of and I have ran out of ideas. As I told you before I think if you create a simple UWP that uses EF from scratch and that works that might be a good start.

**Comment by MMalikKhan** [comment]
thanks @divega i was having the exact same error attached in this issue when i first started troubleshooting, in order to fix that i have updated form RC1 to RC2 and now struck at creating the database.. i m still not sure once i pass this i will hv the to once again  above issue.. i believe in this ticket it was made obvious why this error was coming ? #5386 and it is still open can you suggest why this is happening ? https://github.com/aspnet/EntityFramework/issues/5386

**Comment by natemcmaster** [comment]
If anyone is still encountering this error, I finally figured out what causes the error "Property 'Count' not found on type 'System.Collections.ArrayList'. See https://github.com/aspnet/EntityFramework/issues/5517
