### ISSUE TITLE
aspnet is not the correct parent for EntityFramework

### ISSUE THREAD

**Issue by MrMatthewLayton** [dotnet/efcore#5164]
Apologies if this seems a bit pedantic, but why does EntityFramework come under aspnet on GitHub?

![untitled](https://cloud.githubusercontent.com/assets/17050082/14778036/a1a1b830-0ac8-11e6-8ea1-7a4015e3faad.png)

EntityFramework is a persistence framework that can be used by any type of application (Windows Forms, WPF, ASP.NET, etc.) so why is this project specifically under aspnet?

**Comment by rowanmiller** [comment]
It's purely an organizational thing - we share the same management and a lot of the same infrastructure as ASP.NET. It has no impact on the packages we ship, it just makes it easier for our day to day work. Most of the packages we produce are `Microsoft.*` and don't have ASP.NET in the name (except for the ones that are ASP.NET specific of course 😄).

BTW I totally get why it seems unexpected, but I don't think it really causes any issues... and it makes our day to day work easier.

**Comment by gdoron** [comment]
I'm curious to know why Identity has AspNet in the package & namespace names.

**Comment by series0ne** [comment]
Yes I'm curious about though too, however isn't the Windows Identity Framework (WIF) going to supersede Identity Framework?

**Comment by rowanmiller** [comment]
Are you asking about `Microsoft.AspNetCore.Identity`? If so, that is ASP.NET and identity and very much specific to ASP.NET applications.
