### ISSUE TITLE
Interfaces as entities

### ISSUE THREAD

**Issue by MrMatthewLayton** [dotnet/efcore#5166]
Whilst writing an application using EF6, I found myself in a situation where I would have liked to use interfaces to represent entities.

Take for example an interface which represents a user in my domain model.

```
interface IUser
{
    string UserName { get; set; }
    string Password { get; set; }
}
```

From this I have two implementations, my entity, and my view model.

```
class User : IUser
{
    public int Id;
    public string UserName { get; set; }
    public string Password { get; set; }
}

class UserModel : IUser
{
    public string UserName { get; set; }
    public string Password { get; set; }
    public bool RememberMe { get; set; }
}
```

Notice that while both the entity and the model differ in implementation, they both implement IUser.

So far you might think; "I don't see an issue here, you can always use User in your EF implementation..."

...except that, this doesn't work...

```
class Profile
{
    IUser User { get; set; }
    string FirstName { get; set; }
    string LastName { get; set; }
}
```

In this case, IUser doesn't get persisted, presumably because EF6 doesn't know what IUser is in this instance.

To be entirely honest, I'm not sure how it would be possible, if at all, to use interfaces in Entity Framework, but I thought it was mentioning as an idea...

**Comment by davidroth** [comment]
This is already tracked by #757.
It's not possible at the moment and is on the backlog.
