### ISSUE TITLE
Cleanup dotnet-ef end to end tests

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#5172]
All tests in test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTest are currently set to "Skip" due to flakiness in running these tests on CI. We should clean this up for RTM.

Part of cleaning up the tests depends on https://github.com/NuGet/Home/issues/2469

**Comment by divega** [comment]
@rowanmiller would you like to include this in the global item to re-enable tests before RTM?

**Comment by rowanmiller** [comment]
@divega will do

**Comment by rowanmiller** [comment]
Consolidated into #5346
