### ISSUE TITLE
EF don't create the tables in UWP application (.NET Native)

### ISSUE THREAD

**Issue by WiliamGP** [dotnet/efcore#5177]
I use EF7 and SQLite in my application for Windows 10 Mobile, even with Migrate() function in App.xaml.cs the tables are not created. Every time I use the database I use the EnsureCreated() function, but occurs error "No such table: nameTable". This error only occurs when I compile the application with the .NET Native. Someone can help me with this?

**Comment by natemcmaster** [comment]
Hi @WiliamGP, can you share more about your project setup, the connection string you use, and which version of EF you are using?
