### ISSUE TITLE
Build from source: Build initialize fails

### ISSUE THREAD

**Issue by davidroth** [dotnet/efcore#5178]
I just cloned the dev branch into a clean folder and I am getting the following error when running `build initialize`.

![image](https://cloud.githubusercontent.com/assets/338856/14821191/13539578-0bca-11e6-9874-dd7e66891f51.png)

I am running on VS 2015 Update 2 on Windows 10.

Any ideas?

**Comment by ErikEJ** [comment]
I assume you have no .build folder in your repo - if you do, delete it. Clear .nuget cache? There is a cache under  %userprofile%\.nuget . You can delete that directory directly or if you have the latest nuget command line tool you can try  nuget locals all -clear .

**Comment by davidroth** [comment]
Thanks @ErikEJ - deleting the `%userprofile%.nuget` folder did the trick :+1:
