### ISSUE TITLE
 ef7 DbDataReader' does not contain a definition for Close and no extension method 'Close' accepting a first argument of type 'DbDataReader' could be found

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/efcore#5181]
Originally posted by @stevensrf1 at https://github.com/aspnet/Tooling/issues/449

The more I use ef7 the more it sucks.
I need to call a stored procedure using ef7.
I read many ways to do this but none of the methods used to do this exist. Especially the FromSQL that is suppose to be available.
So I just got the DBConnecton from the DBContext and called a stored procedure int he normal way,
An error appears saying the Datareader Close method can not be found but it is available in DNX 4.5.1 and not available in DNX Core 5.0. What the ****, Those two assemblies were added to the project automatically at start up. I am starting to want to join the GD Microsoft club,

**Comment by rowanmiller** [comment]
@stevensrf1 did you have a using statement for `Microsoft.Data.Entity`? `FromSql` is an extension method and you need that namespace to get it (and our other query related extension methods).
