### ISSUE TITLE
Entity Framwork 7.0.0-rc1-final reverse engineer from existing db "Database first"

### ISSUE THREAD

**Issue by DevNeeraj** [dotnet/efcore#5194]
> I am doing reverse engineering in my project. because in our project we follows database first approach.
> Through this command, i achieved reverse engineering but not with **RevEng** command.

`dnx ef DbContext Scaffold "Server=databasename;Database=data;UserID=*;Password=*;" EntityFramework.MicrosoftSqlServer
`

> I have tried many things but still unable to find **RevEng** command under the **ef**.

In a project, i am using

```
 "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel",
        "ef": "EntityFramework.Commands"
    }
```

and

```
 "dependencies": {
        "EntityFramework.Commands": "7.0.0-rc1-final",
        "EntityFramework.Core": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
        "EntityFramework.MicrosoftSqlServer.Design": "7.0.0-rc1-final",
        "EntityFramework.Relational.Design": "7.0.0-rc1-final",        
}
```

So how can i enable **RevEng** command in **dnx**, 
Help me to out !

**Comment by ErikEJ** [comment]
There is no command called RevEng. Just scaffold

**Comment by DevNeeraj** [comment]
Then what is RevEng command?  I have checked in many post they using RevEng command to get reverse engineering

**Comment by ErikEJ** [comment]
A link to one of the posts?

**Comment by DevNeeraj** [comment]
Some are 
http://stackoverflow.com/questions/30419577/entity-framework-7-reverse-engineering-asp-net-5/30426177#30426177

http://stoutcloud.com/geek-out-entity-framework-7/geek-ef7-reverse-engineering-first-look/

**Comment by lajones** [comment]
There has been a lot of change in this area. The command was originally called `reveng` - which was short for "reverse engineering". But it was changed to `dbcontext scaffold` a while back. `reveng` no longer exists. I'm closing this issue as that seems to answer your question. But feel free to re-open if there's anything I missed.

**Comment by DevNeeraj** [comment]
@lajones 
It's fine for me too. Thanks for this. 
But i have many queries related ef 7 7.0.0-rc1-final ? where i have discusses my queries ?

**Comment by lajones** [comment]
@DevNeeraj You can raise another issue in this forum. But please look over the existing issues before you do - many RC1 issues regarding query have been addressed.

**Comment by DevNeeraj** [comment]
Okay,
Thank you
