### ISSUE TITLE
Cannot have keys other than those declared on the root type

### ISSUE THREAD

**Issue by peirens-bart** [dotnet/efcore#5201]
I'm having problems mapping types in an inheritance gain.

My Models:

```
public class Entity
    {
        public int Id { get; set; }

        public byte[] Timestamp { get; set; }

    }
```

```
public class BinaryImage: Entity
    {
        public string Name { get; set; }

        public byte[] Data { get; set; }

        public string Extension { get; set; }
    }

```

My context:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("dead_user");
            FrameworkModelsMapper.Map(modelBuilder);
            SecurityModelsMapper.Map(modelBuilder);
            MyDatabaseModelsMapper.Map(modelBuilder);
        }

        #endregion

        #region DbSets
        public virtual DbSet<BinaryImage> BinaryImages { get; set; }
```

My Mapper

```
 internal class FrameworkModelsMapper
    {
        internal static void Map(ModelBuilder builder)
        {
            builder.Entity(MapBinaryImage());
            builder.Entity(MapValuta());
            builder.Entity(MapCountry());

        }

        internal static void MapEntity<T>(EntityTypeBuilder<T> builder) where T : Entity
        {
            builder.HasKey(x => x.Id);  **=> give exception**
            builder.Property(x => x.Timestamp)
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();
        }

        private static Action<EntityTypeBuilder<BinaryImage>> MapBinaryImage()
        {
            Action<EntityTypeBuilder<BinaryImage>> config = builder =>
            {
                MapEntity(builder);
                builder.Property(x => x.Data).IsRequired();
                builder.Property(x => x.Name).IsRequired();
                builder.Property(x => x.Extension).IsRequired();
            };
            return config;
        }
}
```

Exception in command line
C:\Code\BookerTools\Source\Development\Version_1\Source\BookerTools.Database.EF>
**dnx ef migrations add BT-0001 -c "ApplicationContext" -p "BookerTools.Database.E
F"**
System.InvalidOperationException: The derived type 'BookerTools.Framework.Models
.BinaryImage' cannot have keys other than those declared on the root type.
   at Microsoft.Data.Entity.Metadata.Internal.EntityType.AddKey(IReadOnlyList`1
properties)
   at Microsoft.Data.Entity.Metadata.Internal.MetadataDictionary`2.GetOrAdd(Func
`1 getKey, Func`1 createKey, Func`2 createValue, Func`2 onNewKeyAdded, Configura
tionSource configurationSource)
   at Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder.HasKey(I
ReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.Internal.InternalEntityTypeBuilder.PrimaryK
ey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.Builders.EntityTypeBuilder`1.HasKey(Express
ion`1 keyExpression)
   at BookerTools.Database.EF.Mappers.FrameworkModelsMapper.MapEntity[T](EntityT
ypeBuilder`1 builder)
   at BookerTools.Database.EF.Mappers.FrameworkModelsMapper.<>c.<MapBinaryImage>
b__5_0(EntityTypeBuilder`1 builder)
   at Microsoft.Data.Entity.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at BookerTools.Database.EF.Mappers.FrameworkModelsMapper.Map(ModelBuilder bui
lder)
   at BookerTools.Database.EF.Context.ApplicationContext.OnModelCreating(ModelBu
ilder modelBuilder)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext con
text, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Fu
nc`2 valueFactory)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.In
voke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetServ
ice[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite
.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite
.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite
.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequ
iredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequ
iredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name
, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddM
igration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
The derived type 'BookerTools.Framework.Models.BinaryImage' cannot have keys oth
er than those declared on the root type.

Is there something that I'm missing?

**Comment by peirens-bart** [comment]
Found the cause of the issue,
One of the models has a property with object as type. if I add ignore on that property everything is working (and ignore is the correct behavior for that property).
I must say, the exception message is a bit confusing, I was looking in BinaryImage but the problem was in  TeamOptions object. BinaryImage is just the first model that I map.

**Comment by smitpatel** [comment]
Exception message has been updated after RC1 see #3727
