### ISSUE TITLE
support for key-value storage

### ISSUE THREAD

**Issue by erikzhang** [dotnet/efcore#5202]
Is there any plans in the future to support key-value storage such as leveldb?

**Comment by rowanmiller** [comment]
Yes. For the 1.0.0 release we are focusing on relational providers, but once that is released we will be bringing other providers online. Our team will be starting with our Azure Table Storage and Redis providers (which we have already prototyped). Ideally providers are written by folks that own the database engine, but we may also pick off a key value store too.
