### ISSUE TITLE
EF doesn't detect [Required] model change (NOT NULL)

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/efcore#5224]
WHen you make a model change and add [Required]  - EF doesn't detect this change and you can create/edit data. WHen you run migrations, it does pick this up:

```
 protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "Movie",
                nullable: false);
```

Expected behavior: 
After adding [Required]  to the model and NOT running migrations/update, EF should throw because the schema is out of sync.

Actual behavior:
The change is not detected and no exception is thrown.

**Comment by rowanmiller** [comment]
Are you expecting EF to validate that the data is non-null before saving to the database? In EF Core we dropped doing validation since it is usually already done client-side, server-side, and then in the database too.

**Comment by Rick-Anderson** [comment]
I was expecting EF to detect the schema change and not let me work with the old model. No change is detected and I'm not require to run migrations/update. IOW, I don't get this message after making this change to my model:

A database operation failed while processing the request.

SqlException: some message
There are pending model changes for mov1Context

Scaffold a new migration for these changes and apply them to the database from the command line:
> dotnet ef migrations add [migration name] 
> dotnet ef database update

**Comment by rowanmiller** [comment]
Ah, yep we also don't do any of that in EF Core. It was part of a larger move to not do any database initialization work at all. The initialization logic we had in EF6.x was helpful in some very basic cases, but also a huge source of bugs and pain for customers.

**Comment by br3nt** [comment]
@rowanmiller , Is there a canonical way to perform validation in non-MVC apps without having dependencies on MVC or WebApi.Core packages?

**Comment by Rick-Anderson** [comment]
@br3nt  EF doesn't do model validation.

**Comment by br3nt** [comment]
@Rick-Anderson Yes, I know.
