### ISSUE TITLE
Migration commands are not logged !?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5234]
Or am I doing something wrong: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Extensions/Logging/DbLoggerProvider.cs#L25

Or is it the well known issue of the command text of a SqlCeCommand being cleared when the instance is dosposed? https://github.com/aspnet/EntityFramework/blob/21fdcf99d8aa00defb03d05e6c883d4df3de79fc/src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalDataReader.cs 

Rc2-20581 btw

**Comment by natemcmaster** [comment]
@ErikEJ can you clarify what behavior you are expecting and not seeing? Are you talking about design-time logging? Or logging when `db.Database.Migrate()` is called?

**Comment by ErikEJ** [comment]
Logging when Migrate is called!

**Comment by bricelam** [comment]
> Or is it the well known issue of the command text of a SqlCeCommand being cleared when the instance is dosposed?

This.

**Comment by ErikEJ** [comment]
Ok. Any thoughts re fixes/ workarounds? I cannot fix the ado.net provider bug, but open to any suggestions!

**Comment by bricelam** [comment]
@anpete Any thoughts on this one?

**Comment by anpete** [comment]
@ErikEJ Any way to wrap the command so that it preserves its state after Dispose?

Alternatively, we would need to re-jig our Execute methods in RelationalCommand

**Comment by ErikEJ** [comment]
@anpete I could do that yes, (as has been done before: https://entityframework.codeplex.com/SourceControl/latest#src/EntityFramework.SqlServerCompact/SqlCeMultiCommand.cs) - but where would I tell EF Core to use the wrapped command??

**Comment by anpete** [comment]
@ErikEJ We call CreateCommand on DbConnection so likely you need to override that.

**Comment by ErikEJ** [comment]
I guess that would mean I also would have to wrap SqlCeConnection, or??

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Storage/Internal/SqlCeDatabaseConnection.cs

**Comment by rowanmiller** [comment]
**Triage:** Concluded that this should be worked around in CE

**Comment by ErikEJ** [comment]
Ok - any suggestions/hints for the wrapping approach? @rowanmiller
