### ISSUE TITLE
Entity Framework doesn't follow ASP.NET rules for hosting environment.

### ISSUE THREAD

**Issue by MicahZoltu** [dotnet/efcore#5236]
``` c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddEntityFramework()
            .AddSqlServer()
            .AddDbContext<MyContext>(options => options.UseSqlServer(Configuration["SqlServerConnectionString"]));
    }

    public void ConfigureDevelopmentServices(IServiceCollection services)
    {
        services.AddEntityFramework()
            .AddSqlite()
            .AddDbContext<MyContext>(options => options.UseSqlite(new SqliteConnectionStringBuilder { Datasource = ":memory:" }.ToString()));
    }
}
```

When I run this with this DNX command: `"web": "Microsoft.AspNet.Server.Kestrel"` the code correctly steps through the `ConfigureDevelopmentServices` method and _NOT_ the `ConfigureServices` method.

However, when I run `dnx ef migrations add Foo` (`"ef": "EntityFramework.Commands"`), it gives me an exception complaining about not being able to find the `SqlServerConnectionString` indicating that the production code is running, not the development code.  `SqlServerConnectionString` is not available in development, only Sqlite is available in development so this error is correct but the code path leading up to it is the problem.

I tried `dnx ef migrations add --environment Development Foo` but that resulted in the same problem.  I also added a log line to `Startup` constructor to output the `hostingEnvironment` and it shows `hostingEnvironment.EnvironmentName` is `Development` (whether I add the `--environment` switch or not).

**Comment by natemcmaster** [comment]
Thanks for the PR @Zoltu. Just so you know, because of our release schedule, this change won't be in the upcoming RC2 release. You can workaround this bug by using IHostingEnvironment and conditionally adding services within `Startup.ConfigureServices`
