### ISSUE TITLE
EF6 microbenchmarks are flaky

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#5242]
The EF6 microbenchmarks fail on cleanup sometimes, potentially leaving the database in an invalid state.

```
Test collection for Microsoft.EntityFrameworkCore.Microbenchmarks.EF6.Query.RawSqlQueryTests (1)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

[http://aspnetci/viewLog.html?tab=buildLog&buildTypeId=Lite_EntityFramework&buildId=88056#_focus=12730]()

**Comment by rowanmiller** [comment]
There doesn't seem to be anything actionable on this one. The EF6 benchmarks don't do any cleanup work and it looks like every test in the run failed with the same error (not just the benchmarks).

**Comment by rowanmiller** [comment]
Discussed with @AndriySvyryd  and it's a little unclear from the log what exactly causes the `Collection was modified` exception.
