### ISSUE TITLE
EF7 RC2 on dnx451

### ISSUE THREAD

**Issue by NickSevens** [dotnet/efcore#5244]
When trying to include package "EntityFramework.MicrosoftSqlServer": "7.0.0-rc2-16649" in project.json I receive an error in package restore:

"NU1002: The dependency Microsoft.Extensions.Caching.Abstractions 1.0.0-rc2-20456 does not support framework DNX,Version=v4.5.1

I've tried the same with "dotnetcore50" and some other framework, but nothing works... :(

**Comment by divega** [comment]
That package got renamed to Microsoft.EntityFrameworkCore.SqlServer for RC2.

**Comment by Trickass** [comment]
Okay, didn't know that :) but still, using that package gives me the exact same issue...

**Comment by rowanmiller** [comment]
@natemcmaster any thoughts on this one?

**Comment by natemcmaster** [comment]
AFAIK we haven't tested EF Core RC2 on DNX because dnx is retired. EF Core relies on dependencies that work with dotnet-cli (https://github.com/dotnet/cli) but do not necessarily work with dnx. @Trickass you could try to use "imports" in project.json to make "dnx451" backwards compatible, but I don't know what the imports are.

@rowanmiller is this a scenario we want to support?

**Comment by rowanmiller** [comment]
This isn't a "blessed scenario"... DNX is retired as of RC2 in place of CLI.

**Comment by Trickass** [comment]
I think I basically got very confused with all dnx, cli, dotnet, ... versions out there... That combined with dev, test, rc, ... package sources really makes me lose track of what I need to work with those packages. :/

**Comment by rowanmiller** [comment]
@Trickass totally get it, things are in a super confusing state at the moment. It will all settle down a lot when we get RC2 out the door and you don't have to rely on a whole bunch of nightly builds of things that sometimes work together.

**Comment by Trickass** [comment]
Great :) i guess i'll survive for another couple weeks without rc2 ;)
Thanks for the info!
