### ISSUE TITLE
Bad reference for Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5245]
Hi,
I am working with a slightly newer version of EF7, which I got off MyGet (EntityFramework.Core.7.0.0-rc2-16769).
Since I upgraded to this from 7.0.0-rc1, creating my DbContext fails in the constructor:

`System.MissingMethodException : Method not found: 'Void Microsoft.Extensions.Logging.ILogger.Log(Microsoft.Extensions.Logging.LogLevel, Int32, System.Object, System.Exception, System.Func`3<System.Object,System.Exception,System.String>)'.`

By decompiling the code, I see that there's a call in `CoreLoggerExtensions`:

`logger.Log((LogLevel) 5, (int) eventId, (object) state(), exception, (Func<object, Exception, string>) ((_, e) => formatter(e)));`

But the corresponding code in `ILogger` has a different signature:

`void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);`

Obviously I've got the wrong dependencies installed - but where do I get the right version of `Microsoft.Extensions.Logging`?

**Comment by divega** [comment]
Entityframework.codeplex.com got renamed to Microsoft.EntityFrameworkCore.SqlServer for RC2. You are likely getting a very old build.

**Comment by rowanmiller** [comment]
@shaulbehr can you share details of what feed you are installing from etc.

**Comment by shaulbehr** [comment]
@divega Thank you.  I think that will probably make a big difference... :)

**Comment by Imjamshid** [comment]
I got the same issue..

An exception of type 'System.MissingMethodException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code

Additional information: Method not found: 'Void Microsoft.Extensions.Logging.ILogger.Log(Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, !!0, System.Exception, System.Func`3<!!0,System.Exception,System.String>)'.


used the following feed to install.

https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/1.0.0-rc2-final
