### ISSUE TITLE
Microsoft.EntityFrameworkCore.Tools does not support Shared Projects

### ISSUE THREAD

**Issue by Sohra** [dotnet/efcore#5248]
A number of the PowerShell commands take a Project parameter that allows you to specify which project is used.  Take for example Add-Migration, the parameter indicates which project will have the migration code added to it.  Used in combination with the OutputDir parameter on this cmdlet, one can control the project and folder/sub-namespace migration code is placed in.

However if a shared project is specified (.shproj files) for the Project parameter, an error is raised:
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Project 'SharedProjectName' is not found.

I think it reasonable to support these as both Visual Studio & MSBuild handle them just fine when other projects reference them (yeah, actually adding that reference requires manually inserting an Imports for the corresponding .projitems, but I believe there are extensions to assist with this and Visual Studio might enable it natively one day.  Visual Studio does render the references to shared projects in the references node though).

**Comment by Sohra** [comment]
I noticed that the `propose-close` label was removed some time back yet nobody took this up, and since I raised it I figured perhaps I should give a solution some thought...

The EF Core script appears to use https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-get-project which does not support Shared Projects - the error I reported actually seems to come from - and it's using EnvDTE under the hood.  That gave some direction, and I've come up with an enhancement to the `GetProject` function within  `EntityFrameworkCore.psm1` which I can type directly into Visual Studio's Package Manager Console, and subsequently invoke to select shared projects within the solution.  I can then call `ProjectItems.AddFromFile` on that object to add files to the project, just like the Add-Migration cmdlet is doing.

With that progress, I would like to go about testing the simple change as part of an updated version of `EntityFrameworkCore.psm1` but I'm not yet very familiar with the build/deployment/testing setup in this repo.  Could anybody give me some guidance on how I might best test this?

**Comment by ajcvickers** [comment]
@Sohra I'll discuss with the team and get back to you.

**Comment by ajcvickers** [comment]
@Sohra We discussed this and we would certainly consider a robust PR for this if you get it working. See https://github.com/aspnet/EntityFrameworkCore/blob/master/docs/getting-and-building-the-code.md for guidance on building the source here. You'll need to do a `-pack` at some point to create NuGet packages from your local code that you can test from a [local package feed](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds).
