### ISSUE TITLE
Mixing sync and async APIs on SqlClient for Linux overwhelms connection pooling

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#5254]
The test re-enabled in https://github.com/aspnet/EntityFramework/pull/5062 fails on Linux consistently. We should investigate if this is a bug in SqlClient or in our test setup.

```
Can_use_sequence_end_to_end_from_multiple_contexts_concurrently_async
```

**Comment by natemcmaster** [comment]
This may be an issue in SqlClient connection pooling on Linux.

Test setup:
50 tasks created. Each task opens a connection to SQL Server to request the next sequence value for 20 items. Tasks run concurrently. On Windows, .NET Core and .NET Framework, this test always passes just fine. On Linux, this test is flaky. It fails about 50% of the time on our CI server:
```
System.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while
 establishing a connection to SQL Server. The server was not found or was not accessible. Verify 
that the instance name is correct and that SQL Server is configured to allow remote connections. 
(provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```

Here is the log output for Linux and Windows. Log output represents actual order of execution. Each line identified with the task number.

[Windows_log.txt](https://github.com/aspnet/EntityFramework/files/273352/Windows_log.txt)
[Linux_log.txt](https://github.com/aspnet/EntityFramework/files/273351/Linux_log.txt)


As you can see in the Windows log, EF only opens about 12 connections at a time. It appears pooling is kicking it to prevent overwhelming the server. 

In the Linux log, EF tries to open hundreds of connections without waiting for currently open connections to close.

cc @saurabh500 are there known issues with SqlClient connection pooling on Linux?

**Comment by saurabh500** [comment]
@natemcmaster  we havent seen such an issue for SqlClient on Linux. This seems like a networking issue. The error is seen when SqlClient cannot open a TCP connection to the Sql Server. 

Is this the only use case you are seeing this? Or can this be reproed for any other test case as well? 


cc @corivera

**Comment by saurabh500** [comment]
More questions 
1. Whats the sql server version? 
2. Do you see this without pooling as well?

**Comment by natemcmaster** [comment]
Made a minimal repro without EF and opened an issue: https://github.com/dotnet/corefx/issues/8701

**Comment by saurabh500** [comment]
Will take a look at it. Thanks for the minimal repro.

**Comment by natemcmaster** [comment]
Per this comment, https://github.com/dotnet/corefx/issues/8701#issuecomment-221961745, Linux has decreased scalability with .Open() compared to Windows. 

cc @divega @ajcvickers this may have implications for the change tracker and sequences. In the test that is failing [see test code here](https://github.com/aspnet/EntityFramework/blob/975b6840ee5c4f16cba202a4a8b88d10e18b8cca/test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs#L103-L156), every call to DbSet.Add fires a query to fetch a sequence value. This is using .Open, not .OpenAsync. Is there anyway EF can mitigate the issue on Linux?

**Comment by divega** [comment]
My understanding is that this test is purposely very chatty with the database. Hopefully the problem with the connection pool on Linux is fixable, but customers that are trying to make their application scale better have better options, like using HiLo (which will only get a new value from the database periodically) or sequences as default values instead of using sequences like this. 

In the future we can also bring back AddAsync() and the async path for value generators. https://github.com/aspnet/EntityFramework/issues/2291 contains some context on why we removed it and why we would bring it back.

**Comment by rowanmiller** [comment]
We'll bring back AddAsync in 1.1.0 - https://github.com/aspnet/EntityFramework/issues/2291
