### ISSUE TITLE
CLI Commands: PMC invokes scaffolding with incorrect arguments

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#5260]
When invoking Scaffold-DbContext on a .NET Core project, the powershell generates an incorrect argument list.

```
Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=northwind;Integrated security=true" Microsoft.EntityFrameworkCore.SqlServer -Verbose -DataAnnotations
Working directory: C:\Users\namc\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApp1
Executing command: dotnet ef --verbose --configuration Debug --build-base-path .\bin\ dbcontext scaffold 'Server=(localdb)\mssqllocaldb;Database=northwind;Integrated security=true' Microsoft.EntityFrameworkCore.SqlServer - - d a t a - a n n o t a t i o n s
Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized option '-'    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName) 
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) 
    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args) 
 Unrecognized option '-' 
```

Somehow, the powershell is adding a space between every letter of `--data-annotations`

https://github.com/aspnet/EntityFramework/blob/3f67cf09cc66919c9ba3d9295965fa8ad12f98da/src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFramework.psm1#L474-L488

**Comment by deshazer72** [comment]
hey I get this when trying to scaffold my db 

Scaffold-DbContext "Server=www.bcsfirst.com,1433;Initial Catalog=Scada;Persist Security Info=False;User ID=myid;Password=mypassword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -Outputdir Models
Unrecognized option '--build-base-path'

I cant seem to fix it
