### ISSUE TITLE
Multiple Conditions in Where in Linq gives Error in EF7 SQLite

### ISSUE THREAD

**Issue by pradeepgade** [dotnet/efcore#5280]
Hi I am trying to give multiple conditions in the where clause for getting the data from the SQLite DB and it's giving an error.

> Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ParameterExpression'.

If I try with single condition (either of the conditions) I am able to retrieve the results.

Not Working Code:
`_context.Object1
.Include(r => r.Object2)
.Include(r => r.Object3)
.Where(r => r.Object2.StringId == StringIdToCompare1 && r.Object3.StringId == StringIdToCompare2)`

Working Code:
`_context.Object1
.Include(r => r.Object2)
.Include(r => r.Object3)
.Where(r => r.Object2.StringId == StringIdToCompare1)`

The StackTrace

>  at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
>    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>    at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
>    at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>    at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>    at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
>    at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>    at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
>    at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(IncludeSpecification includeSpecification, Type resultType, LambdaExpression accessorLambda, Boolean querySourceRequiresTracking)
>    at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
>    at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
>    at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
>    at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
>    at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
>    at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
>    at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
>    at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
>    at Remotion.Linq.QueryableBase`1.GetEnumerator()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by divega** [comment]
This is likely the same as #4597, which no longer repros in RC2.
