### ISSUE TITLE
IDbContextFactory and RC2 Migrations

### ISSUE THREAD

**Issue by danielcirket** [dotnet/efcore#5294]
As per the title if you use an `IDbContextFactory<TContext>` during migrations this must have a default constructor, or a `MissingMethodException` is thrown (Seems this has been mentioned previously here too after some further looking #4832).

Granted in this example the factory isn't really going to be required, however I have other projects which are going to be using an `IDbContextFactory<TContext>` factory implementation for various reasons.

I get the following error when trying to add a migration and assume that this is the culprit:

[DbContextOperations.cs Line 148](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DbContextOperations.cs#L148):

``` c#
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.<>c__DisplayClass12_0.<FindContextFactory>b__2()
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
No parameterless constructor defined for this object.
```

Bit of background on the project if required (using RC2 bits from the aspnetrelease feed):

```
...   
src\   
    \AspNetCoreRc2Project   
    \AspNetCoreRc2Project.Data   
    \AspNetCoreRc2Project.Entities   
...
```

In the website project Startup I have this:

``` c#
public void ConfigureServices(IServiceCollection services)
        {
            //services.AddMvc(); <-- This causes issues mentioned elsewhere for migrations so commented out for now
            services.AddDefaultServices();
            services.AddScoped<IConfiguration>(x => Configuration);
            services.AddDataServices(Configuration);
        }
```

`AddDataServices` is from an extension method in the Data class library project:

``` c#
 public static class ServiceExtensions
    {
        public static IServiceCollection AddDataServices(this IServiceCollection services, IConfiguration configuration)
        {
            if (configuration == null)
                throw new ArgumentNullException(nameof(configuration));

            services.AddEntityFrameworkSqlServer()
                    .AddDbContext<DataContext>(options =>
                    {
                        options.UseSqlServer(configuration["Data:ConnectionString"]);
                    });

            services.TryAdd(GetDataServices());

            return services;
        }

        private static IEnumerable<ServiceDescriptor> GetDataServices()
        {
            yield return ServiceDescriptor.Scoped<ISiteService, SiteService>();
            yield return ServiceDescriptor.Scoped<IDbContextFactory<DataContext>, DataContextFactory>();
        }
    }
```

I'll preface that with the above, and creating a migration does not work at all, because `options.UseSqlServer(...)` isn't picked up on.

So getting that I simply override the `OnConfiguring` method on the DataContext:

``` c#
protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(
                "Server={...}",
                b => b.MigrationsAssembly("WebMonitoring"));
}
```

The above is fine, when I don't want to get my connection string from a configuration file...

However I do, so I changed the constructor to inject the configuration like:

``` c#
public DataContext(IConfiguration configuration)
{
    if (configuration == null)
        throw new ArgumentNullException(nameof(configuration));

    _configuration = configuration;
}
```

and use this:

``` c#
protected override void OnConfiguring(DbContextOptionsBuilder options)
{
    options.UseSqlServer(
                _configuration["Data:ConnectionString"],
                b => b.MigrationsAssembly("ProjectName"));
}
```

This is OK and migrations work as expected with `dotnet ef migrations add <...>`, however if I implement a `IDbContextFactory<TContext>` such as:

``` c#
internal class DataContextFactory : IDbContextFactory<DataContext>
{
    private readonly IConfiguration _configuration;

    public DataContext Create()
    {
        return new DataContext(_configuration);
    }

    public DataContextFactory(IConfiguration configuration)
    {
        if (configuration == null)
            throw new ArgumentNullException(nameof(configuration));

        _configuration = configuration;
    }
}
```

I get the error mentioned at the beginning of the post.

**Comment by danielcirket** [comment]
Would it be possible to try and resolve the factory using the IServiceCollection first, rather than simply constructing it via Activator.CreateInstance?

Not sure what side-effects that would have though.

**Comment by rowanmiller** [comment]
@danielcirket `IDbContextFactory` is typically used when EF can't get a hold of the service provider (i.e. we can't work out how to interact with Startup.cs). If we can get the service provider, then we would just resolve the context directly and not worry about the factory.

**Comment by rowanmiller** [comment]
We'll look at this in RTM as part of the overall interaction with Startup.cs

**Comment by divega** [comment]
Just to add some information, from @bricelam comment at https://github.com/aspnet/EntityFramework/issues/4441#issuecomment-181505444:

> Think of `IDbContextFactory` as an application entry point. Just like the runtime entry point, it will need to setup the service container (e.g. by calling `Startup.ConfigureServices`)

This implies that with the current design `IDbContextFactory` implementations need to be self-contained and not take arguments. If we started resolving them from DI first, that would break the contract that "you just need to implement an `IDbContextFactory<T>` and we will find it".

**Comment by bricelam** [comment]
Notes for Triage: This is currently by-design. If an `IDbContextFactory` is found for the context, we will always try and use that to instantiate the `DbContext`. This is because `IDbContextFactory` is intended to override all other mechanisms (including getting an instance from the service provider and calling the `DbContext`'s default constructor).

**Comment by divega** [comment]
Agreed. For me the take away from this issue is that the name `IDbContextFactory` doesn't completely convey what it is for. It misses the fact that it is a self-contained way to obtain a fully configured context for design time tooling.

**Comment by rowanmiller** [comment]
Discussed and concluded that `IDbContextFactory` is just a design time activator for contexts - and should not be resolved from DI etc.. We did discuss changing the name to help convey this, but decided to keep as-is since there isn't a great name and we had an `IDbContextFactory` in EF6.x which does the same thing.
