### ISSUE TITLE
Wrong sample code in blog from Windows team

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5296]
Hi, I know it is not directly related to you guys, but could you perhaps contact the author of this blog post: https://blogs.windows.com/buildingapps/2016/05/03/data-access-in-universal-windows-platform-uwp-apps/ and help him/her update the code sample so it can compile? 

DatabaseContext => DbContext etc.

**Comment by natemcmaster** [comment]
Thanks @ErikEJ . I'll reach out internally to see if we can fix the sample.
