### ISSUE TITLE
Entity Framework maping data definition language of Description schema

### ISSUE THREAD

**Issue by yaochangyu** [dotnet/efcore#5297]
@code first
The Name property can mapping DDL of Description schema
public class Person
{
public int Id { get; set; }

[Description("姓名")]
public string Name { get; set; }
}

@database first
Description schema can convert property's DescriptionAttribute

@SQL
CREATE TABLE [ConsoleApplication3.MyDbContext].dbo.People (
Id int IDENTITY,
Name nvarchar(max) NULL,
CONSTRAINT [PK_dbo.People] PRIMARY KEY (Id)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

EXEC sp_addextendedproperty N'MS_Description',
N'姓名',
'SCHEMA',
N'dbo',
'TABLE',
N'People',
'COLUMN',
N'Name'
GO

**Comment by rowanmiller** [comment]
We don't intend to do this by default, but we do want it to be easy to plumb this thru model building and migrations. Opened https://github.com/aspnet/EntityFramework/issues/5390 to verify the experience (and document it).
