### ISSUE TITLE
ADO.NET Entity Data Model Template generate property(POCO) should add Column TypeName = "NVARCHAR" from Database

### ISSUE THREAD

**Issue by yaochangyu** [dotnet/efcore#5298]
ADO.NET Entity Data Model Template generate property(POCO) should add Column TypeName = "NVARCHAR" from Database

@Database
CREATE TABLE Test.dbo.Test (
Id INT IDENTITY
,Name NVARCHAR(50) NOT NULL
,CONSTRAINT [PK_dbo.test] PRIMARY KEY CLUSTERED (Id)
) ON [PRIMARY]
GO

@POCO (via ADO.NET Entity Data Model Template Generated)
[Table("Test")]
public partial class Test
{
public int Id { get; set; }

[Required]
[StringLength(50)]
public string Name { get; set; }
}

Can you add attribute of [Column(TypeName = "NVARCHAR")] ?

[Table("Test")]
public partial class Test
{
public int Id { get; set; }

[Required]
[StringLength(50)]
[Column(TypeName = "NVARCHAR")]
public string Name { get; set; }
}

**Otherwise, If I via Code First generate DB,I can not write Chinese.**

**Comment by rowanmiller** [comment]
Code first should use `nvarchar` by default for string properties. You would only get a non-Unicode column if you manually configure the `varchar` data type.

**Comment by yaochangyu** [comment]
Hi,
I Wrong, Sorry
I verified string property which generate NVARCHAR column in SQL Server
