### ISSUE TITLE
cannot add migration in a uwp app

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#5300]
I'm trying to add a ef 7 db context in a uwp app, following the tutorial in the docs site, but when I try to create the migration I have the error message "Object reference not set to an instance of an object."

Am I missing somthing?

**Comment by rowanmiller** [comment]
@lucamorelli are you using RC1 packages from NuGet.org?

**Comment by lucamorelli** [comment]
yes

**Comment by rowanmiller** [comment]
Could you retry with the [RC2 release](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-entity-framework-core-rc2/)

**Comment by rowanmiller** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.
