### ISSUE TITLE
No way of enabling IGNORE_DUP_KEY for unique indexes via code first

### ISSUE THREAD

**Issue by Jargon64** [dotnet/efcore#5301]
I've searched around regarding this and unless I'm mistaken there is no way to do this.

I have a service which receives a lot of data from multiple origins, however it is often that some of the data in each post is duplicated. Multiple records get added at the same time but if a duplicate exists none of them are saved (as an exception is thrown). I could break apart the record adds and save individually but that would become massively inefficient.

Most responses I've read regarding this issue say to check the incoming data first before adding but even the most optimal solution will quickly cause problems due to the eventual size of the table.

If there is a way to do this, I'd love to know. If there isn't, then I'd love to see this get added (and also have a decent suggestion on how to get around it in the meantime).

**Comment by rowanmiller** [comment]
I assume you are using migrations to create the database? If so, there is no default support baked in, but you could use the `Sql(string)` method in a migration to run the raw SQL statement to set this option for the index.
