### ISSUE TITLE
Can't install both Commands and SQLite into same project?

### ISSUE THREAD

**Issue by danBhentschel** [dotnet/efcore#5302]
I've tried this several times now in VS2015:

1) File -> New -> Project
2) Templates -> Visual C# -> Unit Test Project  w/ .NET Framework 4.5.2
3) Install-Package EntityFramework.SQLite -Pre
 ----> SUCCESS
4) Install-Package EntityFramework.Commands -Pre

> Attempting to gather dependency information for package 'EntityFramework.Commands.7.0.0-rc2-16649' with respect to project 'TestEF', targeting '.NETFramework,Version=v4.5.2'
> Install-Package : An error occurred while retrieving package metadata for 'Microsoft.Data.Sqlite.1.0.0-rc2-20466' from source 'C:\Users\DHentschel\Documents\Visual Studio 2015\Projects\TestEF\packages'.
> At line:1 char:1
> - Install-Package EntityFramework.Commands -Pre
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

If I try to install Commands first, and then SQLite second, the behavior is similar. Commands succeeds, but SQLite fails. Am I doing something wrong? I thought this worked the last time I tried, a few months ago.
- danBhentschel

**Comment by ErikEJ** [comment]
Do you have the latest version (3.4.3) of NuGet installed?

**Comment by danBhentschel** [comment]
I had 3.4.0. I just installed 3.4.3, and retried. Same behavior as before.

**Comment by danBhentschel** [comment]
Nevermind. I think I got it. I had AspNetVNext (https://www.myget.org/F/aspnetvnext/api/v2/) setup as a package source. Don't remember when or why I did that. When I removed that source, installation succeeds.

Perhaps the devs might still want to look into this??? But it's no longer an issue for me. I can move forward.

 - danBhentschel

**Comment by ErikEJ** [comment]
You were mixing rc1 and rc2 packages then, and that will not work.

**Comment by danBhentschel** [comment]
Thanks.
