### ISSUE TITLE
Attach not working

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5319]
Hi,
I'm testing attaching an object to a DbContext and saving, and it doesn't appear to work.  Perhaps my usage is incorrect?

```
            var repo1 = Container.GetInstance<IAcademicYearRepository>();
            var year = repo1.Save(new AcademicYear
                                  {
                                      DisplayName = "Old Name",
                                      StartDate = DateTime.UtcNow,
                                      EndDate = DateTime.UtcNow
                                  });

            year.AcademicYearId.ShouldNotEqual(Guid.Empty);

            var repo2 = Container.GetInstance<IAcademicYearRepository>();
            year.DisplayName = "New Value";
            repo2.Update(year);

            var repo3 = Container.GetInstance<IAcademicYearRepository>();
            var actual = repo3.Get(year.AcademicYearId);

            actual.ShouldHaveSamePropertyValues(year); // fails
```

Inside the Update code is:

```
            DbContext.Attach(entity);
            await DbContext.SaveChangesAsync();
            return entity;
```

I'm running Sql Profiler, and I find that the update query doesn't even fire.
Is there something wrong with my usage of .Attach?

**Comment by ajcvickers** [comment]
@shaulbehr Attach tells EF that the entity has not changed from how it exists in the database--i.e. no property values have been modified. Therefore when SaveChanges is called there are no modified values to write to the database and no update is sent. I would suggest going through some of the "getting started" documentation here: https://docs.efproject.net/en/latest/getting-started.html

**Comment by shaulbehr** [comment]
D'oh!  OK, that is facepalm-worthy.  I should have worked that out for myself.
Thanks!
