### ISSUE TITLE
Consider using Microsoft.Extensions.Caching.Memory for all caches

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#5322]
Currently we use `Microsoft.Extensions.Caching.Memory` for our first level query cache and our own custom caching for all other things across the EF Core stack. Since there is no automatic eviction in our custom caching code it would be possible to make EF consume all memory in caching by just doing enough things in an application, e.g. queries with many different combinations of parameters enter the second level query cache, many models are created dynamically, etc.

**Comment by divega** [comment]
Another thing we should consider here is the new explicit compiled query implementation. As far as I understand the delegates returned from the API are bound directly to the compiled query plans, which means that the more distinct compiled queries an application use the more memory will be used that cannot be freed up. We could instead use a unique identifier to point to an entry in the query cache like we do in EF6.

**Comment by ajcvickers** [comment]
We have done enough here with the changes for 3.0. We can revisit in the future if something else comes up.
