### ISSUE TITLE
The instance of entity type cannot be tracked, while updating twice the same entity

### ISSUE THREAD

**Issue by sadjadbp** [dotnet/efcore#5331]
I'm using RC1, so I'm adding DBContext in startup like this

`services.AddEntityFramework().AddSqlServer().AddDbContext<DataContext>();`

Then In my services, just DI my DataContext in the constructor and use it when I want. I think there is no issues here.

Then, I have a method in my service (called by a controller) let's call it F() that call two other methods F1() and F2(). In F1 and F2, I'll get list of Invoices entities from DataContext and update some of them, something like

`var invoices = DataContext.Invoices`
`.Where(x => x.InstallmentNextDate != null)`
`.Where(x => x.InstallmentDueDate != null)`
`.Where(x => x.InstallmentDueDate <= DateTime.Today)`
`.ToList();`

`foreach (var item in invoices)`
`{`
`if (....)`
`item.InstallmentNextDate = null;`
`DataContext.Invoices.Update(item);`
`}`
`DataContext.SaveChanges();`

F2() is also something like that. So some invoices would get updated in F1 and then F2; and if one entity updates twice, I'll get the "The instance of entity type cannot be tracked, ..." error. 

Why is that? I've already called SaveChanges() so shouldn't it remove the tracked objects?
I've tried AsNoTracking, AutoDetectChangesEnabled=false, QueryTrackingBehavior = QueryTrackingBehavior.NoTracking and no luck.

I just want EF for queries and then I'll let it know when/what should be updated, very simple. Am I doing things wrong?

**Comment by rowanmiller** [comment]
> Why is that? I've already called SaveChanges() so shouldn't it remove the tracked objects?

EF doesn't untrack things once it saves, since you may make further edits to the objects and then save again.

> I just want EF for queries and then I'll let it know when/what should be updated, very simple. Am I doing things wrong?

You should use a new context instance for each save operation. We recommend using short lived contexts - i.e. keep them for the smallest scope that makes sense for your application.
