### ISSUE TITLE
RevEng: Use Builder Approach to build *Configuration Classes

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#5352]
At the moment `ModelConfiguration` represents both a) view-model information necessary to output the `DbContext` and `EntityType` class files, and b) is used to create all the other `*Configuration` classes.

It would be better design to have a `ConfigurationBuilder` class which did b) and restrict `ModelConfiguration` to just being the view-model class.

**Comment by bricelam** [comment]
Can this be closed? The implementation has changed a lot since this was filed, and it no longer seems valid.
