### ISSUE TITLE
Migrations: PMC -Context tab completion not working on ASP.NET Core projects

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#5361]
![image](https://cloud.githubusercontent.com/assets/4741851/15263792/0026ef94-1922-11e6-99ab-53af90d30839.png)

**Comment by divega** [comment]
On the bright side it works in UWP projects :smile:

**Comment by rowanmiller** [comment]
And Console 😉

**Comment by natemcmaster** [comment]
I believe it works...there is just a big lag. What happens if you press tab and wait for 30 seconds?

**Comment by rowanmiller** [comment]
The issue was that I hadn't built the project, and tab completion doesn't trigger a build. We should dig into whether we can improve this post RTM.

**Comment by natemcmaster** [comment]
> it works in UWP projects 

> And Console

Actually, it doesn't work on those project types either. Tab completion on context types isn't available until the project has been built at least once. So to clarify, there are really two issues in this thread:

1. Tab completion for context types in PMC doesn't work until project is built (applies to all project types)
2. Tab completion for context types is slower on xproj than csproj.

Which are we trying to solve? (Or both?)

**Comment by rowanmiller** [comment]
Clearing up milestone to re-discuss in triage

**Comment by rowanmiller** [comment]
We're ok with needing to build
