### ISSUE TITLE
Why is there no FromSqlAsync method?

### ISSUE THREAD

**Issue by gdoron** [dotnet/efcore#5374]
Hi,

I there a reason why all the LINQ methods have Async "overload" but `FromSql` does not?

Thanks

**Comment by rowanmiller** [comment]
It's because `FromSql` doesn't actually cause the query to execute. There are only async versions of the methods that cause the query to execute (i.e ToList, First, etc.).

**Comment by gdoron** [comment]
Hmm Oops.

![image](https://cloud.githubusercontent.com/assets/6141009/15295993/fa76389e-1b9b-11e6-8850-d021d33d22d4.png)
