### ISSUE TITLE
[DatabaseGenerated(DatabaseGeneratedOption.Identity)] is not created on Code-First

### ISSUE THREAD

**Issue by portal7** [dotnet/efcore#5375]
I'm adding a ADO.NET Entity Data Model to my Class Library Project, and after map all fields from tables, looks like [Key] Attribute Decorator was added but not **[DatabaseGenerated(DatabaseGeneratedOption.Identity)]** Attribute Decorator when **PK** and **Identity (1,1)** is configured on Database.

So, because this, needs to put manually on each Entity Class a new "[DatabaseGenerated(DatabaseGeneratedOption.Identity)]" ...so whats i dong wrong or it's a bug?

Thanks!

**Comment by rowanmiller** [comment]
@portal7 if the primary key is an integer then the `DatabaseGenerated` attribute wouldn't be generated because integer primary keys are set to Identity by convention. We only generate attributes for things that do not get set by convention.
