### ISSUE TITLE
SQLite Migrate() - RC 2 - 20901

### ISSUE THREAD

**Issue by mvermef** [dotnet/efcore#5386]
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Additional information: SQLite Error 14: 'unable to open database file'.

this would be appropriate since I don't have it open, since it didn't create it........

``` C#
    using (var db = new ApplicationContext())
    {
        db.Database.Migrate();
     }
```

nor

``` C#
    using (var db = new ApplicationContext())
    {
       db.Database.EnsureCreated()
    }
```

works at all...

**Comment by ErikEJ** [comment]
Platform? Connection string?

**Comment by mvermef** [comment]
Sorry, UWP, UseSqlite("filename=data.db"), as was the case with RC1.  Pushing past the error with debugger does create but then app built on T10, just sits at splash screen churning on nothing...

**Comment by mvermef** [comment]
It should either navigate to login (in this case, this was expected), or navigate it main page token existed

**Comment by mvermef** [comment]
If I keep continuing it will create the database, not sure of the issue yet.

**Comment by divega** [comment]
Are you calling

**Comment by divega** [comment]
A few questions:
- Does this happen in debug, release or both?
- Is this code in an app or in a class library?
- Are you calling `SqliteEngine.UseWinSqlite3()`? 
- Otherwise, do you know what version of sqlite3.dll is begin loaded by the application?

**Comment by mvermef** [comment]
in app, debug so far.

not calling SqliteEngine.UseWinSqlite3()....

SQLite -> v3.11.0  is present in bin/debug/x86 folder

**Comment by AuroraDysis** [comment]
maybe you should create corresponding folder first

**Comment by mvermef** [comment]
why would I need to do that?  RC1 didn't require it why would RC2?

**Comment by MMalikKhan** [comment]
Its also happening in my app which i updated from RC1 to RC2 today. Same SQLite Version 3.11.0. this was all working fine in the RC1 for me it crashes on the line MigrateAsync? what has been changed here which needs to be updated in the below code? like @mvermef  said, after clicking continue bunch of times it does create that file in the required directory. any help is appreciated @divega @natemcmaster @maumar 

 var appDbContext = new AppDbContext(_filePath);
            await appDbContext.EnsureFilePathExists();
            await appDbContext.Database.MigrateAsync();
            return appDbContext;

**Comment by MMalikKhan** [comment]
@divega  @natemcmaster any update on the above issue, i have to make my work work in release mode but i cannot move forward with this error

first i get the error 
Exception thrown: 'System.ArgumentException' in System.Linq.Expressions.dll

Additional information: Instance field '_root' is not defined for type 'Microsoft.Extensions.DependencyInjection.ServiceProvider'

then followed by the above mentioned error

**Comment by MMalikKhan** [comment]
@mvermef hey .. did you happen to find any solution or work around, i am having the same issue in relase mode .. and code runs fine in debug mode.. appreciate your quick response

**Comment by natemcmaster** [comment]
@MMalikKhan I'm going to try to answer the original question posted in this issue. For the error you encountered https://github.com/aspnet/EntityFramework/issues/5386#issuecomment-220020630, can you open a separate issue?

@mvermef let me make sure I understand the problem. This the bug here that the database never gets created? Or is it that the exception is thrown? 

Some background that may help. By default, opening a new connection with SQLite will always create a db file *unless* the connection is "readonly". We uses this functionality to test if a dbfile is already present.
```c#
        public override bool Exists()
        {
            using (var readOnlyConnection = _connection.CreateReadOnlyConnection())
            {
                try
                {
                    readOnlyConnection.Open();
                }
                catch (SqliteException ex) when (ex.SqliteErrorCode == SQLITE_CANTOPEN)
                {
                    return false;
                }
            }

            return true;
        }
```
See https://github.com/aspnet/EntityFramework/blob/170ba2a1968e1e4e1d6d38c4213fd8afe57cf3e1/src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteDatabaseCreator.cs#L42-L57

In Visual Studio, if you have "first-chance" exceptions turned on, your debugger will pause on the exception even though our code has a catch to handle it. I'm inferring this your case from the comment above:

> If I keep continuing it will create the database, not sure of the issue yet. Usually have to continue 2 times

If "continuing" through the exception works and your app creates the database, then this is likely not actually a bug. You just need to turn-off first-chance exceptions (or launch without the debugger.) If this is the case, this blog post may help: https://blogs.msdn.microsoft.com/visualstudioalm/2015/01/07/understanding-exceptions-while-debugging-with-visual-studio/.

**Comment by mvermef** [comment]
From watching execution of the code there is no First Chance Exception, the only exceptions that are dropped into output are theses....

Exception thrown: 'System.Reflection.TargetException' in mscorlib.ni.dll
Exception thrown: 'System.Reflection.TargetException' in mscorlib.ni.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.ni.dll

**Comment by MMalikKhan** [comment]
@natemcmaster if i have no database in the folder, like if i uninstall and run, the Migrate method should create all the schema. It does create the DB file but not able to create any tables inside it. so the application after this is just crashing because there are not tables and no data @mvermef can you replicate this one .. ? i am using 1.3.2 Tool and UAP,Version=10.0.10586.0  one thing common between @mvermef  and my code base is i am using Template10 as well. And i dont think this could be the cause.. thanks for all your help

**Comment by natemcmaster** [comment]
> the only exceptions that are dropped into output are theses....

@mvermef can you clarify for me: which of these exceptions is crashing the app? What is the error message? And can you provide a repro sample?

**Comment by MMalikKhan** [comment]
@natemcmaster in the release mode it first crash with this error Exception thrown: 'System.ArgumentException' in System.Linq.Expressions.dll

Additional information: Instance field '_root' is not defined for type 'Microsoft.Extensions.DependencyInjection.ServiceProvider' 
then takes to that SQL database cannot open error

**Comment by MMalikKhan** [comment]
@natemcmaster  @mvermef  this is the sequence of the errors i am getting .. which generate the Databasefile but no table 

Exception thrown: 'System.ArgumentException' in System.Linq.Expressions.dll

Additional information: Instance field '_root' is not defined for type 'Microsoft.Extensions.DependencyInjection.ServiceProvider'

If there is a handler for this exception, the program may be safely continued.

Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll

Additional information: SQLite Error 14: 'unable to open database file'.

If there is a handler for this exception, the program may be safely continued.

Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll

Additional information: SQLite Error 14: 'unable to open database file'.

If there is a handler for this exception, the program may be safely continued.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.Threading.dll

Additional information: A task was canceled.

If there is a handler for this exception, the program may be safely continued.

**Comment by mvermef** [comment]
Not sure which is actually killing execution and continuance of the application to an actual working screen, at present it appears the EF may or may not be the issue..   My app will sit and do nothing so I am not sure if that is a SDK issue or not yet...

One thing I checked related to System.Linq.Expressions.dll was to see what version was pulled into the project.json.lock file and it was 4.0.10 for UWP but base compiler pulled in 4.0 which has be scratching my head looking at the actual version its 4.6 which would correspond to 4.6.1 of .net installed, if have that correct.  Reason I single out that dll, it is the cause for a directives warning on release build, related to 2 methods that are listed as public in the xml but should be private, BCL guys have already corrected it from what I read in another thread with corefx/coreclr

I will know here shortly, forgot about 1.3.2 update. Rolled back to RC1 and the file locking issue doesn't not occur, but I can say I am still seeing other things related to .native tool chain that I thought were fixed for RC2 hoping 1.3.2 update will correct those, directives are the bane of existence at present.

**Comment by MMalikKhan** [comment]
@mvermef  can you delete the database file and run the app in release mode. What i am having issue is it is not able to create database schema as it is unable to open the database.in debug build it does create the database and everything is working fine. with RC2 and 1.3.2 tooling..  with RC1 i didnot have this issue but i was having issue mentioned in [here](https://github.com/aspnet/EntityFramework/issues/5163#issuecomment-220017626)
looking at the logs i found .. thats when i was redirected to upgrade from RC1 to RC2 but i am not able to pass the database creation

ILTransform_0027: Ambiguous type name detected. There are types with name 'System.Collections.ArrayList' in both assembly 'System.Collections.NonGeneric' and 'System.Xml.XmlSerializer'. This directive is ignored. Consider placing this directive within an Assembly scope.

**Comment by divega** [comment]
> It does create the DB file but not able to create any tables inside it. so the application after this is just crashing because there are not tables and no data

It may be obvious but this typically happens if there are no migrations in your project. `ApplyMigrations()` will create the database if it doesn't exist but won't simply update the database to reflect the current state of the model but will apply any pending migrations. You have to at least have created the initial migration with the initial state of your model with will be able to create all the necessary tables on a blank database.

**Comment by mvermef** [comment]
updated to the 1.3.2, no effect.  What ever is causing my new issue isn't related to EF.  can close this issue.  EF does create the file, and it does have tables.  Something changes with this I will reopen.

**Comment by NPadrutt** [comment]
I get this issue when I execute a test in a UWP Test Project. Therefore the test fails. When I run the normally it works fine.. Is there a recommendation how to use with a test?

**Comment by milasch** [comment]
Is there any way I can prevent the exception from being thrown in the first place? My unit test executed on a TeamCity build agent report failure due to the first chance exception intermittently. `context.Database.EnsureCreated()` also throws the first change exception...

**Comment by ajcvickers** [comment]
@milasch We don't use exceptions for control flow in any case where we can come up with a reasonable alternative, but we are limited by what the underlying APIs/providers can do. It's unlikely that any place we are doing this will change.
