### ISSUE TITLE
Nuget package for rc2

### ISSUE THREAD

**Issue by mtycholaz** [dotnet/efcore#5387]
Haven't seen any updates to the NuGet packages yet. Are they coming soon?

**Comment by rowanmiller** [comment]
They are all on NuGet.org. The package names all changed for RC2 - https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html#package-names-and-versions.

**Comment by mtycholaz** [comment]
Sweet, thanks!
