### ISSUE TITLE
Improve end-to-end experience of annotating model and flowing thru migrations to schema

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#5390]
Spun off from https://github.com/aspnet/EntityFramework/issues/5297 (flowing `[Description]` into SQL Server extended properties).

**Comment by rowanmiller** [comment]
We need to verify the end to end experience and then look at ways to improve what is generated in migrations (i.e. can providers replace the code that shows what annotations were altered with there own first class methods, etc.).

As part of this, we should consider whether providers play a part in model diffing and if we allow custom migration operations.

**Comment by bricelam** [comment]
Possible overlap with #6546
