### ISSUE TITLE
Migrations: Opt out from IS NOT NULL in index creation

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#5415]
[When creating an index in migrations](https://github.com/aspnet/EntityFramework/blob/ce07379ec2d5e5e6d3e6077267bcd7c1dde58f92/src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L198) it would be nice if it was possible to specify on a per column basis whether the column should be generated as NOT NULL. Right now all columns are NOT NULL if the index is not clustered.

More generally, it would be nice if provider specific details were implemented in seperate overrideable methods, so that one could implement this with a custom migrations SQL generator. For example:

```
protected override void Generate(CreateIndexOperation operation, IModel model, MigrationCommandListBuilder builder)
        {
            Check.NotNull(operation, nameof(operation));
            Check.NotNull(builder, nameof(builder));

            base.Generate(operation, model, builder, terminate: false);
            AppendIndexWhere(operation, model, builder);

            EndStatement(builder);
        }

protected virtual void AppendIndexWhere(CreateIndexOperation operation, IModel model, MigrationCommandListBuilder builder)
{
            var clustered = operation[SqlServerFullAnnotationNames.Instance.Clustered] as bool?;
            if (operation.IsUnique
                && (clustered != true))
            {
                builder.Append(" WHERE ");
                for (var i = 0; i < operation.Columns.Length; i++)
                {
                    if (i != 0)
                    {
                        builder.Append(" AND ");
                    }

                    builder
                        .Append(SqlGenerationHelper.DelimitIdentifier(operation.Columns[i]))
                        .Append(" IS NOT NULL");
                }
            }
}
```

In this way I can call `base.Generate()` from a derived custom SQL generator and override the provider behaviour where needed by overriding each step. This is because I cannot call `base.base.Generate()` from my custom SQL generator, so it is currently an all or nothing situation.

**Comment by smitpatel** [comment]
You can override `AppendIndexWhere` in derived class and opt out of NOT NULL condition. Is it not working for you?

**Comment by rmja** [comment]
@smitpatel  Exactly, the problem is that `AppendIndexWhere()` [does not exist](https://github.com/aspnet/EntityFramework/blob/ce07379ec2d5e5e6d3e6077267bcd7c1dde58f92/src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L198), but is my proposal, where provider specific stuff is separeted out from the `Generate()` body, so that one can opt out :-)

**Comment by smitpatel** [comment]
Oh sorry. I thought those methods were in current codebase.
The reason provider specific details are not in separate method because it is provider specific SqlGenerator class. Providers derive from base SqlGenerator and modify the SqlGenerator in the way required for the specific provider.
I am not sure if you should be deriving from `SqlServerMigrationsSqlGenerator` class and not the base one.

**Comment by rmja** [comment]
I am deriving from `SqlServerMigrationsSqlGenerator`, but I don't want the `Generate()` from that, but the one from its base `MigrationsSqlGenerator`. If only the `Generate()` functions in `MigrationsSqlGenerator` were public instead of protected, then I could instantiate my own `MigrationsSqlGenerator` and call the `Generate()`'s directly.

**Comment by rowanmiller** [comment]
Related to https://github.com/aspnet/EntityFramework/issues/5532

**Comment by rowanmiller** [comment]
Note for triage, we thought this was a dupe but we had closed the other report of this as "won't fix". However, we've seen several folks not like the redundant `IS NOT NULL` specification now, so we should reconsider.

**Comment by rowanmiller** [comment]
We'll avoid creating the redundant checks, tracking this with https://github.com/aspnet/EntityFramework/issues/5532.
