### ISSUE TITLE
How to use EF7 with sharding tools?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5417]
Hi again,

I'm trying to follow the tutorial [here](https://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-tools-multi-tenant-row-level-security/), which gives a very nice walk through of how to use EF6 with elastic db in a multi-tenant app.

Now I'm trying to do the same thing in EF7, and of course a few interfaces have changed, particularly inside the `DbContext`.
- In EF6 there's a method for `Database.SetInitializer<TContext>()` which doesn't exist in EF7.  Is this replaced by `Database.EnsureCreated()`?
- In EF6 the base class for DbContext takes a `connectionString` parameter.  EF7 doesn't have that; rather it seems you have to call `options.UseSqlServer()` in `OnConfiguring()`.  If I just store the connection string locally in a private readonly variable (from a c'tor parameter), and use that value in `OnConfiguring()`, is that the right approach?
- In the step where we open the DDR connection via the public constructor, I'm totally lost.  This returns a SqlConnection object, but again, the EF7 DbContext doesn't have an overload accepting a `DbConnection`; it just has one overload accepting a `DbContextOptions`, which doesn't appear to have a connection string or anything else relevant.  What is the correct way to open the connection to the appropriate shard?

Thanks in advance for your help!

**Comment by shaulbehr** [comment]
@ajcvickers @rowanmiller Could you offer some help here, please?

**Comment by rowanmiller** [comment]
* In EF6 there's a method for  Database.SetInitializer<TContext>()  which doesn't exist in EF7. Is this replaced by  Database.EnsureCreated() ?

There is no concept of initializers in EF Core, you use the database APIs to take are of database setup during app startup. `EnsureCreated()` is the easiest way to get the database. `Migrate()` is the API to use if you are using migrations. Note `EnsureCreated()` and `Migrate()` are mutually exclusive.

> In EF6 the base class for DbContext takes a  connectionString  parameter. EF7 doesn't have that; rather it seems you have to call  options.UseSqlServer()  in  OnConfiguring() . If I just store the connection string locally in a private readonly variable (from a c'tor parameter), and use that value in  OnConfiguring() , is that the right approach?

Yes, that is a fine approach. Alternatively, you can externally create a `DbContextOptions<TContext>` and pass it in to the constructor (i.e. stop using `OnConfiguring` and create the options externally).

> In the step where we open the DDR connection via the public constructor, I'm totally lost. This returns a SqlConnection object, but again, the EF7 DbContext doesn't have an overload accepting a  DbConnection ; it just has one overload accepting a  DbContextOptions , which doesn't appear to have a connection string or anything else relevant. What is the correct way to open the connection to the appropriate shard?

There is an overload of `UseSqlServer(...)` that takes a `DbConnection`, so you would pass the connection there.
