### ISSUE TITLE
Cannot load some projects in EntityFramework.sln

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5420]
Using VS 2015 Update 2 on Win 8.1, I get these 2 errors when opening EntityFramework.sln on latest dev code - is that expected?

C:\Code\EntityFramework\test\Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests\Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Code\EntityFramework\test\Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests\Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests.xproj

C:\Code\EntityFramework\src\Microsoft.EntityFrameworkCore.Tools.Cli\Microsoft.EntityFrameworkCore.Tools.Cli.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Code\EntityFramework\src\Microsoft.EntityFrameworkCore.Tools.Cli\Microsoft.EntityFrameworkCore.Tools.Cli.xproj

**Comment by smitpatel** [comment]
I believe installation of dotnet SDK should have added those files. Can you try re-installing it?

**Comment by ErikEJ** [comment]
I dont think I ever installed it -- is it https://www.microsoft.com/net/download#core - .NET Core SDK Installer  (Preview 1) x64 ??

**Comment by smitpatel** [comment]
yes. x86/x64 should match with VS/system. Don't know if it matters.

**Comment by natemcmaster** [comment]
Install ".NET Core Tooling Preview 1 for Visual Studio 2015". https://go.microsoft.com/fwlink/?LinkId=798481

**Comment by ErikEJ** [comment]
Thanks @smitpatel  and @natemcmaster !

**Comment by ginesh** [comment]
Thank! that worked!
