### ISSUE TITLE
Query: Lift subquery in INNER JOIN to generate flattened query

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#5421]
For collection navigation include, we generate query of following structure at present

```
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
INNER JOIN (
    SELECT DISTINCT [c].[CustomerID]
    FROM [Customers] AS [c]
    WHERE [C].[CustomerID] = N'ALFKI'
) AS [c0] ON [o].[CustomerID] = [c0].[CustomerID]
ORDER BY [c0].[CustomerID]
```

It can be written as

```
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Customers] AS [c]
INNER JOIN [Orders] AS [o]
ON [o].[CustomerID] = [c].[CustomerID]
WHERE [C].[CustomerID] = N'ALFKI'
ORDER BY [c].[CustomerID]
```

Most of the work this change is available in @anpete's fork.

**Comment by divega** [comment]
Discussed this with @anpete and @smitpatel and I think we can do it as part of the "EXISTS" improvements @smitpatel is already doing, but would like to make the call in triage.

**Comment by ErikEJ** [comment]
@divega  Will those "EXISTS" improvements also affect https://github.com/aspnet/EntityFramework/issues/2626 ?

**Comment by smitpatel** [comment]
Exists improvements tracked by #4903

**Comment by smitpatel** [comment]
@ErikEJ - No.

**Comment by smitpatel** [comment]
While further exploring translations, I found that if the inner subquery has top or offset or needs DISTINCT then subquery may be required. We cannot convert it to flattened query.
With #4903 we have already removed inner join itself if there is no order by on non-principal-key column. So at present this translation seems to apply only the cases when there is no distinct/top/offset and there is order by on non-principal-key column. Considering that we may not need to do this change in RTM. Removing milestone. 

This translation can be applied to any Inner Join query so we may want to do it as a subquery lifting optimizer in future.

**Comment by divega** [comment]
Moving to 1.0.1 for reconsideration based on @smitpatel's comment. cc @rowanmiller

**Comment by ajcvickers** [comment]
@smitpatel Can we just close this one?

**Comment by smitpatel** [comment]
@anpete - Thoughts?

**Comment by ajcvickers** [comment]
Code has moved forward and this no longer has value.
