### ISSUE TITLE
Question: Guidance needed for disconnected entities

### ISSUE THREAD

**Issue by geoffmmorgan** [dotnet/efcore#5424]
I'm looking for some help on how to add entities to my context. The entities are object graphs that include sub entities each defined in their own tables. For example

```
public class Customer
{
     public int CustomerId { get; set; }
     public string Name { get; set; }
     public ICollection<Appointment> Appointments { get; set; }
}

public class Photo
{
     public int PhotoId { get; set; }
     public string Path { get; set; }
     public int AppointmentId { get; set; }
}

public class Appointment
{
     public int AppointmentId { get; set; }
     public int CustomerId { get; set; }
     public ICollection<Photo> Photos { get; set; }
}

public class MyDbContext : DbContext
{
     public DbSet<Customer> Customers { get; set; }
     public DbSet<Photo> Photos { get; set; }
     public DbSet<Appointment> Appointments { get; set; }
}
```

In this case from my server (this is a UWP app) I may get a new appointment. Once I do I would like to add this appointment to my local SQLite DB, however while the appointment may be new the Customer or Photos may or may not be. My question is what is the best way to add it to the context? If I simply do a `context.Appointments.Add(myNewAppointment)` I get "The instance of entity type 'Customer' cannot be tracked because another instance of this type with the same key is already being tracked." Right now I'm anticipating needing to walk through the appointment and check to see if the Customer or Photos already exist and if they do change the EntityState to modified. Is that right? or am I missing something simple.

**Comment by stevejgordon** [comment]
@geoffmmorgan I think then intended API for that would be the TrackGraph method which I believe walks the object graph and updates the entity states for the child entities. I've not used it yet myself. Something like context.ChangeTracker.TrackGraph(myNewAppointment, e => e.Entry.State = EntityState.Added);

**Comment by SimonOrdo** [comment]
Changes were made to Add/Entry.  Check out https://github.com/aspnet/EntityFramework/issues/4424

**Comment by stevejgordon** [comment]
@SimonOrdo Interesting thanks for the link. I need to go play with the latest RC2 release and see what's changed.

**Comment by geoffmmorgan** [comment]
The TrackGraph method worked for me, I did something like this

```
context.ChangeTracker.TrackGraph(serverAppointment, (item) =>
                            {
                                if (item.Entry.Entity is Appointment)
                                {
                                    var appointment = item.Entry.Entity as Appointment;
                                    item.Entry.State = context.Appointments.AsNoTracking().Any(a => a.AppointmentId == appointment.AppointmentId) ? EntityState.Modified : EntityState.Added;
                                }
                                else if (item.Entry.Entity is Customer)
                                {
                                    var customer = item.Entry.Entity as Customer;
                                    item.Entry.State = context.Customers.AsNoTracking().Any(a => a.CustomerId == customer.CustomerId) ? EntityState.Modified : EntityState.Added;
                                }
                            });
```
