### ISSUE TITLE
ef nuget nightly build for asp.net 4

### ISSUE THREAD

**Issue by lucamorelli** [dotnet/efcore#5441]
Hi, I don't understand why, but I have a problem with ef nightly build via nuget: configuring the same url as package source, if I try to add the package via nuget package management window in a asp.net 4 project I see the 1.7.0 version of the packages, but if I open the same window in a asp.net core project I see the current nightly build.
Am I missing something?

**Comment by rowanmiller** [comment]
Do you have the dropdown selected to include pre-release versions on the UI?

**Comment by lucamorelli** [comment]
ops, sorry, I had not noticed that inside the same vs session when I opened nuget in asp.net 5 project the flag was set, and in asp.net 4 not.
thanks
