### ISSUE TITLE
Question: Composite key EF 7 with Data Annotations

### ISSUE THREAD

**Issue by zenixgrace** [dotnet/efcore#5464]
Hi All,

Just wanna ask a stupid question.
Is the feature to define composite key with data annotations will not implement in the next release of EF 7?

Is the only way to implement that by using the Fluent API or it will update for the next release?

**Comment by rowanmiller** [comment]
@zenixgrace you need to use the Fluent API for composite keys. We do not plan to support composite keys with data annotations. We've documented this at https://docs.efproject.net/en/latest/modeling/keys.html.

**Comment by ygoe** [comment]
Why? Is it bad practice to have primary keys of two columns? Or is it too difficult to implement for EF Core?

**Comment by ajcvickers** [comment]
@ygoe See #10111
