### ISSUE TITLE
RC2. Related data is not being saved on saveChanges()

### ISSUE THREAD

**Issue by arthurspa** [dotnet/efcore#5465]
I have the following model:

```
public class League
    {
        // Own properties
        public int Id { get; set; }
        public string Name { get; set; }
        public LeagueGroup Group { get; set; }
    }
```

I'm able to create a new 'League'. If try to change `Group` field to another LeagueGroup, say `LeagueGroup { Id = 2 }` and then:

```
_context.Entry(newLeague).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
_context.SaveChanges();
```

I get no error, but the data is not persisted to database.

The strange thing is that if I change the property `Name` it successfully saves to the database.

I suppose the problem is saving related data.

Does anyone know if it's a bug or am I doing something wrong?

PS.: The same code using ASP.NET RC1 is working. When I create a blank ASP.NET Core (RC2) and try to use the code above I face this problem.

**Comment by SimonOrdo** [comment]
I don't think .Entry saves related entities any more.  Try .Attach, maybe?  

See #4424 for details.

**Comment by SimonOrdo** [comment]
I don't think .Entry saves related entities as of RC2.  Try .Attach maybe. 

See #4424 for details.

**Comment by SimonOrdo** [comment]
I don't think .Entry saves related entities as of RC2. Try .Attach maybe. 

See #4424 for details.

**Comment by rowanmiller** [comment]
Yep the `Entry` API is a low level atomic operation. If you want something that does a bit more heavy lifting for you, then `DbSet.Add/Attach/Update/Remove` are the APIs to use.

**Comment by arthurspa** [comment]
DbSet.Attach worked for me. Thanks.
