### ISSUE TITLE
RC2 Context constructor complaining on missing logging

### ISSUE THREAD

**Issue by jaklithn** [dotnet/efcore#5467]
I have a WinForms application.
Today I upgraded EntityFramework 7 RC1 to EntityFrameworkCore RC2 and followed the instructions.
But the call to base(options) now causes an exception:

Exception thrown: 'System.MissingMethodException' in Microsoft.EntityFrameworkCore.dll

Additional information: Method not found: 'Void Microsoft.Extensions.Logging.ILogger.Log(Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, !!0, System.Exception, System.Func`3<!!0,System.Exception,System.String>)'.

Should the DbContextOptions be initialized differently?

```
public static class ContextFactory
{
    public static MyContext GetContext()
    {
        var options = new DbContextOptions<MyContext>() ;
        return new MyContext(options);
    }
   }

public class MyContext : DbContext
{
            public MyContext(DbContextOptions<MyContext> options) : base(options)
    {
    }
   ....
```

**Comment by ErikEJ** [comment]
Could you share project.json / packages.config ?

**Comment by jaklithn** [comment]
Actually I just forced Nuget to update ALL packages even those I regarded not related. That seems to have fixed the issue. On calling assemply I had Logging RC1 references ....
Thanks for your attention!
