### ISSUE TITLE
Relational Metadata: Default constraint names don't include schema

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#5470]
Should constraint names include the table's schema?

For an entity configured with the following...

``` C#
modelBuilder.Entity<Employee>().ToTable("Employees", "hr");
```

...default constraint names currently look something like the following.

```
PK_Employees
AK_Employees_SSN
IX_Employees_ManagerId
FK_Employees_Employees_ManagerId
```

In EF6, they looked like this.

```
PK_hr.Employees
AK_hr.Employees_SSN
IX_hr.Employees_ManagerId
FK_hr.Employees_hr.Employees_ManagerId
```

**Comment by rowanmiller** [comment]
Do names have to be unique across the schema, or just the table?

**Comment by bricelam** [comment]
For SQL Server, just within a table. I think PostgreSQL requires indexes to be unique across the schema which is determined by the target table.

So the only place it would currently matter is when a table has two foreign keys that look identical except for the referenced table's schema.

**Comment by rowanmiller** [comment]
We'll leave it as-is, we can revisit in the future if it causes issues.
