### ISSUE TITLE
services.AddDbContext() delegate not firing

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/efcore#5484]
I have code like the following in `ConfigureServices()`:

``` csharp
services.AddDbContext<AlbumViewerContext>(builder => {
    var connStr = Configuration["Data:MusicStore:ConnectionString"];
    builder.UseSqlServer(connStr);
});
```

meant to initialize the context. However, the code in the delegate is never fired.

For now my workaround is to implement the context's OnConfiguring:

``` csharp
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    base.OnConfiguring(optionsBuilder);

    if (optionsBuilder.IsConfigured)
        return;

    ConnectionString = Config.GetValue<string>("Data:AlbumViewer:ConnectionString");
    optionsBuilder.UseSqlServer(ConnectionString);
}
```

This works, but doesn't allow for the same configurability at the application level.

What am I missing? Why is the builder delegate not firing?

RC2 bits

**Comment by damienbod** [comment]
The Context ctor has changed in RC2, maybe you need to update this:

Example:
```

public class DomainModelMsSqlServerContext : DbContext
    {
        public DomainModelMsSqlServerContext(DbContextOptions<DomainModelMsSqlServerContext> options) :base(options)
        { }
```
Greetings Damien

**Comment by RickStrahl** [comment]
Hey Damien,

How does that affect AddDbContext()?

Handling inside of DbContext is not a problem, it's configuring from the app level via the DI config.

+++ Rick ---

**Comment by damienbod** [comment]
Hi Rick, 

From what I understand, the DbContext requires the options which are passed form the DI. These are defined in the services.AddDbContext method.

```
// Use a MS SQL Server database
var sqlConnectionString = Configuration["Data:MusicStore:ConnectionString"];

services.AddDbContext<AlbumViewerContext>(options =>
    options.UseSqlServer(
        sqlConnectionString,
        b => b.MigrationsAssembly("YourParentProject")
    )
);
```
Greetings Damien

**Comment by RickStrahl** [comment]
Well, what I'm saying is that that code is not firing. Hooking a debugger that code will never get called and the connection string is never set through that code.

**Comment by ajcvickers** [comment]
@RickStrahl The delegate will not be called until the context instance is created, and then only if your context class accepts a `DbContextOptions<AlbumViewerContext>` in its constructor.

To be more specific:
* AddDbContext adds a service to the D.I. container for `DbContextOptions<AlbumViewerContext>`.
 * The service is added such that when it is resolved it will run the delegate provided to apply your options to the builder.
* When the app requests the DbContext from D.I. it will use constructor injection to resolve all the services that the DbContext depends on.
 * This means that `DbContextOptions<AlbumViewerContext>` must be one of the parameters of  the AlbumViewerContext constructor.
 * D.I will then resolve that service to create the builder, which will cause your delegate to run, and the resulting options will be passed to your context.

**Comment by RickStrahl** [comment]
Ah ok.

FWIW, I think this very unexpected behavior. The whole point of this interface is so that you can configure EF, so it would be nice if an OptionsBuilder could be created for you and passed to you unconfigured.

Having the extra constructor seems counter intuitive and not very discoverable. I suspect this will bite a lot of people.

**Comment by divega** [comment]
FWIW, at some point we had similar thoughts and we built some magic to inject the options without having to define the extra constructor on the derived `DbContext`. But the result proved to be confusing in its own way (see #4668 for more details), so we ended removing the magic so EF now works with DI more like most other things.

The documentation explains it in more detail here: https://docs.efproject.net/en/latest/miscellaneous/configuring-dbcontext.html.

**Comment by RickStrahl** [comment]
Ok, so the recommendation is to just implement that specific constructor.

Still think this will bite a lot of people because the only way to discover this behavior is by explitly implementing that constructor. It might be useful to add a note to the `AddDbContext()` method and the action parameter to indicate that it won't be fired unless the constructor exists (although I think I would have still missed it even then :-)).

**Comment by divega** [comment]
>  It might be useful to add a note to the  AddDbContext()  method and the action parameter to indicate that it won't be fired unless the constructor exists 

Sounds like something we should consider. I think @rowanmiller is tracking things we want to do to improve the documentation of these methods.

We also include a `DbContext` with the right constructor in our default templates.

Note that we still have a parameterless constructor which works when you don't want to pull dependencies from DI.

**Comment by RickStrahl** [comment]
Thanks. It looks like it works as long as `:base(DbContextOptions) ` is called. 

The documentation for this looks good.
