### ISSUE TITLE
Trouble installing Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5489]
Hi,
My project is referencing Microsoft.Extentions.CommandLineUtils v1.0.0-rc3-21031.
I am trying to run the command lines I remember from EF6 in the Package Manager Console, e.g. `update-database` and `add-migration`, but I'm getting an error:

```
update-database : The term 'update-database' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Have the commands changed?  If so, where can I find a reference of the commands available?

**Comment by mleader1** [comment]
I used 
`dotnet ef database update
`
and it works

**Comment by shaulbehr** [comment]
Actually, I think I can see a little better what's going wrong here.  I tried installing Microsoft.EntityFrameworkCore.Tools, and it looks like the installation is hanging on Microsoft.Extensions.Configuration.Abstractions:
```
...
  GET https://www.myget.org/F/aspnetcidev/api/v2/package/Microsoft.Extensions.Configuration.Abstractions/1.0.0-rc3-21031
  OK https://www.myget.org/F/aspnetcidev/api/v2/package/Microsoft.Extensions.Configuration.Abstractions/1.0.0-rc3-21031 302ms
Installing Microsoft.Extensions.Configuration.Abstractions 1.0.0-rc3-21031.
```
And it just stops there.

**Comment by shaulbehr** [comment]
@mleader1 that syntax is not familiar to me - I'm used to `update-database`.  Where can I find a reference for the available command line tools for `dotnet`?

**Comment by mleader1** [comment]
hi @shaulbehr  the one I mentioned is dotnet commandline tool  (i.e. the EntityFrmeworkCore.Tools you referred) 

I'm using the RC2 version and seems you refer to rc3 version I guess it should also work if you run it in command line as long as you have a correct project.json setting

**Comment by shaulbehr** [comment]
Eventually I got the package installed, this works now.  Sorry to clutter your list with non-issues... :)
