### ISSUE TITLE
Consistency in migration API

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/efcore#5491]
I've just finished spinning up the default project shipping with the latest RC of ASP.NET Core and I've noticed something that seems inconsistent in the migrations:

```

            migrationBuilder.CreateTable(
                name: "AspNetUserTokens",
                columns: table => new
                {
                    UserId = table.Column<string>(nullable: false),
                    LoginProvider = table.Column<string>(nullable: false),
                    Name = table.Column<string>(nullable: false),
                    Value = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                });
```

The migration that I'm highlighting here isn't important so much as the API it's using.  The parameter `columns` seems to take a closure that returns an object populated with all the desired columns.

The next parameter `constraints` takes a closure that returns no value but allows some calls to be made on `table`.

I suppose this could be classified as a question, but I think it might also be worthwhile to consider whether consistency in the behaviour of the parameters is worth having?

**Comment by rowanmiller** [comment]
We use the anonymous object return type in the `columns` parameter to provide "strong typing" on subsequent API calls. For example, the `x => new { x.UserId, x.LoginProvider, x.Name }` in the `PrimaryKey` call in your example code - `x` is the anonymous type defined in the `columns` call, so the column names aren't just strings.

**Comment by atrauzzi** [comment]
Wow, that's awesome!  Did not realize that.

Thanks :)
