### ISSUE TITLE
In RC2 how to update database on product.

### ISSUE THREAD

**Issue by chinaq** [dotnet/efcore#5509]
### The issue

In RC1 when I published a website, it generated a ef.cmd file, I can ran `ef database update` to update the product database. How can I do it in RC2 when there is no ef.cmd file.

**Comment by leak** [comment]
http://ef.readthedocs.io/en/latest/cli/dotnet.html#dotnet-ef-database-update

**Comment by rowanmiller** [comment]
@chinaq are you using the `right-click->Publish...` functionality in Visual Studio? If so, there is a checkbox in the wizard to apply migrations to the target database during deployment (new in RC2).

**Comment by chinaq** [comment]
Thanks @rowanmiller. I published by the wizard to apply migrations to the target database, but it comes another problem. Because my website and the repo are in different projects and assembles, it causes 
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(406,5): Error : Your target project 'SofuProdContr.BE.WebApi' doesn't match your migrations assembly 'SofuProdContr.BE.Repo2'. Either change your target project or change your migrations assembly.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(406,5): Error : Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("SofuProdContr.BE.WebApi")). By default, the migrations assembly is the assembly containing the DbContext.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(406,5): Error : Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
```
The context is in the repo assemble `SofuProdContr.BE.Repo2`, and I have to change the target to `SofuProdContr.BE.Repo2`. But When publishing I can not execute `donnet ef` manually. 

How can I resolve this?Thanks.

**Comment by leak** [comment]
You probably have to wait until #5320 will be resolved.

**Comment by rowanmiller** [comment]
@leak is correct, this is due to #5320 which is a limitation we are working to remove for the next release.

In the meantime, the best workaround is to revert to applying migrations in `Startup.cs`. You would do that by putting code like this in the `Configure(...)` method.

```c#
using (var context = new MyContext(app.ApplicationServices.GetRequiredService<DbContextOptions<MyContext>>()))  
{  
    context.Database.Migrate();  
}  
```
