### ISSUE TITLE
Ef Core RC2 and app insights

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/efcore#5510]
What would be the reason for not seeing EF's app insights in net core project? Not locally nor in Azure. Works ok for net452 though.

**Comment by MaximBalaganskiy** [comment]
I can see EF traces in output.

**Comment by MaximBalaganskiy** [comment]
After reinstalling ai extension inazure I see SQL dependencies. But the Command field is still missing both locally and on Azure.

**Comment by bojingo** [comment]
I am also having issues seeing SQL dependency telemetry in App Insights, both locally and in the Azure deployment.  This is a new Azure app with newly installed Application Insights extension on the Web App and I'm getting nothing SQL-related at all.

**Comment by rowanmiller** [comment]
EF Core uses SqlClient for it's database interaction, which is the component responsible for integration into App Insights etc. From your description is sounds like the .NET Core version of SqlClient has an issue with this integration. Could you open up and issue on the https://github.com/dotnet/corefx/ repository (where the SqlClient team tracks issues etc.)

**Comment by rwatjen** [comment]
This works now with Application Insights 2.2.0-beta1 (https://github.com/Microsoft/ApplicationInsights-aspnetcore/releases/tag/v2.2.0-beta1).
