### ISSUE TITLE
IMutableEntityType does not contain a definition for DisplayName

### ISSUE THREAD

**Issue by ithielnor** [dotnet/efcore#5515]
### Steps to reproduce

I followed the migration guides for RC1->RC2. I'm using the table name shim suggested in the EF migration guide within the `OnModelCreating` method:

```
foreach (var entity in builder.Model.GetEntityTypes())
{
    entity.Relational().TableName = entity.DisplayName();
}
```
### The issue

This code snippet does not compile. 

> 'IMutableEntityType' does not contain a definition for 'DisplayName' and no extension method 'DisplayName' accepting a first argument of type 'IMutableEntityType' could be found (are you missing a using directive or an assembly reference?)

My usings include `using Microsoft.EntityFrameworkCore;`
### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: Windows 10
Visual Studio version: VS 2015 Update 2

Other details about my project setup:

**Comment by smitpatel** [comment]
You will need this statement `using Microsoft.EntityFrameworkCore.Metadata.Internal;`

**Comment by divega** [comment]
Just to add to that, the caveat of adding that `using` statement to `Microsoft.EntityFrameworkCore.Metadata.Internal` or any other `*.Internal` namespace is that we will treat any types in that namespace as internal API surface and we can change it at any time. Taking a dependency on it is at your own risk.

**Comment by ithielnor** [comment]
Thanks. This is intended to be a temporary shim to get the migrations right. I will remove it once fully upgraded.
