### ISSUE TITLE
Consider documenting how to use a SQLite :memory: database

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/efcore#5516]
The [documentation](https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/miscellaneous/testing.rst#inmemory-is-not-a-relational-database) mentions SQLite's special file name `:memory:`, but to use this (for example during development), there are some hoops to jump through.

[#5086](https://github.com/aspnet/EntityFramework/issues/5086#issuecomment-210783773) contains the necessary code to make this work in an application using EF. Please consider adding this to the documentation, so users (like me :smile:) don't have to search the GitHub issues for `no such table: __EFMigrationsHistory`.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework.Docs#171
