### ISSUE TITLE
RC2 Question about the table name change to match property name

### ISSUE THREAD

**Issue by mtycholaz** [dotnet/efcore#5539]
One of the new changes in RC2 is that that table name of entities will match the property name. I'm not seeing this happen, in-fact my migration generated code puts the name of the entity as the table name.

But, if I run my code EF tries to find a table with my property name.

Is there a step I'm missing? Is this an option that must be enabled? I'm aware of the workaround [here](https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html#table-naming-convention-changes), but I'd prefer to use the new method.

I'm also aware that I can manually edit my migration to fix this, I'm just wondering why that's needed.

EF Core version: Version 1
Operating system: Windows 10 Pro
Visual Studio version: VS 2015

**Comment by rowanmiller** [comment]
Nothing should be needed to make this work. Can you share your code so that we can try and reproduce the issue.

**Comment by mtycholaz** [comment]
@rowanmiller Actually, I found the problem. 100% user error.
