### ISSUE TITLE
issue when running delete

### ISSUE THREAD

**Issue by spooky** [dotnet/efcore#555]
I'm using EF 7 alpha with asp.net vNext webapi and angular. I have a screen with basic crud operations.
The delete operation fails quite often but not always stating that either "Invalid operation. The connection is closed." or "The connection was not closed. The connection's current state is open." (both triggered just by executing a webapi call through angular's $resource).
The code for the webapi is the following:

```
public virtual async Task<IActionResult> Delete(int id)
{
    var t = await Items.SingleOrDefaultAsync(i => i.ID == id);
    if (t == null)
        return new HttpStatusCodeResult((int)HttpStatusCode.NoContent);

    Items.Remove(t);
    AppContext.SaveChanges();

    return new HttpStatusCodeResult((int)HttpStatusCode.OK);
} 
```

**Comment by 0xdeafcafe** [comment]
According to OP, this was fixed when migrating to beta3 (source, that SO link). Should this be closed?
