### ISSUE TITLE
Updating from RC1 to RC2 add-migration failes

### ISSUE THREAD

**Issue by ilogixxDE** [dotnet/efcore#5550]
We have updated our Project from ETFCore1RC1 to RC2. To check all is as expected we followed the update procedures.
Having all in place all is compiled fine. 
BUT:
add-migration throws an exception saying:

The child/dependent side could not be determined for the one-to-one relationship that was detected between 'EMailMessageData.EMailMessage' and 'EMailMessage.EMailData'. To identify the child/dependent side of the relationship, configure the foreign key property. See http://go.microsoft.com/fwlink/?LinkId=724062 for more details.

In RC1, this worked like a charm. What Needs to be changed to make the migration work again? Or do we ran into a bug?

Regards
Christian

**Comment by rowanmiller** [comment]
In RC2 we stopped "guessing" as much for one-to-one relationships. You need to add a call to HasForeignKey<T> to let EF know which is the dependent/child end - the link in the exception message has details.
