### ISSUE TITLE
TPH with SUM not worked

### ISSUE THREAD

**Issue by miramares** [dotnet/efcore#5559]
I use TPH hierarchy:
GeneralItem (is not abstract class)
Level1Item : GeneralItem
Level2Item : GeneralItem

When I call this 
`double generalMoneyAmount = db.GeneralItem.Where(i => i.ParentId == parentId).Sum(f => f.MoneyAmount);
double level1MoneyAmount = db.Level1Item.Where(i => i.ParentId == parentId).Sum(f => f.MoneyAmount);
double level2MoneyAmount = db.Level1Item.Where(i => i.ParentId == parentId).Sum(f => f.MoneyAmount);`

I get same values, but I have data only for Level1Item.
When I catch SQL command, I see this result
`SELECT SUM("i"."MoneyAmount")
                FROM "GeneralItem" AS "i"
                WHERE "i"."ParentId" = @__8__locals1_parentId_0`

Visual Studio 2015 Update 2
project.json
{
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.SQLite": "7.0.0-rc1-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "MvvmLight": "5.3.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by smitpatel** [comment]
Looks like the query is missing the discriminator predicates. Can you upgrade to RC2 packages of EF (if that works and let us know if you still see the error?

**Comment by miramares** [comment]
I see no updates for nugget package. Can I upgrade in other way?

27. 5. 2016 v 22:26, Smit Patel <notifications@github.com<mailto:notifications@github.com>>:


Looks like the query is missing the discriminator predicates. Can you upgrade to RC2 packages of EF (if that works and let us know if you still see the error?

**Comment by smitpatel** [comment]
Packages are available on nuget.org just names are changed. 
Refer to guide http://ef.readthedocs.io/en/latest/miscellaneous/rc1-rc2-upgrade.html for upgrade.

**Comment by miramares** [comment]
So, when I made upgrade to RC2, all is OK :-) thank you.
But... maybe one question about TPH. When base class is not abstract, how can I restrict data only for this class? Must I always define base class as abstract?

**Comment by smitpatel** [comment]
In TPH, query can be written in various ways to get data of particular class only.
Taking hierarchy as you mentioned in your first post.
1. One of the simplest way is to have DBSet for each class defined. When you query DBSet of `Level1Item`, you will get data for only entities of type `Level1Item`.
2. If you don't have DBSets for other classes and there is only one DBSet for base class (`GeneralItems` then you can use `Ofype<>` or `is` operator like this.
`context.GeneralItems.OfType<Level1Item>()` or `context.GeneralItems.Where(g => g is Level2Item)`
In all cases above, query generates appropriate where clause on discriminator column and gives you only data pertaining to the entity you are querying for.
