### ISSUE TITLE
Consider removing dependency on System.Collections.Immutable if we can (again)

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#5560]
Currently the only usage is in `RelationshipDiscoveryConvention` where we have an `ImmutableSortedDictionary` as the payload for an annotation. 

This issue is just to follow up on whether it is really needed since in the past we made the explicit choice to use other data structures that worked better for us (maybe in this case it is justified).

**Comment by bricelam** [comment]
What was the triage decision on this one?

**Comment by divega** [comment]
We'll keep the dependency because the usage seemed appropriate. Any additional problem we should keep in mind?

**Comment by bricelam** [comment]
Nope, just curious. The assembly is only 200KB, so it seems fine to me.
