### ISSUE TITLE
IdentityColumn: Insert fails 

### ISSUE THREAD

**Issue by ilogixxDE** [dotnet/efcore#5568]
I do have a model that contains an identitycolumn TicketID:

Public Class Ticket
    <Key>
    <DatabaseGenerated(DatabaseGeneratedOption.Identity)>
    Public Overridable Property TicketID As Integer
    End Property
    Public Property CreatedAt As Date
    Public Overridable Property Phonecalls As List(Of PhoneCall)
    Public Overridable Property EMails As List(Of EMail)
    Public Overridable Property Chats As List(Of Chat)
End Class

Now, when adding an EMail, I receive in the SaveChanges function call this Exception:

Cannot insert explicit value for identity column in table 'Ticket' when IDENTITY_INSERT is set to OFF.

Why does this happen?
When I save the explicitly ticket before adding an email and save, the ticket is stored. But the EMailnever gets stored because of the mentioned exception.
What is wrong with the identity column?

Regards

**Comment by smitpatel** [comment]
When you set up a column in database to use `IDENTITY`, you cannot insert explicit values in the column. That is SqlServer restriction.
In EF while saving entities, if you assign explicit value to a property which is configured to use `IDENTITY` then you hit above exception.

**Comment by ilogixxDE** [comment]
Thank you for this.
I know about those restrictions, and for shure the property is NEVER set. So I can't understand. This issue cames upin my model after upgrading from RC1 to RC2.
Is there any Change made from RC1 to RC2 that might be realted to this?

**Comment by smitpatel** [comment]
Can you share your code of your model classes, db context and where you are trying to save changes?

**Comment by ajcvickers** [comment]
@ilogixxDE It is likely because you have a Ticket object that has already been saved and therefore already has a key value set, but the code you are using to save the Email is not telling EF about this, so EF thinks the Ticket object is a new one and is attempting to insert it again. If this doesn't make sense, then as @smitpatel says, please show us your code so we can try to help more directly.

**Comment by divega** [comment]
Closing since we haven't heard back. Feel free to re-open if you can provide a repro.
