### ISSUE TITLE
Feature request: Migrations on Inherited DbContexes

### ISSUE THREAD

**Issue by hikalkan** [dotnet/efcore#5572]
Hi,
### Situation

Assume that we have created a modular application and we have more than one DbContext.

Example: In our core part of the application, we have a CommonDbContext:

``` C#
public class CommonDbContext : DbContext
{
    //common entity DbSet properties
}
```

And we have several modules (in their own assemblies), like:

``` C#
public class BlogModuleDbContext : CommonDbContext
{
    //Blog module's additional entity DbSet properties
}

public class ChatModuleDbContext : CommonDbContext
{
    //Chat module's additional entity DbSet properties
}
```

In this case, I want to have 3 separated migrations normally:
1. Migration for CommonDbContext .
2. Migrations for BlogModuleDbContext (which should not include CommonDbContext entities).
3. Migrations for ChatModuleDbContext (which should not include CommonDbContext entities).

At this point, as you know, derived DbContext's automatic migration generation code include base DbContext (CommonDbContext) changes. While this can be desired in some situations, as you see it's not good for my application.
### Feature Request

Define an attribute (and a method in fluent configuration) to ignore base changes:

``` C#
[IgnoreBaseDbContextMigrations]
public class BlogModuleDbContext : CommonDbContext
{
    //Blog module's additional entity DbSet properties
}
```

Entity Framework migration generator should understand **IgnoreBaseDbContextMigrations** attribute and should not detect base class changes.

IgnoreBaseDbContextMigrations can be enhanced. For example, we may supply a DbContext class type to indicate which will be ignored, and so on... Also, there can be technical problems on some situations (for example, on entity inheritance) which should be thought carefully.

What do you think for such a feature, or do you know any other approach to implement the same requirement?

**Comment by rowanmiller** [comment]
This is already covered by an existing item on our backlog https://github.com/aspnet/EntityFramework/issues/2725. I've added a note to that issue to specifically consider the inherited context scenario when looking at it.

**Comment by hikalkan** [comment]
Thank you. I have not seen it. Is there a workaround currently?

**Comment by bricelam** [comment]
The workaround is to just remove any operations on them that get scaffolded in the migration.

**Comment by hikalkan** [comment]
I'm already doing it, I could not find a better way yet. Thanks.

**Comment by armartinez** [comment]
Question, how are you handling injection of DbContextOptions ? Or you are not injecting them?
