### ISSUE TITLE
502.3 Bad Gateway Error While Submitting a Form using Post Method

### ISSUE THREAD

**Issue by emcyborg** [dotnet/efcore#5575]
Hey There! I am making a ERP with Identity Core RC 2. I am facing a very strange problem. I am putting a relationship between my User table which is "ASPNETUSER" and other table. The problem is that when I add this relationship my application starts giving 502.3 Bad Gateway Error when I post my form for insertion, but when I removed it, it starts working fine. Please look into this. I am very frustrated due to it.

Thanks in advance.

**Comment by rowanmiller** [comment]
Can you open an issue in the ASP.NET Identity repo https://github.com/aspnet/Identity. When you do, can you include some more technical details that can be used to reproduce the issue, we are not able to reproduce it with the limited details supplied here.
