### ISSUE TITLE
Test: AddColumnOperation with max length test

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#5586]
Test `AddColumnOperation_with_maxLength_overridden` is disabled because to make that test work, the test class needs to have implementation of `StringTypeMapper` which is not present therefore it cannot generate string type with specified max length.

**Comment by smitpatel** [comment]
@bricelam - Do we want to remove limitations of fake `RelationalTypeMapper` in future at some point otherwise we can close this one.

**Comment by ajcvickers** [comment]
@smitpatel @bricelam Type mappers are not required to have a StringTypeMapper or a ByteArrayTypeMapper. Any code that is assuming otherwise is wrong and should be fixed.

**Comment by smitpatel** [comment]
@ajcvickers - Product code does not assume it. It has fallback mechanism to find suitable type. Our test code has incomplete mocks and test assumed presence of `StringTypeMapper` so it failed. I have moved those test to provider specific parts.

**Comment by smitpatel** [comment]
There is already test coverage in provider specific tests. No need to do it for relational.
