### ISSUE TITLE
Unable to resolve 'Microsoft.EntityFrameworkCore.SqlServer (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.

### ISSUE THREAD

**Issue by xatabhk** [dotnet/efcore#5605]
Unable to resolve 'Microsoft.EntityFrameworkCore.SqlServer (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'Microsoft.EntityFrameworkCore.Tools.Core (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Http.Extensions (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Http.Abstractions (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Http (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.HttpOverrides (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.DataProtection (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.Extensions.Caching.Abstractions (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Cors (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Antiforgery (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Html.Abstractions (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Http.Features (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Authorization (>= 1.0.0-rc3-21156)' for '.NETFramework,Version=v4.5.2'.
    Unable to resolve 'Microsoft.AspNetCore.Html.Abstractions (>= 1.0.0-rc3-21156)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.EntityFrameworkCore.Tools.Core (>= 1.0.0-rc3-21156)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.Extensions.Configuration.UserSecrets (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.Extensions.CommandLineUtils (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.Extensions.Logging (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.Extensions.CommandLineUtils (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.Extensions.DependencyInjection (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.AspNetCore.Hosting (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.EntityFrameworkCore (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.EntityFrameworkCore.SqlServer (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.AspNetCore.Razor (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.Extensions.PlatformAbstractions (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.

**Comment by smitpatel** [comment]
@xatabhk - It seems that you are using nightly/volatile feeds. Those feeds sometimes gets out of sync temporarily. (e.g. you are trying to restore while feeds are being uploaded. Some new packages are available and some are not there yet) And which can give result like above. Best option is to wait for an hour or so and then try again. Once all packages are properly available on feed, it start working again by itself.

**Comment by xatabhk** [comment]
Yes. It works now.
