### ISSUE TITLE
Migrations on Server Side

### ISSUE THREAD

**Issue by crabulik** [dotnet/efcore#5606]
Hello.
Is it possible to run ef database update command on the server side after publishing via CLI?

Previously in RC1 after publishing the project, it was possible to run ef commands using ef.cmd, wich was located in "approot" of the project folder. Now, if I get it right, ef comands runs only from the folder with source code.

**Comment by bricelam** [comment]
Wait, why did you close this? Did you find an alternative? We think it's an interesting scenario and we'd like to look into possible solutions.

**Comment by crabulik** [comment]
Because nobody answered, I thought it was too obvious. I've made next :
Created separate .Net core console app with a reference to my project. In the body of the console app I make an instance of the db context, and lunch dbcontext.database.migrate().

**Comment by bricelam** [comment]
Great workaround! Ideally, I think we want to provide a console app that can do the same thing. This is possibly covered by #646.

**Comment by bricelam** [comment]
Closing as I believe this is now possible with #646. Issue #6313 is to decide if we need to do anything to improve the experience.
