### ISSUE TITLE
Reverse-Engineer: Scaffold-DbContext not working on ASP.NET Core project

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#5614]
When using win 7 with VS2015 latest update 2 I'm getting the following issue on: [Reverse Engineering Your Model](https://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html#reverse-engineer-your-model). I've completed all the previous steps successfully in the above article:

I use the following command to run 
PM> Scaffold-DbContext "'Server=MyMachine\SQL2012;Database=MyDbName;Trusted_Connection=True;''" Microsoft.EntityFrameworkCore.SqlServer 

I get the following error:
**At line:1 char:75
- & '' ef --configuration Debug --build-base-path .\bin\ dbcontext scaffold 'Serve ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  The string is missing the terminator: '.**

What am I missing?

**Comment by lajones** [comment]
Offhand it looks as though you have a double-quote and a single-quote at the start of the connection string, but 2 double-quotes at the end. If that doesn't solve the problem can you add this to #5376 please? Closing this as a dupe.

**Comment by saf-itpro** [comment]
The 2 double-quotes at the end are actually two single quotes and a double quotes copied  from the original article [Reverse Engineering Your Model](https://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html#reverse-engineer-your-model). I thought there should be one single quote at the end instead. So, I removed one single quote and got the following error: **The expression after '&' in a pipeline element produced a object that was not valid. It must result in a command name, script block or CommandInfo object**.

Question: How do I add my original post above to #5376 as you advised?

**Comment by lajones** [comment]
Re your question - just add a comment describing the above in #5376.

I see the error in [Reverse Engineering Your Model](https://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html#reverse-engineer-your-model) - I'll get that updated - it should have a double-quote followed by a single-quote at the beginning and a single-quote followed by a double-quote at the end.

To get the rest working try adding the `-Verbose` flag to the command. That will print out for you the actual command that is being sent. If you can then include that in #5376 that will help us track down the problem with your particular connection string and we may be able to suggest a workaround while we work on a permanent fix.

**Comment by saf-itpro** [comment]
I added -Verbose flag to the command and I got the following command text to be printed out. I am including this in #5376: 
**Executing command: dotnet ef --configuration Debug --build-base-path .\bin\ dbcontext scaffold 'Server=MyServer\SQL2012;Database=MyDbName;Trusted_Connection=True;' Microsoft.EntityFrameworkCore.SqlServer --verbose**

The error now I'm getting is same as above: **The expression after '&' in a pipeline element produced a object that was not valid. It must result in a command name, script block or CommandInfo object.**
