### ISSUE TITLE
Data overwritten on each save when linking to existing nested table

### ISSUE THREAD

**Issue by pingcrosby** [dotnet/efcore#5629]
### Steps to reproduce

Create two tables employer and address, populate the address table.
Attempt to save multiple employers using a record from the address table in a loop.  If you run the loop 10 times only the last record (no.9) will have the link to the address - stepping through the code on each SaveChanges the dbase is correct; but on the next iteration the new record gets the address link and the old record link becomes null.
### The issue

I would expect every record to contain a link
### Further technical details

No errors are displayed.
The result table looks like

> Employer Table
> id, AddressId, Title
> 
> 1, null, X
> 2, null, X
> 3, null, X
> 4, null, X
> 5, null, X
> 6, null, X
> 7, null, X
> 8, null, X
> 9, null, X
> 10, 1, X

EF Core version:

```
"EntityFramework.Commands": "7.0.0-rc1-final",
"EntityFramework.Core": "7.0.0-rc1-final",
"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
```

```
    public class ApplicationDbContext : DbContext
    {
        public virtual DbSet<Employer> Courses { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // add the relationship       
            modelBuilder.Entity<Employer>().HasOne(u => u.Address).WithOne();      
        }
    }
```

```
public class Employer
{
    public int Id { get; set; }
    public string Title { get; set; }
    public virtual Address Address { get; set; }  
}
```

```
_dbContext is just an injected instance via

 services.AddEntityFramework().AddSqlServer().AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(Configuration["Data:ApplicationConnection:ConnectionString"]));

for (int i = 0; i < 10; i++)
{
  Employer item = new Employer();                              
  item.Address = _dbContext.Addresses.Single(s => s.Id == 1); // data returned ok
   _dbContext.Attach(item.Address);                    
  _dbContext.Courses.Add(item);
  _dbContext.SaveChanges();                  
}
```

I cannot see what i could be doing wrong.

**Comment by ajcvickers** [comment]
@pingcrosby There is a one to one relationship between Address and Employee. That means that each Address can only be associated with a single Employee. Each iteration through the loop you assign the Address to a new Employee, which causes it to be unassigned from the previous Employee. I'm not sure exactly what you are trying to model, but you may want a one to many relationship so that many employees can share the same address. If so, change your relationship mapping to:
```C#
modelBuilder.Entity<Employer>().HasOne(u => u.Address).WithMany(); 
```

**Comment by pingcrosby** [comment]
That was it - stupid typo on my part.

Thanks for the clarification, very much appreciated
