### ISSUE TITLE
MySQL provider

### ISSUE THREAD

**Issue by Daniel15** [dotnet/efcore#5659]
The [documentation says that a MySQL provider is "coming soon"](https://docs.efproject.net/en/latest/providers/mysql/index.html), but does not provide any ETA or link to any issue. I searched this repo and couldn't find any issues relating tracking the creation of the MySQL provider. Is there an issue I can follow to track this, and an ETA for its implementation?

Thanks!

**Comment by gdoron** [comment]
Looking forward for it too.

**Comment by rowanmiller** [comment]
The MySQL provider is being written by the MySQL team, so they will share details and timelines when they are ready. 

DevArt has released a MySQL provider with EF Core support (works with RC2) - http://blog.devart.com/entity-framework-core-1-entity-framework-7-support.html. They are not a free provider though, and EF support is only included in paid versions.

**Comment by divega** [comment]
Closing since I believe we have answered the question.

**Comment by gdoron** [comment]
Any chance you know where we can track the MySQL team work on this?
Do they have a Github repository?

**Comment by divega** [comment]
Not sure they have the EF Core provider in GitHub. @gmartinezsan may be able to answer.

**Comment by gmartinezsan** [comment]
Hi @gdoron, @Daniel15 thanks for your interest in this product. The code is not public yet, but of course it will be once we released the first version of Core support. We are working on some final details and we expect to finish this soon. I will add details here as soon as the plan is more defined.

**Comment by matthewjcooper** [comment]
Any update :)

**Comment by Kagamine** [comment]
@Daniel15 There is an open sourced and free mysql provider for ef core now: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by divega** [comment]
See also the official MySQL provider announcement with initial support for .NET Core and EF Core: http://insidemysql.com/mysql-connectornet-7-0-4-m3-has-been-released/

**Comment by adebisi-fa** [comment]
Thank @Kagamine & @divega for your references!

I just submitted a pull request to update the MySQL Provider section of the EF documentation to reflect your references.

Regards.
