### ISSUE TITLE
Many to Many problem

### ISSUE THREAD

**Issue by ngonzalezromero** [dotnet/efcore#5666]
I have this code to update a entity

``` C#
public async Task<User> UpdateAsync(User entity)
{
    var userDb = await _context.User
        .Include(x => x.UserApplications)
            .ThenInclude(xx =>xx.Application)
        .Include(x => x.State)
        .Include(x => x.UserProfiles)
            .ThenInclude(x => x.Profile)
        .FirstOrDefaultAsync(
            x => x.UserName == entity.UserName
                && x.SecretKey == entity.SecretKey 
                && x.Email == entity.Email);

    userDb.FirstName = entity.FirstName;
    userDb.LastName = entity.LastName;
    userDb.State = await _context.State.FirstAsync(x => x.StateId == entity.State.StateId);

    userDb.UserProfiles.Clear();
    userDb.UserApplications.Clear();
    userDb.UserProfiles.AddRange(entity.UserProfiles); //ManyToMany
    userDb.UserApplications.AddRange(entity.UserApplications); //Many To Many
    _context.User.Update(userDb);
    await _context.SaveChangesAsync();
    return userDb;
}
```

Generate sql

`
           Executed DbCommand (8ms) [Parameters=[@p0='?', @p1='?', @p14='?', @p2='?', @p3='?', @p4='?', @p5='?', @p6='?', @p7='?', @p8='?', @p9='?', @p10='?', @p11='?', @p12='?', @p13='?', @p15='?', @p16='?', @p17='?', @p18='?', @p19='?', @p20='?', @p21='?'], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Application" ("ApplicationId", "ApplicationName")
      VALUES (@p0, @p1);
      UPDATE "User" SET "ApiKeyId" = @p2, "Comment" = @p3, "CreationDate" = @p4, "Email" = @p5, "FirstName" = @p6, "IsOnLine" = @p7, "LastLoginDate" = @p8, "LastName" = @p9, "Password" = @p10, "SecretKey" = @p11, "StateId" = @p12, "UserName" = @p13
      WHERE "UserId" IS NOT DISTINCT FROM @p14;
      DELETE FROM "UserApplication"
      WHERE "UserApplicationId" IS NOT DISTINCT FROM @p15;
      DELETE FROM "UserProfile"
      WHERE "UserProfileId" IS NOT DISTINCT FROM @p16;
      DELETE FROM "UserProfile"
      WHERE "UserProfileId" IS NOT DISTINCT FROM @p17;
      INSERT INTO "UserProfile" ("ProfileId", "UserId")
      VALUES (@p18, @p19)
      RETURNING "UserProfileId";
      INSERT INTO "UserProfile" ("ProfileId", "UserId")
      VALUES (@p20, @p21)
      RETURNING "UserProfileId";
`

Why EF insert a new entity (   INSERT INTO "Application" ("ApplicationId", "ApplicationName")
      VALUES (@p0, @p1)) if only i need update the user?

EF Core version: 1 RC2
Operating system: Mac OSX

Regards

**Comment by divega** [comment]
@ngonzalezromero could you provide more details, i.e. the entity types and the rest of the code before `SaveChanges()`?

**Comment by ngonzalezromero** [comment]
@divega it's all code... before that there is only a Mvc controller...

I found a fix, but it's not efficient, because hit the database for each entity

       public async Task<User> UpdateAsync(User entity)
        {
            var userDb = await _context.User.Include(x => x.UserApplications).ThenInclude(xx => xx.Application).Include(x => x.State).Include(x => x.UserProfiles).ThenInclude(x => x.Profile).FirstOrDefaultAsync(x => x.UserName == entity.UserName && x.SecretKey == entity.SecretKey && x.Email == entity.Email);

            if (userDb == null)
            {
                throw new AppException($"The user {entity.UserName} is invalid");
            }

            if (userDb.State.StateId == _appSettings.StateLocked)
            {
                throw new AppException($"The user {entity.UserName} is locked, can't be updated");
            }

            userDb.FirstName = entity.FirstName;
            userDb.LastName = entity.LastName;
            userDb.State = await _context.State.FirstAsync(x => x.StateId == entity.State.StateId);

            userDb.UserProfiles.Clear();
            userDb.UserApplications.Clear();

            foreach (var item in entity.UserProfiles)
            {
                var pro = await _context.Profile.FirstAsync(x => x.ProfileId == item.ProfileId);
                var p = new UserProfile();
                p.User = userDb;
                p.UserId = userDb.UserId;
                p.Profile = pro;
                p.ProfileId = pro.ProfileId;
                userDb.UserProfiles.Add(p);
            }

            foreach (var item in entity.UserApplications)
            {
                var pro = await _context.Application.FirstAsync(x => x.ApplicationId == item.ApplicationId);
                var p = new UserApplication();
                p.User = userDb;
                p.UserId = userDb.UserId;
                p.Application = pro;
                p.ApplicationId = pro.ApplicationId;
                userDb.UserApplications.Add(p);
            }
            _context.User.Update(userDb);
            await _context.SaveChangesAsync();
            return userDb;

**Comment by ajcvickers** [comment]
@ngonzalezromero It looks like the User entity and its related connections passed into the method are not being tracked by context, In this case if they are existing entities they will need to have their states set to Unchanged such that EF knows this. There are various ways to do this and without knowing the details of your application it is hard to say what the best way is, but I would try calling _context.Attach(entity) at the top of your method. This will tell EF that the User entity and is related collections already exist in the database.

**Comment by ngonzalezromero** [comment]
@ajcvickers Thank you.. i will try
