### ISSUE TITLE
Query: Null semantics :: we are overzealous in applying "full" null expansion in some cases

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#5670]
``` cs
ctx.Customers.Where(c => c.Name != "Foo" && c.NullableInt == 5);
```

will get expanded into:

``` cs
ctx.Customers.Where(c => (c.Name != "Foo" || c.Name == null) && (c.NullableInt == 5 && c.NullableInt != null);
```

while first part, i.e.  `
(c.Name != "Foo" || c.Name == null)
` is necessary, the second expansion is redundant in this case.

In some cases it is beneficial to expand all "leaf" nodes using full expansion, e.g. 

``` cs
ctx.Customers.Where(c => (c.Name != "Foo") ==  (c.NullableInt == 5));
```

but if the top level operand is different than `==` and `!=`, it is not needed and we should only apply simplified null expansion for the second term, which in this case is leave it as is

**Comment by smitpatel** [comment]
@maumar - Is this valid for new query pipeline?

**Comment by maumar** [comment]
we don't have the full/simplified null semantics in the new pipeline, so currently this issue is not applicable. However we might re-introduce it given the perf considerations raised in https://github.com/aspnet/EntityFrameworkCore/issues/17543
