### ISSUE TITLE
SaveChanges and DataContext

### ISSUE THREAD

**Issue by pierregaboriaud** [dotnet/efcore#5675]
Hello,

I think the SaveChanges() method doesn't update the datacontext in a different controller. Please look at my example.
### Example

Startup.cs : 

```
[...]

services.AddDbContext<DataContext>(options =>
{
    options.UseSqlServer(Configuration["Data:ConnectionString"]);
});
```

DataContext.cs :

```
public class DataContext : DbContext
{
    public DbSet<Table>       Tables { get; set; }
}
```

Controller1.cs : 

```
public class Controller1 : Controller
{
    private DataContext _dataContext;
    public UserController(DataContext dataContext_) 
    {
        _dataContext = dataContext_;
    }
    public void Edit() 
    {
        Table t = (from t in _dataContext.Tables where t.Id = 1 select t).Single();
        t.Field = "Foo Bar";

        _dataContext.saveChanges();
    }
    public string Display() {
        return (from t in _dataContext.Tables where t.Id = 1 select t).Single().Field;
    }
}
```

Controller2.cs : 

```
public class Controller2 : Controller
{
    private DataContext _dataContext;
    public UserController(DataContext dataContext_) {
        _dataContext = dataContext_;
    }
    public string Display() {
       return (from t in _dataContext.Tables where t.Id = 1 select t).Single().Field;
    }
}
```
### Calls

Controller1.Edit();
Controller1.Display(); ====> "Foo Bar"
Controller2.Display(); ====> "" (previous data)
### Environment

Visual Studio Update 2
Microsoft.NETCore.App : "1.0.0-rc2-3002702"
"[...]" : "1.0.0-rc2-final"
"Microsoft.EntityFrameworkCore": "1.0.0-rc2-final"

**Comment by divega** [comment]
@pierregaboriaud can you clarify what you mean? But in principle each `DbContext` instance is completely independent and once a `DbContext` tracks an entity it will not update its property values automatically. FWIW, it has always worked that way.

**Comment by pierregaboriaud** [comment]
Ok my bad, I thought that saveChanges method would update each DbContext instance.

**Comment by divega** [comment]
@pierregaboriaud just to be clear, if you use a context to save an entity with new data to the database and then you create a new instance of the context and retrieve the same entity you should be able to see the fresh data you saved before. But the context instances don't share data in any other way. In your code listing I would expect `Controller2` to see the data saved by `Controller1` provided that `Controller2` runs after `Controller1`, and that `Field1` is actually a property and that it is mapped.

**Comment by ajcvickers** [comment]
@divega @pierregaboriaud But using the default dependency injection behavior of AdDbContext and ASP.NET, the same context instance should be injected into both controllers within a given request.
