### ISSUE TITLE
Quick Link in Wiki for "Getting Started" is Broken

### ISSUE THREAD

**Issue by tillig** [dotnet/efcore#5686]
On the side of the wiki pages in the "Quick Links" section there's a link to "Getting Started with EF Core" that currently goes to `http://ef.readthedocs.org/en/latest/getting-started.html` - that page doesn't exist. I'm guessing it should go to `http://ef.readthedocs.io/en/latest/platforms/full-dotnet/index.html` or a similar location.

**Comment by natemcmaster** [comment]
Good catch. I've updated the wiki.
