### ISSUE TITLE
RC2 : EF6.1.3 tooling (Code first migration)

### ISSUE THREAD

**Issue by marcusien** [dotnet/efcore#5698]
I'd like to use code first migrations from EF6.1.3 toolings on .NET Core project.
But even if I have the EF package in my project, the package manager console tells me this

The EntityFramework package is not installed on project 'TreeViewBuilder.Data'.

Have the same usage of EF on other projects (WPF for instance) and it works perfectly. Is there a workaround ?

**Comment by bricelam** [comment]
Could you share the `packages.config` file of the `TreeViewBuilder.Data` project?

**Comment by marcusien** [comment]
Sorry I forgot a detail cause I originally post this issue on asp core git.

I want to use the code first migrations tools with .NET Core project (class library). There's no packages.config in my project so.
Everything is inside project.json et project.lock.json

**Comment by rowanmiller** [comment]
EF6.x commands are currently not supported in project.json/xproj based projects. The project system for these projects is still pre-release and by the time it RTMs will be more integrated with the existing csproj/MSBuild project system. For this reason we aren't planning to update the EF6.x commands to work with project.json/xproj until the consolidation is done.
