### ISSUE TITLE
Scaffold-DbContext causes "Invalid JSON file in..." if project.json includes comments

### ISSUE THREAD

**Issue by rjpaulsen** [dotnet/efcore#5704]
1. If I update my project.json includes a comment, like this:

```
  // required for EF
  "buildOptions": {
    "emitEntryPoint": true
  },
```
1. Then I run this:
   `Scaffold-DbContext {ConnectionString} Microsoft.EntityFrameworkCore.SqlServer`
2. I get the error:

> Invalid JSON file in C:\Users...\project.json
1. It works correctly if I change step 1 to look like this:

```
  "buildOptions": {
    "emitEntryPoint": true
  },
```

**Comment by natemcmaster** [comment]
The [JSON spec](http://www.json.org/) doesn't support comments. Visual Studio tooling hides this from you by stripping comments out of JSON files when it builds.

**Comment by bricelam** [comment]
Also, we rely on APIs from [dotnet/cli](https://github.com/dotnet/cli) to do the JSON parsing. You can read (a lot) more about their decision not to support comments in aspnet/Announcements#24.

Closing as an external issue.

**Comment by SDS-Group** [comment]
Just in case this helps anyone else - I also had this issue when there was a trailing comma at the end of the projects.json file, which is ignored by the compiler but this tool doesn't like it.

**Comment by simeyla** [comment]
Can't the error message be changed? "JSON file invalid - cannot contain comments." 

It is VERY confusing when VS allows me to comment something in JSON. I kind of intrinsically know that JSON doesn't support comments, but then at the same time I'm not quite sure - and it goes green when I try so it all looks good.

**Comment by rowanmiller** [comment]
project.json/xproj are being retired in favor of the MSBuild based .NET Core solution. In general, we are helping folks find workarounds for project.json/xproj but focusing our development effort on the project system that is going to reach RTM.
