### ISSUE TITLE
No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider.

### ISSUE THREAD

**Issue by dewebeloper** [dotnet/efcore#5705]
After replacing EF Core rc 1 with EF Core rc 2 final I get follor error:

> No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

I have UoW pattern and on initialization on constructor I get DbContext object like on image.
![rc2dbcontextissue](https://cloud.githubusercontent.com/assets/3725912/15923064/62b241a4-2e2b-11e6-9057-1175e279a1af.png)

In Startup.cs I have next code:

```
services.AddDbContext<RegistratorDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<AppUser, IdentityRole>(config =>
            {
                config.User.RequireUniqueEmail = true;
                config.Password.RequiredLength = 6;
                config.Password.RequireUppercase = true;
                config.Password.RequireNonAlphanumeric = false;
            })
            .AddEntityFrameworkStores<RegistratorDbContext>();
```

What I did wrong and how to fix this issue? I need to mention that same pattern works in RC1.
Thanks in advance.

**Comment by natemcmaster** [comment]
>  If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions object in its constructor and passes it to the base constructor for DbContext.

What are your constructors for `RegistratorDbContext`?

**Comment by dewebeloper** [comment]
```
public RegistratorDbContext(DbContextOptions<RegistratorDbContext> options)
			: base(options)
		{ }
```

This is constructor.

**Comment by natemcmaster** [comment]
That's the right constructor. Are there any other constructors? 

The issue could be in how RegistratorDbContext and DbContextOptions<RegistratorDbContext> are being resolved. How is your DbContext being injected into `App`? 

For more background, `.AddDbContext` [will also add options as a singleton](https://github.com/aspnet/EntityFramework/blob/1.0.0-rc2/src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs#L119-L122) to your service container. To help us investigate this, pulling the type `DbContextOptions<RegistratorDbContext>` from your service container to make sure it is available. If it's not, your DI container may be using a parameterless constructor instead to resolve your DbContext.

**Comment by dewebeloper** [comment]
No, that is only one constructor on RegistratorDbContext.
On App I have this for constructor
```
public App(IRepositoryProvider repositoryProvider, RegistratorDbContext ctx )
		{
			_context = ctx;
			//CreateDbContext();
			repositoryProvider.DbContext = Context;
			RepositoryProvider = repositoryProvider;
		}
```

That's place where I get issue from picture above.
This is how I inject App in Startup.cs
`services.AddScoped<IApp, App>();`

**Comment by natemcmaster** [comment]
@dewebeloper I don't see any issues in what you have shared so far. My guess is something else is causing the issue. Can you share a standalone repro?

**Comment by dewebeloper** [comment]
Will try to prepare for tomorrow.

**Comment by dewebeloper** [comment]
Sorry for the little delay, but here is full repo with issue https://github.com/dewebeloper/RC2DbContextIssue

**Comment by natemcmaster** [comment]
@dewebeloper the project you shared has a version of "Registrator.Data.dll" that doesn't match the source code. It only has the `public RegistratorDbContext(IHttpContextAccessor httpContextAccessor)` constructor. 

Delete all of your `bin/` and `obj/` directories and rebuild. When I did this, the error "No database provider has been configured" goes away.

**Comment by ericwj** [comment]
I am having almost the exact same issue.

Should I be using version 1.0.0 of `Microsoft.EntityFrameworkCore.Tools.DotNet` with `netcoreapp1.1` on `dotnet --version` 1.0.1 and Microsoft.* packages at 1.1.1?

I actually use a fairly minimal Startup class just to bootstrap a DbContext in a different assembly. So I run `dotnet ef` with the `--startup-project` parameter. It is `dotnet ef` that is crashing in `Microsoft.EntityFrameworkCore.Internal.DatabaseProviderSelector.SelectServices()`.

I am seeing all the correct Add and Use methods being called, but as soon as I comment out the second UseSqlServer in MyDbContext.OnConfiguring, I hit this error. I want to get rid of it as it isn't using the connection string from the configuration file and I would want that to stay that way.

**Comment by smitpatel** [comment]
@ericwj - Does your context have constructor with `DbContextOptions` as parameter?

**Comment by ericwj** [comment]
Yes yes yes
```CS
public MyDbContext : DbContext {
	public MyDbContext() : base() { }
	public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }
	//protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
	//	base.OnConfiguring(optionsBuilder);
	//	// HACK: Requires putting Startup in this project
	//	optionsBuilder.UseSqlServer(Startup.Configuration["Data:DefaultConnection"]);
	//}
	(...)
}
```

**Comment by ajcvickers** [comment]
@ericwj Looks like you might be hitting this: #6826. Try removing the parameterless constructor or adding an IDbContextFactory.

**Comment by ericwj** [comment]
Removing the parameterless constructor works.

**Comment by Bahmanpourgholami** [comment]
You can use below Code in DbContext Class:

   protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test");
    }

**Comment by vijaybadugu** [comment]
I was able to setup the ASP.NET Core web application as an Authorization Server and able to make a request with all kind of Client Core websites. The Problem here is that we have websites developed using old legacy webforms using 4.8 framework. 

Web Forms application as a client, I would like to make a request to Authorization Server Core app. Here I am running few issues with setting up ApplicationDBContext using Sql Server 


public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public ApplicationDbContext()
        : base("DefaultConnection", throwIfV1Schema: false)
    {
    }

    public static ApplicationDbContext Create()
    {
        return new ApplicationDbContext();
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.UseOpenIddict();
    }

When I try to check in startup.cs 

![image](https://github.com/dotnet/efcore/assets/13952619/8ce544e9-ec88-441d-8681-a783ac19295d)
I tried another way of setting of sql server,

![image](https://github.com/dotnet/efcore/assets/13952619/c1957af3-a0f2-4035-b419-1c1fd2d5e722)

When I try to install reference  Microsoft.EntityFrameworkcore.SQLServer , I’m getting the below error message
![image](https://github.com/dotnet/efcore/assets/13952619/412610d2-44b3-400a-b80f-d01836043b61)

**Comment by kcanders** [comment]
Just chiming in here to add that if your db provider is an InMemory db, you will receive this error when running migrations. You have to have your migration build use whatever your ultimate database. Makes sense when you think about it, but certainly took me too long of reading this and similar threads before figuring it out.

**Comment by Saidazizvich** [comment]
its no working maybe Identity Core is working
