### ISSUE TITLE
SqlServer-specific syntax in client evaluation warnings

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#5706]
The testsuite is full of checks that exceptions texts contain `[c].IsLondon` etc.

**Comment by roji** [comment]
Actually it seems that `[c].IsLondon` is generated even when running with Npgsql, where this isn't actual SQL, so the tests pass. I'm guessing this `[c].IsLondon` is some specific representation generated for client evaluation errors?

Will keep this open to consider changing this - it's odd and confusing for users of non-SqlServer databases to get error messages which use SqlServer syntax.

**Comment by anpete** [comment]
@roji This is not SQL server syntax, but rather a serialized linq expression. "[c]" is a relinq QuerySourceReferenceExpression.

**Comment by roji** [comment]
Sorry, my bad.
