### ISSUE TITLE
Logging question

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5707]
### Steps to reproduce

Run my SQLCE functional test suite (based on Spec tests) 
### The issue

I see some dbParameter values logged - what determines if they are logged or not?

For example: string  parameters are logged with (Size: 4000) 

Is this by design?
### Further technical details

EF Core version: RC3 build 21308
Operating system: Windows 81.
Visual Studio version: (e.g. VS 2015 Update 2)

**Comment by ajcvickers** [comment]
@ErikEJ Basically some heuristics about whether the parameter facet is "interesting". For size I believe we log it if it is set.
