### ISSUE TITLE
osoft.entityframeworkcore.tools ef

### ISSUE THREAD

**Issue by kenleese** [dotnet/efcore#5710]
### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
### The issue

Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
### Further technical details

EF Core version: (found in project.json or packages.config)
Operating system: 
Visual Studio version: (e.g. VS 2013 or n/a)

Other details about my project setup:

**Comment by natemcmaster** [comment]
Accidental issue open? This issue only contains the empty template.

**Comment by bricelam** [comment]
lol, given that typing i, c creates a new issue and is missing from the first bit of the title, yes. I think we can assume that.
