### ISSUE TITLE
RC2: Where on optional equality to nullable column produces incorrect SQL

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#5714]
### Steps to reproduce

```
public class Car {
    public string Manufacturer {get;set;}
}
```
### The issue

The following query, which filters on manufacturer if it is different from null:

```
var manufacturer = null; // Or some other string value if filter should be active.
var cars = db.Cars.
                .Where(x => manufacturer == null || x.Manufacturer == manufacturer)
                .ToListAsync();
```

produces SQL with the following condition:

```
((@__manufacturer_1 = NULL) OR [x].[Manufacturer] IS NULL)
```

instead it should be something like:

```
((@__manufacturer_1 IS NULL) OR [x].[Manufacturer] = @__manufacturer_1)
```

RC2-final

**Comment by divega** [comment]
This repros in RC2 but not in recent builds. The `manufacturer == null` part is even optimized out depending on the value of `manufacturer`.
