### ISSUE TITLE
Use code firsts migrations engine to generate SQL

### ISSUE THREAD

**Issue by Plavozont** [dotnet/efcore#5716]
Code first migrations are generating a wonderful SQL code which is compatible with all database engines that entity framework is compatible with. If I was able to use it to generate SQL Code by creating objects with certain structure and converting it to SQL-code I could create a wonderful cross-DBMS applications(that do not actually use entity framework, only it's code-generation feature). I spent a lot of time trying to find a way to use it like this and all this time I thought I was "this" close, but unfortunately it seems it is too strongly typed to have any chance to construct anything at run time. So please provide some API to SQL code generator of entity framework!

**Comment by rowanmiller** [comment]
This should be possible, you probably want to start with `MigrationBuilder` and `MigrationsSqlGenerator`. It's not a primary use case for EF though, so it's not something that will be documented and you will need to do a bit of experimenting and working it out for yourself.
