### ISSUE TITLE
System.Interactive.Async (>= 3.0.0-beta-00397) is not avaliable on the aspnetvnext feed.

### ISSUE THREAD

**Issue by danielcweber** [dotnet/efcore#5720]
Upgrading to the latest bits on the aspnetvnext feed cannot restore System.Interactive.Async since it's not on the feed. It's on aspnetcidev though.

**Comment by natemcmaster** [comment]
Should be up now.

https://www.myget.org/feed/aspnetvnext/package/nuget/System.Interactive.Async
