### ISSUE TITLE
Nit -  reveng generated DbContext and Models violate SA1516

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/efcore#5739]
### Steps to reproduce

Run reveng on existing database
### The issue

It all works. Its just the emitted DbContext class and its models violates SA1201

To be specific the virtual DbSet properties aren't separated by a blank line and the properties of each model aren't separated by a blank line.

```
warning SA1516 : Elements must be seperated by blank line
```
### Further technical details

win7 x64
rc2
vs 2015 update 2
### Comments

This is debateable.  It does make the generated code more verbose but looking at other code in samples etc. it seems this rule is normally used.

**Comment by rowanmiller** [comment]
This isn't something we are planning to change. There are mixed opinions around whether some SA rules actually represent the best/accepted coding patterns. For this particular case, we think that having DbSet properties without blank lines between them best represents the code that the majority of folks want.
