### ISSUE TITLE
Support for private properties

### ISSUE THREAD

**Issue by trichling** [dotnet/efcore#5750]
I have been browsing around the issus for a while and found some related things (#246, #2319) but nothing that matches exatctly. I am trying to make EF map a private property. 
### Steps to reproduce

Consider the following Code:

```
namespace ConsoleApplication
{
     public class Something
    {
        public Something()
        {
            SecretInfo = DateTime.Now.ToString();            
        }

        public int SomethingId { get; set; }
        public string Name { get; set; }
        private string SecretInfo { get; set; }

    }

    public class SomethingContext : DbContext
    {
        public DbSet<Something> Somethings { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=EFCoreTest;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Something>()
                .Property(b => b.SomethingId).UseSqlServerIdentityColumn();

            modelBuilder.Entity<Something>()
                .Property(typeof(string), "SecretInfo").HasColumnName("SecretInfo");
        }

    }

    public class Program
    {
        public static void Main(string[] args)
        {
            using(var blogDb = new SomethingContext())
            {
                var something = new Something()
                {
                    Name = "My awesome Something"
                };

                blogDb.Somethings.Add(something);
                blogDb.SaveChanges();
            }
        }
    }
}
```
### The issue

In the database appears a table `Somethings` with columns `SomethingId`, `Name` and `SecretInfo`. The first two columns are filled properly, while the third column remains `null`. The expected outcome would have been that it contains the value of `DateTime.Now.ToString()` as this is the value of the field set in the constructor of `Something`.
### Further technical details

EF Core version: `"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",`
Operating system: `Windows 10 Enterprise
`Visual Studio version: `VS Code 1.2.0`

**Comment by trichling** [comment]
The code sample in #2319 finally lead me twoards a solution for my problem. I added an override for `SaveChanges` in `SomethingContext`:  

```
 public override int SaveChanges()
        {
            foreach (var entry in ChangeTracker.Entries())
            {
                foreach (var pi in entry.Entity.GetType().GetProperties(BindingFlags.Instance | BindingFlags.NonPublic))
                {
                    entry.Property(pi.Name).CurrentValue = pi.GetValue(entry.Entity);
                }
            }
            return base.SaveChanges();
        }
```

This sets the values of all private properties to the corresponding change-tracker entries.This way they end up in the database during insert / update.

If this is the correct way to go this issue can be closed - if there is an easier route to success I would still be intereseted.

**Comment by ajcvickers** [comment]
@trichling I ran your repro code with the current bits and the SecretInfo property was correctly persisted to the database. I think what you are seeing is a consequence of issue #5446, which was fixed post RC2.
