### ISSUE TITLE
Unable to resolve service within OnModelCreating

### ISSUE THREAD

**Issue by Antaris** [dotnet/efcore#5752]
### Steps to reproduce

I'm trying to use `IInfrastructure.GetService` from within `OnModelCreating`, on RC1 this worked fine, but with RC2 this seems to have stopped. Here is some code:

```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddSingleton<CustomService, CustomService>();
            services.AddDbContext<UserDbContext>(options => options.UseInMemoryDatabase());

            var provider = services.BuildServiceProvider();

            var context = provider.GetService<UserDbContext>();
            var users = context.Users.FirstOrDefault();

            Console.ReadKey();
        }
    }

    public class UserDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        public UserDbContext(DbContextOptions<UserDbContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var service = this.GetService<CustomService>();

            base.OnModelCreating(modelBuilder);
        }
    }

    public class CustomService { }

    public class User {  }
}
```

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.InMemory": "1.0.0-rc2-final",
    "Microsoft.Extensions.DependencyInjection": "1.0.0-rc2-final",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net452+win81" ]
    }
  }
}
```
### The issue

Previously this would allow me to resolve a service at this instance, but since RC2 I now get:

> No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider.

I don't believe its related to #5705, but obviously the current RC2 error message isn't exactly helpful (I know you're addressing this already).

My use case for this method is that I am doing some work to automatically discover and build an entity graph that supports modular DbContext instances where entities defined as navigational properties that belong to another DbContext are included in the current model. This all worked fine pre-RC2.
### Things I've tried:
1. Explicitly calling `services.AddEntityFrameworkInMemoryDatabase` when constructing the `IServiceCollection`
2. Calling `options => options.UseInternalServiceProvider(...)` when configuring the database context through `services.AddDbContext`.
3. Inspected the `context` instance using the VS debugger and I can observe the singleton instance of my service in the container:

![image](https://cloud.githubusercontent.com/assets/255906/16037505/b97e1eea-3218-11e6-8eff-9c7f7d17478c.png)

**Comment by ajcvickers** [comment]
@Antaris I think the main issue is that EF is using its own internal service provider, and the GetService call is attempting to get your service from that provider, which fails because it hasn't been added to that provider. I'm not sure what you tried with UseInternalServiceProvider, but this code works from me:
```C#
public static void Main(string[] args)
{
    var services = new ServiceCollection()
        .AddSingleton<CustomService, CustomService>()
        .AddEntityFrameworkInMemoryDatabase()
        .AddDbContext<UserDbContext>(
            (serviceProvider, options) =>
                {
                    options
                        .UseInternalServiceProvider(serviceProvider)
                        .UseInMemoryDatabase();
                });

    var provider = services.BuildServiceProvider();

    var context = provider.GetService<UserDbContext>();
    var users = context.Users.FirstOrDefault();
}
```

**Comment by Antaris** [comment]
@ajcvickers what happens if your try and resolve in `OnModelCreating` with your code?

**Comment by ajcvickers** [comment]
@Antaris I get an instance of CustomService as expected.

**Comment by Antaris** [comment]
@ajcvickers Figured out the issue, I wasn't using *both* `AddEntityFrameworkInMemoryDatabase` and `UseInternalServiceProvider`.
