### ISSUE TITLE
Migration table generation includes namespace with DbSet entity name.

### ISSUE THREAD

**Issue by bfischer** [dotnet/efcore#5760]
The issue is described more in detail here, with a migration file: 
http://stackoverflow.com/questions/37800317/entity-framework-core-table-names-are-being-mapped-to-include-the-namespace

(I'm using "Blog" and "Post" models instead of my actual names, but they're structured exactly the same)

Basically, I recently upgraded a project from RC1 to RC2, which had previous migration file in it (not sure if this affects anything). After my update, I added a new property to my "Post" model, generated a new migration file, tried updating my database, and received an error saying stating that the table "MyProject.Models.Posts" does not exist. I looked in my migration file and noticed that it is now trying to add indexes, primary/foreign keys, and all other changes to tables names that include the namespace that the actual model exists in (see http://pastebin.com/CZmXTBEM). My models are structured very similar to the ones below:

``` C#
    public class MyContext : DbContext
    {
        public DbSet<Blog> Blog { get; set; }
        public DbSet<Post> Posts { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            builder.Entity<Blog>();
            builder.Entity<Post>();
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
```

Is this behavior normal, or is this some sort of bug?

EF Core version: 1.0.0-rc2-final
Operating system: Win 10
Visual Studio version: VS 2015

**Comment by bricelam** [comment]
When upgrading from RC1 to RC2, you'll need to delete any existing migrations and begin again with new migrations. We made a few changes to the information we put inside of these files that can result in unexpected new migrations.

**Comment by bfischer** [comment]
Do I need to also delete the ApplicationDbContextModelSnapshot and then just create another "Initial" migration, or just delete the migrations only and create another "Initial"?

**Comment by bricelam** [comment]
Yes, delete the snapshot too.

**Comment by bfischer** [comment]
Awesome, looks like that fixed the problem. Database is updated appropriately now. Is the detail about removing previous migrations mentioned in the documentation about updating to RC2? If not, it probably should be.

Thanks for your help, I really appreciate it.
