### ISSUE TITLE
Add-Migration stopped working

### ISSUE THREAD

**Issue by minimalisticMe** [dotnet/efcore#5763]
After updating VS2015 Update 2 (english) to VS2015 Update 3 (german) on win10 build 10586.318  I encounter a strange exception, while doing a migration:

```
Add-Migration : Der Wert liegt außerhalb des erwarteten Bereichs.
In Zeile:1 Zeichen:1
+ Add-Migration
+ ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Add-Migration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Add-Migration
```

The German part in line 1 reads something like `Add-Migration: The value is outside the expected area.` Before the update everything worked fine.

I'm using:
- Microsoft.EntityFrameworkCore.Sqlite v1.0.0-rc2-final
- Microsoft.EntityFrameworkCore.Tools v1.0.0-preview1-final

Creating a new project returns the same error message.

**Comment by natemcmaster** [comment]
@minimalisticMe which project type are you using? (e.g. .NET Core, UWP, ASP.NET, etc) can you share your project? Also, can you execute the command with the extra parameter `-Verbose` and share the output (`Add-Migration Name -Verbose`)? This will show additional output to help us identify what is wrong.

**Comment by minimalisticMe** [comment]
THe project type is c# UWP. The command `-verbose` does not show much more than the project name:

```
Using startup project 'Test2'.
Using project 'Test2'
Add-Migration : Der Wert liegt außerhalb des erwarteten Bereichs.
In Zeile:1 Zeichen:1
+ Add-Migration migration1 -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Add-Migration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Add-Migration
```

The project is a minimal project with just the following lines of code (in different classes)
```
public class Blog
{
    public int BlogId { get; set; }
    [Column(TypeName = "varchar(200)")]
    public string Url { get; set; }

    public BlogImage BlogImage { get; set; }
}

public class BlogImage
{
    public int BlogImageId { get; set; }
    public byte[] Image { get; set; }
    public string Caption { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```
and

```
public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<BlogImage> BlogImage { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Filename=Blogging.db");
    }
}
```

**Comment by minimalisticMe** [comment]
Update: I deinstalled my VC2015.3 and installed the english version of VS2015 Update 3 and now Migration works again.

**Comment by natemcmaster** [comment]
@minimalisticMe I'll be looking into this more after our 1.0.0 release comes out next week. This error looks similar to https://github.com/aspnet/EntityFramework/issues/5383 which may have been fixed in #5476. This fix will be in the 1.0.0 release.

**Comment by natemcmaster** [comment]
@minimalisticMe does your error still reproduce with 1.0.0?

**Comment by minimalisticMe** [comment]
@natemcmaster I cannot check, as I switched to english version of VS2015 and did not turn back since then.

**Comment by natemcmaster** [comment]
Ok. I will close the issue for now. Feel free to re-open if you are able to reproduce it with 1.0.0.
