### ISSUE TITLE
Define Non Clustered Index For Primary Key

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#5790]
Code First does not allow to define a Primary Key as a non-clustered index. This becomes necessary to customize a table for utilization of optimum index.

**Comment by ajcvickers** [comment]
@satyajit-behera There is an extension method for this. For example:
```C#
modelBuilder.Entity<Blog>()
    .HasKey(b => b.BlogId)
    .ForSqlServerIsClustered(false);
```

**Comment by satyajit-behera** [comment]
@ajcvickers @rowanmiller  Thanks a lot

**Comment by satyajit-behera** [comment]
@ajcvickers Is there any similar stuff using EF6 Code first.

**Comment by ajcvickers** [comment]
@satyajit-behera If I remember correctly, in EF6 you can't do it via the Code First API, but you can edit the migration by hand to do it.

**Comment by satyajit-behera** [comment]
@ajcvickers Thanks a lot.
