### ISSUE TITLE
Specified cast is not valid. Error on simple query.

### ISSUE THREAD

**Issue by ElvisHalil** [dotnet/efcore#5799]
`var user2 = _userInfoRepository.FindBy(x => x.TECHUserID == "0d257342-d06d-49c4-9e65-148016606b4f").FirstOrDefault();`

`var user = _userRepository.FindBy(x => x.Id == "0d257342-d06d-49c4-9e65-148016606b4f").Include(x => x.UserInfo).FirstOrDefault();`

I am uncertain as to what exactly is causing this and would appreciate some feedback.  Both these lines cause similar issues.  The biggest difference is that userRepository itself, can return records from the TECHUsers table that it's abstracting.  However, when I add the Include clause for UserInfo I get the specified Cast not Valid Error. 

Something probably important to note is that the userRepository is for my TECHUsers class in my model which inherits from IdentityUser.  I have linked the IdentityUser table (TECHUsers) with my UserInfo table by putting the TECHUsers ID into the UserInfo table.  The relationship all seem perfectly correct in SQL server with foreign keys. 

Here is the stack trace I get: 

`at lambda_method(Closure , ValueBuffer )
   at Microsoft.Data.Entity.Query.EntityLoadInfo.Materialize()
   at Microsoft.Data.Entity.Query.Internal.QueryBuffer.GetEntity(IKeyValue keyValue, EntityLoadInfo entityLoadInfo, Boolean queryStateManager)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.CreateEntity[TEntity](IQuerySource querySource, ValueBuffer valueBuffer, Int32 valueBufferOffset, QueryContext queryContext, IEntityType entityType, Boolean trackingQuery, KeyValueFactory keyValueFactory, Func 2 materializer, Boolean allowNullResult, Boolean useQueryBuffer)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator 2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable 1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_1 1.<CompileQuery>b__1(QueryContext qc)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable 1 source)
   at TECH.Translator.GTGSystems.Implementation.G2.Process(String path, String sessionNumber, DirectoryInfo sessionFolder) in C:\Users\Elvis\Source\Repos\TECH\TECH.Translator\GTGSystems\Implementation\G2.cs:line 68
   at TECH.Translator.Program.ProcessG2() in C:\Users\Elvis\Source\Repos\TECH\TECH.Translator\Program.cs:line 83`

This is starting to be a pretty large solution and really need this little kink worked out so I don't go to deep before having serious issues.  It's also hard to share as I have some local files that are needed in order for this to work properly as its a processor (Translator) reading data from different sources and formats to standardize into a single DB and consistent format regardless of source.  I am using repository pattern and this specific component is a console application. 

I am currently still using:
EF 7 RC-1
ASP.Net Core RC-1
ASP.NET Identity 3.0 RC-1

Any help would be appreciated!

**Comment by anpete** [comment]
@ElvisHalil Can you please try again on RC2?

**Comment by ElvisHalil** [comment]
It was on my agenda to port to RC 2 soon.  Is it likely that this will fix my problem?

**Comment by ElvisHalil** [comment]
I guess there is no point in really staying in RC 1.. I will give this a shot tomorrow and let you know how it goes. @anpete thanks!

**Comment by maumar** [comment]
yes, there have been many improvements to query pipeline between RC1 and RC2, some of them were around include.

**Comment by ElvisHalil** [comment]
I have upgraded to RC2 now and I am getting the same issue. I have a feeling it is to do with ASP.Net Identity.  The table I'm trying to access is a child table of the IdentityUser table. 

_userRepository = Repo for table that inherits from IdentityUser
_userInfoRepository = Repo for table that has a FK to the table above <= this is the table I try to access and get errors no matter if I use a include, or if I try to access it directly through the repo.

**Comment by ElvisHalil** [comment]
I re-generated my migrations and tried to update my DB with the new migration and got an error.  

Defaults cannot be created on columns with an IDENTITY attribute. Table 'Accounts_Identity_Users' 

I will fix these up and see if that resolves my issue.

**Comment by ElvisHalil** [comment]
I have narrowed this down now to one table.  The UserInfo table I have.  I am no longer using ASP.Net Identity.  

Here is my UserInfo class:

public partial class UserInfo
    {
        public int ID { get; set; }
        public Guid UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostalCode { get; set; }
        public Char Gender { get; set; }
        public short? MunicipalityID { get; set; }
        public short? RegionID { get; set; }
        public DateTimeOffset? EffectiveDt { get; set; }
        public virtual Users User { get; set; }
        public virtual Regions Region { get; set; }
        public virtual Municipalities Municipality { get; set; }
    }


Here is what's in SQL:

ID	int	Not Null
Address1	nvarchar(MAX)	Null
Address2	nvarchar(MAX)	Null
Address3	nvarchar(MAX)	Null
EffectiveDt	datetimeoffset(7)	Null
FirstName	nvarchar(MAX)	Not Null
Gender	char(1)	Not Null
LastName	nvarchar(MAX)	Not Null
MunicipalityID	smallint	Null
PostalCode	nvarchar(MAX)	Null
RegionID	smallint	Null
UserID	uniqueidentifier	NotNull

and my modelBuilder in my DBContext:

            modelBuilder.Entity<UserInfo>(entity =>
            {
                entity.ToTable("Accounts_Tech_UserInfo");

                entity.Property(e => e.FirstName)
                .IsRequired();

                entity.Property(e => e.LastName)
                .IsRequired();

                entity.Property(e => e.EffectiveDt)
                .HasDefaultValue(DateTimeOffset.Now);

                entity.Property(e => e.Gender)
                .IsRequired()
                .HasColumnType("char(1)")
                .HasMaxLength(1);
            });

Any ideas why I'm having troubles accessing this table?

**Comment by ElvisHalil** [comment]
Here is my Users class for a bit more context on the model:

    public partial class Users
    {
        public Guid ID { get; set; }
        public string UserName { get; set; }
        public string AADID { get; set; }

        public virtual Operators Operator { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
        public virtual ICollection<UserEmailAddress> UserEmailAddress { get; set; }
        public virtual ICollection<UserPhoneNumber> UserPhoneNumber { get; set; }
    }

This is the related table for UserInfo

**Comment by ElvisHalil** [comment]
Here is a screenshot while debugging, it hits the line where my userRepo is accessed and the DBSet is populated with what is in my DB:

![userrepo](https://cloud.githubusercontent.com/assets/6643233/16212323/12b152da-3704-11e6-8532-368fe7f35371.jpg)


As opposed to my userInfoRepo which looks like this on the next line but haven't continued the debugger:

![userinforepo](https://cloud.githubusercontent.com/assets/6643233/16212349/37a1048c-3704-11e6-89a7-2624c5e05db6.jpg)

**Comment by ElvisHalil** [comment]
Stack Trace:

 at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at TECH.Translator.GTGSystems.Implementation.G2.Process(String path, String sessionNumber, DirectoryInfo sessionFolder) in C:\Users\Elvis\Source\Repos\TECH\TECH.Translator\GTGSystems\Implementation\G2.cs:line 70
   at TECH.Translator.Program.ProcessG2() in C:\Users\Elvis\Source\Repos\TECH\TECH.Translator\Program.cs:line 83

**Comment by ElvisHalil** [comment]
using (TEDContext ctx = new TEDContext())
            {
                var testing123 = ctx.UserInfo.AsEnumerable();
            }

gives me the exact same error

**Comment by anpete** [comment]
@ElvisHalil This could be because of a mismatch in data types between the table values vs the CLR types of the properties on UserInfo. You could try commenting out the UserInfo properties and selectively adding them back to find out where it breaks.

**Comment by ElvisHalil** [comment]
@anpete I had a feeling it was to do with that.  Would this not be considered a bug?  With EF Core it's all code first so the class and the modelBuilder create the tables in the DB.  Why would there be a mismatch like this? 

I'll poke around and do as you suggested to see if I can narrow it down.

**Comment by ElvisHalil** [comment]
I found the culprit.  I commented out my model builder and noticed that the Char data type in my class for Gender would translate to an Int in SQL.  

I changed the data type now to string and adjust it to nvarchar(1) using the model builder. Seems to work now, just need to put back the rest of my fields but I feel confident I've found the problem. 

Why would the Char data type translate to an Int in SQL?

**Comment by ElvisHalil** [comment]
Seems to work now.  I've changed the Gender data type to string instead of char and set it to char in the modelBuilder:

                entity.Property(e => e.Gender)
                .IsRequired()
                .HasColumnType("char(1)")
                .HasMaxLength(1);

This seems to work.  I think there is a bug with char data type.
