### ISSUE TITLE
Sqlite Guid PK saved as binary not text

### ISSUE THREAD

**Issue by RonFrick** [dotnet/efcore#5805]
Is there any way to specify how a guid is saved in SQLite using EF? I have data that is already saved in the .db file using our sync framework, but when I save data using EF it is a different type (BLOB) not text and cannot be queried again.

Screen shot...
![image](https://cloud.githubusercontent.com/assets/11793573/16166065/73b1dfb8-34ad-11e6-8602-17e0ce3161dd.png)

**Comment by RonFrick** [comment]
After I save the data and then try to query the same row I get this...

Additional information: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

**Comment by RonFrick** [comment]
In System.Data.Sqlite there is a way to specify the format of Guids using BinaryGUID=False. Is there a way to do the same in Microsoft.Data.Sqlite?

Thanks!

**Comment by RonFrick** [comment]
https://gist.github.com/flaub/1968486e1b3f2b9fddaf

**Comment by rowanmiller** [comment]
Closing this one as we will track this with https://github.com/aspnet/Microsoft.Data.Sqlite/issues/273 (which would include surfacing an API in EF if we do it).
