### ISSUE TITLE
Query: InMemory: Rewrite equality for reference types (byte[])

### ISSUE THREAD

**Issue by tillig** [dotnet/efcore#5806]
Given a context that has objects using binary types...

``` csharp
public class SqlDataContext : DbContext
{
  public DbSet<ApiKey> ApiKeys { get; set; }
}

public class ApiKey
{
  public byte[] Hash { get; set; }
}
```

If you want to query using the in-memory provider, binary comparisons don't work as expected:

``` csharp
// Always returns null because it's comparing object references
// rather than using value equality.
this.DataContext.ApiKeys.FirstOrDefaultAsync(k => k.Hash == hash)
```

Based on [some StackOverflow research](http://stackoverflow.com/questions/23175762/comparing-byte-array-in-entity-framework-where-clause) I gather in SQL Server this should work.

That said, **is this the best way to search on binary data using EF?** If different providers may behave differently, I'm guessing an alternate mechanism may be needed. For example, maybe I should store the binary as base64 encoded strings and search on that?

**Comment by ajcvickers** [comment]
Notes from #8376: Notes from triage: this bug is really about deep comparisons on arrays, etc. when comparing them inside the in-memory database. Decided that this should always be a deep comparison, done by re-writing the expression, and we should consider using IStructuralComparable.

**Comment by smitpatel** [comment]
This should be easy to do in new pipeline.

**Comment by smitpatel** [comment]
@ajcvickers - You modified code in this area when fixing #14042 would it also fix this?

**Comment by ajcvickers** [comment]
@smitpatel Likely yes, but I'm not 100% sure.

**Comment by smitpatel** [comment]
Put verify-fixed label.
