### ISSUE TITLE
I don't see the local property of the DbSet

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#5810]
In EF6 I have the property MyDbSet.Local in which I can access to the entities that are in the DbContext, so I can access to the local entities so I don't have to do another queries to the database.

In EF Core I don't see this property, so I would like to know the way that I can access to the entities that are loead in the DbContext.

**Comment by ajcvickers** [comment]
@ComptonAlvaro `DbSet.Local` is not yet implemented. You can use  `context.ChangeTracker.Entries' to get access to the entities that are being tracked. For example, to get all tracked entities, you can do:
```C#
context.ChangeTracker.Entries().Select(e => e.Entity)
```
To get all tracked Blog entities, do:
```C#
context.ChangeTracker.Entries<Blog>().Select(e => e.Entity)
```
