### ISSUE TITLE
Sqlite provider uses ambigous DateTime format

### ISSUE THREAD

**Issue by dooreelko** [dotnet/efcore#5814]
### Steps to reproduce
- Suppose I'm in GMT+2
- Have a DateTime field in an entity
- Store there a date built from "2016-06-20 08:50:56Z"
- The database will contain the string representation without time zone (using @"yyyy-MM-dd HH:mm:ss.FFFFFFF") i.e "2016-06-20 08:50:56.12345"
- In another process, load the entity from the db, the default parser will use current time zone to convert string to date
- The date will be 2 hours off
### The issue

This will work only if server and client are both in Greenwich
Since sqlite uses TEXT for DateTime, the format should be explicit with time zone (i.e. "u" will do)
### Further technical details

EF Core version: 7.0.0-rc1-final
Operating system: OSX
Visual Studio version: n/a

**Comment by rowanmiller** [comment]
Hey,

The lack of time zone awareness is an inherent limitation of DateTime. For time zone aware dates, you should use DateTimeOffset instead.

~Rowan
