### ISSUE TITLE
Scaffolding a migration created using RC2 templates don't work with RTM dotnet-ef migrations

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#5820]
I ran into this because the tooling I was based on RC2 templates. It looks like the location where migrations discovers the `maxLength` value for a column changed between RC2 and RTM. In RC2, the `NormalizedName` column for the `ApplicationUser` model looked like so:

`NormalizedName = table.Column<string>(nullable: true)`

and in RTM, it looks like:

`NormalizedName = table.Column<string>(maxLength: 256, nullable: true)`

Running `dotnet ef database update` on the RC2 template results in: `System.Data.SqlClient.SqlException (0x80131904): Column 'NormalizedName' in table 'AspNetRoles' is of a type that is invalid for use as a key column in an index.`. 

Would this warrant an announcement (to tell users to specify the `maxLength` parameter?)

**Comment by pranavkm** [comment]
cc @smitpatel \ @bricelam

**Comment by smitpatel** [comment]
Due to changes introduced in #5555 
We did have a mail thread about this.
as @bricelam noted in that
> 2. Yes, the operations coming out of the model differ will set it to whatever was in the metadata, but the user is free to change the value in the scaffolded migration.

`maxLength` in migrations overrides settings from model. Since templates don't have `maxLength` in migration, `nvarchar(max)` column is created for index causing exception.

**Comment by rowanmiller** [comment]
We'll make sure this gets mentioned in release notes etc.

**Comment by dougbu** [comment]
@rowanmiller why is there no announcement for this breaking change?

I hit this issue too and went looking for a solution in [aspnet/Announcements](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0). Eventually found aspnet/Performance#145 and aspnet/Templates@26b9b04 but...

**Comment by rowanmiller** [comment]
There will be, we just weren't aware of the implication of the change. That's what I meant by 

> We'll make sure this gets mentioned in release notes etc.

😄

**Comment by rowanmiller** [comment]
Announcement created: https://github.com/aspnet/Announcements/issues/195
