### ISSUE TITLE
Includes of collection navigation property's children yields exception

### ISSUE THREAD

**Issue by jmercker** [dotnet/efcore#5827]
### Steps to reproduce

Given a hierarchy of objects like this:
User
    - UserRole
          - Role
                - RolePermissions
                       - Permission
And a User can have 0 or more UserRoles
And a UserRole has a single Role
And a Role has 0 or more RolePermissions
And a RolePermission has a single Permission

Executing this query yields the exception noted below.

Query (C#):  
`var user = ctx.Set<User>().Include(u => u.UserRoles.Select(ur => ur.Role.RolePermissions)).Where(u => u.SessionToken == sessionToken && u.IsActive == true)
                .FirstOrDefault();`

NOTE: The above query is just an example that I used to try to narrow the issue.  My actual usage precludes me from using multiple Include, ThenInclude separately as all DbContext access is being wrapped inside of a generic repository implementation that does not expose the DbContext or IQueryable.  The above approach towards Including additional graph items works fine in EF 6.
### The issue

When processing an Include statement to request a graph of related children where some or all of the children are collections, I am unable to process an include of the format: 
root => root.Children.Select(child => child.ChildProperty).

Exception message: The property expression 'u => {from UserRole ur in [u].UserRoles select [ur].Role.RolePermissions}' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.

Stack trace:
An unhandled exception occurred while processing the request.

InvalidOperationException: The property expression 'u => {from UserRole ur in [u].UserRoles select [ur].Role.RolePermissions}' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.
Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.IncludeExpressionNode.CreateResultOperator(ClauseGenerationContext clauseGenerationContext)
### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: Windows 10
Visual Studio version: VS 2015 Professional

Other details about my project setup:

**Comment by rowanmiller** [comment]
**EF Team Triage:** Our plan is to also have [string based include](https://github.com/aspnet/EntityFramework/issues/3921), we just haven't implemented it yet. With the new C# `nameof` feature, this gives a decent way to handle these more dynamic scenarios. At this stage, we aren't really keen to enable a second pattern for lambda based includes.

**Comment by jmercker** [comment]
That's fine.  As long as there's a way to generically build these types of include graphs without the requirement that a caller have access to the DbContext/IQueryable it should be OK.  I'm sure that there are tons of groups out there using an abstraction around the DbContext that would require it....

**Comment by jmercker** [comment]
The Include/ThenInclude syntax only works well with concrete implementations where you're building queries directly against the DbSet or where a library is exposing that kind of thing through IQueryable.  That's where EF6's include syntax was superior...

**Comment by rowanmiller** [comment]
@jmercker agreed that it is an important scenario. We're not planning to support the exact syntax from EF6, but we do know we need a more dynamic-friendly option.

**Comment by jmercker** [comment]
Thanks Rowan.  I appreciate all that you guys are doing on getting this out.

**Comment by javivalero** [comment]
Hi

    I have the same situation when i try to filter child related data using a Generic repository:
         public TEntity GetById(TIdentifier identifier, string cultureInfo)
        {
            IQueryable<TEntity> query = _UnitOfWork.CreateSet<TEntity>().Where(p => p.Id.Equals(identifier)).AsQueryable();

            query = query.Include(p => p.LanguageLiterals.Where(j=>j.CultureInfo==cultureInfo));

            return query.FirstOrDefault();
        }



           When the query is executed I recevie the same eror on p.LanguageLiterals.Where(j=>j.CultureInfo==cultureInfo)), when i try to filter the child entity "LaguageLiterals" on the field CultureInfo.

          Exist other way to include the related childs using a filter on one field?

kind regards
Javier

**Comment by divega** [comment]
@javivalero you must be getting an exception that explains that the lambda passed to `Include()` needs to be jus plain access to a navigation property or set of navigation properties. A `Where()` clause cannot be nested inside `Include()`
