### ISSUE TITLE
Running a full build takes too long

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#5830]
A full build consistently takes over an hour now on CI. AppVeyor has started cancelling EF builds that run 60+ minutes.

![image](https://cloud.githubusercontent.com/assets/2696087/16249088/8f7ea12c-37c8-11e6-908c-6828f3514293.png)
https://ci.appveyor.com/project/aspnetci/entityframework/build/1.0.2548/messages

Easy options for speeding up build
- Move benchmarks to separate repo (currently taking about 7-8 minutes)
- Don't run every test twice. (e.g. on .NET Framework _and_ .NET Core) (doubles our test time)

More work, but may have increase benefit
- Parallelize non-SQL Server test assemblies
- Find ways to merge long-running tests without reducing coverage

**Comment by ajcvickers** [comment]
We should also try to understand why running all the tests from within Visual Studio still only takes approximately 10 minutes, while running in the C,I. seems to take a lot longer.

**Comment by smitpatel** [comment]
This was mainly fixed by https://github.com/aspnet/EntityFrameworkCore/pull/8377

On our EFCI, it takes around 20 mins. Local build is faster than that. And Travis/Appveyor takes max 40 mins.
