### ISSUE TITLE
[Suggestion] When a table names exists in more than one schema, dbcontext scaffold should use namespace as discriminator

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#5836]
Consider tables `dbo.Person` and `test.Person`. When I scaffold these tables, the scaffolder picks (seemingly in no specific order) types `Person` and `Person1`. Instead, it could use the namespace to discriminate types in this case.

**Comment by rowanmiller** [comment]
Duplicate of https://github.com/aspnet/EntityFramework/issues/3988
