### ISSUE TITLE
differing behavior with SQL processed Queryable.Where() vs. locally processed

### ISSUE THREAD

**Issue by pryankster** [dotnet/efcore#5838]
### Steps to reproduce

Create a class with a nullable string column and a navigation property to another class (good old' blog/article pair works). Dependent class should have an additional (nullable) string property ("subtitle")

Add a graph with a null value on a property.

Query the nullable column with 'Contains()'
### The issue

Behavior differs depending on whether or not the query is executed on the server.

If the Where() clause is executed in Sql, on the server:
- A query which compares the null column will succeed (it will -- correctly -- not match the row, but it will not crash
- A query which uses .Contains() on the server, by default is case-insensitive
  If the Where() clause is executed on the client:
- A query which compares the null column will crash with a NullReferenceException
- A query which uses .Contains() on the client is case sensitive by default.

Note: the problem is not specific to Contains() -- it is a more general problem of not knowing when a query will be executed in SQL or in C#, and that the query mechanics differ significantly between the two
### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system:  Windoes 10
Visual Studio version: (e.g. VS 2013 or n/a) VS2015 Community

Other details about my project setup: 
Example project here: https://github.com/pryankster/EFTests

**Comment by rowanmiller** [comment]
Getting exact parity between C# and the database is not something that we want to try and guarantee. For example, we don't want to artificially throw when you run contains on a column that contains nulls - as SQL Server does support doing that. .NET on the other hand requires you to protect against calling a method on a null reference. 

You can disable client evaluation from happing in LINQ queries run thru EF Core - see https://docs.efproject.net/en/latest/querying/client-eval.html#disabling-client-evaluation.

**Comment by pryankster** [comment]
Seems to me this violates the principle of least astonishment ...  If the queries are going to act differently when processed client side vs. on the server, the default should be to throw an exception (with a helpful "you can turn this into a warning" type message).

It seems like a bad smell to have to code to two different semantics without knowing, a-priori which semantic you're going to get -- if you can't guarantee that "x.Contains()" is going to work the same between the server and client evaluation, it should be called something else -- same with equality -- because, as a programmer, I can't know ahead of time which semantics I'm going to get, it's up to the vagaries (and sometimes brokenness!) of EF to decide how to search my data when I thought I was being explicit about how to search the data.

-- pryankster
