### ISSUE TITLE
Templates: Missing database error page: Update Database does not work

### ISSUE THREAD

**Issue by HaoK** [dotnet/efcore#5840]
When accessing an unexisting database after create a new Individual Auth Web App project, error page shows:

In Visual Studio, you can use the Package Manager Console to apply pending migrations to the database:
PM> Update-Database

This actually does not work by default in a new project, either this text should be removed, or something needs to be fixed?

**Comment by rowanmiller** [comment]
It's an intermittent issue with NuGet not running the Init.ps1 file from the EF tools package. Here is the NuGet issue tracking the problem https://github.com/nuget/home/issues/3023.

**Comment by rowanmiller** [comment]
Just to add context, NuGet runs Init.ps1 from the tools package when it is installed/restored, this script is what registers the command in Package Manager Console

**Comment by HaoK** [comment]
Ok closing as dupe then
