### ISSUE TITLE
Migrations - migrate the model changes

### ISSUE THREAD

**Issue by sanalbakis** [dotnet/efcore#5842]
Dear folks,

I am creating the database via EF, for the first time it is working. I added a new model (Logs.cs in this case) to the context, I need to migrate it, but I have an issue as following under: 
(It is clear but I have unfortunately no solution for this, yet)
E:\Kaya\Projects\Web\PIM\src\SEWA-PIM>dnx ef migrations Add Logging

System.InvalidOperationException: The navigation property '' cannot be added to the entity type 'BaseObject' because a navigation property with the same name already exists on entity type 'BaseObject'.
   at Microsoft.Data.Entity.Metadata.Builders.ReferenceNavigationBuilder.WithOneBuilder(String reference)
   at Microsoft.Data.Entity.Metadata.Builders.ReferenceNavigationBuilder.WithOne(String reference)
   at SEWAPIM.Migrations.SoftcardContextModelSnapshot.<>c.<BuildModel>b__0_51(EntityTypeBuilder b) in  E:\Kaya\Projects\Web\PIM\src\SEWA-PIM\Migrations\SoftcardContextModelSnapshot.cs:line 1657
   at Microsoft.Data.Entity.ModelBuilder.Entity(String name, Action`1 buildAction)
   at SEWAPIM.Migrations.SoftcardContextModelSnapshot.BuildModel(ModelBuilder modelBuilder) in E:\Kaya\Projects\Web\PIM\src\SEWA-PIM\Migrations\SoftcardContextModelSnapshot.cs:line 1644
   at Microsoft.Data.Entity.Infrastructure.ModelSnapshot.<.ctor>b__1_0()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
The navigation property '' cannot be added to the entity type 'BaseObject' because a navigation property with the same name already exists on entity type 'BaseObject'.

You can see my model & builder as following:

BaseObject Class:

```
public class BaseObject : IEntity
{
    public long Id { get; set; }

    public long BaseObjectId { get; set; }

    public long? ParentId { get; set; }
    private BaseObject _parent;

    public virtual BaseObject Parent
    {
        get { return _parent; }
        set
        {
            _parent = value;
            ParentId = value != null ? value.BaseObjectId : (long?)null;
        }
    }

    public long ObjectTypeId { get; set; }
    public ObjectType ObjectType { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public long? CreatedById { get; set; }
    public User CreatedBy { get; set; }

    public long? UpdatedById { get; set; }
    public User UpdatedBy { get; set; }

    public DateTime OnlineFrom { get; set; }
    public DateTime OnlineTo { get; set; }

    public int Sorter { get; set; }

}
```

BaseEntitiy.cs

```
public class BaseEntity : IEntity
{
    public long Id { get; set; }

    public long BaseObjectId { get; set; }
    private BaseObject _baseObject;

    public virtual BaseObject BaseObject
    {
        get { return _baseObject; }
        set
        {
            _baseObject = value;
            BaseObjectId = value.BaseObjectId;
        }
    }

    public long? ParentId { get; set; }
    private BaseObject _parent;

    public virtual BaseObject Parent
    {
        get { return _parent; }
        set
        {
            _parent = value;
            ParentId = value != null ? value.BaseObjectId : (long?)null;
        }
    }

    public virtual string Name { get; set; }

}
```

BaseModel.cs

```
    public static void Create<T>(ModelBuilder builder, string tableName) where T : BaseEntity
    {

        builder.Entity<T>(x =>
        {
            x.Property(p => p.Id).IsRequired();

            x.HasOne(p => p.Parent)
                .WithOne()
                .HasPrincipalKey<BaseObject>(p => p.BaseObjectId)
                .HasForeignKey<T>(p => p.ParentId)
                .HasConstraintName("FK_" + tableName + "_BaseObject_ParentId");

            x.HasAlternateKey(p => p.BaseObjectId);
            x.HasOne(p => p.BaseObject)
                .WithOne()
                .HasPrincipalKey<BaseObject>(p => p.BaseObjectId)
                .HasForeignKey<T>(p => p.BaseObjectId)
                .HasConstraintName("FK_" + tableName + "_BaseObject_BaseObjectId").OnDelete(Microsoft.Data.Entity.Metadata.DeleteBehavior.Restrict);

            x.HasKey(p => p.Id).HasName(string.Format("PK_{0}", tableName));
            x.ToTable(tableName);
            //x.TextProperty(p => p.Name, 80);
            x.Property(p => p.Name).HasMaxLength(80);

        });

    }
```

And in builder I can call the Create function as :

```
 BaseModel.Create<Logs>(builder, "Logs"); 
```

The SnapShot on line 1644: 

```
 modelBuilder.Entity("Business.Entity.Base.BaseObject", b =>
            {
                b.HasOne("Business.Entity.Model.UserData.User")
                    .WithOne()
                    .HasForeignKey("Business.Entity.Base.BaseObject", "CreatedById")
                    .HasAnnotation("Relational:Name", "FK_BaseObject_User_CreatedById")
                    .HasPrincipalKey("Business.Entity.Model.UserData.User", "BaseObjectId");

                b.HasOne("Business.Entity.Base.ObjectType")
                    .WithOne()
                    .HasForeignKey("Business.Entity.Base.BaseObject", "ObjectTypeId")
                    .HasAnnotation("Relational:Name", "FK_BaseObject_ObjectType_ObjectTypeId");

                b.HasOne("Business.Entity.Base.BaseObject")
                    .WithOne()
                    .HasForeignKey("Business.Entity.Base.BaseObject", "ParentId")
                    .HasAnnotation("Relational:Name", "FK_BaseObject_BaseObject_ParentId")
                    .HasPrincipalKey("Business.Entity.Base.BaseObject", "BaseObjectId");

                b.HasOne("Business.Entity.Model.UserData.User")
                    .WithOne()
                    .HasForeignKey("Business.Entity.Base.BaseObject", "UpdatedById")
                    .HasAnnotation("Relational:Name", "FK_BaseObject_User_UpdatedById")
                    .HasPrincipalKey("Business.Entity.Model.UserData.User", "BaseObjectId");
            });
```
### Further technical details

EF Core version: "7.0.0-rc1-final",
Operating system: Windows 10 - x64
Visual Studio version: VS2015

**Comment by rowanmiller** [comment]
Please retry this on RC2 and see if the issue persists. This is similar to a number of issues we fixed in RC2.

**Comment by rowanmiller** [comment]
Feel free to reply if this is not fixed in RC2.

**Comment by sanalbakis** [comment]
Thank you,

I could not upgrade it to Core 1.0.0, yet because there are still some errors. 

I have a "BaseObjectId" and each item in tables have it, it is sequence and this Id is always a foreign key on my system. 

on rc1 I could write the ForeignKey as:

p.HasOne(x => x.Export)
                    .WithOne()
                    .HasPrincipalKey<Export>(x => x.BaseObjectId)
                    .HasForeignKey<ExportCustomer>(x => x.ExportId)
                    .HasConstraintName("FK_ExportCustomer_Export_ExportId");

After I updated it to Core 1.0.0, 
I see there is another ForeignKey created automatically as shown following. The second one is not mines. 

table.ForeignKey(
                        name: "FK_ExportCustomer_Export_ExportId",
                        column: x => x.ExportId,
                        principalTable: "Export",
                        principalColumn: "BaseObjectId",
                        onDelete: ReferentialAction.Cascade);

                    table.ForeignKey(
                        name: "FK_ExportCustomer_Export_ExportId",
                        column: x => x.ExportId,
                        principalTable: "Export",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);

**Comment by rowanmiller** [comment]
@sanalbakis I'm speculating, so this may not explain the issue... but it looks like `ExportCustomer` has an `Export` navigation property, does `Export` have a navigation property pointing back to `ExportCustomer`? If so, you would need to specify that in the `WithOne()` call when configuring the relationship. If the navigation is present, then the empty `WithOne()` call is saying there is no navigation property on the other side, which means the navigation that is there must be a different relationship, which explains the extra foreign key.

**Comment by sanalbakis** [comment]
hi,
sorry. I think the migration problem is solved, because now I can add a new Migration via "Add-Migration Initial2". I was not sure to open a new issue for the relations. This has worked well on rc1, it does not work on updated version.

My Model classes and builder are below: 

Export.cs

    public class Export : BaseEntity
    {
        public string ExportTyp { get; set; }

        public ExportCustomer ExportCustomer { get; set; }

        .....
    }

ExportCustomer.cs 

    public class ExportCustomer : BaseEntity
    {
        public string CustomerNumber { get; set; }

        public string CustomerName { get; set; }

        public bool IsInExport { get; set; }

        public long ExportId { get; set; }
        //public Export Export {get; set; }
        private Export _export;

        public Export Export
        {
            get { return _export; }
            set
            {
                _export = value;
                ExportId = value.BaseObjectId;
            }
        }
        .....
    }

  And the ModelBuilder

     builder.Entity<ExportCustomer>(p =>
     {
                p.HasOne(x => x.Export)
                    .WithOne()
                    .HasPrincipalKey<Export>(x => x.BaseObjectId)
                    .HasForeignKey<ExportCustomer>(x => x.ExportId)
                    .HasConstraintName("FK_ExportCustomer_Export_ExportId");
      }

**Comment by rowanmiller** [comment]
Model builder code should look like this:

```c#
builder.Entity<ExportCustomer>(p =>
 {
            p.HasOne(x => x.Export)
                .WithOne(e => e.ExportCustomer)
                .HasPrincipalKey<Export>(x => x.BaseObjectId)
                .HasForeignKey<ExportCustomer>(x => x.ExportId)
                .HasConstraintName("FK_ExportCustomer_Export_ExportId");
  }
```

Note the non-empty call to `WithOne()`. I'm not sure why this worked in RC1, it was a bug if it wasn't introducing two relationships.

**Comment by sanalbakis** [comment]
Hey,
that's great, it is working now! Thanks a lot! I can not go on with core!
