### ISSUE TITLE
Change type of an existing column

### ISSUE THREAD

**Issue by seriouz** [dotnet/efcore#5843]
I tried to change the type from a int to another class.

``` csharp
public class Permission
{
    public int PermissionId { get; set; }
    public int CreatedBy { get; set; }
}
```

to

``` csharp
public class Permission
{
    public int PermissionId { get; set; }
    public ApplicationUser CreatedBy { get; set; }
}
```

> System.InvalidOperationException: The property 'CreatedBy' cannot be added to the entity type 'Permission' because a navigation property with the same name already exists on entity type 'Permission'.

What is the way for changing column types?

**Comment by rowanmiller** [comment]
@seriouz can you post the full stack trace for the exception.

**Comment by AndriySvyryd** [comment]
@seriouz I wasn't able to reproduce the error. Could you provide the full model or a repro project?

**Comment by divega** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.
