### ISSUE TITLE
DbContextOptionsBuilder.UseSqlServer with escaped backslash in connection string.

### ISSUE THREAD

**Issue by Micteu** [dotnet/efcore#5851]
### Steps to reproduce

Have a connection string (ours was in an appsettings.json file that refers to a SQL Server instance that has a backslash in its name. The connection string will need to have it escaped.

Set up a query on that database.
### The issue

When built in Windows 7 or 10 and ran, this works fine. When built in Docker and ran, it throws an exception. When I changed my connection string over from
Server=serverName\InstanceThinger
to
Server=ipAddress,port
the exception stopped happening.

Exception message:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)

Discussion on Reddit: https://www.reddit.com/r/dotnet/comments/4cjv33/net_core_with_docker/d3i7htt
### Further technical details

EF Core version: 1.0.0-rc2-final
Visual Studio version: 2015

**Comment by natemcmaster** [comment]
This doesn't appear to be related to Entity Framework. The error you shared indicates that this is a networking issue, in particular, DNS inside your Docker container isn't working as you expect it to. Checkout Docker's docs on these topics. https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by Micteu** [comment]
Oh, jeepers. Thanks.
