### ISSUE TITLE
Problem loading self reference items

### ISSUE THREAD

**Issue by rsalvadorg** [dotnet/efcore#5854]
```
public class ParentClass
{
       [Key]
        public int IdParentClass { get; set; }
        public string Name { get; set; }        
        public virtual ICollection<ListItem> ListItems{ get; set; }
}
public class ListItem
{
        [Key]
        public int IdListItem { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdBlockedBy { get; set; } 
        public int IdParentClass { get; set; }
        public virtual ListItem PrevItem { get; set; }
        public virtual ParentClass ParentClass{ get; set; }
        public virtual ICollection<ListItem > ChildItems{ get; set; }
 }

DbContext:
  modelBuilder.Entity<ListItem>()
                .HasOne(p => p.PrevItem )
                .WithMany(i => i.ChildItems)
                .HasForeignKey(x => x.IdBlockedBy )
                .IsRequired(false);

            modelBuilder.Entity<ListItem>()
                .HasOne(p => p.ParentClass)
                .WithMany(i => i.ListItems)
                .HasForeignKey(x => x.IdParentClass );
```

If I load a list of ParentClass in this way, I don't get obviously any ListItem

```
ManagementContext context = new ManagementContext();
return context.Parent.ToList();

```

But I do like that, I get the whole recursive List of list Items. And the question is, how can if I can stop It and just load the first level of the list?

```
ManagementContext context = new ManagementContext();
return context.Parent.Include(a=>a.ListItems).ToList();
```

Something like:

ParentClass:{
IdParentClass : 1
Name: Parent1
ListItems: [
Child1:{
-----Child1a{
----------Child1a1
----------Child1a2}
-----Child1b{
----------Child1b1
----------Child1b2}},
--Child2{
-----Child2a{
----------Child2a1
----------Child2a2}
-----Child2b{
----------Child2b1
----------Child2b2}}
]}

**Comment by rowanmiller** [comment]
Here is a little extract from the EF docs that helps explain what is happening - https://docs.efproject.net/en/latest/querying/related-data.html:

> Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance. So even if you don’t explicitly include the data for a navigation property, the property may still be populated if some or all of the related entities were previously loaded.

Because you are loading all `ParentClass`es and including their related `ListItem`, you end up with all `ListItem`s loaded into memory (because every `ListItem` is associated with a `ParentClass`). Because EF is fixing up all the navigation properties, you end up with the full tree of `ListItem` nodes wired up.
