### ISSUE TITLE
Project 'Default' is not found.

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#5856]
### Steps to reproduce

Add-Migration XXXXXXX
### The issue

Project 'Default' is not found.
### Further technical details

No other logs or anything
just Project 'Default' is not found.

EF Core version: 1.0.0-rc2-3002702
Operating system: 
Visual Studio version: 2015

**Comment by bricelam** [comment]
I've seen this before too. NuGet's Package Manager Console gets into a bad state. Restart VS and try again.

**Comment by rowanmiller** [comment]
We are confident this is the issue @bricelam described. Feel free to reply if it is not.

**Comment by Tameshiwari** [comment]
Well working with Visual Studio 2015 Enterprise and starting a new Asp.Net Core + EF Core project often feels like dealing with an ol' lawn mower... sometimes it would start like magic sometimes it wouldn't... We then try to proceed tryig to restore everything through **dotnet restore** cmd expecting it would help solve the issue and Here we go again... So guess we have to deal with it as it seems a bit unstable ... Now as for the Project 'Default' is not found. issue... that once happened to me before I realised  the Default Project droplist was blank... Aaaaah no wonder why... just selected the name of the application and ooooh guess what? It worked... :)

**Comment by cirenep** [comment]
I just got this error all of a sudden too, even after rebooting VS 2015. Everything worked fine before.

**Comment by bricelam** [comment]
Select a project from the drop down list in NuGet Package Manager. I've been seeing this a lot more lately too.

**Comment by cirenep** [comment]
I reinstalled NuGet PMC and now it works. Go figure.

**Comment by Kriyainc** [comment]
Restarting VS worked for me, using VS2017

**Comment by GeorgeBushRekt** [comment]
This is still an issue in vs2017, please re-open and fix.

**Comment by bricelam** [comment]
@GeorgeBushRekt Could you file an issue on [NuGet/Home](https://github.com/NuGet/Home/issues/new) with the steps to reproduce it?

**Comment by bricelam** [comment]
I vaguely remember something like moving a project to a different solution folder causes it to fail, but I may be remembering wrong.

**Comment by touhidulfahim** [comment]
Select Project From Dropdown 
![image](https://user-images.githubusercontent.com/24824421/45602359-9710cf00-ba3e-11e8-86f8-83016bd2c6e1.png)

**Comment by MelbourneDeveloper** [comment]
@bricelam @rowanmiller I'm still experiencing this issue in Visual Studio 2019 (16.4.4). I've tried Git clean and restart VS several times. There is no longer a "Default project" drop down. Pretty stuck on this one. Add-Migration has worked several times, but it just stopped working today.

**Comment by bricelam** [comment]
Close the Package Manager Console window before restarting VS
