### ISSUE TITLE
Second Level Cache

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [dotnet/efcore#5858]
I'm trying to find information about (distributed) second level caching for EF Core. Are there any thoughts, plans, guidance or solutions as of yet?

**Comment by rowanmiller** [comment]
There is nothing available yet. Putting this on the backlog to possibly tackle in a future release. This would also be a good candidate for a third part extension.

**Comment by bjorn-ali-goransson** [comment]
Thanks for the update. Yes, maybe something can be built with Akka.NET:s
clustering functionality ...

2016-06-27 19:49 GMT+02:00 Rowan Miller <notifications@github.com>:

**Comment by VahidN** [comment]
I've ported my [EFSecondLevelCache](https://github.com/VahidN/EFSecondLevelCache) to .NET Core. Give it a try.
[https://github.com/VahidN/EFSecondLevelCache.Core](https://github.com/VahidN/EFSecondLevelCache.Core)

**Comment by dmitryvk** [comment]
As far as I know, correct implementation of 2nd level cache requires tighter integration between transactions and DbContext than currently is present. Cache needs to be invalidated _only_ after transaction has committed (otherwise there's a race condition between cache invalidation & cache repopulation). There, invalidating cache from override of SaveChanges method is a wrong way of implementing 2nd level cache invalidation/update.

I suppose that adding events/extension points around transaction begin/commit/rollback is a necessity for 3rd-part implementations.

**Comment by ajcvickers** [comment]
After reviewing this issue we are of the belief that a second-level cache could be implemented outside of EF Core, with EF Core plugging into as needed. Hopefully, this external second-level cache can be built using already available and tested caching implementations. We don't plan to implement a second-level cache in the EF codebase at this time, so we are closing this issue. However, we would be happy to work with others in the community to add appropriate hooks as needed to allow and external cache to be used.

**Comment by erikj999** [comment]
Is there any guidance available for actually implementing a 2nd level cache?  For example, is it possible to achieve via extensibility points already in EF Core, or do we need to wrap EF Core with an outer query provider of some sort? Or both?  Thanks!

-Erik

**Comment by Deilan** [comment]
@VahidN You seem to have a solid experience in developing a second level cache for EF Core. Could you give some feedback to EF Core team on that topic?

**Comment by VahidN** [comment]
If you want to implement it using the upcoming `Interceptors` it can be something like this:
```csharp
using System;
using System.Collections.Generic;

public class MyEFCoreCachingInterceptor
{
    /// <summary>
    /// Will be executed before running the actual query against the database.
    /// </summary>
    /// <param name="rawSQL">Hash of the raw sql query will be used as a hash key.</param>
    /// <param name="involvedEntityTypes">
    /// Determines which entities are used in this LINQ query.
    /// This array will be used to invalidate the related cache of all related queries automatically.
    /// </param>
    /// <returns>Result of the query.</returns>
    public object OnQueryMaterializing(string rawSQL, IEnumerable<Type> involvedEntityTypes)
    {
        // TODO: We need a query hint here too. where is it comming from? (stacktrace, method name, ...?)

        // Compute the hash of the rawSQL and use it as the hash key.
        // Fetch its result from the cache.
        return null; // If it returns null, fetch the actual result from the database, otherwise use it as is and don't query the database.
    }

    /// <summary>
    /// Will be executed after running the actual query against the database.
    /// </summary>
    /// <param name="rawSQL">Hash of the raw sql query will be used as a hash key.</param>
    /// <param name="involvedEntityTypes">
    /// Determines which entities are used in this LINQ query.
    /// This array will be used to invalidate the related cache of all related queries automatically.
    /// </param>
    /// <param name="queryResult">Result of the Materialization.</param>
    public void OnQueryMaterialized(string rawSQL, IEnumerable<Type> involvedEntityTypes, object queryResult)
    {
        // TODO: We need a query hint here too. Where is it comming from? (stacktrace, method name, ...?)

        // compute the hash of the rawSQL and use it as the hash key.
        // store the `queryResult` in the cache if it's necessary.
        // `involvedEntityTypes` should be used to determine the cache dependencies, to invalidate all of the realted cache queries at once.
    }

    /// <summary>
    /// Will be executed after commiting a transaction.
    /// </summary>
    /// <param name="involvedEntityTypes"></param>
    public void OnTransactionCommitted(IEnumerable<Type> involvedEntityTypes)
    {
        // Invalidate all of the cache entries which are dependent on any of the specified root keys (involvedEntityTypes), Otherwise the cache becomes stale.
    }
}
```

**Comment by DennisDyallo** [comment]
I tried VahidN's cache and I'm afraid it doesn't scale at all.
Any insert, update or delete operation invalidates the current cached DbSet and all related DbSet's even if the newly inserted/updated entity doesn't affect any of the cached query.
That is to say, if you have cached an entity (of type DbSet<Images>) by using the query Images.Where(e => e.Id == id) and you insert or update into that table, his library will invalidate all queries that are depended on that table, as well as foreign key tables - even though the new/updated document doesn't match any existing cached queries. 
In a busy application this will essentially lead to lots of useless cache invalidations and the end result is cache misses most of the time. 

Hopefully whichever (3rd party?) solution ends up in the framework won't have that limitation.

I think it's kind of weird EF doesn't come with this out of the box.

**Comment by Deilan** [comment]
Also had to drop VahidN's solution: it's not scalable, not documented, looks buggy (or, again, not obvious how to use in non-trivial cases - cause it's not documented) and it's author doesn't even accept issues. 

Looking forward to a different solution.

**Comment by SteffenMangold** [comment]
https://github.com/SteffenMangold/EntityFrameworkCore.Cacheable try it and give feedback please. :) I created it because of the same problems you all have.

**Comment by kwangholee3esi** [comment]
> https://github.com/SteffenMangold/EntityFrameworkCore.Cacheable try it and give feedback please. :) I created it because of the same problems you all have.

Hi SteffenMangold, I'm trying your solution but I wonder how to invalidate cache entries ?

**Comment by xsoheilalizadeh** [comment]
@VahidN released a new [implementation](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor) of second-level cache, give it a try.

**Comment by RyanThomas73** [comment]
The [EFSecondLevelCacheInterceptor](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor) implementation of VahidN is compact, simple, and automatically handles cache invalidation.

But the performance gains don't seem likely to be as significant since the hook is lower in the pipeline. It caches the DbDataReader response but EF Core still has to process that and hydrate new objects every time.

A solution that combines the automatic cache invalidation features but hooks into the pipeline higher and doesn't need to re-hydrate new objects every time would be nice.

**Comment by douglasg14b** [comment]
Why is this closed as not planned? This seems like a fairly core feature to have :/
