### ISSUE TITLE
MaxLength takes precedence over StringLength in EF6, but not in EF Core 

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#5865]
``` C#
private class MaxLengthWithLengthAnnotationClass
{
    public int Id { get; set; }

    [StringLength(500)]
    [MaxLength(30)]
    public string PersonFirstName { get; set; }

    [MaxLength(30)]
    [StringLength(500)]
    public string PersonLastName { get; set; }
}
```

Both properties get max length 30 in EF6, but get 500 in EF Core. (It's not clear if this is deterministic or not in EF Core.)

**Comment by smitpatel** [comment]
The order in which those conventions are added will determine the precedence. Last one will win.
https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs#L45
