### ISSUE TITLE
RTM - Wrong metadata in Release nuspec

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#5867]
### Steps to reproduce

Install EntityFramework.Core via NuGet UI in VS 2015
### The issue

Expect owners and authors in Nuspec (and thus UI) NOT to be the package name, but something like: Microsoft

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
<id>Microsoft.EntityFrameworkCore</id>
<version>1.0.0</version>
**<authors>Microsoft.EntityFrameworkCore</authors>**
**<owners>Microsoft.EntityFrameworkCore</owners>**
```
### Further technical details

EF Core version: 1.0.0
Operating system: 
Visual Studio version: (e.g. VS 2012 Update 2, Nuget 3.4.4)

**Comment by rowanmiller** [comment]
Looks like this applies to all RTM packages from ASP.NET Core and EF Core. I'm not sure if this was intentional cc @Eilon @danroth27 to confirm.

**Comment by Eilon** [comment]
That is most definitely weird.

**Comment by Eilon** [comment]
The owner should end up being correct because the NuGet gallery overwrites whatever you put in there anyway. But it appears something in the build system is messing up the author.

**Comment by Eilon** [comment]
@pranavkm any idea on this? It appears to have happened for all the packages we build...

**Comment by BrennanConroy** [comment]
Probably happened when we switched from RC1 build script to RC2 build script

**Comment by BrennanConroy** [comment]
Oh, looks like it was DNX that was setting the Author and Owner https://github.com/aspnet/dnx/blob/199bc294b6c0958336a4a6d5c9eb5b9d31582fa2/src/Microsoft.Dnx.Tooling/Building/BuildManager.cs#L428-L445

**Comment by BrennanConroy** [comment]
I think we need to change KoreBuild to set the NUGET_AUTHOR environment variable https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/dotnet/commands/dotnet-pack/PackageGenerator.cs#L364-L381

**Comment by Eilon** [comment]
And we need to add a package verifier rule as well. I logged https://github.com/aspnet/DnxTools/issues/72 to add a rule.

**Comment by rowanmiller** [comment]
Closing out this one in the EF repo, @BrennanConroy do you want an issue filed somewhere else to deal with the build changes?

**Comment by BrennanConroy** [comment]
Filed https://github.com/aspnet/KoreBuild/issues/92
