### ISSUE TITLE
how to convert  C# complex type to json field into PostgreSQL Database.

### ISSUE THREAD

**Issue by netcore-jroger** [dotnet/efcore#5868]
as the title says above. any body can help me ?
I'm used "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0-rc2-release1"
sample code:

``` C#
    public class TestInfo
    {
        public int Id { get; set; }

        public string Name { get; set; }

        [Column(TypeName = "json")]
        public Address Addr { get; set; }
    }

    public class Address
    {
        public string One { get; set; }

        public string Two { get; set; }
    }
```

table stracture:

``` sql
CREATE TABLE public."TestInfo"
(
  "Id" integer NOT NULL DEFAULT nextval('"TestInfo_Id_seq"'::regclass),
  "Name" character varying(50),
  "Addr" json,
  CONSTRAINT "PK_TestInfo" PRIMARY KEY ("Id")
)
```

**Comment by natemcmaster** [comment]
@Oger-Me I don't have an answer for your question (maybe someone else will), but FYI the PostgreSQL provider is developed in a separate project. See https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL

cc @roji

**Comment by smitpatel** [comment]
see #242

**Comment by rowanmiller** [comment]
Currently you would need to have a property that represents the JSON string, which is mapped to the database column. The complex type would then just be a façade over the JSON property (which could be private). 

We have captured this idea as part of https://github.com/aspnet/EntityFramework/issues/246 (complex/value type support):

> When doing this we should consider different strategies for how the data is stored. In EF6 we had a column in the parent table for each property in the complex type. Another strategy that folks may want to chose if serializing the data as JSON/XML etc. (see #3486)

**Comment by Oger-Me** [comment]
@rowanmiller @natemcmaster @smitpatel  thank you.

**Comment by roji** [comment]
@Oger-Me, as @natemcmaster says this issue belongs in the [Npgsql provider repo](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL). This scenario should be supported without any hassle, if you've encountered an issue please post more details in a new issue.

**Comment by Oger-Me** [comment]
@roji Thanks.
