### ISSUE TITLE
Add Badge / Link to Entity Framework Core SQL Server to Main GitHub README

### ISSUE THREAD

**Issue by ryanelian** [dotnet/efcore#5873]
Finding the NuGet Package requires some digging through the documentation.

https://docs.efproject.net/en/latest/ 
to https://docs.efproject.net/en/latest/providers/index.html 
to https://docs.efproject.net/en/latest/providers/sql-server/index.html 
to https://docs.efproject.net/en/latest/platforms/full-dotnet/index.html 
to https://docs.efproject.net/en/latest/platforms/full-dotnet/existing-db.html 
then scroll down until you find the `Install-Package Microsoft.EntityFrameworkCore.SqlServer`

Can we have direct link to https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer in the main README? Perhaps using something like http://shields.io/ to display links to common Entity Framework database providers / toolings packages badges that hyperlinks to the web page.

**Comment by rowanmiller** [comment]
Agreed that we can add a note about installing provider to https://docs.efproject.net/en/latest/ too

**Comment by ryanelian** [comment]
Awesome!

Congrats on release btw! :+1:
