### ISSUE TITLE
Add Raw SQL queries feature for Un-mapped types

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/efcore#5880]
What are your thoughs about this feature? Are you planning implementing it? It is a very usefull tool.

`var myList= ctx.Database.SqlQuery("Select ...").ToList<UnMappedModel>();`

[efcore-vs-ef6](https://docs.efproject.net/en/latest/efcore-vs-ef6/features.html)

**Comment by gdoron** [comment]
It's in the backlog.
I don't the time looking for the issue addressing this.

**Comment by rowanmiller** [comment]
Here is the issue tracking it https://github.com/aspnet/EntityFramework/issues/1862. We totally agree it is very useful and it is on the list of the critical features we need to add - of course there are quite a few features on that list, so it may not get implemented immediately.
