### ISSUE TITLE
One-to-many add() collection problem EF7

### ISSUE THREAD

**Issue by iXmonvi33** [dotnet/efcore#5882]
Hey,
The issue like in a tittle. Could u tell me guys how it's supposed to be done correctly in EF7 ?

I used:

_context.Users.Include(p =>  await _userManager.FindByIdAsync(HttpContext.User.GetUserId()).Result);

Raw data 
![sdsdd](https://cloud.githubusercontent.com/assets/19226186/16416626/74c0e630-3d43-11e6-866a-f2479bdf61e9.png)

I think the collection should be "Count = 0" not NULL.

Thanks for some advices.

I found solution but it sucks ;/

 if (user.Auction == null)
      user.Auction = new List<Auctions> { _auction }; // its working but looking bad
else
      user.Auction.Add(_auction); //when i use it NULL exeption
                            }

**Comment by rowanmiller** [comment]
I think you want: `_context.Users.Include(u => u.Auction);`

I surprised that query you posted even executes 😄
