### ISSUE TITLE
Fresh clone and build of Release branch failing due to netcoreapp1.0

### ISSUE THREAD

**Issue by joshcomley** [dotnet/efcore#5885]
### Steps to reproduce

Install the latest RTM SDK and tooling preview 2, clone EntityFramework, change to `Release` branch, compile
### The issue

Compile fails because a number of the projects use `netcoreapp1.0` and various dependencies don't support `netcoreapp1.0`:

https://imgur.com/xdc7j0r
### Further technical details

EF Core version: 1.0.0-rtm
Operating system: Windows 10
Visual Studio version: VS2015 Update 3

Other details about my project setup:

**Comment by smitpatel** [comment]
If you are trying to build release branch, it should not restore preview3 & rc4 packages. What are your package feeds?

**Comment by joshcomley** [comment]
There was a bug in the upgrade process to the latest RTM of everything that even with uninstalls as recommended left some dirs over that was messing everything up:

http://i.imgur.com/P4OArlQ.png

This was a non-EF issue so I'll close, thank you for your reply :)
