### ISSUE TITLE
String comparsion in queries throws errors after update from RC2 to RTM

### ISSUE THREAD

**Issue by vzaoral** [dotnet/efcore#5895]
### Steps to reproduce

Hi! I have class TEstateAdvertiser generated by Scaffold-DbContext command after update to RTM:

```
class TEstateAdvertiser
{
public string Www { get; set; }
public string Info { get; set; }
public bool Visible { get; set; }
...
}
```
### The issue

When I call

```
TEstateAdvertiser advertiser = DbContext.tEstateAdvertiser.Where(
                x => x.Visible && !string.IsNullOrEmpty(x.Info) && !string.IsNullOrEmpty(x.Www)).FirstOrDefault();
```

I got

```
Exception message:  The data types ntext and nvarchar are incompatible in the not equal to operator. 
```

This query was working before update from version RC2. Am I missing something? Thank you for your advice.
### Further technical details

EF Core version: 1.0.0
Operating system: WIN10
Visual Studio version: VS 2015 Update 3

**Comment by rowanmiller** [comment]
This is a limitation of SQL Server, you can not do equality comparison on an `ntext` column. I assume that `Info` is mapped to an `ntext` column? This would have worked in RC2 because it would have been evaluated on the client - i.e. all the data was pulled into memory and then the filter was applied.

**Comment by vzaoral** [comment]
Hello @rowanmiller, you're right, type of `Info` column is `nvarchar(MAX)`. After change data type of column (i.e. `nvarchar(1024)`) query is working. So I assume there is no other way to query column of type `ntext` - just evaluate query in memory on the client or change column type. 
Thank you.

**Comment by rowanmiller** [comment]
Correct. Closing this one out as I don't think there is anything to do on the EF side - this is just a limitation of SQL Server.
