### ISSUE TITLE
Microsoft.NETCore.UniversalWindowsPlatform 5.2.0 is not available

### ISSUE THREAD

**Issue by mvermef** [dotnet/efcore#5902]
Attempt to add this and it will fail... No compatibility 
Search Nuget for Microsoft.NETCore.UniversalWindowsPlatform 5.1 is the only current package on nuget
### The issue

Microsoft.NETCore.UniversalWindowsPlatform >= 5.2 is NOT in Nuget as RTM.  Should it be?
### Question

Can't seem to find whom controls this package since it should have been updated for 1.4 of the UWP tools release if I am not mistaken?  Noticed there was a reference searching for that it has been unlisted with Nuget.....  Kinda causes problems for countless things include EFC

**Comment by natemcmaster** [comment]
It's still available, but you have to specify the version explicitly.
`PM> Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5.2.0`

cc @ericstj @weshaggard do you know why was this package unlisted?

**Comment by mvermef** [comment]
https://github.com/dotnet/corefx/issues/9743

nvm found the reason....  there is an issue with it.

**Comment by mvermef** [comment]
Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5.2.0  
and throws about 300 errors...

> > Install-Package : System.Net.WebHeaderCollection 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Net.WebSockets 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Net.WebSockets.Client 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Text.Encoding.CodePages 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.AppContext 4.1.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Collections.Immutable 1.2.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Globalization.Calendars 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Globalization.Extensions 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.IO.Compression.ZipFile 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.IO.FileSystem 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.IO.FileSystem.Primitives 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.IO.UnmanagedMemoryStream 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Numerics.Vectors 4.1.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Reflection.DispatchProxy 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Reflection.Metadata 1.3.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Reflection.TypeExtensions 4.1.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Runtime.Handles 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Security.Claims 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Threading.Tasks.Dataflow 4.6.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Security.Cryptography.X509Certificates 4.1.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Reflection.Emit 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Xml.XmlDocument 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Buffers 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Diagnostics.DiagnosticSource 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Threading.Tasks.Extensions 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Threading.Overlapped 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Security.Cryptography.Algorithms 4.2.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Security.Cryptography.Encoding 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Security.Cryptography.Primitives 4.0.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Collections.NonGeneric 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : System.Collections.Specialized 4.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> At line:1 char:1
> + Install-Package Microsoft.NETCore.UniversalWindowsPlatform -Version 5 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

>

**Comment by natemcmaster** [comment]
This is probably an issue with your what is in your project.json already. Can you share its contents?

**Comment by mvermef** [comment]
create a new UWP, that is the contents of the project.json.   Note:  I did have to more or less restore and start over with the Update3 mess...There are still issues with it...

**Comment by MMalikKhan** [comment]
@natemcmaster @mvermef  5.2.0 was available on nuget 24 hours ago, i was able to install and when i run the app it just crash the Visual studio. I tried couple time same issue. Later in the afternoon when i checked it was removed and the only one which is available is 5.1.0. I am actually looking forward to update my currently deployed UWP app which uses EF7Rc1 and 5.1.0 to EF1 RTM. and i see there is dependency on EF1 to have 5.2.0 as minimum requirement.And, its not available at the moment, even if it is available then its not working .. what you suggest at the moment.How can i upgrade to latest version of EF from RC1? I already got the VS update 3 yesterday.

**Comment by natemcmaster** [comment]
I've tested this again and haven't encountered errors when editing project.json directly to specify the version. Attempting to install via PMC may cause errors, but that is a usability issue for NuGet. You can still use the UWP package version 5.2.0 even though it is "unlisted". https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/5.2.0/.

```json
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

I'm closing as there isn't any action to take in EF, but feel free to continue discussing.

**Comment by natemcmaster** [comment]
Finally got more news on this. 5.2.0 was delisted because it has known issues. See https://social.msdn.microsoft.com/Forums/en-US/e766a904-7346-4f76-bad2-852d3b301b0e/known-issue-version-52-of-microsoftnetcoreuniversalwindowsplatform-delisted-all?forum=Win10SDKToolsIssues

See https://github.com/aspnet/EntityFramework/issues/5570#issuecomment-230063880
