### ISSUE TITLE
Issue with base asp.net core project and ef

### ISSUE THREAD

**Issue by JarredMiles** [dotnet/efcore#5903]
On a brand new project I Get the following message when doing "dotnet ef database update"

> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>    at Microsoft.Extensions.DependencyInjection.NpgsqlEntityFrameworkServicesBuilderExtensions.AddEntityFrameworkNpgsql(IServiceCollection services)
>    at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__1(Int64 k)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
>    at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`1..ctor(DbContextOptions options)
>    at Zeroprox.Web.Data.ApplicationDbContext..ctor(DbContextOptions`1 options) in C:\Users\chaot\Documents\Projects\Zeroprox\slnZeroproxWebsite\src\Zeroprox.Web\Data\ApplicationDbContext.cs:line 14
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.EntityFrameworkCore.Design.DbContextOperations.<>c__DisplayClass13_2.<FindContextTypes>b__6()
>    at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
>    at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
> Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

The only thing that I changed in the project is that I added the npgsql nuget. I will attach the project that I made the other night.
[slnZeroproxWebsite.zip](https://github.com/aspnet/EntityFramework/files/340041/slnZeroproxWebsite.zip)

**Comment by rowanmiller** [comment]
Npgsql hasn't released their RTM compatible packages yet, so you are ending up with a mix of RTM/RC2 packages (which are not designed to work together). The packages should be up shortly cc @roji

**Comment by rowanmiller** [comment]
Npgsql just published their 1.0.0 package, so you should be good to go now

**Comment by JarredMiles** [comment]
Thanks! I I'll give it a go!
