### ISSUE TITLE
In memory ReverseEngineer API

### ISSUE THREAD

**Issue by stofte** [dotnet/efcore#5904]
Could the ReverseEngineerAsync API could be extended to allow in-memory generation only? I'm interetested in the database source for on-the-fly code-generation purposes, and not for inclusion in a file-based project.

Looking at the tests for guidance, they seem to all use internal mechanisms to get this done (eg ConfigureDesignTimeServices to inject InMemoryFileService).

Thanks!

**Comment by rowanmiller** [comment]
I don't think this is something we would really add as a first class feature, but you could reuse the internal components if you wanted to. They are just in a `.Internal` namespace, but are still public. The namespace just identifies them as something we may break in future releases.
