### ISSUE TITLE
Allow cascade delete of principal in 1:1 relationship when dependent deleted

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#5910]
See #5871 for model and discussion.

The idea is that the conceptual parent/child relationship in the domain model is different from the actual parent/child as defined by type that contains the foreign key. In such a case, it may be useful to the app to have the principal deleted when the one and only one dependent for that principal is deleted, especially if the presence of the FK is not even apparent due to shadow state. However, note that a relational database would not honor this so it would only work correctly if both the principal and dependent were loaded.

**Comment by rowanmiller** [comment]
We'd only consider this if we saw significant demand for it
