### ISSUE TITLE
Install EF7 in portable (and cross platform) library

### ISSUE THREAD

**Issue by SamuelLioult** [dotnet/efcore#5914]
Hi,
I would like to install EF7 (Microsoft.EntityFrameworkCore) packages in a portable class library for UWP. But, to anticipate futur changes in my project, I chose the cross platform template of portable library class (for Android, iOS and UWP of course).
My issue is when I try to install the nugget package. I get this error:

```
Could not install package 'Microsoft.EntityFrameworkCore 1.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the 
package author.
```

Thanks
Samuel
### Further technical details

EF Core version: 1.0.0
Visual Studio version: VS Community 2015 Update 3
NuGet version : 3.4.4

**Comment by rowanmiller** [comment]
@bricelam @natemcmaster this is expected right? We are focused on netstandard rather than portable

**Comment by natemcmaster** [comment]
Correct. We don't support the Xamarin.ios or Xamarin.Android targets. The current thinking is to wait for Xamarin to support .NET Standard.

@SamuelLioult currently, EF Core only supports .NET Standard 1.3 and .NET Framework 4.5.1. Xamarin doesn't yet support either of these target frameworks.

**Comment by SamuelLioult** [comment]
Ok, thanks for your time.
So, I think you can close this issue.
