### ISSUE TITLE
 Exception when calling "OpenFile" width "1"  arguments

### ISSUE THREAD

**Issue by Alados** [dotnet/efcore#5915]
### Steps to reproduce

I try add migrations to my project, and when resolve many errors width assembly, they were work. But with error.
### The issue

Add-migration : Исключение при вызове "OpenFile" с "1" аргументами: "Параметр задан неверно. (Исключение из HRESULT: 0x80070057 (E_INVALIDARG))"
строка:1 знак:1
- Add-migration ForeignKeyForCoordinate
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
  - FullyQualifiedErrorId : ComMethodTargetInvocation,Add-Migration
### Further technical details

EF Core version: 1.0.0
Operating system: windows 8
Visual Studio version: VS 2015

Other details about my project setup:
Migration create and may update database, but enter exception
Sorry for exception message on russian=)

**Comment by rowanmiller** [comment]
Do you have Visual Studio 2015 Update 3 and the [latest version of PowerShell](https://www.microsoft.com/en-us/download/details.aspx?id=40855) installed? I'm thinking this is probably due to an older NuGet client and/or older PowerShell version.

**Comment by Alados** [comment]
I try update, but installer show this "0x80096002: The certificate for the signer of the message is invalid or not found."

**Comment by rowanmiller** [comment]
We haven't been able to reproduce to this issue. It sounds like you are probably already running PowerShell 3.0 and you are right, that installer I pointed you too won't work on Windows 8 as the path is to upgrade to 8.1 in that scenario. Can you confirm that you have VS 2015 Update 3 installed?

BTW the exception looks like it probably happens right at the end of the Add-Migration process, when we try to open the file to display it. Based on that, the migration is probably correctly scaffolded and added to your project. So as a workaround, you should just be able to ignore this error and open the file yourself to look at what was scaffolded.

**Comment by Alados** [comment]
Yes, I have VS 2015 Prof update 3. 
Ok, thank. May closed issues.

**Comment by RogovArtem** [comment]
I have same problem...
