### ISSUE TITLE
"Include" question

### ISSUE THREAD

**Issue by dbrezoev** [dotnet/efcore#5918]
How can I make EF Core to work like previuos versions (without explicitly to Include all navigation props). 
My problem is that I have a tree structure of Nodes. Every Node has collection of Nodes which have collection of Nodes etc. I want to load them with EF. I write something like `this.context.Nodes.Include(n => n.ChildNodes)` but it loads only first level of children. How can I load all levels until they finish? 

eg. How to `.ThenInclude(n => n.ChildNodes)` recursively ?

**Comment by rowanmiller** [comment]
@dbrezoev there isn't a way to specify recursive includes (at least not yet). When you talk about it working in previous versions, I assume you were using Lazy Loading in EF6.x?

One possibility, if you are loading all nodes, is simply to do a `context.Nodes.ToList()`. Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance. So even if you don’t explicitly include the data for a navigation property, the property may still be populated if some or all of the related entities are loaded.

**Comment by maumar** [comment]
@dbrezoev you can also use context.Nodes.Include(n => n.ChildNodes).ThenInclude(n => n.ChildNodes).ThenInclude(...) to fetch multiple levels of navigations
