### ISSUE TITLE
FK created also as unique index

### ISSUE THREAD

**Issue by sanalbakis** [dotnet/efcore#5922]
Hi,

after I updated the app from rc1 to rtm, I get now another problem. I think, I dont need to say it worked well on rc1.

Add-Migration Initial creates the migration file, but all the foreign keys are also unique indexes. 

Migration-file:

```
migrationBuilder.CreateTable(
      name: "BaseObject",
      ....
   constraints: table =>
    {
           table.ForeignKey(
                    name: "FK_BaseObject_ObjectType_ObjectTypeId",
                    column: x => x.ObjectTypeId,
                    principalTable: "ObjectType",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
     }
```

...

```
  migrationBuilder.CreateIndex(
            name: "IX_BaseObject_ObjectTypeId",
            table: "BaseObject",
            column: "ObjectTypeId",
            unique: true);
```

Below you can see my models and builder:

BaseObject.cs

```
   public class BaseObject : IEntity
   {
         public long Id { get; set; }

         public long BaseObjectId { get; set; }

         public long ObjectTypeId { get; set; }
         public ObjectType ObjectType { get; set; }
         .....
   }
```

ObjectType.cs 

```
public class ObjectType
{
    public long Id { get; set; }

    public string Name { get; set; }
}
```

and my builder:

```
builder.Entity<BaseObject>(x =>
{
 ....
  x.HasOne(p => p.ObjectType)
                .WithOne()
                .HasPrincipalKey<ObjectType>(p => p.Id)
                .HasForeignKey<BaseObject>(p => p.ObjectTypeId)
                .HasConstraintName("FK_BaseObject_ObjectType_ObjectTypeId");
  .....
 }
```
### The issue

Exception message:
"Eine Zeile mit doppeltem Schlüssel kann in das dbo.BaseObject-Objekt mit dem eindeutigen IX_BaseObject_ObjectTypeId-Index nicht eingefügt werden. Der doppelte Schlüsselwert ist (24).
Die Anweisung wurde beendet."

English (got the error in SQL):
Cannot insert duplicate key row in object 'dbo.BaseObject' with unique index 'IX_BaseObject_ObjectTypeId'. The duplicate key value is (24).
The statement has been terminated.
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10 X64
Visual Studio version: VS2015

**Comment by ajcvickers** [comment]
@sanalbakis The HasOne() WithOne API that you are using sets up a 1:1 relationship between the two entities. This means that each ObjectType can have at most one BaseObject associated with it. Migrations is creating the unique index on the FK column to enforce this on the database side.

**Comment by sanalbakis** [comment]
@ajcvickers thank you for your answer. How can I do that without any unique index?

For example, CreatedById is also same with the User-BaseObjectId. I need to make here only foreign-key, not a unique index.

**Comment by ajcvickers** [comment]
@sanalbakis Maybe you want a one to many relationship instead? If you really want 1:1 and don't want the unique index then edit your migration file and remove it. However, that means the database will not enforce the 1:1 relationship, and if there are duplicate values in the FK column (as there seem to be from the exception you posted) then you will get undefined behavior in your application whenever you do queries or updates which will likely result in corrupt data.

I would suggest reading the documentation about relationships here: https://docs.efproject.net/en/latest/modeling/relationships.html

**Comment by sanalbakis** [comment]
@ajcvickers , is it a new feature?Untill (incl.) RC1 there were no unique indexes. I see now a solution that I have to remove all navigation properties and foreign keys or is there a way to make a foreign key without unique index?

**Comment by ajcvickers** [comment]
@sanalbakis If you want a foreign key without a unique index, then create a one to many relationship. One to one means unique. One to many means not unique.

**Comment by sanalbakis** [comment]
@ajcvickers thank you for your answers. 

In this case I cannot create one-to-many.The navigation properties are not a list or collection. I think, I will remove all nav. properties. 

regards,

**Comment by ajcvickers** [comment]
@sanalbakis You can do WithMany() without a navigation property.

**Comment by sanalbakis** [comment]
@ajcvickers 
it has really worked! I didnt know that it also so working. Thank you so much!

**Comment by felixhayashi** [comment]
For the record, seems more appropriate to keep the relations as specified in the OP and then simply add

    modelBuilder.Entity<BaseObject>().HasIndex(b => b.ObjectType).IsUnique(false);

**Comment by f135ta** [comment]
> @sanalbakis If you want a foreign key without a unique index, then create a one to many relationship. One to one means unique. One to many means not unique.

The logic behind that thinking is a little odd... I get the solution, add IsUnique, but, thats some pretty abstract thinking to get to the point where ^^ is considered the correct way to implement this functionality..
