### ISSUE TITLE
High level architecture/design document of Reverse Engineering...

### ISSUE THREAD

**Issue by devendra-bhadauria** [dotnet/efcore#5928]
Hi,

I wasn't sure where to post it, in SO or here as it's more like seeking the right information rather than issue. So here it's,

In the future, we may plan to support reverse engineering from our EF Core support (an EF Core Provider). Could you please share some links\docs that talk about its architecture/design, extending it from other provider's perspective? The high level details of design APIs, what they do, and how they interconnect?
If we follow the same roadmap, it'd integrate well with VS tooling e.g. GUI support in the future or we need to restructure it differently (i hope not..).

Thanks,
Devendra

**Comment by ErikEJ** [comment]
Feel free to look at the source code of the implementations for SQL Server, SQLite and SQL Server Compact

**Comment by devendra-bhadauria** [comment]
At least, we could confirm that GUI support will be built on top of current command line interface incrementally for VS Tooling? I know it's commonplace but would like to know from roadmap perspective.

**Comment by ErikEJ** [comment]
Yes, it will

**Comment by rowanmiller** [comment]
@devendra-bhadauria The command line is just a thin shim on top of some core components. The UI will be built on top of these same core components. There will be some additional API surface to support the UI - such as getting a list of tables/schemas to populate a checkbox list in the UI.

**Comment by devendra-bhadauria** [comment]
Thanks Rowan, that makes sense!

I hope heavy lifting would be done by Core design GUI, and the provider specific (design) extension of API surface area will be minimal. As VS tooling would be more accessible/open to MS side of EF Core integration...

**Comment by rowanmiller** [comment]
@devendra-bhadauria yes, that is what we are planning. Closing this out now as I think we have answered the question.
