### ISSUE TITLE
Zero/One to Many Single Navigation issue with FK Constraint

### ISSUE THREAD

**Issue by Jargon64** [dotnet/efcore#5931]
First off, sorry if this has been posted before, I have been unable to find anything specific to my issue. I'm trying to create an optional single navigation relationship where the foreign entity data is populated first.

```
public class Sensor
{
    [Key]
    [Required]
    public Guid Id { get; set; }

    [Required]
    [Column(TypeName = "VARCHAR(8)")]
    [StringLength(8, MinimumLength = 8)]
    public string Serial { get; set; }

    public virtual ICollection<SensorData> Data { get; set; }   
}
```

```
public class SensorData
{
    [Key]
    [Required]
    public Guid Id { get; set; }

    [Required]
    [Column(TypeName = "VARCHAR(8)")]
    [StringLength(8, MinimumLength = 8)]
    public string Serial { get; set; }
}
```

```
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    builder.Entity<Sensor>().HasIndex(s => s.Serial);
    builder.Entity<SensorData>().HasIndex(sd => sd.Serial);

    builder.Entity<Sensor>()
        .HasMany(s => s.Data)
        .WithOne()
        .HasForeignKey(sd => sd.Serial)
        .HasPrincipalKey(s => s.Serial)
        .IsRequired(false);
}
```

(I've included the indexes as I'm not sure if this is affecting the relation).

The sensor data is added first without a corresponding sensor (sensors are registered with the system at a later date), but with this single navigation relation in place an SQL Exception is thrown:

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_SensorData_Sensors_Serial". The conflict occurred in database "[REDACTED]", table "dbo.Sensors", column 'Serial'.
```

I've tried looking around how to properly do this or find someone else who has had my specific issue but haven't found anything. I've tried everything I think of but now I'm at a loss as how to proceed.

Is this a bug with EF or is it down to my implementation? I don't understand why the foreign key constraint is causing issues when the relation is not required. Any help or direction would greatly be appreciated!

**Comment by ajcvickers** [comment]
@Jargon64 When the relationship is not required it means that the FK value can be null. That is, you can have SensorData objects that are not associated with any Sensor. As soon as you set the FK to a value it means that the SensorData object is now associated with the corresponding Sensor. The database enforces this with a constraint, which is why you see the exception.

It's hard to know what to suggest without knowing your application requirements. You probably either need to either keep Serial set to null until the Sensor is created or use something other than Serial as the FK. You could also just remove the constraint from the database--for example, by removing it from the migration that you use to create the database. That might give you want you need, but it is quite unusual and I am not sure that everything in EF will work as expected when there are FK values in the database that do not have a corresponding PK value.

**Comment by smitpatel** [comment]
As @ajcvickers said,
>  When the relationship is not required it means that the FK value can be null. That is, you can have SensorData objects that are not associated with any Sensor.

I tried reproducing this though with given model and context, inserting `SensorData` works fine. The only case I hit the exception as above is inserting `SensorData` with fk property `Serial` set to something which does not exist in table `Sensors` column `Serial`. Regardless of relationship being required/non-required, inserting non-null data in fk column which doesn't exist in principal column violates foreign key constraint and exception is thrown by database server. By looking at the scenario, you should add `SensorData` without value for `Serial` set (default value is null) and when you add `Sensor`s later and assign `SensorData`s to them the `Serial` column in all `SensorData`s will be updated accordingly by EF.

Side note: The column `SensorData.Serial` is marked required using data-annotation and configuring relationship to be non-required sets fk property to be non-required. Hence annotation is unnecessary.

**Comment by Jargon64** [comment]
Thanks for your input guys. Based on what you have said I think I will need to create another field specifically for the FK (most likely `SensorId`) and have the `Serial ` as a pseudo-FK (as the `Serial ` in the `SensorData` dictates to the system what `Serial`s are available). Then add some logic to the app to fill in the `SensorId` when the relation should be enforced. Was hoping there was a way that this could be done in a more autonomous way but I guess it's not possible.
