### ISSUE TITLE
Powershell Migrations No Longer Recognized but CLI Commands are Working

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#5933]
I'm using VS2015 Update 3.

I have a project with a .NET Core class library that has an EFCore DbContext in it.

A second project is a test project that targets the core.

I originally created the migrations in the Package Manager Console by having the test project set as startup and PMC pointing to the context project.

That was fine.

I then tried out using the CLI commands with the --startup-project parameter and that worked also.

However, now in the same project, nor any other projects I have created from scratch, I can no longer use the powershell commands. They are all unrecognized.

You can see the project.json files in this repository which is the one I did originally use the powershell commands for creating and executing the migrations: https://github.com/julielerman/EFCoreNetStandard_RTM

Did I break something?

**Comment by natemcmaster** [comment]
You are probably hitting https://github.com/NuGet/Home/issues/3023. You can either add "M.EF.Tools" as a "dependency" or manually run `$env:USERPROFILE\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.0.0-preview2-final\tools\init.ps1` to initialize the PMC cmdlets.

**Comment by julielerman** [comment]
Thanks Nate. My github search fu was not up to par for this one. I'll go try that when I get back home.

**Comment by julielerman** [comment]
I didn't want to mess with project.json since it was so hard to get it right, so I ran init.ps1 in package manager and the migrations are there again. So yeah.. .preview tools. I get it. Thanks for showing me how to get it back for now. :)
