### ISSUE TITLE
Version strategy for providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#5937]
Now that 1.0.0 has been released, I'm wondering if you have any thoughts as to how providers such as Npgsql should be versioned. I guess it's a general question wherever there's a core and providers.

Should provider releases be synced with core releases (i.e. should I wait for an EFCore 1.0.1 release before releasing the 1.0.1 for the Npgsql provider)? The downside is that the provider no longer follows its own release schedule, and important/critical bugfixes get delayed.

On the other hand, if the provider releases in an independent way then versions numbers go totally out of sync, e.g. Npgsql version 1.2.3 works with EFCore 1.0.8 and above, which seems confusing for end users.

A hybrid approach might be good, i.e. release patch versions independently but sync on minor versions.

**Comment by rowanmiller** [comment]
Our recommendation would be:
* Always sync with the core packages on major versions, as they may contain breaking changes etc.
* Ideally, sync on minor versions, as they may light up new features and it helps folks understand which version of the package to use.
* Feel free to patch at whatever cadence works for you. We don't see any need to sync on these as we only make critical bug fixes.

**Comment by rowanmiller** [comment]
Closing as I think we have answered, but feel free to follow up with questions/suggestions/etc.
