### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite.Design SQLite dependency case issue 

### ISSUE THREAD

**Issue by thild** [dotnet/efcore#5956]
### Steps to reproduce

Add this dependencies to an Asp.Net Core 1.0 project.json

```
  "dependencies": {
    ...
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.0",
    "Microsoft.EntityFrameworkCore.SQLite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.0.0",
    ... 
  },
  "tools": {
    ...
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    ...
  },
```

run: dotnet ef migrations add testMigration

get: project.json(27,58): error NU1001: The dependency Microsoft.EntityFrameworkCore.Sqlite >= 1.0.0 could not be resolved.
Compilation failed.
### The issue

The case of Microsoft.EntityFrameworkCore.Sqlite package dependency in https://github.com/aspnet/EntityFramework/blob/master/src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json is wrong.
The correct case of package name is Microsoft.EntityFrameworkCore.SQLite.

Changing the case in project.lock.json solved the problem.

```
"Microsoft.EntityFrameworkCore.Sqlite.Design/1.0.0": {
   "type": "package",
   "dependencies": {
      "Microsoft.EntityFrameworkCore.Relational.Design": "1.0.0",
-------------------------
      "Microsoft.EntityFrameworkCore.SQLite": "1.0.0"
-------------------------
   },
   "compile": {
      "lib/netstandard1.3/Microsoft.EntityFrameworkCore.Sqlite.Design.dll": {}
   },
   "runtime": {
      "lib/netstandard1.3/Microsoft.EntityFrameworkCore.Sqlite.Design.dll": {}
   }
},
```

Please consider standardizing all sqlite names with same case.
I'm running on Linux, so case matters.
### Further technical details

EF Core version: (found in project.json or packages.config)
"Microsoft.EntityFrameworkCore": "1.0.0",
"Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final",
"Microsoft.EntityFrameworkCore.Relational": "1.0.0",
"Microsoft.EntityFrameworkCore.SQLite": "1.0.0",
"Microsoft.EntityFrameworkCore.Sqlite.Design": "1.0.0",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",

Operating system: 
OpenSUSE Tumbleweed (using dotnet for OpenSUSE 13.2)

Visual Studio version: (e.g. VS 2013 or n/a)
Visual Code 1.2.1

**Comment by rowanmiller** [comment]
Casing in the package dependency is actually consistent with the package we produce (they are both `Sqlite`. My guess is that if you change your project.json file to have the same casing as the package, the issue would disappear.

That said, package names should not be case sensitive, this is a known issue that the NuGet team is working to fix.

**Comment by thild** [comment]
Ok. My mistake. I figured out the problem. The path of the package in .nuget/packages is created based on the casing of dependencies in project.json. Thanks for the reply.
