### ISSUE TITLE
Asynchronous DB calls not working in Azure Elastic DB Pool

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5960]
We have code that works in our development environment.  Simple entity save:

```
            DbContext.Add(entity);
            await DbContext.SaveChangesAsync();
```

When we deployed this to an Azure App Service, connecting to our Elastic DB pool, this asynchronous call simply hung.  No exceptions thrown; the call simply never returned.  The Sql query didn't make it into the input buffer.

When we changed our "Save" code to use synchronous calls, everything worked fine.  
Conclusion: asynchronous saving is not working in Azure.  Unclear whether it's because of the App Service or the Elastic Db Pool or a combination of the two - but I'll leave that to you to figure out.  ;-)

**Comment by AndriySvyryd** [comment]
@shaulbehr Could you try this again using 1.1.0-preview1 ?
If still hangs could you make sure that your code doesn't call `.Wait()` on the result of the method that ends up calling `SaveChangesAsync()` ?

**Comment by AndriySvyryd** [comment]
Closing this as there hasn't been a response. Feel free to reopen if the issues persists with the latest version.
