### ISSUE TITLE
Null string parameter operations throwing NRE

### ISSUE THREAD

**Issue by Muchiachio** [dotnet/efcore#5967]
### Steps to reproduce

``` C#
using (DbContext context = new Context())
{
    String title = null;
    context.Set<Entity>().Where(entity => entity.Title == title.ToLower()).ToArray();
}
```
### The issue

Using `nullString.ToLower()` or other operations on null string results in NRE exceptions on evaluation, this worked in EF6 and RC2.

```
An exception was thrown while attempting to evaluate a LINQ query parameter expression.
Object reference not set to an instance of an object.
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 7 Ultimate x64
Visual Studio version: 2015 Update 3

**Comment by rowanmiller** [comment]
Agreed, we are executing `title.ToLower()` to get the value to compare to and since it is null you get an exception. This is how .NET works and not specific to EF.
