### ISSUE TITLE
Warnings in VS Code Result From Auto-Generated Code

### ISSUE THREAD

**Issue by robbpriestley** [dotnet/efcore#5974]
### Steps to reproduce
- Using **Visual Studio Code** 1.2.1 (although this issue has been around since <0.x)
- Add a new model definition (say a simple class with an ID and several string properties)
- Create a migration (`dotnet ef migrations add initial`)
- Update the database (`dotnet ef database update`)
- EF auto-generates code and places it in the **Migrations** subdirectory
### The issue
- Auto-generated code produces compiler warnings in **Visual Studio Code** which must be hand-corrected to achieve a clean compile. Non-critical, yes. Inconvenient, also yes. Suggest: detect requirements for inclusion of `using` clause and omit unless necessary.
### Common pattern

**20160704220827_initial.cs** 
`using System.Collections.Generic;`
Unnecessary using directive. [netcoreapp1.0]

**MyContextModelSnapshot.cs**
`using Microsoft.EntityFrameworkCore.Migrations;`
Unnecessary using directive. [netcoreapp1.0]
### Further technical details

EF Core version: 1.0.0-rc2-final
Operating system: OSX El Cap 10.11.5
Visual Studio version: Code 1.2.1

**Comment by rowanmiller** [comment]
To help with triage, here is how the warnings show up in VS Code
![image](https://cloud.githubusercontent.com/assets/4741851/16883207/b1369600-4a77-11e6-9421-8f65c794ebb2.png)

**Comment by rowanmiller** [comment]
BTW, worth noting that an actual compile of the project does not render any warnings (as expected):

![image](https://cloud.githubusercontent.com/assets/4741851/16883294/15ca6b96-4a78-11e6-9fd4-00fd30481b3e.png)

**Comment by rowanmiller** [comment]
Discussed in triage and concluded that we are not going to change this. Unnecessary `using` statements generally aren't considered a compiler warning/error for C# code. In fact, things like Visual Studio project templates, the 'Class' item template in VS, etc. include `using`s for things that aren't used but might be useful. When we originally shipped migration in EF4.3 we had logic to trim down usings but got feedback that it is good to have things like `System` imported, even if the scaffolded code doesn't actually need it.
