### ISSUE TITLE
How to realize the batch operation,update and delete

### ISSUE THREAD

**Issue by Seanxwy** [dotnet/efcore#5979]
How to realize the batch update and batch delete data??Don't need to query and then update

**Comment by rowanmiller** [comment]
Currently you would need to issue a raw SQL statement using `context.Database.ExecuteSqlCommand()` to run the command.

In the future, we plan to implement a set-based update/delete feature - https://github.com/aspnet/EntityFramework/issues/795.

**Comment by BruinY** [comment]
But there are no ExecuteSqlCommand 1.0 and now this method
