### ISSUE TITLE
How to implement TPC?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#5983]
Question for the team:

How do you implement Table Per Concrete Type (TPC) in EF7?
I found instructions for previous versions [here](http://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-3-table-per-concrete-type-tpc-and-choosing-strategy-guidelines), but the methods specified there aren't available in EF7.

**Comment by rowanmiller** [comment]
TPC is not yet implemented in EF Core, you can track the feature via https://github.com/aspnet/EntityFramework/issues/3170
