### ISSUE TITLE
In sqlite, when the model is changed, how to create a single table?

### ISSUE THREAD

**Issue by linqingfeng** [dotnet/efcore#5991]
hi,

We know that the use of Database.EnsureCreated () to create the database, but if when the model is changed, how to create the table?

We try to create a database from the logs to get created sql, but the feeling is not a good way, are there any good solution?

**Comment by rowanmiller** [comment]
Migrations is the way to incrementally change the schema as your model changes. I'm not sure what sort of app you are building, but here is an example of using it with a console app https://docs.efproject.net/en/latest/platforms/full-dotnet/new-db.html#create-your-model.

EnsureCreated is just a brute force way to create the schema, but there is no way to change it as your model evolves. It's designed for prototyping, testing, etc. where data does not need to be preserved. Your only option using this API is to drop the database and recreate it.
