### ISSUE TITLE
[question] Migrations with VSTS

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#5993]
Hi,
is there some documentation describing how to apply migrations on deploy using VSTS? I've seen this has been integrated in VS, and I'd like to do the same when deploying from VSTS. Please let me know if I should ask elsewhere.
Thanks!

**Comment by Tarig0** [comment]
Not exactly the answer to your question but since VSTS uses powershell the following should apply

http://stackoverflow.com/questions/38273482/how-to-use-ef-code-first-migration-to-generate-scripts-from-powershell

**Comment by bragma** [comment]
@Tarig0 thanks for your answer. It is in fact not exactly what I was looking for. Up to now I forced migrations using some code in "startup.cs". Now it seems it's possible to do something cleaner and better directly from publishing options of Visual Studio (I have to understand why it's not working, but I like the idea).
But at the end I'd like to achieve the same without having to publish manually from VS and leverage VSTS instead. I expect it to be possible in some way, but I was looking for the suggested (i.e. clean, simple, precanned) way of doing it with some VSTS existing deploy step without having to fiddle with scripts.

**Comment by rowanmiller** [comment]
@sayedihashimi (who owns the publish functionality in Visual Studio) is there a way to use the same workflow from VSTS?

**Comment by bragma** [comment]
@sayedihashimi in particular what I think it's missing is a deployment step in VSTS that allows to apply migrations when publishing from there. I'm puzzled that nobody asked this before, I'd like to know how everybody are doing this now, in particular if the web app is scaled out.
Thanks!

**Comment by Tarig0** [comment]
If I may suggest it would be great if the deployment would dump the information and verbose output to variables so we can easily utilize the information

**Comment by rowanmiller** [comment]
Moved over to the ASP.NET Tools repo - https://github.com/aspnet/Tooling/issues/698
