### ISSUE TITLE
EF 1.0 bug during generate the sql script

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#5994]
Hi EF Team,

This below code is my code.
_userRepository.Table.FirstOrDefault(p => p.JobPostId == postId & p.UserId == userId);

The EF generate this output sql from sql profiler.

exec sp_executesql N'SELECT TOP(1) [p].[Id], [p].[CreatedOnUtc], [p].[JobPostId], [p].[Pitch], [p].[Status], [p].[UserId]
FROM [JobPostUser] AS [p]
WHERE (([p].[JobPostId] = @__postId_0) & ([p].[UserId] = @__userId_1)) = 1',N'@__postId_0 int,@__userId_1 int',@__postId_0=12,@__userId_1=1

Looks like the issue is with '&' and at the end = 1

VS 2015 Update 3
EF 1.0

**Comment by danielcirket** [comment]
Shouldn't this be:

```c#
_userRepository.Table.FirstOrDefault(p => p.JobPostId == postId && p.UserId == userId);
```  

Note the **&&**

**Comment by gdoron** [comment]
You use the & binary operator in your query...

	_userRepository.Table.FirstOrDefault(p => p.JobPostId == postId & p.UserId == userId);
You probably meant:

	_userRepository.Table.FirstOrDefault(p => p.JobPostId == postId && p.UserId == userId);

**Comment by XcoderTeam** [comment]
It is work on RC2 after upgrade to 1.0 this break my site.

**Comment by danielcirket** [comment]
Maybe it did (Although I expect it still failed), but that doesn't mean your syntax was correct either, do you know the difference between '&' and '&&' in terms of what they do? As we mentioned above, from your code sample you should be using '&&'.

See these: 
[https://msdn.microsoft.com/en-us/library/sbf85k1c.aspx](https://msdn.microsoft.com/en-us/library/sbf85k1c.aspx)
[https://msdn.microsoft.com/en-gb/library/ms176122.aspx](https://msdn.microsoft.com/en-gb/library/ms176122.aspx)

**Comment by maumar** [comment]
@XcoderTeam in RC2 we didn't know how to translate & and | operators to SQL, so it was all translated on the client - that's why it worked

**Comment by smitpatel** [comment]
dupe of #5930
