### ISSUE TITLE
Don't throw from data annotations conventions

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#6004]
The exceptions can be moved to the validation step. This allows to ignore or override the invalid annotation using ModelBuilder

**Comment by AndriySvyryd** [comment]
Add root type name to KeyAttribute on derived type exception message

**Comment by ajcvickers** [comment]
Closing this since it doesn't seem to be a real-world problem. Can consider in the future if it turns out to be causing problems.
