### ISSUE TITLE
Migrating multitenant dbs

### ISSUE THREAD

**Issue by lnaie** [dotnet/efcore#6011]
I have to apologize but this topic is not clear as it should be.
Let me explain a bit the context first: I have a design time database where I do all the nifty staff with CF Migrations. That works! Then I need some tool at deployment time, like FluentMigrator, to be able to apply latest db schema changes to all other customer databases. As a side note, apparently 'dotnet ef' command needs the project.json, therefore I wasn't able to use it outside of the Visual Studio project folder. I wanted to build the diff sql script and apply it to all other customer dbs.

Question is how am I supposed to handle this?

**Comment by rowanmiller** [comment]
We do have plans for a command line executable like `dotnet ef` that can be used on any compiled assemblies (tracked by https://github.com/aspnet/EntityFramework/issues/646). In the meantime you can use [Script-Migration -Idempotent](https://docs.efproject.net/en/latest/miscellaneous/cli/powershell.html#script-migration) or [dotnet ef migrations script --idempotnent](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#dotnet-ef-migrations-script) to create a script that can be executed to upgrade a database. Passing the `idempotent` argument will create a script with the inbuilt logic to check the migrations history table and only apply pending operations.

**Comment by rowanmiller** [comment]
Closing as I think I've answered the question, but feel free to reply if not.
