### ISSUE TITLE
Include with SelectMany

### ISSUE THREAD

**Issue by gius** [dotnet/efcore#6016]
Is it possible to include related entities when using SelectMany?
### Example:

We have entity `Order` with navigation properties `User` and `OrderItems`. I want a query to load `OrderItem` with `Order` and `Order.User` properties loaded.

Naive code would look like this:

```
var itemWithOrderAndUser = db.Orders
    .SelectMany(x => x.OrderItems)
    .Include(x => x.Order).ThenInclude(x => x.User)
    .First();
```

It compiles and returns data but `itemWithOrderAndUser.Order` is empty.

Moreover, it seems that the include is ignored completely as the following code has `item.Detail` not loaded as well (it is null)

```
var item = db.Orders
    .Include(x => x.OrderItems).ThenInclude(x => x.Detail)
    .SelectMany(x => x.OrderItems)
    .First();
```

// Note: I know I could start with `db.OrderItems` but it is not aggregate root and also I need to do some filtering on `Order` so this is the preferred way.

**Comment by rowanmiller** [comment]
@anpete @maumar @smitpatel in triage we thought we already had an issue tracking the ability to specify an Include after the query shape has been changed (but is still a valid entity type)... but I'm having a hard time finding it. Any chance you guys know which one it is?

**Comment by anpete** [comment]
@rowanmiller This one? https://github.com/aspnet/EntityFramework/issues/3418

Not sure it is the same thing.

**Comment by rowanmiller** [comment]
Yep, that is the one I was thinking of. Should we just open a general "Support Include after changing query shape" issue and link to these two?

**Comment by anpete** [comment]
Yeah, tried it, and it looks like the same thing, so you can consolidate.

**Comment by rowanmiller** [comment]
Dupe of #3418
