### ISSUE TITLE
Incorrect syntax new '&'

### ISSUE THREAD

**Issue by DWAK-ATTK** [dotnet/efcore#6024]
### Steps to reproduce

Query:
result = (From r In DatabaseContext.ItemCodeRestrictions Where r.ItemCodeID = itemCodeID And r.MoveTypeID = moveTypeID).Any(Function(i) i.RestrictionTypeID = 2)
### The issue

When running the LINQ query above I receive the error:  

> Incorrect syntax near '&'

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace (From Diagnostic Tools window):
Activated   Event   Time    Duration    Thread
    Exception: Exception thrown: 'System.Data.SqlClient.SqlException' in Microsoft.EntityFrameworkCore.dll ("Incorrect syntax near '&'."). Exception thrown: 'System.Data.SqlClient.SqlException' in Microsoft.EntityFrameworkCore.dll ("Incorrect syntax near '&'.")   17.59s      [8540] <No Name> 

```
### Further technical details

EF Core version: 1.0.0
Operating system: Win 10 Enterprise
Visual Studio version: VS 2015

Other details about my project setup:
The LINQ gets translated into this SQL:  

```
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [ItemCodeRestrictions] AS [r]
        WHERE (([r].[ItemCodeID] = @__$VB$Local_itemCodeID_0) & ([r].[MoveTypeID] = @__$VB$Local_moveTypeID_1)) AND ([r].[RestrictionTypeID] = 2))
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
```

If I change the Where clause "And" to an "AndAlso" the correct SQL is generated.  

This issue appears any place I use an And in the Where clause.

**Comment by smitpatel** [comment]
@DWAK-ATTK - Can you provide a repro code? The query you provided does not compile.

**Comment by smitpatel** [comment]
closing in favour of #5930
