### ISSUE TITLE
Does EF Core support Multiple Result Sets from Stored Procedure?

### ISSUE THREAD

**Issue by mgolois** [dotnet/efcore#6026]
Does EF Core support Multiple Result Sets from Stored Procedure?

**Comment by rowanmiller** [comment]
Not at this stage. To execute a stored procedure you have to use a raw SQL query, but that only handles one result set.

**Comment by mgolois** [comment]
thanks @rowanmiller.

**Comment by thushbandara** [comment]
Hi

With reflections and data-readers , we could archive this. Following is the link to Git Repo

https://github.com/nilendrat/EfCoreMultipleResults

Hope this will be of help.

**Comment by KishorNaik** [comment]
Please check following link where we can able to retrieve multiple result sets as well as mapping complex type objects.

https://github.com/KishorNaik/Sol_EF_SqlQuery
