### ISSUE TITLE
Support commands on portable and UWP class library projects

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#6029]
As of 1.0.0-preview2, executing design-time commands on a UWP class library does not work.

**Reason it doesn't work yet**
MSBuild does not gather UWP dependencies into one location. The output of compiling UWP is insufficient to execute. We would need to manually gather the libraries dependencies in order to host the library as an app.

**Workaround**

You can still add migrations/scaffold code, but you must use a UWP app as the `-StartupProject`

**Comment by natemcmaster** [comment]
Blocked by https://github.com/dotnet/cli/issues/4005

**Comment by bricelam** [comment]
Discussed with @rowanmiller and, while there is a way to make it work, it is not recommended by NuGet due to the incurred perf and storage costs. We don't install into PCLs anymore, and we issue the following error when the startup project is a UWP class library:

> Startup project 'ClassLibrary1' is a class library. Select a Universal Windows Platform app as your startup project and try again.
