### ISSUE TITLE
Relational: 2nd Level Caching using a cache server like Redis

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#6041]
Availability of 2nd level caching in a cache server such as Redis can be a really nice feature with EF. 
Availability of Cache invalidation strategies within the framework will help more.

Thanks

**Comment by gdoron** [comment]
I'll be very happy to get rid of my code I copy - paste from project to project and use a built in tool.

**Comment by rowanmiller** [comment]
Duplicate of https://github.com/aspnet/EntityFramework/issues/5858
