### ISSUE TITLE
reference this source code,compile this error: 

### ISSUE THREAD

**Issue by strivelearns** [dotnet/efcore#6065]
E:\Practices\EfTest\src\EfTest\error CS0006: Metadata file 'F:\EntityFramework-1.0.0\src\Microsoft.EntityFrameworkCore.Relational\bin\Debug\netstandard1.3\Microsoft.EntityFrameworkCore.Relational.dll' could not be found EfTest  C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  262

**Comment by smitpatel** [comment]
Above error suggests that building `Microsoft.EntityFrameworkCore.Relational` project failed hence dll was not generated. Which is referenced by some other project.

**Comment by ajcvickers** [comment]
Question answered. Closing.
