### ISSUE TITLE
Changing the principal of an identifying FK throws unhelpful exception

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#6066]
``` C#
private class Order
{
    public int Id { get; set; }
}

private class OrderDetails
{
    [Key]
    public int OrderId { get; set; }

    public Order Order { get; set; }
}

var orderDetails = context.OrderDetails.First();
orderDetails.Order = context.Orders.First(o => o != orderDetails.Order);
context.SaveChanges();
```

Currently throws `The property 'OrderId' on entity type 'OrderDetails' is part of a key and so cannot be modified or marked as modified.`

This is confusing since the user didn't modify the property. We could detect the FK and suggest modifying the model or creating a new dependent entity.

**Comment by rowanmiller** [comment]
Discussed in triage and concluded that this isn't a terrible message. If we see customers getting confused we may reconsider, but for the moment we won't spend time on this.

**Comment by MarcoLoetscher** [comment]
@rowanmiller: You are wrong, the message is confusing.

**Comment by ajcvickers** [comment]
@MarcoLoetscher Can you suggest wording that would be more clear?

**Comment by MarcoLoetscher** [comment]
@ajcvickers: Why an exception is thrown in this example? I think that this example would work in EF6.x?

**Comment by rowanmiller** [comment]
@MarcoLoetscher this is an identifying relationships - meaning the primary key is used as the foreign key. Because the scenario tries to change the foreign key, it requires the primary key to change, which is not supported. This restriction applied to EF6.x as well.
