### ISSUE TITLE
Question: How to add database changes after a specific migration has been made?

### ISSUE THREAD

**Issue by ToddThomson** [dotnet/efcore#6069]
After applying a migration to convert Identity tables from v2 schema to v3 schema I need to process all existing users and roles so that I can generate normalized values ( NormalizedUserName, etc ).

EDIT: These values need to be written back to the database/Identity tables as part of the migration.

What is the best way to accomplish this? Thanks in advance!

**Comment by divega** [comment]
Cc @haok who has worked on a sample for Identity, although the question seems more general.

**Comment by ToddThomson** [comment]
@divega I'm looking for guidance on how to set database table values as part of a EF Core migration. A Post migration event after the database has been altered is what I'm looking for. Can this be accomplished with EF Core at this time?

**Comment by rdefreitas** [comment]
This sounds like a scenario that isn't really best suited to a migration, but an independent script or set of startup actions.

Unless, of  course, you can do everything you need via SQL... then you can use
`migrationBuilder.Sql("UPDATE TABLE [Foo] SET [Bar] = 1")`

**Comment by HaoK** [comment]
In our compact package, we chose to simply compute the normalized properties always in the getters instead of storing them.  But we were targeting identity v2 apps working along side identity v3 apps in the same database.

See https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity.AspNetCoreCompat/IdentityUser.cs 

If you are just upgrading to identity v3, you should just be able to compute the ToUpper once like @rdefreitas suggested.

**Comment by ToddThomson** [comment]
@rdefreitas Yes, I agree, the migration class is not suitable ( except where Sql() can be used ). With EF 6, I had a module Initialize routine that was called during startup to handle migration tasks at the services layer. I utilized System.Data.Entity.Database and MigrateDatabaseToLatestVersion which I don't believe exist in EF Core.

The specific issue I have with the Identity v2 to v3 schema change is that there are a few "normalized" columns ( that are based on other columns ) in the AspNetUsers and AspNetRoles tables that need to be set in order for the Identity v3 services to work properly. This means that I must update the schema and set these columns in one task.

OK, off to work!

**Comment by ToddThomson** [comment]
@divega Ouch. Is it the case that the Migrator will not work with Migrations in a core library?

**Comment by divega** [comment]
Cc @natemcmaster to follow up on the latest question

**Comment by natemcmaster** [comment]
@ToddThomson can you clarify? Are you encountering errors? or do you mean you've encountered the [class library limitation](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#targeting-class-library-projects-is-not-supported) with command line tools?

**Comment by ToddThomson** [comment]
@natemcmaster I need to do additional development and testing in order to give you more information. At this point, everything looks OK.

I did run across the command line tools issue weeks back, but I'm around that now.

**Comment by rowanmiller** [comment]
Sounds like we can close this one out now. Feel free to reply (or open a new issue) if you hit anything further.
