### ISSUE TITLE
tag queries with more information

### ISSUE THREAD

**Issue by luisrudge** [dotnet/efcore#608]
it would be nice to intercept the generated query and append more info so you can tag your queries.
scenario:
i want to correlate a request id to a database query to monitor performance

ruby/ActiveRecord idea: https://github.com/basecamp/marginalia
more info: 
http://samlambert.com/posts/the-power-of-query-comments/

**Comment by rowanmiller** [comment]
Closing this one out as the idea of annotating a query with additional data is captured in https://github.com/aspnet/EntityFramework/issues/1664
