### ISSUE TITLE
Abstract out IIncludable/Async Extensions for Generic use

### ISSUE THREAD

**Issue by rondefreitas** [dotnet/efcore#6085]
### The Problem

When building and testing real-world applications with EntityFramework, it is not always possible to take advantage of the Async and IIncludable extensions.

Many application structures abstract away the ORM code behind generic repositories and services that focus on the IQueryable interface; Along the way, lose the advantage of the EntityFrameworkQueryableExtensions, both in business logic and unit tests, without jumping through sometimes significant hoops.

Developers faced with this problem are often either unable to take advantage of the Async extensions and IIncludableQueryable in their services at all, or are forced to write overly complicated wrapping code to allow these features.
### Proposal

Let's face it, no matter how many times you beat the drum that DbSet _is_ a repository and that DbContext _is_ a Unit of Work, you will never prevent organizations from feeling the need to decouple their ORM entirely from their services project.

I propose we abstract these extensions such that they are available with all instances of IQueryable regardless of the underlying QueryProvider. I'm prepared to contribute this myself, as it's a matter mostly of porting work I've done already on another project.
- Create a new Project and Nuget package for `Microsoft.EntityFrameworkCore.Abstractions` (or `....Extensions`.)
- Default implementations would be provided for extensions such as ToListAsync, which would return a task from the result of the Synchronous version of the method unless targeting an IQueryable for which the QueryProvider implements IAsyncQueryProvider.
- The existing namespaces would remain in tact. The purpose of the project would be solely for using these extensions independent of pulling in all of Entity Framework Core.
- Default implementations of IIncludableQueryable would assume that the IQueryable source is a synchronous collection for which navigation properties are already populated. (note: EF already does this for Include/ThenInclude... they could just use a move to an abstractions project
- **_Requires Discussion**_: debug log events could be generated whenever the default, synchronous implementation is used, so the developer is aware that they are not truly executing asynchronous code.

**Comment by rowanmiller** [comment]
Going to wait unitl @divega is back in the office to discuss this.

**Comment by rdefreitas** [comment]
Thanks @rowanmiller.

I've gone through all of the methods and have come up with a short list of the ones I don't believe are appropriate to be moved, and why.

- *Load*() / *LoadAsync*(): This is very EF specific. The only change I'd propose here is to add the fallback of calling Load if the collection does not implement IAsyncEnumerable.
- *AsTracking*() / *AsNoTracking*(): Too EF specific. The idea behind this change is to support scenarios such as generic repositories within a service library.  The most common scenario I've seen is IRepository + IReadOnlyRepository. IMHO, someone building an implementation of each repository type should be calling AsTracking/AsNoTracking in their EF-dependent Repository wrapper, and not inside of their consuming service or command/query handler.

**Comment by ajcvickers** [comment]
We aren't planning on doing this, but we would consider it again later if there is interest, and especially if there is a good PR for it, making sure to follow the feedback on the closed PR referenced above.
