### ISSUE TITLE
Keys in CLR Abstract Base Class Broken

### ISSUE THREAD

**Issue by nweigl** [dotnet/efcore#6087]
### The issue

We are working on a multitenant database using EF. In EF6, we used an abstract CLR base class to define the primary keys (and other common fields) which all of our models would inherit. We have a composite primary key consisting of TenantID and ID, so TenantID is part of both the primary key and all foreign keys in the table (this allows us to have all the data for all tenants in the same table while keeping everything separated). This worked fine in EF6. In EF Core, we are now getting the following error whenever we try to generate the database:

"The property 'TenantID' cannot be part of a foreign key on 'Customer' because it is contained in a key defined on a base entity type."

It looks like this capability was broken by [#2837](https://github.com/aspnet/EntityFramework/issues/2837). Is there any way you could bring back this capability if the base class is abstract?
### Steps to reproduce

```
    public abstract class EntityBase
    {
        public short TenantID { get; set; }
        public int ID { get; set; }
    }
    public class Customer : EntityBase
    {
        public string Name { get; set; }
        public int AccountID { get; set; }
        public virtual Account Account { get; set; }
    }
    public class Account : EntityBase
    {
        public int Balance { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }

    public class AccountContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public AccountContext()
        {
            Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EntityBase>().HasKey(eb => new { eb.TenantID, eb.ID });
            modelBuilder.Entity<Customer>().HasOne(c => c.Account).WithMany(a => a.Customers).HasForeignKey(c => new { c.TenantID, c.AccountID });
            base.OnModelCreating(modelBuilder);
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TestDB;Trusted_Connection=True;");
        }
    }
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS 2015 Update 3

Other details about my project setup:

**Comment by ajcvickers** [comment]
@nweigl From your description it seems that you want EntityBase to be an unmapped base type. However, the way you have your code it will be mapped because of the `Entity<EntityBase>` call. This means that because EF Core only supports TPH mapping all your entities would end up being saved to just one database table.

To instead use EntityBase as an unmapped base type you can define the key for each of the actual entity types that are mapped, like this:
```C#
modelBuilder.Entity<Customer>().HasKey(eb => new { eb.TenantID, eb.ID });
modelBuilder.Entity<Account>().HasKey(eb => new { eb.TenantID, eb.ID });
```

**Comment by nweigl** [comment]
@ajcvickers I see. I was hoping for a less manual solution so that we don't have to add another key definition every time we add a table, as previously we had defined the composite keys in the base class as attributes, which is no longer supported in EF Core. Originally, I had attempted to find a way to iterate over all the derived tables and set the keys like you mentioned, and was unsuccessful, Something like 
```
foreach (var entity in <some function I couldn't find>)
    modelBuilder.Entity<entity>().HasKey(eb => new { eb.TenantID, eb.ID });
```
Is something like this possible?

**Comment by ajcvickers** [comment]
@nweigl 
```C#
foreach (var entityType in modelBuilder.Model.GetEntityTypes())
{
    entityType.SetPrimaryKey(new[]
    {
        entityType.FindProperty(nameof(EntityBase.TenantID)),
        entityType.FindProperty(nameof(EntityBase.ID))
    });
}
```
