### ISSUE TITLE
Kerberos auth from linux with sql server provider

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/efcore#6101]
### The issue

Is it possible in the future to allow Kerberos authentication from Linux to SQL server.
Currently I have to enable SQL server Authentication on my whole SQL server for my Linux App to connect to the database server.
Linux has good support for joining AD these days and I can use Squid/Samba in intergrated security mode.

I am thinking it would be possible to also create Integrated (Windows) Security connections to SQL Server as well?
Of course I have no idea how much work would be involved.

I do know that all documentation discourages SQL Server in SQL Auth mode.
### Further technical details

EF Core version: 1.0 rtm
Operating system: Centos 7
Visual Studio version: VS2015
Other details about my project setup: Connecting from Centos to SQL server 2008R2 sp3 with SQL Auth

**Comment by rowanmiller** [comment]
@mikes-gh could you ask this over on the CoreFX project, that's where SQL Client is maintained https://github.com/dotnet/corefx/.

**Comment by mikes-gh** [comment]
Wondering why I couldn't find the code :smile: sorry
