### ISSUE TITLE
Explicit "Include" with custom Repository pattern based on DbSet returns null for navigation properties

### ISSUE THREAD

**Issue by neoaisac** [dotnet/efcore#6114]
### Steps to reproduce

Say there are 2 classes related in a 1:M relationship and the navigation property is defined only in the dependent class, without a foreign key property nor any attributes.

``` csharp
public class Client
{
    public int Id { get; set; }
}

public class Order
{
  public Guid Id { get; set; }
  public DateTimeOffset Timestamp { get; set; }
  public Client Client { get; set; }
}
```

And say it is configured with fluent EF Core like below.

``` csharp
public class MyModelBuilder : ModelBuilder
{
  public MyModelBuilder() : base(new ConventionSet())
  {
    Entity<Client>(ClientConfiguration.Configure);
    Entity<Order>(OrderConfiguration.Configure);
  }
}

public static class OrderConfiguration
{
  public static void Configure(EntityTypeBuilder<Order> orderConfig)
  {
    // Assume table/property configurations go here
    //---

    // Defines a shadow property for navigation
    orderConfig.Property<int>("ClientId").HasColumnName("ClientId");

    // Defines the navigation property
    orderConfig.HasOne(x => x.Client)
        .WithMany()
        .HasForeignKey("ClientId") // Shadow property
        .OnDelete(DeleteBehavior.Cascade)
        .IsRequired();
  }

// Assume ClientConfiguration.Configure is done similarly

}
```

And say you have an implementation of the `IRepository<T>` pattern like below.

``` csharp
public interface IRespository<T> : IEnumerable<T>
{
  T Add(T entity);
  T Update(T entity);
  void Delete(T entity);

  // Include for navigation properties
  void Include<TProperty>(Expression<Func<T, TProperty>> navigationPropertyPath);
}

public clas DbSetRepository<T> : IRepository<T>
{
  private readonly DbSet<T> _dbSet;

  public DbSetRepository(DbSet<T> dbSet)
  {
    _dbSet = dbSet;
  }

  // Assume the rest is implemented

  public void Include<TProperty>(Expression<Func<T, TProperty>> navigationPropertyPath)
  {
    _dbSet.Include(navigationPropertyPath);
  }
}
```

And say you have a Unit Of Work implementation to get all repos from the same context like below.

``` csharp
public class UnitOfWork : IUnitOfWork
{
  private readonly DbContext _dbContext;

  public UnitOfWork(DbContext dbContext)
  {
    _dbContext = dbContext;
  }

  public IRepository<T> GetRepository<T>()
  {
    return new DbSetRepository(_dbContext.Set<T>());
  }
}

```
### The issue

Say you use the above code like below (disregard usings, disposables and instantiation of other variables).

``` csharp

var uow = new UnitOfWork(myRuntimeDbContext);
var orderRepository = uow.GetRepository<Order>().Include(x => x.User);
var user = orderRepository.First().User;

if (user == null) throw new NullReferenceException();

```

The code above will throw a `NullReferenceException` as the navigation property `Order.User` has not been loaded, even though there is an explicit call to `Include`.
### Further technical details

EF Core version: 1.0.0 (net461)
Operating system: Windows 7 64 bit
Visual Studio version: VS 2015 Update 3

Other details about my project setup:
- The solution is a traditional .Net solution (.sln, .csproj) targetting .Net FW 4.6.1.
- The whole code does not rely on the implementations of the `IRepository` or `IUnitOfWork`, and I'd like to keep it that way.
- I feel strongly against the usage of attributes in my model. I'd rather have a clean model and map it where needed with fluent APIs.

**Comment by rowanmiller** [comment]
LINQ methods do modify an existing query but construct a new query that adds the operator to the previous query. So calling `_dbSet.Include(navigationPropertyPath)` isn't modifying your `_dbSet` field, it's building an new query (which isn't getting assigned to anything). You need to change `_dbSet` to be an `IQueryable<T>` and do `_dbSet = _dbSet.Include(navigationPropertyPath)`.

**Comment by isaacllopisaracil** [comment]
But I cannot Add, Delete or Update elements in the `IQueryable<T>` so you're saying that my `IRepository<T>` must incorporate a reference both to the `DbSet<T>` for these methods, and an internal `IQueryable<T>` that can be modified by the `Include(Expression)` method, _both_?

**Comment by rowanmiller** [comment]
@neoaisac correct, in that case you would need one for the `DbSet` and one for the "base query" - which is the original query from `DbSet` with all `Include`s etc. applied.
