### ISSUE TITLE
Add SQL statements to SaveChanges batch

### ISSUE THREAD

**Issue by flipchart** [dotnet/efcore#6124]
Is it possible to add to the SQL batch generated for the `.SaveChanges` (or `.SaveChangesAsync`) method of `DbContext`?

Background:
I'm wanting to set entity navigation properties without loading the related entity. So I do something like:

```
class Client {
    int Id { get; set; }
    string Name { get; set; }
}

class Project {
    int Id { get; set; }
    string Name { get; set; }

    Client Client { get; set; }
}

async Task CreateProject(int clientId) {
    using(var context = new XYZDbContext()) {
        var client = new Client { Id = clientId };
        context.Clients.Attach(client);

        var project = new Project {
            Client = client,
        };

        context.Projects.Add(project);

        await context.SaveChangesAsync();
    }
}
```

However, if the attached `Client` doesn't exist, all I get is a `SqlException` wrapped in a `DbUpdateException` and I have to do string parsing of the SQL error message to determine the property that caused the error so that I can inform the user which input to correct. 

What I'd like to do is to add to the SQL batch generated by `.SaveChangesAsync` to check for the existence of each of the referenced entities:

```
exec sp_executesql N'SET NOCOUNT ON;
-- Check that Client exists
IF NOT EXISTS (SELECT 1 FROM Clients WHERE Id = @p1)
    THROW 60000, ''Client does not exist'', 1

INSERT INTO [Projects] ([Id], [ClientId], [Name])
VALUES (@p0, @p1, @p2);
',N'@p0 int,@p1 int,@p2 nvarchar(4000)',@p0=1,@p1=6,@p2=N'Project 1'
```

This way I can customize the SQL messages and precisely determine the invalid input

**Comment by rowanmiller** [comment]
Something like this would typically be handled with a stored procedure (tracked by #245). Another option would be to check for existence before saving, but that is obviously not part of the same batch. If you are feeling brave, you could look at overriding the internal components that execute batches... but that's not a documented scenario, so you'd be on your own in terms of figuring out how to do it.
