### ISSUE TITLE
Add-Migration or Install Package commands errors when ASP.NET Project was copied from Win 8.1 to Win 7

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#6125]
On my windows 8.1 with VS2015 I created [this ASP.NET tutorial](https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html) project that ran fine. But when I copied the project directory to windows 7, deleted the Migration folder and ran the following command, I get the error: `Project "Default" is not found`:
`PM> Add-Migration MyFirstMigration -context BloggingContext`
I get similar error when running Install-Package commands for installing a package on the same project after it was copied to windows 7. **But these commands work fine after** I upgraded from Windows 7 to Windows 10.

Note: I've ASP.NET Core 1.0 and VS2015 Update 3 installed on both machines
Thanks..Saf

**Comment by ErikEJ** [comment]
Powers hell update needed?

**Comment by rowanmiller** [comment]
Agreed with @ErikEJ, you need the latest version of PowerShell to use the commands. Closing as we are pretty confident that is the issue, but if not, then just reply and we'll reopen the issue.

**Comment by saf-itpro** [comment]
@rowanmiller On my windows 10 (upgraded from Windows 7) I've PowerShell 5.0 that is the latest version. Here is the result of `$PSVersionTable` command on PS on my machine. Do I need to do something else?:
`Name                           Value
----                           -----
PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`
