### ISSUE TITLE
decimal properties mapped to text columns in SQLite

### ISSUE THREAD

**Issue by VagueGit** [dotnet/efcore#6137]
From this entity property
        `public double ItemCost { get; set; }`
this migration script snippet is produced
`ItemCost = table.Column<double>`
which creates a column of type `Real` in SQLite
From this entity property
        `public decimal ItemCost { get; set; }`
this migration script snippet is produced
 `ItemCost = table.Column<decimal>`
which creates a column of type `Text` in SQLite
### The issue

Dot Net decimal should map to SQLite Real not text

**Comment by rowanmiller** [comment]
Pretty sure this is by-design, assigning to @bricelam to confirm

**Comment by bricelam** [comment]
Yes, by-design. Storing as a REAL would be lossy.

**Comment by VagueGit** [comment]
Thank you for clarifying that @bricelam
