### ISSUE TITLE
Update database on Runtime    (Is it even possible ?)

### ISSUE THREAD

**Issue by Foroughi** [dotnet/efcore#6141]
I am using this code on OnModelCreating method of my dbcontext to create a table.

```
 modelBuilder.Entity("Aime.Logger.Loggers.Database.Model.Log", b =>
            {
                b.Property<int>("Id")
                  .ValueGeneratedOnAdd();
                b.Property<DateTime>("Datetime");
                b.HasKey("Id");
                b.ToTable("Logs");

            });
```

Clearly I dont want to use the dotnet ef database/migrations command and the main idea is to create the database (based on what are mentioned in OnModelCreateing method) runtime

**Comment by rowanmiller** [comment]
You can use `context.Database.Migrate()` to apply all pending migrations. If you are not using migrations, then `context.Database.EnsureCreated()` will create the database and schema if it does not exist - but there is no way to incrementally update it if you use this approach (that's what migrations are for).
