### ISSUE TITLE
Feature Request: Add -excludeAspNet Flag to Scaffold-DbContext

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/efcore#6148]
If using AspNet Identity and you have the tables in your database, then you reverse engineer your schema using Scaffold-DbContext it also grabs the AspNet\* tables. This causes issues with ASP.NET core web applications. I also used the AspNetUser as a foreign key to my other tables to track who modified a record and this also caused an issue with the project.

SO please add an exclude flag for 
  1) All AspNet\* tables
  2) Any foreign key relationships to/from AspNet\* tables 

Currently we have to manually remove these each time we update our models from our database schema. We prefer to develop database first and database updates first methodology.

Thanks for the consideration!

**Comment by rowanmiller** [comment]
We aren't planning to do something specific to the AspNet* tables, but we do want to have the ability to exclude a set of tables (which would include fk constraints to them). In triage we thought we had something tracking this, but I couldn't find it... so opened https://github.com/aspnet/EntityFramework/issues/6182 to track.
