### ISSUE TITLE
Insert Values into Database using Migrations

### ISSUE THREAD

**Issue by tuppers360** [dotnet/efcore#6151]
I am using the latest builds for VS2015 with preview 3

I want to add values to a DB using the Up migrations method like so:

public partial class PopulateGenresTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            Sql("INSERT INTO Genres (Id, Name) VALUES (1, 'Rock')");
        }

```
    protected override void Down(MigrationBuilder migrationBuilder)
    {

    }
}
```

But the is no Sql in the current context, can anyone advise how to go about this?

Thanks

**Comment by ctolkien** [comment]
```
migrationBuilder.Sql("...");
```

**Comment by tuppers360** [comment]
thanks
