### ISSUE TITLE
dotnet ef dbcontext scaffold does not use assembly name

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/efcore#6152]
## Steps to reproduce

1- Create a asp.net web project. 
2- Change the default namespace in the project properties to something different than the project name.
2- Set the project up to run ef dbcontext scaffold to create models from a SQL server db
3- Run the scaffolding command line
## Expected  behavior

Output classes use the Default namespace value for namespace names
## Actual behavior

Output classes are using project name for namespace names
## Environment data

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

Cross-post from dotnet/cli#3520

/cc @chassq

**Comment by rowanmiller** [comment]
@natemcmaster @bricelam I think we already have this tracked somewhere right?

**Comment by natemcmaster** [comment]
@rowanmiller "default namespace" is a Visual Studio-only feature and does not yet work in "dotnet ef" or .xproj projects. This will be fixed with #5334 

@chassq can you clarify two things?

> Run the scaffolding command line

Are you using `Scaffold-DbContext` or `dotnet ef dbcontext scaffold`? 

> Create a asp.net web project.

Which version of ASP.NET? ASP.NET Core or ASP.NET 4?

**Comment by rowanmiller** [comment]
https://github.com/aspnet/EntityFramework/issues/4524 is the one I was thinking of. `project.json` has default namespaces - but we were going to wait until the project system consolidates before adding support.

**Comment by lajones** [comment]
See also #3988 - there the plans were to make the namespace be some combination of the default namespace for the project (or the project name if a default namespace isn't available) and what you specify for the `--outputDir` (provided `--outputDir` is within the project) and the schemas of the tables.

**Comment by natemcmaster** [comment]
> we were going to wait until the project system consolidates before adding support

I'll be tracking this in https://github.com/aspnet/EntityFramework/issues/6139

**Comment by chassq** [comment]
dotnet ef dbcontext scaffold "Server=<dbserver>;Initial Catalog=<db>;Persist Security Info=False;User ID=<uid>Password=<pwd>;Pooling=False;Encrypt=True;TrustServerCertificate=False;" Microsoft.EntityFrameworkCore.SqlServer --output-dir models --force

ASP.NET Core using full .net framework 4.6.1

**Comment by chassq** [comment]
Accounting for table schemas in ns would be awesome!

**Comment by rowanmiller** [comment]
Tracked by #6139
