### ISSUE TITLE
InMemory: Enable case sensitivity/insensitivity setting

### ISSUE THREAD

**Issue by ctolkien** [dotnet/efcore#6153]
When querying InMemory database, string comparisons are case specific whereas the default collation of SqlServer is case-insensitive.

Would like to see an option added to the `InMemoryDbContextOptionsBuilder` object to specify this behaviour so that we can more closely align with SqlServer.

**Comment by rowanmiller** [comment]
Case sensitivity in SQL Server is actually controlled by the collation settings in the database. We can see the value in having similar settings in the InMemory database so that you can adjust it to align with whatever database you are targeting.

**Comment by kirschem** [comment]
I'd like to tackle this one as my first issue in ef core. Should I branch from master?

**Comment by smitpatel** [comment]
@kirschem - Yes, please branch of master.

**Comment by xaviergxf** [comment]
How will EF.Functions.Collate work with in memory?

**Comment by roji** [comment]
@xaviergxf EF.Functions.Collate is a relational concept only. The way databases implement collations is quite different from anything we could do in InMemory, at least not without considerable work. For example, SQL allows collations to be applied to arbitrary (textual) expressions, and also supports assigning collations to the columns themselves; that's not something that's immediately compatible with how .NET works.

**Comment by xaviergxf** [comment]
This means an exception will be thrown? And for testing i will need to mock the this...

**Comment by roji** [comment]
As very frequently with InMemory, relational features simply aren't supported, making it of limited use for full-fledged testing. In that sense, collations aren't very different from transactions or raw SQL queries. See https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing for more details on this.

**Comment by KimberlyPhan** [comment]
Hi,  I am seeing this issue today, has the feature/fix gone in or is it still in the backlog? If it's gone in, how do I set my in memory db to be case insensitive?
