### ISSUE TITLE
Is Stored Procedure Output parameter supported via FromSQL or ExecuteSqlCommand ?

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#6154]
Hi,

We are trying to execute SP which has only Output type parameter, But if we pass Parameter of type DB2Paramemter then we get below error:
Unhandled Exception: System.NotSupportedException: No mapping to a relational ty
pe can be found for the CLR type 'DB2Parameter'

and if we pass just int type parameter, we don't see\get value.

Is Stored Procedure Output parameter supported via FromSQL or ExecuteSqlCommand ?

Thanks,
Archana

**Comment by rowanmiller** [comment]
It looks like you are using the DB2 provider which I think currently only supports RC1. If so, the ability to pass `DbParameter`s to those APIs was added after RC1. You would need to wait for a version of the provider that supports the 1.0.0 release of EF Core.
