### ISSUE TITLE
How to do data migrations inside an EF7 code first migration?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#6155]
(Asked on [StackOverflow](http://stackoverflow.com/q/38568475/7850), but I'm hoping you guys will get me a more accurate answer, sooner...)

In my schema migration, I need to do a data migration to an external database. So I can't fall back on `migrationBuilder.Sql()`. What I need to do is run a query on the local database and insert the data returned into the external database. In other words, I want to do something like this:

```
// Obviously this is pseudo-code; these interfaces mostly don't exist
protected override void Up(MigrationBuilder migrationBuilder)
{
  var results = migrationBuilder.GetQueryResults("some query");
  using (var extDb = new ExternalDb())
  {
    foreach (var row in results) 
    {
      InsertToExternalDb(row, extDb);
    }
  }
}
```

But I can't find any method on `MigrationBuilder` that returns rows from the current database, and I can't even find a way to get the connection string such that I could write a raw ADO query to the current database.

Any other ideas how I could do this?

**Comment by rdefreitas** [comment]
Currently, there is no way to return loaded entities inside of migrations, however, you can use the Sql method of MigrationBuilder inside your migrations.

`migrationBuilder.Sql("UPDATE [dbo].[Foo] SET [Bar] = 1;");`

**Comment by shaulbehr** [comment]
Yes, but that only works on the local database.  I need to get data out of the local and into an external DB.  
You say "currently".  Does that mean this feature is on the road map?

**Comment by rdefreitas** [comment]
One of the other issues discussed changes to migrations to facilitate seeding.  I'm not sure when it is planned for, though.

As for the local database concern, it will execute against whatever database you're running your migrations against.

**Comment by rowanmiller** [comment]
@shaulbehr this isn't a supported scenario of migrations and not something we really plan to support.

However, you can write whatever code you want in the migration, so you can use ADO.NET to connect to the remote database etc. The big caveat would be that the code would run when the migration script is being calculated, so it would run before any other operations in the migration are applied to the database. It would also run when you are just scripting a migration etc.

**Comment by shaulbehr** [comment]
@rowanmiller  I know I could run ADO.Net queries, and that would be fine solution, except that I don't even have access to the connection string for the current database from inside the migration.  Any chance you could provide that as a property of the MigrationBuilder somewhere?

**Comment by rowanmiller** [comment]
I don't think we would provide that, as connecting to the database doesn't really fit with how migrations works (it breaks scripting etc.). I think the best bet is to use some code to manually locate the connection string if you know it works ok with the way you are using migrations.

**Comment by shaulbehr** [comment]
... except that we've got about 500 database shards, and we were kinda hoping to let EF migrations update their respective schemas on demand, rather than pushing script migrations from one central process that is aware of all the shards.  Any other suggestions?
