### ISSUE TITLE
EntityTypeBuilder missing overload HasKey

### ISSUE THREAD

**Issue by mariuszkochanowski** [dotnet/efcore#6158]
EntityTypeBuilder
has function:
`public virtual KeyBuilder HasKey([NotNull] params string[] propertyNames)`

that allows: .HasKey("UserId", "RoleId")

EntityTypeBuilder<TEntity>
missing overload:
`public virtual KeyBuilder HasKey(params Expression<Func<TEntity, object>>[] keyExpression)`

that could allow: .HasKey(e=>e.UserId, e=>e.RoleId)

**Comment by ajcvickers** [comment]
@arespr Use
```C#
.HasKey(e => new { e.UserId, e.RoleId })
```
