### ISSUE TITLE
Query: SQL LIKE statement (wildcards) using LINQ

### ISSUE THREAD

**Issue by axelheer** [dotnet/efcore#6159]
In the "old" Entity Framework it was possible to use `SqlFunctions` in order to create something like an ordinary `LIKE` statement.

`... where SqlFunctions.PatIndex("%na_f%", x.Name) > 0...`

While in the "new" Entity Framework there seems to be no replacement for `SqlFunctions`. That approach was a workaround anyway, but some way to use a simple `LIKE` statement would be very useful. If not essential.

**Comment by divega** [comment]
Related to #2850.

**Comment by smitpatel** [comment]
@anpete - Is this same as in-memory like we have?

**Comment by axelheer** [comment]
Oh, we have `EF.Functions.Like` now. :metal:

**Comment by irg1008** [comment]
How can we use the patindex function now? Or could I get the index in which like or match pattern happens?

**Comment by roji** [comment]
@irg1008 take a look at the comment just above.

**Comment by irg1008** [comment]
Yeah but Like does not return the index and used inside where, I need to know the index to get a substring of a column value

**Comment by roji** [comment]
Thanks, I misread your comment. EF Core doesn't current have a translation for SQL Server PATINDEX, I opened #33702 to track that. In the meanwhile, if you need this, you should be able to use [user-defined function mapping](https://learn.microsoft.com/en-us/ef/core/querying/user-defined-function-mapping) to map a .NET method stub of your own to PATINDEX.
