### ISSUE TITLE
please add framework netstandard to Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#6170]
it is possible to add netstandard1.x framework to the assembly/nuget package Microsoft.EntityFrameworkCore.Tools?

I have an app running on ubuntu linux and want to have support for netstandard1.6

**Comment by rdefreitas** [comment]
Are you trying to reference this from a supporting library or your executable project?

Executables on .net core ideally should target `netcoreapp1.0` which is supported by the Tools library.

**Comment by rowanmiller** [comment]
@natemcmaster can you comment on this one

**Comment by natemcmaster** [comment]
@leo90skk at the moment, "dotnet-ef" doesn't work on class library projects (see https://github.com/aspnet/EntityFramework/issues/5320). In other words, if you can't do `dotnet run`, then `dotnet ef` wouldn't work either. This is why the .Tools package only targets netcoreapp1.0 and net451. We won't be adding "netstandard1.3" to the .Tools packages until we have a solution for #5320.
