### ISSUE TITLE
Publish Microsoft.EntityFrameworkCore.Relational.Tests as a nuget?

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#6176]
EFCore already provider the specification test suites as nuget packages for consumption by providers. This is great as it allows providers to automatically check if they implement EFCore behavior correctly, etc.

There's also Microsoft.EntityFrameworkCore.Relational.Tests, which contains unit (rather than functional/integration) tests on EFCore components. Aside from running these tests directly, base classes in this project are also used by provider-specific unit test suites (e.g. Microsoft.EntityFrameworkCore.SqlServer.Tests.Migrations) to test their own implementations of various EFCore relational components. Since this package isn't published as a nuget it's not possible for external providers to use it, only SqlServer and Sqlite which happen to be in the solution.

It seems like a refactor may be in order: split Microsoft.EntityFrameworkCore.Relational.Tests into one project which contains actual tests to run on relational components, and another project which contains base classes for consumption by providers (and published as a nuget).

This obviously isn't very urgent, I'm currently working around it by copying source files into my own project.

I asked for this before in https://github.com/aspnet/EntityFramework/issues/3016#issuecomment-139851543 but there were definitely more important things back then.

**Comment by rowanmiller** [comment]
@roji do you have some examples of where this provides value and how much code you would save by having it available. We want to understand how much value this would add.

**Comment by ErikEJ** [comment]
I have had no issues with simply copying a couple of files over

**Comment by natemcmaster** [comment]
I found at least one "abstract" test class in the .Relational.Tests project, which, in theory, means it should be in .Relational.Specification.Tests.

@ErikEJ which files do you copy?

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.Tests/ApiConsistencyTestBase.cs 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.Tests/Extensions/EntityFrameworkServiceCollectionExtensionsTest.cs 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.Tests/Extensions/RelationalServiceCollectionExtensionsTest.cs 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.Tests/Migrations/MigrationSqlGeneratorTestBase.cs 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.Tests/Storage/RelationalTypeMappingTest.cs 

Quite a few, apparently!

**Comment by roji** [comment]
I actually have less than @ErikEJ, but should definitely get to work on these. Looking into this was what made me think about having a publicly-available suite. To @ErikEJ's list I can also add ModelDiffer - Npgsql adds migration operations for managing PostgreSQL extensions, and it would be good to be able to run the basic ModelDiffer tests on Npgsql's overridden version (plus add my own).

Again, not the most pressing feature...

**Comment by roji** [comment]
@natemcmaster there currently seems to be a project split between unit tests and functional/integration tests (which actually connect to the database), so I don't know if putting these in .Relational.Specification.Tests is what you want to do. That split may be useful for running quick unit tests vs. slow functional tests.

**Comment by Kagamine** [comment]
@natemcmaster 

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.Tests/Migrations/MigrationSqlGeneratorTestBase.cs

**Comment by ajcvickers** [comment]
Notes for triage:
* ApiConsistencyTestBase: I think it is fine for this to just be copied by those who need it. I think it would also be OK if somebody wanted to take this and publish it as a package which any tests could depend on. The code is not EF specific so it doesn't need to be built and published as part of our build.
* EntityFrameworkServiceCollectionExtensionsTest: These could be moved to the specification/functional tests.
* MigrationSqlGeneratorTestBase: I think these could also be moved to the specification tests, but I would be interested in hearing @bricelam's opinion on it.
* RelationalTypeMappingTest: These tests should only really be testing the common behavior of the base RelationalTypeMapper. It looks like a SQLite test was added that does more than this. I think it might be nice to refactor this, but I don't think it is critical and I don't think other providers should copy this pattern.
* MigrationsModelDifferTestBase: Would be interested in hearing @bricelam's opinion on this one. I think it could be moved to the specification tests, but I also think it's OK for other providers to copy the code if it is useful for them.

**Comment by bricelam** [comment]
RE MigrationsModelDifferTestBase: I vote to let them copy. The model differ is not provider-specific so they shouldn't need to re-test it. We have some tests in SQL Server to ensure that some provider-specific parts of it work, but not every provider should need these. (e.g. SQLite doesn't)

**Comment by ajcvickers** [comment]
@roji @ErikEJ (and anyone else interested). We discussed in triage and we would likely accept pull requests to move the following from the unit tests into the specification tests:
* EntityFrameworkServiceCollectionExtensionsTest
* MigrationSqlGeneratorTestBase

I'm going to close this issue as discussion.
