### ISSUE TITLE
Map one entity to many others

### ISSUE THREAD

**Issue by minimalisticMe** [dotnet/efcore#6192]
Let's say I have the following simplified classes:

```
public class Room
{
    [Key]
    public int RoomID { get; set; }
}

public class Teacher
{
    [Key]
    public int TeacherID { get; set; }
    public Room Room { get; set; }
}

public class Subject
{
    [Key]
    public int SubjectID { get; set; }
    public Room Room { get; set; }
}
```

And I have two `Rooms` Room r1 and Room r2, two `Teachers`  t1 and t2 and two `Subject` s1 and s2. I now want to assign r1 to t1, t2 and s1 and r2 to s2. I would do this by

```
using (var db = new DBContext())
{
    db.Add(r1);
    db.Add(r2);
    db.SaveChanges();

    var rooms = db.Room.ToList(); // rooms now contains both r1 and r2
    db.Add(new Teacher{ Room = r1; }); // t1
    db.Add(new Teacher{ Room = r1; }); // t2
    db.Add(new Subject{ Room = r1; }); // s1
    db.Add(new Subject{ Room = r2; }); // s2
    db.SaveChanges(); // Error shown below
}
```

The error I get is `Inner Exception: "SQLite Error 19: 'FOREIGN KEY constraint failed'."`. So I cannot do this. What is the proper declaration here, to achieve what I want?

What I want to happen: t1, t2 and s1 share all the same Room r1. When I change r1, I want the changes to be visible, when I next load t1, t2 and s1

Project Type: C# UWP
EF Core version: "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0", "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
Operating system: win10 x64 build 10586.494
Visual Studio version: VS2015.3

**Comment by ajcvickers** [comment]
@minimalisticMe I am not able to reproduce what you are seeing with the code you posted. I have posted the complete console application I am using. Can you make appropriate changes to the application so that it throws the exception you are seeing? 
```C#
public class Room
{
    [Key]
    public int RoomID { get; set; }
}

public class Teacher
{
    [Key]
    public int TeacherID { get; set; }
    public Room Room { get; set; }
}

public class Subject
{
    [Key]
    public int SubjectID { get; set; }
    public Room Room { get; set; }
}

public class DBContext : DbContext
{
    public DbSet<Room> Rooms { get; set; }
    public DbSet<Teacher> Teachers { get; set; }
    public DbSet<Subject> Subjects { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("Data Source=RoomsDb");
}

public class Program
{
    public static void Main()
    {
        using (var db = new DBContext())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            var r1 = new Room();
            var r2 = new Room();

            db.Add(r1);
            db.Add(r2);
            db.SaveChanges();

            var rooms = db.Rooms.ToList(); // rooms now contains both r1 and r2
            db.Add(new Teacher
            {
                Room = r1
            }); // t1

            db.Add(new Teacher
            {
                Room = r1
            }); // t2

            db.Add(new Subject {Room = r1}); // s1
            db.Add(new Subject {Room = r2}); // s2

            db.SaveChanges(); // Error shown below
        }
    }
}
```

**Comment by minimalisticMe** [comment]
@ajcvickers please close this issue. I tried the code on a minimal example too and it worked for me as well.

For people in the future with similar sounding problems:
Turned out, I did some wrong referencing stuff in `Teacher` class. As I had a parent key, that did not get filled in, as I created an instance of `Teacher` on it's own instead over the parent.
