### ISSUE TITLE
dotnet ef database drop hangs

### ISSUE THREAD

**Issue by WillBaldwin** [dotnet/efcore#6197]
### Steps to reproduce

From command prompt:

> dotnet ef database drop

Are you sure you want to drop the database 'BRI_SAI-Development' on server 'myserver'? (y/N)

If you answer Y or N the CLI hangs
### The issue

What I was hoping it would do is drop all the tables so that I can code first from a table-less database.  What I expected it to do is drop the database.  
What is  did was hang.

```
Exception message: n/a
Stack trace: n/a

```
### Further technical details

EF Core version: (found in project.json or packages.config)

```
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
"Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-rc2-final",
"Microsoft.EntityFrameworkCore.Tools": {"version": "1.0.0-preview1-final", "type": "build"}
```

Operating system: Win10 Ent
Visual Studio version: VS2015

Other details about my project setup:

**Comment by rdefreitas** [comment]
@WillBaldwin can you reproduce this on RTM?

**Comment by rowanmiller** [comment]
The tooling changed significantly between RC2 and Preview2 (Preview2 of tooling aligns with RTM of the runtime), so this is most likely resolved in Preview2/RTM. If you still see the issue, then feel free to reply and we will re-open.
