### ISSUE TITLE
lazyload when to be active?

### ISSUE THREAD

**Issue by cinaradem** [dotnet/efcore#6200]
lazy load when to be active? We started a great project and we are experiencing performance problems cannot be for lazy load. sql query + n query

**Comment by gdoron** [comment]
@cinaradem Lazy load doesn't solve 1+n queries but (potentially) **cause** them.
 
 I believe the 1+ N queries you see were already fixed in the 1.1.0 branch, but there are still a few around like #5783

**Comment by rowanmiller** [comment]
Lazy loading is tracked by #3797 and will be implemented post-1.1
