### ISSUE TITLE
Scalar composable function support

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#621]
This work item represents the capability to map to scalar composable functions defined by the store so that they can be used in LINQ queries or in update, e.g. as default values (for which they would possibly need to be niladic :trollface:).

**Comment by natemcmaster** [comment]
Would help with #3438.

Idea:
```c#
entityBuilder.Property(e => e.SchemaName).FromSqlFunction("SCHEMA_NAME(object_id)");
```

**Comment by rowanmiller** [comment]
Consolidating several user defined function related enhancements into #4319
