### ISSUE TITLE
Regarding Data Annotations support in EFCore.

### ISSUE THREAD

**Issue by narenkv** [dotnet/efcore#6235]
Hello,

Regarding Data Annotations support in EFCore.

Currently the MaxLength attributes are working fine with model decoration, however we saw that ForeignKey by throwing an error like "System.InvalidOperationException"  "composite primary key"  

Sample decoration which is not supported in EFCore
        [DataMember, Key, Column(Order = 0), ForeignKey("Role")]
        public Int32 RoleId { get; set; }

Could you please update us on 
1. In future can we expect all Data Annotations will be supported
2. Is it a best practice to follow Fluency API when compared to Data Annotations, Could you please share us the benefits in following

Thanks 
Naren

**Comment by ajcvickers** [comment]
@narenkv Column ordering is not currently supported at all, whether using data annotations or not. See issue #2272. This item is currently on our backlog and we don't plan to implement it in the near future. There are several opinions on whether or not it is a good idea and how far to go with it if it is a good idea.

We are unlikely to implement composite key support using data annotations. It has several issues, such as the column order for the table not necessarily being the column order for the key, even though EF6 assumed that it was.

More generally, EF has always supported a subset of data annotations and continues to do so, although the subset has changed slightly. It has also always been the case that data annotations supported only a subset of the configuration that could be done through the fluent API, and this also remains the case in EF Core.

Whether or not using data annotations is best practice or not depends on your design philosophy. If you like them, then feel free to continue using them, but be aware that there may be some types of configuration that you need in your model that cannot be accomplished with data annotations.

**Comment by narenkv** [comment]
Thanks
