### ISSUE TITLE
SQLite query can deadlock with FirstOrDefaultAsync

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#6238]
This as a secondary issue discovered during investigation of https://github.com/aspnet/EntityFramework/issues/6088#issuecomment-236733592. 

This bug appears to be similar issue to #5481
### Steps to reproduce

Full repro project: https://github.com/aspnet/EntityFramework/issues/6088#issuecomment-237302404

``` c#
public static async Task<Participant> GetAsync(ScreenTimeContext dbContext, int participantId)
{
    return (await
    (from r in dbContext.Participants
     where r.Id == participantId
     select r).FirstOrDefaultAsync());
}
```
### The issue

No error message. The app just hangs. The query never returns a value.
### Workaround

Removing the async/await keywords from the method above fixes the issue.
### Further technical details

EF Core version: Microsoft.EntityFrameworkCore.Sqlite 1.0.0
Operating system: UWP 10586 (debug mode...i.e. it's not .NET Native causing the problem)
Visual Studio version: VS2015U3, UWP 1.4.1 tools

**Comment by divega** [comment]
@anpete we suspect this could be an issue with IX-async.

**Comment by anpete** [comment]
@divega @natemcmaster Does it repro against dev?

**Comment by natemcmaster** [comment]
Yes. I just tried with "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0-alpha1-21786"

**Comment by anpete** [comment]
The problem is caused by making an async blocking call on the UI thread. By default, the sync context tries to run the async continuation on the UI thread, which deadlocks because the UI thread is busy waiting for the async operation to complete. Using ConfigureAwait(false) solves the problem.
