### ISSUE TITLE
Is there a way to alter or remove a previously declared index?

### ISSUE THREAD

**Issue by scottste** [dotnet/efcore#6239]
### Steps to reproduce

Create a default project and add a line similar to the following in the OnModelCreating method:

```
builder.Entity<ApplicationUser>()
                .HasIndex(u => new { u.NormalizedUserName, u.AppTenantId })
                .HasName("UserNameIndex")
                .IsUnique();
```
### The issue

I would expect since I'm explicitly passing the index name that any other indexes with the same name would be removed/ignored instead of just adding another index. If this behavior is intended, is there a way to change/delete an index that was previously declared? My use case is that I'm using Identity and would like to change the user name index for a multi-tenant application so that different tenants can have the same username. My current workaround is to just not call the base OnModelCreating method and instead copy everything but the one index line.
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS 2015

**Comment by gdoron** [comment]
Check these methods (available inside a migration)

	migrationBuilder.CreateIndex()
	migrationBuilder.DropIndex()
	migrationBuilder.RenameIndex()
	
> I would expect since I'm explicitly passing the index name that any other indexes with the same name would be removed/ignored instead of just adding another index.

Regarding the drop of the existing index: :scream: :scream: :scream: :scream: 

Regarding multiple indices with the same name:
> `index_name` Is the name of the index. Index names must be unique within a table or view **but do not have to be unique within a database.**

[Spec](https://msdn.microsoft.com/en-us/library/ms188783(v=sql.100).aspx)

**Comment by divega** [comment]
**Triage:** @AndriySvyryd we would like your opinion on what the behavior should be.

**Comment by AndriySvyryd** [comment]
@scottgu Apart from changing the migration as @gdoron mentioned. You can remove the index from the model by using the Model API:
```C#
var applicationUserType = modelBuilder.Model.FindEntityType(typeof(ApplicationUser));
var normalizedUserNameProperty = applicationUserType .FindProperty("NormalizedUserName");
var appTenantIdProperty  = applicationUserType .FindProperty("AppTenantId");
applicationUserType .RemoveIndex(new[] { normalizedUserNameProperty , appTenantIdProperty  });
```

**Comment by gdoron** [comment]
+1 for the ScottGu. ping.. :laughing: 
@AndriySvyryd

**Comment by YehudahA** [comment]
@AndriySvyryd, Your solution doesn't work with foreign keys.

Example:

``` cs
public class Parent
{
    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Child> Children { get; set; }
}

public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ParentId { get; set; }

    public virtual Parent Parent { get; set; }
}

public class AppDbContext : DbContext
{
    public DbSet<Parent> Parents { get; set; }
    public DbSet<Child> Children { get; set; }

        
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=.\sqlexpress;Database=MyDb;Trusted_Connection=True");
        base.OnConfiguring(optionsBuilder);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        var entityMetadata = modelBuilder.Entity<Child>().Metadata;

        var indexes = entityMetadata.GetIndexes().ToList();

        foreach (var index in indexes)
        {
            entityMetadata.RemoveIndex(index);
        }
    }
}

```

Createed migratoin:

``` cs

public partial class Initial : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Parents",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Name = table.Column<string>(nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Parents", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "Children",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Name = table.Column<string>(nullable: true),
                ParentId = table.Column<int>(nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Children", x => x.Id);
                table.ForeignKey(
                    name: "FK_Children_Parents_ParentId",
                    column: x => x.ParentId,
                    principalTable: "Parents",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_Children_ParentId",
            table: "Children",
            column: "ParentId");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Children");

        migrationBuilder.DropTable(
            name: "Parents");
    }
}

```

**Comment by AndriySvyryd** [comment]
@YehudahA The proper way of doing this is tracked by https://github.com/dotnet/efcore/issues/7605. #214 could also mitigate it by removing the convention that adds it.

The best workaround currently is to remove the offending line from the migration.

**Comment by shuegelm** [comment]
> @YehudahA The proper way of doing this is tracked by #7605. #214 could also mitigate it by removing the convention that adds it.
> 
> The best workaround currently is to remove the offending line from the migration.

But that wont remove the index when he is already created, right?

**Comment by roji** [comment]
>> The best workaround currently is to remove the offending line from the migration.
>
> But that wont remove the index when he is already created, right?

No. Migrations only determine operations to be performed on your database: removing a CreateIndex will cause it to not get created if you run the migration (DropIndex is the thing that removes an index from the database).
