### ISSUE TITLE
Raw store access APIs

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#624]
In previous versions of EF we had handy "raw SQL" methods such as SqlQuery and ExecuteSqlCommand that allowed to drop down to the underlying relational provider to execute SQL queries directly (i.e. bypassing the EF mapping) but still take advantage of some of the services provided by EF, e.g. connection management, transaction handling, object materialization and change tracking. 

In EF7 since we support relational as well as non relational providers we should figure out how to extend this concept to specific providers through a consistent pattern, e.g. for Azure Table Storage it probably makes sense to provide access to the underlying objects from the .NET storage client library, while for relational stores being able to access the underlying connection and having something like SqlQuery and ExecuteSqlCommand defined as extension methods probably makes sense.

**Comment by RickyLin** [comment]
hmm, any progress on this?

**Comment by rowanmiller** [comment]
@RickyLin - We haven't started on this yet. It's a fairly isolated feature, so it will be something we work on a little later in the cycle.

**Comment by mikary** [comment]
We have added a ```FromSql``` method for relational ```DbSet<T>```s that allows for materialization, change tracking, and additional querying off of a custom SQL statement. See #1845 and #1871 for more details and examples

**Comment by NicoJuicy** [comment]
In the meantime, you could probably use a extension method like this 

public static int ExecuteSqlCommand(this RelationalDatabase database, string sql)
    {
        using (var connection = database.Connection)
        {
            using (var command = connection.DbConnection.CreateCommand())
            {
                command.CommandText = sql;
                return command.ExecuteNonQuery();
            }
        }

    }

**Comment by bricelam** [comment]
@NicoJuicy Looks [eerily familiar](http://stackoverflow.com/a/30487747/475031)... :wink:

**Comment by mikary** [comment]
@rowanmiller most of the functionality in this issue is covered by a combination of ```FromSql```, #1862, and #1863 

The only other facet is using a raw command on a non-relational store. Should we still keep this issue open as a reminder on the backlog, or is this something we can close?

**Comment by rowanmiller** [comment]
@mikary yes I agree that those cover the remaining cases from this item

**Comment by rowanmiller** [comment]
non-relational providers can do whatever makes sense for that particular store, so I don't think we need a general item.

**Comment by kant2002** [comment]
Would be good to provide async version of #1863 (ExecuteSqlCommandAsync) as it was earlier. It's strange to have all API's Async but for this one only sync version.

**Comment by rowanmiller** [comment]
Clearing milestone so that we can discuss in triage. I think we have done almost everything here though we should discuss the async request from @kant2002

**Comment by divega** [comment]
@rowanmiller agreed. The lack of async ExecuteSqlCommand is an oversight (thanks @kant2002!). I will just re-open #1863 and assign it to @mikary to track that. We can probably just close this one now.
