### ISSUE TITLE
Decide how data annotations on fields should work

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#6267]
Currently data annotations on fields are used if and only if the field is mapped and has no property associated. For example, the Key attribute will be applied in this case:

``` C#
public class Foo
{
    [Key]
    private int _key;
}
```

assuming _key is a mapped field:

``` C#
builder.Entity<Foo>().Property("_key");
```

The data annotation will not be applied in this case:

``` C#
public class Foo
{
    [Key]
    private int _key;

    public int Key => _key;
}
```

It is instead expected that the data annotation will be taken from the property.

If we decide to allow data annotations to be applied to fields that have associated properties, then we also need to decide what to do when the field and the property have conflicting annotations:

``` C#
public class Foo
{
    [Column("KEY")]
    private int _key;

    [Column("ID")]
    public int Key => _key;
}
```

**Comment by divega** [comment]
We like it the way @ajcvickers implemented it, e.g. an annotation on the property always override the one on the field.
