### ISSUE TITLE
EntityFramework package (not core), has bad frameworkassembly values

### ISSUE THREAD

**Issue by rrelyea** [dotnet/efcore#6272]
### Steps to reproduce

originally filed as: https://github.com/NuGet/Home/issues/3279
**Repro Steps:**
1. Create a new project C#-> Windows 8->Windows Runtime Component (Windows 8.1).
2. Right-click the project node and click "Manage NuGet Packages…" menu to start package manager.
3. Install package “EntityFramework”, and verify it can be installed.

**Expected Result:**
The package “EntityFramework” can be installed correctly.

**Actual Result:**
The package “EntityFramework” can’t be installed as below screenshot.

![untitled841](https://cloud.githubusercontent.com/assets/20632775/17431510/f8150424-5b2c-11e6-9642-e5a3735887e3.png)

**Note:**
It happened on Dev14 U3+NuGet Dev 1731(3.6.0.1731).
It repro on any version of package “EntityFramework”.
It also repro on Dev14 U3 (NuGet 3.4.4.1321).
### The issue

NuGet sees 
`<FrameworkAssembly` ... TargetFramework="" />
TargetFramework should not be empty, but should be Net40 or Net45.

When you don't specify a framework, nuget thinks this works in all TFMs. Thus the package seemed to install on this Win8.1 project, while it should fail.
### Further technical details

None.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework6#48
