### ISSUE TITLE
Migrations, EF detects pending changes which are already in the table history 

### ISSUE THREAD

**Issue by tango-charly** [dotnet/efcore#6278]
Hi,

My Team uses TFS and Visual Studio 2015 on his project.

The Control Version is ok, but when someone do a migration, and someone else try to run a new migration, EF detect pending changes.
We got the latest version of code source,  and the table migration_history have the latest migrations run ! We can't run an update database beacause columns and constraints already exists.
And the personn who did the latest migration is the only one who can add a new migration... In this case, EF work well.

PS : Sorry i can't share my solution

**Comment by divega** [comment]
@tango-charly is your team using EF6 or EF Core?

**Comment by audacity76** [comment]
Hi. The same happened to me, too. Each time I ran the migration the same migrations steps (which already were applied) appeared in the migration (Up/Down). Even if I fired the migration command twice (without any changes). 

I had done some customizations inside the ModelBuilder which caused this: (maybe the ef team can tell me why this happens)

```
// remove all foreign key indexes
var entityTypes = modelBuilder.Model.GetEntityTypes().Select(e => e.ClrType).ToList();
            foreach (var entityType in entityTypes)
            {
                var foreignKeys = modelBuilder.Entity(entityType).Metadata.GetForeignKeys();
                
                foreach (var index in modelBuilder.Entity(entityType).Metadata
                    .GetIndexes()
                    .Where(i => i.Properties.All(p => p.GetContainingForeignKeys().Any()))
                    .ToList())
                    modelBuilder.Entity(entityType).Metadata.RemoveIndex(index.Properties);
            }
// other stuff...
// add all foreign key indexes
 foreach (var entityType in entityTypes)
            {
                var tableName =
                    modelBuilder.Entity(entityType).Metadata.GetAnnotations().FirstOrDefault(a => a.Name == "Relational:TableName")?.Value
                    ?? entityType.Name;

                foreach (var foreignKey in modelBuilder.Entity(entityType).Metadata.GetForeignKeys())
                {
                    var properties = foreignKey.Properties;
                    if (properties.Any(p=> p.DeclaringEntityType.ClrType != entityType && entityTypes.Contains(p.DeclaringEntityType.ClrType))
                        || properties.All(p => p.GetContainingPrimaryKey() != null))
                        continue;

                    var names = properties.Select(n => n.Name).ToArray();
                    var key = string.Join("_", names);

                    modelBuilder.Entity(entityType)
                        .HasIndex(names)
                        .IsUnique(foreignKey.IsUnique)
                        .HasName($"IX_FK_{tableName}_{key}");
                }
            }
```

EF Core 1.0.0

**Comment by tango-charly** [comment]
Hi, 

Thank's for your replies, we are using EF 6.0 not EF Core.

**Comment by ajcvickers** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by joaorabelo** [comment]
Some correction or solution ? 
https://stackoverflow.com/questions/19136066/why-does-add-migration-sometimes-create-duplicate-migrations
