### ISSUE TITLE
How to call a stored procedure

### ISSUE THREAD

**Issue by 188** [dotnet/efcore#6283]
How to call a stored procedure in EF core 1.0

**Comment by ajcvickers** [comment]
@188 You probably want to use `context.Database.ExecuteSqlCommand`, or the FromSql  method, which is documented here: https://docs.efproject.net/en/latest/querying/raw-sql.html

Please be more specific with your question if this information does not answer it.

**Comment by Vasimovic** [comment]
@188 if you want to map to a DbSet<model> from a stored procedure use the fromSql function

Example:

`
var data = db.Set<SomeDbSetModel>().FromSql("yourStoredProcedure p0, p1").ToList();
`

**Comment by 188** [comment]
Thanks

**Comment by josepoma** [comment]
Hi @Vasimovic,@188

In this example : 
`var data = db.Set<SomeDbSetModel>().FromSql("yourStoredProcedure p0, p1").ToList(); `

If in the stored procedure there is no ID column, EFCore displays the error message: 

> The entity type "SomeDbSetMode" requires a key to be defined.

As you can fix this ?, because it can be procedures that do not need to return an ID column.

Jose Poma

**Comment by gdoron** [comment]
It's currently not supported for FromSql to returned a not mapped CLR entity :(

**Comment by Vasimovic** [comment]
As @gdoron said currently not supported, I believe support will be added in 1.0.1 release

If possible you could try adding [Key] to one of the columns and use the AsNoTracking() for now

`var data = db.Set<SomeDbSetModel>().AsNoTracking().FromSql("yourStoredProcedure p0, p1").ToList();`

**Comment by divega** [comment]
@Vasimovic FWIW the feature at https://github.com/aspnet/EntityFramework/issues/1862 is planned for 1.1.0, not 1.0.1. The latter is a patch release containing a few high priority bug fixes.

**Comment by gdoron** [comment]
@divega Since the versions thing was discussed.
Do you know:

1. When is the release date of 1.0.1, it was said to be ~Auguest, which ends in 2 days.
2. Is there going to be a preview release of 1.1.0 just like there was with RC1+2?
If the answer is yes, do you know when?

Thanks Diego!

**Comment by divega** [comment]
@gdoron I don't have specific dates to share, but 1.0.1 will ship soon, and yes, there will be preview releases of 1.1.0. 

cc @Eilon in case he can share specific dates.

**Comment by Eilon** [comment]
@gdoron we were initially planning to do 1.0.1 in August but for a variety of reasons we had to delay it - currently planned for September. You can already get the pre-release patched bits here: https://dotnet.myget.org/gallery/aspnetcore-patch .

For 1.1.0 there will definitely be previews before 1.1.0 RTM. We're working on finalizing the dates, but expect something in ~1 - 1.5 months.
