### ISSUE TITLE
Master-slave, how?

### ISSUE THREAD

**Issue by SF-Simon** [dotnet/efcore#6297]
@ajcvickers 
If we have two databases, in which the A database is used to read, the B database is used to write. There is no convenient way, you can easily achieve this function. Their tables and fields are exactly the same, only to load balance and set the master and slave settings.
The need for this guy and I think it should be consistent:#6231

**Comment by DivenLee** [comment]
Supplement, when I execute a select statement (select * from test), is from a database in the execution and return, but when we perform insert and update statements, etc. These are not query the SQL statement is B database to perform. Then the A database and the B database have been done with the sync settings, and they will sync their own information.

**Comment by KalibGao** [comment]
Hey @rowanmiller
We also have the same queries about master-slaves and master-master database design in the ef core .
Thanks for the open dotnet contributions. Any good news about it, let us know .

**Comment by divega** [comment]
We think #6525 could help with this. Closed as view it on GitHub, or mute the thread.
