### ISSUE TITLE
Partial class with ienumerable of local c#class not working anymore

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/efcore#6299]
I have a table in my database called sections with multiple subsections and each section int the tree can have fields. To create a path for the fields when displaying them I have created a partial class with an enumerable of my own class that contains the full path to where in the section tree a field is. This worked beautifully in EF6 but now I am trying to get it to work with EF7 as our two new projects are all-in with dotnetcore and efcore.

I get an error about a key not being defined at a class that is not in the database. I have tried to define a key and set the class to a complextype but it is not working.

This is my dbmodel of the table Sections:

``` C#
public partial class Sections
    {
        public Sections()
        {
            FormSectionFields = new HashSet<FormSectionFields>();
            FormSections = new HashSet<FormSections>();
            FormSectionSectionsSection = new HashSet<FormSectionSections>();
            FormSectionSectionsSubSection = new HashSet<FormSectionSections>();
            SectionLanguages = new HashSet<SectionLanguages>();
        }

        public int SectionId { get; set; }
        public string Section { get; set; }
        public bool InlineHelpText { get; set; }
        public bool IsGlobal { get; set; }
        public string DependencyExpression { get; set; }
        public DateTime RevisionDate { get; set; }
        public string CssClasses { get; set; }
        public int CreateById { get; set; }
        public DateTime CreateDate { get; set; }
        public int UpdateById { get; set; }
        public DateTime UpdateDate { get; set; }

        public virtual ICollection<FormSectionFields> FormSectionFields { get; set; }
        public virtual ICollection<FormSections> FormSections { get; set; }
        public virtual ICollection<FormSectionSections> FormSectionSectionsSection { get; set; }
        public virtual ICollection<FormSectionSections> FormSectionSectionsSubSection { get; set; }
        public virtual ICollection<SectionLanguages> SectionLanguages { get; set; }
    }
```

And this is my partial class together with my own class.

``` C#
public partial class Sections
    {
        public IEnumerable<FieldWithPath> AllFields
        {
            get
            {
                return FormSectionFields.Select(sf => new FieldWithPath(sf.FormField)).Concat(FormSectionSectionsSection.SelectMany(ss => ss.SubSection.AllFields)).Select(f => f.UnderSection(this));
            }
        }
    }

public class FieldWithPath
    {
        public FieldWithPath(Models.FormFields field) : this(field, new List<Models.Sections>()) { }


        public FieldWithPath(Models.FormFields field, IEnumerable<Models.Sections> path)
        {
            this.Field = field;
            this.Path = path;
        }
        public Models.FormFields Field;
        public IEnumerable<Models.Sections> Path;

        public FieldWithPath UnderSection(Models.Sections section)
        {
            var path = new List<Models.Sections> { section };
            path.AddRange(Path);
            return new FieldWithPath(Field, path);
        }
    }
```

```
Exception message: InvalidOperationException: The entity type 'FieldWithPath' requires a key to be defined.
Stack trace:
```

EF Core version: 1.1.0-alpha1-*
Operating system: Windows 10
Visual Studio version: VS 2015 Update 3

Other details about my project setup:
dotnet core 1.1.0-alpha1-\* web project

**Comment by ajcvickers** [comment]
@johanskoldekrans This is likely because navigation properties can be IEnumerables in EF Core, whereas in EF6 they had to be ICollections. This means that AllFields is being picked up as a navigation property, which is bringing in FieldWithPath as an entity type. If so, then try doing:
```C#
modelBuilder.Ignore<FieldWithPath>();
```

**Comment by johanskoldekrans** [comment]
@ajcvickers Thanks! So I guess there isnt an annotation yet I can use?

**Comment by ajcvickers** [comment]
@johanskoldekrans I think you could put [NotMapped] on the navigation property, but I haven't tried it.

**Comment by johanskoldekrans** [comment]
I will try it and let know!

**Comment by johanskoldekrans** [comment]
@ajcvickers Using [NotMapped] worked just fine! And it helps since I need to scaffold now and then and loose my changes (I'm working database first). Btw, this works just fine as it is except that scaffolding keeps adding the connection string to the contextclass instead of the recommended way.

So should I close this?

Ps. Good work to all of the team, can't remember when you can actually use beta or alpha products in production like we could with dotnetcore and with ef7.
