### ISSUE TITLE
Tooling to convert EDMX to Code-First

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/efcore#630]
Since EF7 won't support EDMX based config would be important to have a way to migrate EDMX based code to Code-First

**Comment by rowanmiller** [comment]
We aren't planning to tackle this in the official EF repo. We do agree this would be helpful and someone on our team or one of our community members could do this as a pet project.

**Comment by StingyJack** [comment]
FWIW, I dont understand why the [issue I logged](https://github.com/aspnet/EntityFramework.Docs/issues/1478) is being linked to this one. I use EDMX created from an existing database so I can use them in dynamic data web apps (not sites). I'm not using it for "code first" or whatever that is.   

I'd not use EF at all but I dont think I have other working options for providers.

**Comment by ErikEJ** [comment]
@stingyjack Could you use reverse engineering, for example using EF Core Power Tools?

**Comment by StingyJack** [comment]
@ErikEJ - I could always decompile or write something. But why should I have to do either when code already exists to be ported.
