### ISSUE TITLE
Skip and Take appear to be running in memory rather than in the database

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/efcore#6302]
Execute a a query with Include, Where, OrderBy, Skip and Take against SQL Server 2012

Note the generated SQL does not have any rowoffset or OrderBy components, this appears to happen after fetching the entire recordset into memory. My table has 200,000 rows.. not good

EF Core version: 1.0.0
Operating system: Windows 10 Anniversary Update
Visual Studio version: 2014 Update 3

Some queries work and do generate the correct paging, some don't.

**Comment by ErikEJ** [comment]
Pls share some code

**Comment by johnkwaters** [comment]
It's a lot of code to share. I just found out too that if you have any kind of Where condition, it works fine. But if there is no Where (but there IS a Skip and Take), it forgets to add the paging to the query. Does that help?

**Comment by johnkwaters** [comment]
Hmmm. I was wrong. I can share some code if it helps.... I have a Sql Server database with an Events table, which has references to some other tables, for instance Office.
Here is the base Query: 

        private IQueryable<DbEvent> MakeEventQuery(EventQuery q)
        {
            var qry = Ctxt.Events
                .Include(e => e.ModifiedByUser)
                .Include(e => e.EFolder)
                .Include(e => e.Office)
                .Include(e => e.Project)
                .ThenInclude(p => p.ProjectStatus)
                .AsQueryable();

            if (q.OfficeId.HasValue)
            {
                qry = qry.Where(e => e.OfficeId == q.OfficeId.Value);
            }
            if (q.EventType.HasValue)
            {
                qry = qry.Where(e => e.EventTypeId == (int)q.EventType.Value);
            }
            if (!string.IsNullOrEmpty(q.Text))
            {
                var terms = q.Text.Split(' ');
                foreach (var term in terms)
                {
                    int projectNo;
                    qry = int.TryParse(term, out projectNo) ?
                        qry.Where(p => Convert.ToString(p.ProjectId).Contains(term) || p.Description.Contains(term)) :
                        qry.Where(p => p.Description.Contains(term));
                }
            }
            return qry;
        }

I call that method to get my base query with Includes and Where, then I add sorting and paging and execute it:

            var qry = MakeEventQuery(q);
            var pagedqry = QueryHelper<DbEvent>.ApplySortingPaging(qry, q);
            var res = Mapper.Map<IEnumerable<EventLite>>(await pagedqry.ToListAsync());

The sorting paging goes like this:

    public static class QueryHelper<T>
    {
        public static IQueryable<T> ApplySortingPaging(IQueryable<T> qry, QueryBase q)
        {
            if (q.SortDescriptors != null && q.SortDescriptors.Any())
            {
                foreach (var sd in q.SortDescriptors)
                {
                    qry = sd.Ascending ? qry.OrderByProperty(sd.FieldName) : qry.OrderByPropertyDescending(sd.FieldName);
                }                
            }
            if (q.PageNo == 0 && q.PageSize == 0)
            {
                return qry;
            }
            return qry.Skip(q.PageNo * q.PageSize).Take(q.PageSize);
        }
    }

And the helper methods are for sorting on nested properties:

public static class SortingHelper
    {
        private static readonly MethodInfo OrderByMethod =
            typeof(Queryable).GetMethods().Single(method =>
           method.Name == "OrderBy" && method.GetParameters().Length == 2);

        private static readonly MethodInfo OrderByDescendingMethod =
            typeof(Queryable).GetMethods().Single(method =>
           method.Name == "OrderByDescending" && method.GetParameters().Length == 2);

        public static bool PropertyExists<T>(string propertyName)
        {
            return typeof(T).GetProperty(propertyName, BindingFlags.IgnoreCase |
                BindingFlags.Public | BindingFlags.Instance) != null;
        }

        public static MemberExpression NestedExpressionProperty(Expression expression, string propertyName)
        {
            var parts = propertyName.Split('.');
            var partsL = parts.Length;

            return (partsL > 1)
                ?
                Expression.Property(
                    NestedExpressionProperty(
                        expression,
                        parts.Take(partsL - 1)
                            .Aggregate((a, i) => a + "." + i)
                    ),
                    parts[partsL - 1])
                :
                Expression.Property(expression, propertyName);
        }

        public static IQueryable<T> OrderByProperty<T>(
           this IQueryable<T> source, string propertyName)
        {
            var paramterExpression = Expression.Parameter(typeof(T));
            Expression orderByProperty = NestedExpressionProperty(paramterExpression, propertyName);
            var lambda = Expression.Lambda(orderByProperty, paramterExpression);
            var genericMethod =
              OrderByMethod.MakeGenericMethod(typeof(T), orderByProperty.Type);
            var ret = genericMethod.Invoke(null, new object[] { source, lambda });
            return (IQueryable<T>)ret;
        }

        public static IQueryable<T> OrderByPropertyDescending<T>(
            this IQueryable<T> source, string propertyName)
        {

            var paramterExpression = Expression.Parameter(typeof(T));
            Expression orderByProperty = NestedExpressionProperty(paramterExpression, propertyName);
            var lambda = Expression.Lambda(orderByProperty, paramterExpression);
            var genericMethod =
              OrderByDescendingMethod.MakeGenericMethod(typeof(T), orderByProperty.Type);
            var ret = genericMethod.Invoke(null, new object[] { source, lambda });
            return (IQueryable<T>)ret;
        }
    }

This code works nicely in many of the queries (ApplySortingPaging), but not in this particular one

I am sorting default by e.ModifiedOn

**Comment by johnkwaters** [comment]
Hmmm.... I am going to delete this, there are some iffy things going on in my sorting helper for thie particular query.
