### ISSUE TITLE
Best practice to incorporate a view for now

### ISSUE THREAD

**Issue by johanskoldekrans** [dotnet/efcore#6310]
I have a view that a need to access with pivoted data in the database. Since EF7 doesn't support views yet, I was wondering how to go about this for now. I have created a class as below and used DataAnnotations to set a key. And in a partial class of the dbcontext I have included the view as a virtual DbSet.

``` C#
    public class vCustomersFields
    {
        public int CustomerID { get; set; }
        [Key]
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
    }

    public partial class AppDbContext : DbContext
    {
        public virtual DbSet<vCustomersFields> vCustomersFields { get; set; }
    }
```

Is this the way to go?! It works like a charm but that doesn't make it right...

EF Core version: 1.1.0-alpha1

**Comment by divega** [comment]
Yes, to the degree that views can be treated as if they were tables, things should work. E.g. query should be the same, updates will only work if the view is updatable and for DDL operations (e.g. table creation and modification) in migrations you will have to replace what EF creates with your own custom SQL.
