### ISSUE TITLE
ATS functional tests have some rough edges

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#633]
The AtsOptimisticConcurrencyTests make use of the default convention ModelBuilder. If the AtsModelBuilder is used instead the tests stop working. This appears to be because columns are being configured as Identity and getting temporary values, which are then persisted since the columns are not really Identity. It works at the moment because the data is clean each run so there are no conficts.

The AtsOptimisticConcurrencyTests first get partition and row key setup as a composite primary key, then have it replaced by a simple primary key. We should clarify what PartitionAndRowKey is supposed to do--should it define the primary key? What if the primary key is already defined? Note that relationships in the Northwind model do not work with composite primary keys, which is probably why the key is defined and then redefined.

The NorthwindQueryFixture tests do use a composite primary key, but the relationships in the model do not. This is likely to cause some issues at some point when FKs and PKs don't really line up anymore.

In general, building different models for different tests is not handled well and needs to be cleaned up.

**Comment by rowanmiller** [comment]
Closing as ATS provider is currently not in our working code base
