### ISSUE TITLE
SQL Server: Possible perf optimization leveraging autocommit transactions in SaveChanges()

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#6342]
By default every Transact-SQL statements is executed in [autocommit](https://technet.microsoft.com/en-us/library/ms187878.aspx) mode, meaning that it will be automatically committed if it succeeds and rolled back if it fails. In theory when `SaveChanges()` gets invoked with only one changed object which doesn't have database generated values, we shouldn't need to wrap the statement in a transaction.

**Comment by gdoron** [comment]
Nice idea.
I guess it would be an opt-in feature since you don't really know whether the DB default transactions mode has been changed.
Right

**Comment by divega** [comment]
**Triage:** we want to understand the actual benefit of this before we prioritize it.

**Comment by divega** [comment]
> I guess it would be an opt-in feature since you don't really know whether the DB default transactions mode has been changed.

@gdoron are you talking about [`SET IMPLICIT_TRANSACTIONS ON`](https://msdn.microsoft.com/en-us/library/ms187807.aspx) or is there any other way to affect the default transaction mode? We should try it but incidentally I believe things would work similarly for most cases as long as the `DbContext` controls connection opening and closing (maybe we only apply the optimization if that is the case).

**Comment by AndriySvyryd** [comment]
There was no measurable difference, SQL Client probably already optimizes this

**Comment by divega** [comment]
@AndriySvyryd thanks for the promt investigation. Closing.
