### ISSUE TITLE
Excluding Property using Fluent API not working(Ignore/Not mapped functionality not working)

### ISSUE THREAD

**Issue by kkbajaj** [dotnet/efcore#6344]
In my Solution i have two DB context.
in one of my model  i want one property should not be mapped and that is only for one DB context.

means in one db context model has all properties and in other db context one property should not be mapped.

i used Fluent api to exclude as mention here http://ef.readthedocs.io/en/latest/modeling/included-properties.html

and my code is look like 

``` C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>(entity =>
            {
                entity.ForSqlServerToTable("Blog");
                entity.Ignore(e => e.LoadedFromDatabase);
                entity.Property(e => e.BlogId ).ValueGeneratedOnAdd();
            });
        }
```
### The issue

The issue is when i try to add migration using add-migration syntax for this DB context, my Visual Studio get crashed/restarts without generating migration script.

that generating script works fine if i comment out `entity.Ignore(e => e.LoadedFromDatabase);`

is this related to some EF core issue. do this has any workaround?
### Further technical details

EF Core version: 1.1.0-alpha1-21879
Operating system: Windows 8.1
Visual Studio version: VS2015 update 3

**Comment by divega** [comment]
@kkbajaj there is no known issue with migrations in EF Core that could cause Visual Studio to crash as you describe. We would really want to get to the bottom of it but we will need some help. Could you provide a project that repros the issue for you?

**Comment by kkbajaj** [comment]
@divega  i cannot provide my original Code. but i will try to extract the code and create separate solution which reproduce the issue. will update soon. thanks.

**Comment by divega** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. Please reactivate when you can provide a repro.
