### ISSUE TITLE
Can't delete nested entity

### ISSUE THREAD

**Issue by YuriiNskyi** [dotnet/efcore#6345]
For the brevity I've left only the code, which generates this situation.
I have two simple models:

```
  public class Library
    {
        [Key]
        [StringLength(450)]
        public string LibraryId { get; set; }

        public string Name { get; set; }

        public Address Address { get; set; }
    }

    public class Address
    {
        [Key]
        [StringLength(450)]
        public string AddressId { get; set; }

        public string StreetName { get; set; }
    }
```

For example, I'm creating this models:

```
           var address = _dbContext.Addresses.Add(new Models.Address()
            {
                AddressId = "addressid",
                StreetName = "Test street name"
            }).Entity;
            _dbContext.Libraries.Add(new Models.Library()
            {
                LibraryId = "libraryid",
                Name = "Test library",
                Address = address
            });
            await _dbContext.SaveChangesAsync();
```

Then, trying to delete nested entity `Address`:

```
var library = _dbContext.Libraries.AsNoTracking().Include(x => x.Address).SingleOrDefault(x => x.LibraryId == "libraryid");
            library.Address = null;
            _dbContext.Entry(library).State = EntityState.Modified;
            await _dbContext.SaveChangesAsync();
```

The problem is, that there is nothing happens, entity `Address` still exists and connected with `Library`.

If change `library.Address = null;` to `_dbContext.Addresses.Remove(library.Address);`, it throws error: 

> The DELETE statement conflicted with the REFERENCE constraint \"FK_Libraries_Addresses_AddressId\". The conflict occurred in database \"TestDatabase\", table \"dbo.Libraries\", column 'AddressId'.\r\nThe statement has been terminated.

What's wrong with this, and how should I fix it?

EF Core version: ("Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
Operating system: Windows 10
Visual Studio version: VS 2015

**Comment by ajcvickers** [comment]
@RepositoryNY First, you should update to the RTM release of EF Core.

Second, there are some issues with your code. You are querying with NoTracking, which means that EF isn't keeping track of the changes made. If you're going to make changes and then persist them to the database, then it would be much better to query with tracking enabled. 

In the code as posted, EF has no idea that the Address navigation property has been nulled out because EF is not tracking the entity when you make the change. So when you save it, EF has no idea that there is any change to save. Even if EF was tracking the objects, the relationship is optional by default (because you don't map the FK and you don't tell EF that it is Required) and so EF would null out the AddressId FK, but would not delete the Address.

When you do the Remove call instead, EF will mark the address entity as deleted and will delete it when SaveChanges is called. But the AddressId FK on library is still referring to the Address that you are trying to delete, so the database reports a constraint violation.

This should work:
```C#
var library = _dbContext.Libraries
   .Include(x => x.Address)
   .SingleOrDefault(x => x.LibraryId == "libraryid");

_dbContext.Addresses.Remove(library.Address);
await _dbContext.SaveChangesAsync();
```
If you make the relationship required, then you can do `library,Address = null;` instead of the Remove call. If you need to do with with entities that aren't tracked, then call Attach on the library object before doing anything and then do the delete or null.

**Comment by RepositoryNY** [comment]
I've understood all what have been written. But one thing can't leave me alone. I understand how to delete entities in such way. But how can I delete **relationship** between entities? I don't want delete `library` and 'address', I just want separate them, delete `library.address` link. How should I do this?

**Comment by ajcvickers** [comment]
@RepositoryNY 
```C#
var library = _dbContext.Libraries
   .Include(x => x.Address)
   .SingleOrDefault(x => x.LibraryId == "libraryid");

library.Address = null;
await _dbContext.SaveChangesAsync();
```

**Comment by RepositoryNY** [comment]
@ajcvickers That's the point! I tried this code, it does nothing! I'm still have relationship between `Library` and `Address`

**Comment by ajcvickers** [comment]
@RepositoryNY Here is a complete console application using your code. This application works for me with the RTM release of EF Core. Can you please look at this and make whatever changes are necessary to reproduce the issue you are seeing.
```C#
public class Library
{
    [Key]
    [StringLength(450)]
    public string LibraryId { get; set; }

    public string Name { get; set; }

    public Address Address { get; set; }
}

public class Address
{
    [Key]
    [StringLength(450)]
    public string AddressId { get; set; }

    public string StreetName { get; set; }
}

public class Program
{
    public class MyDbContext : DbContext
    {
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Library> Libraries { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=LibsAndAds;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    static void Main(string[] args)
    {
        using (var context = new MyDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var address = context.Addresses.Add(new Address()
            {
                AddressId = "addressid",
                StreetName = "Test street name"
            }).Entity;

            context.Libraries.Add(new Library()
            {
                LibraryId = "libraryid",
                Name = "Test library",
                Address = address
            });

            context.SaveChanges();
        }

        using (var context = new MyDbContext())
        {
            var library = context.Libraries
               .Include(x => x.Address)
               .SingleOrDefault(x => x.LibraryId == "libraryid");

            // Library is associated with address
            Debug.Assert(library.Address != null);

            library.Address = null;
            context.SaveChanges();
        }

        using (var context = new MyDbContext())
        {
            var library = context.Libraries
               .Include(x => x.Address)
               .SingleOrDefault(x => x.LibraryId == "libraryid");

            // Library is no longer associated with address
            Debug.Assert(library.Address == null);

            var address = context.Addresses.Single();

            // Address still exists
            Debug.Assert(address != null);
        }
    }
}
```
