### ISSUE TITLE
How to avoid complex insert queries

### ISSUE THREAD

**Issue by moander** [dotnet/efcore#6358]
I can't figure out how to do simple inserts without having the result merged and returned back. 

```
using (var db = new MyDb())
{
    db.Something.Add(foo);
    db.Something.Add(bar);
    db.SaveChanges();
}
```

When db is disposed after SaveChanges I see no reason to
- INSERT into @toInsert1
- MERGE into Something
- OUTPUT into @inserted1
- SELECT @inserted1 back to client

Am I missing something?

**Comment by ajcvickers** [comment]
@moander The SQL is written this way to support store generated values in batch inserts. You should be seeing simpler SQL generated for cases where there are no store-generated values and for cases where there is only a single entity being updated. If this is not the case, then please feel free to reactivate the bug with a repro.

**Comment by moander** [comment]
Thanks @ajcvickers. I was able to simplify the generated query but it required a schema change. It would be nice to have some way of forcing the simple insert behavior :)

After removing the identity column I see:
```sql
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [People2] ([Id], [Name])
VALUES (@p0, @p1),
(@p2, @p3);
',N'@p0 int,@p1 nvarchar(4000),@p2 int,@p3 nvarchar(4000)',@p0=1,@p1=N'Foo',@p2=2,@p3=N'Bar'
```
instead of:
```sql
exec sp_executesql N'SET NOCOUNT ON;
DECLARE @toInsert1 TABLE ([Name] nvarchar(max), [_Position] [int]);
INSERT INTO @toInsert1
VALUES (@p0, 0),
(@p1, 1);

DECLARE @inserted1 TABLE ([Id] int, [Name] nvarchar(max), [_Position] [int]);
MERGE [People] USING @toInsert1 AS i ON 1=0
WHEN NOT MATCHED THEN
INSERT ([Name])
VALUES (i.[Name])
OUTPUT INSERTED.[Id], INSERTED.[Name], i._Position
INTO @inserted1;

SELECT [Id] FROM @inserted1
ORDER BY _Position;
',N'@p0 nvarchar(4000),@p1 nvarchar(4000)',@p0=N'Foo',@p1=N'Bar'
```
