### ISSUE TITLE
Reverse-Engineer: Scaffold-DbContext on ASP.NET Core - minor issue with generated namespace value

### ISSUE THREAD

**Issue by Listbd** [dotnet/efcore#6369]
### Steps to reproduce

Found when using this tutorial https://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html with a project name that contains dashes (e.g. my-really-cool-api)
### The issue

The generated namespace value contains dashes and is therefore not valid.
`namespace my-really-cool-api.Models`
### Workaround

Simply replace the namespace with the correct name (which VS correctly figures out when generating other project items), using underscores instead of dashes:
`namespace my_really_cool_api.Models`
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 8.1
Visual Studio version: VS 2015 Update 3

Other details about my project setup:
Targeting .NET Framework 4.5.2

**Comment by divega** [comment]
**Triage:** wherever we are pulling the namespace from, we should scrub it to make it look like C# like we do with table names.

**Comment by webprofusion-chrisc** [comment]
.. also a switch to set the namespace (e.g. Corporation.ProjectName.Data) rather than basing it on the folder path would be great.

**Comment by lajones** [comment]
I tried to repro this on the 2.0.0 code but could not - the code replaced dashes by underscores as expected. Closing as non-repro but feel free to re-open if you feel I missed something.

We are using #3988 to track potential changes to namespaces of the generated code.
