### ISSUE TITLE
migrations added default to unusable path

### ISSUE THREAD

**Issue by bigteejay** [dotnet/efcore#6374]
### Steps to reproduce

```
D:> dotnet ef migrations add BlankDb
Project TestProj (.NETCoreApp,Version=v1.0) will be compiled because Input items removed from last build
Compiling TestProj for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:06.3254026

Done. To undo this action, use 'dotnet ef migrations remove'

D:> dotnet ef database update BlankDb
Project TestProj (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
The migration 'BlankDb' was not found.
```

I know there is the -o flag to drop the generated migration into another folder, and I can have it drop in Models so it "just works", but this took some time to troubleshoot awhile back.  It would be nice if either: 
1. the update command defaulted to searching in the same place that Migrations are added to (just as running the migrations add finds the DbContext in the Models subfolder)
2. update command had a switch to specify the location of migrations
3. or it mentioned the location it was searching in.
### The issue

Not clear that migrations need to be in the same folder as DbContext to be applied to db.  Not clear that message that seems to indicate that db was updated with migrations (if no migration name specified) actually did (essentially) nothing.

Exceptions details:

```
System.InvalidOperationException: The migration 'BlankDb' was not found.
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsAssemblyExtensions.GetMigrationId(IMigrationsAssembly assembly, String nameOrId)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.PopulateMigrations(IEnumerable`1 appliedMigrationEntries, String targetMigration, IReadOnlyList`1& migrationsToApply, IReadOnlyList`1&migrationsToRevert)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<GetMigrationCommandLists>d__13.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
```
### Further technical details

EF Core version: (found in project.json or packages.config)

```
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",

...

"tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
    "version": "1.0.0-preview2-final",
    "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
    ]
},
```

Operating system: Win7 Pro SP1
Visual Studio version:

> Microsoft Visual Studio Professional 2015
> Version 14.0.25425.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01055
> 
> Installed Version: Professional
> 
> LightSwitch for Visual Studio 2015   00322-40000-00000-AA482
> Microsoft LightSwitch for Visual Studio 2015
> 
> Microsoft Visual Studio Tools for Applications 2015   00322-40000-00000-AA482
> Microsoft Visual Studio Tools for Applications 2015
> 
> Visual Basic 2015   00322-40000-00000-AA482
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-40000-00000-AA482
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-40000-00000-AA482
> Microsoft Visual C++ 2015
> 
> Visual F# 2015   00322-40000-00000-AA482
> Microsoft Visual F# 2015
> 
> Add Empty File   1.9
> Gives the ability to add an empty file with any extension and starting with a dot
> 
> Application Insights Tools for Visual Studio Package   7.2.00808.2
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2015.1   14.1.20810.0
> ASP.NET and Web Tools 2015.1
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Azure App Service Tools v2.9   14.0.20316.0
> Azure App Service Tools v2.9
> 
> Azure Data Lake Node   1.0
> This package contains the Data Lake integration nodes for Server Explorer.
> 
> Azure Data Lake Tools for Visual Studio   2.0.6000.0
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> DataFactoryProject   1.0
> Microsoft Data Factory Package
> 
> GitHub.VisualStudio   1.0
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> Microsoft .NET Core Tools (Preview 2)   14.1.20810.0
> Microsoft .NET Core Tools (Preview 2)
> 
> Microsoft Azure Data Factory Node Node   1.0
> Azure Data Factory extension for Visual Studio Server Explorer.
> 
> Microsoft Azure HDInsight HQL Service   2.0.6000.0
> Language service for Hive query
> 
> Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
> An integrated development environment for HDInsight application development.
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> Microsoft Azure Tools   2.8
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3
> 
> NuGet Package Manager   3.5.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Open Command Line   2.1.175
> Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> Python Tools for Visual Studio   2.2.40623.00
> Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.
> 
> Python Tools for Visual Studio - Django Integration   2.2.40623.00
> Provides templates and integration for the Django web framework.
> 
> Python Tools for Visual Studio - Profiling Support   2.2.40623.00
> Profiling support for Python projects.
> 
> Snippet Designer   1.6.2
> Snippet Designer is a Visual Studio plug in which allows you to create and search for snippets inside the IDE
> 
> SQL Server Analysis Services   13.0.1605.88
> Microsoft SQL Server Analysis Services Designer 
> Version 13.0.1605.88
> 
> SQL Server Data Tools   14.0.60629.0
> Microsoft SQL Server Data Tools
> 
> SQL Server Integration Services  
> Microsoft SQL Server Integration Services Designer
> Version 13.0.1601.5
> 
> SQL Server Reporting Services   13.0.1605.88
> Microsoft SQL Server Reporting Services Designers 
> Version 13.0.1605.88
> 
> ToolWindowHostedEditor   1.0
> Hosting json editor into a tool window
> 
> TypeScript   1.8.36.0
> TypeScript tools for Visual Studio

Other details about my project setup:

```
D:> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by divega** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing information about the exact symptoms, e.g. what folder are you getting migrations added to in your project? Can you please provide this information?

In case your issue is related to any of the issues have already fixed for the next release (as far as I remember there were a few that were related to resolving paths correctly), you may want to try your project with nightly builds of EF Core 1.1. There is more information about the NuGet feeds containing nightly builds at https://github.com/aspnet/Home/wiki/NuGet-feeds.

**Comment by bigteejay** [comment]
Migrations default to "./Migrations"

If you then just run `dotnet ef database update`, you will get an indication that it ran successfully.  

However, without any extra steps, the migration just created won't actually be applied (unless you use the -o switch when generating the migration to place it in "./Models" so it can by found relative to the DbContext and actually applied.)  

Further, if you name the migration to be applied, you'll get an error that it could not be found (though you can see it in "Migrations" and no indication that it only searched "Models" where it found DbContext.)

**Comment by bigteejay** [comment]
To be clear, the workaround is to always use the `-o` flag, placing the generated migrations into the "Models" folder (alongside `DbContext` class/source.)  Then, ensure you always name the migration you expected to apply (to ensure you get an error if it can't be found.)  

None of this however addresses the fact that there is no indication (without digging in source) as to why the migration created couldn't be found without intentionally placing the migration into the models folder (either by `-o` or manual copy/paste.)

**Comment by bigteejay** [comment]
Looking at the link you provided, none of them are indicated as being "nightly" builds.  Which are you suggesting I try?

**Comment by bricelam** [comment]
https://dotnet.myget.org/gallery/aspnetcore-dev
Note, the `Microsoft.EntityFrameworkCore.Tools` was split and you'll need to use `Microsoft.EntityFrameworkCore.Tools.DotNet` instead.

**Comment by bigteejay** [comment]
Added the feed you mentioned @bricelam , working on integrating that into my project.json.

Does it still need to be in the tools section?  With the version and imports?  Since you said "instead" does that mean I replace `"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"` in dependencies with `Microsoft.EntityFrameworkCore.Tools.DotNet`?

I'm not seeing any autocomplete for the version to provide.

**Comment by bigteejay** [comment]
I seem to have it installed (can at least get the `--help` output to display.)  I'm getting a version mismatch error now (about the logging facility.)  Not wanting to pollute my project with version mismatches so I'll likely just roll back for now.

I imagine I can browse source, but are the (now numerous) switches described somewhere?  Several seem to have fairly analogous names...

>   --data-dir &lt;dir>          The folder used as the data directory (defaults to current working directory).
>   --project-dir &lt;dir>       The folder used as the project directory (defaults to current working directory).
>   --content-root-path &lt;dir>       The folder used as the content root path for the application (defaults to application base directory).
