### ISSUE TITLE
VS Intellisense incorrect for ThenInclude on Collection

### ISSUE THREAD

**Issue by jlost** [dotnet/efcore#6382]
### Steps to reproduce

Imagine the following simple many-to-many relationship:

```
public class Pet {
    public int Id {get;set;}
    public List<PetItem> Equipment {get;set;}
}

public class PetItem {
     public int PetId {get;set;}
     public Pet Pet {get;set;}
     public int ItemId {get;set;}
     public Item Item {get;set;}
}

public class Item {
     public int Id {get;set;}
     public string Name {get;set;}
}
```

Then typing the following code:

```
var pet = _dbcontext.Pets.Include(p => p.Equipment).ThenInclude(pi => pi.
```
### The issue

At this point Intellisense suggests the following:
![theninclude_intellisense_problem](https://cloud.githubusercontent.com/assets/11338926/17839924/e8d64338-67c5-11e6-9faf-79398e5d039a.png)

As you can see, it thinks that `pi` is a `List<PetItem>` rather than a `PetItem`.

However, if I simply act like `pi` were a `PetItem` and navigate to its Item property, all is well and Intellisense will not report an error.

Here's another user with the same problem:
http://stackoverflow.com/questions/38044451/entity-framework-core-eager-loading-then-include-on-a-collection
### Further technical details

EF Core version: 1.0.0
Operating system: W10
Visual Studio version: 2015 Update 2

**Comment by ajcvickers** [comment]
@jlost This is an external issue that is already being tracked here: https://github.com/dotnet/roslyn/issues/8237

Closing this as a dupe for the original EF issue #4117
