### ISSUE TITLE
Context caching values?

### ISSUE THREAD

**Issue by SimonOrdo** [dotnet/efcore#6393]
### Steps to reproduce

// Update field

```
var newValue = 4;
var pk = 5;

 Config dat = new Config()
                {
                    ID = pk,
                    UsernameRegistrationFieldId  = newValue 
                };

                _context
                    .Config 
                        .Attach(dat)
                            .Property(x => x.UsernameRegistrationFieldId)
                            .IsModified = true;

                _context.SaveChanges();
```

```
// Then, try to re-read the data from the database
 List<Config> portals = _context.Config
                .Include(x => x.Portal_URL)
                .Include(x => x.UsernameRegistrationField)
                .ToList();
```
### The issue

When updating a column and saving the changes and then attempting to read the value back from the DB using the same context, the updated row isn't actually read back from the database.

In the example, since I only populated two fields in the Config object (other values left blank), that's exactly what the row looks like in EF when the re-read code executes.

When querying with a new DB context, the second code block produces the expected results.

```
EF Core version: 1.0.0
Operating system:  Windows
Visual Studio version: (e.g. VS 2015 )
```

**Comment by ajcvickers** [comment]
@SimonOrdo This is by design. See the comment I posted a few minutes ago on issue #6391 for some common ways of dealing with this.
