### ISSUE TITLE
Migrations: Detect primary key property renames

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#6404]
Similar to #5155 (but perhaps not as useful), we could also detect renamed properties that are part of the primary key if...
1. The number of primary key properties are the same, and
2. The would-be-added property is in the same position as a would-be-removed property

**Comment by bricelam** [comment]
I need to think about it more, but my initial feeling is that it becomes even less useful for alternate keys, and indices.

**Comment by bricelam** [comment]
Also, I wonder if just doing structural matching (e.g. everything is the same except the name) would cover all these cases for much cheaper.

**Comment by divega** [comment]
**Triage:** we want to have a design discussion about this, including @rowanmiller.

**Comment by bricelam** [comment]
Closing in favor of doing #6582 instead.
