### ISSUE TITLE
Assembly version of 1.0.1 patch assemblies

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#6421]
I would have expected the assembly version of the 1.0.1 patch files to stay at 1.0.0 - but that is not the case, I can see - are you planning to use assembly redirects on app.config to make this work with a 1.0.0 provider?

**Comment by bricelam** [comment]
> I would have expected the assembly version of the 1.0.1 patch files to stay at 1.0.0

Me too. At least on Full .NET with the loader being the way it is... @davidfowl @pranavkm @Eilon?

**Comment by Eilon** [comment]
Hmm I'm not sure how that should work. Part of me says that everything should get a version bump because it's The Right Thing To Do™️. But I get that there are problems with that as well.

**Comment by bricelam** [comment]
@Eilon From what I've observed, most projects only ever put the major version in assembly versions because of the over-restrictive loader. We did this on EF6 too. Versions 6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.1.2 & 6.1.3 have all had assembly verstion 6.0.0.0.

**Comment by bricelam** [comment]
Note, their file and informational versions all incremented as expected. Just the assembly version stayed the same to preserve assembly identity.

**Comment by bricelam** [comment]
However, NuGet is designed to add the appropriate binding redirects to consuming projects. So, in practice it may rarely matter.

**Comment by bricelam** [comment]
We should do some testing though since some of the tooling code might have assumed they'd never change.

**Comment by divega** [comment]
> If we decide to increment, we should do some targeted testing because some of the tooling code may have assumed that they'd never change.

Yes, as far as I remember tooling was the main reason we decided to keep the assembly version unchanged. NuGet may add the binding redirects on the app automatically but generally redirecting on a tool is not that easy.

**Comment by divega** [comment]
We decided to bump the assembly version across the board for patch releases. We will keep testing (in particular our tooling) to make sure everything handles it correctly.
