### ISSUE TITLE
Logging not added to context created from generic type

### ISSUE THREAD

**Issue by thesmallbang** [dotnet/efcore#6432]
If created from the type there is no issue and logging occurs as expected.

``` C#
Context = new MyDbContext()
```

When creating a context from a generic type logging does not occur 

``` C#
Context = new TDbContext();
```

If I add the logger manually against the context it works as expected.

``` C#
Context = new TDbContext();
var loggerFactory = Context.GetService<ILoggerFactory>();
            loggerFactory.AddNLog();
```

Class:

``` C#
public abstract class DbContextService<TDbContext> : IDisposable where TDbContext : DbContext, new()
```

EF Core version: 1.0.0  (tools preview1)

**Comment by ajcvickers** [comment]
@thesmallbang I don't think there is enough information here to reproduce the issue. If you could put your code snippets into the a small console application that would be great. I am particularly interested in seeing how you are configuring the context, either using OnConfiguring or AddDbContext.

**Comment by thesmallbang** [comment]
I was not able to duplicate this issue in a simple sample environment. I will close this issue and add a comment if i ever locate the source.
