### ISSUE TITLE
The entity type 'EntityName' is part of a hierarchy, but does not have the discriminator value configured.

### ISSUE THREAD

**Issue by dpjain** [dotnet/efcore#6433]
Created an entity with discriminator values in OnModelCreating method in ApplicationDbContext class:

``` C#
 builder.Entity<EntityName>()
                .HasDiscriminator<int>("Type")
                .HasValue<DerivedClass1>(1)
                .HasValue<DerivedClass2>(2)
                .HasValue<DerivedClass3>(3);
```
### Issue

After migrating the asp.net core RC1 project to asp.net core 1.0 project, tried to update the db using command line (dotnet ef database update), but facing the following issue:
The entity type 'EntityName' is part of a hierarchy, but does not have the discriminator value configured.

EF Core version: "Microsoft.EntityFrameworkCore": "1.0.0"
Visual Studio version: VS 2015

**Comment by ajcvickers** [comment]
@dpjain Since EntityName is part of the mapped hierarchy, then unless it is an abstract class, it must have a discriminator value defined.

**Comment by dpjain** [comment]
Thanks for the reply.
