### ISSUE TITLE
Query: Relational: Efficient GroupJoin via ROW_NUMBER introduction

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#6441]
Our relational streaming GroupJoin operator currently requires materialization for both sides of the join in order to do correct streamed grouping on the client.

Here is a prototype that removes the requirement: https://github.com/anpete/EntityFramework/tree/proto-group-join-improvement

**Comment by divega** [comment]
@anpete is this something that you intend to complete in 1.1.0 or should we move it to the backlog?

**Comment by divega** [comment]
Assigning this to @smitpatel in 3.0 after discussing with him. We believe we can still apply the general idea.

**Comment by ajcvickers** [comment]
Closing as there is now no need to track this following the query pipeline changes.
