### ISSUE TITLE
EF trying to Insert Child Object into Identity field 

### ISSUE THREAD

**Issue by redowl3** [dotnet/efcore#6447]
### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
1.  Parent object includes child object (as a property)
2.  Insert Parent object and EF tries to Insert Child object into it's associated table
3.  Insert fails as cannot insert ID into Identity field
### The issue

Describe what is not working as expected.

Not expecting the child parent to be inserted into it's associated table.

If you are seeing an exception, include the full exceptions details (message and stack trace).

Exception message:
Cannot insert explicit value for identity column in table 'child' when IDENTITY_INSERT is set to off

Stack trace:

```

### Further technical details

EF Core version: (found in project.json or packages.config) 1.0.0
Operating system:  Win 10
Visual Studio version: (e.g. VS 2013 or n/a) VS 2015

Other details about my project setup:

_dbContext.'ParentTable'.Add(ParentObject)
await _dbContext,SaveChangesAsync() - "throws exception"

I have a WebApi project that is connected to a SQLServer both hosted on Azure.  Due to the fact that Azure only supports RTM we have upgraded our WebApi project to 1.0.0 Core and EF 1.0.0.   

Our original WebApi projects using RC1 works using

"EntityFramework": "6.1.3",
"EntityFramework.Core": "7.0.0-rc1-final",
"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",

Both versions of the WebApi (RC1 and RTM) are pointing at the same database.


```

**Comment by ajcvickers** [comment]
@redowl3 EF will attempt to insert any entity that it thinks is new, which is indicated by that entity being in the Added state. When an entity is marked as Added by calling the Add method, then any entities that are reachable from that entity are also marked as Added. Probably you need to call Attach on the graph first and then mark individual new entities as Added, but it is hard to know without a more complete code listing. It may be useful to read through some of the documentation in the Saving Data section here: https://docs.efproject.net/en/latest/saving/index.html

**Comment by redowl3** [comment]
Thanks for the response, is this new functionality?

Here is a very small section of code that illustrates what we are doing

var track = new Track
                    {
                        TrackUrl = blobUrl,
                        TrackName = viewModel.TrackName,
                        UserId = HttpContext.User.GetUserId(),
                        ArtistId = artist.ArtistId,
                        Genre = new Genre() { GenreId = 1 }
                    };
Doesn't work (but did with EF 6.1.3) using a navigation property, whereas

var track = new Track
                    {
                        TrackUrl = blobUrl,
                        TrackName = viewModel.TrackName,
                        UserId = HttpContext.User.GetUserId(),
                        ArtistId = artist.ArtistId,
                        GenreId = 1 
                    };
works (although we don't use a navigation property) with EF Core 

when using 

_dbContext.Tracks.Add(track)
await _dbContext,SaveChangesAsync()

**Comment by ajcvickers** [comment]
In the first snippet of code, EF6 will insert a new Genre, completely ignoring the GenreId set. In EF Core, EF6 will not use the existing Genre with key of 1. With EF Core, if you set the key to some value, then EF Core will attempt to use the key value you set. So it will try to insert a new Genre with GenreId of 1, which as you have seen fails. If you want it to behave like EF6 and generate a key, then leave GenreId set to 0. EF will then insert a new Genre with a new store generated key just as EF6 does.

The second code snippet does something different. It doesn't create any new Genre object, but instead assumes that there is a Genre with an ID of 1 already saved in the database.

So the real question is whether you want a new Genre or to use an existing one. If you want to use a new one with a store generated key, then don't set an explicit key value before saving. If you want to use an existing one, then either query for it:

```C#
var genre = _dbContext.Genres.Single(e => e.GenreId == 1);
var track = new Track { ... , Genre = genre };
_dbContext.Add(track);
_dbContext.SaveChanges();
```
Or if you already have the existing Genre from somewhere, then Attach it:

```C#
_dbContext.Attach(genre);
var track = new Track { ... , Genre = genre };
_dbContext.Add(track);
_dbContext.SaveChanges();
```

**Comment by redowl3** [comment]
Hi, sorry didn't get around to updating this question, but this doesn't appear to working as you've suggested.  As per my original issue, there is a definite difference between  RC1 and RTM, which I can easily recreate (as detailed in the steps).

**Comment by ajcvickers** [comment]
@redowl3 RC1 did not behave in the way described; RTM does.

**Comment by redowl3** [comment]
Right I'm with you, so there was a change.  Thanks for the info.
