### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment'

### ISSUE THREAD

**Issue by dpjain** [dotnet/efcore#6450]
In Startup.cs, AddDBContext is added to the method ConfigureServices(IServiceCollection services)

``` C#
 services.AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));
```

In ApplicationDBContext, the parameterized constructor is added:

``` C#
 public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
        {
        }
```

IHostingEnvironment is used to get the WebRootPath:

``` C#
 IHostingEnvironment hostingService = context.GetService< IHostingEnvironment>();
```
## Issue

But while accessing the HostingEnvironment, facing the following issue: 

Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

EF Core version: "Microsoft.EntityFrameworkCore": "1.0.0",
Visual Studio version: VS 2015

**Comment by dpjain** [comment]
@ajcvickers : Do you have any idea what exactly I am missing?

**Comment by ajcvickers** [comment]
@dpjain The context.GetServuice extension method is really intended as a back door to get at EF services. The reason it is not working here is that EF is using its own internal service provider and IHostingEnvironment is not an EF service. If you need IHostingEnvironment in your context, then you should constructor inject it like any other application service. For example:
```C#
public ApplicationDbContext(
    DbContextOptions<ApplicationDbContext> options,
    IHostingEnvironment hostingService)
        : base(options)
        {
            // Do whatever you need with hostingService here
        }
```
