### ISSUE TITLE
Foreign key names not consistent (SQL CE RevEng)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#6469]
### Steps to reproduce

I am using EnsureClean now, duríng getting the SQLCE provider ready for 1.1
(It acts as a perfect acid test for migrations)
### The issue

Foreign keys are created with this naming pattern:
FK_WithAllNullableIntFk_WithAllNullableIntKey_Fk

```
-- Script Date: 04-09-2016 15:00  - ErikEJ.SqlCeScripting version 3.5.2.58
ALTER TABLE [WithAllNullableIntFk] ADD CONSTRAINT [FK_WithAllNullableIntFk_WithAllNullableIntKey_Fk] FOREIGN KEY ([Fk]) REFERENCES [WithAllNullableIntKey]([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
```

But the DROP CONSTRAINT statement expects this name:
WithAllNullableIntFk_FK_WithAllNullableIntFk_WithAllNullableIntKey_Fk

I assume I am missing something in my migrations implementation - or maybe my model building @bricelam ?? I do not override any ForeignKey migration operations

Stack trace:
Test 'Microsoft.EntityFrameworkCore.Specification.Tests.NullKeysSqlServerCeTest.Include_with_null_FKs_and_nullable_PK' failed:
    System.AggregateException : One or more errors occurred.
---- System.Data.SqlServerCe.SqlCeException : The foreign key constraint does not exist. [ WithAllNullableIntFk_FK_WithAllNullableIntFk_WithAllNullableIntKey_Fk ]
---- The following constructor parameters did not have matching fixture data: NullKeysSqlServerCeFixture fixture

```
----- Inner Stack Trace #1 (System.Data.SqlServerCe.SqlCeException) -----
at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.Tests.RelationalDatabaseCleaner.Clean(DatabaseFacade facade)
SqlCeDatabaseFacadeExtensions.cs(11,0): at Microsoft.EntityFrameworkCore.Specification.Tests.SqlCeDatabaseFacadeExtensions.EnsureClean(DatabaseFacade databaseFacade)
NullKeysSqlCeTest.cs(42,0): at Microsoft.EntityFrameworkCore.Specification.Tests.NullKeysSqlServerCeTest.NullKeysSqlServerCeFixture.EnsureClean(DbContext context)
at Microsoft.EntityFrameworkCore.Specification.Tests.NullKeysTestBase`1.NullKeysFixtureBase.EnsureCreated()
NullKeysSqlCeTest.cs(31,0): at Microsoft.EntityFrameworkCore.Specification.Tests.NullKeysSqlServerCeTest.NullKeysSqlServerCeFixture..ctor()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
### Further technical details

EF Core version: 1.1.0-alpha1-21973
Operating system:  Win 10
Visual Studio version: VS 2015 Update 3

**Comment by bricelam** [comment]
What is in the C# migration file? The name should originally come from [RelationalForeignKeyAnnotations.Name](https://github.com/aspnet/EntityFramework/blob/1.0.0/src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalForeignKeyAnnotations.cs#L41). I'm not sure where the additional part is getting introduced.

**Comment by ErikEJ** [comment]
Thanks, @bricelam  - I use the new EnsureClean (replacement for EnsureDeleted/EnsureCreated) test method, so I am not sure any migration files are involved...

(Btw, EnsureDeleted/EnsureCreated works fne, as no DROP statements are created by that combo)

**Comment by bricelam** [comment]
cc @AndriySvyryd who I think wrote the EnsureClean sutff. I haven't used it and don't know how it works. :smile:

**Comment by ErikEJ** [comment]
I think it was @ajcvickers who wrote it...

**Comment by ajcvickers** [comment]
@ErikEJ @bricelam EnsureClean uses the reverse engineering engine to query for existing database objects and then uses the migrations pipeline to generate commands to drop those objects. So the names of all objects that need to be dropped should come directly from the database and should not have any relation to the current model. This ensures that even if the current model is different from the one that was used to create the database the database will still be cleaned out completely.

**Comment by ajcvickers** [comment]
@ErikEJ @bricelam Note that this is very much a pragmatic YAGI based approach suitable for our test projects. It works for everything we have in SQL Server and SQLite, but there are certainly types of databases that it wouldn't work properly with. So if there are cases where it doesn't work for SQL CE then tweaks may need to be made, for which we would accept pull requests.

Also, we didn't see any significant perf gains when using EnsureClean for SQLite, and the same may be true for SQL CE, in which case it would be perfectly valid to just implement it as a full delete of the database. It was done for SQL Server, where is can be much faster, but in a way that hopefully is mostly provider agnostic and uses our existing assets such that other providers can make use of it if it makes sense.

**Comment by ErikEJ** [comment]
@ajcvickers  aaah ! Sorry for dragging you into this, @bricelam 😄  

I uniquify the FK names i reveng - as several SQLCE tables can have same FK name (unlike SQL Server) 🐑    need to rethink that!

**Comment by ErikEJ** [comment]
@ajcvickers Appreciate the design constraints, but as I mention it is actually a good "test" (not of migrations, as it turns out) - of the reveng ability to roundtrip the schema. I wonder if the ForeignKeyModel is missing the ability to hold both a unique key value and the original constraint name @divega ? 

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Design40/Internal/SqlCeDatabaseModelfactory.cs#L263

**Comment by divega** [comment]
@ErikEJ I am not sure how common it is among SQL based databases to use separate spaces for child object names. If it turned out to be just a SQL CE thing, I wonder if sticking the actual name in an annotation would work. I guess your provider would need to register that annotation for diffing, and use it to create the object, etc.

**Comment by divega** [comment]
Also if the convention you are following the same name is reversible, maybe you just need to do the opposite when creating the object name?
