### ISSUE TITLE
Exception at inserting a Identity PK

### ISSUE THREAD

**Issue by Narf92** [dotnet/efcore#6476]
### The issue

Hello, I'm using EF Core and I had use the instruction scaffold to generate the DBcontext and the model of my SQL server table. When I try to insert an entity into the table it says me that can't insert it wants to insert a value in a Identity column when Identity_insert is off.
I tried to put annotations in the field Id, the one who is giving the problem, and it doesn't work.

This is the script to create the table where I'm trying to insert

```
CREATE TABLE [dbo].[Impuestos](
    [Id] [int] IDENTITY (1,1) NOT NULL,
    [Tipo] [nvarchar] (10) NOT NULL,
    [Descripcion] [nvarchar] (20) NOT NULL,
    [Porcentaje] [int] NOT NULL,
CONSTRAINT [PK_dbo_Impuestos] PRIMARY KEY CLUSTERED 
([Id] ASC)
)
ALTER TABLE [dbo].[Impuestos] ADD CONSTRAINT uc_Impuestos UNIQUE (Tipo,Porcentaje)
```

This the context generated (I take out the connstring but is config

``` C#
public partial class LINXContext : DbContext
    {
        public LINXContext(DbContextOptions options) : base(options)
        {}

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Impuestos>(entity =>
            {
                entity.HasIndex(e => new { e.Tipo, e.Porcentaje })
                    .HasName("uc_Impuestos")
                    .IsUnique();

                entity.Property(e => e.Descripcion)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.Tipo)
                    .IsRequired()
                    .HasMaxLength(10);
            });
        }

        public virtual DbSet<Impuestos> Impuestos { get; set; }
    }

```

This is the object class, it extends SqlEntity for working with repositories layer, and it has the field Id.

``` C#
public partial class Impuestos : SqlEntity
    {
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public int Porcentaje { get; set; }
    }
```

``` C#
public abstract class SqlEntity : ISqlEntity
    {
        public int Id { get; set; }
    }

```

```
"message": "No se puede insertar un valor explícito en la columna de identidad de la tabla 'Impuestos' cuando IDENTITY_INSERT es OFF.",
"stackTrace": "   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)\r\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)",
```
### Further technical details

EF Core version: Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
Operating system: Windows 10
Visual Studio version: VS 2015 update 3

Other details about my project setup:

**Comment by Muchiachio** [comment]
You are most likely have non-zero id in your model. It should be zero for insert/identity scenarios.

**Comment by Narf92** [comment]
The model gets the Id when extends the class SQLEntity, can't I do in this way so I need to have the Id in the model class? When I debbug the post method, the model object shows me that has an Id 0.

Another thing I tried that allowed me to insert a Tax but no update it, was setting a different property as primary key and set Id as a value generated on Add, it doesn't complain in execution time and inserted the Tax, on the other hand when updating it throws me an exception because I tried to modify a PK.

**Comment by ajcvickers** [comment]
@Narf92 Is the issue that the table created by EF has an Identity column and you don't want that? Or is the issue that you want the identity column, but you also want to be able to explicitly specify the key values of items inserted? Or is the issue something else?

**Comment by Narf92** [comment]
@ajcvickers hi, I want to keep the identity but I don't want to insert specify value to the PK so the DB should insert the Id. 
I followed this example [https://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html](url), and the only thing I changed from the model created was taking out the Id to the class SqlEntity that is extended by the model.

**Comment by ajcvickers** [comment]
@Narf92 If you want the database to generate the value then leave the Id property set to zero. If the property is set to some other value, then EF will use the value set.

**Comment by Narf92** [comment]
@ajcvickers I debbuged my app and I saw that there is a method that is setting the Id automatically in the setAsAdded method.
