### ISSUE TITLE
Is there any way to encrypt a connection string or somehow use Integrated security)  from a docker container

### ISSUE THREAD

**Issue by zman13** [dotnet/efcore#6484]
The only way I see a connection string being used currently with .netcore and docker  is with a hard coded username and password in clear text. Is there a more secure way to do this from a docker container. In regular asp.net we had Protected Configuration. Is there anything like that available from this type of environment ? What is recommended best practice?

**Comment by divega** [comment]
@glennc @natemcmaster any insights on this?

**Comment by natemcmaster** [comment]
@zman13 your question looks similar to this: https://github.com/docker/docker/issues/13490. 

TL;DR most people end up using environment variables on the container, but this isn't the most secure. There are many other suggested ways to of doing it, but docker doesn't have a straightforward way of encrypting secrets

**Comment by stefanprodan** [comment]
Hello,

My current solution to store configuration options(connection string, api keys, salts, etc) is to keep them in a Redis cluster running on Docker Swarm. The Redis cluster can be accessed by other services over a dedicated overlay network, no ports are exposed on the docker host. In app.config, I have an entry that points to the DNS name of the Redis cluster. All services that can access to these options are started with `--network redis-net`. At application start, the configuration options are loaded from Redis and kept in memory cache for a short period of time so the app doesn't have to make a network round-trip every time it needs to access a configuration option. 

There are server advantages to this solution:
* sensitive app settings are not stored in source control
* app settings can be updated on the fly without the need to redeploy your containers by updating the Redis keys
* the image and container of an app doesn't expose any secrets when using docker inspect
* configuration options are stored only in memory if you don't allow disk persistance to the Redis cluster
