### ISSUE TITLE
DbContextOptions<ApplicationDbContext> as parameter

### ISSUE THREAD

**Issue by dpjain** [dotnet/efcore#6493]
@ajcvickers  @divega : We have added the following parameterized constructor in ApplicationDBContext class:

``` C#
   public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
        {
        }
```
### The issue

If we need to access the ApplicationDBContext in another class or controller by creating an object for context, then how we will get the existing options (DbContextOptions<ApplicationDbContext>) and pass it to DbContext:

``` C#
using (var dbContext = new ApplicationDbContext())
{
}
```
### Further technical details

EF Core version: EntityFramework.Core 1.0.0
Visual Studio version: VS 2015

**Comment by ajcvickers** [comment]
@dpjain Have your controller or some other injected object depend on `DbContextOptions<ApplicationDbContext>` in its constructor. For example:
```C#
public class MyController
{
    private readonly DbContextOptions<ApplicationDbContext> _contextOptions;

    public MyController(DbContextOptions<ApplicationDbContext> contextOptions)
    {
        _contextOptions = contextOptions;
    }

    public void Foo()
    {
        using (var dbContext = new ApplicationDbContext(_contextOptions))
        {
        }
    }
}
```

**Comment by pathmanshakir** [comment]
@ajcvickers  I am doing what you are suggesting but in my case it's not a controller but a business logic class. I am getting  **ArgumentNullException: Value cannot be null.  Parameter name: options**
it's because of my default constructor that I get null but If I comment out the constrcutor then the new intance of class needs parameters which I don't know what to give in. HELP PLEASE
```
 public class OvertimeRequestBusiness
    {
        public static OvertimeRequestBusiness Instance { get; } = new OvertimeRequestBusiness();
        private readonly DbContextOptions<DatabaseContext> _contextOptions;
     //default ctor
   public OvertimeRequestBusiness() : base() { }
        
  
        public OvertimeRequestBusiness(DbContextOptions<DatabaseContext> contextOptions)
        {
            _contextOptions = contextOptions;
        }
        public async Task<List<User>> GetAllUsersAsync()
        {
            using (var ctx = new DatabaseContext(_contextOptions))
            {
                var query = ctx.Users;
                var res = await query.ToListAsync();
                return res;
            }
        }
    }
```
In my controller 
```
  [Route("users")]
        [HttpGet]
        public async Task<List<User>> GetAllUsers()
        {
          return await OvertimeRequestBusiness.Instance.GetAllUsersAsync();
        }
```
