### ISSUE TITLE
Tracked changes not being reverted when performing a rollback

### ISSUE THREAD

**Issue by eric-littlejohn** [dotnet/efcore#6496]
I have a scenario where I need to process multiple things in a batch. If anything fails to be processed, the whole batch is reverted and retried at a later point. I figured this a perfect case for a transaction, so I wrote the following code:

```
using (IDbContextTransaction transactionScope = DataContext.Database.BeginTransaction())
{
    try
    {
        ctx.SomeEntitySet.Add(new EntitySet() { ID = SpecifiedGuid }
        ctx.SaveChanges();

        SomeLogic();

        transactionScope.Commit();
    }
    catch (Exception exc)
    {
        transactionScope.Rollback();
        throw;
    }
}
```

The issue that Im running into is that lets say an exception is thrown for some reason in SomeLogic(). The exception is caught and the rollback is performed, which is great. However when the retry logic calls the method again, the context throws an exception on the Add() entity line, saying that an entity with that id is already added. In my scenario, its important for the id to match a particular id, so just letting entity framework create it wont work.  

Is the functionality of Rollback() only meant to rollback the database, and not undo the pending changes to the context? Or is there something Im overlooking?

**Comment by ajcvickers** [comment]
@Shadow3188 Rolling back a transaction is not designed to clean out entities from the context. You could try either making appropriate changes to the already tracked instances and then re-trying SaveChanges, or if you want to start again with new entity instances, then you probably want to create a new context instance so it is starting as a clean slate for your unit of work.

**Comment by Shadow3188** [comment]
Sounds good. Ill take that approach then. Thanks for the quick response!
