### ISSUE TITLE
Should the EFCore.FunctionalTests project exist?

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#6498]
I thought we renamed it to `Microsoft.EntityFrameworkCore.Specification.Tests`, but there are still a few source files there...

**Comment by ajcvickers** [comment]
@bricelam I think these are tests that are not useful as abstractions that each provider should test, but rather test non-provider specific behavior of the core. That being said, we could move them, but then they would run multiple times with no differences.

**Comment by bricelam** [comment]
They're fine as they are. I just wanted to make sure they're intentional and not the result of a bad merge.
