### ISSUE TITLE
Split the repository

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#6500]
Now that we've RTMed, splitting projects into separate repositories is more feasible. Here are a couple splits we've talked about in the past:
- Move out the Tools (EFCore.Design, CLI & NuGet Commands)
- Move out the providers (InMemory, SqlServer & Sqlite)

**Comment by rowanmiller** [comment]
We will do this as needed in the future (if it provides net benefit)

**Comment by bricelam** [comment]
Reopening. Given the new information @divega and I got today about tools vs runtime releases, we should re-discuss this, and decide how best to address the Reverse Engineering test issues described in #6497.
