### ISSUE TITLE
Removal of existing entity Keys for derived entities

### ISSUE THREAD

**Issue by RoySalisbury** [dotnet/efcore#6501]
I am trying to add a new property to the IdentityUserRole class in the ASP.NET identity system.  Basically

```
public class ApplicationUserRole<TKey> : IdentityUserRole<TKey> where TKey : IEquatable<TKey>
{
    public virtual int? SiteId { get; set; }
}
```

And then in my DbContext's OnModelCreating:

```
builder.Entity<ApplicationUserRole<int>>(entity =>
{
    entity.HasKey(x => new { x.RoleId, x.UserId, x.SiteId });
});
```

However, there does not seem to be a way to REMOVE the existing Key that only contains the { x.RoleId, x.UserId } complex type.  And when a new key is added, the existing one seems to be changed to an AlternateKey due to the FK mappings that already exist.  

This has the effect that I now have a constraint that is too restrictive. I can't seems to find a way to remove the existing key or tell it not to generate the AlternateKey.

If I take the original model definition from the base class and implement it in my own class (minus the entity.HasKey(x => { x.RoleId, x.UserId }) ) then the model is created just fine with all the FK additions.

So, how do you remove an existing definition from the model in a derived DbContext?

Perhaps a way to "redefine" the Key or AlternateKey and then just "Ignore()" the key definition.  For example:

```
entity.HasKey(x => new { x.RoleId, x.UserId }).Ignore();
entity.HasKey(x => new { x.RoleId, x.UserId, x.SiteId });
```

**Comment by rowanmiller** [comment]
Hey,

> And when a new key is added, the existing one seems to be changed to an AlternateKey due to the FK mappings that already exist. 

You are spot on here, if there is a foreign key targeting a column (or set of columns) that are not the primary key, then an alternate key is introduced. You would need to update those parts of the model too (presumably to make your new `SiteId` part of the foreign key for those relationships). I think your starting to push the boundaries of the customization that is designed to be done with the exiting Identity provider, but you could take a look at the config it does already to help work out what you need to change - https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs#L148.

If you have further questions about customizing the Identity model, then the Identity repository would be the best place to ask these - https://github.com/aspnet/Identity.

~Rowan
