### ISSUE TITLE
Set navigational property to null doesn't work.

### ISSUE THREAD

**Issue by YuriiNskyi** [dotnet/efcore#6504]
I have simple model and viewmodel classes:

```
    public class Library
    {
        [Key]
        public string LibraryId { get; set; }
        public string Name { get; set; }
        public Book Book { get; set; }
    }

    public class Book
    {
        [Key]
        public string BookId { get; set; }
        public string BookName { get; set; }
    }

    public class LibraryViewModel
    {
        public string LibraryId { get; set; }
        public string Name { get; set; }
        public BookViewModel Book { get; set; }
    }

    public class BookViewModel
    {
        public string BookId { get; set; }
        public string BookName { get; set; }
    }
```

So, they are quite simple.

However, I have problem with realizing **Edit** method:

```
public async Task<Book> GetBookById(string id) => await _context.Books.SingleOrDefaultAsync(m => m.BookId == id);
public async Task<Library> ConvertLibraryViewModel(LibraryViewModel libraryViewModel)
        {
            if (libraryViewModel == null) return null;
            Library library = new Library();
            library.LibraryId = libraryViewModel.LibraryId;
            library.Name = libraryViewModel.Name;
            library.Book = await GetBookById(libraryViewModel.Book.BookId);
            return library;
        }

public async Task<IActionResult> Edit(LibraryViewModel libraryViewModel)
        {
            var libraryNew = await ConvertLibraryViewModel(libraryViewModel);

            if (libraryNew != null)
            {
                    _context.Libraries.Attach(libraryNew);
                    _context.Entry(libraryNew).State = EntityState.Modified; 
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
```

It is working, when I'm changing nested entity _Book_ in my _Library_ to another _Book_, and when I'm setting `null` to _Book_. 

Then I'm trying remove relationship between _Book_ and _Library_ (without deleting existing _Book_ in database), simply setting _Library.Book_ to `null`, then `SaveChanges()`. But it doesn't work! Nothing happens, there is still relationship between _Book_ and _Library_, if I take a look into database table where I store my libraries, I will see id of the book in _BookId_ column, filled with previous book id, while it must be empty!

Is it a bug? Or maybe I don't know how to properly work with such operations? What's wrong here?

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS 2015

Other details about my project setup:
SImple ASP.NET Core application created from the Individual user accounts template.;

**Comment by ajcvickers** [comment]
@RepositoryNY All the comments I made on #6345 still apply here. You are making changes to entities that are not being tracked by the context. When you attach the entity, EF has no way of knowing that the null navigation property means that it should clear the relationship as opposed to the related entity just not being loaded. The suggestions I made there to solve the issue also apply here.

Also note that as your model is setup you have a relationship where each library can only have one book and each book has many libraries. Is this what you intended?

**Comment by RepositoryNY** [comment]
@ajcvickers So, how can I tell EF that null navigation property means that it should clear the relationship? 

As far as I understood, there is no way around, we need explicitly load _Library_ and manually change properties in it? 

Could we keep `Convert()` method simple, without loading any entities in it? `Convert()` method doesn't need to know nothing about loading, including, etc, it must just copy properties, that's all.

**Comment by ajcvickers** [comment]
@RepositoryNY The easiest thing to do is to map the FK property by adding a BookId property to Library, This means when you mark the entity as Modified the null FK property will also be marked as Modified, and this null will therefore be sent to the database. If you don't want to map the FK, then you can force it to be null by doing something like `context.Entry(library).Property("BookId").CurrentValue = null;`.

**Comment by RepositoryNY** [comment]
@ajcvickers Thanks for advice!

How about `Convert()` method, could it be simple?

**Comment by ajcvickers** [comment]
@RepositoryNY Yes. You can just set the BookId property in the Convert method.

**Comment by RepositoryNY** [comment]
Could you please give an example of correct `Edit()` and `Convert()` methods, I'm afraid, I'm missing something when trying to understand how those things work,

**Comment by ajcvickers** [comment]
```C#
public Library ConvertLibraryViewModel(LibraryViewModel libraryViewModel)
{
    if (libraryViewModel == null) return null;
    Library library = new Library();
    library.LibraryId = libraryViewModel.LibraryId;
    library.Name = libraryViewModel.Name;
    library.BookId = libraryViewModel?.Book.BookId;
    return library;
}

public async Task<IActionResult> Edit(LibraryViewModel libraryViewModel)
{
    var libraryNew = ConvertLibraryViewModel(libraryViewModel);

    if (libraryNew != null)
    {
        _context.Update(libraryNew);
    }

    await _context.SaveChangesAsync();
    return RedirectToAction("Index");
}
```

**Comment by RepositoryNY** [comment]
@ajcvickers Thank you, I'll try it on Monday!
