### ISSUE TITLE
How to reference a project using EF Core in UWP and Website applications?

### ISSUE THREAD

**Issue by VorSiechtIP** [dotnet/efcore#6505]
Hi,

I posted this question of http://stackoverflow.com/questions/39395465/how-to-share-a-net-core-project-with-a-net-core-website-and-uwp-app but thought I might get possibly more help here.

I'm in the process of creating a proof on concept solution that will have a project using Entity Framework Core.  I would like the project to be referenced by a UWP project and also by a .Net Core website.  I was able to get the Website referencing the project and using Entity Framework Core correctly.  When I try to get the UWP app to use the same code, it compiles, but fails at run time.  I've also tried changing the frameworks around using NetStandard1.4 and NetStandard1.6 but then the Entity Framework Core doesn't work correctly.

My shared project is a .Net Core class library (not an actual Shared Project type in VS).

Here's the error that I get when I run the UWP application.  It occurs when I try to create a new Context class that inherits from DbContext:

> An exception of type 'System.IO.FileLoadException' occurred in
> mscorlib.ni.dll but was not handled in user code
> 
> Additional information: Could not load file or assembly
> 'System.Runtime, Version=4.1.0.0, Culture=neutral,
> PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The
> located assembly's manifest definition does not match the assembly
> reference. (Exception from HRESULT: 0x80131040)

Here's the project.json that I have for the shared project.

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "NETStandard.Library": "1.6.0",
    "System.ComponentModel.Annotations": "4.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }

  }
}
```

Here's the project.json for the UWP project

```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  },
  "frameworks": {
    "uap10.0": {
      "imports": [
        "netcoreapp1.0"
      ]
    }
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

Here's the project.json for the website project

```
{
  "dependencies": {
    "Domain": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by bricelam** [comment]
I'm not sure if UWP projects work well with .NET Core projects. Maybe you could try changing your EF project to a Portable Class Library project.

**Comment by VorSiechtIP** [comment]
@bricelam You're awesome!  I tried using a PCL and I wasn't able to add EF Core becuase I chose Class Library (Portable for iOS, Android and Windows) instead of Class Library (Portable).  I chose the correct library option and selected UWP and .Net Core and was able to add EF and get it compiling and not throwing an exception at runtime for both projects.

Thanks Again!
