### ISSUE TITLE
trying to add ef daily build to a rtm application

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#6508]
_From @lucamorelli on July 15, 2016 20:8_

Hi, I'm not sure this issue is for the tooling repo.
I'm trying to add the ef daily build to an existing rtm application and I found a strange behavior.
Adding **1.1.0-alpha1-21620** version of the ef libraries I have a conflict in the Extensions.Logging library

> Dependency conflict. Microsoft.EntityFrameworkCore 1.1.0-alpha1-21620 expected Microsoft.Extensions.Logging >= 1.1.0-alpha1-21620 but received 1.0.0

In the solution explorer I have the right warning : 
![error](https://cloud.githubusercontent.com/assets/127777/16887040/0a642a98-4ad8-11e6-8b1e-37fd29a10fe5.png)

But compilation succedes, I can run the app that fails in startup.
There is some way to solve this problem? If not, make sense to make the app startable if there is a critical conflict?

_Copied from original issue: aspnet/Tooling#675_

**Comment by divega** [comment]
_From @mlorbetske on July 18, 2016 18:38_

TFS Bug#241390

**Comment by divega** [comment]
_From @mlorbetske on July 26, 2016 21:7_

@rowanmiller any ideas?

**Comment by divega** [comment]
_From @rowanmiller on July 27, 2016 20:40_

@lucamorelli I assume you have the nightly feed configured in your package sources? The feeds that are used should be listed in the Output window once package restore completes.

**Comment by divega** [comment]
_From @lucamorelli on July 28, 2016 6:51_

yes, I was trying to use the nightly feed to see if a few bugs are fixed. The question is if it's possible to use nightly build of ef using rtm version of asp.net core.

**Comment by rowanmiller** [comment]
This has been discussed at length and the conclusion is that for 1.1 you will need to upgrade everything to 1.1 (i.e. you can't just upgrade EF in an ASP.NET app and have the rest of ASP.NET be at 1.0 - since they share logging, DI, etc.) This may change in future releases, but we're going to use this approach for 1.1.

**Comment by lucamorelli** [comment]
Ok, thanks for the info. I hope that in a future this will change because to be unable to have different versions of the same packages in an app could be locking in the develpment and adoption of new features
