### ISSUE TITLE
Designer: No way to mark facets of entity properties not to be overriden by database facets

### ISSUE THREAD

**Issue by massimosignoritti** [dotnet/efcore#6527]
CodePlex link:
http://entityframework.codeplex.com/workitem/706

Youtube:
https://youtu.be/Rfpna7qnIn8

I use Visual Studio 2015 Community

Have you a solution for this issue?
Thank you

**Comment by rowanmiller** [comment]
This is the repository for EF Core, EF6.x is maintained at https://github.com/aspnet/EntityFramework6. That said, this issue isn't something we are planning to change in the EF6 designer. We would however consider a contribution for the change. 

If you (or someone else) decides to tackle this, our idea of how to support it would be an attribute that could be added to the property in C-Space to avoid facets getting overwritten from S-Space.
