### ISSUE TITLE
How to include multiple levels of related objects?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#6528]
I have the following data structure:

School has one Organization
Organization has many OrganizationCrossReferences (many to many intersection)
OrganizationCrossReference has one ParentOrganization and one ChildOrganization.

Now, I want to load a school, including its related Organization and ParentOrganizations.  In EF6 I would do:

```
schoolQuery.Include(s => s.Organization.ParentOrganizations.Select(p => p.ParentOrganization))...
```

In EF7 this isn't working; I get this error:

```
System.InvalidOperationException: The property expression 's => {from OrganizationCrossReference x in [s].Organization.ParentOrganizations select [x].ParentOrganization}' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.
```

What am I doing wrong?  Or is this a bug?

**Comment by ajcvickers** [comment]
@shaulbehr 
```C#
schoolQuery
    .Include(s => s.Organization)
    .ThenInclude(o => o.ParentOrganizations)
    .ThenInclude(p => p.ParentOrganization))...
```
