### ISSUE TITLE
Split MigrationsModelDiffer.Sort into two methods

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#6529]
Per @AndriySvyryd's comment on #6522
MigrationsModelDiffer.Sort should be split into two methods so that it doesn't need to be completely reimplemented when adding an operation

**Comment by rowanmiller** [comment]
@bricelam you can either just do this or we can talk more if you think it needs more thought

**Comment by bricelam** [comment]
Given our [design meeting discussion](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(September-15,-2016)), I don't think this is high enough priority for the 1.1.0 release.
