### ISSUE TITLE
Having IPreUpdateEventListener & IPreInsertEventListener in EF Core

### ISSUE THREAD

**Issue by VahidN** [dotnet/efcore#6535]
It's possible to query the change tracker and do some operations before and after insert/update/delete by overriding the SaveChanges method. but after a while, this method will become unmaintainable. We will have a method with a lot of different responsibilities.
NHibernate has [IPreUpdateEventListener & IPreInsertEventListener](https://ayende.com/blog/3987/nhibernate-ipreupdateeventlistener-ipreinserteventlistener) mechanism to manage it. 
Also there are some EF 6.x libraries to simulate it such as:
- [EFHooks](https://github.com/visoft/EFHooks/)
- [EntityHooks](https://github.com/dombrovsky/EntityHooks)

Do you have any plan to add this functionality to EF Core?

**Comment by rowanmiller** [comment]
This is covered by https://github.com/aspnet/EntityFramework/issues/626
