### ISSUE TITLE
EntityFrameWork in ClassLibrary

### ISSUE THREAD

**Issue by TeuryBazzo** [dotnet/efcore#6540]
{
  "version": "1.0.0-*",

  "dependencies": {
    "CorreAqui.Domain": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "NETStandard.Library": "1.6.0"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}

I've created a project MVC using architecture DDD, i'm trying to use  the entityframework in infra layer but when add Microsoft.EntityFrameworkCore.Tools i'm have this execption.

```
Exception message: NU1002 The dependency Microsoft.EntityFrameworkCore.Tools.1.0.0-preview2-final does not support framework .NETStandard, Version=v1.6


EF Core version: "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
Operating system: 
Visual Studio version: VS 2015 update 3
```

**Comment by rowanmiller** [comment]
See https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#targeting-class-library-projects-is-not-supported for details on this limitation (and workarounds)
