### ISSUE TITLE
Microsoft.EntityFrameworkCore isn't automatically installed in a UWP project

### ISSUE THREAD

**Issue by qmatteoq** [dotnet/efcore#6552]
### Steps to reproduce
1. Follow the tutorial http://ef.readthedocs.io/en/latest/platforms/uwp/ to get started with EF Core in a UWP Project
2. The tutorial will make you install the packages Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.Tools –Pre.
### The issue

The project will never work, because also the package Microsoft.EntityFrameworkCore is required to get EF Core properly working. However, this package isn't automatically installed as a dependency by any of the other packages
### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10 14393.105
Visual Studio version: Visual Studio 2015 Update 3
Other details about my project setup: Simple blank project for testing purposes

**Comment by rowanmiller** [comment]
We've retested the walkthrough and the steps work nw
