### ISSUE TITLE
Best practice to use read-only routing in always on cluster

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#6553]
If I have a always on sql cluster that use read-only routing. Does it exists any best practice how to configure this together with EFCore?

https://msdn.microsoft.com/en-us/library/hh213417.aspx
https://msdn.microsoft.com/en-us/library/hh710054.aspx?f=255&MSPPError=-2147217396

I can always create two different instances of the db-context with different connectionstrings but it should be good if it was able to have inbuilt logic for this scenarios to automatic select the correct db-connection depend on the operation.

**Comment by ajcvickers** [comment]
Possibly related to #6297

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFramework/issues/6525 might be useful for this

**Comment by DivenLee** [comment]
Right, this is the same as my need (#6297). Always hope that EF can choose to use the connection information that is written to the database connection information or read the connection information.

**Comment by ajcvickers** [comment]
It seems like #6525 could be the basis for this, so rather than keeping this issue open we will track any work on that issue, referencing this scenario as needed.
