### ISSUE TITLE
Need TransactionScope in .net core.

### ISSUE THREAD

**Issue by mukundabrt** [dotnet/efcore#6562]
**Need TransactionScope in .net core.**

We follow layer architecture pattern where transaction boundaries are determined in the business logic layer, not in the data access layer. Since the business layer is not aware of database connections, we cannot use connection based transaction APIs. 
As long as TransactionScope is not available in .net core we will have no choice.
... ... ... ...
Otherwise we have to change our architecture for .net core or move to classic.

**Comment by roji** [comment]
@mukundabrt this is tracked by https://github.com/dotnet/corefx/issues/2949. Note that TransactionScope has already been ported to .NET Core but will only be available in .NET Core 1.2.

Regardless, Entity Framework really has nothing to do with this.

**Comment by divega** [comment]
We'll need to do some work on EF Core: https://github.com/aspnet/EntityFramework/issues/5595.
