### ISSUE TITLE
Migration can not create cross-relations between two tables.

### ISSUE THREAD

**Issue by ArtemAvramenko** [dotnet/efcore#6566]
### Steps to reproduce

I define two models for department and employee:

``` cs
public class Dept
{
    [Key]
    public int DeptId { get; set; }

    [ForeignKey("ManagerId")]
    public Emp Manager { get; set; }

    public int? ManagerId { get; set; }

    public string DeptName { get; set; }
}

public class Emp
{
    [Key]
    public int EmpId { get; set; }

    [Required]
    [ForeignKey("DeptId")]
    public Dept Dept { get; set; }

    public int DeptId { get; set; }

    public string EmpName { get; set; }
}
```
### The issue

When I call Add-Migration, I get error:

```
The ForeignKeyAttribute on property 'Manager' on type 'App.Dept' is not valid.
The foreign key name 'ManagerId' was not found on the dependent type 'App.Emp'.
The Name value should be a comma separated list of foreign key property names.
```

EF can not create foreign/primary relation Dept.ManagerId/Emp.EmpId.
Moreover, when I rename ManagerId to EmpId, migration does not create relation Dept.EmpId/Emp.EmpId.

I expect that migration craetas two primary keys and two foreign keys (one with nullable field, other not nullable).
### Further technical details

EF Core version: 6.1.3
Operating system: Windows 8
Visual Studio version: VS 2015

**Comment by Librazy** [comment]
This project is for Entity Framework Core. For 6.1.3, you can seek help at https://github.com/aspnet/EntityFramework6
