### ISSUE TITLE
Ability to specify database collation

### ISSUE THREAD

**Issue by valamelkor** [dotnet/efcore#6577]
There is no way to do this at the moment. Database is created with default settings. It is not an issue on most cases, but there is a plenty of specific ones. For example, I have different collation on production server db, then on development machine. 

After some research I've come up with workaround. Pretty ugly so far, but at least working

In Migrations\00000000000000_CreateIdentitySchema.cs add

```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.Sql($"DECLARE @dbname sysname = db_name(); " +
    "EXEC('ALTER DATABASE [' + @dbname + '] SET SINGLE_USER WITH ROLLBACK IMMEDIATE');" +
    "EXEC('ALTER DATABASE [' + @dbname + '] COLLATE Cyrillic_General_CI_AS');" +
    "EXEC('ALTER DATABASE [' + @dbname + '] SET MULTI_USER') ", suppressTransaction: true);
    ...
}
```

It is ok. But the connection is reset after execution of this first migration so I have to run in separately. 
I've come up with the following script (resetdb.cmd): 

```
dotnet ef database update 00000000000000_CreateIdentitySchema
dotnet ef database update
```

So, there should be a proper way to do such things.

See also #6565

**Comment by rowanmiller** [comment]
We agree this would be useful. It's lower priority than the other features we are working on now, so moving to the backlog to look at in a future release.

**Comment by Ciantic** [comment]
EnsureCreatedAsync there, now this item can be found with GitHub search ;)

**Comment by seriouz** [comment]
I have a database with the collation set the be case sensitive. Now EF build its query with a temp table, but this temp table does not have the collation on the column so on the insert the database server throws an exception.

**Comment by divega** [comment]
@seriouz thanks for reporting this. Please create a new issue with more details. I think you mean to say `SaveChanges()` fails for you, as opposed to querying data. Can you please confirm?

You can try disable batching as a workaround. This can be done in either the `OnConfiguring()` method on the `DbContext` class or on the `AddDbContext()` method in `Startup`:

``` C#
    optionsBuilder = >optionsBuilder
        .UseSqlServer(connectionString)
        .MaxBatchSize(1);
```

cc @AndriySvyryd as FYI

**Comment by javiercampos** [comment]
Has anyone taken a look into this since Dec 2016? I'm using a different (albeit similar) workaround than the OP so I don't have to apply migrations independently (I just open a connection on the `Up` method and send the SQL directly) but it's definitely pretty ugly:

```csharp
[DbContext(typeof(MyDbContext))]
[Migration("00000000000000_SetupDatabase")]
public class SetupDatabase : Migration
{
	protected override void Up(MigrationBuilder migrationBuilder)
	{
		// HACK: there must be a better way
		using (var connection = new SqlConnection(MyContextOptions.ConnectionString))
		{
			connection.Open();
			using (var command =
				new SqlCommand(
					$"ALTER DATABASE [{MyDatabaseName}] COLLATE {MyDefaultCollation}",
					connection))
				command.ExecuteNonQuery();
			SqlConnection.ClearAllPools();
			connection.Close();
		}
	}
}
```

By chance (and I say by chance because as I understand, the `MigrationBuilder` only builds up the instructions that will be executed later and this could be done at any point in time) when the `Up` on this first migration is called, the database is already created but no tables have been created yet.

Still, having native support on SQL Server for this would be great... something like:
```csharp
migrationBuilder.AlterDatabase().Annotation("COLLATE", "WhateverCollation_CI_AI");
```
Should work

**Comment by morilon** [comment]
Do we have an update on this? I'll try this workaround but it would be great to have something configurable to do so.

Something more stylish as

`modelBuilder.Collation("Whatever_CI_AI")`

at least something that disables/enables CI/AI.

`modelBuilder.IsCollationSensitive(false)` or something.

**Comment by RedDeathGitHub** [comment]
Issue is open since 2016, any plans to fix this?

**Comment by ajcvickers** [comment]
@RedDeathGitHub This issue is in the Backlog milestone. This means that it is not going to happen for the 3.0 release. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by morilon** [comment]
Well, I created an extension using some examples I found and I've come up with this.

```
    public static class MigrationBuilderExtensions
    {
        public static void SetDatabaseCollationToInsensitive(this MigrationBuilder builder)
        {
            builder.Sql("DECLARE @dbname sysname = db_name(); " +
                        "EXEC('ALTER DATABASE [' + @dbname + '] COLLATE SQL_Latin1_General_CP1_CI_AI');", true);
        }
    }
```

And after creating your first migration just add the information on the top.

```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.SetDatabaseCollationToInsensitive();
}
```

It's working by just using Update-Database, works for me for now.

**Comment by RedDeathGitHub** [comment]
Before I was creating the Db manually earlier, but I run into "interesting" issue where just after creation - the Db did not accept connections yet. So migrations would try to create an existing Db.
Mostly an issue with testing and local environments but still a nasty one.

This looks interesting, I'll try it, thanks :).

**Comment by smitpatel** [comment]
@RedDeathGitHub - That is SqlServer behavior. After creating brand new database, it does not allow you to connect to it immediately. (Log in failed for user, which EF core uses as clue to non-existent database). We have also seen the same issue in our tests and have wait time and retry logic for that.

**Comment by ajcvickers** [comment]
Consider also character sets--see #15360

**Comment by ajcvickers** [comment]
See also scenario in #15776

**Comment by ajcvickers** [comment]
Also see high-level collations issue #19866

**Comment by rbasniak** [comment]
@cmanoliu 

@ajcvickers I tried your solution, but it seems it's using the custom migration class. Does your code should work on 3.1?

Since we can't debug the code, I tried to put log in the `Generate` method to be sure it's not hitting the method.

**Comment by roji** [comment]
Putting into the 5.0 milestone as per our design discussion.

**Comment by roji** [comment]
Note: am using this issue to track database collation (both at creation time and later alteration). For other database-creation settings, please open separate issues for the specific feature you're missing.
