### ISSUE TITLE
Relational: consider leveraging knowlege of uniqueness in the translation of Single[OrDefault]()

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#6595]
`Single[OrDefault]()` at the top of a query results in SQL that can potentially return 2 rows and then applies the in-memory operator to the results, while the translation of `First[OrDefault]()` produces SQL that could only ever return 1 row.

It has been asserted in https://github.com/aspnet/EntityFramework/issues/6517#issuecomment-248828219 that the "first" operators may perform better than the "single" operators in queries that filter by key equality. You could also argue that no `TAKE` is needed when we expect uniqueness constraints in the database to prevent more than one row containing the same value.

I am creating this bug for us to discuss a possible improvement here: If we measuring the performance of the query shows that there is a big potential gain we can consider leveraging uniqueness knowledge from metadata to produce a faster translation in certain cases.

**Comment by divega** [comment]
Related to #1948

**Comment by divega** [comment]
**EF Team Triage:**
Potential pros:
- Perf benefit?
- Customers seem to expect this behavior
Potential cons:
- Complexity
- Uniqueness may actuall not be enforced in the database

**Comment by ajcvickers** [comment]
We discussed this again at length, but ultimately decided that the value is not high enough when compared against the implementation cost. Therefore we are closing this as we don't plan to implement it. However, we would be happy to consider a well-written PR for this functionality if anyone in the community is willing to do so.
