### ISSUE TITLE
Better ReadOnly Entity Support

### ISSUE THREAD

**Issue by finite8** [dotnet/efcore#6600]
I have a lot of situations where i require that an entity must be read only. This includes things like Postcodes, Countries, Departments, Locations, etc. I need these mapped because i need to to queries and business logic based on them, but i need any attempt to make changes to these entities to be stopped. Obviously, it is a development issue if the application allows changes to such entities to be carried through, but if these issues are only detected after going live, it could be a costly mistake for an easily avoidable error.

My current workaround to get this behaviour is to do the following in my Entity Mapping Configuration (fluent)

```
MapToStoredProcedures(cfg => cfg
    .Insert(ccfg => ccfg.HasName("lolnope"))
    .Delete(ccfg => ccfg.HasName("lolnope"))
    .Update(ccfg => ccfg.HasName("lolnope")));
```

By giving it a stored procedure that doesn't exist, this prevents the entity either directly or indirectly (changing the entity when it is a child property on another entity) from ever having its changes being committed to the database. This seems to have the benefit of allowing me to be selective as well. For example, if i give it a false StoredProc for deletes, i can allow inserts and updates, but never a deletion.

Is it possible to get a Fluent Mapping option to prevent any combination of Insert, Update or Deletes on an entity, rather than my awfully hacky solution?

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework6#71
