### ISSUE TITLE
Records unexpectedly deleted

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#6605]
### Steps to reproduce

Quick domain description: Things optionally have a ThingColour.

This is a 'delete a colour' operation, which just sets a Retired flag on the colour, and goes through all associated Things, setting their Colour to `null`.

``` c#
            var match = _context.Set<ThingColour>()
                .Include(c => c.Things)
                .ThenInclude(b => b.Colour)
                .SingleOrDefault(c => c.Id == id);
            foreach (var thing in match.Things)
            {
                thing.Colour = null;
            }
            match.Retired = DateTime.UtcNow;
            _context.SaveChanges();
```

Note, my code had a bug - I set `IsRequired` in the config, as below:

``` c#
            e.HasOne(b => b.Colour).WithMany(c => c.Things).IsRequired();
```

...But I reckon that should throw an exception, not delete any Things which no longer have a Colour?
### The issue

All of the things that had the colour are deleted!  Was intending on setting the Colour of each of those Things to null.
### Further technical details

EF Core version: 1.1.0-alpha1-22157
Operating system: Win10
Visual Studio version: VS2015 U3

**Comment by ajcvickers** [comment]
@kierenj This is because required relationships (non-nullable FKs) get cascade deletes configured by default. See notes here: https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(August-27,-2015)

**Comment by kierenj** [comment]
Ok, I see all of the rationale there.  Of course, having found myself in this situation, at first it seems not the way I'd prefer it to work - exceptions over data loss - but I haven't had a mature ORM out in production for years as you guys have :)

Thanks for the quick and very direct response.
