### ISSUE TITLE
DBContext.OnModelCreating protection mode

### ISSUE THREAD

**Issue by rvmaccount** [dotnet/efcore#6608]
What is the rationale behind making OnModelCreating virtual method internal? The disadvantage is due to this method being internal one looses intellisence support in Visual Studio.

**Comment by ajcvickers** [comment]
@rvmaccount Internal is an implementation detail. From a public API perspective it is protected because it is only supposed to be used from a derived context class, typically by overriding it. You should get Intellisence support when using it from a derived class.

**Comment by rvmaccount** [comment]
@ajcvickers 
 i have tested this in Visual Studio 2015 Update 3; when internal is applied in a derived class Intellisence does not work. Looks like a VS 2015 issue.

**Comment by ajcvickers** [comment]
@rvmaccount Works for me.
![image](https://cloud.githubusercontent.com/assets/1430078/18881946/13066104-8492-11e6-89c3-1abc557b072b.png)
![image](https://cloud.githubusercontent.com/assets/1430078/18881948/17db1800-8492-11e6-89a4-8373b8ef0b57.png)

Can you post a screenshot of what you are seeing?

**Comment by rvmaccount** [comment]
@ajcvickers  thanks when things don't make restart the box. Works now. Thanks for your help.
