### ISSUE TITLE
Linq is generating left join SQL without Where

### ISSUE THREAD

**Issue by xaqi** [dotnet/efcore#6634]
EF Core version: 1.0.0

``` C#
void Main()
{
    var builder = new DbContextOptionsBuilder();
    builder.UseSqlServer(this.Connection.ConnectionString);
    var db = new MyContext(builder.Options);
    var q = (from a in db.Test
             join b in db.Test on a.Id equals b.Id into ab
             from b in ab.DefaultIfEmpty()
             where a.Id + b.Id > 100
             select new
             {
                 a,
                 b
             });
    q.ToList();
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class MyContext : DbContext
{
    public MyContext(DbContextOptions options) : base(options)
    {
    }
    public DbSet<Test> Test { get; set; }
}
```

The generating SQL is:
`
SELECT [a].[Id], [a].[Name], [b].[Id], [b].[Name]
FROM [Test] AS [a]
LEFT JOIN [Test] AS [b] ON [a].[Id] = [b].[Id]
ORDER BY [a].[Id]
`

The where expression for **a.Id + b.Id > 100** is lost in generated sql.

**Comment by smitpatel** [comment]
The where clause is not lost, it is evaluated on client since it could not be translated to Sql.

**Comment by gdoron** [comment]
@smitpatel Which leads to the question, why can't it be translated to SQL..?

**Comment by AndyQi** [comment]
All the rows in table Test are send to client, it's not exceptable. And the left join where clause works fine in EF6, what's the problem in EFCore?

**Comment by smitpatel** [comment]
@gdoron - due to #4588 
SQL generated using latest dev
```T-SQL
SELECT [a].[Id], [a].[Name], [b].[Id], [b].[Name]
FROM [Test] AS [a]
LEFT JOIN [Test] AS [b] ON [a].[Id] = [b].[Id]
WHERE ([a].[Id] + [b].[Id]) > 100
ORDER BY [a].[Id]
````

**Comment by gdoron** [comment]
@smitpatel I wish I could use the nightly builds of ASP & EF, unfortunately, I get compilation errors for some packages that can't target net461 😞  this is very annoying.
The whole process of upgrading packages in core is a real nightmare, at least for me, there's always something that breaks 😢

**Comment by smitpatel** [comment]
Fix for #4588 is not on nightly builds yet. Once its available I can help you out with building with nightly packages.

**Comment by gdoron** [comment]
@smitpatel 

Trying to update all the packages to the latest on myget feed:

> Package Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-preview3-22107 is not compatible with net461 (.NETFramework,Version=v4.6.1). 
Package Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-preview3-22107 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
Package Microsoft.Extensions.SecretManager.Tools 1.0.0-preview3-22284 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Microsoft.Extensions.SecretManager.Tools 1.0.0-preview3-22284 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
    One or more packages are incompatible with .NETFramework,Version=v4.6.1.

Any idea why is it failing?

Thanks!

**Comment by gdoron** [comment]
@smitpatel Or can you tell me where should I report this issue?
Thanks Smit.

**Comment by smitpatel** [comment]
@gdoron - Those packages are not compatible on net461. I tried installing `preview1-final` & `preview2-final` too which fails. So issue is not related to nightly builds.
Were those packages running on net461 target before?

**Comment by gdoron** [comment]
@smitpatel Something in the dotnet tooling isn't working properly when changing packages.
Many times `git clean` fixes those issues.

This is my current project.json, so yes, it works before:

	  {
	    "userSecretsId": "xxxxxxxxxxxxxxxxxxxx",
	
	    "dependencies": {
	      "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
	      "Microsoft.AspNetCore.Diagnostics": "1.0.0",
	      "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
	      "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
	      "Microsoft.AspNetCore.Mvc": "1.0.0",
	      "Microsoft.AspNetCore.Razor.Tools": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
	      "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
	      "Microsoft.AspNetCore.StaticFiles": "1.0.0",
	      "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
	      "Microsoft.EntityFrameworkCore.Tools": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
	      "Microsoft.Extensions.Configuration.Json": "1.0.0",
	      "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
	      "Microsoft.Extensions.Logging": "1.0.0",
	      "Microsoft.Extensions.Logging.Console": "1.0.0",
	      "Microsoft.Extensions.Logging.Debug": "1.0.0",
	      "Microsoft.Extensions.Caching.Memory": "1.0.0",
	      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
	      "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
	        "version": "1.0.0-preview2-final",
	        "type": "build"
	      },
	      "Yooocan.Entities": "1.0.0-*",
	      "Yooocan.Logic": "1.0.0-*",
	      "Serilog.Sinks.Seq": "2.0.0",
	      "Microsoft.AspNet.WebApi.Client": "5.2.3",
	      "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0",
	      "Microsoft.AspNetCore.Authentication.Google": "1.0.0",
	      "Microsoft.Azure.Search": "1.1.2",
	      "AspNet.Security.OAuth.LinkedIn": "1.0.0-beta1-final",
	      "Microsoft.AspNetCore.Session": "1.0.0",
	      "Serilog.Extensions.Logging": "1.1.0",
	      "AutoMapper": "5.0.2",
	      "Serilog": "2.2.0",
	      "StackExchange.Redis": "1.1.603",
	      "Google.Apis.Analytics.v3": "1.16.0.582"
	    },
	
	    "tools": {
	      "BundlerMinifier.Core": "2.0.238",
	      "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
	      "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
	      "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
	      "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
	      "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
	        "version": "1.0.0-preview2-final",
	        "imports": [
	          "portable-net45+win8"
	        ]
	      }
	    },
	
	    "frameworks": {
	      "net461": {
	        "frameworkAssemblies": {
	        }
	      }
	    },
	
	    "buildOptions": {
	      "emitEntryPoint": true,
	      "preserveCompilationContext": true
	    },
	
	    "runtimeOptions": {
	      "gcServer": true
	    },
	
	    "publishOptions": {
	      "include": [
	        "wwwroot",
	        "Views",
	        "appsettings.json",
	        "web.config"
	      ]
	    },
	
	    "scripts": {
	      "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
	      "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
	    }
	  }

**Comment by smitpatel** [comment]
Following one works for me. Interestingly, I got exception same as above when I put those packages under `dependencies` instead of `tools` node.
Restore should work without git clean. If you are able to get a consistent repro then you can probably report to nuget team.
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
      "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-*",
      "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0-*"
    },

    "tools": {
      "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview3-*",
      "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview3-*"
    },

    "frameworks": {
      "net461": {
        "frameworkAssemblies": {
        }
      }
    }
}
````

**Comment by gdoron** [comment]
@smitpatel I gave up, I spent hours but no luck.
This is so frustrating 😠 

Thanks anyway Smit!
