### ISSUE TITLE
Mapping FromSql to List<>

### ISSUE THREAD

**Issue by gbfromhb** [dotnet/efcore#6639]
I have created a model and have used a Stored Procedure and a View. It is returning two records with a few of the fields different if I query the stored procedure or the view form Sql Management Studio. When I use FromSql and tell it to map to a List<ActivationLink> it is duplicating the record twice and not giving me the two different records.

Here is the store procedure:

``` SQL
    SELECT a.ActIvationId, pfl.FormId, f.Url, c.CustomerName, at.Description AS EventType, m.Market, al.StoreName, al.RetailerAddress, al.RetailerCity, al.RetailerState, al.RetailerZipcode, al.PhoneNumber, a.StartDate, 
           a.StartTime, a.EndTime
    FROM dbo.Activations AS a 
        INNER JOIN dbo.ActivationTypes AS at ON a.ActivationTypeId = at.ActivationTypeId 
        INNER JOIN dbo.ActivationLocations AS al ON a.ActivationLocationId = al.LocationId 
        INNER JOIN dbo.ProjectMarkets AS pm ON al.ProjectMarketId = pm.ProjectMarketId 
        INNER JOIN dbo.Markets AS m ON pm.MarketId = m.MarketId 
        INNER JOIN dbo.Projects AS p ON pm.ProjectId = p.ProjectId 
        LEFT OUTER JOIN dbo.ProjectFormsLink AS pfl ON p.ProjectId = pfl.ProjectId 
        LEFT OUTER JOIN FormStack.Forms AS f ON pfl.FormId = f.FormId 
        INNER JOIN dbo.Customers AS c ON p.CustomerId = c.CustomerID
    WHERE a.ActIvationId = @ActivationId
```

Here is the View

``` SQL
SELECT        a.ActIvationId, pfl.FormId, f.Url, c.CustomerName, at.Description AS EventType, m.Market, al.StoreName, al.RetailerAddress, al.RetailerCity, al.RetailerState, al.RetailerZipcode, al.PhoneNumber, a.StartDate, 
                         a.StartTime, a.EndTime
FROM            dbo.Activations AS a INNER JOIN
                         dbo.ActivationTypes AS at ON a.ActivationTypeId = at.ActivationTypeId INNER JOIN
                         dbo.ActivationLocations AS al ON a.ActivationLocationId = al.LocationId INNER JOIN
                         dbo.ProjectMarkets AS pm ON al.ProjectMarketId = pm.ProjectMarketId INNER JOIN
                         dbo.Markets AS m ON pm.MarketId = m.MarketId INNER JOIN
                         dbo.Projects AS p ON pm.ProjectId = p.ProjectId LEFT OUTER JOIN
                         dbo.ProjectFormsLink AS pfl ON p.ProjectId = pfl.ProjectId LEFT OUTER JOIN
                         FormStack.Forms AS f ON pfl.FormId = f.FormId INNER JOIN
                         dbo.Customers AS c ON p.CustomerId = c.CustomerID
```

Getting the following when queried outside of EF

```
ActIvationId    FormId  Url
65              2457400 https://xxxxxxxxx.com/forms/stillhouse_recap
65              2480856 https://xxxxxxxxxx.com/forms/stilhouse_check_in 
```

Here is the EF query

``` C#
         List<ActivationLink> links = await _dbContext.ActivationLinks
            .FromSql("EXECUTE dbo.GetActivationLinksByActivationId {0}", activationId).ToListAsync();
```

Getting this
![image](https://cloud.githubusercontent.com/assets/2523931/18965554/93daf168-8632-11e6-8733-bc5c888a3930.png)

Notice the FormId and Url should be different

I have even put a unique index on FormID and it seem to not make a difference and still returned the identical records.

``` C#
         builder.Entity<ActivationLink>()
            .HasIndex(al => al.FormId).IsUnique();
```

The versions are:
  OS Name   Microsoft Windows 10 Pro Insider Preview - Version  10.0.14936 Build 14936
  Visual Studio 2015 - Version: 14.0.25431.01 Update 3
  Microsoft.EntityFrameworkCore.SqlServer: 1.0.1

Any advice would be greatly appreciated.

All the best,
Glenn Byron

**Comment by Vasimovic** [comment]
I am curious if you run the stored procedure directly let's say in SQL Server Managment Studio, does it return duplicate rows?

**Comment by EricABC** [comment]
I found I need to wrap the FromSql queries in an additional 'SELECT * FROM (<original>) someAlias'.  I noticed the query going out then gets the * rewritten to [someAlias].[col1], [someAlias].[col2] based on the original DbSet type for the query.  Aliasing the names in the inner query was not enough and would in my case cause multiple query execution when chaining more predicates after FromSql.

**Comment by gbfromhb** [comment]
Vasimovic. Both the stored procedure and the view results were fine no duplicates. Above there is a copy and paste of a part of the results from Sql Management Studio. This thing seems to take away tabs or spaces and it is hard to figure out what this was. 

`Getting the following when queried outside of EF

`ActIvationId   FormId     Url
65                    2457400 https://xxxxxxxxx.com/forms/stillhouse_recap
65                    2480856 https://xxxxxxxxxx.com/forms/stilhouse_check_in`

**Comment by smitpatel** [comment]
@gbfromhb - If `ActivationId` is PK for `ActivationLinks` then when EF tries to materialize data into ActivationLinks then it will do identity resolution and records with same `ActivationId` will be expected to be same and therefore 2nd record actually does not materialize and it will be same as the first one.
EF will not have 2 different entity object with same identity (or PK) in context.
If you still want to have multiple records then you need to map results into non-entity type. It is being tracked by #1862

**Comment by divega** [comment]
Just to add to what @smitpatel is saying, you may just want to change the key of `ActivationLink` to be unique for each row from the query results, e.g. a composite key on `ActivationId` and `FormId`.
