### ISSUE TITLE
Add-Migration - Failed...

### ISSUE THREAD

**Issue by mvermef** [dotnet/efcore#6661]
### The issue is associated UWP application....

PM> Add-Migration CategoryNav
Add-Migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The 
located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"
At line:1 char:1
- Add-Migration CategoryNav
- ~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
  - FullyQualifiedErrorId : FileLoadException,Add-Migration

```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.DependencyInjection": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.*",
    "Newtonsoft.Json": "9.0.1"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

Was trying to run the migration due to some errors.  going back in time I have tried getting assembly load errors for EFC.  Can't find it etc.  Multiple attempts to "get the pack" doesn't seem to work. 

EF Core version: 1.0.1
Operating system: WIn10 AU 1607
Visual Studio version: VS.net 2015 U3

**Comment by divega** [comment]
@mvermef see https://github.com/aspnet/EntityFramework/issues/6551 and the workaround at https://github.com/aspnet/EntityFramework/issues/6551#issuecomment-247840623 in particular.
