### ISSUE TITLE
fromsql why???

### ISSUE THREAD

**Issue by kencery** [dotnet/efcore#6663]
![image](https://cloud.githubusercontent.com/assets/7973271/19022797/c56513e8-8912-11e6-8620-83a6c59121b0.png)

发现EFCore不能支持自己建立的没有映射的实体对象，会出现以下错误，
![image](https://cloud.githubusercontent.com/assets/7973271/19022804/f6d7266e-8912-11e6-828f-3bebbdc4304d.png)

，please tell me ，thank you

**Comment by freshe** [comment]
FromSql only works with entities within your DbContext. The old EF < 7 SqlQuery<T> is coming up in 1.1 #1862

**Comment by divega** [comment]
`FromSql()` currently only works with `DbSets<TEntity>`, and that means with entity types that are added to the model either in `OnModelCreating()` or by having a `DbSet<TEntity>` property in a derived `DbContext`. You did not include your `DbContext` code but I assume `UserDepartRoleInfo` is not mapped. You must be looking for https://github.com/aspnet/EntityFramework/issues/1862
