### ISSUE TITLE
OnDelete behaviour setting is incorrect in generated migration class.

### ISSUE THREAD

**Issue by erisiasoft** [dotnet/efcore#6668]
### Steps to reproduce

I'm afraid the project is broken right now, but repro steps are as follows:

Model is Contact, with two FKs:

```
public class Contact: BaseModel
{
    public int Id { get; set; }
    public virtual Title Title { get; set; }
    public int TitleId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
    public Gender Gender { get; set; }
    public int GenderId { get; set; }

}
```

Configure the included Contact model as follows:

```
modelBuilder.Entity<Contact>()
    .HasOne(e => e.Gender)
    .WithMany()
    .HasForeignKey(e => e.GenderId)
    .OnDelete(DeleteBehavior.Restrict);

modelBuilder.Entity<Contact>()
    .HasOne(e => e.Title)
    .WithMany()
    .HasForeignKey(e => e.TitleId)
    .OnDelete(DeleteBehavior.Restrict);
```

Add an initial (create DB) migration. The OnDelete behaviours are generated as follows. Note the OnDelete values:

constraints: table =>
{
    table.PrimaryKey("PK_Contact", x => x.Id);
    table.ForeignKey(
        name: "FK_Contact_Gender_GenderId",
        column: x => x.GenderId,
        principalTable: "Gender",
        principalColumn: "Id",
        onDelete: ReferentialAction.SetNull);
    table.ForeignKey(
        name: "FK_Contact_Title_TitleId",
        column: x => x.TitleId,
        principalTable: "Title",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
});
### The issue

The OnDelete behaviours in the migration seem totally random vs. those confgigured for the 'Contact' model class. I specify `DeleteBehaviour.Restrict' for both foreign keys, and the migration class has one 'DeleteBehaviour.
### Further technical details

EF Core version: (found in project.json or packages.config)

```
"Microsoft.EntityFrameworkCore": "1.0.1",
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
"Microsoft.EntityFrameworkCore.Commands": "0.0.1-alpha",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
```

Operating system: Windows 10 Pro
Visual Studio 2015 Upgrade 3

Just a single console project with only the data related stuff, since EF Core doesn't work properly in Core c;lass libraries yet.

**Comment by smitpatel** [comment]
I am not able to reproduce this. Following is what I get trying to add initial migration.
Version no.
EF.SqlServer 1.0.0
EF.Tools 1.0.0-preview2-final
EF.Design 1.0.0-preview2-final

In your project.json you have reference to `Microsoft.EntityFrameworkCore.Commands` which was deprecated a while ago and should be removed.

```C#
//DbContext & model classes
public class MyContext : DbContext
{
    public DbSet<Contact> Contacts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;")
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contact>()
            .HasOne(e => e.Gender)
            .WithMany()
            .HasForeignKey(e => e.GenderId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Contact>()
            .HasOne(e => e.Title)
            .WithMany()
            .HasForeignKey(e => e.TitleId)
            .OnDelete(DeleteBehavior.Restrict);

    }
}

public class Contact
{
    public int Id { get; set; }
    public virtual Title Title { get; set; }
    public int TitleId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
    public Gender Gender { get; set; }
    public int GenderId { get; set; }
}

public class Gender
{
    public int Id { get; set; }
}

public class Title
{
    public int Id { get; set; }
}
//constraints generated in migration file
constraints: table =>
{
    table.PrimaryKey("PK_Contacts", x => x.Id);
    table.ForeignKey(
        name: "FK_Contacts_Gender_GenderId",
        column: x => x.GenderId,
        principalTable: "Gender",
        principalColumn: "Id",
        onDelete: ReferentialAction.Restrict);
    table.ForeignKey(
        name: "FK_Contacts_Title_TitleId",
        column: x => x.TitleId,
        principalTable: "Title",
        principalColumn: "Id",
        onDelete: ReferentialAction.Restrict);
});
```
Can you provide a stand-alone repro (with project.json)?

**Comment by erisiasoft** [comment]
Thank you. Amazing how just removing a package fixed it so nicely.
