### ISSUE TITLE
Change API surface for using fields with navigation properties

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#6674]
Because navigation properties are configured using the relationship API there is not currently any way to easily address the navigation properties such that backing fields can be easily configured.

**Comment by ajcvickers** [comment]
This is the current code needed to set property access mode for a navigation property:
```C#
modelBuilder.Entity<Blog>()
    .Metadata
    .FindNavigation(nameof(Blog.Posts))
    .SetPropertyAccessMode(PropertyAccessMode.Field);
```

Proposal 1:
```C#
modelBuilder.Entity<Blog>()
    .HasMany(e => e.Posts)
    .WithOne(e => e.Blog)
    .UsePropertyAccessMode(PropertyAccessMode.Field);
```
This would set the property access mode for all navigation properties of the relationship. This is probably sufficient granularity for almost all applications. Dropping down to core metadata can still be used if each navigation property needs different access.

Proposal 2:
As above, but also sets the property access mode of the FK. This makes the following a little less ambiguous:
```C#
modelBuilder.Entity<Blog>()
    .HasMany(e => e.Posts)
    .WithOne(e => e.Blog)
    .HasForeignKey(e => e.BlogId)
    .UsePropertyAccessMode(PropertyAccessMode.Field);
```

Proposal 3:
As above, but with a modifier flag to choose which of the dependent/principal/FK property to set the access mode for. The default would be to set it for all--i.e. collapsing into proposal 2.
```C#
modelBuilder.Entity<Blog>()
    .HasMany(e => e.Posts)
    .WithOne(e => e.Blog)
    .HasForeignKey(e => e.BlogId)
    .UsePropertyAccessMode(
       PropertyAccessMode.Field, 
       Navigation.Dependant | Navigation.Principal);
```

Proposal 4:
Add an optional second argument to HasMany, WithOne, etc. that allows a nested closure of configuration for the navigation property. 
```C#
modelBuilder.Entity<Blog>()
    .HasMany(
        e => e.Posts, 
        nb => nb.UsePropertyAccessMode(PropertyAccessMode.Field))
    .WithOne(
        e => e.Blog, 
        nb => nb.UsePropertyAccessMode(PropertyAccessMode.Field))
```
This has the advantage that it is a more general solution for the addressing of navigation properties in the fluent API, but may be over-kill.

**Comment by rowanmiller** [comment]
We will do `#4` and can look at sugar in the future if folks get confused

**Comment by julielerman** [comment]
With the current workaround syntax that allows us to use the Metadata to identify a backing field for a navigation property, is there a way to do that when you've made the navigation property totally private? Thanks

**Comment by ajcvickers** [comment]
@julielerman Can you post a code snippet that is not working? It should not matter if the navigation is private or not, but maybe there is something not working correctly in the metadata lookup?

**Comment by julielerman** [comment]
will do  as soon as I can
On Jul 12, 2017, at 11:40 AM, Arthur Vickers <notifications@github.com<mailto:notifications@github.com>> wrote:


@julielerman<https://github.com/julielerman> Can you post a code snippet that is not working? It should not matter if the navigation is private or not, but maybe there is something not working correctly in the metadata lookup?

**Comment by julielerman** [comment]
mini repro still fails. I'll show it to you if you aren't having the problem (e.g. I'm doing something wrong )  FWIW I'm using rtm-* and 
```
Product Information:
 Version:            2.0.0-preview3-006736
 Commit SHA-1 hash:  49dfa8e96b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview3-006736/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25511-03
  Build    : 6e7dadfdaed031624319dfd61415b2ce3498aa51
```

**Comment by ajcvickers** [comment]
@julielerman I am not able to reproduce this. Can you post the entity types and OnModelCreating code?

**Comment by ajcvickers** [comment]
Ah, it might be this. If the relationship is configured like this:
```C#
modelBuilder.Entity<Samurai>().HasOne("Entrance").WithOne();
```
which looks reasonable, but is wrong, then it will result in no exception, but also will not configure the relationship correctly. This is because in the single string overload the string is the entity type name, not the navigation name. This is pretty confusing. @AndriySvyryd @divega. (It should ultimately result in model validation failure, but the null ref on the missing navigation is likely happening before then.)

The correct way to configure it is something like:
```C#
modelBuilder.Entity<Samurai>().HasOne(typeof(Entrance), "Entrance").WithOne();
```

**Comment by smitpatel** [comment]
There isn't overload of `HasOne` which takes 1 string parameter. How the first one would compile?

**Comment by ajcvickers** [comment]
@smitpatel It compiled for me...

**Comment by ajcvickers** [comment]
```C#
 public virtual ReferenceNavigationBuilder HasOne(
            [NotNull] string relatedTypeName,
            [CanBeNull] string navigationName = null)
```

**Comment by julielerman** [comment]
Oh! I didn’t explicitly configure the relationship. It’s one of those nice FK in the dependent mappings that EF Core can figure out.

 I’ll try that first! Can’t do it right away though. But good to know there IS a way! Thanks

On Jul 12, 2017, at 4:44 PM, Arthur Vickers <notifications@github.com<mailto:notifications@github.com>> wrote:


 public virtual ReferenceNavigationBuilder HasOne(
            [NotNull] string relatedTypeName,
            [CanBeNull] string navigationName = null)

**Comment by divega** [comment]
@ajcvickers I agree that is confusing :disappointed: The fact that the type isn't being specified as a generic argument but is still needed is very easy to miss. I wonder if this is the only API in which this happens. 

If we believe it is worth addressing it, something like this may help:

1. Obsolete this version of `HasOne` that doesn't take a generic argument 
2. Create a new API called `HasOneOfType` for this case. It would look like this:

``` C#
modelBuilder.Entity<Samurai>().HasOneOfType("Entrance", navigationName: "Entrance")
    .WithOne();
```

I think it helps because it reads like the (first) argument is the type. 

This looks complicated though:

``` C#
modelBuilder.Entity<Samurai>().HasOneOfType(typeof(Entrance), navigationName: "Entrance")
    .WithOne();
```

Maybe we do it only for the one that works with strings?

Perhaps there is a better solution.

**Comment by julielerman** [comment]
I'm still messing about with this trying to find the pattern that works.
I'll go back to my original setup:
```
public class Samurai {
  public int Id { get; set; }
  public string Name { get; set; }
  private Entrance Entrance{get; set;}
  public void CreateEntrance(string description){
    Entrance=new Entrance{Description=description};
  }
  public string EntranceDescription=>Entrance.Description;
  public int EntranceId=>Entrance.Id;  //this was just for testing :)
}
public class Entrance {
  public int Id { get; set; }
  public string Description { get; set; }
  public int SamuraiId { get; set; }
}
```
Before trying to encapsulate the Entrance property, this was fine with the EFCore groking the 1:1 relationship and that Entrance was the dependent.

I had no other configs in the context than those listed above.
I had to use the propertyinfo setup since Entrance wasn't visible to the compiler.
This ran but caused FindNavigation to return null.

Focusing on the fact that you seem to have explicit Fluent Api configuration, I first tried  adding in Arthurs first suggestion .... even trying with no parameter in withOne and still not adding the samurai navigation property to Entrance:

 ```
protected override void OnModelCreating (ModelBuilder modelBuilder) {
    modelBuilder.Entity<Samurai> ()
      .HasOne (typeof (Entrance), "Entrance")
      .WithOne ();
    var propinfo = typeof (Samurai).GetProperty ("Entrance");
    modelBuilder.Entity<Samurai> ()
      .Metadata
      .FindNavigation (propinfo)
      .SetPropertyAccessMode (PropertyAccessMode.Field);
    base.OnModelCreating (modelBuilder);
  }
```
Again, it threw when it hit FindNavigation.

Next I added in the Samurai navigation property to Entrance and added "Samurai" as the parameter of WithOne(). (Interesting that I couldn't use a lambda. Is that because I didn't use a lambda with the HasOne?)
Here's what it looks like for this iteration

``` protected override void OnModelCreating (ModelBuilder modelBuilder) {
    modelBuilder.Entity<Samurai> ()
      .HasOne (typeof (Entrance), "Entrance")
      .WithOne ("Samurai");
    var propinfo = typeof (Samurai).GetProperty ("Entrance");
    modelBuilder.Entity<Samurai> ()
      .Metadata
      .FindNavigation (propinfo)
      .SetPropertyAccessMode (PropertyAccessMode.Field);
    }```

I got the same result...null error on FindNavigation.

Do you see yet what I'm doing differently than you?

**Comment by ajcvickers** [comment]
There are quite a few things going on here, so I'll try to explain them one by one. First the relationship discovery. Using this code:

```C#
public class Samurai
{
    public int Id { get; set; }

    public string Name { get; set; }

    public Entrance Entrance { get; set; }

    public void CreateEntrance(string description)
        => Entrance = new Entrance { Description = description };

    public string EntranceDescription => Entrance.Description;

    public int EntranceId => Entrance.Id;
}

public class Entrance
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int SamuraiId { get; set; }
}

public class SamuraiContext : DbContext
{
    public DbSet<Samurai> Samurais { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

```

Notice that the navigation property is public. Conventions only use public navigation properties when traversing the graph to discover relationships. (We tried various other options early in EF Core pre-releases, but trying to use non-public members tended to bring in too many things erroneously.) So because there is a public navigation from Samurai to Entrance, Entrance is brought into the model together with the association between the types. At this point the relationship exists, so the FK can be discovered, etc. and the relationship becomes a unidirectional 1:1.

Now if the navigation property is made private it will no longer be found by convention. Therefore, it has to be configured explicitly--this is generally true for navigations and properties; once they are made private, they need to be configured. The way to configure navigation properties in EF is to use the relationship API:

```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Samurai>().HasOne(typeof(Entrance), "Entrance").WithOne();
    }
}
```

Notice that the FK still does not need to be configured because once EF knows about the private navigation property it can then find the public FK by convention.

Also notice that I use a string here for the navigation name. If it were public I could have the compiler help me generate the string and keep in sync with the code using `nameof(Samurai.Entrance)`. But after compilation the result is the same--call to HasOne with a string as the second argument.

Now, moving on to the code to force use of a backing field, for which we need to find the navigation property in the underlying metadata. The easiest way to do this with a private navigation is again to use its name as a string:

```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Samurai>().HasOne(typeof(Entrance), "Entrance").WithOne();

        var navigation = modelBuilder.Entity<Samurai>()
            .Metadata
            .FindNavigation("Entrance");

        navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
    }
```

I'm not using nameof as before because the navigation is private, but the code is again exactly the same after compilation.

Notice that this is only a call to find an existing navigation from metadata--it will never create the navigation in the way that a fluent API might. 

It is possible to use the PropertyInfo instead of the string, but this doesn't usually help anything because you need to use the string anyway to find the PropertyInfo. (The PropertyInfo overloads are useful when you already have a PropertyInfo from doing other things and don't want EF to go look it up again.) Now if the navigation property is public, then this will work:

```C#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Samurai>().HasOne(typeof(Entrance), "Entrance").WithOne();

        var propinfo = typeof(Samurai).GetProperty("Entrance");

        var navigation = modelBuilder.Entity<Samurai>()
            .Metadata
            .FindNavigation(propinfo);

        navigation.SetPropertyAccessMode(PropertyAccessMode.Field);
    }
```

But if the navigation is private then `GetProperty` returns null because it only finds public properties. Of course, there are ways of getting the PropertyInfo for a private property, and then this would work, but I think it's much easier just to use the string directly and let EF take care of the rest.

Hope this helps!

**Comment by julielerman** [comment]
Thanks Arthur.

The bottom line was that the _only_ change I needed was to use the string in FindNavigation. That was one thing I had either never tried, or tried with the wrong set up and didn't try again after adjusting things. 
My entities:
```
public class Samurai {
  public int Id { get; set; }
  public string Name { get; set; }
  private Entrance Entrance {get; set;} //note this is private YAY
  public void CreateEntrance(string description){
    Entrance=new Entrance{Description=description};
  }
   public string EntranceDescription=>Entrance.Description;
}
public class Entrance {
  public int Id { get; set; }
  public string Description { get; set; }
  public int SamuraiId { get; set; }  //note there is no navigation property YAY
 }

```
My context:

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

```
public class MyContext : DbContext {
  public DbSet<Samurai> Samurais { get; set; }
  protected override void OnModelCreating (ModelBuilder modelBuilder) {
    modelBuilder.Entity<Samurai>().HasOne (typeof (Entrance), "Entrance").WithOne ();
    modelBuilder.Entity<Samurai> ()
      .Metadata
      .FindNavigation ("Entrance")
      .SetPropertyAccessMode (PropertyAccessMode.Field);
  }
  protected override void OnConfiguring (DbContextOptionsBuilder optionsBuilder) {
    optionsBuilder.UseInMemoryDatabase ("OwnedOneToOne");
  }
}
```
I'm able to build and store Samurai/Entrance graphs and even query using Include (with the string).

Thank you.

**Comment by ajcvickers** [comment]
@julielerman Curious, are you actually going to create a backing field for Entrance? As the code is now the behavior should be the same regardless of whether you set PropertyAccessMode.Field or not, since the property is an auto-property and there is no difference accessing through the property or field.

**Comment by julielerman** [comment]
This is interesting and a really nice surprise. With the hasone/withone I can make the Entrance private with {get;set;} and EF sees it.  Is that because the backing field logic is picking up the auto property? I would never have thought to try that. 
Now I will add in a backing field and see the difference (with/without the setpropertyaccessmode config)

**Comment by julielerman** [comment]
ok, i see that with the backing field there but without the setpropertyaccessmode config, the property isn't materialized and with the config, it is.
Lots of great options available here!
Still curious about the question: with PRIVATE navigation and auto-properties PLUS the has/one config to tell EF Core about the navigation property, does that all work because of the backing fields?

**Comment by ajcvickers** [comment]
@julielerman  Looking at the code above (posted in this comment: https://github.com/aspnet/EntityFramework/issues/6674#issuecomment-315078717) there are no backing fields involved. (Other than the compiler-generated ones for the auto-properties, which can be ignored since they have no functional impact.) So I'm not sure what you are referring to by "backing field logic" or "work because of the backing fields?" Can you provide a bit more detail about what you are asking?

**Comment by julielerman** [comment]
I'm sorry. I do weird things. :) You've said that if I don't have a backing field (same as your code, except Entrance is now private), I don't need to use the extra config (to set property access mode). (Also, based on what I've done, I don't think you need it either and I thought that's what you were suggesting when you asked about the backing fields...) removed that configuration and indeed my tests work...samurai/ entrance graph is inserted into the data store and the same is materialized in response to a query.

When I modify Samurai so that I have an _entrance field, use that in the getter ala:
```
  private Entrance Entrance { get{return _entrance;} set{} }
  private Entrance _entrance; // <-my backing field 
  public void CreateEntrance (string description) {
    _entrance = new Entrance { Description = description };
  }
  public string EntranceDescription => _entrance?.Description;

```
 and in my methods, at first my tests fail in that I'm not getting the Entrance data back. But when I add the config back:

```
  modelBuilder.Entity<Samurai> ()
      .Metadata
      .FindNavigation ("Entrance")
      .SetPropertyAccessMode (PropertyAccessMode.Field);
```

the entrance data that I saved is materialized again in a query.

**Comment by ajcvickers** [comment]
Okay, yes. That makes sense. It fails because the property setter does nothing in your code, but changing EF to always use the backing field means it never calls the setter, but instead writes directly to the backing field. (Of course, usually you would just not have the setter, rather than having a do-nothing setter, but I assume you are only doing this to experiment.)

**Comment by julielerman** [comment]
"makes sense" : phew! And because I try all the things, I can change the name of the backing field and set it with a second metadata config:
modelBuilder.Entity<Samurai> ()
      .Metadata
      .FindNavigation ("Entrance")
      .SetField("_entranceX");

**Comment by julielerman** [comment]
Ok ....now with 
```
 private Entrance Entrance { get{return _entrance;} }
 private Entrance _entrance;
```
I seem to have no reason at all to explicitly configure the property access mode. Does that sound right?

**Comment by ajcvickers** [comment]
Yes, because there is a backing field and there is no setter, so EF just uses the backing field since there is nothing else it can use.

**Comment by julielerman** [comment]
"because there is nothing else to use" ....that's important. It's figuring it out (well you guys wrote it to be smart enough to do that thank you)
Also I just want to clarify that for the navigation property, there seems to be no reason to explicitly configure property access whether or not I have a backing field. Period.

**Comment by ajcvickers** [comment]
The reason to configure it would be if you have some logic in the property setter that you want EF to by-pass when it is setting the value. In other words, your property setter might do more than just setting the value, but you want EF to really just set the value.

**Comment by julielerman** [comment]
That would be the real use case for the backing field. But honestly, I found that in that scenario I still was getting results without using the configuration.

(Also, the fieldname configuration is needed (makes sense) when the backing field doesn't follow convention)

**Comment by julielerman** [comment]
```
 private Entrance Entrance {
    get { return _entrance; }
    set {
         if (value.Description == "abcde") { Console.WriteLine ($"we got {value.Description}"); }
          _entrance = value;
    }
  }
```
works without the configuration. In other words:
- it compiled,
- it ran without exceptions,
- when I called CreateEntrance, I got the message output.
- When I did a query, it did not output the message

So that we can both get back to work, I'm going to leave it at this  ("don't need the config but do read this issue for more info!") with the article which will clearly be marked as using preview bits when it gets published.

**Comment by lajones** [comment]
Poaching.

**Comment by AndriySvyryd** [comment]
@lajones Take a look at https://github.com/dotnet/efcore/pull/11610, especially the tests should be useful

**Comment by lajones** [comment]
Thanks @AndriySvyryd . I came to the same conclusion. Only I didn't want to use `NonRelationshipTestBase` as my tests are specifically about navigations - so created a new class in the same directory.

**Comment by lajones** [comment]
- [ ] Whichever approach the team likes remove the other one
