### ISSUE TITLE
What does NotImplementedException: Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.IncludeResultOperator mean?

### ISSUE THREAD

**Issue by rykr** [dotnet/efcore#6688]
### Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

I am trying to perform this query:

```
        var members = _data.TeamMemberships
            .Include(tm=>tm.Member)
            .Where(tm=>tm.TeamId == team_id && tm.LeftTeam == null)
            .Select( x => new  TeamRosterViewModel.MemberStat {
                Membership = x, 
                TotalPlayed = _data.PlayerMatchResults.Include(p=>p.Match).Where(p=>p.PlayerId == x.MemberId && p.Match.Status == MatchStatus.Finished).Count(),
                TotalWon = _data.PlayerMatchResults.Include(p=>p.Match).Where(p=>p.PlayerId == x.MemberId && p.Result == MatchResult.Won && p.Match.Status == MatchStatus.Finished).Count(),
                SessionPlayed = 0,
                SessionWon = 0
            }).ToList();
```
### The issue

Describe what is not working as expected.

The subquery counts that I have in the select block are throwing the exception mentioned above.  The counts are working but the include in each of the subquery is causing the problem.  If I remove the include from the two subqueries they run ok.

The exception is NotImplementedException: Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.IncludeResultOperator

Can we not do an include in the subquery?

**Comment by maumar** [comment]
Could you also provide code for your entity classes, as well as the DbContext used? (In particular contents of OnModelCreating)

**Comment by maumar** [comment]
Usually you want to do Include on a top level, before any other operators. Moreover, for your scenario Include is it needed. EF will fetch all the data needed to complete the query automatically. Include is only needed if you want to access navigations of the entities returned by a query in your application. However this is definitely a bug, since we shouldn't be throwing NotImplementedException is n any circumstance

**Comment by rykr** [comment]
I was able to get it working by changing to this:

            var members = from tm in _data.TeamMemberships
                where tm.TeamId == team_id && tm.LeftTeam == null
                select new TeamRosterViewModel.MemberStat {
                    Membership = tm,
                    TotalPlayed = (from pmr in _data.PlayerMatchResults where pmr.PlayerId == tm.MemberId && pmr.Match.Status == MatchStatus.Finished select pmr).Count(),
                    TotalWon = (from pmr in _data.PlayerMatchResults where pmr.PlayerId == tm.MemberId && pmr.Result == MatchResult.Won select pmr).Count(),
                    SessionPlayed = (from pmr in _data.PlayerMatchResults 
                        where pmr.PlayerId == tm.MemberId && 
                        pmr.Match.Status == MatchStatus.Finished && pmr.Match.TeamMatch.SessionId == session.SessionId select pmr).Count(),
                    SessionWon = (from pmr in _data.PlayerMatchResults 
                        where pmr.PlayerId == tm.MemberId && 
                        pmr.Result == MatchResult.Won && pmr.Match.TeamMatch.SessionId == session.SessionId select pmr).Count(),
                };

Not really sure what the difference is but it works now.
