### ISSUE TITLE
First row only then getting data from model with self-reference

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#6723]
I have 2 pretty similar models 
Company and Category

Category has self-reference eg 
public int CategoryId { get; set; }
public int? ParentCategoryId { get; set; }
public Category ParentCategory { get; set; }

So then I get data from Company  (by _context.Companies;) and send it to client via JsonResult I got all row in Json as usual buy then I try to do same with Category I get first row only.

Models

```
public class Category
    {
        [Key]
        [ScaffoldColumn(false)]
        public int CategoryId { get; set; }
        [Display(Name = "Название")]
        public string Title { get; set; }
        public int? ParentCategoryId { get; set; }
        public Category ParentCategory { get; set; }
    }

public class Company
    {
        [Key]
        [ScaffoldColumn(false)]
        public int CompanyId { get; set; }
        public string Title { get; set; }
        public string MainPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string TertiaryPhone { get; set; }
    }
```

Code

```
        public JsonResult Read2([DataSourceRequest] DataSourceRequest request)
        {
            var result = _context.Companies;

            return Json(result);
        }
```

Returns 

```
[{"CompanyId":1,"Title":"Comany1","MainPhone":"Comany1","SecondaryPhone":"Comany1","TertiaryPhone":"Comany1"},{"CompanyId":2,"Title":"Comany2","MainPhone":"Comany2","SecondaryPhone":"Comany2","TertiaryPhone":"Comany2"}]
```

but same 

```
        public JsonResult Read2([DataSourceRequest] DataSourceRequest request)
        {
            var result = _context.Categories;

            return Json(result);
        }
```

returns
[{"CategoryId":3,"Title":"First","ParentCategoryId":null}]

But I have 3 row in Category table.

I am totally unsure that is going wrong and where is a problem. In debug I see jsonresult with 3 objects before it send to client. 

here is data
https://1drv.ms/i/s!AvdtTGXIWO4bg-4rElK7y75gOSox3A

**Comment by dvdobrovolskiy** [comment]
have to admit removing
public Category ParentCategory { get; set; }
from model gives me 3 records now

[{"CategoryId":3,"Title":"First","ParentCategoryId":null},{"CategoryId":4,"Title":"Second","ParentCategoryId":null},{"CategoryId":5,"Title":"Third","ParentCategoryId":null}]

**Comment by rowanmiller** [comment]
Moved to https://github.com/aspnet/Mvc/issues/5393

**Comment by jbagga** [comment]
@dvdobrovolskiy Could you provide more information? Please see [aspnet/Mvc#5393](url)
