### ISSUE TITLE
Include -> ThenInclude on List / Collection Navigation Property accesses the List and not the item contained within

### ISSUE THREAD

**Issue by Nick-Lucas** [dotnet/efcore#6734]
Posting this as it took me ages to find issue #6560 which resolved this problem.
Hopefully this title contains more useful keywords for anyone else searching for the issue.

_Short story_ is it's an intellisense bug, so type your lambda as if it was passing on a object and get on with your day. 🛩

**Comment by divega** [comment]
Please if you hit this provide your feedback on the actual issue https://github.com/dotnet/roslyn/issues/8237 so that the Roslyn team can prioritize it.
