### ISSUE TITLE
Make tools work with Microsoft.EntityFrameworkCore.Design.Core

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#6743]
This is part of #6549

We need to ensure the next release of the tools will work with Microsoft.EntityFrameworkCore.Design version 1.0.0-preview2-final since we don't plan to release a new version before the 1.0.2 release (See #6742)

This is a temporary measure and will be removed before tools RTM.

**Comment by bricelam** [comment]
This won't work. That version doesn't contain the types we need. We need to release a new 1.0 version alongside the next tools release.

**Comment by smithaitufe** [comment]
I don't know the package that contains IDesignTimeDbContextFactory? I can't find. I have installed Microsoft.EntityFrameworkCore.Design package and yet I can't find it
