### ISSUE TITLE
Clarification on #6273 - Existing SQLite DB on first migration

### ISSUE THREAD

**Issue by Chris-Marassovich** [dotnet/efcore#6762]
Hello @bricelam,

In issue #6273 you provided a solution.
I am seeking further clarification on where I can find those values for MigrationId and ProductVersion?

```
INSERT OR IGNORE INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"")
        VALUES ('20160627142134_InitialCreate', '1.0.0');        
```

In my UWP app I am using EFCore for the v2 and in v1 I used another ORM so the DB will exist already in many cases.
I followed the example in the EF Docs to create the migration and I have just the one so far.
I named it FirstMigration.
In the designer file in the migrations folder I can see an attribute
`[Migration("20160812092518_FirstMigration")]`
I assume this is the MigrationId to use in the insert solution you provided?
In the same file I see a code snippet
`modelBuilder.HasAnnotation("ProductVersion", "1.0.0-rtm21413");`
can I also assume this is the ProductVersion to use in the insert solution you provided?

This may seem obvious to you all but to me not so much at this stage.
In addition I am finding my scenario quite hard to test so I want to minimize the testing iterations as much as possible.  During Dev time it appears impossible to simulate a UWP Store app upgrade.  It just wants to uninstall the v1 and install v2 which is not the upgrade process the user will have. :-)

I thank you @bricelam in anticipation of your response.

Cheers
Chris ...

**Comment by bricelam** [comment]
> Can I also assume this is the ProductVersion to use in the insert solution you provided?

Yes, that will work. You can also use the same version number as the `Microsoft.EntityFrameworkCore` package you are using. Only the `1.0.0` part is important.

This number is just there for future-proofing. If we ever make breaking changes to how Migrations interacts with the database, we'll use this version to determine the current compatibility level of the database.
