### ISSUE TITLE
generated wrong SQL when use where TableA.TableB.Field == 'abc'

### ISSUE THREAD

**Issue by juchunwei** [dotnet/efcore#6763]
when I code:

_context.Leaves.Where(l => l.Empl.Name=="ju")

the SQL generated: 

SELECT [l].[Id], [l].[Date], [l].[DepartmentId], [l].[EmplId], [l].[Hours], [l].[LeaveType], [l.Empl].[Id], [l.Empl].[DepartmentId], [l.Empl].[FromDate], [l.Empl].[LeaveDate], [l.Empl].[Name], [l.Empl].[OperationId], [l.Empl].[Section], [l.Empl].[SkillLevel]
FROM [Leaves] AS [l]
LEFT JOIN [Empls] AS [l.Empl] ON [l].[EmplId] = [l.Empl].[Id]
ORDER BY [l].[EmplId]

why it select all the fields in table Empl? and can't find 'where'

is this a bug?

**Comment by maumar** [comment]
All fields are selected due to this issue: https://github.com/aspnet/EntityFramework/issues/6647
Where is not in the query due to issue https://github.com/aspnet/EntityFramework/issues/4588 (which has already been fixed and will be available in 1.1.0)
