### ISSUE TITLE
Delete.cshtml Scaffolding Missing ID Field

### ISSUE THREAD

**Issue by thomas-daughters** [dotnet/efcore#6764]
### Steps to reproduce

Create new MVC controller and views using VS2015 scaffold.
Build and run project.
### The issue

The _Delete.cshtml_ file generated by the scaffold is missing a reference to the ID field. Missing line:
`<input type="hidden" asp-for="ID" />`
### Further technical details

EF Core version: 1.0.1
EF Tool version: 1.0.0-preview2-update1
Operating system: Windows
Visual Studio version: VS 2015 Update 3

**Comment by rowanmiller** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/308
