### ISSUE TITLE
Different concurrency token, same model across providers

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#6765]
While working on optimistic concurrency support in Npgsql, I found myself wondering about EFCore's same-model-across-providers story. Defining a concurrency token for SqlServer typically requires something like:

``` c#
modelBuilder.Entity<MyEntity>(b => b.Property(e => e.Version).IsRowVersion());
```

PostgreSQL doesn't support rowversions (or auto-updating columns in general), but has an automatic system column called `xmin` which changes every time a row is updated. So optimistic concurrency can be configured as follows:

``` c#
modelBuilder.Entity<MyEntity>(b =>
{
    b.Property<uint>("xmin")
        .HasColumnType("xid")
        .ValueGeneratedOnAddOrUpdate()
        .IsConcurrencyToken();
});
```

One important point is that the `xmin` property isn't present at all in SqlServer, so the above model code would cause things to break there. Similarly, SqlServer's `Version` column shouldn't get created when using Npgsql (although it's less problematic if it does, as long as it's not used). EFCore already has provider-specific model operation such as `ForSqlServerToTable`, but these seem to be valid only for provider-specific annotations, where things like `IsConcurrencyToken` are present on the property itself.

I guess this is a general question that goes beyond concurrency tokens, for all cases where differences need to exist within the same model across providers.

**Comment by FransBouma** [comment]
(Currently working on EF Core support in our designer, so I ran into this particular issue as well) `ForSqlServerToTable` feels like a strange thing, it's so specific, it makes it harder to e.g. generate mapping files. Looking at it, it feels it's actually coming from the fact there's just one modelbuilder metadata store across all DbContext instances, which is of course odd: one should have 1 DbContext class per database type and thus also 1 modelbuilder metadata store per database type. 

What if for a database type A fields are mapped differently than for database type B? It's now impossible to define this. Classic mistake, with IMHO deep consequences, especially when the mapping features grow further and you e.g. want to specify type specific features per field per database type.

**Comment by rowanmiller** [comment]
We support having simple differences within the same model (column names, underlying data types, etc.) but for anything that structurally changes the model (i.e. different properties included, different keys, etc.) you need to have two different models. `OnModelCreating` supports this, as it will get re-run if you use the same content with a different provider (i.e. the provider is part of the cache key for the model). This means you  could write something like...

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    if(Database.GetDbConnection() is SqlConnection)
    {
        modelBuilder.Entity<MyEntity>()
            .Property(e => e.Version)
            .IsRowVersion();
    }
    else
    {
        modelBuilder.Entity<MyEntity>()
            .Ignore(b => b.Version);

        modelBuilder.Entity<MyEntity>()
            .Property<uint>("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();
    }
}
```

**Comment by ajcvickers** [comment]
To add to what @rowanmiller said, the Npgsql provider could also interpret having `property.IsConcurrencyToken` and `property.ValueGenerated == ValueGenerated.OnAddOrUpdate` set on a `uint` property to mean that the mapping should be to an "xid" property. This would then allow this:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    if(Database.GetDbConnection() is SqlConnection)
    {
        modelBuilder.Entity<MyEntity>()
            .Property(e => e.Version)
            .IsRowVersion();
    }
    else
    {
        modelBuilder.Entity<MyEntity>()
            .Ignore(b => b.Version);

        modelBuilder.Entity<MyEntity>()
            .Property<uint>("xmin")
            .IsRowVersion();
    }
}
```
This is equivalent to what the SQL Server type mapper does when it sees these facets set on a `byte[]` property.

**Comment by roji** [comment]
Thanks for the answers! I definitely wasn't aware EFCore supported different models based on providers, that's a pretty good answer. I do wonder how this would interact with migrations though...! It may be a good idea to add some documentation on this.

@ajcvickers that would have been great, except that the generate-on-update behavior is a very specific feature of the `xmin` system column in PostgreSQL. In other words, you can't create some arbitrary column with type `xid` and have it generate on update (like you can with byte[] on SQL Server) - you can only do this with the magical, built-in `xmin` column, which exists exactly once in each and every table.

It's not the end of the world - [I plan to add](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/19#issuecomment-253346255) an extension method that would allow users to specify things at the entity level:

```c#
modelBuilder.Entity<Chassis>().UseXminAsConcurrencyToken();
```

**Comment by FransBouma** [comment]
@rowanmiller 
> We support having simple differences within the same model (column names, underlying data types, etc.) but for anything that structurally changes the model (i.e. different properties included, different keys, etc.) you need to have two different models. OnModelCreating supports this, as it will get re-run if you use the same content with a different provider (i.e. the provider is part of the cache key for the model)

Ok, so what if I have 1 model csproj and per database a DbContext class and a class which builds the mappings using the ModelBuilder. Is it then also separated at runtime? (so say I have a model mapped to Northwind in SQL Server and PostgreSQL: I then get 3 csproj projects: 1 with the entity classes, 1 with the SQL Server specific code, namely a DbContext class and a class calling methodbuilder methods for SQL Server, and a csproj with the PostgreSQL specific code, namely a DbContext class and a class calling methodbuilder methods for PostgreSQL. 

As that's a different scenario than what you describe, namely I don't have 1 DbContext class but one for each DB supported in the app. It's important, because if the scenario I describe isn't supported but the one you describe (so 1 DbContext which controls the mappings for all databases) I have to write different template code for the code generator than if the situation I describe is supported as well. Thanks.

**Comment by roji** [comment]
@ajcvickers I just understood your comment better - your suggestion is to enable `IsRowVersion()` to have the same effect in Npgsql as in SQL Server. This has some appeal, but you would still only be able to use it on `xmin` for it to have any effect (and `xmin` cannot exist anywhere but on PostgreSQL). So you end up having per-database settings anyway...

**Comment by ajcvickers** [comment]
@roji Yes, it would still be per-datatabae model, primarily because SQL Server requires a byte array while Npgsql requires a uint. I think what you suggest is fine.

**Comment by ajcvickers** [comment]
Note, it seems that we currently don't automatically build one model per provider-see issue #6804.

**Comment by ajcvickers** [comment]
Never mind--I forgot how it works. :-) You should be getting one model per provider like previously asserted. :-)

**Comment by divega** [comment]
@FransBouma if your tool generates separate derived `DbContext` types for each provider that should be fine as well.

**Comment by FransBouma** [comment]
@divega It does that indeed. This is to be able to swap at runtime between databases. Thanks!
