### ISSUE TITLE
MigrationId and migration class name

### ISSUE THREAD

**Issue by Melander** [dotnet/efcore#6766]
Shouldn't the class name of the created migration reflect the actual MigrationId in the database?

As it is now with EF 6 the migration cs file name looks something like:
`201510280837234_SomeName.cs` and the partial class name would then be named:
`public partial class SomeName : DbMigration { ... }`
The MigrationId in the database is named: `201510280837234_SomeName.cs`

In my world partial class name should be `201510280837234_SomeName` to reflect the MigrationId in the database.

Are there any advantages to having the MigrationsId and class name different?

**Comment by rowanmiller** [comment]
A class name can't start with numeric values. When we first built migrations we put an underscore at the start, but ultimately decided that just dropping the timestamp was cleaner. You could definitely argue either way, but at this stage it's something we are unlikely to change.

**Comment by Melander** [comment]
Yes I understand the class name issue, the down side of not getting the timestamp in the class name is that you don't get the uniqueness it would have had otherwise.. i.e. teams can accidentally create migrations with the same name and will most likely not see this until it's too late.. at svn commit. But I guess that this has been discussed a lot (I must have missed it) :)

Our own quick fix has been to add a timestamp,  developer name and migration name as the add-migration 'name'.

**Comment by rowanmiller** [comment]
Closing as we discussed and decided to stay with what we have. It doesn't seem like it would be too common for two devs to create the same migration name at a similar time. We will reconsider if we get feedback from more folks that they are hitting the issue.

**Comment by Melander** [comment]
Yeah, but that's the issue.. the timestamp isn't inserted into the class name so it's only the migration file name that's unique, not the actual class name. Devs can create similar migration names any time since the class names aren't unique.
