### ISSUE TITLE
DateTimeFormatConst is private, clumsy for FromSql

### ISSUE THREAD

**Issue by Ciantic** [dotnet/efcore#6767]
If one needs to call FromSql, it would be helpful if there were a way to turn the Datetime to same kind of string as EF has done

E.g. in SQLite I had to hard code the [DateTimeFormatConst](https://github.com/aspnet/EntityFramework/blob/master/src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteSqlGenerationHelper.cs#L16)'s value `@"yyyy\-MM\-dd HH\:mm\:ss.FFFFFFF"` to my own program. Could it be exposed as a public value to help building FromSql bits that are more general?

Thanks

**Comment by rowanmiller** [comment]
Our recommendation is to use parameterized queries, rather than stitching strings together - in this case EF will take care of the correct formatting. If you want to stitch strings together, then copying the format is an ok approach.
