### ISSUE TITLE
Attach separate database

### ISSUE THREAD

**Issue by johnmurphy01** [dotnet/efcore#6770]
### Steps to reproduce

I have a requirement to be able to connect two separate SQLite databases. One database is an "offline" database and the other "online" database is one that comes from an API. I need to be able to attach the online database to the offline database.

Here is the basic flow that I have right now:
- I call `EnsureCreated()` on my offline database
- I then call `EnsureCreated()` on my online database just so that I'll have an empty skeleton for now
- Finally, I call from my offline dbContext: `this.Database.ExecuteSqlCommand("attach database 'theDatabasePath' as online")`

I get no errors at that point. However, when I then try to reference any table from the online database within a `FromSql` string, I get an error "no such table: online.myTableName"

I know the database structure of both are fine because if I manually attach the databases via command line, I am able to join tables across databases.
### The issue

I can't attach a separate database. I don't know if this is a limitation of EF7 or if I'm not calling the attach statement properly.
### Further technical details

EF Core version: Microsoft.EntityFrameworkCore.SQLite v 1.0.1
Operating system: Windows 10
Visual Studio version: VS2015

**Comment by johnmurphy01** [comment]
**Update**: I was able to, I think, get the attach to work.

I had to call `OpenConnection()` on the offline database context after `EnsureCreated()`.

Now I can successfully run a query like this: `select * from main.o_files inner join online.files on main.o_files.o__id = online.files._id`

But as soon as I try to replace the * with specific column values I get an exception. The exception says "no such column" and the exception is correct. But it's like EF altered my query.

Example: if I say `select main.o_files.o__id from main.o_files inner join online.files on main.o_files.o__id = online.files._id`, I will get an error: "SQLite Error 1: no such column: o.__created_on". o.__created_on is not a column anywhere in my database but there is o___created_on and __created_on

**Comment by rowanmiller** [comment]
Needing to open the connection is correct. In general EF will open and close the connection as required, but if you open it yourself, it will leave it open (required for attaching a database), rather than closing it after each operation.

@bricelam do you have any ideas on the `main.` getting stripped off?

**Comment by bricelam** [comment]
You can't use `ToTable()` or `[Table]` and specify the database name for the schema. Schemas are not catalogs/databases are different. Our SQLite provider ignores schemas to make working with multi-provider models easier. Support for specifying catalogs is tracked by #4019.

**Comment by rowanmiller** [comment]
Actually I just realized that you are only returning a subset of the columns. `FromSql` requires that all columns for the entity type are returned - which would be why `SELECT *` works. If that's not the issue, then could you post a full code listing that we can run to debug the issue.

**Comment by bricelam** [comment]
Yeah, I think I totally misunderstood the issue. Rowan's reply looks more to the point.

**Comment by johnmurphy01** [comment]
@rowanmiller thanks for the response. I will attempt to run my real query returning all columns and let you know.

**Comment by johnmurphy01** [comment]
Selecting all columns appears to work. 

In the scenario of `UNION ALL` between two separate databases, would it be better to return everything from a `FromSql` method using * or would it be better to use LINQ to get the appropriate data from TableA, then TableB and do the union in C#? Or is the performance difference negligible?

**Comment by rowanmiller** [comment]
@johnmurphy01 my guess is that it will be about the same... but, as with anything performance related, the details are what makes the difference, so I would try it and see.

**Comment by rowanmiller** [comment]
Closing as I think we've answered the original question, but feel free to reply if not 😄
