### ISSUE TITLE
Getting / creating ApplicationDbContext in AccountController ASP.NET Core

### ISSUE THREAD

**Issue by xavirm** [dotnet/efcore#6771]
Hi, I'm trying to get (or create) the ApplicationDbContext in the AccountController of my ASP.NET Core web app.

I've seen that in other controllers the ApplicationDbContext is passed in the constructor, but it's not the same in the Account Controller.

I need it in order to reference other entities at the Controller in order to register (Register method) a user with several custom fields.

What's the best way of getting (or creating) it ? 

Thanks a lot.
Regards,

Windows 10
Visual Studio 2015
ASP.NET Core Web App with Individual User Account

**Comment by rowanmiller** [comment]
Just add it to the constructor and it will get passed in for you.

**Comment by xavirm** [comment]
Thank you very much, Rowan!
Just for educational purposes, how is this done ?
Regards,

**Comment by rowanmiller** [comment]
The context is registered as a service in Startup.cs, then dependency injection takes care of passing in the services that your controller asks for (i.e. it's constructor parameters). More info on that here https://docs.asp.net/en/latest/fundamentals/dependency-injection.html.

**Comment by xavirm** [comment]
Thank you very much, Rowan.
