### ISSUE TITLE
Confusion re One-to-One vs One-to-Zero or One in Docs

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#6776]
I've got a pair of classes set up for a simple one-to-one relationship. The principal has a navigation property to the dependent. The dependent has a navigation property and FK property for the principal.

 public class Principal
  {
    public int Id { get; set; }
    public string Name { get; set; }
    public Dependent Dependent { get; set; }
  }
 public class Dependent
  {
    public int Id { get; set; }
    public string SomeText { get; set; }
    public Principal Principal { get; set; }
    public int PrincipalId { get; set; }
  }

No special configs for this in DbContext ModelBuilder

Using SqlServer, migrations correctly specifies the non-nullable FK column for the table which the dependent maps to:
 PrincipalId = table.Column<int>(nullable: false)
### The issue

Testing with the InMemory provider, I create a new Principal and do NOT specify a dependent. Dependent is therefore null.

SaveChanges happily emulates an insert to the InMemory store and returns with a new value, 1, in the Principal.Id property.

```
 public void CannotSavePrincipalWithNullDependent() {
    var principal=new Principal();
      using (var context=new MyContext())
      {
       context.Principals.Add(principal);
        context.SaveChanges();
      }
      Assert.AreNotEqual(0,principal.Id);
    }
```

The test passes. I would have expected it to throw telling me that the Dependent property can't be null.

Runnng the test against sql server database, it does throw as expected:

Result StackTrace:  
at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Test.MyContext.ctor(DbContextOptions`1 options) in 

Result Message: 
Test method Tests.UnitTest1.CannotSavePrincipalWithNullDependent threw exception: 
System.ArgumentNullException: Value cannot be null.
Parameter name: options
### Further technical details

EF Core version: 1.0.1
Operating system: 
Visual Studio version: (e.g. VS 2015 latest everything, windows 10 latest everything

(I searched a variety of ways in the issues but found nothing relevant. Hope it's not redundant or that I'm not overlooking something obvious. )

**Comment by ajcvickers** [comment]
@julielerman SQL Server stack trace shows null ref is in calling DbContext constructor. Nothing to do with the principal. If this is fixed, then SQL Server should also not throw an exception. There is never anything that prevents a principal from being saved without any dependent. The constraint only says that a dependent, if one exists, must have a principal.

**Comment by julielerman** [comment]
Yep ... as expected...I was missing something. My last minute "oh let's see if the database throws too!" before I posted the issue was not thought through correctly.  But that was not really my problem, just a side-effect.

So back to the original problem then: there's nothing even in my migration that says principal MUST have a dependent. So it's really just creating a 1:0..1, not a true 1:1.

I should at least then make the Dependent a required property even if I don't do the full relationship mapping in the context, right? 

If that's the case then are the docs wrong in suggesting that the one to one should work just with the blog/post setup and you only need to use the mappings to correct a wrongly inferred Principal/Dependent relationship or if you have an oddly named FK or something?

**Comment by ajcvickers** [comment]
In a sense, yes. But that has always been the case. If you do this in EF6:
```C#
modelBuilder.Entity<Principal>()
    .HasRequired(e => e.Dependent)
    .WithRequiredPrincipal(e => e.Principal);
```
with all the same code you posted above, you still won't get an exception when saving a principal without any dependent. So even though it appeared that you could do 1:1, 1:0..1, 0..1:0..1 stuff in the old stack, it was never enforced. In EF Core we got rid of all that stuff since it was confusing and instead just made it so that the FK could either be required or not. This maps directly to nullable (optional) or non-nullable (required). So the API lets you do what the FK constraint lets you do and there is no ambiguity.

When I talk about a 1:1 relationship these days it is just short hand for (up to) one entity on each end, rather than (up to) one entity on one end and any number of entities on the other end. I haven't looked closely at the docs, but I suspect that is what they are trying to convey.

**Comment by julielerman** [comment]
ok thanks. Yes we always have had to do that. I know I spent a lot of time trying to make sure whoever was trying to learn from me understood the difference between the appearance and what EF would truly infer. Yes it's gotten so much better/smarter thanks to the unique FKs and the convention's ability to infer more info. My expectation was driven by the docs and no, I don't presume that one to one is the same as one to zero or one.  So I was confused by the fact that it said "one to one" and I was getting one to many. 
I *do* like the thinking though that the enforced dependent is the anomoly and just to thinkn of one to one covering both scenarios with the nullability being just an extra bit of info.
