### ISSUE TITLE
ThenInclude with InMemory DbContext throws exception

### ISSUE THREAD

**Issue by dlacaille-baytech** [dotnet/efcore#6777]
Hi,
I created a very simple query (see below) that includes a Include and a ThenInclude. At first everything was working correctly but then it stopped working throwing a strange exception (below). Is it caused because I use an InMemory context? 

**Query**
var dbUser = await Context.CompanyUsers
                .Include(u => u.Roles)
                .ThenInclude(r => r.Role)
                .ThenInclude(r => r.Permissions)
                .FirstOrDefaultAsync(u => u.Id == id);

**Exception**
Test Name:  Appplication.Tests.Commands.AdminInviteUserToCompanyTests.Create_Successful_Invitation
Test FullName:  Appplication.Tests.Commands.AdminInviteUserToCompanyTests.Create_Successful_Invitation
Test Source:    \Commands\AdminInviteUserToCompanyTests.cs : line 62
Test Outcome:   Failed
Test Duration:  0:00:07.216

Result StackTrace:  
at CompanyUserRepository.<GetByIdAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at CompanyUserRepository.GetByIdAsync(Guid id)
   at Commands.AdminInviteUserToCompanyHandler.<Execute>d__8.MoveNext() in C:\AdminInviteUserToCompanyHandler.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Prime.Tenant.Appplication.Tests.Commands.AdminInviteUserToCompanyTests.<Create_Successful_Invitation>d__6.MoveNext() in C:\AdminInviteUserToCompanyTests.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
Result Message: Method not found: 'Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,!!2> Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ThenInclude(Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,System.Collections.Generic.ICollection`1<!!1>>, System.Linq.Expressions.Expression`1<System.Func`2<!!1,!!2>>)'.

**Comment by maumar** [comment]
@dlacaille-baytech could you share your model? (entities and dbcontext, especially contents of  OnModelCreating method)

**Comment by dlacaille-baytech** [comment]
Hi @maumar,
See the requested info below. Also, just to clarify, it work fine using a SQL context. The problem occurs when using the InMemory db.

Hope you can help.

**DbContext**
There's nothing in the context but the OnModelCreating below.

  protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Model.RolePermisssion>()
                .HasKey(p => new { p.RoleId, p.PermissionId });

            modelBuilder.Entity<Model.CompanyRole>()
                .HasKey(p => new { p.RoleId, p.CompanyId });

            modelBuilder.Entity<Model.CompanyUserRole>()
                .HasKey(p => new { p.CompanyUserId, p.RoleId });

            modelBuilder.Entity<Model.Invitee>()
                .Property(p => p.ConcurrencyStamp)
                .ValueGeneratedOnAddOrUpdate()
                .IsConcurrencyToken();

            var inviteeRole = modelBuilder.Entity<Model.InviteeRole>();
            inviteeRole.HasKey(p => new { p.RoleId, p.InviteeId });
            inviteeRole.HasOne(p => p.Invitee)
                .WithMany(i => i.Roles)
                .OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Cascade);
        }

**Model**

  public class CompanyUser
    {
        public Guid Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public Guid UserId { get; set; }
        public User User { get; set; }
        public Guid CompanyId { get; set; }
        public Company Company { get; set; }
        public Guid? TeamId { get; set; }
        public Team Team { get; set; }
        public List<CompanyUserRole> Roles { get; set; }
}

  public class Team
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid CompanyId { get; set; }
        public Company Company { get; set; }
        public List<CompanyUser> Members { get; set; }
    }

public class Company
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public List<CompanyUser> Users { get; set; }
        public List<Team> Teams { get; set; }
    }

 public class CompanyUserRole
    {
        public Guid CompanyUserId { get; set; }
        public CompanyUser User { get; set; }
        public Guid RoleId { get; set; }
        public Role Role { get; set; }
    }

  public class Role
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public List<CompanyRole> Companies { get; set; }
    }

**Comment by maumar** [comment]
Additionally, can you share listing for Permission(?) and RolePermission classes? Also, just to be sure - Role entity should have ```List<Permission> Permissions {get; set; }```` property, correct?

**Comment by dlacaille-baytech** [comment]
Hi @maumar,
I've included the three other entities requested. To answer your question, yes, Role contains a list of permissions (see below). I omitted it because I wasn't finding it relevant to the question.

Thanks

 public class RolePermisssion
    {
        public Guid RoleId { get; set; }
        public Role Role { get; set; }
        public Guid PermissionId { get; set; }
        public Permission Permisssion { get; set; }
    }

 public class Permission
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public List<RolePermisssion> Roles { get; set; }
    }
}

 public class Role
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public List<RolePermisssion> Permissions { get; set; }
    }

**Comment by maumar** [comment]
@dlacaille-baytech thanks for the extra information. RolePermission was actually used in the query that is causing and issue, so I wanted to make sure I get the configuration right. However, even with all the info I was still unable to reproduce the bug on my end - tried it on 1.0.1, 1.1.0-preview, as well as our current bits. 

You mentioned that it used to work but then stopped. Was there anything specific that caused the change of behavior? (model change, different data, etc). Alternatively, could you provide a full standalone project that reproduces the issue?

Just as a reference, here is a full listing of the code i ended up trying:

```
    class Program
    {
        static void Main(string[] args)
        {
            Guid id;
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var cu1 = new CompanyUser { Title = "CU1" };
                var cu2 = new CompanyUser { Title = "CU2" };

                var r1 = new Role { Name = "R11" };
                var r2 = new Role { Name = "R12" };
                var r3 = new Role { Name = "R21" };
                var r4 = new Role { Name = "R22" };

                var cur1 = new CompanyUserRole { User = cu1, Role = r1 };
                var cur2 = new CompanyUserRole { User = cu1, Role = r2 };
                var cur3 = new CompanyUserRole { User = cu1, Role = r3 };
                var cur4 = new CompanyUserRole { User = cu2, Role = r2 };
                var cur5 = new CompanyUserRole { User = cu2, Role = r3 };
                var cur6 = new CompanyUserRole { User = cu2, Role = r4 };

                var p1 = new Permission { Name = "P1" };
                var p2 = new Permission { Name = "P1" };

                var rp1 = new RolePermisssion { Role = r1, Permisssion = p1 };
                var rp2 = new RolePermisssion { Role = r2, Permisssion = p1 };
                var rp3 = new RolePermisssion { Role = r3, Permisssion = p1 };
                var rp4 = new RolePermisssion { Role = r4, Permisssion = p1 };
                var rp5 = new RolePermisssion { Role = r1, Permisssion = p2 };
                var rp6 = new RolePermisssion { Role = r2, Permisssion = p2 };
                var rp7 = new RolePermisssion { Role = r3, Permisssion = p2 };
                var rp8 = new RolePermisssion { Role = r4, Permisssion = p2 };

                ctx.CompanyUsers.AddRange(cu1, cu2);
                ctx.Roles.AddRange(r1, r2, r3, r4);
                ctx.Permissions.AddRange(p1, p2);
                ctx.UserRoles.AddRange(cur1, cur2, cur3, cur4, cur5, cur6);
                ctx.RolePermissions.AddRange(rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8);
                ctx.SaveChanges();

                id = cu2.Id;
            }

            using (var ctx = new MyContext())
            {
                var dbUser = ctx.CompanyUsers
                .Include(u => u.Roles)
                .ThenInclude(r => r.Role)
                .ThenInclude(r => r.Permissions)
                .FirstOrDefaultAsync(u => u.Id == id);

                dbUser.Wait();

                var result = dbUser.Result;

                Console.WriteLine(result);
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<CompanyUserRole> UserRoles { get; set; }
        public DbSet<RolePermisssion> RolePermissions { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("Repro6777");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RolePermisssion>()
                .HasKey(p => new { p.RoleId, p.PermissionId });

            modelBuilder.Entity<CompanyRole>()
                .HasKey(p => new { p.RoleId, p.CompanyId });

            modelBuilder.Entity<CompanyUserRole>()
                .HasKey(p => new { p.CompanyUserId, p.RoleId });
        }
    }

    public class CompanyUser
    {
        public Guid Id { get; set; }
        public string Title { get; set; }

        public Guid CompanyId { get; set; }
        public Company Company { get; set; }
        public Guid? TeamId { get; set; }
        public Team Team { get; set; }
        public List<CompanyUserRole> Roles { get; set; }
    }

    public class Team
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid CompanyId { get; set; }
        public Company Company { get; set; }
        public List<CompanyUser> Members { get; set; }
    }

    public class Company
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public List<CompanyUser> Users { get; set; }
        public List<Team> Teams { get; set; }
    }

    public class CompanyUserRole
    {
        public Guid CompanyUserId { get; set; }
        public CompanyUser User { get; set; }
        public Guid RoleId { get; set; }
        public Role Role { get; set; }
    }

    public class CompanyRole
    {
        public Guid RoleId { get; set; }
        public Guid CompanyId { get; set; }

        public Role Role { get; set; }
        public Company Company { get; set; }
    }

    public class RolePermisssion
    {
        public Guid RoleId { get; set; }
        public Role Role { get; set; }
        public Guid PermissionId { get; set; }
        public Permission Permisssion { get; set; }
    }

    public class Permission
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public List<RolePermisssion> Roles { get; set; }
    }

    public class Role
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public List<RolePermisssion> Permissions { get; set; }
    }
```

**Comment by dlacaille-baytech** [comment]
Ok then. Thanks for the support.
