### ISSUE TITLE
Foreign Key relationship not populated when using inheritance

### ISSUE THREAD

**Issue by patrickhitch** [dotnet/efcore#6789]
### Steps to reproduce

See attached solution. Run the console application, the code illustrates the problem.
### The issue

When you run the console application, the second commit results in exception because EF is not populating the object.

If you are seeing an exception, include the full exceptions details (message and stack trace).

> Exception message:
> {Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Series_Activities_ActivityId". The conflict occurred in database "EFTest", table "dbo.Activities", column 'Id'.
> The statement has been terminated.
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
>    at EFTest.Program.Main(String[] args) in C:\Users\Patrick\Source\Repos\Church\EFTest\src\EFTest\Program.cs:line 39}
### Further technical details

 "dependencies": {
    "Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.EntityFrameworkCore.Relational.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },
Operating system: Windows 10 Pro Version 1607, build 14393.321
Visual Studio version: (e.g. VS 2013 or n/a) VS 2015, Update 3

Other details about my project setup:
[EFTest.zip](https://github.com/aspnet/EntityFramework/files/531357/EFTest.zip)

**Comment by rowanmiller** [comment]
This is working as expected. `Activity.Series` and `ActivitySeries.Activity` have been configured as navigation properties for two separate relationships (rather than inverse navigation properties of the same relationship - which is what would happen by convention):

```c#
builder.Entity<Activity>(e =>
            {
                e.HasOne(p => p.Series)
                    .WithOne()
                    .HasForeignKey<Activity>(p => p.SeriesId)
                    .IsRequired();
            });

            builder.Entity<ActivitySeries>(e =>
            {
                e.HasOne(p => p.Activity)
                    .WithOne()
                    .HasForeignKey<ActivitySeries>(p => p.ActivityId)
                    .IsRequired();
            });
```

Because the relationships are both required, the following code fails because the `ActivitySeries` object does not have an `Activity` assigned to its `Activity` property. It attempts to just insert the value currently assigned to the foreign key property (which is zero - the default for int).

```c#
var series = new ActivitySeries
{
    Name = "Test"
};

var activity = new Activity
{
    Series = series
};

using (var dbc = new MyContext())
{
    dbc.Activities.Add(activity);
    dbc.SaveChanges();
}
```

My guess is that you actually intended this to be inverse navigations of the same relationship? If so, you would configure that like this (note the non-empty call to `WithOne`):

```c#
builder.Entity<Activity>(e =>
            {
                e.HasOne(p => p.Series)
                    .WithOne(s => s.Activity)
                    .HasForeignKey<Activity>(p => p.SeriesId)
                    .IsRequired();
            });
```

**Comment by patrickhitch** [comment]
@rowanmiller, you are correct. The activity has one mandatory series and each derived series has a reference back to the entity for which it was attached; in this case activity. I updated my entity builder code as you recommended. It still doesn't populate the keys and I still get the same exception.

**Comment by rowanmiller** [comment]
@patrickhitch in your original code you had two lines of configuration that worked with these navigations, did you remove both of these and replace it with the one block that configures the relationship? In the original code you also had two foreign key properties, `Activity.SeriesId` and `ActivitySeries.ActivityId`, you would need to pick one of these as you can't have a foreign key on both ends of the relationship.

Here is some code that shows it working

```c#
namespace EFTest
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata;
    using System.Linq;

    public class Program
    {
        public static void Main(string[] args)
        {
            var series = new ActivitySeries
            {
                Name = "Test"
            };

            var activity = new Activity
            {
                Series = series
            };

            using (var dbc = new MyContext())
            {
                dbc.Database.EnsureDeleted();
                dbc.Database.EnsureCreated();

                dbc.Activities.Add(activity);
                dbc.SaveChanges();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Activity> Activities { get; set; }
        public DbSet<ActivitySeries> ActivitySeries { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Activity>(e =>
            {
                e.HasOne(p => p.Series)
                    .WithOne(s => s.Activity)
                    .HasForeignKey<Activity>(p => p.SeriesId)
                    .IsRequired();
            });

            builder.Entity<Series>(e =>
            {
                e.HasKey(p => p.Id);
                e.HasDiscriminator<string>("series_type")
                    .HasValue<Series>("series_base")
                    .HasValue<ActivitySeries>("series_activity");

            });

            foreach (var relationship in builder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer((@"Server=(localdb)\mssqllocaldb;Database=EFTest;Trusted_Connection=True;"));
        }
    }

    public class Series
    {
        public int Id { get; set; }

        public string Name { get; set; }

    }

    public class ActivitySeries : Series
    {
        public virtual Activity Activity { get; set; }
    }

    public class Activity
    {
        public int Id { get; set; }

        public int SeriesId { get; set; }
        public virtual ActivitySeries Series { get; set; }
    }
}
```

**Comment by patrickhitch** [comment]
@rowanmiller - Thank you very much. This is exactly what I wanted to do. Very subtle.
