### ISSUE TITLE
What's the best way to get the POCO model mapped table name?

### ISSUE THREAD

**Issue by xyting** [dotnet/efcore#6793]
Dear all,

What's the best way to get the POCO model mapped table name from metadata if the POCO model had been configured use Fluent API ToTable("xxx")?

**Comment by rowanmiller** [comment]
```c#
var table = context.Model.FindEntityType(typeof(Blog)).Relational().TableName;
```

**Comment by xyting** [comment]
@rowanmiller 

thanks
