### ISSUE TITLE
Do we really need IAlterMigrationOperation

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#6796]
Question came from API review.

**Comment by bricelam** [comment]
There is a polymorphic usage in [AlterOperationBuilder](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational/Migrations/Operations/Builders/AlterOperationBuilder.cs) to implement the `OldAnnotation` extension method.
