### ISSUE TITLE
Query: Better handling of Star Projection

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#6801]
While fixing issue #6657 in #6784 , we introduced a new property on `SelectExpression` to keep track of table to be used when doing star projection. We already have property to indicate that it is a star projection `IsProjectStar`. As an alternative to above system, we can add an AliasExpression or ColumnExpression which has name `*` and use it to denote, star projection.
Major benefit of this would be more consistent select expression as at present we set `IsProjectStar` when we need it but we don't reset it if something changes. With this change we would remove it from projections when it is not needed. Also remove special case properties from SelectExpression.

**Comment by popcatalin81** [comment]
> As an alternative to above system, we can add an AliasExpression or ColumnExpression which has name * and use it to denote, star projection.

Please don't forget about multi start queries: `SELECT A.*, C.* FROM A .. JOIN B ... JOIN C`, in which case column name * seems insufficient?

**Comment by smitpatel** [comment]
This approach does not work quite well.
Main issue is, we cannot have Star projection and normal projection in same Select since we cannot exactly say offset of normal projections in returned columns. Therefore if we add something in projection we need to remove the star projection. At many places we process part of query model and add stuff into projection but we need to remove it later if we have to do client eval. Having a logic that, adding something into projection can affect (remove) other things in projection is more likely to cause bugs. Also it removes `IsProjectStar` so to check star projection it requires doing filter on projection which is not perf friendly.

Also tried approach that instead of having 2 public properties `IsProjectStar` and `ProjectStarAlias`, if we can combine them into one. But we need to store alias without knowing if star projection is required or not. Therefore we need at least some public method even if we store it inside a field. Also our `SelectExpression` is not coupled properly with querysource (which is needed to create column expression). For queries like include, we send multiple queries to database even though there is only one querysource, which makes things undefined.

So current implementation looks really alright instead of bringing in complexity and potential for bugs in future.

cc: @anpete

**Comment by smitpatel** [comment]
> Please don't forget about multi start queries:  SELECT A.*, C.* FROM A .. JOIN B ... JOIN C , in which case column name * seems insufficient?

Multi star queries are interesting case. At present there are no queries generated by EF which are multi star. Current implementation of `SelectExpression` does not allow multi star queries. But when it is the case when we need multiple star at top level, which means we are materializing different entities, in such cases we explicitly write all projections (because database can have extra columns which are not mapped in EF). When it is inside subquery then in the case where we require columns from more than one tables then we insert them into the projection for subquery (which removes the star projection). So either way, it should not cause issue.
