### ISSUE TITLE
Save LineString in DbGeometry from MySql Error

### ISSUE THREAD

**Issue by pauloanalista** [dotnet/efcore#6816]
### Steps to reproduce

` using(AppDataContext ctx = new AppDataContext())
            {
                var customer = new Customer("Roberto", 35);
                customer.AddPhone(new Phone());

```
            ctx.Customer.ToList();

            Contato ponto = new Contato()
            {
                Id = 2,
                Email = "paulo.analista@outlook.com",
                Nome = "Paulo",
                Location = DbGeometry.FromText("POINT(10 10)")
            };

            ctx.Contato.Add(ponto);
            //Success
            ctx.SaveChanges();

            Contato linha = new Contato()
            {
                Id = 2,
                Email = "paulo.analista@outlook.com",
                Nome = "Paulo",
                Location = DbGeometry.LineFromText("LINESTRING (-43.397960 -22.741817, -43.396684 -22.744834)", 4326)
            };

            ctx.Contato.Add(linha);
            //Error
            ctx.SaveChanges();


        }`
```
### The issue

When you save an entity that owns a property DbGeometry the entity framework error.

When saving a POINT works perfectly

When saving a LineString or Polygon an error occurs.

```
Exception message:
Stack trace:
```

System.Data.Entity.Infrastructure.DbUpdateException was unhandled
  HResult=-2146233087
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=EntityFramework
  StackTrace:
       em System.Data.Entity.Internal.InternalContext.SaveChanges()
       em System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
       em System.Data.Entity.DbContext.SaveChanges()
       em ConsoleApplication.Program.Main(String[] args) na C:\Users\paulo\Desktop\EFWithMySql\EFWithMySql\ConsoleApplication\Program.cs:linha 44
       em System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       em System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       em Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       em System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233087
       Message=An error occurred while updating the entries. See the inner exception for details.
       Source=EntityFramework
       StackTrace:
            em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
            em System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
            em System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
            em System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
            em System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
            em System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
            em System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
            em System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
            em System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
            em System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
            em System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
            em System.Data.Entity.Internal.InternalContext.SaveChanges()
       InnerException: 
            HResult=-2146232005
            Message=An error occurred while preparing the command definition. See the inner exception for details.
            Source=EntityFramework
            StackTrace:
                 em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.CreateCommand(DbModificationCommandTree commandTree)
                 em System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.CreateCommand(Dictionary`2 identifierValues)
                 em System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
                 em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
            InnerException: 
                 HResult=-2146233080
                 Message=O índice estava fora dos limites da matriz.
                 Source=MySql.Data.Entity.EF6
                 StackTrace:
                      em MySql.Data.Entity.Metadata.NormalizeValue(TypeUsage type, Object value)
                      em MySql.Data.Entity.SqlGenerator.Visit(DbConstantExpression expression)
                      em System.Data.Entity.Core.Common.CommandTrees.DbConstantExpression.Accept[TResultType](DbExpressionVisitor`1 visitor)
                      em MySql.Data.Entity.InsertGenerator.GenerateSQL(DbCommandTree tree)
                      em MySql.Data.MySqlClient.MySqlProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree)
                      em System.Data.Entity.Core.Common.DbProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
                      em System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
                      em System.Data.Entity.Core.Common.DbProviderServices.CreateCommand(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
                      em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.CreateCommand(DbModificationCommandTree commandTree)
                 InnerException: 
### Further technical details

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <connectionStrings>
    <add name="AppConnectionStr" connectionString="Server=localhost; Database=db_entity; Port=3306; Uid=root; Pwd=1234;" providerName="MySql.Data.MySqlClient"/>

  </connectionStrings>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d"></provider></providers>
  </entityFramework>

<system.data>
    <DbProviderFactories>
      <remove invariant="MySql.Data.MySqlClient" />
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </DbProviderFactories>
  </system.data></configuration>

![x](https://cloud.githubusercontent.com/assets/6010161/19515967/84f3f40a-95d8-11e6-8857-475b5330eb37.PNG)
![capturar](https://cloud.githubusercontent.com/assets/6010161/19515978/95c74aac-95d8-11e6-8bdd-44b6e16f48ea.PNG)

**Comment by rowanmiller** [comment]
Closing as this is EF6 and a duplicate issue has already been opened on that repo.

**Comment by pauloanalista** [comment]
@rowanmiller This feature has not yet been developed?

**Comment by rowanmiller** [comment]
Correct, spatial support is not implemented. And the implementation will be significantly different so it is unlikely this specific bug would apply to EF Core.
