### ISSUE TITLE
Updating from 1.0.0-rc2 to 1.0.1 cause IDENTITY INSERT to fail

### ISSUE THREAD

**Issue by ole1986** [dotnet/efcore#6817]
Since I updated the the EntityFramework Core  (in projects.json) from 1.0.0-rc2 to 1.0.1 I cannot insert any new Entity using the IDENTITY INSERT.
### Steps to reproduce

The model is currently set the following:

```
public class Region
{
    [Key]
    // with or without "DatabaseGenerated" does not matter here
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    // [....]
}
```

This is how I am trying to insert a new record

```
// get the guid for the current user and store it into the current model
if (model.ID == 0)
    // once model is attached, the ID changed to `-2147482647`
    ctx.Attach(model).State = EntityState.Added;
else
    ctx.Attach(model).State = EntityState.Modified;
// save changes
ctx.SaveChanges();
```
### The issue

```
Exception message:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert explicit value for identity column in table 'Region' when IDENTITY_INSERT is set to OFF.
```
### Further technical details

SQL Statement below:
**I am actually missing the `SET INDENTITY INSERT Rgion ON`**

```
exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Region] ([ID], [Name])
VALUES (@p0, @p1);
',N'@p0 int,@p1 nvarchar(4000)',@p0=-2147482647,@p1=N'adfdsf'
```
### Table properties (SQL Studio)

![region-identity_issue](https://cloud.githubusercontent.com/assets/4850116/19516155/f9148b20-95fa-11e6-8ff7-9924df952708.PNG)

EF Core version: 1.0.1
Operating system:  Windows 10
Visual Studio version:  VS 2015

**Comment by ole1986** [comment]
I found out how to workaround this issue, pretty simple:
Instead of using `ctx.Attach` for new items (which was working before) I am using ctx.Add instead.

```
// get the guid for the current user and store it into the current model
if (model.ID == 0)
{
    ctx.Add(model);
} else
    ctx.Attach(model).State = EntityState.Modified;
```

Alternative which is obviously also working, to Attach and then reset the ID to 0 (zero):

```
ctx.Attach(model);
model.ID = 0;
```

**Comment by rowanmiller** [comment]
This is by-design. Attach is designed for attaching existing entities and Add is for adding new ones. Calling Attach will always result in the root node being in the unchanged state. This was an intentional change between RC2 and RTM. We recently clarified this in the API documentation https://github.com/aspnet/EntityFramework/commit/4beebdfda9af140ff077272376bd1764b2e78411.
