### ISSUE TITLE
System.BadImageFormatException (An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B))

### ISSUE THREAD

**Issue by llmsjraj** [dotnet/efcore#6825]
![image](https://cloud.githubusercontent.com/assets/22942645/19573275/4610bd6c-9723-11e6-9993-25663515f7a1.png)

Please see attached Exception details.
I have already did.
1. Already Exist "Microsoft.Data.Sqlite.dll" , "System.Data.SQLite.dll", "System.Data.SQLite.EF6.dll", "System.Data.SQLite.Linq.dll" in "Bin" folder.
1. Already Exist "SQLite.Interop.dll" and "sqlite3.dll" in "x64" and "x86" folder.
2. I am implementing Sqlite with EF in "WCF Application".
3. Look the attached 
   [web_config.txt](https://github.com/aspnet/EntityFramework/files/542638/web_config.txt)

web.config

Please help out. I am stuck in it from 2 days.

**Comment by ErikEJ** [comment]
This is the EF Core issue tracker, pls use the EF  6 one here: https://github.com/aspnet/EntityFramework6/issues 

Have you tried setting the platform target to x86?

**Comment by llmsjraj** [comment]
Its amazing!!! I have tried so many times but get same exception. But i have tried now. Its get SUCCESS.
👍
