### ISSUE TITLE
dotnet ef migratons: --data-dir and --project-dir don't work

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#6827]
> dotnet ef migrations add "Initial" --project-dir "C:\Users\ansvyryd\Documents\Visual Studio 2015\Projects\WebApplication1\src\ClassLibrary1"

Produces

> Unexpected value 'C:\Users\ansvyryd\Documents\Visual Studio 2015\Projects\WebApplication1\src\ClassLibrary1' for option 'project-dir'

Same for --data-dir

**Comment by smitpatel** [comment]
Same for `--assembly` & `--startup-assembly`
Issue is EF is running following command
```
Running C:\Program Files\dotnet\dotnet.exe exec --runtimeconfig D:\EFSampleApp\src\EFSampleApp\bin\Debug\netcoreapp1.0\EFSampleApp.runtimeconfig.json --depsfile D:\EFSampleApp\src\EFSampleApp\bin\Debug\netcoreapp1.0\EFSampleApp.deps.json --additionalprobingpath C:\Users\smpatel\.nuget\packages C:\Users\smpatel\.nuget\packages\Microsoft.EntityFrameworkCore.Tools.DotNet\1.0.0-preview4-22568\lib\netcoreapp1.0\..\..\tools\netcoreapp1.0\ef.dll --assembly D:\EFSampleApp\src\EFSampleApp\bin\Debug\netcoreapp1.0\EFSampleApp.dll --startup-assembly D:\EFSampleApp\src\EFSampleApp\bin\Debug\netcoreapp1.0\EFSampleApp.dll --data-dir D:\EFSampleApp\src\EFSampleApp\bin\Debug\netcoreapp1.0\ --project-dir D:\EFSampleApp\src\EFSampleApp --content-root-path D:\EFSampleApp\src\EFSampleApp --root-namespace EFSampleApp --verbose --assembly EFSampleApp
```
`--assembly` is specified twice. The user defined value should replace the default value.

**Comment by bricelam** [comment]
It is currently by design that these options don't work. Just like with the NuGet commands, the following parameters come from the project system and can't be overridden (except by calling `ef.exe` directly).

- `--assembly`
- `--config`
- `--content-root-path`
- `--data-dir`
- `--project-dir`
- `--root-namespace`
- `--startup-assembly`

**Comment by bricelam** [comment]
Marking for re-triage to discuss the design.
