### ISSUE TITLE
Understanding the Development Flow W/O the Designer in EF Core

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#6833]
My current development flow allows me to make a DB change in **one** place, SSDT, and have it propagate to the database (via SQL compare or publish) and my edmx diagram (via update diagram from the DB).

It would seem using the code first model I would have to make the change in **two** places: SSDT and my code first classes.  Is that correct?

**Comment by rowanmiller** [comment]
You would typically use the reverse engineer tools to create the model from the database, rather than hand coding the changes. In EF Core at the moment there isn't a good "update with just the incremental changes", so you re-generate the model to pull in the changes.

**Comment by rowanmiller** [comment]
BTW here is the issue for better "update model from database" support

**Comment by smitpatel** [comment]
@rowanmiller - Issue?

**Comment by rowanmiller** [comment]
Edited comment to include it... thanks 😄
