### ISSUE TITLE
Unexpected SQL generated by Select_Where_Navigation_Deep test

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#6836]
### Steps to reproduce

Run this test: Select_Where_Navigation_Deep
### The issue

This unexpected SQL is generated:

``` C#
            Assert.Equal(@"SELECT [od].[OrderID], [od].[ProductID], [od].[Discount], [od].[Quantity], [od].[UnitPrice], [od.Order.Customer].[CustomerID], [od.Order.Customer].[Address], [od.Order.Customer].[City], [od.Order.Customer].[CompanyName], [od.Order.Customer].[ContactName], [od.Order.Customer].[ContactTitle], [od.Order.Customer].[Country], [od.Order.Customer].[Fax], [od.Order.Customer].[Phone], [od.Order.Customer].[PostalCode], [od.Order.Customer].[Region]
FROM [Order Details] AS [od]
INNER JOIN [Orders] AS [od.Order] ON [od].[OrderID] = [od.Order].[OrderID]
LEFT JOIN [Customers] AS [od.Order.Customer] ON [od.Order].[CustomerID] = [od.Order.Customer].[CustomerID]
ORDER BY [od].[OrderID], [od].[ProductID], [od.Order].[CustomerID]",
            Sql);
```

(This SQL is missing a where clause, and has no TOP statement)
### Further technical details

EF Core version: 1.1.0-alpha1-22167
Operating system: Win 10
Visual Studio version: VS 2015 Update 3

Other details about my project setup:

**Comment by maumar** [comment]
@ErikEJ I ran build on both dev (1.1.0-preview bits) and our current WIP (1.2.0) and in both cases test passes. Are you still seeing this issue? If so, is it SQL server or a different provider?

**Comment by ErikEJ** [comment]
It is the SQLCE provider, but possibly my expected results are out of sync. Will check and let you know (might be a couple of days)

**Comment by ErikEJ** [comment]
Sorry for waitsing your time 😞

**Comment by maumar** [comment]
no worries, not much time was wasted - I had to run those builds anyway :)
