### ISSUE TITLE
Migrations fail for net452 projects

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#6837]
[FullWebApplication.zip](https://github.com/aspnet/EntityFramework/files/545099/FullWebApplication.zip)
On Windows 10 x86 .xproj or .csproj:

```
Add-Migration Initial
```

> The specified executable is not a valid application for this OS platform.

On Windows 10 x64 .xproj:

> An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by bricelam** [comment]
For the x86 one, it looks like we always assume the platform is win-x64.

**Comment by bricelam** [comment]
This should already be fixed in the VS "15" tools. We get the runtime from the project.

**Comment by rowanmiller** [comment]
Given that xproj is not going to RTM we aren't going to spend time on this. The workaround is to use `dotnet ef`

**Comment by andresmoschini** [comment]
> Given that xproj is not going to RTM we aren't going to spend time on this. The workaround is to use `dotnet ef`

@rowanmiller can I use `dotnet ef` when the context is defined in an old csproj library? how?

**Comment by bricelam** [comment]
For plain-old-csproj (e.g. .NET Framework Class Library, WinForms, WPF, Console, etc.) the PMC commands should work. This issue was specifically about targeting net452 on a .NET Core Class Library or ASP.NET Core project.
