### ISSUE TITLE
Restrict same value in table

### ISSUE THREAD

**Issue by SCORPIO12** [dotnet/efcore#6848]
I try to insert dropdown selected value in table and I am done with this

``` C#
protected void Button1_Click(object sender, EventArgs e)
{
  string Vechile_ID = "";
  try
  {
    Data n = new Data();
    tbl_Vechile v = new tbl_Vechile();
    v.Vechile_ID = Vechile_ID;
    {
      v.Vechile_ID = DropDownList1.SelectedValue;
    }

    n.tbl_Vechile.Add(v).ToString();
    n.SaveChanges();
  }
  catch
  {
  }

  Response.Redirect("Mai.aspx");
}
```

Now the problem is suppose dropdown value are

ERE23
DFG4
ER4

When I select ER4 value then ER4 is inserted in table but when I select again and click on button then value again inserted in table where as I want to insert value only once not wanted to insert same value again and again

How I do this

**Comment by johanskoldekrans** [comment]
You can use .Any() to check for values in the table like an Exists in sql. Notice the exclamation mark before the statement.

Before you create a new tbl_Vechile() you can write:

if (!n.tbl_Vechile.Any(x => x.Vechile_ID == Vechile_ID)
{
     --do insert
}
else
{
   --do something else
}

**Comment by SCORPIO12** [comment]
i save this vehcile_id value in session like this
    Session["Vechilevalue"] = DropDownList1.SelectedValue;

and try to call another page i.e. abc page load
abel1.Text = Session["Vechilevalue"].ToString();

 but when i try your code this show an error 
An exception of type 'System.NullReferenceException' occurred in chart_project.dll but was not handled in user code

Additional information: Object reference not set to an instance of an object.

**Comment by johanskoldekrans** [comment]
**This has nothing todo with entityframework btw.**

But you should always check for nulls before trying to make strings or whatever. First of all. Do you have a SelectedValue from the dropdown. Debug and check. Check before setting the value if it is null. For example Session["Vechilevalue"]?.ToString() ?? "" or a simple if-check.

**Comment by ajcvickers** [comment]
@SCORPIO12 The DbSet.Add method always marks the entity as Added, meaning that EF will insert a new entity when SaveChanges is called. One way to know whether the entity already exists is to query the database for it. If the entity is found, then just update it and call SaveChanges. If it is not found, then call Add with a new entity. You might want to check out the "Saving Data" section in the docs here: https://docs.efproject.net/en/latest/
