### ISSUE TITLE
IsModified on update does not work

### ISSUE THREAD

**Issue by pantonis** [dotnet/efcore#6849]
### Steps to reproduce

```
   public void Update(Client client)
        {
            context.Entry<Client>(client).Property(x => x.DateTimeCreated).IsModified = false;
            context.Update(client);
        }
```
### The issue

The DateTimeCreated is still being updated.

EF Core version: 1.0.1
Operating system: Windows 10
Visual Studio version: VS2015

Other details about my project setup:

**Comment by ajcvickers** [comment]
@pantonis The Update method marks all the properties as modified.  If you want all properties marked as modified except DateTimeCreated, then switch the order of your statements.

**Comment by pantonis** [comment]
@ajcvickers Thanks that did the trick
