### ISSUE TITLE
select value from dropdown 

### ISSUE THREAD

**Issue by SCORPIO12** [dotnet/efcore#6852]
I have values in dropdown like thos

Mango

Orange

Grapes

I try to insert selected value from dropdown to table so when i select mango value is insered but when i select orange then mango is inserted where is i want to insert orange.. also when i select grapes always mango value is inserted this is waht i try

``` c#
try  
         {  
          Session["Vechilevalue"] = DropDownList1.SelectedValue;  
             if (Session["Vechilevalue"] != null && !n.tbl_Vec.Any(x => x.Vec_ID == Vec_ID))  
             {  

                 v.Vec_ID = Vec_ID;  
                 {  
                     v.Vec_ID = DropDownList1.SelectedValue;  
                 }  

                 n.tbl_Vec.Add(v).ToString();  
                 n.SaveChanges();  

             }  
             else  
             {  


             }  

         } 
 catch             
{              
} 
```

any solution

**Comment by rowanmiller** [comment]
This is essentially the same question that was already asked and answered in https://github.com/aspnet/EntityFramework/issues/6848.
