### ISSUE TITLE
Adding EF 7.0.0-rc1-final and xunit causes - Failed to add reference.  System.Collections.Concurrent which was not found in the GAC

### ISSUE THREAD

**Issue by bryanjhogan** [dotnet/efcore#6881]
### Steps to reproduce
1. Create a class library new project targeting .Net 4.51 (same problem applies in 4.61).
2. Using NuGet add xunit 2.1.0 
3. Using NuGet add EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final
### The issue

The following error occurs when adding the EF package.

Severity    Code    Description Project File    Line    Suppression State
Error       Failed to add reference. The package 'Microsoft.Extensions.Logging' tried to add a framework reference to 'System.Collections.Concurrent' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
### Further technical details

A workaround to this problem is to add EF first, then add xunit. Doing that leads to no errors.

**Comment by rowanmiller** [comment]
`EntityFramework.MicrosoftSqlServer` is an old package name that never made it to RTM. You want `Microsoft.EntityFrameworkCore.SqlServer`.

**Comment by rowanmiller** [comment]
We had unlisted a lot of the old packages, I'm going thru and unlisting the ones we missed now.

**Comment by bryanjhogan** [comment]
I have a lot code that relies on those packages, and from what I can see the Microsoft.EntityFrameworkCore.SqlServer is not backward compatible EntityFramework.MicrosoftSqlServer. 

What I've noticed so far is the in memory database approach has changed and my old code will not compile with the new packages.

**Comment by rowanmiller** [comment]
Hey,

The code that made up the contents of the `EntityFramework.MicrosoftSqlServer` package was just renamed to `Microsoft.EntityFrameworkCore.SqlServer`, so `1.0.0` of `Microsoft.EntityFrameworkCore.SqlServer` is the RTM follow up to `1.0.0-rc1` of  `EntityFramework.MicrosoftSqlServer`. There are minor changes (given it was still pre-release and not a 100% locked API), but nothing significant.

These docs will help you get moved the to RTM/supported releases of the packages:
* https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html
* https://docs.efproject.net/en/latest/miscellaneous/rc2-rtm-upgrade.html

~Rowan

**Comment by bryanjhogan** [comment]
Thanks Rowan
