### ISSUE TITLE
EFCore 1.1.0 Preview Final 1 Scaffold-DbContext Error.

### ISSUE THREAD

**Issue by bdm4** [dotnet/efcore#6883]
Here is the error from the package manager console: 

Scaffold-DbContext "CONNECTION STRING" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

Cannot execute this command because Microsoft.EntityFrameworkCore.Design is not installed. Install the version of that package that matches the installed version of Microsoft.EntityFrameworkCore and try again.

Relevant part of project.json to show the versions do match: 

``` JSON
{
  "dependencies": {
    "BundlerMinifier.Core": "2.2.296",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Mvc": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Routing": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview3-final",
      "type": "build"
    },   
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0-preview1-final",
    "**Microsoft.EntityFrameworkCore": "1.1.0-preview1-final**",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0-preview1-final",
    "Microsoft.Extensions.Configuration.Json": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Console": "1.1.0-preview1-final",
    "Microsoft.Extensions.Logging.Debug": "1.1.0-preview1-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0-preview1-final",
    "Microsoft.NETCore.App": "1.1.0-preview1-001100-00",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0-preview1-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
    **"Microsoft.EntityFrameworkCore.Design": "1.1.0-preview1-final",**
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0-preview1-final"
  },
  "runtimes": {
    "win10-x64": {}
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0-preview1-final"   
  },
```

This, however, works:
dotnet ef dbcontext scaffold "CONNECTION STRING" -o Models --verbose

**Comment by cooper1101** [comment]
Same problem here. Also states that Design is not installed.

"dependencies": {
        "Microsoft.NETCore.App": {
            "version": "1.0.1",
            "type": "platform"
        },
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Razor.Tools": {
            "version": "1.0.0-preview2-final",
            "type": "build"
        },
        "Microsoft.AspNetCore.Routing": "1.0.1",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.1.0-preview1-final",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0-preview1-final",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final"
    },

    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
    },

**Comment by divega** [comment]
@bricelam could you take a quick look at this issue? It seems specific to PMC commands.

**Comment by bricelam** [comment]
@bdm4 @cooper1101 What type of project are you using? Could you share your project.

**Comment by bdm4** [comment]
@bricelam I don't think it's anything special. Just a small MVC project that's hung up because of another issue I am having with ef.dotnet.tools and nuget.
https://github.com/FPBSchoolOfNursing/MediaWall

**Comment by bricelam** [comment]
It looks like it's a standalone app:

```JSON
{
  "dependencies": {
    "Microsoft.NETCore.App": "1.1.0-preview1-001100-00"
  },
  "runtimes": {
    "win10-x64": {}
  },
}
```

I'm not sure how well we work with those.

**Comment by divega** [comment]
@bricelam should we keep the issue in 1.1 or move it out?

**Comment by bricelam** [comment]
@cooper1101 It looks like you actually don't have `Microsoft.EntityFrameworkCore.Design` installed. Add the following to your dependencies and try again.
```JSON
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Design": "1.1.0-preview1-final"
  }
}
```

**Comment by bricelam** [comment]
@divega I'm still investigating. I'll bring it back to triage when I get to the bottom of it.

**Comment by bricelam** [comment]
I am getting the following error from the project.

> The specified deps.json [C:\Projects\MediaWall\src\MediaWall\bin\Debug\netcoreapp1.0\MediaWall.deps.json] does not exist

Looks like we don't work with standalone apps. Changing to a portable app works:

```JSON
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    }
  }
}
```

**Comment by bricelam** [comment]
I'm not sure how involved it would be (or if it's even possible) to support standalone apps, but we could consider showing a better error message in 1.1.0.

**Comment by divega** [comment]
**EF Team Triage:** we are not planning to support stand-alone apps in their current form. We will revisit stand-alone apps in the future when they are easier to support.
