### ISSUE TITLE
What service is responsible for creating the Entity (or Entry)?

### ISSUE THREAD

**Issue by Remleo** [dotnet/efcore#6891]
Greetings! Please advise. 

I need to wrap my `TEntity` to special `Proxy-class` (derived via Reflection.Emit) when it created or attached to `DbContext` or `DbSet<TEntity>.Local`. Can the new mechanism `optionsBuilder.ReplaceService<>()` help me with? What service can I replace?

Now working with EF Core 1.1.0-preview1-final

Sorry for trouble

**Comment by ajcvickers** [comment]
@Remleo The service is IEntityMaterializerSource. However, it is marked as internal which means that it may change and break your code in any release. Use at your own risk.

**Comment by Remleo** [comment]
@ajcvickers thanks a lot!
