### ISSUE TITLE
No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by cm4ker** [dotnet/efcore#6894]
Hi everyone! I create new ASP NET Core application with EF Core package and try add new migration to the postgres database. When I add tools to the project.json and restore packages (dotnet restore) then I try to create migration with ("dotnet ef" command) and get the next error: "No executable found matching command "dotnet-ef". 

I use [this](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#usage) documentation. I attach my project:
[TTT.zip](https://github.com/aspnet/EntityFramework/files/558998/TTT.zip)
### Further technical details

Operating system: macOS 10.12
.NET Core CLI version: 1.0.0-preview2-003148
I using VS Code as IDE

I have next packages in project.json

"Microsoft.AspNetCore.Mvc": "1.0.1",
"Microsoft.AspNetCore.Routing": "1.0.1",
"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
"Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
"Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
"Microsoft.Extensions.Configuration.Json": "1.0.0",
"Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
"Microsoft.Extensions.Logging": "1.1.0-preview1-final",
"Microsoft.Extensions.Logging.Console": "1.1.0-preview1-final",
"Microsoft.Extensions.Logging.Debug": "1.1.0-preview1-final",
"Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
"Microsoft.EntityFrameworkCore": "1.1.0-preview1-final",
"Microsoft.Extensions.Logging.Abstractions": "1.1.0-preview1-final",
"Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.2",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
"Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.0.2"

I also create question on [stackoverflow](http://stackoverflow.com/questions/40289691/no-executable-dotnet-ef). 

Please help me to understand what the problem. Sorry for my English.

**Comment by AndriySvyryd** [comment]
You need to add `"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"` to the tools section.

See https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-entity-framework-core-1-1-preview-1/ for more info

**Comment by cm4ker** [comment]
Thanks for instant reply! It works!

**Comment by digounet** [comment]
Hello,

This is my csproj  file:
`<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<TargetFramework>netcoreapp1.1</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL">
			<Version>1.1.0</Version>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore">
			<Version>1.1.0</Version>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<Version>1.1.0</Version>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet">
			<Version>1.1.0-preview4-final</Version>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Organizer.Domain\Organizer.Domain.csproj">
			<Project>{D3276E9C-4A92-47EC-BF15-61EC5B78655D}</Project>
			<Name>Organizer.Domain</Name>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="EntityConfig\" />
	  <Folder Include="Context\" />
	</ItemGroup>
</Project>`

when I type `dotnet ef migrations add Initial` then I have `No executable found matching command "dotnet-ef"` error. Can you help me please?
