### ISSUE TITLE
EF Core 1.1 Preview 1 Tooling doesn't work with .NET Core 1.1 Preview 1

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/efcore#6897]
### Steps to reproduce

I'm using .NET Core 1.1 Preview1.

```
$ /opt/dotnet/dotnet 

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0-preview1-001100-00
  Build    : 5e029a1d10ccf5cbdd2d8254c331e1ee24850436

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

To get started on developing applications for .NET Core, install the SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Then I'd like to use EF Core 1.1. Here is a simple project.json.

``` json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0-*",
    "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.1.0-*"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0-preview1-001100-00"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

EF tooling fails to start.

```
$ /opt/dotnet/dotnet restore
<snip>
log  : Restore completed in 1955ms.
$ /opt/dotnet/dotnet ef
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0-preview1-001100-00
  - Alternatively, install the framework version '1.0.0'.
```

When I downgraded netcoreapp to 1.0 and using .NET Core 1.0 runtime, it works.

``` json
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.*"
        }
      },
      "imports": "dnxcore50"
    }
  }
```
### The issue

`dotnet ef` is not working with EF Core 1.1 Preview 1 and .NET Core 1.1 preview. Is it expected limitation?
### Further technical details

EF Core version: 1.1.0-preview1-final
Operating system:  Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by caleblloyd** [comment]
I just got it working.  Try changing your `project.json` to:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0-*",
    "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.1.0-*",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0-preview1-*"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by caleblloyd** [comment]
Nevermind, once I clean my old packages it stops working.  `dotnet ef` fails and says:

	The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
	  - Check application dependencies and target a framework version installed at:
	      /usr/share/dotnet/shared/Microsoft.NETCore.App
	  - The following versions are installed:
	      1.1.0-preview1-001100-00
	      1.0.0-rc2-3002702
	  - Alternatively, install the framework version '1.0.0'.

**Comment by rowanmiller** [comment]
Currently you need to have .NET Core 1.0.0 installed on the machine. It doesn't have to be referenced by the project, but the ef tools need it present.

cc @bricelam to see if we have a plan to avoid this requirement?

**Comment by rowanmiller** [comment]
Closing as this is how .NET CLI works at the moment. We may be able to remove this restriction in the future, but we aren't going to try and work around it.

**Comment by sreichi** [comment]
If you rename it to: 
`"tools": {
  "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
},`
it will work.

Found at http://stackoverflow.com/a/40304210

**Comment by sreichi** [comment]
Update: 
I installed the version 1.0.0-preview2-003131 in addition to Version 1.0.0-preview2.1-003155 inside my Docker Container. After that the dotnet ef commands worked.

**Comment by goenning** [comment]
I really don't understand why Microsoft is not releasing a 1.1 build for EF tools. DotNet Watch already did it when 1.1 was announced. The docker images were built to be used by a single dotnet version.

**Comment by bricelam** [comment]
@goenning That's the plan for preview4
