### ISSUE TITLE
MySql provider max length on SaveChanges

### ISSUE THREAD

**Issue by ChristianHaase** [dotnet/efcore#6900]
### Steps to reproduce

1) Create a class that contains a string property
2) Instantiate said class with the string value being ~500 characters
3) Call `DbContext.SaveChanges()`
4) Watch the value saved in the database
### The issue

Following the above steps, I would expect the string to be saved in the database, but for some strange reason, the string is cut, and only ~250 characters are saved to the database. Debugging my application, I can clearly see that before saving the changes, the correct string is shown for the class property.
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS Community 2015
### project.json

```
    "MySql.Data.Core": "7.0.4-IR-191",
    "MySql.Data.EntityFrameworkCore": "7.0.5-IR21"
```

**Comment by caleblloyd** [comment]
This bug should go to Oracle, not here.

You may want to consider switching MySql EF providers to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql (I am a maintainer). We are fully MIT licensed, take issues and PRs on GitHub, and strive for high performance!
