### ISSUE TITLE
UWP Windows App certification fails

### ISSUE THREAD

**Issue by mstahl77** [dotnet/efcore#6905]
### Steps to reproduce

Include package Microsoft.EntityFrameworkCore.Sqlite version 1.1.0-alpha1-22398 or newer in a blank UWP application. Create a store app package and run Windows App Certification Kit. It will fail with the following errors:
```
Error Found: The supported APIs test detected the following errors:
API LoadLibraryExW in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
```

It will fail with the newest package 1.1.0-preview2-22561 also. The newest that seems to work is: 1.1.0-alpha1-22299

Same error is reported if I try to publish my App to Windows Store.
### Further technical details

EF Core version: Microsoft.EntityFrameworkCore.Sqlite 1.1.0-preview2-22561
Operating system: Windows 10
Visual Studio version: VS 2015 Update 3

**Comment by divega** [comment]
@mstahl77 can you try to confirm if this repros for you with `"Microsoft.EntityFrameworkCore.Sqlite": "1.1.0-preview1-final"` and `"Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"`? There have been changes in .NET Core that could help with this.

**Comment by mstahl77** [comment]
I just tried to create a Windows Store package with these dependencies:
 "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0-preview1-final",
 "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",

But I received the same errors:
Error Found: The supported APIs test detected the following errors:
API LoadLibraryExW in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. clrcompression.dll calls this API.

Here are some other information from the App Certification Kit test results:
App Architecture:
x64
Kit Version:
10.0.14393.33
OS Version:
Microsoft Windows 10 Enterprise (10.0.10586.0)
OS Architecture:
x64

**Comment by divega** [comment]
@ianhays @ericstj I see your names in https://github.com/dotnet/corefx/ issues with clrcompression.dll and WACK. Any clues whether this is expected to fail with 1.1.0-preview1 builds and whether it is going to be fixed for RTM?

**Comment by ericstj** [comment]
Is that a debug or release build of the app?  You might see this with a debug build, but the release build doesn't use LoadLibraryExW etc.

**Comment by ericstj** [comment]
I should clarify that the difference is actually ".NET Native tool chain" vs not ".NET Native tool chain".  Release builds use ".NET Native tool chain" and the build of clrcompression used in that case shouldn't use these APIs.

**Comment by mstahl77** [comment]
I'm creating the package with Release configuration and I have also .NET Native tool chain selected for x86, x64 and ARM:
![releasebuild](https://cloud.githubusercontent.com/assets/13456643/19873978/a74d476c-9fca-11e6-8394-1204ebad5288.PNG)

This is just a blank UWP App where I have added the EF Sqlite dependency, so it's very easy to reproduce for you. I have the same problem in my real App, but I just wanted to reproduce the error with a new App.

Let me know if you need any more information.

**Comment by divega** [comment]
I haven't been able to fully repro this yet (dealing with issues with enabling developer mode in my machine at the moment) but I suspect this could repro with just the `Microsoft.Data.Sqlite` dependency which brings a subset of what `Microsoft.EntityFrameworkCore.Sqlite` would bring.

**Comment by ericstj** [comment]
So I tried exactly this and it passed for me.  If you can share your project somewhere, at least the CSproj, project.json, and project.lock.json I can have a look.
Also, be certain you're running the Windows App Certification Kit against the release build of the app.

**Comment by mstahl77** [comment]
Strange. Here is the project (nothing secret there so I can share everything):
https://onedrive.live.com/?authkey=%21AEAprMoIbcZGeZI&id=D1E75AE4B9D58B60%21264955&cid=D1E75AE4B9D58B60

There are 4 files:
BuildOutput.txt: The output from the build (where yuou can see it's release build, I also deleted the AppPackages, bin and obj folders before the build)
CertTest.xml: Output from the App certification test.
UWPCertTest.zip: The project
UWPCertTest_1.0.14.0_Test.zip: App package that I built (probably not needed, but if you want to try App certification test againt it.)

**Comment by ericstj** [comment]
Looks like it's only the x64 build that has the problem.  Indeed, if I look at your project.lock.json I see that the x64 build is picking up the wrong package, from project.lock.json
```
  "targets": {
...
    "UAP,Version=v10.0/win10-x64-aot": {
...
      "runtime.win7-x64.runtime.native.System.IO.Compression/4.3.0-preview1-24530-04":
```

That should be `"runtime.win10-x64-aot.runtime.native.System.IO.Compression/4.0.1"`

@ianhays I think there is a problem with CLR compression packaging here.  This commit: https://github.com/dotnet/corefx/commit/d0ae14f6136fbc4b3af428b71523758c983c24f0 used the wrong RID for x64.  That should have been `win10-x64-aot`, not `win10-amd64-aot'.

**Comment by ericstj** [comment]
I've opened up an issue in corefx, this can be closed.  Thanks for all the info to help track it down @mstahl77.

**Comment by divega** [comment]
Thanks @mstahl77 for reporting and @ericstj for getting to the bottom of it.
