### ISSUE TITLE
No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by rmccardell** [dotnet/efcore#6906]
### Steps to reproduce

install .NET Core SDK Installer .NET Core SDK - .NET Core + CLI tools preview 3

install Entity Framework core, and EntityFramework tools as illustrated in the following project.json file 

``` javascript
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.Owin": "1.0.0",
    "Nancy": "2.0.0-barneyrubble",
    "Microsoft.EntityFrameworkCore": "1.1.0-preview1-final",
    "Microsoft.EntityFrameworkCore.Design": {
      "type": "build",
      "version": "1.0.0-preview2-final"
    },

    "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.2",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final"
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

program.cs file looks like the following:

``` c#
public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseKestrel()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
```
### The issue

running the dotnet ef migration command yields the following message:
No executable found matching command "dotnet-ef"

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
### Further technical details

EF Core version: 1.1.0-preview1-final
Operating system: Mac Osx El-Capitan
Visual Studio version:  Visual Studio Code

Other details about my project setup:

**Comment by rhires** [comment]
So, the command should be "dotnet ef" (note - no dash).

**Comment by rmccardell** [comment]
I'm sorry typo. I ran the command  dotnet -ef

**Comment by rhires** [comment]
Ok, but there is still no dash in the command. ```dotnet ef```  See [this link](https://docs.efproject.net/en/latest/platforms/netcore/new-db-sqlite.html#install-entity-framework) for how it should be typed out. It's toward the bottom of this section.

**Comment by rmccardell** [comment]
Same error still

**Comment by rmccardell** [comment]
Sorry for the confusion. The whole time I've been typing the command without the dash.

**Comment by rhires** [comment]
Interesting. ```dotnet ef``` yields an error message that includes invalid syntax as part of its error message.  ```dotnet-ef``` ... anyway. #6865 addresses your concern. @bricelam says in particular:

> The package listed in your tools section needs to be updated to 
> Microsoft.EntityFrameworkCore.Tools.DotNet.

I get no errors after making this change. 

HTH.

**Comment by rmccardell** [comment]
I used the package Microsoft.EntityFrameworkCore.Tools.DotNet instead and am still receiving the same error message.  I've been at it for a couple hours now.

**Comment by rmccardell** [comment]
So after waving the white flag, I scrapped this project and created a new one using the yeoman aspnet generator.  Totally working now.  Thanks for your input rhires.
