### ISSUE TITLE
Added state is applied to an FK object that already has an ID

### ISSUE THREAD

**Issue by strohhut** [dotnet/efcore#6907]
### Steps to reproduce
I have a User and a BlogPost table. When I want to insert a BlogPost I use a helper object that I instantiate myselft so that the BlogPost has a User:

```CSharp
blogPost.Creator = new User { Id = authenticatedUserInfo.Id };

using (var ctx = _dbContextFactory.Create())
{
  ctx.BlogPosts.Add(blogPost);
  await ctx.SaveChangesAsync();
}
```

### The issue
With RC1 this worked. Now I need

```CSharp
var entry = ctx.Entry(blogPost.Creator);
entry.State = EntityState.Unchanged;
```

Otherwise I get "Cannot insert explicit value for identity column in table 'User' when IDENTITY_INSERT is set to OFF"

Why gets an object that already has an ID an added state? Shouldn't that only be the case when its ID is default (0)?

### Further technical details

EF Core version: 1.1.0-preview1

**Comment by rowanmiller** [comment]
`Add` always marks the entire graph as added. You could look at using `Attach`, which does have [some key detection logic](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/DbContext.cs#L650), though `TrackGraph` is probably a better API for what you are trying to do:

```c#
db.ChangeTracker.TrackGraph(blogPost, e => e.Entry.State = e.Entry.IsKeySet ? EntityState.Added : EntityState.Unchanged);
```

**Comment by strohhut** [comment]
The logic should probably be:

```
e.Entry.IsKeySet ? EntityState.Unchanged :  EntityState.Added
```

**Comment by rowanmiller** [comment]
@strohhut good point 😄... I updated the code sample
