### ISSUE TITLE
The instance of entity type 'X' cannot be tracked because another instance of this type with the same key is already being tracked

### ISSUE THREAD

**Issue by dannythomas13** [dotnet/efcore#6913]
I am receiving the above mentioned error in my HttpPost when attempting to SaveChanges after adding a new entitity. The entity will have a default Id of 0 since it is an int and is unset, but it appears that it is being set to 1 after being added and an entity with this key already exists.

I have tried to strip down the example so that there is less code to look through.

I am using EF Core and an InMemoryDatabase, configured as such:

```C#
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseInMemoryDatabase());
```
I am seeding the database as follows:

```C#
public class ApplicationDbContextSeedData
    {
        private BlobUtility utility;
        private ApplicationDbContext context;
        private RoleManager<IdentityRole> roleManager;
        private UserManager<ApplicationUser> userManager;

        public ApplicationDbContextSeedData(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            BlobUtility utility)
        {
            this.context = context;
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.utility = utility;
        }

        public async Task EnsureDataSeeded()
        {
            while (this.context.SiteImages.Any())
            {
                this.context.SiteImages.Remove(this.context.SiteImages.First());
                this.context.SaveChanges();
            }          

            context.SaveChanges();

            while (this.context.Projects.Any())
            {
                this.context.Projects.Remove(this.context.Projects.First());
                this.context.SaveChanges();
            }

            var user = await this.userManager.FindByNameAsync("client");

            var project1 = await this.CreateProjectAsync(user);
            context.Projects.Add(project1);

            context.SaveChanges();
        }

        private async Task<Project> CreateProjectAsync(ApplicationUser user)
        {
            var siteImages = new List<SiteImage>();

            int i = 1;

            foreach (var img in await utility.GetAllAsync("intetech"))
            {
                siteImages.Add(new SiteImage
                {
                    Id = i,
                    ImageUrl = img,
                    Name = img.Split('/').Last().Split('.').First()
                });

                i++;
            }

            return new Project
            {
                Id = 1,
                Description = "Thornton Science Park",
                SiteImages = siteImages
            };
        }
    }
```
Here is the project class:
```C#
    public class Project
    {
        public Project()
        {
            this.SiteImages = new Collection<SiteImage>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public ICollection<SiteImage> SiteImages { get; set; }
    }
```
and here is the SiteImage class:
```C#
    public class SiteImage
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
```
The context is injected to the controller:
```C#
public HomeController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            BlobUtility utility)
        {
            this.context = context;
            this.userManager = userManager;
            this.utility = utility;
        }
```
and here are the controller actions that are giving me the issue:
```C#
 [HttpGet]
        public ActionResult CreateSiteImage(int projectId)
        {
            var userId = this.userManager.GetUserId(User);

            var vm = new CreateSiteImageViewModel
            {
                UserId = userId,
                ProjectId = projectId
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSiteImage(CreateSiteImageViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                context.Projects.Include(p => p.SiteImages).FirstOrDefault().SiteImages.Add(new SiteImage());

                context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }
```
I am new to EF but this seems to be pretty basic operation so I am thinking I am missing something fundamental and would appreciate any guidance.

Thanks

**Comment by dannythomas13** [comment]
If it helps I have stripped back the solution and attached it here:

[WG360.zip](https://github.com/aspnet/EntityFramework/files/563639/WG360.zip)

**Comment by dannythomas13** [comment]
I have uploaded a stripped down version of the solution in case that makes it easier than looking at the above description

[WG360.zip](https://github.com/aspnet/EntityFramework/files/563839/WG360.zip)

**Comment by ajcvickers** [comment]
@dannythomas13 EF uses a convention that integer primary keys are setup to have automatically generated values by default. This kicks in when the value of the key is zero. Since you are explicitly setting key values in your seed method it looks like you don't want to use generated values. You can tell EF not to generate values by adding something like this in an override of OnModelCreating on your DbContext class:
```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
        .Entity<SiteImage>()
        .Property(e => e.Id)
        .ValueGeneratedNever();
}
```

**Comment by dannythomas13** [comment]
Thank you @ajcvickers The only reason I set id's in the seed in the first place is because I was getting errors at the time of seeding unless they were set but I took your advice removed all of the id's and it works as you said, it is good to know that once I start setting them I lose the ability to have them created for me

**Comment by ajcvickers** [comment]
@dannythomas13 It's not that you lose the ability to have them created, it's that:
* You can't have an ID of zero. If you need to use zero as a valid ID, then use a nullable int property.
* You need to make sure that any explicitly specified IDs do not collide with any auto-generated IDs.

**Comment by hisuwh** [comment]
@ajcvickers you do lose the ability to have them created for you.
I had the same situation in a test setup.  Seeding a set with an object with id 1.
Then in my test adding new object with id 0 - expecting it to auto generate (and this indeed worked on version 1.x) but it just failed saying it couldn't duplicate the key.

**Comment by ajcvickers** [comment]
@hisuwh Please file a new issue with a complete code listing or project that exhibits the issue you are seeing. It may be related to this issue, but it sounds like a different scenario.
