### ISSUE TITLE
Issues with migrations when using EF 1.0.1

### ISSUE THREAD

**Issue by pjeannet** [dotnet/efcore#6920]
### Steps to reproduce
Tried to add a migration after updating EF from 1.0.0 to 1.0.1

### The issue
I get the following output :

```
Could not invoke this command with the startup project 'Thelos.NAO'. Check that 'Microsoft.EntityFrameworkCore.Design' has been added to "dependencies" in the startup project and that the version of 'Microsoft.EntityFrameworkCore.Tools' in "tools" and 'Microsoft.EntityFrameworkCore.Design' are the same. See http://go.microsoft.com/fwlink/?LinkId=798221 for more details.
```

I saw some other issues with simiral problems but it seems that the temporary fix was for apps only.

### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10
Visual Studio version: VS2015 update 3

Other details about my project setup: this is part of my project.json
```json
  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.EntityFrameworkCore.Design": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.0.0-preview2-update1",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview2-update1",
    "Microsoft.WindowsAzure.ConfigurationManager": "3.2.3",
    "ncalc": "1.3.8",
    "Newtonsoft.Json": "9.0.1",
    "Sendgrid": "8.0.5",
    "WindowsAzure.Storage": "7.2.1"
  },

  "tools": {
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {}
  },
```

**Comment by pierre-weceipt** [comment]
Ok, it seems that "Microsoft.EntityFrameworkCore.Design": "1.0.1" version does not exist and should be "1.0.0-preview2-final". However "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1" does exist.

**Comment by rowanmiller** [comment]
There is a 1.0.1 of Microsoft.EntityFrameworkCore.Design - http://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/1.0.1

**Comment by rowanmiller** [comment]
BTW in the `tools` node, you should also replace:

```
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
```

with 

```
"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
```

**Comment by pierre-weceipt** [comment]
That's strange, intellisense wasn't giving me the tooltip for 1.0.1 but when I replaced it with the preview2 it worked again. I tried the new tool package too (preview3) but as it was not working I thought it was designed to work with the 1.1 preview. It is still a bit confusing with the packages version not being fully unified.
On a side note should we use only core package, db provider package (.sqlserver for ex.) or both? It was working with only core ones but while debugging I noticed the second ones but could only guess about the different use cases.

Thanks for the answer!

**Comment by rowanmiller** [comment]
>  It is still a bit confusing with the packages version not being fully unified.

Absolutely agree, this is definitely a confusing interim state. Once the tools reaches RTM (which will happen when .NET CLI tooling reaches RTM), then we plan to align versions across all packages. We're looking forward to that as much as you are 😄.

**Comment by divega** [comment]
@pierre-weceipt could you provide repro steps and a project?

**Comment by rowanmiller** [comment]
Closing as I think we've answered things, but feel free to reply if you are still blocked. We know the tooling story is super complex and fragile at the moment and we are working to improve it.
