### ISSUE TITLE
EF core treating readonly properties as NULL on Insert

### ISSUE THREAD

**Issue by brunneus** [dotnet/efcore#6928]
I'm struggling to understand why ef core are treating readonly fields as null, I have the following property on my model.

`private readonly string _name;`
`public string Name => _name;`

When I add my entity to the DBContext and try to save changes, An exceptions is throw because Name cannot be null.

The only way I find to this work is to define on ModelCreating that this property has a colunm name.

`p.Property(pr => pr.Name).HasColumnName("name");`

Doing so, this works OK.

I want to know if someone knows why EF core is mapping such property to NULL.

Thanks in advance

PS: I know that this will not work when the EF core tries to build the entity model, but this wasn't supposed to work in terms of saving the entity?

**Comment by divega** [comment]
By convention we don't include read-only properties to the model. Invoking `Property()` the way you found is the right way to tell EF Core to consider the property. However if the field is read-only EF Core won't be able to set it.
