### ISSUE TITLE
What to use in place of Obsolete DbCommandLogData when logging?

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#6934]
### Steps to reproduce
I was using DbCommandLogData to log ONLY the commands, not all of the rest of the data that comes through:

 if (state is Microsoft.EntityFrameworkCore.Storage.DbCommandLogData)
        {
          Console.WriteLine(formatter(state, exception));
        }

### The issue
It's marked obsolete. What can I use to filter on commands during logging database interaction?

### Further technical details

EF Core version: 1.1 preview

**Comment by smitpatel** [comment]
@julielerman - At present we haven't added alternative mechanism to logging. But check out discussion on #6201. That is the way we want to log commands in the future which will remove `DbCommandLogData` hence `Obselete` attribute

**Comment by julielerman** [comment]
Thanks. Saw that earlier and wasn't sure how it related to current bits. Now I understand. :)  Is it possible to change the current notes around DbcommandLogData so that it indicates that it will be obsolete in the future but there isn't a current alternative yet?

**Comment by divega** [comment]
@smitpatel please file a new issue detailing the plan for removing this class.

@julielerman hi, can you please clarify what you mean by "notes around DbcommandLogData"? Is it docs or XML documentation? Thanks!

**Comment by julielerman** [comment]
@divega hi back! Ahh, yes . A bit more useful if I clarified. I just mean about the annotation on the [DbCommandLogData]((https://github.com/aspnet/EntityFramework/blob/1fa247b038927a7d7438f666dc11253f64e0432d/src/Microsoft.EntityFrameworkCore.Relational/Extensions/DbCommandLogData.cs) ) class:

 ```
 [Obsolete("This class is obsolete. It will be removed in a future release.")]
    public class DbCommandLogData : IEnumerable<KeyValuePair<string, object>>
    {
```

**Comment by smitpatel** [comment]
Filed #6946 to outline future of `DbCommandLogData`
