### ISSUE TITLE
Client evaluation warnings when using method parameters with common Linq expressions

### ISSUE THREAD

**Issue by Kizmar** [dotnet/efcore#6939]
We have a couple teams working work .Net Core 1.0.0 and Entity Framework Core 1.0.0. We've both been running into the client evaluation warnings like these when using very common Linq methods (like .Contains(), .Count(), .Distinct(), .Take(), etc...) and passing in method parameters:
> warn: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[8]
      The LINQ expression 'Distinct()' could not be translated and will be evaluated locally. To configure this warning ...

> warn: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[8]
      The LINQ expression 'Any()' could not be translated and will be evaluated locally. To configure this warning ...

> warn: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[8]
      The LINQ expression 'Count()' could not be translated and will be evaluated locally. To configure this warning ...

Both teams are dealing with large data sets and want to avoid client evaluations for performance reasons. We've seen a lot of talk about this in various places on the intarwebs, but none seem to explain how to avoid it or why it's doing it. I can't believe that any time we pass a parameter into Linq, we'll have to live with client evaluations. We'd end up having to turn everything into stored procedures.

Is this working as intended/expected?

If I'm missing some duplicate discussions about this, please point me to them. :)

The documentation on this doesn't really address what we're seeing. It's doing it with simple variables, not just methods: https://docs.efproject.net/en/latest/querying/client-eval.html#disabling-client-evaluation

**Comment by divega** [comment]
@Kizmar can you please provide a repro? Examples of queries should be a good start.

**Comment by Kizmar** [comment]
@divega Yeah when I get some time I'll build an example or two that I can drop in here...

**Comment by rowanmiller** [comment]
Closing but we'll reopen if you are able to provide the details
