### ISSUE TITLE
NET Standard Compatibility with SQLite and Xamarin

### ISSUE THREAD

**Issue by econner20** [dotnet/efcore#6942]
Which version of SQLite is recommended to be used with EF and .NET Standard for Xamarin cross platform compatibility for iOS, Android and UWP.

**Comment by rowanmiller** [comment]
@bricelam can you answer this

**Comment by bricelam** [comment]
Installing the `Microsoft.EntityFrameworkCore.Sqlite` package will install a version that works with UWP. You should be fine using the in-the-box version on iOS and Android.

In 2.0, we're switching to SQLitePCL.raw which includes a version Android that also works with Android N. IT defers to the in-the-box version on iOS, but you can also opt to use an app-local version by using a different SQLitePCL.raw bundle, or bringing your own. See #7667 for details.

**Comment by MelbourneDeveloper** [comment]
I have created a .NET Standard library for SQLite https://github.com/MelbourneDeveloper/SQLite.Net.Standard

It doesn't require any platform specific libraries but it has been thoroughly tested on uwp, android, iOS and .net. It doesn't have an orm. It just gives you flat table access and you could implement something like ADO.net for it.
