### ISSUE TITLE
Warnings CS3001/CS3009 generated in EF.Core, but not in EF6 when [assembly: CLSCompliant(true)] is set using CodeAnalysis with BasicCorrectnessRules.ruleset

### ISSUE THREAD

**Issue by JRBonnema** [dotnet/efcore#6951]
I notice an inconsistency between EF6 and EF.Core.  I'am running the latest version of Microsoft Visual C# 2015 - Update 3. I use WinForms. 

I was experimenting with Code Analysis with various rulesets to see if some of the warnings generated were usefull to improve my code. One of the warnings was to include the following line in AssemblyInfo.cs [assembly: CLSCompliant(true)]

After I added this line in both EF6 and EF.Core environments using several rulesets including 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets\BasicCorrectnessRules.ruleset"  I got the following warnings in EF.Core but not in EF6

Warning	CS3001	Argument type 'DbContextOptionsBuilder' is not CLS-compliant	Claims	C:\Visual Studio 2015\Projects\C# EF\Claims\Claims\DataModel\ClaimsDbContext.cs	29	Active
Warning	CS3001	Argument type 'ModelBuilder' is not CLS-compliant	Claims	C:\Visual Studio 2015\Projects\C# EF\Claims\Claims\DataModel\ClaimsDbContext.cs	35	Active
Warning	CS3009	'ClaimsDbContext': base type 'DbContext' is not CLS-compliant	Claims	C:\Visual Studio 2015\Projects\C# EF\Claims\Claims\DataModel\ClaimsDbContext.cs	13	Active

The Code runs fine in both EF6 and EF.Core. There is no urgency in this issue for me. I'm however wondering why a warning is generated in EF.Core and not in EF6.  

Best regards
JRBonnema

### Further technical details

EF Core version: (found in project.json or packages.config)
<package id="Microsoft.EntityFrameworkCore" version="1.0.1" targetFramework="net461" />
Operating system: Windows 10 Home - latest one
Visual Studio version: Microsoft Visual C# 2015 - Update 3

Other details about my project setup:

**Comment by ajcvickers** [comment]
@JRBonnema Curious what your situation is where CLS compliance is relevant?

**Comment by JRBonnema** [comment]
My interest is purely theoretical, not practical.

Like I said above I was experimenting with Code Analysis (latest version) to see if I could get rid of all the generated warnings. It turned out that In EF6 I can, but in EFCore I cannot. If the generated Code Analysis warnings can be believed all types in EF6 are CLS compliant, while for example the DbContext in EFCore is apparently not CLS compliant.

I can imagine that this issue for you and your team doesn't have a high priority right now, all the same in the long run it's something to consider.

**Comment by divega** [comment]
**EF Team Triage:** we are not planning to make any changes to EF Core re CLS compliance.

**Comment by JRBonnema** [comment]
Fine with me, maybe you should inform the Code Analysis team that in one of there coming releases they should drop the relevant warnings in case of analysing EFCore code.
