### ISSUE TITLE
RIGHT function not available in SQLCE

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#6955]
Any hints how to work around this? (Used for EndsWith)

**Comment by smitpatel** [comment]
This should work by default. Relational one uses `%` syntax for EndsWith instead of RIGHT

**Comment by divega** [comment]
@smitpatel the change to the SQL Server provider was done in 1.1. to fix some issues with the default relational translation (e.g. results are incorrect if the parameter string contains wildcard characters) . I believe @ErikEJ is trying to implement the same improvement and I suspect it should be possible to come up with something based on the supported string functions such as `SUBSTRING()`, `CHARINDEX()` and `LEN()`.

**Comment by smitpatel** [comment]
`a.EndsWith(b)`
`RIGHT(a, LEN(b)) = b`
`SUBSTRING(a, LEN(a) - LEN(b) + 1, LEN(b)) = b`

**Comment by ErikEJ** [comment]
@smitpatel Great!
