### ISSUE TITLE
[Question] - How to handle extensibility of a model

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#6961]
This is just a general question about my use case, and EF7.

My application has an EF7 model and db context. I am calling this the "Core" Data Model.

My application allows third party "extensions" to be installed.

These extensions need to be able to "extend" the existing data model (tables etc) to do things like:

1. Add additional columns
2. Add foreign keys that reference existing core tables.

The issue I have, is how to allow a third party extension to do these things, without breaking the existing "Core" EF context that is in use.

## Extending existing tables with Additional  Columns

Am i right in thinking the correct path for this is:

1. The developer would create a new DbContext.
2. Derive their own entity from the core entity.
3. Map their entity to the existing Table name.
4. Generate a migration - and make sure its empty (does nothing).
3. Add their additional properties, and generate a migration that adds those columns to the table.

The rule would be, never add a new [Required] property without a default value to an existing table. As that would break the existing DbContext. ?

## Adding a Foreign Key that references an existing table.

If a developer wanted their new table to relate to an existing core table:

1. Create their own DbContext
2. Create their own Entity for the new table as usual.
4. What does their new entity look like in terms of adding a navigation property to the existing table (i.e the Foreign Key relationship?_
5. Does the developer need to Ignore() the navigation property (type) from their model? It will already exist in the Core model / DbContext.
6. How to avoid FK violation, when the existing core DbContext tries to delete an entity from its table, after the new FK is in place? Would the rule be, all new FK relationships have to be added with "Cascade on Delete"?

I'd love to head some feedback thoughts,, guidance on this topic!

**Comment by rowanmiller** [comment]
The approach you described is one that we have seen folks use. The foreign key scenario is really the same as the first one, you just need to generate a migration (with all the base types in the model) before you create the new relationship. Cascade delete would work, or optional relationships with SetNull for the cascade behavior.
