### ISSUE TITLE
(Advice) intercepting database accesses

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#6967]
I'm looking for a way to intercept database queries as a means of getting some more in-depth performance stats.  I'm after number of queries, query duration, the result data (for an idea of data magnitude) and ideally some access to any LINQ expression.

I've looked through the code and feel like wrapping `ExecutionStrategyFactory` or `Database` is the way to go - and while I can create an extension method on `RelationalDbContextOptionsBuilder` for the former, or /replace/ services, I can't see a way of wrapping either, such that the underlying provider's implementation is still used.

Is there a decent place to hook into this?

**Comment by rowanmiller** [comment]
The easiest place would be to logging - https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging. You can look at the `state` parameter that gets passed to `Log` method, you are interested in events where state is an instance of `Microsoft.EntityFrameworkCore.Storage.DbCommandLogData`

**Comment by kierenj** [comment]
Ah great thanks, I had been playing with logging and had wondered if anything out in the wild was using real `state` objects - fantastic.

I'm quite keen on getting access to either the LINQ expression going in, or something that can be used to check the "magnitude" of data returned.  This is to determine if a projection or filter has been applied, as well as get some metric on data in/data out for an operation.  I know it's not exactly a common use case, but are there other avenues I can explore for this too?

**Comment by rowanmiller** [comment]
You are probably going to have to look at wrapping some services in order to do that. You're kind of on your own, as it's not really a scenario we test for etc. We do have a test that does some wrapping that may be of use to you as some general guidance to get started - https://github.com/aspnet/EntityFramework/blob/dev/test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/BadDataSqliteTest.cs#L366.

**Comment by rowanmiller** [comment]
Closing, but can reopen if further discussion is needed

**Comment by kierenj** [comment]
For the ref of anyone else:

Ok, the trick is:

1. Replace the `IRelationalConnection` that EF Core's DI system uses via `ReplaceService<IRelationalConnection, MyRc>()`.  Our new `MyRc` will *wrap* the existing connection to add hooks
2. In our `MyRc`, have a constructor param of `IDatabaseProviderServices`.  The EF DI system will populate it.  Cast that to `IRelationalDatabaseProviderServices` and then grab the `RelationalConnection` property from that
3. Wrap all methods, but have `public DbConnection DbConnection { get; }` return an instance of a `DbConnection`-wrapping class
4. In *that* wrapping class, have `CreateDbCommand()` return an instance of a `DbCommand`-wrapping class
5. In *that* wrapping class, have `ExecuteDbDataReader()` return an instance of a `DbDataReader`-wrapping class

Then, in the `DbCommand` and `DbDataReader` wrappers, we can see what commands and parameters are being sent to the database, and the results coming back.

This only works with relational models.

I may write a blog post on this, and will post here if I do.

**Comment by weitzhandler** [comment]
Why did they make `SqlConnection` and `SqlCommand` sealed??
