### ISSUE TITLE
Recommend add IgnoreOnInsert and IgnoreOnUpdate attribute that limit insert or update.

### ISSUE THREAD

**Issue by RainingNight** [dotnet/efcore#6975]
When update db by dtos with [IgnoreOnInsert] or [IgnoreOnUpdate], this is very useful!

**Comment by divega** [comment]
@leshin could you provide a detailed example?

**Comment by rowanmiller** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.
