### ISSUE TITLE
How to use Tools.DotNet 1.0.0-preview3-final with .NET Core 1.1 

### ISSUE THREAD

**Issue by goenning** [dotnet/efcore#6977]
I'm currently trying to use Tools.DotNet 1.0.0-preview3-final on a server that only `.NET Core 1.1` is available. Why is it targeting .NET Core 1.0 if it was released with EF Core 1.1?

```
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /tmp/build_495aac899181b4db6e10cb2bb715e358/goenning-thebooks-api-f8d6738/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0-preview1-001100-00
  - Alternatively, install the framework version '1.0.0'.
```

**Comment by smitpatel** [comment]
@goenning - EF tools are using .NET Core 1.0.0 under the hood. Though it is not required for application to target it. Your application can target any version of .NET Core App. But if you wish to run `dontet ef` commands, it requires your machine to have .NET Core 1.0.0 installed. Just installing .NET Core 1.0.0 on your server will fix the issue without any changes in code.

**Comment by goenning** [comment]
Can we expect a new release of EF tools targeting 1.1 anytime soon? 

Official Docker images, for example, does not ship with both versions. Yeah, I can extend it and install it by myself, but I'm trying to leave the footprint as low as possible.

**Comment by smitpatel** [comment]
For more info on that see #6897
