### ISSUE TITLE
Add entity with related entity that's not tracked by current context throw exception

### ISSUE THREAD

**Issue by cdie** [dotnet/efcore#6985]
### Steps to reproduce
Considering this architecture 
```C#
class Inner
{
    public Guid Id { get; set; }
    public string String { get; set; }
    public ICollection<Top> Tops { get; set; }
}

class Top
{
    public Guid Id { get; set; }
    public string Data { get; set; }
     
    public Inner Inner { get; set; }
    public Guid InnerId { get; set; }
}
```
And this mapping

```C#
var b = modelBuilder.Entity<Inner>();
b.HasMany(m => m.Tops).WithOne(m => m.Inner).HasForeignKey(m => m.InnerId);

 var i = modelBuilder.Entity<Top>();
i.HasOne(m => m.Inner).WithMany(m => m.Tops).HasForeignKey(m => m.InnerId);
```

Doing this operation  (extra simplified for demonstration purpose)
       
  ```C#
 using (var c = new Ctx())
{
    c.Database.Migrate();
    
    Inner i = new Inner
    {
        String = "test",
        Id = Guid.NewGuid()
    };
    
    c.Add(i);
    c.SaveChanges();
}

var list = new List<Inner>();
using (var c = new Ctx())
{
     list.Add(c.Set<Inner>().First());
}

using (var c = new Ctx())
{
    Top i = new Top
    {
        Data = "test",
        Inner = list.First(),
        Id = Guid.NewGuid()
    };
    
    c.Add(i);
    c.SaveChanges();
}
```

Makes last SaveChanges throw exception "Primary key already exists". This is normal because the Inner object is not tracked by the last context. However, this kind of operation happens many times in our application. We don't keep a global context for all application, cause it will explode with too many entries to manage and really slowing the application.
Instead, we use Autofac to resolve our repository, and create a new Context to all resolve operation.
If, in previous example, I attach the Inner object to last context, I don't have any exceptions. Should it not be Dbcontext job to manage that for graph entities ? Simple check would be to see if Id is already set or not ... ?
Else, how can generically found a solution to attached already treated object to context with the good state in order to prevent entites graph to be persisted and throw a primary key exception ?  

### Further technical details

EF Core version:  1.1.0-preview1-final
Operating system: Windows 10 x64
Visual Studio version: VS 2015

**Comment by ajcvickers** [comment]
@cdie There are several ways to handle this:
* Query for the existing object in the context for the unit of work where you will make the changes.
* If the existing object must come from an external source, then treat it as a disconnected entity and Attach it to the context for the unit of work before adding the new entity.
* Use TrackGraph to determine the state for each entity in the graph. For example:
```C#
ctx.ChangeTracker.TrackGraph(
    i, 
    n => n.Entry.State = n.Entry.IsKeySet ? EntityState.Unchanged : EntityState.Added);
```

**Comment by cdie** [comment]
About original issue, setting State (solution I chosse, thanks @ajcvickers for this) is now throwing InvalidOperationException.
In m y case, I retrieve my entity from a part of my app, and with a set of include, in another context, when trying to setting state, I have the exception. I work in a pub-sub situation, so my context is freshly created any time, but I sometimes use Include, which, in this case track this particular entity in this side.

Also note that my domain object IS completely fill when this happens, so i CANNOT query this particular thing within my context.
I've tried Context.Attach, same exception than setting state.

Exception detail :

`The instance of entity type 'Specialite' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.`

Stack Trace :
 ```
à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   à Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState entityState)
   à Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   à Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   à Microsoft.EntityFrameworkCore.DbContext.Attach[TEntity](TEntity entity)
   à DALCore.EFRepository`1.<MarkForInsertOrUpdate>b__34_0(EntityEntryGraphNode e)
```

Please note that this entity as its IsKeySet to true.

I cannot figured out how to avoid this exception which is blocking my process.

**Comment by ajcvickers** [comment]
@cdie That message indicates that there are two entity instances that have the same key. If these are intended to be the same entity--for example, one from a query, the other coming from somewhere else, then it will require them to be resolved to a single instance, possibly just choosing one, otherwise merging values from one into another.
