### ISSUE TITLE
Generic Async and Find Methods

### ISSUE THREAD

**Issue by CaffeinatedFunctionality** [dotnet/efcore#6995]
I have a generic class using `DbSet<T>` I cannot seem to find a `Find` or `FindAsync` method. Is this already implemented and I'm just doing it incorrectly or is this something that hasn't been built yet? Thanks for your hard work guys. I did notice the Async methods work well for calling those methods in not a generic way, however for Generics it seems to not be available.

**Comment by ajcvickers** [comment]
@scy0846 What version of EF Core are you using? Find in all its forms was introduced in EF Core 1,1, which is currently available as a preview package on NuGet.

**Comment by scy0846** [comment]
Oh my God thank you! I see it in the prerelease. Thanks again for your hard
work.

**Comment by scy0846** [comment]
Out of curiosity can you use EF6 for a ASPNet Core project? Is there any
issues with that at all?

**Comment by rowanmiller** [comment]
@scy0846 you can use EF6 in an ASP.NET Core project that targets the full .NET Framework (as opposed to .NET Core).

**Comment by divega** [comment]
The following documentation article shows how to use EF6 with ASP.NET Core in more detail: https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6
