### ISSUE TITLE
Cannot install Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests.1.1.0 from RTM feed

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#7006]
### Steps to reproduce
Attempting to install above package fails

### The issue
See title, installing into a .NET 4.5.1 class library (changing the target framework to 4.6.1 does not make any difference)

Exception message:
Attempting to gather dependency information for package 'Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests.1.1.0' with respect to project 'test\EntityFramework.SqlServerCompact40.Design.FunctionalTest', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests.1.1.0' with DependencyBehavior 'Lowest'
Unable to find a version of 'System.IO.Compression' that is compatible with 'NETStandard.Library 1.6.1 constraint: System.IO.Compression (>= 4.3.0)'.
========== Finished ==========

### Further technical details

EF Core version: 1.1.0
Operating system: Win 10
Visual Studio version: VS 2015 Update 3

**Comment by ErikEJ** [comment]
Fixed in the 1.2 dev feed

**Comment by divega** [comment]
@ErikEJ if this is it still an issue for 1.1.0 RTM it means it is hard to test providers for 1.1.0 RTM. Can you confirm?

**Comment by ErikEJ** [comment]
Yes, still an issue on 1.1 RTM bits, I am just happy to move forward

**Comment by rowanmiller** [comment]
May be related to needing NuGet 3.5

**Comment by ErikEJ** [comment]
@rowanmiller Sounds likely, I am running 3.4.4.1321

**Comment by divega** [comment]
Does not repro for me using NuGet 3.5. 

Note that I had to install xUnit separately because we depend on a pre-release package:

``` 
install-package xunit -pre -version 2.2.0-beta4-build3444
```

**Comment by divega** [comment]
Closing, but please reopen if it does not work for you with NuGet 3.5.

**Comment by ErikEJ** [comment]
Will do, thanks
