### ISSUE TITLE
Allow default value check in value generation to be customized

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#701]
Currently we generate a value for a property on Add when it is marked as needing value generation in metadata and the current value is the default for the type of property. It should be possible to customize the latter check to change the this sentinel value, make it a more complex check (e.g. negative numbers) or so that values are always generated regardless of the current value. This is probably best done with a Func in the model, but note this requires we implement the ability to annotate a model with code snippets.

**Comment by ajcvickers** [comment]
See also the discussion in https://github.com/aspnet/EntityFrameworkCore/issues/15070#issuecomment-477311221

**Comment by roji** [comment]
This could be more relevant with non-nullable reference types. For example, non-nullable string properties can no longer default to null (unless bang is used), so it makes sense for many cases to initialize it e.g. to an empty string. But EF still uses null as the uninitialized sentinel value (to trigger value generation).

**Comment by risperdal** [comment]
Any updates on this manner? The milestone is set for 8.0. But i tried with ef core 8.0. Its same.

**Comment by roji** [comment]
@risperdal have you seen the documentation for this in the [what's new page](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#sentinel-values-and-database-defaults)? If you're using the new API and still having issues, please open a new issue with a minimal, runnable repro.

**Comment by risperdal** [comment]
I see now. Thanks for pointing out. I had assumed this was fixed as it was requested. But i didnt know about the sentinel values. I will read the docs and try to implement according my needs. Thanks very much again.
