### ISSUE TITLE
Nullable Foreign Keys for Columns in one table which is being used to map Many to Many relationship between rows of another table.

### ISSUE THREAD

**Issue by deepanshgupta** [dotnet/efcore#7019]
[ManyToManyOnSameTable.zip](https://github.com/aspnet/EntityFramework/files/591954/ManyToManyOnSameTable.zip)
### Steps to reproduce
1. Download and Unzip the solution attached with the issue.
2. Provide the correct connection string for database connectivity to SQL Server 2016 in the appsettings.json file.
3. Execute the solution and verify the schema created in the database.
4. Firms table in the database would be storing the Id's of the firms.
5. FirmsContentShare table in the database would be used to store many to many relationship of rows in Firms Table.
6. The columns SourceFirmId and TargetFirmId created in FirmsContentShare would store Firms.Id value and thus would be Foreign Keys to Firms.Id column.

### The issue
SourceFirmId and TargetFirmId columns are nullable which seems wrong. Ideally they should be Not Null to maintain referential integrity of the data and their mapping to Firms.Id column.

I am not sure whether there is an oversight at my part and would like to know if there exists a way in Entity Framework to achieve that.

### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10
Visual Studio version: VS 2015

Other details about my project setup:

**Comment by rowanmiller** [comment]
The columns are nullable because the foreign key properties in the entity class are nullable. If you want the relationship to be required, then just change the properties to be non-nullable (i.e. `Guid` instead of `Guid?`.

```
    public class FirmContentShare
    {
        ...
        public Guid? SourceFirmId { get; set; }
        ...
        public Guid? TargetFirmId { get; set; }
        ...
    }
```
