### ISSUE TITLE
Using .Include() on a one-to-one relation does only return one "parent"

### ISSUE THREAD

**Issue by FritzTheDarkCat** [dotnet/efcore#7020]
### Steps to reproduce
1. Using model first... targeting SQL-Server

2. Based on the "Creating a complex data model" post found here: https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model

3. using the partial model (Create the Instructor Entity,  Create the OfficeAssignment Entity) that implements a one-to-one or one-to-zero-or-one relation.

4. using add migration for the two new related models, than database update, finding 2 new tables in the db and seed them with data (> 1 row per table) 

5. using the context to load entities and related entities with .Include()

### The issue
Only one (1) entity (row) and it's related entity is returned. Expected was the return of every (4) entity (row) with related entity.

No exception, no error message...

### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10 Enterprise 10.0.14393 x64
Visual Studio version: VS Community 2015 14.0.25425.01 Update 3

**Comment by smitpatel** [comment]
Can you post the query you used in step 5?

**Comment by maumar** [comment]
@FritzTheDarkCat I was unable to reproduce the issue. I used the following code and I'm getting expected results. 

```
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var i1 = new Instructor { FirstMidName = "FMN1", LastName = "LN1", HireDate = new DateTime(2000, 1, 1) };
                var i2 = new Instructor { FirstMidName = "FMN2", LastName = "LN2", HireDate = new DateTime(2000, 1, 1) };
                var i3 = new Instructor { FirstMidName = "FMN3", LastName = "LN3", HireDate = new DateTime(2000, 1, 1) };
                var i4 = new Instructor { FirstMidName = "FMN4", LastName = "LN4", HireDate = new DateTime(2000, 1, 1) };

                var oa1 = new OfficeAssignment { Instructor = i1, Location = "L1" };
                var oa2 = new OfficeAssignment { Instructor = i3, Location = "L2" };

                ctx.Instructors.AddRange(i1, i2, i3, i4);
                ctx.OfficeAssignments.AddRange(oa1, oa2);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.Instructors.Include(i => i.OfficeAssignment);
                var result = query.ToList(); // 4 instructors, 2 assignments loaded (for the instructors that have them)
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.OfficeAssignments.Include(oa => oa.Instructor);
                var result = query.ToList(); // 2 assignments both with instructors loaded
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<OfficeAssignment> OfficeAssignments { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=.;Database=Repro70200;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }

    public class Instructor
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string LastName { get; set; }

        [Required]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        [StringLength(50)]
        public string FirstMidName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hire Date")]
        public DateTime HireDate { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return LastName + ", " + FirstMidName; }
        }

        //public ICollection<CourseAssignment> Courses { get; set; }
        public OfficeAssignment OfficeAssignment { get; set; }
    }

    public class OfficeAssignment
    {
        [Key]
        [ForeignKey("Instructor")]
        public int InstructorID { get; set; }
        [StringLength(50)]
        [Display(Name = "Office Location")]
        public string Location { get; set; }

        public virtual Instructor Instructor { get; set; }
    }
```

**Comment by FritzTheDarkCat** [comment]
@maumar: thank you for doing the check, you are right, sorry for that.

After maumar's feedback I started from scratch and the query does just fine.

var data = _context.Instructor.Include(i => i.OfficeAssignment);

The query runs in a HttpGet Handler and when I checked the returning data in the browser, only one of the rows made it to the browser. So the problem is nor in EF, my fault, sorry.

Please close this issue or better purge from history..

**Comment by jnm2** [comment]
@FritzTheDarkCat you're fine! We all jump to conclusions- it's how our brains are so good at what they do- and it only sometimes goes wrong. =)

**Comment by joehoeller** [comment]
Can someone explain why .Include(c => c.TableName) only returns one row from the dB? It needs to return all the rows, with associated data and does not.

**Comment by joehoeller** [comment]
This code above makes no sense. Let's say I have a Parent and a Child table.

I want to include all the children of each of the parents in one REST call.

public class Parent
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ParentId { get; set; }
        public string ParentName { get; set; }
        public virtual ICollection<Child> Children { get; set; }

        public Parent()
        {
            Children = new HashSet<Child>();
        }
    }


    public class Child
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ChildId { get; set; }
        public string ChildName { get; set; }

        public Parent Parent { get; set; }
    }


///CONTROLLER:

// GET: api/Parents
        [HttpGet]
        public IEnumerable<Parent> GetParent()
        {
            return _context.Parent.Include(p => p.Children).ToList();
   
        }

///CONTEXT FILE:

 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Parent>().HasMany<Child>().WithOne(p => p.Parent);
        }

**Comment by joehoeller** [comment]
Why does it only produce one Parent with One of the related children?

**Comment by smitpatel** [comment]
@joehoeller - Because the navigation 'OfficeAssignment` is reference navigation. Every `Instructor` will have 0 or 1 (depending on required nature of FK property) `OfficeAssignment`. Hence there will be only 1 row returned.

In your code, you are using collection navigation `Children`. The query will produce one Parent, containing collection of child and the collection will have all the associated children in it. (not just 1)

**Comment by joehoeller** [comment]
It doesnt work though, I literally get one parent and the first child. I want all parents and all their associated children

**Comment by smitpatel** [comment]
@joehoeller - Please create a new issue with repro code.

**Comment by joehoeller** [comment]
This was the fix to my issue, add this to Startup.cs inside the **_public void ConfigureServices(IServiceCollection services)_** method:

```
services.AddMvc().AddJsonOptions(options => {
            options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
        });
```

**Related Articles on the above:**
1. https://benohead.com/c-circular-reference-detected-serializing-object/
2. http://stackoverflow.com/questions/39024354/asp-net-core-api-only-returning-first-result-of-list/39024972

***Note:** If you want to also be able to have your API ready for TCP/IP or MVC/Razor, do not use that and just use the `[JsonIgnore]` attribute, **which is actually a better practice than the above.**

1. http://www.newtonsoft.com/json/help/html/serializationattributes.htm#JsonIgnoreAttribute
2. http://stackoverflow.com/questions/10169648/how-to-exclude-property-from-json-serialization
