### ISSUE TITLE
Merge Tools.DotNet back into Tools

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#7022]
As far as I can tell, there is no need to have two packages.

NuGet appears to support multiple package types.
```XML
<packageTypes>
  <packageType type="Dependency" />
  <packageType type="DotnetCliTool" />
</packageTypes>
```

Unfortunately, the tool still needs to be under `lib\netcoreapp1.0` which means you'll get extra dependencies on that framework. However, we could probably make all our types internal and remove virtually all package dependencies.

**Comment by divega** [comment]
Consider keeping Tools.DotNet alive in some form (as meta-package or something that throws a helpful message?) for a while for compatibility, at least temporarily.

**Comment by bricelam** [comment]
Never mind. I've been lying to everyone. The documentation was vague and misleading.

> Package 'Microsoft.EntityFrameworkCore.Tools' has multiple package types, which is not supported.

cc @DamianEdwards @NTaylorMullen

**Comment by rowanmiller** [comment]
@bricelam anything left to do with this one?

**Comment by bricelam** [comment]
Nope. Won't fix.
