### ISSUE TITLE
migrationBuilder.DropIndex table param can't be null

### ISSUE THREAD

**Issue by arielcloud** [dotnet/efcore#7028]
I tried migrationBuilder.DropIndex("IX_XId_YId")

and got exception on update-database:
"System.ArgumentNullException: Value cannot be null.
Parameter name: name"

but it look like it's documentation allow it to be null. see attached picture
![2016-11-16_17h19_11](https://cloud.githubusercontent.com/assets/12379498/20352700/e283f1ca-ac20-11e6-806e-955aeb0d383d.png)

(version 1.0.1)

**Comment by ErikEJ** [comment]
Did you try 1.1 ?

**Comment by bricelam** [comment]
SQL Server requires the table to be specified, but other providers (like PostgreSQL) do not. Hence, the API allows `null`, but the SQL Server provider does not.

**Comment by bricelam** [comment]
To illustrate, Here is the DDL.
```SQL
-- SQL Server
DROP INDEX [IX_Person_Name] ON [Person];
-- (or)
ALTER TABLE [Person] DROP INDEX [IX_Person_Name];

-- PostgreSQL
DROP INDEX "IX_Person_Name";
```
