### ISSUE TITLE
How to set Column Description

### ISSUE THREAD

**Issue by matthewDDennis** [dotnet/efcore#7029]
I've read the docs, browsed the source and applied my Google and Bing Foo but can not determine
**How to set the description on a SQL column using EF Core Code First.**

Help!

**Comment by rowanmiller** [comment]
There is no native API to do it. You would need to use the `Sql(string)` method in a migration to set the description.

**Comment by NArnott** [comment]
Is there any plans to implement this? My boss just mandated that we start applying a description to every column we create from now on, and we are heavily using EF Core. I'd much rather be able to use Data Annotations to generate these than manual Sql(string) calls.

**Comment by ajcvickers** [comment]
@NArnott This is being tracked by #15037. It is likely also possible to flow your own annotations through to Migrations, but it's not super easy to do right now--see #10258.

**Comment by behzadhabibzadeh** [comment]
modelBuilder.Entity<MyEntity>()
    .Property(e => e.MyProperty)
    .HasComment("My Column Description");
