### ISSUE TITLE
Execution of Stored Procedure in EF Core for anonymous return type.

### ISSUE THREAD

**Issue by SateeshO** [dotnet/efcore#7032]
hello, 

i want to execute Stored Procedure in EF core for anonymous return type. Here i don't have the type of the result set.

this is the kind of syntax i am looking...
var  data= dbContext.Set().FromSql("execute sp_getAllDynamicData")

EF Core version: 1.0.0 
Operating system: Windows 7
Visual Studio version: VS 2015

Whether this is avaiable in any other updated Version.

Thanks

**Comment by divega** [comment]
@SateeshO that is still not supported in EF Core. The feature is tracked as #1862, so closing this issue as a duplicate.
