### ISSUE TITLE
DbSet.Find support for Eager Loading

### ISSUE THREAD

**Issue by gerardog** [dotnet/efcore#7042]
Is eager loading supported when you use the DbSet.Find method introduced on 1.1.0 ?

On 1.0.0, I used to do:

var myBlog = await context.Blogs
        .Include(blog => blog.Posts)
        .FirstOrDefaultAsync(b => b.Id == someId);

On 1.1.0 I was hoping to use the new Find method, but it is not supported on the IIncludableQueryable<> interface, which means the following code does not compile: 

var myBlog = await context.Blogs
        .Include(blog => blog.Posts)
        .FindAsync(someId);

**Comment by ajcvickers** [comment]
Dupe of #6935
