### ISSUE TITLE
Error when Upgrading Existing ASP.NET Core 1.0  to ASP.NET Core 1.1

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#7052]
### Steps to reproduce
Following this official [.NET Core 1.1 article](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/) we upgraded our existing ASP.NET Core 1.0 project to ASP.NET Core 1.1 as follows.

1. In project.json:
Updated the netcoreapp1.0 target framework to netcoreapp1.1.
Updated the Microsoft.NETCore.App package version from 1.0.0 to 1.1.0.

2.  Following this Official EF Blog, we ran the following commands to upgrade to EF Core 1.1:
Update-Package Microsoft.EntityFrameworkCore.SqlServer
Update-Package Microsoft.EntityFrameworkCore.Tools -Pre

### The issue
When compiling the application we got the following error:
Assembly 'Microsoft.EntityFrameworkCore.Relational' with identity 'Microsoft.EntityFrameworkCore.Relational, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.EntityFrameworkCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.EntityFrameworkCore' with identity 'Microsoft.EntityFrameworkCore, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	 C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets
```
Exception message:
Stack trace:
```

### Further technical details

EF Core version: Upgraded from EF Core 1.0 to 1.1
Operating system: Windows 10
Visual Studio version: VS2015-Update 3 (with latest patches)
Other details about my project setup: ASP.NET Core Web Application (.NET Core) project using SQL Server 2012.

**NOTE**:
By mistake, when upgrading EF to 1.1, we had run the `Update-Package Microsoft.EntityFrameworkCore.Relational` command that (as it should) did not run and gave us a warning since we are not using any third party database provider. But the above error should not have anything to this mistakenly run command since it did not run anyway - unless it did something internally and then aborted before giving us a warning

**Comment by divega** [comment]
@saf-itpro could you provide your project.json file so we can look at other possible outdated references?

**Comment by saf-itpro** [comment]
@divega After seeing your request I looked at the project.json file and corrected some values. The error was gone. Now, the app compiles fine but when I run the app I get the error shown in another issue I posted [here](https://github.com/aspnet/EntityFramework/issues/7058)
