### ISSUE TITLE
Entity Framework Tools not working after update to EF Core 1.1.0

### ISSUE THREAD

**Issue by Thaoden** [dotnet/efcore#7053]
### Steps to reproduce
Update .NET Core packages (including ASP.NET Core and EF Core) in solution from 1.0.0 to 1.1.0.

Update package `"Microsoft.EntityFrameworkCore.Tools" : "1.0.0-preview2-final"` to `"Microsoft.EntityFrameworkCore.Tools" : "1.1.0-preview4-final"`. Alternatively, change to package `"Microsoft.EntityFrameworkCore.Tools.DotNet" : "1.1.0-preview4-final"` as per [the anncouncement](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/).

### The issue

When using the `Microsoft.EntityFrameworkCore.Tools` package and trying to invoke any `dotnet ef` command on the console, the error message is thrown:
> No executable found matching command "dotnet-ef".

When using the `Microsoft.EntityFrameworkCore.Tools` package and trying to invoke any entity framework tooling command on the Package Manager Console, the same error is thrown:
> PM> add-migration Test
No executable found matching command "dotnet-ef"

When trying to install the package `Microsoft.EntityFrameworkCore.Tools.DotNet` via Package Manager Console, the following error message is thrown:
> install-package : Package 'Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4-final' uses features that are not supported by the current version of NuGet. To upgrade NuGet, see http://docs.nuget.org/consume/installing-nuget.

When trying to install the package `Microsoft.EntityFrameworkCore.Tools.DotNet` via `project.json`, the following error is logged to the Output window:
> Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4-final is not compatible with net461 (.NETFramework,Version=v4.6.1). Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4-final supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
> One or more packages are incompatible with .NETFramework,Version=v4.6.1.

### Further technical details

EF Core version: 1.1.0
Operating system: Win10
Visual Studio version: VS 2015 Update 3

Other details about my project setup:
> PM> dotnet --version
1.0.0-preview2-1-003177

I have an ASP.NET Core application targeting the full .NET framework. Thus I need the `net461` entry in the `frameworks` section of `project.json`.

**Comment by SaucyJack** [comment]
I am having similar issues running add-migration from package manager console.  I have updated Tools to 1.1.0-preview4-final.

> PM> add-migration Test
> Cannot execute this command because the version of Microsoft.EntityFrameworkCore.Design installed is not compatible with this tool.
> 

I have this in my dependencies:

`"Microsoft.EntityFrameworkCore.Design": "1.1.0"`

**Comment by jjassobarba** [comment]
I haven't been able to use the 1.1.0 version,  I had to use:

`"Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final"`

So I have all my entityframework dependencies with 1.1.0 version except the tools and the design dll.  That's the only way I made it work.

**Comment by divega** [comment]
We believe updating to the latest NuGet Visual Studio Extension from http://docs.nuget.org/consume/installing-nuget should help.

**Comment by SaucyJack** [comment]
Did not work, unless I don't have the latest extension:

`Package Manager Console Host Version 3.5.0.1996`

**Comment by AndriySvyryd** [comment]
@SaucyJack That was a suggestion for @Thaoden. Could you open a new issue with the full contents of your project.json?

**Comment by solenovex** [comment]
I'm using the command line, I have the same issue. 
After Installing .netcore 1.1 and Uninstalling .netcore 1.0 Then I upgrade the eftools("Microsoft.EntityFrameworkCore.Tools") to version "1.1.0-preview4-final".
When I run "dotnet ef xxx", it shows "No executable found matching command "dotnet-ef".

**Comment by AndriySvyryd** [comment]
@solenovex You also need to upgrade "Microsoft.EntityFrameworkCore.Tools.DotNet" to "1.1.0-preview4-final" in the tools section

**Comment by solenovex** [comment]
@AndriySvyryd I did upgrade "Microsoft.EntityFrameworkCore.Tools.DotNet" to "1.1.0-preview4-final" in the tools section
`
{
  "userSecretsId": "aspnet-Heavy.Web-4a2adfa9-ab06-4b00-ac2d-d952bafe9a83",

  "dependencies": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "AutoMapper": "5.1.1",
    "Heavy.Abstract": "1.0.0-*",
    "Heavy.Models": "1.0.0-*",
    "Heavy.Repository": "1.0.0-*",
    "Heavy.ViewModels": "1.0.0-*",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.0.0-preview2-update1",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.0.0-preview2-update1",
    "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.2",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0"  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`
and the cli still shows: 

> D:\Projects\dotnetcore\Heavy.Ltd\Heavy.Web>dotnet ef
> No executable found matching command "dotnet-ef"

**Comment by AndriySvyryd** [comment]
@solenovex No, you placed "Microsoft.EntityFrameworkCore.Tools" under tools, it needs to be "Microsoft.EntityFrameworkCore.Tools.DotNet"

**Comment by solenovex** [comment]
@AndriySvyryd  sorry about that, I wasn't look carefully, I changed it to "Microsoft.EntityFrameworkCore.Tools.DotNet", and "dotnet ef xxx" works now.
Thank you very much.

**Comment by MikaelGRA** [comment]
I think I have roughly the same issue:

I have a ASP.NET Core project that runs ONLY on the Full .NET Framework 4.6.1 (not .NET Core).

However, I cannot make the tooling work after upgrading to 1.1 (Using the Package Manager only).

My DbContext is located in a library project that is referenced by the main web project.

I have tried with:
"Microsoft.EntityFrameworkCore.Tools":
 -> When I use this, I am simply told the following: Could not find assembly 'C:\path\to\solution\ProjectName\.\bin\Debug\net461\win7-x64\ProjectWithContextName.exe'.

"Microsoft.EntityFrameworkCore.Tools.DotNet":
 -> This simply does not target the full .NET, so I cannot use it.

I have also tried updating to the latest nuget package manager. This does not solve the problem.

If I set the 'Default project' to my main web project in the Package Manager Console and attempt to execute the command, I am told: No DbContext named 'ApplicationDbContext' was found.

So I think the tooling can at the very least be found.

**Comment by smitpatel** [comment]
@MikaelGRA 
>"Microsoft.EntityFrameworkCore.Tools":
-> When I use this, I am simply told the following: Could not find assembly 'C:\path\to\solution\ProjectName.\bin\Debug\net461\win7-x64\ProjectWithContextName.exe'.

You need to set your web project as start-up project. After which you may hit this issue.

>If I set the 'Default project' to my main web project in the Package Manager Console and attempt to execute the command, I am told: No DbContext named 'ApplicationDbContext' was found.

Try using `optionsBuilder.MigrationsAssembly()` with assembly name of your class library. This will be done in the web project where you are calling `AddDbContext` method.


> "Microsoft.EntityFrameworkCore.Tools.DotNet":
-> This simply does not target the full .NET, so I cannot use it.

This package should be listed under tools section rather than dependencies. Once you modify project.json and restore packages, you should be able to use `dotnet ef` from the location where `project.json`.

**Comment by MikaelGRA** [comment]
@smitpatel 

> You need to set your web project as start-up project. After which you may hit this issue.

I know. Been using EF for serveral years now. :)

> Try using optionsBuilder.MigrationsAssembly() with assembly name of your class library. This will be done in the web project where you are calling AddDbContext method.

Correct me if I am wrong, but is that not ONLY if you want to have your DbContext in a different assembly from the migration classes? I know about this method and have been using it in a different project, but in this project, the DbContext and migration classes are in the same assembly (but a library project).

> This package should be listed under tools section rather than dependencies. Once you modify project.json and restore packages, you should be able to use dotnet ef from the location where project.json.

I feel like I've tried every combination of having specified "Microsoft.EntityFrameworkCore.Tools" and "Microsoft.EntityFrameworkCore.Tools.DotNet" in both the tools and the dependencies section. Frankly, it's very confusing, and the announcement post does not do a very good job of explaining it.

What I have right now is (working, old version):

project json for main web project:

```json
   "dependencies": {
      "Microsoft.EntityFrameworkCore.Tools": {
         "version": "1.0.0-preview2-final",
         "type": "build"
      }
   },

   "tools": {
      "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
   },

   "frameworks": {
      "net461": {

      }
   },
```

And in addition I am also specifying the "tool" in my project with my DbContext. This works with the old version. However, if I change all versions from "1.0.0-preview2-final" to "1.1.0-preview4-final" (in addition to updating all other required references), it does not work. And it also wont work if I change "Microsoft.EntityFrameworkCore.Tools" in the tools section to "Microsoft.EntityFrameworkCore.Tools.DotNet" (while not changing the dependency).

Tell me this though: Is there a difference between using the command line with the 'dotnet ef' commands and simply using the Package Manager Console. I have ONLY been using the Package Manager Console.

**Comment by smitpatel** [comment]
@MikaelGRA - I am not able to reproduce your issue. Can you share more details about your project setup?

I tried following steps:
1. Create new Asp.net web app using individual accounts.
2. Change the target framework to use net461.
3. Add new class lib to same solution and move model & migrations to class library. Add appropriate packages in class lib and reference it from web project.
Make sure everything builds correctly.
4. If you try to add migration it will throw error about migrations assembly. Add that code in your startup project. Since web project is the target project, your migrations assembly is the web project assembly. 
After above update, migrations works fine. If you want to put your new migrations in class lib then output-dir flag helps.

Now upgrade all packages for 1.1 release. Make correction for `UserSecrets` breaking change. Migrations work fine using PMC commands.

Using `dotnet ef` hits the issue #7071 

> Correct me if I am wrong, but is that not ONLY if you want to have your DbContext in a different assembly from the migration classes? I know about this method and have been using it in a different project, but in this project, the DbContext and migration classes are in the same assembly (but a library project).
Even I found this method to be somewhat confusing. Your target project is the project containing migration assembly since migrations will be added there. Hence if you have db context in different project, you need to add code in web project to specify migrations assembly as web project.

> Tell me this though: Is there a difference between using the command line with the 'dotnet ef' commands and simply using the Package Manager Console. I have ONLY been using the Package Manager Console.
There is no difference in final output. PMC commands calls `dotnet ef` under the hood.

**Comment by MikaelGRA** [comment]
@smitpatel 

Thank you very much for your help, but I am still at a loss.

I have successfully reproduced the error I am experiencing in a unrelated project, right here:

https://github.com/MikaelGRA/Whatever

In this project, I have moved the DbContext/Model to a different project and deleted the migration that comes with the template.

When I used the old version of EF Core, I was able to:
 -> Set 'Whatever' as Startup project
 -> Set 'Whatever.Data' as default project in the Package Manager Console.
 -> Run Add-Migration Initial

This would add a new migration to the 'Whatever.Data' project, however, with the new version, all I am getting is:

Could not find assembly 'C:\WorkGit\Whatever\src\Whatever\\.\bin\Debug\net461\win7-x64\Whatever.Data.exe'.

I have tried using both tools:
 -> "Microsoft.EntityFrameworkCore.Tools"
 -> "Microsoft.EntityFrameworkCore.Tools.DotNet"

But both gives the exact same error.

Could you tell me what I am doing wrong, because I am apparently completely clueless.

NOTE: I am not quite sure what to make of your 'step 4' in your last comment, but I have also tried to set the migrations assembly.

**Comment by smitpatel** [comment]
@MikaelGRA - Thanks for Whatever 😉 

I cloned the repo. Opened solution in VS. Following is the output from PMC afterwards.
```
PM> dotnet restore
log  : Restoring packages for D:\Whatever\src\Whatever.Data\project.json...
log  : Restoring packages for D:\Whatever\src\Whatever\project.json...
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in D:\Whatever\src\Whatever.Data\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in D:\Whatever\src\Whatever\project.json...
log  : Writing lock file to disk. Path: D:\Whatever\src\Whatever.Data\project.lock.json
log  : D:\Whatever\src\Whatever.Data\project.json
log  : Restore completed in 2804ms.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in D:\Whatever\src\Whatever\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in D:\Whatever\src\Whatever\project.json...
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in D:\Whatever\src\Whatever\project.json...
log  : Restoring packages for tool 'Microsoft.Extensions.SecretManager.Tools' in D:\Whatever\src\Whatever\project.json...
log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' in D:\Whatever\src\Whatever\project.json...
log  : Writing lock file to disk. Path: D:\Whatever\src\Whatever\project.lock.json
log  : D:\Whatever\src\Whatever\project.json
log  : Restore completed in 10719ms.
PM> Add-Migration Test
Your target project 'Whatever' doesn't match your migrations assembly 'Whatever.Data'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Whatever")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
PM> Add-Migration Test
To undo this action, use Remove-Migration.
PM> 
```
Due the first error the only code I had to modify was
```c#
services.AddDbContext<ApplicationDbContext>( options =>
        options.UseSqlServer( 
        Configuration.GetConnectionString( "DefaultConnection" ), b => b.MigrationsAssembly("Whatever")
        //, sql => sql.MigrationsAssembly( migrationAssembly )  // Do not believe this is required...
        ) );
```

**Comment by MikaelGRA** [comment]
@smitpatel 

Hehe :)

Now that you mention it. It does seem to work if I:
 -> Set migration assembly to the 'web project'
 -> Set startup project to the 'web project'
 -> Set default project to the 'web project'
 -> Run Add-Migration Initial

Now, this adds a migration. Hurray. 👍  (even though the DbContext is NOT actually located in the web project)

However, It does not add it to the project where I really want it (Whatever.Data), and to me it seems like EF Core 1.1 is actually unable to  generate the migration in that library project rather than the web project. EF Core 1.0 could do this without problems. So this seems a bit broken to me.

However, with this, I am actually able to generate my migrations again. 

So I guess my workaround for now is to simply change the migration assembly when I need to change my database and move around the generated migration classes afterwards, so they are stored in the correct library.

Thanks.

**Comment by smitpatel** [comment]
@MikaelGRA - We understand this is not best user experience at present. Tooling is going through a lot of changes and still in pre-release. It would have much better user experience by the time it RTM :)

**Comment by luisgoncalves** [comment]
I'm running into a different (but related) problem after updating to 1.1.0.

**project.json**

````
"dependencies": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Design": {
      "type": "build",
      "version": "1.1.0"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "type": "build",
      "version": "1.1.0-preview4-final"
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },
````

When I run `dotnet ef database update` I get the following error: `Unrecognized option '--config'`.

Can you help?

**Comment by Thaoden** [comment]
@divega Sorry for the delay, I was out of office for a few days. Downloading the current NuGet .vsix helped in downloading the `"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"` package. However, when running `dotnet ef --help` in the console, I get the same error as @luisgoncalves above:

> PS E:\VSProjects\MyProject> dotnet ef --help
Project MyProjectDependency (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation.
Project MyProject (.NETFramework,Version=v4.6.1) was previously compiled. Skipping compilation.
Specify --help for a list of available options and commands.
Unrecognized option '--config'

In the package manager console, when trying to add a migration, I get an error indicating my `project.json` file has a syntax error, although I can't find any:

> PM> add-migration test
Invalid object passed in, ':' or '}' expected. (305): {
(content of project.json)

Any ideas?

**Comment by maxmalmgren** [comment]
I also experience the error that @Thaoden and @luisgoncalves get when calling *dotnet ef*:

*Unrecognized option '--config'*

I have upgraded from ASP.Net 5 RC1 to ASP.Net Core 1.1.0.

Any further info?

**Comment by maxmalmgren** [comment]
I've reproduced this with a completely new project, it works using netcoreapp1.1 but not with net46 or net451. These are the project.jsons, the topmost one works and the bottom one does not:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Design": {
      "version": "1.1.0",
      "type": "build"
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    }
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      }
    }
  }
}
```
Not working:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Design": {
      "version": "1.1.0",
      "type": "build"
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    }
  },

  "frameworks": {
    "net46": { }
  }
}
```
It seems like support for net46 is not complete?

**Comment by AndriySvyryd** [comment]
https://github.com/aspnet/EntityFramework/issues/7071 tracks the `Unrecognized option '--config'` issue

**Comment by jayslife** [comment]
Hello all,

My team was able to resolve this issue updating the project.json file in the migrations project.  We removed the following from dependencies:
,
    "Microsoft.EntityFrameworkCore.Tools": {
      "type": "build",
      "version": "1.1.0-preview4-final"
    }

We added the following to tools

"tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },

you are then able to run the following command to deploy from your migrations project using your web project.

dotnet ef --startup-project ..\<<Web Project>>\ migrations list

I hope this helps you guys as well.

Jason

**Comment by LucasArgate** [comment]
@jayslife i tried putting you code and look the error: 

> The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.1
  - Alternatively, install the framework version '1.1.0'.

look my project.json:

`"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.Extensions.Logging": "1.1.0.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
    
  },
`


do you know how can i resolve it ?

**Comment by AndriySvyryd** [comment]
@LucasArgate Install the 1.1.0 .NET Core SDK https://www.microsoft.com/net/download/core#/current

**Comment by webbkvalite** [comment]
After trying alot of combinations, this is what works with my framework:

 "dependencies": {
    "System.Net.Http": "4.3.0",
    "YeshuApp.Models": "1.0.0-*",
    "Microsoft.NETCore.App": "1.1.0",
    "Microsoft.ApplicationInsights": "2.2.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Newtonsoft.Json": "9.0.1",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final"
  },

**Comment by karim007** [comment]
@jayslife Thank you very much !

**Comment by Artur-A** [comment]
For me the next configuration works. I expected `Microsoft.EntityFrameworkCore.Design` to be in `tools` section, but it only works when it is in a usual `dependencies` section.

```
  "dependencies": {
     ...
     "Microsoft.EntityFrameworkCore.Design": "1.1.0-*"
  },

  "tools": {
     ...
     "Microsoft.EntityFrameworkCore.Tools": "1.1.0-*",
     "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-*"
  },
```

**Comment by rowanmiller** [comment]
@Artur-A `tools` is specifically for registering .NET CLI Tools, so only `Microsoft.EntityFrameworkCore.Tools.DotNet` should be in there. `Microsoft.EntityFrameworkCore.Design` and `Microsoft.EntityFrameworkCore.Tools` both go as regular dependencies.

**Comment by Artur-A** [comment]
@rowanmiller I see your point, thank you for the clarification.

[tools](https://docs.microsoft.com/en-gb/dotnet/articles/core/tools/project-json#tools)
_An object that defines package dependencies that are used as tools for the current project, not as references. Packages defined here are available in scripts that run during the build process, but they are not accessible to the code in the project itself. Tools can for example include code generators or post-build tools that perform tasks related to packing._

Missed the important section in the [EF Core 1.1 announcement](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/) that `Microsoft.EntityFrameworkCore.Tools` are replaced by `Microsoft.EntityFrameworkCore.Tools.DotNet` for `dotnet ef` cli, i.e. was moved to its own package.

Actually the next information was kind of misleading (outdated) https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro:
![project.json](http://i.imgur.com/Xsx3zNl.png)

**Comment by bricelam** [comment]
After 1.0.0-preview2-final, we split the package into two--the one that should be under dependencies (Microsoft.EntityFrameworkCore.Tools) and the one that should be under tools (Microsoft.EntityFrameworkCore.Tools.DotNet)

**Comment by anichin** [comment]
What about Visual Studio 2017? 

project.json is replaced with project.csproj

but dotnet ef is still looking for project.json

**Comment by bricelam** [comment]
@anichin Ensure you're using version 1.0.0 of `Microsoft.EntityFrameworkCore.Tools.DotNet`.

**Comment by mabbashm110** [comment]
`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0" },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "imports": "portable-net45+win8+dnxcore50",
      "version": "1.0.0-preview2-final"
    }
    },

    "frameworks": {
      "netcoreapp1.0": {
        "imports": [
          "dotnet5.6",
          "portable-net45+win8"
        ]
      }
    },

    "buildOptions": {
      "emitEntryPoint": true,
      "preserveCompilationContext": true
    },

    "runtimeOptions": {
      "configProperties": {
        "System.GC.Server": true
      }
    },

    "publishOptions": {
      "include": [
        "wwwroot",
        "web.config"
      ]
    },

    "scripts": {
      "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
  }
`

I am still getting the errors what is wrong with my json file?

**Comment by bricelam** [comment]
Here is the documentation on using the 1.0.0 version of `dotnet ef`: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

**Comment by ChuckSavage** [comment]
I'm not making an ASP.NET program, but was using EF Core. So all the mentions to project.json didn't help me. 

Via NuGet add 

> Microsoft.EntityFrameworkCore.Tools

It fixed it for me. I added a complete write up here on my answer to my question on StackOverflow - https://stackoverflow.com/a/44275218/353147
