### ISSUE TITLE
SqliteContainsOptimizedTranslator doesn't work when using wildcards

### ISSUE THREAD

**Issue by matgr1** [dotnet/efcore#7054]
### Steps to reproduce
run a query using string.Contains where the search pattern contains '%' or '_'

### The issue
it seems that since SqliteContainsOptimizedTranslator doesn't use LikeExpression and instead uses "instr" wildcards are not supported (at least not in sqlite...)

This wouldn't be a problem for me right now if #2850 were resolved since then I could explicitly use the like operator (in fact I'd prefer that), but I would think that .Contains should still handle wildcards

### Further technical details

EF Core version: 1.1.0
Operating system: Windows 10
Visual Studio version: VS 2015

Other details about my project setup:
Sqlite

**Comment by matgr1** [comment]
Also of note: instr appears to be case-sensitive while like is not

**Comment by maumar** [comment]
We made the change to Contains becasue the scenarios where one wanted to search for strings containing a wildcard (e.g. "75%") were giving unexpected results. Current translation better resembles CLR Contains method, which was our goal. I do agree that we need the ability to use Like and other SQL functions now more than before

**Comment by rowanmiller** [comment]
Using SQL functions is probably already covered by https://github.com/aspnet/EntityFramework/issues/2850

**Comment by matgr1** [comment]
That actually makes good sense to me that it should behave more like the CLR Contains methods, so I take back my comment that it should handle wildcards :)

However, as you mention this does make the case for resolving #2850 much stronger...

**Comment by matgr1** [comment]
in fact, why don't I just close this one...
