### ISSUE TITLE
Scaffolding Stops Working after 1.1.0 Update

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/efcore#7059]
### Steps to reproduce
Create a new project targeting .Net Framework 4.6.2 and Individual User Accounts
```
PM> Install-Package Microsoft.EntityFrameworkCore.SqlServer
PM> Install-Package Microsoft.EntityFrameworkCore.Tools –Pre
PM> Install-Package Microsoft.EntityFrameworkCore.Design
PM> Install-Package Microsoft.EntityFrameworkCore.SqlServer.Design
Add to Tools:
"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview4-final",
Reverse a database:
Scaffold-DbContext "Server=ZONAR;Database=TestDb;Integrated Security=true" Microsoft.EntityFrameworkCore.SqlServer -o Models

Right click in Solution Explorer Add>Controller
Select a MVC Controller with Views, and Add
Select a Model and Add 

Everything works fine, though some packages are out of date. So, update all packages.
PM> update-package

Right click in Solution Explorer Add>Controller
Select a MVC Controller with Views, and Add
Select a Model and Add

Scaffolding runs but no controller or views are created.
```

### Data
####project.json before update:
```json
{
  "userSecretsId": "aspnet-WebApplication3-cb3e53f3-787f-4e0c-af10-48031a8f9dcc",

  "dependencies": {
	"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
	"Microsoft.AspNetCore.Diagnostics": "1.0.0",
	"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
	"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
	"Microsoft.AspNetCore.Mvc": "1.0.1",
	"Microsoft.AspNetCore.Razor.Tools": {
	  "version": "1.0.0-preview2-final",
	  "type": "build"
	},
	"Microsoft.AspNetCore.Routing": "1.0.1",
	"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
	"Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
	"Microsoft.AspNetCore.StaticFiles": "1.0.0",
	"Microsoft.EntityFrameworkCore.Design": "1.1.0",
	"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
	"Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
	"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
	"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
	"Microsoft.Extensions.Configuration.Json": "1.0.0",
	"Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
	"Microsoft.Extensions.Logging": "1.0.0",
	"Microsoft.Extensions.Logging.Console": "1.0.0",
	"Microsoft.Extensions.Logging.Debug": "1.0.0",
	"Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
	"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
	"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
	  "version": "1.0.0-preview2-final",
	  "type": "build"
	},
	"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
	  "version": "1.0.0-preview2-final",
	  "type": "build"
	}
  },

	"tools": {
		"BundlerMinifier.Core": "2.0.238",
		"Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
		"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview4-final",
		"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
		"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
		"Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			"version": "1.0.0-preview2-final",
			"imports": [
				"portable-net45+win8"
			]
		}
	},

  "frameworks": {
	"net462": { }
  },

  "buildOptions": {
	"emitEntryPoint": true,
	"preserveCompilationContext": true
  },

  "publishOptions": {
	"include": [
	  "wwwroot",
	  "**/*.cshtml",
	  "appsettings.json",
	  "web.config"
	]
  },

  "scripts": {
	"prepublish": [ "bower install", "dotnet bundle" ],
	"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```
#### project.json after update
```json
 {
	"userSecretsId": "aspnet-WebApplication3-cb3e53f3-787f-4e0c-af10-48031a8f9dcc",

	"dependencies": {
		"BundlerMinifier.Core": "2.2.306",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
		"Microsoft.AspNetCore.Razor.Tools": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		},
		"Microsoft.AspNetCore.Routing": "1.1.0",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
		"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
		"Microsoft.AspNetCore.StaticFiles": "1.1.0",
		"Microsoft.EntityFrameworkCore.Design": "1.1.0",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
		"Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
		"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
		"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
		"Microsoft.Extensions.Configuration.Json": "1.1.0",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
		"Microsoft.Extensions.Logging": "1.1.0",
		"Microsoft.Extensions.Logging.Console": "1.1.0",
		"Microsoft.Extensions.Logging.Debug": "1.1.0",
		"Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
		"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		},
		"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		}
	},

	"tools": {
		"Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
		"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview4-final",
		"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
		"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
		"Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			"version": "1.0.0-preview2-final",
			"imports": [
				"portable-net45+win8"
			]
		}
	},

	"frameworks": {
		"net462": {}
	},

	"buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true
	},

	"publishOptions": {
		"include": [
			"wwwroot",
			"**/*.cshtml",
			"appsettings.json",
			"web.config"
		]
	},

	"scripts": {
		"prepublish": [ "bower install", "dotnet bundle" ],
		"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
	}
}
```
### 

### Further technical details

EF Core version: (found in project.json or packages.config)
Operating system: Windows 10
Visual Studio version: VS 2015

**Comment by smitpatel** [comment]
@RandyBuchholz - Packages under "tools" section are from previous release. Can you update them to 1.1 release (package versions are like 1.1.0-preview4-final) and try again?

**Comment by RandyBuchholz** [comment]
I ran PM> update-package Microsoft.AspNetCore.Razor.Tools -Pre 
and it brought in:
"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",

When I tried I got output in the Output window(below) but still not results. Before that there was no output in the output window.

C:\Program Files\dotnet\dotnet.exe aspnet-codegenerator --project "C:\Users\Randy\OneDrive\Food\WebApplication3\src\WebApplication3" controller --force --controllerName ClubRoleTypesController --model WebApplication3.Models.ClubRoleType --dataContext WebApplication3.Models.DinnerPartyContext --relativeFolderPath Controllers --controllerNamespace WebApplication3.Controllers --referenceScriptLibraries --useDefaultLayout
RunTime 00:00:03.48

project.json:
{
	"userSecretsId": "aspnet-WebApplication3-cb3e53f3-787f-4e0c-af10-48031a8f9dcc",

	"dependencies": {
		"BundlerMinifier.Core": "2.2.306",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
					"Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
					"Microsoft.AspNetCore.Routing": "1.1.0",
					"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
					"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
					"Microsoft.AspNetCore.StaticFiles": "1.1.0",
					"Microsoft.EntityFrameworkCore.Design": "1.1.0",
					"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
					"Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
					"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
					"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
					"Microsoft.Extensions.Configuration.Json": "1.1.0",
					"Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
					"Microsoft.Extensions.Logging": "1.1.0",
					"Microsoft.Extensions.Logging.Console": "1.1.0",
					"Microsoft.Extensions.Logging.Debug": "1.1.0",
					"Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
					"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
					"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
						"version": "1.0.0-preview2-final",
						"type": "build"
					},
		"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
			"version": "1.0.0-preview2-final",
			"type": "build"
		}
	},

	"tools": {
		"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
		"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
		"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
		"Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			"version": "1.0.0-preview2-final",
			"imports": [
				"portable-net45+win8"
			]
		}
	},

	"frameworks": {
		"net462": {}
	},

	"buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true
	},

	"publishOptions": {
		"include": [
			"wwwroot",
			"**/*.cshtml",
			"appsettings.json",
			"web.config"
		]
	},

	"scripts": {
		"prepublish": [ "bower install", "dotnet bundle" ],
		"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
	}
}

I tried updating the VS packages too (since they were the only dev things not at 1.1):
PM> update-package Microsoft.VisualStudio.Web.CodeGeneration.Tools -Pre
PM> update-package Microsoft.VisualStudio.Web.CodeGenerators.Mvc -Pre
This broke everything saying no code generator was found.

**Comment by smitpatel** [comment]
@RandyBuchholz - It is bug in scaffolding I filed https://github.com/aspnet/Scaffolding/issues/342.
There is also issue with update-package command, trying to generate repro to file an issue for that.
This is the upgraded project.json should look like
```json
{
  "userSecretsId": "aspnet-WebApplication2-dfba6f5d-a176-4b2f-9bd1-81c351bfb4d2",

  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    }
  },

  "tools": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "net452": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by dotnetnoobie** [comment]
@smitpatel if I use the above project.json file

with frameworks.

"**net461**": => no errors are shown, but there is **NO** files generated (no controller, no views)

"**net452**": => works, Controller and Views are generated 
"**net462**": => works, Controller and Views are generated

**Comment by bricelam** [comment]
@dotnetnoobie I'd recommend trying with the latest tools (See #7358 for details)

**Comment by m4ss1m0g** [comment]
I think this can be re-opened because as @dotnetnoobie says 

> net461": => no errors are shown, but there is NO files generated (no controller, no views)

**Comment by divega** [comment]
@m4ss1m0g @dotnetnoobie you are talking about ASP.NET Scaffolding, which is not an EF Core feature. 

At first glance I believe the issue @smitpatel created (https://github.com/aspnet/Scaffolding/issues/342) already covers what you are seeing. If it doesn't, consider creating a new issue at https://github.com/aspnet/Scaffolding/issues/.
