### ISSUE TITLE
Tooling not compatible with net46 projects?

### ISSUE THREAD

**Issue by mejje** [dotnet/efcore#7062]
When upgrading tooling to Microsoft.EntityFrameworkCore.Tools.DotNet 1.1, the nuget restore fails with net46 projects:

> error: Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4-final is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4-final supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
> error: One or more packages are incompatible with .NETFramework,Version=v4.6.
> 

project.json at http://hastebin.com/ohekihiqiy.json

**Comment by smitpatel** [comment]
>     "Microsoft.EntityFrameworkCore.Tools.DotNet": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    
This part should be under "tools" section rather than "dependencies".

**Comment by mejje** [comment]
Thank you, that fixed it. Maybe something left by the old templates or an upgrade I did wrong.
