### ISSUE TITLE
Cannot Reference ViewModel with EFCore in Contructor from UWP XAML

### ISSUE THREAD

**Issue by VagueGit** [dotnet/efcore#7069]
Create the EFGetStarted.UWP app with all prerequisites in accordance with [UWP - New Database](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)

Add a class MainPageViewModel.cs
```
    namespace EFGetStarted.UWP
    {
        public class MainPageViewModel
        {
            public MainPageViewModel()
            {
                using (var db = new BloggingContext())
                {
                }
            }
        }
    }

```
Add the following using directive to MainPage.xaml
`    xmlns:ViewModels="using:EFGetStarted.UWP"
`
and the following
```
    <Page.DataContext>
        <ViewModels:MainPageViewModel x:Name="MainPageViewModel" />
    </Page.DataContext>

```
In VS2015 Update 3there is a build error

> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.	EFGetStarted.UWP	

project.json
   ```
 {
        "dependencies": {
        "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
    },

```    "frameworks": {
        "uap10.0": {}
    },
    "runtimes": {
        "win10-arm": {},
        "win10-arm-aot": {},
        "win10-x86": {},
        "win10-x86-aot": {},
        "win10-x64": {},
        "win10-x64-aot": {}
        }
    }
```
App.config

```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.FileSystem.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0" newVersion="4.0.1.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Overlapped" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0" newVersion="4.0.1.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.ComponentModel.Annotations" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.1.0.0" newVersion="4.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Comment out the using statement and the code builds.
Or comment out

`<ViewModels:MainPageViewModel x:Name="MainPageViewModel" />`

and the code builds.

**Comment by rowanmiller** [comment]
Could you try explicitly listing `"Microsoft.EntityFrameworkCore": "1.1.0"` in your dependencies?

**Comment by VagueGit** [comment]
Thank you for the suggestion @rowanmiller but adding `Microsoft.EntityFrameworkCore": "1.1.0"` makes no difference. The same build error appears.

> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified. EFGetStarted.UWP

**Comment by rowanmiller** [comment]
Thanks for confirming, we'll get someone to dig into it. We've had an influx of issues with the 1.1 release, so it may take a little longer than usual.

**Comment by VagueGit** [comment]
The problem goes away if I set
```
    <Page.DataContext>
        <ViewModels:Blog />
    </Page.DataContext>

```

 I thought this might be due to `using Microsoft.EntityFrameworkCore;` in `Model.cs` so I added the same using to  `MainPageViewModel` but that didn't fix the problem.

**Comment by VagueGit** [comment]
I have moved MainPageViewModel into Model.cs
```
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace EFGetStarted.UWP
{
    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename=Blogging.db");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
    public class MainPageViewModel
    {
        public MainPageViewModel()
        {
            using (var db = new BloggingContext())
            {
            }
        }
    }
}
```
The error persists

> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified. EFGetStarted.UWP

**Comment by rowanmiller** [comment]
Note for triage: I had thought that avoiding EF code during design time might fix the issue, but it does not...

```c#
public class MainPageViewModel
{
    public MainPageViewModel()
    {
        if (!DesignMode.DesignModeEnabled)
        {
            using (var db = new BloggingContext())
            {
            }
        }
    }
}
```

**Comment by rowanmiller** [comment]
I have reached out to the UWP team to get some guidance on this one.

**Comment by rowanmiller** [comment]
@VagueGit I just wanted to confirm that you are just seeing this show up as "blue squigglys" in the editor and that the project builds and runs fine (that is what I see).

**Comment by blackbelt080** [comment]
Will this work with Wp blog posts?

**Comment by blackbelt080** [comment]
I'd like to rewrite this using Mysql

**Comment by rowanmiller** [comment]
@blackbelt080 are your comments related to the specific issue being discussed here? If so, can you provide some more explanation. If not, please open a new issue and include specific technical details of what you are trying to do.

**Comment by VagueGit** [comment]
@rowanmiller Build succeeds and the app runs. There is a blue squiggly and in the error list I see 1 error `Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.	Project EFGetStarted.UWP	C:\...\EFGetStarted.UWP\EFGetStarted.UWP\MainPage.xaml	Line13	

Line 13 is `<ViewModels:MainPageViewModel />`
`

**Comment by rowanmiller** [comment]
Thanks for confirming, the UWP team is going to investigate. 

In the meantime, it’s a big hammer, but this button stops the XAML Designer from running your code at all.

![image](https://cloud.githubusercontent.com/assets/4741851/21026876/6d18e51a-bd43-11e6-8200-49ea3db23734.jpg)

**Comment by VagueGit** [comment]
@rowanmiller This issue seems to have gone away today when I installed the latest update to EfCore.SQLite 1.1.0 through Nuget Package Manager, which is pretty weird in itself in that I thought I was keeping everything uptodate and I thought I installed EfCore 1.1.0 when it was released a couple of weeks ago. Whatever ... it seems to have gone now. Thank you for your attention.

**Comment by rowanmiller** [comment]
I still see the issue with the latest dependencies:

```json
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  },
```

I'm going to close this issue out, as it is not an EF issue, but I have passed it off to the UWP folks to dig into.

**Comment by Andrew-By** [comment]
Just to add up to that. I get an error only on x86 configuration, which is required for Design Data to work.

**Comment by ryanwinter** [comment]
@Andrew-By 's workaround is good for me too.
