### ISSUE TITLE
FromSql: How to execute a singleton query without composition?

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#7098]
Consider this query:
```c#
context.World.FromSql("SELECT id, randomnumber FROM world WHERE Id = {0}", id).First();
```
We should consider adding some way of suppressing composition here.

**Comment by rowanmiller** [comment]
We will start by looking at patterns that do not involve a first class API in EF for this scenario

**Comment by ajcvickers** [comment]
Closing for now. We will consider it in the future if there is a lot of interest or significant scenarios that would be much better with it.
