### ISSUE TITLE
Support another Entity as a Key

### ISSUE THREAD

**Issue by Sohra** [dotnet/efcore#7107]
_(This is a feature request, the guidelines said to log them here)_

When declaring an entity A as a key in another entity B, Entity Framework could lookup the key for that entity (A), and use it as the key for this entity (B) too. This keeps the model classes in .NET "clean" in the sense they don't need to duplicate they key field. E.g.

```
class A { 
 string Key { get; set; } 
}

class B { 
 A Key { get; set; } 
 //Not required, since A has a key defined on it already, and our key is of type A 
 //string KeyWhenPersistedToARelationalDatabase { get; set; } 
}
```
This mapping could be setup with a call to ```modelBuilder.Entity<B>().Key(e => e.Key)``` to map to the SQL tables: 
```
As ([Key] string NOT NULL PRIMARY KEY) 
Bs ([Key] string NOT NULL PRIMARY KEY, FOREIGN KEY (Key) REFERENCES As(Key))
```

When querying B entities by key (an object of type A), the Key field of A would be used to lookup both the rest of the fields for B, in the Bs table, and the rest of the fields for the A key in the As table.
It would be implicit that the key entity A be included whenever creating instances of type B.  There would be no need to explicitly write .Include(b => b.Key).

I hope this request is clear enough and is of merit to more than just me (:  I am loath to pollute my entities just to reflect the relational database backing them.

**Comment by Sohra** [comment]
In the meantime I've been trying to use shadow properties to accomplish "not polluting my entities" but I've been having a little trouble getting things working just how I want it (my class model has generic classes, and also subclasses that have more complex keys than their base class).  It seems rather complicated to get EF working nicely with polymorphic entities.

**Comment by rowanmiller** [comment]
Here is an example of it working with a shadow property. In this example, BlogPhoto uses the PK of the Blog it belongs to.

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Demo
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Blogs.Add(new Blog
                {
                    Url = "test",
                    Photo = new BlogPhoto()
                });
                db.SaveChanges();
            }
        }
    }

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogPhoto> BlogPhotos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Demo;Trusted_Connection=True;ConnectRetryCount=0;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BlogPhoto>()
                .Property<int>("BlogId");

            modelBuilder.Entity<BlogPhoto>()
                .HasKey("BlogId");

            modelBuilder.Entity<BlogPhoto>()
                .HasOne(p => p.Blog)
                .WithOne(b => b.Photo)
                .HasForeignKey(typeof(BlogPhoto).FullName, "BlogId");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public BlogPhoto Photo { get; set; }
    }

    public class BlogPhoto
    {
        public Blog Blog { get; set; }
        public byte[] Photo { get; set; }
    }
}
```

**Comment by rowanmiller** [comment]
BTW that example works on 1.0. In 1.1 we introduced a new overload of `HasForeignKey` which looks a little nicer...

```c#
            modelBuilder.Entity<BlogPhoto>()
                .HasOne(p => p.Blog)
                .WithOne(b => b.Photo)
                .HasForeignKey<BlogPhoto>("BlogId");
```

**Comment by rowanmiller** [comment]
My recommendation for triage... the code shown in the example seems pretty reasonable. If we see a lot of folks wanting to do this, we could look at more of a "sugar" pattern in the fluent API, but at this stage I don't think we have that level of feedback and I suspect it won't be super common.
