### ISSUE TITLE
Migration difference on Delete: No Foreign Key Property generating a Shadow Property vs Fully Defined Relationships

### ISSUE THREAD

**Issue by Ponant** [dotnet/efcore#7110]
Is the following a bug or per design? In case of a design constraint, it will be great to have an explanation and perhaps update the documentation on why there is a difference between FK set as Shadow Properties instead of declared in a CLR class when it comes to deletion.

Here are the articles that I followed 
[No Foreign Key Property vs Fully Defined Relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships )
[Shadow Properties](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties)
[Cascade Delete](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
[video uploaded on Aug 2015](https://channel9.msdn.com/Blogs/Seth-Juarez/Shadow-Properties-in-Entity-Framework-7)

The last link is a 1 year old video and I wonder if the scope of shadow properties has changed since then. In particular, at 6.30 min Seth asks the question if adding a shadow property and doing migrations would change anything and Rowan answers that it does nothing to the migrations pipeline and that it behaves exactly the same, as if this was defined on a CLR class. However, the code generated by the migration in .Net Core 1.1 is different when it comes to delete operations. Hence my question on whether this is per design or a bug.

### The issue
**Without Shadow Property using EF conventions (Fully Defined Relationships)**
```
public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
```
`add-migration init`

This gives as a constraint in xxx.init.cs
`                        onDelete: ReferentialAction.Cascade;`

I can then query, remove and save like this
```
var blog = db.Blogs.Find(id);
db.Remove(blog);
var count = db.SaveChanges();
```
or like that

```
var blog = db.Blogs.Find(id);
var blog = db.Blogs.Include(b => b.Posts)
.FirstOrDefault(b => b.BlogId == id);
db.Remove(blog);
var count = db.SaveChanges();
```
**With Shadow Property (No Foreign Key Property)**
```
public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public Blog Blog { get; set; }
    }
```
`add-migration init`

This gives a different constraint in xxx.init.cs
`                        onDelete: ReferentialAction.Restrict;`

This will not be an issue if I query with an Include,  remove a blog and save, but will throw an error if I do not use `.Include`, with an error 
The DELETE statement conflicted with the REFERENCE constraint "FK_Posts_Blogs_BlogId".

Switching  
`onDelete: ReferentialAction.Restrict`

to
`onDelete: ReferentialAction.Cascade`

will make it work again. Alternatively, I would have had to delete all posts before deleting the blog.

Even though I can see some sort of coherence in the essence of a shadow property, I still do not understand why the delete constraint has been set to onDelete: ReferentialAction.Restrict.

### Further technical details

EF Core version: .Net Core 1.1
Operating system: W10
Visual Studio version: VS 2017 RC

**Comment by ajcvickers** [comment]
@Ponant By convention, EF configures cascade deletes for required relationships. This is because in a required relationship the child entity cannot exist without a parent. A relationship is required if the FK is not nullable, because this means that the FK must always be set to reference some parent.

For optional relationships EF does not configure cascade deletes. A relationship is optional if the FK is nullable. This means that if the parent is deleted, then the children do not need to be deleted because they can exist without a parent by having their FK values set to null.

In your example, the mapped FK is non-nullable, so the relationship is required, and cascade delete is configured. When EF creates an FK in shadow state the default for that FK is to make it nullable. So in the second case above the relationship is optional and no cascade delete is configured.

You can make the relationship required by configuring the FK property explicitly as a non-nullable type: 
```C#
modelBuilder.Entity<Post>()
    .Property<int>("BlogId");
```
or by configuring the relationship as required: 
```C#
modelBuilder.Entity<Post>()
    .HasOne(e => e.Blog)
    .WithMany(e => e.Posts)
    .IsRequired();
```

Or, of you want the relationship to be optional but have cascade deletes, then you can explicitly switch on cascade deletes for the relationship:
```C#
modelBuilder.Entity<Post>()
    .HasOne(e => e.Blog)
    .WithMany(e => e.Posts)
    .OnDelete(DeleteBehavior.Cascade);
```

**Comment by Ponant** [comment]
@ajcvickers, thanks for the answut I lack a response to the question:
"When EF creates an FK in shadow state the default for that FK is to make it nullable": Why this default has been chosen?

Other than that, is there an equivalence between a "FK cannot be null" and a "required relation"? Said differently, does the definition of a required relation is uniquely defined by a FK which cannot be null? To me, a required relation is a relation which has a cascade delete. Thanks

**Comment by ajcvickers** [comment]
@Ponant It is the default because it is the most permissive option and because it is less likely to cause unexpected data loss. Required is defined by the nullability of the FK.

**Comment by rowanmiller** [comment]
Perhaps another way to word the same information will help

> If we find a foreign key property, then we use the nullability of that to work out whether the relationship is required or optional (i.e. `int`, `Guid`, etc. can not be null, so the relationship is required, `string`, `int?`, etc. can hold null, so the relationship is optional). If we don't find a foreign key property (and therefore do not have that hint), then we make relationships optional by default.

**Comment by Ponant** [comment]
@ajcvickers @rowanmiller I think your comments clarify the point (optional by default -->nullable if nothing is obvious to EF is a key point which I overlooked). I understand that this is somewhat in the documentation as I went through it, but perhaps one could improve it a bit by adding such explanations and definitions. By being a non-expert in .Net I cannot offer much pulls at the moment, but I can help in readproffing (the evil's advocate). I wrote many (scientific) papers, so I have experience in making a documentation clear and pedagogical.

**Comment by rowanmiller** [comment]
@Ponant yep absolutely. Where would it have been most helpful/obvious for you to see this documented? Here https://docs.microsoft.com/en-us/ef/core/modeling/relationships#conventions?

**Comment by Ponant** [comment]
@rowanmiller will get back tomorrow as it is late here. I skimmed in the last hour the doc and actually realized that sections on conventions are scattered everywhere. So, for instance, for our case the url you propose would cover a piece of the answer, while this one [https://docs.microsoft.com/en-us/ef/core/modeling/required-optional](https://docs.microsoft.com/en-us/ef/core/modeling/required-optional) would cover the rest.

This brings me think that a section named Convention in the toc.md with a list of all conventions plus examples for overriding them would be best. Then, in the subsections relationships and required/optional, etc, you would have the already existing short info on conventions as a concise reminder. Incidentally, there is no convention section in the toc.md.
Also, let me know how you want to proceed, I do not mind editing via pulls but this is at the price of writing something that may be inaccurate, if not wrong in some places.

**Comment by rowanmiller** [comment]
Yeah we don't really group by `Conventions`, `Data Annotations`, `Fluent API`. That's how we did it in the EF6.x docs, but it was super hard to find what you were after. Now we group by the modeling concept (column mapping, data types, etc.). And then we have a section that describes the conventions for each of those topics (and how to override it etc.). 

I agree the relationships one is a little confusing, I need to think  about how to break it up better (I think it's too big for one page). I see your point about required/options too... that topic is just about scalar properties, so I'll add a note that it's not a bout relationships.. and link off to the appropriate part of the relationships doc.

**Comment by Ponant** [comment]
@rowanmiller There is a search box on the left side; one would expect to type "convention"(s) and find a result. The search box on the right side searches throughout Microsoft.

I think the length is fine because you cover many cases and go to the point, which is what the user will be looking for. Perhaps the following structure might be better? You would start with a drop-down list as with the section "Relational Database Modeling" and set a tree structure with the focus on one-to-many, one-to-one etc. In this way, if I want to set a many-to-many relation then I will find everything by clicking on a many-to-many link. We can start by reordering the one-to-many since you did it already and do the rest after.
Models
***Definition of Terms
***Conventions, Annotationsa dn Fluent API (includes the first and small paragraph on cascade delete and brief description of annotations vs fluent api vs convention)
***One-to-many 
--------Fully Defined Relationships
-------- No Foreign Key Property
--------Single Navigation Property
--------Data Annotations
----------Foreign Key
----------InverseProperty
--------Fluent API
----------Single Navigation Property
----------Foreign Key
----------Principal Key
----------Required
----------Cascade Delete
----------Other relationships (Remove)

***One-to-One
   same structure as  one-to-one (even if a lot will be empty for the moment)
***Many-To-Many
   same struct as one-to-one

**Comment by Ponant** [comment]
@rowanmiller @ajcvickers following the original discussion I just saw that the doc says (relationships)
"Cascade Delete
By convention, cascade delete will be set to Cascade for required relationships and SetNull for optional relationships. Cascade means dependent entities are also deleted. SetNull means that foreign key properties in dependent entities are set to null."

But in our case of a shadow property it is set to Restrict and not SetNull.

**Comment by ajcvickers** [comment]
@Ponant This is a docs bug tracked by #6398

**Comment by Ponant** [comment]
Hi @ajcvickers thanks for the link, and let me say that it seems to explain why I have been struggling over the weekend. I would really appreciate your feedback, I could not solve a problem and your comments in the issue you just mention got me somewhat confused.
My model is however quite common, so that I cannot believe this is a SQL Server issue (but rather mine).

```
//Mimic ASP.Net Identity (with ID set to int instead of string)
    public class IdentityUser
    {
        public int ID { get; set; }
        public string Username { get; set; }
    }

```
```
    public class ApplicationUser : IdentityUser
    {
        public string Country { get; set; }
        public List<Article> Articles { get; set; }
        public List<Comment> Comments { get; set; }
    }
```
```
public class Article
    {
        public int ArticleID { get; set; }
        public string Title { get; set; }

        public int UserID { get; set; }
        public ApplicationUser User { get; set; }

        public List<Comment> Comments { get; set; }
    }
```
```
    public class Comment
    {
        public int CommentID { get; set; }
        public string CommentContent { get; set; }

        public int? ArticleID { get; set; }

        public int UserID { get; set; }
        public ApplicationUser User { get; set; }
    }
```
Following our original disscussion, the FK ArticleID has been set to optional to avoid cycling or multiple paths complains from the Nuget package manager console. Fine. Removing an Article without loading causes an exception, fine, but removing an article with an .Include of the comments does not delete the comments but sets the FK to null. Why is that is not clear to me: 
```
var a = db.Articles.Include(c => c.Comments).FirstOrDefault(c => c.ArticleID == id);
db.Articles.Remove(a);
```
It gets more confusing when I re-run migration and switch the cascade behaviour in init.cs from `Restrict` to `SetNull`,
```
constraints: table =>
                {
                    table.PrimaryKey("PK_Comments", x => x.CommentID);
                    table.ForeignKey(
                        name: "FK_Comments_Articles_ArticleID",
                        column: x => x.ArticleID,
                        principalTable: "Articles",
                        principalColumn: "ArticleID",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        //code continues
                });
```
In this case, `update-database ` will complain `FK_Comments_Users_UserID' on table 'Comments' may cause cycles or multiple cascade paths`. Why does it complain now and not with the `Restrict`??
More generally, I just want that a deleted user means that his articles and comments get deleted and a deleted article deletes all of its comments. Any guidance is truly welcomed because it is hard for me to figure out if this is a miscomprehension from my part or some issue related to .Net core 1.1 or sql server?

**Comment by ajcvickers** [comment]
@Ponant I think maybe the confusion comes from understanding which are EF behaviors and which are database behaviors. For optional relationships, EF will always attempt to set null for any FK property in a tracked entity regardless of the cascading action. This is considered a normal part of fixup--previous versions of EF also worked this way and its not something we wanted to change. For required relationships, EF will only delete tracked dependents if cascade delete is configured. For both these cases EF does not suffer from the cycle issues that SQL Server does. So if all entities are loaded, then EF will have the correct behavior regardless of what the database is capable of.

When using Migrations to create a database, EF attempts to set the database to mimic EF behavior. This can allow an optimization in application code where dependent entities are not loaded but the effect is the same as if they were. Unfortunately, this doesn't work well with SQL Server because of the cycles issue. Because of this we decided to not set null by default because it makes pretty much every model built for SQL Server fail and it is a less common behavior to want in the database. For deletes, we attempt to set it in the database, but if you have a cycle, then you must make an explicit decision to either forgo the database optimization or stop doing cascade deletes altogether.

**Comment by Ponant** [comment]
@ajcvickers what would be your recommendation for the example above?

**Comment by ajcvickers** [comment]
@Ponant I would suggest either a) Don't use cascade deletes at all and make sure everything is deleted manually, or b) Use cascade deletes in EF making sure that everything is loaded, or c) setup some kind of trigger mechanism in SQL Server to get around its problems with cascade deletes, or d) find a database engine with better support for cascade deletes than SQL Server has.

**Comment by Ponant** [comment]
@ajcvickers , thanks for your time and explanations. I will start with b), even though I think I should be careful with load issues.  Thanks

**Comment by Ponant** [comment]
@ajcvickers , any link to where I can read more about the recurring SQL Server cycling issue/limitation? Hard to find!

**Comment by ajcvickers** [comment]
@Ponant http://stackoverflow.com/questions/851625/foreign-key-constraint-may-cause-cycles-or-multiple-cascade-paths
