### ISSUE TITLE
The target "_EFGetProjectMetadata" does not exist in the project.

### ISSUE THREAD

**Issue by mdmoura** [dotnet/efcore#7111]
### Steps to reproduce

I have an **ASP.NET Core 1.1** web application using **Visual Studio 2017 RC** with the following **CSPROJ** file:

    <Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.0</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
      </PropertyGroup>
      <PropertyGroup>
        <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
      </PropertyGroup>
      <PropertyGroup>
        <UserSecretsId>8bbf833a-6ecc-4d83-9229-c386e766e686</UserSecretsId>
      </PropertyGroup>
      <ItemGroup>
        <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
        <EmbeddedResource Include="**\*.resx" Exclude="$(GlobalExclude)" />
      </ItemGroup>
     <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies">
           <Version>1.1.0</Version>
       </PackageReference>
       <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore">
         <Version>1.1.0</Version>
       </PackageReference>
       <PackageReference Include="Microsoft.AspNetCore.Identity">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Mvc">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Razor.Tools">
          <Version>1.1.0-preview4-final</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.ResponseCaching">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.ResponseCompression">
          <Version>1.0.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Rewrite">
          <Version>1.0.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.StaticFiles">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.NETCore.App">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Sdk.Web">
          <Version>1.0.0-alpha-20161104-2-112</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.Console">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink.Loader">
          <Version>14.1.0</Version>
        </PackageReference>
        <PackageReference Include="Moleky.Core">
          <Version>1.0.0</Version>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json">
          <Version>9.0.2-beta1</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
          <Version>1.1.0-preview4-final</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets">
          <Version>1.1.0</Version>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design">
          <Version>1.0.0-msbuild1-final</Version>
        </PackageReference>
      </ItemGroup>
      <ItemGroup>
        <DotNetCliToolReference Include="BundlerMinifier.Core">
          <Version>2.2.301</Version>
        </DotNetCliToolReference>
        <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet">
          <Version>1.0.0-msbuild1-final</Version>
        </DotNetCliToolReference>
        <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools">
          <Version>1.0.0-msbuild1-final</Version>
        </DotNetCliToolReference>
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools">
          <Version>1.0.0-msbuild1-final</Version>
        </DotNetCliToolReference>
      </ItemGroup>
      <ItemGroup />
      <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
    </Project>

### The issue
I did 
      dotnet restore 
and then 
     dotnet ef migrations add "InitialCommit"

When I tried to create the migration I get the error.

    The target "_EFGetProjectMetadata" does not exist in the project.
    Ensure the package 'Microsoft.EntityFrameworkCore.Tools' is installed.

But I have 'Microsoft.EntityFrameworkCore.Tools' on my CSPROJ file:

        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
          <Version>1.1.0-preview4-final</Version>
        </PackageReference>

What am I missing?

**Comment by rowanmiller** [comment]
The preview4 version of `Microsoft.EntityFrameworkCore.Tools` is not compatible with the `msbuild1` version of `Microsoft.EntityFrameworkCore.Tools.DotNet`. Can you try swapping so that both have the `1.0.0-msbuild1-final` version number.

BTW, if you are using VS, then our recommendation would be to use the `preview4` version of `Microsoft.EntityFrameworkCore.Tools` and use the Package Manager Console commands (`Add-Migration`, etc.) in VS (rather than `dotnet ef` at the command line).

I just also want to acknowledge that this whole thing is super messy and confusing at the moment. This is a point in time issue while we move to .NET Core using MSBuild.

**Comment by mdmoura** [comment]
@rowanmiller Changing to `1.0.0-msbuild1-final` solved it ... When you advise to use `preview4` and Package Manager Console does it means `dotnet` will disappear? One good thing about dotnet commands is that their work outside Visual Studio and also in Visual Studio Code. So the same approach everywhere,

**Comment by rowanmiller** [comment]
Correct, unfortunately the Package Manager Console and `dotnet ef` commands can't co-exists in a project at the moment. That will be fixed in our next release.

**Comment by rhyek** [comment]
Hi. I'm trying to use cli version 1.0.0-preview5-004275 with runtime 1.1 with the following in my csproj file:
```xml
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0-msbuild2-final" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.0.0-msbuild1-final" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild1-final" />
  </ItemGroup>
```

I still get the error:
```
C:\Users\...\api\api.csproj : error MSB4057: The target "_EFGetProjectMetadata" does not exist in the project.
Couldn't read metadata for project 'C:\Users\...\api\api.csproj'. Ensure the package 'Microsoft.EntityFrameworkCore.Tools' is installed.
```

I am *not* using VS Studio, but rather Visual Studio Code with dotnet CLI exclusively (or trying to, at least). Any ideas?

**Comment by rhyek** [comment]
Nevermind, just realized my mistake. Needed `PackageReference` instead of `DotNetCliToolReference` for `Microsoft.EntityFrameworkCore.Tools`.

**Comment by bricelam** [comment]
FYI, the requirement of having Tools installed in order to use Tools.DotNet (`dotnet ef`) will be lifted in version 1.0.0-msbuild3-final

**Comment by deepak-khopade-isdr** [comment]
We hit with this issue today and when I opened my .Net core project in Visual Studio 2017 Community, and used the Nuget Package Manager, which added "1.1.0" and not "1.0.0-msbuild1-final", and hence started getting this error in our CI. So looks like for .NET core projects we should not use Package Manager (GUI tool) from Visual Studio and edit project files manually.
Just thought to share my experience.
