### ISSUE TITLE
Dispose method in RelationalDataReader class closes connection

### ISSUE THREAD

**Issue by gmartinezsan** [dotnet/efcore#7114]
### Steps to reproduce
MySQL provider getting a "Connection must be valid and open to commit transaction" exception when 
Executes update command batch.

See the call stack bellow:

 Test 'MySql.Data.EntityFrameworkCore.Tests.FluentAPITests.CanUseModelWithDateTimeOffset' failed: Connection must be valid and open to commit transaction
	transaction.cs(105,0): at MySql.Data.MySqlClient.MySqlTransaction.Commit()
	Storage\RelationalTransaction.cs(75,0): at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
	Update\Internal\BatchExecutor.cs(76,0): at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
	Storage\Internal\NoopExecutionStrategy.cs(38,0): at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
	Extensions\ExecutionStrategyExtensions.cs(236,0): at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
	Update\Internal\BatchExecutor.cs(50,0): at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
	Storage\RelationalDatabase.cs(59,0): at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
	ChangeTracking\Internal\StateManager.cs(675,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
	ChangeTracking\Internal\StateManager.cs(600,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
	DbContext.cs(293,0): at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
	DbContext.cs(257,0): at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

This exception is thrown after saving changes or adding a new row in an entity. Example:

                context.Database.EnsureCreated();
                var dt = DateTime.Now;
                var e = new QuickEntity { Name = "Jos", Created = dt };
                context.QuickEntity.Add(e);
                context.SaveChanges();

The exception is thrown in the context.SaveChanges(); line.
Once we reviewed the code we saw that the implementation of the RelationalDataReader class is closing the connection in the dispose method.

https://github.com/aspnet/EntityFramework/blob/1145ef9b3dd46a07a84cb04b11141ecc8bfc62d2/src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalDataReader.cs

  public virtual void Dispose()
        {
            if (!_disposed)
            {
                _reader.Dispose();
                _command.Dispose();
                _connection?.Close();
                _disposed = true;
            }
        }

This causes that when the transaction commits the changes, the mentioned exception is thrown. We will override this method to solve this issue, but it does not make sense to close the connection if the transaction is not committed yet.

EF Core version: 1.1

**Comment by AndriySvyryd** [comment]
@gmartinezsan `_connection?.Close();` doesn't close the underlying transaction if something else (a tranction) is still using it. You shouldn't need to override this.

**Comment by AndriySvyryd** [comment]
Closing this as we haven't received an update. Feel free to comment if the issue persists.
