### ISSUE TITLE
Extension for linq expression could not work in EF Core, but work in EF 6.

### ISSUE THREAD

**Issue by mrxten** [dotnet/efcore#7118]
I wrote my extension for LINQ **([source code](https://github.com/mrxten/QueryDesigner))**. In a nutshell, the idea is to create Where and OrderBy filters from json object. In this extensions I use expression trees for create them.

Code: 
```csharp
public override IQueryable<Card> Get(FilterContainer filter = null, params object[] args)
    {
        var result = from card in Context.hlt_disp_Card
                     join mkab in Context.hlt_MKAB on card.rf_MkabGuid equals mkab.UGUID
                     join sex in Context.oms_kl_Sex on mkab.rf_kl_SexID equals sex.kl_SexID
                     join dispTypeCard in Context.hlt_disp_Type on card.rf_DispTypeGuid equals dispTypeCard.Guid
                     select new Card
                     {
                         Id = card.disp_CardID,
                         Guid = card.Guid,
                         Number = card.Number,
                         Patient = new Patient
                         {
                             Id = mkab.MKABID,
                             BirthDate = mkab.DATE_BD,
                             Family = mkab.FAMILY,
                             Patronymic = mkab.OT,
                             Name = mkab.NAME,
                             Snils = mkab.SS,
                             Phone = mkab.contactMPhone,
                             Email = mkab.contactEmail,
                             Sex = new ReferenceCodeValue
                             {
                                 Id = sex.kl_SexID,
                                 Code = sex.CODE,
                                 Name = sex.NAME
                             },
                             Policy = new PatientPolicy
                             {
                                 Begin = Tools.Tools.MinDate,
                                 End = Tools.Tools.MaxDate,
                                 IsActive = true,
                                 Number = mkab.N_POL,
                                 Series = mkab.S_POL,
                             }
                         },
                     };
        return result.Request(filter);
    }
```

When I try to use my filter it's works well in EF6, but EF Core represent a warning:

> The LINQ expression '...' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.

What happened to the new version EF?

EF Core version:
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
Operating system: Win10
Visual Studio version: VS2015U3

**Comment by maumar** [comment]
Please try updating EF Core to 1.1 released recently. We drastically improved query translation compared to 1.0.1. Also, could you post the full exception? Knowing what expression can't be translated will help diagnosing the problem.

**Comment by mrxten** [comment]
I almost found a solution to the problem. We need construct expression for EF in dynamic way.For example we have a test code: http://pastebin.com/8U759Xj1We for some reason can not use the inherited properties in the filter. q.Where(ex1).ToList(); - compile toSELECT [card].[disp_CardID], [card].[Guid]FROM [hlt_disp_Card] AS [card]WHERE [card].[disp_CardID] = 1030 and q.Where(ex2).ToList(); - compile toSELECT [card].[disp_CardID], [card].[Guid]FROM [hlt_disp_Card] AS [card] Please help resolve this problem.25.11.2016, 14:34, "Maurycy Markowski" <notifications@github.com>:Please try updating EF Core to 1.1 released recently. We drastically improved query translation compared to 1.0.1. Also, could you post the full exception? Knowing what expression can't be translated will help diagnosing the problem.

**Comment by mrxten** [comment]
I made a mistake. Actual link: http://pastebin.com/8U759Xj125.11.2016, 15:37, "Zhukov Vladislav" <mr.xten@yandex.ru>:I almost found a solution to the problem. We need construct expression for EF in dynamic way.For example we have a test code: http://pastebin.com/8U759Xj1We for some reason can not use the inherited properties in the filter. q.Where(ex1).ToList(); - compile toSELECT [card].[disp_CardID], [card].[Guid]FROM [hlt_disp_Card] AS [card]WHERE [card].[disp_CardID] = 1030 and q.Where(ex2).ToList(); - compile toSELECT [card].[disp_CardID], [card].[Guid]FROM [hlt_disp_Card] AS [card] Please help resolve this problem.25.11.2016, 14:34, "Maurycy Markowski" <notifications@github.com>:Please try updating EF Core to 1.1 released recently. We drastically improved query translation compared to 1.0.1. Also, could you post the full exception? Knowing what expression can't be translated will help diagnosing the problem.

**Comment by mrxten** [comment]
I created a new issue https://github.com/aspnet/EntityFramework/issues/7126 for easy reading my problem.25.11.2016, 15:40, "Zhukov Vladislav" <mr.xten@yandex.ru>:I made a mistake. Actual link: http://pastebin.com/8U759Xj125.11.2016, 15:37, "Zhukov Vladislav" <mr.xten@yandex.ru>:I almost found a solution to the problem. We need construct expression for EF in dynamic way.For example we have a test code: http://pastebin.com/8U759Xj1We for some reason can not use the inherited properties in the filter. q.Where(ex1).ToList(); - compile toSELECT [card].[disp_CardID], [card].[Guid]FROM [hlt_disp_Card] AS [card]WHERE [card].[disp_CardID] = 1030 and q.Where(ex2).ToList(); - compile toSELECT [card].[disp_CardID], [card].[Guid]FROM [hlt_disp_Card] AS [card] Please help resolve this problem.25.11.2016, 14:34, "Maurycy Markowski" <notifications@github.com>:Please try updating EF Core to 1.1 released recently. We drastically improved query translation compared to 1.0.1. Also, could you post the full exception? Knowing what expression can't be translated will help diagnosing the problem.

**Comment by mrxten** [comment]
I almost found a solution to the problem. And created new issure #7126
Please close this issure.
