### ISSUE TITLE
How can I inject codes after entity created

### ISSUE THREAD

**Issue by Kation** [dotnet/efcore#7124]
I found I can customize a **IStateManager** to inject ef core to modify entities. But if a query is under no tracking mode, ef core will not reach **IStateManager**.
I also found I can customize a **IEntityMaterializerSource** to reach entity through 'Expression'.

But, I need ef's **IServiceProvider** where I injected. I need to get value from service and set the value to property of entity.

How can I inject codes where entity have being created with no tracking mode?

**Comment by Kation** [comment]
I found a solution.
Create a class inherit **StateManager** and override **StartTrackingFromQuery**.  Do something with entity we need and return null.

But, we can't tracking entities while querying if we need it to be tracked.

**Comment by ajcvickers** [comment]
@Kation I think what you are looking for is the ObjectMaterialized event, which isn't implemented yet but is being tracked by issue #626.

All the services you reference are internal code. You can try to get something working with them, but it will likely be quite difficult and may get broken by any update of EF Core, so very much do so at your own risk. Probably IEntityMaterializerSource is the most appropriate service to try this with if you do decide to take this approach.
