### ISSUE TITLE
Installing the EntityFramework.Core NuGet package into a Portable Class Library fails

### ISSUE THREAD

**Issue by jfquarto** [dotnet/efcore#7125]
I  am trying to install the EntityFramework.Core package into a Portable Class Library (PCL) via NuGet.
This fails returning this error message:
"Could not install package 'Microsoft.EntityFrameworkCore 1.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=
v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework"

- EF Core version: 1.1.0
- Operating system: Windows 7
- Visual Studio version: VS2015

**Comment by rowanmiller** [comment]
We aren't planning to enable this, as .NET Standard based class libraries are "the way of the future" and supporting PCL would add non-trivial complexity to our project.
