### ISSUE TITLE
Type Metadata - Add DataDomain Attribute and Domain Concepts

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/efcore#7132]
## Issue
1) Type metadata management could be improved in EF.
2) It is often the case where we create several classes (one per entity) simply to add display metadata to the properties of an entity.  A pain for very simple apps that don't require an additional layer of data abstraction beyond the EF models, with a few minor bad side effects like naming concerns.
3) It is often the case where we copy/paste the same display metadata to several attributes because it is "one of these things".

## Proposed
Big Picture: Add "Domains" to the framework.
Current:  Support a "DataDomain" property in DbContext/ModelBuilder and related classes/tooling.

### Need Description
I want to do something like this:

```C#
public static class CustomerDataDomain{
    public const string CommonName = "Customer Name"
    public const string Display = " [Display(Name =  " + CommonName + ")]";
    public const int MaxInputLength = 48; // I'm saving some of the field length for unknown reasons...
}
```
In DbContext:
```C#
entity.Property(e => e.Person)
    .HasDomain< CustomerDataDomain >() // This is the new feature
    .IsRequired()
    .HasColumnType("varchar(64)");
```
In ScaffoldingModelAnnotations it could automatically add the annotation to my model class to produce:

```C#
[Display(Name =  "Customer Name")]
[MaxLength(48)]
public string Person { get; set; }
```
With this feature I would be able to have EF generate "ViewDataModels" and well as Models:

PM> Scaffold-DbContext "connection" Microsoft.EntitiyFrameworkCore.SqlServer -ViewData

### Discussion
Elemental data is often "MetaTyped" very early in the analysis and design process. When I design my application, one of the things I start with are DataDomains. For example, I will create a Domain called Email, and I can assign a object representation ("string"), and database representation ("varchar(128)"). As I flush out my design I can just give new attributes or columns the type of "Email". If things change about the domain I just need to change one place. E.g., I can change Email to database=varchar(64), and all of the datatypes are changed for me. (I use modeling tools, so this is done for me). The thing about the domains is that they are really part of the item metadata and stay with the item through it's application layers, though it is interpreted differently by each layer. With Email, a string in the object, and varchar(128) in the data, and a set of css classes/jscripts in the presentation layer. In the Email case part of this concept is already there. There is even a build in DataAnnotation for it ([Email]) because it is so common. The large idea is that I should be able to assign the DataDomain in the database (e.g.) and if I ran scaffolding on DbContext and Controller it would influence the output of these tools.

It would be nice to be able carry something that exists beginning in the conceptual design stage and ending in the presentation layer all the way through the design/development tooling chain. Adding Domain concepts and DataDomains to EF would help. This would provide and additional layer of abstraction and information.

### Concept
The conceptual idea is to add "Domain" to EF. Almost any EF item can have Domain related information, and there can be entire sets of capabilities around domains. Designers could create a set of Domain classes that would hold metadata about these areas. DataDomains could be just one.

### Conceptual Overview
In looking at how this could be used we would first create an object and attributes called DataDomain in the Framework. Then using Fluent our Context could use:

(Weak typed version)

```C#
entity.Property(e => e.Email)
    .HasDomain("Email")
    .IsRequired()
    .HasColumnType("varchar(128)");
```
or
(Strong type version)

```C#
entity.Property(e => e.Email)
    .HasDomain< Email >("[Options]")
    .IsRequired()
    .HasColumnType("varchar(128)");
```

This would then make something like .DataDomain... available on my objects  for me and for (importantly) tooling.

When scaffolding entities EF could use (I don't know how this is actually done) a template like
```C#
[Display(Name = @Property.DataDomain.CommonName)]
public @Property.DataType Email....
```
#### Design-Time Use Case
If .DataDomain provides a const, it would be usable at design-time.
Assuming for below cases we create classes that derive from a DataDomainBase class - 

```C#
public static class EmailDataDomain : DataDomainBase { 
  public const string DisplayName = "Email Display Name";
}
```
#### Class Constant Use Case
We could use it like (for illustration)
```C#
[Display(Name =  EmailDataDomain.DisplayName)]
public string Person { get; set; }
```
This gives us a simple way to use/reuse Domains.
#### Class with [Display] Use Case
Variations could include an overload of display that has a Domain parameter
```C#
[Display(Domain=typeof(EmailDataDomain)]
public string ContactEmail {get; set; }
```
This exposes all of the properties to things like TagHelpers.
#### Fully Integrated Use Case
Promote "Domain" to create a framework-level DomainAttribute. This is preferred because is the most flexible with the broadest scope. It is also the most complicated and has major impact on the overall EF architecture.
```C#
[Domain(EmailDataDomain)] 
public string ContactEmail { get; set; }
```
#### Fully-Fully Integrated Use Case
Implemented as a service with a Domains Repository it could be injected, and a standard, extendable way to define Domains would be available.
### Actions
I propose two actions
 1) first determine if the overall concept of Domains is valuable and if so start a design group around that. A goal would be to define DomainAttribute and how it would be used.  
 2) Then (if so), prototype the concept by adding DataDomain where necessary to a fork to enable this simple (though weak and later disposable) experimental use:

```C#
public static class CustomerDataDomain : IDataDomain {
    public const string Display = [Display(Name =  "Customer Name")];
}
```

In DbContext:
```C#
entity.Property(e => e.Person)
    .HasDomain(typeof(CustomerDataDomain))
    .IsRequired()
    .HasColumnType("varchar(128)");
```
Which would expose the DataDomain to scaffolding for use as Customer.DataDomain.Display.

2.1) Modify Scaffold-DbContext to accept the -ViewModel switch. 

This might be an early first step that cures a common pain point

### Discussion Comment
One of the difficulties in doing this for the full chain is where to keep this in the data layer. In old SQL Server it could have been (hacked) in the Description field (maybe as json), but I'm not seeing Description in sys.syscolumns. Scaffolding would read and parse this to automatically add the .DataDomain<> to Context.

**Comment by rowanmiller** [comment]
@divega is going to put some more detailed thought into your proposal. In the meantime, I just wanted to note that you can achieve something similar using extension methods already...

```c#
public static PropertyBuilder<string> ApplyEmailDomain(this PropertyBuilder<string> property)
{
    property.HasMaxLength(48);
    property.IsUnicode(false);
    return property;
}
```

```c#
modelBuilder.Entity<Customer>()
    .Property(b => b.Email)
    .ApplyEmailDomain();
```

**Comment by RandyBuchholz** [comment]
Thanks for the extension method approach. @divega can contact me directly with any questions about my thoughts. I'd be happy to participate.

**Comment by ajcvickers** [comment]
Sorry for not responding in a long time on this. After discussing this again, we feel that this kind of functionality would be better implemented as extensions to the core EF code. Closing this as we don't plan to fix it in the main EF codebase.
