### ISSUE TITLE
EFCore 1.1 Add-Migration fails when run from VS2015 Package Manager Console: default project and -Project ignored

### ISSUE THREAD

**Issue by DaveRobSwEng** [dotnet/efcore#7142]
### Steps to reproduce
Added EFCore 1.1 to a component assembly of my WPF application using SQLite as the DB provider.
Added the Microsoft.EntityFrameworkCore.Tools component to the assembly project after the basic functionality was working (including updating PowerShell to 3.0).
Selected the target assembly in the package manager console 'Default Project'
Tried to add a migration to the assembly and the add-migration command failed:

> PM> add-migration -Name Initial -Verbose -project Modules\Sepura.Dispatcher.Database
> Build started...
> Build succeeded.
> Setting app base path C:\Users\robinsond\Documents\Git\dispatcherlite\Sepura.Dispatcher.Shell\bin\Release
> Cannot execute this command because Microsoft.EntityFrameworkCore.Design is not installed. Install the version of that package that matches the installed version of Microsoft.EntityFrameworkCore and try again.

The app base path is the start-up project and not the required project. Selecting the database project as the start-up project caused the add-migration command to proceed normally.

### Further technical details

EFCore versions:
"Microsoft.EntityFrameworkCore" version="1.1.0" targetFramework="net461" 
"Microsoft.EntityFrameworkCore.Design" version="1.1.0" targetFramework="net461" 
"Microsoft.EntityFrameworkCore.Relational" version="1.1.0" targetFramework="net461" 
"Microsoft.EntityFrameworkCore.Relational.Design" version="1.1.0" targetFramework="net461" 
"Microsoft.EntityFrameworkCore.Sqlite" version="1.1.0" targetFramework="net461" 
"Microsoft.EntityFrameworkCore.Tools" version="1.1.0-preview4-final" targetFramework="net461" developmentDependency="true" 

Operating system: Win7/64
Visual Studio version: VS2015 Update 3

**Comment by tdjastrzebski** [comment]
It seems like I experience the same issue. I went through some discussions already but no resolution found. I have the latest Power Shell, the latest Package Manager Console Host Version 3.5.0.1996, all the latest assembly versions.
Executing "Scaffold-DbContext ..."
I get error: 

> Cannot execute this command because Microsoft.EntityFrameworkCore.Design is not installed. Install the version of that package that matches the installed version of Microsoft.EntityFrameworkCore and try again.

I already tried to reinstall Microsoft.EntityFrameworkCore components - it did not help.
**project.json** file attached.

[project.zip](https://github.com/aspnet/EntityFramework/files/616093/project.zip)

**Comment by tdjastrzebski** [comment]
I had a similar problem. What helped:
- make sure you really have .Net Core 1.1 SDK installed (not just ASP.Net Core 1.1). Without it somehow the project builds but Scaffold-DbContext will error out
- make sure executing Scaffold-DbContext you have correct destination project selected ("Set as StartUp Project"),
- make sure you have correct "Default project" selected in Package Manager Console drop-down list

**Comment by bricelam** [comment]
@DaveRobSwEng This looks like a known issue with using `packages.config`-based NuGet. Some transitive dependencies don't get copied to the output directory. The workaround should be to install the `Microsoft.EntityFrameworkCore.Design` package into the `Sepura.Dispatcher.Shell` project.
