### ISSUE TITLE
using dotnet ef on published projects

### ISSUE THREAD

**Issue by mwrock** [dotnet/efcore#7156]
I am working on an asp.net core website on linux. I'd like to be able to use the `dotnet ef` command on a node where I published the site. The published location just has the site dlls and `dotnet ef` seems to demand the `project.json` file be present.

Is this possible or must I use `dotnet ef` from the original source directory? Is there another tool/script I can leverage to accomplish `dotnet ef database update` without needing the project.json and incurring a `dotnet restore` and build?

**Comment by rowanmiller** [comment]
This is currently not possible. We have https://github.com/aspnet/EntityFramework/issues/646 tracking the ability to have a CLI for compiled applications.
