### ISSUE TITLE
Specified cast is not valid on 3rd Include

### ISSUE THREAD

**Issue by ndenkha** [dotnet/efcore#7159]
Not to duplicate work, but I posted my issue on this closed post in case no one will look at a closed issue.

https://github.com/aspnet/EntityFramework/issues/1748

Thanks,
Ninos

**Comment by rowanmiller** [comment]
Can you open the issue over on the EF6 project - github.com/aspnet/EntityFramework6.

**Comment by ndenkha** [comment]
Thank you for checking. I Will do that, and I also found a work around for it.
