### ISSUE TITLE
Publish w/ Migrations from different dlls fail

### ISSUE THREAD

**Issue by Allann** [dotnet/efcore#7169]
### Steps to reproduce
Not sure how easy this will be, but:
1. Have an ASP.Net Core website that has one or more DbContext referenced assemblies (Core dlls)
2. Add the dbcontext in startup.cs (i.e: `services.AddDbContext<MaintenanceContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), b => b.MigrationsAssembly("Jbssa.FreightRates.Maintenance.Data")));`)
3. Publish the web app with the Entity Framework Migrations checked for those dbcontexts.  In Settings tab of the Publish dialog.  Ensuring the correct connection string is supplied.

### The issue
Describe what is not working as expected.

Receive error in Error LIst in VS2015 U3.
Error		Your target project 'Jbssa.FreightRates.Web' doesn't match your migrations assembly 'Jbssa.FreightRates.Rates.Data'. Either change your target project or change your migrations assembly.	Jbssa.FreightRates.Web		0	

Error		Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Jbssa.FreightRates.Web")). By default, the migrations assembly is the assembly containing the DbContext.	Jbssa.FreightRates.Web		0	

### Further technical details

EF Core version: (found in project.json)
  "dependencies": {
    "Jbssa.FreightRates.Maintenance.Domain": "1.0.0-*",
    "Jbssa.ApplicationData.Reference.Domain": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "NETStandard.Library": "1.6.1",
    "Microsoft.AspNetCore.Http.Abstractions": "1.1.0",
    "System.Linq": "4.3.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Jbssa.Application.SharedKernel.Data": "0.1.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }

Operating system: 
Visual Studio version: VS 2015 Update 3 on Win10x64

Other details about my project setup:
Structure:
![image](https://cloud.githubusercontent.com/assets/2005474/20782806/f871927e-b7da-11e6-8d63-1d7fc6628694.png)
Each BC_* project group are a DbContext and associated domain class.  All are .Core class libraries.

**Comment by Allann** [comment]
I have also tried the dotnet command line and get similar errors:

```
C:\TFS2015\Framework\JBS46 Applications\Dev\Jbssa.FreightRates.Web\src\Jbssa.FreightRates.Web>dotnet ef database update --context jbssa.freightrates.history.data.historycontext --verbose
Project Jbssa.FreightRates.History.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.History.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Maintenance.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationData.Reference.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Maintenance.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Rates.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Rates.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationSecurity.Reference.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationSecurity.Reference.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Security (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationData.Reference.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Background (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Web (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Setting app base path C:\TFS2015\Framework\JBS46 Applications\Dev\Jbssa.FreightRates.Web\src\Jbssa.FreightRates.Web\bin\Debug\netcoreapp1.0\win7-x64
Finding DbContext classes...
Using context 'HistoryContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Your target project 'Jbssa.FreightRates.Web' doesn't match your migrations assembly 'Jbssa.FreightRates.History.Data'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Jbssa.FreightRates.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureServices(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Your target project 'Jbssa.FreightRates.Web' doesn't match your migrations assembly 'Jbssa.FreightRates.History.Data'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Jbssa.FreightRates.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.

```

I have found a viable though not pretty solution for this issue, I have moved the DbContext project content into a folder within the asp.net core application (Jbssa.FreightRates.Web) application.  So this is now the new structure.
![image](https://cloud.githubusercontent.com/assets/2005474/20870610/08df8b58-bad7-11e6-98ae-8db0e152656e.png)

After that and removing the migration parameter in the startup.cs ConfigureServices method, all worked fine.  See below.

            services.AddDbContext<HistoryContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));


```
C:\TFS2015\Framework\JBS46 Applications\Dev\Jbssa.FreightRates.Web\src\Jbssa.FreightRates.Web>dotnet ef database update --context jbssa.freightrates.history.data.historycontext --verbose
Project Jbssa.FreightRates.History.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Maintenance.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Rates.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationSecurity.Reference.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationSecurity.Reference.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Security (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationData.Reference.Domain (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.ApplicationData.Reference.Data (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Background (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project Jbssa.FreightRates.Web (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling Jbssa.FreightRates.Web for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:29.4801659

Setting app base path C:\TFS2015\Framework\JBS46 Applications\Dev\Jbssa.FreightRates.Web\src\Jbssa.FreightRates.Web\bin\Debug\netcoreapp1.0\win7-x64
Finding DbContext classes...
Using context 'HistoryContext'.
Done.

```

**Comment by rowanmiller** [comment]
Moved over to Tooling for the Publish folks to look at https://github.com/aspnet/Tooling/issues/898.

When you call the command yourself, you should use `--project` to specify which project the migrations are in. Alternatively, you can call the command on the project with migrations, and use `--startupProject` to point to your web project.
