### ISSUE TITLE
Is there any ability to "if not in transcaction - then connection.BeginTransaction()"

### ISSUE THREAD

**Issue by arielcloud** [dotnet/efcore#7179]
I want to wrap function father() in transaction, but function father() called to function child(), and I want to wrap child() himself with transaction, so that in any case someone call child() - it will save internal changes with transaction.
but if I wrapped both with transaction and call father() it thrown since EF dont let nested transaction...

so, there is any API for "if not in transcaction - then BeginTransaction()"?

10x!

**Comment by ajcvickers** [comment]
@arielcloud Something like this:

```C#
public static void Father(DbContext context)
{
    using (var transaction = context.Database.BeginTransaction())
    {
        Child(context);

        // Do stuff
        context.SaveChanges();

        transaction.Commit();
    }
}

public static void Child(DbContext context)
{
    using (var transaction = context.Database.CurrentTransaction == null
        ? context.Database.BeginTransaction()
        : null)
    {

        // Do stuff
        context.SaveChanges();

        transaction?.Commit();
    }
}
```
