### ISSUE TITLE
Problem with UTF 8 in insert / update  

### ISSUE THREAD

**Issue by tobiashoeft** [dotnet/efcore#7180]
Hey folks ,

i have a problem with the "insert and update" maybe in my WebApi to MySql Database.

if i debug all works fine with german "äääöööüü etc.." on controller and models from angular 2 service.
The values shown up the ÖÄ.

But if the Create or Update runs to db the values looks like this  in Table  GroÃƒÆ’Ã…Â.

If i change the values in Database and call a HttpGet the Values shown ÄÖÖ on Ui.

I already post an issuee to  to SapientGuardian.EntityFrameworkCore.MySql

Link : (https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/35)

But @SapientGuardian can't reproduce it with my sample solution.

The Database is a MySql 5.7.16 and the Default CharSet is UTF8.

If i use the EntityFramework  
`using (var context =SampleDbContext.SampleContextFactory.Create())
                {
                    context.Sample.Add(sample);
                    context.SaveChanges();
                }`

The values don't shown  "ääälllääääÖÖÖ"

But if i use "using (MySqlCommand command = new MySqlCommand)"

The Values stored write the UTF8 to database.

NO ERRORMESSAGES

EF Core version: 1.1.0
Operating system: Win10 x64
Visual Studio version: VS 2015 update 3

<img width="524" alt="unbenanntes bild" src="https://cloud.githubusercontent.com/assets/5573898/20867951/6dc5a412-ba50-11e6-92ac-e8b4fedd6bc3.png">

project.json: 

`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0-*",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "SapientGuardian.EntityFrameworkCore.MySql": "7.1.14",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel.Https": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "System.Security.Cryptography.Algorithms": "4.3.0",
    "MimeKit": "1.10.0",
    "MailKit": "1.10.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "jose-jwt": "2.0.2",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Syncfusion.EJ.AspNet.Core": "14.4600.0.15-preview2-final",
    "Syncfusion.EJ.Pivot": "14.4600.0.15-preview2-final",
    "Syncfusion.Compression.AspNet.Core": "14.4600.0.15-preview2-final",
    "Syncfusion.Pdf.AspNet.Core": "14.4600.0.15-preview2-final",
    "Syncfusion.OfficeChart.AspNet.Core": "14.4600.0.15-preview2-final",
    "Syncfusion.Presentation.AspNet.Core": "14.4600.0.15-preview2-final",
    "Syncfusion.DocIO.AspNet.Core": "14.4600.0.15-preview2-final",
    "Giffel.ServiceLibary": "1.0.0-*",
    "Serilog": "2.3.0",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.SignalR.Server": "0.2.0-*",
    "Microsoft.AspNetCore.WebSockets": "1.0.0"

  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
  "runtimes": {
    "ubuntu.14.04-x64": {}
  },
  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}`

**Comment by rowanmiller** [comment]
Per the discussion on https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/35, this doesn't seem to be reproducible or specifically to do with Entity Framework. It seems to be related to HTTPS and WebAPI.
