### ISSUE TITLE
ArgumentException after migration to EF 1.1

### ISSUE THREAD

**Issue by marcels2204** [dotnet/efcore#7186]
Testname:	TSClean.UnitTests.BusinessLogic.CreateVorgangTests.CreateVorgang_MitBelegTypReinigung_ErzeugtAuftrag
Test FullName:	TSClean.UnitTests.BusinessLogic.CreateVorgangTests.CreateVorgang_MitBelegTypReinigung_ErzeugtAuftrag
Testquelle:	C:\git\TSCleanNeu\src\TSClean.UnitTests\BusinessLogic\CreateVorgangTests.cs Zeile 49
Testergebnis:	Fehlgeschlagene
Testdauer:	0:00:00,492

Ergebnis StackTrace:	
at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateSnapshotExpression(Type entityType, ParameterExpression parameter, Type[] types, IList`1 propertyBases)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory.CreateConstructorExpression(IEntityType entityType, ParameterExpression parameter)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SnapshotFactoryFactory`1.Create(IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.OriginalValues..ctor(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.EnsureOriginalValues()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntrySubscriber.SnapshotAndSubscribe(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at TSClean.Repository.Infrastructure.Repository`1.Add(T entity) in C:\git\TSCleanNeu\src\TSClean.Repository\Infrastructure\Repository.cs:line 30
   at TSClean.BusinessLogic.VorgangBL.CreateVorgangHandler.HandleCore(CreateVorgangCommand command) in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\VorgangBL\CreateVorgang.cs:line 32
   at MediatR.RequestHandler`1.Handle(TMessage message)
   at BusinessLogic.Infrastructure.Pipeline`2.Handle(TRequest request) in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\Pipeline.cs:line 43
   at TSClean.BusinessLogic.Infrastructure.TransactionHandler`2.Handle(TRequest request) in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\TransactionHandler.cs:line 71
   at BusinessLogic.Infrastructure.ValidatorHandler`2.Handle(TRequest request) in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\ValidatorHandler.cs:line 40
   at BusinessLogic.Infrastructure.ExceptionHandler`2.Handle(TRequest request) in C:\git\TSCleanNeu\src\TSClean.BusinessLogic\Infrastructure\ExceptionHandler.cs:line 42
   at TSClean.UnitTests.BusinessLogic.CreateVorgangTests.CreateVorgang_MitBelegTypReinigung_ErzeugtAuftrag() in C:\git\TSCleanNeu\src\TSClean.UnitTests\BusinessLogic\CreateVorgangTests.cs:line 73
Ergebnis Meldung:	
Expression of type 'System.Int32' cannot be used for constructor parameter of type 'System.Nullable`1[System.Int32]'
Parameter name: arguments[19]

QA

**Comment by marcels2204** [comment]
`using System;
using System.Collections.Generic;
using System.Diagnostics;
using TSClean.BusinessEntities.Infrastructure;
using TSClean.Interfaces.BusinessEntities;

namespace TSClean.BusinessEntities
{
    [DebuggerDisplay("Id = {Id}, TrackingState = {TrackingState}, Belegtyp = {Belegtyp}")]
    public class Vorgang : EntityBase, IAnschrift
    {
        private string _nummer;
        private Belegtyp _belegtyp;
        private Belegstatus _belegstatus;
        private int _kundeId;
        private int _kontoId;
        private string _kontonummer;
        private int _gegenkontoId;
        private string _gegenkontoNummer;
        private string _umsatzsteuerIdentnummer;
        private int _adresseId;
        private string _name;
        private string _name2;
        private string _strasse;
        private string _strasse2;
        private string _plz;
        private string _ort;
        private DateTime _belegdatum;
        private DateTime? _leistungsdatumVon;
        private DateTime? _leistungsdatumBis;
        private DateTime? _buchungsdatum;
        private string _bemerkung;
        private string _referenz;
        private decimal _nettoReduziert;
        private decimal _nettoAllgemein;
        private decimal _mwStReduziert;
        private decimal _mwStAllgemein;
        private decimal _brutto;
        private bool _rabatt;
        private decimal _rabattProzent;
        private decimal _rabattNetto;
        private DateTime? _ausgleichsdatum;
        private decimal _zuschlagNetto;
        private bool _gebucht;
        private Buchungsgruppe _buchungsgruppe;
        private bool _umsatzsteuerBerechnet;

        public string Nummer
        {
            get { return _nummer; }
            set
            {
                if (value == _nummer) return;
                _nummer = value;
                OnPropertyChanged();
            }
        }

        public Belegtyp Belegtyp
        {
            get { return _belegtyp; }
            set
            {
                if (value == _belegtyp) return;
                _belegtyp = value;
                OnPropertyChanged();
            }
        }

        public Belegstatus Belegstatus
        {
            get { return _belegstatus; }
            set
            {
                if (value == _belegstatus) return;
                _belegstatus = value;
                OnPropertyChanged();
            }
        }

        public int KundeId
        {
            get { return _kundeId; }
            set
            {
                if (value == _kundeId) return;
                _kundeId = value;
                OnPropertyChanged();
            }
        }

        public Kunde Kunde { get; set; }

        public int KontoId
        {
            get { return _kontoId; }
            set
            {
                if (value == _kontoId) return;
                _kontoId = value;
                OnPropertyChanged();
            }
        }

        public string Kontonummer
        {
            get { return _kontonummer; }
            set
            {
                if (value == _kontonummer) return;
                _kontonummer = value;
                OnPropertyChanged();
            }
        }

        public int GegenkontoId
        {
            get { return _gegenkontoId; }
            set
            {
                if (value == _gegenkontoId) return;
                _gegenkontoId = value;
                OnPropertyChanged();
            }
        }

        public string GegenkontoNummer
        {
            get { return _gegenkontoNummer; }
            set
            {
                if (value == _gegenkontoNummer) return;
                _gegenkontoNummer = value;
                OnPropertyChanged();
            }
        }

        public string UmsatzsteuerIdentnummer
        {
            get { return _umsatzsteuerIdentnummer; }
            set
            {
                if (value == _umsatzsteuerIdentnummer) return;
                _umsatzsteuerIdentnummer = value;
                OnPropertyChanged();
            }
        }

        public int AdresseId
        {
            get { return _adresseId; }
            set
            {
                if (value == _adresseId) return;
                _adresseId = value;
                OnPropertyChanged();
            }
        }

        public Adresse Adresse { get; set; }

        public string Name
        {
            get { return _name; }
            set
            {
                if (value == _name) return;
                _name = value;
                OnPropertyChanged();
            }
        }

        public string Name2
        {
            get { return _name2; }
            set
            {
                if (value == _name2) return;
                _name2 = value;
                OnPropertyChanged();
            }
        }

        public string Strasse
        {
            get { return _strasse; }
            set
            {
                if (value == _strasse) return;
                _strasse = value;
                OnPropertyChanged();
            }
        }

        public string Strasse2
        {
            get { return _strasse2; }
            set
            {
                if (value == _strasse2) return;
                _strasse2 = value;
                OnPropertyChanged();
            }
        }

        public string PLZ
        {
            get { return _plz; }
            set
            {
                if (value == _plz) return;
                _plz = value;
                OnPropertyChanged();
            }
        }

        public string Ort
        {
            get { return _ort; }
            set
            {
                if (value == _ort) return;
                _ort = value;
                OnPropertyChanged();
            }
        }

        public DateTime Belegdatum
        {
            get { return _belegdatum; }
            set
            {
                if (value.Equals(_belegdatum)) return;
                _belegdatum = value;
                OnPropertyChanged();
            }
        }

        public DateTime? LeistungsdatumVon
        {
            get { return _leistungsdatumVon; }
            set
            {
                if (value.Equals(_leistungsdatumVon)) return;
                _leistungsdatumVon = value;
                OnPropertyChanged();
            }
        }

        public DateTime? LeistungsdatumBis
        {
            get { return _leistungsdatumBis; }
            set
            {
                if (value.Equals(_leistungsdatumBis)) return;
                _leistungsdatumBis = value;
                OnPropertyChanged();
            }
        }

        public DateTime? Buchungsdatum
        {
            get { return _buchungsdatum; }
            set
            {
                if (value.Equals(_buchungsdatum)) return;
                _buchungsdatum = value;
                OnPropertyChanged();
            }
        }

        public string Bemerkung
        {
            get { return _bemerkung; }
            set
            {
                if (value == _bemerkung) return;
                _bemerkung = value;
                OnPropertyChanged();
            }
        }

        public string Referenz
        {
            get { return _referenz; }
            set
            {
                if (value == _referenz) return;
                _referenz = value;
                OnPropertyChanged();
            }
        }

        public decimal NettoAllgemein
        {
            get { return _nettoAllgemein; }
            set
            {
                if (value == _nettoAllgemein) return;
                _nettoAllgemein = value;
                OnPropertyChanged();
            }
        }

        public decimal MwStAllgemein
        {
            get { return _mwStAllgemein; }
            set
            {
                if (value == _mwStAllgemein) return;
                _mwStAllgemein = value;
                OnPropertyChanged();
            }
        }

        public decimal NettoReduziert
        {
            get { return _nettoReduziert; }
            set
            {
                if (value == _nettoReduziert) return;
                _nettoReduziert = value;
                OnPropertyChanged();
            }
        }

        public decimal MwStReduziert
        {
            get { return _mwStReduziert; }
            set
            {
                if (value == _mwStReduziert) return;
                _mwStReduziert = value;
                OnPropertyChanged();
            }
        }

        public decimal Brutto
        {
            get { return _brutto; }
            set
            {
                if (value == _brutto) return;
                _brutto = value;
                OnPropertyChanged();
            }
        }

        public bool Rabatt
        {
            get { return _rabatt; }
            set
            {
                if (value == _rabatt) return;
                _rabatt = value;
                OnPropertyChanged();
            }
        }

        public decimal RabattProzent
        {
            get { return _rabattProzent; }
            set
            {
                if (value == _rabattProzent) return;
                _rabattProzent = value;
                OnPropertyChanged();
            }
        }

        public decimal RabattNetto
        {
            get { return _rabattNetto; }
            set
            {
                if (value == _rabattNetto) return;
                _rabattNetto = value;
                OnPropertyChanged();
            }
        }

        public DateTime? Ausgleichsdatum
        {
            get { return _ausgleichsdatum; }
            set
            {
                if (value.Equals(_ausgleichsdatum)) return;
                _ausgleichsdatum = value;
                OnPropertyChanged();
            }
        }

        public decimal ZuschlagNetto
        {
            get { return _zuschlagNetto; }
            set
            {
                if (value == _zuschlagNetto) return;
                _zuschlagNetto = value;
                OnPropertyChanged();
            }
        }

        public bool Gebucht
        {
            get { return _gebucht; }
            set
            {
                if (value == _gebucht) return;
                _gebucht = value;
                OnPropertyChanged();
            }
        }

        public Buchungsgruppe Buchungsgruppe
        {
            get { return _buchungsgruppe; }
            set
            {
                if (value == _buchungsgruppe) return;
                _buchungsgruppe = value;
                OnPropertyChanged();
            }
        }

        public bool UmsatzsteuerBerechnet
        {
            get { return _umsatzsteuerBerechnet; }
            set
            {
                if (value == _umsatzsteuerBerechnet) return;
                _umsatzsteuerBerechnet = value;
                OnPropertyChanged();
            }
        }

        public ChangeTrackingCollection<Vorgangsposition> Positionen { get; private set; } = new ChangeTrackingCollection<Vorgangsposition>();        

        public ChangeTrackingCollection<Zahlung> Zahlungen { get; private set; } = new ChangeTrackingCollection<Zahlung>();

        public Reinigungsdetails Reinigungsdetails { get; set; }        
    }
}
`

**Comment by marcels2204** [comment]
When property Vorgang.Reinigungsdetails is null then DbSet.Add throws no exception. When i set the property and call DbSet.Add the ArgumentException will be thrown.

**Comment by divega** [comment]
@marcels2204 can you please explain why you closed the issue? Do you now think it isn't an issue with 
EF Core?
