### ISSUE TITLE
Concern with Releases

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#7192]
I just tried to update from EF7 1.0.0 to EF7 1.1.0 to see if some bugs were fixed and use some new features.
To my surprise this, in effect, meant I have to also update my MVC 6 packages to the latest 1.1.0 release.

Is that right? I think this is because there are shared dependencies, and EF7 requires later versions of those dependencies.

It seems pretty nasty that updating EF forces you to update an entire MVC web application. 

My concern is that if EF7 1.1.0 release is just forcing the latest dependencies upon people, not because it absolutely needs them to solve issues, but just because they are the latest:

![image](https://cloud.githubusercontent.com/assets/3176632/20934652/c9a2d38e-bbd3-11e6-85e5-1652a9757fc5.png)

Was forcing all of those dependency updates really necessary - would EF not have been compatible with previous versions of those dependencies as well?

If the answer to the above is yes it was necessary, then fair enough, but I just wanted to voice how frustrating this is when a "minor" update to a data library forces a complete application upgrade including the web / ui stack

**Comment by dazinator** [comment]
Closing as this was more of a frustrated rant than an issue.  I haven't actually looked at why I was forced to update MVC whe updating EF, so I'll re-raise once I can confirm the specific.

**Comment by ajcvickers** [comment]
@dazinator It is because of the way the licensing model works rather than anything explicit about dependencies. If you feel we could do this better you may want to file an issue on https://github.com/aspnet/Home

**Comment by dazinator** [comment]
Ok thanks. I raised https://github.com/aspnet/Home/issues/1862
