### ISSUE TITLE
Test: Allow parallel execution of functional tests 

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#7195]
Korebuild has the ability to disable parallel execution of tests in certain test projects where such test projects are specified using env variables.  During recent test failures on CI, it came to light that EF.SqlServer.FunctionalTests cannot be run in parallel and must be added to the exclusion list. Which is how build was running successfully for months on CI so far.

In this particular failure case, 
the database `OptimisticConcurrencyTest` which corresponds to `F1SqlServerFixure` and being used in multiple test suites (namely `DatabindingSqlServerTest`, `OptimisticConcurrencySqlServerTest`, `PropertyEntrySqlServerTest`) caused database corruption and connection issues in future iteration of tests since each test suits create/drop database.
There could be potentially more test suites which are sharing database across them and still modifying it.

We can remove this limitation of no parallel execution of functional tests by creating different database for each test suite (though using the same domain model).

**Comment by ajcvickers** [comment]
@smitpatel Consider having all the tests share a common fixture. We have infrastructure to ensure that the fixture will clean the database once in a thread-safe manner. Tests should not be modifying the database except inside an uncommitted local transaction; if this is not the case, then the tests should be modified to do so--there are common patterns for this in other tests. If a local transaction is not possible, then the test suite will likely need its own database, but this is usually only necessary for code that tests transactions.

**Comment by smitpatel** [comment]
closed as dupe of #7411
