### ISSUE TITLE
Allow update pipeline to push nulls and/or CLR defaults for store generated values

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#7199]
Creating this issue so that we can discuss the value--not suggesting we do this. As of now I don't believe we have any concrete case where we need this or any customer requests for it.

Currently for store generated values, the update pipeline will push a value if is is not equal to the CLR default, otherwise it will expect the store to generate a value. It is possible that sometimes an app will require a CLR default to be pushed. This can often be done by making the property nullable, but this doesn't work if it is actually null that needs to be pushed.

This came up in the discussion of value generators, where if the value generated is the CLR default and the property is marked as ValueGenerated.OnAdd, then the update pipeline will still expect the store to generate a value, which might or might not be the intention. Discriminator value generators are like this--they need to be able to generate nulls. However, it isn't a problem because discriminator values are never store generated and so the property does not need to be marked as ValueGenerated.OnAdd.

**Comment by rowanmiller** [comment]
We'll look at doing this in the future if we find a real customer scenario for it.
