### ISSUE TITLE
Make Core ValueGeneratorSelector more easy to extend for provider writers

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#7206]
It should be easy to choose a temporary ValueGenerator if the value is going to be store generated.

Add all the generators shipped in Core.

**Comment by CoskunSunali** [comment]
Would you please be so kind to give insights on why this issue has been closed as won't fix?

**Comment by AndriySvyryd** [comment]
@CoskunSunali Because no provider writers reported this to be a significant issue

**Comment by AndriySvyryd** [comment]
@CoskunSunali I don't know why this is happening of top of my head, but even if you fix this you will likely run into more issues and this approach would require making many changes to upgrade to EF Core 3

Why do you want to abstract the data provider? Is it to be able to switch between them dynamically? Perhaps the last example on https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers would work better.

**Comment by CoskunSunali** [comment]
@AndriySvyryd I am fully aware of the consequences of wrapping EF but the cost is worth in our scenario. Thank you for the reminder though!

Just to simplify my question; is EF supposed to make calls to `IValueGeneratorSelector.Create` method once a property is set using `ValueGeneratedOnAdd` or `ValueGeneratedOnUpdate` or ValueGeneratedOnAddOrUpdate` without anything else?

**Comment by CoskunSunali** [comment]
@AndriySvyryd I might have completely misunderstood the `propertyBuilder.ValueGenerated...` methods.

Please ignore my questions.

Thank you for your replies!
