### ISSUE TITLE
String is truncated at 43679 characters on Select although the column is nvarchar(max)

### ISSUE THREAD

**Issue by wertzui** [dotnet/efcore#7209]
When you store an object with a string that is mapped to an nvarchar(max) with a large amount of data (>43679 characters), it is inserted without problems.
You can veryfy that in SMSS using `SELECT len(myColumn) FROM myTable`.

However retrieving that Data using Entity Framework Core, the string is truncated at 43679 characters.
```c#
var myObject = myTable.Single();
Debug.WriteLine(myObject.myColumn.Length); // 43679
```

There is a known limitation in SMSS so that it will only display a maximum of 43679 characters for every column. However this limitation should not apply to Entity Framework Core.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (SQL Server 2014)
Operating system: Windows Server 2012 R2
IDE: Visual Studio 2015

**Comment by ErikEJ** [comment]
Are you able to provide a repro?

**Comment by ajcvickers** [comment]
@wertzui Tried this simple example and did not get any truncation, so it certainly feels like we will need more info to repro:
```C#
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=CollectionsTest;Trusted_Connection=True;ConnectRetryCount=0");
    }
}

public class Program
{
    private static void Main()
    {
        using (var context = new BlogContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog
            {
                Title = new string('X', 100000)
            });

            context.SaveChanges();
        }

        using (var context = new BlogContext())
        {
            var blog = context.Blogs.Single();
            Console.WriteLine(blog.Title.Length);
        }
    }
}
```

**Comment by wertzui** [comment]
While I tried to create a minimal examble, I was unable to reproduce the error. I will investigate further and close this issue for the moment. Sorry for the inconvenience.
