### ISSUE TITLE
Asp.net core on linux - version errors in template project.json? - dotnet ef database update fails with version error

### ISSUE THREAD

**Issue by MarkusEgle** [dotnet/efcore#7211]
Just followed exactly the install instructions on https://www.microsoft.com/net/core#linuxubuntu and https://docs.microsoft.com/en-us/aspnet/core/getting-started

Everything is fine so far, except when creating a new user under http://localhost:5000/Account/Register it fails with 

> SQLite Error 'no such table: AspNetUsers'

![sqliteexception](https://cloud.githubusercontent.com/assets/24455421/21010257/5b4e89ae-bd4b-11e6-8d7c-72d594742de1.PNG)

Tried with `dotnet ef database update` to create the table structure but it fails with version errors. 

```
>~/testweb$ dotnet ef database update
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
```

### Steps to reproduce
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list'
cat /etc/apt/sources.list.d/dotnetdev.list 
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
mkdir testweb
cd testweb
dotnet new -t web
dotnet restore
dotnet run
dotnet ef database update

### Further technical details
project.json
```
....
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0-preview1-001153-00",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
....
```

Database Provider: untouched template configuration -> sqlite
Operating system: UbuntuMate 2016.10
```
uname -a
Linux myHostname 4.8.0-30-generic #32-Ubuntu SMP Fri Dec 2 03:43:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
IDE: partially VisualStudio Code, mostly done by command line

I am wondering right now, even with the apt-get install command `sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177` now the template shows me `"version": "1.1.0-preview1-001153-00"`. And:
```
dotnet --version
1.0.0-preview2-1-003177
```

Now I got lost with all the different versions in the project.json, when to use 1.1.0 and when 1.0.0, when should it be preview[1-3]-final or even preview[1-3]-update[1-4] . 

How to update project.json to get the initial ASP.net core template working with saving to SQlite? Preferably .net core 1.1.0. So maybe https://www.microsoft.com/net/core#linuxubuntu shows an outdated install instruction?

**Comment by rowanmiller** [comment]
The main problem here is mixing 1.0 and 1.1 versions. If you are using .NET Core 1.1.0 then you should also be using 1.1.0 versions of ASP.NET Core and EF Core. This isn't specific to EF, but is just the general strategy for .NET Core versioning and support.

In particular, you want the `1.1.0-preview4-final` version of the tools packages.

cc @Rick-Anderson in case you want to clarify any of this in the ASP.NET docs

**Comment by MarkusEgle** [comment]
Just installed like described in https://www.microsoft.com/net/core#linuxubuntu and https://docs.microsoft.com/en-us/aspnet/core/getting-started

> sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
> mkdir testweb
> cd testweb
> dotnet new -t web

The versions got mixed by itself. 
project.json is right out of the box. I tried a few different settings in the project.json to correct it but with no success, as I got confused with all the `1.0.[x]-preview[y]` numbers. 
Where can I search for the different available tools install packages, to get the correct number for the apt-get install command? 
For Windows you should install `.NET Core 1.0.1 Tools Preview 2` to target `.Net Core 1.1.0`, correct?
What is the right available install version on Ubuntu 16.10? 
Searching through the repository I found 
https://apt-mo.trafficmanager.net/repos/dotnet-release/pool/main/d/dotnet-dev-1.0.0-preview3-004056/
but I failed to get a package named dotnet-dev-1.0.0-preview3 installed. 
How to install tools package `1.1.0-preview4-final` on Linux?

**Comment by nicomz** [comment]
Hi, just the same issue. The project runs fine on windows 10 (VS 2015) and command line tools as well. 
While running on linux, commandline tools (dotnet ef database update) throws same message.
`The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found...`

**Comment by saurabhnandu** [comment]
I face the same issue on Ubuntu 16. The docs only install previous version. They need to be updated. You can find the link to install the latest preview 4 version from here [ https://github.com/dotnet/core/blob/master/release-notes/preview4-download.md ]. Then if you have an existing project then run the dotnet migrate command to migrate it to latest project format and fix the package errors.

**Comment by MarkusEgle** [comment]
Since the last few weeks I tried several installations. 
With 
- Ubuntu 16.04.1 Server amd64
- Lubuntu 16.04 Desktop amd64
With 
- the manually downloaded and installed 4 packages from [https://apt-mo.trafficmanager.net/repos/dotnet-release/pool/main/d/](https://apt-mo.trafficmanager.net/repos/dotnet-release/pool/main/d/)
- tried several preview releases including the current `.NET Core SDK 1.0 Preview 4 build 004233`
- tried several latest packages [https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-ubuntu.16.04-x64.latest.tar.gz](https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-ubuntu.16.04-x64.latest.tar.gz)

Now it seems after creating the web template, that the account register area was dropped from the dotnet web template. 

Is it possible that there is no more entity framework part with sqlite in the web template so that the current occurring error 

`dotnet ef --version`
> No executable found matching command "dotnet-ef"

is not comparable with [https://github.com/aspnet/EntityFramework/issues/4797](https://github.com/aspnet/EntityFramework/issues/4797) because of missing `dotnet ef` configuration in `csproj`?

**Comment by rowanmiller** [comment]
Can folks hitting these issues follow the instruction from https://github.com/aspnet/EntityFramework/issues/7358 and then file new issues for any issues encountered. That issue is around testing of the RTM version of the tooling.
