### ISSUE TITLE
Pre-generated entity model binding support?

### ISSUE THREAD

**Issue by Opiumtm** [dotnet/efcore#7214]
Any plans to support pre-generated binding for entity models (pre-generated at compile time queries, code for populating entity values etc)?

For .NET Native on UWP and especially for local database access on mobile devices in UWP using of pre-generated code would greatly optimize performance.
.NET Native on UWP have issues with reflection speed and don't support IL code generation and JIT at run-time. LINQ Expressions isn't compiled to IL, but interpreted. LINQ Expressions performance on .NET Native isn't good. ARM mobile devices require good optimization as ARM CPU isn't as powerful as desktop x86 CPU.

**Comment by divega** [comment]
@Opiumtm we have consider all these improvements as part of https://github.com/aspnet/EntityFramework/issues/1906 and https://github.com/aspnet/EntityFramework/issues/241, which are currently in our backlog.

**Comment by divega** [comment]
**Note for triage:** I think there is overlap between this issue and the existing #1906 and #241 (and also between the latter two). But there is good information here about things we have discussed doing but that are not called out in the existing issues. 

I.e. I think we could probably track compiled models and any code we want to pre-generate (e.g. using Roslyn) in just one issue, and we should decide which issue to keep.

**Comment by rowanmiller** [comment]
Closing in favor of #1906
