### ISSUE TITLE
EF Tools throws "Unrecognized option '--build-base-path'" inside package manager console

### ISSUE THREAD

**Issue by Hoshinokoe** [dotnet/efcore#7215]
I have two projects in solution: asp.net core web and core class library that contains DataContext and migrations.

## The issue
It's not possible to generate migrations with v1.1.0.
The website is building and running successfully.

## Steps to reproduce:
1.  Upgrade nuget packages from v1.0.1 to v1.1.0.
2.  Use 'add-migration' to generate migrations or 'update-database' inside package manager console
3.  Error: **Unrecognized option '--build-base-path**

**project.json for web:**
```javascript 
{
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Newbor.Data": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "AutoMapper.Data": "1.0.0-beta1",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "FluentValidation": "6.4.0-beta8",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.Session": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha5"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config",
      "nlog.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**project.json for class library:**
```javascript
 {
  "version": "1.0.0-*",

  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha5"
    
  },
  
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  }
}
```

**Comment by bricelam** [comment]
Do you have projects in the same solution with a different version of `Microsoft.EntityFrameworkCore.Tools` installed?

**Comment by Hoshinokoe** [comment]
`Microsoft.EntityFrameworkCore.Tools` installed only in Class library project. Both projects in the same solution.

**Comment by Umplify** [comment]
Any ETA when this issue will be fixed? It has become a showstopper for the team. Not sure if we should upgrade packages or stick with older versions?

**Comment by jholovacs** [comment]
Blocking me too.

**Comment by teocomi** [comment]
I got it to work by running it from the command line and not from the package manager: `dotnet ef migrations add {MigrationName}`, make sure you have `C:\Program Files\dotnet\` in your PATH system variable first.

**Comment by divega** [comment]
We believe that this issue no longer exists in our current code. The workaround proposed above (use dotnet ef)  is the same we would recommend.

**Comment by dandax** [comment]
@divega Can you let us know how you tried to repro? I ran into the same issue. My solution has two projects: one is a data project that contains only EF entities and dbcontext, and the other is an MVC project. Try to run Update-Database on my Data project and it fails with the same error.

**Comment by divega** [comment]
@dandax I was referring to a more recent version of our tools which works with MSBuild based projects and @bricelam is working on. @bricelam may be able to provide more details.

**Comment by Hoshinokoe** [comment]
@bricelam When new version of tools will be available through nuget ?

**Comment by bricelam** [comment]
See #7358 for details on trying out the next release.
