### ISSUE TITLE
HasField method not working with MySQl EF Core 1.1

### ISSUE THREAD

**Issue by avikenjale** [dotnet/efcore#7223]
Error:
> Unhandled Exception: System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Micros
oft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger`1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.Diagn
osticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.

Project.json
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {},
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NETStandard.Library": "1.6.1",
        "Microsoft.EntityFrameworkCore.Relational":"1.1.0",
        "MySQL.Data.EntityFrameworkCore":"7.0.6-ir31"
      }
    }
  }
}
```

context file:

```C#
public DbSet<City> City {get;set;}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
         modelBuilder.Entity<City>()
                .Property(c => c.Dist)
                .HasField("_district");
}
```

Model.

```C#
public class City
{
        private string _district = string.Empty;
        public int Id { get; set; }
        public string Name { get; set; }
        public string CountryCode { get; set; }
        public string Dist { get; }
        public int Population { get; set; }
}
```

NOTE/ WORK AROUND:
If I take ""Microsoft.EntityFrameworkCore.Relational":"1.1.0",' line out from project.json and OnModelCreating() method from context file and make property proper in Model class. It works perefectly.

**Comment by rowanmiller** [comment]
The current pre-release of the official MySQL provider doesn't yet support the 1.1 release. They are working on an update. In the meantime, you could look at using the SapientGuardian provider, folks have been using that with 1.1.

**Comment by DonKiely** [comment]
Rowan: How is the Pomelo provider with 1.1?

Thanks,
Don

**Comment by rowanmiller** [comment]
I think I may have seen one issue filed where it tried to call a broken API, but now I can't find the issue.
