### ISSUE TITLE
EF Core 1.1 LinQ and Skip

### ISSUE THREAD

**Issue by sylvaincaillot** [dotnet/efcore#7242]
Hello,
Using VS 2015 and EntityFrameworkCore (1.1.0), I am trying to page my search results using the pagedList plugin from Sakura.
It doesn't work as I am getting an error with EF core.

The following query works fine:

```
IQueryable<SearchResultViewModel> SearchVM = (from item in _context.MyModel
                                                         select new SearchResultViewModel()
                                                         {
                                                             A = item.a,
                                                                B= item.b
                                                         });
            model.SearchResults = SearchVM.ToList();
            return model;
```

If I am adding a skip(10) to simulate the paging plugin for example:

```
IQueryable<SearchResultViewModel> SearchVM = (from item in _context.MyModel
                                                         select new SearchResultViewModel()
                                                         {
                                                             A = item.a,
                                                                B= item.b
                                                         }).Skip(10);

            model.SearchResults = SearchVM.ToList();
            return model;
```

I get the following error message:
```
An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll
Additional information: Incorrect syntax near 'OFFSET'.
```
What should be the correct syntax to skip records in EF core?

Thanks

S.

**Comment by sylvaincaillot** [comment]
OK found the solution.
As I am using SQL Server 2008 R2, I needed to add the following parameter for my context:
 optionsBuilder.UseSqlServer(_config["ConnectionStrings:MyConnection"], b => b.UseRowNumberForPaging());

UseRowNumberForPaging being needed for mssql less than 2012 as suggested [here](http://stackoverflow.com/questions/29995502/paging-with-entity-framework-7-and-sql-server-2008):

Thank you
S.

**Comment by ajcvickers** [comment]
@sylvaincaillot If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?

**Comment by sylvaincaillot** [comment]
Thank you @ajcvickers for the followup. I have migrated the database to SQL Server 2017 so I am not using the UseRowNumberForPaging parameter anymore.

**Comment by ajcvickers** [comment]
@sylvaincaillot Thanks for getting back to us. Appreciated.
