### ISSUE TITLE
MongoDB Provider

### ISSUE THREAD

**Issue by crhairr** [dotnet/efcore#7243]
I've been working on a personal ASP.NET project that uses MongoDB. I recently migrated to ASP.NET Core and wanted to migrate my MongoDB linq adapter to EntityFramework Core so I could integrate better with the ASP.NET Identity providers. I noticed that there was no official support for MongoDB so I pulled the source and took a few weeks to write my own provider. My first draft was on top of the public EF Core NuGet package, and I'm currently in the process of migrating it into the EntityFramework Core solution to take advantage of certain internal features.

My provider is really a glorified adapter between EF Core and the official MongoDB C# Driver. I've gotten it building within Korebuild, and I'm still in the process of expanding unit tests for the project beyond rudimentary query/store functionality tests. So far, it works well with a few caveats:
- Complex type support (integral to document databases) is lacking; I've worked around the issue, but in a way that makes the StateManager not correctly walk the object graph to detect hierarchical changes. Because of this, complex type properties have to be updated in their entirety. This should (hopefully) go away when the Complex Type feature is complete (assuming this feature supports deeply nested and not just single-level complex type properties).
- I haven't yet separated out a Non-Relational/Document layer (similar to Microsoft.EntityFrameworkCore.Relational) to handle common DocumentDB concerns so that it's easier to create other providers (eg: Couchbase), but this is relatively trivial.
- In order to keep my code clean and manageable while finalizing it, I haven't yet peppered it with XML doc comments about internal APIs that aren't meant to be directly consumed by end-users. This is a trivial copy-n-paste operation.

I know that a MonogDB provider is a major feature on the EF Core roadmap Still, I'm very interested in submitting what I've got, but I wanted to make sure that I wouldn't be stepping on any toes before I send a pull request. Worst-case scenario, I can maintain my own fork and publish my provider to my local NuGet feed until an official one is released.

**Comment by ErikEJ** [comment]
Why not create your own repo for it like most other third party EF Core providers?

**Comment by crhairr** [comment]
Due to time constraints, I can't currently commit to maintaining a third-party provider. I have just enough time to maintain my own provider for my own needs, or to contribute to an existing one (hence offering to submit what I have working so far so as to create an existing provider).
If the EF Core team hasn't released an official MongoDB provider by the time I do get more free time, I'll certainly revisit the option.

**Comment by rowanmiller** [comment]
This isn't something that our team wants to take on at this stage. If there are any volunteers in the community then we'd certainly be happy to help them take over the project (we work pretty closely with a number of provider writers).

**Comment by crhairr** [comment]
For anybody that's interested, this code is now in its own standalone repo:

https://github.com/crhairr/EntityFrameworkCore.MongoDb

**Comment by fleed** [comment]
Is this on the current roadmap?

**Comment by ajcvickers** [comment]
@fleed No.

**Comment by vslee** [comment]
You can vote for the issue here https://jira.mongodb.org/browse/CSHARP-3837
