### ISSUE TITLE
Unable to install using Nuget

### ISSUE THREAD

**Issue by brunoklein99** [dotnet/efcore#7247]
EFCore is the only package which I am unable to install. I get stuck trying to gather dependencies.

`Attempting to gather dependency information for package 'Microsoft.EntityFrameworkCore.1.1.0' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.6'`

**Comment by smitpatel** [comment]
@brunoklein99 - What kind of project are you using? Are you able to install other packages without wait?

**Comment by brunoklein99** [comment]
Yes, all other packages install normally.

**Comment by smitpatel** [comment]
Can you share repro project? I am not able to repro it in a new console application.

**Comment by brunoklein99** [comment]
What version of the Package Manager Console are you using? I am using 3.4.4.1321

**Comment by smitpatel** [comment]
`3.5.0.1484`

**Comment by brunoklein99** [comment]
Can I update it somehow? Or are you using 2017 RC?

**Comment by brunoklein99** [comment]
Resolved with `3.5.0.1996`

**Comment by smitpatel** [comment]
I m using VS2015 Update 3. You can download latest nuget from https://dist.nuget.org/index.html
