### ISSUE TITLE
dynamic columns configuration using EF

### ISSUE THREAD

**Issue by qianthinkover** [dotnet/efcore#7252]
When use code-first to develop ORM program,that will make static template for this db model,
if db table changes,the code-model will change either,so if there is one way to implement this dynamic columns mapping at run-time configuration ?

**Comment by divega** [comment]
@qianthinkover there are several features that could make working with dynamic models easier that are covered in this issue in the backlog: https://github.com/aspnet/EntityFramework/issues/2282. 

Within the current feature set, there is at least one thing that could help you easily make programmatic changes to the model, but it is limited to adding properties to the EF model without modifying the .NET classes:  the ability to defined "shadow state" properties:

``` C#
// OnModelCreating:
modelBuilder.Entity<Item>().Property<int>("Rating");

// Usage:
var item = context.Item.First(condition);
var rating = context.Entry(item).Property<int>("Rating").CurrentValue;
```
 We also have a rich metadata API that is lower level than the fluent API used in code first and which can be used to mutate the model in several ways. 

If the "source of truth" of your model is the database schema and you only need to make changes occasionally, you may be better of re-scaffolding the model.

Hope this helps.

**Comment by qianthinkover** [comment]
Yeah thanks for helping, Hope more features will achieved in future,
