### ISSUE TITLE
TPC Ignore throws unexpected exceptions due to MapDerivedTypes

### ISSUE THREAD

**Issue by npbenjohnson** [dotnet/efcore#7255]
I know this example isn't the best usage, but it's for back-loading ef into as a provider in legacy code. There may be more reasonable TPC scenarios this breaks, but I've only found this one.

Simple Data Structure:
```
namespace A {
  public class EfModel : EfModelBase {}
  public class EfModelBase : {
    public Guid? Id {get;set;}
    public Repository Repo {get; set;}
  }
}
namespace B {
 [Serializable()]
 public class ModelForOtherSystem : EfModel {}
}
```

Now using fluent conventions, 
1. EfModel is registered
2. `MapInheritedProperties()` is called on all registered entities
3. `Ignore()` is called on all `Repo` properties

When the model spins up, `MapDerivedTypes` causes `ModelForOtherSystem` to be mapped, but because it (purposely) wasn't added to the model, `MapInheritedProperties()` was never called against it, so it throws  "You cannot use Ignore method on the property 'Repo' on type 'B.ModelForOtherSystem' because this type inherits from the type 'A.EfModel'"

The message is also counter-intuitive, because Repo is mapped to the model in the message, but it isn't declared on it, which I think is fuzzy based on the word "on" and the fact that the error message contains namespaces which generally mean clr, not db, context.

I think the assumption that could fix this is that the derived types of TPC classes are themselves TPC classes?

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework6#170
