### ISSUE TITLE
multiple contexts against the same db results in both trying to create __MigrationHistory

### ISSUE THREAD

**Issue by MichaelMcKechnie** [dotnet/efcore#7260]
I have two DbContext subclasses for the two different contexts I want to use in my solution. Each is defined in their own project, with their own configuration class and contextKey.

With a new database, the second context throws an exception ("name is already used") because it tries to create the __MigrationHistory table - which already exists because it was created by the first context.

In System.Data.Entity.Migrations.History.HistoryRepository.QueryExists I see that the code first checks for any migrations that match the context key, then it checks for the existence of the __MigrationHistory table. Unfortunately, the second check doesn't happen because it's wrapped in an if (!_contextKeyColumnExists). 

I think the  if (!_contextKeyColumnExists) should be removed - the HistoryRepository.QueryExists() method should return true for a database that has a  _MigrationHistory table but does not have any migrations in it yet.

See ~line 462 in ([https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Migrations/History/HistoryRepository.cs]...)
```C#
    foreach (var schema in _schemas.Reverse())
    {
        using (var context = CreateContext(connection, schema))
        {
            _currentSchema = schema;
            _contextKeyColumnExists = true;

            // Do the context-key specific query first, since if it succeeds we can avoid
            // doing the more general query.
            try
            {
                using (new TransactionScope(TransactionScopeOption.Suppress))
                {
                    contextKey = contextKey.RestrictTo(_contextKeyMaxLength);

                    if (context.History.Count(hr => hr.ContextKey == contextKey) > 0)
                    {
                        return true;
                    }
                }
            }
            catch (EntityException)
            {
                _contextKeyColumnExists = false;
            }

            // If the context-key specific query failed, then try the general query to see
            // if there is a history table in this schema at all
            if (!_contextKeyColumnExists)
            {
                try
                {
                    using (new TransactionScope(TransactionScopeOption.Suppress))
                    {
                        context.History.Count();
                    }
                }
                catch (EntityException)
                {
                    _currentSchema = null;
                }
            }
        }
    }
}
finally
{
    DisposeConnection(connection);
}

return !string.IsNullOrWhiteSpace(_currentSchema);
```

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework6#171
