### ISSUE TITLE
Scaffold generating incorrect configuration on OnModelCreating

### ISSUE THREAD

**Issue by CamiloTerevinto** [dotnet/efcore#7265]
Using Microsoft.EntityFrameworkCore.* 1.1.0 and Tools version 1.1.0-preview4-final.
First problem that can be reproduced with in just a minute: 
Create a table, add a column of type decimal(X,Y) where Y != 0 and scaffold it => results in .HasColumnType("decimal") and the precision is completely ignored when saving to the database. This makes me have to check every single column for every table I scaffold every time. This also happens with numeric.

Expected:

`entity.Property(e => e.SomeValue).HasColumnType("decimal(10,2)");`

Actual:

`entity.Property(e => e.SomeValue).HasColumnType("decimal");`

And ignores precision (10.12 is stored as 10.00)

**Comment by ajcvickers** [comment]
@CamiloTerevinto This is a known issue being tracked by issue #5410
