### ISSUE TITLE
"Apply this migration on publish" option missing from Azure Publishing profile

### ISSUE THREAD

**Issue by Banashek** [dotnet/efcore#7276]
I initially created a new dotnet core mvc application in VS2017 using steps similar to the steps found here: https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs

There is an image on that page (found here: https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs/_static/pubs.png) that shows the ability to apply migrations on publishing.

I have lost that checkbox, along with the "Databases" and "Entity Framework Migration" arrow-drop-down menus (I still have the File Publish options).

I'm not sure how to troubleshoot this. I've looked up the issue and found a few resources:

- http://stackoverflow.com/questions/19664459/execute-code-first-migrations-checkbox-disappeared-from-my-publish-profile
- http://stackoverflow.com/questions/16543229/publish-entity-framework-code-first-migrations-with-no-context-in-the-startup-pr?answertab=active#tab-top
- https://msdn.microsoft.com/en-us/library/dd394698%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

However, I haven't found a solution and am not sure of what exactly makes these options appear in the publishing profile.

Is there any current (1.1.0 is pretty new, so i understand if not) documentation on this feature?

If not, is there someone who might be able to point me in the right direction to get this solved? It was completely unexpected that this would stop working in production.

Thanks

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10/Azure
IDE: Visual Studio 2017 RC

**Comment by Banashek** [comment]
Ok it looks like this is a known issue:

https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#migrations-not-applied-during-publish

So how would I go about manually applying these migrations? 

Since I'm using the new project type with vs2017 (no `dotnet ef` commands), I'm not sure the best way to do it.

I was told there used to be a `-Script` option to output a script, but it doesn't look like this option is available from the package manager console.

**Comment by Banashek** [comment]
So it looks like i missed a command that's available in the package manager called `Script-Migration`.

Using this command along with manually running the output against the azure sql instance allows me to continue working for now.

Is there any information on when the visual studio tooling issue might be fixed? It's not directly an issue for this repo, but this seems like the best place to ask.

**Comment by divega** [comment]
@balachir do you know if the issue in the known issues list is fixed?

**Comment by punkouter** [comment]
Yes. Just found this. So I guess I need to manually run the script on the azure db using Script-Migration until it works ?

**Comment by chadwackerman** [comment]
Bug status:

- no one assigned
- closed for no reason
- nobody responding

Further evidence that attempting projects of this scale on GitHub does not work well. Without exception every Microsoft bug I stumble upon is mismanaged. @rowanmiller

**Comment by divega** [comment]
@chadwackerman this was intentionally closed as external because it is not an EF Core issue but a tooling issue and the original poster pointed out it was already for in the known issue list at https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#migrations-not-applied-during-publish. 

Thanks for letting us know that it still repros. I will move it to the right repository.

**Comment by divega** [comment]
This issue was moved to aspnet/Tooling#988

**Comment by AtronSeige** [comment]
Create a appsettings.json file a ConnectionStrings property.
