### ISSUE TITLE
-Verbose doesnt seem to work

### ISSUE THREAD

**Issue by flashrider** [dotnet/efcore#7281]
There is no SQL generated with the use of -verbose. Command and output below:

PM> Update-Database -verbose
Build started...
Build succeeded.
Setting app base path C:\Projects\Project\src\Project.Web\.\bin\Debug\netcoreapp1.1
Finding DbContext classes...
Using context 'BrandliftContext'.
Done.
PM> 

Project.json:
{
  "version": "1.1.0-*",

  "dependencies": {
    "Project.Models": "1.1.0-*",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Project.Interface": "1.1.0-*"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  }
}

**Comment by bricelam** [comment]
That means that no migrations were applied to the database. To get the SQL of aplied migrations use the `Script-Migration` command.

**Comment by flashrider** [comment]
Okay. But tables where generated as expected with a migration. Thanks anyway, I will try with Script-Migration instead.

**Comment by divega** [comment]
Please reopen if by "But tables where generated as expected with a migration" you mean that in a specific execution of the command work happened but there was no output.

**Comment by flashrider** [comment]
Exactly so divega. The complete output of the command I received are listed above and no sql where printed to output window even though the tables where generated as expected.

**Comment by divega** [comment]
@bricelam do you think this is worth looking at or should we ask for a repro on the latest tools?

@flashrider would you be able to try this with our new bits? Details provided in #7358

**Comment by flashrider** [comment]
@divega sorry but I cant. Refactored my project to classic asp.net.
