### ISSUE TITLE
Using ID as Primary key and foreign key at same time.

### ISSUE THREAD

**Issue by brunneus** [dotnet/efcore#7291]
I have two entites, Prospect and person, what I'm trying to do is use Prospect.ID as primary key on ProspectTable  and as foreignkey of PersonID, my ideia is use the same ID for both entities without the need of a PersonID on my Prospect entity. When the prospect is being saved on database, it tries to save a PersonID even I not have this property on my Prospect entity, I would like to know if ef core supports this kind of relationship.

Here's what I got on my model builder.

` modelBuilder.Entity<ProspectDto>(builder =>
            {
                builder.ToTable("Prospects");
                builder.HasKey(prospect => prospect.ID);
            });`

`modelBuilder.Entity<PersonDto>(builder =>
            {
                builder.HasOne(p => p.Prospect).WithOne().HasForeignKey<ProspectDto>(pe => pe.ID);
            });`

Here's what is being executed on database:

`INSERT INTO [Prospects] ([ID], [PersonID])
VALUES (@p421, @p422),`

Thanks.

**Comment by ajcvickers** [comment]
@brunneus I created this console app using your code and I correctly get `ID` used as the foreign key. Maybe you can look at this and see what needs to be changed to reproduce the issue you are seeing?

```C#
public class ProspectDto
{
    public int ID { get; set; }
}

public class PersonDto
{
    public int ID { get; set; }

    public ProspectDto Prospect { get; set; }
}

public class PersonContext : DbContext
{
    public DbSet<ProspectDto> Blogs { get; set; }
    public DbSet<PersonDto> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(
            @"Server=(localdb)\mssqllocaldb;Database=CollectionsTest;Trusted_Connection=True;ConnectRetryCount=0");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<ProspectDto>(
                builder =>
                    {
                        builder.ToTable("Prospects");
                        builder.HasKey(prospect => prospect.ID);
                    });

        modelBuilder
            .Entity<PersonDto>(
                builder =>
                    {
                        builder
                        .HasOne(p => p.Prospect)
                        .WithOne()
                        .HasForeignKey<ProspectDto>(pe => pe.ID);
                    });
    }
}

class Program
{
    static void Main(string[] args)
    {
        using (var context = new PersonContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.GetService<ILoggerFactory>().AddProvider(new MyLoggerProvider());

            context.Add(new PersonDto { Prospect = new ProspectDto() });
            context.SaveChanges();
        }

        using (var context = new PersonContext())
        {
            foreach (var person in context.Set<PersonDto>().Include(e => e.Prospect))
            {
                Console.WriteLine("Person: {0}", person.ID);
                Console.WriteLine("Prospect: {0}", person.Prospect.ID);
            }
        }
    }
}

public class MyLoggerProvider : ILoggerProvider
{
    public ILogger CreateLogger(string categoryName) => new MyLogger();

    public void Dispose()
    {
    }

    private class MyLogger : ILogger
    {
        public bool IsEnabled(LogLevel logLevel) => true;

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
            => Console.WriteLine(formatter(state, exception));

        public IDisposable BeginScope<TState>(TState state) => null;
    }
}
```

**Comment by brunneus** [comment]
Hi @ajcvickers first of all thank you for the answer.

I tried your code, but without success, for some reason, the ef core is "guessing" that I need to have a PersonID on my prospect entity.

just one side note, on my prospect entity, I have a person property navigation.

Here's what my model looks like.


` public class PersonDto : DtoBase
    {
        public PersonDto()
        {
            
        }
    
        public ProspectDto Prospect { get; set; }
    }`


`public class ProspectDto : DtoBase
    {
        public ProspectDto()
        {

        }
        
        public PersonDto Person { get; set; } = new PersonDto();  
    }`

`public abstract class DtoBase
    {
        public Guid ID { get; protected set; }
    }`


And here is what ef core is trying to do.

`INSERT INTO [Prospects] ([ID], [PersonID)
VALUES (@p79, @p80),
(@p82, @p83,,
(@p85, @p86),
(@p88, @p89);

Invalid column name: PersonID`

**Comment by brunneus** [comment]
Just by adding an attribute ForeignKey("ID") on my ProspectDto everthing works.

Here's what my model looks like now.

` public class ProspectDto : DtoBase
    {
        [ForeignKey("ID")]
        public PersonDto Person { get; set; } = new PersonDto();
    }`

And no configuration onModelBuilder are need, this is a little weird actually, because what I was trying to do on modelBuilder is exactly what I did with the attribute, but for some reason it didnt work.

This behavior is some bug,  or I miss some configuration on OnModelBuilder?

Thanks.

**Comment by ajcvickers** [comment]
@brunneus The problem is in this piece of model building code:
```C#
modelBuilder
    .Entity<PersonDto>(
        builder => 
        {
            builder
                .HasOne(p => p.Prospect)
                .WithOne()
                .HasForeignKey<ProspectDto>(pe => pe.ID); 
        });
```

The call to WithOne without any argument tells EF to configure the relationship with no navigation property pointing from ProspectDto to PersonDto. Specifically, it tells EF that the ProspectDto.Person property is not associated with this relationship. EF therefore creates another relationship for this, including creating the FK for it.

To tell EF that the Person property is a navigation property for this relationship you need to add it to the WithOne call:
```C#
modelBuilder
    .Entity<PersonDto>(
        builder => 
        {
            builder
                .HasOne(p => p.Prospect)
                .WithOne(p => p.Person)
                .HasForeignKey<ProspectDto>(pe => pe.ID); 
        });
```

**Comment by breyed** [comment]
I think there's still a bug here in that EF sometimes assumes there is a foreign key property that doesn't really exist. In practice, I see it in a database-first scenario where SQL Server complains about an EF query containing a column that doesn't exist. The false column name is a concatenation of a navigation property and a key column.

I don't have a simple repro for the real-world case. Fortunately, there is simple repro that exposes what seems to be the same underlying bug. Consider a `Dog` entity and an corresponding extension entity, which is only present for certain superdogs:

	public class Dog
	{
		public int Id { get; set; }

		[ForeignKey("Id"), InverseProperty("Dog")]
		public DogEx DogEx { get; set; }
	}

	public class DogEx
	{
		public int Id { get; set; }

		[ForeignKey("Id")]
		public Dog Dog { get; set; }
	}

Building the DbContext fails with this error:

> Invalid relationship has been specified using InverseProperty and ForeignKey. The navigation 'Dog' in entity type 'DogEx' and the navigation 'DogEx' in entity type 'Dog' are related by InversePropertyAttribute but the ForeignKeyAttribute specified for both navigations have different values.

**Comment by smitpatel** [comment]
The given model is ambiguous. It doesn't specify which side is principal end. And `ForeignKey` attribute fails to resolve the ambiguity. Though exception message can be improved.

**Comment by breyed** [comment]
The same error occurs even if I specify the principle end using the Fluent API:

    builder.Entity<DogEx>().HasOne(e => e.Dog).WithOne(e => e.DogEx)
        .HasForeignKey<DogEx>(e => e.Id)
        .HasPrincipalKey<Dog>(e => e.Id);

However, if I use only the Fluent API and remove the annotations on the model, then I don't get the error at initialization. Instead EF tries to use `DogId` in its generated SQL for certain queries.

**Comment by smitpatel** [comment]
@breyed - It is ambiguous not just because of being one-to-one but also the property specified in FK attribute being present on both side. Whenever combination of `ForeignKeyAttribute` & `InverseProperty` causes ambiguous/incorrect model configuration, we throw exception because we don't know what to make out from those attribute. It cannot be overridden by fluent API, the attribute combination needs to be corrected to be consistent.

Therefore removing annotations removes the exception. If you specifying relationship using fluent API only and facing issues then please file a new issue with relevant details

**Comment by breyed** [comment]
I'm pretty sure now that the issues with EF trying to use nonexistent columns were due to `HasForeignKey` and `HasPrincipalKey` not being specified. Thanks for the help. Based on my experience, I added #7561 as a feature request to help with troubleshooting these kinds of problems.
