### ISSUE TITLE
Add a migrations warning for ValueGeneratedOnAdd for a non-key property for SqlServer

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#7295]
If a key property is configured as `ValueGeneratedOnAdd` without an explicit `ValueGenerationStrategy`, then it will fall back to the default `ValueGenerationStrategy` configured on the model, however it will have no effect on non-key properties, which might be confusing for users not closely familiar with these configuration options.
However it can still be a valid model if the user adds custom SQL to add a trigger or other mechanism to generate the value, therefore only a warning should be shown.

**Comment by divega** [comment]
**EF Team Triage:** We won't do this now but we can revisit if we get information from customers that indicates that the warning can help.

**Comment by divega** [comment]
If we ever do this we should consider generating a TODO comment.
