### ISSUE TITLE
log transaction commit / rollback

### ISSUE THREAD

**Issue by arielcloud** [dotnet/efcore#7313]
I'm using ef core in asp.net core app, enabled logging, and in my logs I can see every query my app do against db.

the problem is that for every transaction I can see in logs:

> [Debug] Beginning transaction with isolation level 'Unspecified'.

but I can't see later in logs any indication if this transaction committed, or rollback.

Is exists any config to do it automatically?
thanks!

**Comment by AndriySvyryd** [comment]
@arielcloud You should be able to see commit and rollback messages as well. Can you post project.json and relevant methods from `Startup.cs`?

**Comment by arielcloud** [comment]
startup.cs: 
in startup ():
` Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();`

in configure():
`loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            loggerFactory.AddSerilog();`

webApp project.json
`{
  "dependencies": {
    "AutoMapper": "5.2.0",
    "BL": {
      "target": "project"
    },
    "DataAccess": {
      "target": "project"
    },
    "Entities": {
      "target": "project"
    },
    "infra": {
      "target": "project"
    },
    "Serilog.Extensions.Logging": "1.4.0-dev-10136",
    "Swashbuckle": "6.0.0-beta902",
    "Serilog.Settings.Configuration": "2.2.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Serilog.Sinks.File": "3.1.1",
    "FluentValidation.AspNetCore": "6.4.0-beta9",
    "StructureMap.Microsoft.DependencyInjection": "1.3.0",
    "Serilog.Sinks.Email": "2.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.JsonPatch": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.AspNetCore.ResponseCompression": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Serilog.Sinks.Console": "2.1.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": true,
    "define": [],
    "nowarn": [ "1591" ]
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings*.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}`

entities project.json:
`{
  "version": "1.0.0-*",
  "frameworks": {
    "netcoreapp1.1": {}
  },
  "dependencies": {
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "FluentValidation.AspNetCore": "6.4.0-beta9",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  }
}`

10x!

**Comment by AndriySvyryd** [comment]
@arielcloud Thanks. Could you also provide `appsettings.json`? Make sure to strip any sensitive information from there if present.
Are you logging to a file?
Are you running in Debug or Release mode?

**Comment by arielcloud** [comment]
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "ConnectionStrings": {
    "BI": "Server=.\\SQLEXPRESS;Database=BI;Trusted_Connection=True;",
   },
  "Serilog": {
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "../../log.txt",
          "fileSizeLimitBytes": "1073741824"
        }
      }
    ]
  } 
}
```

as u can see, serilog logging into file.
I saw this on debug mode. now tested on release mode and it's the same.

tried also change all log levels on appsettings.json to trace, and no change.

**Comment by AndriySvyryd** [comment]
@arielcloud It seems to be an issue in Serilog.
You can see all the events if you enable Microsoft Debug-level logging by setting `"Microsoft"` to  `"Debug"` in `appsettings.json` and redirecting the console output to a file by setting `stdoutLogEnabled` to `"true"` and setting `stdoutLogFile` to an existing path in `web.config`, see https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module#log-creation-and-redirection
