### ISSUE TITLE
Decide what to do if we need context from services but it's registered under a base-type

### ISSUE THREAD

**Issue by rowanmiller** [dotnet/efcore#732]
There are going to be several places where we try and obtain a context from DI (migrations, database error page, and maybe others).

This is fine if the context is registered under it's exact type but gets harder if it's registered under something different (interface, base type, etc.). 

In the error page it just fails in these scenarios at the moment, but I think we should do something central and reuse it across the product. We could try the exact type, then walk up the inheritance chain.

**Comment by bricelam** [comment]
`AddDbContext<TContext>()` registers an instance of `IDbContextFactory<TContext>` under `IDbContextFactory` and the `TContext`.

Commands take advantage of this by...
1. Asking for `IEnumerable<IDbContextFactory>`
2. Looking at the `TContext` generic argument
3. Asking for `TContext`

**Comment by ajcvickers** [comment]
I don't think we need to do anything more on this at the moment. Our mechanisms for using AddDbContext and discovering contexts seem to work okay.

**Comment by rowanmiller** [comment]
👍
