### ISSUE TITLE
Limitations of DbSet.Local; DbContext.StateChange event needed.

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#7333]
As far as I know, LocalView is the only public EF Core class that provides a notification of change in state of entities. While it does an excellent job of providing a view of what the DbSet will (or should) look like after the next SaveChanges, a more general-purpose facility is needed. 

For example, say I want to process the Deleted entries just before doing a SaveChanges ... perhaps I want to  automatically add them to a different DbSet for audit purposes. Or perhaps I would like a variation on LocalView that includes the Deleted entries (with strikeout font) so that the user can see the entries that are about to be deleted. It's pretty hard to get the Deleted entries using LocalView, and iterating over the entire DbSet is not very efficient. 

More generally I would like to have a layer in my application that conducts a variety of appropriate validating, reverting, filtering, sorting, paging, and other activities, and these activities may require information about state transitions. While I can always iterate over the entire DbSet, this may not be sufficiently efficient and does not provide the previous as well as current state. 

The source code for LocalView tells us how to catch state transitions, however the APIs used are not public and therefore it would not be the best practice to rely on them. 

Of course, it is always possible to have your UI keep track of the state changes that it is causing, and then use this state change information appropriately further downstream in the application. However, if one of the main features of Entity Framework is state tracking, then why would it make sense for users to reproduce this functionality in their app? In addition this would clutter up the view models with a lot of record-keeping. 

My suggestion would be to add events to DbContext that are fired before and after each state transition of each entity, providing the entity entry and the before and after states. For efficiency you might want to have separate events for different ending states -- i.e. Added/Adding, Deleted/Deleting, Detached/Detaching, Attached/Attaching, Modified/Modifying, Reverted/Reverting events (the last would be for a transition to Unchanged state). 

Along with this I would suggest making OriginalValue part of the public interface. It is closely tied to the state tracking and it provides very useful information. Publically available documentation does not tell us the meaning of OriginalValue for each state. Can we have an OriginalValue of an Added entity property that is modified after the entity has been added?  

- sjb

**Comment by ajcvickers** [comment]
@sjb-sjb Thanks for the detailed comments. I think what you are asking for is covered by issue #626.

I suspect you are already aware of this, but you can `context.ChangeTracker.Entries<TEntity>()` to get state information for all entities of a given type--not sure if that is what you meant by iterating over all entities in the DbSet, but it is better than using the DbSet directly since it will never go to the database and will include Added entities.

Leaving this open to address your comments about documenting original values.

**Comment by sjb-sjb** [comment]
Thanks for the reply. I agree that conceptually 626 covers my request, and I am glad to have this linked to that topic. 

I would point out that there are existing hooks covering my ask, it's just that (a) they are not structured as DbSet events and (b) they are not part of the documented API. In addition I don't think that it is necessary to enable modifying entity state transitions on the fly (for example I don't see a need to cancel a state transition during the occurrence of the state transition). 

So this should be easier to action than the broader design around hooks discussed in 626, which to me looks like it goes more deeply into the guts of the db and presents the challenge of allowing modification of the action that is taking place.
