### ISSUE TITLE
Cannot execute this command because the version of Microsoft.EntityFrameworkCore.Design installed is not compatible with this tool.

### ISSUE THREAD

**Issue by jholovacs** [dotnet/efcore#7346]
I'm using PostgreSQL libraries, and this is driving me crazy.

I have a web application project, with .net 4.61 and .net core.
My domain entities are defined in a 'Common' project.
My db context is in a third project.

My application project.json file looks like this:

```
{
  "userSecretsId": "***********",

  "dependencies": {
    "BundlerMinifier.Core": "2.2.306",
    "MySolution.Common": "1.0.0-*",
    "MySolution.DataAccess": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Authentication.Google": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "System.Collections.Specialized": "4.3.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "define": []
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": ["bower install", "dotnet bundle"],
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  },

  "runtimes": {
    "win10-x64": {},
    "win8-x64": {}
  }
}
```

My data access project looks like this:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "MySolution.Common": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "NETStandard.Library": "1.6.1",
    "Npgsql.EntityFrameworkCore.PostgreSQL": "1.1.0",
    "Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.1.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  }
}
```

I have done successful migrations on previous versions, but now nothing I've tried works.  This is what I get in the Package Manager Console:

```
log  : Restore completed in 24467ms.
PM> add-migration AddressesAndPhones
Both Entity Framework Core and Entity Framework 6 are installed. The Entity Framework Core tools are running. Use 'EntityFramework\Add-Migration' for Entity Framework 6.
Cannot execute this command because the version of Microsoft.EntityFrameworkCore.Design installed is not compatible with this tool.
PM> 
```

As far as I can tell, I'm running the latest and greatest versions for all dependencies.  What am I missing, or can someone at least tell me where the problem might be?

Thanks

**Comment by bricelam** [comment]
Try moving `Microsoft.EntityFrameworkCore.Tools` to `dependencies` (not `tools`--confusing, I know).

**Comment by jholovacs** [comment]
@bricelam I just tried it, then ran `dotnet restore`, then the `add-migration` command.  Same message.

**Comment by bricelam** [comment]
Would you mind sharing your project so we can investigate further?

**Comment by jholovacs** [comment]
@bricelam I gave you access to it, let me know who else needs it; I don't want to open it up to the world.  At this point it's a skeleton (trying to port/ improve an existing application to .NET Core but keep getting hung up on infrastructure) but it will eventually have proprietary code in it.

**Comment by bricelam** [comment]
Hmm... I'm not able to reproduce the error.

    PM> Add-Migration Test -Verbose
    Build started...
    Build succeeded.
    Setting app base path C:\Projects\YourProject\YourProject.Application\bin\Debug\netcoreapp1.0
    Finding DbContext classes...
    Using context 'ApplicationDbContext'.
    Writing migration to 'C:\Projects\YourProject\YourProject.DataAccess\Migrations\20170106182522_Test.cs'.
    Writing model snapshot to 'C:\Projects\YourProject\YourProject.DataAccess\Migrations\ApplicationDbContextModelSnapshot.cs'.
    To undo this action, use Remove-Migration.

I had YourProject.Application selected as the startup and YourProject.DataAccess selected as the default project in PMC.

Ensure you have the [latest .NET Core SDK](https://www.microsoft.com/net/download/core#/current) and [Runtime](https://www.microsoft.com/net/download/core#/current/runtime) installed.

**Comment by jholovacs** [comment]
...well that sucks.  Maybe I have something stuck in cache.

**Comment by jholovacs** [comment]
@bricelam can you tell me how your VS is configured?  I installed the latest SDK and runtimes from the link you provided, and rebooted my machine.  I then wiped out the solution on my file system, re-cloned it from github, built it, and in the PMC I set the default project (the application project was the startup) to the DataAccess project, and the following is the result.  Perhaps there's another component that I'm missing?

Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

```
Package Manager Console Host Version 3.5.0.1996

Type 'get-help NuGet' to see all available NuGet commands.

PM> add-migration AddressesAndPhones -Verbose
Build started...
Build succeeded.
The specified deps.json [C:\projects\MySolution\MySolution.Application\bin\Debug\netcoreapp1.0\MySolution.Application.deps.json] does not exist
Process finished with non-zero exit code
PM> 
```

**Comment by bricelam** [comment]
That looks like the standalone app issue. Ensure your `project.json` files **don't** have a `runtimes` section, and that the dependency on `Microsoft.NETCore.App` looks like this.

```JSON
"Microsoft.NETCore.App": {
  "type": "platform",
  "version": "1.1.0"
}
```

**Comment by bricelam** [comment]
Also, if you're ready to switch to VS 2017, you can try out the latest bits. See #7358 for details.

**Comment by jholovacs** [comment]
Thanks for walking me through this.  That made a huge difference.  I also had to update my global.json file to look like this:

{
  "projects": [],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}

...since I had updated my SDK per your recommendation.  It was almost anticlimactic when it generated the schema and subsequently updated the db.
