### ISSUE TITLE
Cannot insert/update entities with sequence key

### ISSUE THREAD

**Issue by Dixin** [dotnet/efcore#7349]
If a table has a sequence column, EF Core cannot insert/update entities for the table. Take [Microsoft SQL Server 2016 sample database "Wide World Importers"](https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/wide-world-importers) as example:
```c#
[Table("StockItems", Schema = "Warehouse"]
public partial class StockItem
{
    [Key]
    [DatabaseGenerated(???)]
    public int StockItemID { get; set; }
    // Not identity column, but sequence column:  
    // DEFAULT (NEXT VALUE FOR [Sequences].[StockItemID]) FOR [StockItemID]

    [MaxLength(100)]
    [Required]
    public string StockItemName { get; set; }

    public decimal UnitPrice { get; set; }

    public int? SupplierID { get; set; }
}
```

Here `StockItemID` is a sequence column
* If it is marked as `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]`, EF Core generates `scope_identity()` for update operation, which returns `NULL`, and the update operation fails.
```sql
exec sp_executesql N'SET NOCOUNT ON;
UPDATE [Warehouse].[StockItems] SET [StockItemName] = @p0, [UnitPrice] = @p1
WHERE [StockItemID] = @p2 AND [RowVersion] = @p3;
SELECT [StockItemID], [RowVersion]
FROM [Warehouse].[StockItems]
WHERE @@ROWCOUNT = 1 AND [StockItemID] = scope_identity();

',N'@p2 int,@p3 varbinary(8),@p0 nvarchar(100),@p1 decimal(3,0)',@p2=325,@p3=0x0000000000012883,@p0=N'Name1',@p1=555
```
* If it is marked as `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]`, EF Core generates `scope_identity()` for insert operation, which returns `NULL`, and the insert operation fails.

How to insert/update entities for table with sequence column? Any workaround?

**Comment by ajcvickers** [comment]
@Dixin You need to tell EF that the column is set up to generate values using something like:
```C#
modelBuilder
    .Entity<StockItem>()
    .Property(e => e.StockItemID)
    .HasDefaultValueSql("NEXT VALUE FOR [Sequences].[StockItemID]");
```

(Note that EF at runtime doesn't actually care what string you pass to HasDefaultValueSql; it just has to know that there is something there in the database. The string passed will be used if you ever use Migrations to create the database.)
