### ISSUE TITLE
How to get Database Column type in EF 1.1?

### ISSUE THREAD

**Issue by mgolois** [dotnet/efcore#7351]
Hello,

I am working in a .netcore EF Core 1.1 app and I would like to loop through the properties of a given entity before saving in order to get each property database column type. Is it possble? if so, how should I approach this?
Thanks,

Golois

**Comment by ajcvickers** [comment]
@mgolois Assuming you have an entity instance called `entity` and the DbContext as `context`, then this should work:
```C#
var typeMapper = context.GetService<IRelationalTypeMapper>();

foreach (var property in context.Entry(entity).Metadata.GetProperties())
{
    Console.WriteLine(typeMapper.FindMapping(property).StoreType);
}
```
