### ISSUE TITLE
No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by mrozado** [dotnet/efcore#7357]
I have changed my ASP.NET Core app to target .Net 4.5.2 (before it was a Net Core app) in order to support WCF Relay.

I have the Migrations and DB Context in a different project (With the Program.cs and everything) and was working fine before changing the target and updating.

Now, after upgrading EF Core and changing the target of the solution I get the message in the title. 

Here is my project.json
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.1.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Newtonsoft.Json": "9.0.1"
  },

  "frameworks": {
    "net452": {}
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"
  }
}
```

I have checked some other issue reports, and a lot of them say move to Tools.DotNet but I can't  because the app is targeting .net 4.5.2

### Further technical details
EF Core version: 1.1.0
Database Provider: SQL Express 2016
Operating system: Win 10
IDE: VS 2015 update 3

**Comment by mrozado** [comment]
I can't update Tools to Tools.DotNet because the app is targeting .net 4.5.2

**Comment by bricelam** [comment]
Update your `tools` section to include `.DotNet`. You'll also need to use preview3 because of #7071

```json
{
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  }
}
```

**Comment by mrozado** [comment]
@bricelam I did and the following appeared

> Cannot execute this command because 'Microsoft.EntityFrameworkCore.Tools' is not installed in project 'src\CAP.ShipsLogisticsManager.Data'. Add 'Microsoft.EntityFrameworkCore.Tools' to the 'tools' section in project.json. See http://go.microsoft.com/fwlink/?LinkId=798221 for more details.

**Comment by bricelam** [comment]
Ensure you also have the [LTS .NET Core Runtime](https://www.microsoft.com/net/download/core#/runtime) installed.

**Comment by mrozado** [comment]
Ok, after doing that on my pal's machine worked

**Comment by mrozado** [comment]
Thank you mate!

**Comment by bricelam** [comment]
No problem. Sorry for all the trouble! We know it's painful, and we're working hard to make it great.
