### ISSUE TITLE
After EF and Identity EF upgrade, Add-migration removes Indexes and FK

### ISSUE THREAD

**Issue by mrozado** [dotnet/efcore#7369]
After upgrading EF from 1.0.1 to 1.1 and Identity the same, the first Add-migration I do removes like 5 indexes and 2 FK. And adds only 3 in the same Up method.
Out of these 5 Indexes removed, like 2 of them are from Identity origin (Role table)

Is this possible? Any ideas?

### Further technical details
EF Core version: 1.1
Database Provider: SQL Express 2016
Operating system: WIN10
IDE: VS2015

**Comment by mrozado** [comment]
Tryied rolling back the version of EF Core to 1.0.1 but:
Microsoft.EntityFrameworkCore.Tools.DotNet is not working:
> Cannot execute this command because 'Microsoft.EntityFrameworkCore.Tools' is not installed in project 

And using the old Microsoft.EntityFrameworkCore.Tools says 
> No executable found matching command "dotnet-ef"

**Comment by divega** [comment]
@mrozado can you provide more details, e.g. what indexes get removed? We did some work in 1.1.0 so that redundant indexes would not be created.

**Comment by mrozado** [comment]
Yes, after researching a bit it seams to me what you said is what actually happened. Thank you

**Comment by divega** [comment]
Thanks for confirming @mrozado.
