### ISSUE TITLE
Allowing Partial Update of a model

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#7370]
While updating a model (table), we have to fetch the entire model and then update a relevant field in the database. Otherwise, it will update all the other fields as default values in the model.

Will EF allow only selected fields to be updated from a model.

If I have an Employee model with fields
Id
FirstName
LastName
Age....etc,

Can I update only the field "Age" without fetching the entire model from database.

**Comment by ajcvickers** [comment]
@satyajit-behera Attach the entities and then mark appropriate properties with something like:
```C#
context.Entry(myEntity).Property(e => e.Age).IsModified = true;
```

**Comment by everestto** [comment]
s

**Comment by everestto** [comment]
And when it's a collection type, use Collection in place of property.

context.Entry(myEntity).Collection(e => e.Age).IsModified = true;

**Comment by everestto** [comment]
And when it's a collection type, use Collection in place of property.

context.Entry(myEntity).Collection(e => e.Images).IsModified = true;
