### ISSUE TITLE
Adding new model to existing ones using Code First

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#7378]
Currently I achieve the above - `using EF Core` - as follows.

**Question**: Is it the right approach in order to keep the data in the exiting tables intact. I feel I'm doing it rather a long-winded way. Any suggestions on alternate/correct ways of doing it?

 1. Create a new entity (model) and add a corresponding `DbSet<...>` entry in `myProjectContext.cs` file
 2. Delete existing migration from VS2015 and corresponding record in `__EFMigrationsHistory` table from the SQL Server Db
 3. Run `PM> add-migration mytMigration -context myProjectContext`
 4. Comment out all the code in newly generated `mytMigration.cs` file except the code related to newly generated entity (model).
 5. Run `PM> update-database -context myProjectContext`

New table (corresponding to newly added entity) gets created in the exiting Db along with new `__EFMigrationsHistory` table. Data in all the existing tables remains in tact.

**Comment by divega** [comment]
@saf-itpro you should be able to add an entity and create a new migration. When this migration is applied it will not affect data in existing tables.

In summary, you don't need steps 2 and 4.

**Comment by saf-itpro** [comment]
@divega Your suggestion worked. Thank you specifically for briefly explaining what I need to do and that why it will work.
