### ISSUE TITLE
Runtime error (System.Runtime 4.2.0.0 not found) using nightlies

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#7379]
As per https://github.com/dotnet/cli/issues/5242 - have narrowed down my issue to the EF Core preview1 packages.

Exception when using `dotnet run` is as follows:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

If there's some guidance, notes or announcement I missed would you mind pointing me to it?  Have been happily running nightlies until I pushed a new build of my app to Azure a few days ago, whereupon some new version caused this issue for me.

### Further technical details
EF Core version: Remind me how to do this for VS2017 please?  There is no packages.config or project.json.  is there a lock file?
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: `Win 10`
IDE: Commandline ... but also VS2017

**Comment by divega** [comment]
Did the comment at https://github.com/dotnet/cli/issues/5242#issuecomment-271316426 address your issue?

**Comment by kierenj** [comment]
Yes, however I'd like to understand what I could have done to avoid falling into this trap.

Is there some announcement repo or place to look for notices around updates to the nightly EF Core builds which mandate changes in consumers of them, e.g. a point where a new version of the runtime is required?

My main issue is that I was happily running 1.1 on an Azure App Service, until I ran into more EF bugs - so I switched to the nightlies out of necessity, which worked well until this point.  App Services don't have the 1.2.0 runtime and I've been battling to find out their update schedule.  So I feel that a working version and running on an App service are mutually exclusive.

Another solution would be if there are any maintenance/services releases for the 1.1.0 EF packages, with any fixes merged back there?  It looks like there is activity on `rel/1.1.1`, is that likely to include fixes - and I don't suppose it's built by CI somewhere?

**Comment by divega** [comment]
> Is there some announcement repo or place to look for notices around updates to the nightly EF Core builds which mandate changes in consumers of them, e.g. a point where a new version of the runtime is required?

Nightly builds are by definition getting lots of changes every day, some of which are changes in dependencies. Things are expected to move rapidly and to break. It is hard to think of a comprehensive approach for this that wouldn't create a lot of overhead but we could discuss something like labeling PRs that we believe are going cause certain kinds of breaks, e.g. having to upgrade dependencies.

> So I feel that a working version and running on an App service are mutually exclusive.

@muratg Are familiar with this? Any thoughts?

> I switched to the nightlies out of necessity...  It looks like there is activity on rel/1.1.1

Are there specific bugs that you are tracking? Bugs assigned to 1.1.1 milestone either are going to be fixed there or are being investigated to understand if they are regressions. For any other issues that are fixed in 2.0 but not in 1.1, consider asking for a workaround. 

The feed for patch releases is https://dotnet.myget.org/F/aspnetcore-patch/api/v3/index.json, but I am not sure what has made it there.

**Comment by muratg** [comment]
>>So I feel that a working version and running on an App service are mutually exclusive.

>@muratg Are familiar with this? Any thoughts?

I would phrase it differently: nightly builds of the SDK and the runtime are not deployed to Azure App Service.  Azure App Service is updated only when there's a public release.

If you'd like to still deploy with nightlies, you can build your app as a "standalone" app, i.e. packing and deploying the runtime itself with your app. Just a reminder though, only public RTM releases are considered "officially supported".

**Comment by muratg** [comment]
@kierenj, in case you're interested in "standalone" (AKA self-contained apps):

- For project.json based projects, Scott Hanselman has a blog post: http://www.hanselman.com/blog/SelfcontainedNETCoreApplications.aspx
- For csproj projects: https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/deploying/

**Comment by minhyentcu** [comment]
gfd
