### ISSUE TITLE
Updating fails when using an identity column that is not a key

### ISSUE THREAD

**Issue by VladDragnea** [dotnet/efcore#7380]
I define an entity like this:
```c#
public class Entity
{
    public Guid ID { get; set; }
    public int ClusteredId { get; set; }
    public string SomeText { get; set; }
}
```
and a context like this:
```c#
public class SomeContext : DbContext
{
    public DbSet<Entity> Entities { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Entity>(b => {
            b.HasKey(x => x.ID).ForSqlServerIsClustered(false);

            // With the following two lines the update FAILS
            b.Property(x => x.ClusteredId).UseSqlServerIdentityColumn();
            b.HasIndex(x => x.ClusteredId).IsUnique().ForSqlServerIsClustered();

            //// With the following two lines the update works
            //b.Property(x => x.ClusteredId).UseSqlServerIdentityColumn().ValueGeneratedOnAddOrUpdate();
            //b.HasIndex(x => x.ClusteredId).IsUnique().ForSqlServerIsClustered();

            //// With the following two lines the update works
            //b.Property(x => x.ClusteredId).UseSqlServerIdentityColumn();
            //b.HasAlternateKey(x => x.ClusteredId).ForSqlServerIsClustered();
        });
    }
}
```
If i use this context in the following way, it will fail on the second SaveChanges(), because EF will generate SQL to update the ClusteredId column.
```c#
Entity entity = new Entity { SomeText = "Some Text" };
context.Entities.Add(entity);
context.SaveChanges();
context.Entities.Update(entity);
context.SaveChanges();
```
```SQL
exec sp_executesql N'SET NOCOUNT ON;
UPDATE [Entities] SET [ClusteredId] = @p0, [SomeText] = @p1
WHERE [ID] = @p2;
SELECT @@ROWCOUNT;
',N'@p2 uniqueidentifier,@p0 int,@p1 nvarchar(4000)',@p2='...',@p0=1,@p1=N'Some Text'
```
If, when defining the model, I either specify ValueGeneratedOnAddOrUpdate() for the ClusteredId property, or use an alternate key instead of a unique index on the same property, then the code will work, but in my oppinion either one of those two changes should not be neccessary.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by divega** [comment]
@AndriySvyryd can you investigate this? Feel free to move to a different milestone if it turns out to be something we should fix earlier than 2.0.0.

**Comment by szavoda** [comment]
Just confirming that this is an issue.  For anyone that stumbles on this and is trying to find the correct references to use the workaround mentioned above, make sure you have installed the Microsoft.EntityFrameworkCore.SqlServer (1.1.1) package.

**Comment by AndriySvyryd** [comment]
This model is not supported and we now detect this in validation.
The correct workaround is to define an alternate key.

But do let us know if you need this and an alternate key wouldn't work for your scenario.

**Comment by szavoda** [comment]
A common case that is a problem is where you have an order where you want the 'id' field to be a GUID / Uniqueidentifier and you want an 'OrderNumber' field which is an auto-incremented integer.

Can you clarify that this is not supported?  Additionally, would there be an alternative?

**Comment by AndriySvyryd** [comment]
@szavoda In that case why couldn't you define an alternate key on `OrderNumber`?

Enabling value generation on non-key properties would require non-trivial code changes in EF. But since it's possible to define an alternate key on pretty much any property we don't believe there's much value in enabling the non-key scenario.

**Comment by ajcvickers** [comment]
@AndriySvyryd Agree that `UseSqlServerIdentityColumn` is only supported on keys, but if the property is marked as `ValueGenerated.OnAdd` and there is no other column that is an Identity column, then I believe that:
* It should work in the update pipeline
* Migrations will still try to create an Identity column on SQL Server. @bricelam can you confirm this?

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes, if the property is of a compatible type, has ValueGenerated.OnAdd, doesn't have any default value, the model is using Identity as default and there's no other Identity column in the table then Migration will create it as Identity

**Comment by ajcvickers** [comment]
@AndriySvyryd So this modification to the code should work, correct?
```C#
builder.Entity<Entity>(b => {
    b.HasKey(x => x.ID).ForSqlServerIsClustered(false);

    // With the following two lines the update FAILS
    b.Property(x => x.ClusteredId).ValueGeneratedOnAdd();
    b.HasIndex(x => x.ClusteredId).IsUnique().ForSqlServerIsClustered();
```

**Comment by AndriySvyryd** [comment]
Yes

**Comment by AndriySvyryd** [comment]
@ajcvickers No, I just looked at the code and it still needs to be a key.

**Comment by bricelam** [comment]
> ...if the property is marked as ValueGenerated.OnAdd and there is no other column that is an Identity column, then I believe that...Migrations will still try to create an Identity column on SQL Server.

Incorrect. Migrations will create an `IDENTITY` column if and only if the property's `SqlServer:ValueGenerationStrategy` annotation has a value of `IdentityColumn`.

**Comment by ajcvickers** [comment]
@bricelam I believe @AndriySvyryd has now made this consistent--Migrations will get that annotation, even for non-key columns.

**Comment by bricelam** [comment]
Yep, I just saw that. 😄 ...catching up after being heads down last week...

**Comment by malhaar-p** [comment]
It is really good to update EF Core framework time by time rather updating too late. 

I am using EF Core 2.1, I tried this.

builder.Property(e => e.ColumnName).Metadata.AfterSaveBehavior = PropertySaveBehavior.Ignore;
It worked for me.

EF Core 2.1 is stable, and enough updates to cater most of the problems.

**Comment by lobbo232** [comment]
I seem to be encountering this in EF Core 8.0.5. Has something changed recently? Only difference for me is I'm using a scaffolded db context and entities.

**Comment by bastam** [comment]
I use EF Core 9.0.1 and use Scaffold-DbContext. I have the same issue where an identity column is not the primary key. It only works when I make the field the PK in tis table. But changing all my tables so that their identity column is a primary is not an option. Is there a solution to this?
