### ISSUE TITLE
using EF, C# data doesn't match SQL Server db result

### ISSUE THREAD

**Issue by JayGuAtGitHub** [dotnet/efcore#7382]
### Steps to reproduce
you can use the following sql script to generate the test data(the database Saron is set as default)
[EF bug.sql.txt](https://github.com/aspnet/EntityFramework/files/695109/EF.bug.sql.txt)

```c#
            using (var db = new SaronEntities())
            {
                var q =
                from l in db.MiscTableCatalog
                join r in db.MiscTableRelatedFile on l.Id equals r.MiscId into rt
                from r in rt.DefaultIfEmpty()
                where l.TableName != null && l.TableName != ""
                select new
                {
                    MiscTableRelatedFile = r,
                    MiscTableCatalog = l
                };
                var x= q.ToList();
            }
```

watch q.ToString(), the sql is as below:

SELECT 
    1 AS [C1], 
    [Extent2].[MiscId] AS [MiscId], 
    [Extent2].[FileName] AS [FileName], 
    [Extent2].[File] AS [File], 
    [Extent1].[Id] AS [Id], 
    [Extent1].[NameCn] AS [NameCn], 
    [Extent1].[NameEn] AS [NameEn], 
    [Extent1].[ParentId] AS [ParentId], 
    [Extent1].[SeqNbr] AS [SeqNbr], 
    [Extent1].[TableName] AS [TableName], 
    [Extent1].[DataSourceEn] AS [DataSourceEn], 
    [Extent1].[DataSourceCn] AS [DataSourceCn], 
    [Extent1].[DefaultCheck] AS [DefaultCheck]
    FROM  (SELECT 
    [MiscTableCatalog].[Id] AS [Id], 
    [MiscTableCatalog].[NameCn] AS [NameCn], 
    [MiscTableCatalog].[NameEn] AS [NameEn], 
    [MiscTableCatalog].[ParentId] AS [ParentId], 
    [MiscTableCatalog].[SeqNbr] AS [SeqNbr], 
    [MiscTableCatalog].[TableName] AS [TableName], 
    [MiscTableCatalog].[DataSourceEn] AS [DataSourceEn], 
    [MiscTableCatalog].[DataSourceCn] AS [DataSourceCn], 
    [MiscTableCatalog].[DefaultCheck] AS [DefaultCheck]
    FROM [dbo].[MiscTableCatalog] AS [MiscTableCatalog]) AS [Extent1]
    LEFT OUTER JOIN [dbo].[MiscTableRelatedFile] AS [Extent2] ON [Extent1].[Id] = [Extent2].[MiscId]
    WHERE ([Extent1].[TableName] IS NOT NULL) AND ( NOT ((N'' = [Extent1].[TableName]) AND ([Extent1].[TableName] IS NOT NULL)))

watch the result:
![ef bug fig 1 - result from ssms following q tostring](https://cloud.githubusercontent.com/assets/9403854/21791710/abbafd62-d71f-11e6-89a9-ec93a0fe790a.png)

first line:
C1	MiscId	FileName	File	Id	NameCn	NameEn
1	NULL	NULL	NULL	9451af71-37ab-4f1e-9288-0ba3b76898ef	河北	Hebei
the 20th line:
C1	MiscId	FileName	File	Id	NameCn	NameEn
1	NULL	NULL	NULL	a7871184-1827-435d-82f4-4cdd1eae8924	河北	Hebei

watch the x in IDE:
![ef bug fig 2 - result from vs 2013 following the variable x](https://cloud.githubusercontent.com/assets/9403854/21791712/af949eac-d71f-11e6-863d-c983b93d8e89.png)
first line:
		Id	"9451af71-37ab-4f1e-9288-0ba3b76898ef"	string
		NameCn	"河北"	string
		NameEn	"Hebei"	string
20th line:
		Id	"9451af71-37ab-4f1e-9288-0ba3b76898ef"	string
		NameCn	"河北"	string
		NameEn	"Hebei"	string

And it can also be reproduced in my production environment (IIS, windows server 2008, same EF config, SQL Server 2014)

Besides, if i remove the "duplicated" data (either in 9451af71-37ab-4f1e-9288-0ba3b76898ef, hebei and a7871184-1827-435d-82f4-4cdd1eae8924, hebei), it will be fine.

### Further technical details
EF Core version: 
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
</packages>
Database Provider: see in config section
Database: SQL Server 2014
Operating system: windows 7; windows server 2008
IDE: Visual Studio 2013
Config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
  <connectionStrings>
    <add name="SaronEntities" connectionString="metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=***;initial catalog=***;persist security info=True;user id=***;password=***;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
</configuration>

**Comment by maumar** [comment]
This issue was moved to aspnet/EntityFramework6#175
