### ISSUE TITLE
How can I know if the application is invoked by ef cli?

### ISSUE THREAD

**Issue by thiennn** [dotnet/efcore#7387]
I am writing an entity framework configuration provider, similar to the doc https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration#simple-sample-of-entity-framework-custom-provider

I am facing an issue when run ef migration command, because at that time the db connection might not be ready or the table has not been created yet. 

And I would like to know whether there are some mechanism to detect if the application is invoked by the ef cli so that I can skip adding this ef config provider.

For example

```cs
if(!invokedByEfCLI) {
           builder.AddEntityFrameworkConfig(options =>
                options.UseSqlServer(connectionStringConfig.GetConnectionString("DefaultConnection"))
            );
}
```

**Comment by rowanmiller** [comment]
@bricelam any thoughts on this one?

**Comment by thiennn** [comment]
Just take a look at the https://github.com/aspnet/EntityFramework/blob/master/src/Microsoft.EntityFrameworkCore.Design/Internal/OperationExecutor.cs. 

The environment variable DataDirEnvName = "ADONET_DATA_DIR" is set everytime a EF CLI command run. So I have tried

```cs
if (Environment.GetEnvironmentVariable("DataDirEnvName") != "ADONET_DATA_DIR")
{
        builder.AddEntityFrameworkConfig(options =>
              options.UseSqlServer(connectionStringConfig.GetConnectionString("DefaultConnection"))
       );
}
```
and it worked. But still wonder if there is a better way

**Comment by bricelam** [comment]
A better way might be to implement `IDbContextFactory<MyDbContext>` in the same assembly and pass in a flag to your DbContext.

```C#
class MyContextFactory : IDbContextFactory<MyDbContext>
{
    MyDbContext Create(DbContextFactoryOptions options)
        => new MyDbContext(isDesignTime: true);
}
```

Note, you can do more in the `Create` method too (like calling `Startup.ConfigureServices` and getting the `DbContext` from there) the `options` parameter has properties like `ContentRootPath` and `EnvironmentName`.

**Comment by sopelt** [comment]
@ajcvickers isn't this implemented now through https://github.com/dotnet/efcore/blob/767bc93c6e6fca19868f486c7df8f4235bcf53cd/src/EFCore/EF.cs#L41 now? Just to have the reference here.
