### ISSUE TITLE
SSLv3 method not defined

### ISSUE THREAD

**Issue by raphi011** [dotnet/efcore#7395]
Hi! I'm trying to access an SQL Server via EF on Arch Linux and the following error occurs.

```
Exception message:

/opt/dotnet/dotnet: relocation error: /opt/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Security.Cryptography.Native.OpenSsl.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
```

I know Arch Linux is not supported but maybe you guys have a hint so I may be able to fix this.

### Steps to reproduce

Execute an arbitrary EF statement

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Arch Linux
IDE: (e.g. Visual Studio Code)

**Comment by divega** [comment]
@raphi011 Probably a good idea to ask this over at https://github.com/dotnet/corefx/issues.
