### ISSUE TITLE
Migrations remove with ef.exe on UWP doesn't seem to do anything

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#7404]
> bin\x86\Debug\ef.x86.exe migrations list --assembly .\bin\x86\Debug\EFTest.exe --no-appdomain
20170111221928_First
20170111224048_SecondII
20170111224906_Three
20170112224751_MyTestMigAgain

> bin\x86\Debug\ef.x86.exe migrations remove --assembly .\bin\x86\Debug\EFTest.exe --no-appdomain
Reverting model snapshot.
Done.

> bin\x86\Debug\ef.x86.exe migrations list --assembly .\bin\x86\Debug\EFTest.exe --no-appdomain
20170111221928_First
20170111224048_SecondII
20170111224906_Three
20170112224751_MyTestMigAgain

**Comment by bricelam** [comment]
I am not able to repro this. I suspect the project wasn't rebuilt after removing the migration, so the list of migrations was still "cached" in the assembly.
