### ISSUE TITLE
Migrations Add with ef.exe doesn't create blank migration when no changes

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#7405]
In this case a migration was needed and was added:

> ef.x86.exe migrations add MyTestMig --assembly .\EFTest.exe --no-appdomain
Done. To undo this action, use 'ef migrations remove'

In this case there were no changes and no migration was added:

> ef.x86.exe migrations add MyOtherTestMig --assembly .\EFTest.exe --no-appdomain
Done. To undo this action, use 'ef migrations remove'

**Comment by bricelam** [comment]
I suspect, from the commands you pasted that you were running this from the `bin\x86\Debug` directory without specifying `--project-dir`. The migrations were probably being generated as expected, but under `bin\x86\Debug\Migrations` (outside of the project). `--verbose` should tell you where the files are being written.
