### ISSUE TITLE
EF Core Migrations Configuration

### ISSUE THREAD

**Issue by cigano** [dotnet/efcore#7407]
I didn't find a way to configure the Migrations like in EF6. 

```
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
            ContextKey = "MySystem";
        }
```

Is there something planned in EF Core to replace this feature?

**Comment by ekarimi** [comment]
Automatic migrations has been removed from EF7 and currently there is no support for this feature. I don't think this one will be a good idea at all !!!
Source control is much simpler now. You can now add migrations without applying previous one to the database.
Use code migrations.

**Comment by bricelam** [comment]
Are you looking for something like #3053, or is your scenario different?

**Comment by cigano** [comment]
@bricelam I understood the idea, it'll be something like: 

    PM> Recycle-Database

Some Powershell script updates the Snapshot, drop the database, re-scaffold the initial migration and redo a new database with (probably) the seeding process in the end.

Sounds great, but I believe that the initial code migration should have a default name, to source control purposes. 

Please note that this doesn't replace the migrations configuration, as I suggested. It would be great if data loss can be configurable.

**Comment by rowanmiller** [comment]
Configuration of anything migrations related is now done in `OnConfiguring` (or Startup.cs for ASP.NET Core), rather than having a separate `MigrationsConfiguration` class.

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder
        .UseSqlServer(@"Server=.\SQL2016;Database=Test;Trusted_Connection=True;", sqlOptions =>
            sqlOptions.MigrationsAssembly("My.System.Migrations")
                      .MigrationsHistoryTable("_Migrations"));
}
```

Data loss settings only applied to automatic migrations, since scaffolded ones were never run automatically and you could review them before applying.

**Comment by rowanmiller** [comment]
I'm going to close this one out, as we have a lengthy discussion going on #6214 and we also have #3053 tracking a simpler approach for iterative development.

**Comment by bricelam** [comment]
Also, in EF Core, we'll warn during Add-Migration if any scaffolded operation would result in data loss.

**Comment by cigano** [comment]
@rowanmiller Can I configure data loss tolerance using this method?

**Comment by cigano** [comment]
@bricelam Would be possible to use a parameter like `-Force` to execute the migration even with the data loss?

**Comment by bricelam** [comment]
The migrations will always execute. The warning occurs while scaffolding.

EF Core is very extensible since you can customize and replace any service. I'm sure you could serialize the data loss flag in the C# and throw during migrate if it's present.

**Comment by cigano** [comment]
@bricelam Okay, I'll dig into the sources and try to implement something. 

You mentioned the steps to obtain the differences in other issue. I'll use this as a guide to extend EF Core in some way.
