### ISSUE TITLE
Accessing DbContext from model

### ISSUE THREAD

**Issue by sepplK** [dotnet/efcore#7409]
Version: EntityFrameworkCore 1.1.0 (SQL)

Hi,

i can't figure out how to access the DbContext from a readonly property in the model.

Maybe with the IEntityMaterializerSource (optionsBuilder.ReplaceService...) and using another constructor  to inject the current DbContext?

Thanks for help.

Sebastian

**Comment by ajcvickers** [comment]
@sepplK Not really possible right now unless you are willing to hack internal code. Covered by #626 and see my comments on #7124
