### ISSUE TITLE
Re-consider patterns used to set metadata from conventions

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#7410]
See #7301. Currently we have a mechanism for metadata set by convention where attempting to set that piece of metadata may or may not actually do something based on whether or not setting that things is valid. It would be good to consider whether or not this is the best approach given:
* There are places, such as in #7301, where a convention should never try to set metadata that is invalid, so it may be that this code is never actually used.
* It needs to be clear from API/documentation that a convention is doing a try-set rather than a set. This will likely require API changes.
* It may be better for the convention itself to determine whether it is valid to set a property. This is likely to make it easier to understand what the convention is really doing. Also, if it turns out that there only a few conventions that need to do this, then we could end up removing significant code that is not used--see first point.
* If there are common things that conventions need to check, such as whether or not something has already been set explicitly, then this could be extracted into common code used from conventions without it being an integral part of every API.

**Comment by AndriySvyryd** [comment]
This is related to #214

**Comment by rowanmiller** [comment]
Merged info into https://github.com/aspnet/EntityFramework/issues/214
