### ISSUE TITLE
Create tables with same structure

### ISSUE THREAD

**Issue by BigVan** [dotnet/efcore#7418]
Hello everyone.
I need some help:
**Is there any effecient way to build tables with same structure? 
OR
Is there a gentle way to descirbe relations between two objects?**
Recently, I am building a shopping session in my work using EF core with official Mysql provider.
And  I found there are some relations between two objects.
For example,
_A user have some favorite items;
A seller have his own items to sell;
A user may have some contact addresses;
A user may have many orders._
etc.
All of these relations can be described as some <Key-Value> pair table, such as <user_id, item_id>/ <seller_id, item_id>/ <user_id, contact_addr_id> / <user_id, order_id>
However, I found issue #7299 which said **EF Core only supports having one mapping in the model for each entity type**. So I use inherite to implement same relations. 
There are part of my code:

```c#
 public class Relation
    {
        public string Key { set; get; }
        public string Value { set; get; }
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Id { set; get; }
        public Relation(string key, string value)
        {
            this.Key = key;
            this.Value = value;
            this.Id = $"{key}||{value}";
        }
        public Relation() { }
    }

    public class R_User_Recv : Relation
    {
        public R_User_Recv() { }
        public R_User_Recv(string user, string receiver) : base(user, receiver) { }
    }
   public class R_User_Item : Relation 
    {
        public R_User_Item() { }
        public R_User_Item(string user, string item) : base(user, item) { }
    };
```
So I did a lot of duplicate work to finish these relations and its MySql operation.
Anybody can tell me a gentle method to implement some may relations with same structure like I described before?

**Comment by ajcvickers** [comment]
@BigVan I don't fully understand what you are asking for, but I think you might be looking for ways to describe relationships between objects. This section of the documentation would be a good place to start: https://docs.microsoft.com/en-us/ef/core/modeling/relationships

**Comment by rowanmiller** [comment]
Closing, but feel free to reply with follow up questions if we didn't answer
