### ISSUE TITLE
How use long in SaveChangesAsync?

### ISSUE THREAD

**Issue by KANekT** [dotnet/efcore#7420]
How use long in SaveChangesAsync?
```c#
        public Task<long> SaveChangesAsync()
        {
            return this.StorageContext.SaveChangesAsync();
        }
```

I keep the primary keys in a database in long format

But for save I may use only int ?

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.0
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by John0King** [comment]
`SaveChangesAsync` does not return primary key , it return  the number of row that were effected . I don't think you will update/insert/remove more than 2,147,483,647 objects  in one `SaveChanges`.
If you want get the inserted Id, just get it from same the object  after you `SaveChanges`.
And you don't need to set foreignKey , EF will set for you automaticly when `SaveChanges` .

**Comment by KANekT** [comment]
@John0King Thx!
