### ISSUE TITLE
dotnet ef dbcontext list does not return dbcontexts from dependent dlls w/o passing the startup project

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/efcore#7426]
Describe what is not working as expected.
Publish tooling in Visual studio currently calls "dotnet ef dbcontext list" to get the list of dbcontexts to show in the publish settings tab.

If the dbcontext is in a different project, the above command does not return the dbcontexts from the dependent projects.   

Can we have an additional flag (if provided) will search for the db contexts in all dependent projects?

### Steps to reproduce
Add dbcontext to a project
Create a WebApp with dependency to the ef project.
dotnet ef dbcontext list does not return the dbcontexts from the dependent projects without passing in the startup project.

IDE: visual studio 2017

related issue: https://github.com/aspnet/Tooling/issues/898

**Comment by vijayrkn** [comment]
@rowanmiller @bricelam

**Comment by julielerman** [comment]
This will also make it possible to publish projects where EF is in a dependent project

**Comment by bricelam** [comment]
Note, if it's registered in the application services using `services.AddDbContext<MyExternalDbContext>()` it will be listed.

But correct, we currently don't crawl project/assembly references looking for DbContext classes.

**Comment by vijayrkn** [comment]
@bricelam Is it possible to add this feature to dotnet ef to look for the dbcontexts from dependent assemblies/projects when an additional flag is passed?

**Comment by rowanmiller** [comment]
Discussed at length and we think it makes more sense to iterate over the projects in the deployment layer. Feel free to tee up a meeting to discuss further if you want to push back 😄.
