### ISSUE TITLE
Outdated Writing an EF7 Provider wiki docs

### ISSUE THREAD

**Issue by colltoaction** [dotnet/efcore#7433]
[Writing an EF7 Provider](https://github.com/aspnet/EntityFramework/wiki/Writing-an-EF7-Provider) in the wiki is outdated.

Maybe we should point to https://docs.microsoft.com/en-us/ef/core/miscellaneous/internals/writing-a-provider?

**Comment by rowanmiller** [comment]
Yep that page should be deleted. We should take a look at the [design documents](https://github.com/aspnet/EntityFramework/wiki/Design-Documents) and see which ones we want to keep, and which ones should just be deleted.

**Comment by rowanmiller** [comment]
BTW that section in our docs is pretty average too... I think we should just point folks to the blog series by @ajcvickers as it is the most comprehensive (and up to date) info we have https://blog.oneunicorn.com/2016/11/11/so-you-want-to-write-an-ef-core-provider/.

**Comment by tinchou** [comment]
Sure. But maybe don't delete it since it's one of the first search results.
We could put a link to the updated docs.

**Comment by rowanmiller** [comment]
@tinchou agreed, will do

**Comment by rowanmiller** [comment]
Done
