### ISSUE TITLE
Query : possible error around conditional removing visitor and sql functions

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#7441]
Problem so far only surfaces in MySql provider, but potentially it's a wider issue that can be reproduced in Sql provider with a correct query. 

More info: https://github.com/aspnet/EntityFramework/issues/6687#issuecomment-272543460
Mysql repro: http://bugs.mysql.com/bug.php?id=84505

**Comment by gmartinezsan** [comment]
@maumar This issue has been already addressed in the MySQL provider.
