### ISSUE TITLE
Documentation for LoadAsync, cancellation, and transactions

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#7442]
Well, this is more of a question than an issue but ... I guess it's an issue if the documentation doesn't tell me the answer :-) 

Will the use of a transaction result in all-or-none loading when cancellation occurs (or for that matter if an error occurs), assuming I am using LoadAsync? 

For example, it would be helpful to know that when I do an await dbSet.Skip(n).Take(p).LoadAsync(cancellationToken) within a using dbContext.Database.BeginTransactionAsync(), then definitely either the full page of p records is loaded or no records were loaded. 

If it is possible that some but not all of the records get loaded, then I have to check for this and cleanup -- which is not convenient, especially if I am loading into a context that already contains some other records. 

sjb

**Comment by ajcvickers** [comment]
@sjb-sjb You can end up with a partial set of results loaded. However, if there is a failure or cancellation, then there should be no problem just executing the same query again because EF will do identity resolution to ensure that only one instance of each entity is loaded--there should not be a need to clean anything up.

**Comment by sjb-sjb** [comment]
Thanks for the comment. In my case the cancellation will be because I've moved on to loading a different page due to a new incoming user request. It seems like a waste though if I delete perfectly good entities just because it was a partial page load. Maybe I should think about the design a bit more.

**Comment by ajcvickers** [comment]
@sjb-sjb A few things to note. First, the context is not thread safe, so if the same context is being used to load two pages at the same time, then that is an error. Second, if you want the entities from the first page to not be tracked by the context when loading the second page, then that will require some work regardless of whether all the entities were loaded or not. Third, if you find that you are having to attempt to detach/untrack entities a lot, then that usually means that the context lifetime is too long. A context should usually only live for a single unit of work.

**Comment by sjb-sjb** [comment]
Well, I agree about the threading. This is a client application and the tasks are all awaited from the UI thread, so I think the main challenge in my case is not threading per se but to make sure the tasks on that thread don't get in each others' way. I also agree there's got to be some work done somewhere, there's no free lunch. 

About the context lifetime, I have seen this mentioned elsewhere and it seems to be the conventional wisdom. However, I don't get the rationale. The entities are going to be edited by the user (and in a group, not just one at a time) and then saved. If I detach them from the context then I have to keep track myself of which ones have been added, deleted, or modified; and then I have to reproduce that state change when I reattach the entities to a new context in order to save the changes. In other words I would have to do what the context would otherwise do for me. It seems a lot harder than just leaving them attached, no?  

I am assuming that the context isn't constantly keeping an open database connection alive, or anything like that. In my mind, when it is not actually executing a transaction the context is basically a normal (i.e. resource-free) data structure that is doing something useful by tracking the entity state. Am I missing something?

**Comment by ajcvickers** [comment]
@sjb-sjb With regard to detaching entities, it seemed like you were saying that you would need to detach entities for one page because another page is loading. I was trying to say that that might be an indication that each page is a different unit of work.

**Comment by sjb-sjb** [comment]
I agree. It would be nuts to have two tasks competing to load two pages into the same context. 

Thanks again for your insights, I really appreciate the depth of your experience.
