### ISSUE TITLE
[UWP][DATABASE LOCATION][EF CORE][SQLITE]

### ISSUE THREAD

**Issue by predalpha** [dotnet/efcore#7453]
Hello,

im learning EF Core for windows universal apps.
I want to know if it is possible to move the database (filename=Blogging.db) to another place.
For exemple to a shared folder in order to have many people to connect to it.

If i set the connectionstring to @"Filename=" + Windows.Storage.ApplicationData.Current.LocalFolder.Path + "\Blogging.db" 

It works fine. 

But if im away that local folder (f.e : C:\Users\xxx\Music\Blogging.db) i got the following error : 'unable to open database file'

Moreover is there a compiler directive for EF tool when we 'add-migration' command ?

Best regards

[Edit im using Music contract and futureaccesslist but i know this is not the way UWP works]

**Comment by bricelam** [comment]
See aspnet/Microsoft.Data.Sqlite#287

> Moreover is there a compiler directive for EF tool when we 'add-migration' command ?

Not currently. It just does a normal build of your project. See #7387 for a runtime alternative.
