### ISSUE TITLE
Generate a warning for incorrectly mapped char/varchar

### ISSUE THREAD

**Issue by akamud** [dotnet/efcore#7460]
An easy and common mistake to make when using EF with a SQL Server databases is incorrectly mapping `char`/`varchar` columns to `nchar`/`nvarchar` and vice-versa, these leads to serious performance problems because the query ends up with implicit conversions and are very hard to notice only looking at the code/mapping.

I described this [here](http://stackoverflow.com/a/29244442/1710624), and Jimmy Bogard also talks about this in [his blog](https://lostechies.com/jimmybogard/2012/07/18/troubleshooting-sql-index-performance-on-varchar-columns/).

So I was wondering if it would be possible for EF to detect this kind of problem and generate a warning, similar to what it does to [Ingored Include queries](https://github.com/aspnet/EntityFramework/blob/24556c26a4bdae6e77e84678b7e0ee5d0e321365/src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx#L622).

Would this be possible for EF Core to detect?

**Comment by ajcvickers** [comment]
@akamud The problem with this is that EF doesn't know what the type is in the database. (The only time EF knows is when reverse engineering from an existing database, and in that case the model will get the correct mappings as part of the process.)

**Comment by akamud** [comment]
I see, I tried to find somewhere in the code where this could be possible with no success.

I guess this can be closed then.
