### ISSUE TITLE
SQL Server 2016 Change Data Capture support

### ISSUE THREAD

**Issue by subprime** [dotnet/efcore#7462]
**Is there any support planed for the sql server feature called "Change Data Capture". 
How to collect this information with Entity Framework core to use this informations in my project.**

**Why:** Currently i create a web application in .NET Core (Yeah! Rocks!) which is an intranet application that hold many entity informations and the costumer needs a high traceablity and data integrity for each change...

EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2015

**Comment by ErikEJ** [comment]
I think it is not related to using EF Core, you can just enable it on your server.

**Comment by subprime** [comment]
You are right but my costumer won't look into the plain DB. For this we are planing something like a dashboard in the backend area

**Comment by ErikEJ** [comment]
?? Are you talking about showing the results of this? https://msdn.microsoft.com/en-us/library/bb522553.aspx

**Comment by subprime** [comment]
@ErikEJ Right.

**Comment by rowanmiller** [comment]
This isn't really something we would bake into EF, but you could definitely use EF to get the info from the database and then write an app to display it.

**Comment by subprime** [comment]
@rowanmiller 

>  ...but you could definitely use EF to get the info from the database and then write an app to display it

 Can you in short explain how to get this information with EF. Thanks

**Comment by ErikEJ** [comment]
@subprime  Create/map an entity to hold the data, and use EF to query for that data. (remove it manually from scaffolded migrations)
