### ISSUE TITLE
Add-migration not working after update to entityframeworkcore.tools-1.1.0-preview4 - Cannot bind parameter 'Path' to the target. Exception setting "Path"

### ISSUE THREAD

**Issue by agonzalezm** [dotnet/efcore#7463]
I had to update to entityframeworkcore.tools-1.1.0-preview4 because entity inheritace was not working with error:

The current CSharpHelper cannot scaffold literals of type 'System.Func`3[Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator]'. Configure your services to use one that can.

I read that updating to preview 4 fixed the issue but after updating now i get another error related to old path:

Add-Migration -Name initial

```
PM> add-migration -Name initial
add-migration : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\project\packages\Microsoft.EntityFrameworkCore.Tools.1.0.0-preview2-final\tools\OperationHandlers.cs' because it does not exist."
At line:1 char:1
+ add-migration -Name 9_3
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-Migration], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Add-Migration
```

EF Core version: 1.1.0
NET Version: NET 4.5.1
Database Provider:  npgsql
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by bricelam** [comment]
It looks like you're mixing 1.1.0 and 1.0.0 packages. Ensure all your packages align to a single Major.Minor set of packages.

**Comment by bricelam** [comment]
Closing and re-opening VS may also help.

**Comment by agonzalezm** [comment]
Thank restarting VS fixed the issue
