### ISSUE TITLE
Key specification

### ISSUE THREAD

**Issue by benchmatebob** [dotnet/efcore#7470]
I want to create a table with a Unique Key.  In the table Part, How do I specify that 'strPartNbr' is to be unique (only one part number).  Also, I would line 'iRecid' to be a unique key value generated by SQLite.
The code below runs w.
```C#
 try
         {
            var db = new DbBarCodeInv("Filename=BarCodesInv.db ");
            var created = db.Database.EnsureCreated();
         }
         catch (Exception ex)
         {
            string msg = ex.ToString();
         }
.....
namespace TestSQLiteEF
{
   public class DbBarCodeInv : DbContext
   {
      private readonly string _connectionString;
      public DbBarCodeInv(string connectionString)
      {
         _connectionString = connectionString;
      }
      public DbSet<Part> Parts { get; set; }
      public DbSet<Tran> Trans { get; set; }
      public DbSet<Person> Persons { get; set; }
      
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseSqlite(_connectionString);
      }
      public class Part
      {  
         public int iRecid { get; set; }

         [Key, MaxLength(15), Required]
         public string strPartNbr { get; set; } 
         public string strDesc { get; set; }
         public string strLocn { get; set; }
         public string strQoh { get; set; }
         public string strMinQty { get; set; }
      }
....
```
Project.json
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
Operating system: Windows 10
IDE:   Visual Studio 2015 w/Update 3

**Comment by ajcvickers** [comment]
@benchmatebob Remove the Key annotation and then add the following in OnModelCreating:
```C#
modelBuilder.Entity<Part>().HasKey(e => e.iRecid);
modelBuilder.Entity<Part>().HasIndex(e => e.strPartNbr).IsUnique();
```
Or, if you prefer a more DRY syntax, then use:
```C#
modelBuilder.Entity<Part>(b =>
{
    b.HasKey(e => e.iRecid);
    b.HasIndex(e => e.strPartNbr).IsUnique();
});
```

**Comment by benchmatebob** [comment]
Thanks Arthur.

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27655.1C33A4D0]<http://www.benchmate.com/>  [cid:image005.jpg@01D27655.1C33A4D0] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27655.1C33A4D0] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>
