### ISSUE TITLE
Why transaction commit closes db connection?

### ISSUE THREAD

**Issue by Kikimora** [dotnet/efcore#7471]
I wonder what is reason for transaction to close database connection on commit? I'm working on rather intricate scenario where I have to synchronise two requests access to the database and this behaviour breaks my logic.

I planned to use 'sp_getapplock/sp_releaseapplock' MS SQL procedures to implement database mutex which guards access to shared resource. I implemented 'class DbMutex : IDisposable' which acquire lock in constructor and release it in Dispose.  Use case for this class looks like this:
```c#
using (var t = dbContext.Database.StartTransaction()) {
  //acquire lock
  using (var dbMutex = new DbMutex(dbContext.GetConnection(), t, 'shared_lock_id')) {
    //this code is executed only by one request at a time
    if (MySharedResourceUpdated()) {
      //other request have updated my shared resource
      return;
    }
    UpdateSharedResource();
    //commit transaction so other request can see results
    t.Commit();
  }
  //release lock in Dispose
}
```
This code breaks since t.Commit() closes transaction and then my DbLock.Dispose fails to execute 'sp_releaseapplock' on closed connection.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by rowanmiller** [comment]
When EF opens a connection, it will close it when it thinks it is done. In your case, you have additional code, that EF isn't aware of, that requires the connection to be left open. There are open/close APIs on the connection to allow you to control this manually. EF won't close a connection if it didn't open it.
