### ISSUE TITLE
How to use EF CLI Tools in an environment without visual studio

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#7478]
If for instance I'm in a environment where I just have my application release folder that has a bin folder with the dotnet-ef.exe file and there is no visual studio installed in the environment. 

right now if I try this `dotnet ef database update` I get this error:
> No executable found matching command "dotnet-ef"

How can I update the database from this environment with `dotnet ef database update`

**Comment by bricelam** [comment]
You can use `ef.exe` (as we call it). It can operate directly on assemblies without a project file.  It can be found under `%USERPROFILE%\.nuget\packages\Microsoft.EntityFrameworkCore.Tools\1.0.0-msbuild3-final\tools\net451`.

    ef.exe database update --assembly MyApp.exe

**Comment by bricelam** [comment]
Calling it on a .NET Core App is a bit more tricky:

    dotnet exec --depsfile MyApp.deps.json --runtimeconfig MyApp.runtimeconfig.json ef.dll database update --assembly MyApp.dll

**Comment by capiono** [comment]
How do you install  ef.exe?
