### ISSUE TITLE
Tools: Allow specifying content root

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#7480]
The ASP.NET Core content root path is configured by the user on `WebHostBuilder`. We currently default it to match what the templates do, but we should also allow it to be overridden on the PMC and `dotnet ef` commands.

**Comment by bricelam** [comment]
Superseded by #7480

**Comment by smitpatel** [comment]
@bricelam - Superseding issue is the same as this one. Circular reference? :trollface:
