### ISSUE TITLE
AddAsync not saved related entities

### ISSUE THREAD

**Issue by TroySchmidt** [dotnet/efcore#7487]
The problem that I am seeing is that AddAsync is not saving related records.  I have a One To Many relationship or RouteBatches to RoutePaths.  If I AddAsync, the related records do not get saved.  If I change it to Add then it does.  I am still calling SaveChangesAsync.

### Further technical details
EF Core version: v1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2015

**Comment by ajcvickers** [comment]
Dupe of #7298.
