### ISSUE TITLE
Fix shadow state Northwind query tests

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#7489]
It looks like the shadow property was removed from the Northwind model in https://github.com/aspnet/EntityFramework/commit/814582ed629cf2c5e7#diff-b3d0fae678e6f014e6200cc80d30c3b7L43

Not sure if this was by design, but a consequence is that all of the query shadow state tests are, in fact, not using shadow properties! 

@AndriySvyryd This was a while ago, do you remember anything about this change? 😄

**Comment by AndriySvyryd** [comment]
@anpete If was basically a cleanup, if the configuration was not necessary for the tests to pass it was removed.

**Comment by ajcvickers** [comment]
@anpete How much extra coverage/benefit do we get by re-adding the shadow properties? (Given that no assertions broke when removing them.) Should we add assertions that were not there?
