### ISSUE TITLE
The instance of entity type 'User' cannot be tracked because another instance of this type with the same key is already being tracked.

### ISSUE THREAD

**Issue by marekt77** [dotnet/efcore#7501]
I have an class, where two fields are instances of another class.

Creating a new instance of the class, and saving it to the database is not the issue, however updating the record is.

Before going any further, here are my classes:

```C#
public class Recipient
    {
        [Key]
        public Guid RecipientGUID { get; set; }

        [Required(ErrorMessage = "Please enter a Recipient's First Name.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter a Recipient's Last Name.")]
        public string LastName { get; set; }

        public string Company { get; set; }

        public UserGroup Owner { get; set; }

        public virtual ICollection<ContactMethod> ContactMethods { get; set; }

        public User CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        public User LastModifiedBy { get; set; }

        public DateTime LastModifiedOn { get; set; }

        public bool IsActive { get; set; }
    }

public class User
    {
        [Key]
        public Guid UserGUID { get; set; }

        public string UserName { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public bool IsSiteAdmin { get; set; }

        public bool IsActive { get; set; }

        public DateTime? CreatedOn { get; set; }

        public DateTime? LastLogin { get; set; }
    }
```

So, let us say, user Steve creates a new recipient, and the record is saved in the database.  Therefore the fields: CreatedBy and LastModifiedBy are both set to Steve's user record.

Now User Bob comes in, and updates the Recipient.  Still not an issue, LastModifiedBy is changed to Bob, and the records saves, but now let us say Steve comes back and edit's the recipient, well LastModifiedBy is set to Steve, and upon SaveChanges(), I get the following error:

> An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code
> 
> Additional information: The instance of entity type 'User' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.

Yes, the same User is being set to two different fields in the Recipient Class, this is I believe what is causing the issue.  But I cannot figure out why.

First off, is my class definition valid?  Maybe I am doing something wrong with how I have defined it.

Second, if my class definition is ok, what am I doing wrong that I keep getting this error?

here is the code that is doing the actual saving:

```
using (var test = new IONS_EFDbContext())
                {
                    var dbRecipient = test.Recipients
                        .Include(a => a.ContactMethods).ThenInclude(t => t.Type)
                        .Include(b => b.CreatedBy)
                        .Include(c => c.LastModifiedBy)
                        .Include(d => d.Owner).ThenInclude(o => o.Users)
                        .FirstOrDefault(x => x.RecipientGUID == myRecipient.RecipientGUID);

                    test.Entry(dbRecipient.CreatedBy).State = EntityState.Unchanged;

                    if (dbRecipient != null)
                    {
                        dbRecipient.FirstName = myRecipient.FirstName;
                        dbRecipient.LastName = myRecipient.LastName;
                        dbRecipient.Company = myRecipient.Company;

                        foreach (ContactMethod tmpCM in myRecipient.ContactMethods)
                        {
                            var dbCM = dbRecipient.ContactMethods.FirstOrDefault(x => x.ContactMethodGUID == tmpCM.ContactMethodGUID);

                            if (dbCM != null)
                            {
                                dbCM.CountryCode = tmpCM.CountryCode;
                                dbCM.Identifier = tmpCM.Identifier;
                                dbCM.IsPreferred = tmpCM.IsPreferred;
                            }
                            else
                            {
                                dbRecipient.ContactMethods.Add(tmpCM);
                            }
                        }

                        //Only update this if it has changed.
                        if (dbRecipient.LastModifiedBy.UserGUID != myRecipient.LastModifiedBy.UserGUID)
                        {
                            dbRecipient.LastModifiedBy = myRecipient.LastModifiedBy;
                        }

                        dbRecipient.LastModifiedOn = myRecipient.LastModifiedOn;

                        test.Update(dbRecipient);
                        test.SaveChanges();
                    }
```

Yes I am using dependency injection, and if you need any addition info, I will be happy to provide anything you need.

Thanks,

**Comment by ajcvickers** [comment]
@marekt77 The code that sets the navigation property dbRecipient.LastModifiedBy is setting it to an entity instance that is not being tracked by the context. It seems like in this case the context is already tracking another instance for this same entity--presumably because it was brought in by the query through including the "CreatedBy" navigation. EF can't track two instances of the same entity, which is why the exception is thrown, so you will need to give EF additional information here to know what to do. This can be complicated in the general case--for example, if the tracked instance has properties that have been modified in the other instance. However, assuming that isn't the case, then you can just lookup the instance that is being tracked and use it instead, For example:
```C#
if (dbRecipient.LastModifiedBy.UserGUID != myRecipient.LastModifiedBy.UserGUID)
{
    dbRecipient.LastModifiedBy = test.Set<User>().Find(myRecipient.LastModifiedBy.UserGUID);
}
```
