### ISSUE TITLE
SQLite3 db.Parts.Add failing

### ISSUE THREAD

**Issue by benchmatebob** [dotnet/efcore#7504]
I've built a simple database and trying to add one record with two data fields.  When trying to execute SaveChanges, get the error that it can't find the first data field.
```C#
using (var db = new DbBarCodeInv())
         {
            db.Database.EnsureCreated();
            string strDesc = "AIR FILTER";
            string strPartNbr = "ABC-123";
            var part = new Part { Desc = strDesc, PartNbr = strPartNbr };
            try
            {
               db.Parts.Add(part);
               db.SaveChanges();  
            }
            catch (Exception ex)
            {
               string strMsg = ex.ToString(); // InnerException:  {SQLite Error 1:  'Table Parts has no column named Desc'.}
            }
         }

   public class DbBarCodeInv : DbContext
   {
      public class Part
      {
         public int iRecid { get; set; }

         [MaxLength(LENSPPN), Required]
         public string PartNbr { get; set; }
         [MaxLength(LENSPDESC), Required]
         public string Desc { get; set; }
         [MaxLength(LENSPLOCN)]
 ```

Describe what is not working as expected:  Program works fine until db.SaveChanges();

[TestSQLiteEF.zip](https://github.com/aspnet/EntityFramework/files/736689/TestSQLiteEF.zip)

### Further technical details
EF Core version:  1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlLite
Operating system:  WIN 10 Anniversery Edition
IDE: Visual Studio 2015, update 3

**Comment by bricelam** [comment]
You need to ensure the database schema is created either by calling `db.Database.EnsureCreated()` or using the Migrations feature.

**Comment by benchmatebob** [comment]
Brice – I replaced db.Migration() with db.Database.EnsureCreated().  No change, error message states ‘strDesc’ not found.


Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27A12.0F617190]<http://www.benchmate.com/>  [cid:image005.jpg@01D27A12.0F617190] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27A12.0F617190] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>

**Comment by ajcvickers** [comment]
@benchmatebob From a quick look at your code it looks like the database is already created, but it not up-to-date with your model. If the database already exists, then EnsureCreated will do nothing. It won't try to add new tables or columns to it. Migrations is needed to do that. If you don't care about your current database, then you can use EnsureDeleted before EnsureCreated to always re-create your database. If you don't want to blow away your database, then use Migrations.

**Comment by benchmatebob** [comment]
Arthur – I’m still having the same problem.  I tried copying the UWP example.  Code fragments follow:

             From:  App.xaml.cs

        public App()
        {

            this.InitializeComponent();
            this.Suspending += OnSuspending;
            using (var db = new BloggingContext())
            {
               try
               {
                  db.Database.Migrate();
                  db.Database.EnsureCreated();
               }
               catch (Exception ex)
               {
                  string strErrMsg = ex.ToString();           // no error
               }

            }
        }



From:  MainPage.xaml.cs

     public MainPage()
      {
         this.InitializeComponent();

      }
      private void Page_Loaded(object sender, RoutedEventArgs e)
      {
         using (var db = new BloggingContext())
         {
            try
            {
               Blogs.ItemsSource = db.Blogs.ToList();
            }
            catch (Exception ex)
            {
               string strErrMsg = ex.ToString();   // no such Table: Blogs
            }
         }
      }

‘Migration’ does not seem to be working and I can’t find any description of this function or figure out how to fix this error.

Thank you,

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27BAD.B71C75A0]<http://www.benchmate.com/>  [cid:image005.jpg@01D27BAD.B71C75A0] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27BAD.B71C75A0] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>

**Comment by ajcvickers** [comment]
@benchmatebob Did you create a migration? Try working through the "Getting Started" guide for UWP apps making sure that actually create appropriate migrations and then create your database from those migrations, like the walk through shows. https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started

**Comment by benchmatebob** [comment]
Arthur – That’s what I’ve been doing.  However ‘Add-Migration MyFirstMigration’ doesn’t execute when run from the Tool Console as instructed.

I’ve not found any other instructions for migrations.


Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27BC4.36314210]<http://www.benchmate.com/>  [cid:image005.jpg@01D27BC4.36314210] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27BC4.36314210] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>

**Comment by ajcvickers** [comment]
@benchmatebob Can you be more specific about what you mean by, "doesn’t execute"?

**Comment by benchmatebob** [comment]
Arthur – See attached.  Frankly, the instructions don’t make much sense to me.

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27BC6.3CD97130]<http://www.benchmate.com/>  [cid:image005.jpg@01D27BC6.3CD97130] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27BC6.3CD97130] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>

**Comment by ajcvickers** [comment]
@benchmatebob I don't see any attachment. I expect responding through email doesn't upload attachments.

**Comment by benchmatebob** [comment]
Arthur – Here is the error message when I try to ‘Add-Migration …’ as instructed in the UWP database example.

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27C73.A5166FC0]<http://www.benchmate.com/>  [cid:image005.jpg@01D27C73.A5166FC0] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27C73.A5166FC0] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>




PM> Add-Migration MyFirstMigration
Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Add-Migration MyFirstMigration
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
PM>

**Comment by ajcvickers** [comment]
@benchmatebob Did you install the tools, as described under the "Install Entity Framework" section? Also, you might need to close and restart Visual Studio as there is a bug in NuGet that means commands can occasionally not get installed correctly.

**Comment by benchmatebob** [comment]
Arthur – I’ve done all of that.

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27C74.D215CBA0]<http://www.benchmate.com/>  [cid:image005.jpg@01D27C74.D215CBA0] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27C74.D215CBA0] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>

**Comment by bricelam** [comment]
Ensure you're using the [latest version of NuGet](https://dist.nuget.org/index.html). You may also need to run `Set-ExecutionPolicy RemoteSigned` in an elevated PowerShell session to work around a NuGet issue.

**Comment by bricelam** [comment]
Another possible workaround: Close Package Manager Console before restarting Visual Studio.

**Comment by benchmatebob** [comment]
Brice – I have moved from EntityFramework and have successfully tested SQLite using SQLitePCL.  I do not plan to work with EntityFramework.

Thanks for your help,

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27D44.8CE2D610]<http://www.benchmate.com/>  [cid:image005.jpg@01D27D44.8CE2D610] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27D44.8CE2D610] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>

**Comment by bricelam** [comment]
FYI (for you and any others reading this issue), Migrations can be bypassed by calling `db.Database.EnsureCreated()` to create the schema. You can also manually create the database outside of EF and connect to it using a model with matching table and column names.

If you ever want to drop down to raw SQL with EF, you can use `ExecuteSqlCommand`.

```C#
using (var db = new MyDbContext())
{
    db.Database.ExecuteSqlCommand(@"
        CREATE TABLE MyTable (
            Id NOT NULL INTEGER PRIMARY KEY,
            Name TEXT
        );");
}
```

**Comment by benchmatebob** [comment]
Thanks Brice.

Bob Nichols
Benchmate Systems, Inc.
(360) 678-8358
bobn@benchmate.com<mailto:bobn@benchmate.com>
http://www.benchmate.com<http://www.benchmate.com/>

[cid:image004.jpg@01D27D4B.B7840EF0]<http://www.benchmate.com/>  [cid:image005.jpg@01D27D4B.B7840EF0] <https://twitter.com/@BenchmateCMMS>  [cid:image006.jpg@01D27D4B.B7840EF0] <http://www.linkedin.com/pub/bob-nichols/34/a66/b62>
