### ISSUE TITLE
After initial install, closing and re-opening VS 2017 causes EF tools to not work

### ISSUE THREAD

**Issue by LwsSt** [dotnet/efcore#7507]
1. I install the Entity Framework Core Tools using the Package Manager Console as per the instructions in the [announcement](https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-entity-framework-core-1-1-preview-1/): `Install-Package Microsoft.EntityFrameworkCore.Tools -Pre`
2. The package `<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0-preview4-final" />` Gets installed into my csproj file.
3. I can then use commands such as `Add-Migration`, `Update-Database`, etc. in the PMC.
4. After closing and re-opening the project in VS2017, the EF commands no longer work.
5. Running `Install-Package Microsoft.EntityFrameworkCore.Tools -Pre` again does not enable the commands. I have to uninstall the package and re-install to enable the commands again.

Is this expected behaviour? Or is there I command I'm missing that needs to be run to re-enable the commands in the PMC?

### Further technical details
EF Core version: 1.1.0-preview4-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows
IDE: Visual Studio 2017 Community RC1

**Comment by bricelam** [comment]
> Is this expected behaviour?

No, if they're installed into a project, opening the solution should make the commands available in Package Manager Console.

This looks like a bug in NuGet. Would you mind [creating a new issue on the NuGet/Home reop](https://github.com/NuGet/Home/issues/new) so they can follow up?

**Comment by ErikEJ** [comment]
Also make sure to run the latest RC (RC3 currently)

**Comment by Jabbersii** [comment]
New issue raised in Nuget/Home repo: https://github.com/NuGet/Home/issues/4426
