### ISSUE TITLE
Query: OrderBy passed as Func<> does not translate to SQL

### ISSUE THREAD

**Issue by Spaceman1861** [dotnet/efcore#7515]
Greetings :D

When I provide an orderby query like so it doesn't seem to work for nullable datetimeoffset.
```c#
ObjectRepository.AsQueryable.OrderBy(a =>a.someNullableDateTimeOffset).ToList();
```
It correctly filters the object but it does it client side not sql side.

My code works fine when I order by other types such as int or string.

The db type matches up with the model type.

Is ordering by datetimeoffsets currently supported?

Below is the model and methods used.

```c#
public IEnumerable<MessageDto> GetPublishedMessages()
    =>  GetObjects(
        message => message.PublishStatus == "Published",
        message => message.PublishDate,
        true
    );

public interface IModel
{
    int Id { get; set; }
}

public class Message : IModel
{
    public string Title { get; set; }
    public string ShortDescription { get; set; }
    public string Body { get; set; }
    public DateTimeOffset? PublishDate { get; set; }
    public string PublishStatus { get; set; }
}

protected abstract Func<TModel, TDto> ObjModelToObjDtoMap { get; }

protected IEnumerable<TDto> GetObjects(
    Expression<Func<TModel, bool>> where = null,
    Func<TModel, object> orderBy = null,
    bool orderByDescening = false
)
{
    try
    {
        var queryable = ObjectRepository.AsQueryable();
        queryable = where == null
            ? queryable
            : queryable.Where(where);

        if (orderBy != null)
        {
            var orderdQueryable = orderByDescening
                ? queryable.OrderByDescending(orderBy)
                : queryable.OrderBy(orderBy);

            returnEnumerable = orderdQueryable.Select(ObjModelToObjDtoMap).ToList();
        }
        else
        {
            returnEnumerable = queryable.Select(ObjModelToObjDtoMap).ToList();
        }
    }
    catch (Exception exception)
    {
        Logger.LogError(default(EventId), exception, "Message");
    }

    return returnEnumerable;
}
```

Im getting a trace that looks like this.

```sql
exec sp_executesql N'SELECT [Message].[Id], [Message].[Body], [Message].[PublishDate], [Message].[PublishStatus], [Message].[ShortDescription], [Message].[Title]
FROM [Messages] AS [Message]
WHERE [Message].[PublishStatus] = @__EnumToString_0',N'@__EnumToString_0 nvarchar(4000)',@__EnumToString_0=N'Published'
```

Note the code has EnumToString in it because i simplfied the example to post here so code on my end is doing a little be more stuff in the where clause.

### Further technical details
EF Core version: 1.0 also tried 1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10
IDE: Visual Studio 2015

**Comment by smitpatel** [comment]
@Spaceman1861 - I tried running order by in a sample app for EF 1.1 version.
My class
```C#
public class Blog
{
    public int Id { get; set; }
    public string Title { get; set; }
    public DateTimeOffset? DTO { get; set; }

    public override string ToString()
    {
        return "Id=" + Id + " Title=" + Title + " DTO=" + DTO;
    }
}
```
query `var query = db.Blogs.OrderBy(e => e.DTO).ToList();`
generated following SQL
```SQL
SELECT [e].[Id], [e].[DTO], [e].[Title]
FROM [Blogs] AS [e]
ORDER BY [e].[DTO]
```

It is working as expected in 1.1

**Comment by smitpatel** [comment]
@Spaceman1861 - Can you provide a stand-alone repro? The code you posted above, I cannot get it to compile.

**Comment by Spaceman1861** [comment]
@smitpatel yeah ill bash something up.

**Comment by Spaceman1861** [comment]
@smitpatel 
I Found a fix to my issue.

I pass an expression not a func in.

    Expression<Func<TModel, object>>

not 

    Func<TModel, object>

Using your example

  public void getStuffSorted(Expression<Func<TModel, object>> a)
  {
        var query = _context.Set<TModel>().OrderBy(a).ToList();
   }

Not sure this is working as intended it probably is and i just stuffed up.

**Comment by smitpatel** [comment]
@Spaceman1861 - That is the issue. I missed that part. EF cannot translate `Func<>`. It needs `Expression<Func<>>` to reason about the expression tree to successfully convert it to SQL.
Here is a good stackoverflow answer which describes difference between both.
http://stackoverflow.com/questions/793571/why-would-you-use-expressionfunct-rather-than-funct?rq=1

Closing this as things are working as expected on EF side.

**Comment by Spaceman1861** [comment]
@smitpatel  Cheers matey
