### ISSUE TITLE
Reverse engineering (Scaffold) Precision for Decimal Type not working

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#7529]
When doing reverse engineering (Scaffold-DbContext) from database to EF Entities, decimal columns do not get precision.
So for columns that have other then default(18, 2) precision, lets say (20, 4) model will not be correct and if database would be recreated from that model the precision would be changed to default.

### Steps to reproduce
This is column in database

> **Column Name  |   Data Type**
> Value                 |   decimal(20, 4)

And this is created
```c#
entity.Property(e => e.Value).HasColumnType("decimal");
```
And I think it should be:
```c#
entity.Property(e => e.Value).HasColumnType("decimal(20,4)");
```

### Further technical details
EF Core version: 1.1.0
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 Home
IDE: (Visual Studio Community 2015 Update 3)
SQL Server 2016 Developer Edition

**Comment by ajcvickers** [comment]
This is being tracked by #5410
