### ISSUE TITLE
migrations probem with context from separate project

### ISSUE THREAD

**Issue by damienbod** [dotnet/efcore#7544]
The migrations are not working with the current msbuild3 build and context from a separate project

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Time Elapsed 00:00:04.41
Your target project 'AspNet5FileUploadFileTable' doesn't match your migrations assembly 'AspNetCoreFileUploadFileTable'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("AspNet5FileUploadFileTable")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
```

### Steps to reproduce
Use this src:
https://github.com/damienbod/AspNet5FileUploadFileTable

dotnet restore
dotnet build
dotnet ef migrations add test
```c#
 var sqlConnectionString = Configuration["ApplicationConfiguration:SQLConnectionString"];

            services.AddDbContext<FileContext>(options =>
                options.UseSqlServer(
                    sqlConnectionString,
                    b => b.MigrationsAssembly("AspNetCoreFileUploadFileTable")
                )
);
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
VS2017 RC3

**Comment by damienbod** [comment]
@rowanmiller @bricelam @natemcmaster 
Will this be fixed before the VS2017 release. This is blocking me from migrating from project.json to msbuild.

Thanks Damien

**Comment by damienbod** [comment]
Also when I migrate to msbuild, the  Microsoft.EntityFrameworkCore.Tools.DotNet is not migrated, need to change this after. Should this not be migrated?

Greetings Damien

**Comment by damienbod** [comment]
sorry, for bothering you. Found the problem, I renamed the project in Visual studio, but the assembly was not renamed and so the migrations did not work.

**Comment by rowanmiller** [comment]
@bricelam should we be able to handle this?

**Comment by bricelam** [comment]
Yes, I suspect it's a bug in [dotnet/roslyn-project-system](https://github.com/dotnet/roslyn-project-system). By default `AssemblyName` is set to `MSBuildProjectName`, but after renaming the project, the old value is probably still cached somewhere...

**Comment by bricelam** [comment]
> Microsoft.EntityFrameworkCore.Tools.DotNet is not migrated

`dotnet migrate` should handle this. Please create a new issue on [dotnet/cli](https://github.com/dotnet/cli) for this.

**Comment by rowanmiller** [comment]
BTW we suspect closing and re-opening VS would resolve this issue.
