### ISSUE TITLE
1.1 Tooling Not Compatible with Net46?

### ISSUE THREAD

**Issue by markolbert** [dotnet/efcore#7556]
I have an EF Core project which I recently upgraded to 1.1. Everything was working fine...until I tried to add a migration. Executing dotnet ef <whatever> on the command line now generates an error about not being able to find the ef module/program.

Digging into this a bit I discovered that there was a breaking change in the EF Core 1 -> 1.1 transition involving the tooling. In project.json you have to replace this dependency:

`"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
`

with

`"Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
`

Unfortunately...when I do that the package update fails with the error message that this version of the tooling does not support net46. 

Which I have to run under because of certain libraries that I'm using.

Here is the entire project.json file:

```
      "version": "1.0.0-*",
    
      "dependencies": {
        "ConnellDataCore": "1.0.0-*",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
        "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final", 
        "Microsoft.Extensions.Configuration": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Serilog": "2.3.0"
      },
    
      "buildOptions": {
        "emitEntryPoint": true,
        "xmlDoc": false
      },
    
      "frameworks": {
        "net46": {
          "frameworkAssemblies": {
            "System.IO.Compression": "4.0.0.0"
          }
        }
      },
    
      "tools": {
      }

```
I should also point out that the database is defined in a standalone-assembly, so I've had to use the "create a dummy static Program::Main()" trick, along with the "create a temporary context factory" trick.

How do I go about getting back to where I was, being able to add migrations to my EF Core database?

**Comment by markolbert** [comment]
After some further research I found another issue here which I >>think<< solved my problem.

The workaround involved downgrading to 1.0.0.-preview3-final tooling and then running dotnet restore. As well as moving the references to the tooling assemblies from under "dependencies" to under "tooling" (not sure why I had them under dependencies).

Is this still the best workaround at this point?

**Comment by rowanmiller** [comment]
@markolbert yes, that is the correct setup. This will all get much cleaner when we land on an RTM of the MSBuild tooling for .NET Core.
