### ISSUE TITLE
Option to only use explicitly specified columns

### ISSUE THREAD

**Issue by breyed** [dotnet/efcore#7561]
It would be helpful to be able to tell EF never to assume there are any columns on the database that I didn't explicitly put in my code first model. This can make troubleshooting much easier.

For example, I had a situation where I misconfigured a one-to-one relationship by forgetting to include calls to `HasForeignKey` and `HasPrincipalKey` in the Fluent API. Here's what I was supposed to do:

	class Member {
		public int Id { get; set; }
		public string Stuff { get; set; }
		public MemberDetail Detail { get; set; }
	}
	class MemberDetail {
		public int Id { get; set; }
		public string MoreStuff { get; set; }
	}

	// In OnModelCreating...
	var memberDetail = builder.Entity<MemberDetail>();
	memberDetail.HasKey(e => e.Id);
	memberDetail.HasOne(e => e.Member).WithOne(e => e.MemberDetail).HasForeignKey<MemberDetail>(e => e.Id).HasPrincipalKey<Member>(e => e.Id);

I may have forgot `HasKey` too, especially early on. I don't remember. It's all a fog. Reason being that it was terribly hard to debug. I got these crazy errors from SQL Server complaining that there was no column `MemberDetailId`, but I had no insight into why it was trying to use a column of that name. Even if the T-SQL was easy to read (which it wasn't because the structure was complex and it wasn't obvious how to repro the problem on a small scale), it still wouldn't have told me why EF generated the SQL it did.

Part of the confusion is that the project was a port from EF 5, which worked just fine with just a `[ForeignKey("Member")]` annotation on `MemberDetail.Id`. For EF Core, however, it's not enough.

I so wanted to beg EF, "Pllllleeeeeaaaasssseee don't invent columns for me. If the structure doesn't make sense to you, just tell me why." An error on the order of "cannot determine principle end..." would have been wonderful.

**Comment by tuespetre** [comment]
I agree with you, there is an existing enhancement issue here though: https://github.com/aspnet/EntityFramework/issues/1414

**Comment by rowanmiller** [comment]
Closing as dupe

**Comment by breyed** [comment]
To avoid confusion, it's worth nothing that this suggestion differs from #1414, as I detailed in a comment there. So it's not a pure duplicate. It does make sense to holistically consider it along with #1414, though, so for want of a "closed-merged" label, "closed-duplicate" is a useful disposition.

**Comment by avalanchus** [comment]
I ran into the same problem - using FluentAPI it is not possible to specify the name of a foreign key being simultaneously a primary key (inheritance), while using attributes - this is done easily. It is not clear why the point was closed. It's already 19 years, and things are still there
