### ISSUE TITLE
Installing EF Core globally

### ISSUE THREAD

**Issue by govis** [dotnet/efcore#7575]
This is a question - pretty much every guide out there says to install it via the Package Manager with <code>Install-Package Microsoft.EntityFrameworkCore.SqlServer</code> command. Unfortunately this ends up dumping 289MB worth of files into the project directory, which is not nearly sustainable with many projects and given that the actual binaries needed amount to only about 6MB.

So my question is where does one find an installer for the EF Core capable of installing it globally on a machine into a shared location along-side with .NET Core binaries?

This is for Visual Studio 2015 on Windows 10. Thank you in advance.

**Comment by bricelam** [comment]
In Visual Studio 2017, you can add [Package References in Project Files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files). Unlike the default `packages.config` experience, this uses a "global packages folder" so all projects share the same files.

You might be able to mimic this behavior on VS 2015 by adding a `NuGet.Config` file like the following:

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="C:\packages" />
  </config>
</configuration>
```

**Comment by govis** [comment]
Great, I'll give it a try. Thank you.
