### ISSUE TITLE
dotnet ef migrations add migration_name dont work on linux

### ISSUE THREAD

**Issue by deinok** [dotnet/efcore#7580]
I updated the project to VS17 style.

old `dotnet ef migrations add migration_name` dont work (Windows and Ubuntu) Cause: No project.json

VS17 doesnt open project.json projects.

Only works from the Package Manager `Add-Migration migration_name`

Whats the CLI equivalent without PackageManager for Windows and for Ubuntu?

**Comment by smitpatel** [comment]
See #7358 thread for detailed instructions on how to get command line tooling to work in VS2017

**Comment by deinok** [comment]
@smitpatel Thanks. Closing this. But please add more documentation.

**Comment by smitpatel** [comment]
cc: @rowanmiller

**Comment by rowanmiller** [comment]
Yep the docs will all be updated when VS2017 and our tools RTM
