### ISSUE TITLE
EF1.0.1 -> 1.1.0 migration indexes only a side of many-to-many relationship

### ISSUE THREAD

**Issue by bragma** [dotnet/efcore#7584]
UPDATE:
Ooops, sorry, this seems to be a duplicate of #7369. I didn't see it when searching issues for many-to-many.

----
Hi,
I've updated a project using EFCore 1.0.1 to 1.1.0 and found a different behavior on generated indexes for many-to-many join tables. Basically, now it creates only one index for one side (the second column) of the relationship.
Is it an optimization due to the fact that a composite index can also act as a single column index on the first column?

MORE DETAILS:
As an example with User <- ClubUser -> Club, the migration creating ClubUser is:

```
            migrationBuilder.CreateTable(
                name: "ClubUser",
                columns: table => new
                {
                    UserId = table.Column<int>(nullable: false),
                    ClubId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClubUser", x => new { x.UserId, x.ClubId });
                    table.ForeignKey(
                        name: "FK_ClubUser_Clubs_ClubId",
                        column: x => x.ClubId,
                        principalTable: "Clubs",
                        principalColumn: "ClubId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ClubUser_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "UserId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ClubUser_ClubId",
                table: "ClubUser",
                column: "ClubId");

```

Notice that only "IX_ClubUser_ClubId" is created, while previously it created also "IX_ClubUser_UserId" index. Is it correct?

Thanks!

**Comment by divega** [comment]
@bragma yes we added an optimization to try to avoid redundant indexes from being created by convention in 1.1. Is it causing any problems besides the removal of the index itself?

cc @AndriySvyryd
