### ISSUE TITLE
Migration gives full script even with no changes

### ISSUE THREAD

**Issue by Steve887** [dotnet/efcore#7603]
I am using ef.exe to generate migration files for my Entity Framework 1.1.0 context against an existing SQL Server database.

While a migration file is generated correctly, it always consists of a full migration script, creating every table and index, even when my database is up to date and contains an __EFMigrationsHistory table with my initial migration version in it.

Migration History table:
![image](https://cloud.githubusercontent.com/assets/129719/22872580/0ba4be06-f206-11e6-8b82-3f86191645d9.png)

**20170213052618_Test2** is my initial migration with consists of empty `Up` and `Down` methods:

    public partial class Test2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {            
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {           
        }
    }

Because my DbContext is in a class library, I have an external .Net 4.6 console application as per the following workaround http://benjii.me/2016/06/entity-framework-core-migrations-for-class-library-projects/ (except using .net 4.6 instead of core).

I downloaded the [EntityFrameworkCore.Tools](https://github.com/aspnet/EntityFramework.tools) solution and ran build.cmd to build ef.exe which I execute with the following options:

`ef migrations add Test -a "C:\<Path To DbContext Assembly>\<ContextAssembly>.dll" -s "C:\<Path to Console App>\<ConsoleApplication>.dll" --root-namespace <DbContext Namespace> --context <DbContext Name>`

This executes without any errors and generates a new migration file. However, even with no changes made to my model, the migration file contains commands to create a full database rather than the no changes I expected:

    public partial class Test : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Alert",
                columns: table => new
                {
                    Description = table.Column<string>(nullable: true),
                    EffectiveFromDate = table.Column<DateTime>(nullable: false),
                    EffectiveToDate = table.Column<DateTime>(nullable: true),
                    EnabledFlag = table.Column<bool>(nullable: false),
                    Name = table.Column<string>(maxLength: 250, nullable: false),
        etc etc etc  

Is there a reason `ef migration add` is producing a migration file with the full migration in it, rather than the diff, and how can I just produce a diff migration using this method?

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by rowanmiller** [comment]
Are you expecting migrations to be looking at the database schema to work out what changed? If so, that's not how migrations works. It keeps a snapshot of the model when the last migration was generated and then compares the current model to this. A snapshot should have been generated alongside the migration files when you created the `Test2` migration.

**Comment by Steve887** [comment]
@rowanmiller that was how I was assuming it worked. It makes sense now that it looks at the snapshot file to compare.

In my case, I also had to rebuild both my target and console applications after generating a migration to make sure the assemblies had the correct snapshots in them.

Does that also mean the connection string in my `IDbContextFactory` class I'm using, per the link above to get a parameterless constructor, is largely irrelevant except for the database provider?

**Comment by rowanmiller** [comment]
@Steve887 when adding a migration the database should not be involved (so the connection is never opened). The connection in `IDbContextFactory` is used when applying migrations.
