### ISSUE TITLE
UseCSharpNullComparisonBehavior

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#7604]
We need UseCSharpNullComparisonBehavior. Life is just too confusing without it !

P.S. We also need an easy way to sort NULL at the end instead of the beginning -- this has always been a bit of a problem.

**Comment by sjb-sjb** [comment]
More specifically, it should be UseCSharpNullComparisonBehavior == true. Who would ever want it to be false? 

I don't know, maybe this is the default --

**Comment by divega** [comment]
@sjb-sjb in EF Core by default uses in-memory (i.e. C#) semantics for null comparisons. You can turn that off by calling `UseRelationalNulls()` while configuring the `DbContext`. 

We do not have any plans to have an option to force null values to go at the end. Although some relational database such as PostgreSQL will do that by default and may provide ways to control the behavior, other relational databases don't do it. Plus the in-memory null semantics that you are asking for in the first place will result in nulls going at the beginning. I would recommend that you try workarounds such as the one described at http://stackoverflow.com/questions/11333863/sql-server-2005-order-with-null-values-at-the-end. 

Also, feel free to create a new issue if you hit any surprising behaviors while testing with EF Core.

**Comment by sjb-sjb** [comment]
Cool! And, thanks!
