### ISSUE TITLE
Query using Include problem

### ISSUE THREAD

**Issue by sonphnt** [dotnet/efcore#7610]
Hi Everyone,

I have 2 classes like:
Team and Member

I am using Scaffold-DbContext as Database first. It generates 2 classes with

```C#
public partial class Member
{
        public virtual Team Team {get;set;}
}

public partial class Team
{
        public virtual ICollection Member Member {get;set;}
}
```
And I want to get all member in database with Team object to get some information about the team, so I use this query
```C#
dbContext.Member.Include(x=>x.Team).ToList();
```
But the problem when I debug. It also load Members list inside Team entity as well. There are a lot of data.
The object looks like this

```
[
{
     Name: "John",
     Team: {
          Name: "Team 1",
          Member: [] **// I want to avoid and ignore loading this list**
     }
}
]
```

How to avoid this and using correctly?

Thank you very much

**Comment by ajcvickers** [comment]
@sonphnt The include tells EF that for each Member that is loaded the related Team should also be loaded. When that Team is loaded the already loaded Members are added to the collection on Team. In other words, EF isn't loading any more data, it is simply fixing up the references between already loaded data.

If you are having issues with JSON serialization, then you might want to look at this: #4646 and this #7564

**Comment by sonphnt** [comment]
Hi @ajcvickers 

Thanks for your reply but is there any settings to avoid "When that Team is loaded the already loaded Members are added to the collection on Team"

Because Parsing that collection to Json will include that Members array on Team that will generate a huge Json file unless I have to do manually code to get rid of before returning to client.

Thanks

**Comment by NageshAndani** [comment]
@sonphnt , I too has found this behavior resulting in a huge JSON object. As the issue is "closed-by-design", I chose to fix it myself by manually setting the `Member` to null for each member.
 
`var members = dbContext.Member.Include(x=>x.Team).ToList();
foreach (var member in members)
{
        member.Team.Member = null;
}`

This would result in:

`[
{
     Name: "John",
     Team: {
          Name: "Team 1",
          Member: null
     }
}
]`

**Comment by sonphnt** [comment]
Yes. To avoid returning a huge json to client. You should not return entity model like that. You need to cast or convert them to view model or using automapper way.
