### ISSUE TITLE
A severe error occurred on the current command

### ISSUE THREAD

**Issue by randdexco** [dotnet/efcore#7618]
We have 2 exact queries (with a different parameter) running on 2 separate instances of SQL one works OK, the other fires out a A severe error occurred on the current command

OK
-- p__linq__0: '32970379-9fbd-4570-bf20-ee667dc33beb' (Type = Guid, IsNullable = false)

-- Executing at 15/02/2017 14:07:06 +00:00

-- Completed in 4581 ms with result: ProfiledDataReader

ERROR
-- p__linq__0: '02a2a696-3cf6-49f3-8bc7-71cb2a7a1855' (Type = Guid, IsNullable = false)

-- Executing at 15/02/2017 13:33:34 +00:00

-- Failed in 5063 ms with error: A severe error occurred on the current command.  The results, if any, should be discarded.
A severe error occurred on the current command.  The results, if any, should be discarded.

We have been over configuration and schema settings on the SQL instances and both are identical other than that once instance is clustered, we are struggling to find the root cause and need some guidance on the best course of action to track down the issue

**Comment by rowanmiller** [comment]
It's unlikely that there is anything EF-specific in play here. Can you open up an issue in https://github.com/dotnet/corefx for the SQL Client team to look at (though it may be lower level than that too). It would be good to include the fill stack trace of the exception.
