### ISSUE TITLE
InMemory query regression: using Include causes FirstOrDefault to return null 

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#7631]
Queries that used to return an entity with InMemory store now return null.

**Repro**
Test: https://github.com/aspnet/MusicStore/blob/dc60a2e9c5e89d4f4324bb82e5c1af17f7d4490b/test/MusicStore.Test/StoreControllerTest.cs#L108

The query:
https://github.com/aspnet/MusicStore/blob/dc60a2e9c5e89d4f4324bb82e5c1af17f7d4490b/samples/MusicStore/Controllers/StoreController.cs#L59-L63

```c#
album = await DbContext.Albums
               .Where(a => a.AlbumId == id)
               .Include(a => a.Artist)
               .Include(a => a.Genre)
               .FirstOrDefaultAsync();
```

When the .Include extensions are removed from the query, it returns an entity as expected.

**Details**
EF Core version: Ms.EfCore.InMemory 1.2.0-preview1-23482

cc @anpete

**Comment by natemcmaster** [comment]
cc @kichalla @javiercn

**Comment by kichalla** [comment]
Thanks @natemcmaster ...I didn't notice your comment...I just now found the same...here `Artist` is null because of which the query is returning null...

**Comment by anpete** [comment]
@kichalla This is because Artist should never be null here - It is configured in the model as Required by convention because Album.ArtistId is not nullable. Either configure the relationship to be Optional, or ensure that the test albums have artists assigned.

**Comment by anpete** [comment]
Moved issue to MusicStore.
