### ISSUE TITLE
Unit test failing in Visual Studio 2017 RC.

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#7640]
I am seeing some strange behavior in 2017 RC.

The unit tests SqlServerDesignTimeProviderServicesTest and SqliteDesignTimeProviderServicesTest are failing for me when run inside Visual Studio.

The issue is that the assembly version for Microsoft.EntityFrameworkCore.SqlServer.Design is being returned as 1.0.0.0 instead of 1.2.0.0.  (DesignTimeProviderServicesTest.cs line 25)

When I view the package properties for this assembly in Visual Studio it is showing 1.0.0.0.  The csproj file is correctly pulling in EntityFramework.props which then includes version.props which has the assembly version set at 1.2.0.0 

Can someone else confirm this is happening for them?

**Comment by smitpatel** [comment]
They are running fine in current dev. You may have package versions mixed up.
Do a `git clean -xdf` followed by `build.cmd initialize` then open solution in VS.

**Comment by pmiddleton** [comment]
I took another look at it this morning.  I opened the net451 version of the dll in ildasm and can confirm the version is being set to 1.0.0.0  The netstandard1.3 dll is being set to 1.2.

This is happening for the following assemblies

* Microsoft.EntityFrameworkCore.Relational.Design
* Microsoft.EntityFrameworkCore.SqlServer
* Microsoft.EntityFrameworkCore.Relational.Specification.Tests
* Microsoft.EntityFrameworkCore.Specification.Tests
* Microsoft.EntityFrameworkCore.Sqlite.Design

I found two issues in the dotnet sdk project which look like they might be the cause of the problem.

https://github.com/dotnet/sdk/issues/422
https://github.com/dotnet/sdk/issues/93

Paul

**Comment by bricelam** [comment]
Yep. These are known issues. For now, you can safely ignore the three tests that fail.

**Comment by rowanmiller** [comment]
@bricelam is this tracked somewhere already?

**Comment by bricelam** [comment]
The two @pmiddleton mentioned should cover it.
