### ISSUE TITLE
Tests: Use SQLite In-Memory databases

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#7644]
All of our SQLite functional tests use an on-disk database. In theory, we could speed things up by using in-memory databases where possible.

**Comment by bricelam** [comment]
We could also consider using [Write-Ahead Logging](https://www.sqlite.org/draft/wal.html).

**Comment by ErikEJ** [comment]
"in theory" - I think it would be better to spend time on improving the SQL Server tests for speed.

**Comment by bricelam** [comment]
True, they take about twice as long as the SQLite tests. I'm mostly just looking for easy wins here; I agree we shouldn't spend a lot of time on it.

**Comment by ericsink** [comment]
I do use :memory: databases for (most of) my automated tests for SQLitePCL.raw.  Works out well, except of course for those cases where I *need* to test interaction with the file system.
