### ISSUE TITLE
Scaffolding creates an POCO for many to many relationships

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#7664]
I would like to migrate a project from EF 6 to EF Core, but one of the problems that I have it is that for N:N relationships, EF doesn't create the POCO entity, just use navigation properties. However, EF Core creates an entity POCO for this kind of relationships, so in my case, it is a problem because it would make me changes the code. I would like to have a set of POCO entities that I could use for EF 6, EF Core and my UI application (WPF).

Thanks.

**Comment by smitpatel** [comment]
See #1368
