### ISSUE TITLE
Serialization of EF objects with Relationships

### ISSUE THREAD

**Issue by Coruscate5** [dotnet/efcore#7675]
Was just curious if there is documentation or a proper way to generate full JSON of an EF entity with relationships.

Right now, my parent object when serialized produces "null" for properties that have object-relationships - for now I can generate an anonymous object & do the linking myself, but it would be cool if the known relationships (esp. 1-2-1) were serialized automatically..

e.g. MVC action -> "return Entity;" returns "EntityPrimitive1: Val, EntityImage: null" when Entity<->Image is a 1-to-1 relationship. Am I missing something?

**Comment by rowanmiller** [comment]
Did you load the EntityImage when you did the query? See https://docs.microsoft.com/en-us/ef/core/querying/related-data for more info.

**Comment by Coruscate5** [comment]
Hah - thanks, that looks like exactly what I'm missing. I'll try replacing my linq query with this later today..
