### ISSUE TITLE
Encoding utf-8 With MySql 

### ISSUE THREAD

**Issue by kleberksms** [dotnet/efcore#7683]
Im doing a sql query with EF Core, but my encodig return wrong,
https://stackoverflow.com/questions/42162182/encoding-mysql-ef-core
Databse settings:

    charset: latin1
    collation: latin1_general_ci

Database - engine InnoDb - charset: latin1 - collation: latin1_general_ci

This is a MySql Db

https://i.stack.imgur.com/sGBH1.png

https://i.stack.imgur.com/inh89.png

Repository

    public Repository(CrmGatewayCarteirasContext context)
    {
        Context = context;
        DbSet = context.Set<TEntity>();
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    public IEnumerable<TEntity> GetAll()
    {
        return DbSet.ToList();
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed) return;
        _disposed = true;
    }

project.json

{
"dependencies": {
    "Microsoft.NETCore.App": {
        "version": "1.1.0",
        "type": "platform"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Serilog.Extensions.Logging": "1.3.1",
    "Serilog.Sinks.RollingFile": "3.3.0",
    "Serilog.Exceptions": "2.3.0",
    "Seq.Extensions.Logging": "2.1.1",
    "Serilog.Sinks.Seq": "3.2.0",
    "Microsoft.EntityFrameworkCore.Design": {
        "type": "build",
        "version": "1.1.0"
    },
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "AutoMapper": "5.2.0",
    "AutoMapper.Extensions.Microsoft.DependencyInjection": "1.2.0",
    "CrmGateway.SharedKernel": "1.0.0-*",
    "Microsoft.ApplicationInsights.AspNetCore": "2.0.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "SapientGuardian.EntityFrameworkCore.MySql": "7.1.18",
    "StaticCommons": "1.4.0"
},
"tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Tools": {
        "version": "1.1.0-preview4-final",
        "imports": [
            "portable-net45+win8+dnxcore50",
            "portable-net45+win8"
        ]
    }
}}

**Comment by rowanmiller** [comment]
Can you start by filing an issue with MySQL - https://dev.mysql.com/. If they isolate it to an underlying issue in EF Core, they will file the appropriate issue back with us.
