### ISSUE TITLE
EntityFramework Core: Scaffold-DbContext - unable to generate entity type 

### ISSUE THREAD

**Issue by jan-github** [dotnet/efcore#7718]
The command

`Scaffold-DbContext "Server=(localdb)\mssqllocaldb;Database=xxx;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -Tables BC, BC_Template, Template -OutputDir Entities

generates only two of three entities (Bc.cs and Template.cs) and missing Navigation property.

Exception message:

> Unable to generate entity type for table 'dbo.BC_Template'. Please see the warning messages.

SQL script that creates the three tables:

```
USE [xxx]
GO
 
SET ANSI_NULLS ON
GO
 
SET QUOTED_IDENTIFIER ON
GO
 
CREATE TABLE [dbo].[BC](
       [BCID] [int] IDENTITY(1,1) NOT NULL,
       [BCName] [varchar](100) NOT NULL,
       [Description] [varchar](100) NOT NULL,
       [Active] [bit] NOT NULL,
CONSTRAINT [PK_BC_1] PRIMARY KEY CLUSTERED 
(
       [BCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
 
GO
 
USE [xxx]
GO
 
SET ANSI_NULLS ON
GO
 
SET QUOTED_IDENTIFIER ON
GO
 
CREATE TABLE [dbo].[Template](
       [TID] [int] IDENTITY(1,1) NOT NULL,
       [Name] [nvarchar](200) NOT NULL,
       [Type] [nvarchar](50) NOT NULL,
       [URL] [nvarchar](1024) NOT NULL,
CONSTRAINT [PK_Template] PRIMARY KEY CLUSTERED 
(
       [TID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
 
GO
 
ALTER TABLE [dbo].[Template]  WITH CHECK ADD  CONSTRAINT [CK_Type_Template] CHECK  (([Type]='Template' OR [Type]='Email' OR [Type]='SMS' OR [Type]='Attachment'))
GO
 
ALTER TABLE [dbo].[Template] CHECK CONSTRAINT [CK_Type_Template]
GO
 
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'checks if values for Type are set correctly' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Template', @level2type=N'CONSTRAINT',@level2name=N'CK_Type_Template'
GO
 
SET ANSI_NULLS ON
GO
 
SET QUOTED_IDENTIFIER ON
GO

USE [xxx]
GO

CREATE TABLE [dbo].[BC_Template](
       [ID] [int] NOT NULL,
       [BCID] [int] NOT NULL,
       [TID] [int] NOT NULL,
       [Order] [int] NOT NULL,
       [Condition] [nvarchar](200) NULL
) ON [PRIMARY]
GO
 
ALTER TABLE [dbo].[BC_Template]  WITH CHECK ADD  CONSTRAINT [FK_BC_Template_BC] FOREIGN KEY([BCID])
REFERENCES [dbo].[BC] ([BCID])
GO
 
ALTER TABLE [dbo].[BC_Template] CHECK CONSTRAINT [FK_BC_Template_BC]
GO
 
ALTER TABLE [dbo].[BC_Template]  WITH CHECK ADD  CONSTRAINT [FK_BC_Template_Template] FOREIGN KEY([TID])
REFERENCES [dbo].[Template] ([TID])
GO
 
ALTER TABLE [dbo].[BC_Template] CHECK CONSTRAINT [FK_BC_Template_Template]
GO





```

Classes generated:

    public partial class Bc
    {
        public int Bcid { get; set; }
        public string Bcname { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }

    public partial class Template
    {
        public int Tid { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
    }

EF Core Version: 1.1.0: 

    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.1.0",
      "type": "build"
    }

Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.0

Operating system: Windows 10

IDE: Visual Studio 2015 update 3

**Comment by ErikEJ** [comment]
BC_Template is missing a primary key

**Comment by jan-github** [comment]
Thank you, nfortunately I have overlooked something.
