### ISSUE TITLE
Version 1.1.0 Error while creating migrations from Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by raffaeu** [dotnet/efcore#7723]
I am trying to execute a Migration in a new project, using Entity Framework Core.

My project.json is configured as following:

```
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0"
```

This is the command I am trying to execute from Command Prompt

`dotnet ef migrations add CreateIdentitySchema`

And, I get back this exception:
![image](https://cloud.githubusercontent.com/assets/1304736/23337994/28b7ec04-fbff-11e6-8158-b07392b9804b.png)

If I remove a reference to `Microsoft.EntityFrameworkCore.Design`, the command `dotnet ef` throws a different exception, asking for a reference to this package.
Is this broken or not ready yet? Because from Nuget I can see that the latest RTM version is **1.1.0**

**Comment by raffaeu** [comment]
Instead if I use these verions:

```
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.1",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }

```
It works as expected

**Comment by bricelam** [comment]
For the best results using EF 1.1 with `project.json`, we recommend:
```JSON
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "type": "build",
      "version": "1.1.0"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "type": "build",
      "version": "1.1.0-preview4-final"
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  }
}
```

Other tips:
* Install the [latest version of NuGet](https://dist.nuget.org/index.html)
* Don't use a standalone app (has `"runtimes"` and is missing `"type": "platform"` on `Microsoft.NETCore.App`).
* If PMC isn't working, try `dotnet ef` instead.
* Ensure the LTS (1.0) Runtime is also installed. (from [.NET Core Downloads](https://www.microsoft.com/net/download/core#/runtime))
* DataAnnotations won't work as expected on UWP in this version

**Comment by raffaeu** [comment]
Hi @bricelam, I just tried and it works.
I am using ASP.NET Identity with ASP.NET Core 1.1.0 and SQL Server 2016

Thanks
