### ISSUE TITLE
Why Schema is null ? while excepted the default value.

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/efcore#7725]
I use DbContext Scaffold tool for converting AdventureWorks2014 to C# codes.

```
 AdventureWorks2014Context ctx = new AdventureWorks2014Context();
 var schema = ctx.Model.GetEntityTypes().FirstOrDefault().Relational().Schema; // return null
```

Why schema is null ? It should be **dbo** not null. 
or in PostgreSQL should be **public**.

How can I get schema value (default value not null) in cross platform way ? 
when I define a specific schema EF Core return value but when table use defalut database schema it return null Why ? How to fix it ?

**Comment by ajcvickers** [comment]
@HamedFathi The general philosophy that the reverse engineering tool uses is that when something in the database is the same as what EF would do by convention, then that thing is not explicitly mapped. This results in the minimal mapping required to use the database with EF, while also making it the most likely that the mappings can be used in a cross-provider way. In this case, EF will use the dbo schema if none is specified, so "dbo" is not included in the mapping.

In general EF metadata is not designed as a way of finding out information about the database. It will really only ever tell you back the things you already told it.

**Comment by HamedFathi** [comment]
@ajcvickers 

first thanks for clarification

> EF will use the dbo schema if none is specified, so "dbo" is not included in the mapping.

Can you say Where ? I want to know where EF set "dbo" for sqlserver for default schema.
Can you show me the code.

> In general EF metadata is not designed as a way of finding out information about the database. It will really only ever tell you back the things you already told it.


technically you right, but I think it can be simple cross platform solution for gathering information about any databases with a simple extension method on DbContext against write many query based on specific databases so getting some information from metadata that provided with EF Core can be useful in some requirement.

for example I wrote a simple extension method on DbContext for generating Stored Procedure for me with the EF metadata so I dont need to write queries for all databases.

finally Can you suggest a way for getting default schema when EF Core returns null ? maybe I can use reflection for getting that but I dont know where default schema is set and in which assembly.

**Comment by ajcvickers** [comment]
@HamedFathi EF never actually sets "dbo" anywhere. It relies on SQL Server using "dbo" as the default schema. Reverse engineering will set a different default schema if the database that is being reverse engineered is using some other than "dbo" as the default.

**Comment by francoisdenis** [comment]
One problem when the schema is null is that it causes a NullReferenceException when calling DbContext.Model.FindEntityType(entityName).

Any suggestion to avoid this ?

![Screenshot 2021-09-17 093746](https://user-images.githubusercontent.com/34503230/133743845-bae91f24-48c0-4ea1-91d3-3af785dc0a93.jpg)

**Comment by roji** [comment]
@francoisdenis can you please open a new issue and include a runnable code sample which shows the exception happening?
