### ISSUE TITLE
'System.MissingMethodException' occurred in System.Private.CoreLib.ni.dll in the latest prerelease

### ISSUE THREAD

**Issue by MohammedNoureldin** [dotnet/efcore#7728]
I want to report about a bug in the latest prerelease:

I am working on a project (Visual Studio 2015 update 3) where I am using **Entity framework core** with MySQL. I am able to write to data to my database, but when trying to **query data** using `DbSet<T>.Find(...)` or `FirstOrDefault` I get this exception:

> An exception of type 'System.MissingMethodException' occurred in
> System.Private.CoreLib.ni.dll but was not handled in user code
> 
> Additional information: Method not found: 'Void
> Microsoft.EntityFrameworkCore.Query.QueryContextFactory..ctor(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager,
> Microsoft.EntityFrameworkCore.Internal.IConcurrencyDetector,
> Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IChangeDetector)'

The solution:
OK it seems to be a bug in **MySQL -> entity framework adapter `MySql.Data.EntityFrameworkCore`**. I downgraded from `7.0.6-IR31` to `6.10.1-beta` and everything works fine now!

The same text in my stackoverflow quesion:
http://stackoverflow.com/questions/42471620/system-missingmethodexception-occurred-in-system-private-corelib-ni/42472883#42472883

**Comment by ajcvickers** [comment]
@mne1991 If this is an issue with the MySQL provider that you are using, then I would suggest filing an issue with that provider. Also, make sure that you are not mixing multiple versions of EF packages--check for any NuGet warnings. If there is still an issue with EF, then please file an issue with complete code or project to reproduce it.
