### ISSUE TITLE
How to manage migrations in different branches?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#7730]
Here's the situation:  I have two release branches, release/1.0 and release/1.1.  Release 1.0 is the version being QA'd for the next release, while 1.2 is for later release.  All Db migrations created for 1.0 automatically get pushed up to 1.1, and there are several migrations that are only on 1.1.  Let's say:

- Migration 1 is on 1.0
- Migration 2 is on 1.1
- Migration 3 is on 1.0
- Migration 4 is on 1.1

On the QA server, therefore, only migrations 1 and 3 have been run.

Now the QA version (1.0) is approved and pushed to Production.  Time to promote 1.1 to QA so they can start testing it.  Oops, problem: when we pushed 1.1 to QA, it ran Migration 4 as we expected, but it omitted Migration 2, because the QA database was already holding at Migration 3.

What's the proper way of dealing with this situation?  Perhaps EF should check for *all* new migrations, not just the ones that appear alphabetically after the last one?

**Comment by bricelam** [comment]
>  Perhaps EF should check for all new migrations, not just the ones that appear alphabetically after the last one?

This is how Migrations is expected to work. Not applying Migration 2 is a bug. Could you share a repro?

**Comment by shaulbehr** [comment]
Oh, my bad.  The scripts were failing to execute because of a schema conflict, but they were *trying* to run at least.  I fixed the scripts and now we're in sync again.  Thanks!
