### ISSUE TITLE
Wrong powershell version in Package Manager Console on Visual Studio 2017 RC 

### ISSUE THREAD

**Issue by shamglam** [dotnet/efcore#7731]
I'm trying to get up and running with EF Core on Visual Studio 2017 RC 4.

After installing Microsoft.EntityFrameworkCore.Tools and adding a very basic DBContext and a model I try to run add-migration in package manager console but I get the following error: 

The Entity Framework Core Package Manager Console Tools don't support PowerShell version 2.0. Upgrade to PowerShell version 3.0 or higher, restart Visual Studio, and try again.

I'm running on Windows 10 and the PS Version table in regular Powershell is: 

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

but the PSversiontable in Package Manager console is: 

```
Name                           Value                                                                                                                        
----                           -----                                                                                                                        
PSVersion                      2.0                                                                                                                          
PSCompatibleVersions           {1.0, 2.0}                                                                                                                   
BuildVersion                   6.1.7600.16385                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                              
WSManStackVersion              2.0                                                                                                                          
PSRemotingProtocolVersion      2.1                                                                                                                          
SerializationVersion           1.1.0.1              
```
so the required Powershell version is correct but the package manager console doesn't seem to use that.

### Steps to reproduce
run add-migration <whatever> in package manager console

### Further technical details
EF Core version: 1.1.0 and 1.1.0-preview4-final for Microsoft.EntityFrameworkCore.Tools
Database Provider: . Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 (10.0.14393)
IDE: Visual Studio 2017 15.0.0-RC 4 - 26206.0

**Comment by bricelam** [comment]
Could you re-submit this issue on the [NuGet/Home](https://github.com/NuGet/Home) repo? The package manager console has already initialized by the time any EF code is executed.

**Comment by bryanjhogan** [comment]
Link to open ticket - https://github.com/NuGet/Home/issues/4710

**Comment by Naresh3454** [comment]
https://developercommunity.visualstudio.com/content/problem/35803/help-error-the-package-manager-console-requires-po.html
