### ISSUE TITLE
No logging for Scaffolding-DbContext

### ISSUE THREAD

**Issue by markti** [dotnet/efcore#7734]
Running Scaffold-DbContext from Package Manager Console. Getting "Build failed." error message in read. No other details or logs provided as to what is causing the problem. No documentation on how to enable logging so that I can better diagnose the problem.

If you are seeing an exception, include the full exceptions details (message and stack trace).

Exception message: "Build failed."
Stack trace: NONE

### Steps to reproduce

Scaffold-DbContext -Provider "Microsoft.EntityFrameworkCore.SqlServer" -OutputDir "DataModel" -Connection "Server=tcp:mySqlAzureDb.database.windows.net,1433;Initial Catalog=MyAwesomeDatabase;User Id=MyAzureSqlUserName;Password=MyAzureSqlPassword;"

### Further technical details
EF Core version: found in project.json:

- Microsoft.EntityFrameworkCore.Design 1.1.0

- Microsoft.EntityFrameworkCore.SqlServer 1.1.0

- Microsoft.EntityFrameworkCore.SqlServer.Design 1.1.0

- Microsoft.EntityFrameworkCore.Tools 1.1.0-preview4-final

- Microsoft.NETCore.App 1.1.0

Framework: "dnxcore50"

Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise
IDE: Visual Studio 2015 update 3

**Comment by smitpatel** [comment]
Does your project build correctly?

**Comment by ajcvickers** [comment]
@markti If the build fails, then it is intended that you do a build using the normal build mechanism (e.g. from within Visual Studio) and use the output/notifications from that to fix any build issues.
