### ISSUE TITLE
Compound index with nullable field generates a filtered index

### ISSUE THREAD

**Issue by soycabanillas** [dotnet/efcore#7738]
Having this model:

    public class CTransferFeesAccounting
    {
        public CClient CClient { get; set; }
        public long? CClientId { get; set; }

        public CTransfer.CTransfer CTransfer { get; set; }
        public long CTransferId { get; set; }
    }

and this configuration:

            entity
                .HasIndex(k => new
                {
                    k.CClientId,
                    k.CTransferId
                })
                .IsUnique();

EF generates this index:

	CREATE UNIQUE NONCLUSTERED INDEX [IX_CTransferFeesAccounting_CClientId_CTransferId]
		ON [dbo].[CTransferFeesAccounting]([CClientId] ASC, [CTransferId] ASC) WHERE ([CClientId] IS NOT NULL);

This makes the index not unique for the whole table as I can repeat the same values (NULL, 3) (NULL, 3).

I don't know if there is a reason for this behavior, as I couldn't find an issue related, but from my point of view, this doesn't honor the configuration of the entity.

Trying to use this configuration:

	entity
		.HasAlternateKey(k => new
		{
			k.CClientId,
			k.CTransferId
		});

Changes the nullability of the CClientId, and I can no longer insert NULL values on CClientId.

Is there a reason for both behaviors? How can I configure the entity so I end up with the next index?

	CREATE UNIQUE NONCLUSTERED INDEX [IX_CTransferFeesAccounting_CClientId_CTransferId]
		ON [dbo].[CTransferFeesAccounting]([CClientId] ASC, [CTransferId] ASC);

**Comment by AndriySvyryd** [comment]
@soycabanillas This is by design to make SQL Server behavior closer to the ANSI standard. Currently the workarounds would be to make the index clustered or to edit the generated migration and add an operation that drops the filter.

In 2.0.0 We'll add a way to explicitly set a filter for the index:
```C#
entity
    .HasIndex(k => new
    {
        k.CClientId,
        k.CTransferId
    })
    .IsUnique()
    .HasFilter(null);
```
