### ISSUE TITLE
Query : investigate if its enough to visit AccessExpression of the NullConditionalExpression when looking for query sources requiring materialization

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#7746]
Currently in RequiresMaterializationExpressionVisitor, when processing NullConditional expression we only visit its AccessExpression. This might not be enough - Caller and NullableCaller might have some qsres that need to be materialized. For now it's not an issue because we mark all qsres participating in optional navigations, but when we start optimizing those queries we might need to investigate.

**Comment by smitpatel** [comment]
Just to expand on this for the processing of NullConditionalExpression
It is being ignored in ExpressionVisitorBase from visiting. Also it blocks `MemberAccessBindingExpressionVisitor` deriving from ExpressionVisitorBase.

**Comment by maumar** [comment]
It should be OK. Stuff in Caller/NullableCaller is never acesssible from the final projection (the result is either access operation or null)
