### ISSUE TITLE
Transaction auto-rollback

### ISSUE THREAD

**Issue by sm-g** [dotnet/efcore#7748]
[Docs](https://docs.microsoft.com/en-us/ef/core/saving/transactions) contains example without `Rollback` with note "transaction will auto-rollback when disposed if either commands fails".

Does it mean that no 
```
catch (Exception ex) { 
 transaction.Rollback(); 
}
```
needed (opposite to code samples everywhere)? From which line on code than `Rollback` actually will be called?

**Comment by rowanmiller** [comment]
@divega and @AndriySvyryd for their input on this one. Disposing does rollback on SQL Server, but it sounds like the behavior is provider dependent... so maybe we should be rolling back manually in the docs? Or maybe is accepted enough that providers should do this, so we are ok showing simpler coding pattern?

From https://msdn.microsoft.com/en-us/library/bf2cw321(v=vs.110).aspx

> Dispose should rollback the transaction. However, the behavior of Dispose is provider specific, and should not replace calling Rollback.

**Comment by divega** [comment]
Never thought of this behavior being provider specific (i.e. it seems the only behavior that would make sense) but it could be just me :smile: Rolling back inside a catch block should work too, it is only more complicated code and a more complicated interaction with the server.

**Comment by AndriySvyryd** [comment]
I don't think we've called Rollback before in docs, but it's not that much additional code.

**Comment by ajcvickers** [comment]
Do we know of any providers where its is needed to call Rollback explicitly? Our tests rely on Dispose using a rollback, so I think we know it is good for at least SQL Server, SQLite, SQL CE, and Postgres. 

My preference would be to leave it as is.

**Comment by ErikEJ** [comment]
@ajcvickers Is it this test 🤕 https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/TransactionSqlCetest.cs ?

**Comment by ajcvickers** [comment]
@ErikEJ No, what I mean is that we create a transaction and throw it a way in all our functional tests that manipulate data so as to isolate them from each other.

**Comment by rowanmiller** [comment]
I would rather leave things as-is, adding the try/catch just adds clutter to the code 😄

**Comment by sm-g** [comment]
> Do we know of any providers where its is needed to call Rollback explicitly?

I'm tring to find `rollback` in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/search?utf8=%E2%9C%93&q=rollback

**Comment by AndriySvyryd** [comment]
@sm-g The file you are looking for is https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlTransaction.cs
And it does call rollback
