### ISSUE TITLE
Entity Framework Core error in asp.net web application

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#7753]
When I add ENtity Framework Core 1.1 in a web application with Web API 2, I get the following error during compilation:

Severity Code Description Project File Line Suppression State Error CS1703 Multiple assemblies with equivalent identity have been imported: 'C:\Users\User1\Documents\Visual Studio 2015\Projects\WebApplication8\packages\System.Xml.ReaderWriter.4.3.0\lib\net46\System.Xml.ReaderWriter.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.6.1\Facades\System.Xml.ReaderWriter.dll'. Remove one of the duplicate references. WebApplication8 C:\Users\User1\Documents\Visual Studio 2015\Projects\WebApplication8\WebApplication8\CSC 1 Active

EF Core version: 1.1
Operating system: Windows 10
IDE: Visual Studio 2015
Web API 2

**Comment by smitpatel** [comment]
Possibly related https://github.com/dotnet/corefx/issues/14050
