### ISSUE TITLE
Microsoft.EntityFrameworkCore.OData

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/efcore#7759]
Please consider creating a Microsoft.EntityFrameworkCore.OData implementation that given an connection/URI endpoint to an OData service can/will act as if the consumer is connection to a local provider similar to in usage to that of other providers  

`ODataServiceCollectionExtensions`
``` C#
public static IServiceCollection AddEntityFrameworkODataDatabase(
            [NotNull] this IServiceCollection serviceCollection)
```

`ODataDbContextOptionsExtensions`
``` C#
public static DbContextOptionsBuilder UseODataDatabase(
            [NotNull] this DbContextOptionsBuilder optionsBuilder
            [NotNull] string odataEndpoint,
            [CanBeNull] Action<ODataDbContextOptionsBuilder> odataOptionsAction = null)
```

**Comment by ajcvickers** [comment]
@grahamehorner This is not something we plan to implement. Most EF Core providers are implemented by the community and we would be happy if somebody in the community wanted to tackle this. If so, then we would add it to the list of providers available for EF Core: https://docs.microsoft.com/en-us/ef/core/providers/index

**Comment by grahamehorner** [comment]
seems a bit of a strange decision given the number of Microsoft products and services that use odata?

**Comment by divega** [comment]
@grahamehorner I personally think this is a good idea. The triage decision to close the issue means mainly that we don't think it belongs in our issue tracker: 
- Based on our plans and priorities, the EF team is not currently planning to build an OData provider. 
- Also, based on the information currently available to us, if anyone from the community or even another Microsoft team decided to create an OData provider, the code would probably belong in a different repository. 

All this can change but we try to keep open only the issues that are actionable for our team and ideas that can be implemented by the community in the EF Core codebase.

**Comment by grahamehorner** [comment]
it may be time for me to start a open source project I think ;)

**Comment by TonyValenti** [comment]
@grahamehorner - Did you ever get OData working with EFCore?  I need to expose EFCore objects to OData and I keep getting:
````
On data context type 'CachingContext', there is a top IQueryable property 'DatabaseSettings' whose element type is not an entity type. Make sure that the IQueryable property is of entity type or specify the IgnoreProperties attribute on the data context type to ignore this property.
````
