### ISSUE TITLE
EF Core throw error "System.InvalidOperationException"

### ISSUE THREAD

**Issue by Edward-Zhou** [dotnet/efcore#7762]
I follow [Building Your First Web API with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api), and while trying Update query, I got error below:
Exception message:

> An exception of type 'System.InvalidOperationException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

> Additional information: The instance of entity type 'TodoItem' cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context.

### Steps to reproduce
Startup.cs
 ```
public void ConfigureServices(IServiceCollection services)
        {
            //inject repository into DI container, use database in memory
            services.AddDbContext<TodoContext>(options => options.UseInMemoryDatabase().UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking));
            //inject repository into DI container, and use sql databse
            //services.AddDbContext<TodoContext>(options=>options.UseSqlServer(Configuration["ConnectionStrings:DefaultConnection"]));


            //The first generic type represents the type (typically an interface) that will be requested from the container. 
            //The second generic type represents the concrete type that will be instantiated by the container and used to fulfill such requests.
            services.AddSingleton<ITodoRepository, TodoRepository>();

            //add mvc service to container, this is conventional routing
            //This also applys to web api which is Attribute Routing
            services.AddMvc();
        }
```
```
public class TodoRepository : ITodoRepository
{
    private readonly TodoContext _context;
    public TodoRepository(TodoContext context)
    {
        _context = context;
        //initialize database
        Add(new TodoItem { Name = "Item1" });
        //Add(new TodoItem { Name = "Item2" });
        //Add(new TodoItem { Name = "Item3" });
    }

    public IEnumerable<TodoItem> GetAll()
    {
       return _context.TodoItems.AsNoTracking().ToList();
    }

    public void Add(TodoItem item)
    {
        _context.TodoItems.Add(item);
        _context.SaveChanges();
    }

    public TodoItem Find(long key)
    {
        return _context.TodoItems.AsNoTracking().FirstOrDefault(t => t.Key == key);
    }

    public void Remove(long key)
    {
        var entity = _context.TodoItems.AsNoTracking().First(t => t.Key == key);
        _context.TodoItems.Remove(entity);
        _context.SaveChanges();
    }

    public void Update(TodoItem item)
    {
        _context.TodoItems.Update(item);
        _context.SaveChanges();
    }
}`
```

I got error at below code:
```
`    public void Update(TodoItem item)
    {
        _context.TodoItems.Update(item);
        _context.SaveChanges();
    }`
```

### Further technical details
EF Core version:     "Microsoft.EntityFrameworkCore": "1.1.0",
Database Provider:     "Microsoft.EntityFrameworkCore.InMemory": "1.1.0"
Operating system: 
IDE: Visual Studio 2015

Source Code:[https://github.com/Edward-Zhou/DotNetCore](https://github.com/Edward-Zhou/DotNetCore)

**Comment by rowanmiller** [comment]
The problem is that your repository is registered as singleton, meaning there is one instance off it for all requests. That means you are using the same context instance for all requests too. This won't work when you have more than one concurrent request, as DbContext is not thread safe. At the moment your not hitting that though, the problem is that you have the same context and your Update method is trying to update two instances of `ToDoItem` that represent the same row in the database (i.e. they have the same key). This isn't supported, a single instance of a context can only ever have one object that represents a given row.

The solution is probably to make your repository scoped. I'm actually surprised that it works at the moment, I thought DI would have thrown injecting a scoped service (the context) into a singleton service (the repository).

**Comment by ajcvickers** [comment]
@rowanmiller "I thought DI would have thrown injecting a scoped service (the context) into a singleton service" I believe this validation is coming in 2.0, although I don't know if it will be on by default. As of 1.1 D.I. doesn't do this check.
