### ISSUE TITLE
NU1012 dependency conflict. microsoft.entityframeworkcore 1.1.0 expected microsoft.extensions.logging >= 1.1.0 but received 1.0.0

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/efcore#7763]
Installing EFCore 1.1.0 with asp.net core application with full .net framework gives the following error:

![image](https://cloud.githubusercontent.com/assets/10031739/23506382/0211c940-ff6e-11e6-981f-86fbed6de35d.png)

NU1012 dependency conflict. microsoft.entityframeworkcore 1.1.0 expected microsoft.extensions.logging >= 1.1.0 but received 1.0.0

### Further technical details
EF Core version:1.1.0
Operating system: Windows 10
IDE: Visual Studio 2015 with update 3

**Comment by bricelam** [comment]
It looks like you're using ASP.NET Core 1.0 with EF Core 1.1. This is not a supported scenario. Please make sure you're using the same version for each.

If you accept being unsupported, you can probably work around this by adding an explicit dependency on the higher version of the conflicting packages to your `project.json`.
