### ISSUE TITLE
Question: Accessing Current DbContext in Extension

### ISSUE THREAD

**Issue by rjperes** [dotnet/efcore#7764]
Hi,
Sorry, not an issue, but a question: is there any way by which we can access the current context in an extension (IDbContextOptionsExtension)? There is only one method, ApplyServices, which takes a IServiceCollection. I tried building the IServiceProvider and asking for either DbContext or ICurrentDbContext, but no luck. Is this possible at all?
Thanks!
RP

**Comment by ajcvickers** [comment]
@rjperes What is it that you need the context for? IDbContextOptionsExtension has a single responsibility (add services to the internal service collection) that is intended to be used before the context is initialized, so even if the context was available it would likely not be possible to use it for much.

**Comment by rjperes** [comment]
Hi, Arthur! Imagine, for example, that you want to change the model at runtime.

**Comment by ajcvickers** [comment]
@rjperes You can set the model in OnConfiguring or AddDbContext using the DbContextOptionsBuilder.
