### ISSUE TITLE
Sometimes SelectExpressions are pushed down unnecessarily

### ISSUE THREAD

**Issue by tuespetre** [dotnet/efcore#7766]
There are many cases where, for one reason or another, `LiftSubQuery` will push a `SelectExpression` down into a subquery even though it is not required.

Some examples:

- It's being pushed down in the `MainFromClause` even though there are no `JoinClause`s, `GroupJoinClause`s, or `AdditionalFromClause`s
- It's being pushed down in a `JoinClause`, a `GroupJoinClause`, or an `AdditionalFromClause` even though the query will not be able to be flattened

**Comment by tuespetre** [comment]
This was largely resolved by #7843 and will be handled when #7831 is addressed (the third point about inheriting from SubQueryFromClauseFlattenrr, to be specific) 

cc @smitpatel

**Comment by divega** [comment]
@maumar @smitpatel @anpete should this issue be marked as closed-fixed as per the comment above? Or is it a duplicate?

**Comment by smitpatel** [comment]
dupe of #8094
