### ISSUE TITLE
dotnet ef migrations add has a -o parameter this is not present in dotnet ef migrations remove

### ISSUE THREAD

**Issue by viksabnis** [dotnet/efcore#7780]
dotnet ef  migrations add --help
Project ADS.SwarmWebApi (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Usage: ef.dll migrations add [arguments] [options]
Arguments:
  [name]  The name of the migration
Options:
  -h|--help                       Show help information
  **## -o|--output-dir <path>          The directory (and sub-namespace) to use. If omitted, "Migrations" is used. Relative paths are relative the directory in which the command is executed.**
  -c|--context <context>          The DbContext to use. If omitted, the default DbContext is used
  --json                          Use json output. JSON is wrapped by '//BEGIN' and '//END'
  --verbose                       Show verbose output
  --assembly <assembly>           The assembly file to load.
  --startup-assembly <assembly>   The assembly file containing the startup class.
  --data-dir <dir>                The folder used as the data directory (defaults to current working directory).
  --project-dir <dir>             The folder used as the project directory (defaults to current working directory).
  --content-root-path <dir>       The folder used as the content root path for the application (defaults to application base directory).
  --root-namespace <namespace>    The root namespace of the target project (defaults to the project assembly name).
  -e|--environment <environment>  The environment to use. If omitted, "Development" is used.

The -o|--output-dir is missing in dotnet ef migrations remove

 dotnet ef  migrations remove --help
Project ADS.SwarmWebApi (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Usage: ef.dll migrations remove [options]
Options:
  -h|--help                       Show help information
  -c|--context <context>          The DbContext to use. If omitted, the default DbContext is used
  -f|--force                      Removes the last migration without checking the database. If the last migration has been applied to the database, you will need to manually reverse the changes it made.
  --json                          Use json output. JSON is wrapped by '//BEGIN' and '//END'
  --verbose                       Show verbose output
  --assembly <assembly>           The assembly file to load.
  --startup-assembly <assembly>   The assembly file containing the startup class.
  --data-dir <dir>                The folder used as the data directory (defaults to current working directory).
  --project-dir <dir>             The folder used as the project directory (defaults to current working directory).
  --content-root-path <dir>       The folder used as the content root path for the application (defaults to application base directory).
  --root-namespace <namespace>    The root namespace of the target project (defaults to the project assembly name).
  -e|--environment <environment>  The environment to use. If omitted, "Development" is used.

I want to create an assembly which contains only for my migrations - so that the migrations classes arent included in my runtime. 

The --output-dir flag lets me create the migrations in a separate folder --- but now i have no way to remove a migration once added

**Comment by smitpatel** [comment]
`dotnet ef migrations remove` let you remove the last migration applied for given context (if there are multiple). Why do you need to specify a folder for that?
For adding migrations `-o` flag tells where to put new migration files since we are generating new files. Remove doesn't generate files hence doesn't have the flag.

**Comment by bricelam** [comment]
> but now i have no way to remove a migration once added

If you move the migration classes to a separate project, you should then execute the `dotnet ef` command on that project for migraitons operations.

**Comment by VikSab** [comment]
there is no way to execute the dotnet ef command on that project - when i did i got this error message

Could not invoke this command on the startup project '<projectName> '. This version of the Entity Framework Core .NET Command Line Tools does not support commands on class library projects in ASP.NET Core and .NET Core applications. See http://go.microsoft.com/fwlink/?LinkId=798221 for details and workarounds.
-----------------------------------------------------------------------------
if i try to use the dotnet ef --s <project that has context and startup> migrations add/remove - but since the startup project no longer needs the migrations assembly dependency - it is unable to find the current assembly in the startup projects binaries

**Comment by obelixA** [comment]
what's even more, if you use the -o parameter to push the migrations into a separate folder neither the C# "database.migrate()" command nor the nuget console command "update-database" can find the migrations anymore. So there is missing something....

**Comment by bricelam** [comment]
Well, it *should* be possible to reference the migrations assembly from the startup project only at build time (i.e. it won't get published to the server) using the following.
```XML
<ProjectReference Include="..\MyApp.Migrations\MyApp.Migrations.csproj"
                  PrivateAssets="All" />
```
But it doesn't appear to work, so I've filed dotnet/sdk#952.

**Comment by VikSab** [comment]
This means there is a circular dependency - as the Migrations Assembly needs to be dependent on the Startup Assembly for the DbContext  (FYI this is a dotnet core project and we are using project.json till msbuild is mainlined)

**Comment by bricelam** [comment]
@obelixA I've created a sample that uses multiple assemblies with migrations in [bricelam/Sample-SplitMigrations](https://github.com/bricelam/Sample-SplitMigrations).

I'm going to close this issue for now, but let me know if you need any additional help getting this working.

**Comment by VikSab** [comment]
the sample given is for .net with csproj - this issue is not resolved for dotnet core usage with projectjson

**Comment by bricelam** [comment]
The [.NET Core SDK](microsoft.com/net/download/core) RTMed today. We are encouraging everyone doing .NET Core development to move to Visual Studio 2017, including [migrating from project.json to csproj](https://docs.microsoft.com/en-us/dotnet/articles/core/migration/). We will not be supporting csproj and MSBuild for .NET Core in Visual Studio 2015.
