### ISSUE TITLE
how to migrate from sqlite to mysql

### ISSUE THREAD

**Issue by geminiyellow** [dotnet/efcore#7788]
i use sqlite to create my first aspnet core webapi server. and it works good.
but when i try to update my database, the sqlite have lots of limits. 
so i plan to move to mysql. 

then i change my connection string, change my provider, and use 

```
dotnet ef migrations add "MySQL" -o "Models/Migrations" -v
dotnet ef database update -v
```

ok, the migration file show that there is no change.and the ef cli is work with no error.

but when i `dotnet run`, the database seeder is down. it tell me, the `[Key] Id` cannot be null.
that means id cannot **Generated On Add**. hmm? what is happend? anybody can tell me why? 

### Further technical details
EF Core version: `<PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.0" />`
Database Provider: `Pomelo.EntityFrameworkCore.MySql`
Operating system: `mac os 10.12.4 Beta`
IDE: `dotnet cli`

```
dotnet --info
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview4-004233
```

**Comment by geminiyellow** [comment]
and i try to remove all migration layer, and create it from head.
then i found that,

```
-                    Id = table.Column<int>(nullable: false)
-                        .Annotation("Sqlite:Autoincrement", true),
+                    Id = table.Column<int>(nullable: false)
+                        .Annotation("MySql:ValueGeneratedOnAdd", true),
```

then my seeder is work again.

please tell me that is ef core cli 's bug. or show me what is the right flow to migrate from one db to next.

**Comment by geminiyellow** [comment]
and i try the mssql also, use `Microsoft.EntityFrameworkCore.SqlServer` provider, 
but it show

`To change the IDENTITY property of a column, the column needs to be dropped and recreated.`

**Comment by ajcvickers** [comment]
@geminiyellow EF Core provides a common set of patterns and mechanisms for working with databases, but does not attempt to provide a completely abstract layer over the database. In particular, where different databases do things in different ways, EF Core allows the application to make use of these database-specific features. This is also true of Migrations, where one of the things that is handled differently by different databases is value generation. This means that if you move from one database to another you will likely need to regenerate your migrations or hand edit them to take into account the differences. Given this, from what I can see, everything you are reporting is expected. If you have an issue after starting with a clean database running migrations generated for that database, then please feel free to create a bug with those details.

**Comment by geminiyellow** [comment]
oh... ok, got it, i love ef.
