### ISSUE TITLE
Version 1.1: Add-Migration with Context in separate Assembly

### ISSUE THREAD

**Issue by DominicSachs** [dotnet/efcore#7790]
I have the following project structure:

- MyWebApi
- MyCore
- MyServer

MyServer contains the DbContext which is internal. Now i tried to add migrations in MyServer assembly.

In the package manager console ("Default project": MyWebApi) i tried to execute:
Add-Migration Initial --startup-assembly MyWebApi

The following error occours:
Add-Migration : A positional parameter cannot be found that accepts argument '--startup-assembly'.

The use of MigrationsAssembly("WebApi") to generate migrations inside the WebApi project is not an option because the DbContext is internal. How can i use the migrations in a separate assembly with an internal DbContext and without to configure the libraray as an executable.

MyServer -> project.json
"Microsoft.EntityFrameworkCore": "1.1.0",
"Microsoft.EntityFrameworkCore.Design": "1.1.0",
"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"

**Comment by bricelam** [comment]
The name of the PowerShell parameter is `-StartupProject` (not `--startup-assembly`). To see the help for a command in PowerShell, use `Get-Help Add-Migration`.

**Comment by DominicSachs** [comment]
If i use -StartupProject the following error occurs:
Could not find assembly '...\bin\Debug\net461\win7-x64\MyServer.exe'.

There is the MyServer.dll but not MyServer.exe. I really don't want to change my lib to an executable. Is there any other possibility?

**Comment by bricelam** [comment]
For the best results with `project.json`, use the CLI comamnds (i.e. `dotnet ef migrations add --startup-project MyWebApi`)
