### ISSUE TITLE
global level handling of IsDeleted Filter

### ISSUE THREAD

**Issue by krishnasingh1818** [dotnet/efcore#7796]
i have sql db with tables having isdeleted flags.  can i intercept and append isDeleted==0 filter globally  instead of specifying in every join clause for every entity. eg  if i have ef query with joins of 5 entities then for each join i dont want developers to use isdeleted == 0

please advise.

**Comment by ajcvickers** [comment]
@krishnasingh1818 This is something that isn't currently implemented, but we are looking at for a future release. It is being tracked by #7413
