### ISSUE TITLE
A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)

### ISSUE THREAD

**Issue by eriksendc** [dotnet/efcore#7800]
Hi All,

In our production environment we see sporadic exceptions stating `A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)`.

At the moment we're using a pretty simple connection string:

```
Server=172.24.32.7;Database=GetYourPet_1_1_0;User Id=***;Password=***;MultipleActiveResultSets=true
```

The database server is a separate machine from the web server, so there is networking involved. So I'm not sure why the connections go down in the first place, but then I'm wondering if there's a way to catch this exception more generically and retry? And / or should we have more specific settings in the connection string about the size of the connection pool?

Sort of desperate here... any help would be great.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
Stack trace:
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) ~    
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) ~    
at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error) ~   
at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync() ~    
at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket() ~    
at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer() ~    
at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value) ~    
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) ~    
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() ~    
at System.Data.SqlClient.SqlDataReader.get_MetaData() ~    
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) ~    
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest) ~    
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) ~    
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) ~    
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) ~    
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection) ~    
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) ~    
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer) ~    
at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state) ~    
at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext() ~    
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source) ~    
at lambda_method(Closure , QueryContext ) ~    
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc) ~    
at GetYourPet.Services.MeetUpService.Get(String adopterUserId, Int32 petId, ApplicationUserRole applicationUserRole) in D:\a\1\s\GetYourPet\src\GetYourPet\Services\MeetUpService.cs:line 45 ~    
at GetYourPet.Controllers.MeetUpsController.Get(String adopterUserId, Int32 petId) in D:\a\1\s\GetYourPet\src\GetYourPet\Controllers\MeetUpsController.cs:line 63
```
### Steps to reproduce
There are no deterministic steps to reproduce
```c#
line 45 from MeetUpService.cs:

MeetUp meetUp = _applicationDbContext.MeetUps.Where(mu => mu.AdopterUserId == adopterUserId && mu.PetId == petId).FirstOrDefault();
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012 R2
IDE: Visual Studio 2015 w/ Update 3 (but that's just what we develop with... the issue is occurring in our production environment)

**Comment by eriksendc** [comment]
So any feedback on ideas for connection string enhancements would be great. I also just found this. Since we're on 1.1.0, we could probably use this, right?

https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency

I really appreciate any help. I understand this is more likely not an issue for this team...

**Comment by ErikEJ** [comment]
Are you disposing your DbContext properly? Could be Connection Pooling related (Connection Resiliency does not cover this error)

**Comment by eriksendc** [comment]
Hi @ErikEJ ,

Thanks for responding. We're not explicitly disposing. Never saw that in any sample code for EF Core / ASP.NET Core... Our ApplicationDbContext object is the one you get when you do a  File New --> Asp.NET project. We use the standard dependency injection approach to get an instance of the context. I'm not quite sure of the lifecycle of the ApplicationDbContext object after, say, one of our WebAPI controller methods completes. We're using the following pattern:

Controller
```
[Route("api/[controller]")]
public class MeetUpsController : Controller
{
    private readonly IMeetUpService _meetUpService;

    public MeetUpsController(IMeetUpService meetUpService)
    {
        _meetUpService = meetUpService;
    }

    // GET: api/meetups
    [HttpGet]
    public MeetUp Get([FromQuery]string adopterUserId, [FromQuery]int petId)
    {
        return _meetUpService.Get(adopterUserId, petId, User.GetApplicationUserRole());
    }
}
```

Service
```
public class MeetUpService : IMeetUpService
{
    private readonly ApplicationDbContext _applicationDbContext;

    public MeetUpService(ApplicationDbContext applicationDbContext)
    {
        _applicationDbContext = applicationDbContext;
    }

    public MeetUp Get(string adopterUserId, int petId)
    {
        return _applicationDbContext.MeetUps.Where(mu => mu.AdopterUserId == adopterUserId && mu.PetId == petId).FirstOrDefault();
    }
}
```

So is there a place where we're supposed to be disposing?

Thanks,
-Brian Eriksen

**Comment by ajcvickers** [comment]
@eriksendc If IMeetUpService is registered as a scoped service, then everything should be being disposed correctly.

**Comment by eriksendc** [comment]
At the moment we register services as transient:
```
services.AddTransient<IMeetUpService, MeetUpService>();
```
The DbContext is registered this way:
```
services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```
which... as I understand it, registers it as scoped.

So @ajcvickers you would say we should change service registration to AddScoped() (at least for those services that use ApplicationDbContext)? I would have thought that either way you'd get dispose being called...

**Comment by ajcvickers** [comment]
@eriksendc Transient registration for IMeetUpService is also fine.

**Comment by eriksendc** [comment]
So that means that probably we're OK and we just need to wire up the new connection resiliency feature? I'm wondering if we need to tune anything having to do with connection pooling via the connection string...

**Comment by ajcvickers** [comment]
@eriksendc I was only commenting on the dispose question. It looks like there are low-level network issues, and I don't know off the top of my head if this error is considered one of the transient errors that can be recovered from--@ErikEJ indicated it is not. We will discuss further and get back to you.

**Comment by eriksendc** [comment]
@ErikEJ and @ajcvickers  thanks in advance for thinking through this... Let me know if there is any kind of tracing that I could turn on at either end (client or server - web server or or db server) that would provide helpful diagnostic information. I have to say we are seeing a much higher rate of these errors than I'd have expected... Not being able to retry will be a bummer...

FYI, the transport-level exception that is detected / caught by our code is immediately preceeded in our logs by this, logged at the ERROR level:
```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory|An exception occurred in the database while iterating the results of a query.
```

**Comment by eriksendc** [comment]
More info... In the logs, after the stack trace, the following is logged:
```
ClientConnectionId:17ab418e-09d6-4219-b60d-0e9eac0656ef
Error Number:-1,State:0,Class:20
```
I went through the last 24 hours of logs and found 6 occurrences of this error. I then went to the database and ran the following queries:
```
select * FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = 'RING_BUFFER_CONNECTIVITY' and record like '%b8933fdc-8eb5-4bf2-a213-87576f58fdbd%'
select * FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = 'RING_BUFFER_CONNECTIVITY' and record like '%a0ce52ce-73bb-4224-9475-65208c931f5a%'
select * FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = 'RING_BUFFER_CONNECTIVITY' and record like '%9d1d4314-b310-4786-9e4e-86651002d31d%'
select * FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = 'RING_BUFFER_CONNECTIVITY' and record like '%9927083b-6d9c-4876-ad3e-77631b876932%'
select * FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = 'RING_BUFFER_CONNECTIVITY' and record like '%237aafdb-6d8d-4a31-a555-b10a3f8b8db6%'
select * FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = 'RING_BUFFER_CONNECTIVITY' and record like '%17ab418e-09d6-4219-b60d-0e9eac0656ef%'
```
I was hoping to find evidence as to why the client connection would have been dropped by the server, but there were no entries in the connectivity ring buffer. I did spot check the records in the ring buffer... there were fewer than 1000 records there, so it's not like the ring buffer had already overwritten itself.

**Comment by AndriySvyryd** [comment]
@eriksendc Please enable connection resiliency as described in https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency

If you still see the exception you would need to create a custom retry strategy (derived from [SqlServerRetryingExecutionStrategy.cs](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs)) that retries on this error  but please let us know if that's the case.

**Comment by eriksendc** [comment]
@AndriySvyryd OK. Will give that a try and report back. We're putting out a release this Sunday, so I should have some results to share early next week. Just to be clear, though, @ErikEJ 's first reply sounded pretty definitive: "Connection Resiliency does not cover this error". I also see you commented here:

http://stackoverflow.com/questions/25998625/why-does-sqlazureexecutionstrategy-not-handle-error-19-physical-connection-i

The higher ranked answer there had a solution that was basing the retry off of looking at the text of the error. That seems a bit sub-optimal. One would hope there would be some combination of error codes that would be the thing to consider... and you yourself stated "some can be retried and some cannot". So how will I be able to determine when it is safe to retry?

**Comment by AndriySvyryd** [comment]
@eriksendc You would need to log all the error codes (the exception message only shows the first one) and make a judgement call. The strategy shipped with EF retries all the errors that are known to be transient and safe to retry.

It would also depend on how important is the response delay in your app. One way of dealing with errors that might not be transient is to use the default list of errors and a low bound on retry count in the path where a user is blocked. And if it takes too long or any possibly transient error is encountered alert the user and finish the process in the background (asynchronously) with higher retry bound and a larger set of retryable errors.

**Comment by eriksendc** [comment]
@ErikEJ or @AndriySvyryd ... I reading https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency I think I want to create my own execution strategy, modeled on SqlServerExecutionStrategy. I've written my execution strategy class, but I'm just not able to wrap my head around how to wire it up in startup.cs. This is what I'm doing:

                services.AddDbContext<ApplicationDbContext>(
                    options => options.UseSqlServer(
                        Configuration.GetConnectionString("DefaultConnection"), 
                        options1 => options1.ExecutionStrategy(new EfCoreExecutionStrategy())));

I know what I'm passing into ExecutionStrategy isn't right... Can you point me to an example? I've been googling for hours...

**Comment by ErikEJ** [comment]
How about: https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/test/EFCore.SqlServer.FunctionalTests/Utilities/DbContextOptionsBuilderExtensions.cs#L26

**Comment by eriksendc** [comment]
Thanks much, @ErikEJ I now have my own execution strategy in place. I think the main issue will boil down to whether it is safe to retry for the specific errors I'm seeing. They're always err.Number = -1, `A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)`. So if it is not 100% safe to retry given this error, then I'm trying to figure out my next steps... If the database interaction is occurring as a part of an overall "getter" operation from a web api (which is probably > 90% of our scenarios) then it's always safe to retry. What would be nice is for the caller to be able to declare "this can be retried"... Anyways, I appreciate your pointing me in the right direction earlier today... Thanks!

**Comment by AndriySvyryd** [comment]
@eriksendc Check out https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs

**Comment by AndriySvyryd** [comment]
Closing as the issue appears to be resolved. Feel free to add a comment if you still experience it.

**Comment by KannanMuruganmony** [comment]
Hi,
I'm using EF core 1.0.0 and gets the same error. Is there any other work around to solve this issue without updating to 1.1.0?

**Comment by ajcvickers** [comment]
@KannanMuruganmony The features described above were only added in the 1.1 release.

**Comment by husnusinterxion** [comment]
Hi all, 
We migrated on-prem SQL databases to Azure SQL Databases and after migration, during monitoring the services we see exceptions stating "A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable).". We are getting this error intermittently.  The consumer service itself is in on-prem whilst the database is in Azure.

The stack trace : 
{
  "Depth": 0,
  "ClassName": "System.Data.SqlClient.SqlException",
  "Message": "A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)",
  "Source": ".Net SqlClient Data Provider",
  "StackTraceString": "   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relatedEntitiesFactory, Func`3 joinPredicate)\r\n   at lambda_method(Closure , QueryContext , ApiScope , Object[] )\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)\r\n   at lambda_method(Closure , QueryContext , ApiScope )\r\n   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)\r\n   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)",
  "RemoteStackIndex": 0,
  "ExceptionMethod": {
    "Name": "OnError",
    "AssemblyName": "System.Data",
    "AssemblyVersion": "4.0.0.0",
    "AssemblyCulture": "",
    "ClassName": "System.Data.SqlClient.SqlConnection",
    "Signature": "Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])",
    "MemberType": 8
  },
  "HResult": -2146232060
}

**Exception Details:**
 ExceptionDetail.Message:A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
 ExceptionDetail.Number:-1
 ExceptionDetail.Source:.Net SqlClient Data Provider
 ExceptionDetail.Type:System.Data.SqlClient.SqlException
 SourceContext:Microsoft.EntityFrameworkCore.Query
 ContextType:IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext

**What we applied to solve the issue:**
1-Apply custom execution strategy
2-Apply connection resiliency scenarios
3-upgrade NuGet packages
4-change connection policy from "Default" to "Redirect" and open required ports as Microsoft Azure team suggested

Any help will be very appreciated....

Thanks in advance.

**Comment by OlivierChatagnon1707** [comment]
In our case, the issue Physical connection is not usable appeared only if MultipleActiveResultSets=true.
The issue as been fixed by our customer by removing the "network packet analyzer" (In french: analyseur de trames réseau)

**Comment by she2** [comment]
After removing "MultipleActiveResultSets=true", this issue was resolved for .NetCore 3.1

**Comment by gordcross** [comment]
Been pulling my hair out, looking at the server guys with squinty eyes, just did per she2 and voila. Thanks
