### ISSUE TITLE
dotnet core headaches

### ISSUE THREAD

**Issue by smithaitufe** [dotnet/efcore#7802]
I really don't understand what is happening.

It is very annoying to see series of post that are either outdated or not comprehensive enough.

You are following one post, only to see that something has changed in a new release.

First, most posts out there focus on project.json whereas now we talk about .csproj

I was trying to run dotnet ef migrations command, I could not. I was surprised the system complained that it is not a command.

What is the best way to go?

I am using 
Ubuntu 16.04 LTS
Visual Studio Code
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-rc4-004771
```

Are there forums like Slack where one can get active support like we have languages like elixir and phoenix?

Your help in pointing to the right path is highly valued.

**Comment by ajcvickers** [comment]
@smithaitufe It looks like what you are seeing is the same as the issue reported in #7629, which is an issue with NuGet. The NuGet issue and a workaround are included in #7629. If you feel like what you are hitting is not that issue, then please feel free to re-open this issue including the exact error message/output that you are seeing.

With regard to your general questions, we are looking to get some updated documentation on https://docs.microsoft.com/en-us/ef/ that will help people get started with the tools in different scenarios.
