### ISSUE TITLE
How to pass table valued parameters to stored procedure in entity framework 7

### ISSUE THREAD

**Issue by AVin9** [dotnet/efcore#7820]
Is it possible to pass table valued parameter to a stored procedure in entity framework 7

**Comment by divega** [comment]
@AVin9 The following gist shows an approach you can use to create TVPs that works in .NET Core and how to use it with the `FromSql()` method in EF Core. You should be able to use `ExecuteSqlCommand()` instead of `FromSql()` if your stored procedure does not return query results:

https://gist.github.com/divega/f0f88bf16f35641239cfd9bc534e8d7c

**Comment by slubowsky** [comment]
@divega - Trying to update project using TableValuedParameterBuilder (as written by you above - https://github.com/aspnet/EntityFrameworkCore/issues/7820#issuecomment-285769913 - thanks!) to .NET core 3.0 and getting a compile error:
`The type 'SqlDataRecord' exists in both 'Microsoft.Data.SqlClient, Version=1.0.19128.1, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
I have not explicitly pulled in Microsoft.Data.SqlClient. Looks like maybe thats coming in with EF 3.0 and causing conflicts?

**Comment by ErikEJ** [comment]
Update Microsoft.Data.SqlClient to latest preview, and use that with your code

**Comment by slubowsky** [comment]
@ErikEJ - thanks, I had tried that and still get errors so figured thats not the correct solution. But looking more closely I see that perhaps it is getting a little further as its complaining about a different type used later in the file see error below
`The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

Also based on https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/ I had thought that I shouldnt be using Microsoft.Data.SqlClient just yet, but I do see they plan on a GA release together with 3.0 so maybe EF 3.0 requires it?

**Comment by slubowsky** [comment]
Looks like answer at least for now is to actually add PackageReference for both Microsoft.Data.SqlClient and System.Data.SqlClient. Each one takes away some of the errors, neither takes away all..

**Comment by ErikEJ** [comment]
You should be able to just use M.D.S, just change the namespace  from

    using Microsoft.SqlServer.Server;

    using Microsoft.Data.SqlClient.Server;

As documented in the release notes here: https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.19189.1-Preview.md

**Comment by slubowsky** [comment]
I am unable to get that to work, regardless of which using I use. The only way I can get rid of the SqlDbType error shown above is by adding PackageReference to System.Data.SqlClient

**Comment by divega** [comment]
@slubowsky could you please report this to https://github.com/dotnet/sqlclient? There were some known issues with duplicate types in the first preview of Microsoft.Data.SqlClient, but as @ErikEJ I would expect those to be sorted out by know. If they aren't then it is super important to get this feedback to them. 

Please include a repro and information on whether you are using .NET Core, .NET Framework, etc.

> but I do see they plan on a GA release together with 3.0 so maybe EF 3.0 requires it?

Yes, EF Core 3.0 is going to depend on Microsoft.Data.SqlClient.

**Comment by ErikEJ** [comment]
@slubowsky I am not able to repro, I assume you have a reference to System.Data.SqlClient somewhere that should be removed,

**Comment by slubowsky** [comment]
@ErikEJ I narrowed it down to inclusion of package reference to Microsoft.ApplicationInsights.AspNetCore.
Using code from @divega at https://gist.github.com/divega/f0f88bf16f35641239cfd9bc534e8d7c and the following project file you get 2 errors: 
`The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
that I was only to silence by including additional reference to "System.Data.SqlClient"
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19189.1-Preview" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview7.19362.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview7.19362.6" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.0-beta1" />
  </ItemGroup>
</Project>
```
@divega In light of above is the repo you suggested above still the correct place to create an issue?

**Comment by ErikEJ** [comment]
I am able to repro with this csproj:

    <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19189.1-Preview" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.0-beta1" />
  </ItemGroup>

    </Project>

Microsoft.ApplicationInsights.DependencyCollector 2.11.0-beta1 depends on System.Data.SqlClient 4.3.1

**Comment by ajcvickers** [comment]
@ErikEJ Stack trace?

**Comment by ErikEJ** [comment]
It is a build error - I can share the build log?

```

1>------ Build started: Project: ConsoleApp6, Configuration: Debug Any CPU ------
1>Build started 29-07-2019 21:00:19.
1>Target _CheckForNETCoreSdkIsPreview:
1>  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>Target GenerateTargetFrameworkMonikerAttribute:
1>  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>Target CoreGenerateAssemblyInfo:
1>  Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
1>Target CoreCompile:
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn
1>  TVPBuilder.cs(48,29,48,38): error CS0433: The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>  Program.cs(13,92,13,101): error CS0433: The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>Done building target "CoreCompile" in project "ConsoleApp6.csproj" -- FAILED.
1>
1>Done building project "ConsoleApp6.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>TVPBuilder.cs(48,29,48,38): error CS0433: The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>Program.cs(13,92,13,101): error CS0433: The type 'SqlDbType' exists in both 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>    0 Warning(s)
1>    2 Error(s)
1>
1>Time Elapsed 00:00:00.38
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by ajcvickers** [comment]
Filed an issue at https://github.com/dotnet/SqlClient/issues/144
