### ISSUE TITLE
Query: Optimize QueryOptimizer

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#7831]
`QueryModelOptimizer` derives from `SubQueryFromClauseFlattener` class which in turn derives from `QueryModelVisitorBase`.
- QMVBase class does not visit, QueryModels recursively, hence subQMs inside SelectClause etc are not visited by optimizer. We need ExpressionVisitor to apply QueryModelOptimizer recursively.
- Expand logic of lifting of subquery.
- Verify if we need to derive from `SubQueryFromClauseFlattener`, its code structure has a specific format which we can get rid of.

**Comment by smitpatel** [comment]
Reopening since we can still get rid of `SubQueryFromClauseFlattener`

**Comment by AndriySvyryd** [comment]
@smitpatel Not needed?
