### ISSUE TITLE
Must be reducible node exception when performing expand

### ISSUE THREAD

**Issue by RiseeeAgainst** [dotnet/efcore#7832]
Working with OData with Restier and EFCore

Doing the following expand 
http://localhost:31187/api/Northwind/AppEntityType?$expand=AppMetadataNavigation 

and it throws an exception

"message": "Must be reducible node",
"type": "System.ArgumentException"

"stacktrace": "    
в System.Linq.Expressions.Expression.ReduceAndCheck()
   в System.Linq.Expressions.Expression.ReduceExtensions()
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   в System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   в System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   в System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   в System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   в System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   в System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   в System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   в System.Linq.Expressions.Expression`1.Compile()
   в Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   в Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   в Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   в Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database)
   в Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass21_0`1.<CompileAsyncQuery>b__0()
   в Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   в Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   в Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   в Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   в Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   в Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   в Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__130`1.MoveNext()
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в Microsoft.Restier.Providers.EntityFramework.QueryExecutor.<ExecuteQueryAsync>d__4`1.MoveNext() в D:\tfs\Apps\ESB\tags\Anatoly\RESTier2\src\Microsoft.Restier.Providers.EntityFramework\Query\QueryExecutor.cs:строка 62
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в Microsoft.Restier.Publishers.OData.Query.RestierQueryExecutor.<ExecuteQueryAsync>d__4`1.MoveNext() в D:\tfs\Apps\ESB\tags\Anatoly\RESTier2\src\Microsoft.Restier.Publishers.OData\Query\RestierQueryExecutor.cs:строка 35
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в Microsoft.Restier.Core.Query.DefaultQueryHandler.<QueryAsync>d__3.MoveNext() в D:\tfs\Apps\ESB\tags\Anatoly\RESTier2\src\Microsoft.Restier.Core\Query\DefaultQueryHandler.cs:строка 82
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в Microsoft.Restier.Core.ApiBaseExtensions.<QueryAsync>d__15.MoveNext() в D:\tfs\Apps\ESB\tags\Anatoly\RESTier2\src\Microsoft.Restier.Core\ApiBaseExtensions.cs:строка 433
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

### Steps to reproduce

Model:

```C#
   public class Adapter
    {
        public Guid Oid { get; set; }
        public string AdapterId { get; set; }
        public string Version { get; set; }
        public int? OptimisticLockField { get; set; }
        public string OwnerAppName { get; set; }
        public virtual ICollection<AppMetadata> AppMetadataAdapterNavigation { get; set; }
        public virtual ICollection<AppMetadata> AppMetadataAdapter1Navigation { get; set; }
    }

   public class AppEntityType
    {
        public Guid Oid { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? Gcrecord { get; set; }
        public Guid? AppMetadata { get; set; }
        public Guid? BaseType { get; set; }
        public string Name { get; set; }
        public virtual AppMetadata AppMetadataNavigation { get; set; }
        public virtual AppEntityType BaseTypeNavigation { get; set; }
        public virtual ICollection<AppEntityType> InverseBaseTypeNavigation { get; set; }
    }
    public class AppMetadata
    {
        public Guid Oid { get; set; }
        public Guid? Adapter1 { get; set; }
        public string Metadata { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? Gcrecord { get; set; }
        public Guid? Adapter { get; set; }
        public virtual ICollection<AppEntityType> AppEntityType { get; set; }
        public virtual Adapter AdapterNavigation { get; set; }
        public virtual Adapter Adapter1Navigation { get; set; }
    }
```

###
There is a class in Remotion.Linq, that used as expression - QuerySourceReferenceExpression

And this class doesn't overrrides CanReduce property (it's false by default)

I think, that there is two options:
1. Mine expression node shouldn't have nodeType extension
2. This class should to override that property.

In addition I want to say, that when I'm doing another expand, like: Adapter?$expand=AppMetadataAdapterNavigation  it works fine and there is no nodes with nodeType extension.

the method that throws an exception:

```C#
public Expression ReduceAndCheck()
    {
      if (!this.CanReduce)
        throw Error.MustBeReducible();
      Expression expression = this.Reduce();
      if (expression == null || expression == this)
        throw Error.MustReduceToDifferent();
      if (!TypeUtils.AreReferenceAssignable(this.Type, expression.Type))
        throw Error.ReducedNotCompatible();
      return expression;
    }
```

### Further technical details
EF Core version: 1.1.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
IDE: Visual Studio 2015

**Comment by maumar** [comment]
closing this, since #7935 contains better repro and more information
