### ISSUE TITLE
scaffoling existing database: default namespace is not generated

### ISSUE THREAD

**Issue by j-nord** [dotnet/efcore#7834]
The namespace name in the project or in the project.json is not accepted. As default namespace is generated from the directory and not from the given namespace. In addition, the uppercase letter of the directory becomes a lowercase letter.

Example:

Default Namespace: Portale
Directory: Portal

Generate Namespace: "**portal**.Server.Models"

How can we fix this?
### Steps to reproduce
dotnet ef dbcontext scaffold "Server=127.0.0.1;Database=Demo;Integrated Security=true" Microsoft.EntityFrameworkCore.SqlServer  -o "Server/Models" -c "DatenContext" -f

...`  "
dependencies": {
    "DevExpress.XtraReports": "16.1.6",
    "IdentityServer4.AspNetIdentity": "1.0.0",
    "Microsoft.ApplicationInsights.AspNetCore": "2.0.0",
    "Microsoft.AspNet.Identity.Core": "2.2.1",
    "Microsoft.AspNetCore.AngularServices": "1.0.0-beta-000019",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Newtonsoft.Json": "9.0.1"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.DotNet.Watcher.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"
  },

  "tooling": {
    "defaultNamespace": "Portale"
  },

  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.Web": "4.0.0.0"
      },
      "dependencies": {
        "PortableBibliothek": {
          "target": "project"
        },
        "ReportsLibrary": {
          "target": "project"
        }
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },`
...

**Comment by ErikEJ** [comment]
You could try the SQLite / SQLCE Toolbox extension, maybe? https://twitter.com/ErikEJ/status/834452863380250624

**Comment by j-nord** [comment]
@ErikEJ 

No, there are nor subdirectory(model) as parameter.

**Comment by ErikEJ** [comment]
It has been added in the release version! 😄  - give it a try!

![efpoco](https://cloud.githubusercontent.com/assets/4169187/23797240/341a7c52-059f-11e7-9624-d2d6d1b98d37.png)

**Comment by ajcvickers** [comment]
@j-nord This should be fixed with the latest tooling when not using project.json.  Note that the  [.NET Core SDK 1.0.0](https://www.microsoft.com/net/download/core) no longer supports project.json or Visual Studio 2015. Everyone doing .NET Core development is encouraged to [migrate from project.json to csproj](https://docs.microsoft.com/dotnet/articles/core/migration/) and [Visual Studio 2017](https://www.visualstudio.com/downloads/).

If you are still able to repro this after migrating away from project.json and using the latest tooling, then please feel free to re-open this issue.
