### ISSUE TITLE
ResultOperatorHandler.HandleDistinct Failing for IAsyncEnumerable<IAsyncGrouping<...>>

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#784]
In enabling the NorthwindAsyncQueryTests for Redis the test GroupBy_Distinct() had to be commented out. This was because ResultOperatorHandler.HandleDistinct() was constructing an expression which expected a parameter of type IAsyncEnumerable< IGrouping<...>> but the GroupBy was leaving the EntityQueryModelVisitor.StreamedSequenceInfo.ResultItemType as IAsyncEnumerable< IAsyncGrouping<...>>.

Assigning to @anpete as agreed.

**Comment by rowanmiller** [comment]
Closing as Redis is not currently in working code base
