### ISSUE TITLE
Tooling/help for enabling Migrations on an existing database

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#7846]
When discussing #7840 we came to the conclusion that it would be fine to not show Migrations stuff at the beginning of the simple getting started guides if the story to move from EnsureCreated to Migrations was really good. This is essentially the story for enabling Migrations on any existing database, although it could be that EnsureCreated puts some metadata into the database to make the experience better.

**Comment by ajcvickers** [comment]
@bricelam I couldn't find any issue tracking this, but if I missed it and you can find it, then feel free to close this as a dupe.

**Comment by bricelam** [comment]
Wow, that *was* hard to find! 😄 #2167
