### ISSUE TITLE
Migration Target Project Bug

### ISSUE THREAD

**Issue by PMExtra** [dotnet/efcore#7849]
I have a model class library that contains the DbContext.
Then I want to storage migrations in a executable project (probably named `Maintenance`).
But when I run the `Add-Migration` or `dotnet ef migrations add`, I have some trouble.

When I only typed `Add-Migration Initial` or `dotnet ef migrations add Initial`, I got error: 
```
No DbContext was found in assembly 'Maintenance'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.
```

The error was kept even I add `services.AddDbContext<MyDbContext>` in Maintenance.

Then, I tried `Add-Migration Initial -Project MyModel`
It's success to get migrations data in MyModel project.

So, I override the `OnConfiguration` in `MyDbContext`:
```
options.UseNpgsql(connection, b => b.MigrationsAssembly("Maintenance");
```

Then, the miracle happend... I got a very interested error:
```
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("MyModel")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
Your target project 'MyModel' doesn't match your migrations assembly 'Maintenance'. Either change your target project or change your migrations assembly.
```

# Focus on this!!!

**Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.**

My `Package Manager Console's Default project` is still `Maintenance`, but that is not target project.

I also have tried executing "dotnet ef" in Maintenance project folder, but got same error.

Is this a bug of eftools? I have experiences of old version 1.0.0-preview2-final that works awesome.

### Further technical details
EF Core version: 1.1.1
Database Provider: Npgsql
Operating system: Windows 10 (1607)
IDE: Visual Studio 2017 RTM / CLI

EFTools version: 1.0.0-rtm-10308 (by dotnet ef --version)

**Comment by bricelam** [comment]
The simplest way to get what you want is:
1. Scaffold the first migration into 'MyModel'
2. Move the generated migration and model snapshot classes into 'Maintenance'

After this, you should be able to add new migrations directly into 'Maintenance'

Also note, the `-Project` parameter overrides PMC's Default project drop-down

**Comment by bricelam** [comment]
Closing, but please re-open if you still think there's an issue here.

**Comment by PMExtra** [comment]
![image](https://cloud.githubusercontent.com/assets/11289158/24022132/88c45b48-0adf-11e7-8cca-d3c35a69d283.png)

Thanks, I have done it! I make a complete `Startup` to `ConfigureServices`, so that works fine. I hope you can provide a richer document about this.
