### ISSUE TITLE
Stored procedure CRUD mapping

### ISSUE THREAD

**Issue by ekaggata** [dotnet/efcore#7854]
As an alternative to the default table query generation facilities there is to be an option to map the CRUD operations to stored procedures.

**Comment by strangeattr** [comment]
Surprisingly I couldn't found this feature request submitted already. I am sorry if it has actually already been.

**Comment by strangeattr** [comment]
PS: It would sound to broad so I have preferred the more specific task, ideally, however, EF Core should support purely logical application-level entities that are not represented directly by any specific table in the DB but are mapped (in their create/read/update/delete/find actions) to an additional layer of logic implemented on the DB side, on the model code side or both.

**Comment by ErikEJ** [comment]
Duplicate of https://github.com/aspnet/EntityFramework/issues/245
