### ISSUE TITLE
Add Chinese characters support

### ISSUE THREAD

**Issue by shanhongyue** [dotnet/efcore#7862]
I put my asp .net core project under a **Chinese** name folder.

I want to generate migration code, so I type

`Add-Migration xxx`

in Package Manager Console in Visual Studio 2017.

If everything goes well, migration code will be generated. But when it read **project.assets.json** file, it seems not to read this file with utf8 encoding, instead, with ANSI encoding. So Chinese characters in the file cannot be read correctly. So the process is terminated by this exception.

**project.assets.json has not UTF8 BOM!!!**

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Professional Simplified Chinese
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@shanhongyue Could you provide a project to reproduce this? It could be a NuGet bug, or something specific to the project files that you have, but it's hard to know without being able to reproduce it.

**Comment by shanhongyue** [comment]
It has nothing to do with the project configuration, just because there is Chinese characters in the path of the folder where the project is located in, Or in the name of the project itself.

**Comment by bricelam** [comment]
I'm not able to reproduce this issue locally. `Add-Migration` is works without error after creating new ASP.NET Core Web Application with the name 测试测试测试.

@shanhongyue Could you provide your project? If not, does adding `-Verbose` give any additional information?

**Comment by shanhongyue** [comment]
I found the reason. The path may be too long. I placed my solution folder under "E:\保持同步\存档PX1T\我的软件\基于地理位置和关键字的优惠信息推荐\CouponServer". After I moved it to "E:\保持同步\存档PX1T", it succeed in adding migration and updating database.
