### ISSUE TITLE
Request: Allow default context to be set for tooling

### ISSUE THREAD

**Issue by ctolkien** [dotnet/efcore#7866]
In almost all of our projects we tend to several `DbContexts` - As an example, we might have the primary `MyApplicationDbContext`, but also a `ReadOnlyMyApplicationDbContext` which inherits from `ApplicationDbContext`, replaces the DbSets with `AsNoTracking()` variants and throws if you try and call `SaveChanges` etc.

Whenever we need to interact with the tooling, we need to explicitly specify to use `ApplicationDbContext` with every single command which becomes cumbersome.

It would be handy to be able to specify a default context to use (via environment variable? appsetting? csproj config?) and to default to using that context for all tooling operations unless explicitly overridden.

**Comment by bricelam** [comment]
In prerelease versions of the tools, we had `Use-DbContext` in PMC, but we removed it since tab expansion of the `-Context` parameters coupled with command history seemed to be sufficient for most users.

We've also considered honoring a `DBCONTEXT` environment variable in `dotnet ef`. (see #927)

**Comment by ctolkien** [comment]
Ah, I feel this is pretty much a dupe of #927. Will close this off and put my +1 behind that.
