### ISSUE TITLE
Unidirectional Many-to-Many Relationship

### ISSUE THREAD

**Issue by mtdaniels** [dotnet/efcore#7876]
Is it possible to have a unidirectional, many-to-many relationship?  For instance:

```
class Category {
   public int Id{get;set;}
   public string Name{get;set;}
}

class Product {
   public int Id{get;set;}
   public string Name{get;set;}
   public List<ProductCategory> Categories{get;set;}
}

class ProductCategory{
   public int CategoryId{get;set;}
   public Category Category{get;set;}
   
   public int ProductId{get;set;}
   public Product Product{get;set;}
}
```
The real motivation behind this is that I have multiple classes which consume Category.  I would prefer not to have to add all of the join tables to category as it does not add any value to the project.

Note, this is not one-to-many because multiple products can use the same category.

**Comment by smitpatel** [comment]
Writing following code in your `OnModelCreating` method should give you desired results.
```C#
modelBuilder.Entity<ProductCategory>(b =>
{
    b.HasKey(e => new {e.CategoryId, e.ProductId});

    b.HasOne(e => e.Product).WithMany(e => e.Categories).HasForeignKey(e => e.ProductId);

    b.HasOne(e => e.Category).WithMany().HasForeignKey(e => e.CategoryId);
});
```
The only difference this has with general many-to-many relationships is there is no reverse navigation specified from `Category` to `ProductCategory` but usage of `WithMany` marks the relationship to be one to many. Hence overall many to many relationship.

**Comment by mtdaniels** [comment]
Thanks @smitpatel .  I had tried that previously, but was unsuccessful (Product.Categories was always null).  As it turns out, this was caused by lack of lazy loading support (https://github.com/aspnet/EntityFramework/issues/3797) + lack of eager loading (http://stackoverflow.com/questions/38019808/entity-framework-core-ef-7-many-to-many-results-always-null)
