### ISSUE TITLE
Query: We force materialization of query sources for queries with GroupJoin that is not flattened by SelectMany

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#7884]
Currently for queries that contain GroupJoin clause, which is not afterwards flattened by a SelectMany, we force materialization on both outer and inner query sources. This is because for the client _GroupJoin method we don't always know how to properly divide inners into groups - specifically, when the outer (key) is not present in the final projection. 

This is to track remaning work after fixing https://github.com/aspnet/EntityFramework/issues/6647, where we stopped materializing query sources for queries with GroupJoins wrapped in SelectMany - which are the most popular use cases, e.g. optional navigations.

**Comment by smitpatel** [comment]
Irrelevant
