### ISSUE TITLE
ValueGeneratedOnAdd() only works with DEFAULT constraint

### ISSUE THREAD

**Issue by im1dermike** [dotnet/efcore#7886]
I have the following entity configuration for a `Patient` entity:

    builder.Property(x => x.RegistrationDateUtc)
        .IsRequired()
        .ValueGeneratedOnAdd()
        .HasDefaultValueSql("GETUTCDATE()");

I've found that an exception is thrown if I do not have a default value constraint defined on that column as follows:

    CONSTRAINT DF_Patients_RegistrationDateUtc DEFAULT GetUtcDate()

The exception of type `Microsoft.EntityFrameworkCore.DbUpdateException` with the following message:

> Cannot insert the value NULL into column 'RegistrationDateUtc', table 'Norm.dbo.Patients'; column does not allow nulls. INSERT fails.

The necessity for a default value constraint makes the `HasDefaultValueSql("GETUTCDATE()")` configuration meaningless.

**Comment by ajcvickers** [comment]
@im1dermike What is your expectation of what should happen in this case?

**Comment by im1dermike** [comment]
@ajcvickers I'm expecting there not to be a need to define a default value constraint in the database.  This is what I expect `HasDefaultValueSql("GETUTCDATE()")` to accomplish.  Having to define it in two places is redundant.

**Comment by ajcvickers** [comment]
@im1dermike HasDefaultValueSql is for telling EF to use the default value from the database. If EF is being used to create the database, then it will use the string given to setup the constraint. If the database is created some other way, then it tells EF that such a constraint exists such that EF can generate insert statements that make use of it.

Are you looking for a way to have the client generate default values? If so, look at HasValueGenerator().
