### ISSUE TITLE
Expose RequiresValueGenerator as an external extension method for Microsoft.EntityFrameworkCore.Metadata.IProperty.

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/efcore#7890]
Scaffolding uses the `RequiresValueGenerator` property from EFCore 1.0.x and 1.1.x versions to determine autogeneration status. 

The property has been moved to be an Extension method in 1.2.0-preview but in an internal namespace. 

Can this extension method be made available as a public extension method instead? 

cc @bricelam @mlorbetske

**Comment by ajcvickers** [comment]
We discussed this in triage and we're going to look into whether RequiresValueGenerator is the correct thing to use here, or even a useful extension method to have internally at this point. It's semantics are not very tightly defined.

**Comment by ajcvickers** [comment]
Scaffolding was updated to use public API
