### ISSUE TITLE
UseSqlServer() method is missing from Microsoft.EntityFrameworkCore.SqlServer 1.1.1

### ISSUE THREAD

**Issue by ChuckkNorris** [dotnet/efcore#7891]
While following the [Identity4 tutorial](http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html#refentityframeworkquickstart), it seems the `DbContextOptionsBuilder.UseSqlServer()` method is missing. Was this moved to a new package?

![error](http://image.prntscr.com/image/821f6ed25f3348a389c65de0d839b2fc.png)

```
Exception message: 
'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer' and no extension method 'UseSqlServer' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)
```

### Steps to reproduce

```c#
services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddTestUsers(Config.GetUsers())
                .AddConfigurationStore(builder =>
                    builder.UseSqlServer(connectionString, options => 
                        options.MigrationsAssembly(migrationsAssembly)))
                .AddOperationalStore(builder =>
                    builder.UseSqlServer(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)));
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
Possible external dupe: dotnet/roslyn-project-system#1741

**Comment by ajcvickers** [comment]
@ChuckkNorris Does the build fail for you in addition to VS showing the error in the editor window?

**Comment by zeeshaniqbal** [comment]
remove the follow refs from the csproj file,
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGenerators.Mvc" Version="1.1.0-preview4-final" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="1.1.0-preview4-final" />
<PackageReferenceInclude="Microsoft.VisualStudio.Web.CodeGeneration"Version="1.1.0-preview4-final" />

Add the following refs,
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0-msbuild3-final" />
<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />

Source: https://developercommunity.visualstudio.com/content/problem/10914/scaffolding-net-core-with-entity-framework.html

**Comment by ajcvickers** [comment]
@zeeshaniqbal We are not entirely sure how this relates to those packages, and they look like older versions as well.

**Comment by rwobben** [comment]
I have this problem also but I do not have the codegeneration in my .csproj file

**Comment by ChuckkNorris** [comment]
@rwobben I don't believe the `**.CodeGeneration` packages are related to this issue. The issue seems to have resolved itself. Try updating VS2017 (Tools -> Extensions and Updates -> Updates), updating the `Microsoft.EntityFrameworkCore.SqlServer` package, and restarting Visual Studio.

![Update VS2017](http://image.prntscr.com/image/9a1d3503065a47768bdf63392aacb720.png)

**Comment by rwobben** [comment]
Here no updates avaible

**Comment by ChuckkNorris** [comment]
@rwobben Does your solution build even with the syntax errors?

**Comment by rwobben** [comment]
nope, I will not build. 
When building I see the above error 
When needed I can put my whole project on github. It's one view and he first steps to make EF work

**Comment by ChuckkNorris** [comment]
Hm - try manually adding the using statement `using Microsoft.EntityFrameworkCore;` and building again. It could be a Rosalyn-related issue.

**Comment by olegmusin** [comment]
Solution builds even with this issue

**Comment by rwobben** [comment]
Thanks, adding the using did solve it

**Comment by olegmusin** [comment]
Anyway it is abnormal

**Comment by nukec** [comment]
Adding using solved for me as well. Ah ah.

**Comment by td4ddk** [comment]
Adding the using statment solved my problem!

**Comment by KatteKwaad** [comment]
Getting this issue again with Microsoft.EntityFramework.Core.SqlServer 2.0.0 preview1-final.
Adding of that using didn't help

**Comment by orassr** [comment]
yep just added it manually

**Comment by Braed** [comment]
Okay so adding this manually isn't working for me. It says that the using directive is unnecessary.  
Is this going to be fixed soon?

**Comment by haugan** [comment]
Manually installing the NuGet-package "Microsoft.EntityFrameworkCore.SqlServer" fixed it for me as well -
 cheers, @Braed!

**Comment by 10ARK-LeightonSutton** [comment]
Adding the using statement solved my problem too - thanks.

**Comment by victorusoro** [comment]
yes, adding `using` `Microsoft.EntityFrameworkCore;` solved the problem 

Thanks guys..

**Comment by flq** [comment]
Here I am, vs code, did "dotnet new web", have the following packages added via dotnet add package:

```
<PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
<PackageReference Include="Microsoft.AspnetCore.Mvc" Version="1.1.3" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
```

Have in Startup.cs `using Microsoft.EntityFrameworkCore;`

But this line Fails:

```
public void ConfigureServices(IServiceCollection services)
{
  services.AddMvc();
  services.AddDbContext<ConferenceContext>(b => b.UseSqlServer(""));
}
```

>Startup.cs(20,61): error CS1061: 'DbContextOptionsBuilder' does not contain a definition >for 'UseSqlServer' and no extension method 'UseSqlServer' accepting a first argument of >type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?) [C:\dev\team-system-personal\MVC486\MVC486.csproj]

That is easily the weirdest issue I've seen in a while. So, game over, or what?

**Comment by smitpatel** [comment]
Incorrect package
> <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />

You need reference to `Microsoft.EntityFrameworkCore.SqlServer`
EFCore is just core package. You need to reference provider specific package.

**Comment by flq** [comment]
Just realized this myself. Now it's here to read as well for the next hapless fool :)

`dotnet add package Microsoft.EntityFrameworkCore.SqlServer` and off you go

**Comment by ruinunes-parkbee** [comment]
It looks like `UseSqlServer` is now under `ConfigureDbContext` in `AddConfigurationStore`.

Code snippet:
` services.AddIdentityServer()
                    .AddConfigurationStore(opt => opt.ConfigureDbContext = builder => builder.UseSqlServer(AuthorizationConnectionString, options => options.MigrationsAssembly(migrationsAssembly)))
                    .AddOperationalStore(opt => opt.ConfigureDbContext = builder => builder.UseSqlServer(AuthorizationConnectionString, options => options.MigrationsAssembly(migrationsAssembly))); `

**Comment by ajcvickers** [comment]
@ruinunes-parkbee Nothing has changed here from the EF side. Looks like this is IdentityServer code.

**Comment by tiagobarroso** [comment]
I had it when i started with a mvc auth project. 
I noticed that it put SQL LITE references into the project and maybe it caused this issue, as a conflict against SQL SERVER.

To fix it i removed all SQL LITE library references, and after that i installed SQL SERVER reference:

**dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 2.0.0**

It works for me, i wish that it can be helpful!

**Comment by EIDIVANDI** [comment]
just at the moment had the same problem , after verifing the Msdn link [UseSqlServer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverdbcontextoptionsextensions.usesqlserver?view=efcore-2.1 ) found that the Microsoft.EntityFrameworkCore has not added the Microsoft.EntityFrameworkCore.SqlServer

**Comment by viveksingh30** [comment]
in .proj file change Microsoft.AspNetCore.App to Microsoft.AspNetCore.All
  
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" />
  </ItemGroup>

**Comment by fragrancewithin** [comment]
I had same issue, to resolve this i had to Install Microsoft.EntityFrameworkCore.SqlServer package separately then use using Microsoft.EntityFrameworkCore.SqlServer;

**Comment by manishmawat** [comment]
Installing Microsoft.EntityFrameworkCore.SqlServer solved the problem for me.
It is strange that the installed package is showing unused in the file, but it is not showing any error now and build is successful.

**Comment by shadinamrouti** [comment]
Installing the following packages resolves the problem. Use the compatibility version. No need for `using` statements:

```
Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.SqlServer

```

**Comment by prageethmadhu** [comment]
installing this in package manager save me Microsoft.EntityFrameworkCore.SqlServer

**Comment by dannycsng** [comment]
I am using .Net Core 3.0 and install this package Microsoft.EntityFrameworkCore.SqlServer still giving me the same error.

**Comment by akhilnalliboina** [comment]
Try using Microsoft.EntityFrameworkCore;

**Comment by oumaymaSghayer** [comment]
install the  Microsoft.EntityFrameworkCore.SqlServer nugget package manually and Try using Microsoft.EntityFrameworkCore;
->worked

**Comment by azhar-td** [comment]
make sure you have this nuget package installed 
Microsoft.EntityFrameworkCore.SqlServer
confirm version in project before installing

**Comment by psharma2014** [comment]
Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 3.1.3

**Comment by joaocarias** [comment]
Install for nugget:

Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 3.1.5

Fonte: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/

**Comment by ravigit2020** [comment]
Following steps were added to resolve this problem
1. Added NuGet-package "Microsoft.EntityFrameworkCore.SqlServer" 
2. using Microsoft.EntityFrameworkCore;

**Comment by jaybharatjay** [comment]
Very useful video till 17 Minute I am now: https://www.youtube.com/watch?v=fom80TujpYQ
I was facing a problem here:
 services.AddDbContext<PaymentDetailContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DevConnection")));
UseSqlServer not recognizes so I did this 
Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 3.1.5

&
using Microsoft.EntityFrameworkCore;

Then my problem is solved. About me: basically I am a purely PHP programmer since beginning and  only today I started .net .

> Install for nugget:
> 
> Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 3.1.5
> 
> Fonte: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/

Dear sir,
your solution works great.

When I saw this video till 17 Minute:  https://www.youtube.com/watch?v=fom80TujpYQ
I was facing a problem here:
```
 services.AddDbContext<PaymentDetailContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DevConnection")));
```
**UseSqlServer not recognizes so I did this** 
Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 3.1.5

&
using Microsoft.EntityFrameworkCore;

Then my problem is solved. About me: basically I am a purely PHP programmer since beginning and  today only I started .net coding, thanks for good community in .net

**Comment by domicoder** [comment]
> Hm - try manually adding the using statement `using Microsoft.EntityFrameworkCore;` and building again. It could be a Roslyn-related issue.
> 
> If you can post it on GitHub, I don't mind checking it out

it is working for me

**Comment by rushdan** [comment]
> 

I try the latest version (Microsoft.EntityFrameworkCore -Version 6.0.8) on August 2022 not compatible with .net core 3.1 ,  Which version compatible with .net core 3.1 ? Thanks

**Comment by KishoreShyamal** [comment]
Following 2 packages are need.
Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.SqlServer
