### ISSUE TITLE
SqlAzureExecutionStrategy in 1.1?

### ISSUE THREAD

**Issue by mb2140** [dotnet/efcore#7896]
I'm trying to figure out the correct way to implement SqlAzureExecutionStrategy.  According to this pull request it looks like it was merged in 1.1: https://github.com/aspnet/EntityFramework/commit/48cb312acf70ae7492307b062a00186baa573cbc

However I'm not seeing this as an option when updating my connection string.  Currently running my own custom execution strategy:

```
 services.AddDbContext<WebsiteContext>(options =>
                    options.UseSqlServer(Configuration.GetConnectionString("websiteEntities"),
                    builder => builder.ExecutionStrategy(x => new SqlServerRetryingExecutionStrategy(x.Context, 3, TimeSpan.FromSeconds(30), null))));
```

But I'm receiving errors on occasion that say:

`The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit. `

What is the proper way to protect myself from transient errors now?

### Further technical details
EF Core version: 1.1
Database Provider: AzureSQL
Operating system: Windows 8.1
IDE: Visual Studio 2015

**Comment by ErikEJ** [comment]
Did you see the docs here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency
