### ISSUE TITLE
Left Join SelectMany "type arguments cannot be inferred from" error relating to manual workaround for Scaffold-DbContext not creating entities for tables without primary keys

### ISSUE THREAD

**Issue by victor168** [dotnet/efcore#7898]
Hello,

I followed the instructions here (https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db) to have Scaffold-DbContext auto generate entity classes for my database.  However it did not work for tables without primary keys such as the PrimarySecondary table in the following diagram -- essentially a relationship table that defines a many-to-many relationship between 2 other tables:

![many_to_many](https://cloud.githubusercontent.com/assets/26444339/23969630/7b8705fe-099d-11e7-871a-bc0434f3b24e.png)

So I manually created the Entity class:

```
public class PrimarySecondary
{
	public int PrimaryId { get; set; }
	public int? SecondaryId { get; set; }
}
```

And added the following into the DBContext class:

```
public virtual DbSet<PrimarySecondary> PrimarySecondary { get; set; }

// in the OnModelCreating() method
modelBuilder.Entity<PrimarySecondary>(entity =>
{
	entity.ToTable("PrimarySecondary");

	entity.HasKey(e => new { e.PrimaryId, e.SecondaryId });

	entity.Property(e => e.PrimaryId).HasColumnName("PrimaryId");
	entity.Property(e => e.SecondaryId).HasColumnName("SecondaryId");

});
```
And in my class using the DBContext I have the following GroupJoin ("left join") query:

```
var joinedResult = _context.Primary

	.GroupJoin(_context.PrimarySecondary, p => p.PrimaryId, ps => ps.PrimaryId, (p, ps) => new { p, ps })

	.SelectMany(
		temp => temp.ps.DefaultIfEmpty,
		(temp, pps) => new 
		{
			PrimaryId = temp.p.PrimaryId,
			Title = temp.p.Title,
			SecondaryId = (null != pps) ? pps.ps.SecondaryId
		}
	);
``` 

But the above code is getting the warning:  "**The type arguments for method SelectMany cannot be inferred from the usage**"

The baffling part is I use the exact same GroupJoin and SelectMany code as above on other tables who's Entity classes were auto generated without any problems, which is why I'm suspecting this error is related to this fact.  In other words, I can execute left join queries on other tables that I didn't have to create manually with the exact same syntax and it works fine.

FYI, semantically I'm trying to retrieve ALL the rows in the Primary table and any rows that exist in PrimarySecondary having a matching PrimaryId, like in the following example data result set:
```
PrimaryId              Title               SecondaryId
=========              =====               ===========
1001                   Dog                 (null)
1002                   Cat                 225
1002                   Cat                 341
1003                   Rabbit              (null)
1004                   Fox                 225
1004                   Fox                 501
1005                   Wolf                122
```

I feel I'm close, but am missing something probably obvious.  Any ideas what I might be missing or doing incorrectly?

Thanks in advance for any help!

### Further technical details
from my project.cs:
"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.1",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  }
IDE: Visual Studio 2015/2017

**Comment by maumar** [comment]
@victor168 

```cs
SecondaryId = (null != pps) ? pps.ps.SecondaryId
```

what is the ifFalse condition here? its missing in the code sample.

Can you try casting SecondaryId in the final projection to int?, like so:

```cs
var joinedResult = _context.Primary

	.GroupJoin(_context.PrimarySecondary, p => p.PrimaryId, ps => ps.PrimaryId, (p, ps) => new { p, ps })

	.SelectMany(
		temp => temp.ps.DefaultIfEmpty,
		(temp, pps) => new 
		{
			PrimaryId = temp.p.PrimaryId,
			Title = temp.p.Title,
			SecondaryId = (int?)((null != pps) ? pps.ps.SecondaryId : whatever)
		}
	);
```

If this doesn't work I will take a closer look. Also, can you post stack trace for the exception?

**Comment by victor168** [comment]
Hi @maumar !

The if null condition:

```
SecondaryId = (null != pps) ? pps.ps.SecondaryId
```

is to prevent run-time exceptions when the left join query does not match anything on the PrimarySecondary table.  Is this the best way to handle this?

I don't think the casting is a factor, because I still see the error even if I leave out the SecondaryId line entirely, like this:
```
var joinedResult = _context.Primary

	.GroupJoin(_context.PrimarySecondary, p => p.PrimaryId, ps => ps.PrimaryId, (p, ps) => new { p, ps })

	.SelectMany(
		temp => temp.ps.DefaultIfEmpty,
		(temp, pps) => new 
		{
			PrimaryId = temp.p.PrimaryId,
			Title = temp.p.Title
		}
	);
```

Unfortunately, I don't have any run-time stack traces because this error is preventing the code from compiling (I see it in Visual Studio 2015 IDE when mousing-over "SelectMany" which has a red wavy line underneath)

When I try to compile anyway, I see the following error in the Error List tab:

```
Error	CS0411	The type arguments for method 'Queryable.SelectMany<TSource, TCollection, TResult>(IQueryable<TSource>, Expression<Func<TSource, IEnumerable<TCollection>>>, Expression<Func<TSource, TCollection, TResult>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	JSWeb..NETCoreApp,Version=v1.0
```

**Comment by maumar** [comment]
Thanks for the follow up, will try to reproduce this.

**Comment by victor168** [comment]
@maumar Thanks so much!

**Comment by smitpatel** [comment]
The error is in the same line but differently. As @maumar said it is missing ifFalse part.
`SecondaryId = (null != pps) ? pps.ps.SecondaryId`
Moreover `pps.ps` does not exist. The result of `GroupJoin` has anonymous type containing p & ps properties but when you apply `SelectMany` on the top of that, in the result selector of SelectMany `(temp, pps)` temp is same as anonymous type coming out of GroupJoin. But `pps` is flattened out collection of `temp.ps` hence it is of type `PrimarySecondary` and not the anonymous type.

The following query compiles for me, correctly
```C#
var joinedResult = db.Primary
    .GroupJoin(db.PrimarySecondary,
        p => p.PrimaryId,
        ps => ps.PrimaryId,
        (p, ps) => new { p, ps })
    .SelectMany(temp => temp.ps.DefaultIfEmpty(),
        (temp, pps) => new
        {
            PrimaryId = temp.p.PrimaryId,
            Title = temp.p.Title,
            SecondaryId = (pps != null) ? pps.SecondaryId : null
        });
```
Generated SQL:
````SQL
SELECT [p].[PrimaryId], [p].[Title], [ps].[SecondaryId], [ps].[PrimaryId]
FROM [Primary] AS [p]
LEFT JOIN [PrimarySecondary] AS [ps] ON [p].[PrimaryId] = [ps].[PrimaryId]
````
