### ISSUE TITLE
String is truncated at 43679 characters on Select although the column is nvarchar(max)

### ISSUE THREAD

**Issue by vishwajeets7** [dotnet/efcore#7900]
This issue was closed earlier #7209. Would like to reopen as i am still facing the same issue with SQL2012.
The string gets cut off after 43679 characters, when the data type is NVARCHAR(MAX).

**Comment by divega** [comment]
@vishwajeets7 Last time we were unable to repro. Does it happen for you with any `nvarchar(max)` column on SQL Server 2012? Would you be able to produce a repro project?

**Comment by vishwajeets7** [comment]
Thanks for your response.

I can explain you the environment, unfortunately can't copy paste the code.

Working with SQL 2012, I have a table with column as NVARCHAR(MAX), as understood with the definition thought this will handle the long string. I am using EF6, to update the long string data. However found that the string is stored only upto 43679 characters, and the rest is ignored.

**Comment by vishwajeets7** [comment]
Adding....
I have validated almost 10-15 records where the string is getting curtailed.

**Comment by ajcvickers** [comment]
@vishwajeets7 This repository is for EF Core only. If you are seeing this with EF6, then can you please open an issue on https://github.com/aspnet/EntityFramework6. We have attempted to reproduce this in the past with EF Core and have not been able to do so. That is likely to be the case again unless you can give us a full repro (i.e. a simplified version of your scenario with anything that you can't share removed) or at least some more specific details about the model/database/machine configuration or anything else that will help us to be able to reproduce this.

**Comment by ChristiaanSaaiman** [comment]
@vishwajeets7 Have a look at [this](https://social.msdn.microsoft.com/Forums/en-US/4359e2ce-7d42-4535-8f85-3c58b6837e6d/ef-creates-nvarcharmax-for-strings-should-max-be-modified-for-sql-azure?forum=adodotnetentityframework). It may be related to the problem you (and I) are experiencing

**Comment by JoybasakQumaOne** [comment]
I'm using SQL server Management Studio 2014 and facing the same issue. After I dig though the issue I find that the Data is getting saved with actual string value, but the SELECT statement returns only 43679 characters whereas the actual string contains more than 50k character.
Once I generate a script with data of the table I can see the Actual 50k+ character, so I think there must be some setting in SQL server which I'm not aware of. Any help would be highly appreciated.
Thanks
