### ISSUE TITLE
same as #7563?

### ISSUE THREAD

**Issue by gforceg** [dotnet/efcore#7902]
(I think this is the same as closed issue #7563)

I am following [this tutorial](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db) except I'm trying to substitute 'dotnet ef dbcontext scaffold' in place of 'Scaffold-DbContext'

I'm getting no errors, no warnings, and 'Build succeeded.' on the command line when I run:

```
dotnet ef dbcontext scaffold "Server=<NOT MY REAL SERVER>;Database=<NOT MY REAL DB>;Trusted_Connection=True;" Microsoft.EntityFrame
workCore.SqlServer -o Models --json -f
```

A single file is created in 'Models/' called 'myDBNameContext.css' roughly the following contents:

```c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ConsoleApp.SQL.Models
{
    public partial class tscappointmentsContext : DbContext
    {
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.
        // Unable to generate entity type for table '<NOT.MY.REAL.TABLE>'. Please see the warning messages.

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            #warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer(@"Server=<NOT MY REAL SERVER>;Database=<NOT MY REAL DB>;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }
}
```

Per the response to #7563, I would like to provide you with the schema creation script but I don't know what that is or where to locate it. Is the script generated by EF Core? Does it have a naming convention like "MyProjectName.schemaScript.cs"?

I also tried creating appsettings.json and sticking the connection string in it (per the fwlink) but I don't know how to tell the CLI to use that file. When I omit the connection string on the command line I am told that I'm not including a provider (it is accepting the provider as the connection string because it is the first argument).

Maybe the CLI should output the connection string to separate file so that it can still be used w/o generating code that contains an anti-pattern.

Thanks.

**Comment by gforceg** [comment]
Sorry, a little more info:
I'm running Windows 7.
Using VS Code and the CLI (trying with both 'cmd.exe' and git-bash)
SQL Server 2014

Thanks again!

**Comment by gforceg** [comment]
A coworker just advised me that the database I inherited has no primary keys in it. Would that cause this issue?

**Comment by smitpatel** [comment]
@gforceg - If it has no primary keys defined then it is likely to fail creating entity type using ef scaffolding. You may not be seeing warnings due to #7315

**Comment by gforceg** [comment]
Thanks @smitpatel and @Alex-Torres. I swapped out the database in question w/ another that does have primary keys and it worked perfectly.
