### ISSUE TITLE
Create new Sqlite database programatically

### ISSUE THREAD

**Issue by reneherrero** [dotnet/efcore#7919]
Hi,

Forgive me if this sounds like a newbie question, I'm going into uncharted territory...

What I'm trying to do is simple: create a new SQLite database programmatically.  The DB is used for caching purposes and does not need to be updated -> just deleting it and recreating a new one will work fine, and be less error prone I'm temped to think.

I found the context.Database.Migrate(); migrate function, and it does create the database, but only the __EFMigrationsHistory table is created.  Am I missing something?

I've seen tons of docs around the dotnet-ef tooling (no support for UWP is a bummer), but noting of how to perform operations at run time?

Thanks,

**Comment by ajcvickers** [comment]
@reneherrero Look at `context.Database.EnsureCreated()` and `context.Database.EnsureDeleted()`.

**Comment by reneherrero** [comment]
Damn, worked like a charm... can't believe I missed that...
Wish I could by you a beer! :)
Thanks!  And awesome work!  Love how you separated the relational stuff into a separate Nuget and the flexibility that provides... very sweet.
