### ISSUE TITLE
PMC Tools: Scaffold-DbContext hangs when run from install.ps1

### ISSUE THREAD

**Issue by aday12345** [dotnet/efcore#7926]
i am trying to create a NuGet package that will run some Powershell  the will call 'Scaffold-DbContext'
then i do this is looks like visual studio is trying to build the project but it just hangs and i have to end the process because visual studio never comes back.

if i run the 'Scaffold-DbContext' in the pm console directly is works fine but not from a powershell script that is executed during a NuGet package install.

Here is my powershell function

```
Function btnOK_Click()
{
	param($dbConnection, $modelName)
	
    	[void]$MyForm.Close()

	Write-Host 'dbConnection: ' $dbConnection
	Write-Host 'modelName: ' $modelName
         
        Scaffold-DbContext -Connection "data source=Test;initial catalog=Test;user id=TestUser;password=TestPassword" -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir "Models" -Context "TestContext" -Force


}

```
Any ideas?

### Further technical details
EF Core version: 1.1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: windows 7
IDE: Visual Studio 2017 .Net 4.6.2

**Comment by bricelam** [comment]
If you disabled NuGet's automatic package restore, does it work? Maybe NuGet puts a lock on some project resource...

**Comment by aday12345** [comment]
Just tried that at is did not fix it, also tried 'Set-ExecutionPolicy Bypass -Scope Process' on the line before the call to 'Scaffold-DbContext' but it still just freezes vs and i have to end the process

**Comment by aday12345** [comment]
i am going to try looking into this some more, but could this be some kind of bug?

**Comment by bricelam** [comment]
Yes, it could be a bug (or limitation) of NuGet or Visual Studio, or something else. We need to figure out where the deadlock is happening.

**Comment by aday12345** [comment]
Ok, thanks

If there is anything I can do please let me know

**Comment by bricelam** [comment]
@aday12345 You're trying to do this using `install.ps1`, right?

**Comment by aday12345** [comment]
yes

**Comment by ajcvickers** [comment]
@bricelam Can you provide a bit more context on what needs doing here? (Can talk in person when you are in if that's easier.)

**Comment by bricelam** [comment]
We need debug this by creating a NuGet package with an `install.ps1` that calls `Scaffold-DbContext`. Assuming it repros, we need to determine what is deadlocking and file an appropriate issue on either NuGet or the VS project system.

**Comment by ajcvickers** [comment]
@aday12345 `install.ps1` is not something we have seen used very much and is not supported in the modern variants of NuGet. We strongly recommend that you find a different approach. If you still have problems when not using `install.ps1`, then please open a new issue for that. You could try filing a bug on NuGet about things not working when run in `install.ps1` but I am confident that they will also close the issue. Sorry we couldn't be of more help here.

**Comment by aday12345** [comment]
I will try but I am not aware of any other way I can run this command from a NuGet package then using install.ps1 it needs to run from PowerShell
