### ISSUE TITLE
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.3.0'

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/efcore#7931]
Visual Studio Community 2017, .NET desktop development and only the Option SQL Server Express 2016 LocalDB

When I try to install Microsoft.EntityFrameworkCore.SqlServer, I get the following error:

Install-Package : Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.3.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, 
contact the package author.

**Comment by ajcvickers** [comment]
@MarcoLoetscher We made some recent changes to the configuration. Can you try this again?

**Comment by MarcoLoetscher** [comment]
It still does not work.
I think it might be due to the minimal installation of Visual Studio.

![visualstudio](https://cloud.githubusercontent.com/assets/15805817/24369382/15f99d42-1324-11e7-8be9-8a67d8868d59.png)

**Comment by ajcvickers** [comment]
@MarcoLoetscher A couple more questions as we try to track down what is happening:
* What version of EF Core are you using?
* Does it work if you use .NET 4.6 instead of 4.6.1?

**Comment by MarcoLoetscher** [comment]
- EF Core 1.1.1, but with version 1.1.0, I have the same problem.
- Even with .NET 4.6 it does not work.

**Comment by ajcvickers** [comment]
@pranavkm Is this a known issue with 4.6/4.6.1?

**Comment by pranavkm** [comment]
The package targets `netstandard1.1`, so it should work with `net46` (afaik we use it projects targeting `netstandard1.3`). @ericstj any guesses what might be wrong?

**Comment by ericstj** [comment]
No clue.  The package definitely works in net45 and later.  It actually explicitly provides a lib for net45.  Manual installation works fine for me.  Don't trust NuGet's error messages.  IIRC it'll give you the same error if it can't find the package.  Try looking at the package manager output window, it may give you more information.

**Comment by MarcoLoetscher** [comment]
I have tested again with Windows 10 Creators Update and .NET 4.7. When I try to install Microsoft.EntityFrameworkCore.SqlServer, I get the following error:

Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.3.0'. You are trying to install this package into a project that 
targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.

My Visual Studio Installation looks as follows:
![visualstudio](https://cloud.githubusercontent.com/assets/15805817/25062416/03830d7c-21cc-11e7-8549-48c0b54dc5f5.PNG)

**Comment by MarcoLoetscher** [comment]
I found a solution. In Tools -> Options... -> "NuGet Package Manager" -> I clicked "Clear All NuGet Cache(s)", and now it works.
