### ISSUE TITLE
Replacement for IPluralizationService

### ISSUE THREAD

**Issue by Daniel15** [dotnet/efcore#7933]
I'm trying to convert a site from Entity Framework 6 to Entity Framework Core. In my database context, I have some code like this:

```csharp
// Remove "Model" suffix for models ("ProjectModel" -> "projects")
var pluralizationService = DbConfiguration.DependencyResolver.GetService<IPluralizationService>();
modelBuilder.Types().Configure(config =>
{
	var cleanName = config.ClrType.Name.Replace(MODEL_SUFFIX, string.Empty).ToLowerInvariant();
	config.ToTable(pluralizationService.Pluralize(cleanName));
});
```

Is there a replacement for `IPluralizationService`? After reading #3060, my understanding is that pluralisation is no longer done automatically by Entity Framework. However, is the previous implementation of `IPluralizationService` available as a standalone project? In my cases I could just append an "s", I'd really like to use a proper pluralisation library though, and the one included with EF6 worked very well for my use cases.

Thanks!

**Comment by ajcvickers** [comment]
@Daniel15 There is no replacement in EF Core and we don't plan to add one at this time or make the previous one available standalone. Rowan's post here: https://romiller.com/2017/02/10/ef-core-1-1-pluralization-in-reverse-engineer/ uses an external pluralization service. Maybe you could use this for your needs?

**Comment by Daniel15** [comment]
Thanks @ajcvickers! It turns out I don't even need this due to the fact that EF Core uses the DbSet property name as the table name by default (#4688).
