### ISSUE TITLE
Intellitrace support?

### ISSUE THREAD

**Issue by joshmouch** [dotnet/efcore#7941]
Is there a way to get Entity Framework Core queries to show up in the Diagnostic Tools window in Visual Studio?
Is this currently supported, or will it be?

I see that Application Insights can capture when a query occurs, but doesn't capture much detail (no script, no line numbers, etc.).

**Comment by ajcvickers** [comment]
@joshmouch SQL Server queries should be showing up already. Are you asking this for some other provider?

**Comment by joshmouch** [comment]
No, I'm asking for SQL Server.
Do you need VS Ultimate to view them?
Would using the `Microsoft.AspNetCore.TestHost.TestServer` and initiating the requests from an xunit test cause them to not show up in any way?
The only events I see in the Diagnostic Tools are "Application Insight" events.

**Comment by ajcvickers** [comment]
@joshmouch In full .NET Framework, SQL Client had Intellitrace integration. My understand is that this is not available in .NET Core. As of right now, I am not sure what is sending messages where, but I have opened #8009 to investigate and track this.
