### ISSUE TITLE
CommandLineUtils is duplicated

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#7949]
EF has an almost-exact copy of [Microsoft.Extensions.CommandLineUtils.Sources](https://github.com/aspnet/Common/tree/dev/shared/Microsoft.Extensions.CommandLineUtils.Sources/CommandLine)

I believe it was added because early versions of csproj didn't support contentFiles yet. I see it has since diverged from what is in aspnet/Common (https://github.com/aspnet/EntityFramework.Tools/pull/36). Can we lift these changes to aspnet/Common to make the fixes to CommandLineApplication available to _all_ aspnet tooling, not just EF?

cc @bricelam

**Comment by bricelam** [comment]
Ours has been simplified and customized to meet our specific needs. Ultimately, we just want to use System.CommandLine when it's done.

**Comment by natemcmaster** [comment]
What were the changes? Would our other command line apps benefit from them?

**Comment by bricelam** [comment]
Probably not. They allow known options after unknown arguments. E.g. to capture --verbose when in dotnet-ef when 'dotnet ef database update --verbose' is specified. ('database' and 'update' are captured as extra args)

**Comment by bricelam** [comment]
It's really only valuable for dispatching commands.

**Comment by natemcmaster** [comment]
I see. There is still value in de-duping shared code, but if your changes are too disruptive to the way CommandLineApplication worked then never mind.

**Comment by ajcvickers** [comment]
Discussed in triage and decided that, per @bricelam's comments and reccomendation, we wish to keep our fork, since it has changes specific to our tool. We accept the responsibility of merging any upstream fixes.
