### ISSUE TITLE
In Memory does'nt work with special types

### ISSUE THREAD

**Issue by gsGabriel** [dotnet/efcore#7960]
I have a problem when I use the in-memory database. My context has been mapped to a postgresql database and has a table with PostgisGeometry type, but when I try to run tests in memory the following error occurs:

**Cannot call Property for the property 'Geom' on entity type 'TbGeometry' because it is configured as a navigation property. Property can only be used to configure scalar properties.**

Can anybody help me?

### Steps to reproduce
Configure your context to options.UseInMemoryDatabase
Execute your tests

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
IDE: Visual Studio 2017

**Comment by roji** [comment]
I think I know what's going on, but to be sure could you please post the relevant parts of your model (affected entity as well as any code in your OnModelCreating which references it)?

**Comment by ozonni** [comment]
Also we have a problem with hstore type when property has Dictionary<string, string> type.

 System.InvalidOperationException : The property 'Description' is of type 'Dictionary<string, string>' which is not supported by current database provider. Either change the property CLR type or manually configure the database type for it.
Stack Trace:

**Comment by ajcvickers** [comment]
@ozonni The in-memory provider does not support all the data types that the postgres provider supports. Two points to consider:
* Different providers have different capabilities, including supporting different types. EF Core does not attempt to create a fully abstract layer over the database such that providers can just be swapped and the same code will always work. Instead, it allows common patterns and mechanisms to be used with different databases while also exposing database-specific capabilities to the application.
* The in-memory provider is not backed by a relational database. It's use in testing is limited to high-level abstractions that are agnostic to the underlying store. For relational testing with an in-memory database, SQLite in-memory mode is more appropriate. For cases where you application is using database-specific capabilities the testing will likely need to be done at a much higher level if the intention is to do it with in-memory data. For example, consider a repository backed by a different implementation.

**Comment by gsGabriel** [comment]
@roji 

Folow the code

On Model Creating property mapping
`entity.Property(e => e.Geom).HasColumnName("geom");`

Model
`public PostgisGeometry Geom { get; set; }`

**Comment by roji** [comment]
Yeah, as @ajcvickers explained, this is a PostgreSQL-specific type that the Npgsql provider recognizes, but none of the other providers do. It's definitely expected behavior for the memory provider not to support it.

You can have this property ignored when a non-Npgsql provider is being used, if that helps you out.

**Comment by gsGabriel** [comment]
thanks @roji and @ajcvickers

**Comment by syned** [comment]
@roji 
You wrote: "You can have this property ignored when a non-Npgsql provider is being used, if that helps you out."

I have the same issue with arrays. Npgsql is mapping them without issues, but in my tests InMemory provider cannot map them.
Could you please provide an example how can I ignore a property for InMemory provider?

**Comment by roji** [comment]
@syned unless I'm mistaken, the following should do the trick in your `OnModelCreating`:

```c#
if (context.Database.ProviderName != "Npgsql") {
    modelBuilder.Entity<MyEntity>(b => b.Ignore(e => e.MyPropertyToBeIgnored));
}
```

**Comment by syned** [comment]
@roji  Thank you very much! It does the trick.
