### ISSUE TITLE
DateTime comparison in Where predicate is ignoring time of day 

### ISSUE THREAD

**Issue by victor168** [dotnet/efcore#7962]
Hello,

I am using a query with a Where clause like the following:

```
Where(v => v.CreatedDate >= minimumDate)
```

However, it will match regardless of the time of day as long as the Date (i.e. month, day, year) is satisfied.  That is, in my example, if minimumDate was 5pm today, and CreatedDate was 2pm today, it would satisfy the Where clause and this is not correct.

The SQL Server table column "CreatedDate" is using the "datetime" type, so there is time of day information saved.

How to have the time considered when comparing DateTime values in the Where clause?

Thanks!

### Further technical details
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Http.Extensions": "1.1.0",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.1.0",
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha4",
    "Newtonsoft.Json": "9.0.1",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "NETCore.MailKit": "1.0.1",
    "JamaDB": "1.0.0-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "LinqKit.Microsoft.EntityFrameworkCore": "1.1.9"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

**Comment by pmiddleton** [comment]
That is how you compare datetimes so it should be working.  There is probably an issue elsewhere in your code.  Can you provider a working example of the issue.

**Comment by victor168** [comment]
Hi @pmiddleton ,

Thanks for your reply and confirmation that it is working!   

After 4 more hours of debugging I noticed it was indeed my environment.  The SQL Server is residing in a different timezone than my client code.  And my client code is communicating via a REST API to extract the database information.  It turns out that the Json.NET serialization on my client side did not set any timezone handler and was serializing the datetime values as 'local'.  Therefore, the REST API was receiving a time that was always 4hrs less than UTC time which SQL Server was using.

After adding the following to my client code to default Json.NET's serializer settings my integration finally test passed:
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateTimeZoneHandling = DateTimeZoneHandling.Utc
            };
```

Thanks for being my '2nd' eye!!  :)
