### ISSUE TITLE
SQLite Migrations: Support more operations using PRAGMA writable_schema

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#7969]
`PRAGMA writable_schema = 1;` can be used for changes that don't affect the on-disk content:
* `AlterColumn` (when `defaultValue` or `defaultValueSql` change or `nullable` changes to `false`)
* `DropForeignKey`
* `RenameColumn`

⚠️ **Warning:** Misuse corrupts the database.

This could be a cheaper alternative to implementing full table rebuilds.

**Comment by ajcvickers** [comment]
It would be worth investing a day or so investigating whether we can safely get some cheap wins doing this.

**Comment by bricelam** [comment]
I don't think we should do this. It would require parsing and updating the full `CREATE TABLE` statement. Rebuilding the table is easier from a Migrations perspective.
