### ISSUE TITLE
EF Core Slower than EF6 

### ISSUE THREAD

**Issue by PawOrmstrupMadsen** [dotnet/efcore#7978]
We are porting an MVC app to .NET Core including EF6 to EF Code porting.

Performance is going the wrong way. by up to 200%

FULL .NET 4.5.1 Performance and SQL-Query
![ef6](https://cloud.githubusercontent.com/assets/11302862/24296900/3610a89e-10a1-11e7-9325-73ea4dbefaa4.PNG)
[ef6.txt](https://github.com/aspnet/EntityFramework/files/868052/ef6.txt)

.NET Core Performance and SQL-Query
![core](https://cloud.githubusercontent.com/assets/11302862/24296917/460885fa-10a1-11e7-98e1-c1fafa811a38.PNG)
[core.txt](https://github.com/aspnet/EntityFramework/files/868053/core.txt)

Both scenarios have been tested multiple times, in both release and debug, with and without debugger attached. the end result is always the same. its 200% slower on EF Core.

when we run the SQL-queries with Execution Plan enabled the Query costs the same.
so that leads me to believe that the EF Core implementation is slower than EF6 for some reason!

**Comment by tuespetre** [comment]
You have another level of entity in your model with Core than you did with EF6. That might have something to do with it.

Is this on cold start or have the queries already compiled before benchmarking? Can you try the same query through a simple console app that runs the query a good number of times and takes an average?

**Comment by PawOrmstrupMadsen** [comment]
i have a extra entry because its a many to many "container" which EF core dosnt handling as easy as the old ef6.

the times you see are after 3-6 runs, they dont change. the first and second runs are way slower.

**Comment by tuespetre** [comment]
Ah, ok. Thanks for that. I wonder how much of that overhead is coming from having to do the many-to-many like that.

**Comment by julielerman** [comment]
Also don't forget that includes are processed differently in EF Core. So with all those includes and the many to many, you may be paying a hefty price for materializing the objects from the resulting data. 

Have you looked at differences in what calls (& how many) are sent? (I know you said you've tested the raw sql). 

Have you looked at the differences in what the result sets look like? Can you look to see if extra time is BEFORE the query hits the database or in EF handling the results after wards? 

Sometimes just breaking teh query up into a few queries will help. 

Also, this doesn't affect the query, but if you don't need to track changes to the results, do you have tracking off (asnotracking). Just some ideas.

I spend a lot of time helping clients sort out "expensive" queries. Hopefully some of these ideas will lead you in the right direction to overcome differences between how EF6 and EF Core are processing this query.

**Comment by PawOrmstrupMadsen** [comment]
The raw queries are in the txt files. Ef core splits it into two calls as expected and ef6 does it in one query as expected.
They are however equally fast from ssms.

Any suggestion to how i can debug time spend before and after ef calls the db?

The end result-sets from ef6 and ef core are the same.

The reason i found this performance hit in the first place was the bug i reported in #7979 where it would hit the db 2000 times - the amount of image models in the db. 

Btw big fan julie lerman. Watched a lot of your content on pluralsight. 

I see my self as pretty good in ef6 with really hard and complicated queries, but ef core is in my testing not on par with ef6 yet in the performance department. 

Regarding speed:
The speed difference between async and sync calls took me by surprise last year. I pretty much improved all my complex ef6 (many joins) calls by 300-x000 % when using tolistasync.

**Comment by julielerman** [comment]
Ah I see the txt files! I *think* EFProf got updated but I haven't tried it with EF Core in .NET or .NET Core apps yet. I really don't know if you can get that detail from the fancy new performance explorer in 2017. But EF Prof does let you separate query time from app processing time.

**Comment by julielerman** [comment]
https://ayende.com/blog/176897/nhibernate-profiler-entity-framework-profiler-4-0-beta-release

**Comment by PawOrmstrupMadsen** [comment]
I'll run the profiler on monday. It's been a while since i used ef profiler.

**Comment by julielerman** [comment]
me too!  Usually with clients we first watch sql profiler in case it's something obvious like a horrible sql command. If not, then next step is EF Profiler. I really do need to check it out against EF Core and do some comparisons beyond the tsql generated .

**Comment by PawOrmstrupMadsen** [comment]
Sadly, my EF Profiler (4.0.4039) won't show Duration on the queries when doing them from EF Core, it works fine on EF6

![image](https://cloud.githubusercontent.com/assets/11302862/24346787/38f0ccba-12d6-11e7-9927-aba61c4aec1e.png)

I wrote their support for help.

**Comment by gdoron** [comment]
@PawOrmstrupMadsen You can run EF6's SQL in core with `FromSql`, curios to know if it helps.

**Comment by PawOrmstrupMadsen** [comment]
I dont think it will work with FromSql since i have multiple includes.

![image](https://cloud.githubusercontent.com/assets/11302862/24364906/7c165486-1314-11e7-8ce5-d004ad816d3b.png)

But i can give it a shot.

**Comment by ajcvickers** [comment]
@PawOrmstrupMadsen Would it be possible to get a project that reproduces this issue so we can investigate?

**Comment by PawOrmstrupMadsen** [comment]
I'm at a loss, i cannot make EF Core behave as it did before the weekend. It must have been Visual Studio or something else. i can't make EF Core slower than EF 6 today..

EF 6 results today:
![image](https://cloud.githubusercontent.com/assets/11302862/24374279/84b592e4-1334-11e7-8cc1-9262e6daeda0.png)

EF Core results today:
![image](https://cloud.githubusercontent.com/assets/11302862/24374298/963f2bb0-1334-11e7-83a5-1b39bdc0e1a5.png)

I also tried 2 Console app, one targeting Core and the other targeting 4.6.2

EF 6 result:
![image](https://cloud.githubusercontent.com/assets/11302862/24374418/13dd90b6-1335-11e7-8c34-cb54b720a554.png)



EF Core result:
![image](https://cloud.githubusercontent.com/assets/11302862/24374411/0db7e20e-1335-11e7-84e6-119d96cb20dd.png)

First run is not included in Average numbers.

But i did manage to recreate the #7979 bug i reported in the console app.

This works as intended:
![image](https://cloud.githubusercontent.com/assets/11302862/24374471/518a661e-1335-11e7-8033-1b0f99d8d9c3.png)

This suddenly creates a query to the db for every image on the product which it shouldn't since we are including the ImageType already:
![image](https://cloud.githubusercontent.com/assets/11302862/24374509/6e676016-1335-11e7-87f6-07d4a14031f0.png)

making the query times look like this:
![image](https://cloud.githubusercontent.com/assets/11302862/24374577/b09cb26a-1335-11e7-827b-d31521e51e65.png)

I've attached Both Console apps and a Backup of the DB (stripped down to minimum tables)
[files.zip](https://github.com/aspnet/EntityFramework/files/873580/files.zip)

Btw i tried with async using ToListAsync() and it is really slow:

EF 6:
![image](https://cloud.githubusercontent.com/assets/11302862/24375023/2c1673bc-1337-11e7-85df-b5101ab4fd17.png)


EF Core:
![image](https://cloud.githubusercontent.com/assets/11302862/24375017/2463d20e-1337-11e7-9294-f3d589f74701.png)

I know that await / async is a bit slower, but i am still wondering if there is something wrong with ToListAsync() ? it should not be double the time!

PC Specs:
CPU I7-5960x (16 threads)
32GB DDR4 3000Mhz
Samsung 950 Pro 512GB NVME
Windows 10 
VS 2017 Pro
SQL 2016 Developer

**Comment by divega** [comment]
@PawOrmstrupMadsen based on your previous comment, would you agree that this issue doesn't repro but we should investigate #7979 instead using the same repro code?

**Comment by PawOrmstrupMadsen** [comment]
Yes.
