### ISSUE TITLE
Scaffold-DbContext Use Schema in Object Name

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/efcore#7980]
I'm not sure if this repo was split to an issues list and features discussion list. Please let me know.
Also, if there is a general thread for Scaffold-DbContext command line features can you point me to it?
### Current
When reversing a DB with schemas, same-name tables come across as Table, Table1.

### Future
Same-name tables should incorporate the schema name. Ugly, but maybe using an _.
 Account.Owner => Account_Owner
 Invoice.Owner => Invoice_Owner

**Comment by lajones** [comment]
Dupe of #3988.
