### ISSUE TITLE
Question - Build Models from Existing Context?

### ISSUE THREAD

**Issue by RandyBuchholz** [dotnet/efcore#7981]
I'm playing with a Context-First approach, where I write the context and then gen both the db and models. Is there a "migration" command that just generates the classes from an existing context and does nothing more?

**Comment by ajcvickers** [comment]
@RandyBuchholz Can you post a simple example of what you would write and then outline what gets generated?

**Comment by RandyBuchholz** [comment]
In a DB first approach, reversing generates both the context and models. I want to add custom things to my models. So I would like to create the context first, modify it, and then generate the models. Or I may already have the models and I want to apply changes to them based O/R information. Ideally, I could just start from the Context.cs, and generate both the DB and Models.

For example, I may want to add configure or add attributes to specific properties in a DB-First approach. I can create an extension method on PropertyBuilder.  This isn't exactly what I'm trying to do, it's just for illustration.
```
public static PropertyBuilder<string> ApplySomeDomainInfo(this PropertyBuilder<string> property, Enum domain) {
    var domainLength = _domainService.GetLength(domain);
    property.HasMaxLength(domainLength);
    // other code to add DomainAttribute
    return property;
}
```
After I reverse, I edit Context to add this.
```
modelBuilder.Entity<Invoice>(entity =>
{
    entity.ToTable("Invoice", "Accounts");
    entity.Property(e => e.Name).HasColumnType("varchar(64)").ApplyDomain(Domains.Name);
    entity.Property(e => e.Address).HasColumnType("varchar(128)").ApplyDomain(Domains.Address);
});
```
Then I want to generate or update my models to look like this
```
public partial class Invoice
{
    public int Id { get; set; }

    [MaxLength(60)]
    [Domain(Domains.Name)]
    public string Name { get; set; }

    [MaxLength(120)]
    [Domain(Domains.Address)]
    public string Address { get; set; }
}
```
So I want to do the reverse in two steps, or be able to do the second step on its own. Ideally, the command wouldn't build first, because my models may not exist, so Context will be full of errors. I could create dummies and use -force though.

The actual case I'm working on involves designing the DB and parts of the object model in a modeling tool, and then generating Context from the tool. Context would then have the info to build both my DB using existing migration tools, and the models too - if I can somehow execute just the model builder part of Scaffold-DbContext that creates the Model.cs files.

**Comment by ajcvickers** [comment]
@RandyBuchholz This is not something we are planning to tackle. It seems like there would be lots of chicken/egg issues and complexity with the implementation without adding much value to the common ways people use EF.

**Comment by RandyBuchholz** [comment]
@ajcvickers I get that you wouldn't want to put any effort into something like this, and wasn't looking for that. I was just hoping there was something exposed already that I wasn't aware of.

**Comment by ajcvickers** [comment]
@RandyBuchholz Not that I am aware of.
