### ISSUE TITLE
VS 2017 shows red squiggly on UseSqlSever when method is resolved 

### ISSUE THREAD

**Issue by ghost** [dotnet/efcore#7984]
Describe what is not working as expected.

I see a red swiggeling line when this schould be resolved in the startup.cs file 

### Steps to reproduce
Start a new project. 
And add this line to startup.cs : 
    
    services.AddDbContext<AppDbContext>(options => options.UseSqlServer(_configurationRoot.GetConnectionString("DefaultConnection"))); 
            services.AddTransient<ICategoryRepository, MockCategoryRepository>();

you see then this error message when building : 

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	CS1061	'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer' and no   extension method 'UseSqlServer' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)	BethamyPieShop	C:\Users\rwobb\Documents\Visual Studio 2017\Projects\Challenges\BethamyPieShop\BethamyPieShop\Startup.cs	32	Active

    
     

### Further technical details
EF Core version:  1.1 
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017

**Comment by rwobben** [comment]
Solved with a little help, 

I had to add this using :  using Microsoft.EntityFrameworkCore;
