### ISSUE TITLE
Refactor exception catching to use catch-when

### ISSUE THREAD

**Issue by colltoaction** [dotnet/efcore#7987]
I was debugging some code and realized we can refactor our code to use the C#6 `catch`-`when` feature to improve our experience a little bit.

Take a look for example at https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer/Storage/Internal/SqlServerExecutionStrategy.cs#L28.

```cs
try
{
    return operation(state);
}
catch (Exception ex)
{
    if (ExecutionStrategy.CallOnWrappedException(ex, SqlServerTransientExceptionDetector.ShouldRetryOn))
    {
        throw new InvalidOperationException(SqlServerStrings.TransientExceptionDetected, ex);
    }

    throw;
}
```

This means that when `operation` throws an exception that doesn't match the condition, our code will break on the `throw;` line and we'll have to find where the real exception was thrown.

This would be functionally equivalent and provide a better debugging experience:

```cs
try
{
    return operation(state);
}
catch (Exception ex) when (ExecutionStrategy.CallOnWrappedException(ex, SqlServerTransientExceptionDetector.ShouldRetryOn))
{
    throw new InvalidOperationException(SqlServerStrings.TransientExceptionDetected, ex);
}
```

It might be worth looking into other places where this can be done.

**Comment by tinchou** [comment]
This is also cool about exception filters: http://stackoverflow.com/a/38498087/625581
