### ISSUE TITLE
Cannot debug dotnet ef dbcontext scaffold

### ISSUE THREAD

**Issue by zsvanderlaan** [dotnet/efcore#7990]
I am trying to debug my application as it is being invoked by entity framework dbscaffold, but do not get debugging symbols loaded for my code.

My project looks like this:

![image](https://cloud.githubusercontent.com/assets/18043474/24317390/ccb43be6-10b3-11e7-94fe-d01dfc175a95.png)

I have these dependencies:
![image](https://cloud.githubusercontent.com/assets/18043474/24317210/47fc817a-10b2-11e7-9023-ed061be6f671.png)

My csproj file looks like this:
![image](https://cloud.githubusercontent.com/assets/18043474/24317300/fe954480-10b2-11e7-92c4-c0aa9c0be623.png)

When I attempt to run the scaffold command:
dotnet ef dbcontext scaffold <connection_string_here> Microsoft.EntityFrameworkCore.SqlServer --data-annotations --force --context BaseDatabaseContext --output-dir .\Models

I expect that because I have Debugger.Launch() that when my debugger attaches I will be able to see the breakpoint I have set and step through. Unfortunately I do not.

![image](https://cloud.githubusercontent.com/assets/18043474/24317265/c1a7892a-10b2-11e7-9290-e798d074a8a5.png)

Further, if I continue (pressing the continue button) I get the following error which crashes the process:

![image](https://cloud.githubusercontent.com/assets/18043474/24317334/3d94f3a6-10b3-11e7-8980-765217f922c8.png)

Most Importantly, please help me understand why I am getting an source not available error. Secondly, how do i prevent the application from crashing so i can step through? I am hoping to implement my own EntityTypeWriter by registering it in the ConfigureDesignTimeServices method configuration hook, but if I can't step through and see what value's I have to work with it won't do me much good.

Thanks!

**Comment by ajcvickers** [comment]
@Eilon Is there a general issue somewhere on GitHib that tracks making symbols available for our packages?

**Comment by Eilon** [comment]
Symbol publishing is tracked here: https://github.com/aspnet/Coherence/issues/124

**Comment by ajcvickers** [comment]
@zsvanderlaan We are working on being able to get symbols published as part of the wider ASP.NET Core and ,NET Core projects. This is being tracked for us by the issue @Eilon referenced above.

With regard to the crash, does it happen only when debugging, or also when you run the code outside of the debugger?

**Comment by zsvanderlaan** [comment]
I believe the error was caused within my implementation of CustomCandidateNamingService and not dotnetcore.

I look forward to seeing symbol support in the future, this process would have been much simpler.

For the time being i found a workaround by using the -v flag on my scaffold command and used console.Write for output based debugging.

Thanks for the response
