### ISSUE TITLE
Transition references doesn't work how it could be expected: System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.1.1.0...

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/efcore#7994]
VS 2017.  4.6.01586

**Steps:**
1) Create Command Line framework 4.6.2 project
2) Create Library for Standard 1.4. project
3) Reference lib project in the Command Line project,  run it with test line  `var c = new ClassLibrary1.Class1()`,  everithing is ok. 
4) Add Nuget package `Microsoft.EntityFrameworkCore.SqlServer` (current version 1.1.1, supports .NETStandard 1.3) to  our lib project.
5) Create a class in a lib 

```
   public class TestDbContext : DbContext
    {
    }
```

6) Add this to Program.cs

```
        static void Main(string[] args)
        {
            var c = new ClassLibrary1.Class1();
            var t = new TestDbContext();
        }
```
7) Run it

**Expected :** 
no errors

**Actual result:**

![image](https://cloud.githubusercontent.com/assets/11598038/24323865/cd71aa6a-1184-11e7-8dc8-68842fa13f73.png)

Files:
[Transitions.zip](https://github.com/aspnet/EntityFramework/files/870153/Transitions.zip)

Adding "Microsoft.EntityFrameworkCore.SqlServer" directly to the console app solves the problem.

P.S. It seems that transition references doesn't work for all NUGET projects not only for EF core. 
So it is not yours problem. It is generic NETFramework problem.

**Comment by ajcvickers** [comment]
@rpokrovskij This doesn't seem to be an EF issue. Can you file something on NuGet: https://github.com/NuGet/Home/issues
