### ISSUE TITLE
VB.NET Migrations Support

### ISSUE THREAD

**Issue by InteXX** [dotnet/efcore#8012]
Please support VB.NET migrations.

What is the latest status?

**Comment by bricelam** [comment]
Related: #6401

**Comment by intexx** [comment]
@bricelam — Thank you for the link, but my question remains. Is there any ETA for VB support in Migrations? Is VB support expected at all?

**Comment by intexx** [comment]
@ajcvickers — I see you added this to the 2.0.0 milestone. Does this mean that VB support is targeted for the v2.0.0 release? If so, is there any ETA for the milestone?

**Comment by ajcvickers** [comment]
@intexx No, it means that @divega is assigned to do follow up on it.

**Comment by intexx** [comment]
@ajcvickers — OK, thanks. Will he be replying in this thread, do you expect?

**Comment by ajcvickers** [comment]
@intexx Yes, I expect he will, but he is a busy person with many other things to do.

**Comment by intexx** [comment]
@ajcvickers — Aren't we all :-) OK, thanks. I'll wait for his reply.

**Comment by divega** [comment]
@intexx thanks for your patience. The answer for this one is basically the same we had previously for F#:

We are not planning on implementing VB support as part of EF Core, but we would consider fixing any issues or taking any PR required to improve our extensibility story so that VB support can be cleanly implemented as a separate package.

**Comment by divega** [comment]
**Note for triage:** Let's decide together whether we want to close this issue or keep it in the backlog as an up-for-grabs. Although it is a valid request we now tend not to keep open issues to track work we are not planning to do. Whatever the decision, we should probably do the same with #6401 for F#.

**Comment by intexx** [comment]
@divega — Thanks for the update, although I have to admit I'm a bit saddened by the news. The extensibility side of the question sounds like it can be a solution, however bittersweet.

I would tend to agree with closing the issue, in keeping with your stated policy of not tracking active projects.

**Comment by intexx** [comment]
@divega — Could you point out the current C# generator, so I can get an idea of what's involved? I'm having some trouble spotting it.

**Comment by bricelam** [comment]
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs

**Comment by intexx** [comment]
@bricelam — Thanks.

**Comment by bricelam** [comment]
Here's some code to get started for anyone looking to generate migrations in a different language.
```vb
' Put this in your app. EF discovers and calls it at design-time.
Public Class MyDesignTimeServices
    Implements IDesignTimeServices

    Public Sub ConfigureDesignTimeServices(services As IServiceCollection)
        services.AddSingleton(Of MigrationsCodeGenerator, VBMigrationsCodeGenerator)()
    End Sub
End Class
```
```vb
Public Class VBMigrationsCodeGenerator
    Inherits MigrationsCodeGenerator

    Public Overrides ReadOnly Property FileExtension() As String
        Get
            Return ".vb"
        End Get
    End Property

    Public Overrides Function GenerateMigration(migrationNamespace As String, migrationName As String, upOperations As IReadOnlyList(Of MigrationOperation), downOperations As IReadOnlyList(Of MigrationOperation)) As String
        Return "' TODO"
    End Function

    Public Overrides Function GenerateMetadata(migrationNamespace As String, contextType As Type, migrationName As String, migrationId As String, targetModel As IModel) As String
        Return "' TODO"
    End Function

    Public Overrides Function GenerateSnapshot(modelSnapshotNamespace As String, contextType As Type, modelSnapshotName As String, model As IModel) As String
        Return "' TODO"
    End Function
End Class
```
For reference, see the C# implementation in [CSharpMigrationsGenerator.cs](https://github.com/aspnet/EntityFramework/blob/rel/1.1.2/src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs).

**Comment by intexx** [comment]
@bricelam — Thank you!

**Comment by bricelam** [comment]
For anyone watching this issue, we're collaborating on this (and Reverse Engineer support) over in the [bricelam/EFCore.VisualBasic](https://github.com/bricelam/EFCore.VisualBasic) repo.
