### ISSUE TITLE
Have we stopped supporting .NET 4.5.1?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#8018]
What is going on?

**Could not install package 'Microsoft.EntityFrameworkCore.Relational 1.2.0-preview1-24146'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

**Comment by MarcoLoetscher** [comment]
Perhaps because of the following change: https://github.com/aspnet/EntityFramework/issues/7931

**Comment by smitpatel** [comment]
@ErikEJ - See #7976 
@ajcvickers @Eilon can give more info why it was done.

**Comment by Eilon** [comment]
@ErikEJ .NET Framework 4.5 (and 4.5.1) are no longer a supported products, see this blog post: https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

For that reason, plus the additional cost of developing and testing it, we have dropped support for it.

**Comment by ErikEJ** [comment]
@Eilon Thanks, I will follow suit then! 🛩

**Comment by Eilon** [comment]
@ErikEJ sounds good!
