### ISSUE TITLE
The generated SQL query is not optimal

### ISSUE THREAD

**Issue by michaelantoun** [dotnet/efcore#8027]
The generated SQL query does not have the "Count" in the SELECT clause when I call it from IAsyncEnumerable. It selects all the records from Microsoft SQL DB, then returns the count. This is not efficient.

There is no exceptions.

### Steps to reproduce
1. Create in Visual Studio 2017 a Class Library (.NET Standard) then upgrade it to v1.6
2. Install the following packages:
 - Microsoft.EntityFrameworkCore.Tools v1.1.0
 - Microsoft.EntityFrameworkCore.SqlServer v1.1.1
3. Create a class which inherits from DBContext
4. Configure the connection string to connect to Microsoft SQL Server
5. Finally, try the following C# code

```c#
// [Bug] this LINQ query generates a SQL statement without "Count" in the SELECT clause
int count = _myDbContext.Contacts.ToAsyncEnumerable().Count();

// [Works as expected] this LINQ query generates a SQL statement with "Count" in the SELECT clause
int count = _myDbContext.Contacts.Count();
```

### Further technical details
IDE: Visual Studio 2017
Installed Packages: 
 - NETStandard.Library v1.6
 - Microsoft.EntityFrameworkCore.Tools v1.1.0
 - Microsoft.EntityFrameworkCore.SqlServer v1.1.1
SQL Server: Microsoft SQL Server 2014 (SP2-GDR) (KB3194714) - 12.0.5203.0 (X64) 
	Sep 23 2016 18:13:56 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

Thanks!

**Comment by smitpatel** [comment]
This answer explains the reason for the difference pretty well. http://stackoverflow.com/a/2876655/4484219
