### ISSUE TITLE
Advice on creating alias expression

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#8039]
@smitpatel - now that AliasExpression has changed, do you have any tips for how to use it here:

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Query/Sql/Internal/SqlCeQuerySqlGenerator.cs#L112

TIA!

**Comment by smitpatel** [comment]
It would be very straight forward in that case.
With #6994, we no longer have requirement that operand of `InExpression` has to be `AliasExpression`. You can just use left or right without checking it being alias & wrapping in it.

**Comment by ErikEJ** [comment]
Thanks!
