### ISSUE TITLE
the connection is not close

### ISSUE THREAD

**Issue by judypol** [dotnet/efcore#8041]
Describe what is not working as expected.

in Dispose() function,I check the connection state,but the state is always closed, and in the database, can see many sleeping connection. my code is Below:
        if (this.Database.GetDbConnection().State != ConnectionState.Closed)
                {
                    this.Database.GetDbConnection().Close();
                    Debug.WriteLine("Close()");
                }
using(var db=new DbContext())
{
}
### Further technical details
EF Core version:1.0.0 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: window 10,ubuntu
IDE: Visual Studio 2015

**Comment by divega** [comment]
@judypol keep in mind that SQL Server's ADO.NET provider matains a pool of connections that are ready to use. The provider abstracts the management of the pool, so when you close a `SqlConnection` object, the underlying connection isn't really closed but just returned to the pool to be reused. 

To confirm that the open connections you are seeing on the server are the ones on the pool you may want to observe the effects of calling the `ClearPools()` method.

**Comment by judypol** [comment]
@divega,how can I set the max connections. In my Database the connections are more than 500.

**Comment by divega** [comment]
@judypol look at the connection string documentation, in particular the max pool size and min pool size settings at https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring.aspx
