### ISSUE TITLE
Adding entities using AddRange method does not refresh entity ID

### ISSUE THREAD

**Issue by laksh-parab** [dotnet/efcore#8049]
looks like when i add IEnumerable of entities using AddRange method, and then save, then it saves records in the database however it does not refresh entity ID

detail [here on so](http://stackoverflow.com/questions/43147035/addrange-method-does-not-refresh-entity-id-with-ienumerable)

**Comment by ajcvickers** [comment]
@laksh-parab The code shown in the linked post enumerates the IEnumerable twice, each time creating new Test object instances. This means the objects being saved are not the objects on which you are looking at the IDs.

In other words, these aren't the objects you're looking for.
