### ISSUE TITLE
Our customer can't open database port connection on local database they have PCI compliance security issue

### ISSUE THREAD

**Issue by uthens** [dotnet/efcore#8099]
{
"ConnectionStrings": {
"DefaultConnection": "Server=xx.xx.xx.xxx;Database=DBNAME;uid=sa;pwd=password;MultipleActiveResultSets=true;"
},
"AppSettings": {
"InMemoryProvider": "false"
}
}

**Question:**
On EF core we used connection string on appsetting.jason
but our customer can't open database port they have the security issue on pci compliance.

Our API will install on azure, but customer database install on customer local site.

1) How we can resolve on this problem ? and you have other solution for suggestion ?
2) How we can connection customer local database and they can't open database port ?

Best,
Uthen

**Comment by ajcvickers** [comment]
@uthens This doesn't seem to be an issue related to Entity Framework. You could try asking the question on http://stackoverflow.com/ Or maybe open an issue with Azure support if you think there is something actionable there?

**Comment by uthens** [comment]
It's related on this : http://stackoverflow.com/questions/43468765/ef-core-connection-string-on-private-local-database
