### ISSUE TITLE
The entity type '' requires a primary key to be defined

### ISSUE THREAD

**Issue by dmcweeney** [dotnet/efcore#8102]
Hi,

I have a simple table defined with no foreign key constraints defined (yet).
The table has a non-unique index defined.
I have the ModelBuilder defined using fluent api

When I run the code I get the following error:
HResult=0x80131509
  Message=The entity type 'xxx' requires a primary key to be defined.

The table is the target of a one-to-many relationship so does not have a primary key.
Is it a requirement of ef core that a table must have a primary key regardless? (I didn't pick this up from the docs if it is the case).

Asp.Net Core 1.1.1
EF Core 1.1.1
EF Core SqlServer 1.1.1

IDE - VS 2017

Thanks

Donal

**Comment by ajcvickers** [comment]
@dmcweeney Every entity type must have a primary key mapped to some column in the table.

**Comment by dmcweeney** [comment]
Ok @ajcvickers thanks for clarifying...
