### ISSUE TITLE
dotnet ef database update works only on net core web application and not on class library

### ISSUE THREAD

**Issue by nukec** [dotnet/efcore#8106]
So I am trying to understand is command dotnet ef database update and migrations commands working only in asp.net core web projects and not class libraries? I tried to run command in class library, then I changed project type from:

```
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>
```

to:

```
  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
```

and rerun command and identity tables were populated into database. Why?

### Further technical details
EF Core version: latest
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: VS 2017

**Comment by bricelam** [comment]
https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#net-standard-limitation
