### ISSUE TITLE
Don't deploy Microsoft.EFCore.Design on net451

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#811]
In [a design meeting](https://github.com/aspnet/EntityFramework/wiki/Entity-Framework-Design-Meeting-Notes---September-11,-2014#package-layout) we decided to package the net45 version of ~~EntityFramework.Commands.dll~~ **Microsoft.EntityFrameworkCore.Design.dll** under the tools directory so that it would not be deployed.

This, however, is not trivial using KoreBuild since it requires modifying the nuspec file in order to remove dependencies and framework assemblies for the net451 framework.

When this is easier to do, we should implement the intended design.

**Comment by natemcmaster** [comment]
Does this apply anymore?

**Comment by bricelam** [comment]
I think, in the current world, this would mean not deploying `Microsoft.EntityFrameworkCore.Design` in `packages.config`-based projects. It can stay on the backlog.

**Comment by bricelam** [comment]
One way to do this is to include a copy of it in `Microsoft.EntityFrameworkCore.Tools.VisualStudio` (and copy its dependencies there too) then copy it to the project's directory (like we do ef.exe) when we execute a command.

**Comment by bricelam** [comment]
The other way is to get NuGet to support `"type": "build"` dependencies in `packages.config` :wink:

**Comment by bricelam** [comment]
Closing. NuGet MSBuild work includes support for `PrivateAssets="All"`. As support moves to more platforms, this will just work.
