### ISSUE TITLE
Provider: Override table alias in the query pipeline

### ISSUE THREAD

**Issue by tomerNG** [dotnet/efcore#8112]
Is there a way to override the delimiter creation of an alias?
I would like to use "_" instead of ".".

For example: (this is generated by EF right now)
```
SELECT p.PlayerId, p.Country.CountryId
FROM Players AS p
LEFT JOIN Countries AS p.Country ON p.CountryId = p.Country.CountryId
WHERE p.CountryId = '123'
```
I would like to use p_Country as the alias instead of p.Country.
Can I somehow override it on my provider (I'm writing a provider for the Google Spanner db)?

**Comment by smitpatel** [comment]
@tomerNG - (Assuming you are writing relational provider)
You need to add provider specific `QueryCompilationContext`. (e.g. https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer/Query/Internal/SqlServerQueryCompilationContext.cs) which is deriving from `RelationalQueryCompilationContext`. 

Look at this method in `RelationalQueryCompilationContext`
https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/Query/RelationalQueryCompilationContext.cs#L136
It is responsible for create unique table alias in the query. You can override that function and format the table alias whichever way you want.

**Comment by tomerpeled** [comment]
Cool! That's indeed did the trick :)

Thanks!
