### ISSUE TITLE
float? maps to (real, not null)

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#8113]
Sorry if I misunderstand something but google couldn't not help me here
I have model

```
    public class Meter
    {
        [Key]
        [ScaffoldColumn(false)]
        public int MeterId { get; set; }

        public float Base { get; set; }

        public float? Base2 { get; set; }
    }
```

I expect Base2 allow null but this is what I get in DB

```
CREATE TABLE [dbo].[Meters](
	[MeterId] [int] IDENTITY(1,1) NOT NULL,
	[Base] [real] NOT NULL,
	[Base2] [real] NOT NULL
 CONSTRAINT [PK_Meters] PRIMARY KEY CLUSTERED 
(
	[MeterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

sorry buddy, no Nulls allowed

**Update**
```public System.Nullable<float> Base2 { get; set; } ```
works

**Comment by ajcvickers** [comment]
@dvdobrovolskiy What version of EF Core and what database provider are you using? I used 1.1.1 with SQL Server and got this:
```sql
CREATE TABLE [Meter] (
    [MeterId] int NOT NULL IDENTITY,
    [Base] real NOT NULL,
    [Base2] real,
    CONSTRAINT [PK_Meter] PRIMARY KEY ([MeterId])
);```

**Comment by ErikEJ** [comment]
@ajcvickers Would it not be better to explicitly specify "NULL" ? https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-null-dflt-on-transact-sql

**Comment by ajcvickers** [comment]
@bricelam Any comment on @ErikEJ's point?

**Comment by dvdobrovolskiy** [comment]
@ajcvickers 1.1.1 with SQL Server
Assembly Microsoft.EntityFrameworkCore, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

**Comment by ajcvickers** [comment]
@dvdobrovolskiy Can you post some code that reproduces the issue you are seeing?

**Comment by dvdobrovolskiy** [comment]
sorry but what I can show you? it just model and then I add migration via
add-migration some name

**Comment by dvdobrovolskiy** [comment]
I added new property to model mentioned above

        public float? Base4 { get; set; }

and now it works fine

            migrationBuilder.AddColumn<float>(
                name: "Base4",
                table: "Meters",
                nullable: true);

but here is what I had in previous migrations when I added 
        public float? Base2 { get; set; }
        public float? Base3{ get; set; }

            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "Meters",
                nullable: false,
                oldClrType: typeof(string),
                oldNullable: true);

            migrationBuilder.AlterColumn<float>(
                name: "Base3",
                table: "Meters",
                nullable: true,
                oldClrType: typeof(float));

**Comment by ajcvickers** [comment]
@dvdobrovolskiy Can you post a full code listing or project that reproduces this issue?

**Comment by bricelam** [comment]
> @bricelam Any comment on @ErikEJ's point?

I'm not sure how common it is. We've hard-coded other things that assume the default database configuration in the past, but have heard little feedback about it.

**Comment by ErikEJ** [comment]
I think it is also a question about being unambigous, and pleasing SQL DBAs

**Comment by ajcvickers** [comment]
@bricelam I'm fine with leaving it the way it is. @divega any concerns?

**Comment by divega** [comment]
@ajcvickers I may be missing context, but I tend to agree with @ErikEJ that it would be better if our DDL specified nullability explicitly even if, regardless of how common it is to issue `SET ANSI_NULL_DFLT_ON OFF`, e.g.:

``` SQL
CREATE TABLE [Meter] (
    [MeterId] int NOT NULL IDENTITY,
    [Base] real NOT NULL,
    [Base2] real NULL,
    CONSTRAINT [PK_Meter] PRIMARY KEY ([MeterId])
);
```

On the other hand, I have no idea if this is related to how @dvdobrovolskiy has hit this problem. I don't think he has necessarily used `SET ANSI_NULL_DFLT_ON OFF`.

**Comment by ajcvickers** [comment]
@divega I think it is a separate issue. If you are @ErikEJ think this is something that would be worth doing, then can you file a new issue for it?

**Comment by divega** [comment]
@ajcvickers done.

**Comment by dvdobrovolskiy** [comment]
Sorry. Was out of office.

I cannot reproduce problem any more. New properties like 
public float? Base5 { get; set; }
creates nullable field in DB

is anything I can do more?

**Comment by ajcvickers** [comment]
@dvdobrovolskiy Thanks for trying.

**Comment by dvdobrovolskiy** [comment]
It is an issue. 

Now I want to make value nullable
Was
public float Value2 { get; set; }
Become
public float? Value2 { get; set; }

add-migration generate empty migration. No change to column nullable state
Was 
[Value2] [real] NOT NULL 
and is 
[Value2] [real] NOT NULL,
