### ISSUE TITLE
EF6 CodeFirst query return wrong values.

### ISSUE THREAD

**Issue by Knight1988** [dotnet/efcore#8126]
I created following CodeFirst Model.

    public partial class ForumModel : DbContext
    {
        public ForumModel()
            : base("name=ForumModel")
        {
        }

        public virtual DbSet<Subject> Subjects { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Create relationship
            modelBuilder.Entity<Subject>()
                .HasMany(e => e.Children)
                .WithRequired(e => e.Parent)
                .HasForeignKey(e => e.ParentId)
                .WillCascadeOnDelete(false);
        }
    }

    [Table("Subject")]
    public partial class Subject
    {
        public int Id { get; set; }

        public int? ParentId { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        public virtual ICollection<Subject> Children { get; set; }
        public virtual Subject Parent { get; set; }
    }

Then i used a simple query like this

    db.Subjects.Count(p => p.ParentId == null) // should be 2 but return 0

But if i remove the relationship, it return correct value.

**Comment by ajcvickers** [comment]
@Knight1988 This GitHub tracker is for EF Core issues. EF6 issues should be filed at https://github.com/aspnet/EntityFramework6

That being said, it looks like the relationship is being defined as Required, meaning that the ParentId property is expected to be non-nullable, but your query is then expecting there to be nulls in the ParentId column.
