### ISSUE TITLE
SqlException: Using IDENTITY_INSERT ON, and Adding a Record with Id 0 causes error.

### ISSUE THREAD

**Issue by JT-Bruch** [dotnet/efcore#8128]
Describe what is not working as expected.
I have the following code 
```
      EntityTable.AddRange(Models.EntityTable.EnsureSeedData());
      Database.OpenConnection();
      Database.ExecuteSqlCommand("SET IDENTITY_INSERT dbo.EntityTable ON");
      var changeCount = SaveChanges();
      Database.CloseConnection();
```

Which seeds a database for me.  This does not work if the EntityTable first records' value is zero.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Microsoft.EntityFrameworkCore.DbUpdateException occurred
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

Inner Exception 1:
SqlException: Explicit value must be specified for identity column in table 'EntityTable' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity column.

```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
1. Clone this repo https://github.com/JT-Bruch/TestDatabaseSeed 
2. Open Program.CS
3. Make sure the connection string matches your SQL Server
4. Run the TestDatabase CLI Project.
5. See the error.

### Interesting details
After the `AddRange` the data does not look correct in the EntityTable.

![image](https://cloud.githubusercontent.com/assets/7430562/24924543/5f166282-1eb2-11e7-8695-1676722c9bad.png)

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 (Creators Update)
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@JT-Bruch EF Core does not allow key values that are the CLR default for the type when using properties configured to be store generated. We did at some point allow this to be configured, but that added complexity and confusion, so currently if you must use the CLR default as a valid key value, then you need to make the property a nullable type. (Usually a better option is to just not use zero as a valid key value, or to stop using store generated keys.)

**Comment by JT-Bruch** [comment]
@ajcvickers yeah, ideally I wouldn't use the CLR default, the issue is that this data is coming from an existing database and the purpose of this code is to simply generate our database.  Our application is rather large and I'm afraid that having the types be nullable could cause issues, OR change from the CLR default will cause issues with the application logic down the road.  

That said - of the two options I think nullable types is the way to go.

**Comment by JT-Bruch** [comment]
Also - thanks for the prompt response!

**Comment by ajcvickers** [comment]
@JT-Bruch You could consider making the key property ValueGenerated.Never in the model just while you are importing data.
