### ISSUE TITLE
String fields store 255 symbols only for MySql

### ISSUE THREAD

**Issue by firedeepan** [dotnet/efcore#8135]
I created a column with [Column(TypeName = "TEXT")]. But the string is limited to 255 symbols when it is saved. I even tried changing the data type manually in MySql Workbench. Still Entity Framework retrieves only the first 255 symbols from the database.  I tried [StringLength(65635)] and [MaxLength(65635)] still no luck. 

But when I use fluent API with the following code
`entity.Property(p => p.Body).HasColumnType("text");`
It seems to work. Why aren't data annotations working ? I don't want to mess with the fluent API.

**Comment by ajcvickers** [comment]
@firedeepan The MySql provider seems to have issues with data annotations. One such bug is here: https://bugs.mysql.com/bug.php?id=84423

This case is different but probably has the same root cause. Either way, I would file a new issue on the MySql bug tracker.

**Comment by ajcvickers** [comment]
@firedeepan Also, you might want to try a different MySql provider. I can't say which will work best, but others have had luck switching. See https://docs.microsoft.com/en-us/ef/core/providers/ for a list of the ones we are aware of.
