### ISSUE TITLE
RequiresBufferingExpressionVisitor is too agressive

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#8147]
`RequiresBufferingExpressionVisitor` marks queries as requiring buffering even if the `EF.Property` calls are not referring to shadow properties or the shadow properties from referenced entity types are not used in materialization.

**Comment by anpete** [comment]
> or the shadow properties from referenced entity types are not used in materialization.

The shadow properties may be accessed from anywhere during a query and such accesses are unrelated to materialization - The whole query may be in terms of ValueBuffers.

The first point is fair, though; should be trivial to fix.

**Comment by smitpatel** [comment]
We do entity equality rewrite which would convert `entityType != null` to `EF.Property(entityType, PK) != null)`. Here PK can be shadow/non-shadow either. When we bind this through via query buffer we guard against entityType being null. If we stop using QueryBuffer then we have to make this a member access which is not null safe and we have no easy way to make it null safe.

Removing from milestone if this provides us enough value to go through making bigger changes in binding.

**Comment by smitpatel** [comment]
We removed QueryBuffer.
