### ISSUE TITLE
Custom single navigation property name

### ISSUE THREAD

**Issue by Zonciu** [dotnet/efcore#8149]
### Sql log and error message
The navigation property **User.Profile.Id** appear in sql as **[u].[ProfileId]**
```
Exception message:
SELECT TOP(2) [u].[id], [u].[account], [u].[passwd], [u].[ProfileId], [p].[fk_user_id], [p].[email], [p].[name]
FROM [user] AS [u]
LEFT JOIN [profile] AS [p] ON [u].[ProfileId] = [p].[fk_user_id]
WHERE [u].[id] = 5
An exception occurred in the database while iterating the results of a query.
System.Data.SqlClient.SqlException: 列名 'ProfileId' 无效。
```

### Code
```c#
 public class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        { }

        public DbSet<User> User { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(
                entity =>
                {
                    entity.ToTable("user");
                    entity.HasKey(e => e.Id).HasName("id");
                    entity.Property(e => e.Id).HasColumnName("id").IsRequired();
                    entity.Property(e => e.Account).HasColumnName("account").IsRequired();
                    entity.Property(e => e.Password).HasColumnName("passwd").IsRequired();
                    entity.HasOne(b => b.Profile).WithOne();
                });

            modelBuilder.Entity<UserProfile>(
                entity =>
                {
                    entity.ToTable("profile");
                    entity.HasKey(e => e.Id);
                    entity.Property(e => e.Id).HasColumnName("fk_user_id").IsRequired();
                    entity.Property(e => e.Name).HasColumnName("name").IsRequired();
                    entity.Property(e => e.Email).HasColumnName("email").IsRequired();
                });
        }
    }

    public class User
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public UserProfile Profile { get; set; }
    }

    public class UserProfile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
```

When I rename UserProfile.Id into UserProfile.UserId, it works fine, looks like it is related by property name, how to custom the navigation property name by using the Fluent API ?

#### UserProfile.Id => UserProfile.UserId
Correct sql
```
SELECT TOP(2) [u].[id], [u].[account], [u].[passwd], [p].[fk_user_id], [p].[email], [p].[name]
FROM [user] AS [u]
LEFT JOIN [profile] AS [p] ON [p].[fk_user_id] = [u].[id]
WHERE [u].[id] = 5
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017 26403.3

**Comment by ajcvickers** [comment]
@Zonciu The association between the two entity types requires a foreign key in the database. EF uses conventions to determine which property to use as the FK. The property "UserId" matches this convention and so is used as the FK--because the other entity type is called "User". The property "Id" does not match, and so is not used as the FK. In this case, EF creates a "shadow property" for the FK and uses that instead. A shadow property is a property managed by EF in the model but not in your CLR types. This property is called "ProfileId", since it was created for the Profile relationship.

Here are the relevant parts of the documentation:

https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties
https://docs.microsoft.com/en-us/ef/core/modeling/relationships

**Comment by Zonciu** [comment]
@ajcvickers How to custom the FK name? Or it must be named "UserId"？

**Comment by smitpatel** [comment]
If you want to use different FK property then what EF matches by convention then you need to use fluent API to explicitly specify it. Following in the docs describe how to use `HasForeignKey` to define which property to use as FK property. https://docs.microsoft.com/en-us/ef/core/modeling/relationships#one-to-one
