### ISSUE TITLE
Use Type FullName for Discriminator instead of Type Name

### ISSUE THREAD

**Issue by mgildea** [dotnet/efcore#8153]
I guess this is more of a question....

Is there a reason why EF uses Type.Name instead of Type.FullName for the Discriminator column value?  

In my opinion using the type fullname makes the data more explicit and usable when potentially querying records outside of EF and/or using some type of factory pattern.

In several projects I have found it helpful to include a "Type CD" property to store the fullname when persisting objects with the same name from different namespaces (which feels redundant).

**Comment by ajcvickers** [comment]
@mgildea We will discuss in triage, but it seems like the convention we have for discriminators is a good balance of readability while not being overly verbose. You can always configure your discriminators to anything you want using the API. See https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance
