### ISSUE TITLE
Context-wide flag for Add/Attach/Update behavior

### ISSUE THREAD

**Issue by MarcoLoetscher** [dotnet/efcore#8156]
In the future we made add a context-wide flag to modify this behavior (https://github.com/aspnet/EntityFramework/commit/82b0c44cabc2fa1d0909d11a95b179a558e50355).
I can't find this flag. Is this issues tracked?

**Comment by ajcvickers** [comment]
@MarcoLoetscher We don't have any plans to add that flag. The behaviors that we ultimately landed on seem to be working out well. Can you give some more complete details of what you are trying to do that would require that flag?

**Comment by MarcoLoetscher** [comment]
Suppose I have 100 blogs and each blog contains 10 posts. Now I want to add all the blogs to the context, but without the posts. Because of the better performance, the DbContext.AddRange method would have to be used. Unfortunately the behavior can't be controlled when adding, I have to use "DbContext.Entry(newBlog).State = EntityState.Added;" in a loop to add all the blogs.

**Comment by ajcvickers** [comment]
@MarcoLoetscher Why do you not want to add the Posts?

Regardless:
* If you disable AutoDetectChanges while doing the 100 state changes it should have at least as good, if not better, perf than AddRange.
* Look into the TrackGraph method. It should be pretty easy to use it to only track the Blogs and not the Posts.

**Comment by MarcoLoetscher** [comment]
OK, you're right. This issue can be closed.
