### ISSUE TITLE
Update entity with detached data has odd behavior after savechanges

### ISSUE THREAD

**Issue by sweetwxh** [dotnet/efcore#8169]
I retrive json data from web api and then convert it into an entity. Then update it with context.Update method. When the entity is not query with the same id before update, or just update the entity from query, everything goes fine. Yet if I query it ahead, and call context.Update, it will throw an exception, in the catch scope, I  update the properties through EntityEntry's SetValues method, the data will be updated successfully, but the add operation immediately after updating will not be performed(without exception but no data in database). Any other operations after updating are going alright. But if I make some operation after adding data(such as add a new data again), both operation succeed.

### My test code:

```c#
            using (var context = new StudyContext())
            {
                //query data from database
                var data = context.Department.FirstOrDefault(e => e.Id == Guid.Parse("72c36b62-a085-d5db-bab6-a0314987abcf"));

                //simulate data from web api
                var simData = new Department
                {
                    Id = Guid.Parse("72c36b62-a085-d5db-bab6-a0314987abcf"),
                    Name = "T6",
                    ParentId = Guid.Parse("68b39117-37b4-4d6b-9281-7a904dbfc0c3"),
                    LastUpdate = DateTime.Now,
                    CreationDate = DateTime.Now
                };

                var entry = context.Entry(simData);

                try
                {
                    //if data was tracked, here will throw exception
                    context.Update(simData);
                }
                catch (InvalidOperationException)
                {
                    //update properties
                    entry =
                        context.ChangeTracker.Entries<Department>().FirstOrDefault(e => e.Entity.Id == simData.Id);
                    entry?.CurrentValues.SetValues(simData);
                }

                //update successfully
                context.SaveChanges();


                var emp = new Employee
                {
                    Id = Guid.NewGuid(),
                    Name = "Test Insert",
                    DepId = Guid.Parse("702b93b4-b7ac-6cc6-5139-12643ffda37d")
                };

                var b = context.Add(emp);
                //no data will be inserted into database, and only add operation will not be executed
                context.SaveChanges();

                //if there has other operation after adding, both operation will be executed
                //var d2 = context.Employee.FirstOrDefault();
                //d2.Name = "Change";
                //context.Update(d2, true);
            }
```
I'm wondering wether this is a bug or wrong operation?

### Further technical details
EF Core version: 1.1.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSql
Operating system:  Windows 10
IDE: Visual Studio 2017

**Comment by cdie** [comment]
@sweetwxh Have you try a context.ChangeTracker.DetectChanges() before to see if something changed ? 
Did you disable AutoDetectChangesEnabled within your context because of your merge system ? (it happens to me, I've found it a lot of time after ...)

**Comment by ajcvickers** [comment]
@sweetwxh Rather than creating a new instance, if the entity already exists, then assign values to the properties of that instance. EF will then detect changes appropriately and make an update call. If the entity doesn't exist, then EF will insert it. Something like this:
```C#
//query data from database
var data = context.Department.FirstOrDefault(e => e.Id == Guid.Parse("72c36b62-a085-d5db-bab6-a0314987abcf"));

if (data == null)
{
    data = new Department { Id = Guid.Parse("72c36b62-a085-d5db-bab6-a0314987abcf") };
    context.Add(data);
}

data.Name = "T6";
data.ParentId = Guid.Parse("68b39117-37b4-4d6b-9281-7a904dbfc0c3");
data.LastUpdate = DateTime.Now;
data.CreationDate = DateTime.Now;

//update successfully
context.SaveChanges();
```
