### ISSUE TITLE
Running the benchmark tests - a few questions

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#8170]
I have investigated running the benchmark tests against the SQL CE provider.

Initially I just wanted to run the SQL Server tests on my own localdb instance.

I have noted the following:
- You must set runIterations": true in the config.json file in the test project to actually enable running the benchmark tests (which makes sense)
- You must manually create the "Benchmarks" database according to the setting in the "resultDatabases" key in config.json (and you can report results to multiple databases) - it looks like failure to save summary to the database disappears in cyberspace (when running via TestDriven)
- You must restore an Adventureworks2014 to the instance in the "benchmarkDatabase" value in config.json

Q1: Do you have any tools/templates for consuming/presenting the data in the Runs table? (Excel, RDL file or similar) ?
Q2: What is the preferred way of executing the "tests" ? (I use TestDriven)

**Comment by ErikEJ** [comment]
**Notes about changes required to the Benchmarks.EF6 project in order to use the EntityFramework.SqlServerCompact provider**

1: Created a Adventureworks2014.sdf file and added to the project

2: Added the EntityFramework.SqlServerCompact Nuget package

- csproj changes:
````
  <ItemGroup>
    <None Remove="AdventureWorks2014.sdf" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="AdventureWorks2014.sdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework.SqlServerCompact" Version="6.1.3" />
`````
3: Modified Fixture and DbContexts:
`````
         public AdventureWorksContext(string connectionString)  : base(connectionString)
         {
              Database.SetInitializer<AdventureWorksContext>(null);
         }
 
     public class AdventureWorksFixture
     {
         public static AdventureWorksContext CreateContext() 
             => new AdventureWorksContext(ConnectionString);
        public static string ConnectionString { get; } = $@"Data Source=AdventureWorks2014.sdf;";
     }

(OrdersFixture):
     _connectionString = $@"Data Source={databaseName}.sdf;";
`````
4: Added DbConfiguration class:
`````
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.SqlServerCompact;
    using System.Data.SqlServerCe;
    public class SqlCeConfiguration : DbConfiguration
    {
        public SqlCeConfiguration()
        {
            SetExecutionStrategy("System.Data.SqlServerCe.4.0", () => new DefaultExecutionStrategy());
            SetProviderFactory("System.Data.SqlServerCe.4.0", new SqlCeProviderFactory());
            SetProviderServices("System.Data.SqlServerCe.4.0", SqlCeProviderServices.Instance);
        }
    }
`````
5: Modified Model and test to match SQL CE enigine limitations:
`````
   // iso dbo.Products, no schemas in SQLCE
   .SqlQuery("SELECT * FROM Products")

  // only in and bigint can be IDENTITY with SQLCE
   public int DepartmentID { get; set; }
`````

**Comment by divega** [comment]
@ErikEJ 

Q1: We have a Web-based dashboard that @rowanmiller put together. The code isn't public but I don't think there is a strong reason not to make it public (**we should discuss this in triage**).

Q2: You can use anything, but obviously anything running in the machine at the same time as the benchmarks will affect the quality of the results :smile: We run our benchmarks in a CI agent on dedicated hardware. 

Good to know you were able to make the benchmarks work with SQL CE. Regarding the changes that required, if you happen to have any insights around things we could refactor to make it easier for the benchmarks to work with additional providers, feel free to send a PR.

**Comment by ajcvickers** [comment]
@divega to create anew issue about making the dashboard source publicly available.

**Comment by divega** [comment]
Closing since I believe we have answered the questions. @ErikEJ please let us know otherwise and feel free to reactivate. Also create #8285 to track making the Web UI public.
