### ISSUE TITLE
Cross-context transacted SaveChanges

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#8190]
It would be nice to have a convenient way to save changes in multiple contexts and have them all wrapped in a single transaction. Like this:

static public async void SaveChangesAsync(  this IList<T> contexts) where T: DbContext 
{
....
}

To do this, one needs an easy way to have the contexts all share a single connection. 

There is a way to do it, explained in https://docs.microsoft.com/en-us/ef/core/saving/transactions, but this is not very convenient (and doesn't provide a lot of flexibility in configuring context options other than the shared connection).

**Comment by ajcvickers** [comment]
@sjb-sjb To have multiple contexts that share a single connection, the connection can be passed to UseSqlServer, or the equivalent method for the other providers. The transaction APIs can then be used to create a new the same transaction across all contexts. This requires some orchestration across the app which wouldn't be much different in the method signature you suggest, so at this time we don't think we will implement anything on top of what we already have.
