### ISSUE TITLE
Please consider GraphEngine.IO

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/efcore#8202]
I would love to be able to use EF CORE with GraphEngine.IO as the backend store for large graphs

**Comment by ajcvickers** [comment]
@grahamehorner Thanks for showing an interest in this. We are not planning to implement this provider, but we would be happy to answer questions, etc. for anybody attempting to do this as an open source project. We would also value feedback on any broken abstractions or areas that are difficult to implement, and we will consider changing the core code to help in these areas.
