### ISSUE TITLE
Generate models using T4 from Database project directly

### ISSUE THREAD

**Issue by octocat-mona** [dotnet/efcore#8225]
Using an `.edmx` it is currently possible to generate models by clicking `Update Model from Database`.
It would be nice if it could link to a database project directly instead, is that possible?

### Further technical details
IDE: Visual Studio 2017

**Comment by ErikEJ** [comment]
Is this a EF6 question? In that case, you can do something like that with my SQL Toolbox extension

**Comment by kpstolk** [comment]
Yes indeed, I did look at EF Core but couldn't find if it is any different from EF6.

Is this the [SQL Toolbox extension](https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox) you mentioned?
And is it different when using EF Core?

Thanks!

**Comment by ajcvickers** [comment]
@kpstolk This repository is for Entity Framework Core issues. For EF6 issues, please use https://github.com/aspnet/EntityFramework6

That being said, we have investigated integration with database projects in the past but currently have no plans to implement this.

**Comment by kpstolk** [comment]
@ajcvickers Sorry for posting in the wrong project, guess will look at the Toolbox extension for now, but this feature would be useful I think to have!

**Comment by ErikEJ** [comment]
@kpstolk My SQLite Toolbox (yes, correct link) only supports EF6 with that particular feature corrently.
