### ISSUE TITLE
Child relationships lose reference after SelectMany in query

### ISSUE THREAD

**Issue by gsGabriel** [dotnet/efcore#8228]
Hello,

I need a help of us again :D...

I am making an query where it has three levels ... One Users has many Groups that have many SubGroups. My code is follow:

```c#
DbContext.Set<TbUsers>().AsNoTracking().Include(x => x.TbGroups).ThenInclude(x => x.TbSubGroups).SelectMany(x => x.Groups)
```
With the above code I can not get the SubGroups reference in the Groups entity, however if I use the code below I can access the SubGroups entity:

```c#
DbContext.Set<TbUsers>().AsNoTracking().Include(x => x.TbGroups).ThenInclude(x => x.TbSubGroups).ToList()
```

I need to use SelectMany because I will filter the SubGroups data of the existing users in my database.

In Entity Framework 6 this problem did not exist and child relationships are returned with no problem even with SelectMany.

Would anyone have any idea how to solve this problem?

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/querying/related-data#ignored-includes

**Comment by gsGabriel** [comment]
Hmmm I understand, so I have to use Include after modifying the query? Would it be this? Like this...

```c#
DbContext.Set<TbUsers>().AsNoTracking().Include(x => x.TbGroups).ThenInclude(x => x.TbSubGroups).SelectMany(x => x.Groups).Include(x => x.TbSubGroups)
```
Thanks @smitpatel
