### ISSUE TITLE
Query: consider non-generic version of EF.Property() method for dynamic query generation scenarios

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8232]
Dynamic generation of queries (e.g. adding filters, sort order or even projections to a query without knowing the names and the types of the properties at compile time) requires dropping down to building LINQ expressions by hand or using libraries that help with building them. This is often an order of magnitude harder than understanding regular LINQ queries.

In many of those cases `EF.Property<T>()` can help enable the scenario without jumping off the cliff: Currently we know it helps if the name of the property is not known. We believe it can help more when the type of the property is not known as well. E.g. currently `EF.Property<object>(entity, propertyName)` already works in `OrderBy`. 

We could investigate if it already works (or can easily be made to work) in more places, e.g. for equality comparisons in `Where` and if this proves generally helpful, we can consider having a non-generic version of the method that removes the need to specify `<object>`. 

See https://github.com/aspnet/Docs/pull/3214 for examples of the scenarios this could help with.

**Comment by smitpatel** [comment]
EF.Property<object> should be working everywhere in 3.1 pipeline.
