### ISSUE TITLE
Invalid column name

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#8233]
I met bad sql generated by EF 

Bad query generated in situation where 5 nested tables and grouping by 2 columns.
in project I use http://www.telerik.com/ and grouping is done by telerik. I tried to reproduced it without Telerik`s DataSourceRequest (it does grouping) but I cannot reproduce error. I still posting it here because it is still EF to generate query

It is a bit bulky to describe module here so I prepared separate project reproducing issue
http://static.realgrad.ru/WebApplication5.zip

If there is a issue with licence on telerik you can add trial package 
Telerik.UI.for.AspNet.Core.Trial
from 
https://nuget.telerik.com/nuget

here is broken query
I marked problem with comment
```
SELECT [t].[MeterDataId], [t].[Date], [t].[MeterId], [t].[Value], 
[t].[Value2], [t].[Value3], [w.Meter.Client.Apartment.Block].[BlockId], 
[w.Meter.Client.Apartment.Block].[Alias], [w.Meter.Client.Apartment.Block].[CompanyId], 
[w.Meter.Client.Apartment.Block].[EndService], [w.Meter.Client.Apartment.Block].[Entrances], 
[w.Meter.Client.Apartment.Block].[HouseNumber], [w.Meter.Client.Apartment.Block].[InhabitatLocation], 
[w.Meter.Client.Apartment.Block].[InhabitatLocationCalculated], [w.Meter.Client.Apartment.Block].[IsInService],
 [w.Meter.Client.Apartment.Block].[Korpus], [w.Meter.Client.Apartment.Block].[NumberOfApartments],
  [w.Meter.Client.Apartment.Block].[Rayon], [w.Meter.Client.Apartment.Block].[Region], [w.Meter.Client.Apartment.Block].[Search],
   [w.Meter.Client.Apartment.Block].[Sqm], [w.Meter.Client.Apartment.Block].[Square], [w.Meter.Client.Apartment.Block].[Stages], 
   [w.Meter.Client.Apartment.Block].[StartService], [w.Meter.Client.Apartment.Block].[Street], [w.Meter.Client.Apartment.Block].[Stroenie],
    [w.Meter.Client.Apartment.Block].[Town], [w.Meter.Client.Apartment.Block].[UserId], [w.Meter.Client.Apartment.Block.Company].[ShortName], 
	[w.Meter.Client].[FIO], [w.Meter.Client.Apartment.Block.Company].[MeterId], --<==== Here. Where is no MeterId in Company
	[m0].[MeterId], [m0].[Base], [m0].[Base2], [m0].[Base3], [m0].[Base4], [m0].[Brand], [m0].[ClientId], [m0].[MeterType], [m0].[Model], [m0].[SerialNumber], [m0].[StartDate], [m0].[TarifCount], [m0].[Title], [c1].[ClientId], [c1].[Account], [c1].[ApartmentId], [c1].[FIO], [c1].[FirstName], [c1].[LastName], [c1].[Patronymic], [c1].[Sqm], [a0].[ApartmentId], [a0].[BlockId], [a0].[Clients], [a0].[DenaryPhone], [a0].[Entrance], [a0].[Floor], [a0].[MainPhone], [a0].[NonaryPhone], [a0].[Number], [a0].[OctonaryPhone], [a0].[QuaternaryPhone], [a0].[QuinaryPhone], [a0].[Search], [a0].[SecondaryPhone], [a0].[SenaryPhone], [a0].[SeptenaryPhone], [a0].[Sqm], [a0].[Square], [a0].[Stoyak], [a0].[TertiaryPhone], [b0].[BlockId], [b0].[Alias], [b0].[CompanyId], [b0].[EndService], [b0].[Entrances], [b0].[HouseNumber], [b0].[InhabitatLocation], [b0].[InhabitatLocationCalculated], [b0].[IsInService], [b0].[Korpus], [b0].[NumberOfApartments], [b0].[Rayon], [b0].[Region], [b0].[Search], [b0].[Sqm], [b0].[Square], [b0].[Stages], [b0].[StartService], [b0].[Street], [b0].[Stroenie], [b0].[Town], [b0].[UserId], [c2].[CompanyId], [c2].[AccountantPhone], [c2].[DispatcherPhone], [c2].[FullName], [c2].[INN], [c2].[ReceptionPhone], [c2].[ShortName]
FROM (
    SELECT [i2].[MeterDataId], [i2].[Date], [i2].[MeterId], [i2].[Value], [i2].[Value2], [i2].[Value3]
    FROM [MeterData] AS [i2]
) AS [t]
INNER JOIN [Meters] AS [w.Meter] ON [t].[MeterId] = [w.Meter].[MeterId]
INNER JOIN [Clients] AS [w.Meter.Client] ON [w.Meter].[ClientId] = [w.Meter.Client].[ClientId]
INNER JOIN [Apartments] AS [w.Meter.Client.Apartment] ON [w.Meter.Client].[ApartmentId] = [w.Meter.Client.Apartment].[ApartmentId]
INNER JOIN [Blocks] AS [w.Meter.Client.Apartment.Block] ON [w.Meter.Client.Apartment].[BlockId] = [w.Meter.Client.Apartment.Block].[BlockId]
INNER JOIN [Companies] AS [w.Meter.Client.Apartment.Block.Company] ON [w.Meter.Client.Apartment.Block].[CompanyId] = [w.Meter.Client.Apartment.Block.Company].[CompanyId]
INNER JOIN [Meters] AS [m0] ON [t].[MeterId] = [m0].[MeterId]
INNER JOIN [Clients] AS [c1] ON [m0].[ClientId] = [c1].[ClientId]
INNER JOIN [Apartments] AS [a0] ON [c1].[ApartmentId] = [a0].[ApartmentId]
INNER JOIN [Blocks] AS [b0] ON [a0].[BlockId] = [b0].[BlockId]
INNER JOIN [Companies] AS [c2] ON [b0].[CompanyId] = [c2].[CompanyId]
```

**Comment by smitpatel** [comment]
@dvdobrovolskiy - I am not able to get that project to work. Specifically I am getting error ` Unable to resolve 'Telerik.UI.for.AspNet.Core (>= 2017.1.223)' for '.NETCoreApp,Version=v1.1'.`

Can you post a simplified repro, which uses only EF. Also include, your domain classes, dbcontext & most importantly query you are running which is generating above wrong sql.

**Comment by dvdobrovolskiy** [comment]
I mentioned before Telerik.UI.for.AspNet.Core.Trial instead from
https://nuget.telerik.com/nuget

Telerik add grouping to query in some way and this brakes query. Then I add grouping on same column without telerik I got no error

**Comment by smitpatel** [comment]
That nuget feed requires authentication.

**Comment by dvdobrovolskiy** [comment]
Can you please find a time to get telerik`s tral
https://www.telerik.com

Telerik responded with "EF is the one who generate sql not we"

**Comment by smitpatel** [comment]
Can you tell what is the nuget feed url for that package? It should be something like this format
`https://api.nuget.org/v3/index.json`

**Comment by dvdobrovolskiy** [comment]
Hm
I have this
https://nuget.telerik.com/nuget
as source in Nuget package sources

Where I can get this?

**Comment by smitpatel** [comment]
I tried that just now. Again authentication failure. It is some private package which is not accessible to us. Best would be to try and find what is the exact query being used in EF.

**Comment by dvdobrovolskiy** [comment]
It uses telerik.com account authentication .
http://docs.telerik.com/aspnet-mvc/getting-started/nuget-install

Seems like dead end. Will try to roll back to 1.0.0. might be it will help

**Comment by smitpatel** [comment]
There were some issues around choosing the table name in multiple joins. We have fixed it in https://github.com/aspnet/EntityFramework/pull/7691
See issue https://github.com/aspnet/EntityFramework/issues/7220

It is fixed for next release and most likely resolve this error.

Given the error does not produce without telerik, it is doing something to the query & the new query generated is failing to translate correctly. It could be bug in EF (perhaps as mentioned above) but we cannot debug or fix it unless we know what is the query which fails to translate.

**Comment by dvdobrovolskiy** [comment]
Could be. The whole thing telerik does is to add filtering grouping and sorting to EF lambda expression. Hope it will go with release. Sad for now, thnks for help
