### ISSUE TITLE
Query Take and Includes causes related collection to be empty

### ISSUE THREAD

**Issue by Daniel-Glucksman** [dotnet/efcore#8236]
I have the following statement below, for privacy reasons i cannot list the specifics.

    dbcontext
    .AsNoTracking()
    .Where(query)
    .OrderByDescending(d => d.Created)
    .Take(8).
    .Include(c =>xxxxxxxxxxx)
    .ToList()

The results are always more than 8 in varying amounts and some of the referenced included collections are blank, if i remove the take all works well. 

Has anyone encountered a bug with a specific: query, include and take where the results with the take were missing the related collection but without it weren't.

### Further technical details
Entity Framework: 6.1.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@devteamexpress For EF6 issues, please use https://github.com/aspnet/EntityFramework6

Also, for any issue filed there we will need more information on how to reproduce what you are seeing. A complete code listing or project is ideal, but if that's not possible, then at least the shape of the entity types and something that resembles more accurately the query being used.
