### ISSUE TITLE
Why Are There Gaps in IDs?

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#8252]
For some unknown reason my identities are jumping.  Why could that be?  Where do I start to look for why something like this happening?

### Jump 1 Example
![image](https://cloud.githubusercontent.com/assets/14079228/25292209/2e655848-26a3-11e7-8b12-adcf3dba33bb.png)

### Jump 2 Example
![image](https://cloud.githubusercontent.com/assets/14079228/25292219/36a64e36-26a3-11e7-8a96-db09c5077018.png)

### Model
``` c#
[Table("Customers", Schema = "Customers")]
public class Customer : IValidatableObject
{
	public int Id { get; set; }
	...
}
```

### Table Generated from the Migration
``` sql
CREATE TABLE [Customers].[Customers] (
    [Id]                              INT             IDENTITY (1, 1) NOT NULL,
    ...
)

**Comment by smitpatel** [comment]
This stackoverflow questions answers it in detail.
http://stackoverflow.com/questions/14146148/identity-increment-is-jumping-in-sql-server-database

It is the way SqlServer works (on restart) not something specific to EF behavior (which merely uses database values created by SqlServer)

**Comment by wstaelens** [comment]
@smitpatel  Shouldn't this be reported as a bug? As this gives great danger, gaps can grow very quickly, reaching int.maxvalue without having so many items.

I just had the same issue and it affects all my tables now.

related: https://stackoverflow.com/questions/39671899/ids-jumping-up-1000-every-time-i-build-my-app-and-insert-a-new-record
related: https://stackoverflow.com/questions/21563320/why-identity-number-in-ef-jump-to-a-big-number

**Comment by smitpatel** [comment]
@wstaelens - While behavior can cause potential issue like that, the behavior is out of the hands of EF team. We just take SqlServer gives to us. So if you think this is a bug then it should be reported to SqlServer product. 
From EF Core perspective, you can avoid hitting the issue but possibly not using identity. A user defined sequence or some client side value generation code or no value generation could work in EF Core.

**Comment by wstaelens** [comment]
@smitpatel this never happened to us before with regular EF and .NET but it happens now when I'm using EF Core and .NET Core. Strange.

**Comment by spottedmahn** [comment]
>this never happened to us before with regular EF and .NET but it happens now when I'm using EF Core and .NET Core. Strange.

I'm guessing you're using [Sql LocalDb](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-2016-express-localdb?view=sql-server-2017) now and previously you weren't.  Maybe not, just a guess 😊.  

Did you review [the referenced SO post](https://stackoverflow.com/a/39672034/185123)?  @smitpatel

**Comment by wstaelens** [comment]
I'm using SQL Server 2014 Express with SSMS. 
I assume I don't use LocalDB (as it wouldn't be visible in SSMS?)

**Comment by spottedmahn** [comment]
Gotcha, not sure then 🤷‍♂️.

But you can use SSMS and LocalDB:

![image](https://user-images.githubusercontent.com/14079228/53822131-26eafc80-3f3d-11e9-976c-76ec9e86a2b7.png)

**Comment by wstaelens** [comment]
it's not localdb ;-) 
anyway very annoying these gaps.
