### ISSUE TITLE
Create a read-optimized implementation of IModel

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#8258]
This `IModel` will be built after the model is validated and will not have the `ConfigurationSource` or other data used only during model building.

This model will be built by `IModelRuntimeInitializer` and stored in a runtime annotation in case the original model is reused.

To provide the optimized implementations default interface implementations are to be used, see https://github.com/aspnet/EntityFramework/issues/19213

**Comment by AndriySvyryd** [comment]
The relational implementation will also include a read-only database model, which could be reused in Scaffolding and Migrations.
@bricelam, @smitpatel

**Comment by ajcvickers** [comment]
Plan for 3.0 is to make the API changes anyway. That is, the underlying model may not yet actually be different than it is now.

**Comment by ajcvickers** [comment]
Triage: just do the API naming part.
