### ISSUE TITLE
[Unique] Data annotation 

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#8266]
Currently, it's possible to ensure field uniqueness like this:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Model>()
        .HasIndex(m => m.Field)
        .IsUnique();
}
```

I'm not sure about other ways.

My proposition is to add [Unique] data annotation to simplify this process.

**Comment by lajones** [comment]
@midnightstarr There has been a suggestion for an `Index` attribute in the past. I think `Unique` would be part of that. So closing as a dupe of #4050.
