### ISSUE TITLE
Issue many concurrent "Cannot rollback - No transaction is active"

### ISSUE THREAD

**Issue by trinvh** [dotnet/efcore#8286]
I am using EFCore SQLite with SignalR.

When there are many clients connect at the same time, database can not changes (insert/update) anymore, this exception throws: "Can not rollback - No transaction active"

Logs:

`An exception occurred in the database while iterating the results of a query.
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.`

Then

`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.`

After that, when I try to insert or update things:

`Cannot rollback - No transaction is active`

Is there a workaround? This only happens on production with 50 clients+, so it's hard to debug when development. Or any way to check database is busy and hold client connection until the process is finished.

### Steps to reproduce
A client connects with query param that contains its info, then:

- Look into the database, if clientName exists then update its info. Otherwise, add new.
- After connected, client name call GetData() that returns all clients info etc...
- There are about 100 clients connect at the same time.

### Further technical details
EF Core version: 1.0.0-preview2-1-003177
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 7/10 x64
IDE: Visual Studio 2015

**Comment by ErikEJ** [comment]
Why not use a proper, scalable database engine instead - like SQL Server?

**Comment by ajcvickers** [comment]
@trinvh That's a very old version of EF Core. Please update to an RTM version--preferably 1.1.1.

Also, are you ensuring that you don't have the same context instance being accessed by multiple threads concurrently, or making multiple async calls without awaiting each one? The context is not thread-safe and cannot be accessed concurrently by multiple threads.
