### ISSUE TITLE
Include does an inner join and not left join

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#8287]
I have:
```

TableA(ID, IDTableB, IDTableC, IDTableD)
TableB(ID, ...)
TableC(ID, ...)
TableD(ID, ...)
```
In TableA, IDTableB can't be null, IDTAbleC and IDTableD can be null both.

When I am trying to get the related entities I do this:

```
dbContext.TableA
.Include(x => x.TableB)
.Include(x => x.TableC)
.Include(x => x.TableD)
.ToListAsync();
```

I use the same way in EF6 and EF Core, but I get differents queries.

In EF6 I get this:

```
inner join TableB
left join TableC
left join TableD
```

And in EF Core I get:

```
inner join TableB
inner join TableC
inner join TableD
```

In EF6 I get the exptected results, all the rows from TableA and all the rows from TableC and TableD if there are.

However, in EF Core, how all the joins are inner joins, I don't get all the expected records because it is posible that some record in TableA has not related records in TableC or TableD, because IDTableC and IDTAbleD allow nulls.

So I would like to know if this is the exptected behaviour of EF Core or not, and if it is the expected behaviour, how I could set the left join like EF6 does?

Thanks.

EDIT: I have noticed that in another cases the query is splitted in two parts, one for get the parent rows and later a second query that gets the children rows and later EF populate the navigation properties. In this cases works as expected, because I always get the parent rows, no matter if it has childrens or not. But in this particular case, that do it all in a single query, it uses inner join in all the includes and think that it is not correct.

**Comment by maumar** [comment]
Can you share the code listing for entities and DbContext? (in particular contents of OnModelCreating method). Also, which version of EF Core are you using? We will generate LEFT JOIN for includes if we think the navigation is optional - my guess is, the entities are configured is such a way that the navigation (from EF Core perspective) is required.

**Comment by ComptonAlvaro** [comment]
Thanks for the advise. I checked my mapping and I can see that I had .IsRequiered() in this properties. If I comment this option, it is work as I expect.

So when I do the scaffolding, it sets as IsRequiered() when the relationship allows null values, so it not wouldn't be better don't set it as IsRequired()?

**Comment by smitpatel** [comment]
@ComptonAlvaro - For the thing you are seeing with scaffolding is result of https://github.com/aspnet/EntityFramework/issues/7956
