### ISSUE TITLE
AddEntityFramework(IConfiguration) should enable service replacement from Configuration

### ISSUE THREAD

**Issue by HaoK** [dotnet/efcore#829]
We are enabling service replacement across frameworks by flowing the application's configuration into an instance of Microsoft.Framework.DependencyInjection.ServiceDescriber. We should do it in EF as well to allow service replacement using a consistent pattern.

More context here: https://github.com/aspnet/SignalR-Server/pull/39

**Comment by divega** [comment]
Service replacement is cut.
