### ISSUE TITLE
Benchmarks: Some benchmarks have unstable results

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8299]
Some of our benchmarks produce considerably unstable results. For this reason they tend to show up in trend reports as possible regressions. Among others:

- SimpleQueryTests.LoadAll
- SimpleQueryTests.Where
- SimpleQueryTests.OrderBy
- SimpleQueryTests.Projection
- SimpleQueryTests.ProjectionAcrossNavigation
- SimpleQueryTests.SkipTake
- SimpleQueryTests.Include (only observed on .NET Framework, Tracking Off - Async (1 query))
- FixupTests.QueryChildren
- InitializationTests.BuildModel_AdventureWorks
- NavigationsQueryTests.PredicateAcrossOptionalNavigationAllResults
- NavigationsQueryTests.PredicateAcrossOptionalNavigationFilteredResults
- RawSqlQueryTests.SelectAll
- RawSqlQueryTests.SelectComposed
- RawSqlQueryTests.SelectParameterized
- RawSqlQueryTests.StoredProcedure

Example:

![image](https://cloud.githubusercontent.com/assets/1253414/25464572/fa8cb350-2ab1-11e7-91f8-7b11ea645213.png)

We can try to understand if whether increasing the number of iterations or adjusting how we filter outliers could help reduce the impact of noise.

**Comment by divega** [comment]
I noticed that in many of the benchmarks the EF Core results are unstable while the EF6 results are very stable, which makes me suspect the spikes could be a symptom of something EF Core is doing differently.

**Comment by ajcvickers** [comment]
@divega to look for recent examples

**Comment by ajcvickers** [comment]
@divega Punt to 3.0?

**Comment by ajcvickers** [comment]
Closing this as we are in the process of moving to a different perf infrastructure.
