### ISSUE TITLE
Provider - How to override boolean query

### ISSUE THREAD

**Issue by tomerpeled** [dotnet/efcore#8306]
What will be the easiest and correct way to override a boolean query expression from using '1' to use 'true'? (In EFCore provider code)

For example:
`ctx.Players.Where(p => p.IsActive).FirstOrDefault();

`
Currently it generates:
```
SELECT *
FROM Players AS p
WHERE p.IsActive = 1
```

And I would like it to generate:
```
SELECT *
FROM Players AS p
WHERE p.IsActive = true
```

Thanks,
Tomer

**Comment by ErikEJ** [comment]
I think you can override:

            protected override void GenerateLiteralValue(StringBuilder builder, bool value)

In your implementation of RelationalSqlGenerationHelper

**Comment by tomerpeled** [comment]
Great! That works :)

Thanks
