### ISSUE TITLE
Query: Clean-up logic around RemoveConvert

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#8318]
Currently the way we use RemoveConvert in some of the visitors is not very robust. We sometimes remove converts when visiting expression but not bring it back, which can lead to compilation errors for some scenarios where converts are explicitly added by customer.

At the moment we have helper methods for creating EF.Property, member access and assignment that compensates for discrepancies, however ideally we should correct much earlier. 

This is problematic to do, because in some places we don't retain information about the converts, e.g. 
MemberAccessBindingExpressionVisitor.GetPropertyPath returns list of IPropertyBase as well as root qsre, but not the converts that are needed along the path, so when processing:
```((B2)((A2)a).b).c```

we get [a] (qsre), A2.b (IProperty), B2,c (IProperty), but the information about converts is lost.

Another issue is that sometimes we construct query models (e.g. for collection navigations) and use the qsre in the selector (referencing MainFromClause, which is EntityQueryable) later on. Again, if the collection is a derived class, we should convert that qsre to the right type - currently we don't.

**Comment by AndriySvyryd** [comment]
@smitpatel Fixed/not needed?

**Comment by smitpatel** [comment]
Not needed.
