### ISSUE TITLE
EnsureCreated when multiple DbContext in one database

### ISSUE THREAD

**Issue by rodchenkov** [dotnet/efcore#8320]
Hi All

I have integration test project and I need to create test database based on 3 DbContexts.

My code:
`
identityDbContext.Database.EnsureCreated();
configurationDbContext.Database.EnsureCreated();
persistedGrantDbContext.Database.EnsureCreated();
`

As a result only tables for first DbContext (identityDbContext) created.

Can you please provide solution on how to solve this?

**Comment by ajcvickers** [comment]
Dupe of #2874 (See comments at the end for what to do instead.)
