### ISSUE TITLE
Query: Exploratory testing for LinqKit

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#833]
LinqKit features such as AsExpandable() and PredicateBuilder are designed to work well with different LINQ providers but it would be good to make we aren't doing anything in EF7 that prevents them from working. We can then consider incorporating similar functionality or an extensibility point that makes it easier to use the features of AsExpandable() without having to call it explicitly.

**Comment by nocommonsense** [comment]
Hi @divega ,

Has anyone from the EF team managed to start taking a look at LinqKit compatibility with EF Core? I have begun migrating parts of a web app that makes use of LinqKit's 'And', 'Or' and 'Expand' helpers and can see noticeable differences in the SQL that is produced compared to EF6. In addition, Eager loading does not appear to be producing any SQL to bring in the relations - comparing this to EF6 which produces a LEFT OUTER JOIN when carrying out the same code.

Thanks,

Ian.

**Comment by StefH** [comment]
A new Linqkit version has been created which supports the latests EF Core version. Can someone verify if this version works as expected / solves this issue?
