### ISSUE TITLE
Tools: Better support for .NET Standard projects

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#8349]
Since .NET Standard 2.0 projects are broken (#8344), we can take this opportunity to rework how we handle .NET Standard class library projects in the tools when you don't specify a startup project.

The heart of the issue is that .NET Standard is an abstract framework and doesn't contain all of the assets necessary to execute assemblies.

One way to fix this is to, behind the scenes, make the project target .NET Core. Then after we restore and build, all of the assets we need to execute will be present.

**Comment by bricelam** [comment]
We may be able to leverage `GenerateDeps.proj` which is part of the .NET Core SDK.

**Comment by andymac4182** [comment]
What is missing from a netstandard class library project that is required for EF Core?

**Comment by bricelam** [comment]
Primarily the native libraries like sni.dll for SqlClient and sqlite3.dll for SQLite. But it's anything in the NuGet package graph that uses the bait-and-switch pattern (i.e. referencing a stub--the bait--on netstandard, but switching to a framework-specific implementation when installed into an app).

**Comment by ajcvickers** [comment]
Closing this in favor of #8452.
