### ISSUE TITLE
"dotnet ef migrations add" does not work with x64 only project in VS2017 / dotnet ver 1.1.0

### ISSUE THREAD

**Issue by keflem** [dotnet/efcore#8352]
I have a project that only has x64 targets and is targeting net452.  This is due to dependencies on Service Fabric that only comes with x64 packages on .Net framework platform so I cannot target the .Net Standard or .Net Core frameworks.    

Relevant parts of the csproj:

 ```xml
    <TargetFramework>net452</TargetFramework>
  
 ...

 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
 
 ...

    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" PrivateAssets="All" />	

...

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

```
When running "dotnet ef migrations add MyMigration" the following error occurs:

C:\Program Files\dotnet\sdk\1.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Assets file '[Path to file]\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.5.2/win7-x86'. Ensure you have restored this project for TargetFramework='net452' and RuntimeIdentifier='win7-x86'. 

It is not restored with win7-x86 because the build is only for win7-x64.  

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
You need to add the following to your `*.csproj` in order to get NuGet to restore for both x86 and x64.
```XML
<PropertyGroup>
  <RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers>
</PropertyGroup>
```

**Comment by keflem** [comment]
This still does not work.  If you have an assembly that only references x64 (in this case Azure Service Fabric) you get a different error. 

>dotnet ef migrations add MyMigration

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.33
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not load file or assembly 'System.Fabric, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format.
Configuring for localhost databaseSystem.BadImageFormatException: Could not load file or assembly 'Microsoft.ServiceFabric.Services, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Microsoft.ServiceFabric.Services, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.get_DeclaringType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.<>c__DisplayClass17_0.<ContainsForeignMigrations>b__0(TypeInfo t)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ContainsForeignMigrations(String migrationsNamespace)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.ServiceFabric.Services, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase =<removed>
 LOG: Initial PrivatePath = NULL
Calling assembly : <removed>
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: <removed>
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.ServiceFabric.Services, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Could not load file or assembly 'Microsoft.ServiceFabric.Services, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by bricelam** [comment]
So it's an x64-only project? Try adding the following to your `*.csproj`.
```XML
<PropertyGroup>
  <Platform>x64</Platform>
</PropertyGroup>
```

**Comment by keflem** [comment]
That works.  I had a condition on my platform since our builds always do a x64 release.

```` xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
````
But my guess is the *dotnet ef migrations* command does not set the Platform to be x64.

For those who encounter this in the future, this is what my full config settings look like.

**Correct csproj settings**

```` xml
<PropertyGroup>
    <RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers>
    <Platform>x64</Platform>
</PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
</ItemGroup>

<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
</ItemGroup>
````

**Comment by bricelam** [comment]
> my guess is the dotnet ef migrations command does not set the Platform

It just calls `msbuild` on the project. No properties will be set.
