### ISSUE TITLE
Feature Request: New Entity Type - SecureString

### ISSUE THREAD

**Issue by VAchris** [dotnet/efcore#8355]
[SecureString (MSDN)](https://msdn.microsoft.com/en-us/library/system.security.securestring(v=vs.110).aspx) represents text that should be kept confidential, such as by deleting it from computer memory when no longer needed.

I would like to request EF's ability to map to the type SecureString instead of just String.

**Comment by ajcvickers** [comment]
@VAchris We discussed this and we're not going to add built-in support, but custom type mapping/conversions should allow it to be supported--this is tracked by #242. Closing this as a dupe of that.

We are interested in knowing how you would make use of SecureString--what issue specific issue would it solve for you?
