### ISSUE TITLE
Varchar column sending unicode

### ISSUE THREAD

**Issue by mk9753** [dotnet/efcore#8370]
I think I'm coming across something related to this [issue](https://github.com/aspnet/EntityFramework/issues/4686)...
There is a column set up as varchar:
`modelBuilder.Entity<Quotes>().Property(s => s.StripInsuredCorporationName).HasColumnType("varchar(500)");`

Query:
`var tmp = (from q in context.Quotes where (q.StripInsuredCorporationName.Contains(strippedName)) select new { q.QuoteID });`

The resulting SQL:
`SELECT [q].[QuoteID] FROM [tblQuotes] AS [q] WHERE CHARINDEX(N'Test', [q].[StripInsuredCorporationName]) > 0`

Since the column is defined as varchar, not sure what is causing the N to be there.
Thanks

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Win 10
IDE: VS 2017

**Comment by smitpatel** [comment]
Added https://github.com/aspnet/EntityFramework/issues/4978#issuecomment-298977909 to existing issue. Closing as dupe.
