### ISSUE TITLE
Query: translate SequenceEqual on byte[] (and other types?)

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#8376]
We should be able to translate Enumerable.SequenceEqual for some types.
In case of byte[] they translate directly to comparison on sql

**Comment by smitpatel** [comment]
dupe of #5806 for byte[]

**Comment by ajcvickers** [comment]
Notes from triage: this bug is really about deep comparisons on arrays, etc. when comparing them inside the in-memory database. Decided that this should always be a deep comparison, done by re-writing the expression, and we should consider using IStructuralComparable. Closing as dupe of #5806.
