### ISSUE TITLE
GetDbConnection in .Net Standard

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#8404]
I am writing Extension library for EFCore and tried to made it in .Net Standard 1.6 but it seems that one function I need is missing:
**GetDbConnection** from _Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions_
I use it like this:
`var connection  = (SqlConnection)context.Database.GetDbConnection()`;

Is there any way around this, or do I have to wait for Standard 2.0?

I have first asked the [Question](https://github.com/dotnet/standard/issues/329#issuecomment-299892685) on _Standard_ Repos but was advised to file it here.

**Comment by svick** [comment]
[That method is in the `Microsoft.EntityFrameworkCore.Relational` 1.1.1 package](http://dotnetapis.com/pkg/Microsoft.EntityFrameworkCore.Relational/1.1.1/netstandard1.3/doc/Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions/GetDbConnection(Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade)) and supports .Net Standard 1.3 (just like the rest of EF Core).

Are you sure you're referencing that package and that you have `using Microsoft.EntityFrameworkCore;` in your C# file?

**Comment by borisdj** [comment]
Thx for clarifying that it is already supported.
It was probably some mess with packages since I installed and removed several of them more than once.
But now I made completely new project and library, added there this package and all is resolved.
So this issue can be closed.
