### ISSUE TITLE
Query: consider using SELECT TOP (100) PERCENT when composing over a subquery with ORDER BY

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8407]
There are some situations in which in the query pipeline tries to lift a subquery but the presence of an ORDER BY blocks it, hence forcing client eval and splitting the query. 

We would need do a survey of the behavior across databases (either the behavior or the workaround could be SQL Server specific).

**Comment by divega** [comment]
@anpete I created this based on our conversation today. Please make any necessary edits.

**Comment by Mardoxx** [comment]
Got any further insight on this? I'm really struggling to understand why the docs say:

>`SELECT` statements passed to this method [`.FromSql()`] should generally be composable: [...] This means that the SQL passed should not contain any characters or options that are not valid on a subquery, such as:
> - On SQL Server, an ORDER BY clause that is not accompanied of TOP 100 PERCENT in the SELECT clause

**Comment by divega** [comment]
@smitpatel can we close this now?

**Comment by smitpatel** [comment]
We carry the ordering out and preserve it. And we remove inner ordering to allow composition.
