### ISSUE TITLE
Is it possible to declare a relationship as eager loaded?

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/efcore#8425]
I know you can use `.Include()` on a query to eager-load a related object.
What I want to do, though, is declare a relationship so that it *always* eager-loads, e.g. If my `Thing` object must *always* have a related `OtherThing` that I want to have access to:
```
modelBuilder.Entity<Thing>(entity =>
    entity.HasOne(t => t.OtherThing)
        .WithMany(o => o.Things)
        .HasForeignKey(t => t.OtherThingId)
        .EagerLoad(true); // or something like that
```
Is it possible to achieve this somehow?

**Comment by anpete** [comment]
See #1985, #2953
