### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by im1dermike** [dotnet/efcore#8426]
I have the following query:

    var query = from f in context.Freezers
            from p in f.Products.Where(x => x.IsActive).DefaultIfEmpty()
            select new
            {
                Freezer = f,
                Products = p
            };
    var freezer = query.FirstOrDefault()

When this executes, I get the following exception:

> Index was out of range. Must be non-negative and less than the size of the collection.

Seems like a bug...

**Comment by anpete** [comment]
@im1dermike Can you post the stack trace?

**Comment by im1dermike** [comment]
>    at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
>    at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteSelectManyNavigationsIntoJoins(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations, AdditionalFromClause additionalFromClauseBeingProcessed)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
>    at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
>    at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>    at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
>    at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
>    at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
>    at MyCompany.MyProduct.DataAccess.Repositories.FreezerRepository.GetById(Int32 id, Boolean includeActiveProducts) in C:\Development\MyCompany\MyCompany.MyProduct\MyCompany.MyProduct.DataAccess\Repositories\FreezerRepository.cs:line 71
>    at MyCompany.MyProduct.Business.EntityRetriever.GetFreezer(Int32 id, Boolean includeActiveProducts) in C:\Development\MyCompany\MyCompany.MyProduct\MyCompany.MyProduct.Business\EntityRetriever.cs:line 122
>    at MyCompany.MyProduct.Business.Managers.FreezerManager.GetFreezerById(Int32 id) in C:\Development\MyCompany\MyCompany.MyProduct\MyCompany.MyProduct.Business\Managers\FreezerManager.cs:line 53
>    at MyCompany.MyProduct.Web.ApiControllers.MyCompany.FreezersController.GetById(Int32 id) in C:\Development\MyCompany\MyCompany.MyProduct\MyCompany.MyProduct.Web\ApiControllers\MyCompany\FreezersController.cs:line 35
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()

**Comment by maumar** [comment]
@im1dermike which version of EF Core are you using? This looks very similar to #6879 (will be fixed in 2.0.0-preview1 that is about to ship)

**Comment by im1dermike** [comment]
@maumar 1.1.0.  

Is there an ETA?  Will `HasFilter()` ship in that version too?

**Comment by maumar** [comment]
We can't share the exact date, but it will be very soon :) And yes, HasFilter is part of the preview.

**Comment by im1dermike** [comment]
@maumar How can I be alerted when it's released?

**Comment by maumar** [comment]
There will be a blog post here: https://blogs.msdn.microsoft.com/dotnet/

**Comment by im1dermike** [comment]
@maumar Is [this](https://blogs.msdn.microsoft.com/dotnet/2017/05/12/announcing-ef-core-2-0-preview-1/) it?

**Comment by maumar** [comment]
@im1dermike yes
