### ISSUE TITLE
Upgrading to EntityframworkCore.Sqlite 2.0.0 preview-1 causes Android app crashes

### ISSUE THREAD

**Issue by paradisehuman** [dotnet/efcore#8435]
Hi.
When I Upgraded my EFCore.Sqlite 1.1.2 to Ver 2.0.0 preview-1 , my app crashes before deploy. There is no error , there is no any exception!

I want to get rid of this error :

> unauthorized access to “/system/lib/libsqlite.so”

I search a lot in Internet and majority of them said that error would get away by the next EFCore.Sqlite update.

The UPW app runs without any problem with new sqlite update package. The problem is Android. Is there any thing that I must do ?

### Further technical details
EF Core version: 2.0.0 preview-1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
(Also [asked](http://stackoverflow.com/q/43910351/475031) on StackOverflow)

**Comment by bricelam** [comment]
I have no idea what's causing the error. Nothing in EF Core or Microsoft.Data.Sqlite will try to use libsqlite.so. You may want to follow up on [ericsink/SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw), but I suspect he'll say the same thing about his library.
