### ISSUE TITLE
DbContext not found

### ISSUE THREAD

**Issue by maxmantz** [dotnet/efcore#8436]
Hi, 

I'm starting a new .NET Core project with EF Core. I've created the project in VS2017 and installed EnityFrameworkCore.SqlServer from NuGet. Now when I'm trying to create my DbContext like this:

```
public class MyContext : DbContext {

}
```

my VS2017 cannot find the `DbContext` type. What am I doing wrong?

Manually adding a `using Microsoft.Entityframework.Core` doesn't work because the assembly also cannot be found.

**Comment by maxmantz** [comment]
![image](https://cloud.githubusercontent.com/assets/6616421/25950321/d4a33236-365a-11e7-9af9-70ce914eb8c5.png)

FYI this is what my VS2017 looks like.

**Comment by ajcvickers** [comment]
@maxmantz Make sure you have the casing an the dots correct in your using directive: `using Microsoft.EntityFrameworkCore;`

**Comment by maxmantz** [comment]
Thanks for the hint, however I don't believe that this is the issue. VS2017 should give me IntelliSense on the using directive but it doesn't show anything. I also noticed all dependencies in the screenshot are present three times instead of just once. Maybe something is wrong with my NuGet?

**Comment by maxmantz** [comment]
@ajcvickers I just tried typing `using Microsoft.EntityFrameworkCore;` exactly as you've pointed out - sadly it doesn't work.

**Comment by maxmantz** [comment]
Reinstalling VS2017 fixed my issue. Thanks again for your help.

**Comment by slobadx** [comment]
Fixed by closing and reopening **VS2017** in my case.
