### ISSUE TITLE
Microsoft.EntityFrameworkCore.Tools.DotNet in 2.0.0-preview1 fails

### ISSUE THREAD

**Issue by stgeorge** [dotnet/efcore#8444]
I upgraded my project to 2.0.0 preview 1 and one of my csproj file includes the following:

`<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview1-final" />`

This line causes the entire project to fail to compile.

In msbuild output:

`"Unexpected dependency 'xxx.csproj' with no version number.`

In nuget restore output:

`Unable to resolve 'xxx.csproj' for '.NETCoreApp,Version=v2.0'.`

If I take it out, everything works but then I cannot use ef from dotnet.exe...

**Comment by bricelam** [comment]
I think this is a known issue that will be fixed in the next release. The workaround is to run `dotnet restore` on the project instead of letting VS restore packages.

**Comment by ajcvickers** [comment]
@divega We thought in triage that this was in the release notes, but I don't see it there: https://github.com/aspnet/EntityFramework/releases/tag/rel%2F2.0.0-preview1

Assigning to you to follow up getting it there or documenting somewhere else.

**Comment by divega** [comment]
@bricelam @ajcvickers I was not aware of the issue or workaround that should have been in release notes. Given we are for preview2, do we still need to add this or should we close this? If the former, I am happy to edit the release notes of you give me the details.

**Comment by divega** [comment]
Clearing up milestone to get the answer in triage.

**Comment by ajcvickers** [comment]
Closing since we hopefully don't need this for preview2.
