### ISSUE TITLE
Specifying ".IsUnique(false);" is still adding "unique: true" in migrations on EFCore 7 on Linux with MySql

### ISSUE THREAD

**Issue by deepak-khopade-isdr** [dotnet/efcore#8463]
Specifying `.IsUnique(false);` in fluent API to avoid unique index and just to have a normal BTREE index, but still, it's adding `unique: true` in migrations on EFCore 7 on Linux with MySql.

EF Core version: 1.1.1
Database Provider: Pomelo.EntityFrameworkCore.MySql/1.1.1
Operating system: Ubuntu 16.04
IDE: JetBrains Rider and VS CODE

**Comment by ErikEJ** [comment]
This looks like a Pomelo mysql bug, you should report at the Pomelo issue tracker

**Comment by ajcvickers** [comment]
Filed as https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/275
