### ISSUE TITLE
Fluent API method .HasConstraintName<entity, relatedEntity>("FK_name") is not creating the name specified

### ISSUE THREAD

**Issue by deepak-khopade-isdr** [dotnet/efcore#8464]
When added in Fluent API `.HasConstraintName<entity, relatedEntity>("FK_name")` is not creating the name specified and just creating the default name by its own.

If you are referring a single columned PK then its just working fine, but if you are referring a Composite PK with more than one column, it's just not creating the name specified and rather creating default one.

NOTE: the reason I want to specify the name is to avoid getting longer default created names truncated when it comes to MySql (which only allows 64 char long names).

EF Core version: 1.1.1
Database Provider: Pomelo.EntityFrameworkCore.MySql/1.1.1
Operating system: Ubuntu 16.04
IDE: JetBrains Rider and VS CODE

**Comment by ErikEJ** [comment]
This looks like a Pomelo Mysql bug, you should report at the pomelo issue tracker

**Comment by deepak-khopade-isdr** [comment]
@ErikEJ : thanks, I have opened an issue with them, however, I realized the problem for this one in my code. If I don't provide the PrincipalKey or InverseProperty, it would imagine and create 2-way foreign keys. So this is not an issue anymore. Thanks again.
