### ISSUE TITLE
Update logging guidance for 2.0

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8469]
Due to this breaking change aspnet/Announcements#238 the guidance for using logging with EF is not deprecated. It's not obvious what the solution is or what the new guidance should be. For now, we will recommend that people continue to use the deprecated approach.

**Comment by ajcvickers** [comment]
@divega We should discuss how to document this while the main docs pages are still referencing 1.x bits.

**Comment by divega** [comment]
@ajcvickers look like there is little left we can do here. Perhaps track as docs issue?

**Comment by ajcvickers** [comment]
@divega Yeah, we need to make sure that the docs call out that the method is obsolete.

**Comment by ajcvickers** [comment]
Closing this based on these methods not being obsolete anymore. https://github.com/aspnet/Logging/issues/616
