### ISSUE TITLE
Consider more complete cleanup after transactions

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#8476]
Following https://docs.microsoft.com/en-us/ef/core/saving/transactions, to do a cross-context transaction one should share the connection, start a transaction on the first context and then use the transaction in each of the other contexts. 

When you do this and then Dispose the transaction, the use of the transaction in the first (originating) context is cleaned up -- specifically, context.Database.CurrentTransaction is set to null. In the other contexts, however, it is not. You have to explicitly set these to null by UseTransaction(null). If you do not set them to null then any subsequent use of the context results in an exception being thrown saying that the transaction is not associated with the connection. 

I think that if an exception were to occur somewhere along the line then you would also have to clean up the transaction in the non-originating contexts, meaning that you may need to put this cleanup code in a finally block. 

Not a big problem but I thought I would mention it for consideration. It seems a bit inconsistent that the transaction is cleaned up in one of the contexts but not in the sharing contexts.

**Comment by popcatalin81** [comment]
@sjb-sjb EF can't know if the transaction was disposed due to client calling dispose, or some error along the path. If it's the later then the application should know about the error and EF should not swallow it. 

Therefore the right thing to do is let the user sharing the transaction to also clean it up in all the shared places.

**Comment by sjb-sjb** [comment]
I am OK with that. 

Exploring cross-context transactions a little further, though, I have hit a roadblock. I am writing a virtualizing collection. I want to use separate connections for each page load, because different pages could be loading simultaneously. However, after the user modifies records (possibly in several different pages), I want write back all the changes in a transaction. I don't see how to have the contexts all start sharing the same connection at that point. I don't see a way to change the connections of the contexts so that the contexts are using a shared connection. Am I just missing something obvious?

**Comment by sjb-sjb** [comment]
Closing this in favor of a new issue that states the question more clearly.
