### ISSUE TITLE
OnDelete is set to restrict, but foreign key still gets set to null

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#8485]
I configured a relationship with
`OnDelete(DeleteBehavior.Restrict);`
However, when I delete the parent Entity and then call SaveChanges, a child entity's foreign key gets updated to null.

As far as I can see, using DeleteBehavior.Restrict behaves exactly the same as if I had used DeleteBehavior.SetNull. Is this working as intended?

There is some inconsistency in the documentation on this topic.
https://docs.microsoft.com/en-us/ef/core/modeling/relationships
In one place it says:
>SetNull: The foreign key properties in dependent entities are set to null.
Restrict: The delete operation is not applied to dependent entities. The dependent entities remain unchanged.

In another place it says:
>Restrict means that dependent entities that are not loaded into memory will remain unchanged and must be manually deleted, or updated to point to a valid principal entity. For entities that are loaded into memory, EF will attempt to set the foreign key properties to null.

**Comment by ajcvickers** [comment]
@Wain123 This is a duplicate of #8342. The documentation is incorrect and needs updating. For tracked entities, Restrict, and SetNull do the same thing.
