### ISSUE TITLE
In Memory Database can no longer be shared.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/efcore#8486]
EntityFrameworkCore.InMemory 2.0-preview1 now requires `UseInMemoryDatabase()` to take a string for the database name which means you cant share a DB context like in v1.1.2. Each unit test creates a new context thus each test takes a few seconds and this is unusable on my build server.
````
var services = new ServiceCollection();
services.AddEntityFrameworkInMemoryDatabase().AddDbContext<VioDBContext>(options => options.UseInMemoryDatabase("test"));
````

**Comment by ajcvickers** [comment]
@KieranDevlinSycous Use the same database name for every test that should share the same database. See  #7482
