### ISSUE TITLE
How to debug myContext.Database.Migrate()?

### ISSUE THREAD

**Issue by GeertVL-zz** [dotnet/efcore#8497]
When I try to run myContext.Database.Migrate() I get a file not found on the assembly I am working in.
I want to see what is going on because file not found does not make any sense.

I loaded the symbols and set the EFCore nuget packages in debug but it does not step in.

How do I debug from my own testproject into the migrate() method?

**Comment by ajcvickers** [comment]
@GeertVL We're working on a better story for debugging with symbols. For now, probably the best way to get debugging to work is by cloning the repository and building from source.
