### ISSUE TITLE
Add-Migration does not recognize removal of class property

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/efcore#8513]
Describe what is not working as expected.
Add-Migration should not see properties that do not exist in class.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
I removed a property from an existing class and relative foreign key and virtual property.  

I deleted all of my migrations.  

I restarted the computer, cleaned the solution, and rebuilt the solution.

Add-Migration Initial-Create creates a migration with the non-existent property and relative foreign key.

I did Find for the solution to confirm that neither the property nor the foreign key exist in the solution, but every time I delete and create the migration, the property is added to the migration.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

Is there a cache somewhere that needs to be deleted?

```c#
<code listing>
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7
IDE: Visual Studio 2017 15.1 26403.7

**Comment by dpedrelli** [comment]
I created the initial migration which creates the following migration:

migrationBuilder.CreateTable(
                name: "Distributor",
                schema: "shared",
                columns: table => new
                {
                    ID = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    BuyingGroupID = table.Column<int>(nullable: true),
                    CompanyName = table.Column<string>(type: "varchar(100)", nullable: false),
                    Notes = table.Column<string>(type: "VARCHAR (MAX)", nullable: false, defaultValueSql: "''"),
                    Url = table.Column<string>(type: "varchar(500)", nullable: false)
                },

BuyingGroupID is the property that is not in the model.

I added the property back to the model and created a second migration:

            migrationBuilder.AlterColumn<int>(
                name: "BuyingGroupID",
                schema: "shared",
                table: "Distributor",
                nullable: false,
                oldClrType: typeof(int),
                oldNullable: true);

It changed the column from NULL to NOT NULL.

I removed a property from the model and created a third migration.

            migrationBuilder.AlterColumn<int>(
                name: "BuyingGroupID",
                schema: "shared",
                table: "Distributor",
                nullable: true,
                oldClrType: typeof(int));

It altered the column back to NULL.

**Comment by ajcvickers** [comment]
@dpedrelli Is BuyingGroupID a foreign key?

**Comment by smitpatel** [comment]
It is shadow foreign key property.
When ef cannot find foreign key property for a relationship,(from explicit user code or by convention) it adds a shadow property for fk. By default it is nullable (unless relationship is made required). So clr type would be int? 
When you added property you used type int hence property's nullability changed.

**Comment by dpedrelli** [comment]
I found the problem.  There was a virtual property on another class, pointing to this class.  Apparently, Entity Framework created a foreign key column to support the virtual property.
