### ISSUE TITLE
How to: Can I listen for Changes in the underlying MS SQL Tables?

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/efcore#8516]
Is it possible to listen for changes in the MS SQL Table with EF CORE? I would like to be notified if the underlying data changes to refresh a UI Grid.

**Comment by ErikEJ** [comment]
System.Data.SqlClient has SqlDependency class, but it is really not related to EF Core.

**Comment by ericbrunner** [comment]
@ErikEJ Thanks. Maybe my question was not precisely enough. Sorry. I mean as there something in EF Core that can by used like what you mentions with SqlDependency or SqlTableDependency to get change notification. I know it is an ORM but is there something available or should I use the raw `context.Database` of EF Core to get such functionality? Thats all I found so far: [http://www.sqltabledependency.it/](http://www.sqltabledependency.it/)

**Comment by ErikEJ** [comment]
I am not sure I think a feature like that belongs in an ORM

**Comment by ericbrunner** [comment]
@ErikEJ You first answser is it is not related to EF Core. Your second answer is that it should belong to an ORM. If you don't have a valuable answer don't answer.

**Comment by ErikEJ** [comment]
@ericbrunner Sorry, I wrote: I am **not** sure I think a feature like that belongs in an ORM

**Comment by ericbrunner** [comment]
@ErikEJ Sorry Erik for missunderstanding. I will try that: https://www.codeproject.com/articles/1029976/immediate-sql-server-record-change-notifications-w with [SqlTableDependency ](https://tabledependency.codeplex.com/wikipage?title=SqlTableDependency)seems to be a reasonable approach
