### ISSUE TITLE
HtmlString support

### ISSUE THREAD

**Issue by ivankarpey** [dotnet/efcore#8517]
At the current moment if model have field of type HtmlString data model generation failed to

> InvalidOperationException: The entity type 'HtmlString' requires a primary key to be defined.

**Comment by davidfowl** [comment]
Why not just store it as a string?

**Comment by ivankarpey** [comment]
I think this is more a question of consistency between platforms. As I understand this type specifically was added to avoid problems with encode/decode html in strings. If it's not supported on DB level, than it's still required additional conversions, which is at some point depreciates the idea of HtmlString (e.g. what the point of using it, if it's still need a conversion from string, let's just take string and encode/decode it).

**Comment by davidfowl** [comment]
It's specifically for expressing that a string is already encoded so that Razor (or some other view engine) doesn't re-encode it. I don't agree with the assertion that it "depreciates" the idea of `HtmlString`. It *really* is totally orthogonal to the database. There are lots of auxiliary types that can't be represented in EF models.

**Comment by bricelam** [comment]
Possibly covered by #242

**Comment by ajcvickers** [comment]
@ivankarpey Unless the underlying ADO.NET provider natively understands HtmlString, the only thing EF can do is convert it to something that the underlying ADO.NET provider will understand, which is string. This kind of type conversion is covered by @242, as @bricelam said above. If you want support that goes further down the stack, then ADO.NET providers need to add support, which is outside the scope of EF.

**Comment by ivankarpey** [comment]
Get it. Thanks for the explanation.
