### ISSUE TITLE
No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by Just1n** [dotnet/efcore#8542]
```
dotnet ef --version
dotnet : No executable found matching command "dotnet-ef"
At line:1 char:1
+ dotnet ef --version
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No executable f...and "dotnet-ef":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

### Steps to reproduce
 1. Create a Web Api core project.
 2. Add some references in csproj file.
```c#
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.1" />
  </ItemGroup>
</Project>

```
3. Run `dotnet ef --version`

### Further technical details
EF Core version: see above
Database Provider: see above
Operating system: win10    Version 10.0.15063 Build 15063
IDE: Visual Studio 2017

**Please note, I have run `dotnet restore`**

**Comment by bricelam** [comment]
...and you running `dotnet ef` in the same directory as the `*.csproj` file, right?

**Comment by Just1n** [comment]
Hi @bricelam , I run `dotnet ef` in Package Manager Console.
The insteresting is, `dotnet ef` can be run in normal .Net Core Console application, but can't be run in .Net Core WebApi Project via Package Manager Console.

**Comment by bricelam** [comment]
PMC defaults to the solution directory. `cd` to the project directory before running.

Also, we strongly recommend using `Add-Migration` and friends in PMC since integrate better with Visual Studio to provide a superior experience.

**Comment by Just1n** [comment]
Thanks @bricelam , `cd` to the project directory works.
