### ISSUE TITLE
Should Redis EnsureCreated() calls return true the first time they are called?

### ISSUE THREAD

**Issue by lajones** [dotnet/efcore#855]
In issue #845, for InMemory, we changed the definition of the EnsureCreated() to return true if the database being used is persistent and if it was the first time we were calling EnsureCreated(). This was so that a seed method could test whether EnsureCreated() returned true and only seed the database the 1st time.

At the moment the RedisDataSourceCreator always returns false for EnsureCreated() and EnsureCreatedAsync().

We could consider changing it so that we test whether or not the Redis set (one for each entity in the model) which holds the list of primary keys for that entity has been created. If it has then we return false and take no further action, if it has not then we create the set and return true. This would enable the same "seed-setting" logic for Redis as was enabled for InMemory.

But would have to consider what to return and what to create if some but not all of the required sets existed.

**Comment by ajcvickers** [comment]
Closing as Reddis is not currently in a working state and lots of things have changed.
