### ISSUE TITLE
Revisit DbLoggerCategory pattern

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8550]
From API review. @divega to investigate different ways of nesting the classes.

**Comment by divega** [comment]
Discussed this with @ajcvickers and @anpete and we are not convinced it adds enough value. I tried the simplest approach of nesting `DbLoggerCategory under `EF` in #8550 so we can see how it looks like.

Removing milestone.

**Comment by smitpatel** [comment]
@divega - Did you intend to tag different issue in your previous post? Its circular reference atm :trollface:

**Comment by divega** [comment]
@smitpatel thanks!
