### ISSUE TITLE
Make EntityQueryModelVisitor internal, with appropriate refactoring

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8561]
It changes a lot and most providers won't need to inherit from it directly, so it would be good if it could be internal.

Likewise for AsyncQueryMethodProvider

**Comment by ajcvickers** [comment]
@anpete If this doesn't make it for preview2, then please work on it ASAP after preview2.

**Comment by ajcvickers** [comment]
@anpete What's your feeling on this one? Do you think we can do it in the next couple of days, or is it something we should punt/close?

**Comment by anpete** [comment]
Punt

**Comment by ajcvickers** [comment]
Closing for now since it doesn't fit and would be a breaking change to do in the future. If it still seems important for 3.0, we can re-consider then.
