### ISSUE TITLE
Constant strings for warnings/exceptions should be stored in resource files

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#8599]
In DbContextWriter of RevEng
  _sb.AppendLine($"// {entityTypeError.Value} Please see the warning messages.");

**Comment by lajones** [comment]
This is what appears in the generated code if there are errors. We decided not to localize anything which was part of the generated code.

**Comment by smitpatel** [comment]
@bricelam

**Comment by ajcvickers** [comment]
We are not localizing, but we are taking the approach that all strings like this should be in resource files so that in the future we (or someone) could localize.

**Comment by bricelam** [comment]
Closing since this is tracked by #8853
