### ISSUE TITLE
Delete does not work in Microsoft.EntityFrameworkCore.InMemory 1.1.2

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8604]
(this was reported in an internal issue tracking system by @vank-ms , issue #433893)

I reviewed and article about using WebAPI on VS Mac and performed the walkthrough step-by-step, resulting in the attached project, [TodoApi.zip](https://github.com/aspnet/EntityFramework/files/1030405/TodoApi.zip).
The last step was to add a Delete CRUD operation.  When I test this using Postman or Fiddler, on Mac or Windows, DELETE results in the single record's id being incremented, not deleted.

1. Run the attached app
2. Navigate to the url it opens the browser to, plus /api/todo (like: http://localhost:64925/api/todo).  Port # will vary.  Result is:
    [{"key":1,"name":"Item1","isComplete":false}]
3. Send a DELETE request to the app using Fiddler, curl, etc.:
    DELETE ttp://localhost:64925/api/todo/1
4. Refresh the browser.

Expected result:
[]

Actual Result:
[{"key":2,"name":"Item1","isComplete":false}]
Key is incremented, record is not removed.
Repeating the operation with an adjusted url for record #2 increments the id again.

This appears to happen only if there is a single record in the InMemory database.  With two records, the referenced record is deleted as expected.

**Comment by smitpatel** [comment]
This piece of code is culprit 
In `TodoRepository` class
```C#
public TodoRepository(TodoContext context)
{
	_context = context;

	if (_context.TodoItems.Count() == 0)
		Add(new TodoItem { Name = "Item1" });
}
```

When you delete record in 3rd step, it actually deletes it from database. But then you don't have any records left. When you refresh the page, it starts a new request, hence you initialize the `TodoRepository` for new scope. It sees 0 records in db and inserts 1. It increments due to Identity attribute on the property.
