### ISSUE TITLE
Improve binding of RelationalTypeMapping objects to model

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8625]
In #8605 RelationalTypeMapping objects were bound to properties using conventions. However, conventions may not be the best thing to do here, since sometimes conventions aren't used when building the model. This is a problem because the runtime absolutely needs to be able to get RelationalTypeMapping objects for any property. This means that currently there is a fallback mechanism that will try to find a mapping that has not been set. If we could instead ensure that a property always has a mapping. then it would simplify our code. This might be done as part of #8258.

(See also #8624.)

**Comment by ajcvickers** [comment]
If we do this, then we will do it as part of the read-only model--see #8258.

**Comment by ajcvickers** [comment]
Based on discussion in #11738, we should likely remove the fallback code.

**Comment by ajcvickers** [comment]
Note that this item and #14433 are actually different. Both items are about the type mapping always being available on the IProperty. However, for #14433 we will keep using the current solution, which is running a ModelBuiltConvention, but cleanup code that assumes this might not have run. This issue is about a more efficient and more lazy mechanism to do this that would not require a full model traversal.

**Comment by AndriySvyryd** [comment]
This can be accomplished with https://github.com/aspnet/EntityFrameworkCore/issues/9329

**Comment by AndriySvyryd** [comment]
Fixed in bca8fa5c79b2f75c94cbd3dc1984398a5aa13a36
