### ISSUE TITLE
Generate Migration

### ISSUE THREAD

**Issue by chrysikos** [dotnet/efcore#8628]
Can I generate migrations "Enable-Migrations" ,"Add-Migration"  wihtout Visual Studio Package Manager Console?

**Comment by neyromant** [comment]
You can run on console:
```dotnet ef migrations add <MIGRATION_NAME_HERE>```

**Comment by chrysikos** [comment]
This doesn't work, is it compatible for EF6?

**Comment by neyromant** [comment]
No, of cource.
https://github.com/aspnet/EntityFramework#ef-core-here-ef6-elsewhere

"This project is for Entity Framework Core. Entity Framework 6.x is still under active development at https://github.com/aspnet/EntityFramework6."

**Comment by chrysikos** [comment]
Ohhhh sorry for that.

**Comment by neyromant** [comment]
Good luck you with search. Please close the issue.
