### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design has a dependency on Microsoft.AspNetCore.Hosting.Abstractions

### ISSUE THREAD

**Issue by Robiwahn23** [dotnet/efcore#8634]
Has this be done by purpose?
I am using EF Core without AspNetCore - so this reference forces me to include a lot of aspnetcore assemblies.

Referenced Version: v1.1.1

**Comment by divega** [comment]
@Robiwahn23 this is by design in 1.x versions. It is necessary to be able to initialize services in ASP.NET Core applications for design-time work. The good news is that the pattern is changing in 2.0 and we were able to remove the dependency.

**Comment by Robiwahn23** [comment]
great! thanks for clarification. Keep up the good work!!
