### ISSUE TITLE
Master-Detail Considerations/Strategies

### ISSUE THREAD

**Issue by dpedrelli** [dotnet/efcore#8635]
Describe what is not working as expected.

Are there any documents or discussions on considerations and strategies, when dealing with master-detail relationships?  My background is working with individual datasets that point to two-dimensional tables.  I just recently started working with entity classes that have member properties that are other entity classes.

Assume a given class:
```C#
public class Customer
{
  public string Name { get; set; }
  public List<Address> Addresses { get; set; }
}
```

If I `.Include(e => e.Address)`, whenever I update Customer, it will update all of the associated addresses, as well, whether they have changed or not.  This may result in performance issues as well as data collisions, with other people editing addresses.

I am just wondering if there is a guide that discusses these issues.  Also, is there anything that discusses implementing a delta, so that changes can be cancelled, without updating or refreshing?

Thanks.

**Comment by ajcvickers** [comment]
@dpedrelli Can you post a full code listing or project that reproduces what you are seeing? It should be possible (normal) to update the Customer object without the Address objects being updated.

**Comment by dpedrelli** [comment]
I am not having a specific problem.  I am looking for something that discusses the different design and performance considerations.  When do I want to use .Include() and when do I want to query these entities separately?  When querying linked entities separately (without Include()), what are some of the ways to manage these master-detail relationships, from the UI?  How to handle things like caching data changes, prior to updating the database?

**Comment by ajcvickers** [comment]
@dpedrelli Probably the best place to start would be our documentation: https://docs.microsoft.com/en-us/ef/

Without having more specifics it's hard to know exactly what you are looking for, but the docs include details on querying and loading entities. If there are specific scenarios that you think would be good to add to the documentation, then feel free to open issues on https://github.com/aspnet/EntityFramework.Docs
