### ISSUE TITLE
Allow connections strings to be loaded from app.config

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8647]
Issue #7916 brought back the ability to use the `name=` syntax for connection strings and have them found in IConfiguration, if IConfiguration is in the application's D.I. container and that container is accessible to EF.

If possible when running on .NET Framework we should also look into the app.config. Note thatthis won't work on a .NET Core app since app.config is not available.

**Comment by divega** [comment]
There is an implementation of `System.Configuration.ConfigurationManager` for .NET Standard 2.0 that we could leverage for this, however it lives in a separate package. Two options I see to implement this feature are: 
1. Take a dependency on this package 
2. Creates a package that implements `INamedConnectionStringResolver` based on ConfigurationManager and contains sugar methods to replace the default implementation. 

The same mechanism could be used to leverage other configuration sources that are platform specific, e.g. app data in UWP.

**Comment by bricelam** [comment]
I threw together an extension to do this: [EFCore.ConfigurationManager](https://github.com/efcore/EFCore.ConfigurationManager)
