### ISSUE TITLE
[ARM][Windows Emulator][UWP][VB] Sqlite3 not found exception?

### ISSUE THREAD

**Issue by jeffman1** [dotnet/efcore#8657]
I am having a weird problem where some of my code runs with ARM from a UWP class library but not all of it. I am specifically having problems with  calling savechanges here but not executing a sql query command:

```VB
   Using categories As New UIELLUWP.DataAccess.SQLiteDb
    'categories.Database.EnsureDeleted()
    'categories.Database.EnsureCreated()
    'Dim c As DataAccess.CategoryCodes = New DataAccess.CategoryCodes With {
    '  .CategoryCode = "CBM1"
    '     }

    'c.CategoryCode = c.CategoryCode.Trim
    'c.CodeID = categories.CategoryCodes.Count + 1
    'categories.CategoryCodes.Add(c)
    'categories.SaveChanges(True)

    'Dim b As New DataAccess.CategoryReference
    'b.CategoryDescription = "who is this?"
    'b.CategoryName = "Cool Beans"
    'b.CodeID = c.CodeID
    'b.CategoryID = categories.CategoryInformation.Count + 1
    'categories.CategoryInformation.Add(b)
    'categories.SaveChanges(True)
  End Using
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

An exception of type 'System.DllNotFoundException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code

Additional information: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### Steps to reproduce
The code that causes it to error is simple: call savechanges which is above. I can call this code though without exception in app.vb (main UWP project not class library):

```VB
Dim clrtable As New ItemValuation
'make sure the eval table is cleared before the program is initialized
Dim r As Task(Of Boolean) = clrtable.ClearEvalTable()
r.Wait()
```

 In my dll file with code calling the database (UWP class library):

```VB
    Public Async Function ClearEvalTable() As Task(Of Boolean)
    'delete all the evaluated items from the database for next evaluation
    Try
        Using delcmd As New DataAccess.SQLiteDb
            delcmd.Database.ExecuteSqlCommand("DELETE FROM ItemValuationCompare")
            Dim allvalcompare As New List(Of DataAccess.ItemValuationCompare)
            allvalcompare = (From c In delcmd.ItemValuationCompares Select c).ToList
            delcmd.RemoveRange(allvalcompare)
            delcmd.SaveChanges()
            allvalcompare = Nothing
        End Using

        Return True
    Catch ex As Exception
        Log("Error clearing temporary results:" + ex.Message)
        'Dim msg As New MessageDialog("Error clearing temporary results:" + ex.Message)
        'Dim r As msg.ShowAsync()
        Return False
    End Try

 End Function
```

### Further technical details
EF Core version: 1.1.12
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 (10.0.10586)
IDE: Visual Studio 2015 SP3

**Comment by bricelam** [comment]
This may be fixed. You'll need [VS 15.4](https://blogs.msdn.microsoft.com/dotnet/2017/08/25/uwp-net-standard-2-0-preview/) to test it...

**Comment by jeffman1** [comment]
Fixed this issue a month or two back which involved the UWP library DLL for sqlite  file interfering with the one from a update (the one right before creators update).  Also, I changed some code around but not much changes. Sorry for late post but it involved duplicate libraries.

**Comment by bricelam** [comment]
Sweet! Glad it's working.
