### ISSUE TITLE
[DataType] annotation not working

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#8662]
Property
`public DateTime? TimeCreated { get; set; }`
is by default mapped to `datetime2(7)`.

But if I want to map it to older `datetime` type it works when explicitly configured in FluentApi but does not work(remains default type) when configured with Annotation:
````
[DataType("datetime")]
public DateTime? TimeCreated { get; set; }`
````
### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ErikEJ** [comment]
You should use the Column attribute, not DataType

   [Column(TypeName = "datetime")]

**Comment by borisdj** [comment]
Thx for that info.
