### ISSUE TITLE
SqlServer: Scaffold Identity on a non-key appropriately 

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#8688]
After #8680 , scaffolding code will do nothing about identity column,
1. It should put annotation appropriately on DatabaseModel.
2. It should print out appropriate fluent API for column which gets identity by convention but is not actually identity.
3. It should print out fluent API for column which will not get identity by convention but is identity column.
~4. Log warning for identity appearing on invalid property type. (if any)~

**Comment by ajcvickers** [comment]
Also do this for SQLite auto-increment.

**Comment by bricelam** [comment]
See also #8140

**Comment by divega** [comment]
Clearing up milestone. I would like to understand the impact of this better before we punt.

**Comment by smitpatel** [comment]
From what I understand of current codebase,
When scaffolding db, if the column is identity, we scaffold `ValueGenerated.OnAdd`. Which SqlServer by convention setups with identity. If column is not identity then `ValueGenerated.OnAdd` is not put and using key convention, we make `ValueGeneratedNever()` (unless some other code like Sequence marks it otherwise. So identity should just work fine (as @bricelam found during verification of preview2 packages).

@bricelam can provide more info on his testing.

**Comment by bricelam** [comment]
Yes, the reverse engineered model is fully compatible with the database. The minor improvement would be to generate `.UseSqlServerIdentityColumn()` in the C# for non-key columns. This would make the model round-trip-able with Migrations.

**Comment by bricelam** [comment]
This is working as expected. It generates `.ValueGeneratedOnAdd()` which, by convention, leverages the `IDENTITY` column.
