### ISSUE TITLE
Support DbSet fields as well as properties

### ISSUE THREAD

**Issue by harshilns** [dotnet/efcore#8698]
Hi,

I added a DBSet in the context. When using Migrations through command line, it is creating the database but not the tables. 

### Steps to reproduce
```c#

**Context Code**

   public class CostContext:DbContext
    {
        public CostContext(DbContextOptions<CostContext> options):base(options)
        {           
        }
        public DbSet<VendorCost> VendorCosts;
    }
}

**Model**
    public class VendorCost
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
}

**Startup**

            services.AddDbContext<CostContext>(options=>options.UseSqlServer(_config["Data:ConnectionString"]));

**Connection String in the json config file**
{
  "Data": {
    "ConnectionString": "Server=(localdb)\\MSSQLLocalDb;Database=Cost;Trusted_Connection=true;MultipleActiveResultSets=true;"
  }
}

```

### Further technical details
**Environment**
Visual Studio 2017 15.2 (26430.12) Release
Aspnet Core Project
EntityFramework Core 1.1.2
EntityFrameworkCore.Tools.Dotnet 1.0.1
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer)
Windows 7

**Comment by ajcvickers** [comment]
The reason it doesn't work is that VendorCosts is a field, not a property. EF Core only detects DbSet properties. We're probably not going to fix this, but we would accept a well-written PR to do it. Such a PR must ensure that a FieldInfo will work in addition to a PropertyInfo in any place the set property/field is referenced--for example, queries.

**Comment by weitzhandler** [comment]
BTW, I came looking for a solution to this, and found this post related, so posting this here:
[Nullable reference type in C#8 when using DTO classes with an ORM](https://stackoverflow.com/a/59118390/75500).
