### ISSUE TITLE
Sqlite: scaffolding: a nullable bool is created as string in the POCO entity

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/efcore#8725]
I have a database with two tables. One field is a nullable integer that when the POCO entity is created, the property is a long? so i guess that it could be a problem because a long can be bigger than an intenger. This can be see in the table "Contenidos", the field "Año".

Another case is in the table "Ficheros", field "SePuedeBorrar". In the database is a nullable bool, but when the POCO entity is created, the property is an string. This is not correct.

I have attached the database the produces this cases.

I am using Sqlite.Design version 1.1.2, Framework.Tools 1.1.1 and Sqlite 1.1.2.

Thanks.
[Sqlite - scaffolding test.zip](https://github.com/aspnet/EntityFramework/files/1050182/Sqlite.-.scaffolding.test.zip)

**Comment by bricelam** [comment]
SQLite has a [dynamic type system](https://www.sqlite.org/datatype3.html). The user-specified column type name has almost no meaning. We currently apply the same [type affinity rules](https://www.sqlite.org/datatype3.html#type_affinity) as the database engine to pick the most likely candidate from one of the four primitive types supported by SQLite: `INTEGER` (maps to `long`), `REAL` (maps to `double`), `TEXT` (maps to `string`), or `BLOB` (maps to `byte[]`).

#8824 is one idea we had to improve the reverse engineer process to produce more expected CLR types.
