### ISSUE TITLE
Migrations: Properties aren't being picked up

### ISSUE THREAD

**Issue by aredfox** [dotnet/efcore#8727]
When using EF Core Migrations the tooling isn't picking up all my properties, only the "Id" and some (not all) of the FK's (navigation properties). It also seems to understand the "Table Per Hierarchy" very well - as it has set up a discriminator where I wanted it to, but the migration file itself doesn't reflect the properties I have in my Model namespace (see github code).

My DbContext are located here: https://github.com/aredfox/TheConference/blob/master/InfoBooth/TheConference.InfoBooth.Data/InfoBoothContext.cs
My Model classes here: https://github.com/aredfox/TheConference/tree/master/InfoBooth/TheConference.InfoBooth.Core/Model

You can look at the generated "Initial Migration" at [ https://github.com/aredfox/TheConference/blob/master/InfoBooth/TheConference.InfoBooth.Data/Migrations/20170604125116_Initial.cs ]. There you'll see that it detected all the Id properties (defined in the base class `[Entity][1]`), but none of the other properties I of my [Model classes][1].

I used the approach of adding a Console App to run migrations (otherwise it won't work - see [Julie Lerman's tips][2] on getting started with EF Core). Thus when running migrations I do it this way: `dotnet ef --startup-project ../../TheConference.Infrastructure.ConsoleApp migrations add Initial`. 

**Do I have to use *annotations* or *modelBuilder* or a form of *EntityTypeConfiguration<T>* in EFCore to let EF know what I want to take?**.

  [1]: https://github.com/aredfox/TheConference/tree/master/InfoBooth/TheConference.InfoBooth.Core/Model
  [2]: http://thedatafarm.com/data-access/no-executable-found-matching-command-dotnet-ef/

Full read at: https://stackoverflow.com/questions/44354561/ef-core-migrations-doesnt-pick-up-all-properties

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS2017

**Comment by smitpatel** [comment]
Got answered on stackoverflow.
Root cause: Properties were readonly (without setters)
