### ISSUE TITLE
Is there possibility to modify the LINQ-expression tree before execution?

### ISSUE THREAD

**Issue by Thorium** [dotnet/efcore#8730]
This is just a question, not an issue:
Is there possibility to modify the LINQ-expression tree before execution?
Or any kind of extension point where this could be done?

There are a few LINQ-expression-tree-optimizers like [this](https://github.com/Thorium/Linq.Expression.Optimizer), and using those would sometimes benefit the user.

**Comment by smitpatel** [comment]
@Thorium -
The best way to integrate such an optimizer inside EF Core would be to add custom implementation of IQueryCompiler (optionally derived from QueryCompiler). QueryCompiler class is single point through which all EF query executions are started. Methods in that class takes `Expression` as an argument. So it would be easy to pre-process the expression tree before passing it to EF stack.

I looked at the supported optimizations in the linked library. There are quite a few optimizations from that list we already do in EF Core.
`ParameterExtractingExpressionVisitor` which is being called from `QueryCompiler.ExtractParameters` method converts code which is not correlated with server to parameters. It converts local variables to query parameters, evaluates all the expression which can be computed without server input.
`CompositePredicateExpressionVisitor.cs` Is another class which applies bunch of optimizations (it is applied to SQL Expression tree though), many of them around Boolean logic. You can look into each Visitor to found out what optimizations they cover. (we have organized them with common logic for the optimization.)

`QueryOptimizer` is another place for optimizations though it works on QueryModel which is condensed form of an ET produced by Remotion.Linq library.

Let us know if there are any missing extensibility points or blockers in integrating which we can incorporate in our codebase so integration with such ET optimizers can be done.
Also if you see some optimizations which we are missing and can be done inside EF Core then we will consider a well-written PR.

Thanks.
