### ISSUE TITLE
Re-request: Specifying INCLUDES for an index

### ISSUE THREAD

**Issue by arrkaye** [dotnet/efcore#8746]
I'd like to specify INCLUDES columns when defining an index in EF Core.

The [previous advice ](https://github.com/aspnet/EntityFramework/issues/3748) to include in the Sql() call of a migration works, but has the following issues:

1. The SQL string is easily lost if migrations are deleted.
2. We lose the ability to use refactor tools. E.g. renaming fields/columns.
3. It's nice having build failures when you reference a column that doesn't exist, as opposed to runtime.

I think the logical place is to have these definable using the Fluent API in addition to the HasIndex() call.

Is this something that's possible?

**Comment by ajcvickers** [comment]
This is already being tracked by #4846. Closing this as a duplicate.
