### ISSUE TITLE
Do stored procedure calls still require an entity with a corresponding table?

### ISSUE THREAD

**Issue by im1dermike** [dotnet/efcore#8747]
I'd like to be able to call a stored procedure in EF Core where the return type does not correspond to a database table, but rather only a C# class.  Is this possible now that EF Core 2.0 has been released or is this still not possible?

Eg.

    var logs = context.AuditLogs.FromSql("usp_GetAuditLogs").ToList();

Where `AuditLogs` is a `DbSet<AuditLog>` which does not have a database table, only a C# class that the `FromSql` should serialize into.

**Comment by ajcvickers** [comment]
@im1dermike This is tracked by #1862, but unfortunately we don't have time to implement it for 2.0. We consider it a high priority for post 2.0.
