### ISSUE TITLE
Commit time outs in Entity Framework.

### ISSUE THREAD

**Issue by nagarjunacspeaks** [dotnet/efcore#8760]
Question was posted in Stackoverflow but suggestions were not much of help.

https://stackoverflow.com/questions/44170804/commit-failure-error

Please go thru the above and I am just pasting my comment from there.

Please don't provide band aid fixes like increasing default timeout etc. as would like to know root cause of the problem.

It is code first. Also, it does not seem index issue as it not taking any time to query and should be pretty fast in term of sql performance for queries. Seems to be Entity framework and hence C# code issue. There is this below link in the error and hence seems to be drop from EF framework. [link] (go.microsoft.com/fwlink/?LinkId=313468). But, suggestions present at the link seems to be band-aid fixes. Any suggestions related to Entity framework would be appreciated as I am new to this.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework6#298
