### ISSUE TITLE
Add tests for diagnostic events

### ISSUE THREAD

**Issue by anpete** [dotnet/efcore#8779]
Perhaps we have some, but I couldn't find them. If not, we should consider adding tests that verify that we correctly generate diagnostic events.

**Comment by ajcvickers** [comment]
We have tests that test the events are generated with the correct category, and that the events create the same message string as happens down the logging path. We don't generally have tests that test events are fired at the correct time or have the correct payload--those would need to be written for each event based on semantic knowledge of the event.

**Comment by anpete** [comment]
That's what I figured.
