### ISSUE TITLE
Consider removing direct IConfiguration dependency

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8780]
In preparation for 2.0, ASP.NET Core that were coupled to `IConfiguration` are being decoupled. See https://github.com/aspnet/Logging/commit/fe2b2998b8ceef39fdd9510638884aa89dc76350. There should be no reason for us to depend transitively anymore (unless we have a different path to it) but we recently added named connection resolution which uses `IConfiguration`. This issue is about:

1. Figuring out if we still have a transitive dependency (that would probably be an ASP.NET Core bug)
2. Decide what to do with named connections for 2.0 
3. If we want to keep it, should we move it to a different package?
4. Depend if possible on the abstractions package

**Comment by ajcvickers** [comment]
@divega Are you okay with removing the dependency and the named connection code for now and revisiting in 2.1 at the same time as the configuration changes are re-considered (again) across other areas? If so, we should triage this into preview2 today and assign it.

**Comment by ajcvickers** [comment]
Discussed with @divega and decided to keep the reference to the abstractions package and leave the code in for 2.0.
