### ISSUE TITLE
EF core 2.0 DI issue with Asp.net core 1.1

### ISSUE THREAD

**Issue by rajurh** [dotnet/efcore#8781]
Hi Team,

I'm using Asp.Net core 1.1 with EF core 2.0 in which DI complains with below error message.

"Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'." 

   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MoE.ERS.Web.Internal.Mvc.Program.Main(String[] args) in D:\Applications\UI\MVC\Program.cs:line 10

Code snippet which is used in startup.cs

   services
                .AddEntityFrameworkSqlServer()
                .AddDbContext<DBContext>(options =>
                    options.UseSqlServer(Configuration["Connectionstring"]));

If I am using Asp.net core 1.1 with EF core 1.1 no issues observed.  Reason for moving to EF core 2.0 for migration script generation process is simplified.

Any solution or recommendation will be much appreciated.

**Comment by davidfowl** [comment]
Don't mix EF 2 with DI 1.1. Aren't you getting downgrade warnings on restore?

**Comment by rajurh** [comment]
Migration on lib project with multiple context is an issue in EF1.2. That was the reason for EF2.0. If you have any better suggestion or ideas to do migration for context based with EF1.2 please share your thoughts or links on the same.

**Comment by ajcvickers** [comment]
@rajurh Basically what @davidfowl said. This won't work--you need to use consistent versions. If you have a specific issue about migrations on 1.1.2, the please file an issue for that, including full steps to reproduce what you are seeing.
