### ISSUE TITLE
EF core-Connection Pool reset

### ISSUE THREAD

**Issue by livarcocc** [dotnet/efcore#8782]
_From @ushaharali on June 8, 2017 15:51_

We are looking for ways to reset connection pools. Basically if a sql server connection goes bad, we should be able to rest our connection pool.
There are ClearPool() and ClearAllPools() that are available with .net framework
Are there similar methods available for use in .net core ? Or what would be recommended way to achieve this?

_Copied from original issue: dotnet/cli#6803_

**Comment by anpete** [comment]
Those methods are available in .NET core.
