### ISSUE TITLE
Error about foreign key conflicts

### ISSUE THREAD

**Issue by vwzhang** [dotnet/efcore#8784]
Create a simple model class
```C#
class Person { 
public int ID { get; set; }
public string Name { get; set; }
[ForeignKey("Father")]
public int FatherID { get; set; }
[ForeignKey("Mother")]
public int MotherID { get; set; }

public Person Father { get; set; }
public Person Mother { get; set; }
}
```

Cannot create database. The error message is about foreign key conflicts. Using EntiryFramework Core 1.0 with Visual Studio 2017

**Comment by vwzhang** [comment]
Can anybody tell me what I did wrong?

**Comment by smitpatel** [comment]
I was looking at this. Basically you have foreign key cycles with multiple cascade paths which SqlServer doesn't support. You may need to configure your foreign key as Restrict instead of cascade for it to work.
I am trying to find good explanation of that somewhere already available.

**Comment by ajcvickers** [comment]
@vwzhang See this comment for more info: https://github.com/aspnet/EntityFramework/issues/5871#issuecomment-228866687

**Comment by vwzhang** [comment]
I wish there be schema annotation for this circumstance. Basically, I don't need the inverse property. We do this kind of model all the time with EF6 database first. It never cost me any problem. I imported model from  database with EF7 successfully but it created two inverse properties: InverseFather and InverseMother.

**Comment by ajcvickers** [comment]
@vwzhang You can remove the inverse properties if you want. I don't think that there is anything fundamentally different about how EF6 and EF Core handle these mappings.
