### ISSUE TITLE
Test: Verify if ConventionDispatcherTests are checking correct thing

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#8811]
There are quite a few places in these tests where assertion is commented out. Make sure that we are not having any bugs and remove the commented code if not necessary.

**Comment by AndriySvyryd** [comment]
Some of the convention types don't have a way of stopping the following conventions of the same type from running. None of the current conventions need this, but it should be added as part of https://github.com/aspnet/EntityFramework/issues/214. The commented assertions are there to add test coverage faster.
