### ISSUE TITLE
Support per-operation collation using EF.Functions.Collate() or equivalent 

### ISSUE THREAD

**Issue by OpportunityLiu** [dotnet/efcore#8813]

**Comment by divega** [comment]
@OpportunityLiu can you explain how what you propose would behave and what makes LIKE a good place to add the ability to specify collations? It seems to me it would be useful to be able to specify collations for all string values passed to the database in queries, not just for LIKE.

**Comment by OpportunityLiu** [comment]
I prefer somesthing like `Like(string matchExpression, string pattern,string escapeCharacter, Collation collate)`, where `Collation` is an enum of valid collate names for COLLATE.

It would be great if it works for all string queries, but how?  
A possible design is an extension method `AsCollation(this string dbString, Collation collate)`, but the type `string` is too common, I don't think it is a good idea to add a extension method for such a type. Or the method should be a common static method (just remove the `this`).

By the way, there should be an approach to specify the collation when creating a table or adding a column.

**Comment by divega** [comment]
@OpportunityLiu The [basic SQL Server example](https://docs.microsoft.com/en-us/sql/t-sql/statements/collations#a-specifying-collation-during-a-select) could look like this:

``` C#
var q = 
    from loc in context.Locations
    orderby EF.Functions.Collate(loc.Place, Collations.Latin1_General_CS_AS_KS_WS)
    select loc.Place;
```

Yes, it should not be an extension method.

**Comment by divega** [comment]
> By the way, there should be an approach to specify the collation when creating a table or adding a column.

For columns it is apparently already possible to append the collation to the store type. For database we should have a separate feature.

**Comment by ajcvickers** [comment]
See also comments here: https://github.com/aspnet/EntityFrameworkCore/issues/10539

**Comment by VahidN** [comment]
It would be great if you add [DbCollate] the same as SQLite's [DbFunction] to EF Core. Because it's possible to override the `OnConfiguring` method and add `connection.CreateCollation` but how about the LINQ queries with `fieldName COLLATE xyz`? It should be manged by EF internally.

**Comment by smitpatel** [comment]
cc: @roji

**Comment by roji** [comment]
Oh nice to know this issue already exists. Something like `EF.Functions.Collate()` would definitely work for the PostgreSQL per-column collation case.

**Comment by sametoz** [comment]
Is there an development on this topic?

**Comment by roji** [comment]
This issue is in our backlog milestone. That means we don't have immediate plans to work on it.

**Comment by roji** [comment]
Note: on MSSQL, when a column's collation is case-insensitive (the default), we can translate string.Equals with StringComparison.Ordinal as:

```sql
SELECT * FROM data WHERE name = 'hello10000' and name = 'hello10000' COLLATE Latin1_General_CS_AS;
```

This uses the index and is efficient (see https://github.com/dotnet/efcore/issues/1222#issuecomment-582786868).

**Comment by ajcvickers** [comment]
Also see high-level collations issue #19866

**Comment by roji** [comment]
Here's a bit of research into the COLLATE expression in queries across databases. tl;dr all databases accept literals only as the collation name, but quoting differs slightly (so SQL generation may require tweaking). Also, re operator precedence, in general COLLATE binds very tightly, but we should possibly look further to understand if we need to put parentheses in some situations.

# Collation name parameter

## PostgreSQL

The collation name is a regular identifier following PostgreSQL rules (like table/column name, can even have a schema); must be double-quoted when containing special characters (or upper-case).

```sql
SELECT 'hello' COLLATE "en-US-x-icu"; -- works (quoted identifier)
CREATE COLLATION some_collation (provider = icu, locale = 'und-u-ks-level2', deterministic = false);
SELECT 'hello' COLLATE some_collation; -- works (unquoted identifier)
SELECT 'hello' COLLATE "en-US" || "-x-icu"; -- concatenation not supported (identifier, not a text literal)
```

## SQL Server

Literal only [according to the docs](https://docs.microsoft.com/en-us/sql/t-sql/statements/collations?view=sql-server-ver15#arguments). Cannot be quoted - is a bare word.

```sql
SELECT 'hello' COLLATE Latin1_General_CS_AS_KS_WS;
SELECT 'hello' COLLATE [Latin1_General_CS_AS_KS_WS]; -- doesn't work
SELECT 'hello' COLLATE 'Latin1_General_CS_AS_KS_WS'; -- doesn't work
SELECT 'hello' COLLATE Latin1_General + CS_AS_KS_WS; -- concatenation not supported
```

## Sqlite

Weirdly permissive with regards to quoting rules, but still permits only literals:

```sql
SELECT 'hello' COLLATE BINARY; -- works
SELECT 'hello' COLLATE "BINARY"; -- works
SELECT 'hello' COLLATE 'BINARY'; -- work
SELECT 'hello' COLLATE ('BIN' || 'ARY'); -- concatenation not supported
```

## MySQL

```sql
SELECT 'hello' COLLATE utf8mb4_german2_ci; -- works
SELECT 'hello' COLLATE 'utf8mb4_german2_ci'; -- works
SELECT 'hello' COLLATE CONCAT('utf8mb4','_german2_ci'); -- doesn't work
```

**Comment by roji** [comment]
Based on the above analysis and our design discussion, we'll be bringing this in for 5.0. This includes

* An EF.Functions.Collate() extension function
* A CollateExpression SQL expression to which it is translated
* Query SQL generation for that expression

**Comment by roji** [comment]
Added doc note on EF.Functions.Collate about index/perf impact. I think there's nothing more pending here @smitpatel.

**Comment by lixaotec** [comment]
Dont know if its already planned, but would be nice to have a 
WHERE name LIKE '%joão%' COLLATE Latin1_General_CS_AS (EF.Functions.Like)

**Comment by roji** [comment]
Yeah, this is supported, you can try out the latest preview or dailies:

```c#
_ = ctx.Blogs
    .Where(b => EF.Functions.Like(EF.Functions.Collate(b.Name, "Latin1_General_CS_AS"), "%joão%"))
    .ToList();
```

Note that the collate is applied to the column instead of to the constant - because of #22317 - but the result is the same.
