### ISSUE TITLE
Use an EXE as Startup Assembly on EF.exe database update

### ISSUE THREAD

**Issue by marianosz** [dotnet/efcore#8838]
Trying to run migrations from the EF.exe tool on microsoft.entityframeworkcore.tools.dotnet 1.0.1 for net451, when the startup assembly is packed as an EXE (web app on ASP.NET Core with NET 461 as base FWK) , the tool doesn't work

This is the command that I'm running:

ef.exe database update --assembly .\Project.Entities.dll --startup-assembly .\Project.Web.exe  --context Project.Entities.DContext --verbose

output:
Using assembly 'Project.Entities'.
Using startup assembly 'Project.Web'.
Using application base 'C:\src\Project'.
Using content root 'C:\src\Project'.
Using root namespace 'Project.Entities'.
Using project directory 'C:\src\Project'.
Using configuration file '.\Project.Web.exe.config'.

System.IO.FileNotFoundException: Could not load file or assembly 'Project.Web' or one of its dependencies. The system cannot find the file specified.
File name: 'Project.Web'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass4_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<>c__DisplayClass4_0.<.ctor>b__4()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

### Further technical details
EF Core tools version: 1.0.1
Operating system: Windows
IDE: VS 2017

**Comment by bricelam** [comment]
Is it `Project.Web.exe` or `Project.Assembly.Web.exe`?

**Comment by marianosz** [comment]
Is Project.Web. I already edited the issue info.

**Comment by bricelam** [comment]
Do the [fusion logs](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) give any additional information (e.g. where it's looking)?

**Comment by marianosz** [comment]
I will check and let you know later. Thanks.

**Comment by marianosz** [comment]
There is no info on fuslogvw...

**Comment by marianosz** [comment]
*** Assembly Binder Log Entry  (6/13/2017 @ 14:13:11) ***

The operation failed.
Bind result: hr = 0x8007000b. An attempt was made to load a program with an incorrect format.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Users\sanch\.nuget\packages\microsoft.entityframeworkcore.tools.dotnet\1.0.0\tools\net451\ef.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Project.Web
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: Project.Web | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/src/Project/Release/PublishOutput
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = NULL
Calling assembly : Microsoft.EntityFrameworkCore.Design, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\src\Project\Release\PublishOutput\Project.Web.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/src/ProjectRelease/PublishOutput/Project.Web.DLL.
LOG: Attempting download of new URL file:///C:/src/Project/PublishOutput/Project.Web/SNOP.Project.DLL.
LOG: Attempting download of new URL file:///C:/src/Project/PublishOutput/Project.Web.EXE.
LOG: Assembly download was successful. Attempting setup of file: C:\src\Project\PublishOutput\Project.Web.exe
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Project.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ERR: Invalid assembly platform or ContentType in file (hr = 0x8007000b).
ERR: Run-from-source setup phase failed with hr = 0x8007000b.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

So the file is located, but seems that is not supporting the exe format

**Comment by bricelam** [comment]
Ah, it looks like your assembly is 32-bit. Try using `ef.x86.exe` instead.

**Comment by marianosz** [comment]
Is working! I cant believe how I miss that, I was sure that was compiling to x64. Thanks for your help!

**Comment by Aksmile148** [comment]
My project targetFramework is net452. 

When I try to run add-migration from a nugget package manager console, it pops up a dialog window box "ef.x86.exe"
When I clicked open, it shows the following error message 


add-migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with the null character.
Parameter name: basePath"
At line:1 char:1
+ add-migration LasbcaTb
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException,Add-Migration


Kindly help for solution please.

**Comment by bricelam** [comment]
@Aksmile148 Can you submit a new issue with a repro attached?
