### ISSUE TITLE
Support Integrated Security (Trusted Connections) on Linux

### ISSUE THREAD

**Issue by uriah-ascend** [dotnet/efcore#8839]
I have a requirement from our dbas that we use only trusted connections. We're trying to deploy our EF Core app to a debian docker container based on microsoft/aspnetcore:1.1.  Trusted connections do not appear to be supported in that environment unless I am missing something.

It is apparently possible with an ODBC driver on linux using the kinit tool:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication
https://www.easysoft.com/products/data_access/odbc-sql-server-driver/kerberos.html

When I tried to setup kinit just as a stab in the dark, I got "The keyword 'integrated security' is not supported on this platform." So much for wishful thinking.  This would be a pretty useful feature to support going forward and I think I could push the conversation out if we knew it was in the works.

Thanks,
Uriah

**Comment by ErikEJ** [comment]
This is not a EF question, and look like it will be fixed in .NET Core 2.0 https://github.com/dotnet/corefx/issues/4198

**Comment by uriah-ascend** [comment]
Thanks @ErikEJ , apologies for the misreport.
