### ISSUE TITLE
SQLite RevEng: Allow tables without a primary key

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#8840]
If a table in SQLite doesn't have an explicit primary key, the implicit `rowid` column can be used to uniquely identify a row. We should map the `rowid` column to a property in this case.

**Comment by bricelam** [comment]
This is a better alternative to #5719 on SQLite

**Comment by ajcvickers** [comment]
We discussed this again in triage and it is not something we plan to implement at this time. However, it is something that we would consider taking a community PR for. Also, as with everything else, we could change our minds with enough feedback.
