### ISSUE TITLE
Access Model Relationships at runtime

### ISSUE THREAD

**Issue by jayslife** [dotnet/efcore#8866]
I am looking to access the EF Model relationships via my dbcontext and currently don't see a way to accomplish this. 

I know that i have access to this type of information during OnModelCreating via the ModelBuilder, because we are currently able disable cascade deleting any persons by gaining access to all foreign keys. ex.

`foreach (var relationship in modelBuilder.Model.FindEntityType(typeof(Person)).GetReferencingForeignKeys())
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }`

However, I'm not sure is this type of information is accessible during something like the save of a record.

Simple Model Setup

 public class Person
    {
        [Key]
        public virtual int Id { get; set; }
        public virtual string PriorLastName { get; set; }
        public virtual int AddressId { get; set; }
        public virtual Address PersonAddress { get; set; }
        ...
    }

 public class Address
    {
        [Key]
        public virtual int Id { get; set; }
        public virtual string Line1{ get; set; }
        public virtual int Line2 { get; set; }
        ...
    }

Use Case:
When calling a save directly to address repo, which in turn calls save to dbcontext. If i had access to the foreign key's of address, it would return that a foreign key to person exists. I am now able to run the code i need to run for all persons that have an address id of the address being saved. 

For my real life scenario the person along with its address is pushed out to an external system.

Note: Please keep in mind, I have simplified the example in this ticket. This is needed for a larger scale scenario. I mention this because I know the someone will come back with just save the Person with the address, which is not possible in my real life situation.

### Further technical details
EF Core version: 1.1.2
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@jayslife DbContext.Model?

**Comment by jayslife** [comment]
Thank you @ajcvickers, this must have been the easiest ticket all day....lol! Not sure how I missed that.

Thank you for your help!
