### ISSUE TITLE
DbContextModelSnapshot cannot be updated because it is readonly when using TFS

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8870]
(From https://developercommunity.visualstudio.com/content/problem/47317/entity-framework-7-code-first-migration-issue-when.html)

Use a .Net Core solution under source control ( Team Services) -In package Manager console, add-migration without checking out DbContextModelSnapshot.cs -After the migrations script are created, DbContextModelSnapshot.cs cannot be updated because is read-only. What I expect is that Add-Migration automatically check-out the Snapshot file (as in previous version of visual Studio), to avoid the error.

**Comment by ajcvickers** [comment]
@bricelam Please push back if we can't do this for some reason.

**Comment by bricelam** [comment]
I'll look into it, but I'm doubtful. We write the files in `ef.exe` which has no knowledge of version control.

**Comment by bricelam** [comment]
We decided not to do anything special here. If you are using TFS, you should either checkout the model snapshot before adding a migration or use a local workspace which prevents TFS from making the files read-only.

**Comment by vassiliospallis** [comment]
Nice decision. Kudos.

**Comment by vassiliospallis** [comment]
And how you explain the fact that for some projects the auto checkout happens automatically and for some others it doesn't? Instead of closing the ticket rapidly we would expect to check it more deeply.
