### ISSUE TITLE
No DbContext was found in assembly 'Library.Web'. Ensure that you're using the correct assembly and that the type is ne ither abstract nor generic

### ISSUE THREAD

**Issue by smithaitufe** [dotnet/efcore#8873]
I have been struggling with this for a while now.

I have a solution that contains four projects.

Here is the github repository.

https://github.com/smithaitufe/library

I want to be able to create Migrations in Library.Web. The Library.Web project uses Library.Core and Library.Repo projects.

The connection string is defined in Library.Web.

But whenever I run dotnet ef migrations add Initial, I receive this error

```
No DbContext was found in assembly 'Library.Web'. Ensure that you're using the correct assembly and that the type is ne
ither abstract nor generic
```

Please what should I do?

**Comment by bricelam** [comment]
Add a class that looks something like this to Library.Web.
```C#
class LibraryDbContextFactory : IDbContextFactory<LibraryDbContext>
{
    public LibraryDbContext Create(string[] args)
        => Program.BuildWebHost(args).Services.CreateScope().Services
            .GetRequiredService<LibraryDbContext>();
}
```

**Comment by smithaitufe** [comment]
I am seeing this error

```
'IServiceScope' does not contain a definition for 'Services' and no extension method 'Services' accepting a first argument of type 'IServiceScope' could be found (are you missing a using directive or an assembly reference?) [Library.Web]

```

**Comment by bricelam** [comment]
Sorry, looks like the property is called `ServiceProvider`.
