### ISSUE TITLE
ComplexType preview1

### ISSUE THREAD

**Issue by day01** [dotnet/efcore#8874]
I am trying to add complexType (as a value type) to my entity. I am generating migration and in migration: 
```
migrationBuilder.CreateTable(
                name: "TABLENAME_Modified",
                schema: "SCHEMA",
                columns: table => new
                {
                    TABLENAMEId = table.Column<long>(nullable: false),
                    Date = table.Column<DateTime>(nullable: false),
                    UserId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TABLENAME_Modified", x => x.TABLENAMEId);
                    table.ForeignKey(
                        name: "FK_TABLENAMEs_Modified_TABLENAMEs_TABLENAMEId",
                        column: x => x.TABLENAMEId,
                        principalSchema: "SCHEMA",
                        principalTable: "TABLENAMEs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```

### Steps to reproduce
```c#
public AuditField Modified { get; set; }
```

```c#
[ComplexType]
    public class AuditField
    {
        public int UserId { get; set; }
        public DateTime Date { get; set; }
        public override string ToString()
        {
            return $"By {UserId}, when {Date}";
        }
    }
```

```c#
entityTypeBuilder.OwnsOne(x => x.Modified);
```

Is it correct behavior or my configuration is wrong?
I expected complexType properties will be in the same table sth like Modified__UserId column.

### Further technical details
EF Core version: 2.0.0-preview1-final
Database Provider: Postgresql
Operating system: win10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
Your configuration is correct. (You don't need `ComplexTypeAttribute` on your entity though).
The only thing is the feature to map complex type properties in same table as owner entity type was not in 2.0.0-preview1 release. It was added afterwards. It will be available in 2.0.0-preview2 release which will be release this month. Once you upgrade to that you will be get those properties in same table just like complex type in EF6
