### ISSUE TITLE
Context.Entry() doesn't return the same EntityEntry when called twice

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#8875]
`Context.Entry(this)==Context.Entry(this)`
Returns false. I'm not sure if this is working as intended - the documentation doesn't mention anything about it, and I don't see why it wouldn't return the same instance.

**Comment by ajcvickers** [comment]
@Wain123 Currently you will get a new instance each time. This is because these types are facades over internal types. It's possible that we could choose to cache them at some point in the future, but I think that would be unlikely.
