### ISSUE TITLE
Relational: Consider removing "async" keyword from async MoveNext methods

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#889]
The async `MoveNext` methods in general only needs to use `await` on the first row and can pass through the `Task<bool>` from the underlying reader for subsequent rows. That is nice because it means less async state machine overhead on multi-row materialization.

However there is additional work that we do in the MoveNext method which blocks than from happening:
1. We are initializing the _current field using the shaper inside the method. We can easily move that to the Current property getter.
2. We are manually disposing the underlying async enumerator as a workaround for Reactive-Extensions/Rx.NET#5, which should be fixed there.

**Comment by AndriySvyryd** [comment]
@divega I think this is a wont fix now, we have to coordinate results from related readers.

**Comment by smitpatel** [comment]
- Shaper is not async.
- The only part we do async is moving the datareader to next row.
- Multi-row materialization does not return on MoveNext till all the rows needed to materialize has passed through.
- MoveNextAsync comes from IAsyncEnumerator
- It return ValueTask<bool>

I think we have all the optimization needed already.

**Comment by divega** [comment]
The original idea behind this was to defer the work on the shaper util .Current is called. That way they implementation for MoveNextAsync for all but the first row could just be non-async (hence no async state machine overhead) and just call the underlying async method to read from the database as the tail call.

But it is likely that this is now unnecessary in the new pipeline. I would expect implementing https://github.com/aspnet/EntityFrameworkCore/issues/17391 to have more benefits.
