### ISSUE TITLE
net461 SQL Server tests attempt to create scratch database in unwritable folder

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#8896]
**Details**
Using dotnet-CLI 2.0.0-preview2-006484
Using the dotnet.exe on system PATH.
Only affects .NET Framework tests

**Repro**

Install latest preview2-CLI
https://github.com/dotnet/cli/tree/release/2.0.0-preview2#installers-and-binaries

```
git clone https://github.com/aspnet/EntityFramework.git --branch dev
cd EntityFramework/test/EFCore.SqlServer.FunctionalTests/
dotnet restore
dotnet test --framework net461 --filter ExistsAsync_returns_true_when_database_with_filename_exists
```

**Result**

> Failed   Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorExistsTest.ExistsAsync_returns_true_when_database_with_filename_exists
Error Message:
 System.Data.SqlClient.SqlException : CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Program Files\dotnet\sdk\2.0.0-preview2-006484\TestHost\Scratch_c0b55f28-4650-468d-84df-e02f5f96b6d7.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.

**Comment by bricelam** [comment]
Last time I investigated similar errors, something about the way VSTest was running tests (possibly related to AppDomain setup) was preventing LocalDB from being able to access the user's profile resulting in a worse-than-usual default database directory.

**Comment by ajcvickers** [comment]
Created https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?id=453058&_a=edit for this and marking this as external and blocked.
/cc @divega @Eilon
