### ISSUE TITLE
Databinding: Guide users to not bind against DbSet.Local directly

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#8898]
In EF Core `DbSet.Local` is more efficient than in EF6 but doesn't have stable order, so it is not good for databinding. For databinding you are supposed to call `ToObservableCollection` (for the WPF flavor) or `ToBindingList` (for the WinForms flavor). 

This is already in the XML documentation but nothing prevents users from binding directly to `DbSet.Local`.

We should consider implementing `IListSource.GetList()` to throw an informative exception like we do for query, but we also need to verify that doing so will help for WPF.

**Comment by ajcvickers** [comment]
Leaving open to answer the WPF question.

**Comment by divega** [comment]
Note for triage: This issue had one question pending: I tried binding in a WPF to an observable collection that implements IListSource and GetList was called. 

Given that in 3.0 we want to have better WPF/WinForms support, I would like to discuss if we want to do this (if we decide not to do it, maybe we should close the issue?). 

On the other hand, this reminded me of https://github.com/aspnet/EntityFrameworkCore/issues/14231, which was recently reported and says DbSet.Local isn't good for iterating either... I can't remember what DbSet.Local is good for :trollface:.

**Comment by ajcvickers** [comment]
I started to work on this, but it turns out that we already did this for 2.0. See https://github.com/aspnet/EntityFrameworkCore/pull/9003

The only reason this issue was still open was to check if WPF calls the method, which has now been done., so closing.

**Comment by OlegFj17** [comment]
Sorry to interrupt you. Maybe you can help.. If I bind Local.ToObservableCollection() to for exapmle DataGrid it works fine. But do I understand correctly that with this context I can only make synchronous queries to the database? Because otherwise Local collection changed from nonUI thread and an exception is thrown about that ICollectionView cannot be changed from non UI thread..  Thank you!

**Comment by ajcvickers** [comment]
@roji I think this is a consequence of `ConfigureAwait false`. Fixup can now happen in a different thread, and this then means that events in the observable collection (or other notifications) are triggering calls into the U.I. on the non-U.I. thread.

/cc @AndriySvyryd

**Comment by roji** [comment]
@ajcvickers we did do #23971 to preserve the synchronization context when accepting changes - is there something here with Local.ToObservableCollection that goes beyond that (am not too familiar with that...)?

**Comment by ajcvickers** [comment]
@roji Yes, it gets called when materializing entities/doing fixup after _queries_.

**Comment by roji** [comment]
Ok. Just to make sure given the issue title: is this something we want to recommend/support? ( I have no opinion here whatsoever, just asking)

**Comment by roji** [comment]
Triage: I'll take a look to see if it could make sense to do ConfigureAwait(true) for this path, like we did for SaveChanges. Otherwise we could consider some sort of per-query or context option to just do true everywhere, if we think that's important.

**Comment by OlegFj17** [comment]
EnableCollectionSynchronization helped me! sorry to stir up your issue.. )

**Comment by ajcvickers** [comment]
Opened https://github.com/dotnet/efcore/issues/27533
