### ISSUE TITLE
Migration commands don't work in VS .NET Core project

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#8900]
`Add-Migration` and the other commands aren't available in the PMC after restoring and building the project.

Console app targeting netcoreapp2.0
VS 15.3 Preview 3.0 26615.0.d15rel
.Net Core SDK 2.0.0 Preview2 6484
Microsoft.EntityFrameworkCore.Tools 2.0.0-preview2-final
Feed: https://dotnet.myget.org/gallery/dotnet-2-0-0-preview2-final/

**Comment by bricelam** [comment]
This is an external (NuGet) issue. EF's `init.ps1` isn't being invoked.

A few things that have helped in the past:
* Run `Set-ExecutionPolicy RemoteSigned` as an administrator and try again
* Close the PMC window, restart VS, open the solution, then open PMC and try again

**Comment by AndriySvyryd** [comment]
Updating to 26616.2.d15rel seems to have fixed this
