### ISSUE TITLE
Error configuring cascade delete on self referenced model

### ISSUE THREAD

**Issue by helderboone** [dotnet/efcore#8903]
```
public class Foo
    {
        public int Id { get; set; }           

        public virtual Foo Parent { get; set; }

        public int? ParentId { get; set; }

        public virtual ICollection<Foo> Branches { get; set; }
    }
```

Hi! I'm trying to configure a self referenced model to  cascade delete when deleting its parent. I have tried configuring in this two ways: 
```
builder.HasMany(a => a.Branches)
                   .WithOne(a => a.Parent)
                   .HasForeignKey(a => a.ParentId)
                   .OnDelete(DeleteBehavior.Cascade);
```
```
            builder.HasMany(a => a.Branches)
                   .WithOne(a => a.Parent)
                   .OnDelete(DeleteBehavior.Cascade);
```

However both configs are throwing Foreign key constraint 'FK_Foo_Foo_ParentId' on table 'Foo' may cause cycles or multiple cascade paths when I try to update the database.

**Comment by ajcvickers** [comment]
This is a SQL Server limitation.  See https://github.com/aspnet/EntityFramework/issues/6956#issuecomment-258908700 for more info.
