### ISSUE TITLE
DbContext with Async queries

### ISSUE THREAD

**Issue by romil-zealous** [dotnet/efcore#8908]
Hello,

EF: 6.1.3

When I use any async methods such as .ToListAsync(), .FirstOrDefaultAsync() etc, my query execution freezes and it never returns anything. If I use synchronous methods such ash .ToList() on same DbContext, then I get the results which is expected.
I am not able to understand what is the issue with async methods. Please help.

Regards,
Romil

**Comment by vladislav-karamfilov** [comment]
This is the EntityFramework Core repo. You should ask your question in EF6 repo here: https://github.com/aspnet/EntityFramework6
