### ISSUE TITLE
Consider porting fix for Migrations: AlterColumn tries to drop non-existing index on SQL Server (#7535) to a 1.1 patch

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#8930]
See #7535.

**Comment by BennyM** [comment]
Yes please

**Comment by ajcvickers** [comment]
Marking for re-triage as it is not clear that this meets the current bar for a patch.

**Comment by bricelam** [comment]
The workaround is pretty painful, but `2.0.0` is out now so I could go either way...
