### ISSUE TITLE
Two-stage migrations (compatibility/staging mode)

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#8932]
Add a way of generating separate scripts for just the non-breaking changes and for the breaking changes. This would allow the previous version of the application to continue to work against the database while the new version is being deployed/tested.
The pattern is sometimes called “Expand/Contract Migrations” because it groups migrations into two categories: Those that are non-destructive expansions of the DB schema and those that are destructive contractions of the schema.

**Comment by ajcvickers** [comment]
@AndriySvyryd Can you add a bit more explanation, like what we did in triage.

**Comment by AndriySvyryd** [comment]
It's currently possible to do it manually by carefully planning out the changes. As the first improvement we could add a flag to validate that the new migration has no breaking changes.

**Comment by bricelam** [comment]
Possibly covered by aspnet/EntityFramework.Docs#691

**Comment by ajcvickers** [comment]
We discussed this again and decided that, beyond guidance (possibly a case study) there is nothing we're going to do here.
