### ISSUE TITLE
Logging DbCommands: Can the logger know which context executed the command?

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#8934]
The ILogger has the following function declaration:
`void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);`
When logging a DbCommand, as far as I can tell, none of the parameters tell you which context executed the command. Is it possible to access this information in the logger?

**Comment by ajcvickers** [comment]
@Wain123 ILogger, while theoretically supporting arbitrarily structured data, doesn't really do this when used in the recommended way. It instead supports strings where some parts of the string are also added to state in a structured way.

For the 2.0 release, if you want to get events with correlation, then look into using DiagnosticSource instead. DiagnosticSource events have correlation IDs for command and connections. We don't correlate the context yet (although we might do that for some events in the future) but usually the context and the connection are 1:1, so it should give you what you need.
