### ISSUE TITLE
Request: Interception point after entities are created

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#8937]
I have a query like this:
```
foreach(var post in ctx.Posts){
  post.DoStuff();
}
```
I would like to have an interception point after the constructors of all Posts are finished, but before DoStuff is first called. The latest interception point that's available to the ILogger is after the results of the query are fetched from the DB, but still before the constructors, so that's too early.

The reason I need this interception point is that I want to call a function "void Init()" on each post I load from the DB. I can't call Init in the Post constructor, because Init can make a DB query, and I would get a System.InvalidOperationException: 'A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.'

**Comment by ajcvickers** [comment]
@Wain123 This is part of #626 which unfortunately didn't make it for 2.0, but is a high priority for us.
