### ISSUE TITLE
Unseal all attributes

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#8943]
Because we don't seal things unless we really need to...

Attributes are:
* DbContext
* DbFunction
* DesignTimeProviderServices
* Migration
* NotParameterized

**Comment by ajcvickers** [comment]
Discussed in triage and decided not to do this. If we ever get a request to unseal them, then we'll re-consider.

**Comment by StingyJack** [comment]
@ajcvickers  - Please unseal the `KeyAttribute` so I can specifically identify and differentiate Primary keys, Surrogate Keys, and Natural Keys.

**Comment by ajcvickers** [comment]
@StingyJack `KeyAttribute` is not defined by EF Core. It comes from Microsoft.ComponentModel.Annotations. Regardless, this has been discussed before and there are no plans to unseal it.
