### ISSUE TITLE
DbContext.Update does not flag properties as modified when they are part of Unique Constraint

### ISSUE THREAD

**Issue by SergeyBarskiy** [dotnet/efcore#8948]
Describe what is not working as expected.
DbContext.Update does not flag properties as modified when they are part of Unique Constraint, thus they are not included in update statements

### Steps to reproduce

I have a simple Person model:
public class Person
    {

        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Height { get; set; }
        public bool IsActive { get; set; }
        public DateTime? BirthDate { get; set; }

        public virtual ICollection<PersonPhone> PersonPnones { get; set; } = new HashSet<PersonPhone>();

        public int? PersonTypeId { get; set; }
        public virtual PersonType PersonType { get; set; }

       
    }
I add a unique constraint
modelBuilder.Entity<Person>().HasAlternateKey(a => new { a.LastName, a.FirstName }).HasName("UQ_LNAME");

I create person instance and send to Update method while changing values for last name
_context.Update(person);
 _context.SaveChanges();

...the update statement in SQL Server does not contain string properties:
exec sp_executesql N'SET NOCOUNT ON;
UPDATE [Contacts].[People] SET [BirthDate] = @p0, [Height] = @p1, [IsActive] = @p2, [PersonTypeId] = @p3
WHERE [PersonId] = @p4;
SELECT @@ROWCOUNT;

UPDATE [Contacts].[PersonPhones] SET [PersonId] = @p5, [PhoneNumber] = @p6
WHERE [PersonPhoneId] = @p7;
SELECT @@ROWCOUNT;

UPDATE [Contacts].[PersonPhones] SET [PersonId] = @p8, [PhoneNumber] = @p9
WHERE [PersonPhoneId] = @p10;
SELECT @@ROWCOUNT;

',N'@p4 int,@p0 datetime,@p1 decimal(2,1),@p2 bit,@p3 int,@p7 int,@p5 int,@p6 varchar(8000),@p10 int,@p8 int,@p9 varchar(8000)',@p4=1,@p0='2017-06-20 00:00:00',@p1=5.5,@p2=1,@p3=NULL,@p7=1,@p5=1,@p6='777-888-9999',@p10=2,@p8=1,@p9='778-990-1234'

### Further technical details
EF Core version: 2.0 preview 1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
EF Core does not allow modifying values of an alternate Key. (Just like primary key)
If you are just looking to enforce uniqueness on properties then unique index would be a better choice.

**Comment by SergeyBarskiy** [comment]
Thanks, @smitpatel 
That is what I figured, but that this seems counter-intuitive to me.  Based on my experience alternate keys are used to control duplicates for user-entered data, whereas primary keys are typically system generated.  Based on this seems like I should be able to update alternate keys columns value or how for example the end user can fix a mistake made when inserting the data?

**Comment by smitpatel** [comment]
The main purpose of alternate key (which makes them different from unique index) is to be target of a foreign key constraint. In SqlServer alternate key or unique index are pretty similar but they are not interchangeable. Alternate keys enforce uniqueness using unique index only.

For your case, you just want to control duplicates then unique index is right thing to use. It will avoid duplicates and allow to correct errors made in insertion.
On the other hand if you are using alternate key then any correction in data has to propagate all FKs pointing to it. Which may cause more updates throughout the database. Therefore, at present EF Core does not allow updating value of key (either primary key or alternate key). PK is usually value generated, same way foreign key constraint usually target primary key of table. But that is not case always. So EF treats PK/AK similarly hence no updates allowed.
P.S. SqlServer allows updating values of even primary key columns.
