### ISSUE TITLE
Cannot use EF Core 2.0 preview in "classic" class library

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#8954]
Trying to use EFCore.Relational 2.0-preview2-final in a .NET 4.6.1 class library fails:

Feed: https://dotnet.myget.org/F/dotnet-2-0-0-preview2-final/api/v3/index.json 

*Error*
1>C:\Users\xxx\Source\Repos\ClassLibrary1\Class1.cs(10,32,10,41): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Step to repro: 
1: Add new Class lib, target .NET 4.6.1
2: Add class:
````
using Microsoft.EntityFrameworkCore;
namespace ClassLibrary1
{
    public class TestContext : DbContext
    {
    }
}
````
3: Build

### Further technical details
EF Core version: 2.0-preview2-final
Database Provider: N/A
Operating system: Win 10
IDE: VS 2017 15.3.0 preview 2.1

**Comment by ErikEJ** [comment]
Yes, I need to use NuGet 4.3.0, which is only available in VS 2017 15.3 preview

**Comment by bricelam** [comment]
Does manually installing the `NETStandard.Library.NETFramework` package help?

**Comment by ajcvickers** [comment]
This should be fixed when the next public release of VisStu gets shipped. Please re-open or file a new issue if this still fails after the bits are available publicly.

**Comment by ErikEJ** [comment]
@bricelam Yes, it does. @ajcvickers Thanks, I will muddle along with Brice's workaround (updating the SQL CE provider to preview2)
