### ISSUE TITLE
Add PropertyBuilder access to DiscriminatorBuilder

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#8961]
Currently to configure a facet on the discriminator column you would need to do this:
```C#
modelBuilder.Entity<MyEntity>().HasDiscriminator<string>("Discriminator");
modelBuilder.Entity<MyEntity>().Property<string>("Discriminator").HasColumnName("SharedDiscriminator");
```

We could make this terser by adding an overload for nested closure:
```C#
modelBuilder.Entity<MyEntity>().HasDiscriminator<string>("Discriminator", db =>
        db.HasColumnName("SharedDiscriminator"));
```

**Comment by ajcvickers** [comment]
You're making it look worse than it is. 😸 
```C#
modelBuilder.Entity<MyEntity>(b =>
    {
        b.HasDiscriminator<string>("Discriminator");
        b.Property<string>("Discriminator").HasColumnName("SharedDiscriminator")
    });
```

**Comment by ajcvickers** [comment]
Discussed in triage and decided not to do this. It's really no different from other cases at this level--like making a key and setting the property as store-generated. And we had previously decided to not add additional nested closures at this level.
