### ISSUE TITLE
Disable _EFMigrationsHistory (HistoryRepository) when generating scripts in migrations

### ISSUE THREAD

**Issue by mackvatoloco** [dotnet/efcore#8970]
While there are ways to customize the HistoryRepository (like renaming table, renaming columns, etc). There is no current way to disable the feature. 

We currently use EFCore migrations to create the migrations files and the scripts for those migrations per provider (we use SqlServer and MySql providers). We never use EFCore migrations to modify the database directly. We build a tool that does that using the generated scripts to have more control on versioning (we add more information like who created the db or who upgrade it) and script management (being able to modify the script before applying it for complex scenarios).

Everything works great, except we don't use the _EFMigrationsHistory at all. And since we don't ever use migrations to create/modify the database, neither does EFCore apparently. We can of course manually remove the create and insert portions for _EFMigrationsHistory from the script, but we would like to automate this process.

I've tried to use my own HistoryRepository and returning empty strings for scripts. But there are problems with this approach because the client for HistoryRepository (the Migrator) sometimes validates empty scripts. If I provide a comment line it would work but the migrator still adds the _sqlGenerationHelper.BatchTerminator (for SqlServer is "GO"+newline+newline), so there still some manual work to do. 
Here's my HistoryRepository:
```c#
public class MySqlServerHistoryRepository : SqlServerHistoryRepository
	{
		public MySqlServerHistoryRepository(
			IDatabaseCreator databaseCreator, IRawSqlCommandBuilder rawSqlCommandBuilder,
			ISqlServerConnection connection, IDbContextOptions options,
			IMigrationsModelDiffer modelDiffer,
			IMigrationsSqlGenerator migrationsSqlGenerator,
			IRelationalAnnotationProvider annotations,
			ISqlGenerationHelper sqlGenerationHelper)
		: base(databaseCreator, rawSqlCommandBuilder, connection, options,
			modelDiffer, migrationsSqlGenerator, annotations, sqlGenerationHelper)
		{
		}

		#region Used to avoid EF history table in scripts
		public override IReadOnlyList<HistoryRow> GetAppliedMigrations() => new List<HistoryRow>();
		public override bool Exists() => true;
		public override Task<bool> ExistsAsync(CancellationToken cancellationToken = default(CancellationToken)) => Task.FromResult(true);
		public override string GetCreateIfNotExistsScript() => string.Empty;
		public override string GetBeginIfExistsScript(string migrationId) => string.Empty;
		public override string GetEndIfScript() => string.Empty;
		public override string GetBeginIfNotExistsScript(string migrationId) => string.Empty;
		public override string GetCreateScript() => string.Empty;
		public override string GetDeleteScript(string migrationId) => string.Empty;
		public override string GetInsertScript(HistoryRow row) => "--";
		#endregion
	}
```
I am not a fan of this types of solutions, I would rather have a simple way to not include the table at all. It could be by overriding something in the HistoryRepository or an option in migration script.

Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.MySql
Operating system: Any
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
We would consider a PR to add a flag --no-history, or similar.

**Comment by glucaci** [comment]
I've took a look on this and implies a signature change of `IMigrator.GenerateScript(...)` but this will be a breaking change.

Is the purpose of this interface to be used outside of EFCore?
- If yes then the signature of `IMigrator.GenerateScript(...)` is not to rigid for further changes ?
- If no then should not be excluded from ApiCheck or changed to internal ?
