### ISSUE TITLE
dotnet ef cli and msbuild tasks compiled for desktop msbuild

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#8985]
My project (vs2017) targets net452, and I have installed `gitversiontask` nuget package, which includes an msbuild task compiled with msbuild targeting full .net desktop version of msbuild.

When I build the project through `msbuild` the project builds as the msbuild task can be loaded and executed.

When I build the project through `dotnet cli` the build fails, because a dotnet cli build is not able to load the msbuild task from the assembly, assuming because the build process itself then runs under .net core.

However I can work around this for most cli operations because `dotnet cli` commands often just execute an msbuild target. So for example I can pack my project using `msbuild /t:pack` instead of `dotnet pack` etc and then my build is running under full msbuild desktop version, rather than .net core - and things work.

Some `dotnet cli` commands also have a `no-build` option. So for example, I could publish a project with the dotnet cli, and not trigger a build by using the `no-build` argument, which is useful if I have already handled the build myself via a `msbuild`. 

However `dotnet ef` commands do not have a `no-build` flag, so they always want to force a build (assuming this will be an incremental build) of the project. Unfortunately this leads to a few problems - I can;t use the dotnet ef cli commands because most of them force builds, and building my project under net core fails due to the reason I have highlighted. I am not sure how I can work around this, as I can't see any equivalent msbuild target to invoke for these commands, and I can't tell ef to"no-build" or build via desktop msbuild.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:

dotnet ef dbcontext scaffold --framework net452 --startup-project ../Reach.GCv3.Mvc.WebApplication "Data Source=*****;Initial Catalog=*****;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" "Microsoft.EntityFrameworkCore.SqlServer" -c GcDbContext -o Models -f -a -t Organisation -t Lkp_UserStatus -t User -t ReportCategory -t SecurityContextRoleUserMap -t SecurityRole -t Company -t CompanyGroup -t ReportContextMap -t SecurityContext -t Report -t SecurityReportUserMap -t ReportCategoryMap -t ReportTokenImage -t Campaign -t Callfile -t PeriodDay -t Survey -t SurveyItem -t QuestionVariant -t Supplier -t Lkp_SupplierTypes -t SupplierOrderType -t SupplierOrder -t SupplierOrderItem -t Outlet -t Lkp_OutletStatus -t Lkp_OutletType -t OutletAddress -t OutletMapSupplier -t Territory -t TerritoryMap -t Product -t ProductControl -t ProductControlMap -t OutletGroup -t OutletGroupMap -t OutletGroupMapDeleted -t ProductDiscount -t ProductBrand -t ProductPrice -t Lkp_PriceType -t Lkp_ProductGroup -t Lkp_SupplierOrderApprovalRuleType -t SupplierOrderTypeApprovalRule -t Lkp_SupplierOrderStatus -t StockOnHand -t OrderSystemConfig -t OrderSystemConfigCompanyValues -t Lkp_NotificationType -t Notification -t Lkp_MessageType -t UserNotification -t UserEmailNotification -t Device -t UserDevice -t UserDeviceNotification -t SupplierOrderNotification -t CompanyOrderTag -t SupplierOrderTagMap -t ConfigurationSetting -t FileEntry -t UserEmailNotificationAttachment -t SupplierOrderTemplate -t Lkp_SupplierOrderTemplateType -t SupplierOrderFileEntry -t CompanyReportOrder -t ClientApplication -t ClientApplicationVersion -t UserDeviceClientApplicationVersionMap -t UserHomePage -t Lkp_FileType
C:\Users\darrell.tunnell\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\darrell.tunnell\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\darrell.tunnell\Source\Repos\gc3-website\src\Reach.GCv3.DatabaseHelpers\Reach.GCv3.DatabaseHelpers.csproj]
C:\Users\darrell.tunnell\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\darrell.tunnell\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\darrell.tunnell\Source\Repos\gc3-website\src\Reach.GCv3.BusinessCore\Reach.GCv3.BusinessCore.csproj]
C:\Users\darrell.tunnell\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.targets(49,5): error MSB4062: The "GitVersionTask.WriteVersionInfoToBuildLog" task could not be loaded from the assembly C:\Users\darrell.tunnell\.nuget\packages\gitversiontask\4.0.0-beta0012\build\GitVersionTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\darrell.tunnell\Source\Repos\gc3-website\src\Reach.Excel\Reach.Excel.csproj]
```
I am aware that a solution to this problem is for gitversion task to be compiled for .net core so that the msbuild tasks can run under net core - I don't dispute that. However I do think that `dotnet ef` cli forcing a build under net core - when in my circumstance I know that a build is not required (because I am handling the build myself via msbuild) is a problem and that there should be a way to specify "no-build".

### Steps to reproduce
Create a new project, target net452, add nuget package gitversiontask version 4.0.0 beta 0012, add relevent EF db context code, then try to run dotnet ef commands.

### Further technical details
EF Core version: 1.0.3
Microsoft.EntityFramework.Core.SqlServer.Design(1.0.3)
Microsoft.EntityFramework.Core.SqlServer(1.0.3)
Microsoft.EntityFramework.Core.Tools (1.0.0)
Operating system: Win10 
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
Is using the PMC Tools (Add-Migration and friends) an option?

The CLI tool needs to read project metadata using `dotnet msbuild` in order to work.

**Comment by dazinator** [comment]
Good idea i'll try the powershell approach

**Comment by ajcvickers** [comment]
Discussed this in triage and decided that ultimately the MSBuild task needs to be built to work with .NET Core. Beyond that, using VS/PowerShell approach may be the way to go. Closing since there is nothing actionable for EF here.

**Comment by dazinator** [comment]
Ok, thanks for giving it your consideration. Im going to help port that build task!
