### ISSUE TITLE
Requiring Microsoft.EntityFrameworkCore.Design for EF CLI?

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/efcore#8994]
Describe what is not working as expected.
I'm curious why Microsoft.EntityFrameworkCore.Tools.DotNet requires Microsoft.EntityFrameworkCore.Design at runtime, but it's not a straight-up dependency? It makes it easy to forget to include the dependency. Is there a reason for that?

(This is for 1.x, not 2.0)

**Comment by bricelam** [comment]
Reason: NuGet. `DotNetCliTool` packages restore completely isolated from the project, so if we made `EFCore.Design` a dependency of `EFCore.Tools.DotNet` NuGet wouldn't put it where we needed it--in the project's dependencies.

At a super high level, `dotnet-ef` executes your project's code using an entry point in `EFCore.Design`. In order for your app to have that entry point at design time with all of the required dependencies and binding redirects, we let NuGet take care of it by making it a `PackageReference`. (With `PrivateAssets="All"` to prevent it from being published or transitively brought in to other projects.)

At one point, we considered having `dotnet-ef` just copy it to the output directory before invoking, but then we'd also have to take care of dependencies and binding redirects.

Another possibility was to include the design-time entry point in `Microsoft.EntityFrameworkCore`, but then you'd end up with design-time-only code on your servers taking up space.

**Comment by bricelam** [comment]
We're also considering per-provider metapackages that include everything you need for a complete development experience in a single package. For example:

* Microsoft.EntityFrameworkCore.SqlServer.All
  * Microsoft.EntityFrameworkCore.SqlServer
  * Microsoft.EntityFrameworkCore.Tools (need [NuGet/Home#4125](https://github.com/NuGet/Home/issues/4125#issuecomment-268575442) to prevent publishing this)
  * Microsoft.EntityFrameworkCore.Tools.DotNet (need NuGet to support DotNetCliTool package dependencies)

**Comment by bricelam** [comment]
And just so all the bases are covered...

If DotNetCliTool packages didn't require putting the tool under `lib/`, and instead used something like `tools/netcoreapp2.0`, we could merge `EFCore.Tools.DotNet` into `EFCore.Tools` and there would just be two packages you'd need to care about: the provider & the design-time tools.

**Comment by shawnwildermuth** [comment]
Thanks, perfect explanation

**Comment by bricelam** [comment]
lol, can you tell I've wanted to improve this experience for a while..?
