### ISSUE TITLE
Scaffolding nullable foreign key

### ISSUE THREAD

**Issue by mguinness** [dotnet/efcore#9010]
When scaffolding a Sqlite database, if the FK is nullable it doesn't define IsRequired(false) on the relationship.

### Steps to reproduce
With the following database schema:

```sql
CREATE TABLE Cities (
   CityId INTEGER NOT NULL,
   StateId INTEGER NULL,
   CONSTRAINT PK_Cities PRIMARY KEY (CityId),
   CONSTRAINT FK_Cities_States_0 FOREIGN KEY (StateId) REFERENCES States (StateId)
);

CREATE TABLE States (
   StateId INTEGER NOT NULL,
   StateName TEXT NOT NULL,
   CONSTRAINT PK_States PRIMARY KEY (StateId)
);
```

The following relationship is scaffolded:

```c#
modelBuilder.Entity<Cities>(entity =>
{
    entity.HasOne(d => d.State)
        .WithMany(p => p.Cities)
        .HasForeignKey(d => d.StateId);
});
```

Since StateId field is nullable in Cities table, should it not have IsRequired(false) to indicate this is a not a required relationship?  If IsRequired() is absent, what is the default?

### Further technical details
EF Core version: 1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
What is the type of `Cities.StateId` property?

**Comment by mguinness** [comment]
This is the entire scaffold

```c#
public partial class Cities
{
    public long CityId { get; set; }
    public long? StateId { get; set; }

    public virtual States State { get; set; }
}

public partial class States
{
    public States()
    {
        Cities = new HashSet<Cities>();
    }

    public long StateId { get; set; }
    public string StateName { get; set; }

    public virtual ICollection<Cities> Cities { get; set; }
}

public partial class testContext : DbContext
{
    public virtual DbSet<Cities> Cities { get; set; }
    public virtual DbSet<States> States { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cities>(entity =>
        {
            entity.HasKey(e => e.CityId)
                .HasName("PK_Cities");

            entity.HasOne(d => d.State)
                .WithMany(p => p.Cities)
                .HasForeignKey(d => d.StateId);
        });

        modelBuilder.Entity<States>(entity =>
        {
            entity.HasKey(e => e.StateId)
                .HasName("PK_States");

            entity.Property(e => e.StateName).IsRequired();
        });
    }
}
```

**Comment by smitpatel** [comment]
> If IsRequired() is absent, what is the default?

It defaults to the nullability of the FK property.

The foreign key property `Cities.StateId` is `long?` which is nullable CLR type. Therefore relationship will be nullable and there is no need for explicit code for that.
Scaffolding database, generates only required explicit Fluent API configuration. If given CLR classes in the model, if something will be configured by convention or default then we won't write fluent API for that.

**Comment by mguinness** [comment]
@smitpatel Thanks for the explanation.  So based on [Required/optional properties](https://docs.microsoft.com/en-us/ef/core/modeling/required-optional) if that FK property was a string, then .IsRequired(false) would still not be emitted even though the database field is required?

**Comment by smitpatel** [comment]
If the FK property was string, then its CLR type is nullable so by default it would be nullable column in database. But if the database column is required then we would emit code to configure that property to be required. (via one of the methods in the article you linked based on user's choice of data annotation over fluent API).

Once the underlying property in EF model is made required, if that property is FK then the relationship also becomes required.
