### ISSUE TITLE
2.0.0 Cast Errors due to dbReader.GetValues instead of dbReader.GetFieldValue<T>

### ISSUE THREAD

**Issue by caleblloyd** [dotnet/efcore#9013]
Working on porting [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/dev) to EF Core 2.0.0 in our `dev` branch

It looks like EF 2.0.0 is calling `dbReader.GetValues` now instead of `GetFieldValue<T>`

This is causing all kinds of InvalidCastExceptions.  For example there is no `boolean` type in MySQL so we store bools as `bit(1)`.  Then `GetFieldValue<bool>` properly casts this to a bool.

Now with 2.0.0, EF calls `dbReader.GetValues` and providing no context as to what types it wants back, and the dbReader returns the unadulterated result from the database.  This causes InvalidCastExceptions.

Why was the change to `dbReader.GetValues` made, and what should we do to get some context as to what type to return?

**Comment by ajcvickers** [comment]
@caleblloyd Are you registering `UntypedRelationalValueBufferFactoryFactory`? If so, don't. The default is `TypedRelationalValueBufferFactoryFactory`, which should have the behavior you want. If you are using `TypedRelationalValueBufferFactoryFactory` and still see this behavior, then there may be a bug.

**Comment by caleblloyd** [comment]
Oops, yes we were registering `UntypedRelationalValueBufferFactoryFactory`.  Let me remove that and try
