### ISSUE TITLE
Code First Models creating weird self referencing keys

### ISSUE THREAD

**Issue by tsebastiani** [dotnet/efcore#9016]
Hi,
I usually define relationships with fluent API in DbContext and they work properly, but I was wondering how to slim down a bit the context code using the EF relationship detection mechanism.
I've created a simple one-to-many relationship and I ran the migration, and I found a weird self referencing relationship.
In my context there are only this two references to the model and nothing else.
```c#
        public DbSet<CompanyGroup> CompanyGroup { get; set; }
        public DbSet<Company> Company { get; set; }
```

![relation](https://user-images.githubusercontent.com/15978528/27697903-e0243cba-5cf5-11e7-953c-a9891b20b36c.png)

### Steps to reproduce

```c#
    public class CompanyGroup: AbstractModel {

        public int CompanyGroupId {get; set;}
        public List<Company> CompanyList {get; set;}
    }

    public class Company: AbstractModel {

        public int CompanyId {get;set;}

        public Company CompanyGroup{get; set;}
        
    }
```
The AbstractModel class is empty, I'm extending it for the future.

### Further technical details
EF Core version: 1.1.1
Database Provider:Pomelo.EntityFrameworkCore.MySql 1.1.1
Operating system: Linux
IDE: VsCode

**Comment by smitpatel** [comment]
Your property `Company.CompanyGroup` has return type `Company` which seems like typo. That is causing self-referencing relationship.

If you change the target type to `CompanyGroup` then there will be single one to many relationship.

**Comment by tsebastiani** [comment]
Apologize for the issue, I completely missed the type and got confused because was creating the proper relationship even if the type was wrong.

Cheers.
