### ISSUE TITLE
Efficiency of notification change tracking

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/efcore#9028]
@ajcvickers has a great blog posting on how to use notification change tracking with EF Core: https://blog.oneunicorn.com/2016/11/16/notification-entities-in-ef-core-1-1 

However I have seen virtually no other discussion of this topic. What I would like to ask about is what the efficiency is likely to be in various scenarios. For example if I want to load 50,000 transactions into a client program and then change or add a few of them, am I better off using snapshot change detection or notification change tracking?

**Comment by ajcvickers** [comment]
@sjb-sjb Honestly, we don't have good data on this at the moment--it's on the backlog to do more perf testing in this area. If I were you I would run some tests with your code and see what you find. I would be interested to hear what you find.

**Comment by sjb-sjb** [comment]
Thanks, I will let you know if I find out anything useful. I am still struggling with the data virtualization (for listview) and starting to wonder if it is worth it. Should I be knocking myself out writing a paging system for 50,000 records or should I just read 'em all and chew up the memory?
