### ISSUE TITLE
Allow backing fields to be owned properties

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#9044]
(I understand that this may depend on this backlogged issue: https://github.com/aspnet/EntityFramework/issues/6674  since backing fields only support scalar properties currently.)

I have a  class defined as a value object.
  
```
public class Identity : ValueObject<Identity>  {
    public static Identity Create(string first, string last)    {
     return new Identity(first, last);
    }
    public Identity() {  }
    private Identity(string first, string last) {
      First = first;
      Last = last;
    }
    public string First { get; private set; }
    public string Last { get; private set; }
    public string FullName()=>First+" "+Last;
}
```
(Note that the ValueObject type I'm implementing provides additional value object logic like Equals but does not affect the issue.)

If it is a publicly accessible property of another class e.g.

` public Identity Identity {  get; private set; }`

 then I can specify it as the target property in "OwnsOne" mapping.

`  modelBuilder.Entity<SomeRootClass>().OwnsOne(s=>s.Identity);`

And the database gets created as I expect ...with the First and Last properties mapped to columns in the SomeRootClass table.

However, I don't want Identity to be a publicly available property in SomeRootClass. Instead, I have a backing field called _identity and some methods for getting and setting the value.

Because of that, I seem to be unable to express OwnsOne in any way. (perhaps it's possible and I just am missing the path??)

The most logical thing I could think to try was to first explicitly map the backing field to a shadow property ala:

`  modelBuilder.Entity<SomeRootClass>().Property<Identity>("Identity");`

and then use the EF.Property method to tie that to OwnsOne.

` modelBuilder.Entity<SomeRootClass>().OwnsOne(s=>EF.Property<Identity>(s,"Identity"));
`
EF's model builder complains saying that 

`s => Property(s, "Identity")' is not a valid property expression. The expression should represent a property access: 't => t.MyProperty'.`

This makes sense since  the model doesn't know about Identity yet because it's just building up the fluent mappings.

The only workaround I can find is to create a public property for Identity which is exactly what I'm hoping to avoid.

So is there a way to do this that I"m just not seeing? Or is this something that can be made possible?

Thanks

### Further technical details
EF Core version: 2.0.0-preview2-final
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: not applicable
IDE: not applicable

**Comment by ajcvickers** [comment]
@julielerman There needs to be a navigation property, and currently it is not possible to use just a field for a navigation property. (I filed #9059.) However, the property can be private if you want:

```C#
private Identity Identity { get; set; }
```
```C#
modelBuilder.Entity<Person>().OwnsOne(typeof(Identity), "Identity");
```
(I'm assuming from your description that you want no property at all, rather than a property with a _backing_ field. If you have a property and want to specify the backing field, then see #6674.)

**Comment by julielerman** [comment]
haha yes, I referenced that same issue at the beginning of my issue. I assumed they were related

**Comment by julielerman** [comment]
Also, I can't believe the syntax is that simple when you have a private property... I tried quite a variety of ideas but never hit that! Thanks @ajcvickers.  This is a totally acceptable workaround.

**Comment by glucaci** [comment]
I have one question related to backing fields for owned types. How can be something like this configured?
```csharp
private readonly string _email;
public Email Email => (Email)_email;
```
I've expected to be something like:
```charp
modelBuilder.Entity<MyType>().OwnsOne(x => x.Email)
```
and then
```charp
.HasField("_email");
```
but HasField is not available on ReferenceOwnershipBuilder.

**Comment by ajcvickers** [comment]
@glucaci "Email" is a navigation property, and hence it needs to be configured differently than a normal property--see issue #6674
