### ISSUE TITLE
Suggestion: Create factory for ParameterExtractingExpressionVisitor

### ISSUE THREAD

**Issue by Tasteful** [dotnet/efcore#9049]
In version EF Core version 1.1 the `ParameterExtractingExpressionVisitor` was used in one place `QueryCompiler` and easy to override.

Now in EF Core version 2 the `ParameterExtractingExpressionVisitor` is created atleast in 2 different places without a good way to override.

Implement an `ParameterExtractingExpressionVisitorFactory` for easier overrides.

Found during implementing workaround for #8909

**Comment by Marusyk** [comment]
Is this still an issue? Now `ParameterExtractingExpressionVisitor` used in one place and it seems we do not need any factory at the time.

**Comment by Tasteful** [comment]
Now when only one instance is left and it seems to be pretty easy to override I don't think this is needed.

**Comment by Marusyk** [comment]
Yeah, I think this issue can be closed (or at least remove label up-for-grabs)
