### ISSUE TITLE
Anyone else having build issues?

### ISSUE THREAD

**Issue by pmiddleton** [dotnet/efcore#9053]
There is a new core framework version out (2.0.0-preview3-006628) and now I am unable to build.  Is anyone else having this issue?

I have updated my MSBuildSdksPath to point at %userprofile%\.dotnet\x64\sdk\2.0.0-preview3-006628\Sdks

I have tried deleting %userprofile%\.dotnet and %userprofile%\.nuget to force a new download.  I am still unable to build from the command line or visual studio.  

Anyone have any other ideas of what I can try?

**Comment by bricelam** [comment]
I'm using [Visual Studio 2017 version 15.3.0 Preview 3](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes) and [.NET Core 2.0.0 Preview 2](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md). If I `git clean -xdf` and open the solution in VS ***without*** running `build.cmd` things generally work.

**Comment by bricelam** [comment]
(Also, unset `MSBuildSdksPath`)

**Comment by ajcvickers** [comment]
@pmiddleton Building has been very flaky lately due to many changes coming in for 2.0 from many sources, including VS, NuGet, and .NET Core, as well as changes in the ASP.NET infrastructure which EF uses. It's been hard for everyone and we apologize for that and feel your pain. Hopefully @bricelam's suggestion works for you. We'll try to do better in the future.

**Comment by pmiddleton** [comment]
@bricelam - I switched over to the preview and removed the MsBuildSdksPath and that has me building again - thanks!  What are you using to run your unit tests in the preview - I can't get TestDriven.Net to install in the preview, and the built in test runner is blowing up.  

@ajcvickers - No problems, totally expected with everything that is currently in flight.  I just hope you all don't mind my asking for ideas when I get stuck with build issues.

**Comment by bricelam** [comment]
It sucks, but the CLI is the only reliable way I've found to run tests.

    dotnet test
    dotnet test --filter FullyQualifiedName~Namespace.Class
    dotnet test --filter FullyQualifiedName=Namespace.Class.Method

I also usually add `-f netcoreapp2.0` so they only run once.

**Comment by bricelam** [comment]
To debug, I add a `Debugger.Launch()` call and attach VS.

**Comment by roji** [comment]
I've personally been running EF Core tests on the CLI on and off for, I think, years :)

It's just comforting to see `dotnet test` as an official recommendation from the team :)

**Comment by ajcvickers** [comment]
@roji Internally we try to keep TestDriven.NET working as much as possible, but I haven't been able to get it to work on the latest preview.

**Comment by roji** [comment]
@ajcvickers I'm personally on the R# runner, it's true that things were OK until relatively recently, but here I'm reminiscing about the days of project.json, pre-RTM .NET Core etc. etc. So much life lost in stone-age debugging techniques...

Anyway I'm sure it'll sort itself out soon.

**Comment by pmiddleton** [comment]
@roji - I have never used the R# task runner - does it  work in the preview version of VS?  I would prefer to avoid the command line as well.  

At least we don't have to fall back to using GDB :)

**Comment by pmiddleton** [comment]
yea I just tried R# on the db functions xunit tests and I get a runtime error from R#.  I guess it's command line time for me - flashbacks to college :)

**Comment by ErikEJ** [comment]
>> So much life lost in stone-age debugging techniques...
@ajcvickers  @divega  Agree 100% - and sadly it looks like there have been gaps in the test matrix for EF Core preview 2, as it does not look like  I will be able to ship a preview-2-final provider for SQLCE 😞  https://github.com/ErikEJ/EntityFramework.SqlServerCompact/issues/463 

- no test of pure  .NET 4.6.1 provider (both SQLite and SQL Server providers are .NET Standard)
