### ISSUE TITLE
Are conventions, e.g. pluralization, supported? Where are they documented?

### ISSUE THREAD

**Issue by tomasaschan** [dotnet/efcore#9063]
I'm not sure what the correct terminology is, but what I mean is that the default pluralization conventions are different for entities that are explicitly included in the db context, by adding a property with type `DbSet<ExplicitlyIncludedEntity>`, compared to entities that are included in the context because they're referenced by some entity that is explicitly included.

The result is that when you include an already existing entity type in your db context, the pluralization convention changes, and you need to add and apply a migration that renames the table before you can run the application.

### Code samples

Consider the following types:

```
public class Implicit
{
    [Key]
    public int Id { get; set; }
}

public class Explicit
{
    [Key]
    public int Id { get; set; }
    
    public Implicit Reference { get; set; }
}

public class MyContext : DbContext
{
    public DbSet<Explicit> Explicits { get; set; }
}
```

This config will create two tables; `Explicits` and `Implicit`.

Now, if I add a property to the db context:

```
public class MyContext : DbContext
{
    public DbSet<Explicit> Explicits { get; set; }

    public DbSet<Implicit> Implicits { get; set; }
}
```

then EF expects the `Implicit` entities to be in a table named `Implicits`, not `Implicit`, and thus needs a migration that renames the table before continuing.

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by divega** [comment]
@tlycken technically there is no pluralization involved, but just a convention that uses whatever name you had for the `DbSet` property as the name of the table. 

Adding `public DbSet<Implicit> Implicits { get; set; }` results in a different model from the original. To achieve the same without having an `Implicits` property you can call `ToTable()` on the entity configuration in `OnModelCreating`.

**Comment by tlycken** [comment]
@divega Ah, I see. Thanks for clarifying that. I guess what I'm really looking for, then, is adding a pluralization convention to my code that pluralizes table names also for implicitly included entities.

I've looked through the documentation over at https://docs.microsoft.com/en-us/ef/core as well as tried a number of variations of google searches for how to do this, but found only SO posts about RC2, or posts that say that "something like this will be included, but it's not done yet." Do you know if this is still in-progress, or, if not, where I can find it documented?

**Comment by divega** [comment]
@tlycken we currently don't have a way to define custom conventions in EF Core that a similar way to how you can do it in EF6, however in EF Core it is easy to just iterate over elements of the model that is being built while still inside `OnModelCreating`. E.g. the following code implements a (rather naïve) pluralization "convention":

``` C#
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            ...
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                modelBuilder.Entity(entityType.Name).ToTable(entityType.Name + "s");
            }
        }
```

Of course you would probably want to use a more complete pluralization solution, e.g. Inflector from https://github.com/srkirkland/Inflector/.

**Comment by divega** [comment]
BTW another note on the original question: we don't intend to automatically pluralize table names generated from code first in EF Core. This causes every bug fix in the pluralizer itself to break existing applications. You are welcome to do it in your own code as indicated above if you are ok with never updating the pluralizer or having to deal with potential table renames any time you do.
