### ISSUE TITLE
Enable non-owner navigations to owned types

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/efcore#9093]

**Comment by smitpatel** [comment]
> No description provided.

😭

**Comment by AndriySvyryd** [comment]
>> No description provided.

>😭 

It's self-explanatory

**Comment by ajcvickers** [comment]
Based on using owned types as either aggregates or complex types, we think this is a useful restriction in the conceptual model. We would consider revisiting this based on feedback with details on how it is need.
