### ISSUE TITLE
InvalidOperationException: No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SqlClient'.

### ISSUE THREAD

**Issue by stanuku** [dotnet/efcore#9120]
Hello - I'm getting this runtime exception.

My solution details:

**Target Framework = .NET 4.6.1** 

- VS 2017 15.2 (26430.120
- A class library project (repositories library) using DbContext (using Entity Framework 6.3, **not** EF Core)
- ASP.NET Core 1.1 API project referencing the repositories project.
- Running any query using DbContext throws this exception.

Adding the ```<entityFramework>``` in the App.config of the API project doesn't help. **I suspect that the build is not copying EntityFramework.SqlServer.dll to the API project's bin folder.**

Adding Entity Framework package to the API project directly does copy the EntityFramework.SqlServer.dll to the bin folder during build. However, I don't prefer to do that. Rather I would like to maintain the indirection through the repository project.

Any suggestions? (again, I'm not using EF Core, can't take chances in this critical project).

Thanks

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework6#311
