### ISSUE TITLE
DiagnosticSource errors building latest Npgsql provider

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#9123]
Since I started syncing with preview3/rtm, trying to build the Npgsql functional tests project with netcoreapp2.0 fails:

```
Microsoft (R) Build Engine version 15.3.388.41745 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  EFCore.PG -> C:\projects\Npgsql.EntityFrameworkCore.PostgreSQL\src\EFCore.PG\bin\Debug\netstandard2.0\Npgsql.EntityFrameworkCore.PostgreSQL.dll
  EFCore.PG.FunctionalTests -> C:\projects\Npgsql.EntityFrameworkCore.PostgreSQL\test\EFCore.PG.FunctionalTests\bin\Debug\net461\Npgsql.EntityFrameworkCore.PostgreSQL.Funct
ionalTests.dll
C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3277: Found conflicts between different versions of the same d
ependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\projects\Npgsql.EntityFramew
orkCore.PostgreSQL\test\EFCore.PG.FunctionalTests\EFCore.PG.FunctionalTests.csproj]
Utilities\NpgsqlDatabaseCleaner.cs(16,21): error CS1705: Assembly 'Microsoft.EntityFrameworkCore' with identity 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neu
tral, PublicKeyToken=adb9793829ddae60' uses 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher vers
ion than referenced assembly 'System.Diagnostics.DiagnosticSource' with identity 'System.Diagnostics.DiagnosticSource, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b
13ffcd2ddd51' [C:\projects\Npgsql.EntityFrameworkCore.PostgreSQL\test\EFCore.PG.FunctionalTests\EFCore.PG.FunctionalTests.csproj]
```

Note that the EF Core provider itself builds just fine, and the test project also builds fine with net461. Oddly enough I have no issues compiling EF Core itself (i.e. the SqlServer provider). As we're starting to near RTM I thought I'd ask right away.

[This is the csproj in question](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/dev/test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj).

**Comment by smitpatel** [comment]
See https://github.com/aspnet/EntityFramework/commit/8f120e03d70aa6e0cedb790671d883bdc14ca7f7

For some reason `DiagnosticSource` was moved from 4.4.0-* to 4.4.1-* which has different assembly version. You would run into such conflict if your dependencies are referring to different versions and no assembly redirect. I believe explicitly adding reference to it would resolve it.

**Comment by roji** [comment]
Hmm, adding `<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.4.1-*" />` to both the provider project (EFCore.PG) and the functional test project hasn't made the error go away.

**Comment by smitpatel** [comment]
@roji - Do you get error when building or running tests? I cannot run functional tests because no npgsql installed.
Though I found 1 weird thing while building.
https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/dev/build.ps1#L36
Why you are using release version of KoreBuild? That is really old one. & the branching strategy for KoreBuild been really bad. If you are trying to sync up with nightly builds then I recommend using dev.zip (that's how I got the project to build correctly.)

**Comment by smitpatel** [comment]
Ok found the error. Related issue #9124 
Change your KoreBuild to dev which will download latest CLI. And use the latest CLI for testing. (preview2 rtm CLI won't work).

The reason we had to upgrade the version is underlying CLI started using newer one.
I managed tests to start while using latest CLI.

**Comment by roji** [comment]
@smitpatel when building - no need to run the tests. Are you saying you've managed to build the functional tests project with no errors on netcoreapp2.0?

build.ps1 and friends are really old and unused, I've only been building the sln/csproj directly for a long while now.  I'll remove it.

**Comment by roji** [comment]
Messages crossed :)

OK, I'll try the latest CLI and report back, thanks!

**Comment by roji** [comment]
FYI on https://github.com/dotnet/cli is talking about 2.1.0-preview1-006723, either you guys are really fast with the next version or there's some version mismatch??

**Comment by smitpatel** [comment]
sln/csproj directly would work as long as you are depending on last release of EFCore. 
15.3 preview 3 + .NET SDK preview2 + EFCore packages preview2-final will work without any error.

If you take nightly builds then EFCore depends on newer CLI so you need to install latest nightly SDK too.
The current SDK EF is depending on is here https://github.com/dotnet/cli/tree/release/2.0.0#installers-and-binaries

build.* script downloads and install latest CLI via KoreBuild. Its not necessary step but then you have to install required CLI yourself.

**Comment by smitpatel** [comment]
We love versioning hell :trollface: 

dotnet/cli has already branched for 2.0 release. Check release/2.0.0 branch. That's what we are depending on at present. Once we branch, branches will be in sync. We are bit slow than dotnet 😞

**Comment by roji** [comment]
Confirmed, using dotnet cli 2.0.0-preview3-006694 to build works fine without any errors, thanks!

**Comment by smitpatel** [comment]
cc @ErikEJ , @Kagamine - If you guys hit this issue

**Comment by ErikEJ** [comment]
Thanks, salve is .net 4.6.1 only, so I assume this does not apply?

**Comment by roji** [comment]
@ErikEJ I was just fine with .net 4.6.1, you probably don't need to do anything.

**Comment by Kagamine** [comment]
@caleblloyd
