### ISSUE TITLE
Owned Types: SaveChanges fails on SQL Server but succeeds for In-memory

### ISSUE THREAD

**Issue by julielerman** [dotnet/efcore#9125]
This is a reboot of "Owned Types: SaveChanges fails on Relational but succeeds for In-memory" https://github.com/aspnet/EntityFramework/issues/8907  as I'm still having this problem in rtm-26180.

I've created a repo with a webapi and a test project. THe test project tests inserting an object where the property for the owned entity is populated. It succeeds with inmemory and fails with sql server

` System.InvalidOperationException : The entity of 'Samurai' is sharing the table 'Samurais' with 'Samurai.SecretIdentity#PersonName', but there is no entity of this type with the same key value that has been marked as 'Added'.`

There are additional tests in there that also show in-memory allowing the property to be null on insert (which I would like to be true) whereas @AndriySvyryd has said that shouldn't be possible. I did not bother testing that with sql db.

My repo: https://github.com/julielerman/OwnedEntityStoreToDbProblem

dotnet info:
```
.NET Command Line Tools (2.0.0-preview3-006694)

Product Information:
 Version:            2.0.0-preview3-006694
 Commit SHA-1 hash:  44cd1cf385

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview3-006694/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25507-02
  Build    : cb31faee171130d052245748e11e96b27fd8d00c
```

**Comment by ajcvickers** [comment]
@julielerman You added a private SecretIdentity navigation property, but your code doesn't use it--it instead still uses the completely separate field.

**Comment by julielerman** [comment]
arrgh .... I shifted the private property/field/etc so many times I didn't catch that. Sorry to waste your time.

**Comment by fofaria** [comment]
@julielerman did you manage to get around this issue? I just finished the mappings to my Domain and i got the same error as you:
**The entity of 'CustomerContact' is sharing the table 'dbo.Customer_Contacts' with 'CustomerContact.Address#Address', but there is no entity of this type with the same key value that has been marked as 'Added'.**

**Comment by julielerman** [comment]
yes. I came up with a decent pattern, but got some help from @anpete and @divega to make it really great. It's at https://github.com/julielerman/DevInt2017EFCore  but I also have a 3/4 written blog post about it. Will post here when I publish that.
