### ISSUE TITLE
LIKE and case sensitivity

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#9126]
While looking at the client-side implementation of LIKE, I noticed the [following line](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/DbFunctionsExtensions.cs#L86):

```c#
if (matchExpression.Equals(pattern, StringComparison.OrdinalIgnoreCase))
```

(the regex below similarly has `RegexOptions.IgnoreCase`).

Now, I don't know SqlServer or the SQL Standard that well, but I'm wondering about the "correct" default for LIKE case sensitivity. PostgreSQL LIKE is case-sensitive (and an alternative ILIKE exists for insensitive). At the very least [Oracle seems to be case-sensitive by default as well](https://stackoverflow.com/questions/5391069/case-insensitive-searching-in-oracle).

Given that I'm popping this out a bit last minute with 2.0.0 around the corner, I'm guessing that at least the client-side implementation is going to remain case-insensitive. I'm wondering what you'd recommend for the Npgsql behavior: to align with the "default" EF Core behavior, I'd generate case-insensitive ILIKE clauses rather than LIKE. But to cause less surprise with PostgreSQL users who are used to LIKE being sensitive, `EF.Functions.Like()` should generate LIKE - and accept that there are going to be variations across providers with this kind of thing.

Let me know what you think.

**Comment by divega** [comment]
> I'm guessing that at least the client-side implementation is going to remain case-insensitive.

Hello @roji. In retrospective the choice may have been a bit arbitrary, but that is correct: It is very late in the 2.0 game and it is very unlikely that we would change the behavior at this point.

Also, changing the default later would be a breaking change, but we can certainly consider adding ways to control the behavior:

- Adding overloads that take `StringComparison`
- Adding a flag at the context options level to control the behavior
- Enabling the current provider influence the in-memory behavior to match the database behavior (that would could potentially break existing code but would be scoped to specific providers). 

We will use this issue to track that. 

> I'm wondering what you'd recommend for the Npgsql behavior: to align with the "default" EF Core behavior, I'd generate case-insensitive ILIKE clauses rather than LIKE. But to cause less surprise with PostgreSQL users who are used to LIKE being sensitive, EF.Functions.Like() should generate LIKE - and accept that there are going to be variations across providers with this kind of thing.

We think it is ok to have variations across providers for this kind of thing, although it is nice to match the in-memory behavior as long as you don't need to go out of way to do so. 

In case it helps you make a choice for Npgsql, here is some precedent: 

For direct equality comparisons between strings we kind of made the opposite call: depending on SQL Server's collation the comparison is likely to be case-insensitive on the database, but it will be case-sensitive in memory. We made an explicit decision not to go out of our way to compensate. E.g.:
-  compensating for the comparison to always be case-sensitive on a SQL Server database would have involved either generating SQL that explicitly overrides the collation or repeating all comparisons in memory. 
- compensating for the comparison to always be case insensitive would have required also generating SQL that explicitly overrides the collation (keep in mind that although it is common to get a case-insensitive collation in SQL Server, that is not true for all servers, databases, tables or columns) and rewriting all in-memory evaluations to perform case insensitive string comparisons. 

Neither option seemed worth pursuing and it seemed to make more sense to leave it to the application developer and the administrator of the database to control case-sensitiveness through the existing mechanisms. I wonder if in PostgreSQL the situation is similar.

**Comment by divega** [comment]
@ajcvickers It seems to me that the fact that this will be case insensitive in memory and that case sensitivity will depend on the database could be worth mentioning in the XML docs of te method at https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/DbFunctionsExtensions.cs#L21. Thoughts?

**Comment by ajcvickers** [comment]
Sure.

**Comment by divega** [comment]
@ajcvickers For 2.0? :smile:

**Comment by divega** [comment]
Clearing up the milestone. I responded the immediate question. 

Adding ways to control the case sensitivity could go in the backlog. 

Adding information about the behavior in the XML docs is something we can do sooner.

**Comment by ajcvickers** [comment]
Nope.

**Comment by roji** [comment]
OK, thanks for the doc update and the guidance. In light of the above, I'll have PostgreSQL's implementation of `EF.Functions.Like()` be case-sensitive (as PostgreSQL LIKE is), and add a PostgreSQL-specific `EF.Functions.ILike()` which will generate PostgreSQL ILIKE, the case-insensitive-equivalent.

As you say, the future we can add an overload with `StringComparison` or something else. I guess I can recommend trying to think about this kind of thing up-front, so that we can have this kind of discussion early and possibly influence design decisions. As an EF Core user, I personally think it's a little disappointing to find basic functionality such as LIKE varying in behavior across providers - I'd have expected EF to provide uniform behavior (no matter what it is really).

**Comment by smitpatel** [comment]
> As an EF Core user, I personally think it's a little disappointing to find basic functionality such as LIKE varying in behavior across providers - I'd have expected EF to provide uniform behavior (no matter what it is really).

While having the InMemory version which may do different than provider (which may unintentionally kick in while client eval) is bad. But for different providers, I suppose it ok behavior. A raw query like `Select * from Customers as c Where c.Id Like "A%"` would also produce different results. I see the function as a way to generate query like above without falling down to raw sql.

**Comment by divega** [comment]
> I'll have PostgreSQL's implementation of EF.Functions.Like() be case-sensitive (as PostgreSQL LIKE is), and add a PostgreSQL-specific EF.Functions.ILike() which will generate PostgreSQL ILIKE, the case-insensitive-equivalent.

@roji up to you :smile: Personally I can see it both ways, e.g. my expectations as a user of EF Core + Npgsql may be skewed towards PostgreSQL behaviors or towards EF Core behaviors depending on where I am coming from and what I am the most familiar with. 

I want to call out that since apparently in PostgreSQL the SQL you write controls completely whether lookups will be case sensitive or insensitive, I don't think there are enough similarities between this decision and the way we decided to not try to force case sensitivity for SQL Server. In other words, I don't think you can use my comments at https://github.com/aspnet/EntityFramework/issues/9126#issuecomment-314219840 as guidance.

> I guess I can recommend trying to think about this kind of thing up-front, so that we can have this kind of discussion early and possibly influence design decisions. As an EF Core user, I personally think it's a little disappointing to find basic functionality such as LIKE varying in behavior across providers - I'd have expected EF to provide uniform behavior (no matter what it is really).

@roji Let me tell you what my two regrets are with this, then please try to tell me specifically what else we can do better next time:

1. We did not have an explicit discussion about the case sensitiveness of the in-memory implementation. I am not sure the discussion would have changed the outcome. I personally would prefer it to be consistent with in-memory equality comparisons (e.g. be case sensitive, then adding a version later that takes a `StringComparison` would feel more natural) but that is not necessarily the most pragmatic option.

2. We did not have a longer runway for provider writers like you to implement your versions of the new features, give us this kind of feedback and then be able to react to that feedback before we have this major release. Instead we have been baking new functionality like this in relatively late.

**Comment by ajcvickers** [comment]
Agree with @divega on the regrets. Let's make sure we discuss this in the next retrospective.

**Comment by roji** [comment]
> I want to call out that since apparently in PostgreSQL the SQL you write controls completely whether lookups will be case sensitive or insensitive, I don't think there are enough similarities between this decision and the way we decided to not try to force case sensitivity for SQL Server. In other words, I don't think you can use my comments at #9126 (comment) as guidance.

Yeah, that seems right. I'm definitely no expert, but unlike SQL Server PostgreSQL case-sensitivity doesn't seem to be affected by any global or database-wide setting, like SQL Server. Operations in general are case sensitive unless otherwise specified (possibly reflecting Unix heritage as opposed to SQL Server's Windows heritage?), so you have case sensitive LIKE vs. case-insensitive ILIKE. In addition, the standard way to hold case insensitive text data is to use the [citext datatype](https://www.postgresql.org/docs/current/static/citext.html), instead of varchar/text, so case sensitivity is determined at the column datatype level rather than at the database global level.

> We did not have an explicit discussion about the case sensitiveness of the in-memory implementation. I am not sure the discussion would have changed the outcome. I personally would prefer it to be consistent with in-memory equality comparisons (e.g. be case sensitive, then adding a version later that takes a StringComparison would feel more natural) but that is not necessarily the most pragmatic option.

I agree. In general it seems that EF Core should strive to provide uniform behavior across databases (which is, after all, one of the functions of an O/RM). In practice this is not always possible - I'm simply not sure what it would entail to make SQL Server/Sqlite/MySQL to do case-sensitive LIKE, it might even be impossible in some cases.

Regarding your comments about the general process, I understand completely and in a way it's partially my responsibility too as a provider writer. I actually submitted [the first PR for DbFunctions and LIKE support](https://github.com/aspnet/EntityFramework/pull/7611), but while I thought about [LIKE escape characters across databases](https://github.com/aspnet/EntityFramework/issues/8696) early enough, I missed the case sensitivity issue until pretty late.

Based on past experience, it seems that when introduces this kind of feature which relies on specific database support and may contain behavioral variations, it would be best to sit down and spend more time on looking at the different databases. There have been several cases where EF Core features are implemented mainly with SQL Server and Sqlite in mind (and sometimes only with SQL Server since Sqlite isn't relevant for that particular feature), and when I look into it for PostgreSQL I find an incompatibility or behavioral variation.

I do agree that having a longer runway for provider writers would also help, although it seems that relying on provider writers for exposing SQL Server-specific assumptions is a bit dangerous - I specifically sometimes don't have time to implement feature as you implement them, and get around to them only much later (sometimes even in a later version). I think that unfortunately at least some cross-database knowledge and exploration must happen in the EF Core team for new features.

**Comment by ajcvickers** [comment]
After discussion in triage we are going to close this for now and be on the lookout for any customer feedback with regards to client evaluation. Since the real reason for people to use this is to translate to SQL it may be that the client evaluation semantics are not especially important, and so we don't plan to do work in that area for now. However, we will reconsider this if it does turn out to be a pain point.

**Comment by ajcvickers** [comment]
@roji I just wanted to say that we have also been discussing your feedback in terms of scheduling, gathering information about other databases, etc., but we're following up on that in the way we do planning for 2.1 rather than by keeping this issue open.

**Comment by roji** [comment]
> After discussion in triage we are going to close this for now and be on the lookout for any customer feedback with regards to client evaluation. Since the real reason for people to use this is to translate to SQL it may be that the client evaluation semantics are not especially important, and so we don't plan to do work in that area for now.

It's true that the client evaluation doesn't seem extremely important - the issue is more about things behaving the same way across providers, for people running on multiple databases. In other words, with future features it seems like a good idea to try to define a single behavior for providers (and client evaluation) wherever practical.

> @roji I just wanted to say that we have also been discussing your feedback in terms of scheduling, gathering information about other databases, etc., but we're following up on that in the way we do planning for 2.1 rather than by keeping this issue open.

Sure thing.

**Comment by flensrocker** [comment]
First of all: thank you for EF Core, it helps a lot!
And to set the tone of this message: I'm not angry or something like that, I would just like to know, what to do. So read this with a calm voice. 😀

I know, I'm late to the party, but only because I'm now facing the problem, to port some code from SQL Server to PostgreSQL and got hit by this today.

How am I supposed to write provider agnostic code with EF Core in this case? Esp. since `EF.Functions.Like` is in `Microsoft.EntityFrameworkCore` and `EF.Functions.ILike` is in `Npgsql.EntityFrameworkCore.PostgreSQL` - a dependency I don't want to have in some "common helper functions library".

I'm new to PostgreSQL, is a solution that I have to type those columns I "like" 😎 as `citext`? Having different entity configurations per provider is already something I have in place...

Another "solution" I would like to see: Having `EF.Functions.ILike` in `Microsoft.EntityFrameworkCore` and let it translate to `LIKE` for SQL Server. But I don't know how to write "DbFunctions" for different providers in the same function...

Thank you for your patience!

**Comment by roji** [comment]
@flensrocker I understand the frustration, this is unfortunately one of those cases where there really are differences across databases, and it's not always possible to completely taper over them and present a single way to do things that works everywhere.

First, the ideal solution here is to use collations (please read [this doc thoroughly](https://learn.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity)): you set up a case-insensitive collation for your column, and then all string matching operations (including LIKE) simply work in a case sensitive manner, without any idea for citext, ILIKE or any other stuff. PG unfortunately has lagged a bit in its support for case-insensitive (non-deterministic) collations, but the good news is that starting with the upcoming PostgreSQL 18, LIKE will support case-insensitive collations ([link](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=85b7efa1c)), so that's the recommended way to do things (no need for EF.Functions.ILike or citext).

Until then, the PG-side solutions (including how to use ILike) are already documented [here](https://www.npgsql.org/efcore/misc/collations-and-case-sensitivity.html?tabs=data-annotations). If you want to use EF.Functions.ILike rather than citext, then you need to have different LINQ queries for different databases - that's unfortunately sometimes required.

> Another "solution" I would like to see: Having EF.Functions.ILike in Microsoft.EntityFrameworkCore and let it translate to LIKE for SQL Server. But I don't know how to write "DbFunctions" for different providers in the same function...

That would mean adding a PG-specific thing in the core of EF - we're not going to do that. Not to mention that if your proposed EF.Functions.ILike is used on e.g. SQL Server, and a case-sensitive collation is used, it will work in a case-sensitive way, doing the opposite of what ILike is supposed to do (i.e. be case insensitive).

**Comment by flensrocker** [comment]
Thank you, @roji ! This should be enough material so I can find a solution, that works for me.
This kind of feedback is one of the reasons I like to use EF. Having the possibility to get in touch with the team is highly appreciated!
