### ISSUE TITLE
Enable attaching entity by ID without creating entity

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/efcore#9137]
I often have an inheritance hierarchy where the set entity type is abstract.
In case I want to delete an entity, I'm unable to attach the entity without loading it first, to find out what type it really is of.
My suggestion is then to add method the the `DbSet<TEntity>` - `AttachByKey(params object[] entityKeys)` that returns an `EntityEntry<TEntity>` without having to know what concrete type the entity is.
Sometimes the client only has the id of the entity to be deleted, without any info of the class type, for example in 1-1 foreign key references.

Here's what I'd like to see:

    class Program
    {
      public async Task DeletePerson(int personId)
      {
        using (var ctx=new AppContext())
        {
          var personEntry = ctx.People.AttachById(personId);
          personEntry.State = EntityState.Deleted;
          await ctx.SaveChangesAsync();
        }
      }    
    }

    public class AppContext : DbContext
    {
      public DbSet<Contact> People { get; set; }   
    }

    public abstract class Contact
    {
      public int Id { get; set; }
    }
    public class Customer : Contact { }
    public class Employee : Contact { }

**Comment by ajcvickers** [comment]
@weitzhandler We discussed this in triage and decided to not implement this for a few reasons:
* We think the scenario is better handled by implementing set-based delete--see issue #795
* For TPH mapping it is possible to delete without knowing the type. For TPT/TPC it could be more difficult and would require extra logic. Even though we don't support TPT/TPC yet, we don't want to introduce the concept of unknown types at this point to avoid the additional complexity.
* The API would only work for deleting, but this would not be apparent. It could cause unexpected results if people started to try to use it for other things.

**Comment by weitzhandler** [comment]
@ajcvickers tx for the update!
