### ISSUE TITLE
Inserting a graph into the database is not streamlined.

### ISSUE THREAD

**Issue by javiercn** [dotnet/efcore#9161]
Describe what is not working as expected.
I'm creating a graph of entities.
Movies *<->1 MovieActor 1 <-> * Actors

I setup all the relationships by giving a value to the Id property on each Movie and Actor and then creating and setting the MovieActor relationships using the temporary Ids as foreign keys on each MovieActor entry.
When I do context.Movies.AddRange(movies) and then call context.SaveChanges()

I get the following exception:
```
System.Data.SqlClient.SqlException : Cannot insert explicit value for identity column in table 'Artists' when IDENTITY_INSERT is set to OFF.
Cannot insert explicit value for identity column in table 'Artists' when IDENTITY_INSERT is set to OFF.
Cannot insert explicit value for identity column in table 'Movies' when IDENTITY_INSERT is set to OFF.
```

The problem happens because I'm setting a value for the Id column when (apparently) I shouldn't.
In order to workaround this, I'm forced to do the following:
```
context.AddRange(movies);
context.AddRange(artists);
LinkMoviesToArtists(movies,artists);
```

The problem is that the exception doesn't give me any clue on how to solve the problem. It would help a lot if the exception indicated that the property should not be set explicitly or that it should be explicitly marked as temporary in the entry with `context.Entry(object).Property(p=> p.Id).IsTemporary = true` or that an alternative when setting up relationships would be to add all entities to the context first and building the associations after that.

**Comment by ajcvickers** [comment]
Discussed the following in triage:
* The exception is provider-specific and we don't currently have a mechanism for providers to intercept and wrap provider-specific exceptions from SaveChanges. I thought we had an issue for this, but I can't find it. I'll create a new one if @divega thinks this is something we should do.
* This is much easier to do if there are navigation properties, so if the domain model is required to expose no navigation properties, then using private navigation properties might make this easier.
* If the application wants to take over all key values (as opposed to just taking them over for seeding test data) then just not using store-generated keys is a solution.
* Ultimately, handling many-to-many relationships should make this easier even without navigation properties. Issue #1368

Leaving open to get feedback from @divega when he is back.

**Comment by popcatalin81** [comment]
@ajcvickers I've so far encountered several disconnected scenarios where you:

1. Want store generated primary keys (and not Guids or something similar)
2. Don't want to rely on navigation properties to create the relations but instead on temporary Kyes (-1, -2...) to avoid serialization issues that will be created when serializing a graph with navigation properties, like circular references or duplicated entries.

@javiercn  There is a rather generic solution to mark the keys of an entire graph as temporary:

```CSharp
public static void SetKeysAsTemporary(DbContext ctx)
{
	foreach (var entry in ctx.ChangeTracker.Entries()
		.ToArray()
		.Where(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added))
	{
		var key = entry.Metadata.FindPrimaryKey();
		if (key != null)
		{
			foreach (var property in key.Properties.Where(p => p.ValueGenerated == ValueGenerated.OnAdd))
			{                        
				entry.GetInfrastructure().MarkAsTemporary(property);
				entry.Property(property.Name).IsTemporary = true;
			}
		}
	}
}
```

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
