### ISSUE TITLE
EF DbContext generator doesn't work. "overwrite the replacement token '$edmxInputFile$'"

### ISSUE THREAD

**Issue by sorokinDev** [dotnet/efcore#9168]
## Problem:
EF DbContext Generator doesn't work in Visual Studio. Just today's morning everything worked fine, but later I noice following problem.
## Error:
Running transformation: Please overwrite the replacement token '$edmxInputFile$' with the actual name of the .edmx file you would like to generate from.
## Steps to reproduce:
Create New project. Click on EF DbContext Generator(5 or 6 version doesn't matter). It doesn't show selector with options "from database, code first..." as always. Instead it just generates 2 files: "Model1.Context.tt" and "Model1.tt" and shows the error above.
## Screens:
![ef_1](https://user-images.githubusercontent.com/19349760/28169622-96bc561a-67eb-11e7-9eff-9054bffb090d.png)
![ef_2](https://user-images.githubusercontent.com/19349760/28169623-96d65f1a-67eb-11e7-9408-de3a589ae4da.png)

### Also:
I noticed in "Model1.Context.tt", that it has link and it returns 404.
```csharp
private const string ExternalTypeNameAttributeName = @"http://schemas.microsoft.com/ado/2006/04/codegeneration:ExternalTypeName";
```
## Further technical details:
I tried this on 3 PC: two with VS2017 and one with VS2015, all win10 x64.

**Comment by ErikEJ** [comment]
This issue tracker is for EF Core, not EF6 - and I suggest you use the EF Reverse POCO template instead.

**Comment by ajcvickers** [comment]
@sorokinDev As Erik says, this is the issue tracker for EF Core. For EF6, issues should be filed on https://github.com/aspnet/EntityFramework6. However, if we are going to be able to follow up on an issue there, then it will need to include full version information for Visual Studio (including which updates are installed.
