### ISSUE TITLE
Tests: xUnit.net not disposing OwnedQuerySqliteFixture

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#9174]
xUnit.net does not dispose some `OwnedQuerySqliteFixture` objects.

This leaves a scratch database open until the garbage collector reclaims it.

**Comment by smitpatel** [comment]
Easy win?

**Comment by AndriySvyryd** [comment]
Is it because all tests in `OwnedQuerySqliteFixture` are skipped?

**Comment by AndriySvyryd** [comment]
This will be fixed once #8973 is resolved
