### ISSUE TITLE
Showoff + guidance needed

### ISSUE THREAD

**Issue by roji** [dotnet/efcore#9183]
PostgreSQL supports array types, which are simple columns that contain an array of an arbitrary element type. Even multidimensional arrays are supported. I added support a while back for mapping CLR arrays to PostgreSQL arrays, and this works great - you can have an `int[]` property on your entity and have it mapped to a PostgreSQL array column in the database.

The next logical step is to also translate array *operations* - PostgreSQL also provides operators for indexing and searching arrays, and these operations can even be optimized by indices. So, a LINQ operation such `ctx.SomeEntities.Where(e => e.SomeArray[0] == 3)` could be translated into SQL `WHERE "e"."SomeArray"[1] = 3`.

I did manage to get several such operations mapped, including indexing, comparing arrays for equality and array length - you can take a look at [this test suite](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/array-translation/test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs) to see what's currently supported (that's the showoff part).

However, since array operations aren't simple methods which can be translated as usual, I had to create my own [NpgsqlSqlTranslatingExpressionVisitor](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/array-translation/src/EFCore.PG/Query/ExpressionVisitors/NpgsqlSqlTranslatingExpressionVisitor.cs) to identify these array operations (`ExpressionType.ArrayIndex`, `Expression.ArrayLength`) and pass them through for treatment by my [NpgsqlQuerySqlGenerator](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/array-translation/src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs). Since this kind of change goes a bit deeper than usual I thought I'd request a review from the team, [here's the branch in question](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/tree/array-translation). 

I'm particularly unsure about the way I'm checking that the member expressions are QuerySourceReferenceExpression, as a way to only translate array operations which occur on a member of an EF Core DbSet object - I want to avoid performing translation on, say, some client-side value (see the Where_indexer_closure test for an example).

**Comment by smitpatel** [comment]
I posted some comments on the commit directly.

**Comment by ajcvickers** [comment]
@smitpatel Can you check which internal code this is using, if any.

**Comment by roji** [comment]
@smitpatel, thank you very much for your comments. I've added some commits which hopefully address everything you said, I'd appreciate another quick look to make sure I didn't mess anything up.

Some points:

* You proposed implementing the array operation logic as an optimization (i.e. override `RelationalQueryModelVisitor.OptimizeQueryModel`), could you please elaborate on translation vs. optimization? Is it just a "categorization" of translations which has no visible effect, or something deeper that could trigger a behavioral change? I think I see operations in SqlTranslatingExpressionVisitor which could technically be removed (i.e. return null), triggering client evaluation - can these not be considered optimizations as well?
* I tried adding a test that accesses an array's length via `EF.Property`: see [Length_on_EF_Property](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/array-translation/test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs#L126). The test fails with the following error:
```
 System.NotSupportedException : Cannot parse expression 'e' as it has an unsupported type. Only query sources (that is, expressions that implement IEnumerable) and query operators can be parsed.
---- System.ArgumentException : Parameter 'expression.Type' is a 'Microsoft.EntityFrameworkCore.Query.SomeEntity', which cannot be assigned to type 'System.Collections.IEnumerable'.
```
It's worth noting that this test is identical to [ArrayQueryTest.Length](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/array-translation/test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs#L115) except for accessing the property via `EF.Property`, so I'm not sure what is going on...

**Comment by smitpatel** [comment]
@ajcvickers - Verified that all code needed to override is public and not in internal namespace.

**Comment by smitpatel** [comment]
@roji - Things looking fine. My badly phrased comment may have some confusion, I have clarified it on the PR.
To other questions here,
For most cases optimization vs translation has no visible effect. For certain cases it would make some difference in SQL though if implemented right then functionally it should give same & correct results.
A partial difference I know of is in TypeIs operator for which added optimization. TypeIs was getting translated to extra predicate on discriminator but it caused all of columns of base type to be fetched. (same goes for OfType). Which was unnecessary. We could have optimized that at SQL level too but we decided to modify the QM so that translation works as is and gives optimal SQL. Due to that we could get rid of OfType result operator and translation for TypeIs expression at relational level.

There are mainly 2 utilities.
1. Separation of concern. We know which part of pipeline would do exactly what. So we don't end up with surprise optimization during translation. And translation can remain as pure as it can be.
2. More optimization done at QueryModel level means less patterns to understand for translator and lesser optimization you need to apply for SQL.

**Comment by smitpatel** [comment]
For 2nd one, it seems like bug in EF. I will investigate.

**Comment by roji** [comment]
@smitpatel I think I've fixed the Visit vs. Generate confusion. Also see my failed attempt to implement array operation translation as optimization (https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/213#issuecomment-316981366).

Finally, do you want a separate issue for the failure of `EF.Property` in test `Length_on_EF_Property`?

**Comment by smitpatel** [comment]
@roji - File a new issue so we can track it separately for customers.

**Comment by roji** [comment]
@smitpatel opened #9242 to track the EF.Property issue.

**Comment by roji** [comment]
Have merged array operation translation support into Npgsql 2.0.0, thanks for all the guidance @smitpatel!
