### ISSUE TITLE
ToListAsync method requires System.Private.CoreLib

### ISSUE THREAD

**Issue by Zonciu** [dotnet/efcore#9184]
I' trying to call ToListAsync method from DbSet, but I get a error.

DBContext
```
public class UserCenterDbContext
{
        public virtual DbSet<User> Users { get; private set; }

        public UserCenterDbContext(DbContextOptions<UserCenterDbContext> options)
            : base(options)
        { }

        ......
}
```
Use
```
......

 var users = await _dbContext.Users.ToListAsync();

......
```
![image](https://user-images.githubusercontent.com/10374056/28240364-30331ca2-69b3-11e7-9f7c-47b3050a0232.png)

### Further technical details
SDK version: 2.0.0-preview2-006497
EF Core version: 2.0.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows10
IDE:  Visual Studio 2017(15.2 26430.15)

**Comment by ErikEJ** [comment]
What error?

**Comment by Zonciu** [comment]
Well……it's fine now, VS 2017's bug, I reopen the solution and there is no errors anymore.😂
