### ISSUE TITLE
Have to change present working directory to project in solution to use EF Core CLI tools

### ISSUE THREAD

**Issue by humzakhan** [dotnet/efcore#9187]
I have installed EF Core in a library project which is then referenced in my ASP.NET Core application.

When finally I got the package `Microsoft.EntityFrameworkCore.Tools.Dotnet ` installed, I was unable to use the `dotnet ef` commands until or unless I change my present working directory in Package Manager Console to that project.

### Project Structure

`
- Project
    - Project.Lib
        - Project.Data
        - Other Libraries
    - Project.Web
        - Project.Web.Portal
        - Other Web Projects
`

The present working directory is set to `Project` and the `Default Project` in Package Manager Console is set to `Project.Data`.

### Steps to reproduce

Follow the project structure mentioned above and then try to run the following command after installing the `Microsoft.EntityFrameworkCore.Tools.Dotnet` package:

`dotnet ef`

### Expected Behaviour 

```
PM> dotnet ef

Entity Framework Core .NET Command Line Tools 1.0.1-rtm-10418

Usage: dotnet ef [options] [command]

Options:
  --version        Show version information
  -h|--help        Show help information
  -v|--verbose     Show verbose output.
  --no-color       Don't colorize output.
  --prefix-output  Prefix output with level.

Commands:
  database    Commands to manage the database.
  dbcontext   Commands to manage DbContext types.
  migrations  Commands to manage migrations.

Use "dotnet ef [command] --help" for more information about a command.
PM> 
```

### Current Behaviour 

```
PM> dotnet ef
dotnet : No executable found matching command "dotnet-ef"
At line:1 char:1
+ dotnet ef
+ ~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No executable f...and "dotnet-ef":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
```

### Workaround

Change present working directory to `Project.Lib/Project.Data`:

`PM> cd Project.Lib/Project.Data`

Now If I use the `dotnet ef` command, it works perfectly fine.

### Further Details

I'm creating this issue because, in Entity Framework 6, it doesn't matter in which project EF is installed. I could simply use EF 6 commands from the Package Manager Console without changing my present working directory. I just had to make sure the `Default Project` option of the Package Manager Console is set to the class library project which has EF 6 installed.

I'm curious whether this behavior is intended or a consequence of 'everything-as-a-package' pattern .NET Core follows.

**Comment by bricelam** [comment]
We strongly recommend using the PMC commands (`Add-Migration`, `Update-Database`, etc.) inside package manager console since they provide a more integrated experience.

**Comment by humzakhan** [comment]
@bricelam Pardon my incompetence, but the PMC commands you mentioned are compatible with EF Core when used with the Npgsql Adapter? I didn't know this until now!

**Comment by ajcvickers** [comment]
@roji Are you aware of any issues using the PMC commands with Npgsql?

**Comment by roji** [comment]
@ajcvickers I admit I spend my time with the dotnet cli commands rather than Powershell, but I'm not aware of any issues... would definitely want to know if someone comes across any.

**Comment by ajcvickers** [comment]
Thanks @roji 

@humzakhan If PMC commands are not working for you, then could you file a new issue showing how to reproduce the problem and what error message and/or stack trace you see?

**Comment by ajcvickers** [comment]
@tdykstra @Rick-Anderson It seems that none of the tutorials for ASP.NET Core show using of the PMC commands even when clicking on the link that says "using Visual Studio"--for example: https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations. We are wondering if this is contributing to the idea that the PMC commands do not work with EF Core? Where would be the best place to file an issue on this?
/cc @divega

**Comment by Rick-Anderson** [comment]
@ajcvickers  My tutorial uses [PMC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model#add-ef-tooling-and-perform-initial-migration) - however I just added that a week ago. I know @tdykstra  planned on adding it to his. I created https://github.com/aspnet/Docs/issues/3747 to get PMC added to @tdykstra 's tutorial.

**Comment by ajcvickers** [comment]
Okay, thanks @Rick-Anderson. Looks like you guys have it covered.

**Comment by humzakhan** [comment]
@ajcvickers Hello there, the PMC commands works perfectly fine. Just started to use them, and yes you're right, none of the tutorials available online use the PMC commands. All of them use the .NET CLI ones. This was the major reason I didn't know about their compatibility with EF Core and Npgsql.
