### ISSUE TITLE
Alias limit

### ISSUE THREAD

**Issue by gsGabriel** [dotnet/efcore#9195]
Houston, i have an inssue.

My problem is the size of the ALIAS in the POSTGRESQL database (63 bytes). The query that EF CORE sets exceeds this limit. I have a table with a self-relationship and when I access the many levels of IdProcedimentoPaiNavigation the native limit of POSTGRESQL is exceeded in the query. But the problem is not the boundary of the mounted ALIAS, the problem is that since it is a self-relation, it assembles the alias with the similar name and how POSTGRESQL only accepts the first 63 bytes means that the different levels are replicated INNER JOIN throwing the exception.

Could you help me?

```
Exception message: table name "x.IdProcedimentoPaiNavigation.IdProcedimentoPaiNavigation.IdPro" specified more than once
Stack trace:
```
### Further technical details
EF Core version: 1.1.2
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
IDE: Visual Studio 2017

**Comment by roji** [comment]
This should be fixed for 2.0.0, can you please give 2.0.0-preview2 a try and confirm?

**Comment by gsGabriel** [comment]
ok, i can do this

**Comment by gsGabriel** [comment]
@roji Yes, it worked, I still can not identify the difference of the query because I'm not able to recover the sql in EF CORE 2, but I'm happy that it worked. I would like to congratulate you on the incredible work you are doing.

Thanks

**Comment by roji** [comment]
@gsGabriel great to hear you're good, and thanks for the kind words - although in this particular case it's an EF Core feature rather than anything I did specifically.
