### ISSUE TITLE
Projection covering child entities results in individual queries / value buffers

### ISSUE THREAD

**Issue by kierenj** [dotnet/efcore#9196]
I have a query as follows which maps related entities:

```c#
// apply projection
var items1 = qry.Select(p => new
{
    PrincipalId = p.Id,
    IsDisabled = p.IsDisabled,
    Roles = p.Roles.Select(r => r.RoleId),
    Claims = p.Claims.Select(c => new ClaimTuple {Type = c.Type, Value = c.Value}),
    CredentialKeys = p.Credentials.Select(c => c.Key)
})
.ToList();
```

My issue is that the Roles, Claims and CredentialKeys collections come back as value buffers.  If I include `ToArray()` in the map expression, a sub-query is run for each of them, for each row.

Is there any way to achieve this kind of projection?

(If I don't project with `Select()`, I can still `Include()` all of the nested entities, though of course this brings back columns which I don't need, and in fact still results in one additional query for each of the columns I request)

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017

**Comment by kierenj** [comment]
Just a quick question, is there any kind of projection support for sub-entities at the moment outside of what I'm seeing?

**Comment by maumar** [comment]
In 2.0.0-preview2 we added feature that converts "naked" collection navigations into include statements, so those will be optimized. (see #8584). Also, collections that are collapsed to a single result (e.g. by using result operator like Min/Max/Count) will be translated into the original query. Everything else will yield N+1 queries at the moment.

**Comment by maumar** [comment]
tracked by https://github.com/aspnet/EntityFrameworkCore/issues/9282
