### ISSUE TITLE
Query: string concatenation where at least one operand in null translates to null, which is different than Linq to objects

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#9201]
```cs
string s1 = null;
string s2 = null;

var q1 = s1 + s2; // translates to null in sql, and to empty string in L2O

string s3 = null;
string s4 = "Foo";

var q2 = s3 + s4; // translates to null in sql, and to "Foo" in L2O
```

**Comment by ajcvickers** [comment]
Will triage when @divega @anpete are back. (I have no strong opinion if I am not here.)

**Comment by divega** [comment]
*EF triage*: we believe it would be nice if the behavior was closer to L2O. However we don't think this is urgent and it would be a nice opportunity for a contributor. 

FWIW, it would also be a minor breaking change.

**Comment by smitpatel** [comment]
Duplicate of #3836
