### ISSUE TITLE
EF + EF Tools not working in .NET Core 2.0

### ISSUE THREAD

**Issue by salinaaaaaa** [dotnet/efcore#9212]
Ive upgraded and install EF Core 2.0 and ALL of its dependencies. The CLI Tool commands, like Add-Migration, Update-Database do not work.

 
`PM >  Add-Migration
Add-Migration : The term Add-Migration is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
Add-Migration
CategoryInfo : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException`

**Comment by joehoeller** [comment]
I found out it is due to a conflict with EF Core Identity

**Comment by ajcvickers** [comment]
@joehoeller Is this now working for you? If not, does restarting Visual Studio help?

**Comment by varora1406** [comment]
Same not working for me as well

**Comment by varora1406** [comment]
![image](https://user-images.githubusercontent.com/24986539/28499654-56cc03c6-6fd8-11e7-8d7b-5131d1ea791a.png)

I have already tried restarting visual studio a lot. Do we have any knowledge towards this?

**Comment by ajcvickers** [comment]
@varora1406 You are using a mix of preview2 and preview1 packages. You need to update everything to be consistent.

@joehoeller Since we haven't heard from you I'll assume you got this working and close this issue. Please feel free to re-open with additional information if needed.

**Comment by joehoeller** [comment]
Sorry, I have been busy and just checked this. No it still doesnt work.

**Comment by joehoeller** [comment]
@ajcvickers doesnt work in v2.0

**Comment by smitpatel** [comment]
@joehoeller - Share your csproj file.

**Comment by joehoeller** [comment]
I fixed it: You have to install EFCore Tools, and then restart VS2017

**Comment by besha100** [comment]
@joehoeller, could tell me the steps you follow, because I have the same problem now

**Comment by joehoeller** [comment]
I created a new project and copied my models and controllers over, and issue resolved itself
