### ISSUE TITLE
Nullable Guid not persisted correctly when compiled with .NET native tool chain for UWP app

### ISSUE THREAD

**Issue by teh-sHr0oMaN** [dotnet/efcore#9215]
In a UWP application, when an EFCore model containing a nullable guid (Guid?) property is saved to the local SQLite database, the value is incorrectly saved. This only occurs when compiled using the .NET native tool chain.

**Code**
Sample can be found here: https://github.com/teh-sHr0oMaN/NullableGuidEFCoreIssue

**Steps to reproduce**
Compile and run the sample UWP application in .NET native mode. 
The second post object has it's CopiedFromPostId property set to the first's PostId.
Before _db.SaveChanges();_ is called verify that the guids match.
After the SaveChanges is executed, verify that the CopiedFromPostId on the second post object no longer matches the first's PostId.
Clicking the Load button will reload the posts from the SQLite db - verify that the properties no longer match.
A SQLite db browser such as DB Browser for SQLite can also be used to verify the discrepancy. 

**Package Versions**
Microsoft.EntityFrameworkCore: 1.1.2
Microsoft.EntityFrameworkCore.Sqlite: 1.1.2
Microsoft.NETCore.UniversalWindowsPlatform: 5.2.2
Operating system: Windows 10, version 1073, OS Build 15063.483 
IDE: Visual Studio 2017

**Comment by teh-sHr0oMaN** [comment]
Appears that the DBContext was missing an explicit statement that the CopiedFromPostId is not required.
See below:
```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Post>().Property(b => b.CopiedFromPostId).IsRequired(false);
        }
```

**Comment by ajcvickers** [comment]
@teh-sHr0oMaN Was the IsRequired call only needed for .NET native?
