### ISSUE TITLE
dotnet ef scaffold does not sanitize type names 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/efcore#9216]
1. Create a directory with a hyphen e.g. `ef-test`
2. cd `ef-test`. `dotnet new mvc -au Individual`
3. Run the `dbcontext scaffold ` command

Expected:
The root namespaces generated by scaffold sanitizes the project's root namespace like `dotnet new` does i.e. `namespace ef_test`

Actual:
The generated code includes `namespace ef-test` which fails to compile.

**Comment by bricelam** [comment]
Interesting. AFAIK, we just get the `RootNamespace` MSBuild property. I wonder if the SDK should sanitize this...

**Comment by ajcvickers** [comment]
@bricelam to follow up with external teams.
