### ISSUE TITLE
Docs: ConcurrencyCheck has no effect

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9219]
https://docs.microsoft.com/en-us/ef/core/modeling/concurrency

Setting concurrency check has no effect on generated migration.

@AndriySvyryd @bricelam - Is this expected behavior?

**Comment by AndriySvyryd** [comment]
Concurrency checking is purely client-side. The user needs to ensure that the token is updated on every change either on the client or in the database through separate means.
