### ISSUE TITLE
Related Entity Collection is null

### ISSUE THREAD

**Issue by rynowak** [dotnet/efcore#9222]
The collection of related entities on a model object retrieved from the dbcontext is null

This is based on the sample code from https://docs.microsoft.com/en-us/ef/core/saving/related-data

### Steps to reproduce

Uses entities defined at https://github.com/aspnet/EntityFramework.Docs/tree/master/samples/core/Saving/Saving/RelatedData/

```c#
using (var context = new BloggingContext())
        {
            var blog = new Blog
            {
                Url = "http://blogs.msdn.com/dotnet",
                Posts = new List<Post>
                {
                    new Post { Title = "Intro to C#" },
                    new Post { Title = "Intro to VB.NET" },
                    new Post { Title = "Intro to F#" }
                }
            };

            context.Blogs.Add(blog);
            context.SaveChanges();
        }

            using (var context = new BloggingContext())
            {
                var blog = context.Blogs.First();
                var post = new Post { Title = "Intro to EF Core" };

                // Exception thrown here because blog.Posts is null
                blog.Posts.Add(post);
                context.SaveChanges();

                Console.WriteLine($"Post Count: {context.Posts.Count()}");
            }
```

**Comment by ajcvickers** [comment]
@rynowak This is by-design. EF will not initialize the Posts navigation property unless it is included in the query, and since there is no lazy loading it will not get lazily initialized.

**Comment by smitpatel** [comment]
This needs update in docs.

**Comment by rynowak** [comment]
OK great, I'll continue testing using `.Include(...)`

**Comment by rynowak** [comment]
I've included this note in my consolidated feedback from signoff https://github.com/aspnet/Docs/issues/3787

**Comment by ajcvickers** [comment]
Tracking in https://github.com/aspnet/EntityFramework.Docs/issues/424
