### ISSUE TITLE
Tools: get-help Add-Migration displays invalid related command

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#9231]
get-help Add-Migration

displays:

```
RELATED LINKS
    Remove-Migration
    Update-Database
    about_EntityFrameworkCore 
```

`about_EntityFrameworkCore` doesn't seem to be there

**Comment by bricelam** [comment]
That's the overview help topic that shows the unicorn.
```ps1
Get-Help about_EntityFrameworkCore
```

**Comment by BenjiZombie** [comment]
Also, `-Environment <String>` is not a valid option anymore

**Comment by bricelam** [comment]
@BenjiZombie Correct. You need to use the `ASPNETCORE_ENVIRONMENT` environment variable now.
