### ISSUE TITLE
EntityFramework Core 2.0 Preview 2 Symbol Packages

### ISSUE THREAD

**Issue by MichaelZino** [dotnet/efcore#9246]
Are the symbol packages for EF Core 2.0 Preview 2 available for download?

**Comment by ajcvickers** [comment]
@MichaelZino I'm pretty sure the infrastructure wasn't in place for preview2. I'm following up with some people as to what the status will be going forward.

**Comment by ajcvickers** [comment]
@Eilon Pinging you for external issue per conversion yesterday.

**Comment by Eilon** [comment]
Yeah we've only uploaded symbols for RTM versions of the product so far. We might change that in the future, but no immediate plans for that.

If you're using 2.0.0 RTM the symbol loading should work, as long as you have the Microsoft Symbol Server enabled:

![image](https://user-images.githubusercontent.com/202643/29895101-b320e3b8-8d8c-11e7-8c6c-a3f59ff66d60.png)

Though there isn't automatic source indexing, if you have a repo cloned to the 2.0.0 milestone, you can open any file in the repo and set a breakpoint in it and it should work just fine (I did that yesterday and it worked great!).
