### ISSUE TITLE
how do I invalidate my model if I drop a column

### ISSUE THREAD

**Issue by rykr** [dotnet/efcore#9269]
I'm not using migrations at all.

I'm basically doing dbfirst/code first.  Make a db change, edit the code to match, and run.  So far things have been fine.  I've now got a table that I dropped a column from and removed the  property from the model.   It builds but it's still trying to include the column in the SQL.  

If I copy the model to a new name and fix up the table names in my dbcontext then it works fine so I know the model is ok and the database table is ok. There must be some model or schema cache somewhere that says model A has a property X and I want to invalidate that cache.

Am I right about that?

**Comment by smitpatel** [comment]
If you are not using migrations at all then whatever model is built out of your classes will be used. So if a property is being included in SQL that means property is part of the model.
Check the following
- Did you remove the property from CLR class corresponding to the table?
- Are you doing any `.Property()` call with the property name of the removed property? If you remove CLR property but still call `.Property()` EF will create a shadow property and it will remain in the model.
- Is the property removed was foreign key property for some relationship? EF introduces FK property by convention if it cannot find one. So if your property name was same as conventional name then even if you remove the CLR property, convention will create shadow property with same name anyway.

If all of above looks fine then please share a sample code which demonstrate the issue you are seeing.

**Comment by rykr** [comment]
Thanks for your reply.  I have searched in db create script and I am not using the column as any type of FK.  I also am not calling .Property in any way.

Also, I can rename the CLR object to some other name and it will work fine using the same database and table!!  For now I have added back the division_id field to my database to make it work.  

I have no idea why it keeps generating SQL with that field present.  BTW, this is with MySQL using the SapientGuardian provider.  Could the provider have something to do with it?

**Comment by smitpatel** [comment]
There is no model cache when application is offline so there is nothing to validate. If the column is being included in SQL then for some reason the column is being added to the model. I outlined some of the reasons why a property would be added to the model. If it is none of those case then please share a repro code which would demonstrate the issue you are seeing.

**Comment by rykr** [comment]
maybe I don't have it properly "offline".   All I did was delete my
migration table.  Is that enough for it to go "offline"?

**Comment by rykr** [comment]
I found it.  Man those things can be hard to find.  I have  a property on another model and EF was trying to create a connection.   Sorry for the noise.

**Comment by smitpatel** [comment]
Just for clarification:
Offline means when app is not running.
Since model building is a costly operation, when you start your app and use the model for first time, EF Core will build it and cache it. So while app is running all subsequent access to model will use the cached model. This works correctly since currently model cannot change at runtime. Once you shutdown your app that cached model is gone and when you start app again the procedure repeats.
