### ISSUE TITLE
CLI Tools: DBCONTEXT environment variable

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#927]
Since the command line interfaces (`k ef` and `ef.exe`) don't have a good way of implementing the `Use-DbContext` command, we should allow an environment variable to be set instead.

**Comment by bricelam** [comment]
Pulling into 2.0.0 to resolve alongside #7353

**Comment by ajcvickers** [comment]
Closing as we haven't seen significant demand for this feature. We could revisit this decision based on feedback and we would also consider a well-written community PR for it.
