### ISSUE TITLE
Question: How to compile and Debug EF 1.1.1 with VS 2017 msbuild infra

### ISSUE THREAD

**Issue by archanasoni** [dotnet/efcore#9273]
Hi,

We are trying to have debug setup for IBM EF provider. Currently IBM EF is dependent on version 1.1.1
When we download source code from Github we don't see xproj file, csproj files are exist but we can not target those as ours are xproj based infra.
Hence we moved our code to VS 2017 based infra, now when we try to compile MS EF 1.1.1 code in VS 2017 it throws multiple error first issue comes it can not target multiple platforms. to handle this we tried by removing net451 as we do not need it. but we are getting several other exceptions. 

How can we compile EF 1.1.1 with VS 2017, is there any doc for it ?

**Comment by smitpatel** [comment]
EF 1.1.1 does not work with VS 2017. It was written in VS 2015. At present there is no plan to update 1.1.2 branch to move to 2017 msbuild based infrastructure.

**Comment by archanasoni** [comment]
Thanks @smitpatel for the info.
