### ISSUE TITLE
Clarification over configuring an Owned type with multiple properties

### ISSUE THREAD

**Issue by Antaris** [dotnet/efcore#9278]
Hi Team,

Looking at the tests for the Owned type mechanism, and also the release notes for Preview 2, I'm a little confused on how I go about correctly configuring an Owned entity using the fluent `EntityTypeBuilder<T>`.

Say for instance, I have the following type: `Message`, representing an email message:

```
public class Message {
  public EmailAddress Recipient { get; set; }
  public EmailAddress Sender { get; set; }
}
```

And another class `EmailAddress`:

```
public class EmailAddress {
  public string Email { get; set; }
  public string Name { get; set; }
}
```

I'm trying to configure the `Recipient` and `Sender` properties:

```
builder.OwnsOne(m => m.Recipient)
  .Property(ea => ea.Email).IsUnicode().IsRequired().HasMaxLength(255);
```

For the second property, I do this again:

```
builder.OwnsOne(m => m.Recipient)
  .Property(ea => ea.Name).IsUnicode().HasMaxLength(255);
```
I can't seem to chain another call to `Property` from previous chain:

```
builder.OwnsOne(m => m.Recipient)
  .Property(ea => ea.Email).IsUnicode().IsRequired().HasMaxLength(255)
  .Property(ea => ea.Name).IsUnicode().HasMaxLength(255);
```

What is the expected pattern for this?

**Comment by smitpatel** [comment]
Expected pattern would be like this
```
builder.OwnsOne(m => m.Recipient, b =>
    {
        b.Property(ea => ea.Email).IsUnicode().IsRequired().HasMaxLength(255);
        b.Property(ea => ea.Name).IsUnicode().HasMaxLength(255);
    });
```
You cannot chain because after `.Property` call it returns `PropertyBuilder` so that you can chain property configurations.
Also, this would configure only `Recipient`. Properties `Sender` will have default configuration only unless you configure them like above.
