### ISSUE TITLE
Serializing/Copying a Context

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#9288]
As far as I can see, DbContext doesn't implement ISerializable or anything of that sort.

I'm trying to create something like a "savepoint" - basically, remember exactly what a context (including all of its entities etc) looked like at a certain point in time, then perform some operations, then restore everything to the saved state in case of an error.

I can implement serialization on my entities, but I can't do the same for EF's internal state. Is there some functionality that could allow this?

**Comment by divega** [comment]
@Wain123 Serialization of `DbContext` state is something that we have discussed in the past as a possible approach for EF Core (or EF) to work in disconnected scenarios and in long running processes which require persisting intermediary states to be able to continue with them later. Pursuing this feature isn't currently in our radar but we would like to understand your scenario as much as possible to better asses the priority of having it in the future. 

It seems that you are describing something similar to the long running processes but we want to make sure that you are not talking about recovering from errors that happen during `SaveChanges()` which should already automatically cause any changes in the state to be rolled back.

**Comment by Wain123** [comment]
I am more-or-less talking about errors during SaveChanges, but the Rollback/Commit/AcceptAllChanges functionality isn't sufficient here.

I am writing software for logistics and production. It needs to handle highly concurrent scenarios with many users working with the same data. So, I can't just load some entity, show it to the user, let him make changes, then save it - the data would have changed a dozen times between the load and the save. Instead, I try to delay loading any concurrency-critical data until the user clicks the "save" button.

For example, if a user wants to move 1 unit of stuff from warehouse A to warehouse B, the process would look like this:
- User sees data about warehouses A and B.
- User clicks "move stuff". This creates an entity "stuff movement", but the warehouse entities are still unchanged.
- User clicks "save". The warehouse entities are reloaded, then they are modified, then SaveChanges.

If everything goes fine, I commit the transaction and AcceptAllChanges.
If not, I rollback the transaction and want to return to the moment right before the user clicked "save". If the user clicks "save" again afterwards, I want to re-do the whole process of "reload warehouses, modify warehouses, savechanges". I do NOT want to return to the moment right before SaveChanges was called, since that would mean I have two modified warehouses in my context, and I wouldn't know whether they were modified automatically during the "save" operation or they were modified directly by the user.

Of course, this simple example can also be solved without serializing a context, but imagine a scenario where the actions between clicking "save" and doing SaveChanges are more difficult to undo.

**Comment by Wain123** [comment]
Do you have any estimate on whether/when this feature will eventually be implemented? I'm considering implementing my own workaround, depending on how long I'd have to wait otherwise - and the target milestone has changed a few times so far. Any estimate that's more precise than "backlog" would be useful.

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
