### ISSUE TITLE
EFCore in DotNetStandard2.0 Library contains not found dependencies

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/efcore#9289]
I have EFCore installed in a DotNetStandard2.0 CL and everything is working fine except I get a warning on Build regarding not found packages and resolution has to take place

This is the warning I get on Build
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	Microsoft.Extensions.Primitives 2.0.0-preview1-final depends on 
System.Runtime.CompilerServices.Unsafe (>= 4.4.0-preview1-25219-04)
but System.Runtime.CompilerServices.Unsafe 4.4.0-preview1-25219-04 was not found. 
An approximate best match of System.Runtime.CompilerServices.Unsafe 4.4.0-preview1-25305-02 
was resolved.	
```

Installing System.Runtime.CompilerServices.Unsafe explicitly fixes warning
Install-Package System.Runtime.CompilerServices.Unsafe -Pre

### Steps to reproduce
Create New DotNetStandard2.0 CL
Add Microsoft.EntityFrameworkCore.SqlServer
Run Build

### Further technical details
EF Core version: 2.0.0-preview2-final
Database Provider: Sql Server
Operating system: Windows 10 Pro
IDE: VS 2017 Prevew 3

**Comment by smitpatel** [comment]
Can you share your csproj file and Nuget.config?

**Comment by isaac2004** [comment]
Certainly

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview2-final" />
  </ItemGroup>


</Project>

````

**Comment by smitpatel** [comment]
Check out https://github.com/aspnet/EntityFramework/issues/8923#issuecomment-310431600
In preview2-final there is no `SqlServer.Design` package. Please remove that line and try again.

**Comment by smitpatel** [comment]
After removing the stale package restore works fine for me.

**Comment by isaac2004** [comment]
That did it, thanks
