### ISSUE TITLE
Using ICurrentDbContext to access the current context during migrations

### ISSUE THREAD

**Issue by rmja** [dotnet/efcore#9302]
I am using a custom `SqlServerMigrationsSqlGenerator` to handle [multi tenant migrations](https://github.com/aspnet/EntityFramework/issues/4583). In 1.1 it was possible to let this custom generator depend on `ICurrentDbContext`. I could then determine the name of the tenant from a string property on the context, and handle sql generation operations appropriately.

In 2.0, `ICurrentDbContext` resolves to null making it impossible to determine the name of the tenant when handling migrations.

### Steps to reproduce
Create a custom migrations sql generator:
```
public class CustomSqlServerMigrationsSqlGenerator : SqlServerMigrationsSqlGenerator
    {
        public CustomSqlServerMigrationsSqlGenerator(MigrationsSqlGeneratorDependencies dependencies, IMigrationsAnnotationProvider migrationsAnnotations, ICurrentDbContext currentDbContextAccessor)
            : base(dependencies, migrationsAnnotations)
        {
            // currentDbContextAccessor is null
        }

        // The currentDbContextAccessor.Context is needed here to correctly handle migrations (the name of the tenant is needed)
    }
```
and register it with
```
.AddDbContext<Context>(options => options.ReplaceService<IMigrationsSqlGenerator, CustomSqlServerMigrationsSqlGenerator>())
```

### Further technical details
EF Core version: 2.0-preview2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by divega** [comment]
We wonder if there should be a way to ask the SQL Server migrations SQL generator to be scoped if customers want to be able to resolve scope services while using them.

**Comment by rmja** [comment]
@divega Do you have a suggestion for a temporary workaround?

**Comment by divega** [comment]
@rmja we wanted @ajcvickers to take a look but he won't be able to do it for a few days. 

This is just a guess but I believe you could try re-registering `SqlServerMigrationsSqlGenerator` in DI as `IMigrationsSqlGenerator` but with a scoped lifetime. 

Another approach would be to make the model tenant specific, e.g. adding an annotation with the tenant id to the model, which is already taken as a method parameter in `IMigrationsSqlGenerator.Generate()`.

**Comment by rmja** [comment]
Oh yes, this seems to work:

```
var services = new ServiceCollection()
                .AddEntityFrameworkSqlServer()
                .AddScoped<IMigrationsSqlGenerator, CustomSqlServerMigrationsSqlGenerator>() // Scoped instead of singleton
                .BuildServiceProvider();

            builder
                .UseSqlServer(connectionString)
                .UseInternalServiceProvider(services);
```

Thanks
