### ISSUE TITLE
Linq to query wrong query generation ?

### ISSUE THREAD

**Issue by irowbin** [dotnet/efcore#9313]
Describe what is not working as expected.

I have a linq query to get max with where clause, But i am getting values even if its null.
```c#
var max = _context.Table.Where( x => x.ParentId == dto.ParentId  ) // property is null
                                      .Max( x => x.Order);
```
Should generate the SQL like this i guess?
```sql
SELECT MAX([x].[Order])
FROM [Table] AS [x]
WHERE [x].[ParentId] = null
```
but i am getting the SQL like this.

```sql
SELECT MAX([x].[Order])
FROM [Table] AS [x]
WHERE [x].[ParentId] IS NULL  -- is should be equal (=) ?
```
Even the where clause predicate is falsy as null property, i am getting values? 

<br>
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
none
```

### Steps to reproduce

- Create Linq query to get max with where clause.
`.Where( x => x.ParentId == dto.ParentId  ).Max( x => x.Order)`

- Check the generated SQL query using SQL Server Profiler.

### Further technical details
EF Core version: `1.1.2`
Database Provider: `1.1.2`
Operating system: windows `10`
IDE:  Visual Studio 2017 release

**Comment by smitpatel** [comment]
What is the value of `dto.ParentId`?

**Comment by irowbin** [comment]
It is an `int` which is `nullable`

**Comment by smitpatel** [comment]
In T-SQL while using comparison operators, if any argument is null then it returns UNKNOWN which is different from how it works in C#. Hence `a == null` in C# gets translated to `a is NULL` in T-SQL. 
More info on null handling in t-sql here https://docs.microsoft.com/en-us/sql/t-sql/queries/is-null-transact-sql

To check if result from database actually match up with what in memory would give run this query,
`var maxInMemory = _context.Table.ToList().Where( x => x.ParentId == dto.ParentId  ).Max( x => x.Order);`
Both will give same results.

**Comment by irowbin** [comment]
You mean that any null arguments gets translated to a `is NULL`  and if i want to translate `is` to be `equal ` then i have to call `.ToList()` before comparison? That's what your saying? Thanks

**Comment by smitpatel** [comment]
Yes by default `== null` will get translated to `Is NULL` to get results as C# would expect. EF Core compensate for difference between database/in memory null handling. If you want to remove this processing done by EF and convert `== null` to database as `= NULL` then you can configure it.
On your `DbContextOptionsBuilder` (the `options` on which you call `UseSqlServer`) call `UseRelationalNulls()`
