### ISSUE TITLE
Setup and Deployment of Entity Framework Project

### ISSUE THREAD

**Issue by kumarsathishD** [dotnet/efcore#9325]
Hi EF Team ,

Thanks for making a EF an Open source project , so now we can contribute to it and make it much better.
I have a small clarification I won't say it as an issue.
How to move a project which used EF as a ORM into a production or to a client machine.
Let me explain you the scenario.
I have created a project in WPF which uses entity framework as an ORM, Now I need to pass the setup i.e exe/msi to the client machine. How to achieve it ? 
Currently I am creating a setup of the project using install shield of visual studio and then changing the connection string and all is done manually , Is there a process to avoid the same.

Cheers
Sathish

**Comment by divega** [comment]
@kumarsathishD it is unclear if this is question is about EF6 (for future reference, maintained at https://github.com/aspnet/entityframework6) or EF Core (maintained here). I know the repository name of the latter is confusing. That is why we are planning to rename this one very soon. 

Regardless, you would need to include all the assemblies from the product alongside the application in the installer package. 

For something like the connection string, I have seen several approaches:

1. Have it hardcoded (e.g. if the scope of the application is very small and this is acceptable)
2. Having in the configuration file or a separate file and modifying manually 
3. Include a step in the setup process that creates the right connection string
4. Include a configuration screen/page in the application that allows configuring and persisting the connection string, possibly invoked automatically on first usage. 

Regarding how to do it as part of the setup process, or even getting other, possibly better suggestions on how to do this, I would suggest you ask this question somewhere else, e.g. in https://stackoverflow.com, where you have more chances of finding experts on that area.

**Comment by milasch** [comment]
@divega Happy new year. 

I find it a bit convoluted to have two implementations of the same in this scenario: WPF targets ef core which targets .net core's implementation of `System.Collections.Immutable`, etc. But WPF also targets .NET framework which already implements `System.Collections.Immutable`. Should an assembly redirect be used so that the installer doesn't need to deploy the .NET core's implementations or that is just asking for trouble, if at all possible?
