### ISSUE TITLE
EF Core 2.0 Preview 2 - One-to-One relationship not working

### ISSUE THREAD

**Issue by michaelsogos** [dotnet/efcore#9327]
I have an issue regarding one-to-one relationship between two entities.

Both entities properties are created has expected in the [official docs](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#other-relationship-patterns), but if i make a simple linq query like `var entity = (from r in ctx.ParentEntity select r).FirstOrDefault()` then the navigation property to the child entity is always NULL.

I discovered that if i specifically include child entity in this way `(from r in ctx.ParentEntity.Include(p=>p.ChildEntity) select r).FirstOrDefault()` then everything works as expected .

There is a way to automatically include child entities, maybe within DbContext class implementation, to not waste our linq query?

**Comment by divega** [comment]
@anpete to answer with some information about what we do for owned types, but for now the recommended pattern is to use `Include()` explicitly in the query.

**Comment by anpete** [comment]
As @divega says, the only time we do automatic include is when the target navigation is owned.

@michaelsogos You can always add a method or property to your context that creates a ParentEntity query, initialized with any Includes you need. E.g.
```c#
// DbContext class
IQueryable<ParentEntity> Parents { get { return ParentEntity.Include(p => p.Children; ) } }
```
