### ISSUE TITLE
Android: Linq, System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by groege** [dotnet/efcore#9337]
See: https://github.com/mono/mono/pull/5246
IsComObject throws System.PlatformNotSupportedException, should return false, which has been fixed in mono. Problem is I'd really need a workaround asap until this is available to Xamarin, maybe someone here can help me with this?
The only workaround I know of would be to use ToList() and only then use linq... (but this would mean a lot of changes in the code which would always query all the data...)
It would be really awesome if anyone could give me some tips.

### Steps to reproduce
Use a expression with EF Core on android

```c#
using(var ctx = new SomeContext())
{
    ctx.SomeEntity.Any(x => x.SomeValue == "someValue");
}
```

### Further technical details
EF Core version: 1.1.2
Database Provider: SqLite
Operating system: Android
IDE: Visual Studio 2017 Preview 7

Edit:
For some reason this worked before, maybe IsComObject wasn't called before? If this is the case what could have changed that?

**Comment by divega** [comment]
@groege I am not sure what is calling `IsComObject`, but I am sure EF Core code does not call it directly. The call stack should indicate where it is coming from. 

Depending on when the call is happening, using SQL passed to `FromSql()` to filter the results may help.

**Comment by divega** [comment]
Hopefully the answer helps but otherwise it doesn't seem an actionable issue on EF Core, especially since the Mono issue seems to have been fixed. Closing.
