### ISSUE TITLE
2.0 RTM Query Specification Tests -  asserts all fail

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9338]
All the 2.0 RTM query tests now fail for me - what did I miss? 😄 
Expected \r\n - but get \n only now???

(This was working with 2.0-preview2 bits)

I am using:

        private void AssertSql(params string[] expected)
            => Fixture.TestSqlLoggerFactory.AssertBaseline(expected);

```
 Microsoft.EntityFrameworkCore.Specification.Tests.QuerySqlCeTest.Where_join_orderby_join_select [FAIL]
      Assert.Equal() Failure
                                        (pos 179)
      Expected: ···lCode], [c].[Region]\r\nFROM [Customers] AS [c]\r\nINNER JOIN [Or···
      Actual:   ···lCode], [c].[Region]\nFROM [Customers] AS [c]\nINNER JOIN [Orde···
                                        (pos 179)

```

### Further technical details
EF Core version: 2.0.0 RTM (myget feed)
Database Provider: SQL CE
Operating system: Win 10
IDE: (e.g. Visual Studio 2017)

**Comment by divega** [comment]
Looks like it could be a difference on how our repos treat line breaks/feeds.

**Comment by ErikEJ** [comment]
But this is blocking me from shipping 2.0 - I have 1200 failing tests :sad:

**Comment by smitpatel** [comment]
I was looking at code/commits/history.

There is nothing obvious which has changed causing such issue.
The expected output is correct. We use string builder to create the command which uses Env.NewLine so it should be CRLF. The actual output should contain the same, we do change EOL to file line endings but for us it is regular code, for others it can be a compiled code coming from somewhere so behavior may be different. Or it can be some issue in settings of git repo (git processes CRLF/LF based on repo settings)

If this is something incorrect in EF codebase then perhaps @roji may have hit it too.

**Comment by bricelam** [comment]
Very strange that `Environment.NewLine` appears to be returning `\n`. Especially since, I assume, your tests only ever run on Windows and .NET Framework...

**Comment by bricelam** [comment]
Could Mono be interfering somehow?

**Comment by ErikEJ** [comment]
Pure Windows! Something related to how 2.0 is built?

**Comment by bricelam** [comment]
Ah yes. Our current pattern replaces the new lines in the actual value. Our CI must either check out the code on Unix or with an older git client.

See does adding `*.cs eol=lf` to your `.gitattributes` workaround the issue? (may need to re-checkout the cs files after adding.)

**Comment by bricelam** [comment]
P.S. I'm trying to make the pattern more robust in #9332.

**Comment by ErikEJ** [comment]
Thanks so much for your help an advice so far.

Wonder what changed CI wise between preview-2 and RTM then?

This code change "fixes" the issue:

        private void AssertSql(params string[] expected)
        {
            foreach (var item in expected)
            {
                item.Replace("\r\n", "\n");
            }
            Fixture.TestSqlLoggerFactory.AssertBaseline(expected);
        }

**Comment by ErikEJ** [comment]
Closing, as I was able to workaround it...
