### ISSUE TITLE
Question: Logging of failing SQL statements in spec tests

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9343]
How is it I do that now? Is it:

TestSqlLoggerFactory.CaptureOutput(testOutputHelper);

(and also, how does this work when using xunit console runner?)

### Further technical details
EF Core version: 2.0.0 rtm
Database Provider: SQLCE
Operating system: 
IDE: VS 2017 preview 3

**Comment by smitpatel** [comment]
`Fixture.TestLoggerFactory.SetOutputHelper(testOutputHelper)` like this
https://github.com/aspnet/EntityFramework/blob/dev/test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs#L21

xUnit test project prints everything in testOutputHelper to VS output window. I am not sure what would be the output in the xunit console runner. It should be the same. Please check their documentation if you find any issues.

**Comment by ErikEJ** [comment]
Thanks, Smit, works like a charm!
