### ISSUE TITLE
Status of 'SQLite does not support schemas'

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/efcore#9345]
What is the status of using schemas in SQLite for [Unit Testing](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite)?  I tried reading through #329 but I could understand the state of things with regards to this specific feature.

EF Core version: 1.1.0
Database Provider: SQLite
Operating system: Win10
IDE: VS 2017

**Comment by bricelam** [comment]
The SQLite provider will ignore schemas in version 2.0.0 making multi-provider scenarios easier.

**Comment by bricelam** [comment]
See #6679

**Comment by spottedmahn** [comment]
@bricelam awesome, thanks!

**Comment by xaviergxf** [comment]
I'm still getting the following error when using Sqlite with HasDefaultSchema: no such table dbo.xyz after the creation of the database.

**Comment by bricelam** [comment]
@xaviergxf Can you submit a new issue?
