### ISSUE TITLE
Using command line with white background and dotnet ef tools

### ISSUE THREAD

**Issue by christiannagel** [dotnet/efcore#9346]
I'm often using a command line window with white background and black text as the default setting is not readable with some projectors.

With this setting, the unicorn logo cannot be seen, and more important: yellow warnings can't be read, e.g. warnings that show up when data might be lost on migrations.

Wouldn't it be possible to use colors dependent on the background?

**Comment by bricelam** [comment]
When considering this in the past, we found that most theme designers ensure the light colors remain visible when the background is light.

Instead of changing the default foreground and background colors, change the actual colors:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"ColorTable00"=dword:00ffffff
"ColorTable01"=dword:000000ff
"ColorTable02"=dword:0000ff00
"ColorTable03"=dword:0000ffff
"ColorTable04"=dword:00ff0000
"ColorTable05"=dword:00ff00ff
"ColorTable06"=dword:00ffff00
"ColorTable07"=dword:00000000
"ColorTable08"=dword:00c0c0c0
"ColorTable09"=dword:00000080
"ColorTable10"=dword:00008000
"ColorTable11"=dword:00008080
"ColorTable12"=dword:00800000
"ColorTable13"=dword:00800080
"ColorTable14"=dword:00808000
"ColorTable15"=dword:00808080


```

**Comment by bricelam** [comment]
Looks like [applying themes](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) just got a whole lot easier. You may want to try `solarized_light` for your scenario:
![image](https://user-images.githubusercontent.com/1226749/29280645-df65e284-80d0-11e7-8e6f-eaefcbbd0724.png)
