### ISSUE TITLE
inherited DbContext not found by CLI

### ISSUE THREAD

**Issue by santanaguy** [dotnet/efcore#9348]
I am designing a framework for our internal use. The plan is to have a base context defined in a .net standard 1.3 assembly and then the clients will derive from that context. The clients can use .Net full or .Net Core.
This works well so far for .Net Full, but i am having some trouble for the CLI to recognize my Context in a .Net Core 1.1 library. I am attaching a project to illustrate the issue but the general idea is:

1- Define a BaseContext in a .Net Standard 1.3 library
2- Add a reference to that library *as a direct dll reference* (if you add it as a project reference, the problem will go away apparently)
3- In a .Net Core 1.1 library define a SpecificContext that inherits from BaseContext
4- Try adding a migration or even use dotnef ef dbcontext list. This will fail because no context is found.

Things that i found that helped:
 * Change the target framework of the specific library to .NetCoreApp 1.0
 * Add the reference as a project (this is not really feasible for me outside this example)

[EF Bug.zip](https://github.com/aspnet/EntityFramework/files/1205280/EF.Bug.zip)

**Comment by bricelam** [comment]
I am not able to reproduce this on the solution provided...

You may want to try updating the following to 1.0.1.

``` xml
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet"
                        Version="1.0.0" />
```
