### ISSUE TITLE
Test: Remove dependency on SqlServer from EFCore.Design.Tests

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9352]
With recent changes in RevEng testsing `EFCore.Design.Tests` now depends on SqlServer. That is due to mainly 3 tests.
- `ScaffoldingTypeMapperSqlServerTest` - to verify if our scaffolding type mapper is working correctly.
- `RelationalScaffoldingModelFactoryTest` - Mainly, to evaluate if we are passing correct arguments to scaffolding type mapper.
- `ModelSnapshotSqlServerTest` - To verify generated model snapshot.

For all of above, the main reason to use `SqlServer` is typemapper, which is needed for `ScaffoldingTypeMapper` & `CoreConventionSetBuilder` 

We can add a fake type mapper which is rich enough to allow us to test each facet and remove dependency from SqlServer.

**Comment by divega** [comment]
**EF Triage:** We have a type mapper for testing, but we need to make it richer so we can use it for this.
