### ISSUE TITLE
Fluent mapping does not reflect changes to model

### ISSUE THREAD

**Issue by Shadetheartist** [dotnet/efcore#9359]
This will seem like some noob complaint but i assure you it's not. Please don't write this off as me being a goof with the data model and/or fluent syntax.

I recently removed an unnecessary foreign key column from my sql server data model. To mirror the change in my app i removed the same property and its navigation property from the POCO model class, then also removed the column and foreign key mapping from the (fluent syntax) code in my db context class. 

In my mind the application should have run just fine after these changes as the model class no longer contains any reference to the removed column whatsoever. Alas there is something causing an issue and i think it's due to EF.

My best guess is that *somewhere* there is a cached or otherwise alternative version of my old, unedited model type stepping in for the actual model. I have already tried deleting and recompiling the compiled binaries to no avail. 

```
Exception message: Invalid column name 'MaterialCategoryId'.

Stack trace:
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
System.Data.SqlClient.SqlDataReader.get_MetaData()
System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, string resetOptionsString)
System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, bool async, int timeout, out Task task, bool asyncWrite, SqlDataReader ds)
System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, TaskCompletionSource<object> completion, int timeout, out Task task, bool asyncWrite, string method)
System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, string method)
System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
System.Data.Common.DbCommand.ExecuteReader()
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, string executeMethod, IReadOnlyDictionary<string, object> parameterValues, bool closeConnection)
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable+Enumerator.BufferlessMoveNext(bool buffer)
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute<TState, TResult>(Func<TState, TResult> operation, Func<TState, ExecutionResult<TResult>> verifySucceeded, TState state)
Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute<TState, TResult>(IExecutionStrategy strategy, Func<TState, TResult> operation, TState state)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable+Enumerator.MoveNext()
Microsoft.EntityFrameworkCore.Query.QueryMethodProvider+<_ShapedQuery>d__3.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+<_TrackEntities>d__15.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor+EnumeratorExceptionInterceptor.MoveNext()
System.Collections.Generic.List..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)

... beyond this point is irrelevant and secret business stuff

```

#### Edit

I tried adding the field back into the model with the [NotMapped] data annotation, and now i get 

```c#
[NotMapped]
public int MaterialCategoryId { get; set; }
```

```
SqlException: Invalid column name 'MaterialCategoryId1'.
```

Which is the same column but with a `1` appended for what i assume is uniqueness. But why is EF so adamant about including this deleted column? Is there some cache file i can delete?

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Jetbrains Rider & Visual studio 2017 (it makes no difference)

**Comment by smitpatel** [comment]
> I recently removed an unnecessary foreign key column from my sql server data model. To mirror the change in my app i removed the same property and its navigation property from the POCO model class, then also removed the column and foreign key mapping from the (fluent syntax) code in my db context class.

Did you remove the inverse navigation property from target POCO model class?

If following are your classes
```C#
public class Blog
{
    public int Id { get; set; }
    public List<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```
Then removing `Post.BlogId` foreign key property & `Post.Blog` navigation will not remove relationship. There is still navigation `Blog.Posts` which indicate relationship between Post & Blog. And EF Core convention will create relationship for that. Since Post is dependent side (due to collection navigation), Convention will introduce shadow property named `BlogId` on Post class. If you add `Post.BlogId` and mark it as NotMapped then EF will name shadow property as `BlogId1` to avoid clash.

**Comment by Shadetheartist** [comment]
Yeah that worked. Thanks for the help!
