### ISSUE TITLE
Creating a database with EnsureCreated will fail if you refer to a SQL UDF in a computed column

### ISSUE THREAD

**Issue by JonPSmith** [dotnet/efcore#9368]
I have written some code that adds a computed column to an entity which calls a user defined function (UDF). I have the code to add the UDF, but in my unit test code, I cannot add that before I call `EnsureCreated`. Therefore the call to `EnsureCreated` fails.

This seems to be a Catch22 situation if I want to unit test something like this. Has anyone thought about how to get round this? @pmiddleton, what do you do when unit testing with SQL functions etc. added?

The is the exception I get when I call `EnsuredCreated`.
```
System.Data.SqlClient.SqlException : Cannot find either column "dbo" or the user-defined function or aggregate "dbo.udf_AverageVotes", or the name is ambiguous.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at test.UnitTests.DataLayer.Ch12_FixSubOptimalSql..ctor(ITestOutputHelper output) in C:\Users\Jon\Documents\Visual Studio 2017\Projects\EfCoreInAction\Test\UnitTests\DataLayer\Ch12_FixSubOptimalSql.cs:line 39
```

### Steps to reproduce

My two entity classes
```c#
public class FixSubOptimalSql
{
    public int FixSubOptimalSqlId { get; set; }
    public string Name { get; set; }
    public decimal? AverageVotes { get; set; }
    public ICollection<Ch12Review> Reviews { get; set; }
}
```
```c#
public class Ch12Review
{
    public const int NameLength = 100;

    public int Ch12ReviewId { get; set; }
    [MaxLength(NameLength)]
    public string VoterName { get; set; }
    public int NumStars { get; set; }
    public string Comment { get; set; }

    //-----------------------------------------
    //Relationships

    public int FixSubOptimalSqlId { get; set; }
}
```
My DbContext
```c#
public class Chapter12DbContext : DbContext
{
    public DbSet<IndexClass> IndexClasses { get; set; }
    public DbSet<FixSubOptimalSql> FixSubOptimalSqls { get; set; }

    public Chapter12DbContext(
        DbContextOptions<Chapter12DbContext> options)      
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IndexClass>()
            .HasIndex(p => p.WithIndex);

        modelBuilder.Entity<FixSubOptimalSql>()
            .Property(p => p.AverageVotes)
            .HasComputedColumnSql(
                "dbo.udf_AverageVotes([FixSubOptimalSqlId])");   
    }
}
```
My test code, including the ctor code to create the database and seed it
The code fails on the call to `EnsureCreated` in the test ctor
```c#
public class Ch12_FixSubOptimalSql
{
    private readonly ITestOutputHelper _output;
    private readonly DbContextOptions<Chapter12DbContext> _options;
    public Ch12_FixSubOptimalSql(ITestOutputHelper output)
    {
        _output = output;

        var connection = this.GetUniqueDatabaseConnectionString();
        var optionsBuilder =
            new DbContextOptionsBuilder<Chapter12DbContext>();

        optionsBuilder.UseSqlServer(connection);
        _options = optionsBuilder.Options;

        using (var context = new Chapter12DbContext(_options))
        {
            if (context.Database.EnsureCreated())
            {
                //only add the UDF if its a new database (as drop will fail as column uses it)
                var scriptFilePath = Path.Combine(TestFileHelpers.GetSolutionDirectory(),
                    @"Test\Chapter12Listings\EfCode\AddUserDefinedFunction.sql");
                connection.ExecuteScriptFileInTransaction(scriptFilePath);
            }

            if (!context.FixSubOptimalSqls.Any())
            {
                var entities = new List<FixSubOptimalSql>
                {
                    new FixSubOptimalSql
                    {
                        Name = "Book - no votes"
                    },
                    new FixSubOptimalSql
                    {
                        Name = "Book - one vote",
                        Reviews = new List<Ch12Review>
                        {
                            new Ch12Review { NumStars = 5}
                        }
                    },
                    new FixSubOptimalSql
                    {
                        Name = "Book - two votes",
                        Reviews = new List<Ch12Review>
                        {
                            new Ch12Review { NumStars = 2},
                            new Ch12Review { NumStars = 4},
                        }
                    },
                };
                context.AddRange(entities);
                context.SaveChanges();
            }
        }
    }

    [Fact]
    public void UseUdfToCreateOptimalSqlOk()
    {
        //SETUP

        using (var context = new Chapter12DbContext(_options))
        {
            var logIt = new LogDbContext(context);
            //ATTEMPT
            var entities = context.FixSubOptimalSqls.ToList();

            //VERIFY
            entities.Count.ShouldEqual(3);
            entities.Select(x => x.AverageVotes).ShouldEqual(new []{null, (decimal?)5, (decimal?)3 });
            foreach (var log in logIt.Logs)
            {
                _output.WriteLine(log);
            }
        }
    }
}
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 version 15.2

**Comment by pmiddleton** [comment]
The UDF unit tests don't verify that the functions exist in the database during OnModelCreating.  Therefore I have never run into this issue.  They are either already defined in the test database, or created after EnsureCreated runs via context.Database.ExecuteSqlCommand.

Your problem is that the create table statement for FixSubOptimalSql needs the udf defined before it can create the computed column.  

What you need is a way to run some raw sql during OnModelCreating to create the UDF if it does not exists.  AFAIK that feature does not exist.

**Comment by JonPSmith** [comment]
Hi @pmiddleton,

I *so* hoped you had an answer to that! Oh well. It seems that if I want to use UDFs in a computed column I would need to use scripts to create my database and use that same scripts to produce my unit test databases. Not as nice as calling `EnsureCreated`, but the only way around it I can see. 

Anyone else want to comment on this?

**Comment by smitpatel** [comment]
It is not just UDFs, even triggers and other things. `EnsureCreated()` creates database with EF only objects. Any database object created/managed outside of EF will not be there when using `EnsureCreated()`.

**Comment by JonPSmith** [comment]
Hi @smitpatel,

I am quite happy that `EnsureCreated` only creates EF only objects. I expected that and I run a method after `EnsureCreated` that takes a script file and adds the missing SQL parts to the newly created database.

 The problem I have is that `EnsureCreated` throws an exception because the UDF I use in a  computed column isn't in the database. This is a catch22 situation - I can't create the database to put the UDF before `EnsureCreated` is run, but when I run `EnsureCreated` it fails because the UDF isn't in place.

**Comment by JonPSmith** [comment]
I found a work around if anyone is interested.

1. Define my computed column, but with a constant
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<IndexClass>()
        .HasIndex(p => p.WithIndex);

    modelBuilder.Entity<FixSubOptimalSql>()
        .Property(p => p.AverageVotes)
        //The columed column is set to a constant to start
        //This column will be updated by the script that creates the UDF
        .HasComputedColumnSql("1");
}
```
2. In my SQL script that creates the database I drop the original computed column and add a computed column that uses the UDF.
```SQL
CREATE FUNCTION udf_AverageVotes (@id int)
RETURNS decimal  AS
BEGIN
DECLARE @result AS decimal
SELECT @result = AVG(NumStars) FROM dbo.Ch12Review AS r
     WHERE @id = r.FixSubOptimalSqlId
RETURN @result
END
GO

ALTER TABLE dbo.FixSubOptimalSqls
   DROP COLUMN AverageVotes
GO

ALTER TABLE dbo.FixSubOptimalSqls
   ADD AverageVotes AS (dbo.udf_AverageVotes([FixSubOptimalSqlId]))
GO
```

That works, because I can now call `EnsureCreated` followed by my method `ExecuteScriptFileInTransaction` with applies the script file.

Not the best solution, but works OK if I am using Migrations, as I can apply the same script inside the migration `Up` method. Not quite so good if I uses scripts to migrate the database, but in that case I would just have to build the test database via scripts and not use `EnsureCreated`.

**Comment by JonPSmith** [comment]
Feedback to EF team - I *think* others might bump into this sort of issue, as using computed columns with UDFs to 'fix' LINQ to SQL translations identified via the `QueryClientEvaluationWarning` warning is a valid use case. 

In my case I was fixing the issue that LINQ's `Average` method does not translate to SQL AVG (which EF6.x did).

**Comment by pmiddleton** [comment]
Average should be translated to AVG.  What query are you trying to run where it is not?

**Comment by JonPSmith** [comment]
Hi @pmiddleton,

That is great news about `Average`! I haven't moved to EF Core ver 2 yet. Still, the example/problem I describe is sound (but I'll have to change my example in the book :))

**Comment by divega** [comment]
@JonPSmith Thanks for reporting this. We had a brief discussion in triage about it and here is summary of our thoughts:

- `EnsureCreated()` is in general very limited and by-design does not provide the same flexibility as migrations, i.e. there is no hook in which you can provide your own DDL SQL fragments for something like this. 
- Given that, your workaround can be seen as the best current solution: create the schema without the function, then add the function and the reference to it in computed properties as a later step. 
- The only way we could avoid this is by making functions more first class, e.g.:
 - Add a way you can declare database functions in the model and specify what their implementation should be in the database.
 - Teach the model different to detect changes on them and DDL generation to create/drop and alter them.
 - Then both migrations and `EnsureCreated()` would the pick up this new ability 

I am going to go ahead and create a backlog issue for having functions declared in the model. I see an almost unbounded spectrum of things that could be done in this space, with the caveat that you should already be able to do anything by dropping down to SQL DDL statements if you are using migrations :smile:

**Comment by divega** [comment]
@JonPSmith @pmiddleton I have created https://github.com/aspnet/EntityFramework/issues/9393. I am going to close this issue, please reply if you think we missed anything actionable in this discussion.

**Comment by divega** [comment]
Closed-by-design because this is a limitation of the current design.
