### ISSUE TITLE
Migrations CLI Fails if default ASP.NET Configuration is used

### ISSUE THREAD

**Issue by SergeyBarskiy** [dotnet/efcore#9371]
Try to add a migration when default configuraiton provider is used using CLI
dotnet ef migrations add Initial
Exception will be thrown: Value cannot be null.

### Steps to reproduce
Create ASP.NET Core project that is using default configuration:
```csharp
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
```
Try to run ef migrations add.  This will throw the exception because it cannot find connection string.
Workaround:
```csharp
public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
            //support migrations with default configuration
            if (string.IsNullOrEmpty(Configuration["ConnectionStrings:DefaultConnection"]))
            {
                Configuration["ConnectionStrings:DefaultConnection"] = "Server=.;Database=ContactsDatabase;Trusted_Connection=True;MultipleActiveResultSets=true";
            }
        }
```
Another workaround - mark appsettings.json to copy to output folder always.

### Further technical details
EF Core version: 2.0 preview 2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
> Another workaround - mark appsettings.json to copy to output folder always.

This shouldn't be necessary since the current directory was switched to the project directory in version 2.0.0-preview1-final.

Could you share your `Program` class code?

**Comment by SergeyBarskiy** [comment]
Sure
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }

**Comment by SergeyBarskiy** [comment]
My bad.  I was still using version 1.0.1 of tools.  Did not realize it got renamed not to have .Net suffix.
