### ISSUE TITLE
ThenInclude() not giving proper IntelliSense for many-to-many/junction tables

### ISSUE THREAD

**Issue by Matthewsre** [dotnet/efcore#9374]
When setting up a manual many-to-many relationship table, using ThenInclude is not showing the properties of the ICollection object. Instead it just looks like IntelliSenseon a collection with Select, Where, etc.

The comments in this stackoverflow post for the accepted answer made me realize I could choose the next property even though it wasn't showing up in IntelliSense:
https://stackoverflow.com/questions/40319251/using-ef-core-theninclude-on-junction-tables

I tried searching for this issue but could not find it, so I thought I would log it here.

I am on Visual Studio Pro 2017 15.2 (26430.16) Release

**Comment by smitpatel** [comment]
duplicate  of #4117
External issue in Roslyn dotnet/roslyn#8237
