### ISSUE TITLE
[SQLCE 2.0 provider] FindEntityType changed/broken?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9375]
This was working in preview1 (I think...), at least in 1.1 - but no longer works in 2.0 rtm (based on MyGet feed)

        protected override void Generate(RenameIndexOperation operation, IModel model, MigrationCommandListBuilder builder)
        {
            Check.NotNull(operation, nameof(operation));
            Check.NotNull(builder, nameof(builder));

            if (model == null)
            {
                throw new NotSupportedException(string.Format(NotSupported, operation.GetType().Name));
            }

            //TODO entity is now null! :-(
            var entity = model.FindEntityType(operation.Table);
            var index = model.FindEntityType(operation.Table).GetIndexes().Single(i => _annotations.For(i).First().Name == operation.NewName);

            var dropIndexOperation = new DropIndexOperation
            {
                Name = operation.Name,
                IsDestructiveChange = true,
                Table = operation.Table
            };
            builder.EndCommand();
            Generate(dropIndexOperation, model, builder);

            var createIndexOperation = new CreateIndexOperation
            {
                Columns = index.Properties.Select(p => p.Name).ToArray(),
                IsUnique = index.IsUnique,
                Name = operation.NewName,
                Table = operation.Table
            };
            builder.EndCommand();
            Generate(createIndexOperation, model, builder);
        }

### Further technical details
EF Core version: 2.0.0-rtm-26452
Database Provider: SQLCE
Operating system: Win 10
IDE: VS 2017 15.3

**Comment by smitpatel** [comment]
I am not sure why it was working in earlier releases. `operation.Table` is just string name of the table. If you use that to search for EntityType in the model, it would never work. EntityType.Name is supposed to be Type.Name of clr type. You can use `FindEntityTypes` helper method which should be available in your derived class.

**Comment by ErikEJ** [comment]
Thanks!

**Comment by ajcvickers** [comment]
@ErikEJ Did you ever figure out why your code was working in 1.1 and then broke in 2.0? Is it anything we need to be concerned about?

**Comment by ErikEJ** [comment]
@ajcvickers I got the timeline wrong, it was never in 1.1!

**Comment by ajcvickers** [comment]
Thanks Erik. 😄
