### ISSUE TITLE
EntityFrameworkCore.SqlServer 2.0.0-preview2-final on net461

### ISSUE THREAD

**Issue by topguss** [dotnet/efcore#9383]
Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0-preview2-final is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Package Microsoft.EntityFrameworkCore.SqlServer 2.0.0-preview2-final supports: netstandard2.0 (.NETStandard,Version=v2.0)
One or more packages are incompatible with .NETFramework,Version=v4.6.1 (win7-x86).
If you are seeing an exception, include the full exceptions details (message and stack trace).

There is information that net461 support netstandard2.0!
[https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/)

**Comment by ErikEJ** [comment]
Which VS version and NuGet version? You must use VS 15.3 preview (or newer)

**Comment by topguss** [comment]
VS 15.2. I will try to update my VS. Thanks.
