### ISSUE TITLE
Unable to run Add-Migration command anymore on VS2017

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#9387]
I moved from one PC to a new PC where I had to re-install every thing including `VS2017`. When I run my same project from old PC to new PC (both Windows 10) app runs fine. I then added a new model and when I run the following Package Manager console command I get the following error shown below. The issue seems very similar to already reported [here](https://github.com/aspnet/EntityFramework/issues/7175) but that post was closed based on a  suggestion from `@Allen` that we try  `.SetBasePath(env.ContentRootPath)` in our Startup method. But as one can see we already have the above suggestion in our `Startup.cs` shown below. Could someone help us modify our `Startup.cs`  file below to help us resolve the issue? This is critical since it's keeping us from adding new models and/or modifying existing model(s).

    PM> add-migration myMigration -context TestProjContext

**Error**:

>An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not find 'UserSecretsIdAttribute' on assembly 'ef, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
No parameterless constructor was found on 'MyProjContext'. Either add a parameterless constructor to 'MyProjContext' or add an implementation of 'IDbContextFactory<MyProjContext>' in the same assembly as 'MyProjContext'.

**Startup.cs**:

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using TestProj.Data;
    using TestProj.Models;
    using TestProj.Services;
    
    namespace TestProj
    {
        public class Startup
        {
            public Startup(IHostingEnvironment env)
            {
                var builder = new ConfigurationBuilder()
                    .SetBasePath(env.ContentRootPath)
                    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
    
                if (env.IsDevelopment())
                {
                    // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                    builder.AddUserSecrets();
                }
    
                builder.AddEnvironmentVariables();
                Configuration = builder.Build();
            }
    
            public IConfigurationRoot Configuration { get; }
    
            // This method gets called by the runtime. Use this method to add services to the container.
            public void ConfigureServices(IServiceCollection services)
            {
                var connection = @"Server=MyWin10Desktop;Database=MySQL2012Db;Trusted_Connection=True;";
                services.AddDbContext<TestProjContext>(options => options.UseSqlServer(connection));
    
                // Add framework services.
                services.AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
    
                services.AddIdentity<ApplicationUser, ApplicationRole>()
                    .AddEntityFrameworkStores<ApplicationDbContext>()
                    .AddDefaultTokenProviders();
    
                services.AddMvc();
                services.AddDistributedMemoryCache();
                services.AddSession();
    
                // Add application services.
                services.AddTransient<IEmailSender, AuthMessageSender>();
                services.AddTransient<ISmsSender, AuthMessageSender>();
            }
    
            // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
            public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
            {
                loggerFactory.AddConsole(Configuration.GetSection("Logging"));
                loggerFactory.AddDebug();
    
                if (env.IsDevelopment())
                {
                    app.UseDeveloperExceptionPage();
                    app.UseDatabaseErrorPage();
                    app.UseBrowserLink();
                }
                else
                {
                    app.UseExceptionHandler("/Home/Error");
                }
    
                app.UseStaticFiles();
    
                app.UseIdentity();
                app.UseSession(); //me: must come before app.UseMvc()
    
                // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715
    
                app.UseMvc(routes =>
                {
                    routes.MapRoute(
                        name: "default",
                        template: "{controller=Home}/{action=Index}/{id?}");
                });
            }
        }
    }

**UPDATE**
This app was upgraded from `VS2015` to `VS2017` and if I remember correctly this is the first time I ran the `add-migration` command in `VS2017`. In` VS2015` I had been running this command frequently without any issue. So, issue may have been related to upgrade since the upgrade wizard removed the project.json file and replaced it with `.csproj` file. Following is entire content of my `.csproj` file. It seems the issue may have been related to [here ](https://github.com/aspnet/Announcements/issues/209) and [here ](https://github.com/aspnet/Announcements/issues/223) in these two GitHub posts. But I'm not sure what I would need to do.

**TestProj.csproj file**
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NameOfLastUsedPublishProfile>FolderProfile</NameOfLastUsedPublishProfile>
  </PropertyGroup>
</Project>`

**Comment by bricelam** [comment]
Update to...
```csharp
builder.AddUserSecrets<Startup>();
```

**Comment by saf-itpro** [comment]
@bricelam I have added an **UPDATE** at the end of my post above describing what may have been causing the error.

**Comment by saf-itpro** [comment]
@bricelam  I assume you are asking to go to `Startup.cs` and in the following constructor of Startup class change `builder.AddUserSecrets();` to `builder.AddUserSecrets<Startup>();`, correct? I did that and it **worked**. 

```
public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                builder.AddUserSecrets<Startup>();
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }
.....
}
```

**Comment by bricelam** [comment]
P.S. This 1.1.0 breaking change was announced in aspnet/Announcements#209.
