### ISSUE TITLE
How to Override EvaluatableExpressionFilter

### ISSUE THREAD

**Issue by yukozh** [dotnet/efcore#9397]
I'm the author of Pomelo.EFCore.MySql, Now I want to translate more method call, I've seen method call translation has been limited in the class `EvaluatableExpressionFilter`, so I'm finding a way to override this class. Any thoughts?

**Comment by smitpatel** [comment]
@Kagamine can you tell us which kind of method call you want to translate which requires overriding `EvaluatableExpressionFilter`? MethodCallTranslator is independent of the filter. Please give us an example of such query.

**Comment by Kagamine** [comment]
We want to create a static class contains the MySQL Miscellaneous Functions
https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html

**Comment by ajcvickers** [comment]
@anpete Can you provide some guidance on how to extend EF.Functions.

**Comment by pmiddleton** [comment]
For a database driver to add support for new functions it needs to do two things.

Derive from RelationalEvaluatableExpressionFilter and override IsEvaluatableMethodCall.  This method is used by ReLinq to know which functions will be translated by the driver.  ReLinq will attempt to evaluate any function not returned by this function when it reduces the query.

Derive from RelationalCompositeMethodCallTranslator and override Translate.  This is where the actual transformation from MethodCallExpression to SqlFunctionExpression is performed.

Make sure to call the base methods for those overridden methods.  Both of these classes need to be registered with DI.
