### ISSUE TITLE
Migration in different assembly than target assembly not happening 2nd time

### ISSUE THREAD

**Issue by rahulsahay19** [dotnet/efcore#9400]
Hi,

When I am trying to apply migrations 2nd time its not happening. I followed both the steps. However, in this migration, I am just trying to apply data-constraints on my both movie and moviereview classes. It gives me following error.

![156th](https://user-images.githubusercontent.com/3886381/29246917-622a63fa-8024-11e7-9f63-157c967b2405.png)

Source code is also available on git, you can check the same @ https://github.com/rahulsahay19/MovieReviewSPA-NG4

I tried my 2nd migration with below annotations on the class. Also, I am using Visual Studio 2017.
```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieReviewSPA.Model
{
    public class Movie
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string MovieName { get; set; }
        [Required]
        [StringLength(255)]
        public string DirectorName { get; set; }
        [Required]
        [StringLength(10)]
        public string ReleaseYear { get; set; }
        public virtual ICollection<MovieReview> Reviews { get; set; }

    }
}
```
and 
```csharp
using System.ComponentModel.DataAnnotations;

namespace MovieReviewSPA.Model
{
    public class MovieReview
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string ReviewerName { get; set; }
        [Required]
        [StringLength(500)]
        public string ReviewerComments { get; set; }
        [Required]
        public int ReviewerRating { get; set; }
        public int MovieId { get; set; }

    }
}
```
Thanks,
Rahul

**Comment by denismaster** [comment]
Try to set --project and --startup-project when running the command, like this
dotnet ef --project ../MovieReviewSPA.Data --startup-project . <migrations add, database update, etc>
