### ISSUE TITLE
How to add UWP Project

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9401]
_From @hannespreishuber on August 13, 2017 16:39_

I am running on 6.0.0-preview2-25612-02 of Microsoft.NETCore.UniversalWindowsPlatform and try to add a EntityFramework SQLClient Package,.
no idea how to.

Message form Nuget is
Das Paket Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview1-26636 ist nicht mit uap10.0.16257 (UAP,Version=v10.0.16257) kompatibel. Paket Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview1-26636 unterstützt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)

_Copied from original issue: aspnet/EntityFramework6#338_

**Comment by smitpatel** [comment]
_From @ErikEJ on August 13, 2017 17:5_

You have to stay on version 1.1.2 for now (until a newer version of UWP comes later this year)

**Comment by smitpatel** [comment]
_From @hannespreishuber on August 13, 2017 18:5_

doenst compile with 1.1.2 several Errors with the .net base data types

**Comment by smitpatel** [comment]
_From @hannespreishuber on August 13, 2017 18:8_

`<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <Version>1.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.0.0-preview2-25612-02</Version>
    </PackageReference>
  </ItemGroup>
  `

**Comment by smitpatel** [comment]
EF Core 2.0 & higher is supposed to work on UWP 6.0+ Perhaps there is some missing hook to get nuget to install the package.
Can you tell which version of VS & dotnet are you using?

**Comment by hannespreishuber** [comment]
Microsoft Visual Studio Community 2017 Preview
Version 15.3.0 Preview 7.0
VisualStudio.15.Preview/15.3.0-pre.7.0+26730.0
Microsoft .NET Framework
Version 4.7.02542

Installierte Version: Community

Visual Basic 2017   00369-60000-00001-AA269
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA269
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA269
Microsoft Visual C++ 2017

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

Application Insights-Tools für Visual Studio-Paket   8.8.00712.1
Application Insights-Tools für Visual Studio

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
For additional information, visit https://www.asp.net/

Azure App Service-Tools v3.0.0   15.0.30728.0
Azure App Service-Tools v3.0.0

JavaScript-Sprachdienst   2.0
JavaScript-Sprachdienst

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP-Projektsystem   2.0
JavaScript UWP-Projektsystem

Microsoft Azure-Tools   2.9
Microsoft Azure-Tools für Microsoft Visual Studio 2017 – v2.9.50719.1

Microsoft Continuous Delivery-Tools für Visual Studio   0.3
Die Konfiguration der fortlaufenden Buildintegration und der fortlaufenden Buildbereitstellung innerhalb der Visual Studio-IDE wird vereinfacht.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++-Assistenten   1.0
Microsoft Visual C++-Assistenten

NuGet-Paket-Manager   4.3.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter "http://docs.nuget.org/".

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

TypeScript   2.3.4.0
TypeScript-Tools für Visual Studio

VC-Paket für Microsoft Visual Studio   1.0
VC-Paket für Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools für universelle Windows-Apps   15.0.26730.00
Mit den Visual Studio Tools für universelle Windows-Apps können Sie eine universelle App-Erfahrung erstellen, die auf jedem Gerät genutzt werden kann, das Windows 10 ausführt: Smartphone, Tablet, PC und viele weitere Geräte. Das Microsoft Windows 10 SDK ist in den Tools enthalten.

**Comment by hannespreishuber** [comment]
C:\Users\pre>dotnet --version
2.0.0

**Comment by ajcvickers** [comment]
@AndriySvyryd This seems to be the same issue you were hitting when testing UWP. Is there an external NuGet issue we can reference? Also, can you post the "assets fallback" workaround? (Or let me know I'm off-base if this is a different issue. 😸)

**Comment by AndriySvyryd** [comment]
@hannespreishuber This is a known NuGet issue, it's fixed in version 4.3.0.4365. As a workaround add this to your project file:
```
  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);netstandard2.0</PackageTargetFallback>
  </PropertyGroup>
```

**Comment by AndriySvyryd** [comment]
@hannespreishuber Note that if you compile in release mode most queries will currently fail due to https://github.com/aspnet/EntityFramework/issues/9355

**Comment by emiliano84** [comment]
@smitpatel where can I kindly find  6.0.0 previews of Microsoft.NETCore.UniversalWindowsPlatform?

and guys is there any way to follow its development/roadmap? for ef, .net core and asp.net core I found everything on github, but for UWP I couldn't. thanks!

**Comment by AndriySvyryd** [comment]
@emiliano84 You can get the daily builds from https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json

But to compile you will also need Windows 10 RS3 Insider Preview, the corresponding SDK and Visual Studio 15.4 Preview

**Comment by divega** [comment]
@AndriySvyryd FWIW, PackageTargetFallback is deprecated and customers should use AssetTargetFallback instead.
