### ISSUE TITLE
And how about AutoDetectChangesEnabled with AddDbContextPool in ef core 2.0?

### ISSUE THREAD

**Issue by ChristopherRobinSuperStar** [dotnet/efcore#9417]
Now I get  "System.InvalidOperationException: 'OnConfiguring cannot be used to modify DbContextOptions when DbContext pooling is enabled.'"

And is it nessesary to set it like this or what is the best way to do it?
db.ChangeTracker.AutoDetectChangesEnabled = false;
db.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;

Thanks!

**Comment by ajcvickers** [comment]
@ChristopherRobinSuperStar When using DbContext pooling the best approach is to build the DbContextOptions externally and pass it to the DbContext constructor. When using AddDbContext (typically for ASP.NET Core applications) this is done using something like this:
```C#
services.AddDbContext<BloggingContext>(
    options => options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking));
```
If not using AddDbContext, then create a new DbContextOptionsBuilder explicitly and use this in the same way.

Note that AutoDetectChangesEnabled has always been a property of ChangeTracker and so should never be configured in OnConfiguring.

**Comment by changhengyu** [comment]
您好，我想请教一个问题，在.net 6的efcore 中使用连接池，我使用了配置中心，当我的数据库连接字符串变化后，想重新生成新的连接池实例，如何做到呢
![image](https://user-images.githubusercontent.com/29672730/185079159-b605e7d9-48fb-4a13-8bd0-0130e942da43.png)
