### ISSUE TITLE
context.Database.GetDbConnection() should expose also the ConnectionId

### ISSUE THREAD

**Issue by fitzchak** [dotnet/efcore#9428]
Maybe it is better to add GetConnection which would return the IRelationalConnection which also expose the ConnectionId in addition to the DbConnection.

See: https://github.com/aspnet/EntityFramework/blob/fbaebcbfb57f245edfded68f0bad78f4978d8867/src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs#L336

**Comment by ajcvickers** [comment]
@fitzchak We had a design similar to that in the early days of EF Core, but we decided to simplify the API by collapsing the connection. Things that are commonly used are exposed directly or as extension methods. However, things like ConnectionId are relatively low level and so not exposed directly. For code that does need access it's quite easy to get the IRelationalConnection when needed:
```C#
var connection = context.GetService<IRelationalConnection>();
```
