### ISSUE TITLE
Add a way to observe transactions commit/rollback

### ISSUE THREAD

**Issue by ArnaudDebaene** [dotnet/efcore#9429]
It would be usefull to add an API to be able to observe transactions commit/rollback. For example, an event TransactionCompleted could be added to IDbContextTransaction (similar to what is available in Systm.Transactions.Transaction)

**Comment by ajcvickers** [comment]
@ArnaudDebaene I've added a note to #626, which the the overall issue covering this kind of event. For now, you might want to look into what events are available on DbConnection and DbTransaction and try using those directly.
