### ISSUE TITLE
Refernce 'Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0' Fails

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#9430]
We are trying to reference Microsoft.EntityFrameworkCore.Tools.DotNet from our scaffold project (netcoreapp2.0). We get this error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Package 'Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0' has a package type 'DotnetCliTool' that is not supported by project 'z_scaffold\db.scaffold'

```
Exception message:
Stack trace:
```

### Steps to reproduce
Create new netappcore2.0 project and try to reference Microsoft.EntityFrameworkCore.Tools.DotNet

### Further technical details
EF Core version:2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 (latest patches)
IDE: (e.g. Visual Studio 2017 15.3)

UPDATE: What we had to do is add the line:
` <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />`
to the csproj file directly

**Comment by smitpatel** [comment]
External issue https://github.com/NuGet/Home/issues/4190
