### ISSUE TITLE
EF Core 2.0 includes not accessible in WHERE with NotMapped Property

### ISSUE THREAD

**Issue by amirreza58** [dotnet/efcore#9440]
I have 2 entity 
```c#
    public class ProductsTable
    {

        [Key]
        public int id { get; set; }

        public string name { get; set; }

        public bool track_inventory { get; set; }
        .
        .
        .
        .
        .

        /* ---------------------------------------------------------------------- */
        /*	Relations
        /* ---------------------------------------------------------------------- */
        public virtual ProductsInventoryTable ProductsInventory { get; set; }


        /* ---------------------------------------------------------------------- */
        /*	Extra 
        /* ---------------------------------------------------------------------- */

        [NotMapped]
        public int view_availability
        {
            get
            {
                int retValue = 0;

                .
                .
                .

                if (track_inventory) {
                    if (ProductsInventory.stock <= 0)
                    {
                        return 1;
                    }
                }

                return retValue;

            }
        }


    }

```
```c#
public class ProductsInventoryTable
    {

        public ProductsInventoryTable()
        {
            stock = 0;
        }


        [Key]
        public int id { get; set; }

        public int product_id { get; set; }
        public int stock { get; set; }

        public virtual ProductsTable Product { get; set; }

```
and there relations (works well in EF core 1.x)

this code works well in EF core 1.x:

```c#
                _dbContext.products
                        .Include(x => x.ProductsInventory)
                        .Where(x => x.view_availability == 0)
                        .AsNoTracking()
                        .ToList();


```
after upgrading to EF core 2.0.0 with same database :

```
Exception message: NullReferenceException: Object reference not set to an instance of an object.
Stack trace: (ProductsInventory.stock == 0) { return 1; }
```
NullReferenceException for ProductsInventory ,its looks like view_availability property dose not access to ProductsInventory 

this code works :
```c#
                _dbContext.products
                        ...
                        .Where(x => x.ProductsInventory.stock > 0)
                        ...
                        .ToList();

```
so my ProductsInventory is not null

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Server 2016
IDE: Visual Studio 2017 15.3

**Comment by smitpatel** [comment]
Since where is on client, work-around
```
_dbContext.products
    .Include(x => x.ProductInventory)
    .AsNoTracking()
    .ToList()
    .Where(x => x.view_availability == 0)
    .ToList();
```

**Comment by ajcvickers** [comment]
@smitpatel or @anpete Can one of you write down the ideas we had here so we don't forget them?

**Comment by AndriySvyryd** [comment]
A reminder for @smitpatel or @anpete to write down the ideas discussed.

**Comment by smitpatel** [comment]
I have already forgotten :trollface: 
@anpete can write down the ideas 

Adding @maumar on the thread since we stumbled upon such issue here https://github.com/aspnet/EntityFrameworkCore/issues/9551

Include is a result operator and it causes a subquery formation which is flattened out later. But if the include is made sufficiently localized that it would work on the exact QM its been applied on then this case would work (we would have attached related data before evaluating where on client). The linked issue faced the same issue because of the group by was applied after Include and after group by everything got tangled on where exactly the include should be applied.

**Comment by smitpatel** [comment]
Also consider https://github.com/aspnet/EntityFrameworkCore/issues/3418

**Comment by AndriySvyryd** [comment]
@smitpatel by design?

**Comment by smitpatel** [comment]
By design since Where cannot evaluate on client. If in projection then Include would be populated before calling into it. (#15181)
