### ISSUE TITLE
PropertyBuilder specific methods can be used by different property types

### ISSUE THREAD

**Issue by rooonikz** [dotnet/efcore#9441]
In EF6 we have type specific types and its' methods (e.g. StringPropertyConfiguration and IsUnicode()) to configure mapping between C# Entity and SQL Table. Now, in EF Core we can apply IsUnicode() method of PropertyBuilder<T> FluentAPI even on datetime type and so on. Would not it be better to have only type specific PropertyBuilders as it was previously implemented in EF 6 ? Thanks.

### EF 6
```c#
    public StringPropertyConfiguration IsUnicode(bool? unicode)
    {
      this.Configuration.IsUnicode = unicode;
      return this;
    }
```
### EF Core
```c#
    // TProperty has no constraint
    public virtual PropertyBuilder<TProperty> IsUnicode(bool unicode = true)
    {
      return (PropertyBuilder<TProperty>) base.IsUnicode(unicode);
    }
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@rooonikz There were several reasons for doing things differently in EF Core, but the probably the most important is that EF Core can be used with any CLR type that a database provider can map, while EF6 only worked with a limited set of pre-defined CLR types.
