### ISSUE TITLE
dotnet core cli missing option

### ISSUE THREAD

**Issue by wli3** [dotnet/efcore#9443]
_From @daviatorstorm on August 16, 2017 11:35_

`dotnet core cli` missing `-e` (environment) option in command line.
I'm trying to make a migration and database update using `ef core` tools, but I cannot do it so easy as with `-e` option

_Copied from original issue: dotnet/cli#7454_

**Comment by wli3** [comment]
Hi @daviatorstorm,

Thank you for the issue. Are you referencing this issue?

>EF Core 1.x CLI tools supported an argument called environment which could be use to specify the environment when the commands were run against an ASP.NET Core application. This argument is no longer available in 2.0:
console
-e|--environment <NAME>                The environment to use. Defaults to "Development".
With 2.0, you can use the ASPNETCORE_ENVIRONMENT environment variable instead.

If so ASPNETCORE_ENVIRONMENT can be used instead. 

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

**Comment by wli3** [comment]
_From @daviatorstorm on August 17, 2017 8:0_

Hello @wli3,

I'm using TeamCity as CI and multi environment. So I tried to specify directly in project directory a `ASPNETCORE_ENVIRONMENT` variable. But it doesn't work for me.

So I rolled back to `1.1`.

**Comment by wli3** [comment]
Hi @bricelam @natemcmaster  could you help me with this issue?

**Comment by wli3** [comment]
_From @natemcmaster on August 17, 2017 16:56_

@wli3 this isn't the right project for the issue. I recommend you move this here: https://github.com/aspnet/entityframeworkcore

**Comment by bricelam** [comment]
How are you running the command? Can't you just update the invocation to something like this?
```cmd
SET ASPNETCORE_ENVIRONMENT=NotDevelopment
dotnet ef database update
```
