### ISSUE TITLE
Test: Use mix of ConnectionString/Connection in SqlServer functional tests

### ISSUE THREAD

**Issue by smitpatel** [dotnet/efcore#9457]
The new testing pattern uses shared connection between tests in a fixture. We should have mix of connection string and connection pattern since most of our customers uses connection string.

**Comment by AndriySvyryd** [comment]
Currently there are 16 SqlServer test containers using connection string

**Comment by ajcvickers** [comment]
@AndriySvyryd  and @anpete to decide when enough is enough.
