### ISSUE TITLE
Migration column renaming causes a failing query?

### ISSUE THREAD

**Issue by LeonardoDaga** [dotnet/efcore#9475]
Sorry. I'm not an expert. So I apologize if I don't use the right terms to describe the issue.

What I found is that a simple query
```c#
            var Teams = from t in context.Team
                        where t.ChampID == champID
                        select t;
```
returns an empty collection even if there are several Team objects with the ChampID requested.
ChampID is a nullable int navigation property of the class Team. 
When I create the first migration to add the table related to Team, the migration tool creates a column named "ChampID1":
`ChampID1 = table.Column<int>(type: "int", nullable: true),`
a foreign key:
```c#
            migrationBuilder.AddForeignKey(
                name: "FK_Team_Champ_ChampID1",
                table: "Team",
                column: "ChampID1",
                principalTable: "Champ",
                principalColumn: "ID",
                onDelete: ReferentialAction.Restrict);
```
and an index:
```c#
            migrationBuilder.CreateIndex(
                name: "IX_Team_ChampID1",
                table: "Team",
                column: "ChampID1");
```

The class Team is defined as follows:
```c#
public class Team
{
        [ScaffoldColumn(false)]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Team Name")]
        public string TeamName { get; set; }

        // Navigation property
        [ScaffoldColumn(false)]
        public int? ChampID; 
        public Champ Champ { get; set; }
...
```
To be noted that in this case I can make the code working simply referring to the ID of the Champ class instead of the ChampID.

I wonder if I'm doing something wrong or the remapping of the ChampID property to the ChampID1 database column creates an issue in some specific cases. 
To be noted also that (I don't know why), when I first created this project with VS2015, EF Core 1.0 and ASP.NET core 1.0 everything was working and the query above successfully returned the list of the Team with the desired ChampID property. Moreover the column ChampID was not renamed to ChampID1 during the migration.

Thank you for any help.

```
Exception message: none. The output collection is simply empty.
Stack trace:
```
### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.Tools 2.0.0
Database Provider:SQL Server Express 13.0.4001
Operating system: Windows 10 Pro 15063
IDE: Visual Studio 2017 15.3

**Comment by ajcvickers** [comment]
@LeonardoDaga We're finding it a little difficult to understand what is going on here. Could you provide a complete code listing or attach a project that demonstrates the issue you are seeing?

**Comment by LeonardoDaga** [comment]
Hello @ajcvickers , 
I created a repository just to evidence this problem.
The created website, from scratch, includes just three classes. 
One of them is the Team class that has a reference to the Champ class ID, a nullable int.
Creating the migration, the Team column that contains the Champ ID is named ChampID1, even if there is no ambiguity with other names.

Seeding the database (there is an utility function in the folder Utility, called by the Startup.cs) the ChampID1 is not filled with the Champ ID, even if the Team item added to the table is properly initialized.
The Player objects, instead, that have the same relation with the Teams but with a non-nullable integer ID, are properly initialized. 

You can run the project and check it by yourself.
https://github.com/LeonardoDaga/EF20AspNet20Test

One more problem is that, when updating the database with the migrations generated with "dotnet ef migrations add <name>", something bad happens when the models are still not in the database and there is some code that already refers to that models. 
I had to comment out the seeding function to let the "dotnet ef database update" work correctly.

**Comment by ajcvickers** [comment]
@LeonardoDaga `ChampID` is a field, not a property, so it is not mapped by default by EF. Make it a property and it should work.

(If you really want to keep it a field, then it needs to be mapped explicitly. Something like this:
```C#
modelBuilder.Entity<Team>().Property("ChampID");
```)

**Comment by LeonardoDaga** [comment]
Well, thank you. I missed this point. 
As I premised, I'm new to this technology.
