### ISSUE TITLE
UWP: Unable to use Microsoft.EntityFrameworkCore.Sqlite Version 2

### ISSUE THREAD

**Issue by brightcr** [dotnet/efcore#9482]
The solution is not building with latest stable version of Microsoft.EntityFrameworkCore.Sqlite 2.0.0 and getting below compiler error:

- The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

Due to this other types e.g. DbContext from this namespace are not found

It is not working with reloading project, restarting visual studio, PC, etc.

However, it is working if downgraded to Version: 1.1.2

### Steps to reproduce
Install Package Microsoft.EntityFrameworkCore.Sqlite 2.0.0

Add some code to refer EF Core e.g.
``` C#
using Microsoft.EntityFrameworkCore;
namespace SQLLiteStorageApp.Models
{
    class BloggingContext : DbContext
    {
    }
}

```
Build solution

Actual : Compiler Error
Expected: Solution should build

### Further technical details
EF Core version: 2.0.0
Project Type: UWP App
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 1607 (14393.1593)
IDE: Visual Studio 2017 (15.3)

**Comment by smitpatel** [comment]
which version of UWP?

**Comment by brightcr** [comment]
Latest Version 5.4.0

**Comment by smitpatel** [comment]
To use EF Core 2.0 with UWP you would need UWP 6+ (which is in prerelease state at present)
See https://github.com/aspnet/EntityFrameworkCore/issues/9401 for more details on prerequisites and how to use EF Core 2 in UWP 6.
