### ISSUE TITLE
Consider trying to make it clearer that IDesignTimeDbContextFactory should not be registered as a service

### ISSUE THREAD

**Issue by divega** [dotnet/efcore#9490]
Comments like https://github.com/aspnet/EntityFrameworkCore/issues/8499#issuecomment-323554888 and others seem to debunk any belief that renaming the type could help clarify how it is used. 

I am not sure anything is going to help significantly but it seems we haven’t taken the chance to say “do not register this as a service” in the API docs. It is possible we could do better in the conceptual docs as well, and in any exception message that leads to using the type.

**Comment by ajcvickers** [comment]
@divega Can this be moved out of the 2.1 milestone. (We are trying to make 2.1 only include issues that we must fix for 2.1)

**Comment by divega** [comment]
We could punt, or just do it now. Removing myself in case someone else can take care of it this week.
