### ISSUE TITLE
Method incorrect declaration

### ISSUE THREAD

**Issue by rooonikz** [dotnet/efcore#9500]
When you want to use IdentityBuilder to setup Identity services for your application (e.g. AddUserStore<>() AddRoleStore<>() AddPasswordValidator<>() and so on). When you have looked at these methods' declarations, you will see: 

```c#
    public virtual IdentityBuilder AddUserStore<TUser>() where TUser : class
    {
      return this.AddScoped(typeof (IUserStore<>).MakeGenericType(this.UserType), typeof (TUser));
    }
```

Looking at _**TUser**_ type, you are thinking about passing User type as generic parameter. Using Autofac DI container integration I have got this ArgumentException:

```
ArgumentException: The type 'CMS.Domain.User' is not assignable to service 'Microsoft.AspNetCore.Identity.IUserStore`1[[CMS.Domain.User, CMS.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'.
```
Then I decompile AddScoped() method, and here what I see:

```c#
    private IdentityBuilder AddScoped(Type serviceType, Type concreteType)
    {
      this.Services.AddScoped(serviceType, concreteType);
      return this;
    }
```
AddScoped method second argument is concreteType! As I think, it would be better to replace **`Add*WhateverIdentityService*<TUser> where TUser: class`**  by **`Add*WhateverIdentityService*<TWhateverIdentityService> where TWhateverIdentityService: class`** to avoid disagreements. Thank you.

### Further technical details
EF Core version: EF Core 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/Identity/issues/1382
