### ISSUE TITLE
'Reference to type 'BaseControlContext" claim it is defined in Microsoft.AspNetCore.Authentication, but it could not be found.

### ISSUE THREAD

**Issue by muhsohail** [dotnet/efcore#9520]
**Issue:**

I am below facing weird issue. 

_

> **"Reference to type 'BaseControlContext" claim it is defined in Microsoft.AspNetCore.Authentication, but it could not be found.**

_

I am reading and creating OpenID Connect server with ASOS this article ASOS - AspNet.Security.OpenIdConnect.Server.

Article link: [http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-introduction/](url)

I simply created new sample solution and added new subclass AuthorizationProvider class of OpenIdConnectServerProvider and override the virtual method i.e. ExtractAuthorizationRequest

**Code**:

I am just pasting line causing problem.
```C#
    public class AuthorizationProvider : OpenIdConnectServerProvider
    {
        public override Task ExtractAuthorizationRequest(ExtractAuthorizationRequestContext context)
        {
            // If a request_id parameter can be found in the authorization request,
            // restore the complete authorization request stored in the user session.
            if (!string.IsNullOrEmpty(context.Request.RequestId))
            {
                var payload = context.HttpContext.Session.Get(context.Request.RequestId);
                if (payload == null)
                {
                    context.Reject(
                        error: OpenIdConnectConstants.Errors.InvalidRequest,
                        description: "Invalid request: timeout expired.");
                    return Task.FromResult(0);
                }
                // Restore the authorization request parameters from the serialized payload.
                using (var reader = new BsonReader(new MemoryStream(payload)))
                {
                    foreach (var parameter in JObject.Load(reader))
                    {
                        // Avoid overriding the current request parameters.
                        if (context.Request.HasParameter(parameter.Key))
                        {
                            continue;
                        }
                        context.Request.SetParameter(parameter.Key, parameter.Value);
                    }
                }
            }
            return Task.FromResult(0);
        }
    }
```

Actually as soon as i add Microsoft.AspNetCore.Identity (2.0.0) NuGet package to my project, context.Reject start giving the following error

**"Reference to type 'BaseControlContext" claim it is defined in Microsoft.AspNetCore.Authentication, but it could not be found.**

But as soon as I remove Microsoft.AspNetCore.Identity NuGet dependency, the error goes away and all looks fine.

### Further technical details
EF Core version: >netcoreapp2.0 
Database Provider:Microsoft.EntityFrameworkCore.SqlServer / Microsoft.AspNetCore.Identity]
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017)

**Comment by ajcvickers** [comment]
@littleKing82 This doesn't sound like it is an Entity Framework issue. It is most likely related to a mix of different package versions. Make sure that all Microsoft ASP.NET/Extensions packages have been updated 2.0 and that no 1.x packages are being referenced, possibly by external packages. If this does not solve the problem, I would suggest following up with the authors of the third-party OpenID code, or on https://github.com/aspnet/Security or https://github.com/aspnet/Identity.
