### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by falps** [dotnet/efcore#9533]
When batch updates and additions occur, the following error occurs:
An item with the same key has already been added. Key: p2068，
StackTrace:
at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at System.Collections.Generic.Dictionary2.Add(TKey key, TValue value)
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.CreateStoreCommand()
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable1 commandBatches, IRelationalConnection connection) at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList1 entries)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by falps** [comment]
My test environment is as follows：
system:win10 ,
database:mysql 5.7 , 
Entity Framework Core provider for MySql: Pomelo.EntityFrameworkCore.MySql  2.0.0-rtm-10058
EF version 2.0 
IDE: Visual Studio 2017
code:
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Compute();
            Console.Read();
        }
        private static void Compute()
        {
            List<share_details> _lishare = new List<share_details>();
            List<consumption_details> _liconsumpe = new List<consumption_details>();
            List<sales_details> _lisale = new List<sales_details>();
            for (int i = 0; i < 5000; i++)
            {
                share_details sh1 = new share_details();
                sh1.coins = 100;
                sh1.create_time = DateTime.Now;
                sh1.ip = "127.0.0.1";
                sh1.new_balance = 1000;
                sh1.new_coins = 1000;
                sh1.old_balance = 999;
                sh1.old_coins = 999;
                sh1.type = 1;
                sh1.user_id = i;
                _lishare.Add(sh1);
                sh1 = new share_details();
                sh1.coins = 100;
                sh1.create_time = DateTime.Now;
                sh1.ip = "127.0.0.1";
                sh1.new_balance = 1000;
                sh1.new_coins = 1000;
                sh1.old_balance = 999;
                sh1.old_coins = 999;
                sh1.type = 1;
                sh1.user_id = i;
                _lishare.Add(sh1);
                consumption_details con = new consumption_details();
                con.create_time = DateTime.Now;
                con.from_original_points = 1000;
                con.from_uid = 100;
                con.points = 1000;
                con.to_original_points = 1000;
                con.to_uid = i;
                con.type = 1;
                con.uid = i;
                _liconsumpe.Add(con);

                var salepoint = new sales_details();
                salepoint.create_time = DateTime.Now;
                salepoint.points = 100.1;
                salepoint.to_original_points = 1000;
                salepoint.to_uid = i;
                salepoint.type = 1;
                _lisale.Add(salepoint);

            }

            try
            {
                using (var context = new ShareBaContext())
                {
                    foreach (var item1 in _lishare)
                    {
                        context.share_details.Add(item1);
                        break;
                    }
                    foreach (var item2 in _liconsumpe)
                    {
                        context.consumption_details.Add(item2);
                    }
                    foreach (var item in _lisale)
                    {
                        context.sales_details.Add(item);
                    }
                    context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }
    }
    public class sales_details
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
      
        public DateTime create_time { get; set; }
       
        public double to_original_points { get; set; }
       
        public double points { get; set; }
       
        public long to_uid { get; set; }

        public byte type { get; set; }
       
        public long rewareID { get; set; }
     
        public string reponsetext { get; set; }

    }
    public class consumption_details
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
       
        public DateTime create_time { get; set; }
     
        public double from_original_points { get; set; }
       
        public double to_original_points { get; set; }
       
        public double points { get; set; }
       
        public long from_uid { get; set; }
      
        public long to_uid { get; set; }
       
        public byte type { get; set; }

        /// <summary>
        /// 奖励积分ID
        /// </summary>
        public long rewareID { get; set; }
        /// <summary>
        /// 回复内容
        /// </summary>
        public string reponsetext { get; set; }
        public long uid { get; set; }

    }
    public class share_details
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
      
        public DateTime create_time { get; set; }
       
        public long user_id { get; set; }
      
        public double new_coins { get; set; }
       
        public double old_coins { get; set; }
      
        public double new_balance { get; set; }
      
        public double old_balance { get; set; }
       
        public string ip { get; set; }
       
        public double coins { get; set; }

       
        public byte type { get; set; }

    }
    public class ShareBaContext : DbContext
    {
        public DbSet<consumption_details> consumption_details { get; set; }

        public DbSet<sales_details> sales_details { get; set; }

        public DbSet<share_details> share_details { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
           optionsBuilder.UseMySql("Server=localhost;database=testmysql;uid=root;pwd=123456;");
        }
    }
}

sql:
/*
SQLyog Professional v12.09 (64 bit)
MySQL - 5.7.17-log : Database - testmysql
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`testmysql` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `testmysql`;

/*Table structure for table `consumption_details` */

DROP TABLE IF EXISTS `consumption_details`;

CREATE TABLE `consumption_details` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `from_uid` bigint(20) unsigned NOT NULL,
  `to_uid` bigint(20) unsigned NOT NULL,
  `create_time` datetime NOT NULL,
  `from_original_points` double(20,2) unsigned NOT NULL,
  `to_original_points` double(20,2) unsigned NOT NULL,
  `points` double(20,2) unsigned NOT NULL,
  `type` tinyint(3) unsigned NOT NULL,
  `rewareID` bigint(20) DEFAULT '0',
  `reponsetext` varchar(200) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3282799 DEFAULT CHARSET=utf8 COMMENT='';

/*Table structure for table `sales_details` */

DROP TABLE IF EXISTS `sales_details`;

CREATE TABLE `sales_details` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL,
  `to_original_points` double(20,2) unsigned NOT NULL,
  `points` double(20,2) unsigned NOT NULL,
  `to_uid` bigint(20) unsigned NOT NULL,
  `type` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `rewareID` bigint(20) DEFAULT '0',
  `reponsetext` varchar(200) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `create_time` (`create_time`,`to_uid`)
) ENGINE=InnoDB AUTO_INCREMENT=3005479 DEFAULT CHARSET=utf8 COMMENT='';

/*Table structure for table `share_details` */

DROP TABLE IF EXISTS `share_details`;

CREATE TABLE `share_details` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `new_coins` double(20,4) unsigned NOT NULL DEFAULT '0.0000',
  `old_coins` double(20,4) unsigned NOT NULL DEFAULT '0.0000',
  `new_balance` double(20,4) unsigned NOT NULL DEFAULT '0.0000',
  `old_balance` double(20,4) unsigned NOT NULL DEFAULT '0.0000',
  `ip` varchar(15) NOT NULL DEFAULT '',
  `coins` double(20,4) unsigned NOT NULL DEFAULT '0.0000',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `create_time` (`create_time`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

**Comment by ajcvickers** [comment]
@falps This seems to work find with the SQL Server provider, so it looks like it could be an issue with the MySQL provider. I would suggest filing an issue here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by sanishx** [comment]
I'm also having this isue

**Comment by alexzaytsev-newsroomly** [comment]
I have the same issue...
