### ISSUE TITLE
Materialization process issue writing a provider (EntityMaterializerSource)

### ISSUE THREAD

**Issue by bubibubi** [dotnet/efcore#9538]
During materialization process I can control how values are converted from DBMS types to CLR types implementing a custom EntityMaterializerSource.  
In the standard implementation this is done by EntityMaterializerSource.TryReadValue.  
Provider implementers can know the expected value and can convert the DBMS value to the expected value in the right way.  

If the value is generated during Runtime for example running a query like this 
``` C#
Context.TableWithSeveralFieldsTypes.Where(c => c.MyBool).Select(c => c.MyBool != false).First();
```
entity framework does a direct cast without using EntityMaterializerSource.TryReadValue.  
In particular it access directly to ValueBuffer and casts the retrieved value.  
If the DBMS does not support boolean (but similar behaviour is with TimeSpan) I think is not possible to make the materialization process work.

this is the call stack of the InvalidCastException  running the query above

```
Result StackTrace:	
in lambda_method(Closure , QueryContext , ValueBuffer )
   in Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   in Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   in Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   in Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   in Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   in System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   in lambda_method(Closure , QueryContext )
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   in Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   in System.Linq.Queryable.First[TSource](IQueryable`1 source)
   in EFCore.Jet.Integration.Test.DataTypesTest.Booleans() in C:\Develop\ForPlanning\EntityFrameworkCore.Jet\test\EFCore.Jet.Integration.Test\DataTypesTest.cs:riga 40
```

I know that is not important but with EF 6 the values were retrieved from DBMS using DbDataReader specific functions (for example GetBoolean) so there were not this issue.

**Comment by smitpatel** [comment]
@anpete since Oracle has same issue with bool.
@bubibubi - `EntityMaterializerSource.TryReadValue` may not be used always. Check `TypedRelationalValueBufferFactory`. (& Untyped version)

**Comment by anpete** [comment]
@bubibubi Which IRelationalValueBufferFactoryFactory does your provider use?

**Comment by bubibubi** [comment]
@anpete @smitpatel, I was using the default `IRelationalValueBufferFactoryFactory`. Looking at `UntypedRelationalValueBufferFactory.Create` it calls the _processValuesAction using the `DbDataReader` values.  

In my case and probably in Oracle case the `DbDataReader.GetValues` returns 0 for false and -1 for true (no way to cast them as bit or something similar as in SQL Server).  

So, the query
``` C#
Context.TableWithSeveralFieldsTypes.Where(c => c.MyBool).Select(c => c.MyBool != false).First();
```
returns 0 for `false` and -1 for `true`. Fixing the action for booleans has no effect because I'm checking for boolean type but the type returned from the database is integer.

I'm probably missing something but I can't understand what.

===
So now there is another question.  Looking at the source code of `UntypedRelationalValueBufferFactoryFactory.CreateValueProcessor` there is a check for the enums. I think that is never used at least for SQL Server (I don't know what happens to MySQL enums). Deleting the code for enum Handling from `UntypedRelationalValueBufferFactoryFactory.CreateValueProcessor` and running this stupid test (I can't actually compile EF tests, I will work on it next week)

``` C#
public class Entity
{
    public int Id { get; set; }

    public EnumDataType EnumDataType { get; set; }
}

public enum EnumDataType
{
    a,
    b,
    c
}
Context.Entities.AddRange(
    new Entity() {EnumDataType = EnumDataType.a}, 
    new Entity() {EnumDataType = EnumDataType.b}, 
    new Entity() {EnumDataType = EnumDataType.c});

Context.SaveChanges();

Context.Entities.Select(_ => _.EnumDataType).ToList();
Context.Entities.Single(_ => _.EnumDataType == EnumDataType.c);

```

It works fine (also debugging it, the `ValueBuffer` contains integers).
It's not a suprise because a direct cast of an int to enum is ok.

Also here, I'm probably missing something but I can't understand what.
Sorry about this.

**Comment by anpete** [comment]
If you switch to TypedRelationalValueBufferFactoryFactory, then EF will call the DbDataReader.GetX methods instead of GetValues. This can make it easier to do custom type conversions because you could wrap the underlying DbDataReader and perform the conversion in the specifica GetX method. E.g. GetBoolean.

**Comment by bubibubi** [comment]
@anpete I think I've understood what's happening just in case someone else will have same issue as mine.  
If something in the DbDatareader.GetX (for example GetBoolean or GetLong) goes wrong, the EF does not throw an exception but tries to call DbDatareader.GetValue and cast the returned value (or, in some other cases, check the type and throw an exception).
