### ISSUE TITLE
Query: null semantics should apply to GreaterThanOrEqual, LessThanOrEqual, not only strict equality

### ISSUE THREAD

**Issue by maumar** [dotnet/efcore#9544]
This currently manifests in our translation of string.Contains:

```
SELECT [c].[FirstName]
FROM [FunkyCustomers] AS [c]
WHERE CHARINDEX(NULL, [c].[FirstName]) <= 0
```

we should be applying null semantics here instead:

```
SELECT [c].[FirstName]
FROM [FunkyCustomers] AS [c]
WHERE CHARINDEX(NULL, [c].[FirstName]) <= 0 OR CHARINDEX(NULL, [c].[FirstName]) IS NULL
```

**Comment by ajcvickers** [comment]
@maumar and @divega should sync up on this.

**Comment by smitpatel** [comment]
@maumar - Do you want to look at this in 5.0?

**Comment by maumar** [comment]
not sure if I should do this, since 3-value logic for those operators is not as straightforward as I initially thought.

**Comment by maumar** [comment]
Maybe we can look at it as a strech/investigation

**Comment by smitpatel** [comment]
If it is complicated then we can defer. Just wanted to bring this up if we are already fixing this.
