### ISSUE TITLE
Can't install Microsoft.EntityFrameworkCore.Sqlite.Core in UWP app

### ISSUE THREAD

**Issue by wstaelens** [dotnet/efcore#9575]
VS2017 Pro (15.3.2)

`Installing Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0.
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063). Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm. Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm-aot. Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64. Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64-aot. Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86. Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x86-aot. Package Microsoft.EntityFrameworkCore.Sqlite.Core 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
Package restore failed. Rolling back package changes for '...'`

When will it be supported?

**Comment by ajcvickers** [comment]
Duplicate of #9401
