### ISSUE TITLE
EF Core 2.0 migration issue using Identity

### ISSUE THREAD

**Issue by gbjbaanb** [dotnet/efcore#9597]
I'm taking a ASP.NET Core 1.1 project and upgrading to Core 2.0. It went well enough with an existing DB, but when I deleted the DB and tried to re-create it using the "dotnet ef" tooling, things went pear shaped.

Firstly: running 'dotnet ef migrations add initial' popped up an error:

> No parameterless constructor was found on 'ApplicationContext'. Either add a parameterless 
> constructor to 'ApplicationContext' or add an implementation of 'IDesignTimeDbContextFactory' in the > same assembly as 'ApplicationContext'

Fair enough - so after a bit of searching, I added an implementation of IDTDBCF to my project and it got further, creating the migration class and snapshot, but with a error (in yellow) on the console:

> Error Number:208,State:1,Class:16
> An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the 
> application service provider. Error: Invalid object name 'AspNetUsers'.

Then running "dotnet ef database update" (for the sake of completeness) results in.... a working database.

So, the first issue is really one of updating the documentation for migration to say how to get a working migration, the parameterless constructor option given in the error message seems like it would be easier, but it then requires an OnConfiguring implementation with roughly the same code - and I'm not sure what to put in there as it didn't work for me. 

The yellow error message is worrying too, I wouldn't expect to see a huge stack trace and error message for something that works.

FYI the DB call that produces the ignored error is:

`fail: Microsoft.EntityFrameworkCore.Database.Command[200102]
      Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [AspNetUsers] AS [a])
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END
`

**Comment by smitpatel** [comment]
Are you calling `Migrate()` in your startup? Did you update your Program.cs file? Ref: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/

**Comment by Murf** [comment]
Why close?

**Comment by smitpatel** [comment]
@Murf - The issue has been closed because of no response from OP. We don't have enough information to investigate the cause of issue.

**Comment by gbjbaanb** [comment]
Sorry - been away from github and code for a bit.,

Yes, I followed the migration page religiously (as I knew I would have to before submitting this bug and feeling stupid when an obvious answer was pointed out, as always happens).

I have updated the Program.cs file.

But I don't know what you're referring to by calling Migrate() - this is not mentioned in that document, searching for that word results in no hits on the page, or on the linked page to migrate ASP.NET identity./

**Comment by smitpatel** [comment]
> Error Number:208,State:1,Class:16
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the
application service provider. Error: Invalid object name 'AspNetUsers'

@gbjbaanb - Share your `BuildWebHost` method and all relevant paths that code can take. You are querying database while before creating it. That is the reason it fails only for fresh db.

Are you having code in your startup to seed database? Especially a check like this `db.Users.Any()`

**Comment by gbjbaanb** [comment]
This is my BuildWebHost:

	public class Program
	{
		public static void Main(string[] args)
		{
			BuildWebHost(args).Run();
		}

		public static IWebHost BuildWebHost(string[] args) =>
			WebHost.CreateDefaultBuilder(args)
			.UseStartup<Startup>()
			.Build();
	}

Now that's an idea about reading the DB before creation (not that all I did was update to .netcore 2, the code to insert into the DB has not changed).

This is the new method I had to create to get the new migration to work, as explained in the original question:

	// workaround for new Core 2.0 migrations tooling
	public class ConfiguringDbContextFactory : IDesignTimeDbContextFactory<MyContext>
	{
		public MyContextCreateDbContext(string[] args)
		{
			var configuration = new ConfigurationBuilder()
				.SetBasePath(Directory.GetCurrentDirectory())
				.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
				.Build();

			var builder = new DbContextOptionsBuilder<MyContext>();

			var connectionString = configuration.GetConnectionString("MyContext");

			builder.UseSqlServer(connectionString);

			return new MyContext(builder.Options);
		}
	}

it calls no custom DB insertion code. My Startup class constructor doesn't call any DB code either.

I do have coded that queries the DB to decide whether to insert default data, it calls UserManager.FindByEmailAsync, there are no other calls to the DB. This call is in the Configure() routine on Startup, and I thought the whole point of the changes were to remove the dependency on this method.

I think I may have gotten the IDesignTimeDbContextFactory class wrong, but there is precious little documentation on what this should be. Is it that the ConfigurationBuilder is calling into my Startup.Configure() method?

**Comment by smitpatel** [comment]
> I do have coded that queries the DB to decide whether to insert default data, it calls UserManager.FindByEmailAsync, there are no other calls to the DB. This call is in the Configure() routine on Startup,

That is the cause of error. In 2.0 `Startup.Configure` method is to configure the application (e.g. add services, configure their behavior, configure http endpoints etc). `Configure` is not the place to put the logic which should be run when application is started.

https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#move-database-initialization-code contains detailed information about what changed between versions & what users need to do when upgrading around database initialization. If you follow the update guide then you can remove `ConfigureDbContextFactory`

**Comment by Srinivasvasantavada** [comment]
please help me out .i'm using asp.net 2.0 "An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider"

**Comment by smitpatel** [comment]
@Srinivasvasantavada - Please file a new issue, with the code of your `Program.cs`, `Startup.cs` classes & full stacktrace.

**Comment by andras-ferencz** [comment]
I know this is a closed issue, but I just want to come here to SCREAM AT WHATEVER INEPT HUMAN BEGIN DECIDED ANY OF THIS WAS A REASONABLE IDEA AND CURSE THEM TO THE DEPTHS OF GEHENNA WHERE THEY WILL BE FOREVER CURSED TO USE THEIR OWN AWFUL IMPLEMENTATIONS.

Thank you.
