### ISSUE TITLE
EF Core 2.0 duplicate fields generated for derived generic entities

### ISSUE THREAD

**Issue by shobman** [dotnet/efcore#9600]
EF Core 2.0 is generating invalid migrations for properties of generic entities which are also derived as part of an inheritance / TPH data model.

I have attached a working demo application with both EF Core 1 and EF Core 2 projects to illustrate the issue: [EF2.DerivedGenericsIssue.zip](https://github.com/aspnet/EntityFrameworkCore/files/1255011/EF2.DerivedGenericsIssue.zip)

## Expected behaviour

As per EF Core 1.0 the expected behaviour is that any properties defined on a generic entity which is also a derived entity should be created as a single field in the database.

## Actual behaviour

The properties of the derived / generic entity are generated as separate fields for each of type of T.  

## Steps to reproduce

As an example, entity Report has a derived generic entity of Report&lt;T&gt;.  The generic entity has a property 'Description'.  
```
public interface IReportEntity
{
    string Review { get; set; }
}

public class Report
{
}

public class Sector: IReportEntity
{
    public string Review { get;set; }
}

public class Product : IReportEntity
{
    public string Review { get;set; }
}

public class Portfolio: IReportEntity
{
    public string Review { get;set; }
}

public class Report<T> : Report
    where T : IReportEntity
{
    public string Description { get; set; }
}
```

### EF Core 2 Migration :thumbsdown:

When generating the migration using EF Core 2.0 the Description on the generic entity is being duplicated for each of the generic types.
```
 migrationBuilder.CreateTable(
    name: "Reports",
    columns: table => new
    {
        Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
        ProductReport_Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
        Id = table.Column<int>(type: "int", nullable: false)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
        Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
        Type = table.Column<string>(type: "nvarchar(max)", nullable: false),
        SectorReport_Description = table.Column<string>(type: "nvarchar(max)", nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Reports", x => x.Id);
    });
```
### EF Core 1 Migration :thumbsup:

When migrating the same model in EF 1.0 the migration is generated correctly:
```
migrationBuilder.CreateTable(
    name: "Reports",
    columns: table => new
    {
        Id = table.Column<int>(nullable: false)
            .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
        Name = table.Column<string>(nullable: true),
        Type = table.Column<string>(nullable: false),
        Description = table.Column<string>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Reports", x => x.Id);
    });
```

## Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by HenrikTP** [comment]
This is a general issue, happens for POCO entities as well.

**Comment by ajcvickers** [comment]
@shobman This is by-design. Consider the types below, which are from from the repro code--slightly different from those above. `Report<Sector>`, `Report<Product>`, and `Report<Portfolio>` are all different types. This means that the Description property is on a different type in each case. EF therefore maps it by default to different columns. Some things to note:
* If Description was on `Report` instead of on `Report<T>`, then it would be the same property in all three cases and it would be mapped to the same column.
* To force multiple properties to map the same column, use the `.HasColumnName` API to tell EF that each of the properties should be mapped to the same column. (Note that this requires that things like the type are the same for each property.)

```C#
interface IReport : IEntity
{
    string Description { get; set; }
}

public interface IReportEntity : IEntity
{
    string Review { get; set; }
}

public class Report : EntityBase
{
}

public class Report<T> : Report, IReport
    where T : IReportEntity
{
    public string Description { get; set; }
}

public class SectorReport : Report<Sector>
{
    // foreign key/s
    public int SectorId { get; set; }

    // navigation properties
    public Sector Sector { get; set; }
}

public class ProductReport : Report<Product>
{
    // foreign key/s
    public int ProductId { get; set; }

    // navigation properties
    public Product Product { get; set; }
}

public class PortfolioReport : Report<Portfolio>
{
    // foreign key/s
    public int PortfolioId { get; set; }

    // navigation properties
    public Portfolio Portfolio { get; set; }
}
```

**Comment by shobman** [comment]
Thanks for the info. I've used .HasColumnName and I'm all sorted. Cheers!

**Comment by ajcvickers** [comment]
Hi @shobman, @HenrikTP. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by shobman** [comment]
Hi @ajcvickers . Good question.

I guess in summary - after my experience with the 1.0 pre-releases, I didn't want the headache all over again. And this time I also have dependencies on packages that haven't yet updated.

I started using dotnet core and ef core after some of the earliest releases of 1.0 pre RC. During that time there was a lot of instability. Partly my fault no doubt but I just found it hard to keep up and being occasionally forced to deal with breaking changes and new bugs and work arounds with the new drops. At that time our product was in its infancy and I was still learning all things dotnet core and getting my way around the new cli etc.

Since our product went live after the 1.0 release and since the msbuild upgrade things have been super stable. And now my head is down building out new features for our app.

Also having now attempted to upgrade to 2.0 I've also stumbled across a couple of dependencies I'm using which also haven't yet updated to 2.0. So I'll continue to wait o those and chip in where I can to get them updated.

**Comment by ajcvickers** [comment]
@shobman Thanks for the feedback. The instability of pre-releases has definitely need a problem; it's something that the wider team is aware of and we are striving to be better in that respect--but I totally get where you are coming from--things have been pretty painful at times. Thanks again; appreciated!

**Comment by ErikEJ** [comment]
@ajcvickers Hi Arthur. I think one of the main blockers for adopting pre 2.0 releases was the absence of a released version of VS that supported .NET Standard 2.0 - that certainly caused me a lot of pain. Now that .NET Standard is there, hopefully it will just be a matter of pulling a preview package from NuGet, not updating your entire dev environment. Also more prominent announcements about the  availability of preview releases would probably increase adoption - yes, I know there is the blog, but maybe something to get notified by email subscription would be useful?

**Comment by srivch** [comment]
hi - In TPH when using navigation properties, as of EF 1.1 if "some" of the derived entities shared a common navigation property (foreign key), only one navigation property was created, but now in 2.0 for each derived class a separate navigation property is getting created. Is there a way to get 1.1 behaviour? 

```
public class Info {
}

public class Base {

}

public class DerivedA {
     public Info Info {get; set; }
}

public class DerivedB {

}

public class DerivedC{
     public Info Info {get; set; }
}
```

In the above example with EF Core 1.1, there would be only one Info navigation property (FK) created in Info class, but in EF Core 2.0, two are created, one for DerviedA and other for DerivedC. From what i have understood this seems to be by design, but is there a way to revert to 1.1 behaviour.

**Comment by ajcvickers** [comment]
@srivch You can use HasColumnName to map both properties to the same column. Something like this:
```
modelBuilder.Entity<DerivedA>().Property("InfoId").HasColumnName("InfoId");
modelBuilder.Entity<DerivedC>().Property("InfoId").HasColumnName("InfoId");
```

**Comment by ajcvickers** [comment]
@ErikEJ Thanks for the feedback; much appreciated. I think we all hope the VS situation will be better going forward!

**Comment by HenrikTP** [comment]
@ajcvickers We basic issue w changes before rtm. We implemented code from earliest pre 1.0 and kept up w the changes uptill 1.0 rtm but when the 2.0 prelease started we didnt wanna get caught up in further possible changes from pre 2.0 to rtm so we decided to wait for rtm.

**Comment by ajcvickers** [comment]
@HenrikTP Thanks for the feedback; much appreciated.

**Comment by pHr34kY** [comment]
I know it's a year late... but I've found that you can avoid calling HasColumnName() in your builder by using ColumnAttribute on the class properties:

```
public class SectorReport : Report<Sector>
{
    // foreign key/s
    [Column(nameof(SectorId))]
    public int SectorId { get; set; }

    // navigation properties
    public Sector Sector { get; set; }
}
```
