### ISSUE TITLE
Adding New IQueryable Type

### ISSUE THREAD

**Issue by hoagsie** [dotnet/efcore#9606]
I'm digging into EF Core trying to figure out how to add a new query type to support table hints. I have my own `SqlServerQuerySqlGeneratorFactory` with `VisitTable` overridden and ready to receive hints and an extension method similar to `IIncludableQueryable` that looks like so to bundle them with a given query:

    internal static readonly MethodInfo WithHintsMethodInfo =
        typeof(QueryableExtensions).GetTypeInfo().GetDeclaredMethods(nameof(WithHints))
            .Single(info => info.GetGenericArguments().Length == 1 && info.GetParameters()
                                .Any(parameterInfo => parameterInfo.Name == "hints" &&
                                                          parameterInfo.ParameterType != typeof(string)));

    public static IQueryable<TEntity> WithHints<TEntity>(this IQueryable<TEntity> query, TableHints hints)
    {
        return new HintedQueryable<TEntity>(
            query.Provider is EntityQueryProvider
                ? query.Provider.CreateQuery<TEntity>(
                    Expression.Call(
                        instance: null,
                        method: WithHintsMethodInfo.MakeGenericMethod(typeof(TEntity)),
                        arguments: new [] {query.Expression, Expression.Constant(hints)}))
                : query);
    }

HintedQueryable looks like so:

    public class HintedQueryable<TEntity> : IQueryable<TEntity>
    {
        private readonly IQueryable<TEntity> _queryable;
        
        public HintedQueryable(IQueryable<TEntity> queryable)
        {
            _queryable = queryable;
        }

        public IEnumerator<TEntity> GetEnumerator() => _queryable.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public Expression Expression => _queryable.Expression;
        public Type ElementType => _queryable.ElementType;
        public IQueryProvider Provider => _queryable.Provider;
    }

This results in a "could not parse expression" exception.

I've been digging through the internals and have gotten to the `SqlServerQueryModelVisitor` pieces trying to see what I need to add to support my `HintedQueryable` type. I feel like I'm close to an answer but any insight or a better solution would appreciated. I'm working with the 1.1.2 code.

**Comment by anpete** [comment]
Take a look at how AsNoTracking and Include are implemented. What you want to do is create a custom ResultOperator; take a look [here](https://github.com/aspnet/EntityFrameworkCore/tree/dev/src/EFCore/Query/ResultOperators/Internal)

**Comment by hoagsie** [comment]
Thanks for this. In my investigation, I also saw some registration going on with the Remotion libraries. Is that necessary for something like this as well or will EF auto detect ResultOperators et al? To recap, the process looks like so:

- Create IQueryable Type
- Create Method for Type
- Create ResultOperator
- Create ExpressionNode
- [Register Type and Node with Remotion] - correct?
- Create Custom SQL Generator and Replace EF Core's Generator
- Detect Output from ResultOperator
- Modify SQL as Necessary

Am I missing anything?

**Comment by anpete** [comment]
That flow looks roughly correct. However, you don't need a custom IQueryable type, just add the extension method. 

To register your new node, you need to call INodeTypeProviderFactory.RegisterMethods - An example of that, for our FromSql node, can be found in RelationalQueryCompilationContextFactory.

**Comment by hoagsie** [comment]
I have all this done including the removal of my custom IQueryable type. However, modeling this after Include is giving me a confusing result. If I copy Include's constructor and take a LambdaExpression as my second parameter, I get an exception about not being able to cast a TypedParameterExpression to a LambdaExpression. However, using Include works fine.

For your reference: IncludeExpressionNode

```
public IncludeExpressionNode(
            MethodCallExpressionParseInfo parseInfo,
            [NotNull] LambdaExpression navigationPropertyPathLambda)
            : base(parseInfo, null, null)
```

My TableHintExpressionNode

```
public TableHintExpressionNode(
            MethodCallExpressionParseInfo parseInfo,
            LambdaExpression hints)
            : base(parseInfo, null, null)
```
In examining the TypedParameterExpression, my custom TableHint container class is passed through fine. Unfortunately, I'm not seeing how to extract the runtime hints from the TypedParameterExpression for it to be useful. Can you explain what's going on?

**Comment by hoagsie** [comment]
I was able to massage the parameters both on passing and reception. I eventually settled on a generics based solution so the hints that get passed are directly tied to types therefore reducing the likelihood of "weirdness." However, this feels sort of like a hack as I was hoping to pass values directly rather than having to do type examination and some Activator.CreateInstance wizardry. I think in this case the "hack" is more or less OK. I would still like some input on my above question in case I need to extend EF in the future. Thanks regardless!

**Comment by anpete** [comment]
The expression node ctor parameter corresponds to the type of argument being passed to the custom operator method. So, for Include, the type is LambdaExpression because the Include method takes a lambda as the argument, I.e. customer => customer.Orders.

Now your operator takes a TableHints object, which if passed in line to the method call, will typically result in a ConstantExpression node in the expression tree. However, if you are seeing TypedParameterExpression, it is likely because of our parameterizer, which aggressively turns constants into parameters in order to reduce query cache fragmentation. The easiest thing to do is likely to just apply the NotParameterizedAttribute to the table hints parameter on the operator method - This will prevent parameterization of the argument.

BTW, what you are doing would be a useful feature for EF. Would you be open to sending a PR? If so, we could further refine things during the PR process.

**Comment by hoagsie** [comment]
I did not know that attribute existed. Worked like a charm. I'll work on a PR over the next few evenings.
