### ISSUE TITLE
Unable to create migrations with target framework 461

### ISSUE THREAD

**Issue by severisv** [dotnet/efcore#9612]
`dotnet ef migrations add new_migration`

```
Exception message:
Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

### Steps to reproduce
https://github.com/severisv/ef-core-bug-repro
`dotnet restore`
`dotnet ef migrations add new_migration`

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: cmd

**Comment by ErikEJ** [comment]
Have you tried using the vs pmc tools instead?

**Comment by vas6ili** [comment]
I have the same error message when trying to use EF Core 2.0.0 in an Azure Functions project targeting `net461`. 

```
mscorlib: Exception while executing function: RenewCertificates. Microsoft.EntityFrameworkCore.Relational: Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```
I tried adding the latest `System.ValueTuple` package reference to the project and it didn't fix the problem.

**Comment by ErikEJ** [comment]
Have you tried adding this to app.config:

`<assemblyBinding> <dependentAssembly> <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" /> <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" /> </dependentAssembly> </assemblyBinding>`

**Comment by vas6ili** [comment]
The solution in the blog post did fix the issue. The app.config binding redirects don't seem to work in a Function app project. 
Thank you

**Comment by severisv** [comment]
Can't get migrations through PMC to work (following [this](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell) guide): `Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet`.

The assembly redirect workaround isn't doing the trick either, though I'm not sure I'm doing it right. What I tried was creating a file named `app.config` in the project directory and paste the xml elements. Does it require a certain structure?

**Comment by JuanIrigoyen** [comment]
severisv in the article you have a example with the app.config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
       <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" />
       <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
    </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by severisv** [comment]
Now it works, thanks!

**Comment by ajcvickers** [comment]
@severisv Looks like in the repro above the EF tools are not installed. This is likely why the PMC commands were not working.

Closing since it seems things are working for people now. The need to do the binding redirect is something we will follow up on more.
