### ISSUE TITLE
Where is the EF Core 2.0 owned types / table splitting documentation? 

### ISSUE THREAD

**Issue by FransBouma** [dotnet/efcore#9620]
Hi,

For LLBLGen Pro v5.3 I'm updating our EF Core support to v2.0 and as our designer supports table splitting and value types / complex types (DDD), we can support table splitting and owned types for EF Core 2.0. However there appears to be no documentation (that I could find) about owned types mapping for code first. 

For table splitting there also appears to be no documentation, e.g. what the limitations are, and how to set it up. I can assume a few things, e.g. that the split off entity can be mapped the same way as the root entity but if there are limitations, e.g. fields have to be nullable in the DB, navigational properties are/aren't supported, that's unknown, as there's no documentation at all about this. 

For owned type mappings there's also no documentation: as they appear to have no PK, I can't use regular entity mappings (I think, but again: no idea) so how to set it up is unclear. I know there's 1 single example in the 'what's new' page in the documentation but that maps everything with conventions which is unusable for us as we need to cover all scenarios, e.g. a field is renamed and we need to explicitly specify the mapping. Also with this, there is no description about what the limitations are, e.g. whether the owned type can or can't be null, whether the fields have to be null or don't have to be... 

TIA

**Comment by ErikEJ** [comment]
There is this: https://docs.microsoft.com/en-us/ef/core/what-is-new/

**Comment by FransBouma** [comment]
@ErikEJ Yes I know that page, that's what I looked at before coming here, but that tells me absolutely nothing at all, other than that table splitting needs a relationship. The documentation doesn't contain any other remark about owned types nor table splitting at all: and I need the specifics: what are the limitations and for owned types: how to map them, etc. as I explained in the start post.

**Comment by cdie** [comment]
I agree. I've tried myself to use owned entities (I usualy use shadow properties to help my not break my domain model), but I've not reached my goal, because of missing examples/documentation.
It would be great if all in that page can have a specific documentation page

**Comment by ajcvickers** [comment]
@FransBouma I moved this to https://github.com/aspnet/EntityFramework.Docs/issues/466 on the EF-docs repo, which is a more appropriate place to track this. Maybe for now you should hold off on adding support in your product until we have time to complete detailed documentation?

**Comment by FransBouma** [comment]
We're still a month off or so of RTM, so there's still time, I think it's not a lot of work to add it (maybe a few hours, most work is in the validator to weed out errors the user made so they step on the limitations (if any) in the feature). I'll wait for the docs to land to proceed. :)

**Comment by SneezeWeeze** [comment]
Any update?
