### ISSUE TITLE
Can we have a `DeleteBehaviorAttribute`  

### ISSUE THREAD

**Issue by John0King** [dotnet/efcore#9621]
Data annotations is a much easier way to configure model than Fluent API.
And we can only configure `DeleteBehavior` via Fluent API today, that means we need configure foreign key again in fluent api.
Can we have a `DeleteBebaviorAttribute(DeleteBehavior behavior)`   in `Microsoft.EntityFramework` Namespace ?

**Comment by Vekz** [comment]
Hey, I've wanted to take on the challange of implementing this.
This would've been my first ever issue done in open source community so please be understanding.

As far as I understand I should have DeleteBehaviorAttribute class created in EFCore.Abstractions, and it's Convention created in EFCore/Metadata.

Could someone just explain to me how could I reference DeleteBehavior enum from inside of EFCore.Abstractions?

**Comment by ajcvickers** [comment]
@Vekz Sounds like a good plan. For the enum, move it to Abstractions and add type-forwarding to avoid a breaking change. For an example, search for `TypeForwardedTo` in the EF source.

**Comment by Vekz** [comment]
Okay, I've finished writing tests and figuring out how to put everything I've learned in past day so every case works.
And I managed to succeed.

Only this enum's left for me to implement. I'm gonna make PR probably later today. Thanks for really fast reply and pointing me to the solution.

**Comment by Vekz** [comment]
I didn't think I would get so much trouble from this TypeForwarding. 

I get CS0012 on tests that build models from snapshot after I've done TypeForwarding. 
Should I just add EFCore.Abstractions assembly reference to the test builder?

Sorry if it's stupid question this is actually first time I've ever touched TypeForwarding.

**Comment by Vekz** [comment]
@ajcvickers Could I ask you for a CR? 
I know you are probably busy with other tasks and I don't expect PR being merged as it's not the most urgent feature on the list for sure.
But I would love to hear your feedback does the code meet all requirements or could I've done something better.
