### ISSUE TITLE
[Question] - Running an async task prior to first dbcontext use.

### ISSUE THREAD

**Issue by dazinator** [dotnet/efcore#9624]
I would like to ensure that prior to first use, my `DbContext` has had Migrations run.
I'd like ensure the migrations run asynchronously so they don't tie up a thread - some migrations I expect will influence potentially large volumes of data so could take a while.

The common pattern I have seen is to do this on application startup:

```       
                using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>()
                    .CreateScope())
                {
                    serviceScope.ServiceProvider.GetService<TDbContext>().Database.Migrate();
                }
```

I could simply wrap that in a `Task.Run()` so I can proceed with other things on startup and allow it to run concurrently - however I'd also like to simplify usage of my library for consumers - for example If I distribute this library on NuGet - I want consuming it to be as simple as:

```
services.AddMySpecialComponent(someOptions);

```

So I created the following service that I can register into the `IServiceCollection` as a singleton:

```
 public class EnsureMigrations<TDbContext>
        where TDbContext: DbContext
    {
        private readonly IServiceScopeFactory _serviceScopeFactory;

        public EnsureMigrations(IServiceScopeFactory serviceScopeFactory)
        {
            _serviceScopeFactory = serviceScopeFactory;
            EnsureMigrated = new Lazy<Task>(() =>
            {
                return Task.Run(()=> {

                    using (var serviceScope = _serviceScopeFactory.CreateScope())
                    {
                        serviceScope.ServiceProvider.GetService<TDbContext>().Database.Migrate();
                    }                   
                });
            });
        }

        public Lazy<Task> EnsureMigrated { get; }

    }

```

The idea for this class, is that I will register it as a singleton, and it will expose a `Lazy<Task>` for the migrations work. The very first time this task is awaited, the migrations will run. On subsequent times, it should just return straight away as the task has already completed.

The next question became where to await this task - as I need this to happen prior to usage of the DbContext.
Given that people can new up an instance of a `DbContext` (synchronous) and then start querying against it, synchronously - there is never an appropriate point for async work to be awaited. The best I could initially do was this:

```
 public partial class AppTenantContext : DbContext
    {
        public AppTenantContext(EnsureMigrations<AppTenantContext> ensureMigrated)
        {
            // can't await here.. but can wait (blocking)
            ensureMigrated.EnsureMigrated.Value.Wait();
        }
 ...
}

```

For me this is a problem in EF core, in that it doesn't allow you to configure anywhere, some async work that will run prior to first use of the DbContext, non blocking. Simply because it doesn't force consumption of a DbContext through an async factory method.

So that led me to revert my DbContext constructor idea and create the following generic service:

```
    public interface IDbContextAccessor<TDbContext>
         where TDbContext : DbContext
    {
        Task<DbContext> GetDbContext();
       
    }

    public class DbContextAccessor<TDbContext> : IDbContextAccessor<TDbContext>
        where TDbContext : DbContext
    {
        private readonly EnsureMigrations<TDbContext> _migrator;
        private readonly TDbContext _dbContext;

        public DbContextAccessor(EnsureMigrations<TDbContext> ensureMigrated, TDbContext dbContext)
        {
            _migrator = ensureMigrated;
        }

        public async Task<DbContext> GetDbContext()
        {
            await _migrator.EnsureMigrated.Value;
            return _dbContext;          
        }
    }
```

So the idea, is that when you want to do any work with a DbContext, you are forced to obtain it via an async method so that if work is required, is can be done asynchronously - like this:

```
IDbContextAccessor<AppTenantContext> dbContextAccessor = SomeInjectedAccessor();
var dbContext = await dbContextAccessor.GetDbContext();

```

Unfortunately this now has the drawback that a consumer could still bypass the migrations by constructing the `DbContext` directly and bypassing the `IDbContextAccessor` - but I can't find a good solution to that problem..

So my question is, is there a better solution for this, or any fundamental problems inherent in this solution that you think are likely to cause me issues further on down the line? Should I be solving this differently?

Also I think this `IDbContextAccessor` idea has potential for something that could be implemented by you guys, to allow us to register any setup tasks (like `EnsureCreated`, `Migrate` - seeding data etc) and have them run the first time DbContext is accessed.

**Comment by ajcvickers** [comment]
@dazinator In general, running migrations as part of application startup is not something we recommend because:
* It requires permission to modify the schema by the running application, which may not be available and/or desirable
* It has concurrency issues that need to be handled carefully--you are touching on some of these above, and depending on other aspects of the configuration there can be more: for example, two application servers accessing the same database.

We would recommend that database migration happen as part of application deployment, rather than first run. The deployment may use scripts (e.g. generated from migrations) or may run tools directly against the production database. In either case, it is done in a controlled manner and in an environment with appropriate permissions.

**Comment by dazinator** [comment]
Thank you for your response. That makes sense, especially for things like webfarms where each site points to a shared database. I was thinking of consumers of my nuget package whom have an application that might: 

1. Have its own isolated database.
2. Not have any formal deployment process in place (I.e some cowboy/girl is manually deploying the app to a single node each release)
2. Be distributed / downloaded and installed via an msi

Having a mechanism to allow migrations to be automatically applied at application runtime (rather than through some CD process) still seems quite valuable for the above sorts of scenarios imho, would you agree? I imagine figuring out how to get wix to apply ef migrations during an installation might be quite painful in comparison. It seems fairly natural to me to want to ensure this work happens asychronously though. Anyway, thanks for the feedback.
