### ISSUE TITLE
Unable to build tag rel/2.0.0 on Linux

### ISSUE THREAD

**Issue by vellozzi** [dotnet/efcore#9633]
I've checked out the rel/2.0.0 tag and tried to run build.sh.
I'm expecting to run build.sh in the root of the repo on my Linux box and have a clean build.
Instead I'm seeing:

/home/ec2-user/git/EntityFrameworkCore/src/EFCore.Design/EFCore.Design.csproj : error NU1102: Unable to find package NETStandard.Library.NETFramework with version (>= 2.0.0) [/home/ec2-user/git/EntityFrameworkCore/.build/KoreBuild.proj]
/home/ec2-user/git/EntityFrameworkCore/src/EFCore.Design/EFCore.Design.csproj : error NU1102:   - Found 2 version(s) in nuget.org [ Nearest version: 2.0.0-preview2-25405-01 ] [/home/ec2-user/git/EntityFrameworkCore/.build/KoreBuild.proj]
/home/ec2-user/git/EntityFrameworkCore/src/EFCore.Design/EFCore.Design.csproj : error NU1102:   - Found 0 version(s) in AspNetCore [/home/ec2-user/git/EntityFrameworkCore/.build/KoreBuild.proj]
/home/ec2-user/git/EntityFrameworkCore/src/EFCore.Design/EFCore.Design.csproj : error NU1102:   - Found 0 version(s) in AspNetCoreTools [/home/ec2-user/git/EntityFrameworkCore/.build/KoreBuild.proj]
 
### Steps to reproduce

git clone https://github.com/aspnet/EntityFrameworkCore.git
cd EntityFrameworkCore
git checkout tags/rel/2.0.0 -b v2.0.0
./build.sh

**Comment by smitpatel** [comment]
@vellozzi - Thanks for bringing this to our notice. I have updated the tag to remove offending package.
Please fetch updated tags using following
```
git fetch origin --tags
```

Though I have tested building tag locally, if you still face issue building please re-open issue.

**Comment by vellozzi** [comment]
That did it.  Thanks.
