### ISSUE TITLE
EFCore 1.1.2 vs 2.0 compatibility - MissingMethodException: Method not found 'Int32 ExecuteSqlCommand(...

### ISSUE THREAD

**Issue by borisdj** [dotnet/efcore#9653]
I have an EFCore.BulkOperations Extension library.
It is targeting _NetStandard 1.4_ and has packages:
-_Microsoft.EntityFrameworkCore 1.1.2_
-Microsoft.EntityFrameworkCore.Relational 1.1.2.
I expected it would work on projects that are using EFCore 2.0 as well, however it seems it is not compatible.
The exception I am getting is:
```
System.MissingMethodException occurred HResult=0x80131513
Message=Method not found: 'Int32
  Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(
    Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade, System.String,System.Object[])'.
Source=<Cannot evaluate the exception source>
```
Cause of the problem is method `context.Database.ExecuteSqlCommand(...)` - from Relational package.
What is even more strange is that the exception is thrown form a line where another method is being called just because that method contains call to this `ExecuteSqlCommand`.
So I had little trouble finding the bug.
I have tried changing library target to _NetStandard 2.0_ and updated these 2 packages to 2.0 and it works, but with this change then older versions will not work.
One solution would be to have 2 nuggets but I would like to know if both versions could be supported from single library, and how?

### Further technical details
EF Core version: 1.1.2 / 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.3

**Comment by ajcvickers** [comment]
@borisdj EF Core 2.0 has breaking changes over 1.1.2. It will not be possible to target both versions with the same code. We don't intend for this to be a common thing, but going from 1.x to 2.x was one time we needed to make some breaks.

**Comment by borisdj** [comment]
OK, Thx for info.
