### ISSUE TITLE
UserId1 Field

### ISSUE THREAD

**Issue by dvdobrovolskiy** [dotnet/efcore#9665]
As mentioned at stackoverflow
https://stackoverflow.com/questions/45880998/userroles-table-has-additional-userid1-field-after-upgrade-to-net-core-2-0

after upgrade and adding new migration I got new field to UserRoles table called UserId1
This field also received foreign key and now want to be reference to to UserId in Users table

Here is full migration (no changes to model was made. simply new migration after upgrade)
***
protected override void Up(MigrationBuilder migrationBuilder)
        {
              migrationBuilder.DropIndex(
                name: "UserNameIndex",
                table: "Users");

            migrationBuilder.DropIndex(
                name: "RoleNameIndex",
                table: "Roles");

            migrationBuilder.AddColumn<int>(
                name: "UserId1",
                table: "UserRoles",
                type: "int",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "Users",
                column: "NormalizedUserName",
                unique: true,
                filter: "[NormalizedUserName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "Roles",
                column: "NormalizedName",
                unique: true,
                filter: "[NormalizedName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_UserRoles_UserId1",
                table: "UserRoles",
                column: "UserId1");

            migrationBuilder.AddForeignKey(
                name: "FK_AspNetUserTokens_Users_UserId",
                table: "AspNetUserTokens",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

             migrationBuilder.AddForeignKey(
                name: "FK_UserRoles_Users_UserId1",
                table: "UserRoles",
                column: "UserId1",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
***

This breaks all user-roles behaviour leaving existing users without their roles. 

I do have primary key type changed to int in users and roles  (User : IdentityUser<int>)
also tables renamed to Users and Roles

**Update**
It is probably mess in my ApplicationDbContext (when strange it worked good in 1.1)
***
builder.Entity<IdentityRoleClaim<int>>(entity =>
            {
                entity.ToTable("RoleClaims");
            });

            builder.Entity<Role>(entity =>
            {
                entity.HasKey(e => new { e.Id});
                entity.HasIndex(e => e.NormalizedName).HasName("RoleNameIndex");

                entity.Property(e => e.Name).HasMaxLength(256);

                entity.Property(e => e.NormalizedName).HasMaxLength(256);

                entity.HasMany(d => d.RolePermissions).WithOne(p => p.Role).HasForeignKey(d => d.RoleId);

                entity.ToTable("Roles");
            });

            builder.Entity<User>(entity =>
            {
                entity.HasKey(e => new { e.Id }).HasName("Id");

                entity.HasIndex(e => e.NormalizedEmail).HasName("EmailIndex");

                entity.HasIndex(e => e.NormalizedUserName).HasName("UserNameIndex");

                entity.Property(e => e.Email).HasMaxLength(256);

                entity.Property(e => e.NormalizedEmail).HasMaxLength(256);

                entity.Property(e => e.NormalizedUserName).HasMaxLength(256);

                entity.Property(e => e.UserName).HasMaxLength(256);

                entity.HasMany(d => d.UserPermissions).WithOne(p => p.User).HasForeignKey(d => d.UserId);
                //entity.HasMany(d => d.UserCompanies).WithOne(p => p.User).HasForeignKey(d => d.UserId);

                entity.HasMany(d => d.ResponsableZayavkas).WithOne(p => p.Responsable).HasForeignKey(d => d.ResponsableId);
                entity.HasMany(d => d.WorkerZayavkas).WithOne(p => p.Worker).HasForeignKey(d => d.WorkerId);

                entity.ToTable("Users");
            });

            builder.Entity<IdentityUserClaim<int>>(entity =>
            {
                entity.ToTable("UserClaims");
            });

            builder.Entity<IdentityUserLogin<int>>(entity =>
            {
                entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

                entity.Property(e => e.LoginProvider).HasMaxLength(450);

                entity.Property(e => e.ProviderKey).HasMaxLength(450);

                entity.ToTable("UserLogins");
            });

            builder.Entity<IdentityUserRole<int>>(entity =>
            {
                entity.HasKey(e => new { e.UserId, e.RoleId });
                entity.ToTable("UserRoles");
            });
***

**Comment by ajcvickers** [comment]
Looks like the same issues as are being discussed here: https://github.com/aspnet/Identity/issues/1364
