### ISSUE TITLE
No compiler error given when qualifer not specified

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#9671]
We have something like this code. Note the "o" qualifier is left off the column in theSingleOrDefaultAsync method.

`var o = await db.Order.Include(m => m.OrderMarketing).ThenInclude(om => om.Marketing).ThenInclude(m => m.MarketingOption).SingleOrDefaultAsync(o => OrderId == vm.OrderId);`

This always returns null until we place the "o." qualifier back on the column.
`var o = await db.Order.Include(m => m.OrderMarketing).ThenInclude(om => om.Marketing).ThenInclude(m => m.MarketingOption).SingleOrDefaultAsync(o => o.OrderId == vm.OrderId);`

I would think this might give us a compiler error/warning?

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 Pro latest patches
Visual Studio 2017 latest patches

**Comment by smitpatel** [comment]
@chassq - Do you have `OrderId` defined in the scope where the query is being used? It can be in scope, through local variable or method parameter or property/field defined on the containing class.

**Comment by chassq** [comment]
you are correct it was a property in our class. Thanks for the help!
