### ISSUE TITLE
Using EF Core in only UWP class library project

### ISSUE THREAD

**Issue by abnemo** [dotnet/efcore#9672]
Hello!

Tried to find it out, but without success. 

The question is: 

Is it possible to use EF Core in an UWP class library project without having an UWP app project as  startup project in the same solution? Runnig Add-Migration command fails with this error:
```
Startup project 'ClassLibrary1' is a class library. Select a Universal Windows Platform app as your startup project and try again.
```

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore.Tools 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.Sqlite 1.1.2
Operating system: Windows 10 Pro 1703
IDE: Visual Studio 2017 Community

**Comment by ajcvickers** [comment]
@abnemo Sorry for taking a long time to respond; this issue slipped through the cracks. Basically, you'll need to create a .NET Standard class library that also cross-targets .NETCoreApp.
