### ISSUE TITLE
default value doesn't work 

### ISSUE THREAD

**Issue by gsGabriel** [dotnet/efcore#9680]
Hello guys,
I have a little problem, I believe that is at least. Well, one of my tables has a default value, but the field with the default value is Boolean and is not null. When I pass a false value (which my business rule allows) Entity Framework changes to true always.

When I took this line of code, everything worked correctly again.

.HasDefaultValueSql("true");

Can anybody help me?

I use the EF CORE 1.1.2 with NPGSQL Driver

**Comment by ajcvickers** [comment]
Duplicate of #7089 and see also  #8400 and #7163.
