### ISSUE TITLE
DeleteBehavior.ClientSetNull documentation is wrong

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#9687]
https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete contains the sentence "[...] control whether the deletion of a principal/parent entity should have a side effect on dependent/child entities it is related to."

DeleteBehavior metadata contains the sentence "Indicates how a delete operation is applied to dependent entities in a relationship when the principal is deleted or the relationship is severed."

ClientSetNull sets the FK to null when the navigation property is set to null (i.e. the relationship is severed). It does nothing when the parent is deleted. When SaveChanges is called with a deleted parent, it sets the FK to null.

The docs, metadata and actual behavior are all mutually distinct in describing when exactly a DeleteBehavior does something.

This might apply to other DeleteBehaviors too, I just tested it with ClientSetNull.

**Comment by ajcvickers** [comment]
@Wain123 Agree the the documentation could be clearer. I think the bit that is missing is _when_ the FK is set to null:
* When changing a navigation property, the FK will be updated as soon as EF detects the change
* When deleting an entity, the FK is set to null when the change is cascaded in SaveChanges

**Comment by ajcvickers** [comment]
Read through after triage and docs don't cover delete orphans behavior.

**Comment by ajcvickers** [comment]
Filed https://github.com/aspnet/EntityFramework.Docs/issues/473
