### ISSUE TITLE
Setting a navigation property to null and then back to a value doesn't update the FK

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#9688]
The relationship is configured like this:
```C#
modelBuilder.Entity<Post>().HasOne(t => t.Blog).WithMany("PostBlogCollection").HasForeignKey("Blog_Seqnr").OnDelete(DeleteBehavior.ClientSetNull);
```
The following code:
```C#
var post = ctx.Posts.First();
var blog = ctx.Blogs.Where(z => z != post.Blog).First();
Console.WriteLine(post.Blog_Seqnr);
post.Blog = blog;
Console.WriteLine(post.Blog_Seqnr);
post.Blog = null;
Console.WriteLine(post.Blog_Seqnr);
post.Blog = blog;
Console.WriteLine(post.Blog_Seqnr);
```
Outputs "1 2 null null". I expected the output to be "1 2 null 2". (Nulls are invisible in WriteLine, I manually wrote "null" for clarity)

**Comment by ajcvickers** [comment]
@Wain123 Because EF hasn't detected changes. [This post](https://blog.oneunicorn.com/2012/03/10/secrets-of-detectchanges-part-1-what-does-detectchanges-do/) explains the principles--the specifics are about EF6, but the concepts are the same in EF Core.
