### ISSUE TITLE
EF Core 2.0 extremely slow on non-empty Postgre tables

### ISSUE THREAD

**Issue by lubomir-sokolovsky-sde** [dotnet/efcore#9689]
I am working on a course-participation system with ASP.NET Core MVC and EF Core. We are using a PostgreSQL database. We have a model like this:

Member -1:N< MonthlySubscription -1:N< Participation >N:1- Course

Each table contains only strings or numbers with no large data. Each table has 5-15 columns. Every month, we get participation data, transform them and store in a database. The case I have been investigating contained 30 Courses, 78 Monthly subscriptions and 283 Participation records. 

We are currently in the process of migration from .NET Core 1.1 to 2.0. So far, we have been using only synchronous version of SaveChanges method, because the performance of SaveChangesAsync in EF Core 1.1 was abysmal. While saving the record set mentioned above with SaveChanges took approximately 20 seconds, the whole process was finished after 79 minutes with SaveChangesAsync!

With the transition to 2.0, we wanted to re-investigate the possibility of using SaveChangesAsync. We were very pleased when the first test finished after 23 seconds. This was just like version 1.1 with synchronous SaveChanges. However, the subsequent tests were much worse - the process of saving data oscilated between 30 - 60 minutes. So we tried to go back to synchronous SaveChanges, but the results were very similar. The first test was always great, but the subsequent ones were extremely slow. We found out that inserting data is fast enough on empty tables, but becomes very slow with increased data in the tables. E.g.: For a changeset of 1 Monthly subscription record and 3 Participation records, it took 6 seconds to complete the SaveChanges method.

Here is a small summary table of the results:
- EF Core 1.1 synchronous, populated DB - ~20 s
- EF Core 2.0 synchronous, empty DB - ~20 s
- EF Core 2.0 synchronous, populated DB - ~2700 s

- EF Core 1.1 asynchronous, populated DB - ~4800 s
- EF Core 2.0 asynchronous, empty DB - ~20 s
- EF Core 2.0 asynchronous, populated DB - ~2700 s

I do not understand, what is causing this behaviour. The most interesting part is that even the first test on empty tables is not run as a single transaction - the records are saved sequentially, in groups. Thus the DB is slowly filling with records. Yet, for some reason, it takes only about 20 seconds, while the subsequent tests are considerably longer.

### Further technical details
EF Core version: 2.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 v 1703
IDE: Visual Studio 2017 v 15.3.3

**Comment by ajcvickers** [comment]
@lubomir-sokolovsky-sde Two questions:
* Have you tried with SQL Server? (i.e. is this possibly a Postgres issue?) //cc @roji 
* Could you post some code or attach a project that would allow us to reproduce what you are seeing and investigate further?

**Comment by lubomir-sokolovsky-sde** [comment]
@ajcvickers 
After further investigation we found out that the issue disappeared when we turned logging off. It seems, the logger interfered with other asynchronous database operations. Currently, we can report that the duration of executing SaveChangesAsync() is stable in the range of 20-30 seconds. 

We are still experiencing a rather unusual situation, when the HTTP response for monthly data persistence request never finishes - although the data are stored in the DB after said 20-30 seconds. However, I believe that is a totally different issue. Thus this issue can be closed. I apologize for the false alarm.

**Comment by ajcvickers** [comment]
@lubomir-sokolovsky-sde We're curious what logging APIs/frameworks you are using? Specifically, is there anything about the way logging is happening from EF Core or ASP.NET Core that is leading to these issues?

**Comment by lubomir-sokolovsky-sde** [comment]
@ajcvickers 
It was just a simple execution time logger, slightly inspired by MiniProfiler. We had two versions, one logging into the database, the other into a log file. Here is the latter one:

```
    public class ExecutionTimeLogger : IDisposable
    {
        private readonly string eventName;
        private readonly string logfilePath;
        private readonly Stopwatch watch;

        public ExecutionTimeLogger([CallerMemberName]string eventName = null, string logfilePath = null)
        {
            this.logfilePath = logfilePath ?? "C:\\exectimelog.txt";
            this.eventName = eventName;
            watch = Stopwatch.StartNew();
        }

        public void Dispose()
        {
            watch.Stop();
            File.AppendAllText(logfilePath, $"[{DateTime.UtcNow}] {eventName} - {watch.ElapsedMilliseconds} ms.\r\n");
        }
    }
```

The usage of the logger was to simply wrap piece of code into a using statement. You could wrap several methods that call each other, resulting in several loggers being active in the same call stack. I suspect that due to the fact that the logger is not asynchronous and several of them could be active at one time, all performing an I/O task, we experienced some deadlocks.

**Comment by ajcvickers** [comment]
@lubomir-sokolovsky-sde Thanks for the info.
