### ISSUE TITLE
DiagnosticSource - how to find out which Context executed a DbCommand?

### ISSUE THREAD

**Issue by Wain123** [dotnet/efcore#9691]
See #8934.

I subscribed a DiagnosticSource and can receive information about DbCommands, but I still don't see how I can determine which Context executed the command?

**Comment by ajcvickers** [comment]
@Wain123 Get the IRelationalConnection from the context and get the correlation ID from that. For example:
```C#
var id = context.GetService<IRelationalConnection>().ConnectionId;
```
