### ISSUE TITLE
EF tools cannot find migrations in project

### ISSUE THREAD

**Issue by Firgeis** [dotnet/efcore#9694]
Running "ef migrations add InitialCreate" created the Migrations folder as follows:
![efmigvscode](https://user-images.githubusercontent.com/6520188/30064340-ca417626-9227-11e7-86d5-d74648eada72.JPG)

However when running "dotnet ef migrations list" or trying to update the database, EF cannot find the Migrations.

Following is the fsproj:

![efprojectfile](https://user-images.githubusercontent.com/6520188/30064352-d298ea16-9227-11e7-823f-edb8891a26a6.JPG)

### Further technical details
Operating system:  Windows 10
IDE: Visual Studio Code 1.15.1

**Comment by bricelam** [comment]
Correct. The C# code won't be compiled into the F# assembly. See #6401.
