### ISSUE TITLE
How to make EF Core 1.1.0 migrations less verbose?

### ISSUE THREAD

**Issue by duszakpawel** [dotnet/efcore#9706]
I run migration scripts by executing the following command in Package Manager Console:

`dotnet ef database update`

without specifying the `verbose` flag. The output in console is full of sql scripts. I would like to have printed only names of migrations that are being applied. Is there any way I can achieve this?

Kind regards,
Pawel

### Steps to reproduce
Run `dotnet ef database update` in Package Manager Console.

### Further technical details
EF Core version: 1.1.0
Database Provider: MS SQL Server 2016
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by bricelam** [comment]
Are you using older preview versions of the packages? We dampened the SQL verbosity (in #6751) since the initial 1.0.1 release.

**Comment by bricelam** [comment]
You might be seeing the output of the application's console logger...

**Comment by duszakpawel** [comment]
Here is my project.json file. I have tried to update the Tools version to 1.1.0 but nothing changed.

{
  "version": "1.0.0",
  "description": "Context Class Library",
  "dependencies": {
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.Extensions.PlatformAbstractions": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final"
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "copyToOutput": [
      "appsettings.json"
    ]
  },
  "frameworks": {
    "net462": {
    }
  },
  "tools": {

    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final"
  }
}

**Comment by duszakpawel** [comment]
It's not the application's console logger btw.

**Comment by duszakpawel** [comment]
Have anybody experienced the same issue? I'm stuck and don't know how to fix it.

**Comment by bricelam** [comment]
I suspect it has to do with your usage of version 1.0.0-preview3-final of Microsoft.EntityFrameworkCore.Tools.

`project.json` is not supported. Everyone doing .NET Core development should [migrate to csproj](https://docs.microsoft.com/en-us/dotnet/core/migration/).
