### ISSUE TITLE
Designer error on descendant form when datacontext is declared on inherited base form

### ISSUE THREAD

**Issue by ctodd1** [dotnet/efcore#9707]
I develop in winforms. I receive an error on a descendant form's designer page when I declare my datacontext on its base ancestor form. Error states: Could not load file or assembly 'netstandard, Version=2.0.0.0,...'

To reproduce the issue:
Create a new project w/ EF Core 2.0 with two forms. One form needs to inherit from the other and on the base form, declare your datacontext. Build the project, then double-click on descendant form and you will receive the error. Remove the declaration and rebuild your project and the error goes away.

I'm attaching a project.

[TestEFCore2.zip](https://github.com/aspnet/EntityFrameworkCore/files/1281285/TestEFCore2.zip)

**Comment by ajcvickers** [comment]
@ctodd1 Thanks for reporting this. This issue is not related to EF Core, but instead comes from Visual Studio not understanding .NET Core types, which is being tracked here: https://github.com/dotnet/project-system/issues/2100

Closing this issue as external.
