### ISSUE TITLE
Add-Migration ends siliently if the project is located in a network path

### ISSUE THREAD

**Issue by Chrille79** [dotnet/efcore#9720]
If the project is in a network path \\\\ad\profile\myproject

Add-Migration command ends without an error or work

To workaround the issue. 

Copy the project to a local path "c:\myproject
then Add-Migration works like it should.

### Expected Result
Works on a network path or an output from Add-Migration that explain the issue

### Further technical details
EF Core version: 2.0.0
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: W10
IDE: (e.g. Visual Studio 2017)

**Comment by bricelam** [comment]
#7540 was supposed to fix this...

**Comment by bricelam** [comment]
I'm not able to repro this using the nightly build 2.1.0-preview2-30058.
