### ISSUE TITLE
Allow namespace in code generated by tools to be specified on the command line

### ISSUE THREAD

**Issue by chassq** [dotnet/efcore#9723]
When using scaffold to write to a relative directory in the project the namespace of the target folder does not seem to be honored. For example:

`dotnet ef dbcontext scaffold "Server=localhost\SQLEXPRESS;Database=<dbname>;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -c ApplicationDbContext --force --output-dir ..\lib.dal.sql\models`

Note that we are writing to a folder of another project. However the namespace of the files created is that of the project namespace not of the folder. The namespace is in this case lib.dal.sql but should be lib.dal.sql.models

### Steps to reproduce
Create a scaffold project but write the output to another directory in another project.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 latest patches
IDE: Visual Studio 2017 latest patches

**Comment by smitpatel** [comment]
Removing milestone as neither migrations nor scaffolding process any namespace when it is outside of your project directory. (not enough data to compute anything). We just use default namespace.

**Comment by ajcvickers** [comment]
After discussing in triage we are going to close this as by-design. The namespace resolution works correctly when generating to a location inside the project. When generating to locations that step out of the project (with "..\\") it becomes ambiguous and error prone, so we just generate using the root namespace.

**Comment by chassq** [comment]
Ok, then please add a namespace override to the cmd line args. I assume since scaffold does not support NetStandard (according to the docs I think) we cannot target a NetStandard lib yet.

**Comment by smitpatel** [comment]
Co-assigned Brice for design.

**Comment by ajcvickers** [comment]
Note from triage: we will consider allowing the namespace to be specified on the command line. @bricelam to make some proposals.

**Comment by bricelam** [comment]
Note, we should do this for both `Add-Migration` and `Scaffold-DbContext`.

**Comment by darkguy2008** [comment]
So, is this done? I'm having an issue where my app's directory is "api-users" and it tries to make the namespace as "namespace api-users.Models" which obviously doesn't work and crashes everywhere.

**Comment by ajcvickers** [comment]
@darkguy2008 
This issue is in the Backlog milestone. This means that it is not going to happen for the 3.0 release. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by bricelam** [comment]
@darkguy2008 See also dotnet/sdk#1564

**Comment by ErikEJ** [comment]
EF Core Power Tool offers full control of file locations and namespaces.

**Comment by Felza** [comment]
@ErikEJ Great tool! This fixed my issue, thanks!
Though I would like to add a comment to the "full control of namespace". Your tool offers the option to control sub-namespaces, but not the option for different root namespace.

**Comment by ErikEJ** [comment]
I think you have full control if you generate Entity Classes and DbContext separately

**Comment by atrauzzi** [comment]
Just duplicating my observation from the other issue: Having a Visual Studio specific tool doesn't cover my situation where I'm using .net Core from command line and in linux.  Also, relying on Visual Studio addin for functionality does frustrate automation scenarios.

Even if at the very least, forcing people to now include **all of VS** in their builds.  Which isn't possible if they're building on linux.

**Comment by darkguy2008** [comment]
Okay so we already have .NET Core 3.x, as @ajcvickers said it was on the backlog, so it would be safe to assume it's been done, right? Otherwise this issue wouldn't be open still...

Agreed with @atrauzzi , the problem with all these opensource software is that bugs or features stay open for years and years without any progress unless it directly affects an official developer...

**Comment by ajcvickers** [comment]
@darkguy2008 What specifically makes you think this has been done? (It's open and in the 5.0 milestone.)

**Comment by darkguy2008** [comment]
@ajcvickers "We will re-assess the backlog following the 3.0 release and consider this item at that time.".

Unfortunately the priorities, again as I said, are not on the end user's needs.

**Comment by atrauzzi** [comment]
@ajcvickers - I've pushed a lot of GitHub suggestions in the past for things that don't present as "popular"through GitHub tickets.

The people here aren't going to be fully representative of demand. I think the better argument here is consistency and aligning with the overall direction of Microsoft tools. The lack of a cross platform, command line equivalent here is a clear win.

If I wear my PM hat, simmering tells me that once built, this will be used and very widely appreciated.

**Comment by ajcvickers** [comment]
@atrauzzi This is why we have a [planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) that considers many factors, not just the number of votes. That being said, there are currently **114** [issues with more votes](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) than this one. So while cross-platform tooling is strategically important to Microsoft, this particular issue is still pretty far down the priority list, especially for a small team.

**Comment by atrauzzi** [comment]
Who do I have to tweet at for you guys to get more resources? 😉

You're like...the 2nd most important .net Core project in the ecosystem IMO!?

**Comment by ErikEJ** [comment]
@atrauzzi I am planning a .NET Core command line tool that does what the VS extension does (in terms of generating scaffolding code)

**Comment by ErikEJ** [comment]
You can vote here: https://github.com/ErikEJ/EFCorePowerTools/issues/340

**Comment by bricelam** [comment]
Related: #3988

**Comment by darkguy2008** [comment]
This is awesome, thanks a lot for your hard work!!! :D

**Comment by lajones** [comment]
@darkguy2008 You're very welcome :-)
