### ISSUE TITLE
[Question]: General impersonation strategy in read scenarios in EF Core

### ISSUE THREAD

**Issue by MarcusKohnert** [dotnet/efcore#9732]
**Context:**
Custom Enterprise Intranet Webapplication, everything running in the same domain
IE 11
ASP.NET Core 1.1
.NET Framework 4.6.2
EF Core SQL Server 1.1.2

ConnectionString: "Server=???;Initial Catalog=???;Integrated Security=True;MultipleActiveResultSets=True"

**Customer Requirements:**
Database connection must be established with the browser's user identity.

**What is working:**
Impersonation generally works in synchronous writing scenarios because I'm able to wrap SaveChanges with a call to Impersonate() like this:

```
// some class inheriting DbContext getting an identityProvider injected via ctor

public override int SaveChanges()
{
     using (((WindowsIdentity)this.identityProvider.Identity).Impersonate())
     {
         return base.SaveChanges();
     }
}
```

**The question:**
How can I implement a central impersonation stategy in reading scenarios? From my understanding the database is hit on dbContext.SomeEntity.ToList(). Is there some mechanism to wrap database connection attempts with calls to Impersonate()?

Also, when I've found a central solution do I have to give up on async reads as explained [here](https://github.com/aspnet/IISIntegration/issues/398#issuecomment-314148971)?

Thanks in advance!

**Comment by ajcvickers** [comment]
@MarcusKohnert As long as you are not using async code, then you should be able to impersonate once for the thread and keep it, or as needed around database access (like you show) for reads and writes. You might able to do something more automated by hooking into events on the DbConnection, but I don't know enough about Windows impersonation to know exactly how that would work. With regard to EF, we're not planning on doing anything specific here, and the async limitation is not something that EF can do anything about--I can't provide anything more here than was already provided in the post you liked and the issue linked from that post.
