### ISSUE TITLE
Cannot run all tests from command line with latest dev

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9746]
All tests do not complete, but crash mid run
```
[xUnit.net 00:01:07.9406404]   Finished:    Microsoft.EntityFrameworkCore.InMemory.FunctionalTests

Total tests: 4034. Passed: 3988. Failed: 1. Skipped: 45.
Test Run Failed.
Test execution time: 1,1437 Minutes

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:07:48.87
dotnet.exe failed with exit code: 1
At C:\Users\ErikEjlskovJensen\.dotnet\buildtools\korebuild\2.1.0-preview1-15493\scripts\common.psm1:11 char:9
+         throw "$cmdName failed with exit code: $exitCode"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF Core version: latest dev
Database Provider: N/A
Operating system: 
IDE: (VS 2017 15.3)

**Comment by smitpatel** [comment]
@ErikEJ - Which test is failing? All our CIs are passing on latest dev correctly.

**Comment by smitpatel** [comment]
Is it `ConcurrencyDetectorInMemoryTest.Find_logs_concurrent_access_nonasync` that test is failing in rel/2.0.1 branch for some reason.

**Comment by ErikEJ** [comment]
The test run breaks due to the error above

**Comment by ajcvickers** [comment]
@ErikEJ In the output above it says that one test is failing. Which test is failing, or is the output not reporting any failures but then it still says, "Failed: 1"?

**Comment by ErikEJ** [comment]
@ajcvickers  OK, so execution stops after the first test failure?

**Comment by smitpatel** [comment]
@ErikEJ - ErrorActionPreference is set as stop after first failure. This is done to avoid building/testing after an error is found during CI build since it would require rebuild after fixing error anyway. That way, it frees up resources after first failure.

**Comment by ErikEJ** [comment]
@smitpatel Makes sense. Maybe it would be useful to run the CI on a non-US system once in a while to avoid the many localization issues that keep reappearing?
