### ISSUE TITLE
Wordpess/bootstrap/sass code to enqueue

### ISSUE THREAD

**Issue by Br324** [dotnet/efcore#9760]
Hi all, Trying to include Bootstrap and sass in worpress not sure what version of Bootstrap to use as I want to include sass ,I also what to put in enqueue code but cant get it to work with variations of code below. I also have been using scout/compass.
Also do I need to use ruby on rails for Bootstrap 4 and will I have to move from scout to Gulp and npm to use sass. Thanks in advance for any help.

`<?php
function my_theme_enqueue_styles() {

    $parent_style = 'parent-style'; // 2017 style

    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
  
     wp_enqueue_style(
      'bootstrap',
    get_stylesheet_directory_uri() . '/bootstrap/css/bootstrap.min.css');

    wp_enqueue_script(
      'bootstrap',
    get_stylesheet_directory_uri() . '/bootstrap/js/bootstrap.min.js');
     
}
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
?>`

**Comment by ajcvickers** [comment]
Closing as this doesn't seem to have any relation to Entity Framework. Please find a more appropriate place for these questions.
