### ISSUE TITLE
Package Manager Console command -> (dotnet ef database drop)

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#9770]
Copied from: https://developercommunity.visualstudio.com/content/problem/51993/package-manager-console-command-dotnet-ef-database.html

I run command  -> "dotnet ef database drop" , responce was -> 

Are you sure you want to drop the database 'test' on server '(localdb)\mssqllocaldb'? (y/N)

but then i coud't write anything on console . i solved it by running new command window  (on command window everything is fine ) , but on package manager console , i can't write anything after run "dotnet ef database drop" command

**Comment by ajcvickers** [comment]
This is a limitation with the way PowerShell works. While we could look at workarounds, we don't feel there is enough value at this time because:
* It is recommended that the PMC tools be used in the PMC
* There is a --force option that can be used to skip the prompt
* There is a --dry-run option that can be used to see what would be deleted without doing it

**Comment by markusschaber** [comment]
We had cases where the PMC commands errored out, while "dotnet ef" worked for us. I'll see whether I can come up with STR...

**Comment by ajcvickers** [comment]
@markusschaber Can you file an issue for the errors you are seeing when using the PMC?

**Comment by markusschaber** [comment]
@ajcvickers I will, given that we can still reproduce them with the current version.
