### ISSUE TITLE
Tests using InMemory DB broke when upgrading to 2.0 when using Include or Collection

### ISSUE THREAD

**Issue by OskarKlintrot** [dotnet/efcore#9774]
I just upgraded to dotnet 2.0 and EF 2.0. Everything works fine feature wise in the web application where I'm using a MS SQL server and it works just fine when I change to the InMemory db. However, when I run the unit tests I'm using the InMemory db and all tests that is using `Include` or `Collection` or similar **where there is a related entity** fails. My `DbContext` returns nothing then. However, **if there is no related entities everything works fine**. I tried to create a minimal console app example but I can't replicate the issue outside my current web project.

### Steps to reproduce
Full working (or well, not working...) example here with broken tests: https://github.com/OskarKlintrot/ef2.0-inmemory-breaking-changes/tree/master/BROKEN

This is how I seed and create my `DbContext` in the tests:

```c#
public static class DbContextFake
{
    /// <summary>
    /// Creates a new DbContext that is using an In Memory-database
    /// </summary>
    /// <typeparam name="TContext"></typeparam>
    /// <param name="databaseName">If not set this will be the name of the calling method</param>
    /// <returns></returns>
    public static TContext GetDbContext<TContext>([CallerMemberName] string databaseName = "")
        where TContext : DbContext
    {
        var options = new DbContextOptionsBuilder<TContext>()
                .UseInMemoryDatabase(databaseName)
                .Options;

        return (TContext)Activator.CreateInstance(typeof(TContext), options);
    }

    /// <summary>
    /// Seeds the database
    /// </summary>
    /// <typeparam name="TContext"></typeparam>
    /// <param name="action"></param>
    /// <param name="ensureDeleted">If true the database will be deleted if it exists</param>
    /// <param name="databaseName">If not set this will be the name of the calling method</param>
    public static void SeedDb<TContext>(Action<TContext> action, bool ensureDeleted = true, [CallerMemberName] string databaseName = "")
        where TContext : DbContext
    {
        using (var context = GetDbContext<TContext>(databaseName))
        {
            if (ensureDeleted) context.Database.EnsureDeleted();
            action(context);
            context.SaveChanges();
        }
    }
}
```

However that code is working [in my failed attempted to replicate the issue](https://github.com/OskarKlintrot/ef2.0-inmemory-breaking-changes/blob/master/InMemoryIssue/InMemoryIssue.UnitTests/Fakes/DbContextFake.cs).

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: W10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@OskarKlintrot We haven't investigated this fully yet, but could you be hitting #9470? In summary, if there are entities with non-null FK values, then the in-memory database must contain a matching PK value for queries with Include to always work correctly. Put another way, the data in the in-memory database can no longer violate FK constraints and still be returned correctly from queries.

**Comment by OskarKlintrot** [comment]
I'm not at my computer atm but could it be that issue still since it is
actually working when running the application? If I remember correctly the
entity had a PK when I put a breakpoint at the context. But I guess I could
still seed the db wrong somehow. I think I'm populating the db differently
in the web app and the tests. If so it would make sense.

Den 12 sep. 2017 19:05 skrev "Arthur Vickers" <notifications@github.com>:

**Comment by OskarKlintrot** [comment]
The issue was how I populated the DB in the tests. I had a `UserId` but not a matching `User`. Closing this as it was a PEBCAK issue :) Thanks for the help @ajcvickers!
