### ISSUE TITLE
ConfigureDesignTimeServices  entry point

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/efcore#9786]
[From this issue:](https://github.com/aspnet/EntityFrameworkCore/issues/5617)

_We'll add an IDesignTimeServices interface. If there is an implementation of this interface in your startup assembly, we'll find it at design-time and use it to configure the design-time services._

Is this still the current design?  If so, why does the implementation have to be in the startup assembly?  Why can it not be in an assembly whos name is passed as an argument?
I have never created my model or dbcontext in an executable assembly project.  Its non-intuitive to have create a dummy assembly for this purpose.

**Comment by ajcvickers** [comment]
@sam-wheat The reason it is in the startup assembly is that it is not about EF specifically, but about getting access to the IoC container that is defining the services for your application. This typically happens at application startup since it is needed to start the application.
