### ISSUE TITLE
Projecting results of query with a property using string interpolation is significantly slower

### ISSUE THREAD

**Issue by codymullins** [dotnet/efcore#9788]
Projecting the results of a query into a flattened model where a property on the entity uses string interpolation significantly changes the speed of the query - from an average of 36 seconds to 76 seconds to page 60,000 records in batches of 1000. 

Looking at the generated SQL, it doesn't seem to be doing anything strange - just pulling the two properties used. No exception is thrown. I'm having difficulty finding documentation around this so far, so if this kind of performance change is expected I think it would be nice to have it also documented. I did expect some performance change but didn't think the query would run twice as long.

**Expected:**
Using string interpolation in properties should not significantly affect performance when projecting into a flattened model.

**Actual:**
Using string interpolation doubles the time it takes for the query to run (from 36 seconds -> 76 seconds)

### Steps to reproduce

1. Query a DbSet using `.Where(..)`, the query does not seem to matter
2. Page the results (my test is doing 60k results, doing batches of 1000 in a loop - this is a console app hitting the API endpoint)
3. Select the result into a flattened DTO, one test using a computed property (i.e `$"{FirstName} {LastName}"`) and one using just one of the properties like the first name

Below is sample code to illustrate my point, this mimics the structure and query that I'm using to produce this issue. I am a bit tight for time but can try to come back later with a solution uploaded somewhere if needed.
```c#
public class MyService
{
    private readonly MyContext _context;

    public MyService(MyContext context)
    {
        _context = context;
    }

    // average 76 seconds paging through 60k records
    public async Task GetWithComputedPropertyAsync()
    {
        // the query doesn't seem to matter significatly, so just filtering by anything
        // and then paging before projecting the results onto a flattened model
        await _context.Foos.Where(p => p.Something == "something")
            .Skip(0)
            .Take(1000)
            .Select(p => new FlattenedFooModel
            {
                Something = p.Something,
                CreatedById = p.CreatedById,
                CreatedDate = p.CreatedDate,
                FooId = p.FooId,
                BarName = p.Bar.FullName, // full name here is computed using string interpolation
                FubarProperty = p.Bar.Fubar.FubarProperty
            })
            .ToListAsync();
    }

    // average 36 seconds paging through 60k records
    public async Task GetWithoutComputedPropertyAsync()
    {
        // the query doesn't seem to matter significatly, so just filtering by anything
        // and then paging before projecting the results onto a flattened model
        await _context.Foos.Where(p => p.Something == "something")
            .Skip(0)
            .Take(1000)
            .Select(p => new FlattenedFooModel
            {
                Something = p.Something,
                CreatedById = p.CreatedById,
                CreatedDate = p.CreatedDate,
                FooId = p.FooId,
                BarName = p.Bar.FirstName, // not using the computed property for this query
                FubarProperty = p.Bar.Fubar.FubarProperty
            })
            .ToListAsync();
    }
}

public class FlattenedFooModel
{
    public int FooId { get; set; }
    public string Something { get; set; }
    public string BarName { get; set; }
    public string FubarProperty { get; set; }
    public DateTime CreatedDate { get; set; }
    public int CreatedById { get; set; }
}

public class Foo
{
    public int FooId { get; set; }
    public string Something { get; set; }
    public DateTime CreatedDate { get; set; }
    public int CreatedById { get; set; }
    public Bar Bar { get; set; }
}

public class Bar
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string FullName => $"{FirstName} {LastName}"; // computed

    public Fubar Fubar { get; set; }
}

public class Fubar
{
    public int FubarId { get; set; }
    public string FubarProperty { get; set; }
    public DateTime FubarTimestamp { get; set; }
}

public class MyContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 64 bit Windows 10, version 1607, OS Build 14393.693
IDE: (e.g. Visual Studio 2017)
Processor: Intel Core i7-7600U @ 2.8FHZ
Memory: 32 GB

**Comment by smitpatel** [comment]
The main difference between both queries is, `Bar.FirstName` is mapped in EF model whereas `Bar.FullName` is not. That happens because `Bar.FullName` does not have a setter.

This difference of mapped property causes different execution plans for both the queries.
For `Bar.FirstName` (without computed property), EF Core knows which column to read value from in database, so it will just fetch the value of that column from the table.
For `Bar.FullName` since it is not mapped, EF Core does not know how to get its value from db. The only value to get its value is to construct Bar object and access the property. That requires additional work of fetching all columns of Bar table and constructing object for each one of them to get the value. Due to this additional work, the query will be slower compared to a mapped property.

If you want to map the property to computed column in database. In which case both queries will have similar time.

**Comment by codymullins** [comment]
I will try your suggestion. I did notice, however, the SQL generated was pulling the correct columns and not every column as you mentioned. Will report back my results.
