### ISSUE TITLE
DataContext.SaveChanges() trap and throw error to caller issue

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/efcore#9789]
Hi,
I am using a Generic Repository + Service in my ASP.NET Core MVC app.
I can't figure how to solve the DbUpdateException flow to go back to the controller.
I always though adding a try-catch in a caller's method would catch the error from callee.

My goal is to catch the error in the controller.
the exception happens before  the try-catch in the repository
What am I missing ?
Anyone having a working sample ?
Thanks
-v
###

> Controller -> Service -> Repository

 
In my Repository
```
public void Save()
    {
      DataContext.SaveChanges();
    }
```
in my Generic Service:
```
 public void Save()
    {
      Repo.Save();
    }
```
in same service: CRUD method Create
```
public virtual Guid Create(TEntity item)
    {
      //Create 
      var newItem = Repo.Insert(item);
      Save();
      return newItem.Id;
    }
```
from generic controller:
```
     [HttpPost]
    public virtual ActionResult Create(TCreateInput input, bool? usingAjaxList)
    {
      if (!ModelState.IsValid)
        return PartialView(input);

      var newItem = Mapper.Map<TCreateInput, TEntity>(input);
      try
      {
        var id = Service.Create(newItem);
      }
      catch (CommonException ex)
      {
        GrrDevLogHelper.Error<Crudere<TEntity, TCreateInput, TEditInput>>(ex);
        //TODO:Manage Validation Error GUI
        return PartialView(input);
      }

      newItem = Mapper.Map<TEntity, TEntity>(newItem);

      var entity = Service.Get(newItem.Id).MapTo<TEntity>();

      if (usingAjaxList.HasValue)
        return Json(new {Content = this.RenderView(RowViewName, new[] {entity})});

      return Json(MapEntityToGridModel(entity));
    }
```

### Further technical details
EF Core version: 2.0.0
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system:  Windows10 x64
IDE: (e.g. Visual Studio 2017 - latest preview)

**Comment by ajcvickers** [comment]
@vRITHNER What is CommonException? Is this where you expect DbUpdateException to be caught? DbUpdateException doesn't inherit from CommonException, so it won't be caught here.

**Comment by vRITHNER** [comment]
@ajcvickers thanks for the tip.  
A question remains: CommonException inherits from Exception;
even if I forgot to add the DbUpdateException catch, all errors should fall back a the end of the chain in the latest Exception catch or am I wrong ?

**Comment by ajcvickers** [comment]
@vRITHNER I'm having difficulty following what you mean. Could you post a complete code listing or project that demonstrates the issue you are having?

**Comment by vRITHNER** [comment]
Sorry, I was not clear... and distracted.

I forgot to add Exception below my CommonException to catch all.
I quickly repro it in Linqpad :

```
void Main()
{
	try
	{
		var fakec = new FakeController();
		fakec.GetResultWithNoError().Dump();
		
		//fakec.GetResultWithError(null).Dump();
		//fakec.GetResultWithError("bad").Dump();
		
		fakec.GetResultWithError("common").Dump();
	}
//	catch (ArgumentOutOfRangeException ex)
//	{
//		ex.Message.Dump("out");
//	}
//	catch (ArgumentNullException ex)
//	{
//		ex.Message.Dump("null");
//	}
//	catch (CommonException ex)
//	{
//		ex.Message.Dump("common");
//	}

	catch (Exception ex)
	{
		ex.Message.Dump("standard");
		ex.GetType().Name.Dump("Ex type");
	}
}

public class FakeController
{

	public object GetResultWithNoError()
	{
		return $"Hello from  [{nameof(GetResultWithNoError)}]";
	}

	public object GetResultWithError(object arg)
	{
		if (arg == null)
			throw new ArgumentNullException($"error [{arg}] from GetResultWithError");

		if (arg is string && arg == "bad")
			throw new ArgumentOutOfRangeException($"error [{arg}] from GetResultWithError");

		if (arg is string && arg == "common")
			throw new CommonException($"error [{arg}] from GetResultWithError");
			
		return $"Hello from  [{nameof(GetResultWithError)}] with this [{arg}]";
	}

}
```


Thanks @ajcvickers  :-)
-Vince
