### ISSUE TITLE
Migrations fail after upgrading from 1.1.1 to 2.0 - Migration is not recreating indexes when altering foreign key column

### ISSUE THREAD

**Issue by clement911** [dotnet/efcore#9794]
Similar to https://github.com/aspnet/EntityFrameworkCore/issues/4642 which supposedly was fixed.

We have a large project for which we keep the entire history of all migrations.

Any developer can checkout the project and run all the migrations on their local db server to create their own db.
This worked great until we tried to upgrade from 1.1.1 to 2.0

We use asp.net on top of .net framework 4.6.1 with sql server 2016.

We have upgraded our csproj file as follows: 
`<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />`

In 1.1.1, the migration used to automatically drop the index before altering column, and recreate it after.
It doesn't seem to be the case anymore. Because of that, the alter statement fails.

Here is such a migration:

```
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Field_FieldGroup_FieldGroupId",
                schema: "view",
                table: "Field");

            migrationBuilder.AlterColumn<long>(
                name: "FieldGroupId",
                schema: "view",
                table: "Field",
                nullable: false,
                oldClrType: typeof(long),
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Field_FieldGroup_FieldGroupId",
                schema: "view",
                table: "Field",
                column: "FieldGroupId",
                principalSchema: "view",
                principalTable: "FieldGroup",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
```

The foreign key is being changed to non null (narrowed) for which sql server requires to recreate indices.

As you can see there is no explicit drop/create index, even though one index did created when the original foreign key (which was null) is created. In 1.1.1, it used to happen automatically but not anymore.

Can you advise on what to do here? Is there a fix coming?

We do not want to recreate a huge single initial migration because we are not sure whether some migrations we manually modified, and the loss of flexibility to deploy on various databases that may not have all migrations ran yet.

**Comment by clement911** [comment]
Please in the future document all breaking changes in the migration documentation.
https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/

**Comment by bricelam** [comment]
@clement911 Could you share your project so we can further investigate this?

**Comment by clement911** [comment]
I tried to do a small repro project but for some reason it worked fine. I will investigate further.

**Comment by bricelam** [comment]
Closing for now, but feel free to re-open if your investigation uncovers anything.
