### ISSUE TITLE
In memory provider defaults to lazy includes while other provides require explicit includes statement in the query.

### ISSUE THREAD

**Issue by paulvanbladel** [dotnet/efcore#9797]
Take the canonical example of an ORDER with a related customer.
With the sql provider, when retrieving an ORDER the customer details will NOT be included unless an explicit INCLUDE is given in the query.
With the in memory provider the CUSTOMER is lazy loaded automatically !
I'm using the in memory provider for **unit testing.** Obviously, such a major difference in functionality makes it useless for unit testing.

**Comment by ajcvickers** [comment]
@paulvanbladel This is not the designed behavior of the in-memory provider. Can you post a complete code listing or project that reproduces what you are seeing?

**Comment by paulvanbladel** [comment]
@ajcvickers . 
Trying to reproduce in separate sample, but I don't get the same behavior.
Strange... Sorry, will close the issue and report back when I get similar behavior.
