### ISSUE TITLE
Migration contains bad (old) annotation for identity column

### ISSUE THREAD

**Issue by pila13** [dotnet/efcore#9799]
The initial migration generated by Package Manager -> add-migration
contains 1.x version annotation for identity column configured in Fluent Api as below:

```builder.HasKey(c => c.Id);
    builder.Property(c => c.Id)
    .IsRequired()
    .ValueGeneratedOnAdd() ;
```
    
The wrong annotation is: 

`.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)`

and does not build
it should be probably:

`.Annotation("DatabaseGenerated", DatabaseGeneratedOption.Identity)`

### Further technical details
EF Core version: 2.0.0
Database Provider:Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@pila13 Can you provide more details about this? The "wrong annotation" seems correct to me at first look, and the annotation you are expecting is not something I would ever expect to see. In one way are things not working? When you say, "does not build" do you get an error? If so, what is that error?

**Comment by pila13** [comment]
I' m sorry - it was my misunderstanding + missing reference. I thought that `enum SqlServerValueGenerationStrategy`  had been removed in 2.0 which is obviously not true.  Please close the issue.
