### ISSUE TITLE
Running Add-Migration throws a nonsensical error

### ISSUE THREAD

**Issue by The-MAZZTer** [dotnet/efcore#9805]
Describe what is not working as expected.

When running Add-Migration, even with no changes to my DbContext, dotnet performs what seemed to be a native (unmanaged) crash (stack trace was all native code... possibly a stack corruption or null pointer jump or something, bottom of the stack was at 0x00000018) and I got the error below. No migration was created.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
add-migration : Exception calling "AddFromFile" with "1" argument(s): "'basePath' cannot be an empty string ("") or start with the null character.
Parameter name: basePath"
At line:1 char:1
+ add-migration -context TechAssistDatabase -name AddDeletedColumn
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException,Add-Migration
```

### Steps to reproduce
I simply run Add-Migration. At first I tried to tweak my new additions but even with the exact same DbContext it is not working.

### Further technical details
.NET Core version; Happened with project set to 1.0 and 1.1
EF Core version: 1.0.3
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 7 Enterprise Build 7601 Service Pack 1
IDE: Visual Studio 2017 (15.3.2)

Possibly related issue I found, same error message as mine but none of the resolutions work for me: https://github.com/aspnet/EntityFrameworkCore/issues/7905

One user suggest simply trying repeatedly. This eventually seemed to work for me, but the migration did not migrate but tried to create the full database structure. This caused migration attempts to fail as tables already existed. I eventually had to write the migration file myself by hand.

**Comment by bricelam** [comment]
What version of `Microsoft.EntityFrameworkCore.Tools` are you using?

**Comment by bricelam** [comment]
(This may have been fixed in version 1.0.1)

**Comment by The-MAZZTer** [comment]
It is indeed 1.0.0. 

VS wanted to update to 2.0.0 but I was able to bump the version manually in my csproj file. Thanks!

I may not be managing my packages correctly. VS does not seem to have the option to remain on a specific 1.0.X version while getting bug fix updates that was present in the .NET Core Preview SDKs. Or my project is not properly set up for it. I will have to look into it.

I will close and create a new ticket if I have further problems.

**Comment by rsandhumcr** [comment]
I had the same problem with .net core 1.1 .
I solved my problem by creating a console app in my solution.
Made a reference to the project containing my written db context in the console app.
Executed the 'Add-Migration Initial' with success. (You need to add the Tool library)
