### ISSUE TITLE
Assembly version reasoning (question)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9831]
Hi, what will be the AssemblyVersion of the 2.0.1 release.

If it is not 2.0.0, please explain why (as it breaks any scenarios where binding redirects are not possible)

**Comment by ajcvickers** [comment]
@ErikEJ We had the conversation for 1.x.x assemblies and the conclusion at the org level where the builds are done was that the assembly version should increase. At that time we decided to wait for issues that came up and then potentially change the decision later. It would be really great if you could describe concrete scenarios where this is causing issues--I think because we don't ship VS tools for EF Core we haven't seen problems in the same way as we did for EF6, so input from the community is really important here.

**Comment by ErikEJ** [comment]
@ajcvickers As you may know, I am now (almost) in the business of shipping VS tools for EF Core. 

I have 2 features currently: 

1: Get a DebugView string from a DbContext in a user project. Assembly versioning should not be a problem here (but DbContext activation is a major headache)

2: Reverse engineering - I include EF Core relational + 3 relational providers in order to use their designtime services. In this case, lack of binding redirects means that I must require all included provider to have dependency on the chosen EF Core assembly version, so a 2.0.1 release of for example the SQL CE provider (or any other 3rd party providers I decide to support) will be needed in order to take advantage of the scaffolding bug fixes in 2.0.1

Currently not a huge issue, but seems like a nonsensical decision non the less (to always increase the assembly version)

**Comment by ajcvickers** [comment]
@ErikEJ For #2, is there no way to load the 2.0.1 version even if the provider only depends on 2.0.0? I was under the impression that this would work with .NET Core.

**Comment by ajcvickers** [comment]
@ErikEJ Also, to play devil's advocate a bit (because it's what others will say), you say it's "a nonsensical decision...to always increase the assembly version." But releasing a 2.0.1 version of a package where the assembly version is 2.0.0 is also nonsensical. Correspondingly, having multiple versions of an assembly that are different but all report as 2.0.0 is also nonsensical. Which is why the argument to do something different has to be very strong. In fact, doing something different indicates that .NET assembly versioning is broken. While that is true for .NET Framework, it's not clear that it is also true in .NET Core.

**Comment by ErikEJ** [comment]
>> For #2, is there no way to load the 2.0.1 version even if the provider only depends on 2.0.0? I was under the impression that this would work with .NET Core. 

VS runs under .NET Framework. not .NET Core...  Have not tested the scenario under .NET Core.

>> Correspondingly, having multiple versions of an assembly that are different but all report as 2.0.0 is also nonsensical. Which is why the argument to do something different has to be very strong. 

I guess I have just been "blinded" by the behaviour in .NET Framework (and it was the only one anyone knew until recently)

**Comment by ajcvickers** [comment]
@ErikEJ I think what we need is a clear step-by-step scenario where the result is that tooling cannot work if the assembly version has been incremented. Then we can take that case to others and have them make a call whether it is acceptable or not. If the decision is that it is not acceptable, then we can consider what possible fixes can be made for that scenario. This may lead us to a path where assembly versions are not changed, but it could also lead to a different fix for the scenario in question.

We're going to discuss with @bricelam when he is available, and we may be able to come up with the scenario ourselves, but any help you can provide is also appreciated.

**Comment by ErikEJ** [comment]
@ajcvickers Let me give it a try, I assume that updating to 2.0.1 for SQL Server and SQLite providers will break the SQLCE provider if it stays at 2.0.0

**Comment by ErikEJ** [comment]
@ajcvickers Where is the Myget feed for 2.0.1 ??

**Comment by ErikEJ** [comment]
Repro steps (for a VS extension using a 4.6.1 library - currently using EF Core 2.0)

Projects:

A: Extension DLL: https://github.com/ErikEJ/SqlCeToolbox/tree/master/src/GUI/EFCorePowerTools 
B: Reverse Enigneer "library": https://github.com/ErikEJ/SqlCeToolbox/tree/master/src/GUI/ReverseEngineer20


1: Update packages in project B:

    Install-Package Microsoft.EntityFrameworkCore.Sqlite -Version 2.0.1-rtm-36 -Source https://dotnet.myget.org/F/aspnet-2-0-2-october2017-patch/api/v3/index.json 

     Install-Package Microsoft.EntityFrameworkCore.Design -Version 2.0.1-rtm-36 -Source https://dotnet.myget.org/F/aspnet-2-0-2-october2017-patch/api/v3/index.json 

    Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 2.0.1-rtm-36 -Source https://dotnet.myget.org/F/aspnet-2-0-2-october2017-patch/api/v3/index.json 

Notice that the following app.config is now added by NuGet to the project, but it has no effect, since the process is devenv.exe:

```
     <dependentAssembly>
        <assemblyIdentity name="Microsoft.EntityFrameworkCore" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.1.0" newVersion="2.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.EntityFrameworkCore.Relational" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.1.0" newVersion="2.0.1.0" />
      </dependentAssembly>

```

Error calling the revsers engineer code here using the SQL CE 2.0.0 provider:
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/ReverseEngineer/EFCoreReverseEngineer.cs#L36 
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at EFCoreReverseEngineer.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerCodeFirstHandler.ReverseEngineerCodeFirst(Project project) in C:\Code\SqlCeToolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerCodeFirstHandler.cs:line 115

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.EntityFrameworkCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : EntityFrameworkCore.SqlServerCompact40, Version=2.0.0.0, Culture=neutral, PublicKeyToken=9af395b34ac99006.
    
```

**Comment by ErikEJ** [comment]
Adding the two binding redirects above to devenv.exe.config fixes the error!

**Comment by ErikEJ** [comment]
Hackety hack: https://github.com/ErikEJ/SqlCeToolbox/pull/504/files

**Comment by ErikEJ** [comment]
Agree that hackety hack is not an ideal solution 👍

**Comment by ajcvickers** [comment]
@ErikEJ So this was discussed among the ASP.NET/EF team and the guidance for VS tooling going forward is to do everything that involves loading/running application code out-of-proc with Visual Studio. It is recognized that this can be painful, and certainly not everything works this way currently, but long term it will likely be more robust since it reduces the coupling with VS.

Thanks for digging into this since I think it was important that it was discussed, and we'll let you know if we hear of any change to this in the future. Closing for now.

**Comment by ErikEJ** [comment]
@ajcvickers So you are saying I should create a command line tool (reveng.exe) and launch this from VS (hidden) ?? - This will of course fix the assembly redirect problem.

**Comment by ajcvickers** [comment]
@ErikEJ I suspect it would be something like that, but I'm not sure if there are better ways of doing it out-of-proc.

**Comment by bricelam** [comment]
In EF6, we used an AppDomain in devenv.exe to honor the project's binding redirects.

**Comment by bricelam** [comment]
EFCore.Design is app-domain-friendly and was created to enable the same approach. Unfortunately, .NET Standard & Core required us to go out-of-process and we decided just to do that everywhere. But AppDomain's should still work just fine on .NET Framework.

**Comment by ErikEJ** [comment]
For other reasons I will release a 2.0.1 provider, so it is currently not an issue
