### ISSUE TITLE
Migrator with multiple schemas throws Database already exists.

### ISSUE THREAD

**Issue by Oleksandr-Tokmakov** [dotnet/efcore#9836]
Hi. I'm trying to use schema per tenant approach in sql database. I override multiple services... and it almost works. I can create tables with different schemas, migrations works.
But when I created set of tables for tenant A and I tried to create another set of tables under another schema for tenant B I got exception:
```
Exception message: SqlException: Database 'name' already exists. Choose a different database name.
Stack trace:
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(string methodName, bool async, int timeout, bool asyncWrite)
System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource<object> completion, string methodName, bool sendToPipe, int timeout, out bool usedCache, bool asyncWrite, bool inRetry)
System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable<MigrationCommand> migrationCommands, IRelationalConnection connection)
Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Create()
Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(string targetMigration)
Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```
I downloaded source from git hub and did small investigation. In Migrator class of Microsoft.EntityFrameworkCore.Migrations.Internal namespace there is a method:
public virtual void Migrate(string targetMigration = null)
and it has following lines:
```
_logger.MigrateUsingConnection(this, _connection);

            if (!_historyRepository.Exists())
            {
                if (!_databaseCreator.Exists())
                {
                    _databaseCreator.Create();
                }

                var command = _rawSqlCommandBuilder.Build(_historyRepository.GetCreateScript());

                command.ExecuteNonQuery(_connection);
            }

            var commandLists = GetMigrationCommandLists(_historyRepository.GetAppliedMigrations(), targetMigration);
            foreach (var commandList in commandLists)
            {
                _migrationCommandExecutor.ExecuteNonQuery(commandList(), _connection);
            }
```
I thought the problem in this place because it calls _databaseCreator.Create();. When I try to execute migrations for second tenant(new schema) it checks is history table exists and it returns false because for current schema there is no history tables. Next it checks for existence of database. And I'd like to think that it's source of the issue but looking at stack trace it's more likely that it's _migrationCommandExecutor.ExecuteNonQuery(commandList(), _connection);

GetMigrationCommandLists get's migrations from IMigrationsAssembly implementation. In my IMigrationsAssembly service there are only 3 migrations. It might be it tries to create db from model snapshot. I don't know. 
It looks that I'm very close to make it working but I need help here.

So why EF tries to create db when I change schema and try to apply migrations?

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: windows 10 pro
IDE: Visual Studio 2017

**Comment by Oleksandr-Tokmakov** [comment]
@bricelam I sent you email on brice@bricelam.net with my data access layer. It's tiny.

No, I don't perform migration in parallel. I was testing how multitenancy works so on first web request to tenant A EF created database and tables in format - <schemaname>.<tablename> on second request to tenant B it threw exception.

**Comment by bricelam** [comment]
Yes, email received. I just haven't gotten around to investigating it yet.

**Comment by bricelam** [comment]
I'm not able to repro this. Here is the code I tried with:
``` csharp
var connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Test";
for (int i = 0; i < 50; i++)
{
    new TenantDbContextFactory("t" + i, connectionString).CreateDbContext(args: null);
}
```
Tables for all 50 tenets were created without error.

**Comment by Oleksandr-Tokmakov** [comment]
Hi again! 
It works when connection string is the same for each tenant. In my case each tenant has own login to sqlserver and in connection string we have different User ID value. So when I use the same login for all tenants it works as expected(in such case connection strings are exactly the same, so it might be that next request uses the same connection from connection pool). 
But when I use different User ID in connection strings I still get Database already exists.

**Comment by bricelam** [comment]
Do you ensure that no two connections migrate at the same time?

**Comment by bricelam** [comment]
We suspect this might just be the behavior of SQL Server--to tell one user it doesn't exist immediately after being created by another user. There's not much we can do if this is the case. You may need to add additional locking and retry behavior to handle this in the app.
