### ISSUE TITLE
Migrations doesn't work with SQLite in-memory database

### ISSUE THREAD

**Issue by gabor182** [dotnet/efcore#9842]
I am using Code First to build my databse. When I run the initial 'dotnet ef database update' command, I get the following error:
```
PS D:\Projects\NetCoreDummy\NetCoreDummy.Database> dotnet ef database update
Database context created.
Applying migration '20170918143246_Initial'.
Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20170918143246_Initial', '2.0.0-rtm-26452');
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: __EFMigrationsHistory'....
```

When I call 'dotnet ef migrations script', the generated sql file contains the required command to create the __EFMigrationsHistory table.
Should not these two be identical? If the script contains the table creation then the generated Migration class should too.

My DbContextFactory looks like this:
```
public class DummyDbContextFactory : IDesignTimeDbContextFactory<DummyDbContext>
{
	private ConfigurationBuilder _configBuilder = new ConfigurationBuilder();
	private IConfigurationRoot _configRoot;
	private string _jsonConfigFile => AppContext.BaseDirectory + "appsettings.json";
	private string _connectionStringPath => "ConnectionStrings:DummySqlite";

	public string ConnectionString => "Data Source=Dummy.db; Mode=Memory; Cache=Default";

	public DummyDbContextFactory()
	{
		//_configBuilder.AddJsonFile(_jsonConfigFile);
		//_configRoot = _configBuilder.Build();

		//ConnectionString = _configRoot[_connectionStringPath];
	}

	public DummyDbContext CreateDbContext(string[] args)
	{
		var optionsBuilder = new DbContextOptionsBuilder<DummyDbContext>();
		if (args.Length == 0)
		{
			optionsBuilder.UseSqlite(ConnectionString);
		}
		else
		{
			optionsBuilder.UseSqlite(args[0]);
		}

		return new DummyDbContext(optionsBuilder.Options);
	}
}
```
The csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>
  
</Project>
```

Is there something that I am missing or is this a bug?

**Comment by ajcvickers** [comment]
@gabor182 Management of the history table is handled by Migrations when using the Migrations commands. When generating a script, there is no Migrations code running to handle this, so Migrations puts code into the script instead.

You should not be seeing that error from the Migrations tooling. Can you post a project or full code listing that exhibits this issue?

**Comment by gabor182** [comment]
@ajcvickers I've uploaded the full solution.

[netCoreConsoleAutoFac.zip](https://github.com/aspnet/EntityFrameworkCore/files/1313389/netCoreConsoleAutoFac.zip)

**Comment by ajcvickers** [comment]
@gabor182 This is happening because the SQLite database is in in-memory mode. The in-memory mode database only persists as long as a connection to it is open, so I'm not sure if this can be made to work correctly with Migrations or not--we will discuss. Everything worked correctly for me when I changed to using an on-disk database. You might also consider using `context.Database.EnsureCreated()` for testing with an in-memory database that has been created with your current Code First model.

**Comment by gabor182** [comment]
@ajcvickers Thank you! That would be nice if migrations could work with in-memory database as well.

**Comment by ErikEJ** [comment]
No, this does not make any sense - dont spend your time on it - just using EnsureCreated should be fine

**Comment by ajcvickers** [comment]
We discussed this in triage and decided we won't fix it. Even if the database update command completed without error, the database would still be immediately thrown away before any tests could use it. EnsureCreated can be used for in-memory testing, or an on-disk SQLite database can be used if Migrations are needed.

**Comment by mc0re** [comment]
>           EnsureCreated can be used for in-memory testing.

How? Code like 
```
using (var context=new MyContext())
{
    context.Database.EnsureCreated();
    DoMainStuff();
}
```
still throws that error
> no such table: __EFMigrationsHistory

Same goes for inserting `EnsureCreated` in the context constructor.

**Comment by roji** [comment]
@mc0re `EnsureCreated()` should definitely not be looking for `__EFMigrationsHistory` in any way. Can you double-check that there is no migration-related operation or code going on? If the issue persists, please open a new issue with a small console application that demonstrates this behavior.

**Comment by lhengen** [comment]
I too experienced this issue when I attempted to use an in memory sqllite database for integration tests.  cbcontext.Database.EnsureCreated is called, which executes all the model building code and EnsureCreated throws the exception "One or more errors occurred. (SQLite Error 1: 'no such table: __EFMigrationsHistory'.)".  Any resolution for this?

**Comment by ajcvickers** [comment]
@lhengen If `EnsureCreated` is throwing this exception, and it's not because `Migrate` is being called somewhere when the context is created, then please file a new issue including a small, runnable project/solution or complete code listing that demonstrates this behavior so that we can investigate.

**Comment by lhengen** [comment]
Thanks for the response.  I hit this issue first, but just found another [one ](https://github.com/aspnet/EntityFrameworkCore/issues/5086) that explains why.

**Comment by macias** [comment]
@ajcvickers 

> Even if the database update command completed without error, the database would still be immediately thrown away before any tests could use it.

Could you please add a comment to this statement why database would be thrown away? I was under the impression documentation promise "db lives as long as at least one connection does" holds true here as well.

**Comment by ajcvickers** [comment]
@macias This could be made to work by keeping an open connection through the migration process. However, the value in doing so is very low. If migrations are needed, then use a file-based database.

**Comment by macias** [comment]
@ajcvickers I just wanted to clarify this issue. I completely do not agree with the value of this feature -- for tests whenever I can I prefer using RAM-based approach than disk one.
