### ISSUE TITLE
Question: How can I improve DbContext activation here?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/efcore#9861]
@bricelam Any suggestions for improving this 
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs#L218 
to be able to activate more DbContext implementations without requiring EFCore.Design to be installed in the user project and resorting to pure reflection -
feel free to close right away if you consider this question completely of of scope) - would having DbContextActivator in EFcore be useful?

**Comment by bricelam** [comment]
I wonder if your tool could somehow depend on EFCore.Design and use DbContextActivator. It should remain forward-compatible with EFCore.dll

**Comment by ErikEJ** [comment]
Thanks, Brice. I gave up on Dbcontext activation, there was no way I could get VS to activate in release mode, only worked when debugging my extension. I now provide a Nuget package with an extension method to build a dgml file from a DbContext Model
