### ISSUE TITLE
Application break accessing dbcontext, Asp .net core web api 2.0 with entity framework core 2.0 database first approach

### ISSUE THREAD

**Issue by jvelezc** [dotnet/efcore#9868]
Multiple users are having the same issue with EF going to break mode both in unit test projects and web api.
https://stackoverflow.com/questions/45852923/application-break-accessing-dbcontext-asp-net-core-web-api-2-0-with-entity-fra

**Comment by ajcvickers** [comment]
Duplicate of #9478
