### ISSUE TITLE
How to configure Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator

### ISSUE THREAD

**Issue by andreyshade** [dotnet/efcore#9878]
How I can disable ValidateNonNullPrimaryKeys validator?

**Comment by ajcvickers** [comment]
@andreyshade These validation rules are there so that the rest of the runtime can assume certain invariants--in this case, that every entity type has a primary key defined. Many parts of the runtime will fail with non-obvious errors (likely null ref exceptions) when encountering entity types without primary keys.

Can you give some more details on what your goal is in disabling this?

**Comment by ajcvickers** [comment]
@andreyshade It sounds like the model for your custom DbContext has not been configured correctly. Can you post the code so we can take a look?

**Comment by andreyshade** [comment]
```
   public class MyDbContext : DbContext
    {
        public DbSet<ApplicationUser> ApplicationUser { get; set; }
        public DbSet<IdentityUserClaim<string>> IdentityUserClaim { get; set; }
        public DbSet<IdentityUserRole<string>> IdentityUserRole { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Filename = my.db");
        }
    }
```

**Comment by ajcvickers** [comment]
@andreyshade You'll need code in OnModelCreating to configure those entity types. Consider deriving from the Identity context instead and calling the base OnModelCreating, or at least look in that context for some idea of the configuration needed for those entity types.

**Comment by andreyshade** [comment]
@ajcvickers Where I can to view how to do this? Can I use EntityFrameworkCore library without my CustomDBContext?

**Comment by ajcvickers** [comment]
@andreyshade The only docs I can find right now are  the general docs for Identity: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?tabs=visual-studio%2Caspnetcore2x

I have filed an issue to create better docs for this case: https://github.com/aspnet/Identity/issues/1447
