### ISSUE TITLE
NoSQL providers (Cassandra)

### ISSUE THREAD

**Issue by bugproof** [dotnet/efcore#9880]
Are there any NoSQL providers for EF Core? I'm particularly interested in Cassandra. I would like to use Cassandra and ASP.NET Core for my project.

**Comment by ajcvickers** [comment]
@fmj02 We're starting investigation of a Cosmos DB provider targeting DocumentDB, but we haven't got anything concrete to show yet.

**Comment by ErikEJ** [comment]
There is a MongoDb provider

**Comment by kuncevic** [comment]
@ericstj are you talking about that https://github.com/crhairr/EntityFrameworkCore.MongoDb ?

**Comment by divega** [comment]
@kuncevic I think you mentioned the wrong Eric :smile:, but yes, that is the MongoDB provider we know about.

**Comment by kuncevic** [comment]
@divega ahh i c, thanks for following up.

**Comment by Christina005** [comment]
Is there any further news on this

**Comment by ajcvickers** [comment]
@Christina005 There is some initial code checked in to support CosmosDB document databases, but nothing released yet.

**Comment by Christina005** [comment]
@ajcvickers  I apologize, I actually meant for Cassandra, I did not follow the thread long enough to see the topic had changed. Do you know if there is a provider available for Cassandra?

**Comment by ajcvickers** [comment]
@Christina005 Not that I am aware of.

**Comment by Christina005** [comment]
@ajcvickers ok, thank you

**Comment by vhmoura** [comment]
Have you tried datastax https://github.com/datastax/csharp-driver ?
