### ISSUE TITLE
Child entities are not being created when it has two parents

### ISSUE THREAD

**Issue by jyothi530** [dotnet/efcore#9881]
I have a scenario where a child entity has two types of parent  entities. One type of parent already exists in the database. I am creating other type of parent entity. While creating I also want to add child entities. But that child entities will refer other parent as well. When that parent is loaded using EF then the child entities are not being created.
Please find the example data model that I am facing issue.
```C#
//Parent 1
public class Project
{
    public Guid Id {get; set;}     
   public string Type {get; set;}
   public List<ProjectProduct> ProjectProducts { get; set;}
   
   public void AddProjectProduct(Guid projectId)
   {
	if(ProjectProducts == null)
		ProjectProducts = new List<ProjectProducts>();
	
	ProjectProducts.Add(new ProjectProduct{ ProductId = productId; });
   }

}

//Parent 2
public class Product
{
    public Guid Id {get; set;}     
   public string Name {get; set;}
   public string Category {get; set;}
   public List<ProjectProduct> ProjectProducts { get; set;}
}

//Child
public class ProjectProduct
{
    public Guid Id {get; set;}
    public Guid ProjectId {get; set;}
    public Guid ProductId {get; set;}
    public Project Project {get; set;} 
    public Product Product {get; set;}
}
```
With the above data model when I am creating Project I have to create ProjectProducts whose products are of specific category. So I queried all products with specific category. When I am adding ProjectProducts by calling AddProjectProduct with the loaded Products it is not creating corresponding ProjectProducts.
But if the products are not loaded using DbContext and calling AddProjectProduct with the hardcoded ProductIds it is creating entries in the database.
It seems like when an entity has two parent entities and you are adding child using one parent entity and the the other is in the context it is not creating child entries.

**Comment by Tarig0** [comment]
Could you provide more of the parent 1 class? The code you have here is not syntactically correct

**Comment by jyothi530** [comment]
Actually Child class foreign key references are also Guid. I corrected them. Parent1(Project) will have a collection of Products. But Parent2(Product) should be unaware of Parent1(Project). So we introduced ProjectProduct table. While creating Parent1 there is a scenario where we have to get specific categories of Parent2 and add them as Childs to Parent1 which should happen in the same transaction. But it is not creating Child entities.
The relation between Parent1 and Child is one-many and Parent2 and Child is also one-many but should be readonly collection. For now it is not readonly. We are maintaining that collection on Parent2 is because when childs are loaded we need to load it's corresponding Product(Parent2) as well. But because EF does not support one way navigation (i.e. Many-To-One relation without defining one-to-many) we are maintaining the collection on Parent2 as well.
NHibernate supports one-way navigation.  

Below code explains the issue

```
var products = await Context.Products.Where(product => product.Category=''Xyz).ToListAsync();
var project = new Project
		{
			Id = Guid.NewGuid(),
			Type = "Survey"
		};
products.ForEach(product => project.AddProjectProduct(product.Id));
Context.Projects.Add(project);
```

Creating Project in the way above mentioned it is creating Project(Parent1) entity but not Childs (ProjectProduct)

```
//The below list of products are available in the database but loaded from a separate dbcontext
var products = new List<Product>
		{
			new Product
			{
				Id = "2476fda3-173a-4922-b6aa-e96699276a45"
				Name = "Shirts",
				Category = "Clothing"
			},
			new Product
			{
				Id = "89b16c3d-46f4-4936-be81-1130413ecf5e"
				Name = "Denims",
				Category = "Clothing"
			}
		};
var project = new Project
		{
			Id = Guid.NewGuid(),
			Type = "Survey"
		};
products.ForEach(product => project.AddProjectProduct(product.Id));
Context.Projects.Add(project);
```

Create project in this way it is creating Project along with the mentioned childs.

**Comment by ajcvickers** [comment]
@jyothi530 I put your code into a little test application and it seems to be working as expected. Can you look and see what needs to be changed in the test application for it to exhibit the behavior you are seeing?

Here's the code:
```C#
//Parent 1
public class Project
{
    public Guid Id { get; set; }
    public string Type { get; set; }
    public List<ProjectProduct> ProjectProducts { get; set; }

    public void AddProjectProduct(Guid productId)
    {
        if (ProjectProducts == null)
            ProjectProducts = new List<ProjectProduct>();

        ProjectProducts.Add(new ProjectProduct { ProductId = productId });
    }
}

//Parent 2
public class Product
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Category { get; set; }
    public List<ProjectProduct> ProjectProducts { get; set; }
}

//Child
public class ProjectProduct
{
    public Guid Id { get; set; }
    public Guid ProjectId { get; set; }
    public Guid ProductId { get; set; }
    public Project Project { get; set; }
    public Product Product { get; set; }
}

public class TestDbContext : DbContext
{
    public DbSet<Product> Products { get; set; }
    public DbSet<Project> Projects { get; set; }
    public DbSet<ProjectProduct> ProjectProduct { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseSqlServer(
                @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");
    }
}

public class Program
{
    public static void Main()
    {
        using (var context = new TestDbContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var products = new List<Product>
            {
                new Product
                {
                    Id = Guid.NewGuid(),
                    Name = "Shirts",
                    Category = "Clothing"
                },
                new Product
                {
                    Id = Guid.NewGuid(),
                    Name = "Denims",
                    Category = "Clothing"
                }
            };

            context.AddRange(products);
            context.SaveChanges();
        }

        using (var context = new TestDbContext())
        {
            var products = context.Products.Where(product => product.Category == "Clothing").ToList();
            var project = new Project
            {
                Id = Guid.NewGuid(),
                Type = "Survey"
            };
            products.ForEach(product => project.AddProjectProduct(product.Id));
            context.Projects.Add(project);
            context.SaveChanges();
        }

        using (var context = new TestDbContext())
        {
            var products = context.Products
                .Include(e => e.ProjectProducts)
                .ThenInclude(e => e.Project)
                .ToList();
        }
    }
}
```
Here's what the loaded graph looks like at the end:
![image](https://user-images.githubusercontent.com/1430078/30822163-b75f7192-a1dc-11e7-857f-8474edc33792.png)

**Comment by ajcvickers** [comment]
@jyothi530 Also, EF does support one way navigations. See the docs here: https://docs.microsoft.com/en-us/ef/core/modeling/relationships. In particular, the sections on "Single Navigation Property".

**Comment by jyothi530** [comment]
@ajcvickers Thank you. Actually there is a small change in the model that should be done to reproduce the issue. To not allow creating ProjectProducts through Product entity I have defined my Product entity in the following way during which time ProjectProduct entries are not being created if the Product entities are loaded in the same context. If I do project.AddProjectProduct(new Guid({Valid_Product_Guid})) then the ProjectProduct entries are getting created.
```
public class Product
    {
        private List<ProjectProduct> _projectProducts;

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public List<ProjectProduct> ProjectProducts
        {
            get { return _projectProducts ?? new List<ProjectProduct>(); }
            private set { _projectProducts = value; }
        }
    }
```

One way Navigation: Actually I was looking for just HasOne() without defining WithMany() to avoid the collection property on the other side. But I found out that it is not required to actually have a collection property from the doc you have provided. But we have to define HasOne() relation with a parameter less WithMany() to make one way navigation work in which case EF will consider a virtual collection. 

Thank you. The one way navigation thing will resolve the problem I was looking for (not to have a collection on the parent side).

But if you look at the creation ProjectProduct entries I think it is an issue. Because if the Products are loaded with a context it is not creating ProjectProduct entries but when you are adding ProjectProduct entries with valid Product Ids that are not loaded using context it is creating database entries which is inconsistent.
I will leave it to you to consider whether it is an issue or not.
Thank you

**Comment by ajcvickers** [comment]
@jyothi530 The problem is this line:
```C#
get { return _projectProducts ?? new List<ProjectProduct>(); }
```
This essentially means that EF thinks it is adding entities to the collection, but then later when it looks at the collection it sees it has become empty again. This is interpreted as entities being removed from the collection. If the collection navigation property is going to be present in the entity, then it must be well-behaved.

**Comment by jyothi530** [comment]
@ajcvickers  But why the inconsistency like when the Product entries are loaded using context to create ProjectProducts when Project is being created the entries are not being created. But when you have all the required Product information from the UI and create ProjectProducts without loading Products from context it is creating entries.

**Comment by ajcvickers** [comment]
@jyothi530 I'm sorry, but I don't understand what you mean. Can you write code that demonstrates what you mean?

**Comment by jyothi530** [comment]
@ajcvickers Please find the code with comments below that has the issue of inconsistency I was talking about. 

```
public class Program
    {
        public static void Main(string[] args)
        {
            Guid productId1 = Guid.NewGuid(),
                 productId2 = Guid.NewGuid(),
                 productId3 = Guid.NewGuid();

            using (var context = new TestDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var products = new List<Product>
            {
                new Product
                {
                    Id = productId1,
                    Name = "Shirts",
                    Category = "Clothing"
                },
                new Product
                {
                    Id = productId2,
                    Name = "Denims",
                    Category = "Clothing"
                },
                new Product
                {
                    Id = productId3,
                    Name = "Polos",
                    Category = "Clothing"
                }
            };

                context.AddRange(products);
                context.SaveChanges();
            }

            using (var context = new TestDbContext())
            {
                var products = context.Products.Where(product => new[] { productId1, productId2 }
                                .Contains(product.Id)).ToList();

                var project = new Project
                {
                    Id = Guid.NewGuid(),
                    Type = "Survey"
                };
               //The foreach loop is creating ProjectProducts with Products that are loaded using context.
                //This is not creating entries in ProjectProducts table
                products.ForEach(product => project.AddProjectProduct(product.Id));

                //This is creating an entry into ProjectProduct table.Here the Product 3 is not loaded using context
                project.AddProjectProduct(productId3);
              
  context.Projects.Add(project);
                context.SaveChanges();
            }

            using (var context = new TestDbContext())
            {
                var projects = context.Projects
                    .Include(e => e.ProjectProducts)
                    .ThenInclude(e => e.Product)
                    .ToList();
            }
        }
    }

    public class Product
    {
        private List<ProjectProduct> _projectProducts;

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public List<ProjectProduct> ProjectProducts
        {
            get { return _projectProducts ?? new List<ProjectProduct>(); }
            private set { _projectProducts = value; }
        }
    }

    public class Project
    {
        public Guid Id { get; set; }
        public string Type { get; set; }
        public List<ProjectProduct> ProjectProducts { get; set; }

        public void AddProjectProduct(Guid productId)
        {
            if (ProjectProducts == null)
                ProjectProducts = new List<ProjectProduct>();

            ProjectProducts.Add(new ProjectProduct
            {
                ProductId = productId
            });
        }
    }

    public class ProjectProduct
    {
        public Guid Id { get; set; }
        public Guid ProjectId { get; set; }
        public Guid ProductId { get; set; }
        public Project Project { get; set; }
        public Product Product { get; set; }
    }

    public class TestDbContext : DbContext
    {
        public DbSet<Product> Products { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectProduct> ProjectProduct { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer(
                    @"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;ConnectRetryCount=0");
        }
    }   
```

**Comment by ajcvickers** [comment]
@jyothi530 It's because the ProjectProducts navigation property is not implemented in a valid way. This code:
```C#
get { return _projectProducts ?? new List<ProjectProduct>(); }
```
results in a new collection being created every time the property is accessed. Changing the code to something more reasonable, like this:
```C#
get { return _projectProducts ?? (_projectProducts = new List<ProjectProduct>()); }
```
makes the code work like you expect.
