### ISSUE TITLE
Add-migration fail after upgrade to 2.0.0

### ISSUE THREAD

**Issue by oto313** [dotnet/efcore#9891]
When I upgraded to Entityframework core 2.0. It started to show me error, when I want to create migration (by command "add-migration").

The error is that startup project doesnt reference Microsoft.EntityFrameworkCore.Design package, but i installed version 2.0 of this package (Microsoft.EntityFrameworkCore.Designpackage) and the reference is in csproj.

When I tried to downgrade back to version 1.1.2. The command add-migration show another error ("The system cannot find the file specified").
The entityframework works appart from EntityFrameworkCore.Tools (the CRUD operation works)

Error message EF 2.0.0:
```
Your startup project 'Project' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```

Error message EF 1.1.2:
```
add-migration : Exception calling "Start" with "1" argument(s): "The system cannot find the file specified"
At line:1 char:1
+ add-migration add-price
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception,Add-Migration
 
```

### Steps to reproduce
Upgrade package from 1.1.2 to 2.0.0 Entityframework Core

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Npgsql
Operating system: Windows 10
IDE:  Visual Studio 2017

**Comment by ajcvickers** [comment]
@oto313 Can you post the contents of your csproj files and also any global.json file for your application?

**Comment by oto313** [comment]
There is Claims.csproj (renamed to Claims.txt), but i did not find global.json, I am using .NET Framework 4.6.1 not .NET Core, i think that the file is only in .NET Core project

[Claims.txt](https://github.com/aspnet/EntityFrameworkCore/files/1330997/Claims.txt)

**Comment by bricelam** [comment]
Does uninstalling the 1.1.3 version of Microsoft.EntityFrameworkCore.Relational.Design help?

**Comment by pgmolloy** [comment]
This is happening just using the tutorial I am unable to use EF migrations for 2.0 projects right now. Here's what I receive using the tutorial. My files are same as tutorial. Take a look at the second line being generated "rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]", where is this coming from.


PM> Update-Database -context 'BloggingContext'
rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
Update-Database : Exception calling "Substring" with "1" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At line:1 char:1
+ Update-Database -context 'BloggingContext'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Database], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException,Update-Database

**Comment by oto313** [comment]
Uninstalling and installing the package Microsoft.EntityFrameworkCore.Relational.Design does not help.

**Comment by ajcvickers** [comment]
@oto313 Our best guess here is that there is some incorrect/inconsistent versions of packages installed. Probably the best approach is to start over with a clean project making sure to use Package References in NuGet rather than packages.config--see image below. Make sure that only 2.0 packages are installed.

![image](https://user-images.githubusercontent.com/1430078/30932441-50f000e2-a37c-11e7-9676-e94727429c39.png)

If you want to try to fix up the current project, then:
* Make sure only 2.0 packages are installed
* Uninstall packages that are no longer needed--such as Microsoft.EntityFrameworkCore.Relational.Design

**Comment by oto313** [comment]
I found where is the problem, I was using Costura.Fody package (which merge all dependencies into one exe file), when uninstalled it is working
