### ISSUE TITLE
ServiceFabric

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/efcore#9895]
Please consider creating an in memory provider for ServiceFabric using Reliable Collections

**Comment by ajcvickers** [comment]
@grahamehorner This is something that is being investigated by the ServiceFabric team but there is nothing concrete to share at this time. We'll update this issue if/when we have more to share.

**Comment by grahamehorner** [comment]
@ajcvickers that's great; the use case I have is that we have some relatively small amounts of data that is currently held in a database; this is cached but we if there were an EF provider (InMemory) for ServiceFabric that this would save on having to create/manage a database outside of ServiceFabric and have the associated dependency on communication/network;  I'd be happy to help out with this if your able to point me in the direction of the right people/person?

**Comment by ajcvickers** [comment]
Closing old issue as this is no longer something we intend to implement.
