### ISSUE TITLE
EF Code First: Changing a column length

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#9897]
I am using the following approach to change the length of a column from 25 to 30 in a SQL Server table on production server. But this approach seem quite tedious for just making one small change. Is there a better way to do it? I'm using `ASP.NET Core 1.1.1` with `Code First` and `VS2017`

1. On Developer machine, change the corresponding Model as:
```
[Column(TypeName = "varchar(30)")]
public string ColumnName { get; set; }

```
2.  Run `PM> Add-Migration ...` and `PM> Update-Database ...` commands in `Package Manager` console of `VS2017`

3.  Re-load the data to the corresponding table with changed column length

4. Re-deploy the entire database to production.

5. Re-deploy the entire project to production.

**Comment by ajcvickers** [comment]
@saf-itpro It's not entirely clear what you mean by "Re-load the data to the corresponding table with changed column length". If you mean that you copy data from a production database into a local database and then recopy that database back to production, then that shouldn't be needed. Two options are:
* Apply Migrations commands directly to the produce database as part of deployment of an application upgrade
* Use the -script with the Migrations commands to generate a SQL script for the changes that can then be applied to the production database as part of deploying an application upgrade
