### ISSUE TITLE
Entity Framework core fails to generate correct SQL

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#9899]
Reported via VS:
 
For an asp.net core project, Im using EF to run a complex query that involves an outer join (one where members are joined with a "friends" relationship table to ignore blocked members). 

The EF expression generates correct SQL if I use a single Where clause, but if I add 2 where clauses, the EF compile fails. I get "m.ID could nbot be bound" exception. This is because the SQL doesn't seem to generate as a single query.

Note for triage: @ajcvickers has some additional code not posted here.

**Comment by ajcvickers** [comment]
@smitpatel I'll send you the code.

**Comment by smitpatel** [comment]
This works correctly with 2.0.1-rtm-125 package.

**Comment by ErikEJ** [comment]
@smitpatel

**Comment by smitpatel** [comment]
@ErikEJ - ?
