### ISSUE TITLE
DbContext inside of parallel tasks failed.

### ISSUE THREAD

**Issue by irowbin** [dotnet/efcore#9901]
Describe what is not working as expected.

I am trying to using DbContext inside of a parallel tasks.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'AppDbContext'.

at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Internal.IDbSetCache.GetOrAddSet(IDbSetSource source, Type type)
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
```

### Steps to reproduce

```c#
//  I've added my DbContext to the service collection like this
services.AddDbContextPool<AppDbContext>(o =>  {...});

//  injected in the controller like this
private readonly AppDbContext _context;

public UserController(AppDbContext  context){
   _context = context;
}

Task.Run( () => {

// var _context = new AppDbContext(...); 

foreach(var user in Users){

       email.Send(user.email);

      _context.log.add(...);
      _context.SaveChanges();
      // more operations using DbContext

    }

});
```

### Further technical details
EF Core version: 2.0.0
Database Provider: 2.0.0
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@irowbin Is the code really using `new` to create a new context instance inside each thread? If it is instead resolved from the D.I. container, then make sure thread creates a new scope before obtaining the context, otherwise the same context instance with be used by multiple threads.

**Comment by irowbin** [comment]
No i am not creating a new instance in each thread. I am accessing from the DI and i am keep seeing that exception. What do you mean?
> make sure thread creates a new scope before obtaining the context

Do i have to change from `services.AddDbContextPool<AppDbContext>()` to `services.AddScoped<AppDbContext>()` ? Thanks

**Comment by ajcvickers** [comment]
@irowbin DbContext is not thread-safe. You'll need to make sure that each thread has it's own instance of DbContext (or carefully add locking if you need to use the same instance.) Typically, DbContext is registered as scoped, so creating a new scope for each thread will ensure each thread gets a new instance.

**Comment by irowbin** [comment]
@ajcvickers So how can i configure that? If i have 100 iteration then i have to create new instance for each  thread? Does above code works with that if i change the DI to `services.AddScoped<AppDbContext>()`?

**Comment by irowbin** [comment]
@ajcvickers This is how i done the job. Please let me know whether this approach is good practice.

```c#


foreach(var user in Users){

    Task.Run( async() => {
      var builder = new DbContextOptionsBuilder<AppDbContext>();
          builder.UseSqlServer(_config["data:connectionString"]);

       var _context = new AppDbContext(builder.Options);

      await  email.SendAsync(user.email);

      await _context.log.addAsync(...);
      await _context.SaveChangesAsync();

      // more operations using DbContext
  });
}
```

**Comment by ajcvickers** [comment]
@irowbin The context should be disposed, but other than that it looks safe. Whether or not it makes sense to create multiple threads to do this is something I can't answer--it depends on your needs and environment.
