### ISSUE TITLE
Fix R#/VS settings so they don't conflict

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/efcore#9911]
In particular, the indentation settings should not conflict: see https://github.com/aspnet/EntityFrameworkCore/pull/9903#issuecomment-332504242

Also, consider that we have multiple solutions now. All solutions should use the same settings, even if this means duplicating the settings files.

**Comment by smitpatel** [comment]
We already have this https://github.com/aspnet/EntityFrameworkCore/blob/dev/EFCore.Runtime.sln.DotSettings

We may just need to copy the same code for other solutions so all the sln uses same dotsettings

**Comment by AndriySvyryd** [comment]
@smitpatel Those only work if you have R#

**Comment by smitpatel** [comment]
I couldn't find a way to configure VS. 😢 
VS does not differentiate between single statement or block after case so `{` goes with indent.

**Comment by smitpatel** [comment]
We could also move to editorconfig meanwhile
That would make it easy to share code style between VS & R#
https://www.jetbrains.com/help/resharper/2017.1/Using_EditorConfig.html

**Comment by ajcvickers** [comment]
Propose we punt this for 2.1 at this time.

**Comment by AndriySvyryd** [comment]
Assigning to @anpete to also consider Rider

**Comment by smitpatel** [comment]
Looking at the linked PR, there seem to be no conflicts.
There is already known conflict
> VS does not differentiate between single statement or block after case so { goes with indent.

There is no way to configure VS, and I believe, we have been remove the `{` braces for case labels, which could be done as we change code.

Apart from that there is no conflicts known. Closing this unless others know about conflicts or someone wants to change the R# settings to indent `{` after case label.

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd @anpete @bricelam @maumar So then, I'm going to do a complete R# code cleanup and it shouldn't cause any issues going forward. If anybody is against this, then speak now.

**Comment by smitpatel** [comment]
> it shouldn't cause any issues going forward

You would need to change R# to indent case blocks with {} or you remove {} from all case labels then there won't be any issues. (apart from VS crash while running code cleanup :trollface: )
