### ISSUE TITLE
Add Function

### ISSUE THREAD

**Issue by JakePorter05** [dotnet/efcore#9927]
Devs, 
Is there a way to add or register an sqlite function to the dbcontext.                 
```C#
entity.Property(e => e.PK_ContactLink)
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("newid()");
```
I am using this code for the migration. Which works great for sqlexpress. But of course doesn't have a newid() for sqlite. I have looked up designing a function for the sqlite, but I need a way to register the function to the context without doing it manually everytime I make a context instance. 
Any advice would be great thanks.

**Comment by Tasher05** [comment]
I decided to just edit it like this for now and this also doesn't work:

 entity.Property(e => e.PK_Contact)
                    .HasColumnType("uniqueidentifier")
                    .ForSqlServerHasDefaultValueSql("newid()")
                    .ForSqliteHasDefaultValueSql("Test");

it generates this: 
PK_Contact = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "newid()"),

no compiler specifics.

**Comment by Tasher05** [comment]
OK this
entity.Property(e => e.PK_Contact)
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("newid()");
generates this: 
PK_Contact = table.Column<Guid>(type: "uniqueidentifier", nullable: false, defaultValueSql: "newid()"),
And when ran on a sqlite db it puts (newid()) in the default value column. 
And the context.add()
              savechanges()
Will generate a new guid in the sqlite database. 
So conclusion: Thank you for the magic under the hood that apparently automatically uses the something to fill in the guid value
