### ISSUE TITLE
Select Navigation translation question

### ISSUE THREAD

**Issue by cqkisyouq** [dotnet/efcore#9931]
var ssd = _applicationService.Get(query => query).Select(x => new
            {
                x.Id,
                Clients = x.Clients.ToList()
            }).ToList();

The above query twice ,Translation is innerjoin

The following query number is application of a _applicationService,Translation is the select

             ssd = _applicationService.Get(query => query).Select(x => new
            {
                x.Id,
                Clients = x.Clients.Where(d=>d.CreatedOnUtc>DateTime.Now.AddYears(-1)).ToList()
            }).ToList();

Why do you do that?

**Comment by maumar** [comment]
tracked by https://github.com/aspnet/EntityFrameworkCore/issues/9282
