### ISSUE TITLE
How to add a new parent record along with its children records?

### ISSUE THREAD

**Issue by saf-itpro** [dotnet/efcore#9943]
In ASP.NET/EF `Core 1.1.1`, application, I'm trying to create a Parent record along with its children records. The FK relationship is 1-1. In Parent and children tables the PK Id's are Identity columns. Suppose we've have a Customer  (Parent) entity and an Address (Child) entity. Each customer has only one Address record. Whenever a Customer record is created, I would like EF to create its corresponding Address record. 

In the following code, I get the error `MyProjContext does not contain a definition for Parents` at the line `_context.Parents.Add(p);`.

```
....
....
// Create instance for parent class
var p = new Parent { Name = "some name", FY = SelectedYear, ... };

// Add entity instance to db context
_context.Parents.Add(p);

// Save changes, this action sets the generated id value to entity's property
_context.SaveChanges();

// Create instances for child entities
var c1 = new Child { ItemName = "Abc", ParentID = p.ParentID };
var c2 = new Child { ItemName = "Rst", ParentID = p.ParentID };

// Add child to db context
_context.Childs.Add(c1);
_context.Childs.Add(c2);

// Save changes
_context.SaveChanges();
```

**Comment by ajcvickers** [comment]
@saf-itpro In the code above, Parents would typically be a DbSet property on your DbContext class. If it's not there, it likely means the context and model are not setup appropriately. It might be a good idea to go through some of the getting started documentation here: https://docs.microsoft.com/en-us/ef/core/

**Comment by saf-itpro** [comment]
@ajcvickers Got it. Thank you.
