### ISSUE TITLE
Where is the "update-database -TargetMigration " feature fore EF CORE MIG???

### ISSUE THREAD

**Issue by livarcocc** [dotnet/efcore#9945]
_From @19317362 on October 3, 2017 2:55_

It works very good in EF6.  But why you give up the BEST feature in EFCORE?

_Copied from original issue: dotnet/cli#7749_

**Comment by bricelam** [comment]
It's just `-Migration` in EF Core. Use `Get-Help Update-Database` to see other available parameters.

**Comment by bricelam** [comment]
Unless you're using `dotnet ef database update` in which case, it's just the first argument. Use `dotnet ef database update --help` to see available options there.

**Comment by 19317362** [comment]
Thanks. Sorry for my mistake. 
This is a breaking changes for tool chain. I'll check for document.

Sorry.
