### ISSUE TITLE
Question: EF code first, DBA's are suspect...

### ISSUE THREAD

**Issue by boxofnotgoodery** [dotnet/efcore#9948]
Our development staff would like to start leveraging code first schema generation, in order to reduce our cycle time.

Our current DBA staff are suspicious that code first schema's are poorly performing.

Especially because we are relying on Guid's for entity identifiers.
(I'm suggesting we simply cluster on a int value, and leave our guids as PK/FK)

Is there any type of documentation or other material that could help ease some internal tension on this issue?  Our DBA's are rarely persuaded by anything other than 'official' statements.

**Comment by ajcvickers** [comment]
@boxofnotgoodery EF can use different kinds of keys, so using Code First/Migrations should not be something that forces use of one type of key or the other.

**Comment by boxofnotgoodery** [comment]
Their issue is more general about the "quality" of ef code first generated schema.

From experience I'm aware they might not be the most tuned table strucutres, but they generally work well enough.

Again, looking more for any type of "official" statement about the overall ability of code first to generate acceptable schema for non "toy" applications.

I doubt such a thing exists.. Maybe I should see if MS has a list of larger orgs that rely on code first..

It's not really a technology issue as it is a confidence issue.

**Comment by ajcvickers** [comment]
@boxofnotgoodery It doesn't have to be either Code First or DBA. The DBA can still have input into the schema and the code first mappings can be changed as necessary to keep the DBA happy. Another way of saying this is that Code First does not dictate that a schema has to be a certain way--it all depends on how the Code First mappings are configured. So it doesn't really make sense to have a statement that "Code First generates acceptable schemas". 

All that being said, to answer your question directly I'm not aware of any official statement on this, or a public list of larger orgs that are using Code First.
