### ISSUE TITLE
Migrations: Team environments can break rebuilds

### ISSUE THREAD

**Issue by bricelam** [dotnet/efcore#996]
Imagine the following scenario.
1. DevA scaffolds a migration adding ColumnX from Table1
2. DevB scaffolds a migration that rebuilds Table1
3. DevA commits
4. DevB pulls with no conflicts in the model snapshot and commits
5. DevC pulls and runs Apply-Migration

When Table1 is rebuilt, it will not contain ColumnX. This is because when DevB's migration was scaffolded, it did not know about ColumnX.

This will be true whether we rebuild by "binding" to the model or by scaffold an imperative table rebuild.

**Comment by ajcvickers** [comment]
Leaving on the backlog to consider what we can do with regards to squashing, rebasing, etc of migrations. See also #2167 and #2174.
