### ISSUE TITLE
[Question] dotnet ef commands to target a specific appsettings.[environment].json

### ISSUE THREAD

**Issue by pjmagee** [dotnet/efcore#9972]
Not sure what is the correct channel so I created a Stackoverflow question with some tags for ef core and .net core 2.0 but not sure if those were custom made so I am also linking my question here as I'm also seeing people ask questions and they are being answered and closed off with a closed-question tag. 

I'd appreciate any guidance **[on my question here](https://stackoverflow.com/questions/46583136/how-to-run-dotnet-ef-commands-to-target-a-specific-appsettings-environment-j)**.

Thanks!

**Comment by ajcvickers** [comment]
@pjmagee EF really plays no part in this. ASP.NET Core uses the environment variable, so if it is this that is causing an issue (i.e. you have to dynamically change the environment and this isn't easy), then you might want to file an issue on https://github.com/aspnet/Home

**Comment by pjmagee** [comment]
This isnt an issue about ASP.NET. Anyway, turns out this problem is more related to https://github.com/aspnet/EntityFrameworkCore/issues/8332
