### ISSUE TITLE
Feature request: Navigation property without related field.

### ISSUE THREAD

**Issue by hikalkan** [dotnet/efcore#998]
Assume that I have a Blog and User entities.

<pre lang="cs">public class User
{
    public int Id { get; set; }
    public int Name { get; set; }
}</pre>

<pre lang="cs">public class Blog
{
    public int Id { get; set; }
    public int Name { get; set; }
    
    [ForeignKey("CreatorId")]
    public User Creator { get; set; } //Navigation property
}</pre>

Notice that: Blog has no CreatorId. I think it's needless since I can get CreatorId using <code>blog.Creator.Id</code>. This should not cause lazy-loading since I'm using CreatorId which is a field of Blogs table. Surely, this ensures #997 (Load with proxy). 

Example code:

<pre lang="cs">var blog = dbContext.Blogs.Get(1); //Get blog with Id = 1
var creatorId = blog.Creator.Id; //Should not lazy load Creator
var creatorName = blog.Creator.Name; //Should lazy load Creator now!</pre>

Get method also can be useful to get an entity with a known Id. We could use Single(b => b.Id == 1) instead of Get. But I think Get will be more natural.

These features does exists in NHibernate. I think EF should also has these features.

**Comment by rowanmiller** [comment]
Closing as there has been no further discussion, feel free to reopen if you feel this isn't correct.

**Comment by jenseralmeida** [comment]
So, I think that will be nice to have this on Entity Framework. Sure we can do this with 'shadow state' but will be nice and a more natural approach if we can just not use and leard a foreign api junto to get a id.

```csharp
public class User
{
    public int Id { get; set; }
    public int Name { get; set; }
}
var blog = dbContext.Blogs.Get(1); //Get blog with Id = 1
var creatorId = blog.Creator.Id; //Should not lazy load Creator
var creatorName = blog.Creator.Name; //Should lazy load Creator now!
```
http://stackoverflow.com/questions/246766/nhibernate-activerecord-any-way-to-map-to-a-foreign-key-column-only
